unsigned char L5_Outcome_1500[1000][15]={	 //	 0	 1500
{ AC, AC, AC, SK, AC, LO, SH, PF, JA, AC, AC, AC, QN, JA, CR }, 	 //	 1	 1500
{ AC, AC, AC, WN, ST, LO, SH, AC, QN, AC, AC, AC, WN, QN, KN }, 	 //	 2	 1500
{ AC, AC, AC, TN, QN, LO, SH, AC, TN, SH, AC, AC, WN, TN, JA }, 	 //	 3	 1500
{ AC, SH, AC, LO, TN, LO, AC, PF, KN, TN, AC, AC, QN, KN, TN }, 	 //	 4	 1500
{ AC, AC, JA, KN, QN, LO, AC, ST, KN, QN, AC, LO, AC, KN, SH }, 	 //	 5	 1500
{ AC, AC, KN, KN, TN, LO, AC, SH, SK, AC, AC, LO, AC, QN, AC }, 	 //	 6	 1500
{ AC, AC, AC, PF, SH, LO, LO, AC, AC, JA, AC, KN, AC, AC, JA }, 	 //	 7	 1500
{ AC, AC, AC, TN, QN, LO, LO, AC, TN, PF, AC, KN, WN, TN, JA }, 	 //	 8	 1500
{ AC, KN, AC, AC, KN, LO, KN, AC, AC, AC, AC, KN, AC, LO, LO }, 	 //	 9	 1500
{ AC, ST, KN, KN, AC, LO, QN, SH, AC, LO, AC, QN, AC, PF, AC }, 	 //	 10	 1500
{ AC, QN, AC, TN, KN, LO, QN, AC, AC, AC, AC, SK, AC, AC, LO }, 	 //	 11	 1500
{ AC, SK, ST, WN, TN, LO, JA, AC, AC, AC, AC, JA, KN, KN, AC }, 	 //	 12	 1500
{ AC, SH, KN, TN, TN, LO, TN, SH, WN, ST, AC, TN, AC, AC, AC }, 	 //	 13	 1500
{ AC, TN, JA, SK, ST, LO, WN, ST, JA, AC, AC, AC, AC, JA, KN }, 	 //	 14	 1500
{ AC, TN, JA, KN, KN, LO, WN, TN, QN, KN, AC, AC, AC, ST, CR }, 	 //	 15	 1500
{ AC, TN, AC, KN, KN, LO, WN, AC, AC, KN, AC, AC, AC, PF, CR }, 	 //	 16	 1500
{ AC, WN, JA, KN, WN, LO, AC, ST, KN, TN, AC, KN, AC, SK, TN }, 	 //	 17	 1500
{ AC, WN, AC, ST, KN, LO, AC, PF, JA, KN, AC, KN, QN, TN, KN }, 	 //	 18	 1500
{ AC, WN, AC, KN, QN, LO, AC, AC, KN, SH, AC, KN, WN, KN, JA }, 	 //	 19	 1500
{ AC, WN, AC, KN, SH, LO, AC, AC, KN, JA, AC, KN, WN, KN, JA }, 	 //	 20	 1500
{ AC, WN, AC, QN, AC, LO, AC, KN, SK, AC, AC, KN, WN, JA, AC }, 	 //	 21	 1500
{ AC, AC, AC, TN, KN, LO, KN, AC, WN, KN, AC, QN, AC, AC, SK }, 	 //	 22	 1500
{ AC, AC, AC, KN, AC, LO, KN, AC, WN, AC, AC, QN, WN, QN, AC }, 	 //	 23	 1500
{ AC, AC, AC, PF, AC, LO, KN, WN, AC, AC, AC, QN, KN, AC, CR }, 	 //	 24	 1500
{ AC, KN, PF, QN, KN, LO, QN, QN, QN, QN, AC, ST, QN, SK, PF }, 	 //	 25	 1500
{ AC, QN, QN, QN, SK, LO, ST, QN, QN, QN, AC, JA, SK, QN, QN }, 	 //	 26	 1500
{ AC, JA, KN, SK, JA, LO, TN, SH, QN, TN, AC, AC, AC, KN, AC }, 	 //	 27	 1500
{ AC, JA, AC, KN, KN, LO, TN, AC, KN, AC, AC, AC, AC, KN, LO }, 	 //	 28	 1500
{ AC, JA, JA, PF, KN, LO, TN, TN, KN, KN, AC, AC, AC, KN, SK }, 	 //	 29	 1500
{ AC, TN, AC, SH, KN, LO, AC, KN, TN, KN, AC, AC, QN, TN, CR }, 	 //	 30	 1500
{ AC, TN, AC, QN, KN, LO, AC, AC, QN, AC, AC, AC, PF, QN, LO }, 	 //	 31	 1500
{ AC, TN, AC, JA, KN, LO, AC, KN, JA, KN, AC, AC, WN, JA, KN }, 	 //	 32	 1500
{ AC, AC, SH, TN, KN, LO, AC, AC, TN, SK, AC, PF, AC, TN, QN }, 	 //	 33	 1500
{ AC, AC, SH, QN, QN, LO, AC, AC, KN, PF, AC, PF, AC, AC, JA }, 	 //	 34	 1500
{ AC, AC, JA, JA, KN, LO, AC, TN, JA, KN, AC, PF, AC, JA, KN }, 	 //	 35	 1500
{ AC, AC, PF, KN, KN, LO, AC, QN, KN, KN, AC, PF, AC, SK, CR }, 	 //	 36	 1500
{ AC, AC, AC, JA, JA, LO, PF, AC, SH, TN, AC, KN, AC, TN, AC }, 	 //	 37	 1500
{ AC, KN, AC, AC, TN, LO, KN, WN, AC, AC, AC, SK, KN, PF, AC }, 	 //	 38	 1500
{ AC, KN, ST, WN, AC, LO, AC, AC, AC, LO, AC, SH, KN, KN, AC }, 	 //	 39	 1500
{ AC, KN, AC, KN, WN, LO, AC, KN, KN, TN, AC, SH, QN, WN, TN }, 	 //	 40	 1500
{ AC, KN, AC, KN, JA, LO, AC, AC, QN, JA, AC, SH, PF, ST, JA }, 	 //	 41	 1500
{ AC, KN, AC, JA, TN, LO, AC, PF, TN, ST, AC, SH, QN, AC, AC }, 	 //	 42	 1500
{ AC, KN, JA, TN, KN, LO, AC, TN, WN, KN, AC, SH, AC, AC, SK }, 	 //	 43	 1500
{ AC, KN, AC, AC, TN, LO, AC, AC, PF, TN, AC, SH, WN, KN, TN }, 	 //	 44	 1500
{ AC, KN, PF, KN, KN, LO, AC, QN, KN, QN, AC, SH, AC, WN, PF }, 	 //	 45	 1500
{ LO, AC, JA, WN, AC, AC, SH, TN, QN, AC, AC, AC, AC, QN, SK }, 	 //	 46	 1500
{ LO, AC, TN, SK, AC, AC, SH, AC, JA, KN, AC, AC, AC, JA, QN }, 	 //	 47	 1500
{ LO, SH, AC, JA, JA, AC, AC, KN, JA, WN, AC, AC, WN, JA, TN }, 	 //	 48	 1500
{ LO, AC, AC, QN, QN, AC, AC, WN, QN, PF, AC, AC, KN, QN, JA }, 	 //	 49	 1500
{ LO, AC, AC, JA, CR, AC, AC, KN, SH, KN, AC, LO, QN, TN, KN }, 	 //	 50	 1500
{ LO, AC, AC, ST, SH, AC, AC, WN, JA, JA, AC, LO, KN, TN, JA }, 	 //	 51	 1500
{ LO, AC, AC, SH, JA, AC, AC, KN, TN, JA, AC, LO, WN, TN, JA }, 	 //	 52	 1500
{ LO, AC, AC, AC, ST, AC, LO, AC, PF, AC, AC, KN, AC, KN, KN }, 	 //	 53	 1500
{ LO, AC, AC, KN, AC, AC, LO, AC, AC, AC, AC, KN, WN, PF, CR }, 	 //	 54	 1500
{ LO, KN, KN, JA, LO, AC, KN, SH, TN, AC, AC, KN, AC, AC, AC }, 	 //	 55	 1500
{ LO, QN, AC, AC, AC, AC, QN, AC, KN, LO, AC, SK, AC, QN, AC }, 	 //	 56	 1500
{ LO, QN, AC, AC, AC, AC, SK, AC, AC, KN, AC, JA, PF, PF, QN }, 	 //	 57	 1500
{ LO, WN, AC, ST, TN, AC, AC, KN, JA, ST, AC, KN, QN, TN, AC }, 	 //	 58	 1500
{ LO, ST, AC, AC, AC, AC, JA, AC, AC, SK, AC, TN, PF, LO, KN }, 	 //	 59	 1500
{ LO, JA, SH, KN, TN, AC, TN, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 60	 1500
{ LO, TN, JA, AC, KN, AC, AC, ST, LO, KN, AC, AC, AC, KN, KN }, 	 //	 61	 1500
{ LO, TN, ST, KN, AC, AC, AC, AC, SK, KN, AC, AC, KN, QN, QN }, 	 //	 62	 1500
{ LO, AC, JA, KN, TN, AC, AC, ST, KN, ST, AC, AC, AC, SK, AC }, 	 //	 63	 1500
{ LO, AC, JA, AC, AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, CR }, 	 //	 64	 1500
{ LO, AC, PF, TN, JA, AC, AC, QN, TN, TN, AC, AC, AC, WN, AC }, 	 //	 65	 1500
{ LO, AC, PF, QN, TN, AC, AC, QN, ST, TN, AC, AC, AC, JA, ST }, 	 //	 66	 1500
{ LO, AC, JA, AC, QN, AC, AC, ST, AC, QN, AC, PF, AC, LO, SH }, 	 //	 67	 1500
{ LO, AC, SH, SK, KN, AC, AC, AC, JA, KN, AC, PF, AC, JA, SK }, 	 //	 68	 1500
{ LO, KN, TN, QN, AC, AC, SK, AC, KN, LO, AC, QN, AC, AC, AC }, 	 //	 69	 1500
{ LO, KN, PF, AC, AC, AC, SK, QN, AC, LO, AC, QN, AC, LO, AC }, 	 //	 70	 1500
{ LO, QN, JA, KN, KN, AC, KN, TN, KN, KN, AC, AC, AC, WN, KN }, 	 //	 71	 1500
{ LO, QN, JA, KN, JA, AC, KN, TN, KN, JA, AC, AC, AC, SK, JA }, 	 //	 72	 1500
{ LO, QN, TN, KN, QN, AC, KN, AC, QN, PF, AC, AC, AC, ST, JA }, 	 //	 73	 1500
{ LO, QN, PF, LO, SK, AC, KN, QN, KN, KN, AC, AC, AC, KN, KN }, 	 //	 74	 1500
{ LO, KN, TN, KN, KN, AC, AC, AC, KN, KN, AC, SH, AC, WN, KN }, 	 //	 75	 1500
{ LO, KN, TN, TN, CR, AC, AC, AC, TN, QN, AC, SH, AC, WN, KN }, 	 //	 76	 1500
{ LO, KN, AC, TN, AC, AC, AC, WN, TN, AC, AC, SH, KN, WN, AC }, 	 //	 77	 1500
{ AC, AC, JA, TN, SK, AC, SH, ST, TN, KN, AC, AC, AC, TN, KN }, 	 //	 78	 1500
{ AC, AC, JA, SK, AC, AC, SH, ST, QN, KN, AC, AC, AC, KN, QN }, 	 //	 79	 1500
{ AC, AC, SH, WN, KN, AC, SH, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 80	 1500
{ AC, AC, SH, ST, QN, AC, SH, AC, JA, QN, AC, AC, AC, TN, QN }, 	 //	 81	 1500
{ AC, AC, JA, KN, KN, AC, SH, TN, QN, SK, AC, AC, AC, ST, QN }, 	 //	 82	 1500
{ AC, AC, AC, JA, AC, AC, SH, KN, SH, KN, AC, AC, WN, TN, QN }, 	 //	 83	 1500
{ AC, SH, AC, QN, KN, AC, AC, KN, QN, QN, AC, AC, WN, SK, PF }, 	 //	 84	 1500
{ AC, AC, KN, WN, SH, AC, AC, SH, QN, JA, AC, LO, AC, QN, JA }, 	 //	 85	 1500
{ AC, AC, KN, QN, JA, AC, AC, SH, QN, JA, AC, LO, AC, SK, JA }, 	 //	 86	 1500
{ AC, AC, PF, AC, TN, AC, AC, QN, PF, TN, AC, LO, AC, KN, TN }, 	 //	 87	 1500
{ AC, AC, AC, SK, JA, AC, LO, KN, JA, TN, AC, KN, WN, JA, AC }, 	 //	 88	 1500
{ AC, KN, AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, WN, AC, CR }, 	 //	 89	 1500
{ AC, KN, AC, KN, QN, AC, KN, WN, AC, KN, AC, ST, KN, PF, AC }, 	 //	 90	 1500
{ AC, KN, TN, PF, KN, AC, ST, AC, AC, AC, AC, QN, AC, AC, LO }, 	 //	 91	 1500
{ AC, KN, AC, AC, JA, AC, ST, AC, AC, TN, AC, QN, WN, PF, AC }, 	 //	 92	 1500
{ AC, ST, AC, AC, AC, AC, QN, KN, AC, AC, AC, QN, WN, AC, CR }, 	 //	 93	 1500
{ AC, TN, KN, KN, JA, AC, WN, SH, KN, TN, AC, AC, AC, KN, AC }, 	 //	 94	 1500
{ AC, TN, KN, KN, JA, AC, WN, SH, AC, JA, AC, AC, AC, PF, JA }, 	 //	 95	 1500
{ AC, TN, PF, JA, QN, AC, WN, QN, JA, KN, AC, AC, AC, SH, AC }, 	 //	 96	 1500
{ AC, TN, PF, SH, WN, AC, WN, QN, TN, TN, AC, AC, AC, TN, TN }, 	 //	 97	 1500
{ AC, WN, PF, TN, TN, AC, AC, QN, TN, ST, AC, KN, AC, TN, AC }, 	 //	 98	 1500
{ AC, AC, AC, KN, WN, AC, KN, PF, QN, TN, AC, QN, QN, ST, TN }, 	 //	 99	 1500
{ AC, ST, AC, AC, AC, AC, JA, AC, LO, LO, AC, TN, PF, KN, AC }, 	 //	 100	 1500
{ AC, JA, KN, WN, QN, AC, TN, SH, QN, QN, AC, AC, AC, QN, QN }, 	 //	 101	 1500
{ AC, JA, TN, KN, AC, AC, TN, AC, KN, KN, AC, AC, AC, WN, QN }, 	 //	 102	 1500
{ AC, JA, TN, WN, AC, AC, TN, AC, QN, AC, AC, AC, AC, QN, AC }, 	 //	 103	 1500
{ AC, JA, AC, QN, TN, AC, TN, AC, SK, TN, AC, AC, AC, JA, TN }, 	 //	 104	 1500
{ AC, TN, AC, JA, TN, AC, AC, KN, JA, TN, AC, AC, WN, SH, TN }, 	 //	 105	 1500
{ AC, TN, AC, QN, QN, AC, AC, KN, ST, QN, AC, AC, WN, JA, SH }, 	 //	 106	 1500
{ AC, AC, JA, AC, QN, AC, AC, TN, PF, QN, AC, PF, AC, KN, SH }, 	 //	 107	 1500
{ AC, AC, PF, JA, SK, AC, AC, QN, JA, KN, AC, PF, AC, JA, KN }, 	 //	 108	 1500
{ AC, AC, QN, AC, WN, AC, AC, AC, LO, TN, AC, PF, KN, KN, TN }, 	 //	 109	 1500
{ AC, AC, QN, TN, JA, AC, AC, AC, TN, TN, AC, PF, KN, WN, AC }, 	 //	 110	 1500
{ AC, AC, AC, QN, PF, AC, PF, KN, SK, JA, AC, KN, QN, JA, TN }, 	 //	 111	 1500
{ AC, AC, KN, KN, AC, AC, PF, SH, AC, SK, AC, KN, AC, PF, KN }, 	 //	 112	 1500
{ AC, AC, AC, ST, CR, AC, PF, AC, JA, KN, AC, KN, PF, TN, KN }, 	 //	 113	 1500
{ AC, AC, AC, QN, CR, AC, PF, AC, QN, QN, AC, KN, AC, QN, KN }, 	 //	 114	 1500
{ AC, AC, AC, SK, AC, AC, PF, AC, JA, KN, AC, KN, AC, JA, QN }, 	 //	 115	 1500
{ AC, AC, AC, KN, AC, AC, PF, AC, QN, KN, AC, KN, AC, ST, QN }, 	 //	 116	 1500
{ AC, AC, AC, SH, ST, AC, PF, KN, TN, AC, AC, KN, WN, TN, KN }, 	 //	 117	 1500
{ AC, PF, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN, LO, CR }, 	 //	 118	 1500
{ AC, SK, QN, KN, CR, AC, QN, QN, QN, QN, AC, KN, SK, ST, KN }, 	 //	 119	 1500
{ AC, QN, TN, KN, TN, AC, KN, AC, SK, ST, AC, AC, AC, QN, AC }, 	 //	 120	 1500
{ AC, QN, AC, WN, JA, AC, KN, AC, QN, TN, AC, AC, AC, QN, AC }, 	 //	 121	 1500
{ AC, KN, AC, TN, QN, AC, AC, KN, TN, QN, AC, SH, QN, WN, SH }, 	 //	 122	 1500
{ AC, KN, KN, AC, AC, AC, AC, SH, LO, LO, AC, SH, AC, KN, AC }, 	 //	 123	 1500
{ AC, KN, KN, JA, AC, AC, AC, SH, JA, AC, AC, SH, AC, JA, SK }, 	 //	 124	 1500
{ AC, AC, AC, TN, QN, AC, SH, AC, TN, KN, ST, AC, AC, WN, AC }, 	 //	 125	 1500
{ AC, AC, AC, TN, QN, AC, SH, PF, AC, QN, ST, AC, QN, AC, SH }, 	 //	 126	 1500
{ AC, AC, AC, KN, TN, AC, SH, PF, SK, ST, ST, AC, QN, QN, AC }, 	 //	 127	 1500
{ AC, AC, AC, KN, KN, AC, SH, KN, KN, AC, ST, AC, WN, KN, LO }, 	 //	 128	 1500
{ AC, SH, JA, KN, KN, AC, AC, TN, KN, QN, ST, AC, AC, WN, PF }, 	 //	 129	 1500
{ AC, SH, JA, SK, AC, AC, AC, TN, JA, AC, ST, AC, AC, JA, SK }, 	 //	 130	 1500
{ AC, AC, AC, QN, QN, AC, AC, WN, KN, PF, ST, AC, KN, AC, JA }, 	 //	 131	 1500
{ AC, AC, AC, KN, SK, AC, AC, WN, KN, KN, ST, LO, KN, SK, KN }, 	 //	 132	 1500
{ AC, AC, AC, WN, PF, AC, LO, AC, QN, JA, ST, KN, WN, QN, TN }, 	 //	 133	 1500
{ AC, AC, AC, JA, KN, AC, LO, KN, SH, KN, ST, KN, WN, TN, CR }, 	 //	 134	 1500
{ AC, LO, SH, JA, AC, AC, KN, AC, TN, AC, ST, KN, AC, AC, AC }, 	 //	 135	 1500
{ AC, ST, AC, TN, QN, AC, QN, AC, AC, KN, ST, QN, WN, AC, AC }, 	 //	 136	 1500
{ AC, QN, AC, AC, QN, AC, QN, KN, KN, KN, ST, QN, QN, QN, AC }, 	 //	 137	 1500
{ AC, SK, ST, AC, LO, AC, JA, AC, AC, AC, ST, JA, KN, AC, AC }, 	 //	 138	 1500
{ AC, JA, KN, TN, LO, AC, JA, SH, WN, AC, ST, JA, AC, AC, AC }, 	 //	 139	 1500
{ AC, WN, AC, TN, CR, AC, AC, AC, TN, QN, ST, KN, WN, TN, KN }, 	 //	 140	 1500
{ AC, AC, AC, QN, SH, AC, KN, AC, QN, JA, ST, QN, AC, SK, JA }, 	 //	 141	 1500
{ AC, AC, AC, SK, AC, AC, KN, AC, JA, LO, ST, QN, WN, JA, AC }, 	 //	 142	 1500
{ AC, AC, AC, WN, QN, AC, KN, WN, AC, PF, ST, QN, KN, KN, JA }, 	 //	 143	 1500
{ AC, KN, AC, AC, QN, AC, QN, WN, AC, KN, ST, ST, KN, LO, AC }, 	 //	 144	 1500
{ AC, JA, JA, AC, KN, AC, TN, ST, AC, KN, ST, AC, AC, AC, KN }, 	 //	 145	 1500
{ AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, ST, AC, PF, KN, SK }, 	 //	 146	 1500
{ AC, TN, AC, QN, PF, AC, AC, AC, QN, JA, ST, AC, PF, QN, TN }, 	 //	 147	 1500
{ AC, TN, AC, AC, ST, AC, AC, WN, AC, AC, ST, AC, KN, AC, KN }, 	 //	 148	 1500
{ AC, TN, QN, TN, QN, AC, AC, AC, TN, QN, ST, AC, KN, WN, SH }, 	 //	 149	 1500
{ AC, AC, AC, JA, TN, AC, AC, KN, TN, TN, ST, AC, QN, AC, TN }, 	 //	 150	 1500
{ AC, AC, AC, KN, AC, AC, AC, KN, KN, AC, ST, AC, QN, SK, AC }, 	 //	 151	 1500
{ AC, AC, AC, QN, ST, AC, AC, KN, KN, AC, ST, AC, QN, AC, KN }, 	 //	 152	 1500
{ AC, AC, QN, SH, WN, AC, AC, AC, TN, TN, ST, AC, KN, TN, TN }, 	 //	 153	 1500
{ AC, AC, QN, QN, SK, AC, AC, AC, KN, QN, ST, AC, KN, AC, QN }, 	 //	 154	 1500
{ AC, AC, AC, LO, PF, AC, AC, KN, KN, JA, ST, PF, QN, KN, TN }, 	 //	 155	 1500
{ AC, AC, AC, ST, PF, AC, AC, KN, JA, JA, ST, PF, QN, TN, TN }, 	 //	 156	 1500
{ AC, AC, KN, KN, AC, AC, AC, SH, SK, AC, ST, PF, AC, QN, AC }, 	 //	 157	 1500
{ AC, AC, AC, TN, QN, AC, PF, KN, TN, PF, ST, KN, QN, TN, JA }, 	 //	 158	 1500
{ AC, AC, AC, WN, AC, AC, PF, AC, QN, AC, ST, KN, AC, QN, AC }, 	 //	 159	 1500
{ AC, AC, AC, JA, TN, AC, PF, AC, TN, TN, ST, KN, PF, AC, TN }, 	 //	 160	 1500
{ AC, KN, AC, AC, QN, AC, KN, WN, AC, KN, ST, SK, KN, AC, AC }, 	 //	 161	 1500
{ AC, SK, JA, AC, LO, AC, QN, ST, AC, AC, ST, KN, AC, AC, AC }, 	 //	 162	 1500
{ AC, KN, ST, KN, JA, AC, AC, AC, KN, TN, ST, SH, KN, SK, AC }, 	 //	 163	 1500
{ AC, KN, QN, SH, QN, AC, AC, AC, TN, QN, ST, SH, KN, TN, QN }, 	 //	 164	 1500
{ AC, AC, JA, AC, SH, ST, SH, TN, PF, JA, KN, AC, AC, AC, JA }, 	 //	 165	 1500
{ AC, AC, JA, JA, KN, ST, SH, TN, TN, AC, KN, AC, AC, AC, LO }, 	 //	 166	 1500
{ AC, AC, AC, SK, AC, ST, SH, AC, JA, AC, KN, AC, AC, JA, AC }, 	 //	 167	 1500
{ AC, AC, AC, KN, KN, ST, SH, AC, QN, AC, KN, AC, WN, ST, LO }, 	 //	 168	 1500
{ AC, AC, AC, QN, CR, ST, SH, KN, QN, KN, KN, AC, WN, QN, KN }, 	 //	 169	 1500
{ AC, AC, AC, KN, JA, ST, SH, KN, QN, WN, KN, AC, WN, ST, TN }, 	 //	 170	 1500
{ AC, AC, AC, KN, TN, ST, AC, KN, KN, ST, KN, AC, QN, WN, AC }, 	 //	 171	 1500
{ AC, AC, JA, KN, AC, ST, AC, TN, KN, AC, KN, AC, AC, KN, SK }, 	 //	 172	 1500
{ AC, AC, AC, QN, TN, ST, AC, WN, SK, ST, KN, AC, KN, JA, AC }, 	 //	 173	 1500
{ AC, AC, JA, KN, CR, ST, AC, TN, KN, QN, KN, LO, AC, SK, KN }, 	 //	 174	 1500
{ AC, AC, AC, KN, TN, ST, AC, AC, KN, TN, KN, LO, WN, SK, ST }, 	 //	 175	 1500
{ AC, AC, PF, QN, PF, ST, AC, QN, SK, JA, KN, LO, AC, JA, TN }, 	 //	 176	 1500
{ AC, ST, JA, AC, AC, ST, QN, TN, AC, KN, KN, QN, AC, PF, QN }, 	 //	 177	 1500
{ AC, TN, SH, TN, ST, ST, TN, AC, AC, AC, KN, TN, AC, AC, KN }, 	 //	 178	 1500
{ AC, TN, PF, QN, QN, ST, WN, QN, KN, PF, KN, AC, AC, AC, JA }, 	 //	 179	 1500
{ AC, WN, JA, SH, QN, ST, AC, ST, TN, PF, KN, KN, AC, TN, JA }, 	 //	 180	 1500
{ AC, WN, AC, WN, QN, ST, AC, KN, AC, QN, KN, KN, QN, KN, QN }, 	 //	 181	 1500
{ AC, WN, TN, JA, AC, ST, AC, AC, TN, AC, KN, KN, AC, AC, CR }, 	 //	 182	 1500
{ AC, WN, AC, LO, KN, ST, AC, AC, KN, KN, KN, KN, AC, KN, KN }, 	 //	 183	 1500
{ AC, AC, AC, QN, QN, ST, KN, WN, ST, PF, KN, QN, KN, JA, JA }, 	 //	 184	 1500
{ AC, KN, PF, WN, KN, ST, QN, QN, QN, QN, KN, ST, QN, QN, PF }, 	 //	 185	 1500
{ AC, KN, JA, AC, AC, ST, QN, TN, AC, LO, KN, ST, AC, PF, AC }, 	 //	 186	 1500
{ AC, KN, AC, KN, AC, ST, QN, AC, AC, SK, KN, ST, AC, PF, KN }, 	 //	 187	 1500
{ AC, TN, JA, JA, AC, ST, AC, ST, SH, LO, KN, AC, AC, TN, AC }, 	 //	 188	 1500
{ AC, TN, SH, QN, TN, ST, AC, AC, QN, TN, KN, AC, AC, QN, ST }, 	 //	 189	 1500
{ AC, TN, AC, KN, JA, ST, AC, AC, WN, WN, KN, AC, AC, QN, TN }, 	 //	 190	 1500
{ AC, TN, TN, KN, KN, ST, AC, AC, KN, SK, KN, AC, AC, SK, QN }, 	 //	 191	 1500
{ AC, AC, AC, TN, ST, ST, AC, KN, WN, AC, KN, AC, WN, AC, KN }, 	 //	 192	 1500
{ AC, AC, SH, KN, KN, ST, AC, AC, SK, AC, KN, PF, AC, QN, LO }, 	 //	 193	 1500
{ AC, AC, AC, ST, KN, ST, AC, PF, JA, AC, KN, PF, QN, TN, LO }, 	 //	 194	 1500
{ AC, AC, QN, WN, QN, ST, PF, PF, QN, QN, KN, KN, KN, QN, QN }, 	 //	 195	 1500
{ AC, AC, AC, JA, TN, ST, PF, AC, JA, TN, KN, KN, AC, SH, ST }, 	 //	 196	 1500
{ AC, KN, AC, AC, AC, ST, SK, AC, KN, KN, KN, QN, AC, QN, QN }, 	 //	 197	 1500
{ AC, QN, PF, AC, ST, ST, KN, QN, PF, AC, KN, AC, AC, AC, KN }, 	 //	 198	 1500
{ AC, KN, JA, AC, KN, ST, AC, ST, KN, KN, KN, SH, AC, QN, KN }, 	 //	 199	 1500
{ AC, KN, JA, SK, TN, ST, AC, ST, QN, TN, KN, SH, AC, KN, TN }, 	 //	 200	 1500
{ AC, KN, SH, QN, AC, ST, AC, AC, ST, AC, KN, SH, AC, JA, CR }, 	 //	 201	 1500
{ ST, AC, AC, AC, QN, KN, AC, WN, LO, KN, KN, LO, KN, KN, AC }, 	 //	 202	 1500
{ ST, AC, PF, QN, JA, KN, AC, QN, KN, TN, KN, LO, AC, AC, AC }, 	 //	 203	 1500
{ ST, AC, AC, AC, LO, KN, LO, KN, LO, AC, KN, KN, WN, KN, AC }, 	 //	 204	 1500
{ ST, KN, ST, PF, KN, KN, KN, AC, AC, AC, KN, ST, KN, AC, LO }, 	 //	 205	 1500
{ ST, KN, JA, JA, TN, KN, ST, ST, TN, AC, KN, QN, AC, AC, AC }, 	 //	 206	 1500
{ ST, TN, JA, JA, LO, KN, TN, ST, TN, AC, KN, TN, AC, AC, AC }, 	 //	 207	 1500
{ ST, TN, JA, TN, SK, KN, WN, ST, AC, KN, KN, AC, AC, AC, KN }, 	 //	 208	 1500
{ ST, TN, SH, AC, JA, KN, WN, AC, PF, JA, KN, AC, AC, AC, JA }, 	 //	 209	 1500
{ ST, WN, KN, AC, KN, KN, AC, SH, AC, KN, KN, KN, AC, PF, KN }, 	 //	 210	 1500
{ ST, ST, AC, AC, QN, KN, JA, KN, AC, KN, KN, TN, WN, AC, AC }, 	 //	 211	 1500
{ ST, TN, ST, AC, KN, KN, AC, AC, AC, KN, KN, AC, KN, AC, KN }, 	 //	 212	 1500
{ ST, TN, AC, WN, KN, KN, AC, PF, AC, KN, KN, AC, QN, KN, KN }, 	 //	 213	 1500
{ ST, AC, QN, TN, JA, KN, AC, AC, AC, TN, KN, PF, KN, AC, AC }, 	 //	 214	 1500
{ ST, AC, SH, JA, AC, KN, PF, AC, TN, LO, KN, KN, AC, AC, AC }, 	 //	 215	 1500
{ ST, KN, KN, AC, LO, KN, SK, SH, PF, AC, KN, QN, AC, AC, AC }, 	 //	 216	 1500
{ ST, SK, AC, PF, TN, KN, QN, PF, AC, AC, KN, KN, QN, AC, AC }, 	 //	 217	 1500
{ ST, SK, JA, TN, AC, KN, QN, TN, AC, KN, KN, KN, AC, AC, QN }, 	 //	 218	 1500
{ KN, AC, AC, AC, TN, KN, SH, AC, AC, TN, KN, AC, WN, AC, TN }, 	 //	 219	 1500
{ KN, AC, AC, AC, CR, KN, AC, KN, PF, QN, KN, LO, QN, KN, KN }, 	 //	 220	 1500
{ KN, JA, KN, TN, QN, KN, JA, SH, AC, KN, KN, JA, AC, AC, AC }, 	 //	 221	 1500
{ KN, TN, JA, AC, AC, KN, TN, TN, AC, AC, KN, TN, AC, AC, CR }, 	 //	 222	 1500
{ KN, TN, TN, PF, AC, KN, TN, AC, AC, SK, KN, TN, AC, AC, KN }, 	 //	 223	 1500
{ KN, KN, AC, JA, AC, KN, QN, AC, TN, AC, KN, ST, AC, AC, AC }, 	 //	 224	 1500
{ KN, QN, QN, QN, QN, KN, ST, QN, QN, KN, KN, JA, QN, SK, AC }, 	 //	 225	 1500
{ KN, TN, JA, TN, KN, KN, AC, TN, WN, AC, KN, AC, AC, AC, LO }, 	 //	 226	 1500
{ KN, AC, PF, WN, JA, KN, AC, QN, AC, JA, KN, PF, AC, KN, WN }, 	 //	 227	 1500
{ KN, AC, AC, AC, QN, KN, PF, KN, AC, PF, KN, KN, QN, AC, JA }, 	 //	 228	 1500
{ KN, PF, SH, TN, JA, KN, KN, AC, WN, TN, KN, KN, AC, AC, AC }, 	 //	 229	 1500
{ KN, PF, AC, AC, AC, KN, KN, AC, KN, AC, KN, KN, AC, QN, AC }, 	 //	 230	 1500
{ KN, KN, AC, QN, AC, KN, KN, KN, QN, KN, KN, KN, QN, QN, QN }, 	 //	 231	 1500
{ KN, QN, JA, AC, KN, KN, KN, TN, AC, QN, KN, AC, AC, AC, PF }, 	 //	 232	 1500
{ KN, QN, PF, WN, AC, KN, KN, QN, AC, SK, KN, AC, AC, KN, KN }, 	 //	 233	 1500
{ KN, KN, AC, AC, WN, KN, AC, WN, AC, TN, KN, SH, KN, AC, TN }, 	 //	 234	 1500
{ KN, AC, AC, AC, CR, KN, AC, KN, PF, KN, SK, LO, QN, KN, KN }, 	 //	 235	 1500
{ KN, LO, AC, AC, AC, KN, KN, PF, LO, AC, SK, KN, QN, KN, AC }, 	 //	 236	 1500
{ KN, JA, JA, KN, AC, KN, JA, TN, AC, SK, SK, JA, AC, PF, KN }, 	 //	 237	 1500
{ KN, SH, AC, AC, AC, KN, TN, AC, PF, SK, SK, TN, WN, AC, KN }, 	 //	 238	 1500
{ KN, TN, JA, TN, SK, KN, WN, ST, AC, QN, SK, AC, AC, AC, QN }, 	 //	 239	 1500
{ KN, WN, PF, AC, KN, KN, AC, QN, AC, KN, SK, KN, AC, LO, KN }, 	 //	 240	 1500
{ KN, AC, JA, AC, LO, KN, KN, ST, AC, AC, SK, QN, AC, AC, AC }, 	 //	 241	 1500
{ KN, KN, PF, AC, QN, KN, QN, QN, AC, KN, SK, ST, AC, AC, AC }, 	 //	 242	 1500
{ KN, JA, KN, AC, SH, KN, TN, SH, PF, JA, SK, AC, AC, AC, JA }, 	 //	 243	 1500
{ KN, TN, AC, AC, KN, KN, AC, KN, AC, AC, SK, AC, WN, AC, LO }, 	 //	 244	 1500
{ KN, AC, JA, KN, KN, KN, AC, ST, AC, QN, SK, AC, AC, PF, PF }, 	 //	 245	 1500
{ KN, AC, AC, AC, QN, KN, AC, AC, PF, QN, SK, AC, AC, KN, SH }, 	 //	 246	 1500
{ KN, KN, KN, QN, QN, KN, KN, QN, QN, QN, SK, KN, PF, SK, QN }, 	 //	 247	 1500
{ KN, SK, AC, AC, QN, KN, QN, KN, AC, KN, SK, KN, QN, PF, AC }, 	 //	 248	 1500
{ KN, SK, AC, AC, JA, KN, QN, AC, AC, TN, SK, KN, AC, LO, AC }, 	 //	 249	 1500
{ KN, KN, AC, AC, TN, KN, AC, PF, AC, TN, SK, SH, QN, AC, ST }, 	 //	 250	 1500
{ KN, SH, AC, JA, TN, SK, AC, AC, TN, TN, QN, AC, AC, AC, TN }, 	 //	 251	 1500
{ KN, SH, AC, WN, QN, SK, AC, WN, AC, QN, QN, AC, KN, KN, QN }, 	 //	 252	 1500
{ KN, SH, QN, WN, TN, SK, AC, AC, AC, TN, QN, AC, KN, KN, TN }, 	 //	 253	 1500
{ KN, AC, AC, AC, LO, SK, AC, AC, KN, AC, QN, AC, AC, QN, AC }, 	 //	 254	 1500
{ KN, AC, QN, AC, AC, SK, AC, AC, AC, KN, QN, AC, KN, LO, QN }, 	 //	 255	 1500
{ KN, AC, JA, PF, QN, SK, AC, TN, AC, QN, QN, LO, AC, AC, QN }, 	 //	 256	 1500
{ KN, LO, JA, QN, AC, SK, KN, ST, KN, AC, QN, KN, AC, AC, AC }, 	 //	 257	 1500
{ KN, LO, AC, JA, JA, SK, KN, AC, TN, TN, QN, KN, AC, AC, AC }, 	 //	 258	 1500
{ KN, LO, AC, AC, TN, SK, KN, KN, AC, ST, QN, KN, WN, PF, AC }, 	 //	 259	 1500
{ KN, JA, JA, PF, AC, SK, JA, TN, AC, KN, QN, JA, AC, AC, QN }, 	 //	 260	 1500
{ KN, JA, JA, AC, QN, SK, SH, TN, AC, KN, QN, TN, AC, AC, AC }, 	 //	 261	 1500
{ KN, TN, ST, AC, AC, SK, TN, AC, AC, AC, QN, WN, KN, AC, AC }, 	 //	 262	 1500
{ KN, TN, JA, PF, SK, SK, WN, ST, AC, QN, QN, AC, AC, AC, QN }, 	 //	 263	 1500
{ KN, WN, AC, TN, JA, SK, AC, PF, AC, JA, QN, KN, QN, AC, JA }, 	 //	 264	 1500
{ KN, AC, PF, TN, TN, SK, KN, QN, AC, ST, QN, QN, AC, AC, AC }, 	 //	 265	 1500
{ KN, JA, PF, PF, JA, SK, TN, QN, AC, JA, QN, AC, AC, AC, JA }, 	 //	 266	 1500
{ KN, TN, TN, AC, WN, SK, AC, AC, PF, TN, QN, AC, AC, AC, TN }, 	 //	 267	 1500
{ KN, AC, TN, QN, KN, SK, AC, AC, KN, KN, QN, AC, AC, AC, SK }, 	 //	 268	 1500
{ KN, PF, SH, AC, TN, SK, KN, AC, AC, AC, QN, KN, AC, PF, AC }, 	 //	 269	 1500
{ KN, SK, TN, AC, AC, SK, QN, AC, PF, AC, QN, KN, AC, AC, AC }, 	 //	 270	 1500
{ KN, KN, QN, WN, KN, SK, AC, AC, AC, SK, QN, SH, KN, KN, QN }, 	 //	 271	 1500
{ SK, AC, TN, PF, CR, QN, SH, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 272	 1500
{ SK, SH, AC, AC, KN, QN, AC, KN, AC, QN, QN, AC, WN, AC, PF }, 	 //	 273	 1500
{ SK, AC, AC, KN, TN, QN, AC, KN, AC, TN, QN, LO, QN, PF, TN }, 	 //	 274	 1500
{ SK, AC, AC, AC, KN, QN, LO, AC, PF, KN, QN, KN, AC, AC, CR }, 	 //	 275	 1500
{ SK, QN, QN, KN, KN, QN, QN, PF, KN, SK, QN, QN, KN, SK, QN }, 	 //	 276	 1500
{ SK, QN, SH, AC, AC, QN, QN, AC, AC, LO, QN, SK, AC, LO, AC }, 	 //	 277	 1500
{ SK, AC, AC, AC, KN, QN, KN, AC, KN, KN, QN, QN, AC, QN, KN }, 	 //	 278	 1500
{ SK, JA, AC, WN, TN, QN, TN, KN, AC, ST, QN, AC, WN, KN, AC }, 	 //	 279	 1500
{ SK, TN, AC, AC, KN, QN, AC, KN, AC, QN, QN, AC, QN, LO, PF }, 	 //	 280	 1500
{ SK, AC, JA, AC, KN, QN, AC, TN, AC, KN, QN, PF, AC, AC, KN }, 	 //	 281	 1500
{ SK, AC, ST, AC, LO, QN, PF, AC, AC, AC, QN, KN, KN, PF, AC }, 	 //	 282	 1500
{ SK, QN, JA, TN, SK, QN, KN, ST, AC, QN, QN, AC, AC, AC, QN }, 	 //	 283	 1500
{ SK, QN, AC, AC, AC, QN, KN, AC, AC, SK, QN, AC, PF, AC, KN }, 	 //	 284	 1500
{ SK, QN, JA, JA, SK, QN, KN, TN, TN, QN, QN, AC, AC, AC, QN }, 	 //	 285	 1500
{ QN, AC, KN, JA, CR, QN, SH, SH, TN, QN, QN, AC, AC, AC, KN }, 	 //	 286	 1500
{ QN, AC, SH, TN, TN, QN, AC, AC, WN, TN, QN, AC, AC, AC, ST }, 	 //	 287	 1500
{ QN, AC, AC, WN, TN, QN, AC, WN, AC, TN, QN, LO, KN, KN, ST }, 	 //	 288	 1500
{ QN, LO, JA, WN, AC, QN, KN, ST, AC, SK, QN, KN, AC, KN, KN }, 	 //	 289	 1500
{ QN, KN, PF, TN, TN, QN, KN, QN, WN, ST, QN, KN, AC, AC, AC }, 	 //	 290	 1500
{ QN, KN, JA, AC, AC, QN, KN, TN, AC, AC, QN, ST, AC, AC, CR }, 	 //	 291	 1500
{ QN, ST, AC, KN, TN, QN, QN, PF, SK, TN, QN, QN, QN, QN, TN }, 	 //	 292	 1500
{ QN, ST, PF, AC, KN, QN, QN, QN, AC, KN, QN, QN, QN, AC, KN }, 	 //	 293	 1500
{ QN, QN, AC, AC, AC, QN, QN, WN, KN, AC, QN, QN, KN, QN, CR }, 	 //	 294	 1500
{ QN, QN, JA, KN, AC, QN, QN, TN, AC, AC, QN, SK, AC, PF, AC }, 	 //	 295	 1500
{ QN, JA, SH, AC, AC, QN, JA, AC, AC, KN, QN, JA, AC, PF, QN }, 	 //	 296	 1500
{ QN, JA, AC, AC, LO, QN, JA, PF, AC, AC, QN, SH, QN, PF, AC }, 	 //	 297	 1500
{ QN, SH, AC, PF, ST, QN, TN, AC, AC, AC, QN, TN, AC, AC, KN }, 	 //	 298	 1500
{ QN, TN, ST, WN, TN, QN, TN, AC, AC, AC, QN, TN, KN, KN, AC }, 	 //	 299	 1500
{ QN, TN, PF, TN, QN, QN, TN, QN, WN, KN, QN, WN, AC, AC, AC }, 	 //	 300	 1500
{ QN, JA, JA, AC, QN, QN, TN, TN, PF, PF, QN, AC, AC, AC, JA }, 	 //	 301	 1500
{ QN, JA, TN, QN, KN, QN, TN, AC, KN, AC, QN, AC, AC, AC, LO }, 	 //	 302	 1500
{ QN, JA, AC, AC, AC, QN, TN, KN, PF, AC, QN, AC, WN, AC, AC }, 	 //	 303	 1500
{ QN, AC, KN, AC, ST, QN, AC, SH, AC, AC, QN, PF, AC, AC, KN }, 	 //	 304	 1500
{ QN, AC, AC, AC, SK, QN, PF, AC, LO, QN, QN, KN, WN, KN, QN }, 	 //	 305	 1500
{ QN, AC, PF, QN, JA, QN, PF, QN, KN, TN, QN, KN, AC, AC, AC }, 	 //	 306	 1500
{ QN, PF, KN, TN, AC, QN, KN, SH, AC, KN, QN, KN, AC, AC, QN }, 	 //	 307	 1500
{ QN, PF, JA, PF, JA, QN, KN, TN, AC, TN, QN, KN, AC, AC, AC }, 	 //	 308	 1500
{ QN, PF, AC, TN, LO, QN, KN, AC, WN, AC, QN, KN, AC, AC, AC }, 	 //	 309	 1500
{ QN, KN, AC, KN, QN, QN, KN, AC, AC, KN, QN, SK, WN, PF, AC }, 	 //	 310	 1500
{ QN, KN, AC, PF, JA, QN, SK, WN, AC, TN, QN, QN, KN, AC, AC }, 	 //	 311	 1500
{ QN, KN, JA, JA, TN, QN, AC, ST, TN, AC, QN, SH, AC, AC, AC }, 	 //	 312	 1500
{ QN, SH, AC, AC, TN, QN, AC, AC, PF, TN, SH, AC, AC, AC, ST }, 	 //	 313	 1500
{ QN, AC, TN, JA, QN, QN, AC, AC, TN, PF, SH, AC, AC, AC, JA }, 	 //	 314	 1500
{ QN, AC, AC, AC, LO, QN, AC, KN, LO, AC, SH, LO, QN, KN, AC }, 	 //	 315	 1500
{ QN, AC, AC, AC, ST, QN, AC, AC, LO, AC, SH, LO, AC, KN, KN }, 	 //	 316	 1500
{ QN, AC, PF, AC, QN, QN, LO, QN, AC, KN, SH, KN, AC, AC, AC }, 	 //	 317	 1500
{ QN, LO, AC, WN, LO, QN, KN, PF, AC, AC, SH, KN, QN, KN, AC }, 	 //	 318	 1500
{ QN, QN, QN, AC, JA, QN, QN, QN, AC, WN, SH, SK, QN, PF, TN }, 	 //	 319	 1500
{ QN, QN, QN, QN, KN, QN, SK, SK, SK, KN, SH, JA, JA, JA, SK }, 	 //	 320	 1500
{ QN, SK, JA, TN, TN, QN, JA, TN, AC, AC, SH, JA, AC, AC, AC }, 	 //	 321	 1500
{ QN, JA, PF, AC, AC, QN, SH, QN, PF, LO, SH, TN, AC, AC, AC }, 	 //	 322	 1500
{ QN, TN, SH, JA, AC, QN, TN, AC, TN, AC, SH, TN, AC, AC, AC }, 	 //	 323	 1500
{ QN, TN, AC, WN, AC, QN, TN, KN, AC, LO, SH, WN, WN, KN, AC }, 	 //	 324	 1500
{ QN, TN, AC, AC, AC, QN, WN, KN, LO, KN, SH, AC, WN, KN, QN }, 	 //	 325	 1500
{ QN, WN, JA, AC, KN, QN, AC, TN, AC, KN, SH, KN, AC, AC, SK }, 	 //	 326	 1500
{ QN, AC, AC, AC, JA, QN, KN, AC, AC, WN, SH, QN, AC, LO, TN }, 	 //	 327	 1500
{ QN, KN, TN, QN, JA, QN, QN, AC, KN, TN, SH, ST, AC, AC, AC }, 	 //	 328	 1500
{ QN, TN, AC, KN, JA, QN, AC, KN, AC, JA, SH, AC, QN, PF, JA }, 	 //	 329	 1500
{ QN, KN, AC, AC, TN, QN, KN, AC, AC, ST, SH, KN, AC, PF, AC }, 	 //	 330	 1500
{ QN, SK, JA, AC, AC, QN, QN, ST, AC, AC, SH, KN, AC, PF, CR }, 	 //	 331	 1500
{ QN, KN, AC, AC, KN, QN, AC, KN, AC, QN, SH, SH, QN, AC, PF }, 	 //	 332	 1500
{ QN, SH, AC, QN, SK, SH, AC, AC, KN, KN, JA, AC, AC, AC, KN }, 	 //	 333	 1500
{ QN, AC, JA, AC, KN, SH, AC, TN, PF, SK, JA, AC, AC, AC, QN }, 	 //	 334	 1500
{ QN, AC, AC, AC, QN, SH, AC, AC, PF, PF, JA, AC, WN, AC, JA }, 	 //	 335	 1500
{ QN, AC, AC, AC, JA, SH, LO, WN, KN, JA, JA, KN, KN, QN, WN }, 	 //	 336	 1500
{ QN, QN, AC, AC, QN, SH, QN, AC, AC, KN, JA, SK, WN, LO, AC }, 	 //	 337	 1500
{ QN, QN, QN, QN, QN, SH, SK, AC, ST, PF, JA, JA, KN, JA, JA }, 	 //	 338	 1500
{ QN, JA, QN, TN, LO, SH, JA, AC, AC, AC, JA, JA, KN, AC, AC }, 	 //	 339	 1500
{ QN, JA, ST, KN, TN, SH, SH, AC, AC, AC, JA, TN, KN, PF, AC }, 	 //	 340	 1500
{ QN, SH, TN, WN, TN, SH, TN, AC, AC, AC, JA, TN, AC, KN, AC }, 	 //	 341	 1500
{ QN, SH, AC, PF, JA, SH, TN, AC, AC, TN, JA, TN, WN, AC, AC }, 	 //	 342	 1500
{ QN, TN, AC, AC, ST, SH, WN, AC, AC, AC, JA, AC, WN, AC, KN }, 	 //	 343	 1500
{ QN, WN, AC, AC, QN, SH, AC, PF, AC, PF, JA, KN, QN, LO, JA }, 	 //	 344	 1500
{ QN, WN, AC, AC, AC, SH, AC, AC, PF, AC, JA, KN, WN, KN, AC }, 	 //	 345	 1500
{ QN, QN, AC, QN, LO, SH, ST, AC, KN, AC, JA, JA, AC, AC, AC }, 	 //	 346	 1500
{ QN, ST, AC, AC, AC, SH, JA, KN, PF, AC, JA, TN, WN, AC, CR }, 	 //	 347	 1500
{ QN, JA, PF, AC, KN, SH, TN, QN, PF, KN, JA, AC, AC, AC, SK }, 	 //	 348	 1500
{ QN, AC, KN, AC, AC, SH, PF, SH, AC, AC, JA, KN, AC, PF, AC }, 	 //	 349	 1500
{ QN, AC, TN, QN, AC, SH, PF, AC, KN, LO, JA, KN, AC, AC, AC }, 	 //	 350	 1500
{ QN, AC, AC, AC, JA, SH, PF, WN, KN, JA, JA, KN, KN, QN, WN }, 	 //	 351	 1500
{ QN, KN, KN, PF, AC, SH, SK, SH, AC, SK, JA, QN, AC, AC, KN }, 	 //	 352	 1500
{ QN, KN, AC, WN, KN, SH, SK, AC, AC, AC, JA, QN, AC, KN, LO }, 	 //	 353	 1500
{ QN, QN, AC, AC, AC, SH, KN, AC, PF, KN, JA, AC, PF, AC, QN }, 	 //	 354	 1500
{ QN, KN, AC, WN, KN, SH, AC, PF, AC, KN, JA, SH, QN, KN, SK }, 	 //	 355	 1500
{ SH, AC, JA, QN, AC, JA, SH, TN, KN, AC, JA, AC, AC, AC, CR }, 	 //	 356	 1500
{ SH, AC, PF, PF, TN, JA, SH, QN, AC, TN, JA, AC, AC, AC, ST }, 	 //	 357	 1500
{ SH, SH, ST, AC, JA, JA, AC, AC, AC, WN, JA, AC, KN, PF, TN }, 	 //	 358	 1500
{ SH, AC, KN, TN, KN, JA, AC, SH, WN, KN, JA, AC, AC, AC, KN }, 	 //	 359	 1500
{ SH, AC, SH, QN, TN, JA, AC, AC, KN, TN, JA, AC, AC, AC, ST }, 	 //	 360	 1500
{ SH, AC, AC, AC, SH, JA, AC, PF, PF, JA, JA, AC, QN, AC, JA }, 	 //	 361	 1500
{ SH, KN, JA, KN, AC, JA, KN, ST, AC, AC, JA, ST, AC, PF, AC }, 	 //	 362	 1500
{ SH, KN, KN, KN, QN, JA, KN, QN, QN, QN, JA, ST, PF, ST, SH }, 	 //	 363	 1500
{ SH, KN, TN, QN, AC, JA, ST, AC, KN, AC, JA, QN, AC, AC, AC }, 	 //	 364	 1500
{ SH, QN, AC, AC, AC, JA, QN, AC, AC, KN, JA, SK, WN, PF, QN }, 	 //	 365	 1500
{ SH, TN, TN, AC, TN, JA, TN, AC, AC, ST, JA, TN, AC, AC, AC }, 	 //	 366	 1500
{ SH, WN, QN, AC, QN, JA, AC, AC, AC, QN, JA, KN, KN, AC, QN }, 	 //	 367	 1500
{ SH, AC, AC, AC, QN, JA, KN, KN, AC, QN, JA, QN, WN, AC, QN }, 	 //	 368	 1500
{ SH, KN, JA, TN, TN, JA, QN, ST, AC, ST, JA, ST, AC, AC, AC }, 	 //	 369	 1500
{ SH, ST, AC, AC, AC, JA, JA, AC, KN, SK, JA, TN, AC, QN, KN }, 	 //	 370	 1500
{ SH, JA, AC, AC, AC, JA, TN, KN, AC, AC, JA, AC, QN, LO, CR }, 	 //	 371	 1500
{ SH, TN, ST, AC, JA, JA, AC, AC, AC, JA, JA, AC, KN, PF, JA }, 	 //	 372	 1500
{ SH, AC, KN, WN, LO, JA, AC, SH, AC, AC, JA, AC, AC, KN, AC }, 	 //	 373	 1500
{ SH, AC, PF, JA, CR, JA, AC, QN, TN, QN, JA, AC, AC, AC, KN }, 	 //	 374	 1500
{ SH, KN, AC, AC, AC, JA, KN, WN, AC, AC, JA, SK, KN, AC, CR }, 	 //	 375	 1500
{ SH, KN, AC, TN, QN, JA, KN, KN, AC, KN, JA, SK, WN, AC, AC }, 	 //	 376	 1500
{ SH, KN, AC, TN, AC, JA, SK, AC, WN, AC, JA, QN, AC, AC, AC }, 	 //	 377	 1500
{ SH, QN, PF, AC, AC, JA, KN, QN, AC, AC, JA, AC, AC, LO, CR }, 	 //	 378	 1500
{ JA, SH, QN, AC, QN, JA, AC, AC, AC, SH, JA, AC, KN, AC, JA }, 	 //	 379	 1500
{ JA, AC, AC, AC, TN, JA, AC, KN, LO, ST, JA, LO, QN, KN, AC }, 	 //	 380	 1500
{ JA, KN, QN, KN, LO, JA, KN, AC, AC, AC, JA, ST, KN, PF, AC }, 	 //	 381	 1500
{ JA, QN, QN, SK, TN, JA, QN, QN, QN, ST, JA, QN, QN, KN, AC }, 	 //	 382	 1500
{ JA, JA, PF, AC, JA, JA, JA, QN, AC, TN, JA, JA, AC, AC, AC }, 	 //	 383	 1500
{ JA, JA, AC, AC, AC, JA, JA, PF, AC, KN, JA, SH, QN, PF, QN }, 	 //	 384	 1500
{ JA, WN, PF, AC, QN, JA, AC, QN, AC, KN, JA, KN, AC, PF, AC }, 	 //	 385	 1500
{ JA, AC, SH, AC, JA, JA, KN, AC, PF, TN, JA, QN, AC, AC, AC }, 	 //	 386	 1500
{ JA, AC, AC, AC, SH, JA, KN, AC, PF, JA, JA, QN, PF, AC, JA }, 	 //	 387	 1500
{ JA, KN, SH, AC, ST, JA, QN, AC, AC, AC, JA, ST, AC, AC, KN }, 	 //	 388	 1500
{ JA, JA, ST, WN, AC, JA, TN, AC, AC, AC, JA, AC, KN, KN, CR }, 	 //	 389	 1500
{ JA, AC, AC, AC, KN, JA, AC, AC, PF, SK, JA, AC, WN, KN, QN }, 	 //	 390	 1500
{ JA, AC, JA, PF, QN, JA, AC, TN, AC, SH, JA, PF, AC, AC, JA }, 	 //	 391	 1500
{ JA, AC, QN, PF, KN, JA, AC, AC, AC, KN, JA, PF, KN, AC, CR }, 	 //	 392	 1500
{ JA, KN, KN, TN, QN, JA, KN, SH, WN, KN, JA, SK, AC, AC, AC }, 	 //	 393	 1500
{ JA, SK, AC, AC, AC, JA, QN, AC, PF, AC, JA, KN, PF, AC, AC }, 	 //	 394	 1500
{ JA, SK, AC, JA, JA, JA, QN, AC, TN, TN, JA, KN, AC, AC, AC }, 	 //	 395	 1500
{ JA, SK, AC, TN, AC, JA, QN, AC, AC, SK, JA, KN, AC, AC, KN }, 	 //	 396	 1500
{ JA, AC, JA, TN, JA, JA, SH, ST, AC, JA, WN, AC, AC, AC, WN }, 	 //	 397	 1500
{ JA, AC, AC, AC, PF, JA, SH, WN, KN, JA, WN, AC, KN, QN, TN }, 	 //	 398	 1500
{ JA, QN, AC, TN, TN, JA, SK, AC, WN, AC, WN, JA, AC, AC, AC }, 	 //	 399	 1500
{ JA, SK, AC, PF, LO, JA, JA, PF, AC, AC, WN, JA, QN, AC, AC }, 	 //	 400	 1500
{ JA, SK, AC, AC, AC, JA, JA, PF, LO, AC, WN, JA, QN, KN, AC }, 	 //	 401	 1500
{ JA, JA, AC, AC, AC, JA, JA, AC, LO, SK, WN, JA, AC, KN, KN }, 	 //	 402	 1500
{ JA, TN, AC, AC, TN, JA, WN, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 403	 1500
{ JA, KN, AC, AC, JA, JA, QN, KN, AC, TN, WN, ST, WN, AC, AC }, 	 //	 404	 1500
{ JA, ST, PF, WN, AC, JA, JA, QN, AC, KN, WN, TN, AC, KN, QN }, 	 //	 405	 1500
{ JA, TN, JA, JA, SK, JA, AC, ST, TN, QN, WN, AC, AC, AC, QN }, 	 //	 406	 1500
{ JA, TN, ST, PF, WN, JA, AC, AC, AC, TN, WN, AC, KN, AC, TN }, 	 //	 407	 1500
{ JA, AC, JA, WN, KN, JA, AC, ST, AC, SK, WN, AC, AC, KN, QN }, 	 //	 408	 1500
{ JA, AC, ST, WN, JA, JA, AC, AC, AC, JA, WN, AC, KN, KN, WN }, 	 //	 409	 1500
{ JA, AC, AC, TN, TN, JA, AC, AC, WN, TN, WN, AC, AC, AC, ST }, 	 //	 410	 1500
{ JA, AC, AC, AC, TN, JA, AC, AC, LO, ST, WN, PF, AC, KN, AC }, 	 //	 411	 1500
{ JA, AC, AC, AC, CR, JA, PF, AC, AC, QN, WN, KN, WN, PF, KN }, 	 //	 412	 1500
{ JA, KN, AC, AC, AC, JA, SK, AC, PF, AC, WN, QN, AC, KN, SK }, 	 //	 413	 1500
{ JA, SK, AC, PF, AC, JA, QN, PF, AC, LO, WN, KN, QN, AC, AC }, 	 //	 414	 1500
{ JA, SK, AC, WN, QN, JA, QN, PF, QN, QN, WN, KN, QN, QN, QN }, 	 //	 415	 1500
{ JA, QN, TN, AC, TN, JA, KN, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 416	 1500
{ JA, KN, AC, TN, KN, JA, AC, PF, AC, QN, WN, SH, QN, AC, PF }, 	 //	 417	 1500
{ JA, KN, AC, TN, ST, JA, AC, WN, AC, AC, WN, SH, KN, AC, KN }, 	 //	 418	 1500
{ JA, KN, PF, AC, KN, JA, AC, QN, AC, KN, WN, SH, AC, AC, KN }, 	 //	 419	 1500
{ JA, AC, QN, AC, ST, WN, SH, AC, AC, AC, TN, AC, KN, AC, KN }, 	 //	 420	 1500
{ JA, SH, ST, TN, KN, WN, AC, AC, AC, KN, TN, AC, KN, AC, KN }, 	 //	 421	 1500
{ JA, AC, AC, AC, KN, WN, LO, KN, AC, KN, TN, KN, QN, AC, CR }, 	 //	 422	 1500
{ JA, QN, ST, WN, AC, WN, QN, AC, AC, AC, TN, QN, KN, KN, CR }, 	 //	 423	 1500
{ JA, JA, AC, AC, AC, WN, JA, PF, LO, AC, TN, SH, QN, KN, CR }, 	 //	 424	 1500
{ JA, TN, AC, TN, JA, WN, WN, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 425	 1500
{ JA, TN, AC, KN, TN, WN, WN, AC, AC, ST, TN, AC, WN, PF, AC }, 	 //	 426	 1500
{ JA, ST, AC, AC, AC, WN, JA, WN, AC, SK, TN, TN, KN, LO, KN }, 	 //	 427	 1500
{ JA, AC, JA, TN, JA, WN, AC, ST, WN, JA, TN, AC, AC, AC, JA }, 	 //	 428	 1500
{ JA, AC, AC, AC, KN, WN, AC, KN, PF, KN, TN, AC, QN, AC, KN }, 	 //	 429	 1500
{ JA, AC, AC, TN, TN, WN, AC, KN, AC, TN, TN, AC, QN, AC, TN }, 	 //	 430	 1500
{ JA, AC, AC, AC, SK, WN, AC, KN, PF, KN, TN, AC, WN, KN, KN }, 	 //	 431	 1500
{ JA, AC, JA, KN, AC, WN, PF, TN, AC, KN, TN, KN, AC, PF, QN }, 	 //	 432	 1500
{ JA, KN, PF, QN, QN, WN, SK, QN, KN, KN, TN, QN, AC, AC, AC }, 	 //	 433	 1500
{ JA, QN, AC, QN, QN, WN, KN, AC, KN, QN, TN, AC, AC, AC, QN }, 	 //	 434	 1500
{ JA, QN, TN, TN, ST, WN, KN, AC, WN, AC, TN, AC, AC, AC, KN }, 	 //	 435	 1500
{ WN, SH, SH, JA, QN, TN, AC, AC, TN, SH, TN, AC, AC, AC, JA }, 	 //	 436	 1500
{ WN, SH, AC, AC, JA, TN, AC, AC, PF, WN, TN, AC, AC, AC, TN }, 	 //	 437	 1500
{ WN, AC, AC, TN, AC, TN, LO, KN, AC, LO, TN, KN, QN, AC, AC }, 	 //	 438	 1500
{ WN, LO, AC, AC, TN, TN, KN, WN, AC, ST, TN, KN, KN, PF, AC }, 	 //	 439	 1500
{ WN, QN, AC, TN, AC, TN, QN, WN, AC, LO, TN, QN, KN, AC, AC }, 	 //	 440	 1500
{ WN, QN, AC, PF, AC, TN, QN, AC, AC, LO, TN, SK, WN, AC, AC }, 	 //	 441	 1500
{ WN, QN, AC, AC, AC, TN, SK, KN, AC, AC, TN, JA, QN, AC, CR }, 	 //	 442	 1500
{ WN, QN, JA, AC, JA, TN, SK, TN, PF, TN, TN, JA, AC, AC, AC }, 	 //	 443	 1500
{ WN, SK, AC, AC, AC, TN, JA, AC, AC, SK, TN, JA, PF, LO, KN }, 	 //	 444	 1500
{ WN, JA, AC, AC, AC, TN, JA, PF, PF, AC, TN, JA, QN, AC, SK }, 	 //	 445	 1500
{ WN, JA, AC, AC, AC, TN, SH, KN, AC, KN, TN, TN, WN, AC, QN }, 	 //	 446	 1500
{ WN, QN, ST, WN, LO, TN, ST, AC, AC, AC, TN, JA, KN, KN, AC }, 	 //	 447	 1500
{ WN, JA, AC, AC, TN, TN, TN, AC, AC, ST, TN, AC, AC, LO, AC }, 	 //	 448	 1500
{ WN, AC, ST, AC, WN, TN, AC, AC, AC, TN, TN, AC, KN, AC, TN }, 	 //	 449	 1500
{ WN, AC, AC, AC, TN, TN, AC, KN, PF, AC, TN, AC, WN, KN, AC }, 	 //	 450	 1500
{ WN, AC, PF, AC, SK, TN, AC, QN, AC, QN, TN, PF, AC, AC, QN }, 	 //	 451	 1500
{ WN, AC, AC, AC, JA, TN, PF, KN, AC, WN, TN, KN, QN, LO, TN }, 	 //	 452	 1500
{ WN, PF, SH, QN, TN, TN, KN, AC, KN, AC, TN, KN, AC, AC, AC }, 	 //	 453	 1500
{ WN, KN, AC, AC, AC, TN, KN, AC, LO, SK, TN, KN, AC, KN, KN }, 	 //	 454	 1500
{ WN, QN, TN, AC, KN, TN, KN, AC, PF, SK, TN, AC, AC, AC, QN }, 	 //	 455	 1500
{ WN, QN, QN, QN, TN, TN, KN, AC, KN, TN, TN, AC, KN, AC, ST }, 	 //	 456	 1500
{ TN, AC, AC, TN, SK, TN, SH, AC, WN, QN, TN, AC, AC, AC, QN }, 	 //	 457	 1500
{ TN, AC, JA, AC, QN, TN, AC, ST, PF, PF, TN, AC, AC, AC, JA }, 	 //	 458	 1500
{ TN, AC, PF, TN, SK, TN, AC, QN, WN, QN, TN, AC, AC, AC, QN }, 	 //	 459	 1500
{ TN, AC, JA, KN, QN, TN, AC, TN, AC, SH, TN, LO, AC, PF, JA }, 	 //	 460	 1500
{ TN, KN, AC, QN, JA, TN, KN, AC, KN, TN, TN, KN, AC, AC, AC }, 	 //	 461	 1500
{ TN, ST, AC, AC, AC, TN, QN, WN, KN, KN, TN, QN, KN, QN, QN }, 	 //	 462	 1500
{ TN, SK, AC, AC, QN, TN, JA, AC, AC, KN, TN, JA, WN, LO, AC }, 	 //	 463	 1500
{ TN, JA, AC, AC, AC, TN, JA, PF, AC, AC, TN, JA, QN, AC, SK }, 	 //	 464	 1500
{ TN, JA, AC, PF, JA, TN, JA, AC, AC, TN, TN, SH, PF, AC, AC }, 	 //	 465	 1500
{ TN, JA, AC, PF, AC, TN, JA, AC, AC, KN, TN, SH, AC, AC, QN }, 	 //	 466	 1500
{ TN, SH, AC, AC, AC, TN, TN, AC, PF, AC, TN, TN, PF, AC, AC }, 	 //	 467	 1500
{ TN, TN, ST, AC, KN, TN, TN, AC, AC, AC, TN, WN, KN, PF, LO }, 	 //	 468	 1500
{ TN, TN, AC, AC, QN, TN, TN, AC, AC, KN, TN, WN, PF, PF, AC }, 	 //	 469	 1500
{ TN, TN, KN, PF, CR, TN, WN, SH, AC, KN, TN, AC, AC, AC, KN }, 	 //	 470	 1500
{ TN, WN, AC, AC, KN, TN, AC, PF, AC, AC, TN, KN, QN, AC, LO }, 	 //	 471	 1500
{ TN, KN, KN, AC, QN, TN, QN, SH, AC, KN, TN, ST, AC, AC, AC }, 	 //	 472	 1500
{ TN, KN, SH, AC, AC, TN, QN, AC, AC, SK, TN, ST, AC, AC, KN }, 	 //	 473	 1500
{ TN, TN, KN, QN, SH, TN, AC, SH, KN, JA, TN, AC, AC, AC, JA }, 	 //	 474	 1500
{ TN, TN, AC, AC, KN, TN, AC, PF, AC, KN, TN, AC, QN, AC, KN }, 	 //	 475	 1500
{ TN, AC, PF, KN, CR, TN, AC, QN, AC, QN, TN, AC, AC, PF, KN }, 	 //	 476	 1500
{ TN, AC, AC, AC, LO, TN, AC, AC, PF, AC, TN, PF, WN, AC, AC }, 	 //	 477	 1500
{ TN, AC, AC, AC, ST, TN, PF, KN, KN, AC, TN, KN, QN, QN, KN }, 	 //	 478	 1500
{ TN, QN, AC, PF, TN, TN, KN, PF, AC, ST, TN, AC, QN, AC, AC }, 	 //	 479	 1500
{ TN, KN, AC, AC, AC, TN, AC, KN, LO, AC, TN, SH, QN, KN, SK }, 	 //	 480	 1500
{ TN, AC, AC, AC, JA, TN, AC, AC, LO, JA, ST, AC, WN, KN, WN }, 	 //	 481	 1500
{ TN, AC, JA, PF, SK, TN, AC, ST, AC, QN, ST, LO, AC, AC, QN }, 	 //	 482	 1500
{ TN, AC, ST, AC, QN, TN, AC, AC, AC, SH, ST, LO, KN, AC, JA }, 	 //	 483	 1500
{ TN, AC, KN, WN, QN, TN, AC, SH, AC, SH, ST, LO, AC, KN, JA }, 	 //	 484	 1500
{ TN, KN, ST, AC, AC, TN, KN, AC, AC, AC, ST, KN, KN, AC, CR }, 	 //	 485	 1500
{ TN, KN, TN, QN, QN, TN, KN, AC, KN, KN, ST, KN, AC, AC, AC }, 	 //	 486	 1500
{ TN, QN, AC, PF, QN, TN, SK, WN, AC, KN, ST, JA, KN, AC, AC }, 	 //	 487	 1500
{ TN, TN, AC, AC, AC, TN, WN, AC, LO, AC, ST, AC, AC, KN, AC }, 	 //	 488	 1500
{ TN, QN, AC, AC, TN, TN, ST, WN, AC, ST, ST, JA, KN, PF, AC }, 	 //	 489	 1500
{ TN, JA, TN, AC, QN, TN, TN, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 490	 1500
{ TN, TN, ST, AC, JA, TN, AC, AC, AC, TN, ST, AC, KN, AC, AC }, 	 //	 491	 1500
{ TN, AC, AC, AC, SH, TN, PF, PF, AC, JA, ST, KN, QN, LO, JA }, 	 //	 492	 1500
{ TN, KN, AC, AC, QN, TN, KN, AC, PF, KN, ST, KN, AC, AC, AC }, 	 //	 493	 1500
{ TN, SK, AC, AC, AC, TN, QN, AC, LO, AC, ST, KN, AC, KN, AC }, 	 //	 494	 1500
{ TN, QN, AC, AC, AC, TN, KN, AC, PF, AC, ST, AC, AC, KN, CR }, 	 //	 495	 1500
{ TN, AC, PF, TN, PF, ST, SH, QN, TN, JA, AC, AC, AC, TN, TN }, 	 //	 496	 1500
{ TN, SH, AC, TN, KN, ST, AC, AC, TN, KN, AC, AC, PF, TN, CR }, 	 //	 497	 1500
{ TN, SH, AC, LO, SK, ST, AC, PF, KN, QN, AC, AC, QN, KN, QN }, 	 //	 498	 1500
{ TN, SH, AC, TN, PF, ST, AC, PF, WN, JA, AC, AC, QN, AC, TN }, 	 //	 499	 1500
{ TN, SH, AC, KN, TN, ST, AC, KN, KN, ST, AC, AC, WN, KN, AC }, 	 //	 500	 1500
{ TN, AC, JA, ST, TN, ST, AC, ST, JA, ST, AC, AC, AC, TN, AC }, 	 //	 501	 1500
{ TN, AC, KN, AC, AC, ST, AC, SH, LO, LO, AC, AC, AC, KN, AC }, 	 //	 502	 1500
{ TN, AC, SH, QN, AC, ST, AC, AC, QN, KN, AC, AC, AC, SK, QN }, 	 //	 503	 1500
{ TN, AC, SH, KN, JA, ST, AC, AC, SK, TN, AC, AC, AC, QN, AC }, 	 //	 504	 1500
{ TN, AC, AC, KN, WN, ST, AC, PF, KN, TN, AC, AC, QN, SK, TN }, 	 //	 505	 1500
{ TN, AC, AC, KN, QN, ST, AC, AC, KN, PF, AC, LO, PF, SK, JA }, 	 //	 506	 1500
{ TN, AC, AC, QN, QN, ST, AC, PF, ST, PF, AC, LO, QN, JA, JA }, 	 //	 507	 1500
{ TN, AC, JA, AC, AC, ST, LO, ST, AC, AC, AC, KN, AC, LO, AC }, 	 //	 508	 1500
{ TN, KN, JA, TN, TN, ST, KN, TN, AC, AC, AC, KN, AC, AC, AC }, 	 //	 509	 1500
{ TN, KN, AC, AC, AC, ST, KN, AC, PF, AC, AC, ST, AC, AC, SK }, 	 //	 510	 1500
{ TN, KN, AC, KN, AC, ST, KN, AC, AC, AC, AC, ST, WN, PF, SK }, 	 //	 511	 1500
{ TN, SK, AC, AC, AC, ST, JA, KN, AC, AC, AC, JA, QN, PF, SK }, 	 //	 512	 1500
{ TN, SK, AC, AC, AC, ST, JA, AC, PF, AC, AC, JA, WN, KN, CR }, 	 //	 513	 1500
{ TN, JA, AC, AC, AC, ST, JA, PF, PF, SK, AC, JA, QN, KN, KN }, 	 //	 514	 1500
{ TN, TN, AC, AC, AC, ST, TN, PF, LO, AC, AC, WN, QN, KN, SK }, 	 //	 515	 1500
{ TN, WN, KN, JA, AC, ST, AC, SH, TN, LO, AC, KN, AC, AC, AC }, 	 //	 516	 1500
{ TN, JA, KN, SK, KN, ST, TN, SH, QN, KN, AC, AC, AC, KN, KN }, 	 //	 517	 1500
{ TN, JA, AC, AC, AC, ST, TN, PF, LO, AC, AC, AC, QN, KN, AC }, 	 //	 518	 1500
{ TN, JA, JA, AC, KN, ST, TN, TN, PF, QN, AC, AC, AC, KN, PF }, 	 //	 519	 1500
{ TN, JA, TN, QN, KN, ST, TN, AC, SK, AC, AC, AC, AC, JA, LO }, 	 //	 520	 1500
{ TN, JA, TN, AC, KN, ST, TN, AC, KN, KN, AC, AC, AC, QN, KN }, 	 //	 521	 1500
{ TN, TN, SH, SK, AC, ST, AC, AC, JA, SK, AC, AC, AC, JA, KN }, 	 //	 522	 1500
{ TN, TN, AC, KN, LO, ST, AC, WN, KN, AC, AC, AC, KN, KN, AC }, 	 //	 523	 1500
{ TN, AC, SH, SK, TN, ST, AC, AC, JA, TN, AC, AC, AC, JA, TN }, 	 //	 524	 1500
{ TN, AC, PF, TN, TN, ST, AC, QN, TN, ST, AC, AC, AC, TN, AC }, 	 //	 525	 1500
{ TN, KN, AC, QN, AC, ST, KN, AC, KN, AC, AC, KN, AC, AC, AC }, 	 //	 526	 1500
{ TN, KN, AC, PF, TN, ST, KN, AC, AC, ST, AC, SK, WN, AC, AC }, 	 //	 527	 1500
{ TN, KN, AC, PF, TN, ST, KN, KN, AC, ST, AC, SK, WN, AC, AC }, 	 //	 528	 1500
{ TN, KN, PF, AC, TN, ST, SK, QN, AC, AC, AC, QN, AC, AC, AC }, 	 //	 529	 1500
{ TN, SK, AC, AC, AC, ST, QN, KN, PF, LO, AC, KN, QN, AC, AC }, 	 //	 530	 1500
{ TN, QN, KN, ST, PF, ST, KN, SH, JA, JA, AC, AC, AC, TN, TN }, 	 //	 531	 1500
{ TN, KN, JA, AC, JA, ST, AC, ST, AC, JA, AC, SH, AC, LO, JA }, 	 //	 532	 1500
{ TN, KN, AC, JA, KN, ST, AC, PF, TN, KN, AC, SH, QN, AC, KN }, 	 //	 533	 1500
{ ST, AC, AC, AC, TN, AC, SH, AC, PF, ST, KN, AC, AC, KN, AC }, 	 //	 534	 1500
{ ST, SH, AC, JA, AC, AC, AC, AC, JA, KN, KN, AC, PF, SH, QN }, 	 //	 535	 1500
{ ST, AC, JA, QN, TN, AC, AC, ST, KN, TN, KN, AC, AC, AC, TN }, 	 //	 536	 1500
{ ST, AC, SH, SH, KN, AC, AC, AC, TN, QN, KN, AC, AC, TN, PF }, 	 //	 537	 1500
{ ST, AC, SH, AC, LO, AC, AC, AC, KN, AC, KN, AC, AC, QN, AC }, 	 //	 538	 1500
{ ST, AC, KN, TN, TN, AC, AC, SH, WN, AC, KN, LO, AC, AC, AC }, 	 //	 539	 1500
{ ST, AC, AC, KN, SK, AC, AC, AC, WN, KN, KN, LO, AC, QN, KN }, 	 //	 540	 1500
{ ST, LO, AC, JA, AC, AC, KN, AC, TN, LO, KN, KN, AC, AC, AC }, 	 //	 541	 1500
{ ST, KN, AC, TN, JA, AC, KN, AC, WN, TN, KN, KN, AC, AC, AC }, 	 //	 542	 1500
{ ST, QN, AC, AC, AC, AC, QN, KN, AC, AC, KN, SK, WN, LO, SK }, 	 //	 543	 1500
{ ST, SK, JA, AC, JA, AC, JA, TN, AC, TN, KN, JA, AC, AC, AC }, 	 //	 544	 1500
{ ST, WN, SH, SK, TN, AC, AC, AC, JA, TN, KN, KN, AC, JA, TN }, 	 //	 545	 1500
{ ST, WN, AC, SH, TN, AC, AC, AC, TN, AC, KN, KN, AC, TN, AC }, 	 //	 546	 1500
{ ST, KN, QN, KN, AC, AC, QN, AC, AC, AC, KN, ST, KN, PF, CR }, 	 //	 547	 1500
{ ST, ST, KN, QN, JA, AC, JA, SH, KN, TN, KN, TN, AC, AC, AC }, 	 //	 548	 1500
{ ST, TN, SH, KN, WN, AC, AC, AC, KN, TN, KN, AC, AC, SK, TN }, 	 //	 549	 1500
{ ST, TN, AC, QN, AC, AC, AC, AC, SK, LO, KN, AC, PF, JA, AC }, 	 //	 550	 1500
{ ST, TN, AC, KN, SK, AC, AC, AC, KN, KN, KN, AC, PF, KN, KN }, 	 //	 551	 1500
{ ST, TN, AC, WN, TN, AC, AC, AC, QN, TN, KN, AC, AC, QN, ST }, 	 //	 552	 1500
{ ST, AC, AC, AC, KN, AC, AC, WN, LO, SK, KN, AC, KN, KN, QN }, 	 //	 553	 1500
{ ST, AC, AC, WN, QN, AC, AC, KN, AC, PF, KN, PF, QN, KN, JA }, 	 //	 554	 1500
{ ST, AC, AC, JA, KN, AC, AC, AC, SH, KN, KN, PF, PF, TN, KN }, 	 //	 555	 1500
{ ST, AC, AC, QN, AC, AC, AC, AC, KN, SK, KN, PF, PF, AC, KN }, 	 //	 556	 1500
{ ST, KN, AC, TN, LO, AC, KN, KN, AC, AC, KN, KN, WN, AC, AC }, 	 //	 557	 1500
{ ST, KN, JA, QN, AC, AC, SK, ST, KN, AC, KN, QN, AC, AC, AC }, 	 //	 558	 1500
{ ST, SK, JA, KN, AC, AC, QN, ST, AC, KN, KN, KN, AC, PF, QN }, 	 //	 559	 1500
{ ST, KN, ST, JA, LO, AC, AC, AC, SH, AC, KN, SH, KN, TN, AC }, 	 //	 560	 1500
{ ST, KN, ST, TN, KN, AC, AC, AC, TN, KN, KN, SH, KN, TN, CR }, 	 //	 561	 1500
{ ST, KN, AC, JA, JA, AC, AC, AC, JA, TN, KN, SH, AC, SH, AC }, 	 //	 562	 1500
{ ST, KN, AC, LO, TN, AC, AC, AC, KN, AC, KN, SH, PF, KN, AC }, 	 //	 563	 1500
{ ST, KN, AC, AC, AC, AC, AC, KN, PF, AC, KN, SH, WN, AC, AC }, 	 //	 564	 1500
{ AC, AC, AC, KN, QN, KN, SH, AC, KN, KN, QN, AC, AC, WN, AC }, 	 //	 565	 1500
{ AC, SH, AC, AC, PF, KN, AC, KN, AC, JA, QN, AC, QN, LO, TN }, 	 //	 566	 1500
{ AC, SH, AC, PF, TN, KN, AC, AC, KN, ST, QN, AC, AC, KN, AC }, 	 //	 567	 1500
{ AC, AC, AC, QN, AC, KN, AC, PF, SK, KN, QN, AC, QN, JA, QN }, 	 //	 568	 1500
{ AC, AC, AC, KN, AC, KN, AC, WN, SK, AC, QN, AC, KN, QN, AC }, 	 //	 569	 1500
{ AC, AC, ST, AC, AC, KN, AC, AC, AC, LO, QN, LO, KN, AC, AC }, 	 //	 570	 1500
{ AC, AC, AC, WN, AC, KN, AC, PF, QN, AC, QN, LO, QN, QN, AC }, 	 //	 571	 1500
{ AC, AC, JA, TN, QN, KN, AC, TN, WN, QN, QN, LO, AC, AC, QN }, 	 //	 572	 1500
{ AC, AC, TN, TN, AC, KN, AC, AC, TN, SK, QN, LO, AC, WN, KN }, 	 //	 573	 1500
{ AC, AC, AC, JA, QN, KN, AC, WN, TN, QN, QN, LO, KN, AC, SH }, 	 //	 574	 1500
{ AC, AC, AC, TN, QN, KN, AC, KN, WN, PF, QN, LO, WN, AC, JA }, 	 //	 575	 1500
{ AC, AC, AC, LO, QN, KN, LO, KN, KN, SH, QN, KN, QN, KN, JA }, 	 //	 576	 1500
{ AC, QN, QN, QN, QN, KN, QN, QN, ST, PF, QN, SK, QN, JA, JA }, 	 //	 577	 1500
{ AC, QN, AC, PF, AC, KN, SK, AC, AC, SK, QN, JA, AC, AC, KN }, 	 //	 578	 1500
{ AC, JA, PF, AC, AC, KN, JA, QN, AC, AC, QN, JA, AC, PF, SK }, 	 //	 579	 1500
{ AC, JA, AC, AC, LO, KN, JA, KN, AC, AC, QN, JA, WN, LO, AC }, 	 //	 580	 1500
{ AC, JA, AC, AC, TN, KN, JA, AC, PF, AC, QN, SH, AC, AC, AC }, 	 //	 581	 1500
{ AC, SH, ST, AC, LO, KN, TN, AC, AC, AC, QN, TN, KN, AC, AC }, 	 //	 582	 1500
{ AC, SH, QN, WN, KN, KN, TN, AC, AC, AC, QN, TN, KN, KN, LO }, 	 //	 583	 1500
{ AC, TN, AC, AC, AC, KN, TN, WN, KN, LO, QN, TN, KN, QN, AC }, 	 //	 584	 1500
{ AC, TN, PF, AC, LO, KN, TN, QN, AC, AC, QN, TN, AC, AC, AC }, 	 //	 585	 1500
{ AC, TN, AC, KN, AC, KN, WN, KN, AC, AC, QN, AC, QN, PF, AC }, 	 //	 586	 1500
{ AC, TN, QN, QN, QN, KN, WN, QN, QN, QN, QN, AC, QN, SK, SH }, 	 //	 587	 1500
{ AC, WN, KN, QN, QN, KN, AC, SH, KN, PF, QN, KN, AC, AC, JA }, 	 //	 588	 1500
{ AC, WN, AC, QN, JA, KN, AC, AC, SK, TN, QN, KN, AC, JA, AC }, 	 //	 589	 1500
{ AC, AC, AC, QN, QN, KN, KN, AC, QN, KN, QN, QN, WN, QN, AC }, 	 //	 590	 1500
{ AC, KN, QN, WN, KN, KN, QN, PF, AC, KN, QN, ST, KN, KN, KN }, 	 //	 591	 1500
{ AC, JA, JA, QN, KN, KN, TN, TN, KN, QN, QN, AC, AC, AC, PF }, 	 //	 592	 1500
{ AC, TN, KN, KN, JA, KN, AC, SH, KN, WN, QN, AC, AC, WN, TN }, 	 //	 593	 1500
{ AC, TN, SH, TN, SK, KN, AC, AC, TN, QN, QN, AC, AC, WN, QN }, 	 //	 594	 1500
{ AC, TN, SH, QN, KN, KN, AC, AC, ST, KN, QN, AC, AC, JA, KN }, 	 //	 595	 1500
{ AC, AC, PF, LO, KN, KN, AC, QN, KN, QN, QN, AC, AC, KN, PF }, 	 //	 596	 1500
{ AC, AC, AC, SK, AC, KN, AC, PF, JA, AC, QN, PF, QN, JA, AC }, 	 //	 597	 1500
{ AC, AC, JA, JA, TN, KN, AC, TN, SH, TN, QN, PF, AC, TN, ST }, 	 //	 598	 1500
{ AC, AC, AC, QN, LO, KN, AC, AC, QN, AC, QN, PF, WN, SK, AC }, 	 //	 599	 1500
{ AC, AC, AC, KN, QN, KN, AC, WN, KN, PF, QN, PF, KN, WN, JA }, 	 //	 600	 1500
{ AC, AC, AC, SH, KN, KN, AC, WN, TN, KN, QN, PF, KN, TN, KN }, 	 //	 601	 1500
{ AC, AC, PF, KN, AC, KN, AC, QN, KN, LO, QN, PF, AC, SK, AC }, 	 //	 602	 1500
{ AC, AC, AC, ST, KN, KN, PF, AC, JA, AC, QN, KN, PF, TN, LO }, 	 //	 603	 1500
{ AC, AC, AC, JA, JA, KN, PF, PF, JA, WN, QN, KN, QN, SH, TN }, 	 //	 604	 1500
{ AC, AC, AC, JA, SK, KN, PF, AC, TN, KN, QN, KN, WN, AC, KN }, 	 //	 605	 1500
{ AC, QN, AC, AC, JA, KN, KN, WN, AC, TN, QN, AC, KN, AC, AC }, 	 //	 606	 1500
{ AC, KN, JA, LO, QN, KN, AC, ST, KN, PF, QN, SH, AC, KN, JA }, 	 //	 607	 1500
{ AC, KN, JA, TN, KN, KN, AC, ST, WN, KN, QN, SH, AC, AC, KN }, 	 //	 608	 1500
{ AC, KN, SH, KN, TN, KN, AC, AC, WN, ST, QN, SH, AC, QN, AC }, 	 //	 609	 1500
{ KN, AC, JA, JA, LO, QN, AC, TN, TN, AC, PF, LO, AC, AC, AC }, 	 //	 610	 1500
{ KN, KN, AC, QN, QN, QN, KN, AC, KN, KN, PF, ST, AC, AC, AC }, 	 //	 611	 1500
{ KN, ST, QN, SK, QN, QN, QN, QN, QN, PF, PF, QN, SK, KN, JA }, 	 //	 612	 1500
{ KN, QN, KN, AC, AC, QN, QN, SH, AC, SK, PF, QN, AC, AC, KN }, 	 //	 613	 1500
{ KN, QN, JA, AC, AC, QN, QN, TN, AC, SK, PF, QN, AC, AC, KN }, 	 //	 614	 1500
{ KN, TN, TN, AC, JA, QN, WN, AC, AC, JA, PF, AC, AC, AC, WN }, 	 //	 615	 1500
{ KN, ST, QN, PF, AC, QN, JA, AC, AC, AC, PF, TN, KN, AC, AC }, 	 //	 616	 1500
{ KN, AC, AC, AC, QN, QN, AC, PF, KN, KN, PF, AC, QN, QN, AC }, 	 //	 617	 1500
{ KN, KN, AC, AC, AC, QN, SK, KN, LO, AC, PF, QN, QN, KN, CR }, 	 //	 618	 1500
{ KN, KN, AC, TN, JA, QN, SK, AC, AC, TN, PF, QN, PF, AC, AC }, 	 //	 619	 1500
{ QN, SH, JA, TN, TN, PF, AC, TN, WN, TN, JA, AC, AC, AC, TN }, 	 //	 620	 1500
{ QN, AC, AC, QN, QN, PF, AC, AC, KN, QN, JA, AC, AC, AC, QN }, 	 //	 621	 1500
{ QN, AC, AC, AC, WN, PF, AC, AC, KN, TN, JA, LO, AC, QN, TN }, 	 //	 622	 1500
{ QN, AC, ST, AC, AC, PF, LO, AC, AC, AC, JA, KN, KN, PF, AC }, 	 //	 623	 1500
{ QN, LO, AC, QN, AC, PF, KN, AC, KN, AC, JA, KN, AC, AC, AC }, 	 //	 624	 1500
{ QN, LO, AC, PF, TN, PF, KN, AC, AC, ST, JA, KN, WN, AC, AC }, 	 //	 625	 1500
{ QN, ST, AC, PF, AC, PF, QN, WN, AC, AC, JA, QN, KN, AC, AC }, 	 //	 626	 1500
{ QN, ST, QN, WN, TN, PF, QN, AC, AC, AC, JA, QN, KN, KN, AC }, 	 //	 627	 1500
{ QN, QN, AC, AC, AC, PF, QN, KN, AC, AC, JA, SK, WN, AC, CR }, 	 //	 628	 1500
{ QN, TN, JA, AC, AC, PF, TN, ST, AC, AC, JA, WN, AC, PF, AC }, 	 //	 629	 1500
{ QN, AC, AC, AC, KN, PF, KN, AC, AC, KN, JA, QN, AC, AC, KN }, 	 //	 630	 1500
{ QN, ST, ST, PF, AC, PF, JA, AC, AC, AC, JA, TN, KN, AC, AC }, 	 //	 631	 1500
{ QN, ST, AC, JA, LO, PF, JA, AC, TN, AC, JA, TN, AC, AC, AC }, 	 //	 632	 1500
{ QN, TN, ST, PF, QN, PF, AC, AC, AC, QN, JA, AC, KN, AC, SH }, 	 //	 633	 1500
{ QN, TN, ST, KN, KN, PF, AC, AC, AC, SK, JA, AC, KN, PF, QN }, 	 //	 634	 1500
{ QN, TN, KN, QN, KN, PF, AC, SH, KN, QN, JA, AC, AC, AC, PF }, 	 //	 635	 1500
{ QN, AC, AC, AC, TN, PF, PF, KN, LO, TN, JA, KN, WN, KN, TN }, 	 //	 636	 1500
{ PF, AC, SH, AC, KN, JA, SH, AC, PF, KN, TN, AC, AC, AC, KN }, 	 //	 637	 1500
{ PF, SH, AC, QN, KN, JA, AC, AC, KN, KN, TN, AC, AC, AC, KN }, 	 //	 638	 1500
{ PF, AC, JA, QN, QN, JA, AC, TN, KN, SH, TN, AC, AC, AC, JA }, 	 //	 639	 1500
{ PF, AC, ST, TN, KN, JA, AC, AC, AC, KN, TN, LO, KN, AC, KN }, 	 //	 640	 1500
{ PF, AC, AC, AC, QN, JA, LO, AC, AC, QN, TN, KN, AC, LO, SH }, 	 //	 641	 1500
{ PF, LO, ST, AC, LO, JA, KN, AC, AC, AC, TN, KN, KN, AC, AC }, 	 //	 642	 1500
{ PF, KN, AC, AC, AC, JA, ST, KN, PF, AC, TN, QN, QN, AC, CR }, 	 //	 643	 1500
{ PF, ST, JA, QN, AC, JA, QN, TN, KN, AC, TN, QN, AC, AC, AC }, 	 //	 644	 1500
{ PF, JA, AC, AC, JA, JA, JA, WN, AC, TN, TN, JA, KN, AC, AC }, 	 //	 645	 1500
{ PF, JA, AC, AC, AC, JA, JA, WN, KN, AC, TN, SH, KN, QN, AC }, 	 //	 646	 1500
{ PF, TN, PF, AC, AC, JA, TN, QN, AC, AC, TN, WN, AC, LO, SK }, 	 //	 647	 1500
{ PF, TN, AC, AC, KN, JA, WN, AC, PF, SK, TN, AC, AC, AC, QN }, 	 //	 648	 1500
{ PF, AC, AC, AC, TN, JA, KN, WN, LO, TN, TN, QN, KN, KN, TN }, 	 //	 649	 1500
{ PF, ST, KN, TN, TN, JA, JA, SH, WN, AC, TN, TN, AC, AC, AC }, 	 //	 650	 1500
{ PF, TN, ST, PF, TN, JA, AC, AC, AC, TN, TN, AC, KN, AC, ST }, 	 //	 651	 1500
{ PF, TN, AC, AC, QN, JA, AC, WN, AC, QN, TN, AC, KN, PF, QN }, 	 //	 652	 1500
{ PF, PF, AC, AC, AC, JA, KN, AC, LO, AC, TN, KN, AC, KN, AC }, 	 //	 653	 1500
{ PF, KN, KN, AC, JA, JA, KN, SH, AC, TN, TN, KN, AC, AC, AC }, 	 //	 654	 1500
{ PF, SK, ST, KN, AC, JA, QN, AC, AC, AC, TN, KN, KN, PF, AC }, 	 //	 655	 1500
{ PF, QN, JA, AC, AC, JA, KN, ST, AC, AC, TN, AC, AC, PF, CR }, 	 //	 656	 1500
{ PF, KN, AC, AC, JA, JA, AC, WN, AC, JA, TN, SH, KN, LO, JA }, 	 //	 657	 1500
{ JA, AC, JA, JA, KN, TN, SH, ST, JA, KN, AC, AC, AC, SH, CR }, 	 //	 658	 1500
{ JA, AC, TN, AC, TN, TN, SH, AC, KN, ST, AC, AC, AC, QN, AC }, 	 //	 659	 1500
{ JA, AC, PF, PF, AC, TN, SH, QN, KN, KN, AC, AC, AC, KN, QN }, 	 //	 660	 1500
{ JA, SH, JA, QN, AC, TN, AC, ST, QN, AC, AC, AC, AC, SK, AC }, 	 //	 661	 1500
{ JA, SH, AC, LO, JA, TN, AC, KN, KN, TN, AC, AC, QN, KN, AC }, 	 //	 662	 1500
{ JA, SH, KN, KN, AC, TN, AC, SH, KN, LO, AC, AC, AC, KN, AC }, 	 //	 663	 1500
{ JA, SH, PF, KN, QN, TN, AC, QN, KN, QN, AC, AC, AC, KN, SH }, 	 //	 664	 1500
{ JA, AC, JA, SK, AC, TN, AC, ST, QN, AC, AC, AC, AC, KN, AC }, 	 //	 665	 1500
{ JA, AC, AC, QN, TN, TN, AC, AC, QN, ST, AC, LO, WN, SK, AC }, 	 //	 666	 1500
{ JA, AC, AC, AC, PF, TN, LO, PF, LO, JA, AC, KN, QN, KN, TN }, 	 //	 667	 1500
{ JA, KN, PF, AC, AC, TN, KN, QN, AC, AC, AC, ST, AC, LO, CR }, 	 //	 668	 1500
{ JA, ST, AC, AC, KN, TN, QN, AC, AC, AC, AC, QN, PF, AC, LO }, 	 //	 669	 1500
{ JA, QN, AC, WN, AC, TN, QN, AC, AC, AC, AC, QN, PF, KN, CR }, 	 //	 670	 1500
{ JA, QN, KN, AC, AC, TN, QN, SH, AC, KN, AC, SK, AC, PF, QN }, 	 //	 671	 1500
{ JA, TN, JA, QN, TN, TN, WN, ST, SK, ST, AC, AC, AC, JA, AC }, 	 //	 672	 1500
{ JA, TN, JA, KN, WN, TN, WN, TN, AC, TN, AC, AC, AC, PF, TN }, 	 //	 673	 1500
{ JA, WN, AC, QN, KN, TN, AC, AC, QN, SK, AC, KN, AC, QN, QN }, 	 //	 674	 1500
{ JA, WN, AC, PF, KN, TN, AC, AC, KN, KN, AC, KN, AC, KN, CR }, 	 //	 675	 1500
{ JA, AC, AC, AC, KN, TN, KN, AC, KN, SK, AC, QN, AC, QN, QN }, 	 //	 676	 1500
{ JA, KN, QN, SK, CR, TN, QN, AC, QN, KN, AC, ST, KN, KN, KN }, 	 //	 677	 1500
{ JA, ST, AC, AC, AC, TN, JA, KN, PF, AC, AC, TN, QN, AC, AC }, 	 //	 678	 1500
{ JA, JA, SH, AC, QN, TN, TN, AC, LO, SH, AC, AC, AC, KN, JA }, 	 //	 679	 1500
{ JA, JA, PF, SH, AC, TN, TN, QN, TN, AC, AC, AC, AC, TN, AC }, 	 //	 680	 1500
{ JA, AC, AC, QN, SH, TN, AC, KN, SK, JA, AC, AC, WN, JA, JA }, 	 //	 681	 1500
{ JA, AC, AC, TN, JA, TN, AC, KN, TN, JA, AC, PF, QN, TN, JA }, 	 //	 682	 1500
{ JA, PF, AC, AC, TN, TN, KN, AC, PF, ST, AC, KN, AC, AC, AC }, 	 //	 683	 1500
{ JA, KN, AC, QN, TN, TN, KN, AC, KN, ST, AC, KN, AC, AC, AC }, 	 //	 684	 1500
{ JA, KN, AC, AC, AC, TN, KN, AC, LO, AC, AC, KN, PF, KN, AC }, 	 //	 685	 1500
{ JA, KN, SH, WN, KN, TN, KN, AC, AC, AC, AC, SK, AC, KN, LO }, 	 //	 686	 1500
{ JA, KN, JA, AC, TN, TN, SK, ST, PF, ST, AC, QN, AC, AC, AC }, 	 //	 687	 1500
{ JA, QN, KN, AC, SH, TN, KN, SH, AC, JA, AC, AC, AC, PF, JA }, 	 //	 688	 1500
{ JA, QN, JA, QN, KN, TN, KN, TN, SK, KN, AC, AC, AC, JA, CR }, 	 //	 689	 1500
{ JA, QN, JA, KN, TN, TN, KN, TN, AC, ST, AC, AC, AC, PF, AC }, 	 //	 690	 1500
{ JA, QN, TN, WN, KN, TN, KN, AC, AC, SK, AC, AC, AC, KN, QN }, 	 //	 691	 1500
{ JA, KN, AC, JA, CR, TN, AC, AC, SH, KN, AC, SH, AC, TN, KN }, 	 //	 692	 1500
{ JA, KN, AC, TN, AC, TN, AC, AC, TN, SK, AC, SH, AC, TN, KN }, 	 //	 693	 1500
{ JA, KN, JA, AC, JA, TN, AC, TN, AC, JA, AC, SH, AC, AC, JA }, 	 //	 694	 1500
{ JA, KN, AC, QN, AC, TN, AC, AC, ST, AC, AC, SH, AC, JA, AC }, 	 //	 695	 1500
{ TN, AC, AC, LO, AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, CR }, 	 //	 696	 1500
{ TN, SH, AC, JA, KN, AC, AC, KN, JA, SK, AC, AC, QN, JA, QN }, 	 //	 697	 1500
{ TN, SH, AC, KN, TN, AC, AC, PF, SK, TN, AC, AC, QN, QN, TN }, 	 //	 698	 1500
{ TN, SH, QN, QN, SH, AC, AC, AC, KN, JA, AC, AC, KN, AC, JA }, 	 //	 699	 1500
{ TN, SH, AC, SK, AC, AC, AC, KN, QN, LO, AC, AC, WN, KN, AC }, 	 //	 700	 1500
{ TN, AC, AC, KN, JA, AC, AC, KN, WN, TN, AC, LO, QN, QN, AC }, 	 //	 701	 1500
{ TN, AC, AC, QN, PF, AC, AC, KN, QN, JA, AC, LO, QN, SK, TN }, 	 //	 702	 1500
{ TN, AC, SH, SH, KN, AC, AC, AC, TN, KN, AC, LO, AC, TN, KN }, 	 //	 703	 1500
{ TN, AC, TN, KN, KN, AC, AC, AC, KN, SK, AC, LO, AC, WN, QN }, 	 //	 704	 1500
{ TN, AC, TN, JA, TN, AC, AC, AC, JA, AC, AC, LO, AC, JA, AC }, 	 //	 705	 1500
{ TN, ST, AC, AC, AC, AC, QN, PF, PF, KN, AC, QN, QN, KN, QN }, 	 //	 706	 1500
{ TN, QN, SH, WN, AC, AC, QN, AC, AC, SK, AC, QN, AC, KN, KN }, 	 //	 707	 1500
{ TN, QN, SH, AC, TN, AC, SK, AC, AC, ST, AC, JA, AC, AC, AC }, 	 //	 708	 1500
{ TN, JA, AC, AC, AC, AC, SH, AC, PF, SK, AC, TN, AC, AC, KN }, 	 //	 709	 1500
{ TN, TN, SH, AC, WN, AC, WN, AC, KN, TN, AC, AC, AC, QN, TN }, 	 //	 710	 1500
{ TN, TN, PF, AC, AC, AC, WN, QN, LO, SK, AC, AC, AC, KN, KN }, 	 //	 711	 1500
{ TN, WN, AC, QN, CR, AC, AC, KN, SK, KN, AC, KN, QN, JA, KN }, 	 //	 712	 1500
{ TN, AC, AC, AC, KN, AC, KN, PF, AC, KN, AC, QN, QN, AC, CR }, 	 //	 713	 1500
{ TN, ST, JA, AC, AC, AC, JA, ST, AC, AC, AC, TN, AC, LO, AC }, 	 //	 714	 1500
{ TN, ST, TN, QN, LO, AC, JA, AC, KN, AC, AC, TN, AC, AC, AC }, 	 //	 715	 1500
{ TN, JA, AC, JA, ST, AC, TN, AC, JA, AC, AC, AC, AC, SH, KN }, 	 //	 716	 1500
{ TN, JA, AC, AC, QN, AC, TN, AC, AC, KN, AC, AC, WN, AC, AC }, 	 //	 717	 1500
{ TN, TN, JA, PF, KN, AC, AC, ST, KN, KN, AC, AC, AC, KN, SK }, 	 //	 718	 1500
{ TN, TN, QN, QN, SH, AC, AC, AC, QN, JA, AC, AC, KN, SK, JA }, 	 //	 719	 1500
{ TN, AC, AC, QN, AC, AC, AC, PF, QN, AC, AC, AC, QN, QN, SK }, 	 //	 720	 1500
{ TN, AC, AC, KN, KN, AC, AC, PF, SK, KN, AC, AC, QN, QN, KN }, 	 //	 721	 1500
{ TN, AC, PF, WN, JA, AC, AC, QN, QN, JA, AC, AC, AC, QN, JA }, 	 //	 722	 1500
{ TN, AC, AC, ST, KN, AC, AC, PF, JA, KN, AC, PF, QN, TN, KN }, 	 //	 723	 1500
{ TN, KN, AC, KN, TN, AC, KN, WN, AC, AC, AC, SK, KN, PF, AC }, 	 //	 724	 1500
{ TN, KN, SH, SK, KN, AC, AC, AC, JA, KN, AC, SH, AC, JA, SK }, 	 //	 725	 1500
{ TN, KN, AC, KN, AC, AC, AC, WN, KN, AC, AC, SH, KN, WN, CR }, 	 //	 726	 1500
{ AC, AC, AC, LO, TN, AC, SH, KN, KN, ST, AC, AC, QN, KN, AC }, 	 //	 727	 1500
{ AC, AC, SH, KN, AC, AC, SH, AC, WN, LO, AC, AC, AC, QN, AC }, 	 //	 728	 1500
{ AC, AC, AC, JA, LO, AC, SH, AC, TN, AC, AC, AC, PF, AC, AC }, 	 //	 729	 1500
{ AC, AC, AC, SK, TN, AC, SH, AC, JA, TN, AC, AC, WN, JA, ST }, 	 //	 730	 1500
{ AC, AC, AC, TN, QN, AC, SH, AC, TN, KN, AC, AC, WN, TN, AC }, 	 //	 731	 1500
{ AC, AC, AC, KN, QN, AC, SH, WN, KN, SH, AC, AC, KN, KN, JA }, 	 //	 732	 1500
{ AC, AC, AC, QN, KN, AC, SH, WN, ST, SK, AC, AC, KN, JA, QN }, 	 //	 733	 1500
{ AC, SH, ST, KN, JA, AC, AC, AC, WN, TN, AC, AC, KN, QN, AC }, 	 //	 734	 1500
{ AC, SH, AC, QN, KN, AC, AC, KN, ST, KN, AC, AC, WN, JA, CR }, 	 //	 735	 1500
{ AC, AC, JA, KN, WN, AC, AC, ST, KN, TN, AC, LO, AC, WN, TN }, 	 //	 736	 1500
{ AC, AC, AC, SK, LO, AC, LO, AC, JA, AC, AC, KN, AC, JA, AC }, 	 //	 737	 1500
{ AC, AC, AC, TN, KN, AC, LO, AC, TN, KN, AC, KN, AC, WN, SK }, 	 //	 738	 1500
{ AC, AC, AC, KN, TN, AC, LO, AC, SK, TN, AC, KN, AC, QN, TN }, 	 //	 739	 1500
{ AC, AC, AC, KN, SK, AC, LO, KN, KN, QN, AC, KN, WN, SK, QN }, 	 //	 740	 1500
{ AC, QN, AC, AC, AC, AC, QN, KN, KN, SK, AC, QN, WN, QN, KN }, 	 //	 741	 1500
{ AC, SK, TN, AC, AC, AC, JA, AC, AC, KN, AC, JA, AC, PF, QN }, 	 //	 742	 1500
{ AC, JA, SH, QN, QN, AC, JA, AC, KN, KN, AC, JA, AC, AC, AC }, 	 //	 743	 1500
{ AC, JA, TN, TN, AC, AC, JA, AC, WN, AC, AC, SH, AC, AC, AC }, 	 //	 744	 1500
{ AC, JA, AC, PF, AC, AC, SH, AC, AC, AC, AC, TN, PF, AC, CR }, 	 //	 745	 1500
{ AC, TN, PF, JA, AC, AC, TN, QN, TN, AC, AC, WN, AC, AC, AC }, 	 //	 746	 1500
{ AC, TN, JA, QN, AC, AC, WN, ST, ST, KN, AC, AC, AC, JA, QN }, 	 //	 747	 1500
{ AC, TN, JA, KN, SH, AC, WN, TN, WN, JA, AC, AC, AC, QN, JA }, 	 //	 748	 1500
{ AC, TN, JA, KN, QN, AC, WN, TN, KN, SH, AC, AC, AC, KN, JA }, 	 //	 749	 1500
{ AC, TN, AC, SK, PF, AC, WN, AC, JA, JA, AC, AC, AC, JA, TN }, 	 //	 750	 1500
{ AC, WN, KN, JA, QN, AC, AC, SH, JA, QN, AC, KN, AC, SH, QN }, 	 //	 751	 1500
{ AC, WN, AC, QN, QN, AC, AC, WN, QN, SH, AC, KN, KN, SK, JA }, 	 //	 752	 1500
{ AC, JA, KN, QN, JA, AC, TN, SH, SK, TN, AC, AC, AC, JA, AC }, 	 //	 753	 1500
{ AC, JA, AC, KN, SK, AC, TN, AC, KN, QN, AC, AC, AC, SK, QN }, 	 //	 754	 1500
{ AC, TN, QN, SK, CR, AC, AC, AC, JA, KN, AC, AC, KN, JA, KN }, 	 //	 755	 1500
{ AC, TN, AC, SK, KN, AC, AC, KN, JA, QN, AC, AC, WN, JA, PF }, 	 //	 756	 1500
{ AC, AC, AC, TN, KN, AC, PF, AC, WN, KN, AC, KN, PF, AC, KN }, 	 //	 757	 1500
{ AC, AC, AC, JA, QN, AC, PF, PF, TN, QN, AC, KN, QN, AC, QN }, 	 //	 758	 1500
{ AC, AC, AC, SK, KN, AC, PF, AC, QN, AC, AC, KN, AC, KN, LO }, 	 //	 759	 1500
{ AC, AC, AC, JA, AC, AC, PF, WN, JA, LO, AC, KN, KN, JA, AC }, 	 //	 760	 1500
{ AC, KN, AC, AC, AC, AC, KN, KN, PF, SK, AC, SK, QN, AC, KN }, 	 //	 761	 1500
{ AC, SK, QN, QN, ST, AC, QN, QN, QN, AC, AC, KN, QN, QN, KN }, 	 //	 762	 1500
{ AC, QN, SH, AC, LO, AC, KN, AC, LO, AC, AC, AC, AC, KN, AC }, 	 //	 763	 1500
{ AC, QN, AC, JA, KN, AC, KN, AC, SH, KN, AC, AC, AC, TN, CR }, 	 //	 764	 1500
{ AC, QN, AC, KN, QN, AC, KN, AC, KN, PF, AC, AC, AC, SK, JA }, 	 //	 765	 1500
{ AC, KN, AC, SK, KN, AC, AC, KN, QN, KN, AC, SH, QN, KN, SK }, 	 //	 766	 1500
{ AC, KN, AC, JA, KN, AC, AC, PF, TN, AC, AC, SH, QN, AC, LO }, 	 //	 767	 1500
{ AC, KN, JA, KN, TN, AC, AC, TN, KN, ST, AC, SH, AC, KN, AC }, 	 //	 768	 1500
{ AC, KN, AC, KN, AC, AC, AC, WN, KN, AC, AC, SH, KN, KN, SK }, 	 //	 769	 1500
{ AC, KN, AC, SK, QN, AC, AC, KN, JA, SH, AC, SH, WN, JA, JA }, 	 //	 770	 1500
{ AC, AC, AC, KN, JA, AC, SH, AC, KN, JA, SK, AC, PF, WN, WN }, 	 //	 771	 1500
{ AC, AC, AC, WN, AC, AC, SH, AC, QN, KN, SK, AC, AC, QN, QN }, 	 //	 772	 1500
{ AC, AC, AC, QN, CR, AC, SH, KN, SK, QN, SK, AC, WN, JA, KN }, 	 //	 773	 1500
{ AC, SH, AC, KN, AC, AC, AC, AC, KN, SK, SK, AC, PF, KN, KN }, 	 //	 774	 1500
{ AC, AC, AC, ST, KN, AC, AC, WN, JA, KN, SK, AC, KN, TN, KN }, 	 //	 775	 1500
{ AC, AC, JA, KN, JA, AC, AC, ST, WN, WN, SK, LO, AC, QN, TN }, 	 //	 776	 1500
{ AC, AC, AC, SH, JA, AC, AC, KN, TN, TN, SK, LO, QN, TN, AC }, 	 //	 777	 1500
{ AC, AC, QN, AC, AC, AC, AC, AC, LO, KN, SK, LO, KN, KN, QN }, 	 //	 778	 1500
{ AC, QN, JA, AC, JA, AC, QN, ST, PF, TN, SK, QN, AC, AC, AC }, 	 //	 779	 1500
{ AC, JA, AC, AC, AC, AC, SH, PF, AC, KN, SK, TN, QN, AC, QN }, 	 //	 780	 1500
{ AC, TN, TN, AC, TN, AC, WN, AC, AC, AC, SK, AC, AC, PF, AC }, 	 //	 781	 1500
{ AC, WN, JA, AC, SH, AC, AC, ST, KN, JA, SK, KN, AC, QN, JA }, 	 //	 782	 1500
{ AC, WN, KN, LO, TN, AC, AC, SH, KN, TN, SK, KN, AC, KN, TN }, 	 //	 783	 1500
{ AC, WN, AC, QN, AC, AC, AC, AC, KN, AC, SK, KN, PF, AC, AC }, 	 //	 784	 1500
{ AC, WN, AC, AC, SK, AC, AC, WN, AC, KN, SK, KN, KN, LO, KN }, 	 //	 785	 1500
{ AC, AC, AC, JA, AC, AC, KN, KN, SH, SK, SK, QN, QN, TN, KN }, 	 //	 786	 1500
{ AC, AC, AC, QN, AC, AC, KN, AC, SK, KN, SK, QN, PF, JA, QN }, 	 //	 787	 1500
{ AC, AC, AC, KN, SK, AC, KN, AC, QN, KN, SK, QN, WN, ST, KN }, 	 //	 788	 1500
{ AC, AC, AC, PF, AC, AC, KN, AC, KN, AC, SK, QN, WN, KN, AC }, 	 //	 789	 1500
{ AC, JA, PF, AC, KN, AC, TN, QN, AC, KN, SK, AC, AC, AC, KN }, 	 //	 790	 1500
{ AC, TN, JA, SK, KN, AC, AC, TN, QN, SK, SK, AC, AC, KN, QN }, 	 //	 791	 1500
{ AC, TN, AC, TN, JA, AC, AC, WN, AC, JA, SK, AC, KN, AC, JA }, 	 //	 792	 1500
{ AC, AC, AC, TN, JA, AC, AC, PF, TN, JA, SK, AC, QN, TN, JA }, 	 //	 793	 1500
{ AC, AC, JA, KN, KN, AC, AC, TN, KN, SK, SK, AC, AC, WN, QN }, 	 //	 794	 1500
{ AC, AC, ST, WN, AC, AC, AC, AC, QN, LO, SK, PF, KN, QN, AC }, 	 //	 795	 1500
{ AC, AC, PF, KN, TN, AC, AC, QN, SK, AC, SK, PF, AC, QN, AC }, 	 //	 796	 1500
{ AC, AC, AC, QN, TN, AC, AC, KN, QN, AC, SK, PF, WN, QN, AC }, 	 //	 797	 1500
{ AC, SK, QN, QN, KN, AC, QN, QN, QN, KN, SK, KN, QN, QN, KN }, 	 //	 798	 1500
{ AC, KN, JA, KN, KN, AC, AC, ST, SK, AC, SK, SH, AC, QN, LO }, 	 //	 799	 1500
{ AC, AC, AC, TN, LO, SK, SH, AC, TN, AC, KN, AC, AC, WN, AC }, 	 //	 800	 1500
{ AC, AC, QN, AC, AC, SK, SH, AC, AC, AC, KN, AC, KN, AC, AC }, 	 //	 801	 1500
{ AC, SH, AC, KN, CR, SK, AC, AC, KN, KN, KN, AC, AC, WN, KN }, 	 //	 802	 1500
{ AC, SH, JA, TN, TN, SK, AC, TN, TN, ST, KN, AC, AC, WN, AC }, 	 //	 803	 1500
{ AC, SH, JA, AC, LO, SK, AC, TN, KN, AC, KN, AC, AC, QN, AC }, 	 //	 804	 1500
{ AC, AC, JA, KN, TN, SK, AC, ST, KN, TN, KN, AC, AC, SK, ST }, 	 //	 805	 1500
{ AC, AC, KN, KN, JA, SK, AC, SH, KN, WN, KN, AC, AC, KN, TN }, 	 //	 806	 1500
{ AC, AC, AC, ST, KN, SK, AC, AC, JA, QN, KN, AC, WN, TN, PF }, 	 //	 807	 1500
{ AC, AC, PF, KN, CR, SK, AC, QN, WN, QN, KN, AC, AC, QN, KN }, 	 //	 808	 1500
{ AC, AC, AC, KN, QN, SK, AC, KN, KN, SH, KN, AC, WN, KN, JA }, 	 //	 809	 1500
{ AC, AC, PF, SH, PF, SK, AC, QN, TN, JA, KN, LO, AC, TN, TN }, 	 //	 810	 1500
{ AC, AC, AC, JA, SH, SK, LO, KN, SH, JA, KN, KN, QN, TN, JA }, 	 //	 811	 1500
{ AC, AC, SH, AC, AC, SK, LO, AC, PF, LO, KN, KN, AC, AC, AC }, 	 //	 812	 1500
{ AC, AC, AC, TN, AC, SK, LO, AC, TN, AC, KN, KN, PF, WN, CR }, 	 //	 813	 1500
{ AC, QN, AC, AC, TN, SK, QN, KN, AC, AC, KN, QN, WN, AC, AC }, 	 //	 814	 1500
{ AC, JA, AC, AC, AC, SK, JA, AC, PF, SK, KN, JA, PF, AC, KN }, 	 //	 815	 1500
{ AC, SH, PF, AC, AC, SK, TN, QN, AC, AC, KN, TN, AC, AC, CR }, 	 //	 816	 1500
{ AC, WN, JA, KN, AC, SK, AC, TN, KN, AC, KN, KN, AC, WN, CR }, 	 //	 817	 1500
{ AC, AC, ST, AC, TN, SK, KN, AC, AC, AC, KN, QN, KN, PF, AC }, 	 //	 818	 1500
{ AC, AC, AC, TN, LO, SK, KN, AC, TN, AC, KN, QN, PF, WN, AC }, 	 //	 819	 1500
{ AC, AC, AC, KN, AC, SK, KN, AC, QN, AC, KN, QN, PF, ST, AC }, 	 //	 820	 1500
{ AC, ST, QN, AC, AC, SK, JA, AC, AC, AC, KN, TN, KN, PF, AC }, 	 //	 821	 1500
{ AC, JA, AC, PF, JA, SK, TN, AC, AC, WN, KN, AC, AC, AC, TN }, 	 //	 822	 1500
{ AC, TN, SH, AC, AC, SK, AC, AC, KN, AC, KN, AC, AC, QN, SK }, 	 //	 823	 1500
{ AC, AC, AC, JA, ST, SK, AC, WN, JA, AC, KN, AC, KN, SH, KN }, 	 //	 824	 1500
{ AC, AC, PF, QN, AC, SK, AC, QN, QN, AC, KN, AC, AC, QN, AC }, 	 //	 825	 1500
{ AC, AC, AC, ST, SH, SK, AC, KN, JA, JA, KN, AC, WN, TN, JA }, 	 //	 826	 1500
{ AC, AC, AC, SK, ST, SK, PF, KN, QN, AC, KN, KN, QN, KN, KN }, 	 //	 827	 1500
{ AC, AC, AC, KN, JA, SK, PF, AC, KN, WN, KN, KN, AC, WN, TN }, 	 //	 828	 1500
{ AC, AC, AC, JA, AC, SK, PF, AC, JA, SK, KN, KN, AC, SH, KN }, 	 //	 829	 1500
{ AC, AC, AC, KN, QN, SK, PF, AC, KN, QN, KN, KN, AC, KN, QN }, 	 //	 830	 1500
{ AC, AC, QN, KN, SK, SK, PF, AC, QN, QN, KN, KN, KN, ST, QN }, 	 //	 831	 1500
{ AC, QN, ST, AC, AC, SK, KN, AC, AC, AC, KN, AC, KN, AC, AC }, 	 //	 832	 1500
{ AC, QN, AC, AC, KN, SK, KN, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 833	 1500
{ AC, KN, SH, JA, JA, SK, AC, AC, JA, JA, KN, SH, AC, SH, JA }, 	 //	 834	 1500
{ AC, KN, TN, JA, QN, SK, AC, AC, TN, PF, KN, SH, AC, AC, JA }, 	 //	 835	 1500
{ AC, KN, AC, JA, SK, SK, AC, AC, SH, QN, KN, SH, AC, TN, QN }, 	 //	 836	 1500
{ SK, AC, AC, AC, KN, KN, SH, KN, PF, KN, KN, AC, QN, KN, SK }, 	 //	 837	 1500
{ SK, AC, KN, AC, TN, KN, AC, SH, AC, TN, KN, AC, AC, LO, ST }, 	 //	 838	 1500
{ SK, AC, PF, TN, WN, KN, AC, QN, WN, TN, KN, AC, AC, AC, TN }, 	 //	 839	 1500
{ SK, KN, AC, AC, TN, KN, KN, PF, AC, ST, KN, KN, QN, AC, AC }, 	 //	 840	 1500
{ SK, JA, AC, TN, AC, KN, JA, AC, AC, AC, KN, SH, PF, AC, CR }, 	 //	 841	 1500
{ SK, TN, AC, JA, AC, KN, WN, AC, TN, SK, KN, AC, AC, AC, KN }, 	 //	 842	 1500
{ SK, TN, TN, AC, JA, KN, WN, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 843	 1500
{ SK, AC, KN, KN, AC, KN, KN, PF, WN, AC, KN, QN, QN, QN, SK }, 	 //	 844	 1500
{ SK, ST, AC, AC, AC, KN, JA, KN, KN, AC, KN, TN, QN, QN, SK }, 	 //	 845	 1500
{ SK, ST, PF, WN, AC, KN, JA, QN, AC, LO, KN, TN, AC, KN, AC }, 	 //	 846	 1500
{ SK, JA, JA, QN, SK, KN, TN, TN, KN, KN, KN, AC, AC, AC, KN }, 	 //	 847	 1500
{ SK, JA, AC, AC, AC, KN, TN, WN, AC, KN, KN, AC, KN, AC, QN }, 	 //	 848	 1500
{ SK, AC, AC, AC, TN, KN, AC, KN, PF, TN, KN, AC, QN, KN, TN }, 	 //	 849	 1500
{ SK, AC, QN, AC, SK, KN, AC, AC, AC, QN, KN, PF, KN, PF, QN }, 	 //	 850	 1500
{ SK, KN, AC, KN, SK, KN, AC, KN, AC, QN, KN, SH, WN, PF, QN }, 	 //	 851	 1500
{ KN, AC, ST, TN, PF, KN, AC, AC, AC, JA, KN, LO, KN, AC, TN }, 	 //	 852	 1500
{ KN, AC, AC, AC, JA, KN, LO, AC, LO, JA, KN, KN, AC, KN, WN }, 	 //	 853	 1500
{ KN, TN, QN, AC, AC, KN, TN, AC, AC, AC, KN, WN, KN, LO, SK }, 	 //	 854	 1500
{ KN, WN, AC, KN, QN, KN, AC, PF, AC, QN, KN, KN, QN, PF, QN }, 	 //	 855	 1500
{ KN, WN, PF, TN, KN, KN, AC, QN, AC, KN, KN, KN, AC, AC, CR }, 	 //	 856	 1500
{ KN, JA, AC, TN, SK, KN, TN, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 857	 1500
{ KN, TN, AC, KN, KN, KN, AC, KN, AC, SK, KN, AC, QN, PF, QN }, 	 //	 858	 1500
{ KN, TN, PF, KN, SH, KN, AC, QN, AC, JA, KN, AC, AC, PF, JA }, 	 //	 859	 1500
{ KN, AC, ST, AC, SK, KN, AC, AC, AC, QN, KN, AC, KN, AC, QN }, 	 //	 860	 1500
{ KN, AC, KN, WN, QN, KN, AC, SH, AC, PF, KN, PF, AC, KN, JA }, 	 //	 861	 1500
{ KN, AC, JA, AC, KN, KN, AC, TN, AC, QN, KN, PF, AC, AC, PF }, 	 //	 862	 1500
{ KN, PF, AC, KN, ST, KN, KN, AC, AC, AC, KN, KN, WN, PF, KN }, 	 //	 863	 1500
{ KN, KN, AC, AC, KN, KN, KN, AC, AC, AC, KN, KN, AC, AC, LO }, 	 //	 864	 1500
{ KN, KN, ST, AC, TN, KN, AC, AC, AC, TN, KN, SH, KN, LO, TN }, 	 //	 865	 1500
{ KN, SH, JA, AC, JA, KN, AC, TN, AC, JA, WN, AC, AC, LO, JA }, 	 //	 866	 1500
{ KN, SH, AC, JA, ST, KN, AC, AC, TN, AC, WN, AC, AC, AC, KN }, 	 //	 867	 1500
{ KN, SH, PF, AC, CR, KN, AC, QN, AC, QN, WN, AC, AC, LO, KN }, 	 //	 868	 1500
{ KN, AC, ST, WN, KN, KN, AC, AC, AC, QN, WN, AC, KN, KN, PF }, 	 //	 869	 1500
{ KN, AC, AC, AC, TN, KN, AC, PF, LO, TN, WN, AC, QN, KN, TN }, 	 //	 870	 1500
{ KN, AC, AC, AC, SK, KN, AC, AC, PF, KN, WN, AC, WN, AC, KN }, 	 //	 871	 1500
{ KN, AC, JA, AC, WN, KN, AC, ST, AC, TN, WN, LO, AC, AC, TN }, 	 //	 872	 1500
{ KN, QN, AC, WN, TN, KN, QN, KN, AC, ST, WN, SK, QN, KN, AC }, 	 //	 873	 1500
{ KN, QN, AC, AC, TN, KN, QN, AC, AC, ST, WN, SK, PF, AC, AC }, 	 //	 874	 1500
{ KN, QN, AC, TN, JA, KN, QN, PF, AC, TN, WN, SK, QN, AC, AC }, 	 //	 875	 1500
{ KN, JA, KN, PF, TN, KN, JA, SH, AC, AC, WN, SH, AC, AC, AC }, 	 //	 876	 1500
{ KN, JA, JA, WN, AC, KN, SH, ST, AC, AC, WN, TN, AC, KN, AC }, 	 //	 877	 1500
{ KN, SH, SH, WN, AC, KN, TN, AC, AC, KN, WN, TN, AC, KN, QN }, 	 //	 878	 1500
{ KN, WN, AC, PF, CR, KN, AC, KN, AC, KN, WN, KN, WN, AC, KN }, 	 //	 879	 1500
{ KN, AC, AC, TN, AC, KN, KN, AC, WN, LO, WN, QN, AC, AC, AC }, 	 //	 880	 1500
{ KN, JA, ST, PF, AC, KN, TN, AC, AC, AC, WN, AC, KN, AC, SK }, 	 //	 881	 1500
{ KN, TN, AC, AC, SK, KN, AC, KN, AC, KN, WN, AC, QN, AC, KN }, 	 //	 882	 1500
{ KN, TN, PF, WN, KN, KN, AC, QN, AC, KN, WN, AC, AC, KN, KN }, 	 //	 883	 1500
{ KN, AC, AC, WN, QN, KN, AC, KN, AC, SH, WN, PF, QN, KN, JA }, 	 //	 884	 1500
{ KN, AC, KN, KN, JA, KN, AC, SH, AC, JA, WN, PF, AC, PF, JA }, 	 //	 885	 1500
{ KN, AC, TN, PF, AC, KN, PF, AC, AC, SK, WN, KN, AC, AC, KN }, 	 //	 886	 1500
{ KN, AC, AC, AC, TN, KN, PF, KN, PF, ST, WN, KN, WN, KN, AC }, 	 //	 887	 1500
{ KN, KN, AC, AC, AC, KN, KN, AC, KN, AC, WN, SK, PF, QN, CR }, 	 //	 888	 1500
{ KN, SH, KN, TN, TN, WN, AC, SH, WN, TN, QN, AC, AC, AC, ST }, 	 //	 889	 1500
{ KN, AC, JA, WN, JA, WN, AC, ST, AC, JA, QN, AC, AC, KN, JA }, 	 //	 890	 1500
{ KN, AC, ST, PF, JA, WN, AC, AC, AC, JA, QN, AC, KN, AC, JA }, 	 //	 891	 1500
{ KN, AC, AC, AC, KN, WN, LO, AC, PF, SK, QN, KN, WN, AC, QN }, 	 //	 892	 1500
{ KN, KN, AC, AC, AC, WN, KN, AC, PF, AC, QN, ST, PF, KN, AC }, 	 //	 893	 1500
{ KN, QN, JA, JA, AC, WN, SK, TN, TN, AC, QN, JA, AC, AC, AC }, 	 //	 894	 1500
{ KN, SK, AC, AC, AC, WN, JA, AC, LO, SK, QN, JA, AC, KN, KN }, 	 //	 895	 1500
{ KN, JA, KN, AC, LO, WN, JA, SH, AC, AC, QN, JA, AC, AC, AC }, 	 //	 896	 1500
{ KN, JA, ST, AC, AC, WN, SH, AC, AC, AC, QN, TN, KN, AC, AC }, 	 //	 897	 1500
{ KN, JA, AC, AC, AC, WN, SH, AC, KN, AC, QN, TN, AC, QN, AC }, 	 //	 898	 1500
{ KN, TN, TN, KN, LO, WN, TN, AC, AC, AC, QN, WN, AC, PF, AC }, 	 //	 899	 1500
{ KN, AC, KN, AC, AC, WN, KN, SH, AC, AC, QN, QN, AC, AC, SK }, 	 //	 900	 1500
{ KN, KN, PF, TN, AC, WN, QN, QN, AC, AC, QN, ST, AC, AC, SK }, 	 //	 901	 1500
{ KN, JA, ST, AC, ST, WN, TN, AC, AC, AC, QN, AC, KN, AC, KN }, 	 //	 902	 1500
{ KN, TN, JA, KN, SK, WN, AC, ST, AC, QN, QN, AC, AC, PF, QN }, 	 //	 903	 1500
{ KN, AC, JA, QN, QN, WN, AC, TN, KN, KN, QN, PF, AC, AC, AC }, 	 //	 904	 1500
{ WN, AC, AC, AC, SK, QN, SH, AC, AC, QN, KN, AC, WN, AC, QN }, 	 //	 905	 1500
{ WN, AC, PF, TN, PF, QN, SH, QN, AC, JA, KN, AC, AC, AC, TN }, 	 //	 906	 1500
{ WN, AC, PF, TN, TN, QN, AC, QN, AC, TN, KN, LO, AC, AC, ST }, 	 //	 907	 1500
{ WN, AC, AC, AC, PF, QN, AC, KN, LO, JA, KN, LO, WN, KN, TN }, 	 //	 908	 1500
{ WN, LO, JA, JA, TN, QN, KN, TN, TN, AC, KN, KN, AC, AC, AC }, 	 //	 909	 1500
{ WN, KN, PF, PF, TN, QN, KN, QN, AC, AC, KN, KN, AC, AC, AC }, 	 //	 910	 1500
{ WN, KN, ST, KN, AC, QN, KN, AC, AC, AC, KN, ST, KN, PF, SK }, 	 //	 911	 1500
{ WN, KN, KN, AC, CR, QN, ST, PF, KN, QN, KN, QN, QN, QN, KN }, 	 //	 912	 1500
{ WN, JA, SH, AC, JA, QN, JA, AC, AC, TN, KN, JA, AC, AC, AC }, 	 //	 913	 1500
{ WN, JA, AC, QN, JA, QN, JA, AC, KN, TN, KN, JA, AC, AC, AC }, 	 //	 914	 1500
{ WN, SH, AC, AC, JA, QN, TN, AC, AC, TN, KN, TN, WN, LO, AC }, 	 //	 915	 1500
{ WN, TN, JA, AC, JA, QN, TN, ST, AC, TN, KN, WN, AC, AC, AC }, 	 //	 916	 1500
{ WN, TN, AC, AC, JA, QN, TN, WN, AC, TN, KN, WN, KN, PF, AC }, 	 //	 917	 1500
{ WN, ST, AC, KN, TN, QN, JA, PF, AC, AC, KN, TN, QN, PF, AC }, 	 //	 918	 1500
{ WN, TN, JA, WN, ST, QN, AC, ST, AC, AC, KN, AC, AC, KN, KN }, 	 //	 919	 1500
{ WN, PF, AC, AC, AC, QN, KN, KN, PF, AC, KN, KN, QN, AC, AC }, 	 //	 920	 1500
{ WN, KN, AC, AC, QN, QN, KN, WN, AC, KN, KN, SK, KN, AC, AC }, 	 //	 921	 1500
{ WN, SK, QN, QN, QN, QN, QN, PF, ST, KN, KN, KN, KN, JA, AC }, 	 //	 922	 1500
{ QN, AC, PF, SH, AC, KN, SH, QN, TN, AC, AC, AC, AC, TN, AC }, 	 //	 923	 1500
{ QN, SH, JA, SK, KN, KN, AC, ST, QN, KN, AC, AC, AC, KN, KN }, 	 //	 924	 1500
{ QN, AC, KN, AC, KN, KN, AC, SH, PF, SK, AC, AC, AC, KN, QN }, 	 //	 925	 1500
{ QN, AC, TN, SK, AC, KN, AC, AC, QN, KN, AC, AC, AC, KN, QN }, 	 //	 926	 1500
{ QN, AC, AC, SK, AC, KN, AC, AC, QN, AC, AC, AC, WN, KN, SK }, 	 //	 927	 1500
{ QN, AC, AC, SK, AC, KN, AC, AC, JA, AC, AC, LO, AC, JA, SK }, 	 //	 928	 1500
{ QN, KN, KN, PF, AC, KN, KN, SH, AC, AC, AC, ST, AC, AC, SK }, 	 //	 929	 1500
{ QN, KN, AC, AC, QN, KN, ST, AC, AC, KN, AC, QN, WN, PF, AC }, 	 //	 930	 1500
{ QN, QN, AC, QN, JA, KN, QN, PF, QN, TN, AC, QN, QN, QN, AC }, 	 //	 931	 1500
{ QN, QN, AC, AC, AC, KN, QN, AC, LO, LO, AC, SK, AC, KN, AC }, 	 //	 932	 1500
{ QN, SK, ST, PF, LO, KN, JA, AC, AC, AC, AC, JA, KN, AC, AC }, 	 //	 933	 1500
{ QN, JA, AC, KN, AC, KN, JA, KN, AC, AC, AC, JA, QN, PF, AC }, 	 //	 934	 1500
{ QN, JA, JA, PF, LO, KN, SH, ST, AC, AC, AC, TN, AC, AC, AC }, 	 //	 935	 1500
{ QN, TN, JA, AC, QN, KN, WN, ST, KN, KN, AC, AC, AC, QN, AC }, 	 //	 936	 1500
{ QN, TN, KN, SK, LO, KN, WN, SH, JA, AC, AC, AC, AC, JA, AC }, 	 //	 937	 1500
{ QN, TN, AC, PF, KN, KN, WN, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 938	 1500
{ QN, WN, AC, AC, QN, KN, AC, AC, LO, QN, AC, KN, AC, KN, SH }, 	 //	 939	 1500
{ QN, WN, AC, WN, KN, KN, AC, AC, QN, KN, AC, KN, PF, QN, SK }, 	 //	 940	 1500
{ QN, WN, AC, SH, KN, KN, AC, AC, TN, AC, AC, KN, AC, TN, LO }, 	 //	 941	 1500
{ QN, WN, AC, KN, PF, KN, AC, AC, SK, JA, AC, KN, WN, QN, TN }, 	 //	 942	 1500
{ QN, JA, SH, PF, CR, KN, TN, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 943	 1500
{ QN, JA, TN, WN, PF, KN, TN, AC, AC, JA, AC, AC, AC, KN, TN }, 	 //	 944	 1500
{ QN, TN, JA, ST, WN, KN, AC, ST, JA, TN, AC, AC, AC, TN, TN }, 	 //	 945	 1500
{ QN, TN, AC, JA, JA, KN, AC, AC, TN, WN, AC, AC, WN, AC, TN }, 	 //	 946	 1500
{ QN, TN, PF, KN, TN, KN, AC, QN, KN, AC, AC, AC, AC, WN, AC }, 	 //	 947	 1500
{ QN, AC, SH, TN, KN, KN, AC, AC, TN, AC, AC, AC, AC, TN, LO }, 	 //	 948	 1500
{ QN, AC, AC, JA, KN, KN, AC, AC, SH, SK, AC, AC, PF, TN, QN }, 	 //	 949	 1500
{ QN, AC, AC, KN, KN, KN, AC, AC, SK, AC, AC, AC, PF, QN, LO }, 	 //	 950	 1500
{ QN, AC, JA, AC, QN, KN, AC, TN, AC, KN, AC, PF, AC, LO, AC }, 	 //	 951	 1500
{ QN, AC, AC, KN, SK, KN, AC, AC, KN, KN, AC, PF, AC, WN, KN }, 	 //	 952	 1500
{ QN, AC, AC, SK, AC, KN, AC, WN, QN, AC, AC, PF, KN, KN, AC }, 	 //	 953	 1500
{ QN, AC, QN, AC, JA, KN, AC, AC, AC, WN, AC, PF, KN, AC, TN }, 	 //	 954	 1500
{ QN, QN, JA, TN, QN, KN, KN, ST, TN, QN, AC, AC, AC, WN, QN }, 	 //	 955	 1500
{ QN, QN, SH, KN, SK, KN, KN, AC, QN, QN, AC, AC, AC, ST, QN }, 	 //	 956	 1500
{ QN, QN, JA, LO, QN, KN, KN, TN, KN, KN, AC, AC, AC, KN, AC }, 	 //	 957	 1500
{ QN, KN, ST, AC, QN, KN, AC, AC, AC, KN, AC, SH, KN, LO, AC }, 	 //	 958	 1500
{ QN, KN, AC, KN, QN, KN, AC, KN, KN, PF, AC, SH, QN, SK, JA }, 	 //	 959	 1500
{ KN, AC, JA, TN, TN, AC, SH, ST, WN, TN, LO, AC, AC, AC, TN }, 	 //	 960	 1500
{ KN, AC, AC, ST, CR, AC, AC, AC, JA, KN, LO, AC, AC, TN, KN }, 	 //	 961	 1500
{ KN, AC, AC, TN, JA, AC, AC, KN, AC, WN, LO, LO, QN, AC, TN }, 	 //	 962	 1500
{ KN, AC, AC, JA, TN, AC, AC, AC, JA, AC, LO, LO, WN, JA, AC }, 	 //	 963	 1500
{ KN, AC, AC, AC, KN, AC, LO, KN, AC, KN, LO, KN, QN, PF, SK }, 	 //	 964	 1500
{ KN, KN, JA, AC, TN, AC, ST, TN, PF, AC, LO, QN, AC, AC, AC }, 	 //	 965	 1500
{ KN, KN, TN, AC, ST, AC, ST, AC, AC, AC, LO, QN, AC, AC, KN }, 	 //	 966	 1500
{ KN, QN, QN, QN, TN, AC, QN, QN, QN, ST, LO, QN, SK, QN, AC }, 	 //	 967	 1500
{ KN, JA, PF, QN, AC, AC, SH, QN, KN, AC, LO, TN, AC, AC, AC }, 	 //	 968	 1500
{ KN, TN, JA, QN, AC, AC, TN, ST, KN, AC, LO, WN, AC, AC, AC }, 	 //	 969	 1500
{ KN, WN, AC, SH, QN, AC, AC, AC, TN, QN, LO, KN, AC, TN, SH }, 	 //	 970	 1500
{ KN, WN, AC, AC, QN, AC, AC, WN, AC, QN, LO, KN, KN, LO, SH }, 	 //	 971	 1500
{ KN, AC, AC, AC, TN, AC, KN, PF, PF, AC, LO, QN, QN, AC, AC }, 	 //	 972	 1500
{ KN, AC, SH, SK, JA, AC, AC, AC, JA, TN, LO, AC, AC, JA, AC }, 	 //	 973	 1500
{ KN, AC, ST, KN, WN, AC, AC, AC, KN, TN, LO, PF, KN, SK, TN }, 	 //	 974	 1500
{ KN, AC, SH, KN, QN, AC, AC, AC, KN, QN, LO, PF, AC, KN, SH }, 	 //	 975	 1500
{ KN, AC, AC, JA, WN, AC, AC, AC, SH, TN, LO, PF, AC, TN, TN }, 	 //	 976	 1500
{ KN, AC, AC, QN, KN, AC, AC, AC, ST, AC, LO, PF, AC, JA, LO }, 	 //	 977	 1500
{ KN, AC, AC, AC, PF, AC, AC, KN, LO, JA, LO, PF, WN, KN, TN }, 	 //	 978	 1500
{ KN, PF, AC, TN, TN, AC, KN, KN, AC, ST, LO, KN, WN, AC, AC }, 	 //	 979	 1500
{ KN, KN, PF, AC, QN, AC, KN, QN, PF, KN, LO, KN, AC, AC, AC }, 	 //	 980	 1500
{ KN, SK, AC, KN, AC, AC, QN, AC, AC, SK, LO, KN, AC, PF, KN }, 	 //	 981	 1500
{ KN, SK, QN, SK, QN, AC, QN, AC, QN, PF, LO, KN, KN, KN, JA }, 	 //	 982	 1500
{ KN, KN, ST, KN, JA, AC, AC, AC, KN, TN, LO, SH, KN, KN, AC }, 	 //	 983	 1500
{ KN, KN, TN, JA, LO, AC, AC, AC, SH, AC, LO, SH, AC, TN, AC }, 	 //	 984	 1500
{ KN, KN, AC, KN, AC, AC, AC, AC, WN, SK, LO, SH, AC, QN, KN }, 	 //	 985	 1500
