unsigned char L5_Outcome_12000[1000][15]={	 //	 0	 12000
{ AC, SH, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 1	 12000
{ AC, SH, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 2	 12000
{ AC, SH, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 3	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 4	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 5	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 6	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 7	 12000
{ AC, SH, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 8	 12000
{ AC, SH, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 9	 12000
{ AC, SH, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 10	 12000
{ AC, SH, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 11	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 12	 12000
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 13	 12000
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 14	 12000
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 15	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 16	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 17	 12000
{ AC, AC, SH, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 18	 12000
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 19	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 20	 12000
{ AC, AC, AC, WN, LO, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 21	 12000
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 22	 12000
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 23	 12000
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 24	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 25	 12000
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 26	 12000
{ AC, AC, AC, KN, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 27	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 28	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 29	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 30	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 31	 12000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 32	 12000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 33	 12000
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 34	 12000
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 35	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 36	 12000
{ AC, AC, AC, WN, LO, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 37	 12000
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 38	 12000
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 39	 12000
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 40	 12000
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 41	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 42	 12000
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 43	 12000
{ AC, AC, AC, KN, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 44	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 45	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 46	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 47	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 48	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 49	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 50	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 51	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 52	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 53	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 54	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 55	 12000
{ AC, AC, AC, PF, LO, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 56	 12000
{ AC, AC, AC, PF, TN, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 57	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 58	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 59	 12000
{ AC, AC, AC, TN, LO, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 60	 12000
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 61	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 62	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 63	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 64	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 65	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 66	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 67	 12000
{ AC, WN, AC, WN, AC, LO, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 68	 12000
{ AC, WN, AC, WN, AC, LO, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 69	 12000
{ AC, WN, AC, WN, AC, LO, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 70	 12000
{ AC, WN, AC, KN, AC, LO, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 71	 12000
{ AC, WN, AC, KN, AC, LO, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 72	 12000
{ AC, TN, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 73	 12000
{ AC, TN, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 74	 12000
{ AC, TN, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 75	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 76	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 77	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 78	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 79	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 80	 12000
{ AC, TN, TN, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 81	 12000
{ AC, TN, TN, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 82	 12000
{ AC, TN, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 83	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 84	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 85	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 86	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 87	 12000
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 88	 12000
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 89	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 90	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 91	 12000
{ AC, AC, SH, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 92	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 93	 12000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 94	 12000
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 95	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 96	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 97	 12000
{ AC, AC, AC, WN, LO, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 98	 12000
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 99	 12000
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 100	 12000
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 101	 12000
{ AC, AC, AC, KN, LO, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 102	 12000
{ AC, AC, AC, KN, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 103	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 104	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 105	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 106	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 107	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 108	 12000
{ AC, AC, TN, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 109	 12000
{ AC, AC, TN, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 110	 12000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 111	 12000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 112	 12000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 113	 12000
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 114	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 115	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 116	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 117	 12000
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 118	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 119	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 120	 12000
{ AC, AC, AC, KN, LO, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 121	 12000
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 122	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 123	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 124	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 125	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 126	 12000
{ AC, AC, AC, PF, TN, LO, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 127	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 128	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 129	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 130	 12000
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 131	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 132	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 133	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 134	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 135	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 136	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 137	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 138	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 139	 12000
{ AC, AC, AC, TN, LO, LO, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 140	 12000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 141	 12000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 142	 12000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 143	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 144	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 145	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 146	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 147	 12000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 148	 12000
{ AC, KN, AC, WN, AC, LO, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 149	 12000
{ AC, KN, AC, KN, AC, LO, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 150	 12000
{ AC, KN, AC, WN, AC, LO, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 151	 12000
{ AC, KN, AC, KN, AC, LO, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 152	 12000
{ AC, KN, AC, KN, AC, LO, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 153	 12000
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 154	 12000
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 155	 12000
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 156	 12000
{ LO, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 157	 12000
{ LO, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 158	 12000
{ LO, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 159	 12000
{ LO, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 160	 12000
{ LO, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 161	 12000
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 162	 12000
{ LO, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 163	 12000
{ LO, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 164	 12000
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 165	 12000
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 166	 12000
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 167	 12000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 168	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 169	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 170	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 171	 12000
{ LO, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 172	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 173	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 174	 12000
{ LO, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 175	 12000
{ LO, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 176	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 177	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 178	 12000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 179	 12000
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 180	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 181	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 182	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 183	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 184	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 185	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 186	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 187	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 188	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 189	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 190	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 191	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 192	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 193	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 194	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 195	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 196	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 197	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 198	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 199	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 200	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 201	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 202	 12000
{ LO, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 203	 12000
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 204	 12000
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 205	 12000
{ LO, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 206	 12000
{ LO, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 207	 12000
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 208	 12000
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 209	 12000
{ LO, TN, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 210	 12000
{ LO, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 211	 12000
{ LO, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 212	 12000
{ LO, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 213	 12000
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 214	 12000
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 215	 12000
{ LO, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 216	 12000
{ LO, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 217	 12000
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 218	 12000
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 219	 12000
{ LO, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 220	 12000
{ LO, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 221	 12000
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 222	 12000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 223	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 224	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 225	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 226	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 227	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 228	 12000
{ LO, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 229	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 230	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 231	 12000
{ LO, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 232	 12000
{ LO, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 233	 12000
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 234	 12000
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 235	 12000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 236	 12000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 237	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 238	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 239	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 240	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 241	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 242	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 243	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 244	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 245	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 246	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 247	 12000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 248	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 249	 12000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 250	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 251	 12000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 252	 12000
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 253	 12000
{ LO, KN, AC, KN, AC, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 254	 12000
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 255	 12000
{ LO, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 256	 12000
{ LO, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 257	 12000
{ LO, KN, AC, KN, AC, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 258	 12000
{ LO, KN, AC, KN, AC, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 259	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 260	 12000
{ AC, SH, SH, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 261	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 262	 12000
{ AC, SH, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 263	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 264	 12000
{ AC, SH, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 265	 12000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 266	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 267	 12000
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 268	 12000
{ AC, SH, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 269	 12000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 270	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 271	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 272	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 273	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 274	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 275	 12000
{ AC, SH, TN, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 276	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 277	 12000
{ AC, SH, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 278	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 279	 12000
{ AC, SH, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 280	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 281	 12000
{ AC, SH, TN, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 282	 12000
{ AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 283	 12000
{ AC, SH, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 284	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 285	 12000
{ AC, SH, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 286	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 287	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 288	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 289	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 290	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 291	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 292	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 293	 12000
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 294	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 295	 12000
{ AC, AC, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 296	 12000
{ AC, AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 297	 12000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 298	 12000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 299	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }, 	 //	 300	 12000
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 301	 12000
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 302	 12000
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 303	 12000
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 304	 12000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 305	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 306	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 307	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 308	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, LO, AC }, 	 //	 309	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 310	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, CR }, 	 //	 311	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 312	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 313	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 314	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 315	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 316	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 317	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, CR }, 	 //	 318	 12000
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 319	 12000
{ AC, AC, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 320	 12000
{ AC, AC, TN, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 321	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 322	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 323	 12000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 324	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 325	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }, 	 //	 326	 12000
{ AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 327	 12000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 328	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, WN, AC, AC }, 	 //	 329	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 330	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, WN, LO, AC }, 	 //	 331	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, CR }, 	 //	 332	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 333	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, SK }, 	 //	 334	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, WN, AC, AC }, 	 //	 335	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 336	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 337	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 338	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, CR }, 	 //	 339	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 340	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, SK }, 	 //	 341	 12000
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 342	 12000
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 343	 12000
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 344	 12000
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 345	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, PF, AC, AC }, 	 //	 346	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 347	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, CR }, 	 //	 348	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, SK }, 	 //	 349	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, PF, AC, AC }, 	 //	 350	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, SK }, 	 //	 351	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, PF, PF, AC }, 	 //	 352	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, CR }, 	 //	 353	 12000
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 354	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, WN, AC, AC }, 	 //	 355	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, CR }, 	 //	 356	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 357	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, WN, LO, AC }, 	 //	 358	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, LO, SK }, 	 //	 359	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, WN, AC, AC }, 	 //	 360	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 361	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 362	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, SK }, 	 //	 363	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, LO, WN, PF, AC }, 	 //	 364	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 365	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, PF, CR }, 	 //	 366	 12000
{ AC, WN, AC, WN, LO, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 367	 12000
{ AC, WN, AC, WN, TN, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 368	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, SK }, 	 //	 369	 12000
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, CR }, 	 //	 370	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, CR }, 	 //	 371	 12000
{ AC, WN, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 372	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, SK }, 	 //	 373	 12000
{ AC, WN, AC, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 374	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, LO, AC, KN, AC, KN, AC }, 	 //	 375	 12000
{ AC, WN, AC, WN, LO, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 376	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, CR }, 	 //	 377	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, SK }, 	 //	 378	 12000
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, CR }, 	 //	 379	 12000
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 380	 12000
{ AC, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 381	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, LO, AC, KN, AC, PF, AC }, 	 //	 382	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, CR }, 	 //	 383	 12000
{ AC, WN, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 384	 12000
{ AC, TN, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 385	 12000
{ AC, TN, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 386	 12000
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 387	 12000
{ AC, TN, SH, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 388	 12000
{ AC, TN, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 389	 12000
{ AC, TN, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 390	 12000
{ AC, TN, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 391	 12000
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 392	 12000
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 393	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 394	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 395	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 396	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 397	 12000
{ AC, TN, TN, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 398	 12000
{ AC, TN, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 399	 12000
{ AC, TN, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 400	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 401	 12000
{ AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 402	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 403	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 404	 12000
{ AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 405	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 406	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 407	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 408	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 409	 12000
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 410	 12000
{ AC, AC, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 411	 12000
{ AC, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 412	 12000
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 413	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 414	 12000
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 415	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 416	 12000
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 417	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 418	 12000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 419	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 420	 12000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 421	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }, 	 //	 422	 12000
{ AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 423	 12000
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 424	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 425	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 426	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, CR }, 	 //	 427	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 428	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 429	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 430	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 431	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 432	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, CR }, 	 //	 433	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 434	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, SK }, 	 //	 435	 12000
{ AC, AC, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 436	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 437	 12000
{ AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 438	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 439	 12000
{ AC, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 440	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 441	 12000
{ AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 442	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 443	 12000
{ AC, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 444	 12000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 445	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 446	 12000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 447	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 448	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }, 	 //	 449	 12000
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 450	 12000
{ AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 451	 12000
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 452	 12000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 453	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 454	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, CR }, 	 //	 455	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 456	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 457	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, SK }, 	 //	 458	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 459	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 460	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 461	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, CR }, 	 //	 462	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 463	 12000
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 464	 12000
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 465	 12000
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 466	 12000
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 467	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 468	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, CR }, 	 //	 469	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, SK }, 	 //	 470	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, PF, LO, AC }, 	 //	 471	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 472	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, LO, CR }, 	 //	 473	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 474	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, LO, SK }, 	 //	 475	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, CR }, 	 //	 476	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 477	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, SK }, 	 //	 478	 12000
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 479	 12000
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 480	 12000
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 481	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, WN, AC, AC }, 	 //	 482	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 483	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, SK }, 	 //	 484	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 485	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 486	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, WN, AC, AC }, 	 //	 487	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 488	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, CR }, 	 //	 489	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 490	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, PF, CR }, 	 //	 491	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 492	 12000
{ AC, KN, AC, PF, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, SK }, 	 //	 493	 12000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 494	 12000
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 495	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, LO, AC, SH, AC, KN, AC }, 	 //	 496	 12000
{ AC, KN, AC, WN, LO, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 497	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, CR }, 	 //	 498	 12000
{ AC, KN, AC, WN, TN, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 499	 12000
{ AC, KN, AC, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, CR }, 	 //	 500	 12000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 501	 12000
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, LO, AC, SH, AC, PF, AC }, 	 //	 502	 12000
{ AC, KN, AC, KN, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 503	 12000
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 504	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, LO, AC, SH, AC, KN, AC }, 	 //	 505	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, SK }, 	 //	 506	 12000
{ AC, KN, AC, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, SK }, 	 //	 507	 12000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 508	 12000
{ AC, KN, AC, KN, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 509	 12000
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, AC, SH, AC, PF, CR }, 	 //	 510	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 511	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 512	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 513	 12000
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 514	 12000
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, AC }, 	 //	 515	 12000
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, AC }, 	 //	 516	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 517	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 518	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 519	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 520	 12000
{ AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 521	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 522	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 523	 12000
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, AC }, 	 //	 524	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 525	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 526	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 527	 12000
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 528	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 529	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 530	 12000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 531	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, AC }, 	 //	 532	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 533	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 534	 12000
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 535	 12000
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 536	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 537	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 538	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 539	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 540	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, LO, AC }, 	 //	 541	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, PF, AC }, 	 //	 542	 12000
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 543	 12000
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 544	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, AC, AC }, 	 //	 545	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, LO, AC }, 	 //	 546	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, AC, AC }, 	 //	 547	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, PF, AC }, 	 //	 548	 12000
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, LO, ST, LO, AC, AC, AC }, 	 //	 549	 12000
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 550	 12000
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, LO, ST, LO, AC, AC, AC }, 	 //	 551	 12000
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 552	 12000
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 553	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, AC, AC }, 	 //	 554	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, AC, AC }, 	 //	 555	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, PF, AC }, 	 //	 556	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, PF, AC }, 	 //	 557	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, ST, KN, AC, KN, AC }, 	 //	 558	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, ST, KN, AC, PF, AC }, 	 //	 559	 12000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, ST, KN, AC, PF, AC }, 	 //	 560	 12000
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, ST, KN, AC, AC, AC }, 	 //	 561	 12000
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, ST, KN, AC, KN, AC }, 	 //	 562	 12000
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, ST, KN, AC, AC, AC }, 	 //	 563	 12000
{ AC, TN, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 564	 12000
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 565	 12000
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 566	 12000
{ AC, TN, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, AC }, 	 //	 567	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 568	 12000
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 569	 12000
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, AC }, 	 //	 570	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 571	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 572	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 573	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 574	 12000
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 575	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 576	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 577	 12000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 578	 12000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 579	 12000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 580	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, AC }, 	 //	 581	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 582	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 583	 12000
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 584	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 585	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 586	 12000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 587	 12000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 588	 12000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 589	 12000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 590	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 591	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 592	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, LO, AC }, 	 //	 593	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 594	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 595	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, PF, AC }, 	 //	 596	 12000
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 597	 12000
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, LO, ST, PF, AC, AC, AC }, 	 //	 598	 12000
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 599	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, PF, AC, AC }, 	 //	 600	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, PF, LO, AC }, 	 //	 601	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, PF, AC, AC }, 	 //	 602	 12000
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 603	 12000
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, LO, ST, PF, AC, AC, AC }, 	 //	 604	 12000
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 605	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, AC, AC }, 	 //	 606	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, AC, AC }, 	 //	 607	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, LO, AC }, 	 //	 608	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, AC, AC }, 	 //	 609	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, AC, AC }, 	 //	 610	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, ST, SH, AC, KN, AC }, 	 //	 611	 12000
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, ST, SH, AC, PF, AC }, 	 //	 612	 12000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, ST, SH, AC, KN, AC }, 	 //	 613	 12000
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, ST, SH, AC, PF, AC }, 	 //	 614	 12000
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 615	 12000
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 616	 12000
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 617	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 618	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 619	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 620	 12000
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 621	 12000
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 622	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 623	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 624	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 625	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 626	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 627	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 628	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 629	 12000
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 630	 12000
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 631	 12000
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 632	 12000
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 633	 12000
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 634	 12000
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 635	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 636	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 637	 12000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 638	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 639	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 640	 12000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 641	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 642	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 643	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 644	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 645	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 646	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 647	 12000
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 648	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 649	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 650	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 651	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 652	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 653	 12000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 654	 12000
{ ST, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 655	 12000
{ ST, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 656	 12000
{ ST, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 657	 12000
{ ST, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 658	 12000
{ KN, LO, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 659	 12000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 660	 12000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 661	 12000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 662	 12000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 663	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 664	 12000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 665	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 666	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 667	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, SK }, 	 //	 668	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, CR }, 	 //	 669	 12000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 670	 12000
{ KN, KN, KN, PF, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 671	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 672	 12000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 673	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 674	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, CR }, 	 //	 675	 12000
{ KN, KN, KN, LO, CR, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 676	 12000
{ KN, KN, KN, LO, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 677	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 678	 12000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 679	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 680	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, CR }, 	 //	 681	 12000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 682	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 683	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 684	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 685	 12000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 686	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 687	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, WN, KN }, 	 //	 688	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, SK, KN }, 	 //	 689	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, SK, KN }, 	 //	 690	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, SK, KN }, 	 //	 691	 12000
{ KN, PF, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 692	 12000
{ KN, PF, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 693	 12000
{ KN, PF, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 694	 12000
{ KN, PF, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 695	 12000
{ KN, PF, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 696	 12000
{ KN, KN, KN, LO, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 697	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 698	 12000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 699	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, SK }, 	 //	 700	 12000
{ KN, KN, KN, PF, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 701	 12000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 702	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 703	 12000
{ KN, KN, KN, LO, CR, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 704	 12000
{ KN, KN, KN, LO, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 705	 12000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 706	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 707	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 708	 12000
{ KN, KN, KN, PF, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 709	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 710	 12000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 711	 12000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 712	 12000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 713	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 714	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, WN, KN }, 	 //	 715	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, WN, KN }, 	 //	 716	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, SK, KN }, 	 //	 717	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, SK, KN }, 	 //	 718	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, WN, KN }, 	 //	 719	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, WN, KN }, 	 //	 720	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, SK, KN }, 	 //	 721	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, SK, KN }, 	 //	 722	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 723	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 724	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 725	 12000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 726	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 727	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 728	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 729	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 730	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 731	 12000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 732	 12000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 733	 12000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 734	 12000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 735	 12000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 736	 12000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 737	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 738	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 739	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 740	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, LO, AC, AC, AC }, 	 //	 741	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 742	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 743	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 744	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 745	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 746	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 747	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 748	 12000
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 749	 12000
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 750	 12000
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 751	 12000
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 752	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 753	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, PF, AC, AC, AC }, 	 //	 754	 12000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, PF, AC, AC, AC }, 	 //	 755	 12000
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 756	 12000
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 757	 12000
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 758	 12000
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 759	 12000
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 760	 12000
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 761	 12000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 762	 12000
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 763	 12000
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 764	 12000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 765	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 766	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 767	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 768	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 769	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 770	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 771	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 772	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 773	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 774	 12000
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 775	 12000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 776	 12000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 777	 12000
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 778	 12000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 779	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 780	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 781	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 782	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 783	 12000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 784	 12000
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 785	 12000
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 786	 12000
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 787	 12000
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 788	 12000
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 789	 12000
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 790	 12000
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 791	 12000
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 792	 12000
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 793	 12000
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 794	 12000
{ AC, WN, AC, AC, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 795	 12000
{ AC, WN, AC, AC, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 796	 12000
{ AC, WN, AC, AC, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 797	 12000
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 798	 12000
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 799	 12000
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 800	 12000
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 801	 12000
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 802	 12000
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 803	 12000
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 804	 12000
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 805	 12000
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 806	 12000
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 807	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 808	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 809	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 810	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 811	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 812	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 813	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 814	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 815	 12000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 816	 12000
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 817	 12000
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 818	 12000
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 819	 12000
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 820	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 821	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 822	 12000
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 823	 12000
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 824	 12000
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 825	 12000
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 826	 12000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 827	 12000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 828	 12000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 829	 12000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 830	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 831	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 832	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 833	 12000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, PF, AC, AC, AC }, 	 //	 834	 12000
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 835	 12000
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 836	 12000
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 837	 12000
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 838	 12000
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 839	 12000
{ TN, SH, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 840	 12000
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 841	 12000
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 842	 12000
{ TN, SH, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 843	 12000
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 844	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 845	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 846	 12000
{ TN, SH, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 847	 12000
{ TN, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 848	 12000
{ TN, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 849	 12000
{ TN, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 850	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 851	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 852	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 853	 12000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 854	 12000
{ TN, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 855	 12000
{ TN, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 856	 12000
{ TN, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 857	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 858	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 859	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 860	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 861	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 862	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 863	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 864	 12000
{ TN, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 865	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 866	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 867	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 868	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 869	 12000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 870	 12000
{ TN, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 871	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 872	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 873	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 874	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 875	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 876	 12000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 877	 12000
{ TN, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 878	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 879	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 880	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 881	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 882	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 883	 12000
{ TN, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 884	 12000
{ TN, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 885	 12000
{ TN, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 886	 12000
{ TN, WN, AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 887	 12000
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 888	 12000
{ TN, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 889	 12000
{ TN, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 890	 12000
{ TN, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 891	 12000
{ TN, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 892	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 893	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 894	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 895	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 896	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 897	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 898	 12000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 899	 12000
{ TN, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 900	 12000
{ TN, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 901	 12000
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 902	 12000
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 903	 12000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 904	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 905	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 906	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 907	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 908	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 909	 12000
{ TN, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 910	 12000
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 911	 12000
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 912	 12000
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 913	 12000
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 914	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 915	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 916	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 917	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 918	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 919	 12000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 920	 12000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 921	 12000
{ TN, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 922	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 923	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 924	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 925	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 926	 12000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 927	 12000
{ TN, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 928	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 929	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 930	 12000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 931	 12000
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 932	 12000
{ TN, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 933	 12000
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 934	 12000
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 935	 12000
{ TN, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 936	 12000
{ TN, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 937	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 938	 12000
{ AC, SH, SH, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 939	 12000
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 940	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 941	 12000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 942	 12000
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 943	 12000
{ AC, SH, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 944	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 945	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 946	 12000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 947	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 948	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 949	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 950	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 951	 12000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 952	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 953	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 954	 12000
{ AC, SH, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 955	 12000
{ AC, SH, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 956	 12000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 957	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 958	 12000
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 959	 12000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 960	 12000
{ AC, AC, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 961	 12000
{ AC, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 962	 12000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 963	 12000
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 964	 12000
{ AC, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 965	 12000
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 966	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 967	 12000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 968	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 969	 12000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 970	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }, 	 //	 971	 12000
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 972	 12000
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 973	 12000
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 974	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 975	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 976	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 977	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 978	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 979	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, LO, AC }, 	 //	 980	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 981	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 982	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 983	 12000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 984	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, PF, AC }, 	 //	 985	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, CR }, 	 //	 986	 12000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 987	 12000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, SK }, 	 //	 988	 12000
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 989	 12000
{ AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 990	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 991	 12000
{ AC, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 992	 12000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 993	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 994	 12000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 995	 12000
{ AC, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 996	 12000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 997	 12000
{ AC, AC, AC, WN, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 998	 12000
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 999	 12000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO }};	 //	 1000	 12000
