unsigned char L5_Outcome_8500[1000][15]={	 //	 0	 8500
{ AC, AC, AC, AC, AC, LO, SH, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 1	 8500
{ AC, SH, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 2	 8500
{ AC, SH, SH, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 3	 8500
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 4	 8500
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 5	 8500
{ AC, SH, TN, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 6	 8500
{ AC, SH, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 7	 8500
{ AC, SH, TN, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 8	 8500
{ AC, SH, TN, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 9	 8500
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 10	 8500
{ AC, AC, SH, TN, TN, LO, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 11	 8500
{ AC, AC, SH, TN, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 12	 8500
{ AC, AC, AC, WN, KN, LO, AC, AC, AC, SK, AC, AC, AC, KN, QN }, 	 //	 13	 8500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, SH, AC, AC, AC, PF, JA }, 	 //	 14	 8500
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 15	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, PF, AC, QN }, 	 //	 16	 8500
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 17	 8500
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 18	 8500
{ AC, AC, AC, WN, PF, LO, AC, AC, AC, JA, AC, AC, AC, KN, TN }, 	 //	 19	 8500
{ AC, AC, AC, WN, SK, LO, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 20	 8500
{ AC, AC, AC, KN, JA, LO, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 21	 8500
{ AC, AC, AC, PF, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 22	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, WN, LO, QN }, 	 //	 23	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, WN, LO, KN }, 	 //	 24	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, WN, AC, KN }, 	 //	 25	 8500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, WN, PF, AC }, 	 //	 26	 8500
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, LO, PF, LO, AC }, 	 //	 27	 8500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, LO, PF, AC, AC }, 	 //	 28	 8500
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 29	 8500
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 30	 8500
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, LO, WN, LO, AC }, 	 //	 31	 8500
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 32	 8500
{ AC, WN, AC, WN, TN, LO, AC, AC, AC, ST, AC, KN, AC, KN, AC }, 	 //	 33	 8500
{ AC, WN, AC, KN, AC, LO, AC, AC, AC, KN, AC, KN, AC, PF, QN }, 	 //	 34	 8500
{ AC, WN, TN, AC, AC, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 35	 8500
{ AC, WN, AC, AC, QN, LO, AC, AC, AC, KN, AC, KN, AC, PF, AC }, 	 //	 36	 8500
{ AC, TN, SH, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 37	 8500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 38	 8500
{ AC, TN, TN, WN, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 39	 8500
{ AC, TN, TN, AC, QN, LO, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 40	 8500
{ AC, TN, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 41	 8500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 42	 8500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 43	 8500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 44	 8500
{ AC, AC, SH, AC, JA, LO, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 45	 8500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 46	 8500
{ AC, AC, AC, PF, TN, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 47	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, PF, AC, KN }, 	 //	 48	 8500
{ AC, AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 49	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, PF, AC, KN }, 	 //	 50	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, PF, PF, KN }, 	 //	 51	 8500
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 52	 8500
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 53	 8500
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 54	 8500
{ AC, AC, AC, WN, KN, LO, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 55	 8500
{ AC, AC, AC, WN, KN, LO, AC, AC, AC, SK, AC, AC, AC, KN, QN }, 	 //	 56	 8500
{ AC, AC, AC, WN, QN, LO, AC, AC, AC, QN, AC, AC, AC, KN, SH }, 	 //	 57	 8500
{ AC, AC, AC, WN, SH, LO, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 58	 8500
{ AC, AC, AC, WN, KN, LO, AC, AC, AC, KN, AC, AC, AC, KN, CR }, 	 //	 59	 8500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, SH, AC, AC, AC, PF, JA }, 	 //	 60	 8500
{ AC, AC, AC, KN, SH, LO, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 61	 8500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC, AC, WN, AC, AC }, 	 //	 62	 8500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, PF, PF, KN, AC }, 	 //	 63	 8500
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 64	 8500
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, ST, AC, PF, WN, AC, AC }, 	 //	 65	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC, PF, WN, AC, QN }, 	 //	 66	 8500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC, PF, WN, AC, QN }, 	 //	 67	 8500
{ AC, KN, AC, PF, AC, LO, AC, AC, AC, SK, AC, SH, AC, AC, KN }, 	 //	 68	 8500
{ AC, KN, AC, AC, JA, LO, AC, AC, AC, TN, AC, SH, AC, LO, AC }, 	 //	 69	 8500
{ AC, KN, AC, TN, AC, LO, AC, AC, AC, KN, AC, SH, AC, AC, QN }, 	 //	 70	 8500
{ AC, KN, AC, AC, AC, LO, AC, AC, AC, AC, AC, SH, PF, LO, AC }, 	 //	 71	 8500
{ AC, KN, AC, AC, AC, LO, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 72	 8500
{ LO, SH, SH, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 73	 8500
{ LO, SH, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 74	 8500
{ LO, SH, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 75	 8500
{ LO, SH, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 76	 8500
{ LO, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 77	 8500
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 78	 8500
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 79	 8500
{ LO, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 80	 8500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 81	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 82	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 83	 8500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN }, 	 //	 84	 8500
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 85	 8500
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 86	 8500
{ LO, AC, TN, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 87	 8500
{ LO, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 88	 8500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, LO, JA }, 	 //	 89	 8500
{ LO, AC, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 90	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 91	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 92	 8500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 93	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, PF, PF }, 	 //	 94	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, WN, AC, AC }, 	 //	 95	 8500
{ LO, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, LO, AC, KN, AC }, 	 //	 96	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, PF, AC, LO }, 	 //	 97	 8500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, LO, PF, LO, KN }, 	 //	 98	 8500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, PF, LO, AC }, 	 //	 99	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, PF, LO, LO }, 	 //	 100	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, PF, PF, LO }, 	 //	 101	 8500
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 102	 8500
{ LO, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, LO, AC, KN, AC }, 	 //	 103	 8500
{ LO, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, LO, AC, AC, KN }, 	 //	 104	 8500
{ LO, AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, LO, AC, AC, LO }, 	 //	 105	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, LO, WN, PF, AC }, 	 //	 106	 8500
{ LO, WN, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 107	 8500
{ LO, WN, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, LO }, 	 //	 108	 8500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, SK }, 	 //	 109	 8500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, SK }, 	 //	 110	 8500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, PF, AC, AC }, 	 //	 111	 8500
{ LO, WN, AC, WN, TN, AC, AC, AC, AC, ST, AC, KN, AC, KN, AC }, 	 //	 112	 8500
{ LO, WN, AC, AC, QN, AC, AC, AC, AC, KN, AC, KN, AC, PF, AC }, 	 //	 113	 8500
{ LO, WN, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, PF, LO }, 	 //	 114	 8500
{ LO, TN, SH, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 115	 8500
{ LO, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 116	 8500
{ LO, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 117	 8500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 118	 8500
{ LO, TN, TN, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 119	 8500
{ LO, TN, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 120	 8500
{ LO, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 121	 8500
{ LO, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 122	 8500
{ LO, AC, SH, PF, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 123	 8500
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 124	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, PF, QN }, 	 //	 125	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 126	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 127	 8500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, LO, KN }, 	 //	 128	 8500
{ LO, AC, TN, PF, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 129	 8500
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 130	 8500
{ LO, AC, TN, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 131	 8500
{ LO, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 132	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN }, 	 //	 133	 8500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 134	 8500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 135	 8500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 136	 8500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 137	 8500
{ LO, AC, AC, PF, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC, KN }, 	 //	 138	 8500
{ LO, AC, AC, WN, QN, AC, AC, AC, AC, KN, AC, PF, AC, KN, AC }, 	 //	 139	 8500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, PF, LO, KN }, 	 //	 140	 8500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, PF, LO, AC }, 	 //	 141	 8500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, PF, AC, AC }, 	 //	 142	 8500
{ LO, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 143	 8500
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, AC, AC, PF, AC, AC, LO }, 	 //	 144	 8500
{ LO, AC, AC, KN, QN, AC, AC, AC, AC, KN, AC, PF, AC, PF, AC }, 	 //	 145	 8500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, WN, LO, AC }, 	 //	 146	 8500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, WN, PF, AC }, 	 //	 147	 8500
{ LO, KN, AC, AC, ST, AC, AC, AC, AC, AC, AC, SH, AC, LO, KN }, 	 //	 148	 8500
{ LO, KN, AC, AC, JA, AC, AC, AC, AC, TN, AC, SH, AC, LO, AC }, 	 //	 149	 8500
{ LO, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 150	 8500
{ LO, KN, AC, AC, KN, AC, AC, AC, AC, AC, AC, SH, AC, AC, LO }, 	 //	 151	 8500
{ LO, KN, AC, AC, QN, AC, AC, AC, AC, KN, AC, SH, AC, PF, AC }, 	 //	 152	 8500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, PF, CR }, 	 //	 153	 8500
{ AC, AC, AC, AC, TN, AC, SH, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 154	 8500
{ AC, AC, AC, AC, AC, AC, SH, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 155	 8500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 156	 8500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 157	 8500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 158	 8500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 159	 8500
{ AC, SH, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 160	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, SK }, 	 //	 161	 8500
{ AC, AC, SH, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 162	 8500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, QN, AC, AC, AC, AC, SH }, 	 //	 163	 8500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, AC, PF, KN, AC }, 	 //	 164	 8500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, PF, KN, AC }, 	 //	 165	 8500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 166	 8500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 167	 8500
{ AC, AC, TN, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 168	 8500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 169	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, SK, AC, AC, AC, AC, QN }, 	 //	 170	 8500
{ AC, AC, AC, AC, SK, AC, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 171	 8500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, LO, AC, AC, WN, AC, AC }, 	 //	 172	 8500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, ST, AC, AC, WN, PF, AC }, 	 //	 173	 8500
{ AC, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 174	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, CR }, 	 //	 175	 8500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, TN, AC, LO, WN, AC, AC }, 	 //	 176	 8500
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, AC, LO, WN, AC, AC }, 	 //	 177	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, LO, AC, LO, WN, PF, AC }, 	 //	 178	 8500
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, KN, AC, LO, WN, PF, AC }, 	 //	 179	 8500
{ AC, WN, SH, PF, LO, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 180	 8500
{ AC, WN, SH, TN, LO, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 181	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, PF, AC, AC }, 	 //	 182	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, SK }, 	 //	 183	 8500
{ AC, WN, TN, PF, LO, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 184	 8500
{ AC, WN, TN, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 185	 8500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 186	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, CR }, 	 //	 187	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, WN, PF, AC }, 	 //	 188	 8500
{ AC, TN, SH, WN, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 189	 8500
{ AC, TN, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 190	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 191	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 192	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, CR }, 	 //	 193	 8500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 194	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 195	 8500
{ AC, AC, SH, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 196	 8500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 197	 8500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 198	 8500
{ AC, AC, SH, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 199	 8500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, QN, AC, AC, AC, AC, QN }, 	 //	 200	 8500
{ AC, AC, AC, AC, JA, AC, AC, AC, PF, WN, AC, AC, AC, AC, TN }, 	 //	 201	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, LO, AC, AC, PF, KN, AC }, 	 //	 202	 8500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, AC, AC, AC, PF, KN, LO }, 	 //	 203	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 204	 8500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 205	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 206	 8500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, WN, AC, LO }, 	 //	 207	 8500
{ AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, AC, AC, WN, PF, KN }, 	 //	 208	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, SK }, 	 //	 209	 8500
{ AC, AC, SH, PF, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 210	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, PF, KN, SK }, 	 //	 211	 8500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, PF, PF, AC, AC }, 	 //	 212	 8500
{ AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 213	 8500
{ AC, AC, TN, TN, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 214	 8500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, SK }, 	 //	 215	 8500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, ST, AC, PF, WN, KN, AC }, 	 //	 216	 8500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, PF, WN, KN, AC }, 	 //	 217	 8500
{ AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, PF, WN, AC, KN }, 	 //	 218	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, SK }, 	 //	 219	 8500
{ AC, KN, TN, PF, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 220	 8500
{ AC, KN, TN, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 221	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, LO, CR }, 	 //	 222	 8500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 223	 8500
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 224	 8500
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 225	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, AC }, 	 //	 226	 8500
{ AC, SH, TN, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 227	 8500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 228	 8500
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, SK, ST, AC, AC, KN, KN }, 	 //	 229	 8500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 230	 8500
{ AC, AC, SH, PF, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 231	 8500
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 232	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, QN, ST, AC, AC, AC, PF }, 	 //	 233	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 234	 8500
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 235	 8500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 236	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, PF, AC, KN }, 	 //	 237	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 238	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 239	 8500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 240	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 241	 8500
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 242	 8500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 243	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, WN, AC, LO }, 	 //	 244	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, WN, LO, KN }, 	 //	 245	 8500
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 246	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, ST, LO, PF, PF, AC }, 	 //	 247	 8500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, ST, LO, AC, AC, AC }, 	 //	 248	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, LO, WN, AC, LO }, 	 //	 249	 8500
{ AC, WN, SH, PF, TN, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 250	 8500
{ AC, WN, AC, WN, ST, AC, AC, AC, AC, AC, ST, KN, AC, KN, KN }, 	 //	 251	 8500
{ AC, WN, AC, KN, KN, AC, AC, AC, AC, AC, ST, KN, AC, PF, LO }, 	 //	 252	 8500
{ AC, WN, AC, AC, KN, AC, AC, AC, AC, AC, ST, KN, AC, LO, LO }, 	 //	 253	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, ST, KN, WN, AC, AC }, 	 //	 254	 8500
{ AC, TN, SH, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 255	 8500
{ AC, TN, SH, TN, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 256	 8500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 257	 8500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, PF, LO }, 	 //	 258	 8500
{ AC, TN, AC, KN, AC, AC, AC, AC, AC, KN, ST, AC, AC, PF, QN }, 	 //	 259	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 260	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, AC }, 	 //	 261	 8500
{ AC, TN, TN, PF, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 262	 8500
{ AC, TN, TN, AC, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 263	 8500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 264	 8500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, AC, LO, LO }, 	 //	 265	 8500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, KN, ST, AC, AC, KN, QN }, 	 //	 266	 8500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 267	 8500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 268	 8500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 269	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, SK }, 	 //	 270	 8500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 271	 8500
{ AC, AC, AC, PF, WN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 272	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 273	 8500
{ AC, AC, AC, TN, SH, AC, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 274	 8500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, ST, AC, PF, KN, AC }, 	 //	 275	 8500
{ AC, AC, TN, TN, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 276	 8500
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 277	 8500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 278	 8500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 279	 8500
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 280	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, AC }, 	 //	 281	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, AC, WN, PF, LO }, 	 //	 282	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, ST, PF, PF, LO, LO }, 	 //	 283	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, ST, PF, WN, KN, AC }, 	 //	 284	 8500
{ AC, KN, AC, AC, ST, AC, AC, AC, AC, AC, ST, SH, AC, AC, KN }, 	 //	 285	 8500
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, SK, ST, SH, AC, KN, KN }, 	 //	 286	 8500
{ AC, KN, AC, WN, KN, AC, AC, AC, AC, AC, ST, SH, AC, KN, LO }, 	 //	 287	 8500
{ AC, KN, AC, AC, KN, AC, AC, AC, AC, AC, ST, SH, AC, PF, LO }, 	 //	 288	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, ST, SH, PF, AC, AC }, 	 //	 289	 8500
{ AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, ST, SH, AC, AC, AC }, 	 //	 290	 8500
{ AC, KN, TN, TN, LO, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 291	 8500
{ AC, KN, AC, PF, ST, AC, AC, AC, AC, AC, ST, SH, AC, AC, KN }, 	 //	 292	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, ST, SH, WN, LO, AC }, 	 //	 293	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, ST, SH, WN, AC, AC }, 	 //	 294	 8500
{ AC, SH, SH, TN, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 295	 8500
{ AC, SH, TN, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 296	 8500
{ AC, AC, SH, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 297	 8500
{ AC, AC, AC, PF, ST, ST, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 298	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 299	 8500
{ AC, AC, AC, AC, CR, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 300	 8500
{ AC, AC, AC, AC, JA, ST, AC, AC, AC, WN, KN, AC, AC, AC, TN }, 	 //	 301	 8500
{ AC, AC, TN, TN, AC, ST, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 302	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, PF, AC, KN, AC, AC, AC, AC }, 	 //	 303	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 304	 8500
{ AC, AC, AC, AC, SK, ST, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 305	 8500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, PF, KN, AC, AC, AC, JA }, 	 //	 306	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, WN, AC, CR }, 	 //	 307	 8500
{ AC, AC, SH, PF, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 308	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, LO, KN, LO, PF, LO, AC }, 	 //	 309	 8500
{ AC, AC, TN, AC, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 310	 8500
{ AC, AC, TN, AC, AC, ST, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 311	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, LO, WN, AC, CR }, 	 //	 312	 8500
{ AC, WN, SH, AC, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 313	 8500
{ AC, WN, AC, WN, AC, ST, AC, AC, AC, AC, KN, KN, AC, KN, CR }, 	 //	 314	 8500
{ AC, WN, TN, TN, AC, ST, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 315	 8500
{ AC, WN, AC, KN, AC, ST, AC, AC, AC, LO, KN, KN, AC, PF, AC }, 	 //	 316	 8500
{ AC, TN, SH, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 317	 8500
{ AC, TN, AC, WN, AC, ST, AC, AC, AC, LO, KN, AC, AC, KN, AC }, 	 //	 318	 8500
{ AC, TN, AC, KN, AC, ST, AC, AC, AC, AC, KN, AC, AC, PF, CR }, 	 //	 319	 8500
{ AC, TN, TN, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 320	 8500
{ AC, TN, AC, KN, AC, ST, AC, AC, AC, AC, KN, AC, AC, PF, SK }, 	 //	 321	 8500
{ AC, AC, SH, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 322	 8500
{ AC, AC, AC, AC, CR, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 323	 8500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 324	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 325	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 326	 8500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 327	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, PF, AC, CR }, 	 //	 328	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, LO, KN, AC, PF, LO, AC }, 	 //	 329	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, PF, PF, SK }, 	 //	 330	 8500
{ AC, AC, AC, PF, ST, ST, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 331	 8500
{ AC, AC, AC, PF, KN, ST, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 332	 8500
{ AC, AC, AC, AC, CR, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 333	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 334	 8500
{ AC, AC, AC, AC, SK, ST, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 335	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, QN, KN, AC, AC, AC, PF }, 	 //	 336	 8500
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 337	 8500
{ AC, AC, AC, AC, SK, ST, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 338	 8500
{ AC, AC, AC, AC, JA, ST, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 339	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, WN, AC, CR }, 	 //	 340	 8500
{ AC, AC, SH, TN, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 341	 8500
{ AC, AC, SH, AC, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 342	 8500
{ AC, AC, AC, PF, TN, ST, AC, AC, AC, ST, KN, PF, AC, AC, AC }, 	 //	 343	 8500
{ AC, AC, TN, PF, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 344	 8500
{ AC, AC, TN, TN, AC, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 345	 8500
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, PF, WN, AC, SK }, 	 //	 346	 8500
{ ST, AC, AC, AC, AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 347	 8500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 348	 8500
{ ST, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 349	 8500
{ ST, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 350	 8500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 351	 8500
{ ST, AC, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 352	 8500
{ ST, AC, AC, AC, JA, KN, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 353	 8500
{ ST, AC, AC, AC, JA, KN, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 354	 8500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 355	 8500
{ ST, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 356	 8500
{ KN, AC, AC, AC, AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 357	 8500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 358	 8500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 359	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 360	 8500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 361	 8500
{ KN, AC, AC, AC, AC, KN, SH, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 362	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, SK, AC, AC, AC, AC }, 	 //	 363	 8500
{ KN, AC, AC, AC, JA, KN, AC, AC, AC, TN, SK, AC, AC, AC, AC }, 	 //	 364	 8500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, SK, AC, AC, AC, QN }, 	 //	 365	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, LO, AC, AC, AC }, 	 //	 366	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, SK, AC, AC, AC, AC }, 	 //	 367	 8500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 368	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, SK, AC, AC, AC, AC }, 	 //	 369	 8500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, SK, AC, AC, AC, AC }, 	 //	 370	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, PF, AC, AC, AC }, 	 //	 371	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, PF, AC, AC, AC }, 	 //	 372	 8500
{ KN, AC, AC, AC, AC, SK, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 373	 8500
{ KN, AC, AC, AC, QN, SK, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 374	 8500
{ KN, AC, AC, AC, LO, SK, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 375	 8500
{ KN, TN, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 376	 8500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, KN, QN, AC, AC, AC, QN }, 	 //	 377	 8500
{ KN, AC, AC, AC, TN, SK, AC, AC, AC, ST, QN, AC, AC, AC, AC }, 	 //	 378	 8500
{ KN, AC, AC, AC, JA, SK, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 379	 8500
{ KN, AC, AC, AC, QN, SK, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 380	 8500
{ KN, AC, AC, AC, LO, SK, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 381	 8500
{ SK, AC, AC, AC, AC, QN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 382	 8500
{ SK, AC, AC, AC, AC, QN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 383	 8500
{ SK, SH, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 384	 8500
{ SK, SH, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 385	 8500
{ SK, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 386	 8500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, SK, QN, AC, AC, AC, KN }, 	 //	 387	 8500
{ SK, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 388	 8500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN, AC, AC, AC, QN }, 	 //	 389	 8500
{ SK, AC, AC, AC, TN, QN, AC, AC, AC, ST, QN, AC, AC, AC, AC }, 	 //	 390	 8500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 391	 8500
{ QN, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 392	 8500
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 393	 8500
{ QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 394	 8500
{ QN, AC, AC, AC, AC, QN, SH, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 395	 8500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, KN, SH, AC, AC, AC, QN }, 	 //	 396	 8500
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, SH, LO, AC, AC, AC }, 	 //	 397	 8500
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, LO, SH, KN, AC, AC, AC }, 	 //	 398	 8500
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, LO, SH, KN, AC, AC, AC }, 	 //	 399	 8500
{ QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, CR }, 	 //	 400	 8500
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, ST, SH, AC, AC, AC, AC }, 	 //	 401	 8500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, TN, SH, AC, AC, AC, AC }, 	 //	 402	 8500
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, ST, SH, AC, AC, AC, AC }, 	 //	 403	 8500
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, SH, PF, AC, AC, AC }, 	 //	 404	 8500
{ QN, KN, AC, AC, AC, QN, AC, AC, AC, LO, SH, SH, AC, AC, AC }, 	 //	 405	 8500
{ QN, AC, AC, AC, AC, SH, SH, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 406	 8500
{ QN, AC, AC, AC, AC, SH, SH, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 407	 8500
{ QN, AC, AC, AC, AC, SH, SH, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 408	 8500
{ QN, SH, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 409	 8500
{ QN, AC, AC, AC, JA, SH, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 410	 8500
{ QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 411	 8500
{ QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 412	 8500
{ QN, AC, AC, AC, JA, SH, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 413	 8500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, KN, JA, AC, AC, AC, QN }, 	 //	 414	 8500
{ SH, AC, AC, AC, AC, JA, SH, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 415	 8500
{ SH, AC, AC, AC, AC, JA, SH, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 416	 8500
{ SH, SH, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 417	 8500
{ SH, SH, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 418	 8500
{ SH, WN, AC, AC, AC, JA, AC, AC, AC, LO, JA, KN, AC, AC, AC }, 	 //	 419	 8500
{ SH, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 420	 8500
{ SH, AC, AC, AC, TN, JA, AC, AC, AC, ST, JA, AC, AC, AC, AC }, 	 //	 421	 8500
{ SH, AC, AC, AC, TN, JA, AC, AC, AC, ST, JA, AC, AC, AC, AC }, 	 //	 422	 8500
{ SH, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC, AC }, 	 //	 423	 8500
{ SH, AC, AC, AC, LO, JA, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 424	 8500
{ SH, KN, AC, AC, AC, JA, AC, AC, AC, LO, JA, SH, AC, AC, AC }, 	 //	 425	 8500
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 426	 8500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC, AC }, 	 //	 427	 8500
{ JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 428	 8500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC, AC }, 	 //	 429	 8500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 430	 8500
{ JA, AC, AC, AC, JA, JA, AC, AC, AC, TN, WN, AC, AC, AC, AC }, 	 //	 431	 8500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, AC, WN, LO, AC, AC, AC }, 	 //	 432	 8500
{ JA, WN, AC, AC, AC, JA, AC, AC, AC, LO, WN, KN, AC, AC, AC }, 	 //	 433	 8500
{ JA, WN, AC, AC, AC, JA, AC, AC, AC, LO, WN, KN, AC, AC, AC }, 	 //	 434	 8500
{ JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 435	 8500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, WN, AC, AC, AC, AC }, 	 //	 436	 8500
{ JA, AC, AC, AC, JA, JA, AC, AC, AC, TN, WN, AC, AC, AC, AC }, 	 //	 437	 8500
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, ST, TN, AC, AC, AC, AC }, 	 //	 438	 8500
{ JA, AC, AC, AC, QN, WN, AC, AC, AC, KN, TN, AC, AC, AC, AC }, 	 //	 439	 8500
{ JA, TN, AC, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 440	 8500
{ JA, AC, AC, AC, JA, WN, AC, AC, AC, TN, TN, AC, AC, AC, AC }, 	 //	 441	 8500
{ JA, AC, AC, AC, AC, WN, AC, AC, AC, SK, TN, AC, AC, AC, KN }, 	 //	 442	 8500
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, ST, TN, AC, AC, AC, AC }, 	 //	 443	 8500
{ JA, KN, AC, AC, AC, WN, AC, AC, AC, LO, TN, SH, AC, AC, AC }, 	 //	 444	 8500
{ WN, AC, AC, AC, AC, TN, SH, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 445	 8500
{ WN, AC, AC, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC, AC }, 	 //	 446	 8500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, SK, TN, AC, AC, AC, KN }, 	 //	 447	 8500
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 448	 8500
{ WN, AC, AC, AC, TN, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 449	 8500
{ WN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 450	 8500
{ WN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 451	 8500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, SK, TN, AC, AC, AC, KN }, 	 //	 452	 8500
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 453	 8500
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 454	 8500
{ WN, KN, AC, AC, AC, TN, AC, AC, AC, LO, TN, SH, AC, AC, AC }, 	 //	 455	 8500
{ TN, AC, AC, AC, AC, TN, SH, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 456	 8500
{ TN, SH, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 457	 8500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN, AC, AC, AC, QN }, 	 //	 458	 8500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, KN, TN, AC, AC, AC, AC }, 	 //	 459	 8500
{ TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 460	 8500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, KN, TN, AC, AC, AC, AC }, 	 //	 461	 8500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, KN, TN, AC, AC, AC, AC }, 	 //	 462	 8500
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 463	 8500
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 464	 8500
{ TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 465	 8500
{ TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 466	 8500
{ TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 467	 8500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 468	 8500
{ TN, AC, AC, AC, JA, TN, AC, AC, AC, TN, ST, AC, AC, AC, AC }, 	 //	 469	 8500
{ TN, SH, SH, PF, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 470	 8500
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 471	 8500
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 472	 8500
{ TN, SH, TN, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 473	 8500
{ TN, AC, AC, AC, CR, ST, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 474	 8500
{ TN, AC, AC, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 475	 8500
{ TN, AC, AC, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 476	 8500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 477	 8500
{ TN, AC, AC, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 478	 8500
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, WN, AC, AC }, 	 //	 479	 8500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 480	 8500
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 481	 8500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 482	 8500
{ TN, WN, AC, AC, LO, ST, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 483	 8500
{ TN, WN, AC, WN, LO, ST, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 484	 8500
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 485	 8500
{ TN, TN, SH, TN, AC, ST, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 486	 8500
{ TN, TN, SH, TN, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 487	 8500
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 488	 8500
{ TN, AC, SH, TN, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 489	 8500
{ TN, AC, AC, AC, SH, ST, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 490	 8500
{ TN, AC, AC, AC, PF, ST, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 491	 8500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 492	 8500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 493	 8500
{ TN, AC, TN, AC, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 494	 8500
{ TN, AC, AC, AC, AC, ST, AC, AC, PF, LO, AC, AC, AC, AC, AC }, 	 //	 495	 8500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 496	 8500
{ TN, AC, AC, AC, ST, ST, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 497	 8500
{ TN, AC, AC, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 498	 8500
{ TN, AC, AC, WN, AC, ST, AC, AC, AC, LO, AC, PF, AC, KN, AC }, 	 //	 499	 8500
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC, PF, WN, AC, AC }, 	 //	 500	 8500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 501	 8500
{ TN, KN, AC, AC, TN, ST, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 502	 8500
{ TN, KN, AC, KN, LO, ST, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 503	 8500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 504	 8500
{ ST, AC, AC, AC, AC, AC, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 505	 8500
{ ST, SH, SH, TN, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 506	 8500
{ ST, SH, AC, KN, TN, AC, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 507	 8500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 508	 8500
{ ST, AC, SH, PF, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 509	 8500
{ ST, AC, SH, TN, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 510	 8500
{ ST, AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 511	 8500
{ ST, AC, AC, WN, LO, AC, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 512	 8500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, AC, PF, LO, AC }, 	 //	 513	 8500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 514	 8500
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, PF, PF, AC }, 	 //	 515	 8500
{ ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 516	 8500
{ ST, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, PF, CR }, 	 //	 517	 8500
{ ST, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, LO, AC, PF, CR }, 	 //	 518	 8500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO, PF, AC, SK }, 	 //	 519	 8500
{ ST, AC, AC, AC, JA, AC, AC, AC, AC, TN, KN, LO, AC, AC, AC }, 	 //	 520	 8500
{ ST, AC, AC, AC, QN, AC, AC, AC, AC, KN, KN, LO, AC, AC, AC }, 	 //	 521	 8500
{ ST, WN, TN, PF, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 522	 8500
{ ST, WN, TN, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 523	 8500
{ ST, WN, AC, WN, AC, AC, AC, AC, AC, AC, KN, KN, AC, KN, SK }, 	 //	 524	 8500
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, WN, AC, AC }, 	 //	 525	 8500
{ ST, WN, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, WN, PF, AC }, 	 //	 526	 8500
{ ST, TN, SH, PF, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 527	 8500
{ ST, TN, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 528	 8500
{ ST, TN, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 529	 8500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 530	 8500
{ ST, TN, TN, AC, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 531	 8500
{ ST, TN, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 532	 8500
{ ST, TN, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 533	 8500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, WN, LO, AC }, 	 //	 534	 8500
{ ST, AC, SH, PF, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 535	 8500
{ ST, AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 536	 8500
{ ST, AC, AC, WN, LO, AC, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 537	 8500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC, SK }, 	 //	 538	 8500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, PF, CR }, 	 //	 539	 8500
{ ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 540	 8500
{ ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 541	 8500
{ ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 542	 8500
{ ST, AC, AC, AC, JA, AC, AC, AC, AC, TN, KN, PF, AC, AC, AC }, 	 //	 543	 8500
{ ST, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC, SK }, 	 //	 544	 8500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, WN, PF, SK }, 	 //	 545	 8500
{ ST, KN, SH, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 546	 8500
{ ST, KN, AC, WN, AC, AC, AC, AC, AC, AC, KN, SH, AC, KN, CR }, 	 //	 547	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, PF, LO, AC }, 	 //	 548	 8500
{ ST, KN, TN, AC, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 549	 8500
{ ST, KN, TN, TN, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 550	 8500
{ ST, KN, AC, WN, LO, AC, AC, AC, AC, AC, KN, SH, AC, KN, AC }, 	 //	 551	 8500
{ ST, KN, AC, TN, AC, AC, AC, AC, AC, AC, KN, SH, AC, AC, SK }, 	 //	 552	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, WN, AC, AC }, 	 //	 553	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, WN, LO, AC }, 	 //	 554	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, WN, LO, AC }, 	 //	 555	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, WN, AC, AC }, 	 //	 556	 8500
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, SH, WN, PF, AC }, 	 //	 557	 8500
{ AC, SH, AC, WN, AC, KN, AC, AC, AC, AC, QN, AC, AC, KN, CR }, 	 //	 558	 8500
{ AC, SH, TN, PF, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 559	 8500
{ AC, SH, AC, KN, AC, KN, AC, AC, AC, AC, QN, AC, AC, PF, SK }, 	 //	 560	 8500
{ AC, AC, SH, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 561	 8500
{ AC, AC, SH, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 562	 8500
{ AC, AC, AC, AC, JA, KN, AC, AC, AC, WN, QN, AC, AC, AC, TN }, 	 //	 563	 8500
{ AC, AC, AC, TN, ST, KN, AC, AC, AC, AC, QN, AC, AC, AC, KN }, 	 //	 564	 8500
{ AC, AC, AC, TN, KN, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO }, 	 //	 565	 8500
{ AC, AC, AC, AC, SK, KN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 566	 8500
{ AC, AC, TN, AC, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 567	 8500
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, WN, PF, CR }, 	 //	 568	 8500
{ AC, AC, AC, TN, JA, KN, AC, AC, AC, TN, QN, LO, AC, AC, AC }, 	 //	 569	 8500
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, LO, PF, AC, CR }, 	 //	 570	 8500
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, LO, PF, PF, CR }, 	 //	 571	 8500
{ AC, AC, TN, TN, AC, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 572	 8500
{ AC, WN, SH, PF, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 573	 8500
{ AC, WN, AC, TN, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, CR }, 	 //	 574	 8500
{ AC, WN, AC, KN, AC, KN, AC, AC, AC, AC, QN, KN, AC, PF, SK }, 	 //	 575	 8500
{ AC, WN, TN, AC, AC, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 576	 8500
{ AC, TN, SH, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 577	 8500
{ AC, TN, SH, AC, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 578	 8500
{ AC, TN, TN, AC, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 579	 8500
{ AC, TN, AC, KN, AC, KN, AC, AC, AC, AC, QN, AC, AC, PF, SK }, 	 //	 580	 8500
{ AC, AC, SH, PF, AC, KN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 581	 8500
{ AC, AC, AC, AC, AC, KN, AC, AC, PF, LO, QN, AC, AC, AC, AC }, 	 //	 582	 8500
{ AC, AC, AC, AC, SK, KN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 583	 8500
{ AC, AC, AC, AC, QN, KN, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 584	 8500
{ AC, AC, AC, AC, CR, KN, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 585	 8500
{ AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN, AC, AC, AC, CR }, 	 //	 586	 8500
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, PF, PF, CR }, 	 //	 587	 8500
{ AC, AC, TN, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 588	 8500
{ AC, AC, TN, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 589	 8500
{ AC, AC, AC, AC, WN, KN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 590	 8500
{ AC, AC, AC, AC, TN, KN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 591	 8500
{ AC, AC, AC, AC, PF, KN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 592	 8500
{ AC, AC, AC, AC, SK, KN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 593	 8500
{ AC, AC, AC, AC, QN, KN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 594	 8500
{ AC, AC, AC, PF, QN, KN, AC, AC, AC, KN, QN, PF, AC, AC, AC }, 	 //	 595	 8500
{ AC, AC, AC, TN, TN, KN, AC, AC, AC, ST, QN, PF, AC, AC, AC }, 	 //	 596	 8500
{ AC, AC, AC, TN, QN, KN, AC, AC, AC, KN, QN, PF, AC, AC, AC }, 	 //	 597	 8500
{ AC, KN, AC, WN, AC, KN, AC, AC, AC, AC, QN, SH, AC, KN, CR }, 	 //	 598	 8500
{ AC, KN, TN, TN, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 599	 8500
{ AC, KN, AC, TN, AC, KN, AC, AC, AC, AC, QN, SH, AC, AC, CR }, 	 //	 600	 8500
{ KN, AC, AC, AC, TN, QN, AC, AC, AC, ST, PF, AC, AC, AC, AC }, 	 //	 601	 8500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, KN, PF, AC, AC, AC, QN }, 	 //	 602	 8500
{ KN, WN, AC, AC, AC, QN, AC, AC, AC, LO, PF, KN, AC, AC, AC }, 	 //	 603	 8500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, KN, PF, AC, AC, AC, QN }, 	 //	 604	 8500
{ KN, AC, AC, AC, LO, QN, AC, AC, AC, AC, PF, PF, AC, AC, AC }, 	 //	 605	 8500
{ KN, KN, AC, AC, AC, QN, AC, AC, AC, LO, PF, SH, AC, AC, AC }, 	 //	 606	 8500
{ QN, AC, AC, AC, JA, PF, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 607	 8500
{ QN, WN, AC, AC, AC, PF, AC, AC, AC, LO, JA, KN, AC, AC, AC }, 	 //	 608	 8500
{ QN, TN, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 609	 8500
{ QN, AC, AC, AC, AC, PF, AC, AC, AC, KN, JA, AC, AC, AC, QN }, 	 //	 610	 8500
{ QN, AC, AC, AC, LO, PF, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 611	 8500
{ QN, AC, AC, AC, TN, PF, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 612	 8500
{ QN, KN, AC, AC, AC, PF, AC, AC, AC, LO, JA, SH, AC, AC, AC }, 	 //	 613	 8500
{ PF, AC, AC, AC, AC, JA, SH, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 614	 8500
{ PF, SH, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 615	 8500
{ PF, AC, AC, AC, TN, JA, AC, AC, AC, ST, TN, AC, AC, AC, AC }, 	 //	 616	 8500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, SK, TN, AC, AC, AC, KN }, 	 //	 617	 8500
{ PF, AC, AC, AC, JA, JA, AC, AC, AC, TN, TN, AC, AC, AC, AC }, 	 //	 618	 8500
{ PF, TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 619	 8500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, KN, TN, AC, AC, AC, QN }, 	 //	 620	 8500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, KN, TN, AC, AC, AC, QN }, 	 //	 621	 8500
{ PF, AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 622	 8500
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 623	 8500
{ JA, AC, AC, AC, CR, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 624	 8500
{ JA, AC, AC, AC, SH, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 625	 8500
{ JA, AC, AC, AC, CR, TN, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 626	 8500
{ JA, AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 627	 8500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 628	 8500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 629	 8500
{ JA, AC, AC, AC, SH, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 630	 8500
{ JA, AC, AC, AC, JA, TN, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 631	 8500
{ JA, AC, AC, AC, PF, TN, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 632	 8500
{ JA, AC, AC, AC, SH, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 633	 8500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 634	 8500
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, LO, PF, LO, AC }, 	 //	 635	 8500
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, LO, PF, PF, AC }, 	 //	 636	 8500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 637	 8500
{ JA, AC, AC, WN, AC, TN, AC, AC, AC, LO, AC, LO, AC, KN, AC }, 	 //	 638	 8500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 639	 8500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 640	 8500
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, WN, PF, AC }, 	 //	 641	 8500
{ JA, TN, SH, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 642	 8500
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 643	 8500
{ JA, TN, TN, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 644	 8500
{ JA, TN, TN, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 645	 8500
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 646	 8500
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 647	 8500
{ JA, AC, SH, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 648	 8500
{ JA, AC, AC, AC, JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 649	 8500
{ JA, AC, AC, AC, JA, TN, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 650	 8500
{ JA, AC, AC, AC, CR, TN, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 651	 8500
{ JA, AC, AC, AC, ST, TN, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 652	 8500
{ JA, AC, AC, AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 653	 8500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 654	 8500
{ JA, AC, TN, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 655	 8500
{ JA, AC, AC, AC, QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 656	 8500
{ JA, AC, AC, AC, JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 657	 8500
{ JA, AC, AC, AC, QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 658	 8500
{ JA, AC, AC, AC, CR, TN, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 659	 8500
{ JA, AC, AC, KN, LO, TN, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 660	 8500
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC, PF, PF, AC, AC }, 	 //	 661	 8500
{ JA, KN, AC, WN, TN, TN, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 662	 8500
{ JA, KN, AC, AC, LO, TN, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 663	 8500
{ TN, SH, SH, PF, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 664	 8500
{ TN, SH, SH, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 665	 8500
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 666	 8500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, CR }, 	 //	 667	 8500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, SK }, 	 //	 668	 8500
{ TN, SH, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 669	 8500
{ TN, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 670	 8500
{ TN, SH, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 671	 8500
{ TN, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 672	 8500
{ TN, SH, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 673	 8500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 674	 8500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, CR }, 	 //	 675	 8500
{ TN, AC, SH, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 676	 8500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 677	 8500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 678	 8500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, PF, TN }, 	 //	 679	 8500
{ TN, AC, TN, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 680	 8500
{ TN, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 681	 8500
{ TN, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 682	 8500
{ TN, AC, TN, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 683	 8500
{ TN, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 684	 8500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, LO, JA }, 	 //	 685	 8500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 686	 8500
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 687	 8500
{ TN, AC, AC, WN, QN, AC, AC, AC, AC, KN, AC, LO, AC, KN, AC }, 	 //	 688	 8500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, WN, AC, LO }, 	 //	 689	 8500
{ TN, WN, AC, AC, ST, AC, AC, AC, AC, AC, AC, KN, AC, LO, KN }, 	 //	 690	 8500
{ TN, WN, AC, KN, KN, AC, AC, AC, AC, AC, AC, KN, AC, PF, LO }, 	 //	 691	 8500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, WN, AC, AC }, 	 //	 692	 8500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, WN, PF, AC }, 	 //	 693	 8500
{ TN, TN, SH, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 694	 8500
{ TN, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 695	 8500
{ TN, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 696	 8500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, SK }, 	 //	 697	 8500
{ TN, AC, SH, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 698	 8500
{ TN, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 699	 8500
{ TN, AC, SH, TN, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 700	 8500
{ TN, AC, SH, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 701	 8500
{ TN, AC, SH, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 702	 8500
{ TN, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 703	 8500
{ TN, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 704	 8500
{ TN, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 705	 8500
{ TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 706	 8500
{ TN, AC, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 707	 8500
{ TN, AC, AC, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, PF, KN }, 	 //	 708	 8500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, PF, LO, AC }, 	 //	 709	 8500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, LO }, 	 //	 710	 8500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, PF, PF, AC }, 	 //	 711	 8500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, PF, KN }, 	 //	 712	 8500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, PF, PF, AC }, 	 //	 713	 8500
{ TN, AC, TN, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 714	 8500
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 715	 8500
{ TN, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 716	 8500
{ TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 717	 8500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 718	 8500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, WN, LO, KN }, 	 //	 719	 8500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, WN, AC, AC }, 	 //	 720	 8500
{ TN, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 721	 8500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, PF, PF, AC, LO }, 	 //	 722	 8500
{ TN, AC, AC, PF, KN, AC, AC, AC, AC, AC, AC, PF, AC, AC, LO }, 	 //	 723	 8500
{ TN, AC, AC, KN, TN, AC, AC, AC, AC, ST, AC, PF, AC, PF, AC }, 	 //	 724	 8500
{ TN, KN, SH, PF, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 725	 8500
{ TN, KN, SH, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 726	 8500
{ TN, KN, AC, AC, ST, AC, AC, AC, AC, AC, AC, SH, AC, LO, KN }, 	 //	 727	 8500
{ TN, KN, AC, AC, ST, AC, AC, AC, AC, AC, AC, SH, AC, PF, KN }, 	 //	 728	 8500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, PF, AC, AC }, 	 //	 729	 8500
{ TN, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 730	 8500
{ TN, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 731	 8500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, WN, AC, AC }, 	 //	 732	 8500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC }, 	 //	 733	 8500
{ AC, SH, SH, KN, LO, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 734	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 735	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, CR }, 	 //	 736	 8500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 737	 8500
{ AC, AC, AC, AC, CR, AC, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 738	 8500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, QN, AC, AC, AC, AC, QN }, 	 //	 739	 8500
{ AC, AC, AC, AC, JA, AC, AC, AC, PF, WN, AC, AC, AC, AC, TN }, 	 //	 740	 8500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, PF, KN, AC }, 	 //	 741	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 742	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, AC, AC, AC, SK }, 	 //	 743	 8500
{ AC, AC, AC, AC, SK, AC, AC, AC, PF, QN, AC, AC, AC, AC, QN }, 	 //	 744	 8500
{ AC, AC, AC, AC, TN, AC, AC, AC, PF, TN, AC, AC, AC, AC, ST }, 	 //	 745	 8500
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, AC, AC, AC, WN, PF, LO }, 	 //	 746	 8500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, LO, AC, LO, AC, AC, AC }, 	 //	 747	 8500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, ST, AC, LO, PF, AC, AC }, 	 //	 748	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, PF, KN, SK }, 	 //	 749	 8500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, LO, PF, AC, AC }, 	 //	 750	 8500
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, AC, LO, PF, AC, AC }, 	 //	 751	 8500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, LO, AC, AC, AC }, 	 //	 752	 8500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, LO, WN, AC, AC }, 	 //	 753	 8500
{ AC, WN, TN, AC, LO, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 754	 8500
{ AC, TN, SH, WN, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 755	 8500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 756	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 757	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 758	 8500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 759	 8500
{ AC, AC, SH, WN, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 760	 8500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 761	 8500
{ AC, AC, SH, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 762	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, AC, AC, AC, SK }, 	 //	 763	 8500
{ AC, AC, AC, AC, TN, AC, AC, AC, PF, TN, AC, AC, AC, AC, ST }, 	 //	 764	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 765	 8500
{ AC, AC, AC, AC, CR, AC, AC, AC, PF, QN, AC, AC, AC, AC, KN }, 	 //	 766	 8500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 767	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, LO }, 	 //	 768	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, SK }, 	 //	 769	 8500
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, TN, AC, AC, PF, PF, AC }, 	 //	 770	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, SK }, 	 //	 771	 8500
{ AC, AC, TN, WN, LO, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 772	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 773	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, WN, KN, SK }, 	 //	 774	 8500
{ AC, AC, AC, WN, ST, AC, AC, AC, AC, AC, AC, PF, PF, KN, KN }, 	 //	 775	 8500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, PF, WN, AC, LO }, 	 //	 776	 8500
{ AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, AC, PF, WN, PF, KN }, 	 //	 777	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, PF, PF, AC }, 	 //	 778	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, SH, WN, AC, AC }, 	 //	 779	 8500
{ AC, SH, SH, PF, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO }, 	 //	 780	 8500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 781	 8500
{ AC, SH, AC, AC, ST, AC, AC, AC, AC, AC, SK, AC, AC, PF, KN }, 	 //	 782	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, PF, LO, AC }, 	 //	 783	 8500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, KN, SK, AC, AC, AC, QN }, 	 //	 784	 8500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 785	 8500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, WN, PF, AC }, 	 //	 786	 8500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 787	 8500
{ AC, AC, AC, PF, CR, AC, AC, AC, AC, QN, SK, AC, AC, AC, KN }, 	 //	 788	 8500
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, QN, SK, AC, AC, AC, SH }, 	 //	 789	 8500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 790	 8500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 791	 8500
{ AC, AC, TN, AC, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO }, 	 //	 792	 8500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 793	 8500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, QN, SK, AC, AC, AC, PF }, 	 //	 794	 8500
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, SK, AC, WN, LO, KN }, 	 //	 795	 8500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, SK, AC, WN, PF, AC }, 	 //	 796	 8500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, SK, LO, PF, KN, AC }, 	 //	 797	 8500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, SK, LO, PF, AC, AC }, 	 //	 798	 8500
{ AC, AC, TN, AC, LO, AC, AC, AC, AC, AC, SK, LO, AC, AC, AC }, 	 //	 799	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK, LO, WN, AC, QN }, 	 //	 800	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, LO, WN, AC, LO }, 	 //	 801	 8500
{ AC, WN, SH, AC, TN, AC, AC, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 802	 8500
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, SK, SK, KN, AC, KN, KN }, 	 //	 803	 8500
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, KN, SK, KN, AC, PF, QN }, 	 //	 804	 8500
{ AC, WN, TN, AC, LO, AC, AC, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 805	 8500
{ AC, WN, TN, AC, TN, AC, AC, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 806	 8500
{ AC, WN, AC, AC, ST, AC, AC, AC, AC, AC, SK, KN, AC, AC, KN }, 	 //	 807	 8500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, SK, KN, WN, AC, AC }, 	 //	 808	 8500
{ AC, TN, SH, PF, AC, AC, AC, AC, AC, SK, SK, AC, AC, AC, KN }, 	 //	 809	 8500
{ AC, TN, SH, AC, ST, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN }, 	 //	 810	 8500
{ AC, TN, SH, TN, ST, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN }, 	 //	 811	 8500
{ AC, TN, AC, WN, ST, AC, AC, AC, AC, AC, SK, AC, AC, KN, KN }, 	 //	 812	 8500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, KN, SK, AC, AC, KN, QN }, 	 //	 813	 8500
{ AC, TN, AC, WN, KN, AC, AC, AC, AC, AC, SK, AC, AC, KN, LO }, 	 //	 814	 8500
{ AC, TN, AC, KN, ST, AC, AC, AC, AC, AC, SK, AC, AC, PF, KN }, 	 //	 815	 8500
{ AC, TN, AC, KN, AC, AC, AC, AC, AC, SK, SK, AC, AC, PF, KN }, 	 //	 816	 8500
{ AC, TN, AC, WN, KN, AC, AC, AC, AC, AC, SK, AC, AC, KN, LO }, 	 //	 817	 8500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 818	 8500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 819	 8500
{ AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, WN }, 	 //	 820	 8500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 821	 8500
{ AC, AC, AC, TN, CR, AC, AC, AC, AC, QN, SK, AC, AC, AC, KN }, 	 //	 822	 8500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, SK, AC, PF, AC, AC }, 	 //	 823	 8500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, SK, AC, PF, AC, AC }, 	 //	 824	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK, AC, PF, LO, QN }, 	 //	 825	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK, AC, PF, PF, QN }, 	 //	 826	 8500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, SK, AC, PF, PF, AC }, 	 //	 827	 8500
{ AC, AC, TN, AC, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO }, 	 //	 828	 8500
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, SH, SK, AC, AC, AC, JA }, 	 //	 829	 8500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, SK, AC, AC, AC, PF }, 	 //	 830	 8500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 831	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, AC, WN, AC, LO }, 	 //	 832	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK, AC, WN, PF, QN }, 	 //	 833	 8500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, SK, AC, WN, PF, AC }, 	 //	 834	 8500
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, SK, PF, AC, AC, AC }, 	 //	 835	 8500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, SK, PF, PF, KN, AC }, 	 //	 836	 8500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, SK, PF, PF, KN, AC }, 	 //	 837	 8500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, SK, PF, PF, AC, AC }, 	 //	 838	 8500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, SK, PF, AC, AC, AC }, 	 //	 839	 8500
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, SK, PF, WN, LO, KN }, 	 //	 840	 8500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, SK, PF, WN, KN, AC }, 	 //	 841	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK, PF, WN, AC, QN }, 	 //	 842	 8500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, SK, PF, WN, AC, KN }, 	 //	 843	 8500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, PF, WN, AC, LO }, 	 //	 844	 8500
{ AC, KN, SH, AC, LO, AC, AC, AC, AC, AC, SK, SH, AC, AC, AC }, 	 //	 845	 8500
{ AC, KN, SH, AC, TN, AC, AC, AC, AC, AC, SK, SH, AC, AC, AC }, 	 //	 846	 8500
{ AC, KN, AC, AC, KN, AC, AC, AC, AC, AC, SK, SH, AC, AC, LO }, 	 //	 847	 8500
{ AC, KN, AC, WN, KN, AC, AC, AC, AC, AC, SK, SH, AC, KN, LO }, 	 //	 848	 8500
{ AC, KN, TN, TN, LO, AC, AC, AC, AC, AC, SK, SH, AC, AC, AC }, 	 //	 849	 8500
{ AC, KN, AC, AC, ST, AC, AC, AC, AC, AC, SK, SH, AC, AC, KN }, 	 //	 850	 8500
{ AC, KN, AC, AC, KN, AC, AC, AC, AC, AC, SK, SH, AC, LO, LO }, 	 //	 851	 8500
{ AC, KN, AC, TN, ST, AC, AC, AC, AC, AC, SK, SH, AC, AC, KN }, 	 //	 852	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, SK, SH, WN, AC, AC }, 	 //	 853	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, SK, SH, WN, AC, AC }, 	 //	 854	 8500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, SK, SH, WN, PF, AC }, 	 //	 855	 8500
{ AC, SH, SH, TN, AC, SK, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 856	 8500
{ AC, SH, SH, TN, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 857	 8500
{ AC, SH, TN, AC, AC, SK, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 858	 8500
{ AC, AC, SH, PF, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 859	 8500
{ AC, AC, SH, TN, AC, SK, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 860	 8500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 861	 8500
{ AC, AC, AC, AC, QN, SK, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 862	 8500
{ AC, AC, AC, AC, JA, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 863	 8500
{ AC, AC, AC, AC, QN, SK, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 864	 8500
{ AC, AC, AC, AC, SK, SK, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 865	 8500
{ AC, AC, AC, AC, CR, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 866	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN, AC, PF, AC, AC }, 	 //	 867	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, PF, LO, SK }, 	 //	 868	 8500
{ AC, AC, AC, AC, JA, SK, AC, AC, AC, WN, KN, AC, AC, AC, TN }, 	 //	 869	 8500
{ AC, AC, AC, AC, QN, SK, AC, AC, AC, PF, KN, AC, AC, AC, JA }, 	 //	 870	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, WN, AC, SK }, 	 //	 871	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN, AC, WN, PF, AC }, 	 //	 872	 8500
{ AC, AC, SH, PF, AC, SK, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 873	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, LO, PF, AC, SK }, 	 //	 874	 8500
{ AC, AC, TN, AC, AC, SK, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 875	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, LO, WN, AC, SK }, 	 //	 876	 8500
{ AC, WN, SH, PF, AC, SK, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 877	 8500
{ AC, WN, AC, WN, AC, SK, AC, AC, AC, AC, KN, KN, AC, KN, CR }, 	 //	 878	 8500
{ AC, WN, AC, KN, AC, SK, AC, AC, AC, LO, KN, KN, AC, PF, AC }, 	 //	 879	 8500
{ AC, TN, TN, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 880	 8500
{ AC, TN, AC, KN, AC, SK, AC, AC, AC, AC, KN, AC, AC, PF, SK }, 	 //	 881	 8500
{ AC, AC, SH, PF, AC, SK, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 882	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, PF, AC, KN, AC, AC, AC, AC }, 	 //	 883	 8500
{ AC, AC, AC, TN, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 884	 8500
{ AC, AC, AC, AC, QN, SK, AC, AC, AC, QN, KN, AC, AC, AC, SH }, 	 //	 885	 8500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 886	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, PF, AC, CR }, 	 //	 887	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, PF, PF, SK }, 	 //	 888	 8500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 889	 8500
{ AC, AC, AC, AC, JA, SK, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 890	 8500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 891	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN, AC, WN, AC, AC }, 	 //	 892	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, PF, PF, AC, CR }, 	 //	 893	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, PF, PF, AC, SK }, 	 //	 894	 8500
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN, PF, WN, AC, AC }, 	 //	 895	 8500
{ AC, KN, AC, WN, AC, SK, AC, AC, AC, AC, KN, SH, AC, KN, CR }, 	 //	 896	 8500
{ AC, KN, AC, TN, AC, SK, AC, AC, AC, AC, KN, SH, AC, AC, CR }, 	 //	 897	 8500
{ AC, KN, AC, TN, AC, SK, AC, AC, AC, AC, KN, SH, AC, AC, SK }, 	 //	 898	 8500
{ AC, KN, AC, KN, AC, SK, AC, AC, AC, AC, KN, SH, AC, PF, SK }, 	 //	 899	 8500
{ AC, KN, TN, TN, AC, SK, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 900	 8500
{ AC, KN, AC, KN, AC, SK, AC, AC, AC, AC, KN, SH, AC, PF, SK }, 	 //	 901	 8500
{ SK, AC, AC, AC, AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 902	 8500
{ SK, AC, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 903	 8500
{ SK, KN, AC, AC, AC, KN, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 904	 8500
{ KN, AC, AC, AC, AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 905	 8500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 906	 8500
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 907	 8500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 908	 8500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 909	 8500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 910	 8500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 911	 8500
{ KN, AC, AC, AC, AC, KN, SH, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 912	 8500
{ KN, AC, AC, AC, AC, KN, SH, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 913	 8500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, CR }, 	 //	 914	 8500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, LO, WN, KN, AC, AC, AC }, 	 //	 915	 8500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 916	 8500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 917	 8500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, WN, AC, AC, AC, KN }, 	 //	 918	 8500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, WN, AC, AC, AC, AC }, 	 //	 919	 8500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, WN, AC, AC, AC, KN }, 	 //	 920	 8500
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, WN, PF, AC, AC, AC }, 	 //	 921	 8500
{ KN, AC, AC, AC, AC, WN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 922	 8500
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, SK, QN, AC, AC, AC, KN }, 	 //	 923	 8500
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, SK, QN, AC, AC, AC, KN }, 	 //	 924	 8500
{ KN, AC, AC, AC, LO, WN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 925	 8500
{ KN, TN, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 926	 8500
{ KN, AC, AC, AC, QN, WN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 927	 8500
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, KN, QN, AC, AC, AC, QN }, 	 //	 928	 8500
{ KN, AC, AC, AC, TN, WN, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 929	 8500
{ KN, AC, AC, AC, LO, WN, AC, AC, AC, AC, QN, PF, AC, AC, AC }, 	 //	 930	 8500
{ WN, SH, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 931	 8500
{ WN, SH, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 932	 8500
{ WN, AC, AC, AC, JA, QN, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 933	 8500
{ WN, AC, AC, AC, LO, QN, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 934	 8500
{ WN, AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 935	 8500
{ WN, TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 936	 8500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 937	 8500
{ WN, KN, AC, AC, AC, QN, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 938	 8500
{ QN, SH, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 939	 8500
{ QN, SH, TN, AC, AC, KN, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 940	 8500
{ QN, SH, AC, AC, AC, KN, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 941	 8500
{ QN, SH, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 942	 8500
{ QN, AC, AC, AC, KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 943	 8500
{ QN, AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 944	 8500
{ QN, AC, AC, AC, JA, KN, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 945	 8500
{ QN, AC, AC, AC, CR, KN, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 946	 8500
{ QN, AC, AC, AC, QN, KN, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 947	 8500
{ QN, AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 948	 8500
{ QN, AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 949	 8500
{ QN, AC, AC, AC, KN, KN, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 950	 8500
{ QN, AC, AC, AC, LO, KN, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 951	 8500
{ QN, AC, AC, KN, LO, KN, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 952	 8500
{ QN, AC, AC, AC, LO, KN, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 953	 8500
{ QN, AC, AC, WN, LO, KN, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 954	 8500
{ QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC, LO, WN, PF, AC }, 	 //	 955	 8500
{ QN, WN, AC, AC, TN, KN, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 956	 8500
{ QN, WN, AC, AC, TN, KN, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 957	 8500
{ QN, WN, AC, KN, AC, KN, AC, AC, AC, LO, AC, KN, AC, PF, AC }, 	 //	 958	 8500
{ QN, WN, AC, AC, AC, KN, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 959	 8500
{ QN, TN, SH, AC, LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 960	 8500
{ QN, TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 961	 8500
{ QN, TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 962	 8500
{ QN, AC, SH, PF, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 963	 8500
{ QN, AC, AC, AC, CR, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 964	 8500
{ QN, AC, AC, AC, KN, KN, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 965	 8500
{ QN, AC, AC, AC, QN, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 966	 8500
{ QN, AC, AC, AC, QN, KN, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 967	 8500
{ QN, AC, AC, AC, PF, KN, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 968	 8500
{ QN, AC, AC, AC, ST, KN, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 969	 8500
{ QN, AC, AC, AC, SH, KN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 970	 8500
{ QN, AC, AC, AC, SK, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 971	 8500
{ QN, AC, AC, AC, CR, KN, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 972	 8500
{ QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 973	 8500
{ QN, AC, AC, WN, AC, KN, AC, AC, AC, LO, AC, PF, AC, KN, AC }, 	 //	 974	 8500
{ QN, AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 975	 8500
{ QN, AC, AC, KN, AC, KN, AC, AC, AC, LO, AC, PF, AC, PF, AC }, 	 //	 976	 8500
{ QN, AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 977	 8500
{ QN, AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 978	 8500
{ QN, KN, AC, AC, AC, KN, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 979	 8500
{ QN, KN, AC, AC, AC, KN, AC, AC, AC, AC, AC, SH, PF, PF, AC }, 	 //	 980	 8500
{ QN, KN, AC, KN, AC, KN, AC, AC, AC, LO, AC, SH, AC, PF, AC }, 	 //	 981	 8500
{ QN, KN, AC, AC, AC, KN, AC, AC, AC, AC, AC, SH, WN, PF, AC }, 	 //	 982	 8500
{ KN, AC, AC, AC, AC, AC, SH, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 983	 8500
{ KN, AC, AC, AC, AC, AC, SH, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 984	 8500
{ KN, SH, SH, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, CR }, 	 //	 985	 8500
{ KN, SH, AC, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC }, 	 //	 986	 8500
{ KN, SH, AC, KN, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, SK }, 	 //	 987	 8500
{ KN, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC, AC }, 	 //	 988	 8500
{ KN, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC, AC }, 	 //	 989	 8500
{ KN, SH, TN, AC, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 990	 8500
{ KN, SH, TN, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 991	 8500
{ KN, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, WN, AC, AC }, 	 //	 992	 8500
{ KN, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, WN, AC, AC }, 	 //	 993	 8500
{ KN, AC, SH, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 994	 8500
{ KN, AC, SH, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 995	 8500
{ KN, AC, AC, WN, LO, AC, AC, AC, AC, AC, LO, AC, AC, KN, AC }, 	 //	 996	 8500
{ KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC, CR }, 	 //	 997	 8500
{ KN, AC, TN, AC, LO, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC }, 	 //	 998	 8500
{ KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, LO, AC, AC, SK }, 	 //	 999	 8500
{ KN, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, LO, AC, PF, CR }};	 //	 1000	 8500
