#include "ReelDefine.h"

unsigned char L5_Outcome_0360[1000][15]={	 //	 0	 360
{ AC, QN, SK, ST, PF, LO, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 1	 360
{ AC, SK, SK, ST, JA, LO, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 2	 360
{ AC, SK, SK, ST, WN, LO, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 3	 360
{ AC, SK, SK, ST, TN, LO, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 4	 360
{ AC, KN, SK, ST, PF, LO, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 5	 360
{ AC, SK, SK, ST, PF, LO, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 6	 360
{ LO, QN, SK, ST, PF, AC, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 7	 360
{ LO, SK, SK, ST, JA, AC, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 8	 360
{ LO, SK, SK, ST, WN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 9	 360
{ LO, SK, SK, ST, TN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 10	 360
{ LO, KN, SK, ST, PF, AC, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 11	 360
{ LO, SK, SK, ST, PF, AC, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 12	 360
{ AC, QN, SK, ST, PF, AC, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 13	 360
{ AC, SK, SK, ST, JA, AC, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 14	 360
{ AC, SK, SK, ST, WN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 15	 360
{ AC, SK, SK, ST, TN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 16	 360
{ AC, KN, SK, ST, PF, AC, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 17	 360
{ AC, SK, SK, ST, PF, AC, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 18	 360
{ AC, QN, SK, ST, PF, AC, SK, JA, JA, JA, ST, JA, TN, TN, TN }, 	 //	 19	 360
{ AC, SK, SK, ST, JA, AC, JA, JA, JA, WN, ST, JA, TN, TN, TN }, 	 //	 20	 360
{ AC, SK, SK, ST, WN, AC, JA, JA, JA, TN, ST, JA, TN, TN, TN }, 	 //	 21	 360
{ AC, SK, SK, ST, TN, AC, JA, JA, JA, TN, ST, JA, TN, TN, TN }, 	 //	 22	 360
{ AC, KN, SK, ST, PF, AC, SK, JA, JA, JA, ST, QN, TN, TN, TN }, 	 //	 23	 360
{ AC, SK, SK, ST, PF, AC, QN, JA, JA, JA, ST, KN, TN, TN, TN }, 	 //	 24	 360
{ AC, QN, SK, ST, PF, ST, SK, JA, JA, JA, KN, JA, TN, TN, TN }, 	 //	 25	 360
{ AC, SK, SK, ST, JA, ST, JA, JA, JA, WN, KN, JA, TN, TN, TN }, 	 //	 26	 360
{ AC, SK, SK, ST, WN, ST, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 27	 360
{ AC, SK, SK, ST, TN, ST, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 28	 360
{ AC, KN, SK, ST, PF, ST, SK, JA, JA, JA, KN, QN, TN, TN, TN }, 	 //	 29	 360
{ AC, SK, SK, ST, PF, ST, QN, JA, JA, JA, KN, KN, TN, TN, TN }, 	 //	 30	 360
{ ST, QN, SK, ST, PF, KN, SK, JA, JA, JA, KN, JA, TN, TN, TN }, 	 //	 31	 360
{ ST, SK, SK, ST, JA, KN, JA, JA, JA, WN, KN, JA, TN, TN, TN }, 	 //	 32	 360
{ ST, SK, SK, ST, WN, KN, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 33	 360
{ ST, SK, SK, ST, TN, KN, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 34	 360
{ ST, KN, SK, ST, PF, KN, SK, JA, JA, JA, KN, QN, TN, TN, TN }, 	 //	 35	 360
{ ST, SK, SK, ST, PF, KN, QN, JA, JA, JA, KN, KN, TN, TN, TN }, 	 //	 36	 360
{ KN, QN, SK, ST, PF, KN, SK, JA, JA, JA, KN, JA, TN, TN, TN }, 	 //	 37	 360
{ KN, SK, SK, ST, JA, KN, JA, JA, JA, WN, KN, JA, TN, TN, TN }, 	 //	 38	 360
{ KN, SK, SK, ST, WN, KN, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 39	 360
{ KN, SK, SK, ST, TN, KN, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 40	 360
{ KN, KN, SK, ST, PF, KN, SK, JA, JA, JA, KN, QN, TN, TN, TN }, 	 //	 41	 360
{ KN, SK, SK, ST, PF, KN, QN, JA, JA, JA, KN, KN, TN, TN, TN }, 	 //	 42	 360
{ KN, QN, WN, SH, TN, KN, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 43	 360
{ KN, QN, WN, TN, TN, KN, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 44	 360
{ KN, QN, TN, SH, WN, KN, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 45	 360
{ KN, QN, TN, TN, WN, KN, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 46	 360
{ KN, QN, TN, TN, TN, KN, QN, TN, TN, TN, SK, SK, TN, TN, ST }, 	 //	 47	 360
{ KN, QN, TN, TN, TN, KN, QN, TN, TN, TN, SK, SK, TN, WN, ST }, 	 //	 48	 360
{ KN, QN, TN, JA, TN, KN, QN, TN, TN, TN, SK, SK, TN, AC, TN }, 	 //	 49	 360
{ KN, QN, TN, TN, TN, KN, QN, TN, TN, TN, SK, SK, LO, TN, TN }, 	 //	 50	 360
{ KN, QN, TN, TN, TN, KN, QN, TN, TN, TN, SK, SK, LO, WN, TN }, 	 //	 51	 360
{ KN, QN, QN, KN, KN, KN, QN, QN, SK, KN, SK, SK, SK, QN, SK }, 	 //	 52	 360
{ KN, QN, QN, KN, KN, KN, QN, QN, SK, SK, SK, SK, SK, QN, QN }, 	 //	 53	 360
{ KN, QN, QN, KN, AC, KN, QN, QN, SK, AC, SK, SK, SK, QN, SK }, 	 //	 54	 360
{ KN, QN, QN, KN, AC, KN, QN, QN, SK, SK, SK, SK, SK, QN, KN }, 	 //	 55	 360
{ KN, QN, SK, ST, PF, KN, QN, JA, JA, JA, SK, SK, TN, TN, TN }, 	 //	 56	 360
{ KN, QN, WN, SH, TN, KN, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 57	 360
{ KN, QN, WN, TN, TN, KN, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 58	 360
{ KN, QN, TN, SH, WN, KN, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 59	 360
{ KN, QN, TN, TN, WN, KN, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 60	 360
{ KN, QN, TN, TN, TN, KN, SK, TN, TN, TN, SK, JA, TN, TN, ST }, 	 //	 61	 360
{ KN, QN, TN, TN, TN, KN, SK, TN, TN, TN, SK, JA, TN, WN, ST }, 	 //	 62	 360
{ KN, QN, TN, JA, TN, KN, SK, TN, TN, TN, SK, JA, TN, AC, TN }, 	 //	 63	 360
{ KN, QN, TN, TN, TN, KN, SK, TN, TN, TN, SK, JA, LO, TN, TN }, 	 //	 64	 360
{ KN, QN, TN, TN, TN, KN, SK, TN, TN, TN, SK, JA, LO, WN, TN }, 	 //	 65	 360
{ KN, QN, QN, KN, KN, KN, SK, QN, KN, KN, SK, JA, SK, SK, SK }, 	 //	 66	 360
{ KN, QN, QN, KN, AC, KN, SK, QN, KN, AC, SK, JA, SK, SK, SK }, 	 //	 67	 360
{ KN, QN, QN, KN, KN, KN, SK, QN, SK, KN, SK, JA, SK, QN, SK }, 	 //	 68	 360
{ KN, QN, QN, KN, KN, KN, SK, QN, SK, SK, SK, JA, SK, QN, QN }, 	 //	 69	 360
{ KN, QN, QN, KN, AC, KN, SK, QN, SK, AC, SK, JA, SK, QN, SK }, 	 //	 70	 360
{ KN, QN, QN, KN, AC, KN, SK, QN, SK, SK, SK, JA, SK, QN, KN }, 	 //	 71	 360
{ KN, QN, QN, KN, KN, KN, SK, SK, SK, KN, SK, JA, JA, QN, SK }, 	 //	 72	 360
{ KN, QN, QN, KN, SK, KN, SK, SK, SK, QN, SK, JA, JA, QN, QN }, 	 //	 73	 360
{ KN, QN, QN, KN, AC, KN, SK, SK, SK, AC, SK, JA, JA, QN, SK }, 	 //	 74	 360
{ KN, QN, QN, KN, SK, KN, SK, SK, SK, KN, SK, JA, JA, QN, KN }, 	 //	 75	 360
{ KN, SK, SK, ST, JA, KN, JA, JA, JA, WN, SK, JA, TN, TN, TN }, 	 //	 76	 360
{ KN, SK, SK, ST, WN, KN, JA, JA, JA, TN, SK, JA, TN, TN, TN }, 	 //	 77	 360
{ KN, SK, SK, ST, TN, KN, JA, JA, JA, TN, SK, JA, TN, TN, TN }, 	 //	 78	 360
{ KN, KN, WN, SH, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 79	 360
{ KN, KN, WN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 80	 360
{ KN, KN, TN, SH, WN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 81	 360
{ KN, KN, TN, TN, WN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 82	 360
{ KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, ST }, 	 //	 83	 360
{ KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, WN, ST }, 	 //	 84	 360
{ KN, KN, TN, JA, TN, KN, KN, TN, TN, TN, SK, SK, TN, AC, TN }, 	 //	 85	 360
{ KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, LO, TN, TN }, 	 //	 86	 360
{ KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, LO, WN, TN }, 	 //	 87	 360
{ KN, KN, QN, QN, KN, KN, KN, QN, SK, KN, SK, SK, SK, JA, SK }, 	 //	 88	 360
{ KN, KN, QN, QN, KN, KN, KN, QN, SK, SK, SK, SK, SK, JA, QN }, 	 //	 89	 360
{ KN, KN, QN, QN, AC, KN, KN, QN, SK, AC, SK, SK, SK, JA, SK }, 	 //	 90	 360
{ KN, KN, QN, QN, AC, KN, KN, QN, SK, SK, SK, SK, SK, JA, KN }, 	 //	 91	 360
{ KN, KN, QN, KN, KN, KN, KN, QN, SK, KN, SK, SK, SK, QN, SK }, 	 //	 92	 360
{ KN, KN, QN, KN, KN, KN, KN, QN, SK, SK, SK, SK, SK, QN, QN }, 	 //	 93	 360
{ KN, KN, QN, KN, AC, KN, KN, QN, SK, AC, SK, SK, SK, QN, SK }, 	 //	 94	 360
{ KN, KN, QN, KN, AC, KN, KN, QN, SK, SK, SK, SK, SK, QN, KN }, 	 //	 95	 360
{ KN, KN, SK, ST, PF, KN, KN, JA, JA, JA, SK, SK, TN, TN, TN }, 	 //	 96	 360
{ KN, KN, WN, SH, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 97	 360
{ KN, KN, WN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 98	 360
{ KN, KN, TN, SH, WN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 99	 360
{ KN, KN, TN, TN, WN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 100	 360
{ KN, KN, TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, ST }, 	 //	 101	 360
{ KN, KN, TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, WN, ST }, 	 //	 102	 360
{ KN, KN, TN, JA, TN, KN, SK, TN, TN, TN, SK, QN, TN, AC, TN }, 	 //	 103	 360
{ KN, KN, TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, LO, TN, TN }, 	 //	 104	 360
{ KN, KN, TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, LO, WN, TN }, 	 //	 105	 360
{ KN, KN, QN, QN, KN, KN, SK, QN, QN, KN, SK, QN, SK, SK, SK }, 	 //	 106	 360
{ KN, KN, QN, QN, AC, KN, SK, QN, QN, AC, SK, QN, SK, SK, SK }, 	 //	 107	 360
{ KN, KN, QN, QN, KN, KN, SK, QN, SK, KN, SK, QN, SK, JA, SK }, 	 //	 108	 360
{ KN, KN, QN, QN, KN, KN, SK, QN, SK, SK, SK, QN, SK, JA, QN }, 	 //	 109	 360
{ KN, KN, QN, QN, AC, KN, SK, QN, SK, AC, SK, QN, SK, JA, SK }, 	 //	 110	 360
{ KN, KN, QN, QN, AC, KN, SK, QN, SK, SK, SK, QN, SK, JA, KN }, 	 //	 111	 360
{ KN, KN, QN, KN, KN, KN, SK, QN, KN, KN, SK, QN, SK, SK, SK }, 	 //	 112	 360
{ KN, KN, QN, KN, AC, KN, SK, QN, KN, AC, SK, QN, SK, SK, SK }, 	 //	 113	 360
{ KN, KN, QN, KN, KN, KN, SK, QN, SK, KN, SK, QN, SK, QN, SK }, 	 //	 114	 360
{ KN, KN, QN, KN, KN, KN, SK, QN, SK, SK, SK, QN, SK, QN, QN }, 	 //	 115	 360
{ KN, KN, QN, KN, AC, KN, SK, QN, SK, AC, SK, QN, SK, QN, SK }, 	 //	 116	 360
{ KN, KN, QN, KN, AC, KN, SK, QN, SK, SK, SK, QN, SK, QN, KN }, 	 //	 117	 360
{ KN, KN, QN, QN, KN, KN, SK, SK, SK, KN, SK, QN, JA, JA, SK }, 	 //	 118	 360
{ KN, KN, QN, QN, SK, KN, SK, SK, SK, QN, SK, QN, JA, JA, QN }, 	 //	 119	 360
{ KN, KN, QN, QN, AC, KN, SK, SK, SK, AC, SK, QN, JA, JA, SK }, 	 //	 120	 360
{ KN, KN, QN, QN, SK, KN, SK, SK, SK, KN, SK, QN, JA, JA, KN }, 	 //	 121	 360
{ KN, KN, QN, KN, KN, KN, SK, SK, SK, KN, SK, QN, JA, QN, SK }, 	 //	 122	 360
{ KN, KN, QN, KN, SK, KN, SK, SK, SK, QN, SK, QN, JA, QN, QN }, 	 //	 123	 360
{ KN, KN, QN, KN, AC, KN, SK, SK, SK, AC, SK, QN, JA, QN, SK }, 	 //	 124	 360
{ KN, KN, QN, KN, SK, KN, SK, SK, SK, KN, SK, QN, JA, QN, KN }, 	 //	 125	 360
{ KN, SK, SK, ST, PF, KN, QN, JA, JA, JA, SK, KN, TN, TN, TN }, 	 //	 126	 360
{ KN, QN, WN, SH, TN, SK, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 127	 360
{ KN, QN, WN, TN, TN, SK, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 128	 360
{ KN, QN, TN, SH, WN, SK, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 129	 360
{ KN, QN, TN, TN, WN, SK, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 130	 360
{ KN, QN, TN, TN, TN, SK, SK, TN, TN, TN, QN, JA, TN, TN, ST }, 	 //	 131	 360
{ KN, QN, TN, TN, TN, SK, SK, TN, TN, TN, QN, JA, TN, WN, ST }, 	 //	 132	 360
{ KN, QN, TN, JA, TN, SK, SK, TN, TN, TN, QN, JA, TN, AC, TN }, 	 //	 133	 360
{ KN, QN, TN, TN, TN, SK, SK, TN, TN, TN, QN, JA, LO, TN, TN }, 	 //	 134	 360
{ KN, QN, TN, TN, TN, SK, SK, TN, TN, TN, QN, JA, LO, WN, TN }, 	 //	 135	 360
{ KN, QN, QN, KN, KN, SK, SK, QN, KN, KN, QN, JA, SK, SK, SK }, 	 //	 136	 360
{ KN, QN, QN, KN, AC, SK, SK, QN, KN, AC, QN, JA, SK, SK, SK }, 	 //	 137	 360
{ KN, QN, QN, KN, KN, SK, SK, QN, SK, KN, QN, JA, SK, QN, SK }, 	 //	 138	 360
{ KN, QN, QN, KN, KN, SK, SK, QN, SK, SK, QN, JA, SK, QN, QN }, 	 //	 139	 360
{ KN, QN, QN, KN, AC, SK, SK, QN, SK, AC, QN, JA, SK, QN, SK }, 	 //	 140	 360
{ KN, QN, QN, KN, AC, SK, SK, QN, SK, SK, QN, JA, SK, QN, KN }, 	 //	 141	 360
{ KN, QN, SK, QN, KN, SK, SK, JA, SK, SK, QN, JA, TN, JA, QN }, 	 //	 142	 360
{ KN, QN, SK, QN, SK, SK, SK, JA, SK, QN, QN, JA, TN, JA, QN }, 	 //	 143	 360
{ KN, QN, SK, QN, AC, SK, SK, JA, SK, SK, QN, JA, TN, JA, KN }, 	 //	 144	 360
{ KN, QN, SK, QN, SK, SK, SK, JA, SK, KN, QN, JA, TN, JA, KN }, 	 //	 145	 360
{ KN, QN, SK, SK, SK, SK, SK, JA, JA, QN, QN, JA, TN, JA, QN }, 	 //	 146	 360
{ KN, QN, SK, SK, SK, SK, SK, JA, JA, KN, QN, JA, TN, JA, KN }, 	 //	 147	 360
{ KN, QN, SK, KN, KN, SK, SK, JA, SK, SK, QN, JA, TN, QN, QN }, 	 //	 148	 360
{ KN, QN, SK, KN, SK, SK, SK, JA, SK, QN, QN, JA, TN, QN, QN }, 	 //	 149	 360
{ KN, QN, SK, KN, AC, SK, SK, JA, SK, SK, QN, JA, TN, QN, KN }, 	 //	 150	 360
{ KN, QN, SK, KN, SK, SK, SK, JA, SK, KN, QN, JA, TN, QN, KN }, 	 //	 151	 360
{ KN, QN, SK, SK, SK, SK, SK, JA, QN, QN, QN, JA, TN, KN, QN }, 	 //	 152	 360
{ KN, QN, SK, SK, SK, SK, SK, JA, QN, KN, QN, JA, TN, KN, KN }, 	 //	 153	 360
{ KN, SK, SK, ST, JA, SK, JA, JA, JA, WN, QN, JA, TN, TN, TN }, 	 //	 154	 360
{ KN, SK, SK, ST, WN, SK, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 155	 360
{ KN, SK, SK, ST, TN, SK, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 156	 360
{ KN, KN, WN, SH, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 157	 360
{ KN, KN, WN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 158	 360
{ KN, KN, TN, SH, WN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 159	 360
{ KN, KN, TN, TN, WN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 160	 360
{ KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, ST }, 	 //	 161	 360
{ KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, WN, ST }, 	 //	 162	 360
{ KN, KN, TN, JA, TN, SK, SK, TN, TN, TN, QN, QN, TN, AC, TN }, 	 //	 163	 360
{ KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, LO, TN, TN }, 	 //	 164	 360
{ KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, LO, WN, TN }, 	 //	 165	 360
{ KN, KN, QN, QN, KN, SK, SK, QN, QN, KN, QN, QN, SK, SK, SK }, 	 //	 166	 360
{ KN, KN, QN, QN, AC, SK, SK, QN, QN, AC, QN, QN, SK, SK, SK }, 	 //	 167	 360
{ KN, KN, QN, QN, KN, SK, SK, QN, SK, KN, QN, QN, SK, JA, SK }, 	 //	 168	 360
{ KN, KN, QN, QN, KN, SK, SK, QN, SK, SK, QN, QN, SK, JA, QN }, 	 //	 169	 360
{ KN, KN, QN, QN, AC, SK, SK, QN, SK, AC, QN, QN, SK, JA, SK }, 	 //	 170	 360
{ KN, KN, QN, QN, AC, SK, SK, QN, SK, SK, QN, QN, SK, JA, KN }, 	 //	 171	 360
{ KN, KN, QN, KN, KN, SK, SK, QN, KN, KN, QN, QN, SK, SK, SK }, 	 //	 172	 360
{ KN, KN, QN, KN, AC, SK, SK, QN, KN, AC, QN, QN, SK, SK, SK }, 	 //	 173	 360
{ KN, KN, QN, KN, KN, SK, SK, QN, SK, KN, QN, QN, SK, QN, SK }, 	 //	 174	 360
{ KN, KN, QN, KN, KN, SK, SK, QN, SK, SK, QN, QN, SK, QN, QN }, 	 //	 175	 360
{ KN, KN, QN, KN, AC, SK, SK, QN, SK, AC, QN, QN, SK, QN, SK }, 	 //	 176	 360
{ KN, KN, QN, KN, AC, SK, SK, QN, SK, SK, QN, QN, SK, QN, KN }, 	 //	 177	 360
{ KN, KN, SK, QN, KN, SK, SK, JA, SK, SK, QN, QN, TN, JA, QN }, 	 //	 178	 360
{ KN, KN, SK, QN, SK, SK, SK, JA, SK, QN, QN, QN, TN, JA, QN }, 	 //	 179	 360
{ KN, KN, SK, QN, AC, SK, SK, JA, SK, SK, QN, QN, TN, JA, KN }, 	 //	 180	 360
{ KN, KN, SK, QN, SK, SK, SK, JA, SK, KN, QN, QN, TN, JA, KN }, 	 //	 181	 360
{ KN, KN, SK, SK, SK, SK, SK, JA, JA, QN, QN, QN, TN, JA, QN }, 	 //	 182	 360
{ KN, KN, SK, SK, SK, SK, SK, JA, JA, KN, QN, QN, TN, JA, KN }, 	 //	 183	 360
{ KN, KN, SK, KN, KN, SK, SK, JA, SK, SK, QN, QN, TN, QN, QN }, 	 //	 184	 360
{ KN, KN, SK, KN, SK, SK, SK, JA, SK, QN, QN, QN, TN, QN, QN }, 	 //	 185	 360
{ KN, KN, SK, KN, AC, SK, SK, JA, SK, SK, QN, QN, TN, QN, KN }, 	 //	 186	 360
{ KN, KN, SK, KN, SK, SK, SK, JA, SK, KN, QN, QN, TN, QN, KN }, 	 //	 187	 360
{ KN, KN, SK, SK, SK, SK, SK, JA, QN, QN, QN, QN, TN, KN, QN }, 	 //	 188	 360
{ KN, KN, SK, SK, SK, SK, SK, JA, QN, KN, QN, QN, TN, KN, KN }, 	 //	 189	 360
{ KN, SK, SK, ST, PF, SK, QN, JA, JA, JA, QN, KN, TN, TN, TN }, 	 //	 190	 360
{ SK, QN, WN, SH, TN, QN, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 191	 360
{ SK, QN, WN, TN, TN, QN, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 192	 360
{ SK, QN, TN, SH, WN, QN, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 193	 360
{ SK, QN, TN, TN, WN, QN, SK, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 194	 360
{ SK, QN, TN, TN, TN, QN, SK, TN, TN, TN, QN, JA, TN, TN, ST }, 	 //	 195	 360
{ SK, QN, TN, TN, TN, QN, SK, TN, TN, TN, QN, JA, TN, WN, ST }, 	 //	 196	 360
{ SK, QN, TN, JA, TN, QN, SK, TN, TN, TN, QN, JA, TN, AC, TN }, 	 //	 197	 360
{ SK, QN, TN, TN, TN, QN, SK, TN, TN, TN, QN, JA, LO, TN, TN }, 	 //	 198	 360
{ SK, QN, TN, TN, TN, QN, SK, TN, TN, TN, QN, JA, LO, WN, TN }, 	 //	 199	 360
{ SK, QN, QN, KN, KN, QN, SK, SK, SK, KN, QN, JA, JA, QN, SK }, 	 //	 200	 360
{ SK, QN, QN, KN, SK, QN, SK, SK, SK, QN, QN, JA, JA, QN, QN }, 	 //	 201	 360
{ SK, QN, QN, KN, AC, QN, SK, SK, SK, AC, QN, JA, JA, QN, SK }, 	 //	 202	 360
{ SK, QN, QN, KN, SK, QN, SK, SK, SK, KN, QN, JA, JA, QN, KN }, 	 //	 203	 360
{ SK, QN, SK, QN, KN, QN, SK, JA, SK, SK, QN, JA, TN, JA, QN }, 	 //	 204	 360
{ SK, QN, SK, QN, SK, QN, SK, JA, SK, QN, QN, JA, TN, JA, QN }, 	 //	 205	 360
{ SK, QN, SK, QN, AC, QN, SK, JA, SK, SK, QN, JA, TN, JA, KN }, 	 //	 206	 360
{ SK, QN, SK, QN, SK, QN, SK, JA, SK, KN, QN, JA, TN, JA, KN }, 	 //	 207	 360
{ SK, QN, SK, SK, SK, QN, SK, JA, JA, QN, QN, JA, TN, JA, QN }, 	 //	 208	 360
{ SK, QN, SK, SK, SK, QN, SK, JA, JA, KN, QN, JA, TN, JA, KN }, 	 //	 209	 360
{ SK, QN, SK, KN, KN, QN, SK, JA, SK, SK, QN, JA, TN, QN, QN }, 	 //	 210	 360
{ SK, QN, SK, KN, SK, QN, SK, JA, SK, QN, QN, JA, TN, QN, QN }, 	 //	 211	 360
{ SK, QN, SK, KN, AC, QN, SK, JA, SK, SK, QN, JA, TN, QN, KN }, 	 //	 212	 360
{ SK, QN, SK, KN, SK, QN, SK, JA, SK, KN, QN, JA, TN, QN, KN }, 	 //	 213	 360
{ SK, QN, SK, SK, SK, QN, SK, JA, QN, QN, QN, JA, TN, KN, QN }, 	 //	 214	 360
{ SK, QN, SK, SK, SK, QN, SK, JA, QN, KN, QN, JA, TN, KN, KN }, 	 //	 215	 360
{ SK, SK, WN, SH, TN, QN, JA, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 216	 360
{ SK, SK, WN, TN, TN, QN, JA, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 217	 360
{ SK, SK, TN, SH, WN, QN, JA, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 218	 360
{ SK, SK, TN, TN, WN, QN, JA, TN, TN, TN, QN, JA, TN, TN, TN }, 	 //	 219	 360
{ SK, SK, TN, TN, TN, QN, JA, TN, TN, TN, QN, JA, TN, TN, ST }, 	 //	 220	 360
{ SK, SK, TN, TN, TN, QN, JA, TN, TN, TN, QN, JA, TN, WN, ST }, 	 //	 221	 360
{ SK, SK, TN, JA, TN, QN, JA, TN, TN, TN, QN, JA, TN, AC, TN }, 	 //	 222	 360
{ SK, SK, TN, TN, TN, QN, JA, TN, TN, TN, QN, JA, LO, TN, TN }, 	 //	 223	 360
{ SK, SK, TN, TN, TN, QN, JA, TN, TN, TN, QN, JA, LO, WN, TN }, 	 //	 224	 360
{ SK, SK, SK, QN, KN, QN, JA, JA, SK, SK, QN, JA, TN, JA, QN }, 	 //	 225	 360
{ SK, SK, SK, QN, SK, QN, JA, JA, SK, QN, QN, JA, TN, JA, QN }, 	 //	 226	 360
{ SK, SK, SK, QN, AC, QN, JA, JA, SK, SK, QN, JA, TN, JA, KN }, 	 //	 227	 360
{ SK, SK, SK, QN, SK, QN, JA, JA, SK, KN, QN, JA, TN, JA, KN }, 	 //	 228	 360
{ SK, SK, SK, KN, KN, QN, JA, JA, SK, SK, QN, JA, TN, QN, QN }, 	 //	 229	 360
{ SK, SK, SK, KN, SK, QN, JA, JA, SK, QN, QN, JA, TN, QN, QN }, 	 //	 230	 360
{ SK, SK, SK, KN, AC, QN, JA, JA, SK, SK, QN, JA, TN, QN, KN }, 	 //	 231	 360
{ SK, SK, SK, KN, SK, QN, JA, JA, SK, KN, QN, JA, TN, QN, KN }, 	 //	 232	 360
{ SK, KN, WN, SH, TN, QN, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 233	 360
{ SK, KN, WN, TN, TN, QN, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 234	 360
{ SK, KN, TN, SH, WN, QN, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 235	 360
{ SK, KN, TN, TN, WN, QN, SK, TN, TN, TN, QN, QN, TN, TN, TN }, 	 //	 236	 360
{ SK, KN, TN, TN, TN, QN, SK, TN, TN, TN, QN, QN, TN, TN, ST }, 	 //	 237	 360
{ SK, KN, TN, TN, TN, QN, SK, TN, TN, TN, QN, QN, TN, WN, ST }, 	 //	 238	 360
{ SK, KN, TN, JA, TN, QN, SK, TN, TN, TN, QN, QN, TN, AC, TN }, 	 //	 239	 360
{ SK, KN, TN, TN, TN, QN, SK, TN, TN, TN, QN, QN, LO, TN, TN }, 	 //	 240	 360
{ SK, KN, TN, TN, TN, QN, SK, TN, TN, TN, QN, QN, LO, WN, TN }, 	 //	 241	 360
{ SK, KN, QN, QN, KN, QN, SK, SK, SK, KN, QN, QN, JA, JA, SK }, 	 //	 242	 360
{ SK, KN, QN, QN, SK, QN, SK, SK, SK, QN, QN, QN, JA, JA, QN }, 	 //	 243	 360
{ SK, KN, QN, QN, AC, QN, SK, SK, SK, AC, QN, QN, JA, JA, SK }, 	 //	 244	 360
{ SK, KN, QN, QN, SK, QN, SK, SK, SK, KN, QN, QN, JA, JA, KN }, 	 //	 245	 360
{ SK, KN, QN, KN, KN, QN, SK, SK, SK, KN, QN, QN, JA, QN, SK }, 	 //	 246	 360
{ SK, KN, QN, KN, SK, QN, SK, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 247	 360
{ SK, KN, QN, KN, AC, QN, SK, SK, SK, AC, QN, QN, JA, QN, SK }, 	 //	 248	 360
{ SK, KN, QN, KN, SK, QN, SK, SK, SK, KN, QN, QN, JA, QN, KN }, 	 //	 249	 360
{ SK, KN, SK, QN, KN, QN, SK, JA, SK, SK, QN, QN, TN, JA, QN }, 	 //	 250	 360
{ SK, KN, SK, QN, SK, QN, SK, JA, SK, QN, QN, QN, TN, JA, QN }, 	 //	 251	 360
{ SK, KN, SK, QN, AC, QN, SK, JA, SK, SK, QN, QN, TN, JA, KN }, 	 //	 252	 360
{ SK, KN, SK, QN, SK, QN, SK, JA, SK, KN, QN, QN, TN, JA, KN }, 	 //	 253	 360
{ SK, KN, SK, SK, SK, QN, SK, JA, JA, QN, QN, QN, TN, JA, QN }, 	 //	 254	 360
{ SK, KN, SK, SK, SK, QN, SK, JA, JA, KN, QN, QN, TN, JA, KN }, 	 //	 255	 360
{ SK, KN, SK, KN, KN, QN, SK, JA, SK, SK, QN, QN, TN, QN, QN }, 	 //	 256	 360
{ SK, KN, SK, KN, SK, QN, SK, JA, SK, QN, QN, QN, TN, QN, QN }, 	 //	 257	 360
{ SK, KN, SK, KN, AC, QN, SK, JA, SK, SK, QN, QN, TN, QN, KN }, 	 //	 258	 360
{ SK, KN, SK, KN, SK, QN, SK, JA, SK, KN, QN, QN, TN, QN, KN }, 	 //	 259	 360
{ SK, KN, SK, SK, SK, QN, SK, JA, QN, QN, QN, QN, TN, KN, QN }, 	 //	 260	 360
{ SK, KN, SK, SK, SK, QN, SK, JA, QN, KN, QN, QN, TN, KN, KN }, 	 //	 261	 360
{ SK, SK, WN, SH, TN, QN, QN, TN, TN, TN, QN, KN, TN, TN, TN }, 	 //	 262	 360
{ SK, SK, WN, TN, TN, QN, QN, TN, TN, TN, QN, KN, TN, TN, TN }, 	 //	 263	 360
{ SK, SK, TN, SH, WN, QN, QN, TN, TN, TN, QN, KN, TN, TN, TN }, 	 //	 264	 360
{ SK, SK, TN, TN, WN, QN, QN, TN, TN, TN, QN, KN, TN, TN, TN }, 	 //	 265	 360
{ SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, QN, KN, TN, TN, ST }, 	 //	 266	 360
{ SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, QN, KN, TN, WN, ST }, 	 //	 267	 360
{ SK, SK, TN, JA, TN, QN, QN, TN, TN, TN, QN, KN, TN, AC, TN }, 	 //	 268	 360
{ SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, QN, KN, LO, TN, TN }, 	 //	 269	 360
{ SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, QN, KN, LO, WN, TN }, 	 //	 270	 360
{ SK, SK, SK, QN, KN, QN, QN, JA, SK, SK, QN, KN, TN, JA, QN }, 	 //	 271	 360
{ SK, SK, SK, QN, SK, QN, QN, JA, SK, QN, QN, KN, TN, JA, QN }, 	 //	 272	 360
{ SK, SK, SK, QN, AC, QN, QN, JA, SK, SK, QN, KN, TN, JA, KN }, 	 //	 273	 360
{ SK, SK, SK, QN, SK, QN, QN, JA, SK, KN, QN, KN, TN, JA, KN }, 	 //	 274	 360
{ SK, SK, SK, KN, KN, QN, QN, JA, SK, SK, QN, KN, TN, QN, QN }, 	 //	 275	 360
{ SK, SK, SK, KN, SK, QN, QN, JA, SK, QN, QN, KN, TN, QN, QN }, 	 //	 276	 360
{ SK, SK, SK, KN, AC, QN, QN, JA, SK, SK, QN, KN, TN, QN, KN }, 	 //	 277	 360
{ SK, SK, SK, KN, SK, QN, QN, JA, SK, KN, QN, KN, TN, QN, KN }, 	 //	 278	 360
{ QN, QN, SK, ST, PF, QN, SK, JA, JA, JA, QN, JA, TN, TN, TN }, 	 //	 279	 360
{ QN, SK, SK, ST, JA, QN, JA, JA, JA, WN, QN, JA, TN, TN, TN }, 	 //	 280	 360
{ QN, SK, SK, ST, WN, QN, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 281	 360
{ QN, SK, SK, ST, TN, QN, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 282	 360
{ QN, KN, SK, ST, PF, QN, SK, JA, JA, JA, QN, QN, TN, TN, TN }, 	 //	 283	 360
{ QN, SK, SK, ST, PF, QN, QN, JA, JA, JA, QN, KN, TN, TN, TN }, 	 //	 284	 360
{ QN, QN, SK, ST, PF, QN, SK, JA, JA, JA, SH, JA, TN, TN, TN }, 	 //	 285	 360
{ QN, SK, SK, ST, JA, QN, JA, JA, JA, WN, SH, JA, TN, TN, TN }, 	 //	 286	 360
{ QN, SK, SK, ST, WN, QN, JA, JA, JA, TN, SH, JA, TN, TN, TN }, 	 //	 287	 360
{ QN, SK, SK, ST, TN, QN, JA, JA, JA, TN, SH, JA, TN, TN, TN }, 	 //	 288	 360
{ QN, KN, SK, ST, PF, QN, SK, JA, JA, JA, SH, QN, TN, TN, TN }, 	 //	 289	 360
{ QN, SK, SK, ST, PF, QN, QN, JA, JA, JA, SH, KN, TN, TN, TN }, 	 //	 290	 360
{ QN, QN, SK, ST, PF, SH, SK, JA, JA, JA, JA, JA, TN, TN, TN }, 	 //	 291	 360
{ QN, SK, SK, ST, JA, SH, JA, JA, JA, WN, JA, JA, TN, TN, TN }, 	 //	 292	 360
{ QN, SK, SK, ST, WN, SH, JA, JA, JA, TN, JA, JA, TN, TN, TN }, 	 //	 293	 360
{ QN, SK, SK, ST, TN, SH, JA, JA, JA, TN, JA, JA, TN, TN, TN }, 	 //	 294	 360
{ QN, KN, SK, ST, PF, SH, SK, JA, JA, JA, JA, QN, TN, TN, TN }, 	 //	 295	 360
{ QN, SK, SK, ST, PF, SH, QN, JA, JA, JA, JA, KN, TN, TN, TN }, 	 //	 296	 360
{ SH, QN, SK, ST, PF, JA, SK, JA, JA, JA, JA, JA, TN, TN, TN }, 	 //	 297	 360
{ SH, SK, SK, JA, JA, JA, JA, JA, SH, WN, JA, JA, TN, TN, TN }, 	 //	 298	 360
{ SH, SK, SK, JA, WN, JA, JA, JA, SH, TN, JA, JA, TN, TN, TN }, 	 //	 299	 360
{ SH, SK, SK, JA, TN, JA, JA, JA, SH, TN, JA, JA, TN, TN, TN }, 	 //	 300	 360
{ SH, SK, SK, JA, PF, JA, JA, JA, SH, JA, JA, JA, TN, TN, TN }, 	 //	 301	 360
{ SH, SK, SK, SH, JA, JA, JA, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 302	 360
{ SH, SK, SK, SH, WN, JA, JA, JA, TN, TN, JA, JA, TN, TN, TN }, 	 //	 303	 360
{ SH, SK, SK, SH, TN, JA, JA, JA, TN, TN, JA, JA, TN, TN, ST }, 	 //	 304	 360
{ SH, SK, SK, SH, TN, JA, JA, JA, TN, ST, JA, JA, TN, TN, AC }, 	 //	 305	 360
{ SH, SK, SK, SH, PF, JA, JA, JA, TN, JA, JA, JA, TN, TN, TN }, 	 //	 306	 360
{ SH, SK, SK, SH, TN, JA, JA, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 307	 360
{ SH, SK, SK, TN, JA, JA, JA, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 308	 360
{ SH, SK, SK, TN, WN, JA, JA, JA, TN, TN, JA, JA, TN, TN, TN }, 	 //	 309	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, TN, ST }, 	 //	 310	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, ST, JA, JA, TN, TN, AC }, 	 //	 311	 360
{ SH, SK, SK, TN, PF, JA, JA, JA, TN, JA, JA, JA, TN, TN, TN }, 	 //	 312	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 313	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, WN, TN }, 	 //	 314	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, WN, ST }, 	 //	 315	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, ST, JA, JA, TN, WN, AC }, 	 //	 316	 360
{ SH, SK, SK, TN, TN, JA, JA, JA, TN, AC, JA, JA, TN, WN, AC }, 	 //	 317	 360
{ SH, SK, SK, JA, TN, JA, JA, JA, TN, TN, JA, JA, TN, AC, TN }, 	 //	 318	 360
{ SH, SK, SK, JA, TN, JA, JA, JA, TN, TN, JA, JA, TN, AC, ST }, 	 //	 319	 360
{ SH, SK, SK, JA, TN, JA, JA, JA, TN, ST, JA, JA, TN, AC, AC }, 	 //	 320	 360
{ SH, SK, SK, JA, TN, JA, JA, JA, TN, AC, JA, JA, TN, AC, AC }, 	 //	 321	 360
{ SH, KN, SK, ST, PF, JA, SK, JA, JA, JA, JA, QN, TN, TN, TN }, 	 //	 322	 360
{ SH, SK, SK, ST, PF, JA, QN, JA, JA, JA, JA, KN, TN, TN, TN }, 	 //	 323	 360
{ JA, QN, SK, ST, PF, JA, SK, JA, JA, JA, JA, JA, TN, TN, TN }, 	 //	 324	 360
{ JA, SK, SK, JA, JA, JA, JA, JA, SH, WN, JA, JA, TN, TN, TN }, 	 //	 325	 360
{ JA, SK, SK, JA, WN, JA, JA, JA, SH, TN, JA, JA, TN, TN, TN }, 	 //	 326	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, SH, TN, JA, JA, TN, TN, TN }, 	 //	 327	 360
{ JA, SK, SK, JA, PF, JA, JA, JA, SH, JA, JA, JA, TN, TN, TN }, 	 //	 328	 360
{ JA, SK, SK, SH, JA, JA, JA, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 329	 360
{ JA, SK, SK, SH, WN, JA, JA, JA, TN, TN, JA, JA, TN, TN, TN }, 	 //	 330	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, TN, JA, JA, TN, TN, ST }, 	 //	 331	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, ST, JA, JA, TN, TN, AC }, 	 //	 332	 360
{ JA, SK, SK, SH, PF, JA, JA, JA, TN, JA, JA, JA, TN, TN, TN }, 	 //	 333	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 334	 360
{ JA, SK, SK, TN, JA, JA, JA, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 335	 360
{ JA, SK, SK, TN, WN, JA, JA, JA, TN, TN, JA, JA, TN, TN, TN }, 	 //	 336	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, TN, ST }, 	 //	 337	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, ST, JA, JA, TN, TN, AC }, 	 //	 338	 360
{ JA, SK, SK, TN, PF, JA, JA, JA, TN, JA, JA, JA, TN, TN, TN }, 	 //	 339	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 340	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, WN, TN }, 	 //	 341	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, TN, WN, ST }, 	 //	 342	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, ST, JA, JA, TN, WN, AC }, 	 //	 343	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, AC, JA, JA, TN, WN, AC }, 	 //	 344	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, TN, JA, JA, TN, AC, TN }, 	 //	 345	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, TN, JA, JA, TN, AC, ST }, 	 //	 346	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, ST, JA, JA, TN, AC, AC }, 	 //	 347	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, AC, JA, JA, TN, AC, AC }, 	 //	 348	 360
{ JA, KN, SK, ST, PF, JA, SK, JA, JA, JA, JA, QN, TN, TN, TN }, 	 //	 349	 360
{ JA, SK, SK, ST, PF, JA, QN, JA, JA, JA, JA, KN, TN, TN, TN }, 	 //	 350	 360
{ JA, QN, SK, ST, PF, JA, SK, JA, JA, JA, WN, JA, TN, TN, TN }, 	 //	 351	 360
{ JA, SK, SK, JA, JA, JA, JA, JA, SH, WN, WN, JA, TN, TN, TN }, 	 //	 352	 360
{ JA, SK, SK, JA, WN, JA, JA, JA, SH, TN, WN, JA, TN, TN, TN }, 	 //	 353	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, SH, TN, WN, JA, TN, TN, TN }, 	 //	 354	 360
{ JA, SK, SK, JA, PF, JA, JA, JA, SH, JA, WN, JA, TN, TN, TN }, 	 //	 355	 360
{ JA, SK, SK, SH, JA, JA, JA, JA, TN, WN, WN, JA, TN, TN, TN }, 	 //	 356	 360
{ JA, SK, SK, SH, WN, JA, JA, JA, TN, TN, WN, JA, TN, TN, TN }, 	 //	 357	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, TN, WN, JA, TN, TN, ST }, 	 //	 358	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, ST, WN, JA, TN, TN, AC }, 	 //	 359	 360
{ JA, SK, SK, SH, PF, JA, JA, JA, TN, JA, WN, JA, TN, TN, TN }, 	 //	 360	 360
{ JA, SK, SK, SH, TN, JA, JA, JA, TN, AC, WN, JA, TN, TN, AC }, 	 //	 361	 360
{ JA, SK, SK, TN, JA, JA, JA, JA, TN, WN, WN, JA, TN, TN, TN }, 	 //	 362	 360
{ JA, SK, SK, TN, WN, JA, JA, JA, TN, TN, WN, JA, TN, TN, TN }, 	 //	 363	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, WN, JA, TN, TN, ST }, 	 //	 364	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, ST, WN, JA, TN, TN, AC }, 	 //	 365	 360
{ JA, SK, SK, TN, PF, JA, JA, JA, TN, JA, WN, JA, TN, TN, TN }, 	 //	 366	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, AC, WN, JA, TN, TN, AC }, 	 //	 367	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, WN, JA, TN, WN, TN }, 	 //	 368	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, TN, WN, JA, TN, WN, ST }, 	 //	 369	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, ST, WN, JA, TN, WN, AC }, 	 //	 370	 360
{ JA, SK, SK, TN, TN, JA, JA, JA, TN, AC, WN, JA, TN, WN, AC }, 	 //	 371	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, TN, WN, JA, TN, AC, TN }, 	 //	 372	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, TN, WN, JA, TN, AC, ST }, 	 //	 373	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, ST, WN, JA, TN, AC, AC }, 	 //	 374	 360
{ JA, SK, SK, JA, TN, JA, JA, JA, TN, AC, WN, JA, TN, AC, AC }, 	 //	 375	 360
{ JA, KN, SK, ST, PF, JA, SK, JA, JA, JA, WN, QN, TN, TN, TN }, 	 //	 376	 360
{ JA, SK, SK, ST, PF, JA, QN, JA, JA, JA, WN, KN, TN, TN, TN }, 	 //	 377	 360
{ JA, QN, SK, ST, PF, WN, SK, JA, JA, JA, TN, JA, TN, TN, TN }, 	 //	 378	 360
{ JA, SK, SK, ST, JA, WN, JA, JA, JA, WN, TN, JA, TN, TN, TN }, 	 //	 379	 360
{ JA, SK, SK, ST, WN, WN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 380	 360
{ JA, SK, SK, ST, TN, WN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 381	 360
{ JA, JA, SK, SK, SH, WN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 382	 360
{ JA, JA, SK, SK, JA, WN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 383	 360
{ JA, JA, SK, SK, JA, WN, SH, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 384	 360
{ JA, JA, SK, SK, PF, WN, SH, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 385	 360
{ JA, SH, SK, SK, SH, WN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 386	 360
{ JA, SH, SK, SK, JA, WN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 387	 360
{ JA, SH, SK, SK, JA, WN, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 388	 360
{ JA, SH, SK, SK, PF, WN, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 389	 360
{ JA, TN, SK, SK, SH, WN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 390	 360
{ JA, TN, SK, SK, JA, WN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 391	 360
{ JA, TN, SK, SK, JA, WN, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 392	 360
{ JA, TN, SK, SK, PF, WN, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 393	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 394	 360
{ JA, ST, SK, SK, LO, WN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 395	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 396	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, AC, TN, TN, TN, JA, CR }, 	 //	 397	 360
{ JA, ST, SK, SK, CR, WN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 398	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 399	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, KN, TN, TN, TN, JA, SK }, 	 //	 400	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, SK, TN, TN, TN, JA, QN }, 	 //	 401	 360
{ JA, ST, SK, SK, QN, WN, JA, JA, JA, QN, TN, TN, TN, JA, QN }, 	 //	 402	 360
{ JA, ST, SK, SK, QN, WN, JA, JA, JA, QN, TN, TN, TN, JA, SH }, 	 //	 403	 360
{ JA, ST, SK, SK, QN, WN, JA, JA, JA, SH, TN, TN, TN, JA, JA }, 	 //	 404	 360
{ JA, ST, SK, SK, JA, WN, JA, JA, JA, WN, TN, TN, TN, JA, TN }, 	 //	 405	 360
{ JA, ST, SK, SK, WN, WN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 406	 360
{ JA, ST, SK, SK, TN, WN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 407	 360
{ JA, ST, SK, SK, TN, WN, JA, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 408	 360
{ JA, ST, SK, SK, TN, WN, JA, JA, JA, ST, TN, TN, TN, JA, AC }, 	 //	 409	 360
{ JA, ST, SK, SK, ST, WN, JA, JA, JA, AC, TN, TN, TN, JA, KN }, 	 //	 410	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, KN, TN, TN, TN, JA, QN }, 	 //	 411	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, QN, TN, TN, TN, JA, PF }, 	 //	 412	 360
{ JA, ST, SK, SK, QN, WN, JA, JA, JA, PF, TN, TN, TN, JA, JA }, 	 //	 413	 360
{ JA, ST, SK, SK, JA, WN, JA, JA, JA, TN, TN, TN, TN, JA, AC }, 	 //	 414	 360
{ JA, ST, SK, SK, TN, WN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 415	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 416	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, AC, TN, TN, TN, JA, SK }, 	 //	 417	 360
{ JA, ST, SK, SK, AC, WN, JA, JA, JA, SK, TN, TN, TN, JA, KN }, 	 //	 418	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 419	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, KN, TN, TN, TN, JA, CR }, 	 //	 420	 360
{ JA, ST, SK, SK, CR, WN, JA, JA, JA, QN, TN, TN, TN, JA, KN }, 	 //	 421	 360
{ JA, ST, SK, SK, QN, WN, JA, JA, JA, KN, TN, TN, TN, JA, AC }, 	 //	 422	 360
{ JA, ST, SK, SK, KN, WN, JA, JA, JA, AC, TN, TN, TN, JA, LO }, 	 //	 423	 360
{ JA, KN, SK, ST, PF, WN, SK, JA, JA, JA, TN, QN, TN, TN, TN }, 	 //	 424	 360
{ JA, SK, SK, ST, PF, WN, QN, JA, JA, JA, TN, KN, TN, TN, TN }, 	 //	 425	 360
{ WN, QN, SK, ST, PF, TN, SK, JA, JA, JA, TN, JA, TN, TN, TN }, 	 //	 426	 360
{ WN, SK, SK, ST, JA, TN, JA, JA, JA, WN, TN, JA, TN, TN, TN }, 	 //	 427	 360
{ WN, SK, SK, ST, WN, TN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 428	 360
{ WN, SK, SK, ST, TN, TN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 429	 360
{ WN, JA, SK, SK, SH, TN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 430	 360
{ WN, JA, SK, SK, JA, TN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 431	 360
{ WN, JA, SK, SK, JA, TN, SH, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 432	 360
{ WN, JA, SK, SK, PF, TN, SH, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 433	 360
{ WN, SH, TN, QN, KN, TN, TN, TN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 434	 360
{ WN, SH, TN, QN, AC, TN, TN, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 435	 360
{ WN, SH, TN, QN, KN, TN, TN, TN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 436	 360
{ WN, SH, TN, QN, KN, TN, TN, TN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 437	 360
{ WN, SH, TN, QN, SK, TN, TN, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 438	 360
{ WN, SH, TN, QN, AC, TN, TN, TN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 439	 360
{ WN, SH, TN, QN, AC, TN, TN, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 440	 360
{ WN, SH, TN, QN, SK, TN, TN, TN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 441	 360
{ WN, SH, TN, SK, SK, TN, TN, TN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 442	 360
{ WN, SH, TN, SK, SK, TN, TN, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 443	 360
{ WN, SH, TN, KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 444	 360
{ WN, SH, TN, KN, AC, TN, TN, TN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 445	 360
{ WN, SH, TN, KN, KN, TN, TN, TN, SK, KN, TN, TN, TN, QN, SK }, 	 //	 446	 360
{ WN, SH, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN }, 	 //	 447	 360
{ WN, SH, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 448	 360
{ WN, SH, TN, KN, AC, TN, TN, TN, SK, AC, TN, TN, TN, QN, SK }, 	 //	 449	 360
{ WN, SH, TN, KN, AC, TN, TN, TN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 450	 360
{ WN, SH, TN, KN, SK, TN, TN, TN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 451	 360
{ WN, SH, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 452	 360
{ WN, SH, TN, SK, SK, TN, TN, TN, QN, KN, TN, TN, TN, KN, KN }, 	 //	 453	 360
{ WN, SH, SK, SK, SH, TN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 454	 360
{ WN, SH, SK, SK, JA, TN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 455	 360
{ WN, SH, SK, SK, JA, TN, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 456	 360
{ WN, SH, SK, SK, PF, TN, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 457	 360
{ WN, TN, TN, QN, KN, TN, TN, TN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 458	 360
{ WN, TN, TN, QN, AC, TN, TN, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 459	 360
{ WN, TN, TN, QN, KN, TN, TN, TN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 460	 360
{ WN, TN, TN, QN, KN, TN, TN, TN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 461	 360
{ WN, TN, TN, QN, SK, TN, TN, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 462	 360
{ WN, TN, TN, QN, AC, TN, TN, TN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 463	 360
{ WN, TN, TN, QN, AC, TN, TN, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 464	 360
{ WN, TN, TN, QN, SK, TN, TN, TN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 465	 360
{ WN, TN, TN, SK, SK, TN, TN, TN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 466	 360
{ WN, TN, TN, SK, SK, TN, TN, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 467	 360
{ WN, TN, TN, KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 468	 360
{ WN, TN, TN, KN, AC, TN, TN, TN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 469	 360
{ WN, TN, TN, KN, KN, TN, TN, TN, SK, KN, TN, TN, TN, QN, SK }, 	 //	 470	 360
{ WN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN }, 	 //	 471	 360
{ WN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 472	 360
{ WN, TN, TN, KN, AC, TN, TN, TN, SK, AC, TN, TN, TN, QN, SK }, 	 //	 473	 360
{ WN, TN, TN, KN, AC, TN, TN, TN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 474	 360
{ WN, TN, TN, KN, SK, TN, TN, TN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 475	 360
{ WN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 476	 360
{ WN, TN, TN, SK, SK, TN, TN, TN, QN, KN, TN, TN, TN, KN, KN }, 	 //	 477	 360
{ WN, TN, SK, SK, SH, TN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 478	 360
{ WN, TN, SK, SK, JA, TN, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 479	 360
{ WN, TN, SK, SK, JA, TN, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 480	 360
{ WN, TN, SK, SK, PF, TN, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 481	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 482	 360
{ WN, ST, SK, SK, LO, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 483	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 484	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, CR }, 	 //	 485	 360
{ WN, ST, SK, SK, CR, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 486	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 487	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, SK }, 	 //	 488	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, SK, TN, TN, TN, JA, QN }, 	 //	 489	 360
{ WN, ST, SK, SK, QN, TN, JA, JA, JA, QN, TN, TN, TN, JA, QN }, 	 //	 490	 360
{ WN, ST, SK, SK, QN, TN, JA, JA, JA, QN, TN, TN, TN, JA, SH }, 	 //	 491	 360
{ WN, ST, SK, SK, QN, TN, JA, JA, JA, SH, TN, TN, TN, JA, JA }, 	 //	 492	 360
{ WN, ST, SK, SK, JA, TN, JA, JA, JA, WN, TN, TN, TN, JA, TN }, 	 //	 493	 360
{ WN, ST, SK, SK, WN, TN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 494	 360
{ WN, ST, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 495	 360
{ WN, ST, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 496	 360
{ WN, ST, SK, SK, TN, TN, JA, JA, JA, ST, TN, TN, TN, JA, AC }, 	 //	 497	 360
{ WN, ST, SK, SK, ST, TN, JA, JA, JA, AC, TN, TN, TN, JA, KN }, 	 //	 498	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, KN, TN, TN, TN, JA, QN }, 	 //	 499	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, QN, TN, TN, TN, JA, PF }, 	 //	 500	 360
{ WN, ST, SK, SK, QN, TN, JA, JA, JA, PF, TN, TN, TN, JA, JA }, 	 //	 501	 360
{ WN, ST, SK, SK, JA, TN, JA, JA, JA, TN, TN, TN, TN, JA, AC }, 	 //	 502	 360
{ WN, ST, SK, SK, TN, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 503	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 504	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, SK }, 	 //	 505	 360
{ WN, ST, SK, SK, AC, TN, JA, JA, JA, SK, TN, TN, TN, JA, KN }, 	 //	 506	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 507	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, CR }, 	 //	 508	 360
{ WN, ST, SK, SK, CR, TN, JA, JA, JA, QN, TN, TN, TN, JA, KN }, 	 //	 509	 360
{ WN, ST, SK, SK, QN, TN, JA, JA, JA, KN, TN, TN, TN, JA, AC }, 	 //	 510	 360
{ WN, ST, SK, SK, KN, TN, JA, JA, JA, AC, TN, TN, TN, JA, LO }, 	 //	 511	 360
{ WN, KN, SK, ST, PF, TN, SK, JA, JA, JA, TN, QN, TN, TN, TN }, 	 //	 512	 360
{ WN, SK, SK, ST, PF, TN, QN, JA, JA, JA, TN, KN, TN, TN, TN }, 	 //	 513	 360
{ TN, QN, SK, ST, PF, TN, SK, JA, JA, JA, TN, JA, TN, TN, TN }, 	 //	 514	 360
{ TN, SK, SK, ST, JA, TN, JA, JA, JA, WN, TN, JA, TN, TN, TN }, 	 //	 515	 360
{ TN, SK, SK, ST, WN, TN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 516	 360
{ TN, SK, SK, ST, TN, TN, JA, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 517	 360
{ TN, JA, SK, SK, SH, TN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 518	 360
{ TN, JA, SK, SK, JA, TN, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 519	 360
{ TN, JA, SK, SK, JA, TN, SH, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 520	 360
{ TN, JA, SK, SK, PF, TN, SH, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 521	 360
{ TN, SH, WN, QN, KN, TN, TN, TN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 522	 360
{ TN, SH, WN, QN, AC, TN, TN, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 523	 360
{ TN, SH, WN, QN, KN, TN, TN, TN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 524	 360
{ TN, SH, WN, QN, KN, TN, TN, TN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 525	 360
{ TN, SH, WN, QN, SK, TN, TN, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 526	 360
{ TN, SH, WN, QN, AC, TN, TN, TN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 527	 360
{ TN, SH, WN, QN, AC, TN, TN, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 528	 360
{ TN, SH, WN, QN, SK, TN, TN, TN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 529	 360
{ TN, SH, WN, SK, SK, TN, TN, TN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 530	 360
{ TN, SH, WN, SK, SK, TN, TN, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 531	 360
{ TN, SH, WN, KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 532	 360
{ TN, SH, WN, KN, AC, TN, TN, TN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 533	 360
{ TN, SH, WN, KN, KN, TN, TN, TN, SK, KN, TN, TN, TN, QN, SK }, 	 //	 534	 360
{ TN, SH, WN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN }, 	 //	 535	 360
{ TN, SH, WN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 536	 360
{ TN, SH, WN, KN, AC, TN, TN, TN, SK, AC, TN, TN, TN, QN, SK }, 	 //	 537	 360
{ TN, SH, WN, KN, AC, TN, TN, TN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 538	 360
{ TN, SH, WN, KN, SK, TN, TN, TN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 539	 360
{ TN, SH, WN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 540	 360
{ TN, SH, WN, SK, SK, TN, TN, TN, QN, KN, TN, TN, TN, KN, KN }, 	 //	 541	 360
{ TN, TN, WN, QN, KN, TN, TN, TN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 542	 360
{ TN, TN, WN, QN, AC, TN, TN, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 543	 360
{ TN, TN, WN, QN, KN, TN, TN, TN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 544	 360
{ TN, TN, WN, QN, KN, TN, TN, TN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 545	 360
{ TN, TN, WN, QN, SK, TN, TN, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 546	 360
{ TN, TN, WN, QN, AC, TN, TN, TN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 547	 360
{ TN, TN, WN, QN, AC, TN, TN, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 548	 360
{ TN, TN, WN, QN, SK, TN, TN, TN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 549	 360
{ TN, TN, WN, SK, SK, TN, TN, TN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 550	 360
{ TN, TN, WN, SK, SK, TN, TN, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 551	 360
{ TN, TN, WN, KN, KN, TN, TN, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 552	 360
{ TN, TN, WN, KN, AC, TN, TN, TN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 553	 360
{ TN, TN, WN, KN, KN, TN, TN, TN, SK, KN, TN, TN, TN, QN, SK }, 	 //	 554	 360
{ TN, TN, WN, KN, KN, TN, TN, TN, SK, SK, TN, TN, TN, QN, QN }, 	 //	 555	 360
{ TN, TN, WN, KN, SK, TN, TN, TN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 556	 360
{ TN, TN, WN, KN, AC, TN, TN, TN, SK, AC, TN, TN, TN, QN, SK }, 	 //	 557	 360
{ TN, TN, WN, KN, AC, TN, TN, TN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 558	 360
{ TN, TN, WN, KN, SK, TN, TN, TN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 559	 360
{ TN, TN, WN, SK, SK, TN, TN, TN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 560	 360
{ TN, TN, WN, SK, SK, TN, TN, TN, QN, KN, TN, TN, TN, KN, KN }, 	 //	 561	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, QN, KN, TN, TN, LO, SK, SK }, 	 //	 562	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, QN, AC, TN, TN, LO, SK, SK }, 	 //	 563	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, KN, TN, TN, LO, JA, SK }, 	 //	 564	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, SK, TN, TN, LO, JA, QN }, 	 //	 565	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, QN, TN, TN, LO, JA, QN }, 	 //	 566	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, AC, TN, TN, LO, JA, SK }, 	 //	 567	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, SK, TN, TN, LO, JA, KN }, 	 //	 568	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, KN, TN, TN, LO, JA, KN }, 	 //	 569	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, QN, TN, TN, LO, JA, QN }, 	 //	 570	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, KN, TN, TN, LO, JA, KN }, 	 //	 571	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, KN, KN, TN, TN, LO, SK, SK }, 	 //	 572	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, KN, AC, TN, TN, LO, SK, SK }, 	 //	 573	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, KN, TN, TN, LO, QN, SK }, 	 //	 574	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, TN, LO, QN, QN }, 	 //	 575	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, TN, LO, QN, QN }, 	 //	 576	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, AC, TN, TN, LO, QN, SK }, 	 //	 577	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, SK, TN, TN, LO, QN, KN }, 	 //	 578	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, KN, TN, TN, LO, QN, KN }, 	 //	 579	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, TN, LO, KN, QN }, 	 //	 580	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, KN, TN, TN, LO, KN, KN }, 	 //	 581	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, QN, KN, TN, WN, LO, SK, SK }, 	 //	 582	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, QN, AC, TN, WN, LO, SK, SK }, 	 //	 583	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, KN, TN, WN, LO, JA, SK }, 	 //	 584	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, SK, TN, WN, LO, JA, QN }, 	 //	 585	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, QN, TN, WN, LO, JA, QN }, 	 //	 586	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, AC, TN, WN, LO, JA, SK }, 	 //	 587	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, SK, TN, WN, LO, JA, KN }, 	 //	 588	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, KN, TN, WN, LO, JA, KN }, 	 //	 589	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, QN, TN, WN, LO, JA, QN }, 	 //	 590	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, KN, TN, WN, LO, JA, KN }, 	 //	 591	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, KN, KN, TN, WN, LO, SK, SK }, 	 //	 592	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, KN, AC, TN, WN, LO, SK, SK }, 	 //	 593	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, KN, TN, WN, LO, QN, SK }, 	 //	 594	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, TN, WN, LO, QN, QN }, 	 //	 595	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, TN, WN, LO, QN, QN }, 	 //	 596	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, AC, TN, WN, LO, QN, SK }, 	 //	 597	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, SK, TN, WN, LO, QN, KN }, 	 //	 598	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, KN, TN, WN, LO, QN, KN }, 	 //	 599	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, TN, WN, LO, KN, QN }, 	 //	 600	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, KN, TN, WN, LO, KN, KN }, 	 //	 601	 360
{ TN, TN, SK, SK, SH, TN, TN, JA, JA, JA, TN, WN, TN, JA, JA }, 	 //	 602	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, TN, WN, TN, JA, JA }, 	 //	 603	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, TN, WN, TN, JA, WN }, 	 //	 604	 360
{ TN, TN, SK, SK, PF, TN, TN, JA, JA, JA, TN, WN, TN, JA, TN }, 	 //	 605	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 606	 360
{ TN, ST, SK, SK, LO, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 607	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 608	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, CR }, 	 //	 609	 360
{ TN, ST, SK, SK, CR, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 610	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 611	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, SK }, 	 //	 612	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, SK, TN, TN, TN, JA, QN }, 	 //	 613	 360
{ TN, ST, SK, SK, QN, TN, JA, JA, JA, QN, TN, TN, TN, JA, QN }, 	 //	 614	 360
{ TN, ST, SK, SK, QN, TN, JA, JA, JA, QN, TN, TN, TN, JA, SH }, 	 //	 615	 360
{ TN, ST, SK, SK, QN, TN, JA, JA, JA, SH, TN, TN, TN, JA, JA }, 	 //	 616	 360
{ TN, ST, SK, SK, JA, TN, JA, JA, JA, WN, TN, TN, TN, JA, TN }, 	 //	 617	 360
{ TN, ST, SK, SK, WN, TN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 618	 360
{ TN, ST, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, TN, JA, TN }, 	 //	 619	 360
{ TN, ST, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 620	 360
{ TN, ST, SK, SK, TN, TN, JA, JA, JA, ST, TN, TN, TN, JA, AC }, 	 //	 621	 360
{ TN, ST, SK, SK, ST, TN, JA, JA, JA, AC, TN, TN, TN, JA, KN }, 	 //	 622	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, KN, TN, TN, TN, JA, QN }, 	 //	 623	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, QN, TN, TN, TN, JA, PF }, 	 //	 624	 360
{ TN, ST, SK, SK, QN, TN, JA, JA, JA, PF, TN, TN, TN, JA, JA }, 	 //	 625	 360
{ TN, ST, SK, SK, JA, TN, JA, JA, JA, TN, TN, TN, TN, JA, AC }, 	 //	 626	 360
{ TN, ST, SK, SK, TN, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 627	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 628	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, AC, TN, TN, TN, JA, SK }, 	 //	 629	 360
{ TN, ST, SK, SK, AC, TN, JA, JA, JA, SK, TN, TN, TN, JA, KN }, 	 //	 630	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 631	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, KN, TN, TN, TN, JA, CR }, 	 //	 632	 360
{ TN, ST, SK, SK, CR, TN, JA, JA, JA, QN, TN, TN, TN, JA, KN }, 	 //	 633	 360
{ TN, ST, SK, SK, QN, TN, JA, JA, JA, KN, TN, TN, TN, JA, AC }, 	 //	 634	 360
{ TN, ST, SK, SK, KN, TN, JA, JA, JA, AC, TN, TN, TN, JA, LO }, 	 //	 635	 360
{ TN, JA, TN, QN, KN, TN, TN, TN, QN, KN, TN, AC, TN, SK, SK }, 	 //	 636	 360
{ TN, JA, TN, QN, AC, TN, TN, TN, QN, AC, TN, AC, TN, SK, SK }, 	 //	 637	 360
{ TN, JA, TN, QN, KN, TN, TN, TN, SK, KN, TN, AC, TN, JA, SK }, 	 //	 638	 360
{ TN, JA, TN, QN, KN, TN, TN, TN, SK, SK, TN, AC, TN, JA, QN }, 	 //	 639	 360
{ TN, JA, TN, QN, SK, TN, TN, TN, SK, QN, TN, AC, TN, JA, QN }, 	 //	 640	 360
{ TN, JA, TN, QN, AC, TN, TN, TN, SK, AC, TN, AC, TN, JA, SK }, 	 //	 641	 360
{ TN, JA, TN, QN, AC, TN, TN, TN, SK, SK, TN, AC, TN, JA, KN }, 	 //	 642	 360
{ TN, JA, TN, QN, SK, TN, TN, TN, SK, KN, TN, AC, TN, JA, KN }, 	 //	 643	 360
{ TN, JA, TN, SK, SK, TN, TN, TN, JA, QN, TN, AC, TN, JA, QN }, 	 //	 644	 360
{ TN, JA, TN, SK, SK, TN, TN, TN, JA, KN, TN, AC, TN, JA, KN }, 	 //	 645	 360
{ TN, JA, TN, KN, KN, TN, TN, TN, KN, KN, TN, AC, TN, SK, SK }, 	 //	 646	 360
{ TN, JA, TN, KN, AC, TN, TN, TN, KN, AC, TN, AC, TN, SK, SK }, 	 //	 647	 360
{ TN, JA, TN, KN, KN, TN, TN, TN, SK, KN, TN, AC, TN, QN, SK }, 	 //	 648	 360
{ TN, JA, TN, KN, KN, TN, TN, TN, SK, SK, TN, AC, TN, QN, QN }, 	 //	 649	 360
{ TN, JA, TN, KN, SK, TN, TN, TN, SK, QN, TN, AC, TN, QN, QN }, 	 //	 650	 360
{ TN, JA, TN, KN, AC, TN, TN, TN, SK, AC, TN, AC, TN, QN, SK }, 	 //	 651	 360
{ TN, JA, TN, KN, AC, TN, TN, TN, SK, SK, TN, AC, TN, QN, KN }, 	 //	 652	 360
{ TN, JA, TN, KN, SK, TN, TN, TN, SK, KN, TN, AC, TN, QN, KN }, 	 //	 653	 360
{ TN, JA, TN, SK, SK, TN, TN, TN, QN, QN, TN, AC, TN, KN, QN }, 	 //	 654	 360
{ TN, JA, TN, SK, SK, TN, TN, TN, QN, KN, TN, AC, TN, KN, KN }, 	 //	 655	 360
{ TN, JA, SK, SK, SH, TN, TN, JA, JA, JA, TN, AC, TN, JA, JA }, 	 //	 656	 360
{ TN, JA, SK, SK, JA, TN, TN, JA, JA, JA, TN, AC, TN, JA, JA }, 	 //	 657	 360
{ TN, JA, SK, SK, JA, TN, TN, JA, JA, JA, TN, AC, TN, JA, WN }, 	 //	 658	 360
{ TN, JA, SK, SK, PF, TN, TN, JA, JA, JA, TN, AC, TN, JA, TN }, 	 //	 659	 360
{ TN, KN, SK, ST, PF, TN, SK, JA, JA, JA, TN, QN, TN, TN, TN }, 	 //	 660	 360
{ TN, SK, SK, ST, PF, TN, QN, JA, JA, JA, TN, KN, TN, TN, TN }, 	 //	 661	 360
{ TN, QN, SK, ST, PF, TN, SK, JA, JA, JA, ST, JA, TN, TN, TN }, 	 //	 662	 360
{ TN, SK, SK, ST, JA, TN, JA, JA, JA, WN, ST, JA, TN, TN, TN }, 	 //	 663	 360
{ TN, SK, SK, ST, WN, TN, JA, JA, JA, TN, ST, JA, TN, TN, TN }, 	 //	 664	 360
{ TN, SK, SK, ST, TN, TN, JA, JA, JA, TN, ST, JA, TN, TN, TN }, 	 //	 665	 360
{ TN, SH, SK, SK, SH, TN, TN, JA, JA, JA, ST, TN, TN, JA, JA }, 	 //	 666	 360
{ TN, SH, SK, SK, JA, TN, TN, JA, JA, JA, ST, TN, TN, JA, JA }, 	 //	 667	 360
{ TN, SH, SK, SK, JA, TN, TN, JA, JA, JA, ST, TN, TN, JA, WN }, 	 //	 668	 360
{ TN, SH, SK, SK, PF, TN, TN, JA, JA, JA, ST, TN, TN, JA, TN }, 	 //	 669	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, QN, KN, ST, TN, TN, SK, SK }, 	 //	 670	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, QN, AC, ST, TN, TN, SK, SK }, 	 //	 671	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, KN, ST, TN, TN, JA, SK }, 	 //	 672	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, SK, ST, TN, TN, JA, QN }, 	 //	 673	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, QN, ST, TN, TN, JA, QN }, 	 //	 674	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, AC, ST, TN, TN, JA, SK }, 	 //	 675	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, SK, ST, TN, TN, JA, KN }, 	 //	 676	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, KN, ST, TN, TN, JA, KN }, 	 //	 677	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, QN, ST, TN, TN, JA, QN }, 	 //	 678	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, KN, ST, TN, TN, JA, KN }, 	 //	 679	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, KN, KN, ST, TN, TN, SK, SK }, 	 //	 680	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, KN, AC, ST, TN, TN, SK, SK }, 	 //	 681	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, KN, ST, TN, TN, QN, SK }, 	 //	 682	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, ST, TN, TN, QN, QN }, 	 //	 683	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, ST, TN, TN, QN, QN }, 	 //	 684	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, AC, ST, TN, TN, QN, SK }, 	 //	 685	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, SK, ST, TN, TN, QN, KN }, 	 //	 686	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, KN, ST, TN, TN, QN, KN }, 	 //	 687	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, ST, TN, TN, KN, QN }, 	 //	 688	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, KN, ST, TN, TN, KN, KN }, 	 //	 689	 360
{ TN, TN, SK, SK, SH, TN, TN, JA, JA, JA, ST, TN, TN, JA, JA }, 	 //	 690	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, ST, TN, TN, JA, JA }, 	 //	 691	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, ST, TN, TN, JA, WN }, 	 //	 692	 360
{ TN, TN, SK, SK, PF, TN, TN, JA, JA, JA, ST, TN, TN, JA, TN }, 	 //	 693	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, QN, KN, ST, WN, TN, SK, SK }, 	 //	 694	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, QN, AC, ST, WN, TN, SK, SK }, 	 //	 695	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, KN, ST, WN, TN, JA, SK }, 	 //	 696	 360
{ TN, TN, TN, QN, KN, TN, TN, TN, SK, SK, ST, WN, TN, JA, QN }, 	 //	 697	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, QN, ST, WN, TN, JA, QN }, 	 //	 698	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, AC, ST, WN, TN, JA, SK }, 	 //	 699	 360
{ TN, TN, TN, QN, AC, TN, TN, TN, SK, SK, ST, WN, TN, JA, KN }, 	 //	 700	 360
{ TN, TN, TN, QN, SK, TN, TN, TN, SK, KN, ST, WN, TN, JA, KN }, 	 //	 701	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, QN, ST, WN, TN, JA, QN }, 	 //	 702	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, JA, KN, ST, WN, TN, JA, KN }, 	 //	 703	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, KN, KN, ST, WN, TN, SK, SK }, 	 //	 704	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, KN, AC, ST, WN, TN, SK, SK }, 	 //	 705	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, KN, ST, WN, TN, QN, SK }, 	 //	 706	 360
{ TN, TN, TN, KN, KN, TN, TN, TN, SK, SK, ST, WN, TN, QN, QN }, 	 //	 707	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, QN, ST, WN, TN, QN, QN }, 	 //	 708	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, AC, ST, WN, TN, QN, SK }, 	 //	 709	 360
{ TN, TN, TN, KN, AC, TN, TN, TN, SK, SK, ST, WN, TN, QN, KN }, 	 //	 710	 360
{ TN, TN, TN, KN, SK, TN, TN, TN, SK, KN, ST, WN, TN, QN, KN }, 	 //	 711	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, QN, ST, WN, TN, KN, QN }, 	 //	 712	 360
{ TN, TN, TN, SK, SK, TN, TN, TN, QN, KN, ST, WN, TN, KN, KN }, 	 //	 713	 360
{ TN, TN, SK, SK, SH, TN, TN, JA, JA, JA, ST, WN, TN, JA, JA }, 	 //	 714	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, ST, WN, TN, JA, JA }, 	 //	 715	 360
{ TN, TN, SK, SK, JA, TN, TN, JA, JA, JA, ST, WN, TN, JA, WN }, 	 //	 716	 360
{ TN, TN, SK, SK, PF, TN, TN, JA, JA, JA, ST, WN, TN, JA, TN }, 	 //	 717	 360
{ TN, JA, SK, SK, SH, TN, TN, JA, JA, JA, ST, AC, TN, JA, JA }, 	 //	 718	 360
{ TN, JA, SK, SK, JA, TN, TN, JA, JA, JA, ST, AC, TN, JA, JA }, 	 //	 719	 360
{ TN, JA, SK, SK, JA, TN, TN, JA, JA, JA, ST, AC, TN, JA, WN }, 	 //	 720	 360
{ TN, JA, SK, SK, PF, TN, TN, JA, JA, JA, ST, AC, TN, JA, TN }, 	 //	 721	 360
{ TN, KN, SK, ST, PF, TN, SK, JA, JA, JA, ST, QN, TN, TN, TN }, 	 //	 722	 360
{ TN, SK, SK, ST, PF, TN, QN, JA, JA, JA, ST, KN, TN, TN, TN }, 	 //	 723	 360
{ TN, QN, SK, ST, PF, ST, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 724	 360
{ TN, SK, SK, ST, JA, ST, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 725	 360
{ TN, SK, SK, ST, WN, ST, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 726	 360
{ TN, SK, SK, ST, TN, ST, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 727	 360
{ TN, SH, SK, SK, SH, ST, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 728	 360
{ TN, SH, SK, SK, JA, ST, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 729	 360
{ TN, SH, SK, SK, JA, ST, TN, JA, JA, JA, AC, TN, TN, JA, WN }, 	 //	 730	 360
{ TN, SH, SK, SK, PF, ST, TN, JA, JA, JA, AC, TN, TN, JA, TN }, 	 //	 731	 360
{ TN, TN, SK, SK, SH, ST, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 732	 360
{ TN, TN, SK, SK, JA, ST, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 733	 360
{ TN, TN, SK, SK, JA, ST, TN, JA, JA, JA, AC, TN, TN, JA, WN }, 	 //	 734	 360
{ TN, TN, SK, SK, PF, ST, TN, JA, JA, JA, AC, TN, TN, JA, TN }, 	 //	 735	 360
{ TN, TN, SK, SK, SH, ST, TN, JA, JA, JA, AC, WN, TN, JA, JA }, 	 //	 736	 360
{ TN, TN, SK, SK, JA, ST, TN, JA, JA, JA, AC, WN, TN, JA, JA }, 	 //	 737	 360
{ TN, TN, SK, SK, JA, ST, TN, JA, JA, JA, AC, WN, TN, JA, WN }, 	 //	 738	 360
{ TN, TN, SK, SK, PF, ST, TN, JA, JA, JA, AC, WN, TN, JA, TN }, 	 //	 739	 360
{ TN, JA, SK, SK, SH, ST, TN, JA, JA, JA, AC, AC, TN, JA, JA }, 	 //	 740	 360
{ TN, JA, SK, SK, JA, ST, TN, JA, JA, JA, AC, AC, TN, JA, JA }, 	 //	 741	 360
{ TN, JA, SK, SK, JA, ST, TN, JA, JA, JA, AC, AC, TN, JA, WN }, 	 //	 742	 360
{ TN, JA, SK, SK, PF, ST, TN, JA, JA, JA, AC, AC, TN, JA, TN }, 	 //	 743	 360
{ TN, KN, SK, ST, PF, ST, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 744	 360
{ TN, SK, SK, ST, PF, ST, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 745	 360
{ ST, QN, SK, ST, PF, AC, SK, JA, JA, JA, KN, JA, TN, TN, TN }, 	 //	 746	 360
{ ST, SK, SK, ST, JA, AC, JA, JA, JA, WN, KN, JA, TN, TN, TN }, 	 //	 747	 360
{ ST, SK, SK, ST, WN, AC, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 748	 360
{ ST, SK, SK, ST, TN, AC, JA, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 749	 360
{ ST, KN, SK, ST, PF, AC, SK, JA, JA, JA, KN, QN, TN, TN, TN }, 	 //	 750	 360
{ ST, SK, SK, ST, PF, AC, QN, JA, JA, JA, KN, KN, TN, TN, TN }, 	 //	 751	 360
{ AC, QN, SK, ST, PF, KN, SK, JA, JA, JA, QN, JA, TN, TN, TN }, 	 //	 752	 360
{ AC, SK, SK, ST, JA, KN, JA, JA, JA, WN, QN, JA, TN, TN, TN }, 	 //	 753	 360
{ AC, SK, SK, ST, WN, KN, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 754	 360
{ AC, SK, SK, ST, TN, KN, JA, JA, JA, TN, QN, JA, TN, TN, TN }, 	 //	 755	 360
{ AC, KN, SK, ST, PF, KN, SK, JA, JA, JA, QN, QN, TN, TN, TN }, 	 //	 756	 360
{ AC, SK, SK, ST, PF, KN, QN, JA, JA, JA, QN, KN, TN, TN, TN }, 	 //	 757	 360
{ KN, QN, SK, ST, PF, QN, SK, JA, JA, JA, PF, JA, TN, TN, TN }, 	 //	 758	 360
{ KN, SK, SK, ST, JA, QN, JA, JA, JA, WN, PF, JA, TN, TN, TN }, 	 //	 759	 360
{ KN, SK, SK, ST, WN, QN, JA, JA, JA, TN, PF, JA, TN, TN, TN }, 	 //	 760	 360
{ KN, SK, SK, ST, TN, QN, JA, JA, JA, TN, PF, JA, TN, TN, TN }, 	 //	 761	 360
{ KN, KN, SK, ST, PF, QN, SK, JA, JA, JA, PF, QN, TN, TN, TN }, 	 //	 762	 360
{ KN, SK, SK, ST, PF, QN, QN, JA, JA, JA, PF, KN, TN, TN, TN }, 	 //	 763	 360
{ QN, QN, SK, ST, PF, PF, SK, JA, JA, JA, JA, JA, TN, TN, TN }, 	 //	 764	 360
{ QN, SK, SK, ST, JA, PF, JA, JA, JA, WN, JA, JA, TN, TN, TN }, 	 //	 765	 360
{ QN, SK, SK, ST, WN, PF, JA, JA, JA, TN, JA, JA, TN, TN, TN }, 	 //	 766	 360
{ QN, SK, SK, ST, TN, PF, JA, JA, JA, TN, JA, JA, TN, TN, TN }, 	 //	 767	 360
{ QN, KN, SK, ST, PF, PF, SK, JA, JA, JA, JA, QN, TN, TN, TN }, 	 //	 768	 360
{ QN, SK, SK, ST, PF, PF, QN, JA, JA, JA, JA, KN, TN, TN, TN }, 	 //	 769	 360
{ PF, QN, SK, ST, PF, JA, SK, JA, JA, JA, TN, JA, TN, TN, TN }, 	 //	 770	 360
{ PF, SK, SK, JA, JA, JA, JA, JA, SH, WN, TN, JA, TN, TN, TN }, 	 //	 771	 360
{ PF, SK, SK, JA, WN, JA, JA, JA, SH, TN, TN, JA, TN, TN, TN }, 	 //	 772	 360
{ PF, SK, SK, JA, TN, JA, JA, JA, SH, TN, TN, JA, TN, TN, TN }, 	 //	 773	 360
{ PF, SK, SK, JA, PF, JA, JA, JA, SH, JA, TN, JA, TN, TN, TN }, 	 //	 774	 360
{ PF, SK, SK, SH, JA, JA, JA, JA, TN, WN, TN, JA, TN, TN, TN }, 	 //	 775	 360
{ PF, SK, SK, SH, WN, JA, JA, JA, TN, TN, TN, JA, TN, TN, TN }, 	 //	 776	 360
{ PF, SK, SK, SH, TN, JA, JA, JA, TN, TN, TN, JA, TN, TN, ST }, 	 //	 777	 360
{ PF, SK, SK, SH, TN, JA, JA, JA, TN, ST, TN, JA, TN, TN, AC }, 	 //	 778	 360
{ PF, SK, SK, SH, PF, JA, JA, JA, TN, JA, TN, JA, TN, TN, TN }, 	 //	 779	 360
{ PF, SK, SK, SH, TN, JA, JA, JA, TN, AC, TN, JA, TN, TN, AC }, 	 //	 780	 360
{ PF, SK, SK, TN, JA, JA, JA, JA, TN, WN, TN, JA, TN, TN, TN }, 	 //	 781	 360
{ PF, SK, SK, TN, WN, JA, JA, JA, TN, TN, TN, JA, TN, TN, TN }, 	 //	 782	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, JA, TN, TN, ST }, 	 //	 783	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, ST, TN, JA, TN, TN, AC }, 	 //	 784	 360
{ PF, SK, SK, TN, PF, JA, JA, JA, TN, JA, TN, JA, TN, TN, TN }, 	 //	 785	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, AC, TN, JA, TN, TN, AC }, 	 //	 786	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, JA, TN, WN, TN }, 	 //	 787	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, TN, TN, JA, TN, WN, ST }, 	 //	 788	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, ST, TN, JA, TN, WN, AC }, 	 //	 789	 360
{ PF, SK, SK, TN, TN, JA, JA, JA, TN, AC, TN, JA, TN, WN, AC }, 	 //	 790	 360
{ PF, SK, SK, JA, TN, JA, JA, JA, TN, TN, TN, JA, TN, AC, TN }, 	 //	 791	 360
{ PF, SK, SK, JA, TN, JA, JA, JA, TN, TN, TN, JA, TN, AC, ST }, 	 //	 792	 360
{ PF, SK, SK, JA, TN, JA, JA, JA, TN, ST, TN, JA, TN, AC, AC }, 	 //	 793	 360
{ PF, SK, SK, JA, TN, JA, JA, JA, TN, AC, TN, JA, TN, AC, AC }, 	 //	 794	 360
{ PF, JA, SK, SK, SH, JA, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 795	 360
{ PF, JA, SK, SK, JA, JA, SH, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 796	 360
{ PF, JA, SK, SK, JA, JA, SH, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 797	 360
{ PF, JA, SK, SK, PF, JA, SH, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 798	 360
{ PF, SH, SK, SK, SH, JA, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 799	 360
{ PF, SH, SK, SK, JA, JA, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 800	 360
{ PF, SH, SK, SK, JA, JA, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 801	 360
{ PF, SH, SK, SK, PF, JA, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 802	 360
{ PF, TN, SK, SK, SH, JA, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 803	 360
{ PF, TN, SK, SK, JA, JA, TN, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 804	 360
{ PF, TN, SK, SK, JA, JA, TN, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 805	 360
{ PF, TN, SK, SK, PF, JA, TN, JA, JA, JA, TN, TN, TN, JA, TN }, 	 //	 806	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, QN, KN, TN, TN, TN, SK, SK }, 	 //	 807	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, QN, AC, TN, TN, TN, SK, SK }, 	 //	 808	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, SK, LO, TN, TN, TN, JA, AC }, 	 //	 809	 360
{ PF, ST, SK, QN, LO, JA, JA, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 810	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 811	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, SK, AC, TN, TN, TN, JA, CR }, 	 //	 812	 360
{ PF, ST, SK, QN, CR, JA, JA, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 813	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 814	 360
{ PF, ST, SK, QN, QN, JA, JA, JA, SK, QN, TN, TN, TN, JA, QN }, 	 //	 815	 360
{ PF, ST, SK, QN, QN, JA, JA, JA, SK, QN, TN, TN, TN, JA, SH }, 	 //	 816	 360
{ PF, ST, SK, QN, QN, JA, JA, JA, SK, SH, TN, TN, TN, JA, JA }, 	 //	 817	 360
{ PF, ST, SK, QN, SH, JA, JA, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 818	 360
{ PF, ST, SK, QN, JA, JA, JA, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 819	 360
{ PF, ST, SK, QN, JA, JA, JA, JA, SK, JA, TN, TN, TN, JA, WN }, 	 //	 820	 360
{ PF, ST, SK, QN, JA, JA, JA, JA, SK, WN, TN, TN, TN, JA, TN }, 	 //	 821	 360
{ PF, ST, SK, QN, WN, JA, JA, JA, SK, TN, TN, TN, TN, JA, TN }, 	 //	 822	 360
{ PF, ST, SK, QN, TN, JA, JA, JA, SK, TN, TN, TN, TN, JA, TN }, 	 //	 823	 360
{ PF, ST, SK, QN, TN, JA, JA, JA, SK, TN, TN, TN, TN, JA, ST }, 	 //	 824	 360
{ PF, ST, SK, QN, TN, JA, JA, JA, SK, ST, TN, TN, TN, JA, AC }, 	 //	 825	 360
{ PF, ST, SK, QN, ST, JA, JA, JA, SK, AC, TN, TN, TN, JA, KN }, 	 //	 826	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, SK, KN, TN, TN, TN, JA, QN }, 	 //	 827	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, SK, QN, TN, TN, TN, JA, PF }, 	 //	 828	 360
{ PF, ST, SK, QN, QN, JA, JA, JA, SK, PF, TN, TN, TN, JA, JA }, 	 //	 829	 360
{ PF, ST, SK, QN, PF, JA, JA, JA, SK, JA, TN, TN, TN, JA, TN }, 	 //	 830	 360
{ PF, ST, SK, QN, JA, JA, JA, JA, SK, TN, TN, TN, TN, JA, AC }, 	 //	 831	 360
{ PF, ST, SK, QN, TN, JA, JA, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 832	 360
{ PF, ST, SK, QN, AC, JA, JA, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 833	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 834	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, SK, KN, TN, TN, TN, JA, CR }, 	 //	 835	 360
{ PF, ST, SK, QN, CR, JA, JA, JA, SK, QN, TN, TN, TN, JA, KN }, 	 //	 836	 360
{ PF, ST, SK, QN, QN, JA, JA, JA, SK, KN, TN, TN, TN, JA, AC }, 	 //	 837	 360
{ PF, ST, SK, QN, KN, JA, JA, JA, SK, AC, TN, TN, TN, JA, LO }, 	 //	 838	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, KN, KN, TN, TN, TN, SK, SK }, 	 //	 839	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, KN, AC, TN, TN, TN, SK, SK }, 	 //	 840	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, SK, LO, TN, TN, TN, QN, AC }, 	 //	 841	 360
{ PF, ST, SK, KN, LO, JA, JA, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 842	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 843	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, SK, AC, TN, TN, TN, QN, CR }, 	 //	 844	 360
{ PF, ST, SK, KN, CR, JA, JA, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 845	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 846	 360
{ PF, ST, SK, KN, QN, JA, JA, JA, SK, QN, TN, TN, TN, QN, QN }, 	 //	 847	 360
{ PF, ST, SK, KN, QN, JA, JA, JA, SK, QN, TN, TN, TN, QN, SH }, 	 //	 848	 360
{ PF, ST, SK, KN, QN, JA, JA, JA, SK, SH, TN, TN, TN, QN, JA }, 	 //	 849	 360
{ PF, ST, SK, KN, SH, JA, JA, JA, SK, JA, TN, TN, TN, QN, JA }, 	 //	 850	 360
{ PF, ST, SK, KN, JA, JA, JA, JA, SK, JA, TN, TN, TN, QN, JA }, 	 //	 851	 360
{ PF, ST, SK, KN, JA, JA, JA, JA, SK, JA, TN, TN, TN, QN, WN }, 	 //	 852	 360
{ PF, ST, SK, KN, JA, JA, JA, JA, SK, WN, TN, TN, TN, QN, TN }, 	 //	 853	 360
{ PF, ST, SK, KN, WN, JA, JA, JA, SK, TN, TN, TN, TN, QN, TN }, 	 //	 854	 360
{ PF, ST, SK, KN, TN, JA, JA, JA, SK, TN, TN, TN, TN, QN, TN }, 	 //	 855	 360
{ PF, ST, SK, KN, TN, JA, JA, JA, SK, TN, TN, TN, TN, QN, ST }, 	 //	 856	 360
{ PF, ST, SK, KN, TN, JA, JA, JA, SK, ST, TN, TN, TN, QN, AC }, 	 //	 857	 360
{ PF, ST, SK, KN, ST, JA, JA, JA, SK, AC, TN, TN, TN, QN, KN }, 	 //	 858	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, SK, KN, TN, TN, TN, QN, QN }, 	 //	 859	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, SK, QN, TN, TN, TN, QN, PF }, 	 //	 860	 360
{ PF, ST, SK, KN, QN, JA, JA, JA, SK, PF, TN, TN, TN, QN, JA }, 	 //	 861	 360
{ PF, ST, SK, KN, PF, JA, JA, JA, SK, JA, TN, TN, TN, QN, TN }, 	 //	 862	 360
{ PF, ST, SK, KN, JA, JA, JA, JA, SK, TN, TN, TN, TN, QN, AC }, 	 //	 863	 360
{ PF, ST, SK, KN, TN, JA, JA, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 864	 360
{ PF, ST, SK, KN, AC, JA, JA, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 865	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 866	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, SK, KN, TN, TN, TN, QN, CR }, 	 //	 867	 360
{ PF, ST, SK, KN, CR, JA, JA, JA, SK, QN, TN, TN, TN, QN, KN }, 	 //	 868	 360
{ PF, ST, SK, KN, QN, JA, JA, JA, SK, KN, TN, TN, TN, QN, AC }, 	 //	 869	 360
{ PF, ST, SK, KN, KN, JA, JA, JA, SK, AC, TN, TN, TN, QN, LO }, 	 //	 870	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, LO, TN, TN, TN, KN, AC }, 	 //	 871	 360
{ PF, ST, SK, SK, LO, JA, JA, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 872	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 873	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, AC, TN, TN, TN, KN, CR }, 	 //	 874	 360
{ PF, ST, SK, SK, CR, JA, JA, JA, QN, KN, TN, TN, TN, KN, KN }, 	 //	 875	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, KN, TN, TN, TN, KN, KN }, 	 //	 876	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, KN, TN, TN, TN, KN, SK }, 	 //	 877	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, SK, TN, TN, TN, KN, QN }, 	 //	 878	 360
{ PF, ST, SK, SK, QN, JA, JA, JA, QN, QN, TN, TN, TN, KN, QN }, 	 //	 879	 360
{ PF, ST, SK, SK, QN, JA, JA, JA, QN, QN, TN, TN, TN, KN, SH }, 	 //	 880	 360
{ PF, ST, SK, SK, QN, JA, JA, JA, QN, SH, TN, TN, TN, KN, JA }, 	 //	 881	 360
{ PF, ST, SK, SK, SH, JA, JA, JA, QN, JA, TN, TN, TN, KN, JA }, 	 //	 882	 360
{ PF, ST, SK, SK, JA, JA, JA, JA, QN, JA, TN, TN, TN, KN, JA }, 	 //	 883	 360
{ PF, ST, SK, SK, JA, JA, JA, JA, QN, JA, TN, TN, TN, KN, WN }, 	 //	 884	 360
{ PF, ST, SK, SK, JA, JA, JA, JA, QN, WN, TN, TN, TN, KN, TN }, 	 //	 885	 360
{ PF, ST, SK, SK, WN, JA, JA, JA, QN, TN, TN, TN, TN, KN, TN }, 	 //	 886	 360
{ PF, ST, SK, SK, TN, JA, JA, JA, QN, TN, TN, TN, TN, KN, TN }, 	 //	 887	 360
{ PF, ST, SK, SK, TN, JA, JA, JA, QN, TN, TN, TN, TN, KN, ST }, 	 //	 888	 360
{ PF, ST, SK, SK, TN, JA, JA, JA, QN, ST, TN, TN, TN, KN, AC }, 	 //	 889	 360
{ PF, ST, SK, SK, ST, JA, JA, JA, QN, AC, TN, TN, TN, KN, KN }, 	 //	 890	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, KN, TN, TN, TN, KN, QN }, 	 //	 891	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, QN, TN, TN, TN, KN, PF }, 	 //	 892	 360
{ PF, ST, SK, SK, QN, JA, JA, JA, QN, PF, TN, TN, TN, KN, JA }, 	 //	 893	 360
{ PF, ST, SK, SK, PF, JA, JA, JA, QN, JA, TN, TN, TN, KN, TN }, 	 //	 894	 360
{ PF, ST, SK, SK, JA, JA, JA, JA, QN, TN, TN, TN, TN, KN, AC }, 	 //	 895	 360
{ PF, ST, SK, SK, TN, JA, JA, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 896	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 897	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, AC, TN, TN, TN, KN, SK }, 	 //	 898	 360
{ PF, ST, SK, SK, AC, JA, JA, JA, QN, SK, TN, TN, TN, KN, KN }, 	 //	 899	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, KN, TN, TN, TN, KN, KN }, 	 //	 900	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, KN, TN, TN, TN, KN, CR }, 	 //	 901	 360
{ PF, ST, SK, SK, CR, JA, JA, JA, QN, QN, TN, TN, TN, KN, KN }, 	 //	 902	 360
{ PF, ST, SK, SK, QN, JA, JA, JA, QN, KN, TN, TN, TN, KN, AC }, 	 //	 903	 360
{ PF, ST, SK, SK, KN, JA, JA, JA, QN, AC, TN, TN, TN, KN, LO }, 	 //	 904	 360
{ PF, KN, SK, ST, PF, JA, SK, JA, JA, JA, TN, QN, TN, TN, TN }, 	 //	 905	 360
{ PF, SK, SK, ST, PF, JA, QN, JA, JA, JA, TN, KN, TN, TN, TN }, 	 //	 906	 360
{ JA, QN, SK, ST, PF, TN, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 907	 360
{ JA, SK, SK, ST, JA, TN, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 908	 360
{ JA, SK, SK, ST, WN, TN, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 909	 360
{ JA, SK, SK, ST, TN, TN, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 910	 360
{ JA, KN, SK, ST, PF, TN, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 911	 360
{ JA, SK, SK, ST, PF, TN, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 912	 360
{ TN, QN, SK, ST, PF, AC, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 913	 360
{ TN, SK, SK, ST, JA, AC, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 914	 360
{ TN, SK, SK, ST, WN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 915	 360
{ TN, SK, SK, ST, TN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 916	 360
{ TN, SH, SK, SK, SH, AC, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 917	 360
{ TN, SH, SK, SK, JA, AC, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 918	 360
{ TN, SH, SK, SK, JA, AC, TN, JA, JA, JA, AC, TN, TN, JA, WN }, 	 //	 919	 360
{ TN, SH, SK, SK, PF, AC, TN, JA, JA, JA, AC, TN, TN, JA, TN }, 	 //	 920	 360
{ TN, TN, SK, SK, SH, AC, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 921	 360
{ TN, TN, SK, SK, JA, AC, TN, JA, JA, JA, AC, TN, TN, JA, JA }, 	 //	 922	 360
{ TN, TN, SK, SK, JA, AC, TN, JA, JA, JA, AC, TN, TN, JA, WN }, 	 //	 923	 360
{ TN, TN, SK, SK, PF, AC, TN, JA, JA, JA, AC, TN, TN, JA, TN }, 	 //	 924	 360
{ TN, TN, SK, SK, SH, AC, TN, JA, JA, JA, AC, WN, TN, JA, JA }, 	 //	 925	 360
{ TN, TN, SK, SK, JA, AC, TN, JA, JA, JA, AC, WN, TN, JA, JA }, 	 //	 926	 360
{ TN, TN, SK, SK, JA, AC, TN, JA, JA, JA, AC, WN, TN, JA, WN }, 	 //	 927	 360
{ TN, TN, SK, SK, PF, AC, TN, JA, JA, JA, AC, WN, TN, JA, TN }, 	 //	 928	 360
{ TN, JA, SK, SK, SH, AC, TN, JA, JA, JA, AC, AC, TN, JA, JA }, 	 //	 929	 360
{ TN, JA, SK, SK, JA, AC, TN, JA, JA, JA, AC, AC, TN, JA, JA }, 	 //	 930	 360
{ TN, JA, SK, SK, JA, AC, TN, JA, JA, JA, AC, AC, TN, JA, WN }, 	 //	 931	 360
{ TN, JA, SK, SK, PF, AC, TN, JA, JA, JA, AC, AC, TN, JA, TN }, 	 //	 932	 360
{ TN, KN, SK, ST, PF, AC, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 933	 360
{ TN, SK, SK, ST, PF, AC, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 934	 360
{ AC, QN, SK, ST, PF, AC, SK, JA, JA, JA, AC, JA, TN, TN, TN }, 	 //	 935	 360
{ AC, SK, SK, ST, JA, AC, JA, JA, JA, WN, AC, JA, TN, TN, TN }, 	 //	 936	 360
{ AC, SK, SK, ST, WN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 937	 360
{ AC, SK, SK, ST, TN, AC, JA, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 938	 360
{ AC, KN, SK, ST, PF, AC, SK, JA, JA, JA, AC, QN, TN, TN, TN }, 	 //	 939	 360
{ AC, SK, SK, ST, PF, AC, QN, JA, JA, JA, AC, KN, TN, TN, TN }, 	 //	 940	 360
{ AC, QN, WN, SH, TN, AC, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 941	 360
{ AC, QN, WN, TN, TN, AC, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 942	 360
{ AC, QN, TN, SH, WN, AC, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 943	 360
{ AC, QN, TN, TN, WN, AC, QN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 944	 360
{ AC, QN, TN, TN, TN, AC, QN, TN, TN, TN, SK, SK, TN, TN, ST }, 	 //	 945	 360
{ AC, QN, TN, TN, TN, AC, QN, TN, TN, TN, SK, SK, TN, WN, ST }, 	 //	 946	 360
{ AC, QN, TN, JA, TN, AC, QN, TN, TN, TN, SK, SK, TN, AC, TN }, 	 //	 947	 360
{ AC, QN, TN, TN, TN, AC, QN, TN, TN, TN, SK, SK, LO, TN, TN }, 	 //	 948	 360
{ AC, QN, TN, TN, TN, AC, QN, TN, TN, TN, SK, SK, LO, WN, TN }, 	 //	 949	 360
{ AC, QN, QN, KN, KN, AC, QN, QN, SK, KN, SK, SK, SK, QN, SK }, 	 //	 950	 360
{ AC, QN, QN, KN, KN, AC, QN, QN, SK, SK, SK, SK, SK, QN, QN }, 	 //	 951	 360
{ AC, QN, QN, KN, AC, AC, QN, QN, SK, AC, SK, SK, SK, QN, SK }, 	 //	 952	 360
{ AC, QN, QN, KN, AC, AC, QN, QN, SK, SK, SK, SK, SK, QN, KN }, 	 //	 953	 360
{ AC, QN, SK, ST, PF, AC, QN, JA, JA, JA, SK, SK, TN, TN, TN }, 	 //	 954	 360
{ AC, QN, WN, SH, TN, AC, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 955	 360
{ AC, QN, WN, TN, TN, AC, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 956	 360
{ AC, QN, TN, SH, WN, AC, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 957	 360
{ AC, QN, TN, TN, WN, AC, SK, TN, TN, TN, SK, JA, TN, TN, TN }, 	 //	 958	 360
{ AC, QN, TN, TN, TN, AC, SK, TN, TN, TN, SK, JA, TN, TN, ST }, 	 //	 959	 360
{ AC, QN, TN, TN, TN, AC, SK, TN, TN, TN, SK, JA, TN, WN, ST }, 	 //	 960	 360
{ AC, QN, TN, JA, TN, AC, SK, TN, TN, TN, SK, JA, TN, AC, TN }, 	 //	 961	 360
{ AC, QN, TN, TN, TN, AC, SK, TN, TN, TN, SK, JA, LO, TN, TN }, 	 //	 962	 360
{ AC, QN, TN, TN, TN, AC, SK, TN, TN, TN, SK, JA, LO, WN, TN }, 	 //	 963	 360
{ AC, QN, QN, KN, KN, AC, SK, QN, KN, KN, SK, JA, SK, SK, SK }, 	 //	 964	 360
{ AC, QN, QN, KN, AC, AC, SK, QN, KN, AC, SK, JA, SK, SK, SK }, 	 //	 965	 360
{ AC, QN, QN, KN, KN, AC, SK, QN, SK, KN, SK, JA, SK, QN, SK }, 	 //	 966	 360
{ AC, QN, QN, KN, KN, AC, SK, QN, SK, SK, SK, JA, SK, QN, QN }, 	 //	 967	 360
{ AC, QN, QN, KN, AC, AC, SK, QN, SK, AC, SK, JA, SK, QN, SK }, 	 //	 968	 360
{ AC, QN, QN, KN, AC, AC, SK, QN, SK, SK, SK, JA, SK, QN, KN }, 	 //	 969	 360
{ AC, QN, QN, KN, KN, AC, SK, SK, SK, KN, SK, JA, JA, QN, SK }, 	 //	 970	 360
{ AC, QN, QN, KN, SK, AC, SK, SK, SK, QN, SK, JA, JA, QN, QN }, 	 //	 971	 360
{ AC, QN, QN, KN, AC, AC, SK, SK, SK, AC, SK, JA, JA, QN, SK }, 	 //	 972	 360
{ AC, QN, QN, KN, SK, AC, SK, SK, SK, KN, SK, JA, JA, QN, KN }, 	 //	 973	 360
{ AC, SK, SK, ST, JA, AC, JA, JA, JA, WN, SK, JA, TN, TN, TN }, 	 //	 974	 360
{ AC, SK, SK, ST, WN, AC, JA, JA, JA, TN, SK, JA, TN, TN, TN }, 	 //	 975	 360
{ AC, SK, SK, ST, TN, AC, JA, JA, JA, TN, SK, JA, TN, TN, TN }, 	 //	 976	 360
{ AC, KN, WN, SH, TN, AC, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 977	 360
{ AC, KN, WN, TN, TN, AC, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 978	 360
{ AC, KN, TN, SH, WN, AC, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 979	 360
{ AC, KN, TN, TN, WN, AC, KN, TN, TN, TN, SK, SK, TN, TN, TN }, 	 //	 980	 360
{ AC, KN, TN, TN, TN, AC, KN, TN, TN, TN, SK, SK, TN, TN, ST }, 	 //	 981	 360
{ AC, KN, TN, TN, TN, AC, KN, TN, TN, TN, SK, SK, TN, WN, ST }, 	 //	 982	 360
{ AC, KN, TN, JA, TN, AC, KN, TN, TN, TN, SK, SK, TN, AC, TN }, 	 //	 983	 360
{ AC, KN, TN, TN, TN, AC, KN, TN, TN, TN, SK, SK, LO, TN, TN }, 	 //	 984	 360
{ AC, KN, TN, TN, TN, AC, KN, TN, TN, TN, SK, SK, LO, WN, TN }, 	 //	 985	 360
{ AC, KN, QN, QN, KN, AC, KN, QN, SK, KN, SK, SK, SK, JA, SK }, 	 //	 986	 360
{ AC, KN, QN, QN, KN, AC, KN, QN, SK, SK, SK, SK, SK, JA, QN }, 	 //	 987	 360
{ AC, KN, QN, QN, AC, AC, KN, QN, SK, AC, SK, SK, SK, JA, SK }, 	 //	 988	 360
{ AC, KN, QN, QN, AC, AC, KN, QN, SK, SK, SK, SK, SK, JA, KN }, 	 //	 989	 360
{ AC, KN, QN, KN, KN, AC, KN, QN, SK, KN, SK, SK, SK, QN, SK }, 	 //	 990	 360
{ AC, KN, QN, KN, KN, AC, KN, QN, SK, SK, SK, SK, SK, QN, QN }, 	 //	 991	 360
{ AC, KN, QN, KN, AC, AC, KN, QN, SK, AC, SK, SK, SK, QN, SK }, 	 //	 992	 360
{ AC, KN, QN, KN, AC, AC, KN, QN, SK, SK, SK, SK, SK, QN, KN }, 	 //	 993	 360
{ AC, KN, SK, ST, PF, AC, KN, JA, JA, JA, SK, SK, TN, TN, TN }, 	 //	 994	 360
{ AC, KN, WN, SH, TN, AC, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 995	 360
{ AC, KN, WN, TN, TN, AC, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 996	 360
{ AC, KN, TN, SH, WN, AC, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 997	 360
{ AC, KN, TN, TN, WN, AC, SK, TN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 998	 360
{ AC, KN, TN, TN, TN, AC, SK, TN, TN, TN, SK, QN, TN, TN, ST }, 	 //	 999	 360
{ AC, KN, TN, TN, TN, AC, SK, TN, TN, TN, SK, QN, TN, WN, ST }};	 //	 1000	 360
