unsigned char L5_Outcome_3300[100][15]={	 //	 0	 3300
{ AC, AC, JA, JA, JA, LO, AC, TN, TN, TN, AC, LO, AC, AC, AC }, 	 //	 1	 3300
{ AC, WN, JA, JA, JA, LO, AC, TN, TN, TN, AC, KN, AC, AC, AC }, 	 //	 2	 3300
{ AC, TN, TN, TN, TN, LO, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 3	 3300
{ AC, TN, TN, TN, TN, LO, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 4	 3300
{ AC, AC, JA, JA, JA, LO, AC, TN, TN, TN, AC, PF, AC, AC, AC }, 	 //	 5	 3300
{ AC, KN, JA, JA, JA, LO, AC, TN, TN, TN, AC, SH, AC, AC, AC }, 	 //	 6	 3300
{ LO, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 7	 3300
{ LO, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 8	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, AC, LO, AC, AC, AC }, 	 //	 9	 3300
{ AC, WN, JA, JA, JA, AC, AC, TN, TN, TN, AC, KN, AC, AC, AC }, 	 //	 10	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, AC, PF, AC, AC, AC }, 	 //	 11	 3300
{ AC, KN, JA, JA, JA, AC, AC, TN, TN, TN, AC, SH, AC, AC, AC }, 	 //	 12	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, ST, LO, AC, AC, AC }, 	 //	 13	 3300
{ AC, WN, JA, JA, JA, AC, AC, TN, TN, TN, ST, KN, AC, AC, AC }, 	 //	 14	 3300
{ AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, ST, AC, AC, TN, TN }, 	 //	 15	 3300
{ AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, ST, AC, AC, WN, TN }, 	 //	 16	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, ST, PF, AC, AC, AC }, 	 //	 17	 3300
{ AC, KN, JA, JA, JA, AC, AC, TN, TN, TN, ST, SH, AC, AC, AC }, 	 //	 18	 3300
{ AC, AC, JA, JA, JA, ST, AC, TN, TN, TN, KN, LO, AC, AC, AC }, 	 //	 19	 3300
{ AC, WN, JA, JA, JA, ST, AC, TN, TN, TN, KN, KN, AC, AC, AC }, 	 //	 20	 3300
{ AC, AC, JA, JA, JA, ST, AC, TN, TN, TN, KN, PF, AC, AC, AC }, 	 //	 21	 3300
{ AC, KN, JA, JA, JA, ST, AC, TN, TN, TN, KN, SH, AC, AC, AC }, 	 //	 22	 3300
{ JA, TN, TN, TN, TN, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 23	 3300
{ JA, TN, TN, TN, TN, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 24	 3300
{ WN, TN, TN, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 25	 3300
{ WN, TN, TN, TN, TN, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 26	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, LO, TN, TN, AC, AC, AC }, 	 //	 27	 3300
{ TN, TN, TN, TN, LO, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 28	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, CR }, 	 //	 29	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, SK }, 	 //	 30	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, LO, TN, WN, AC, AC, AC }, 	 //	 31	 3300
{ TN, TN, TN, TN, LO, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 32	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, CR }, 	 //	 33	 3300
{ TN, TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, SK }, 	 //	 34	 3300
{ TN, TN, TN, TN, TN, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 35	 3300
{ TN, TN, TN, TN, TN, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 36	 3300
{ TN, TN, TN, TN, TN, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 37	 3300
{ TN, TN, TN, TN, TN, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 38	 3300
{ AC, AC, JA, JA, JA, KN, AC, TN, TN, TN, QN, LO, AC, AC, AC }, 	 //	 39	 3300
{ AC, WN, JA, JA, JA, KN, AC, TN, TN, TN, QN, KN, AC, AC, AC }, 	 //	 40	 3300
{ AC, AC, JA, JA, JA, KN, AC, TN, TN, TN, QN, PF, AC, AC, AC }, 	 //	 41	 3300
{ AC, KN, JA, JA, JA, KN, AC, TN, TN, TN, QN, SH, AC, AC, AC }, 	 //	 42	 3300
{ PF, TN, TN, TN, TN, JA, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 43	 3300
{ PF, TN, TN, TN, TN, JA, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 44	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, LO, AC, AC, AC, LO, AC }, 	 //	 45	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, LO, AC }, 	 //	 46	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, LO, CR }, 	 //	 47	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, KN, AC, AC, AC, LO, QN }, 	 //	 48	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, LO, AC }, 	 //	 49	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, LO, SK }, 	 //	 50	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, SK, AC, AC, AC, LO, KN }, 	 //	 51	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, LO, AC, AC, AC, KN, AC }, 	 //	 52	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, AC, AC, AC, AC, KN, AC }, 	 //	 53	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, AC, AC, AC, AC, KN, CR }, 	 //	 54	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, KN, AC, AC, AC, KN, QN }, 	 //	 55	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, AC, AC, AC, AC, KN, AC }, 	 //	 56	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, AC, AC, AC, AC, KN, SK }, 	 //	 57	 3300
{ JA, JA, JA, WN, AC, TN, TN, TN, AC, SK, AC, AC, AC, KN, KN }, 	 //	 58	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, LO, AC, AC, AC, PF, AC }, 	 //	 59	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, AC }, 	 //	 60	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, CR }, 	 //	 61	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, KN, AC, AC, AC, PF, QN }, 	 //	 62	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, AC }, 	 //	 63	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, SK }, 	 //	 64	 3300
{ JA, JA, JA, AC, AC, TN, TN, TN, AC, SK, AC, AC, AC, PF, KN }, 	 //	 65	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, LO, AC, AC, AC, PF, AC }, 	 //	 66	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, AC }, 	 //	 67	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, CR }, 	 //	 68	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, KN, AC, AC, AC, PF, QN }, 	 //	 69	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, AC }, 	 //	 70	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, AC, AC, AC, AC, PF, SK }, 	 //	 71	 3300
{ JA, JA, JA, KN, AC, TN, TN, TN, AC, SK, AC, AC, AC, PF, KN }, 	 //	 72	 3300
{ TN, TN, TN, TN, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 73	 3300
{ TN, TN, TN, TN, TN, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 74	 3300
{ TN, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 75	 3300
{ TN, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 76	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 77	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN, AC }, 	 //	 78	 3300
{ TN, TN, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 79	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 80	 3300
{ TN, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, WN, TN }, 	 //	 81	 3300
{ TN, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 82	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, ST }, 	 //	 83	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, WN, AC }, 	 //	 84	 3300
{ TN, TN, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, WN, TN }, 	 //	 85	 3300
{ TN, TN, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 86	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, AC, LO, AC, AC, AC }, 	 //	 87	 3300
{ AC, WN, JA, JA, JA, AC, AC, TN, TN, TN, AC, KN, AC, AC, AC }, 	 //	 88	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, AC, PF, AC, AC, AC }, 	 //	 89	 3300
{ AC, KN, JA, JA, JA, AC, AC, TN, TN, TN, AC, SH, AC, AC, AC }, 	 //	 90	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, SK, LO, AC, AC, AC }, 	 //	 91	 3300
{ AC, WN, JA, JA, JA, AC, AC, TN, TN, TN, SK, KN, AC, AC, AC }, 	 //	 92	 3300
{ AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, SK, AC, AC, TN, TN }, 	 //	 93	 3300
{ AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, SK, AC, AC, WN, TN }, 	 //	 94	 3300
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, TN, SK, PF, AC, AC, AC }, 	 //	 95	 3300
{ AC, KN, JA, JA, JA, AC, AC, TN, TN, TN, SK, SH, AC, AC, AC }, 	 //	 96	 3300
{ AC, AC, JA, JA, JA, SK, AC, TN, TN, TN, KN, LO, AC, AC, AC }, 	 //	 97	 3300
{ AC, WN, JA, JA, JA, SK, AC, TN, TN, TN, KN, KN, AC, AC, AC }, 	 //	 98	 3300
{ AC, AC, JA, JA, JA, SK, AC, TN, TN, TN, KN, PF, AC, AC, AC }, 	 //	 99	 3300
{ AC, KN, JA, JA, JA, SK, AC, TN, TN, TN, KN, SH, AC, AC, AC }};	 //	 100	 3300
