#include "ReelDefine.h"

unsigned char L5_Outcome_4600[1000][15]={	 //	 0	 4600
{ AC, TN, TN, TN, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 1	 4600
{ AC, TN, TN, TN, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 2	 4600
{ AC, TN, TN, TN, AC, LO, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 3	 4600
{ AC, TN, TN, TN, AC, LO, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 4	 4600
{ LO, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 5	 4600
{ LO, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 6	 4600
{ LO, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 7	 4600
{ LO, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 8	 4600
{ AC, SH, TN, SH, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 9	 4600
{ AC, SH, TN, SH, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 10	 4600
{ AC, SH, TN, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 11	 4600
{ AC, SH, TN, SH, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 12	 4600
{ AC, SH, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 13	 4600
{ AC, SH, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 14	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 15	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN, AC }, 	 //	 16	 4600
{ AC, SH, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 17	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 18	 4600
{ AC, SH, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, WN, TN }, 	 //	 19	 4600
{ AC, SH, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 20	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, ST }, 	 //	 21	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, WN, AC }, 	 //	 22	 4600
{ AC, SH, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, WN, TN }, 	 //	 23	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 24	 4600
{ AC, AC, TN, SH, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 25	 4600
{ AC, AC, TN, SH, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 26	 4600
{ AC, AC, TN, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 27	 4600
{ AC, AC, TN, SH, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 28	 4600
{ AC, AC, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 29	 4600
{ AC, AC, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 30	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 31	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN, AC }, 	 //	 32	 4600
{ AC, AC, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 33	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 34	 4600
{ AC, AC, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, WN, TN }, 	 //	 35	 4600
{ AC, AC, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 36	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, ST }, 	 //	 37	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, WN, AC }, 	 //	 38	 4600
{ AC, AC, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, WN, TN }, 	 //	 39	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 40	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, ST, AC, LO, AC, AC, AC }, 	 //	 41	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, AC, AC, LO, AC, AC, AC }, 	 //	 42	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 43	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 44	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 45	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 46	 4600
{ AC, WN, TN, TN, TN, AC, AC, AC, WN, ST, AC, KN, AC, AC, AC }, 	 //	 47	 4600
{ AC, WN, TN, TN, TN, AC, AC, AC, WN, AC, AC, KN, AC, AC, AC }, 	 //	 48	 4600
{ AC, TN, TN, SH, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 49	 4600
{ AC, TN, TN, SH, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 50	 4600
{ AC, TN, TN, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 51	 4600
{ AC, TN, TN, SH, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 52	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC }, 	 //	 53	 4600
{ AC, TN, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 54	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 55	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, CR }, 	 //	 56	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 57	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 58	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, SK }, 	 //	 59	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN, QN }, 	 //	 60	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, TN, QN }, 	 //	 61	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, QN }, 	 //	 62	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, SH }, 	 //	 63	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN, JA }, 	 //	 64	 4600
{ AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA }, 	 //	 65	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA }, 	 //	 66	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, WN }, 	 //	 67	 4600
{ AC, TN, TN, TN, ST, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN }, 	 //	 68	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC, TN, QN }, 	 //	 69	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, QN, AC, AC, AC, TN, PF }, 	 //	 70	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, PF, AC, AC, AC, TN, JA }, 	 //	 71	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, TN, AC, AC, AC, TN, AC }, 	 //	 72	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 73	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, SK }, 	 //	 74	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN, KN }, 	 //	 75	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 76	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 77	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, CR }, 	 //	 78	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, TN, QN, AC, AC, AC, TN, KN }, 	 //	 79	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, KN, AC, AC, AC, TN, AC }, 	 //	 80	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, TN, LO }, 	 //	 81	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC, WN, AC }, 	 //	 82	 4600
{ AC, TN, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 83	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 84	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, CR }, 	 //	 85	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, TN, KN, AC, AC, AC, WN, KN }, 	 //	 86	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, WN, KN }, 	 //	 87	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, WN, SK }, 	 //	 88	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, WN, QN }, 	 //	 89	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, WN, QN }, 	 //	 90	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, WN, QN }, 	 //	 91	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, WN, SH }, 	 //	 92	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, WN, JA }, 	 //	 93	 4600
{ AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, WN, JA }, 	 //	 94	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, WN, JA }, 	 //	 95	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, WN, WN }, 	 //	 96	 4600
{ AC, TN, TN, TN, ST, AC, AC, AC, TN, AC, AC, AC, AC, WN, KN }, 	 //	 97	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC, WN, QN }, 	 //	 98	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, QN, AC, AC, AC, WN, PF }, 	 //	 99	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, PF, AC, AC, AC, WN, JA }, 	 //	 100	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, TN, TN, AC, AC, AC, WN, AC }, 	 //	 101	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 102	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, SK }, 	 //	 103	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, WN, KN }, 	 //	 104	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, TN, KN, AC, AC, AC, WN, KN }, 	 //	 105	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, WN, KN }, 	 //	 106	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, WN, CR }, 	 //	 107	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, TN, QN, AC, AC, AC, WN, KN }, 	 //	 108	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, TN, KN, AC, AC, AC, WN, AC }, 	 //	 109	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, WN, LO }, 	 //	 110	 4600
{ AC, AC, TN, SH, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 111	 4600
{ AC, AC, TN, SH, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 112	 4600
{ AC, AC, TN, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 113	 4600
{ AC, AC, TN, SH, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 114	 4600
{ AC, AC, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 115	 4600
{ AC, AC, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 116	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 117	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN, AC }, 	 //	 118	 4600
{ AC, AC, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 119	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 120	 4600
{ AC, AC, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, WN, TN }, 	 //	 121	 4600
{ AC, AC, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 122	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, ST }, 	 //	 123	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, WN, AC }, 	 //	 124	 4600
{ AC, AC, TN, TN, PF, AC, AC, AC, TN, JA, AC, AC, AC, WN, TN }, 	 //	 125	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 126	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, ST, AC, PF, AC, AC, AC }, 	 //	 127	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, AC, AC, PF, AC, AC, AC }, 	 //	 128	 4600
{ AC, KN, TN, TN, TN, AC, AC, AC, WN, ST, AC, SH, AC, AC, AC }, 	 //	 129	 4600
{ AC, KN, TN, TN, TN, AC, AC, AC, WN, AC, AC, SH, AC, AC, AC }, 	 //	 130	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, TN }, 	 //	 131	 4600
{ AC, SH, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, ST }, 	 //	 132	 4600
{ AC, SH, TN, JA, JA, AC, AC, AC, TN, WN, ST, AC, AC, AC, TN }, 	 //	 133	 4600
{ AC, SH, TN, JA, WN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 134	 4600
{ AC, SH, TN, JA, TN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 135	 4600
{ AC, SH, TN, JA, PF, AC, AC, AC, TN, JA, ST, AC, AC, AC, TN }, 	 //	 136	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, TN }, 	 //	 137	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, ST }, 	 //	 138	 4600
{ AC, AC, TN, JA, JA, AC, AC, AC, TN, WN, ST, AC, AC, AC, TN }, 	 //	 139	 4600
{ AC, AC, TN, JA, WN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 140	 4600
{ AC, AC, TN, JA, TN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 141	 4600
{ AC, AC, TN, JA, PF, AC, AC, AC, TN, JA, ST, AC, AC, AC, TN }, 	 //	 142	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, ST, ST, LO, AC, AC, AC }, 	 //	 143	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, AC, ST, LO, AC, AC, AC }, 	 //	 144	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 145	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 146	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 147	 4600
{ AC, TN, TN, TN, AC, AC, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 148	 4600
{ AC, TN, TN, TN, AC, AC, WN, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 149	 4600
{ AC, TN, TN, TN, AC, AC, WN, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 150	 4600
{ AC, WN, TN, TN, TN, AC, AC, AC, WN, ST, ST, KN, AC, AC, AC }, 	 //	 151	 4600
{ AC, WN, TN, TN, TN, AC, AC, AC, WN, AC, ST, KN, AC, AC, AC }, 	 //	 152	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, WN, AC, ST, AC, AC, AC, CR }, 	 //	 153	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, WN, KN, ST, AC, AC, AC, KN }, 	 //	 154	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, KN, ST, AC, AC, AC, KN }, 	 //	 155	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, KN, ST, AC, AC, AC, SK }, 	 //	 156	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, SK, ST, AC, AC, AC, QN }, 	 //	 157	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, WN, QN, ST, AC, AC, AC, QN }, 	 //	 158	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, WN, QN, ST, AC, AC, AC, QN }, 	 //	 159	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, WN, QN, ST, AC, AC, AC, SH }, 	 //	 160	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, WN, SH, ST, AC, AC, AC, JA }, 	 //	 161	 4600
{ AC, TN, TN, TN, SH, AC, AC, AC, WN, JA, ST, AC, AC, AC, JA }, 	 //	 162	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, WN, JA, ST, AC, AC, AC, JA }, 	 //	 163	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, WN, JA, ST, AC, AC, AC, WN }, 	 //	 164	 4600
{ AC, TN, TN, TN, JA, AC, AC, AC, WN, WN, ST, AC, AC, AC, TN }, 	 //	 165	 4600
{ AC, TN, TN, TN, WN, AC, AC, AC, WN, TN, ST, AC, AC, AC, TN }, 	 //	 166	 4600
{ AC, TN, TN, TN, ST, AC, AC, AC, WN, AC, ST, AC, AC, AC, KN }, 	 //	 167	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, WN, KN, ST, AC, AC, AC, QN }, 	 //	 168	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, QN, ST, AC, AC, AC, PF }, 	 //	 169	 4600
{ AC, TN, TN, TN, QN, AC, AC, AC, WN, PF, ST, AC, AC, AC, JA }, 	 //	 170	 4600
{ AC, TN, TN, TN, PF, AC, AC, AC, WN, JA, ST, AC, AC, AC, TN }, 	 //	 171	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, WN, AC, ST, AC, AC, AC, SK }, 	 //	 172	 4600
{ AC, TN, TN, TN, AC, AC, AC, AC, WN, SK, ST, AC, AC, AC, KN }, 	 //	 173	 4600
{ AC, TN, TN, TN, SK, AC, AC, AC, WN, KN, ST, AC, AC, AC, KN }, 	 //	 174	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, KN, ST, AC, AC, AC, KN }, 	 //	 175	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, KN, ST, AC, AC, AC, CR }, 	 //	 176	 4600
{ AC, TN, TN, TN, CR, AC, AC, AC, WN, QN, ST, AC, AC, AC, KN }, 	 //	 177	 4600
{ AC, TN, TN, TN, KN, AC, AC, AC, WN, AC, ST, AC, AC, AC, LO }, 	 //	 178	 4600
{ AC, TN, TN, JA, JA, AC, AC, AC, TN, WN, ST, AC, AC, AC, TN }, 	 //	 179	 4600
{ AC, TN, TN, JA, WN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 180	 4600
{ AC, TN, TN, JA, TN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 181	 4600
{ AC, TN, TN, JA, PF, AC, AC, AC, TN, JA, ST, AC, AC, AC, TN }, 	 //	 182	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, TN }, 	 //	 183	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, TN, ST, AC, AC, AC, ST }, 	 //	 184	 4600
{ AC, AC, TN, JA, JA, AC, AC, AC, TN, WN, ST, AC, AC, AC, TN }, 	 //	 185	 4600
{ AC, AC, TN, JA, WN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 186	 4600
{ AC, AC, TN, JA, TN, AC, AC, AC, TN, TN, ST, AC, AC, AC, TN }, 	 //	 187	 4600
{ AC, AC, TN, JA, PF, AC, AC, AC, TN, JA, ST, AC, AC, AC, TN }, 	 //	 188	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, ST, ST, PF, AC, AC, AC }, 	 //	 189	 4600
{ AC, AC, TN, TN, TN, AC, AC, AC, WN, AC, ST, PF, AC, AC, AC }, 	 //	 190	 4600
{ AC, KN, TN, TN, TN, AC, AC, AC, WN, ST, ST, SH, AC, AC, AC }, 	 //	 191	 4600
{ AC, KN, TN, TN, TN, AC, AC, AC, WN, AC, ST, SH, AC, AC, AC }, 	 //	 192	 4600
{ AC, TN, TN, TN, AC, ST, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 193	 4600
{ AC, TN, TN, TN, AC, ST, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 194	 4600
{ AC, TN, TN, TN, AC, ST, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 195	 4600
{ AC, TN, TN, TN, AC, ST, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 196	 4600
{ AC, TN, TN, TN, AC, ST, WN, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 197	 4600
{ AC, TN, TN, TN, AC, ST, WN, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 198	 4600
{ ST, SH, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 199	 4600
{ ST, SH, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 200	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 201	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 202	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, ST, KN, LO, AC, AC, AC }, 	 //	 203	 4600
{ ST, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 204	 4600
{ ST, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 205	 4600
{ ST, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 206	 4600
{ ST, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 207	 4600
{ ST, TN, TN, TN, AC, KN, WN, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 208	 4600
{ ST, TN, TN, TN, AC, KN, WN, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 209	 4600
{ ST, WN, TN, TN, TN, KN, AC, AC, AC, ST, KN, KN, AC, AC, AC }, 	 //	 210	 4600
{ ST, TN, TN, TN, CR, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 211	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 212	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 213	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 214	 4600
{ ST, TN, TN, TN, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 215	 4600
{ ST, TN, TN, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 216	 4600
{ ST, TN, TN, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SH }, 	 //	 217	 4600
{ ST, TN, TN, TN, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 218	 4600
{ ST, TN, TN, TN, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 219	 4600
{ ST, TN, TN, TN, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 220	 4600
{ ST, TN, TN, TN, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 221	 4600
{ ST, TN, TN, TN, JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN }, 	 //	 222	 4600
{ ST, TN, TN, TN, WN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 223	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF }, 	 //	 224	 4600
{ ST, TN, TN, TN, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC, JA }, 	 //	 225	 4600
{ ST, TN, TN, TN, PF, KN, AC, AC, AC, JA, KN, AC, AC, AC, TN }, 	 //	 226	 4600
{ ST, TN, TN, TN, SK, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 227	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 228	 4600
{ ST, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 229	 4600
{ ST, TN, TN, TN, CR, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 230	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 231	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 232	 4600
{ ST, AC, TN, TN, TN, KN, AC, AC, AC, ST, KN, PF, AC, AC, AC }, 	 //	 233	 4600
{ ST, KN, TN, TN, TN, KN, AC, AC, AC, ST, KN, SH, AC, AC, AC }, 	 //	 234	 4600
{ KN, SH, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 235	 4600
{ KN, SH, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 236	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 237	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 238	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, ST, KN, LO, AC, AC, AC }, 	 //	 239	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 240	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 241	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 242	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 243	 4600
{ KN, TN, TN, TN, AC, KN, WN, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 244	 4600
{ KN, TN, TN, TN, AC, KN, WN, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 245	 4600
{ KN, WN, TN, TN, TN, KN, AC, AC, AC, ST, KN, KN, AC, AC, AC }, 	 //	 246	 4600
{ KN, TN, TN, TN, CR, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 247	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 248	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 249	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 250	 4600
{ KN, TN, TN, TN, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 251	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 252	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SH }, 	 //	 253	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 254	 4600
{ KN, TN, TN, TN, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 255	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 256	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 257	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN }, 	 //	 258	 4600
{ KN, TN, TN, TN, WN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 259	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF }, 	 //	 260	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC, JA }, 	 //	 261	 4600
{ KN, TN, TN, TN, PF, KN, AC, AC, AC, JA, KN, AC, AC, AC, TN }, 	 //	 262	 4600
{ KN, TN, TN, TN, SK, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 263	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 264	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 265	 4600
{ KN, TN, TN, TN, CR, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 266	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 267	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 268	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, ST, KN, PF, AC, AC, AC }, 	 //	 269	 4600
{ KN, KN, TN, TN, TN, KN, AC, AC, AC, ST, KN, SH, AC, AC, AC }, 	 //	 270	 4600
{ KN, SH, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 271	 4600
{ KN, SH, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, ST }, 	 //	 272	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 273	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, ST }, 	 //	 274	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, ST, SK, LO, AC, AC, AC }, 	 //	 275	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC }, 	 //	 276	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC }, 	 //	 277	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, WN, AC, AC, AC }, 	 //	 278	 4600
{ KN, TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, WN, AC, AC, AC }, 	 //	 279	 4600
{ KN, TN, TN, TN, AC, KN, WN, AC, AC, AC, SK, AC, AC, AC, CR }, 	 //	 280	 4600
{ KN, TN, TN, TN, AC, KN, WN, AC, AC, AC, SK, AC, AC, AC, SK }, 	 //	 281	 4600
{ KN, WN, TN, TN, TN, KN, AC, AC, AC, ST, SK, KN, AC, AC, AC }, 	 //	 282	 4600
{ KN, TN, TN, TN, CR, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 283	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 284	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK }, 	 //	 285	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN }, 	 //	 286	 4600
{ KN, TN, TN, TN, SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN }, 	 //	 287	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN }, 	 //	 288	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, SH }, 	 //	 289	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, SH, SK, AC, AC, AC, JA }, 	 //	 290	 4600
{ KN, TN, TN, TN, SH, KN, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 291	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 292	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, JA, SK, AC, AC, AC, WN }, 	 //	 293	 4600
{ KN, TN, TN, TN, JA, KN, AC, AC, AC, WN, SK, AC, AC, AC, TN }, 	 //	 294	 4600
{ KN, TN, TN, TN, WN, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 295	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, QN, SK, AC, AC, AC, PF }, 	 //	 296	 4600
{ KN, TN, TN, TN, QN, KN, AC, AC, AC, PF, SK, AC, AC, AC, JA }, 	 //	 297	 4600
{ KN, TN, TN, TN, PF, KN, AC, AC, AC, JA, SK, AC, AC, AC, TN }, 	 //	 298	 4600
{ KN, TN, TN, TN, SK, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 299	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 300	 4600
{ KN, TN, TN, TN, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 301	 4600
{ KN, TN, TN, TN, CR, KN, AC, AC, AC, QN, SK, AC, AC, AC, KN }, 	 //	 302	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 303	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, ST }, 	 //	 304	 4600
{ KN, AC, TN, TN, TN, KN, AC, AC, AC, ST, SK, PF, AC, AC, AC }, 	 //	 305	 4600
{ KN, KN, TN, TN, TN, KN, AC, AC, AC, ST, SK, SH, AC, AC, AC }, 	 //	 306	 4600
{ KN, SH, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 307	 4600
{ KN, SH, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 308	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 309	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 310	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, ST, QN, LO, AC, AC, AC }, 	 //	 311	 4600
{ KN, TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 312	 4600
{ KN, TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 313	 4600
{ KN, TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 314	 4600
{ KN, TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 315	 4600
{ KN, TN, TN, TN, AC, SK, WN, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 316	 4600
{ KN, TN, TN, TN, AC, SK, WN, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 317	 4600
{ KN, WN, TN, TN, TN, SK, AC, AC, AC, ST, QN, KN, AC, AC, AC }, 	 //	 318	 4600
{ KN, TN, TN, TN, CR, SK, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 319	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 320	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC, SK }, 	 //	 321	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN }, 	 //	 322	 4600
{ KN, TN, TN, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 323	 4600
{ KN, TN, TN, TN, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 324	 4600
{ KN, TN, TN, TN, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 325	 4600
{ KN, TN, TN, TN, QN, SK, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 326	 4600
{ KN, TN, TN, TN, SH, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 327	 4600
{ KN, TN, TN, TN, JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 328	 4600
{ KN, TN, TN, TN, JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 329	 4600
{ KN, TN, TN, TN, JA, SK, AC, AC, AC, WN, QN, AC, AC, AC, TN }, 	 //	 330	 4600
{ KN, TN, TN, TN, WN, SK, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 331	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 332	 4600
{ KN, TN, TN, TN, QN, SK, AC, AC, AC, PF, QN, AC, AC, AC, JA }, 	 //	 333	 4600
{ KN, TN, TN, TN, PF, SK, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 334	 4600
{ KN, TN, TN, TN, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 335	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 336	 4600
{ KN, TN, TN, TN, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC, CR }, 	 //	 337	 4600
{ KN, TN, TN, TN, CR, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 338	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 339	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 340	 4600
{ KN, AC, TN, TN, TN, SK, AC, AC, AC, ST, QN, PF, AC, AC, AC }, 	 //	 341	 4600
{ KN, KN, TN, TN, TN, SK, AC, AC, AC, ST, QN, SH, AC, AC, AC }, 	 //	 342	 4600
{ SK, SH, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 343	 4600
{ SK, SH, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 344	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 345	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 346	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, ST, QN, LO, AC, AC, AC }, 	 //	 347	 4600
{ SK, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 348	 4600
{ SK, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 349	 4600
{ SK, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 350	 4600
{ SK, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 351	 4600
{ SK, TN, TN, TN, AC, QN, WN, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 352	 4600
{ SK, TN, TN, TN, AC, QN, WN, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 353	 4600
{ SK, WN, TN, TN, TN, QN, AC, AC, AC, ST, QN, KN, AC, AC, AC }, 	 //	 354	 4600
{ SK, TN, TN, TN, CR, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 355	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 356	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK }, 	 //	 357	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, SK, QN, AC, AC, AC, QN }, 	 //	 358	 4600
{ SK, TN, TN, TN, SK, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 359	 4600
{ SK, TN, TN, TN, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 360	 4600
{ SK, TN, TN, TN, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 361	 4600
{ SK, TN, TN, TN, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 362	 4600
{ SK, TN, TN, TN, SH, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 363	 4600
{ SK, TN, TN, TN, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 364	 4600
{ SK, TN, TN, TN, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 365	 4600
{ SK, TN, TN, TN, JA, QN, AC, AC, AC, WN, QN, AC, AC, AC, TN }, 	 //	 366	 4600
{ SK, TN, TN, TN, WN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 367	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 368	 4600
{ SK, TN, TN, TN, QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA }, 	 //	 369	 4600
{ SK, TN, TN, TN, PF, QN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 370	 4600
{ SK, TN, TN, TN, SK, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 371	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 372	 4600
{ SK, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, CR }, 	 //	 373	 4600
{ SK, TN, TN, TN, CR, QN, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 374	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 375	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 376	 4600
{ SK, AC, TN, TN, TN, QN, AC, AC, AC, ST, QN, PF, AC, AC, AC }, 	 //	 377	 4600
{ SK, KN, TN, TN, TN, QN, AC, AC, AC, ST, QN, SH, AC, AC, AC }, 	 //	 378	 4600
{ QN, SH, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 379	 4600
{ QN, SH, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 380	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 381	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 382	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, ST, QN, LO, AC, AC, AC }, 	 //	 383	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 384	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 385	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 386	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 387	 4600
{ QN, TN, TN, TN, AC, QN, WN, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 388	 4600
{ QN, TN, TN, TN, AC, QN, WN, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 389	 4600
{ QN, WN, TN, TN, TN, QN, AC, AC, AC, ST, QN, KN, AC, AC, AC }, 	 //	 390	 4600
{ QN, TN, TN, TN, CR, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 391	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 392	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK }, 	 //	 393	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, SK, QN, AC, AC, AC, QN }, 	 //	 394	 4600
{ QN, TN, TN, TN, SK, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 395	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 396	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 397	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 398	 4600
{ QN, TN, TN, TN, SH, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 399	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 400	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 401	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, WN, QN, AC, AC, AC, TN }, 	 //	 402	 4600
{ QN, TN, TN, TN, WN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 403	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 404	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA }, 	 //	 405	 4600
{ QN, TN, TN, TN, PF, QN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 406	 4600
{ QN, TN, TN, TN, SK, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 407	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 408	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, CR }, 	 //	 409	 4600
{ QN, TN, TN, TN, CR, QN, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 410	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 411	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 412	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, ST, QN, PF, AC, AC, AC }, 	 //	 413	 4600
{ QN, KN, TN, TN, TN, QN, AC, AC, AC, ST, QN, SH, AC, AC, AC }, 	 //	 414	 4600
{ QN, SH, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 415	 4600
{ QN, SH, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, ST }, 	 //	 416	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 417	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, ST }, 	 //	 418	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, ST, SH, LO, AC, AC, AC }, 	 //	 419	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC }, 	 //	 420	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC }, 	 //	 421	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, WN, AC, AC, AC }, 	 //	 422	 4600
{ QN, TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, WN, AC, AC, AC }, 	 //	 423	 4600
{ QN, TN, TN, TN, AC, QN, WN, AC, AC, AC, SH, AC, AC, AC, CR }, 	 //	 424	 4600
{ QN, TN, TN, TN, AC, QN, WN, AC, AC, AC, SH, AC, AC, AC, SK }, 	 //	 425	 4600
{ QN, WN, TN, TN, TN, QN, AC, AC, AC, ST, SH, KN, AC, AC, AC }, 	 //	 426	 4600
{ QN, TN, TN, TN, CR, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN }, 	 //	 427	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN }, 	 //	 428	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, SK }, 	 //	 429	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, SK, SH, AC, AC, AC, QN }, 	 //	 430	 4600
{ QN, TN, TN, TN, SK, QN, AC, AC, AC, QN, SH, AC, AC, AC, QN }, 	 //	 431	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, QN, SH, AC, AC, AC, QN }, 	 //	 432	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, QN, SH, AC, AC, AC, SH }, 	 //	 433	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, SH, SH, AC, AC, AC, JA }, 	 //	 434	 4600
{ QN, TN, TN, TN, SH, QN, AC, AC, AC, JA, SH, AC, AC, AC, JA }, 	 //	 435	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, JA, SH, AC, AC, AC, JA }, 	 //	 436	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, JA, SH, AC, AC, AC, WN }, 	 //	 437	 4600
{ QN, TN, TN, TN, JA, QN, AC, AC, AC, WN, SH, AC, AC, AC, TN }, 	 //	 438	 4600
{ QN, TN, TN, TN, WN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 439	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, QN, SH, AC, AC, AC, PF }, 	 //	 440	 4600
{ QN, TN, TN, TN, QN, QN, AC, AC, AC, PF, SH, AC, AC, AC, JA }, 	 //	 441	 4600
{ QN, TN, TN, TN, PF, QN, AC, AC, AC, JA, SH, AC, AC, AC, TN }, 	 //	 442	 4600
{ QN, TN, TN, TN, SK, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN }, 	 //	 443	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN }, 	 //	 444	 4600
{ QN, TN, TN, TN, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, CR }, 	 //	 445	 4600
{ QN, TN, TN, TN, CR, QN, AC, AC, AC, QN, SH, AC, AC, AC, KN }, 	 //	 446	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 447	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, ST }, 	 //	 448	 4600
{ QN, AC, TN, TN, TN, QN, AC, AC, AC, ST, SH, PF, AC, AC, AC }, 	 //	 449	 4600
{ QN, KN, TN, TN, TN, QN, AC, AC, AC, ST, SH, SH, AC, AC, AC }, 	 //	 450	 4600
{ QN, SH, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 451	 4600
{ QN, SH, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 452	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 453	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 454	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, ST, JA, LO, AC, AC, AC }, 	 //	 455	 4600
{ QN, TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 456	 4600
{ QN, TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 457	 4600
{ QN, TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 458	 4600
{ QN, TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 459	 4600
{ QN, TN, TN, TN, AC, SH, WN, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 460	 4600
{ QN, TN, TN, TN, AC, SH, WN, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 461	 4600
{ QN, WN, TN, TN, TN, SH, AC, AC, AC, ST, JA, KN, AC, AC, AC }, 	 //	 462	 4600
{ QN, TN, TN, TN, CR, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 463	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 464	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 465	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 466	 4600
{ QN, TN, TN, TN, SK, SH, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 467	 4600
{ QN, TN, TN, TN, QN, SH, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 468	 4600
{ QN, TN, TN, TN, QN, SH, AC, AC, AC, QN, JA, AC, AC, AC, SH }, 	 //	 469	 4600
{ QN, TN, TN, TN, QN, SH, AC, AC, AC, SH, JA, AC, AC, AC, JA }, 	 //	 470	 4600
{ QN, TN, TN, TN, SH, SH, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 471	 4600
{ QN, TN, TN, TN, JA, SH, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 472	 4600
{ QN, TN, TN, TN, JA, SH, AC, AC, AC, JA, JA, AC, AC, AC, WN }, 	 //	 473	 4600
{ QN, TN, TN, TN, JA, SH, AC, AC, AC, WN, JA, AC, AC, AC, TN }, 	 //	 474	 4600
{ QN, TN, TN, TN, WN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 475	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, QN, JA, AC, AC, AC, PF }, 	 //	 476	 4600
{ QN, TN, TN, TN, QN, SH, AC, AC, AC, PF, JA, AC, AC, AC, JA }, 	 //	 477	 4600
{ QN, TN, TN, TN, PF, SH, AC, AC, AC, JA, JA, AC, AC, AC, TN }, 	 //	 478	 4600
{ QN, TN, TN, TN, SK, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 479	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 480	 4600
{ QN, TN, TN, TN, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 481	 4600
{ QN, TN, TN, TN, CR, SH, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 482	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 483	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 484	 4600
{ QN, AC, TN, TN, TN, SH, AC, AC, AC, ST, JA, PF, AC, AC, AC }, 	 //	 485	 4600
{ QN, KN, TN, TN, TN, SH, AC, AC, AC, ST, JA, SH, AC, AC, AC }, 	 //	 486	 4600
{ SH, SH, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 487	 4600
{ SH, SH, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 488	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 489	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 490	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, ST, JA, LO, AC, AC, AC }, 	 //	 491	 4600
{ SH, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 492	 4600
{ SH, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 493	 4600
{ SH, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 494	 4600
{ SH, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 495	 4600
{ SH, TN, TN, TN, AC, JA, WN, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 496	 4600
{ SH, TN, TN, TN, AC, JA, WN, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 497	 4600
{ SH, WN, TN, TN, TN, JA, AC, AC, AC, ST, JA, KN, AC, AC, AC }, 	 //	 498	 4600
{ SH, TN, TN, TN, CR, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 499	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 500	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 501	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 502	 4600
{ SH, TN, TN, TN, SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 503	 4600
{ SH, TN, TN, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 504	 4600
{ SH, TN, TN, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, SH }, 	 //	 505	 4600
{ SH, TN, TN, TN, QN, JA, AC, AC, AC, SH, JA, AC, AC, AC, JA }, 	 //	 506	 4600
{ SH, TN, TN, TN, SH, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 507	 4600
{ SH, TN, TN, TN, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 508	 4600
{ SH, TN, TN, TN, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, WN }, 	 //	 509	 4600
{ SH, TN, TN, TN, JA, JA, AC, AC, AC, WN, JA, AC, AC, AC, TN }, 	 //	 510	 4600
{ SH, TN, TN, TN, WN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 511	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, QN, JA, AC, AC, AC, PF }, 	 //	 512	 4600
{ SH, TN, TN, TN, QN, JA, AC, AC, AC, PF, JA, AC, AC, AC, JA }, 	 //	 513	 4600
{ SH, TN, TN, TN, PF, JA, AC, AC, AC, JA, JA, AC, AC, AC, TN }, 	 //	 514	 4600
{ SH, TN, TN, TN, SK, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 515	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 516	 4600
{ SH, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 517	 4600
{ SH, TN, TN, TN, CR, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 518	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 519	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 520	 4600
{ SH, AC, TN, TN, TN, JA, AC, AC, AC, ST, JA, PF, AC, AC, AC }, 	 //	 521	 4600
{ SH, KN, TN, TN, TN, JA, AC, AC, AC, ST, JA, SH, AC, AC, AC }, 	 //	 522	 4600
{ JA, SH, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 523	 4600
{ JA, SH, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 524	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 525	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 526	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, ST, JA, LO, AC, AC, AC }, 	 //	 527	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 528	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 529	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 530	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, WN, AC, AC, AC }, 	 //	 531	 4600
{ JA, TN, TN, TN, AC, JA, WN, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 532	 4600
{ JA, TN, TN, TN, AC, JA, WN, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 533	 4600
{ JA, WN, TN, TN, TN, JA, AC, AC, AC, ST, JA, KN, AC, AC, AC }, 	 //	 534	 4600
{ JA, TN, TN, TN, CR, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 535	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 536	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 537	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 538	 4600
{ JA, TN, TN, TN, SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 539	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 540	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, SH }, 	 //	 541	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, SH, JA, AC, AC, AC, JA }, 	 //	 542	 4600
{ JA, TN, TN, TN, SH, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 543	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 544	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, WN }, 	 //	 545	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, WN, JA, AC, AC, AC, TN }, 	 //	 546	 4600
{ JA, TN, TN, TN, WN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 547	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, QN, JA, AC, AC, AC, PF }, 	 //	 548	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, PF, JA, AC, AC, AC, JA }, 	 //	 549	 4600
{ JA, TN, TN, TN, PF, JA, AC, AC, AC, JA, JA, AC, AC, AC, TN }, 	 //	 550	 4600
{ JA, TN, TN, TN, SK, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 551	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 552	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 553	 4600
{ JA, TN, TN, TN, CR, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 554	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 555	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 556	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, ST, JA, PF, AC, AC, AC }, 	 //	 557	 4600
{ JA, KN, TN, TN, TN, JA, AC, AC, AC, ST, JA, SH, AC, AC, AC }, 	 //	 558	 4600
{ JA, SH, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 559	 4600
{ JA, SH, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, ST }, 	 //	 560	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 561	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, ST }, 	 //	 562	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, ST, WN, LO, AC, AC, AC }, 	 //	 563	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC }, 	 //	 564	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC }, 	 //	 565	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, WN, AC, AC, AC }, 	 //	 566	 4600
{ JA, TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, WN, AC, AC, AC }, 	 //	 567	 4600
{ JA, TN, TN, TN, AC, JA, WN, AC, AC, AC, WN, AC, AC, AC, CR }, 	 //	 568	 4600
{ JA, TN, TN, TN, AC, JA, WN, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 569	 4600
{ JA, WN, TN, TN, TN, JA, AC, AC, AC, ST, WN, KN, AC, AC, AC }, 	 //	 570	 4600
{ JA, TN, TN, TN, CR, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN }, 	 //	 571	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN }, 	 //	 572	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, SK }, 	 //	 573	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, SK, WN, AC, AC, AC, QN }, 	 //	 574	 4600
{ JA, TN, TN, TN, SK, JA, AC, AC, AC, QN, WN, AC, AC, AC, QN }, 	 //	 575	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, QN, WN, AC, AC, AC, QN }, 	 //	 576	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, QN, WN, AC, AC, AC, SH }, 	 //	 577	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, SH, WN, AC, AC, AC, JA }, 	 //	 578	 4600
{ JA, TN, TN, TN, SH, JA, AC, AC, AC, JA, WN, AC, AC, AC, JA }, 	 //	 579	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, JA, WN, AC, AC, AC, JA }, 	 //	 580	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, JA, WN, AC, AC, AC, WN }, 	 //	 581	 4600
{ JA, TN, TN, TN, JA, JA, AC, AC, AC, WN, WN, AC, AC, AC, TN }, 	 //	 582	 4600
{ JA, TN, TN, TN, WN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 583	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, QN, WN, AC, AC, AC, PF }, 	 //	 584	 4600
{ JA, TN, TN, TN, QN, JA, AC, AC, AC, PF, WN, AC, AC, AC, JA }, 	 //	 585	 4600
{ JA, TN, TN, TN, PF, JA, AC, AC, AC, JA, WN, AC, AC, AC, TN }, 	 //	 586	 4600
{ JA, TN, TN, TN, SK, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN }, 	 //	 587	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN }, 	 //	 588	 4600
{ JA, TN, TN, TN, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, CR }, 	 //	 589	 4600
{ JA, TN, TN, TN, CR, JA, AC, AC, AC, QN, WN, AC, AC, AC, KN }, 	 //	 590	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 591	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, ST }, 	 //	 592	 4600
{ JA, AC, TN, TN, TN, JA, AC, AC, AC, ST, WN, PF, AC, AC, AC }, 	 //	 593	 4600
{ JA, KN, TN, TN, TN, JA, AC, AC, AC, ST, WN, SH, AC, AC, AC }, 	 //	 594	 4600
{ JA, SH, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 595	 4600
{ JA, SH, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 596	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 597	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 598	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, ST, TN, LO, AC, AC, AC }, 	 //	 599	 4600
{ JA, SH, TN, PF, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 600	 4600
{ JA, SH, TN, PF, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 601	 4600
{ JA, SH, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 602	 4600
{ JA, SH, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 603	 4600
{ JA, SH, TN, TN, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 604	 4600
{ JA, SH, TN, TN, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 605	 4600
{ JA, SH, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 606	 4600
{ JA, SH, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 607	 4600
{ JA, TN, TN, PF, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 608	 4600
{ JA, TN, TN, PF, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 609	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 610	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 611	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 612	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 613	 4600
{ JA, TN, TN, PF, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 614	 4600
{ JA, TN, TN, PF, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 615	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 616	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 617	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 618	 4600
{ JA, TN, TN, AC, AC, WN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 619	 4600
{ JA, TN, TN, TN, AC, WN, WN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 620	 4600
{ JA, TN, TN, TN, AC, WN, WN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 621	 4600
{ JA, WN, TN, TN, TN, WN, AC, AC, AC, ST, TN, KN, AC, AC, AC }, 	 //	 622	 4600
{ JA, JA, TN, PF, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 623	 4600
{ JA, JA, TN, PF, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 624	 4600
{ JA, JA, TN, AC, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 625	 4600
{ JA, JA, TN, AC, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 626	 4600
{ JA, JA, TN, TN, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 627	 4600
{ JA, JA, TN, TN, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 628	 4600
{ JA, JA, TN, AC, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 629	 4600
{ JA, JA, TN, AC, AC, WN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 630	 4600
{ JA, TN, TN, TN, CR, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 631	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 632	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 633	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 634	 4600
{ JA, TN, TN, TN, SK, WN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 635	 4600
{ JA, TN, TN, TN, QN, WN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 636	 4600
{ JA, TN, TN, TN, QN, WN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 637	 4600
{ JA, TN, TN, TN, QN, WN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 638	 4600
{ JA, TN, TN, TN, SH, WN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 639	 4600
{ JA, TN, TN, TN, JA, WN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 640	 4600
{ JA, TN, TN, TN, JA, WN, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 641	 4600
{ JA, TN, TN, TN, JA, WN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 642	 4600
{ JA, TN, TN, TN, WN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 643	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 644	 4600
{ JA, TN, TN, TN, QN, WN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 645	 4600
{ JA, TN, TN, TN, PF, WN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 646	 4600
{ JA, TN, TN, TN, SK, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 647	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 648	 4600
{ JA, TN, TN, TN, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 649	 4600
{ JA, TN, TN, TN, CR, WN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 650	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 651	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 652	 4600
{ JA, AC, TN, TN, TN, WN, AC, AC, AC, ST, TN, PF, AC, AC, AC }, 	 //	 653	 4600
{ JA, KN, TN, TN, TN, WN, AC, AC, AC, ST, TN, SH, AC, AC, AC }, 	 //	 654	 4600
{ WN, SH, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 655	 4600
{ WN, SH, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 656	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 657	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 658	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, ST, TN, LO, AC, AC, AC }, 	 //	 659	 4600
{ WN, SH, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 660	 4600
{ WN, SH, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 661	 4600
{ WN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 662	 4600
{ WN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 663	 4600
{ WN, SH, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 664	 4600
{ WN, SH, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 665	 4600
{ WN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 666	 4600
{ WN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 667	 4600
{ WN, TN, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 668	 4600
{ WN, TN, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 669	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 670	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 671	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 672	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 673	 4600
{ WN, TN, TN, PF, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 674	 4600
{ WN, TN, TN, PF, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 675	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 676	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 677	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 678	 4600
{ WN, TN, TN, AC, AC, TN, TN, AC, AC, AC, TN, WN, AC, AC, AC }, 	 //	 679	 4600
{ WN, TN, TN, TN, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 680	 4600
{ WN, TN, TN, TN, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 681	 4600
{ WN, WN, TN, TN, TN, TN, AC, AC, AC, ST, TN, KN, AC, AC, AC }, 	 //	 682	 4600
{ WN, JA, TN, PF, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 683	 4600
{ WN, JA, TN, PF, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 684	 4600
{ WN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 685	 4600
{ WN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 686	 4600
{ WN, JA, TN, TN, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 687	 4600
{ WN, JA, TN, TN, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 688	 4600
{ WN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 689	 4600
{ WN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 690	 4600
{ WN, TN, TN, TN, CR, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 691	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 692	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 693	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 694	 4600
{ WN, TN, TN, TN, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 695	 4600
{ WN, TN, TN, TN, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 696	 4600
{ WN, TN, TN, TN, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 697	 4600
{ WN, TN, TN, TN, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 698	 4600
{ WN, TN, TN, TN, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 699	 4600
{ WN, TN, TN, TN, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 700	 4600
{ WN, TN, TN, TN, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 701	 4600
{ WN, TN, TN, TN, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 702	 4600
{ WN, TN, TN, TN, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 703	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 704	 4600
{ WN, TN, TN, TN, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 705	 4600
{ WN, TN, TN, TN, PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 706	 4600
{ WN, TN, TN, TN, SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 707	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 708	 4600
{ WN, TN, TN, TN, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 709	 4600
{ WN, TN, TN, TN, CR, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 710	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 711	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 712	 4600
{ WN, AC, TN, TN, TN, TN, AC, AC, AC, ST, TN, PF, AC, AC, AC }, 	 //	 713	 4600
{ WN, KN, TN, TN, TN, TN, AC, AC, AC, ST, TN, SH, AC, AC, AC }, 	 //	 714	 4600
{ TN, SH, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 715	 4600
{ TN, SH, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 716	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 717	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 718	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, ST, TN, LO, AC, AC, AC }, 	 //	 719	 4600
{ TN, SH, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 720	 4600
{ TN, SH, TN, PF, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 721	 4600
{ TN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 722	 4600
{ TN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 723	 4600
{ TN, SH, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 724	 4600
{ TN, SH, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 725	 4600
{ TN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 726	 4600
{ TN, SH, TN, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 727	 4600
{ TN, TN, TN, PF, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 728	 4600
{ TN, TN, TN, PF, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 729	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 730	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 731	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 732	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 733	 4600
{ TN, WN, TN, TN, TN, TN, AC, AC, AC, ST, TN, KN, AC, AC, AC }, 	 //	 734	 4600
{ TN, JA, TN, PF, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 735	 4600
{ TN, JA, TN, PF, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 736	 4600
{ TN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 737	 4600
{ TN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 738	 4600
{ TN, JA, TN, TN, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 739	 4600
{ TN, JA, TN, TN, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 740	 4600
{ TN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 741	 4600
{ TN, JA, TN, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 742	 4600
{ TN, TN, TN, PF, CR, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 743	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 744	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 745	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 746	 4600
{ TN, TN, TN, PF, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 747	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 748	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 749	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 750	 4600
{ TN, TN, TN, PF, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 751	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 752	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 753	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 754	 4600
{ TN, TN, TN, PF, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 755	 4600
{ TN, TN, TN, PF, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 756	 4600
{ TN, TN, TN, PF, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 757	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 758	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 759	 4600
{ TN, TN, TN, PF, PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 760	 4600
{ TN, TN, TN, PF, SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 761	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 762	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 763	 4600
{ TN, TN, TN, PF, CR, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 764	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 765	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 766	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 767	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 768	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 769	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 770	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 771	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 772	 4600
{ TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 773	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 774	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 775	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 776	 4600
{ TN, TN, TN, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 777	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 778	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 779	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 780	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 781	 4600
{ TN, TN, TN, AC, PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 782	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 783	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 784	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 785	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 786	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 787	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 788	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 789	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 790	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 791	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 792	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 793	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 794	 4600
{ TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 795	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 796	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 797	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 798	 4600
{ TN, TN, TN, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 799	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 800	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 801	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 802	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 803	 4600
{ TN, TN, TN, AC, PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 804	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 805	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 806	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 807	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 808	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 809	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 810	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, ST, TN, PF, AC, AC, AC }, 	 //	 811	 4600
{ TN, KN, TN, TN, TN, TN, AC, AC, AC, ST, TN, SH, AC, AC, AC }, 	 //	 812	 4600
{ TN, SH, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 813	 4600
{ TN, SH, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 814	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 815	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 816	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, ST, ST, LO, AC, AC, AC }, 	 //	 817	 4600
{ TN, TN, TN, PF, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 818	 4600
{ TN, TN, TN, PF, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 819	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 820	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 821	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 822	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 823	 4600
{ TN, TN, TN, PF, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 824	 4600
{ TN, TN, TN, PF, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 825	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 826	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 827	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 828	 4600
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 829	 4600
{ TN, TN, TN, PF, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 830	 4600
{ TN, TN, TN, PF, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 831	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 832	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 833	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 834	 4600
{ TN, TN, TN, AC, AC, TN, WN, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 835	 4600
{ TN, WN, TN, TN, TN, TN, AC, AC, AC, ST, ST, KN, AC, AC, AC }, 	 //	 836	 4600
{ TN, TN, TN, PF, CR, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 837	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 838	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, SK }, 	 //	 839	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, SK, ST, AC, AC, AC, QN }, 	 //	 840	 4600
{ TN, TN, TN, PF, SK, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 841	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 842	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 843	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 844	 4600
{ TN, TN, TN, PF, SH, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 845	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 846	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 847	 4600
{ TN, TN, TN, PF, JA, TN, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 848	 4600
{ TN, TN, TN, PF, WN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 849	 4600
{ TN, TN, TN, PF, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 850	 4600
{ TN, TN, TN, PF, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 851	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, QN, ST, AC, AC, AC, PF }, 	 //	 852	 4600
{ TN, TN, TN, PF, QN, TN, AC, AC, AC, PF, ST, AC, AC, AC, JA }, 	 //	 853	 4600
{ TN, TN, TN, PF, PF, TN, AC, AC, AC, JA, ST, AC, AC, AC, TN }, 	 //	 854	 4600
{ TN, TN, TN, PF, SK, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 855	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 856	 4600
{ TN, TN, TN, PF, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 857	 4600
{ TN, TN, TN, PF, CR, TN, AC, AC, AC, QN, ST, AC, AC, AC, KN }, 	 //	 858	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 859	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 860	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, SK }, 	 //	 861	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, ST, AC, AC, AC, QN }, 	 //	 862	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 863	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 864	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 865	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 866	 4600
{ TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 867	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 868	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 869	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 870	 4600
{ TN, TN, TN, AC, WN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 871	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 872	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 873	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, QN, ST, AC, AC, AC, PF }, 	 //	 874	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, PF, ST, AC, AC, AC, JA }, 	 //	 875	 4600
{ TN, TN, TN, AC, PF, TN, AC, AC, AC, JA, ST, AC, AC, AC, TN }, 	 //	 876	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 877	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 878	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 879	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, QN, ST, AC, AC, AC, KN }, 	 //	 880	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 881	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 882	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, SK }, 	 //	 883	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, SK, ST, AC, AC, AC, QN }, 	 //	 884	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 885	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 886	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 887	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 888	 4600
{ TN, TN, TN, AC, SH, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 889	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 890	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 891	 4600
{ TN, TN, TN, AC, JA, TN, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 892	 4600
{ TN, TN, TN, AC, WN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 893	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 894	 4600
{ TN, TN, TN, AC, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 895	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, QN, ST, AC, AC, AC, PF }, 	 //	 896	 4600
{ TN, TN, TN, AC, QN, TN, AC, AC, AC, PF, ST, AC, AC, AC, JA }, 	 //	 897	 4600
{ TN, TN, TN, AC, PF, TN, AC, AC, AC, JA, ST, AC, AC, AC, TN }, 	 //	 898	 4600
{ TN, TN, TN, AC, SK, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 899	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 900	 4600
{ TN, TN, TN, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 901	 4600
{ TN, TN, TN, AC, CR, TN, AC, AC, AC, QN, ST, AC, AC, AC, KN }, 	 //	 902	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 903	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 904	 4600
{ TN, AC, TN, TN, TN, TN, AC, AC, AC, ST, ST, PF, AC, AC, AC }, 	 //	 905	 4600
{ TN, KN, TN, TN, TN, TN, AC, AC, AC, ST, ST, SH, AC, AC, AC }, 	 //	 906	 4600
{ TN, AC, TN, TN, TN, ST, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 907	 4600
{ TN, TN, TN, PF, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 908	 4600
{ TN, TN, TN, PF, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 909	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 910	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 911	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 912	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 913	 4600
{ TN, TN, TN, PF, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 914	 4600
{ TN, TN, TN, PF, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 915	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 916	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 917	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 918	 4600
{ TN, TN, TN, AC, AC, ST, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 919	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 920	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 921	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 922	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 923	 4600
{ TN, TN, TN, WN, AC, ST, WN, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 924	 4600
{ TN, TN, TN, WN, AC, ST, WN, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 925	 4600
{ TN, TN, TN, WN, AC, ST, WN, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 926	 4600
{ TN, TN, TN, WN, AC, ST, WN, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 927	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 928	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 929	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 930	 4600
{ TN, TN, TN, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 931	 4600
{ TN, TN, TN, KN, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 932	 4600
{ TN, TN, TN, KN, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 933	 4600
{ TN, TN, TN, KN, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 934	 4600
{ TN, TN, TN, KN, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 935	 4600
{ TN, WN, TN, TN, TN, ST, AC, AC, AC, ST, AC, KN, AC, AC, AC }, 	 //	 936	 4600
{ TN, TN, TN, AC, CR, ST, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 937	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 938	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, LO, SK }, 	 //	 939	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, SK, AC, AC, AC, LO, QN }, 	 //	 940	 4600
{ TN, TN, TN, AC, SK, ST, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 941	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 942	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, LO, SH }, 	 //	 943	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, SH, AC, AC, AC, LO, JA }, 	 //	 944	 4600
{ TN, TN, TN, AC, SH, ST, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 945	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 946	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, LO, WN }, 	 //	 947	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, WN, AC, AC, AC, LO, TN }, 	 //	 948	 4600
{ TN, TN, TN, AC, WN, ST, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 949	 4600
{ TN, TN, TN, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 950	 4600
{ TN, TN, TN, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, LO, ST }, 	 //	 951	 4600
{ TN, TN, TN, AC, TN, ST, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 952	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 953	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, PF, AC, AC, AC, LO, JA }, 	 //	 954	 4600
{ TN, TN, TN, AC, PF, ST, AC, AC, AC, JA, AC, AC, AC, LO, TN }, 	 //	 955	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 956	 4600
{ TN, TN, TN, AC, SK, ST, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 957	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 958	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, LO, CR }, 	 //	 959	 4600
{ TN, TN, TN, AC, CR, ST, AC, AC, AC, QN, AC, AC, AC, LO, KN }, 	 //	 960	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 961	 4600
{ TN, TN, TN, WN, CR, ST, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 962	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 963	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, KN, AC, AC, AC, KN, SK }, 	 //	 964	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, SK, AC, AC, AC, KN, QN }, 	 //	 965	 4600
{ TN, TN, TN, WN, SK, ST, AC, AC, AC, QN, AC, AC, AC, KN, QN }, 	 //	 966	 4600
{ TN, TN, TN, WN, QN, ST, AC, AC, AC, QN, AC, AC, AC, KN, QN }, 	 //	 967	 4600
{ TN, TN, TN, WN, QN, ST, AC, AC, AC, QN, AC, AC, AC, KN, SH }, 	 //	 968	 4600
{ TN, TN, TN, WN, QN, ST, AC, AC, AC, SH, AC, AC, AC, KN, JA }, 	 //	 969	 4600
{ TN, TN, TN, WN, SH, ST, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 970	 4600
{ TN, TN, TN, WN, JA, ST, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 971	 4600
{ TN, TN, TN, WN, JA, ST, AC, AC, AC, JA, AC, AC, AC, KN, WN }, 	 //	 972	 4600
{ TN, TN, TN, WN, JA, ST, AC, AC, AC, WN, AC, AC, AC, KN, TN }, 	 //	 973	 4600
{ TN, TN, TN, WN, WN, ST, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 974	 4600
{ TN, TN, TN, WN, TN, ST, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 975	 4600
{ TN, TN, TN, WN, TN, ST, AC, AC, AC, TN, AC, AC, AC, KN, ST }, 	 //	 976	 4600
{ TN, TN, TN, WN, TN, ST, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 977	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, QN, AC, AC, AC, KN, PF }, 	 //	 978	 4600
{ TN, TN, TN, WN, QN, ST, AC, AC, AC, PF, AC, AC, AC, KN, JA }, 	 //	 979	 4600
{ TN, TN, TN, WN, PF, ST, AC, AC, AC, JA, AC, AC, AC, KN, TN }, 	 //	 980	 4600
{ TN, TN, TN, WN, JA, ST, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 981	 4600
{ TN, TN, TN, WN, SK, ST, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 982	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 983	 4600
{ TN, TN, TN, WN, KN, ST, AC, AC, AC, KN, AC, AC, AC, KN, CR }, 	 //	 984	 4600
{ TN, TN, TN, WN, CR, ST, AC, AC, AC, QN, AC, AC, AC, KN, KN }, 	 //	 985	 4600
{ TN, TN, TN, WN, QN, ST, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 986	 4600
{ TN, TN, TN, AC, CR, ST, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 987	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 988	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, PF, SK }, 	 //	 989	 4600
{ TN, TN, TN, AC, KN, ST, AC, AC, AC, SK, AC, AC, AC, PF, QN }, 	 //	 990	 4600
{ TN, TN, TN, AC, SK, ST, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 991	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 992	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, PF, SH }, 	 //	 993	 4600
{ TN, TN, TN, AC, QN, ST, AC, AC, AC, SH, AC, AC, AC, PF, JA }, 	 //	 994	 4600
{ TN, TN, TN, AC, SH, ST, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 995	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 996	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 997	 4600
{ TN, TN, TN, AC, JA, ST, AC, AC, AC, WN, AC, AC, AC, PF, TN }, 	 //	 998	 4600
{ TN, TN, TN, AC, WN, ST, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 999	 4600
{ TN, TN, TN, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, PF, TN }};	 //	 1000	 4600
