#include "ReelDefine.h"

unsigned char L5_Outcome_2000[1000][15]={	 //	 0	 2000
{ AC, AC, PF, PF, JA, LO, AC, QN, AC, JA, AC, LO, AC, AC, WN }, 	 //	 1	 2000
{ AC, AC, AC, AC, WN, LO, LO, WN, AC, TN, AC, KN, KN, PF, TN }, 	 //	 2	 2000
{ AC, LO, KN, AC, ST, LO, KN, QN, KN, AC, AC, KN, PF, QN, KN }, 	 //	 3	 2000
{ AC, LO, PF, AC, AC, LO, KN, KN, KN, AC, AC, KN, KN, QN, AC }, 	 //	 4	 2000
{ AC, KN, KN, PF, AC, LO, KN, KN, KN, AC, AC, ST, SH, KN, CR }, 	 //	 5	 2000
{ AC, KN, KN, KN, KN, LO, KN, KN, AC, KN, AC, ST, KN, PF, CR }, 	 //	 6	 2000
{ AC, ST, AC, QN, QN, LO, QN, PF, QN, QN, AC, QN, QN, QN, QN }, 	 //	 7	 2000
{ AC, TN, PF, KN, KN, LO, TN, KN, KN, KN, AC, WN, KN, SK, KN }, 	 //	 8	 2000
{ AC, TN, KN, KN, KN, LO, WN, KN, KN, KN, AC, AC, SH, SK, CR }, 	 //	 9	 2000
{ AC, TN, KN, JA, WN, LO, WN, SH, TN, TN, AC, AC, AC, AC, TN }, 	 //	 10	 2000
{ AC, TN, JA, QN, SK, LO, WN, TN, KN, KN, AC, AC, AC, AC, KN }, 	 //	 11	 2000
{ AC, WN, KN, KN, SK, LO, AC, KN, KN, KN, AC, KN, KN, WN, KN }, 	 //	 12	 2000
{ AC, WN, KN, KN, SK, LO, AC, KN, KN, KN, AC, KN, PF, SK, KN }, 	 //	 13	 2000
{ AC, AC, KN, KN, SH, LO, KN, KN, KN, JA, AC, QN, SH, KN, JA }, 	 //	 14	 2000
{ AC, AC, WN, LO, AC, LO, KN, KN, KN, AC, AC, QN, KN, KN, CR }, 	 //	 15	 2000
{ AC, AC, QN, PF, AC, LO, KN, AC, KN, SK, AC, QN, KN, KN, KN }, 	 //	 16	 2000
{ AC, JA, JA, AC, QN, LO, TN, TN, AC, QN, AC, AC, AC, AC, QN }, 	 //	 17	 2000
{ AC, JA, AC, TN, QN, LO, TN, AC, WN, QN, AC, AC, AC, AC, QN }, 	 //	 18	 2000
{ AC, QN, KN, AC, ST, LO, KN, SH, PF, AC, AC, AC, AC, AC, KN }, 	 //	 19	 2000
{ AC, QN, AC, PF, CR, LO, KN, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 20	 2000
{ AC, QN, AC, AC, KN, LO, KN, WN, KN, KN, AC, AC, KN, QN, KN }, 	 //	 21	 2000
{ LO, SH, QN, QN, QN, AC, AC, AC, QN, SH, AC, AC, KN, QN, JA }, 	 //	 22	 2000
{ LO, SH, AC, WN, KN, AC, AC, KN, AC, AC, AC, AC, WN, KN, LO }, 	 //	 23	 2000
{ LO, AC, ST, TN, AC, AC, AC, AC, AC, LO, AC, AC, KN, AC, AC }, 	 //	 24	 2000
{ LO, AC, KN, KN, KN, AC, AC, KN, KN, QN, AC, LO, KN, SK, PF }, 	 //	 25	 2000
{ LO, AC, AC, TN, SH, AC, AC, PF, AC, JA, AC, LO, QN, AC, JA }, 	 //	 26	 2000
{ LO, AC, KN, KN, KN, AC, LO, PF, KN, KN, AC, KN, QN, SK, KN }, 	 //	 27	 2000
{ LO, LO, AC, KN, QN, AC, KN, WN, KN, QN, AC, KN, KN, KN, SH }, 	 //	 28	 2000
{ LO, KN, QN, AC, KN, AC, KN, PF, KN, SK, AC, ST, KN, QN, QN }, 	 //	 29	 2000
{ LO, KN, PF, PF, QN, AC, KN, KN, KN, SH, AC, ST, KN, KN, JA }, 	 //	 30	 2000
{ LO, KN, QN, KN, KN, AC, KN, AC, KN, KN, AC, ST, KN, KN, CR }, 	 //	 31	 2000
{ LO, QN, AC, KN, KN, AC, QN, WN, KN, KN, AC, QN, KN, KN, KN }, 	 //	 32	 2000
{ LO, TN, JA, AC, SK, AC, WN, TN, AC, KN, AC, AC, AC, AC, KN }, 	 //	 33	 2000
{ LO, TN, PF, AC, QN, AC, WN, QN, AC, QN, AC, AC, AC, AC, QN }, 	 //	 34	 2000
{ LO, WN, AC, TN, TN, AC, AC, WN, AC, TN, AC, KN, KN, AC, TN }, 	 //	 35	 2000
{ LO, WN, PF, KN, AC, AC, AC, QN, AC, AC, AC, KN, AC, PF, CR }, 	 //	 36	 2000
{ LO, AC, KN, KN, SH, AC, KN, KN, KN, JA, AC, QN, SH, WN, JA }, 	 //	 37	 2000
{ LO, AC, KN, KN, KN, AC, KN, SH, KN, KN, AC, QN, AC, KN, CR }, 	 //	 38	 2000
{ LO, AC, AC, AC, AC, AC, KN, AC, PF, SK, AC, QN, WN, KN, KN }, 	 //	 39	 2000
{ LO, KN, KN, KN, KN, AC, QN, KN, WN, AC, AC, ST, KN, QN, LO }, 	 //	 40	 2000
{ LO, ST, KN, AC, SK, AC, JA, KN, KN, KN, AC, TN, PF, QN, KN }, 	 //	 41	 2000
{ LO, JA, JA, TN, QN, AC, TN, TN, WN, QN, AC, AC, AC, AC, QN }, 	 //	 42	 2000
{ LO, JA, TN, TN, QN, AC, TN, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 43	 2000
{ LO, TN, KN, PF, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, CR }, 	 //	 44	 2000
{ LO, TN, AC, AC, KN, AC, AC, WN, AC, KN, AC, AC, KN, AC, KN }, 	 //	 45	 2000
{ LO, AC, KN, KN, CR, AC, PF, KN, KN, KN, AC, KN, PF, KN, KN }, 	 //	 46	 2000
{ LO, KN, ST, LO, CR, AC, KN, AC, KN, QN, AC, SK, KN, KN, KN }, 	 //	 47	 2000
{ LO, KN, KN, QN, AC, AC, KN, SH, KN, SK, AC, SK, AC, AC, KN }, 	 //	 48	 2000
{ LO, QN, JA, PF, ST, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN }, 	 //	 49	 2000
{ LO, QN, JA, TN, JA, AC, KN, TN, AC, JA, AC, AC, AC, AC, WN }, 	 //	 50	 2000
{ LO, QN, WN, KN, TN, AC, KN, KN, KN, ST, AC, AC, KN, WN, AC }, 	 //	 51	 2000
{ LO, KN, AC, WN, KN, AC, AC, WN, AC, KN, AC, SH, KN, KN, CR }, 	 //	 52	 2000
{ AC, AC, AC, AC, JA, AC, SH, KN, AC, JA, AC, AC, QN, AC, JA }, 	 //	 53	 2000
{ AC, AC, AC, AC, QN, AC, SH, KN, AC, PF, AC, AC, QN, LO, JA }, 	 //	 54	 2000
{ AC, AC, JA, TN, AC, AC, SH, TN, WN, AC, AC, AC, AC, AC, SK }, 	 //	 55	 2000
{ AC, AC, AC, AC, PF, AC, SH, AC, AC, JA, AC, AC, WN, AC, TN }, 	 //	 56	 2000
{ AC, SH, AC, AC, KN, AC, AC, KN, AC, KN, AC, AC, QN, AC, KN }, 	 //	 57	 2000
{ AC, SH, AC, KN, JA, AC, AC, KN, AC, WN, AC, AC, QN, PF, TN }, 	 //	 58	 2000
{ AC, AC, QN, PF, TN, AC, AC, AC, AC, TN, AC, AC, KN, AC, TN }, 	 //	 59	 2000
{ AC, AC, AC, AC, JA, AC, LO, AC, AC, WN, AC, KN, PF, LO, TN }, 	 //	 60	 2000
{ AC, AC, AC, AC, CR, AC, LO, KN, KN, QN, AC, KN, WN, QN, KN }, 	 //	 61	 2000
{ AC, QN, QN, WN, JA, AC, QN, QN, QN, TN, AC, QN, QN, QN, AC }, 	 //	 62	 2000
{ AC, TN, QN, WN, QN, AC, TN, QN, QN, QN, AC, WN, QN, QN, QN }, 	 //	 63	 2000
{ AC, TN, WN, AC, KN, AC, TN, KN, KN, KN, AC, WN, KN, QN, SK }, 	 //	 64	 2000
{ AC, WN, PF, AC, KN, AC, AC, QN, AC, KN, AC, KN, AC, AC, CR }, 	 //	 65	 2000
{ AC, AC, QN, KN, KN, AC, KN, PF, KN, KN, AC, QN, KN, WN, SK }, 	 //	 66	 2000
{ AC, AC, WN, KN, SH, AC, KN, KN, KN, JA, AC, QN, KN, KN, JA }, 	 //	 67	 2000
{ AC, AC, AC, AC, SH, AC, KN, KN, AC, JA, AC, QN, WN, AC, JA }, 	 //	 68	 2000
{ AC, JA, SH, TN, SK, AC, TN, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 69	 2000
{ AC, PF, ST, KN, AC, AC, KN, AC, KN, AC, AC, KN, KN, KN, AC }, 	 //	 70	 2000
{ AC, PF, KN, PF, JA, AC, KN, KN, KN, TN, AC, KN, PF, KN, AC }, 	 //	 71	 2000
{ AC, KN, KN, QN, KN, AC, KN, WN, KN, KN, AC, KN, TN, AC, KN }, 	 //	 72	 2000
{ AC, KN, KN, KN, KN, AC, KN, PF, AC, SK, AC, SK, QN, PF, QN }, 	 //	 73	 2000
{ AC, SK, QN, SK, QN, AC, QN, AC, QN, QN, AC, KN, KN, KN, QN }, 	 //	 74	 2000
{ AC, QN, ST, KN, SK, AC, KN, AC, KN, KN, AC, AC, KN, KN, KN }, 	 //	 75	 2000
{ AC, QN, AC, AC, SH, AC, KN, AC, PF, JA, AC, AC, AC, AC, JA }, 	 //	 76	 2000
{ AC, QN, AC, TN, SH, AC, KN, AC, WN, JA, AC, AC, AC, AC, JA }, 	 //	 77	 2000
{ AC, QN, KN, KN, AC, AC, KN, KN, KN, AC, AC, AC, PF, SK, AC }, 	 //	 78	 2000
{ AC, QN, AC, KN, KN, AC, KN, KN, KN, KN, AC, AC, WN, KN, CR }, 	 //	 79	 2000
{ AC, KN, JA, AC, CR, AC, AC, ST, AC, QN, AC, SH, AC, AC, KN }, 	 //	 80	 2000
{ AC, KN, AC, QN, QN, AC, AC, PF, QN, QN, AC, SH, QN, QN, SH }, 	 //	 81	 2000
{ AC, AC, PF, AC, CR, AC, AC, QN, AC, KN, ST, AC, AC, PF, KN }, 	 //	 82	 2000
{ AC, AC, AC, AC, QN, AC, AC, WN, LO, KN, ST, LO, KN, KN, AC }, 	 //	 83	 2000
{ AC, AC, PF, QN, KN, AC, LO, KN, KN, KN, ST, KN, KN, AC, KN }, 	 //	 84	 2000
{ AC, AC, KN, WN, ST, AC, LO, KN, AC, AC, ST, KN, KN, KN, KN }, 	 //	 85	 2000
{ AC, AC, KN, KN, CR, AC, LO, KN, KN, KN, ST, KN, PF, KN, KN }, 	 //	 86	 2000
{ AC, KN, KN, KN, TN, AC, KN, PF, KN, TN, ST, ST, QN, KN, ST }, 	 //	 87	 2000
{ AC, ST, KN, PF, ST, AC, QN, KN, KN, AC, ST, QN, KN, KN, KN }, 	 //	 88	 2000
{ AC, JA, KN, LO, KN, AC, JA, KN, KN, KN, ST, JA, SH, KN, KN }, 	 //	 89	 2000
{ AC, TN, KN, KN, SK, AC, TN, KN, KN, KN, ST, TN, KN, SK, KN }, 	 //	 90	 2000
{ AC, WN, WN, AC, KN, AC, AC, KN, KN, KN, ST, KN, KN, QN, SK }, 	 //	 91	 2000
{ AC, AC, AC, AC, SH, AC, KN, KN, AC, JA, ST, QN, QN, AC, JA }, 	 //	 92	 2000
{ AC, AC, AC, KN, SH, AC, KN, KN, SK, JA, ST, QN, QN, QN, JA }, 	 //	 93	 2000
{ AC, AC, AC, WN, JA, AC, KN, PF, QN, JA, ST, QN, QN, QN, JA }, 	 //	 94	 2000
{ AC, AC, JA, AC, JA, AC, AC, ST, AC, TN, ST, AC, AC, PF, AC }, 	 //	 95	 2000
{ AC, AC, WN, QN, KN, AC, AC, KN, KN, KN, ST, AC, KN, AC, CR }, 	 //	 96	 2000
{ AC, AC, ST, AC, QN, AC, AC, AC, AC, PF, ST, PF, KN, AC, JA }, 	 //	 97	 2000
{ AC, AC, PF, QN, KN, AC, AC, KN, KN, KN, ST, PF, KN, AC, SK }, 	 //	 98	 2000
{ AC, AC, AC, AC, TN, AC, PF, KN, PF, TN, ST, KN, QN, KN, ST }, 	 //	 99	 2000
{ AC, AC, AC, AC, SK, AC, PF, AC, AC, QN, ST, KN, WN, AC, QN }, 	 //	 100	 2000
{ AC, PF, QN, PF, QN, AC, KN, AC, KN, PF, ST, KN, KN, KN, JA }, 	 //	 101	 2000
{ AC, KN, WN, AC, CR, AC, KN, KN, PF, KN, ST, KN, KN, KN, KN }, 	 //	 102	 2000
{ AC, QN, WN, PF, TN, AC, KN, KN, KN, AC, ST, AC, KN, KN, AC }, 	 //	 103	 2000
{ AC, QN, PF, AC, JA, AC, KN, QN, PF, TN, ST, AC, AC, AC, AC }, 	 //	 104	 2000
{ AC, AC, AC, AC, CR, ST, SH, AC, AC, KN, KN, AC, AC, LO, KN }, 	 //	 105	 2000
{ AC, AC, AC, AC, TN, ST, SH, AC, AC, TN, KN, AC, AC, LO, ST }, 	 //	 106	 2000
{ AC, AC, JA, AC, JA, ST, AC, TN, AC, TN, KN, AC, AC, LO, AC }, 	 //	 107	 2000
{ AC, AC, PF, SK, QN, ST, AC, QN, QN, QN, KN, AC, AC, KN, SH }, 	 //	 108	 2000
{ AC, AC, AC, AC, QN, ST, AC, KN, PF, SH, KN, AC, WN, AC, JA }, 	 //	 109	 2000
{ AC, AC, JA, AC, KN, ST, AC, ST, AC, KN, KN, LO, AC, LO, SK }, 	 //	 110	 2000
{ AC, LO, AC, LO, SK, ST, KN, KN, KN, KN, KN, KN, WN, KN, KN }, 	 //	 111	 2000
{ AC, KN, KN, KN, QN, ST, KN, SH, QN, KN, KN, KN, AC, ST, AC }, 	 //	 112	 2000
{ AC, KN, KN, QN, KN, ST, KN, KN, QN, KN, KN, KN, KN, SK, KN }, 	 //	 113	 2000
{ AC, KN, KN, SH, TN, ST, KN, KN, TN, TN, KN, KN, KN, TN, ST }, 	 //	 114	 2000
{ AC, KN, PF, AC, SH, ST, KN, KN, KN, JA, KN, ST, KN, QN, JA }, 	 //	 115	 2000
{ AC, QN, KN, KN, KN, ST, QN, KN, KN, AC, KN, SK, KN, WN, LO }, 	 //	 116	 2000
{ AC, WN, QN, QN, KN, ST, AC, PF, KN, KN, KN, KN, KN, AC, CR }, 	 //	 117	 2000
{ AC, AC, KN, QN, AC, ST, KN, WN, KN, AC, KN, QN, TN, AC, SK }, 	 //	 118	 2000
{ AC, JA, AC, TN, LO, ST, TN, AC, WN, AC, KN, AC, AC, AC, AC }, 	 //	 119	 2000
{ AC, AC, KN, AC, KN, ST, AC, KN, KN, KN, KN, AC, PF, QN, KN }, 	 //	 120	 2000
{ AC, AC, AC, AC, QN, ST, AC, WN, PF, QN, KN, PF, KN, AC, SH }, 	 //	 121	 2000
{ AC, AC, PF, WN, JA, ST, AC, QN, AC, WN, KN, PF, AC, KN, TN }, 	 //	 122	 2000
{ AC, AC, AC, AC, KN, ST, PF, PF, LO, SK, KN, KN, QN, KN, QN }, 	 //	 123	 2000
{ AC, AC, AC, AC, CR, ST, PF, AC, PF, QN, KN, KN, WN, KN, KN }, 	 //	 124	 2000
{ AC, PF, AC, LO, KN, ST, KN, KN, KN, KN, KN, KN, QN, KN, SK }, 	 //	 125	 2000
{ AC, PF, KN, JA, QN, ST, KN, KN, TN, QN, KN, KN, KN, AC, SH }, 	 //	 126	 2000
{ AC, PF, KN, TN, SK, ST, KN, KN, AC, KN, KN, KN, KN, AC, KN }, 	 //	 127	 2000
{ AC, KN, KN, AC, QN, ST, KN, QN, KN, SH, KN, SK, PF, QN, JA }, 	 //	 128	 2000
{ AC, KN, QN, QN, QN, ST, KN, QN, QN, QN, KN, SK, QN, SK, QN }, 	 //	 129	 2000
{ AC, QN, KN, KN, QN, ST, KN, PF, KN, QN, KN, AC, QN, WN, QN }, 	 //	 130	 2000
{ ST, SH, AC, AC, TN, KN, AC, KN, AC, AC, KN, AC, WN, AC, AC }, 	 //	 131	 2000
{ ST, AC, ST, WN, AC, KN, AC, AC, AC, AC, KN, AC, KN, KN, AC }, 	 //	 132	 2000
{ ST, AC, AC, AC, AC, KN, AC, KN, KN, AC, KN, AC, QN, QN, AC }, 	 //	 133	 2000
{ ST, LO, AC, PF, AC, KN, KN, KN, KN, AC, KN, KN, QN, KN, SK }, 	 //	 134	 2000
{ ST, LO, PF, TN, KN, KN, KN, KN, WN, KN, KN, KN, KN, AC, SK }, 	 //	 135	 2000
{ ST, LO, KN, QN, CR, KN, KN, KN, QN, QN, KN, KN, SH, SK, KN }, 	 //	 136	 2000
{ ST, KN, KN, AC, AC, KN, KN, QN, KN, AC, KN, KN, PF, QN, CR }, 	 //	 137	 2000
{ ST, KN, AC, KN, WN, KN, KN, KN, KN, TN, KN, KN, WN, WN, TN }, 	 //	 138	 2000
{ ST, KN, AC, LO, JA, KN, KN, KN, KN, JA, KN, ST, QN, KN, WN }, 	 //	 139	 2000
{ ST, KN, AC, AC, KN, KN, KN, KN, KN, QN, KN, ST, WN, QN, PF }, 	 //	 140	 2000
{ ST, ST, KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, PF, KN, CR }, 	 //	 141	 2000
{ ST, QN, KN, KN, SK, KN, QN, KN, KN, KN, KN, SK, PF, KN, KN }, 	 //	 142	 2000
{ ST, QN, KN, KN, KN, KN, SK, SH, KN, KN, KN, JA, AC, SK, KN }, 	 //	 143	 2000
{ ST, JA, KN, KN, KN, KN, JA, QN, KN, KN, KN, JA, PF, SK, KN }, 	 //	 144	 2000
{ ST, JA, KN, QN, KN, KN, JA, KN, KN, KN, KN, JA, KN, AC, CR }, 	 //	 145	 2000
{ ST, TN, ST, PF, KN, KN, TN, AC, KN, KN, KN, WN, KN, KN, KN }, 	 //	 146	 2000
{ ST, TN, KN, LO, KN, KN, WN, KN, KN, KN, KN, AC, PF, KN, KN }, 	 //	 147	 2000
{ ST, WN, AC, PF, PF, KN, AC, WN, KN, JA, KN, KN, KN, KN, TN }, 	 //	 148	 2000
{ ST, WN, QN, AC, TN, KN, AC, AC, PF, TN, KN, KN, KN, KN, TN }, 	 //	 149	 2000
{ ST, AC, KN, QN, PF, KN, KN, KN, QN, JA, KN, QN, KN, SK, TN }, 	 //	 150	 2000
{ ST, AC, KN, LO, SH, KN, KN, SH, KN, JA, KN, QN, AC, KN, JA }, 	 //	 151	 2000
{ ST, KN, KN, KN, KN, KN, QN, KN, KN, AC, KN, ST, SH, WN, LO }, 	 //	 152	 2000
{ ST, ST, KN, KN, KN, KN, JA, KN, KN, AC, KN, TN, KN, KN, LO }, 	 //	 153	 2000
{ ST, AC, ST, AC, JA, KN, PF, AC, LO, TN, KN, KN, KN, KN, AC }, 	 //	 154	 2000
{ ST, PF, PF, KN, PF, KN, KN, KN, AC, JA, KN, KN, KN, PF, TN }, 	 //	 155	 2000
{ ST, PF, KN, KN, AC, KN, KN, KN, WN, AC, KN, KN, SH, QN, AC }, 	 //	 156	 2000
{ ST, PF, KN, JA, AC, KN, KN, KN, TN, AC, KN, KN, SH, AC, AC }, 	 //	 157	 2000
{ ST, PF, KN, KN, KN, KN, KN, SH, WN, AC, KN, KN, AC, QN, LO }, 	 //	 158	 2000
{ ST, PF, KN, AC, SH, KN, KN, KN, PF, JA, KN, KN, PF, AC, JA }, 	 //	 159	 2000
{ ST, KN, QN, AC, ST, KN, KN, PF, KN, AC, KN, KN, KN, QN, KN }, 	 //	 160	 2000
{ ST, KN, KN, PF, QN, KN, KN, SH, KN, SH, KN, KN, AC, KN, JA }, 	 //	 161	 2000
{ ST, KN, KN, SH, KN, KN, KN, KN, TN, KN, KN, KN, PF, TN, KN }, 	 //	 162	 2000
{ ST, KN, KN, AC, AC, KN, KN, KN, AC, KN, KN, SK, SH, AC, QN }, 	 //	 163	 2000
{ ST, KN, KN, LO, JA, KN, KN, PF, KN, WN, KN, SK, QN, KN, TN }, 	 //	 164	 2000
{ ST, KN, KN, KN, KN, KN, SK, KN, QN, KN, KN, QN, KN, ST, KN }, 	 //	 165	 2000
{ ST, QN, KN, QN, AC, KN, KN, KN, QN, AC, KN, AC, KN, SK, AC }, 	 //	 166	 2000
{ ST, QN, KN, KN, JA, KN, KN, KN, QN, JA, KN, AC, SH, ST, JA }, 	 //	 167	 2000
{ ST, QN, TN, QN, TN, KN, KN, AC, KN, ST, KN, AC, AC, AC, AC }, 	 //	 168	 2000
{ ST, QN, KN, SK, KN, KN, KN, KN, JA, AC, KN, AC, KN, JA, LO }, 	 //	 169	 2000
{ ST, QN, KN, QN, KN, KN, KN, KN, ST, QN, KN, AC, KN, JA, PF }, 	 //	 170	 2000
{ KN, AC, KN, KN, CR, KN, AC, KN, KN, KN, KN, LO, PF, KN, KN }, 	 //	 171	 2000
{ KN, AC, PF, SK, JA, KN, LO, KN, QN, TN, KN, KN, KN, KN, AC }, 	 //	 172	 2000
{ KN, LO, ST, WN, JA, KN, KN, AC, QN, WN, KN, KN, KN, QN, TN }, 	 //	 173	 2000
{ KN, LO, ST, JA, LO, KN, KN, AC, SH, AC, KN, KN, KN, TN, AC }, 	 //	 174	 2000
{ KN, LO, AC, SH, JA, KN, KN, WN, TN, TN, KN, KN, KN, TN, AC }, 	 //	 175	 2000
{ KN, LO, AC, KN, AC, KN, KN, WN, AC, SK, KN, KN, KN, PF, KN }, 	 //	 176	 2000
{ KN, LO, KN, WN, CR, KN, KN, KN, AC, QN, KN, KN, PF, KN, KN }, 	 //	 177	 2000
{ KN, LO, QN, TN, LO, KN, KN, AC, TN, AC, KN, KN, KN, WN, AC }, 	 //	 178	 2000
{ KN, KN, KN, QN, QN, KN, KN, WN, QN, QN, KN, KN, TN, QN, QN }, 	 //	 179	 2000
{ KN, KN, ST, SK, QN, KN, KN, AC, JA, QN, KN, KN, KN, JA, SH }, 	 //	 180	 2000
{ KN, KN, ST, KN, QN, KN, KN, AC, AC, KN, KN, KN, KN, PF, AC }, 	 //	 181	 2000
{ KN, KN, KN, ST, AC, KN, KN, PF, JA, KN, KN, KN, QN, TN, QN }, 	 //	 182	 2000
{ KN, KN, AC, KN, SK, KN, KN, KN, KN, QN, KN, KN, WN, WN, QN }, 	 //	 183	 2000
{ KN, KN, KN, WN, JA, KN, KN, WN, QN, WN, KN, ST, TN, QN, TN }, 	 //	 184	 2000
{ KN, KN, KN, JA, AC, KN, KN, WN, SH, LO, KN, ST, TN, TN, AC }, 	 //	 185	 2000
{ KN, KN, KN, AC, QN, KN, KN, QN, AC, KN, KN, ST, PF, PF, AC }, 	 //	 186	 2000
{ KN, KN, KN, KN, ST, KN, ST, KN, WN, AC, KN, QN, SH, QN, KN }, 	 //	 187	 2000
{ KN, TN, KN, KN, KN, KN, WN, KN, KN, KN, KN, AC, SH, WN, CR }, 	 //	 188	 2000
{ KN, AC, KN, ST, AC, KN, KN, KN, JA, KN, KN, QN, PF, TN, QN }, 	 //	 189	 2000
{ KN, KN, KN, KN, SK, KN, QN, WN, AC, KN, KN, ST, TN, PF, KN }, 	 //	 190	 2000
{ KN, KN, KN, AC, QN, KN, QN, KN, KN, KN, KN, ST, KN, QN, AC }, 	 //	 191	 2000
{ KN, AC, KN, PF, JA, KN, PF, KN, KN, JA, KN, KN, KN, KN, WN }, 	 //	 192	 2000
{ KN, PF, ST, TN, JA, KN, KN, AC, TN, JA, KN, KN, KN, WN, JA }, 	 //	 193	 2000
{ KN, PF, KN, LO, AC, KN, KN, QN, KN, LO, KN, KN, PF, KN, AC }, 	 //	 194	 2000
{ KN, PF, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, SH, KN, SK }, 	 //	 195	 2000
{ KN, PF, KN, KN, KN, KN, KN, SH, SK, KN, KN, KN, AC, QN, KN }, 	 //	 196	 2000
{ KN, PF, AC, KN, WN, KN, KN, WN, AC, TN, KN, KN, KN, PF, TN }, 	 //	 197	 2000
{ KN, PF, KN, WN, KN, KN, KN, KN, QN, SK, KN, KN, PF, QN, QN }, 	 //	 198	 2000
{ KN, KN, ST, KN, QN, KN, KN, AC, AC, SH, KN, KN, KN, PF, JA }, 	 //	 199	 2000
{ KN, KN, QN, AC, SK, KN, KN, PF, AC, QN, KN, KN, KN, AC, QN }, 	 //	 200	 2000
{ KN, KN, AC, WN, AC, KN, KN, WN, QN, AC, KN, KN, KN, QN, SK }, 	 //	 201	 2000
{ KN, KN, KN, JA, TN, KN, KN, PF, JA, ST, KN, KN, QN, JA, AC }, 	 //	 202	 2000
{ KN, KN, KN, AC, AC, KN, KN, WN, PF, AC, KN, SK, TN, KN, SK }, 	 //	 203	 2000
{ KN, KN, PF, SH, JA, KN, KN, KN, TN, JA, KN, SK, KN, TN, WN }, 	 //	 204	 2000
{ KN, KN, KN, AC, QN, KN, KN, PF, AC, SH, KN, SK, QN, LO, JA }, 	 //	 205	 2000
{ KN, SK, AC, KN, TN, KN, QN, WN, KN, TN, KN, KN, KN, KN, TN }, 	 //	 206	 2000
{ KN, QN, ST, SK, KN, KN, KN, AC, QN, KN, KN, AC, KN, KN, KN }, 	 //	 207	 2000
{ KN, QN, QN, KN, SH, KN, KN, PF, KN, JA, KN, AC, KN, WN, JA }, 	 //	 208	 2000
{ KN, QN, KN, AC, JA, KN, KN, KN, AC, JA, KN, AC, SH, PF, JA }, 	 //	 209	 2000
{ KN, QN, KN, KN, AC, KN, KN, SH, KN, AC, KN, AC, AC, KN, SK }, 	 //	 210	 2000
{ KN, QN, KN, QN, TN, KN, KN, KN, QN, TN, KN, AC, PF, QN, ST }, 	 //	 211	 2000
{ KN, KN, KN, KN, JA, KN, AC, WN, KN, JA, KN, SH, TN, KN, JA }, 	 //	 212	 2000
{ KN, KN, KN, KN, SK, KN, AC, KN, KN, QN, KN, SH, SH, WN, QN }, 	 //	 213	 2000
{ KN, SH, AC, KN, AC, KN, AC, WN, AC, AC, SK, AC, KN, PF, AC }, 	 //	 214	 2000
{ KN, AC, KN, KN, KN, KN, AC, KN, KN, SK, SK, LO, KN, KN, QN }, 	 //	 215	 2000
{ KN, LO, ST, QN, AC, KN, KN, AC, KN, SK, SK, KN, KN, AC, KN }, 	 //	 216	 2000
{ KN, LO, PF, KN, QN, KN, KN, KN, AC, KN, SK, KN, KN, PF, AC }, 	 //	 217	 2000
{ KN, LO, WN, JA, SK, KN, KN, KN, JA, KN, SK, KN, KN, SH, KN }, 	 //	 218	 2000
{ KN, LO, KN, QN, KN, KN, KN, KN, QN, SK, SK, KN, KN, QN, QN }, 	 //	 219	 2000
{ KN, LO, KN, TN, CR, KN, KN, KN, TN, KN, SK, KN, KN, TN, KN }, 	 //	 220	 2000
{ KN, KN, KN, KN, JA, KN, KN, WN, AC, JA, SK, KN, TN, PF, WN }, 	 //	 221	 2000
{ KN, KN, KN, PF, TN, KN, KN, QN, KN, ST, SK, KN, PF, KN, AC }, 	 //	 222	 2000
{ KN, KN, QN, KN, QN, KN, KN, PF, KN, QN, SK, KN, KN, WN, SH }, 	 //	 223	 2000
{ KN, KN, PF, JA, AC, KN, KN, KN, JA, AC, SK, KN, KN, JA, CR }, 	 //	 224	 2000
{ KN, KN, KN, PF, QN, KN, KN, SH, KN, KN, SK, KN, AC, KN, AC }, 	 //	 225	 2000
{ KN, KN, KN, PF, KN, KN, KN, KN, AC, KN, SK, KN, PF, AC, KN }, 	 //	 226	 2000
{ KN, KN, PF, KN, SH, KN, KN, KN, SK, JA, SK, ST, KN, QN, JA }, 	 //	 227	 2000
{ KN, KN, KN, SK, AC, KN, KN, KN, QN, KN, SK, ST, SH, KN, QN }, 	 //	 228	 2000
{ KN, KN, KN, KN, WN, KN, KN, PF, WN, TN, SK, ST, QN, QN, TN }, 	 //	 229	 2000
{ KN, KN, KN, KN, AC, KN, ST, WN, KN, AC, SK, QN, TN, SK, CR }, 	 //	 230	 2000
{ KN, ST, AC, AC, AC, KN, QN, PF, KN, AC, SK, QN, QN, QN, SK }, 	 //	 231	 2000
{ KN, TN, KN, AC, CR, KN, TN, KN, KN, KN, SK, WN, KN, QN, KN }, 	 //	 232	 2000
{ KN, TN, PF, QN, AC, KN, WN, QN, KN, AC, SK, AC, AC, AC, AC }, 	 //	 233	 2000
{ KN, WN, AC, WN, AC, KN, AC, PF, AC, AC, SK, KN, QN, KN, AC }, 	 //	 234	 2000
{ KN, WN, QN, KN, KN, KN, AC, AC, KN, KN, SK, KN, KN, KN, SK }, 	 //	 235	 2000
{ KN, AC, AC, QN, WN, KN, KN, KN, KN, TN, SK, QN, WN, AC, TN }, 	 //	 236	 2000
{ KN, TN, ST, PF, AC, KN, AC, AC, AC, AC, SK, AC, KN, AC, CR }, 	 //	 237	 2000
{ KN, AC, AC, AC, AC, KN, AC, AC, LO, SK, SK, AC, AC, KN, KN }, 	 //	 238	 2000
{ KN, AC, AC, AC, AC, KN, AC, AC, KN, AC, SK, PF, PF, QN, AC }, 	 //	 239	 2000
{ KN, PF, PF, TN, AC, KN, KN, KN, TN, SK, SK, KN, KN, TN, KN }, 	 //	 240	 2000
{ KN, PF, PF, TN, SH, KN, KN, KN, AC, JA, SK, KN, KN, AC, JA }, 	 //	 241	 2000
{ KN, PF, WN, AC, KN, KN, KN, KN, AC, AC, SK, KN, KN, AC, LO }, 	 //	 242	 2000
{ KN, KN, QN, AC, KN, KN, KN, PF, PF, KN, SK, KN, KN, KN, SK }, 	 //	 243	 2000
{ KN, KN, PF, TN, AC, KN, KN, KN, TN, AC, SK, KN, KN, TN, CR }, 	 //	 244	 2000
{ KN, KN, KN, SK, TN, KN, KN, KN, QN, AC, SK, KN, SH, KN, AC }, 	 //	 245	 2000
{ KN, KN, WN, TN, QN, KN, KN, KN, TN, QN, SK, KN, KN, WN, QN }, 	 //	 246	 2000
{ KN, KN, KN, SK, QN, KN, KN, KN, JA, KN, SK, KN, PF, JA, AC }, 	 //	 247	 2000
{ KN, KN, KN, KN, SK, KN, KN, PF, QN, KN, SK, KN, QN, ST, KN }, 	 //	 248	 2000
{ KN, QN, PF, AC, JA, KN, KN, KN, AC, JA, SK, AC, KN, AC, WN }, 	 //	 249	 2000
{ KN, QN, AC, KN, JA, KN, KN, WN, KN, TN, SK, AC, KN, KN, AC }, 	 //	 250	 2000
{ KN, QN, QN, LO, TN, KN, KN, AC, KN, TN, SK, AC, KN, KN, ST }, 	 //	 251	 2000
{ KN, KN, KN, KN, CR, KN, AC, WN, QN, QN, SK, SH, TN, ST, KN }, 	 //	 252	 2000
{ KN, KN, KN, KN, JA, KN, AC, WN, KN, TN, SK, SH, TN, SK, AC }, 	 //	 253	 2000
{ KN, KN, KN, KN, SH, KN, AC, KN, QN, JA, SK, SH, SH, ST, JA }, 	 //	 254	 2000
{ KN, KN, AC, WN, QN, KN, AC, WN, AC, KN, SK, SH, KN, KN, AC }, 	 //	 255	 2000
{ KN, SH, ST, TN, AC, SK, AC, AC, AC, AC, QN, AC, KN, AC, SK }, 	 //	 256	 2000
{ KN, AC, AC, AC, AC, SK, LO, KN, PF, AC, QN, KN, QN, KN, AC }, 	 //	 257	 2000
{ KN, LO, ST, KN, AC, SK, KN, AC, KN, SK, QN, KN, KN, WN, KN }, 	 //	 258	 2000
{ KN, KN, KN, KN, SK, SK, KN, WN, WN, QN, QN, ST, TN, QN, QN }, 	 //	 259	 2000
{ KN, KN, KN, JA, TN, SK, KN, KN, SH, TN, QN, ST, KN, TN, TN }, 	 //	 260	 2000
{ KN, KN, KN, TN, AC, SK, KN, KN, TN, AC, QN, ST, KN, TN, CR }, 	 //	 261	 2000
{ KN, KN, KN, SK, JA, SK, KN, KN, QN, TN, QN, ST, KN, KN, AC }, 	 //	 262	 2000
{ KN, KN, KN, KN, JA, SK, KN, PF, AC, JA, QN, ST, QN, PF, JA }, 	 //	 263	 2000
{ KN, KN, AC, KN, AC, SK, KN, KN, KN, KN, QN, ST, WN, KN, QN }, 	 //	 264	 2000
{ KN, ST, AC, QN, SK, SK, QN, KN, QN, QN, QN, QN, QN, QN, QN }, 	 //	 265	 2000
{ KN, TN, KN, AC, SK, SK, TN, KN, KN, KN, QN, WN, KN, QN, KN }, 	 //	 266	 2000
{ KN, WN, KN, KN, KN, SK, AC, WN, KN, KN, QN, KN, TN, SK, KN }, 	 //	 267	 2000
{ KN, KN, KN, KN, TN, SK, QN, KN, QN, AC, QN, ST, KN, ST, AC }, 	 //	 268	 2000
{ KN, JA, QN, LO, KN, SK, TN, AC, KN, KN, QN, AC, KN, KN, KN }, 	 //	 269	 2000
{ KN, TN, AC, QN, QN, SK, AC, AC, KN, KN, QN, AC, AC, AC, AC }, 	 //	 270	 2000
{ KN, AC, QN, AC, KN, SK, AC, AC, AC, AC, QN, AC, KN, PF, LO }, 	 //	 271	 2000
{ KN, PF, KN, AC, QN, SK, KN, KN, PF, QN, QN, KN, KN, KN, QN }, 	 //	 272	 2000
{ KN, KN, KN, QN, SK, SK, KN, KN, ST, QN, QN, SK, KN, JA, QN }, 	 //	 273	 2000
{ KN, KN, KN, AC, QN, SK, KN, KN, AC, QN, QN, SK, KN, AC, SH }, 	 //	 274	 2000
{ KN, SK, QN, WN, KN, SK, QN, QN, QN, KN, QN, KN, QN, QN, KN }, 	 //	 275	 2000
{ KN, QN, ST, KN, WN, SK, KN, AC, KN, TN, QN, AC, KN, SK, TN }, 	 //	 276	 2000
{ KN, QN, KN, KN, QN, SK, KN, KN, KN, QN, QN, AC, PF, KN, QN }, 	 //	 277	 2000
{ KN, QN, AC, LO, KN, SK, KN, KN, KN, KN, QN, AC, WN, KN, CR }, 	 //	 278	 2000
{ SK, AC, KN, KN, KN, QN, SH, KN, KN, AC, QN, AC, KN, KN, LO }, 	 //	 279	 2000
{ SK, SH, JA, TN, AC, QN, AC, ST, WN, LO, QN, AC, AC, AC, AC }, 	 //	 280	 2000
{ SK, SH, JA, WN, AC, QN, AC, ST, AC, AC, QN, AC, AC, KN, CR }, 	 //	 281	 2000
{ SK, AC, AC, AC, AC, QN, AC, AC, PF, LO, QN, AC, AC, KN, AC }, 	 //	 282	 2000
{ SK, LO, KN, KN, KN, QN, KN, SH, KN, AC, QN, KN, AC, KN, LO }, 	 //	 283	 2000
{ SK, KN, ST, KN, SK, QN, KN, AC, KN, QN, QN, KN, KN, KN, QN }, 	 //	 284	 2000
{ SK, KN, ST, SK, CR, QN, KN, AC, QN, QN, QN, KN, KN, KN, KN }, 	 //	 285	 2000
{ SK, KN, KN, KN, LO, QN, KN, PF, KN, AC, QN, KN, QN, WN, AC }, 	 //	 286	 2000
{ SK, KN, PF, KN, TN, QN, KN, KN, KN, ST, QN, ST, KN, KN, AC }, 	 //	 287	 2000
{ SK, KN, KN, KN, KN, QN, KN, KN, WN, KN, QN, ST, KN, QN, SK }, 	 //	 288	 2000
{ SK, TN, SH, JA, TN, QN, WN, AC, TN, ST, QN, AC, AC, AC, AC }, 	 //	 289	 2000
{ SK, WN, PF, PF, KN, QN, AC, KN, KN, AC, QN, KN, KN, KN, LO }, 	 //	 290	 2000
{ SK, AC, WN, KN, JA, QN, KN, KN, KN, JA, QN, QN, KN, KN, JA }, 	 //	 291	 2000
{ SK, JA, JA, AC, TN, QN, TN, TN, AC, AC, QN, AC, AC, AC, AC }, 	 //	 292	 2000
{ SK, AC, AC, AC, AC, QN, AC, PF, LO, AC, QN, AC, QN, KN, SK }, 	 //	 293	 2000
{ SK, AC, KN, WN, ST, QN, PF, KN, AC, AC, QN, KN, KN, KN, KN }, 	 //	 294	 2000
{ SK, AC, QN, KN, KN, QN, PF, AC, KN, AC, QN, KN, KN, KN, LO }, 	 //	 295	 2000
{ SK, PF, KN, QN, JA, QN, KN, KN, KN, JA, QN, KN, PF, AC, WN }, 	 //	 296	 2000
{ SK, KN, KN, KN, KN, QN, KN, KN, AC, SK, QN, KN, SH, PF, QN }, 	 //	 297	 2000
{ SK, QN, KN, QN, ST, QN, KN, PF, KN, AC, QN, AC, QN, AC, KN }, 	 //	 298	 2000
{ SK, QN, AC, KN, KN, QN, KN, KN, KN, KN, QN, AC, WN, SK, CR }, 	 //	 299	 2000
{ SK, KN, QN, AC, AC, QN, AC, AC, AC, AC, QN, SH, KN, AC, CR }, 	 //	 300	 2000
{ QN, AC, AC, AC, AC, QN, SH, AC, KN, SK, QN, AC, PF, QN, KN }, 	 //	 301	 2000
{ QN, AC, ST, KN, AC, QN, AC, AC, AC, AC, QN, AC, KN, PF, SK }, 	 //	 302	 2000
{ QN, LO, KN, KN, SK, QN, KN, SH, KN, KN, QN, KN, AC, SK, KN }, 	 //	 303	 2000
{ QN, LO, WN, QN, LO, QN, KN, KN, KN, AC, QN, KN, KN, AC, AC }, 	 //	 304	 2000
{ QN, ST, KN, LO, KN, QN, QN, KN, KN, KN, QN, QN, SH, KN, KN }, 	 //	 305	 2000
{ QN, ST, QN, AC, JA, QN, QN, QN, AC, JA, QN, QN, QN, LO, JA }, 	 //	 306	 2000
{ QN, ST, QN, KN, QN, QN, QN, QN, KN, PF, QN, QN, QN, KN, JA }, 	 //	 307	 2000
{ QN, ST, QN, TN, PF, QN, QN, QN, AC, JA, QN, QN, QN, AC, TN }, 	 //	 308	 2000
{ QN, QN, PF, QN, JA, QN, QN, QN, QN, JA, QN, SK, QN, QN, WN }, 	 //	 309	 2000
{ QN, JA, KN, KN, KN, QN, JA, SH, KN, KN, QN, JA, AC, KN, KN }, 	 //	 310	 2000
{ QN, AC, KN, KN, AC, QN, KN, QN, KN, SK, QN, QN, PF, WN, KN }, 	 //	 311	 2000
{ QN, AC, KN, KN, TN, QN, KN, KN, KN, AC, QN, QN, PF, KN, AC }, 	 //	 312	 2000
{ QN, KN, QN, AC, AC, QN, QN, AC, AC, AC, QN, ST, KN, LO, CR }, 	 //	 313	 2000
{ QN, QN, PF, KN, KN, QN, ST, KN, KN, KN, QN, JA, KN, WN, KN }, 	 //	 314	 2000
{ QN, TN, JA, AC, AC, QN, AC, ST, AC, AC, QN, AC, AC, LO, SK }, 	 //	 315	 2000
{ QN, TN, KN, KN, CR, QN, AC, KN, KN, KN, QN, AC, PF, KN, KN }, 	 //	 316	 2000
{ QN, AC, JA, KN, AC, QN, AC, ST, AC, KN, QN, PF, AC, PF, QN }, 	 //	 317	 2000
{ QN, PF, KN, KN, ST, QN, KN, SH, KN, AC, QN, KN, AC, KN, KN }, 	 //	 318	 2000
{ QN, PF, AC, KN, KN, QN, KN, KN, KN, KN, QN, KN, WN, KN, KN }, 	 //	 319	 2000
{ QN, KN, KN, KN, AC, QN, KN, WN, KN, AC, QN, SK, TN, WN, SK }, 	 //	 320	 2000
{ QN, KN, WN, LO, SH, QN, KN, KN, KN, JA, QN, SK, KN, KN, JA }, 	 //	 321	 2000
{ QN, KN, KN, KN, AC, QN, SK, PF, SK, AC, QN, QN, QN, QN, CR }, 	 //	 322	 2000
{ QN, KN, KN, KN, ST, QN, AC, SH, KN, AC, QN, SH, AC, KN, KN }, 	 //	 323	 2000
{ QN, KN, KN, KN, KN, QN, AC, KN, QN, SK, QN, SH, KN, ST, QN }, 	 //	 324	 2000
{ QN, KN, AC, AC, QN, QN, AC, KN, AC, KN, QN, SH, WN, PF, AC }, 	 //	 325	 2000
{ QN, AC, QN, AC, CR, QN, LO, PF, LO, KN, SH, KN, KN, KN, KN }, 	 //	 326	 2000
{ QN, LO, KN, KN, AC, QN, KN, QN, KN, SK, SH, KN, PF, KN, KN }, 	 //	 327	 2000
{ QN, KN, KN, KN, QN, QN, KN, QN, KN, QN, SH, KN, PF, SK, SH }, 	 //	 328	 2000
{ QN, ST, AC, TN, AC, QN, QN, PF, AC, AC, SH, QN, QN, AC, AC }, 	 //	 329	 2000
{ QN, ST, KN, WN, QN, QN, QN, PF, QN, SH, SH, QN, QN, QN, JA }, 	 //	 330	 2000
{ QN, QN, KN, AC, SK, QN, QN, KN, KN, KN, SH, QN, KN, QN, KN }, 	 //	 331	 2000
{ QN, QN, QN, QN, KN, QN, QN, PF, QN, SK, SH, SK, KN, QN, QN }, 	 //	 332	 2000
{ QN, JA, KN, AC, KN, QN, SH, KN, KN, KN, SH, TN, SH, QN, KN }, 	 //	 333	 2000
{ QN, TN, KN, KN, KN, QN, TN, SH, KN, KN, SH, TN, AC, SK, KN }, 	 //	 334	 2000
{ QN, TN, SH, AC, TN, QN, WN, AC, AC, ST, SH, AC, AC, AC, AC }, 	 //	 335	 2000
{ QN, AC, QN, KN, KN, QN, KN, AC, KN, AC, SH, QN, KN, KN, LO }, 	 //	 336	 2000
{ QN, JA, JA, QN, QN, QN, TN, ST, KN, KN, SH, AC, AC, AC, AC }, 	 //	 337	 2000
{ QN, TN, QN, KN, ST, QN, AC, AC, AC, AC, SH, AC, KN, PF, KN }, 	 //	 338	 2000
{ QN, AC, KN, KN, CR, QN, AC, KN, KN, KN, SH, PF, KN, WN, KN }, 	 //	 339	 2000
{ QN, KN, QN, KN, AC, QN, KN, AC, KN, AC, SH, KN, KN, KN, AC }, 	 //	 340	 2000
{ QN, SK, KN, PF, KN, QN, QN, KN, KN, KN, SH, KN, SH, KN, KN }, 	 //	 341	 2000
{ QN, AC, QN, LO, KN, SH, SH, PF, KN, KN, JA, AC, KN, KN, KN }, 	 //	 342	 2000
{ QN, AC, SH, QN, TN, SH, SH, AC, KN, AC, JA, AC, AC, AC, AC }, 	 //	 343	 2000
{ QN, AC, QN, PF, KN, SH, SH, AC, KN, KN, JA, AC, KN, KN, KN }, 	 //	 344	 2000
{ QN, AC, KN, AC, AC, SH, AC, SH, AC, AC, JA, AC, AC, LO, CR }, 	 //	 345	 2000
{ QN, AC, QN, PF, KN, SH, AC, AC, KN, KN, JA, AC, KN, KN, KN }, 	 //	 346	 2000
{ QN, AC, PF, KN, KN, SH, LO, KN, KN, KN, JA, KN, KN, SK, CR }, 	 //	 347	 2000
{ QN, KN, KN, KN, KN, SH, KN, SH, AC, KN, JA, KN, AC, PF, CR }, 	 //	 348	 2000
{ QN, KN, KN, KN, AC, SH, ST, PF, SK, KN, JA, QN, QN, QN, QN }, 	 //	 349	 2000
{ QN, ST, AC, AC, JA, SH, QN, KN, AC, TN, JA, QN, QN, LO, AC }, 	 //	 350	 2000
{ QN, SK, PF, KN, SK, SH, JA, KN, KN, KN, JA, JA, KN, KN, KN }, 	 //	 351	 2000
{ QN, TN, KN, QN, CR, SH, TN, KN, KN, KN, JA, WN, PF, AC, KN }, 	 //	 352	 2000
{ QN, KN, KN, KN, ST, SH, QN, WN, KN, AC, JA, ST, TN, WN, KN }, 	 //	 353	 2000
{ QN, KN, QN, SK, AC, SH, QN, QN, QN, LO, JA, ST, QN, KN, AC }, 	 //	 354	 2000
{ QN, KN, WN, LO, KN, SH, QN, KN, KN, KN, JA, ST, KN, KN, SK }, 	 //	 355	 2000
{ QN, TN, KN, AC, AC, SH, AC, SH, AC, SK, JA, AC, AC, LO, KN }, 	 //	 356	 2000
{ QN, KN, KN, KN, LO, SH, KN, PF, KN, AC, JA, KN, QN, KN, AC }, 	 //	 357	 2000
{ QN, KN, QN, QN, KN, SH, KN, PF, KN, KN, JA, SK, KN, AC, SK }, 	 //	 358	 2000
{ QN, SK, AC, AC, AC, SH, QN, PF, AC, AC, JA, KN, QN, LO, CR }, 	 //	 359	 2000
{ QN, QN, AC, PF, KN, SH, KN, KN, KN, KN, JA, AC, QN, KN, SK }, 	 //	 360	 2000
{ QN, QN, AC, QN, QN, SH, KN, AC, KN, KN, JA, AC, AC, AC, AC }, 	 //	 361	 2000
{ QN, QN, AC, QN, KN, SH, KN, WN, KN, KN, JA, AC, KN, AC, CR }, 	 //	 362	 2000
{ QN, KN, KN, KN, KN, SH, AC, WN, SK, KN, JA, SH, TN, QN, KN }, 	 //	 363	 2000
{ SH, AC, AC, AC, AC, JA, LO, KN, PF, AC, JA, KN, QN, KN, SK }, 	 //	 364	 2000
{ SH, LO, KN, KN, LO, JA, KN, KN, KN, AC, JA, KN, SH, KN, AC }, 	 //	 365	 2000
{ SH, LO, KN, KN, TN, JA, KN, KN, KN, AC, JA, KN, PF, SK, AC }, 	 //	 366	 2000
{ SH, KN, KN, QN, JA, JA, KN, KN, KN, WN, JA, ST, SH, AC, TN }, 	 //	 367	 2000
{ SH, KN, KN, KN, KN, JA, ST, SH, KN, SK, JA, QN, AC, WN, QN }, 	 //	 368	 2000
{ SH, QN, KN, KN, KN, JA, QN, WN, KN, KN, JA, QN, TN, KN, KN }, 	 //	 369	 2000
{ SH, QN, KN, KN, KN, JA, SK, KN, KN, QN, JA, JA, KN, WN, PF }, 	 //	 370	 2000
{ SH, JA, ST, PF, KN, JA, JA, AC, KN, KN, JA, SH, KN, KN, KN }, 	 //	 371	 2000
{ SH, TN, WN, QN, KN, JA, TN, KN, KN, KN, JA, TN, KN, AC, KN }, 	 //	 372	 2000
{ SH, TN, KN, KN, KN, JA, TN, KN, KN, QN, JA, WN, KN, KN, PF }, 	 //	 373	 2000
{ SH, WN, JA, KN, AC, JA, AC, ST, AC, LO, JA, KN, AC, PF, AC }, 	 //	 374	 2000
{ SH, JA, JA, QN, AC, JA, TN, TN, KN, AC, JA, AC, AC, AC, AC }, 	 //	 375	 2000
{ SH, TN, AC, TN, TN, JA, AC, WN, AC, AC, JA, AC, KN, AC, AC }, 	 //	 376	 2000
{ SH, AC, KN, PF, KN, JA, AC, KN, KN, KN, JA, AC, SH, KN, KN }, 	 //	 377	 2000
{ SH, AC, AC, AC, AC, JA, PF, KN, AC, KN, JA, KN, QN, PF, QN }, 	 //	 378	 2000
{ SH, KN, KN, KN, TN, JA, KN, PF, KN, ST, JA, KN, QN, KN, AC }, 	 //	 379	 2000
{ JA, SH, ST, AC, ST, JA, AC, AC, AC, AC, JA, AC, KN, AC, KN }, 	 //	 380	 2000
{ JA, SH, KN, KN, SK, JA, AC, KN, KN, KN, JA, AC, SH, KN, KN }, 	 //	 381	 2000
{ JA, AC, AC, PF, TN, JA, AC, WN, AC, ST, JA, AC, KN, AC, AC }, 	 //	 382	 2000
{ JA, AC, JA, PF, AC, JA, AC, ST, AC, AC, JA, LO, AC, AC, CR }, 	 //	 383	 2000
{ JA, KN, ST, LO, AC, JA, KN, AC, KN, AC, JA, KN, KN, KN, SK }, 	 //	 384	 2000
{ JA, KN, AC, LO, KN, JA, KN, KN, KN, KN, JA, ST, WN, KN, CR }, 	 //	 385	 2000
{ JA, KN, KN, KN, KN, JA, ST, PF, KN, AC, JA, QN, QN, SK, LO }, 	 //	 386	 2000
{ JA, QN, WN, LO, SK, JA, QN, KN, KN, KN, JA, QN, KN, KN, KN }, 	 //	 387	 2000
{ JA, QN, WN, KN, KN, JA, SK, KN, KN, KN, JA, JA, KN, KN, CR }, 	 //	 388	 2000
{ JA, SH, KN, AC, KN, JA, TN, KN, KN, KN, JA, TN, PF, QN, KN }, 	 //	 389	 2000
{ JA, AC, KN, KN, TN, JA, KN, KN, KN, TN, JA, QN, PF, KN, ST }, 	 //	 390	 2000
{ JA, TN, KN, AC, SK, JA, AC, KN, KN, KN, JA, AC, KN, QN, KN }, 	 //	 391	 2000
{ JA, AC, KN, KN, SK, JA, AC, KN, KN, KN, JA, PF, PF, WN, KN }, 	 //	 392	 2000
{ JA, AC, AC, WN, KN, JA, PF, WN, AC, KN, JA, KN, KN, KN, KN }, 	 //	 393	 2000
{ JA, PF, KN, LO, AC, JA, KN, QN, KN, SK, JA, KN, PF, KN, KN }, 	 //	 394	 2000
{ JA, PF, WN, AC, SH, JA, KN, KN, KN, JA, JA, KN, KN, QN, JA }, 	 //	 395	 2000
{ JA, KN, QN, KN, QN, JA, KN, PF, KN, QN, JA, KN, KN, KN, SH }, 	 //	 396	 2000
{ JA, KN, AC, WN, SK, JA, KN, WN, AC, KN, JA, KN, KN, KN, KN }, 	 //	 397	 2000
{ JA, KN, PF, AC, AC, JA, KN, KN, KN, AC, JA, SK, KN, QN, SK }, 	 //	 398	 2000
{ JA, KN, KN, AC, JA, JA, KN, KN, KN, TN, JA, SK, PF, QN, AC }, 	 //	 399	 2000
{ JA, QN, TN, JA, TN, JA, KN, AC, TN, ST, JA, AC, AC, AC, AC }, 	 //	 400	 2000
{ JA, KN, ST, AC, AC, JA, AC, AC, AC, AC, JA, SH, KN, PF, SK }, 	 //	 401	 2000
{ JA, KN, KN, KN, SK, JA, AC, PF, KN, KN, JA, SH, QN, WN, KN }, 	 //	 402	 2000
{ JA, LO, KN, KN, KN, JA, KN, WN, KN, QN, WN, KN, TN, KN, PF }, 	 //	 403	 2000
{ JA, LO, ST, KN, KN, JA, KN, AC, KN, SK, WN, KN, KN, WN, QN }, 	 //	 404	 2000
{ JA, KN, KN, AC, AC, JA, KN, KN, KN, AC, WN, ST, SH, QN, CR }, 	 //	 405	 2000
{ JA, TN, ST, KN, KN, JA, TN, AC, KN, KN, WN, WN, KN, KN, KN }, 	 //	 406	 2000
{ JA, WN, KN, KN, KN, JA, AC, WN, KN, KN, WN, KN, TN, KN, KN }, 	 //	 407	 2000
{ JA, WN, KN, SK, CR, JA, AC, KN, QN, QN, WN, KN, KN, KN, KN }, 	 //	 408	 2000
{ JA, TN, ST, TN, AC, JA, AC, AC, AC, AC, WN, AC, KN, AC, SK }, 	 //	 409	 2000
{ JA, TN, JA, JA, AC, JA, AC, TN, TN, LO, WN, AC, AC, AC, AC }, 	 //	 410	 2000
{ JA, AC, JA, WN, AC, JA, AC, TN, AC, KN, WN, AC, AC, KN, QN }, 	 //	 411	 2000
{ JA, AC, KN, KN, KN, JA, PF, KN, KN, KN, WN, KN, PF, SK, CR }, 	 //	 412	 2000
{ JA, QN, JA, TN, JA, JA, KN, ST, WN, TN, WN, AC, AC, AC, AC }, 	 //	 413	 2000
{ JA, QN, KN, KN, TN, JA, KN, KN, KN, TN, WN, AC, SH, KN, ST }, 	 //	 414	 2000
{ JA, QN, AC, QN, QN, JA, KN, AC, KN, KN, WN, AC, AC, AC, AC }, 	 //	 415	 2000
{ JA, QN, JA, TN, QN, JA, KN, TN, AC, KN, WN, AC, AC, AC, AC }, 	 //	 416	 2000
{ JA, SH, JA, KN, AC, WN, AC, TN, AC, KN, TN, AC, AC, PF, QN }, 	 //	 417	 2000
{ JA, AC, AC, AC, AC, WN, LO, AC, PF, AC, TN, KN, AC, KN, CR }, 	 //	 418	 2000
{ JA, LO, KN, KN, TN, WN, KN, KN, KN, TN, TN, KN, SH, KN, TN }, 	 //	 419	 2000
{ JA, LO, WN, AC, AC, WN, KN, KN, KN, AC, TN, KN, KN, QN, SK }, 	 //	 420	 2000
{ JA, LO, KN, LO, JA, WN, KN, KN, KN, WN, TN, KN, PF, KN, TN }, 	 //	 421	 2000
{ JA, LO, QN, PF, AC, WN, KN, AC, KN, AC, TN, KN, KN, KN, AC }, 	 //	 422	 2000
{ JA, KN, KN, KN, KN, WN, KN, KN, WN, AC, TN, KN, KN, QN, LO }, 	 //	 423	 2000
{ JA, QN, KN, KN, KN, WN, QN, KN, KN, QN, TN, SK, KN, SK, PF }, 	 //	 424	 2000
{ JA, AC, KN, KN, SK, WN, KN, KN, KN, QN, TN, QN, SH, KN, QN }, 	 //	 425	 2000
{ JA, PF, KN, KN, JA, WN, KN, KN, KN, JA, TN, KN, SH, WN, JA }, 	 //	 426	 2000
{ JA, KN, KN, PF, QN, WN, KN, KN, KN, PF, TN, KN, PF, KN, JA }, 	 //	 427	 2000
{ JA, KN, PF, AC, QN, WN, KN, KN, KN, QN, TN, SK, KN, QN, SH }, 	 //	 428	 2000
{ JA, KN, KN, QN, WN, WN, KN, KN, KN, TN, TN, SK, SH, AC, TN }, 	 //	 429	 2000
{ JA, SK, KN, KN, KN, WN, QN, KN, KN, SK, TN, KN, KN, SK, QN }, 	 //	 430	 2000
{ JA, QN, JA, QN, TN, WN, KN, ST, KN, ST, TN, AC, AC, AC, AC }, 	 //	 431	 2000
{ WN, AC, AC, JA, AC, TN, SH, AC, TN, LO, TN, AC, AC, AC, AC }, 	 //	 432	 2000
{ WN, AC, QN, KN, KN, TN, AC, PF, KN, KN, TN, AC, KN, KN, KN }, 	 //	 433	 2000
{ WN, AC, SH, QN, AC, TN, AC, AC, KN, AC, TN, AC, AC, AC, AC }, 	 //	 434	 2000
{ WN, KN, KN, KN, KN, TN, KN, PF, WN, KN, TN, KN, QN, QN, SK }, 	 //	 435	 2000
{ WN, KN, QN, LO, KN, TN, KN, PF, KN, KN, TN, ST, KN, KN, SK }, 	 //	 436	 2000
{ WN, SK, QN, LO, KN, TN, JA, AC, KN, KN, TN, JA, KN, KN, KN }, 	 //	 437	 2000
{ WN, AC, KN, AC, AC, TN, KN, KN, KN, AC, TN, QN, SH, QN, CR }, 	 //	 438	 2000
{ WN, AC, ST, AC, AC, TN, AC, AC, AC, AC, TN, AC, KN, PF, SK }, 	 //	 439	 2000
{ WN, AC, PF, AC, AC, TN, AC, QN, AC, AC, TN, PF, AC, LO, CR }, 	 //	 440	 2000
{ WN, AC, AC, AC, AC, TN, AC, KN, PF, AC, TN, PF, WN, AC, AC }, 	 //	 441	 2000
{ WN, AC, WN, LO, ST, TN, PF, KN, KN, AC, TN, KN, KN, KN, KN }, 	 //	 442	 2000
{ WN, PF, ST, SK, ST, TN, KN, AC, QN, AC, TN, KN, KN, KN, KN }, 	 //	 443	 2000
{ WN, PF, AC, LO, QN, TN, KN, WN, KN, SH, TN, KN, KN, KN, JA }, 	 //	 444	 2000
{ WN, PF, WN, SK, ST, TN, KN, KN, QN, AC, TN, KN, KN, KN, KN }, 	 //	 445	 2000
{ WN, KN, KN, KN, KN, TN, KN, PF, WN, QN, TN, KN, QN, QN, PF }, 	 //	 446	 2000
{ WN, KN, QN, QN, KN, TN, KN, PF, KN, KN, TN, SK, KN, AC, SK }, 	 //	 447	 2000
{ WN, QN, KN, KN, QN, TN, KN, KN, KN, QN, TN, AC, SH, KN, SH }, 	 //	 448	 2000
{ WN, QN, KN, PF, KN, TN, KN, SH, KN, KN, TN, AC, AC, KN, KN }, 	 //	 449	 2000
{ TN, AC, AC, AC, AC, TN, SH, KN, AC, AC, TN, AC, QN, PF, CR }, 	 //	 450	 2000
{ TN, AC, PF, PF, CR, TN, SH, KN, KN, KN, TN, AC, KN, KN, KN }, 	 //	 451	 2000
{ TN, KN, QN, LO, ST, TN, KN, AC, KN, AC, TN, ST, KN, KN, KN }, 	 //	 452	 2000
{ TN, KN, KN, KN, AC, TN, QN, PF, KN, SK, TN, ST, QN, WN, KN }, 	 //	 453	 2000
{ TN, AC, AC, PF, AC, TN, AC, PF, AC, AC, TN, AC, QN, AC, AC }, 	 //	 454	 2000
{ TN, AC, PF, KN, AC, TN, PF, KN, KN, KN, TN, KN, KN, KN, QN }, 	 //	 455	 2000
{ TN, AC, KN, QN, SK, TN, PF, KN, KN, KN, TN, KN, KN, AC, KN }, 	 //	 456	 2000
{ TN, KN, KN, KN, QN, TN, KN, SH, KN, PF, TN, SK, AC, KN, JA }, 	 //	 457	 2000
{ TN, KN, KN, KN, AC, TN, SK, SH, KN, SK, TN, QN, AC, SK, KN }, 	 //	 458	 2000
{ TN, QN, QN, PF, CR, TN, KN, AC, KN, QN, TN, AC, KN, KN, KN }, 	 //	 459	 2000
{ TN, AC, AC, AC, AC, TN, SH, WN, AC, AC, ST, AC, KN, PF, SK }, 	 //	 460	 2000
{ TN, AC, PF, AC, TN, TN, SH, QN, AC, AC, ST, AC, AC, AC, AC }, 	 //	 461	 2000
{ TN, SH, AC, TN, TN, TN, AC, AC, WN, ST, ST, AC, AC, AC, AC }, 	 //	 462	 2000
{ TN, AC, KN, KN, AC, TN, AC, KN, KN, SK, ST, LO, KN, KN, KN }, 	 //	 463	 2000
{ TN, LO, KN, KN, AC, TN, KN, KN, KN, AC, ST, KN, SH, SK, AC }, 	 //	 464	 2000
{ TN, LO, AC, LO, TN, TN, KN, WN, KN, TN, ST, KN, KN, KN, TN }, 	 //	 465	 2000
{ TN, KN, QN, KN, AC, TN, KN, PF, KN, AC, ST, KN, KN, KN, AC }, 	 //	 466	 2000
{ TN, KN, AC, KN, KN, TN, KN, KN, KN, KN, ST, ST, QN, KN, KN }, 	 //	 467	 2000
{ TN, KN, QN, LO, KN, TN, KN, PF, KN, QN, ST, ST, KN, KN, PF }, 	 //	 468	 2000
{ TN, KN, WN, PF, SK, TN, KN, KN, KN, QN, ST, ST, KN, KN, QN }, 	 //	 469	 2000
{ TN, KN, KN, KN, ST, TN, ST, QN, KN, AC, ST, QN, PF, KN, KN }, 	 //	 470	 2000
{ TN, KN, KN, KN, KN, TN, ST, KN, KN, SK, ST, QN, SH, KN, QN }, 	 //	 471	 2000
{ TN, KN, KN, KN, QN, TN, ST, KN, KN, KN, ST, QN, SH, WN, AC }, 	 //	 472	 2000
{ TN, KN, QN, WN, SK, TN, ST, QN, QN, QN, ST, QN, QN, QN, QN }, 	 //	 473	 2000
{ TN, QN, PF, LO, KN, TN, QN, KN, KN, KN, ST, QN, KN, KN, CR }, 	 //	 474	 2000
{ TN, QN, KN, KN, KN, TN, QN, WN, KN, KN, ST, SK, TN, KN, KN }, 	 //	 475	 2000
{ TN, JA, KN, KN, KN, TN, SH, KN, KN, KN, ST, TN, SH, KN, SK }, 	 //	 476	 2000
{ TN, TN, WN, KN, KN, TN, TN, KN, KN, KN, ST, WN, KN, WN, CR }, 	 //	 477	 2000
{ TN, TN, SH, TN, JA, TN, WN, AC, WN, TN, ST, AC, AC, AC, AC }, 	 //	 478	 2000
{ TN, AC, KN, QN, KN, TN, KN, KN, KN, SK, ST, QN, PF, AC, QN }, 	 //	 479	 2000
{ TN, KN, KN, KN, AC, TN, QN, KN, KN, KN, ST, ST, PF, KN, QN }, 	 //	 480	 2000
{ TN, JA, KN, QN, CR, TN, TN, KN, KN, KN, ST, AC, KN, AC, KN }, 	 //	 481	 2000
{ TN, KN, PF, AC, KN, TN, KN, KN, LO, KN, ST, KN, KN, KN, KN }, 	 //	 482	 2000
{ TN, KN, KN, LO, TN, TN, KN, KN, KN, TN, ST, SK, PF, KN, ST }, 	 //	 483	 2000
{ TN, KN, AC, AC, LO, TN, AC, KN, AC, AC, ST, SH, QN, AC, AC }, 	 //	 484	 2000
{ TN, AC, AC, AC, AC, ST, SH, KN, AC, SK, AC, AC, WN, PF, KN }, 	 //	 485	 2000
{ TN, SH, AC, AC, KN, ST, AC, KN, AC, AC, AC, AC, WN, AC, LO }, 	 //	 486	 2000
{ TN, AC, AC, KN, SH, ST, AC, KN, AC, JA, AC, AC, QN, PF, JA }, 	 //	 487	 2000
{ TN, AC, AC, KN, KN, ST, AC, PF, AC, SK, AC, LO, QN, PF, QN }, 	 //	 488	 2000
{ TN, AC, AC, KN, JA, ST, AC, KN, AC, JA, AC, LO, WN, PF, WN }, 	 //	 489	 2000
{ TN, LO, QN, KN, QN, ST, KN, PF, KN, SH, AC, KN, KN, KN, JA }, 	 //	 490	 2000
{ TN, LO, AC, PF, QN, ST, KN, WN, KN, PF, AC, KN, KN, KN, JA }, 	 //	 491	 2000
{ TN, KN, AC, LO, TN, ST, KN, WN, KN, ST, AC, KN, KN, KN, AC }, 	 //	 492	 2000
{ TN, KN, KN, KN, KN, ST, KN, KN, QN, KN, AC, ST, KN, ST, KN }, 	 //	 493	 2000
{ TN, JA, KN, PF, ST, ST, JA, KN, KN, AC, AC, SH, KN, KN, KN }, 	 //	 494	 2000
{ TN, TN, KN, KN, SK, ST, TN, KN, KN, KN, AC, WN, KN, WN, KN }, 	 //	 495	 2000
{ TN, TN, KN, AC, KN, ST, WN, KN, KN, KN, AC, AC, PF, QN, KN }, 	 //	 496	 2000
{ TN, WN, KN, AC, ST, ST, AC, KN, PF, AC, AC, KN, KN, KN, KN }, 	 //	 497	 2000
{ TN, KN, KN, KN, KN, ST, QN, PF, KN, SK, AC, ST, QN, SK, QN }, 	 //	 498	 2000
{ TN, ST, KN, QN, CR, ST, JA, KN, KN, KN, AC, TN, PF, AC, KN }, 	 //	 499	 2000
{ TN, AC, AC, KN, JA, ST, AC, KN, AC, JA, AC, AC, QN, PF, WN }, 	 //	 500	 2000
{ TN, AC, SH, JA, TN, ST, AC, AC, TN, TN, AC, AC, AC, AC, TN }, 	 //	 501	 2000
{ TN, AC, KN, KN, KN, ST, PF, KN, KN, AC, AC, KN, KN, SK, LO }, 	 //	 502	 2000
{ TN, PF, QN, AC, KN, ST, KN, PF, KN, KN, AC, KN, KN, QN, KN }, 	 //	 503	 2000
{ TN, KN, KN, KN, KN, ST, SK, KN, QN, KN, AC, QN, SH, ST, KN }, 	 //	 504	 2000
{ TN, QN, KN, PF, QN, ST, KN, SH, AC, SH, AC, AC, AC, AC, JA }, 	 //	 505	 2000
{ TN, QN, KN, TN, QN, ST, KN, SH, WN, PF, AC, AC, AC, AC, JA }, 	 //	 506	 2000
{ TN, QN, PF, AC, QN, ST, KN, QN, PF, PF, AC, AC, AC, AC, JA }, 	 //	 507	 2000
{ TN, KN, AC, KN, KN, ST, AC, KN, AC, SK, AC, SH, QN, PF, QN }, 	 //	 508	 2000
{ TN, KN, AC, KN, SH, ST, AC, WN, AC, JA, AC, SH, KN, PF, JA }, 	 //	 509	 2000
{ ST, SH, PF, WN, AC, AC, AC, QN, AC, AC, KN, AC, AC, KN, CR }, 	 //	 510	 2000
{ ST, AC, AC, AC, AC, AC, AC, KN, PF, KN, KN, AC, WN, AC, QN }, 	 //	 511	 2000
{ ST, LO, KN, AC, TN, AC, KN, KN, AC, TN, KN, KN, KN, AC, ST }, 	 //	 512	 2000
{ ST, KN, KN, KN, QN, AC, KN, SH, AC, KN, KN, KN, AC, PF, AC }, 	 //	 513	 2000
{ ST, KN, KN, QN, QN, AC, KN, KN, ST, KN, KN, KN, KN, JA, AC }, 	 //	 514	 2000
{ ST, KN, ST, KN, ST, AC, KN, AC, KN, AC, KN, ST, KN, KN, KN }, 	 //	 515	 2000
{ ST, KN, WN, AC, SH, AC, KN, KN, KN, JA, KN, ST, KN, QN, JA }, 	 //	 516	 2000
{ ST, KN, WN, KN, TN, AC, KN, KN, KN, ST, KN, ST, KN, KN, AC }, 	 //	 517	 2000
{ ST, KN, AC, AC, AC, AC, ST, KN, KN, LO, KN, QN, QN, QN, AC }, 	 //	 518	 2000
{ ST, QN, KN, KN, KN, AC, QN, KN, KN, KN, KN, SK, PF, WN, CR }, 	 //	 519	 2000
{ ST, JA, KN, KN, CR, AC, JA, KN, KN, QN, KN, SH, KN, KN, KN }, 	 //	 520	 2000
{ ST, AC, AC, AC, AC, AC, KN, AC, KN, AC, KN, QN, WN, QN, AC }, 	 //	 521	 2000
{ ST, KN, KN, QN, CR, AC, QN, KN, KN, KN, KN, ST, KN, AC, KN }, 	 //	 522	 2000
{ ST, PF, KN, WN, AC, AC, KN, KN, QN, SK, KN, KN, KN, QN, KN }, 	 //	 523	 2000
{ ST, PF, KN, JA, SK, AC, KN, KN, SH, QN, KN, KN, KN, TN, QN }, 	 //	 524	 2000
{ ST, KN, KN, KN, QN, AC, KN, WN, WN, SH, KN, KN, TN, QN, JA }, 	 //	 525	 2000
{ ST, KN, AC, KN, CR, AC, KN, KN, KN, KN, KN, KN, QN, KN, KN }, 	 //	 526	 2000
{ ST, QN, QN, QN, QN, AC, KN, QN, QN, QN, KN, AC, SK, QN, QN }, 	 //	 527	 2000
{ ST, KN, PF, LO, KN, AC, AC, KN, KN, KN, KN, SH, KN, KN, CR }, 	 //	 528	 2000
{ ST, KN, KN, KN, KN, AC, AC, KN, WN, KN, KN, SH, KN, QN, KN }, 	 //	 529	 2000
{ AC, AC, KN, KN, KN, KN, AC, KN, KN, QN, QN, AC, KN, WN, PF }, 	 //	 530	 2000
{ AC, AC, AC, AC, QN, KN, AC, WN, KN, QN, QN, AC, KN, QN, QN }, 	 //	 531	 2000
{ AC, AC, JA, AC, KN, KN, AC, ST, AC, KN, QN, LO, AC, LO, CR }, 	 //	 532	 2000
{ AC, AC, WN, AC, KN, KN, LO, KN, PF, KN, QN, KN, KN, KN, KN }, 	 //	 533	 2000
{ AC, KN, AC, SK, CR, KN, KN, WN, QN, QN, QN, KN, KN, KN, KN }, 	 //	 534	 2000
{ AC, KN, KN, KN, SH, KN, KN, KN, AC, JA, QN, KN, KN, PF, JA }, 	 //	 535	 2000
{ AC, QN, KN, WN, QN, KN, QN, PF, QN, PF, QN, QN, QN, QN, JA }, 	 //	 536	 2000
{ AC, TN, ST, KN, KN, KN, TN, AC, KN, KN, QN, WN, KN, KN, KN }, 	 //	 537	 2000
{ AC, AC, AC, JA, KN, KN, KN, PF, JA, AC, QN, QN, QN, SH, LO }, 	 //	 538	 2000
{ AC, ST, KN, KN, CR, KN, JA, KN, KN, QN, QN, TN, KN, KN, KN }, 	 //	 539	 2000
{ AC, PF, AC, LO, AC, KN, KN, KN, KN, LO, QN, KN, QN, KN, AC }, 	 //	 540	 2000
{ AC, KN, KN, WN, JA, KN, KN, KN, AC, JA, QN, KN, KN, KN, WN }, 	 //	 541	 2000
{ AC, KN, KN, KN, KN, KN, AC, QN, AC, KN, QN, SH, PF, PF, CR }, 	 //	 542	 2000
{ AC, KN, KN, KN, KN, KN, AC, KN, AC, QN, QN, SH, SH, PF, PF }, 	 //	 543	 2000
{ KN, AC, QN, AC, ST, QN, AC, AC, AC, AC, PF, AC, KN, AC, KN }, 	 //	 544	 2000
{ KN, AC, JA, PF, AC, QN, AC, ST, AC, KN, PF, LO, AC, AC, QN }, 	 //	 545	 2000
{ KN, AC, ST, AC, AC, QN, AC, AC, AC, AC, PF, LO, KN, AC, AC }, 	 //	 546	 2000
{ KN, AC, QN, WN, AC, QN, AC, AC, AC, AC, PF, LO, KN, KN, CR }, 	 //	 547	 2000
{ KN, LO, KN, KN, KN, QN, KN, KN, AC, QN, PF, KN, KN, PF, PF }, 	 //	 548	 2000
{ KN, KN, KN, KN, AC, QN, KN, WN, QN, AC, PF, KN, TN, ST, AC }, 	 //	 549	 2000
{ KN, KN, ST, KN, TN, QN, KN, AC, KN, ST, PF, KN, KN, SK, AC }, 	 //	 550	 2000
{ KN, KN, KN, AC, QN, QN, KN, KN, AC, KN, PF, KN, KN, LO, AC }, 	 //	 551	 2000
{ KN, KN, KN, SK, SH, QN, KN, KN, JA, JA, PF, KN, KN, JA, JA }, 	 //	 552	 2000
{ KN, KN, KN, KN, TN, QN, KN, KN, QN, ST, PF, KN, SH, ST, AC }, 	 //	 553	 2000
{ KN, KN, KN, AC, KN, QN, KN, QN, KN, KN, PF, ST, PF, QN, SK }, 	 //	 554	 2000
{ KN, KN, KN, WN, AC, QN, KN, KN, AC, KN, PF, ST, KN, KN, QN }, 	 //	 555	 2000
{ KN, KN, KN, KN, QN, QN, KN, PF, SK, PF, PF, ST, QN, QN, JA }, 	 //	 556	 2000
{ KN, KN, QN, KN, TN, QN, KN, AC, KN, ST, PF, ST, KN, SK, AC }, 	 //	 557	 2000
{ KN, KN, KN, WN, SK, QN, ST, PF, QN, QN, PF, QN, QN, QN, QN }, 	 //	 558	 2000
{ KN, SK, WN, KN, KN, QN, JA, KN, KN, KN, PF, JA, KN, KN, CR }, 	 //	 559	 2000
{ KN, JA, KN, KN, CR, QN, SH, KN, KN, QN, PF, TN, KN, KN, KN }, 	 //	 560	 2000
{ KN, TN, PF, KN, KN, QN, TN, KN, KN, KN, PF, WN, KN, WN, KN }, 	 //	 561	 2000
{ KN, TN, JA, QN, TN, QN, WN, ST, KN, ST, PF, AC, AC, AC, AC }, 	 //	 562	 2000
{ KN, KN, KN, KN, JA, QN, QN, KN, AC, JA, PF, ST, SH, PF, JA }, 	 //	 563	 2000
{ KN, KN, KN, KN, QN, QN, QN, PF, KN, QN, PF, ST, QN, WN, SH }, 	 //	 564	 2000
{ KN, QN, PF, AC, KN, QN, ST, KN, KN, KN, PF, JA, KN, QN, KN }, 	 //	 565	 2000
{ KN, AC, JA, AC, AC, QN, AC, ST, AC, AC, PF, PF, AC, PF, AC }, 	 //	 566	 2000
{ KN, AC, AC, AC, AC, QN, PF, AC, PF, AC, PF, KN, AC, KN, SK }, 	 //	 567	 2000
{ KN, PF, QN, SK, AC, QN, KN, PF, QN, AC, PF, KN, KN, KN, AC }, 	 //	 568	 2000
{ KN, KN, KN, WN, AC, QN, KN, KN, QN, SK, PF, KN, KN, QN, KN }, 	 //	 569	 2000
{ KN, KN, KN, JA, KN, QN, KN, KN, TN, QN, PF, KN, KN, AC, PF }, 	 //	 570	 2000
{ KN, KN, KN, KN, SH, QN, SK, KN, KN, JA, PF, QN, KN, SK, JA }, 	 //	 571	 2000
{ KN, KN, KN, KN, AC, QN, SK, KN, QN, KN, PF, QN, SH, ST, QN }, 	 //	 572	 2000
{ KN, SK, ST, PF, SK, QN, QN, AC, KN, KN, PF, KN, KN, KN, KN }, 	 //	 573	 2000
{ KN, QN, KN, AC, KN, QN, KN, KN, LO, KN, PF, AC, KN, KN, KN }, 	 //	 574	 2000
{ KN, KN, KN, KN, WN, QN, AC, KN, KN, TN, PF, SH, KN, KN, TN }, 	 //	 575	 2000
{ KN, KN, KN, KN, SK, QN, AC, KN, AC, KN, PF, SH, KN, PF, KN }, 	 //	 576	 2000
{ KN, KN, KN, KN, CR, QN, AC, KN, QN, QN, PF, SH, PF, ST, KN }, 	 //	 577	 2000
{ QN, SH, KN, LO, AC, PF, AC, KN, KN, SK, JA, AC, KN, KN, KN }, 	 //	 578	 2000
{ QN, AC, WN, KN, QN, PF, LO, KN, KN, KN, JA, KN, KN, KN, AC }, 	 //	 579	 2000
{ QN, LO, WN, WN, ST, PF, KN, KN, AC, AC, JA, KN, KN, KN, KN }, 	 //	 580	 2000
{ QN, LO, KN, KN, KN, PF, KN, PF, KN, KN, JA, KN, QN, KN, CR }, 	 //	 581	 2000
{ QN, KN, ST, SK, CR, PF, KN, AC, QN, QN, JA, KN, KN, KN, KN }, 	 //	 582	 2000
{ QN, ST, QN, SK, LO, PF, QN, QN, QN, AC, JA, QN, QN, KN, AC }, 	 //	 583	 2000
{ QN, QN, KN, KN, KN, PF, QN, QN, KN, KN, JA, SK, PF, KN, KN }, 	 //	 584	 2000
{ QN, QN, AC, AC, AC, PF, QN, PF, KN, LO, JA, SK, QN, QN, AC }, 	 //	 585	 2000
{ QN, TN, KN, KN, ST, PF, TN, KN, KN, AC, JA, WN, KN, KN, KN }, 	 //	 586	 2000
{ QN, TN, KN, KN, AC, PF, WN, KN, KN, SK, JA, AC, KN, KN, KN }, 	 //	 587	 2000
{ QN, AC, KN, QN, JA, PF, KN, KN, KN, TN, JA, QN, PF, AC, AC }, 	 //	 588	 2000
{ QN, TN, KN, TN, AC, PF, AC, SH, WN, LO, JA, AC, AC, AC, AC }, 	 //	 589	 2000
{ QN, AC, KN, KN, KN, PF, PF, QN, KN, KN, JA, KN, PF, WN, KN }, 	 //	 590	 2000
{ QN, PF, WN, AC, QN, PF, KN, KN, KN, PF, JA, KN, KN, QN, JA }, 	 //	 591	 2000
{ QN, KN, ST, KN, AC, PF, KN, AC, KN, AC, JA, KN, KN, KN, AC }, 	 //	 592	 2000
{ QN, KN, KN, LO, KN, PF, KN, PF, KN, KN, JA, SK, QN, KN, KN }, 	 //	 593	 2000
{ PF, AC, JA, QN, AC, JA, SH, TN, KN, LO, TN, AC, AC, AC, AC }, 	 //	 594	 2000
{ PF, SH, PF, JA, JA, JA, AC, QN, TN, TN, TN, AC, AC, AC, AC }, 	 //	 595	 2000
{ PF, AC, ST, KN, KN, JA, AC, AC, KN, KN, TN, AC, KN, KN, KN }, 	 //	 596	 2000
{ PF, AC, KN, QN, KN, JA, AC, KN, KN, KN, TN, LO, KN, AC, CR }, 	 //	 597	 2000
{ PF, LO, KN, QN, JA, JA, KN, KN, KN, JA, TN, KN, PF, AC, JA }, 	 //	 598	 2000
{ PF, KN, KN, KN, KN, JA, ST, WN, KN, KN, TN, QN, TN, WN, CR }, 	 //	 599	 2000
{ PF, QN, KN, KN, KN, JA, QN, SH, KN, KN, TN, SK, AC, KN, KN }, 	 //	 600	 2000
{ PF, QN, PF, QN, KN, JA, SK, KN, KN, KN, TN, JA, KN, AC, SK }, 	 //	 601	 2000
{ PF, JA, KN, KN, KN, JA, SH, SH, KN, KN, TN, TN, AC, KN, KN }, 	 //	 602	 2000
{ PF, AC, AC, AC, AC, JA, KN, KN, PF, AC, TN, QN, QN, KN, AC }, 	 //	 603	 2000
{ PF, AC, AC, AC, AC, JA, KN, AC, PF, AC, TN, QN, PF, KN, AC }, 	 //	 604	 2000
{ PF, KN, KN, KN, KN, JA, QN, KN, QN, KN, TN, ST, SH, ST, SK }, 	 //	 605	 2000
{ PF, JA, QN, KN, KN, JA, TN, AC, KN, KN, TN, AC, KN, KN, KN }, 	 //	 606	 2000
{ PF, AC, WN, PF, KN, JA, AC, KN, KN, KN, TN, PF, KN, KN, SK }, 	 //	 607	 2000
{ PF, AC, AC, AC, AC, JA, PF, PF, AC, AC, TN, KN, QN, AC, SK }, 	 //	 608	 2000
{ PF, PF, KN, KN, PF, JA, KN, KN, KN, JA, TN, KN, SH, KN, TN }, 	 //	 609	 2000
{ PF, KN, ST, PF, PF, JA, KN, AC, KN, JA, TN, KN, KN, KN, TN }, 	 //	 610	 2000
{ PF, KN, KN, QN, ST, JA, KN, SH, KN, AC, TN, SK, AC, AC, KN }, 	 //	 611	 2000
{ PF, QN, TN, TN, JA, JA, KN, AC, AC, TN, TN, AC, AC, AC, AC }, 	 //	 612	 2000
{ JA, AC, TN, PF, KN, TN, SH, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 613	 2000
{ JA, SH, TN, TN, QN, TN, AC, AC, WN, SH, AC, AC, AC, AC, JA }, 	 //	 614	 2000
{ JA, SH, AC, AC, CR, TN, AC, KN, AC, KN, AC, AC, WN, AC, KN }, 	 //	 615	 2000
{ JA, AC, KN, QN, KN, TN, AC, KN, KN, KN, AC, AC, SH, AC, KN }, 	 //	 616	 2000
{ JA, AC, WN, QN, KN, TN, AC, KN, KN, KN, AC, AC, KN, AC, KN }, 	 //	 617	 2000
{ JA, KN, ST, PF, TN, TN, KN, AC, KN, TN, AC, KN, KN, KN, TN }, 	 //	 618	 2000
{ JA, KN, AC, KN, SK, TN, KN, KN, KN, KN, AC, KN, QN, KN, KN }, 	 //	 619	 2000
{ JA, KN, KN, KN, SK, TN, KN, SH, KN, QN, AC, KN, AC, SK, QN }, 	 //	 620	 2000
{ JA, KN, KN, KN, SH, TN, KN, WN, KN, JA, AC, ST, TN, WN, JA }, 	 //	 621	 2000
{ JA, KN, KN, PF, QN, TN, KN, KN, KN, QN, AC, ST, PF, KN, SH }, 	 //	 622	 2000
{ JA, TN, KN, PF, KN, TN, WN, KN, KN, KN, AC, AC, SH, KN, KN }, 	 //	 623	 2000
{ JA, TN, TN, AC, ST, TN, AC, AC, PF, AC, AC, AC, AC, AC, KN }, 	 //	 624	 2000
{ JA, PF, ST, LO, TN, TN, KN, AC, KN, ST, AC, KN, KN, KN, AC }, 	 //	 625	 2000
{ JA, PF, KN, KN, AC, TN, KN, KN, KN, LO, AC, KN, SH, KN, AC }, 	 //	 626	 2000
{ JA, PF, WN, KN, SH, TN, KN, KN, KN, JA, AC, KN, KN, SK, JA }, 	 //	 627	 2000
{ JA, KN, WN, KN, PF, TN, KN, KN, KN, JA, AC, KN, KN, WN, TN }, 	 //	 628	 2000
{ JA, KN, KN, KN, AC, TN, KN, PF, KN, AC, AC, KN, QN, KN, SK }, 	 //	 629	 2000
{ JA, KN, QN, AC, SK, TN, KN, AC, PF, KN, AC, KN, KN, KN, KN }, 	 //	 630	 2000
{ TN, AC, AC, JA, TN, AC, SH, AC, TN, TN, AC, AC, AC, AC, TN }, 	 //	 631	 2000
{ TN, SH, AC, KN, WN, AC, AC, PF, AC, TN, AC, AC, QN, PF, TN }, 	 //	 632	 2000
{ TN, SH, QN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, PF, SK }, 	 //	 633	 2000
{ TN, AC, AC, PF, QN, AC, AC, PF, AC, PF, AC, AC, QN, AC, JA }, 	 //	 634	 2000
{ TN, AC, QN, TN, PF, AC, AC, AC, AC, JA, AC, AC, KN, AC, TN }, 	 //	 635	 2000
{ TN, AC, JA, KN, AC, AC, AC, ST, AC, AC, AC, LO, AC, PF, AC }, 	 //	 636	 2000
{ TN, AC, AC, WN, QN, AC, AC, PF, AC, QN, AC, LO, QN, KN, SH }, 	 //	 637	 2000
{ TN, AC, KN, WN, SK, AC, LO, KN, AC, KN, AC, KN, KN, KN, KN }, 	 //	 638	 2000
{ TN, KN, AC, KN, KN, AC, KN, KN, KN, KN, AC, ST, QN, KN, KN }, 	 //	 639	 2000
{ TN, ST, KN, KN, KN, AC, QN, WN, KN, KN, AC, QN, TN, SK, KN }, 	 //	 640	 2000
{ TN, JA, KN, KN, KN, AC, JA, KN, KN, KN, AC, JA, SH, KN, SK }, 	 //	 641	 2000
{ TN, JA, KN, QN, KN, AC, JA, KN, KN, KN, AC, JA, KN, AC, CR }, 	 //	 642	 2000
{ TN, TN, KN, JA, AC, AC, WN, SH, TN, SK, AC, AC, AC, AC, KN }, 	 //	 643	 2000
{ TN, TN, SH, AC, CR, AC, WN, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 644	 2000
{ TN, WN, QN, LO, KN, AC, AC, PF, KN, QN, AC, KN, KN, KN, PF }, 	 //	 645	 2000
{ TN, WN, QN, AC, QN, AC, AC, AC, AC, PF, AC, KN, KN, AC, JA }, 	 //	 646	 2000
{ TN, WN, AC, AC, TN, AC, AC, KN, AC, TN, AC, KN, WN, LO, TN }, 	 //	 647	 2000
{ TN, WN, AC, AC, QN, AC, AC, KN, AC, QN, AC, KN, WN, AC, QN }, 	 //	 648	 2000
{ TN, AC, KN, KN, CR, AC, KN, SH, KN, KN, AC, QN, AC, KN, KN }, 	 //	 649	 2000
{ TN, AC, AC, AC, AC, AC, KN, KN, LO, AC, AC, QN, WN, KN, CR }, 	 //	 650	 2000
{ TN, KN, AC, PF, KN, AC, QN, WN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 651	 2000
{ TN, QN, PF, KN, CR, AC, ST, KN, KN, KN, AC, JA, KN, KN, KN }, 	 //	 652	 2000
{ TN, TN, AC, WN, KN, AC, AC, KN, AC, QN, AC, AC, QN, KN, PF }, 	 //	 653	 2000
{ TN, TN, AC, AC, KN, AC, AC, KN, AC, KN, AC, AC, WN, LO, KN }, 	 //	 654	 2000
{ TN, AC, KN, KN, KN, AC, AC, PF, KN, KN, AC, AC, QN, KN, KN }, 	 //	 655	 2000
{ TN, AC, PF, QN, QN, AC, AC, QN, KN, QN, AC, AC, AC, AC, QN }, 	 //	 656	 2000
{ TN, AC, ST, KN, KN, AC, AC, AC, AC, KN, AC, PF, KN, PF, CR }, 	 //	 657	 2000
{ TN, AC, KN, KN, KN, AC, PF, QN, KN, KN, AC, KN, PF, WN, KN }, 	 //	 658	 2000
{ TN, KN, KN, QN, KN, AC, KN, WN, KN, KN, AC, KN, TN, AC, KN }, 	 //	 659	 2000
{ TN, KN, KN, KN, KN, AC, SK, QN, WN, KN, AC, QN, PF, QN, KN }, 	 //	 660	 2000
{ TN, QN, KN, TN, QN, AC, KN, SH, AC, QN, AC, AC, AC, AC, QN }, 	 //	 661	 2000
{ AC, AC, AC, AC, QN, AC, SH, KN, AC, QN, AC, AC, QN, AC, SH }, 	 //	 662	 2000
{ AC, AC, AC, AC, QN, AC, SH, PF, AC, SH, AC, AC, QN, PF, JA }, 	 //	 663	 2000
{ AC, SH, ST, WN, KN, AC, AC, AC, AC, SK, AC, AC, KN, KN, QN }, 	 //	 664	 2000
{ AC, AC, KN, KN, CR, AC, AC, KN, KN, KN, AC, AC, KN, WN, KN }, 	 //	 665	 2000
{ AC, LO, AC, SK, ST, AC, KN, WN, QN, AC, AC, KN, KN, KN, KN }, 	 //	 666	 2000
{ AC, LO, KN, LO, AC, AC, KN, KN, KN, AC, AC, KN, PF, KN, CR }, 	 //	 667	 2000
{ AC, KN, KN, KN, AC, AC, KN, WN, KN, AC, AC, KN, TN, KN, CR }, 	 //	 668	 2000
{ AC, ST, AC, PF, KN, AC, QN, WN, KN, KN, AC, QN, KN, KN, KN }, 	 //	 669	 2000
{ AC, SK, AC, PF, KN, AC, JA, WN, KN, KN, AC, JA, KN, KN, KN }, 	 //	 670	 2000
{ AC, SH, KN, AC, CR, AC, TN, KN, KN, KN, AC, TN, PF, QN, KN }, 	 //	 671	 2000
{ AC, TN, PF, KN, KN, AC, WN, KN, KN, KN, AC, AC, KN, KN, CR }, 	 //	 672	 2000
{ AC, TN, PF, PF, QN, AC, WN, QN, AC, SH, AC, AC, AC, AC, JA }, 	 //	 673	 2000
{ AC, WN, KN, TN, ST, AC, AC, SH, AC, AC, AC, KN, AC, AC, KN }, 	 //	 674	 2000
{ AC, WN, QN, AC, KN, AC, AC, AC, AC, QN, AC, KN, KN, AC, PF }, 	 //	 675	 2000
{ AC, AC, AC, AC, QN, AC, KN, AC, PF, SH, AC, QN, WN, AC, JA }, 	 //	 676	 2000
{ AC, AC, WN, KN, QN, AC, KN, KN, KN, QN, AC, QN, KN, KN, SH }, 	 //	 677	 2000
{ AC, AC, KN, PF, KN, AC, KN, KN, KN, SK, AC, QN, PF, KN, QN }, 	 //	 678	 2000
{ AC, KN, KN, KN, KN, AC, QN, QN, KN, QN, AC, ST, PF, WN, PF }, 	 //	 679	 2000
{ AC, AC, AC, SK, QN, AC, PF, PF, QN, KN, AC, KN, QN, KN, AC }, 	 //	 680	 2000
{ AC, PF, QN, PF, QN, AC, KN, AC, KN, PF, AC, KN, KN, KN, JA }, 	 //	 681	 2000
{ AC, KN, QN, KN, AC, AC, KN, PF, KN, LO, AC, KN, KN, KN, AC }, 	 //	 682	 2000
{ AC, KN, WN, WN, KN, AC, KN, KN, AC, KN, AC, KN, KN, KN, KN }, 	 //	 683	 2000
{ AC, KN, KN, AC, TN, AC, KN, KN, KN, TN, AC, KN, PF, QN, TN }, 	 //	 684	 2000
{ AC, QN, KN, LO, QN, AC, KN, KN, KN, QN, AC, AC, SH, KN, QN }, 	 //	 685	 2000
{ AC, QN, KN, PF, TN, AC, KN, KN, KN, TN, AC, AC, SH, KN, TN }, 	 //	 686	 2000
{ AC, QN, SH, QN, SK, AC, KN, AC, KN, KN, AC, AC, AC, AC, KN }, 	 //	 687	 2000
{ AC, AC, AC, AC, QN, AC, SH, WN, PF, PF, SK, AC, KN, KN, JA }, 	 //	 688	 2000
{ AC, SH, AC, PF, AC, AC, AC, WN, AC, LO, SK, AC, KN, AC, AC }, 	 //	 689	 2000
{ AC, SH, QN, AC, QN, AC, AC, AC, AC, KN, SK, AC, KN, LO, AC }, 	 //	 690	 2000
{ AC, AC, PF, KN, KN, AC, AC, QN, AC, KN, SK, AC, AC, PF, KN }, 	 //	 691	 2000
{ AC, AC, QN, AC, TN, AC, AC, AC, AC, ST, SK, AC, KN, AC, AC }, 	 //	 692	 2000
{ AC, AC, KN, TN, WN, AC, AC, SH, AC, TN, SK, LO, AC, AC, TN }, 	 //	 693	 2000
{ AC, AC, AC, AC, PF, AC, AC, PF, KN, JA, SK, LO, QN, QN, TN }, 	 //	 694	 2000
{ AC, AC, AC, AC, LO, AC, AC, WN, PF, AC, SK, LO, KN, AC, AC }, 	 //	 695	 2000
{ AC, AC, AC, AC, JA, AC, LO, AC, AC, JA, SK, KN, AC, AC, WN }, 	 //	 696	 2000
{ AC, LO, KN, KN, AC, AC, KN, QN, KN, SK, SK, KN, PF, KN, KN }, 	 //	 697	 2000
{ AC, LO, AC, AC, KN, AC, KN, WN, KN, KN, SK, KN, KN, QN, CR }, 	 //	 698	 2000
{ AC, KN, QN, KN, JA, AC, KN, AC, KN, WN, SK, KN, KN, KN, TN }, 	 //	 699	 2000
{ AC, KN, AC, KN, AC, AC, KN, KN, KN, KN, SK, KN, WN, KN, QN }, 	 //	 700	 2000
{ AC, KN, ST, AC, KN, AC, KN, AC, KN, AC, SK, ST, KN, QN, LO }, 	 //	 701	 2000
{ AC, JA, KN, KN, KN, AC, JA, WN, KN, KN, SK, JA, TN, KN, KN }, 	 //	 702	 2000
{ AC, SH, PF, AC, KN, AC, TN, KN, KN, KN, SK, TN, KN, QN, SK }, 	 //	 703	 2000
{ AC, WN, KN, LO, KN, AC, AC, KN, KN, SK, SK, KN, KN, KN, QN }, 	 //	 704	 2000
{ AC, AC, KN, KN, QN, AC, KN, KN, KN, QN, SK, QN, SH, KN, SH }, 	 //	 705	 2000
{ AC, JA, KN, KN, KN, AC, TN, KN, KN, AC, SK, AC, KN, KN, LO }, 	 //	 706	 2000
{ AC, TN, KN, KN, JA, AC, AC, SH, AC, JA, SK, AC, AC, PF, JA }, 	 //	 707	 2000
{ AC, AC, ST, AC, SK, AC, AC, AC, AC, KN, SK, AC, KN, AC, KN }, 	 //	 708	 2000
{ AC, AC, PF, PF, KN, AC, AC, KN, KN, KN, SK, AC, KN, KN, SK }, 	 //	 709	 2000
{ AC, AC, KN, WN, QN, AC, AC, SH, AC, PF, SK, PF, AC, KN, JA }, 	 //	 710	 2000
{ AC, AC, PF, LO, AC, AC, PF, KN, KN, KN, SK, KN, KN, KN, QN }, 	 //	 711	 2000
{ AC, KN, KN, LO, AC, AC, KN, KN, KN, AC, SK, KN, SH, KN, AC }, 	 //	 712	 2000
{ AC, KN, AC, LO, QN, AC, KN, WN, KN, PF, SK, KN, KN, KN, JA }, 	 //	 713	 2000
{ AC, KN, KN, LO, KN, AC, AC, KN, KN, KN, SK, SH, SH, KN, KN }, 	 //	 714	 2000
{ AC, KN, QN, PF, KN, AC, AC, AC, AC, KN, SK, SH, KN, AC, CR }, 	 //	 715	 2000
{ AC, AC, SH, TN, TN, SK, SH, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 716	 2000
{ AC, SH, KN, PF, CR, SK, AC, KN, KN, KN, KN, AC, SH, KN, KN }, 	 //	 717	 2000
{ AC, SH, QN, PF, TN, SK, AC, AC, AC, AC, KN, AC, KN, AC, AC }, 	 //	 718	 2000
{ AC, SH, QN, AC, LO, SK, AC, AC, AC, AC, KN, AC, KN, LO, AC }, 	 //	 719	 2000
{ AC, SH, AC, KN, AC, SK, AC, KN, AC, AC, KN, AC, WN, PF, AC }, 	 //	 720	 2000
{ AC, AC, AC, AC, TN, SK, AC, WN, LO, TN, KN, AC, KN, KN, TN }, 	 //	 721	 2000
{ AC, AC, KN, KN, QN, SK, AC, SH, AC, QN, KN, LO, AC, PF, QN }, 	 //	 722	 2000
{ AC, AC, PF, AC, KN, SK, LO, KN, LO, SK, KN, KN, KN, KN, QN }, 	 //	 723	 2000
{ AC, AC, KN, SK, TN, SK, LO, KN, QN, TN, KN, KN, KN, KN, TN }, 	 //	 724	 2000
{ AC, AC, AC, AC, SH, SK, LO, AC, AC, JA, KN, KN, WN, AC, JA }, 	 //	 725	 2000
{ AC, LO, KN, LO, WN, SK, KN, WN, KN, TN, KN, KN, TN, KN, TN }, 	 //	 726	 2000
{ AC, LO, ST, AC, SK, SK, KN, AC, PF, QN, KN, KN, KN, KN, QN }, 	 //	 727	 2000
{ AC, LO, KN, AC, QN, SK, KN, KN, PF, SH, KN, KN, KN, AC, JA }, 	 //	 728	 2000
{ AC, LO, KN, KN, QN, SK, KN, PF, KN, QN, KN, KN, QN, SK, QN }, 	 //	 729	 2000
{ AC, KN, KN, JA, SK, SK, KN, KN, JA, KN, KN, KN, KN, SH, KN }, 	 //	 730	 2000
{ AC, KN, KN, KN, SK, SK, KN, SH, QN, KN, KN, ST, AC, ST, KN }, 	 //	 731	 2000
{ AC, KN, KN, KN, ST, SK, ST, KN, KN, AC, KN, QN, PF, SK, KN }, 	 //	 732	 2000
{ AC, JA, KN, KN, KN, SK, JA, QN, KN, KN, KN, SH, PF, WN, KN }, 	 //	 733	 2000
{ AC, TN, KN, PF, CR, SK, WN, KN, KN, QN, KN, AC, KN, KN, KN }, 	 //	 734	 2000
{ AC, WN, WN, SK, KN, SK, AC, KN, QN, AC, KN, KN, KN, KN, LO }, 	 //	 735	 2000
{ AC, AC, KN, LO, JA, SK, KN, QN, KN, JA, KN, QN, PF, KN, JA }, 	 //	 736	 2000
{ AC, KN, KN, KN, CR, SK, QN, SH, KN, KN, KN, ST, AC, WN, KN }, 	 //	 737	 2000
{ AC, TN, JA, KN, TN, SK, AC, TN, AC, ST, KN, AC, AC, PF, AC }, 	 //	 738	 2000
{ AC, AC, AC, QN, KN, SK, AC, KN, QN, SK, KN, PF, QN, QN, QN }, 	 //	 739	 2000
{ AC, PF, KN, QN, AC, SK, KN, KN, QN, AC, KN, KN, KN, SK, AC }, 	 //	 740	 2000
{ AC, KN, KN, WN, TN, SK, KN, KN, QN, AC, KN, KN, KN, QN, AC }, 	 //	 741	 2000
{ AC, KN, KN, PF, KN, SK, KN, PF, KN, AC, KN, KN, QN, KN, LO }, 	 //	 742	 2000
{ AC, SK, KN, KN, KN, SK, QN, SH, KN, KN, KN, KN, AC, WN, KN }, 	 //	 743	 2000
{ SK, SH, AC, QN, AC, KN, AC, AC, KN, AC, KN, AC, AC, AC, AC }, 	 //	 744	 2000
{ SK, AC, QN, LO, KN, KN, AC, AC, KN, KN, KN, LO, KN, KN, KN }, 	 //	 745	 2000
{ SK, AC, KN, KN, KN, KN, LO, WN, KN, KN, KN, KN, TN, KN, KN }, 	 //	 746	 2000
{ SK, AC, QN, KN, JA, KN, LO, PF, KN, TN, KN, KN, KN, KN, AC }, 	 //	 747	 2000
{ SK, LO, KN, KN, TN, KN, KN, QN, KN, AC, KN, KN, PF, KN, AC }, 	 //	 748	 2000
{ SK, LO, KN, PF, KN, KN, KN, SH, KN, AC, KN, KN, AC, KN, LO }, 	 //	 749	 2000
{ SK, LO, KN, JA, CR, KN, KN, KN, TN, QN, KN, KN, PF, AC, KN }, 	 //	 750	 2000
{ SK, KN, WN, TN, JA, KN, KN, KN, WN, JA, KN, KN, KN, AC, JA }, 	 //	 751	 2000
{ SK, KN, KN, QN, KN, KN, KN, QN, KN, SK, KN, ST, PF, AC, QN }, 	 //	 752	 2000
{ SK, KN, KN, JA, SK, KN, KN, KN, JA, KN, KN, ST, PF, JA, KN }, 	 //	 753	 2000
{ SK, KN, KN, KN, KN, KN, ST, SH, KN, KN, KN, QN, AC, KN, CR }, 	 //	 754	 2000
{ SK, KN, QN, KN, KN, KN, ST, AC, KN, KN, KN, QN, KN, KN, KN }, 	 //	 755	 2000
{ SK, QN, WN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, CR }, 	 //	 756	 2000
{ SK, JA, QN, LO, KN, KN, JA, AC, KN, KN, KN, SH, KN, KN, KN }, 	 //	 757	 2000
{ SK, AC, KN, WN, QN, KN, KN, KN, AC, SH, KN, QN, KN, KN, JA }, 	 //	 758	 2000
{ SK, AC, KN, AC, LO, KN, KN, KN, LO, AC, KN, QN, PF, KN, AC }, 	 //	 759	 2000
{ SK, AC, KN, TN, QN, KN, KN, KN, TN, PF, KN, QN, PF, TN, JA }, 	 //	 760	 2000
{ SK, ST, KN, KN, KN, KN, JA, QN, KN, KN, KN, TN, PF, SK, KN }, 	 //	 761	 2000
{ SK, TN, AC, TN, JA, KN, AC, PF, AC, TN, KN, AC, QN, AC, AC }, 	 //	 762	 2000
{ SK, AC, ST, TN, LO, KN, AC, AC, AC, AC, KN, AC, KN, AC, AC }, 	 //	 763	 2000
{ SK, AC, AC, AC, AC, KN, AC, AC, LO, LO, KN, PF, AC, KN, AC }, 	 //	 764	 2000
{ SK, AC, ST, SK, QN, KN, PF, AC, QN, KN, KN, KN, KN, KN, AC }, 	 //	 765	 2000
{ SK, AC, AC, AC, AC, KN, PF, PF, LO, AC, KN, KN, QN, KN, CR }, 	 //	 766	 2000
{ SK, PF, KN, PF, AC, KN, KN, KN, AC, AC, KN, KN, SH, AC, CR }, 	 //	 767	 2000
{ SK, PF, KN, KN, SK, KN, KN, KN, QN, QN, KN, KN, SH, ST, QN }, 	 //	 768	 2000
{ SK, PF, KN, TN, PF, KN, KN, KN, WN, JA, KN, KN, PF, AC, TN }, 	 //	 769	 2000
{ SK, PF, KN, TN, WN, KN, KN, KN, AC, TN, KN, KN, PF, AC, TN }, 	 //	 770	 2000
{ SK, PF, KN, KN, PF, KN, KN, PF, KN, JA, KN, KN, QN, SK, TN }, 	 //	 771	 2000
{ SK, PF, KN, QN, QN, KN, KN, PF, KN, PF, KN, KN, QN, AC, JA }, 	 //	 772	 2000
{ SK, KN, KN, PF, JA, KN, KN, WN, KN, JA, KN, KN, TN, KN, JA }, 	 //	 773	 2000
{ SK, KN, AC, SK, QN, KN, KN, WN, QN, QN, KN, KN, KN, KN, QN }, 	 //	 774	 2000
{ SK, KN, WN, JA, AC, KN, KN, KN, TN, AC, KN, KN, KN, AC, SK }, 	 //	 775	 2000
{ SK, KN, KN, ST, KN, KN, KN, KN, JA, KN, KN, KN, PF, TN, KN }, 	 //	 776	 2000
{ SK, KN, KN, WN, PF, KN, KN, KN, QN, JA, KN, SK, KN, QN, TN }, 	 //	 777	 2000
{ SK, KN, KN, QN, KN, KN, KN, SH, KN, KN, KN, SK, AC, AC, CR }, 	 //	 778	 2000
{ SK, KN, KN, AC, AC, KN, KN, KN, PF, SK, KN, SK, KN, AC, KN }, 	 //	 779	 2000
{ SK, KN, KN, QN, WN, KN, KN, KN, ST, TN, KN, SK, PF, JA, TN }, 	 //	 780	 2000
{ SK, KN, KN, LO, WN, KN, KN, PF, KN, TN, KN, SK, QN, KN, TN }, 	 //	 781	 2000
{ SK, KN, AC, LO, AC, KN, KN, KN, KN, LO, KN, SK, WN, KN, AC }, 	 //	 782	 2000
{ SK, QN, KN, KN, TN, KN, KN, WN, KN, TN, KN, AC, TN, KN, TN }, 	 //	 783	 2000
{ SK, QN, KN, TN, QN, KN, KN, KN, TN, QN, KN, AC, KN, WN, SH }, 	 //	 784	 2000
{ SK, QN, KN, QN, KN, KN, KN, KN, QN, AC, KN, AC, SH, QN, LO }, 	 //	 785	 2000
{ SK, QN, AC, KN, TN, KN, KN, KN, KN, AC, KN, AC, WN, SK, AC }, 	 //	 786	 2000
{ SK, KN, QN, AC, AC, KN, AC, AC, AC, AC, KN, SH, KN, LO, CR }, 	 //	 787	 2000
{ KN, AC, KN, KN, KN, KN, LO, PF, KN, KN, KN, KN, QN, KN, KN }, 	 //	 788	 2000
{ KN, LO, ST, ST, JA, KN, KN, AC, JA, JA, KN, KN, KN, TN, JA }, 	 //	 789	 2000
{ KN, LO, KN, TN, SH, KN, KN, KN, TN, JA, KN, KN, SH, TN, JA }, 	 //	 790	 2000
{ KN, LO, KN, SK, JA, KN, KN, KN, QN, JA, KN, KN, SH, KN, WN }, 	 //	 791	 2000
{ KN, LO, KN, LO, QN, KN, KN, SH, KN, QN, KN, KN, AC, KN, SH }, 	 //	 792	 2000
{ KN, LO, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, PF, LO, CR }, 	 //	 793	 2000
{ KN, LO, KN, KN, SK, KN, KN, KN, QN, QN, KN, KN, PF, ST, QN }, 	 //	 794	 2000
{ KN, LO, KN, LO, PF, KN, KN, PF, KN, JA, KN, KN, QN, KN, TN }, 	 //	 795	 2000
{ KN, LO, KN, PF, KN, KN, KN, PF, KN, QN, KN, KN, QN, KN, PF }, 	 //	 796	 2000
{ KN, LO, KN, KN, KN, KN, KN, PF, AC, KN, KN, KN, QN, PF, SK }, 	 //	 797	 2000
{ KN, LO, QN, SK, KN, KN, KN, AC, JA, AC, KN, KN, KN, JA, LO }, 	 //	 798	 2000
{ KN, LO, AC, LO, JA, KN, KN, KN, KN, JA, KN, KN, WN, KN, WN }, 	 //	 799	 2000
{ KN, KN, KN, TN, QN, KN, KN, QN, TN, PF, KN, KN, PF, TN, JA }, 	 //	 800	 2000
{ KN, KN, QN, TN, JA, KN, KN, PF, WN, JA, KN, KN, KN, AC, WN }, 	 //	 801	 2000
{ KN, KN, AC, SK, AC, KN, KN, WN, JA, KN, KN, KN, KN, JA, QN }, 	 //	 802	 2000
{ KN, KN, PF, PF, QN, KN, KN, KN, AC, KN, KN, ST, KN, AC, AC }, 	 //	 803	 2000
{ KN, KN, PF, SH, CR, KN, KN, KN, TN, QN, KN, ST, KN, TN, KN }, 	 //	 804	 2000
{ KN, KN, KN, WN, LO, KN, KN, PF, AC, AC, KN, ST, QN, KN, AC }, 	 //	 805	 2000
{ KN, KN, KN, KN, AC, KN, ST, QN, KN, AC, KN, QN, PF, KN, AC }, 	 //	 806	 2000
{ KN, KN, KN, KN, QN, KN, ST, KN, KN, QN, KN, QN, KN, SK, SH }, 	 //	 807	 2000
{ KN, SK, KN, AC, CR, KN, JA, KN, KN, KN, KN, JA, SH, QN, KN }, 	 //	 808	 2000
{ KN, JA, QN, KN, KN, KN, JA, PF, KN, KN, KN, JA, KN, KN, KN }, 	 //	 809	 2000
{ KN, TN, KN, LO, AC, KN, TN, KN, KN, SK, KN, TN, KN, KN, KN }, 	 //	 810	 2000
{ KN, WN, WN, PF, AC, KN, AC, KN, KN, LO, KN, KN, KN, KN, AC }, 	 //	 811	 2000
{ KN, AC, ST, LO, AC, KN, KN, AC, KN, LO, KN, QN, KN, KN, AC }, 	 //	 812	 2000
{ KN, AC, AC, AC, AC, KN, KN, AC, PF, KN, KN, QN, AC, AC, QN }, 	 //	 813	 2000
{ KN, AC, KN, SH, KN, KN, KN, KN, TN, QN, KN, QN, PF, TN, PF }, 	 //	 814	 2000
{ KN, AC, KN, JA, KN, KN, KN, KN, TN, KN, KN, QN, PF, AC, CR }, 	 //	 815	 2000
{ KN, AC, QN, SK, ST, KN, KN, AC, QN, AC, KN, QN, KN, KN, KN }, 	 //	 816	 2000
{ KN, AC, QN, KN, SH, KN, PF, PF, KN, JA, KN, KN, KN, KN, JA }, 	 //	 817	 2000
{ KN, AC, WN, LO, JA, KN, PF, KN, KN, JA, KN, KN, KN, KN, WN }, 	 //	 818	 2000
{ KN, AC, WN, KN, AC, KN, PF, KN, KN, AC, KN, KN, KN, KN, CR }, 	 //	 819	 2000
{ KN, PF, KN, AC, JA, KN, KN, WN, KN, TN, KN, KN, TN, QN, AC }, 	 //	 820	 2000
{ KN, PF, KN, ST, JA, KN, KN, KN, JA, JA, KN, KN, PF, TN, WN }, 	 //	 821	 2000
{ KN, PF, QN, AC, SK, KN, KN, AC, AC, KN, KN, KN, KN, LO, KN }, 	 //	 822	 2000
{ KN, KN, KN, AC, JA, KN, KN, QN, PF, JA, KN, KN, PF, AC, WN }, 	 //	 823	 2000
{ KN, KN, KN, TN, SK, KN, KN, QN, WN, KN, KN, KN, PF, AC, KN }, 	 //	 824	 2000
{ KN, KN, QN, TN, JA, KN, KN, AC, WN, WN, KN, KN, KN, AC, TN }, 	 //	 825	 2000
{ KN, KN, KN, AC, ST, KN, KN, WN, LO, AC, KN, SK, TN, KN, KN }, 	 //	 826	 2000
{ KN, KN, ST, QN, JA, KN, KN, AC, KN, WN, KN, SK, KN, AC, TN }, 	 //	 827	 2000
{ KN, KN, KN, QN, JA, KN, KN, SH, QN, TN, KN, SK, AC, QN, AC }, 	 //	 828	 2000
{ KN, KN, KN, AC, JA, KN, KN, PF, AC, JA, KN, SK, QN, PF, WN }, 	 //	 829	 2000
{ KN, KN, KN, KN, JA, KN, SK, WN, KN, WN, KN, QN, TN, WN, TN }, 	 //	 830	 2000
{ KN, QN, KN, QN, SK, KN, KN, KN, ST, QN, KN, AC, SH, JA, QN }, 	 //	 831	 2000
{ KN, SH, AC, WN, TN, KN, AC, WN, AC, AC, WN, AC, KN, KN, AC }, 	 //	 832	 2000
{ KN, AC, AC, KN, AC, KN, AC, PF, AC, AC, WN, LO, QN, PF, AC }, 	 //	 833	 2000
{ KN, LO, PF, PF, QN, KN, KN, KN, AC, KN, WN, KN, KN, AC, AC }, 	 //	 834	 2000
{ KN, LO, PF, ST, JA, KN, KN, KN, JA, JA, WN, KN, KN, TN, WN }, 	 //	 835	 2000
{ KN, LO, PF, ST, TN, KN, KN, KN, JA, TN, WN, KN, KN, TN, TN }, 	 //	 836	 2000
{ KN, LO, KN, SH, KN, KN, KN, KN, TN, QN, WN, KN, KN, TN, PF }, 	 //	 837	 2000
{ KN, KN, KN, KN, JA, KN, KN, SH, WN, TN, WN, KN, AC, QN, AC }, 	 //	 838	 2000
{ KN, KN, KN, KN, AC, KN, KN, SH, WN, AC, WN, KN, AC, QN, SK }, 	 //	 839	 2000
{ KN, KN, KN, KN, QN, KN, ST, SH, QN, SH, WN, QN, AC, ST, JA }, 	 //	 840	 2000
{ KN, QN, QN, KN, QN, KN, QN, QN, QN, SH, WN, SK, QN, ST, JA }, 	 //	 841	 2000
{ KN, SH, KN, PF, ST, KN, TN, KN, KN, AC, WN, TN, KN, KN, KN }, 	 //	 842	 2000
{ KN, TN, KN, TN, TN, KN, WN, SH, WN, ST, WN, AC, AC, AC, AC }, 	 //	 843	 2000
{ KN, AC, QN, KN, AC, KN, KN, PF, KN, AC, WN, QN, KN, WN, SK }, 	 //	 844	 2000
{ KN, AC, WN, JA, QN, KN, KN, KN, SH, PF, WN, QN, KN, TN, JA }, 	 //	 845	 2000
{ KN, KN, KN, KN, QN, KN, QN, KN, QN, QN, WN, ST, KN, ST, SH }, 	 //	 846	 2000
{ KN, KN, KN, KN, LO, KN, QN, PF, KN, AC, WN, ST, QN, KN, AC }, 	 //	 847	 2000
{ KN, JA, PF, AC, AC, KN, TN, QN, PF, AC, WN, AC, AC, AC, AC }, 	 //	 848	 2000
{ KN, PF, WN, JA, SH, KN, KN, KN, JA, JA, WN, KN, KN, JA, JA }, 	 //	 849	 2000
{ KN, PF, KN, AC, AC, KN, KN, KN, AC, KN, WN, KN, KN, PF, QN }, 	 //	 850	 2000
{ KN, KN, AC, LO, JA, KN, KN, KN, KN, JA, WN, KN, QN, KN, WN }, 	 //	 851	 2000
{ KN, KN, PF, JA, KN, KN, KN, KN, JA, QN, WN, KN, KN, SH, PF }, 	 //	 852	 2000
{ KN, KN, KN, SH, KN, KN, KN, KN, TN, KN, WN, KN, SH, TN, KN }, 	 //	 853	 2000
{ KN, KN, KN, ST, QN, KN, KN, KN, JA, QN, WN, KN, SH, TN, QN }, 	 //	 854	 2000
{ KN, KN, WN, KN, KN, KN, KN, KN, AC, KN, WN, KN, KN, PF, SK }, 	 //	 855	 2000
{ KN, KN, KN, JA, TN, KN, KN, KN, SH, TN, WN, KN, PF, TN, TN }, 	 //	 856	 2000
{ KN, KN, KN, QN, JA, KN, KN, KN, ST, WN, WN, KN, PF, JA, TN }, 	 //	 857	 2000
{ KN, KN, PF, AC, TN, KN, KN, KN, AC, TN, WN, SK, KN, LO, TN }, 	 //	 858	 2000
{ KN, KN, PF, AC, PF, KN, KN, KN, PF, JA, WN, SK, KN, KN, TN }, 	 //	 859	 2000
{ KN, KN, KN, AC, KN, KN, KN, KN, PF, AC, WN, SK, SH, AC, LO }, 	 //	 860	 2000
{ KN, KN, KN, TN, CR, KN, KN, KN, WN, KN, WN, SK, PF, AC, KN }, 	 //	 861	 2000
{ KN, KN, KN, TN, QN, KN, KN, KN, WN, PF, WN, SK, PF, AC, JA }, 	 //	 862	 2000
{ KN, KN, AC, PF, AC, KN, KN, KN, KN, SK, WN, SK, WN, KN, KN }, 	 //	 863	 2000
{ KN, KN, KN, KN, AC, KN, SK, WN, KN, AC, WN, QN, TN, KN, AC }, 	 //	 864	 2000
{ KN, KN, KN, KN, JA, KN, SK, KN, SK, WN, WN, QN, KN, QN, TN }, 	 //	 865	 2000
{ KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, WN, KN, PF, KN, SK }, 	 //	 866	 2000
{ KN, QN, PF, WN, TN, KN, KN, KN, AC, ST, WN, AC, KN, KN, AC }, 	 //	 867	 2000
{ KN, QN, KN, SK, AC, KN, KN, KN, QN, LO, WN, AC, KN, KN, AC }, 	 //	 868	 2000
{ KN, QN, KN, WN, SH, KN, KN, KN, QN, JA, WN, AC, KN, QN, JA }, 	 //	 869	 2000
{ KN, AC, KN, AC, AC, WN, SH, SH, PF, LO, QN, AC, AC, AC, AC }, 	 //	 870	 2000
{ KN, AC, AC, AC, AC, WN, LO, AC, PF, AC, QN, KN, AC, KN, CR }, 	 //	 871	 2000
{ KN, KN, KN, WN, CR, WN, KN, KN, QN, KN, QN, KN, KN, QN, KN }, 	 //	 872	 2000
{ KN, KN, KN, QN, KN, WN, KN, KN, SK, KN, QN, KN, KN, JA, KN }, 	 //	 873	 2000
{ KN, KN, KN, KN, QN, WN, KN, KN, AC, KN, QN, KN, SH, PF, AC }, 	 //	 874	 2000
{ KN, KN, KN, KN, JA, WN, KN, SH, WN, WN, QN, KN, AC, QN, TN }, 	 //	 875	 2000
{ KN, KN, KN, JA, CR, WN, KN, KN, TN, QN, QN, ST, KN, AC, KN }, 	 //	 876	 2000
{ KN, KN, QN, QN, CR, WN, KN, AC, KN, KN, QN, ST, KN, AC, KN }, 	 //	 877	 2000
{ KN, ST, AC, AC, AC, WN, QN, KN, AC, AC, QN, QN, QN, LO, SK }, 	 //	 878	 2000
{ KN, WN, PF, KN, KN, WN, AC, KN, KN, KN, QN, KN, KN, WN, SK }, 	 //	 879	 2000
{ KN, JA, PF, LO, KN, WN, TN, KN, KN, KN, QN, AC, KN, KN, CR }, 	 //	 880	 2000
{ KN, JA, AC, PF, KN, WN, TN, WN, KN, KN, QN, AC, KN, KN, KN }, 	 //	 881	 2000
{ KN, JA, WN, KN, KN, WN, TN, KN, KN, KN, QN, AC, KN, SK, CR }, 	 //	 882	 2000
{ KN, TN, KN, WN, AC, WN, AC, SH, AC, AC, QN, AC, AC, KN, AC }, 	 //	 883	 2000
{ KN, TN, AC, TN, AC, WN, AC, AC, WN, LO, QN, AC, AC, AC, AC }, 	 //	 884	 2000
{ KN, AC, PF, LO, CR, WN, AC, KN, KN, KN, QN, AC, KN, KN, KN }, 	 //	 885	 2000
{ KN, AC, AC, AC, AC, WN, AC, PF, LO, LO, QN, PF, QN, KN, AC }, 	 //	 886	 2000
{ KN, AC, JA, AC, AC, WN, AC, TN, AC, SK, QN, PF, AC, PF, KN }, 	 //	 887	 2000
{ KN, PF, QN, AC, TN, WN, KN, PF, KN, TN, QN, KN, KN, QN, TN }, 	 //	 888	 2000
{ KN, KN, QN, AC, QN, WN, KN, PF, PF, QN, QN, KN, KN, KN, QN }, 	 //	 889	 2000
{ KN, KN, KN, JA, AC, WN, KN, KN, JA, SK, QN, KN, KN, SH, KN }, 	 //	 890	 2000
{ KN, KN, KN, ST, KN, WN, KN, KN, JA, KN, QN, KN, KN, TN, CR }, 	 //	 891	 2000
{ KN, KN, AC, AC, KN, WN, KN, WN, LO, QN, QN, KN, KN, KN, PF }, 	 //	 892	 2000
{ KN, KN, ST, AC, QN, WN, KN, AC, KN, KN, QN, SK, KN, QN, AC }, 	 //	 893	 2000
{ KN, KN, KN, PF, TN, WN, KN, PF, KN, ST, QN, SK, QN, KN, AC }, 	 //	 894	 2000
{ KN, KN, AC, LO, KN, WN, KN, KN, KN, KN, QN, SK, WN, KN, KN }, 	 //	 895	 2000
{ WN, AC, KN, KN, SK, QN, SH, KN, KN, KN, KN, AC, KN, SK, KN }, 	 //	 896	 2000
{ WN, AC, QN, AC, KN, QN, AC, AC, AC, AC, KN, AC, KN, AC, LO }, 	 //	 897	 2000
{ WN, LO, QN, KN, QN, QN, KN, PF, KN, KN, KN, KN, KN, WN, AC }, 	 //	 898	 2000
{ WN, LO, KN, AC, KN, QN, KN, KN, AC, AC, KN, KN, KN, AC, LO }, 	 //	 899	 2000
{ WN, KN, KN, KN, TN, QN, KN, KN, WN, AC, KN, ST, SH, QN, AC }, 	 //	 900	 2000
{ WN, QN, KN, KN, KN, QN, QN, SH, KN, KN, KN, SK, AC, KN, KN }, 	 //	 901	 2000
{ WN, SK, KN, KN, SK, QN, JA, KN, KN, KN, KN, JA, KN, SK, KN }, 	 //	 902	 2000
{ WN, JA, KN, KN, ST, QN, JA, KN, KN, AC, KN, SH, KN, KN, KN }, 	 //	 903	 2000
{ WN, WN, KN, QN, KN, QN, AC, KN, KN, QN, KN, KN, KN, AC, PF }, 	 //	 904	 2000
{ WN, AC, KN, KN, TN, QN, KN, PF, KN, AC, KN, QN, QN, WN, AC }, 	 //	 905	 2000
{ WN, QN, QN, LO, KN, QN, ST, PF, KN, KN, KN, JA, KN, KN, KN }, 	 //	 906	 2000
{ WN, AC, TN, QN, AC, QN, AC, AC, KN, AC, KN, AC, AC, AC, AC }, 	 //	 907	 2000
{ WN, AC, AC, AC, AC, QN, AC, AC, KN, AC, KN, PF, WN, QN, CR }, 	 //	 908	 2000
{ WN, AC, KN, LO, KN, QN, PF, KN, KN, KN, KN, KN, SH, KN, KN }, 	 //	 909	 2000
{ WN, PF, KN, AC, QN, QN, KN, KN, AC, SH, KN, KN, KN, LO, JA }, 	 //	 910	 2000
{ WN, PF, KN, TN, KN, QN, KN, KN, TN, KN, KN, KN, KN, TN, SK }, 	 //	 911	 2000
{ WN, PF, AC, AC, LO, QN, KN, WN, LO, AC, KN, KN, KN, KN, AC }, 	 //	 912	 2000
{ WN, PF, QN, AC, AC, QN, KN, AC, KN, KN, KN, KN, KN, QN, QN }, 	 //	 913	 2000
{ WN, PF, AC, KN, KN, QN, KN, KN, KN, KN, KN, KN, WN, KN, SK }, 	 //	 914	 2000
{ WN, KN, QN, QN, JA, QN, KN, PF, KN, JA, KN, KN, KN, AC, WN }, 	 //	 915	 2000
{ WN, KN, KN, QN, KN, QN, KN, KN, SK, KN, KN, KN, KN, JA, CR }, 	 //	 916	 2000
{ WN, KN, KN, JA, WN, QN, KN, KN, JA, TN, KN, KN, KN, SH, TN }, 	 //	 917	 2000
{ WN, KN, KN, AC, AC, QN, KN, KN, AC, SK, KN, KN, KN, PF, KN }, 	 //	 918	 2000
{ WN, KN, KN, PF, JA, QN, KN, SH, KN, WN, KN, KN, AC, KN, TN }, 	 //	 919	 2000
{ WN, KN, KN, AC, TN, QN, KN, KN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 920	 2000
{ WN, QN, JA, JA, AC, QN, KN, ST, TN, AC, KN, AC, AC, AC, AC }, 	 //	 921	 2000
{ WN, KN, KN, KN, KN, QN, AC, QN, WN, QN, KN, SH, PF, QN, PF }, 	 //	 922	 2000
{ QN, AC, JA, TN, CR, KN, SH, TN, WN, KN, AC, AC, AC, AC, KN }, 	 //	 923	 2000
{ QN, AC, AC, TN, KN, KN, SH, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 924	 2000
{ QN, LO, KN, KN, KN, KN, KN, KN, SK, QN, AC, KN, PF, QN, PF }, 	 //	 925	 2000
{ QN, LO, AC, AC, JA, KN, KN, KN, KN, JA, AC, KN, WN, QN, JA }, 	 //	 926	 2000
{ QN, KN, KN, KN, PF, KN, KN, KN, SK, JA, AC, ST, KN, QN, TN }, 	 //	 927	 2000
{ QN, ST, AC, AC, AC, KN, QN, PF, AC, KN, AC, QN, QN, LO, QN }, 	 //	 928	 2000
{ QN, ST, KN, LO, KN, KN, QN, KN, KN, KN, AC, QN, KN, KN, SK }, 	 //	 929	 2000
{ QN, TN, AC, AC, QN, KN, WN, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 930	 2000
{ QN, WN, AC, AC, SK, KN, AC, KN, AC, KN, AC, KN, QN, AC, KN }, 	 //	 931	 2000
{ QN, WN, PF, KN, AC, KN, AC, QN, AC, KN, AC, KN, AC, PF, QN }, 	 //	 932	 2000
{ QN, ST, PF, LO, SK, KN, JA, KN, KN, KN, AC, TN, KN, KN, KN }, 	 //	 933	 2000
{ QN, ST, KN, LO, KN, KN, JA, KN, KN, KN, AC, TN, KN, KN, SK }, 	 //	 934	 2000
{ QN, AC, AC, TN, KN, KN, AC, PF, AC, KN, AC, PF, QN, AC, SK }, 	 //	 935	 2000
{ QN, KN, QN, PF, TN, KN, KN, PF, KN, TN, AC, KN, KN, KN, ST }, 	 //	 936	 2000
{ QN, KN, AC, KN, CR, KN, KN, KN, KN, QN, AC, KN, WN, SK, KN }, 	 //	 937	 2000
{ QN, SK, PF, KN, SK, KN, QN, QN, QN, QN, AC, KN, QN, ST, QN }, 	 //	 938	 2000
{ QN, KN, AC, AC, QN, KN, AC, KN, AC, QN, AC, SH, QN, LO, QN }, 	 //	 939	 2000
{ QN, KN, AC, AC, QN, KN, AC, WN, AC, QN, AC, SH, KN, AC, SH }, 	 //	 940	 2000
{ KN, AC, WN, AC, KN, AC, SH, KN, KN, KN, LO, AC, KN, QN, CR }, 	 //	 941	 2000
{ KN, SH, QN, AC, SH, AC, AC, AC, AC, JA, LO, AC, KN, PF, JA }, 	 //	 942	 2000
{ KN, AC, QN, AC, CR, AC, AC, AC, AC, QN, LO, LO, KN, LO, KN }, 	 //	 943	 2000
{ KN, AC, WN, LO, AC, AC, LO, KN, KN, SK, LO, KN, KN, KN, KN }, 	 //	 944	 2000
{ KN, KN, KN, AC, JA, AC, KN, PF, KN, TN, LO, KN, QN, QN, AC }, 	 //	 945	 2000
{ KN, KN, KN, JA, JA, AC, KN, KN, JA, JA, LO, ST, KN, SH, WN }, 	 //	 946	 2000
{ KN, WN, PF, TN, AC, AC, AC, QN, AC, SK, LO, KN, AC, AC, KN }, 	 //	 947	 2000
{ KN, KN, KN, AC, SK, AC, QN, WN, KN, KN, LO, ST, TN, QN, KN }, 	 //	 948	 2000
{ KN, KN, KN, KN, AC, AC, QN, KN, KN, AC, LO, ST, KN, SK, CR }, 	 //	 949	 2000
{ KN, ST, KN, QN, SK, AC, JA, KN, KN, KN, LO, TN, KN, AC, KN }, 	 //	 950	 2000
{ KN, JA, TN, TN, LO, AC, TN, AC, WN, AC, LO, AC, AC, AC, AC }, 	 //	 951	 2000
{ KN, JA, AC, KN, KN, AC, TN, WN, KN, KN, LO, AC, KN, KN, KN }, 	 //	 952	 2000
{ KN, PF, QN, QN, JA, AC, KN, PF, KN, WN, LO, KN, KN, AC, TN }, 	 //	 953	 2000
{ KN, PF, QN, SK, LO, AC, KN, AC, QN, AC, LO, KN, KN, KN, AC }, 	 //	 954	 2000
{ KN, KN, KN, JA, TN, AC, KN, KN, SH, TN, LO, KN, KN, TN, TN }, 	 //	 955	 2000
{ KN, KN, KN, PF, QN, AC, KN, WN, KN, KN, LO, SK, TN, KN, AC }, 	 //	 956	 2000
{ KN, KN, KN, KN, PF, AC, KN, QN, QN, JA, LO, SK, PF, ST, TN }, 	 //	 957	 2000
{ KN, KN, KN, QN, SH, AC, KN, KN, SK, JA, LO, SK, KN, JA, JA }, 	 //	 958	 2000
{ KN, KN, KN, KN, JA, AC, AC, KN, QN, WN, LO, SH, KN, ST, TN }, 	 //	 959	 2000
{ KN, KN, KN, KN, QN, AC, AC, SH, QN, QN, LO, SH, AC, ST, QN }, 	 //	 960	 2000
{ KN, KN, AC, WN, QN, AC, AC, WN, AC, KN, LO, SH, KN, KN, AC }, 	 //	 961	 2000
