#include "ReelDefine.h"

unsigned char L5_Outcome_0100[1000][15]={	 //	 0	 100
{ AC, AC, SK, TN, TN, LO, AC, JA, TN, TN, AC, LO, TN, WN, TN }, 	 //	 1	 100
{ AC, LO, TN, TN, PF, LO, KN, TN, TN, JA, AC, KN, LO, TN, TN }, 	 //	 2	 100
{ AC, LO, TN, TN, PF, LO, KN, AC, TN, JA, AC, KN, AC, WN, TN }, 	 //	 3	 100
{ AC, KN, SK, JA, TN, LO, KN, JA, TN, TN, AC, KN, TN, AC, ST }, 	 //	 4	 100
{ AC, QN, TN, JA, PF, LO, QN, TN, SH, JA, AC, SK, TN, TN, TN }, 	 //	 5	 100
{ AC, JA, KN, JA, TN, LO, SH, WN, SH, AC, AC, TN, TN, TN, AC }, 	 //	 6	 100
{ AC, JA, KN, SH, CR, LO, SH, WN, TN, KN, AC, TN, TN, TN, KN }, 	 //	 7	 100
{ AC, JA, TN, JA, KN, LO, SH, TN, SH, KN, AC, TN, TN, TN, SK }, 	 //	 8	 100
{ AC, JA, TN, TN, JA, LO, SH, TN, TN, WN, AC, TN, TN, WN, TN }, 	 //	 9	 100
{ AC, SH, SK, JA, CR, LO, TN, JA, TN, QN, AC, TN, TN, AC, KN }, 	 //	 10	 100
{ AC, TN, WN, JA, JA, LO, TN, TN, SH, JA, AC, TN, TN, TN, JA }, 	 //	 11	 100
{ AC, TN, TN, TN, AC, LO, TN, LO, AC, AC, AC, TN, JA, AC, AC }, 	 //	 12	 100
{ AC, TN, TN, SH, JA, LO, TN, AC, TN, JA, AC, TN, AC, TN, JA }, 	 //	 13	 100
{ AC, TN, WN, TN, JA, LO, WN, TN, TN, TN, AC, AC, TN, TN, AC }, 	 //	 14	 100
{ AC, TN, TN, TN, QN, LO, WN, TN, TN, PF, AC, AC, TN, WN, JA }, 	 //	 15	 100
{ AC, JA, TN, SH, AC, LO, TN, LO, TN, KN, AC, AC, JA, TN, QN }, 	 //	 16	 100
{ AC, TN, TN, TN, KN, LO, AC, LO, AC, KN, AC, AC, JA, AC, SK }, 	 //	 17	 100
{ AC, TN, SK, JA, TN, LO, AC, JA, TN, TN, AC, AC, TN, AC, TN }, 	 //	 18	 100
{ AC, AC, TN, SH, JA, LO, AC, TN, TN, TN, AC, PF, LO, TN, AC }, 	 //	 19	 100
{ AC, AC, SK, ST, JA, LO, PF, JA, JA, WN, AC, KN, TN, TN, TN }, 	 //	 20	 100
{ AC, PF, KN, JA, TN, LO, KN, WN, TN, TN, AC, KN, TN, AC, TN }, 	 //	 21	 100
{ AC, KN, WN, ST, WN, LO, KN, TN, JA, TN, AC, KN, TN, TN, TN }, 	 //	 22	 100
{ AC, QN, KN, JA, WN, LO, KN, WN, SH, TN, AC, AC, TN, TN, TN }, 	 //	 23	 100
{ LO, AC, TN, JA, PF, AC, AC, TN, TN, JA, AC, LO, LO, AC, TN }, 	 //	 24	 100
{ LO, LO, TN, TN, TN, AC, KN, TN, AC, ST, AC, KN, TN, AC, AC }, 	 //	 25	 100
{ LO, KN, SK, SH, TN, AC, ST, JA, TN, ST, AC, QN, TN, TN, AC }, 	 //	 26	 100
{ LO, ST, TN, TN, TN, AC, QN, TN, AC, TN, AC, QN, TN, AC, ST }, 	 //	 27	 100
{ LO, JA, SK, TN, JA, AC, JA, JA, TN, WN, AC, SH, TN, TN, TN }, 	 //	 28	 100
{ LO, SH, KN, JA, KN, AC, TN, WN, TN, QN, AC, TN, TN, AC, PF }, 	 //	 29	 100
{ LO, SH, TN, ST, AC, AC, TN, TN, JA, AC, AC, TN, TN, TN, CR }, 	 //	 30	 100
{ LO, SH, SK, JA, AC, AC, TN, JA, SH, AC, AC, TN, TN, TN, CR }, 	 //	 31	 100
{ LO, TN, TN, JA, ST, AC, TN, TN, SH, AC, AC, TN, TN, TN, KN }, 	 //	 32	 100
{ LO, TN, TN, TN, SK, AC, TN, TN, WN, QN, AC, TN, LO, AC, QN }, 	 //	 33	 100
{ LO, TN, WN, ST, TN, AC, TN, TN, JA, TN, AC, WN, TN, TN, TN }, 	 //	 34	 100
{ LO, TN, TN, SH, KN, AC, TN, AC, TN, KN, AC, WN, AC, TN, CR }, 	 //	 35	 100
{ LO, TN, SK, SH, TN, AC, WN, JA, TN, ST, AC, AC, TN, TN, AC }, 	 //	 36	 100
{ LO, JA, KN, TN, SK, AC, TN, WN, TN, KN, AC, AC, TN, WN, KN }, 	 //	 37	 100
{ LO, JA, SK, SH, AC, AC, TN, JA, TN, AC, AC, AC, TN, TN, CR }, 	 //	 38	 100
{ LO, KN, JA, JA, TN, AC, KN, TN, TN, TN, AC, KN, AC, AC, TN }, 	 //	 39	 100
{ LO, KN, KN, SH, TN, AC, AC, WN, TN, AC, AC, SH, TN, TN, AC }, 	 //	 40	 100
{ AC, LO, TN, TN, TN, AC, KN, LO, TN, ST, AC, KN, JA, TN, AC }, 	 //	 41	 100
{ AC, LO, TN, JA, JA, AC, KN, LO, TN, WN, AC, KN, JA, AC, TN }, 	 //	 42	 100
{ AC, JA, KN, JA, WN, AC, JA, WN, SH, TN, AC, JA, TN, TN, TN }, 	 //	 43	 100
{ AC, JA, WN, ST, CR, AC, SH, TN, JA, QN, AC, TN, TN, TN, KN }, 	 //	 44	 100
{ AC, JA, TN, TN, JA, AC, SH, AC, TN, WN, AC, TN, AC, TN, TN }, 	 //	 45	 100
{ AC, SH, WN, ST, QN, AC, TN, TN, JA, QN, AC, TN, TN, TN, SH }, 	 //	 46	 100
{ AC, SH, JA, TN, QN, AC, TN, TN, TN, QN, AC, TN, AC, TN, QN }, 	 //	 47	 100
{ AC, TN, TN, SH, CR, AC, TN, AC, TN, QN, AC, WN, AC, TN, KN }, 	 //	 48	 100
{ AC, TN, TN, TN, QN, AC, WN, TN, TN, KN, AC, AC, LO, WN, AC }, 	 //	 49	 100
{ AC, QN, KN, ST, JA, AC, ST, WN, JA, WN, AC, JA, TN, TN, TN }, 	 //	 50	 100
{ AC, TN, TN, TN, KN, AC, AC, TN, TN, KN, AC, AC, LO, WN, SK }, 	 //	 51	 100
{ AC, KN, WN, JA, JA, AC, ST, TN, TN, TN, ST, QN, TN, AC, AC }, 	 //	 52	 100
{ AC, QN, WN, TN, WN, AC, QN, TN, TN, TN, ST, QN, TN, WN, TN }, 	 //	 53	 100
{ AC, QN, KN, JA, TN, AC, QN, WN, TN, AC, ST, SK, TN, AC, AC }, 	 //	 54	 100
{ AC, QN, WN, TN, WN, AC, SK, TN, TN, TN, ST, JA, TN, WN, TN }, 	 //	 55	 100
{ AC, TN, TN, SH, KN, AC, TN, LO, TN, SK, ST, TN, JA, TN, QN }, 	 //	 56	 100
{ AC, TN, TN, SH, KN, AC, TN, LO, TN, QN, ST, WN, JA, TN, PF }, 	 //	 57	 100
{ AC, TN, JA, TN, KN, AC, TN, TN, TN, AC, ST, WN, AC, WN, LO }, 	 //	 58	 100
{ AC, TN, TN, SH, JA, AC, WN, TN, TN, WN, ST, AC, LO, TN, TN }, 	 //	 59	 100
{ AC, WN, TN, TN, TN, AC, AC, TN, AC, TN, ST, KN, TN, AC, TN }, 	 //	 60	 100
{ AC, AC, JA, SH, WN, AC, KN, TN, TN, TN, ST, QN, AC, TN, TN }, 	 //	 61	 100
{ AC, ST, KN, JA, KN, AC, JA, WN, SH, KN, ST, TN, TN, TN, CR }, 	 //	 62	 100
{ AC, JA, KN, JA, SK, AC, TN, WN, TN, KN, ST, AC, TN, AC, KN }, 	 //	 63	 100
{ AC, JA, SK, TN, QN, AC, TN, JA, TN, KN, ST, AC, TN, TN, AC }, 	 //	 64	 100
{ AC, TN, TN, TN, KN, AC, AC, TN, AC, KN, ST, AC, TN, AC, SK }, 	 //	 65	 100
{ AC, QN, TN, SH, PF, AC, KN, AC, TN, JA, ST, AC, AC, TN, TN }, 	 //	 66	 100
{ AC, AC, TN, JA, PF, ST, SH, TN, SH, JA, KN, AC, TN, TN, TN }, 	 //	 67	 100
{ AC, AC, TN, TN, TN, ST, SH, AC, TN, AC, KN, AC, AC, WN, AC }, 	 //	 68	 100
{ AC, AC, TN, TN, TN, ST, AC, TN, WN, AC, KN, LO, LO, AC, AC }, 	 //	 69	 100
{ AC, KN, TN, TN, TN, ST, KN, TN, AC, ST, KN, ST, TN, AC, AC }, 	 //	 70	 100
{ AC, KN, TN, TN, JA, ST, KN, AC, TN, WN, KN, ST, AC, TN, TN }, 	 //	 71	 100
{ AC, QN, TN, JA, PF, ST, SK, LO, TN, JA, KN, JA, JA, AC, TN }, 	 //	 72	 100
{ AC, JA, TN, ST, SK, ST, SH, TN, JA, QN, KN, TN, TN, TN, QN }, 	 //	 73	 100
{ AC, SH, SK, TN, AC, ST, TN, JA, TN, AC, KN, TN, TN, WN, SK }, 	 //	 74	 100
{ AC, TN, SK, JA, KN, ST, TN, JA, SH, KN, KN, TN, TN, TN, KN }, 	 //	 75	 100
{ AC, TN, KN, JA, QN, ST, TN, WN, TN, QN, KN, WN, TN, AC, SH }, 	 //	 76	 100
{ AC, TN, TN, TN, KN, ST, WN, TN, WN, SK, KN, AC, TN, AC, QN }, 	 //	 77	 100
{ AC, JA, TN, JA, CR, ST, TN, LO, TN, KN, KN, AC, JA, AC, KN }, 	 //	 78	 100
{ AC, TN, TN, TN, KN, ST, AC, TN, AC, QN, KN, AC, LO, AC, PF }, 	 //	 79	 100
{ AC, AC, SK, SH, TN, ST, AC, JA, TN, ST, KN, PF, TN, TN, AC }, 	 //	 80	 100
{ AC, PF, TN, TN, TN, ST, KN, TN, WN, TN, KN, KN, LO, AC, ST }, 	 //	 81	 100
{ AC, PF, SK, ST, JA, ST, KN, JA, JA, WN, KN, KN, TN, TN, TN }, 	 //	 82	 100
{ AC, KN, TN, JA, TN, ST, KN, TN, SH, TN, KN, KN, TN, TN, TN }, 	 //	 83	 100
{ AC, KN, KN, ST, WN, ST, AC, WN, JA, TN, KN, SH, TN, TN, TN }, 	 //	 84	 100
{ ST, AC, TN, TN, WN, KN, SH, LO, TN, TN, KN, AC, JA, TN, TN }, 	 //	 85	 100
{ ST, AC, KN, TN, TN, KN, AC, WN, TN, TN, KN, AC, TN, TN, ST }, 	 //	 86	 100
{ ST, AC, TN, SH, JA, KN, AC, AC, TN, WN, KN, AC, AC, TN, TN }, 	 //	 87	 100
{ ST, AC, TN, SH, JA, KN, AC, TN, TN, WN, KN, LO, LO, TN, TN }, 	 //	 88	 100
{ ST, AC, SK, TN, TN, KN, LO, JA, TN, ST, KN, KN, TN, WN, AC }, 	 //	 89	 100
{ ST, SK, TN, TN, JA, KN, JA, TN, TN, TN, KN, JA, TN, TN, AC }, 	 //	 90	 100
{ ST, JA, KN, JA, SK, KN, SH, WN, SH, QN, KN, TN, TN, TN, QN }, 	 //	 91	 100
{ ST, JA, WN, SH, KN, KN, SH, TN, TN, SK, KN, TN, TN, TN, QN }, 	 //	 92	 100
{ ST, JA, TN, ST, TN, KN, SH, TN, JA, ST, KN, TN, TN, TN, AC }, 	 //	 93	 100
{ ST, SH, KN, ST, SK, KN, TN, WN, JA, QN, KN, TN, TN, TN, QN }, 	 //	 94	 100
{ ST, SH, TN, TN, TN, KN, TN, TN, WN, TN, KN, TN, TN, AC, ST }, 	 //	 95	 100
{ ST, TN, KN, TN, WN, KN, TN, WN, TN, TN, KN, WN, TN, WN, TN }, 	 //	 96	 100
{ ST, TN, TN, JA, JA, KN, TN, LO, TN, JA, KN, WN, JA, AC, JA }, 	 //	 97	 100
{ ST, TN, SK, SH, QN, KN, TN, JA, TN, KN, KN, WN, TN, TN, AC }, 	 //	 98	 100
{ ST, TN, JA, TN, WN, KN, WN, TN, TN, TN, KN, AC, AC, TN, TN }, 	 //	 99	 100
{ ST, QN, TN, TN, TN, KN, ST, TN, AC, AC, KN, JA, LO, AC, AC }, 	 //	 100	 100
{ ST, JA, KN, TN, QN, KN, TN, WN, TN, QN, KN, AC, TN, WN, SH }, 	 //	 101	 100
{ KN, AC, WN, JA, TN, KN, SH, TN, TN, AC, KN, AC, TN, AC, AC }, 	 //	 102	 100
{ KN, KN, SK, SH, JA, KN, KN, JA, TN, WN, KN, ST, TN, TN, TN }, 	 //	 103	 100
{ KN, KN, TN, JA, WN, KN, ST, TN, SH, TN, KN, QN, TN, TN, TN }, 	 //	 104	 100
{ KN, QN, TN, JA, PF, KN, QN, LO, TN, JA, KN, QN, JA, AC, TN }, 	 //	 105	 100
{ KN, SK, WN, TN, JA, KN, JA, TN, TN, TN, KN, JA, TN, TN, AC }, 	 //	 106	 100
{ KN, JA, KN, TN, WN, KN, JA, WN, TN, TN, KN, JA, TN, TN, TN }, 	 //	 107	 100
{ KN, JA, TN, TN, JA, KN, JA, TN, TN, TN, KN, JA, TN, TN, AC }, 	 //	 108	 100
{ KN, JA, KN, TN, TN, KN, JA, WN, TN, AC, KN, SH, TN, TN, AC }, 	 //	 109	 100
{ KN, JA, TN, SH, LO, KN, SH, TN, TN, AC, KN, TN, TN, TN, AC }, 	 //	 110	 100
{ KN, JA, TN, ST, AC, KN, SH, TN, JA, AC, KN, TN, TN, TN, AC }, 	 //	 111	 100
{ KN, SH, TN, JA, KN, KN, TN, LO, TN, SK, KN, TN, JA, AC, QN }, 	 //	 112	 100
{ KN, SH, TN, TN, TN, KN, TN, LO, AC, TN, KN, TN, JA, AC, ST }, 	 //	 113	 100
{ KN, SH, JA, SH, AC, KN, TN, TN, TN, AC, KN, TN, AC, TN, SK }, 	 //	 114	 100
{ KN, TN, TN, SH, QN, KN, TN, LO, TN, QN, KN, TN, JA, TN, SH }, 	 //	 115	 100
{ KN, TN, SK, TN, KN, KN, TN, JA, TN, KN, KN, TN, TN, WN, CR }, 	 //	 116	 100
{ KN, TN, KN, TN, JA, KN, TN, WN, TN, JA, KN, WN, TN, WN, WN }, 	 //	 117	 100
{ KN, TN, TN, TN, QN, KN, TN, LO, AC, SH, KN, WN, JA, AC, JA }, 	 //	 118	 100
{ KN, TN, TN, TN, KN, KN, TN, LO, AC, AC, KN, WN, JA, AC, LO }, 	 //	 119	 100
{ KN, TN, JA, SH, KN, KN, TN, TN, TN, QN, KN, WN, AC, TN, PF }, 	 //	 120	 100
{ KN, WN, TN, ST, TN, KN, AC, TN, JA, TN, KN, KN, TN, TN, TN }, 	 //	 121	 100
{ KN, KN, TN, TN, JA, KN, KN, TN, TN, WN, KN, SK, LO, WN, TN }, 	 //	 122	 100
{ KN, SH, SK, SH, TN, KN, AC, JA, TN, TN, SK, AC, TN, TN, ST }, 	 //	 123	 100
{ KN, AC, WN, ST, TN, KN, AC, TN, JA, TN, SK, AC, TN, TN, TN }, 	 //	 124	 100
{ KN, AC, WN, JA, JA, KN, AC, TN, TN, TN, SK, AC, TN, AC, AC }, 	 //	 125	 100
{ KN, AC, TN, SH, JA, KN, AC, TN, TN, WN, SK, AC, LO, TN, TN }, 	 //	 126	 100
{ KN, AC, SK, TN, TN, KN, AC, JA, TN, AC, SK, AC, TN, TN, AC }, 	 //	 127	 100
{ KN, KN, JA, SH, TN, KN, KN, TN, TN, TN, SK, ST, AC, TN, ST }, 	 //	 128	 100
{ KN, QN, TN, TN, JA, KN, QN, TN, TN, TN, SK, QN, LO, WN, AC }, 	 //	 129	 100
{ KN, JA, TN, TN, CR, KN, SH, TN, TN, QN, SK, TN, TN, TN, KN }, 	 //	 130	 100
{ KN, SH, TN, SH, ST, KN, TN, AC, TN, AC, SK, TN, AC, TN, KN }, 	 //	 131	 100
{ KN, TN, WN, JA, JA, KN, TN, TN, SH, WN, SK, WN, TN, TN, TN }, 	 //	 132	 100
{ KN, TN, KN, JA, TN, KN, WN, WN, TN, TN, SK, AC, TN, AC, ST }, 	 //	 133	 100
{ KN, TN, TN, TN, AC, KN, WN, TN, WN, AC, SK, AC, TN, AC, CR }, 	 //	 134	 100
{ KN, ST, WN, ST, TN, KN, JA, TN, JA, TN, SK, TN, TN, TN, ST }, 	 //	 135	 100
{ KN, TN, TN, TN, QN, KN, AC, AC, TN, SH, SK, AC, AC, WN, JA }, 	 //	 136	 100
{ KN, AC, TN, TN, WN, KN, PF, AC, TN, TN, SK, KN, AC, WN, TN }, 	 //	 137	 100
{ KN, KN, SK, TN, TN, KN, KN, JA, TN, TN, SK, KN, TN, WN, ST }, 	 //	 138	 100
{ KN, QN, TN, SH, TN, KN, KN, TN, TN, AC, SK, AC, TN, TN, AC }, 	 //	 139	 100
{ KN, KN, TN, SH, TN, KN, AC, TN, TN, ST, SK, SH, TN, TN, AC }, 	 //	 140	 100
{ KN, KN, JA, TN, WN, KN, AC, TN, TN, TN, SK, SH, AC, TN, TN }, 	 //	 141	 100
{ KN, SH, JA, TN, JA, SK, AC, TN, TN, TN, QN, AC, AC, TN, AC }, 	 //	 142	 100
{ KN, AC, TN, TN, JA, SK, AC, TN, TN, TN, QN, LO, LO, WN, AC }, 	 //	 143	 100
{ KN, AC, KN, SH, TN, SK, LO, WN, TN, AC, QN, KN, TN, TN, AC }, 	 //	 144	 100
{ KN, KN, TN, SH, JA, SK, KN, LO, TN, WN, QN, KN, JA, TN, TN }, 	 //	 145	 100
{ KN, KN, WN, ST, WN, SK, ST, TN, JA, TN, QN, QN, TN, TN, TN }, 	 //	 146	 100
{ KN, QN, TN, SH, TN, SK, QN, AC, TN, TN, QN, QN, AC, TN, TN }, 	 //	 147	 100
{ KN, TN, SK, TN, CR, SK, TN, JA, TN, QN, QN, WN, TN, TN, KN }, 	 //	 148	 100
{ KN, TN, KN, SH, TN, SK, WN, WN, TN, TN, QN, AC, TN, TN, ST }, 	 //	 149	 100
{ KN, WN, WN, TN, TN, SK, AC, TN, TN, ST, QN, KN, TN, WN, AC }, 	 //	 150	 100
{ KN, ST, TN, TN, AC, SK, JA, TN, TN, SK, QN, TN, TN, TN, KN }, 	 //	 151	 100
{ KN, JA, TN, TN, TN, SK, TN, LO, WN, AC, QN, AC, JA, AC, AC }, 	 //	 152	 100
{ KN, JA, SK, TN, AC, SK, TN, JA, TN, AC, QN, AC, TN, WN, SK }, 	 //	 153	 100
{ KN, JA, JA, TN, PF, SK, TN, TN, TN, JA, QN, AC, AC, TN, TN }, 	 //	 154	 100
{ KN, TN, TN, TN, QN, SK, AC, LO, TN, PF, QN, AC, JA, TN, JA }, 	 //	 155	 100
{ KN, AC, KN, SH, TN, SK, AC, WN, TN, AC, QN, AC, TN, TN, AC }, 	 //	 156	 100
{ KN, PF, KN, ST, TN, SK, KN, WN, JA, TN, QN, KN, TN, TN, TN }, 	 //	 157	 100
{ SK, SH, JA, SH, JA, QN, AC, TN, TN, TN, QN, AC, AC, TN, AC }, 	 //	 158	 100
{ SK, AC, TN, TN, TN, QN, AC, TN, TN, AC, QN, LO, LO, TN, AC }, 	 //	 159	 100
{ SK, JA, KN, SH, TN, QN, JA, WN, TN, AC, QN, JA, TN, TN, AC }, 	 //	 160	 100
{ SK, JA, TN, JA, JA, QN, JA, TN, TN, TN, QN, JA, LO, AC, AC }, 	 //	 161	 100
{ SK, JA, TN, TN, TN, QN, JA, LO, TN, ST, QN, SH, JA, TN, AC }, 	 //	 162	 100
{ SK, JA, TN, TN, TN, QN, SH, TN, TN, ST, QN, TN, LO, WN, AC }, 	 //	 163	 100
{ SK, SH, TN, TN, AC, QN, TN, AC, TN, LO, QN, TN, AC, TN, AC }, 	 //	 164	 100
{ SK, TN, TN, SH, TN, QN, TN, AC, TN, AC, QN, TN, AC, TN, AC }, 	 //	 165	 100
{ SK, TN, JA, TN, QN, QN, TN, TN, TN, QN, QN, WN, AC, TN, SH }, 	 //	 166	 100
{ SK, TN, JA, JA, CR, QN, TN, TN, TN, QN, QN, WN, AC, AC, KN }, 	 //	 167	 100
{ SK, TN, TN, TN, JA, QN, AC, TN, TN, JA, QN, AC, LO, TN, WN }, 	 //	 168	 100
{ SK, PF, TN, TN, TN, QN, KN, AC, TN, TN, QN, KN, AC, TN, ST }, 	 //	 169	 100
{ SK, KN, TN, SH, TN, QN, KN, LO, TN, TN, QN, KN, JA, TN, TN }, 	 //	 170	 100
{ SK, KN, TN, JA, TN, QN, KN, LO, TN, TN, QN, SK, JA, AC, TN }, 	 //	 171	 100
{ SK, QN, TN, TN, TN, QN, KN, TN, AC, TN, QN, AC, LO, AC, ST }, 	 //	 172	 100
{ SK, KN, TN, ST, WN, QN, AC, TN, JA, TN, QN, SH, TN, TN, TN }, 	 //	 173	 100
{ QN, SH, SK, TN, TN, QN, AC, JA, TN, ST, QN, AC, TN, WN, AC }, 	 //	 174	 100
{ QN, LO, WN, TN, TN, QN, KN, TN, TN, ST, QN, KN, TN, TN, AC }, 	 //	 175	 100
{ QN, KN, TN, TN, TN, QN, KN, LO, WN, TN, QN, ST, JA, AC, TN }, 	 //	 176	 100
{ QN, ST, KN, TN, TN, QN, QN, WN, TN, TN, QN, QN, TN, TN, ST }, 	 //	 177	 100
{ QN, JA, TN, SH, JA, QN, JA, TN, TN, TN, QN, JA, LO, TN, AC }, 	 //	 178	 100
{ QN, JA, TN, TN, TN, QN, JA, TN, AC, TN, QN, SH, TN, AC, TN }, 	 //	 179	 100
{ QN, SH, SK, JA, JA, QN, TN, JA, SH, JA, QN, TN, TN, TN, WN }, 	 //	 180	 100
{ QN, TN, TN, TN, JA, QN, TN, LO, AC, TN, QN, TN, JA, AC, AC }, 	 //	 181	 100
{ QN, TN, TN, SH, JA, QN, TN, AC, TN, JA, QN, TN, AC, TN, WN }, 	 //	 182	 100
{ QN, TN, TN, TN, JA, QN, TN, TN, WN, JA, QN, WN, TN, AC, WN }, 	 //	 183	 100
{ QN, TN, JA, TN, QN, QN, TN, TN, TN, QN, QN, WN, AC, TN, SH }, 	 //	 184	 100
{ QN, TN, JA, TN, SH, QN, TN, TN, TN, JA, QN, WN, AC, TN, JA }, 	 //	 185	 100
{ QN, TN, TN, TN, KN, QN, WN, LO, TN, KN, QN, AC, JA, TN, CR }, 	 //	 186	 100
{ QN, TN, TN, TN, QN, QN, WN, LO, AC, QN, QN, AC, JA, AC, SH }, 	 //	 187	 100
{ QN, WN, TN, TN, TN, QN, AC, TN, WN, TN, QN, KN, TN, AC, TN }, 	 //	 188	 100
{ QN, AC, TN, SH, TN, QN, KN, TN, TN, TN, QN, QN, LO, TN, ST }, 	 //	 189	 100
{ QN, QN, JA, TN, TN, QN, ST, TN, TN, TN, QN, JA, AC, TN, TN }, 	 //	 190	 100
{ QN, ST, TN, TN, JA, QN, JA, TN, TN, TN, QN, TN, LO, TN, AC }, 	 //	 191	 100
{ QN, JA, JA, TN, CR, QN, TN, TN, TN, QN, QN, AC, AC, WN, KN }, 	 //	 192	 100
{ QN, AC, SK, JA, TN, QN, PF, JA, TN, ST, QN, KN, TN, AC, AC }, 	 //	 193	 100
{ QN, PF, TN, TN, WN, QN, KN, AC, TN, TN, QN, KN, AC, TN, TN }, 	 //	 194	 100
{ QN, QN, KN, SH, WN, QN, KN, WN, TN, TN, QN, AC, TN, TN, TN }, 	 //	 195	 100
{ QN, QN, SK, SH, WN, QN, KN, JA, TN, TN, QN, AC, TN, TN, TN }, 	 //	 196	 100
{ QN, AC, WN, TN, TN, QN, SH, TN, TN, ST, SH, AC, TN, WN, AC }, 	 //	 197	 100
{ QN, AC, TN, TN, WN, QN, AC, AC, TN, TN, SH, LO, AC, WN, TN }, 	 //	 198	 100
{ QN, LO, TN, JA, PF, QN, KN, TN, TN, JA, SH, KN, TN, AC, TN }, 	 //	 199	 100
{ QN, SK, TN, ST, JA, QN, JA, TN, JA, WN, SH, JA, TN, TN, TN }, 	 //	 200	 100
{ QN, SH, SK, JA, QN, QN, TN, JA, SH, KN, SH, TN, TN, TN, AC }, 	 //	 201	 100
{ QN, TN, TN, ST, QN, QN, TN, TN, JA, QN, SH, TN, TN, TN, SH }, 	 //	 202	 100
{ QN, TN, TN, TN, AC, QN, TN, TN, WN, AC, SH, TN, LO, AC, AC }, 	 //	 203	 100
{ QN, TN, TN, TN, PF, QN, TN, TN, WN, JA, SH, TN, LO, AC, TN }, 	 //	 204	 100
{ QN, TN, SK, ST, LO, QN, TN, JA, JA, AC, SH, TN, TN, TN, AC }, 	 //	 205	 100
{ QN, TN, TN, TN, KN, QN, TN, TN, WN, SK, SH, WN, LO, AC, QN }, 	 //	 206	 100
{ QN, TN, TN, SH, AC, QN, TN, AC, TN, AC, SH, WN, AC, TN, CR }, 	 //	 207	 100
{ QN, TN, TN, TN, QN, QN, WN, LO, WN, QN, SH, AC, JA, AC, SH }, 	 //	 208	 100
{ QN, TN, TN, TN, QN, QN, WN, LO, WN, SH, SH, AC, JA, AC, JA }, 	 //	 209	 100
{ QN, KN, TN, TN, TN, QN, QN, TN, WN, TN, SH, ST, TN, AC, ST }, 	 //	 210	 100
{ QN, ST, KN, TN, AC, QN, JA, WN, TN, AC, SH, TN, TN, TN, AC }, 	 //	 211	 100
{ QN, ST, TN, TN, PF, QN, JA, TN, TN, JA, SH, TN, LO, WN, TN }, 	 //	 212	 100
{ QN, JA, TN, TN, QN, QN, TN, AC, TN, KN, SH, AC, AC, WN, AC }, 	 //	 213	 100
{ QN, KN, TN, TN, JA, QN, KN, TN, TN, WN, SH, SK, LO, WN, TN }, 	 //	 214	 100
{ QN, KN, SK, JA, TN, QN, KN, JA, TN, ST, SH, SK, TN, AC, AC }, 	 //	 215	 100
{ QN, QN, TN, TN, TN, QN, KN, LO, AC, AC, SH, AC, JA, AC, AC }, 	 //	 216	 100
{ QN, SH, KN, TN, TN, SH, AC, WN, TN, TN, JA, AC, TN, TN, ST }, 	 //	 217	 100
{ QN, SH, KN, ST, PF, SH, AC, WN, JA, JA, JA, AC, TN, TN, TN }, 	 //	 218	 100
{ QN, AC, SK, SH, WN, SH, LO, JA, TN, TN, JA, KN, TN, TN, TN }, 	 //	 219	 100
{ QN, LO, WN, ST, JA, SH, KN, TN, JA, WN, JA, KN, TN, TN, TN }, 	 //	 220	 100
{ QN, SH, TN, TN, TN, SH, TN, TN, AC, TN, JA, TN, TN, AC, ST }, 	 //	 221	 100
{ QN, SH, JA, TN, KN, SH, TN, TN, TN, KN, JA, TN, AC, TN, SK }, 	 //	 222	 100
{ QN, TN, KN, TN, KN, SH, TN, WN, TN, AC, JA, TN, TN, WN, LO }, 	 //	 223	 100
{ QN, TN, TN, TN, KN, SH, TN, TN, WN, QN, JA, TN, TN, AC, PF }, 	 //	 224	 100
{ QN, TN, TN, TN, ST, SH, TN, LO, AC, AC, JA, TN, JA, AC, KN }, 	 //	 225	 100
{ QN, AC, TN, JA, PF, SH, KN, AC, TN, JA, JA, QN, AC, AC, TN }, 	 //	 226	 100
{ QN, ST, KN, ST, KN, SH, JA, WN, JA, AC, JA, TN, TN, TN, LO }, 	 //	 227	 100
{ QN, ST, TN, ST, JA, SH, JA, TN, JA, JA, JA, TN, TN, TN, JA }, 	 //	 228	 100
{ QN, JA, TN, TN, ST, SH, TN, LO, TN, AC, JA, AC, JA, WN, KN }, 	 //	 229	 100
{ QN, JA, TN, TN, KN, SH, TN, LO, TN, AC, JA, AC, JA, WN, LO }, 	 //	 230	 100
{ QN, AC, TN, TN, TN, SH, AC, LO, WN, TN, JA, PF, JA, AC, ST }, 	 //	 231	 100
{ QN, AC, TN, JA, JA, SH, PF, TN, TN, WN, JA, KN, LO, AC, TN }, 	 //	 232	 100
{ QN, AC, TN, TN, TN, SH, PF, AC, TN, AC, JA, KN, AC, WN, AC }, 	 //	 233	 100
{ QN, KN, TN, JA, TN, SH, KN, TN, SH, TN, JA, KN, TN, TN, TN }, 	 //	 234	 100
{ QN, KN, TN, TN, WN, SH, KN, LO, TN, TN, JA, SK, JA, TN, TN }, 	 //	 235	 100
{ QN, KN, TN, TN, TN, SH, KN, LO, TN, ST, JA, SK, JA, WN, AC }, 	 //	 236	 100
{ QN, QN, TN, SH, JA, SH, KN, LO, TN, WN, JA, AC, JA, TN, TN }, 	 //	 237	 100
{ SH, AC, TN, TN, JA, JA, AC, TN, TN, TN, JA, AC, TN, TN, AC }, 	 //	 238	 100
{ SH, AC, TN, SH, WN, JA, AC, AC, TN, TN, JA, LO, AC, TN, TN }, 	 //	 239	 100
{ SH, AC, TN, TN, TN, JA, LO, TN, AC, ST, JA, KN, LO, AC, AC }, 	 //	 240	 100
{ SH, QN, WN, TN, TN, JA, QN, TN, TN, ST, JA, QN, TN, WN, AC }, 	 //	 241	 100
{ SH, QN, TN, TN, TN, JA, QN, TN, TN, ST, JA, SK, LO, TN, AC }, 	 //	 242	 100
{ SH, QN, TN, TN, TN, JA, QN, TN, AC, TN, JA, SK, LO, AC, ST }, 	 //	 243	 100
{ SH, QN, WN, TN, WN, JA, SK, TN, TN, TN, JA, JA, TN, WN, TN }, 	 //	 244	 100
{ SH, QN, TN, TN, TN, JA, SK, TN, WN, TN, JA, JA, TN, AC, ST }, 	 //	 245	 100
{ SH, JA, TN, JA, TN, JA, SH, AC, TN, TN, JA, TN, AC, AC, TN }, 	 //	 246	 100
{ SH, TN, SK, JA, SK, JA, TN, JA, SH, QN, JA, TN, TN, TN, QN }, 	 //	 247	 100
{ SH, TN, SK, TN, SK, JA, TN, JA, TN, QN, JA, WN, TN, WN, QN }, 	 //	 248	 100
{ SH, TN, JA, JA, PF, JA, TN, TN, TN, JA, JA, WN, AC, AC, TN }, 	 //	 249	 100
{ SH, TN, TN, TN, KN, JA, WN, LO, TN, QN, JA, AC, JA, TN, PF }, 	 //	 250	 100
{ SH, KN, TN, TN, TN, JA, QN, TN, TN, ST, JA, ST, LO, TN, AC }, 	 //	 251	 100
{ SH, QN, SK, TN, TN, JA, ST, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 252	 100
{ SH, ST, KN, JA, KN, JA, JA, WN, SH, KN, JA, TN, TN, TN, CR }, 	 //	 253	 100
{ SH, TN, TN, TN, ST, JA, AC, LO, WN, AC, JA, AC, JA, AC, KN }, 	 //	 254	 100
{ SH, KN, JA, SH, TN, JA, KN, TN, TN, TN, JA, KN, AC, TN, TN }, 	 //	 255	 100
{ JA, AC, SK, JA, JA, JA, AC, JA, SH, WN, JA, AC, TN, TN, TN }, 	 //	 256	 100
{ JA, KN, WN, TN, JA, JA, KN, TN, TN, TN, JA, KN, TN, WN, AC }, 	 //	 257	 100
{ JA, KN, WN, ST, PF, JA, ST, TN, JA, JA, JA, QN, TN, TN, TN }, 	 //	 258	 100
{ JA, KN, TN, TN, TN, JA, ST, AC, TN, TN, JA, QN, AC, TN, ST }, 	 //	 259	 100
{ JA, ST, SK, JA, TN, JA, QN, JA, SH, TN, JA, QN, TN, TN, TN }, 	 //	 260	 100
{ JA, SH, TN, JA, TN, JA, TN, LO, TN, TN, JA, TN, JA, AC, ST }, 	 //	 261	 100
{ JA, SH, TN, TN, KN, JA, TN, AC, TN, KN, JA, TN, AC, WN, CR }, 	 //	 262	 100
{ JA, TN, KN, TN, QN, JA, TN, WN, TN, KN, JA, WN, TN, TN, AC }, 	 //	 263	 100
{ JA, TN, KN, TN, KN, JA, TN, WN, TN, KN, JA, WN, TN, WN, KN }, 	 //	 264	 100
{ JA, TN, TN, TN, KN, JA, TN, TN, WN, AC, JA, WN, TN, AC, LO }, 	 //	 265	 100
{ JA, TN, TN, TN, KN, JA, TN, LO, AC, KN, JA, WN, JA, AC, KN }, 	 //	 266	 100
{ JA, TN, TN, TN, JA, JA, WN, LO, TN, JA, JA, AC, JA, TN, JA }, 	 //	 267	 100
{ JA, KN, TN, TN, PF, JA, QN, LO, TN, JA, JA, ST, JA, WN, TN }, 	 //	 268	 100
{ JA, ST, KN, JA, SH, JA, JA, WN, SH, JA, JA, TN, TN, TN, JA }, 	 //	 269	 100
{ JA, JA, TN, JA, CR, JA, TN, LO, TN, KN, JA, AC, JA, AC, KN }, 	 //	 270	 100
{ JA, TN, TN, TN, SK, JA, AC, TN, TN, QN, JA, AC, TN, TN, QN }, 	 //	 271	 100
{ JA, TN, TN, TN, SH, JA, AC, AC, TN, JA, JA, AC, AC, WN, JA }, 	 //	 272	 100
{ JA, PF, TN, TN, TN, JA, KN, AC, TN, ST, JA, KN, AC, TN, AC }, 	 //	 273	 100
{ JA, AC, TN, TN, TN, JA, AC, TN, WN, TN, WN, LO, LO, AC, TN }, 	 //	 274	 100
{ JA, AC, TN, ST, WN, JA, LO, TN, JA, TN, WN, KN, TN, TN, TN }, 	 //	 275	 100
{ JA, ST, TN, TN, PF, JA, QN, LO, TN, JA, WN, QN, JA, TN, TN }, 	 //	 276	 100
{ JA, TN, SK, JA, QN, JA, TN, JA, TN, KN, WN, TN, TN, AC, AC }, 	 //	 277	 100
{ JA, TN, JA, JA, AC, JA, TN, TN, TN, AC, WN, WN, AC, AC, CR }, 	 //	 278	 100
{ JA, TN, TN, ST, TN, JA, WN, TN, JA, TN, WN, AC, TN, TN, TN }, 	 //	 279	 100
{ JA, TN, TN, TN, QN, JA, WN, TN, AC, QN, WN, AC, LO, AC, QN }, 	 //	 280	 100
{ JA, ST, KN, TN, KN, JA, JA, WN, TN, SK, WN, TN, TN, TN, QN }, 	 //	 281	 100
{ JA, JA, SK, TN, AC, JA, TN, JA, TN, AC, WN, AC, TN, TN, CR }, 	 //	 282	 100
{ JA, TN, WN, JA, TN, JA, AC, TN, TN, AC, WN, AC, TN, AC, AC }, 	 //	 283	 100
{ JA, KN, TN, TN, TN, JA, KN, LO, WN, AC, WN, KN, JA, AC, AC }, 	 //	 284	 100
{ JA, KN, JA, TN, WN, JA, KN, TN, TN, TN, WN, KN, AC, TN, TN }, 	 //	 285	 100
{ JA, KN, KN, SH, TN, JA, KN, WN, TN, AC, WN, SK, TN, TN, AC }, 	 //	 286	 100
{ JA, KN, KN, SH, JA, JA, SK, WN, TN, WN, WN, QN, TN, TN, TN }, 	 //	 287	 100
{ JA, KN, TN, JA, TN, JA, SK, LO, TN, TN, WN, QN, JA, AC, TN }, 	 //	 288	 100
{ JA, SK, KN, ST, TN, JA, QN, WN, JA, TN, WN, KN, TN, TN, TN }, 	 //	 289	 100
{ JA, QN, SK, TN, JA, JA, KN, JA, TN, WN, WN, AC, TN, TN, TN }, 	 //	 290	 100
{ JA, KN, TN, TN, TN, JA, AC, AC, TN, ST, WN, SH, AC, WN, AC }, 	 //	 291	 100
{ JA, AC, JA, SH, JA, WN, AC, TN, TN, TN, TN, LO, AC, TN, AC }, 	 //	 292	 100
{ JA, AC, TN, TN, TN, WN, LO, TN, WN, TN, TN, KN, TN, AC, TN }, 	 //	 293	 100
{ JA, KN, KN, ST, JA, WN, KN, WN, JA, WN, TN, ST, TN, TN, TN }, 	 //	 294	 100
{ JA, QN, TN, TN, PF, WN, QN, LO, TN, JA, TN, SK, JA, WN, TN }, 	 //	 295	 100
{ JA, QN, SK, TN, WN, WN, QN, JA, TN, TN, TN, SK, TN, TN, TN }, 	 //	 296	 100
{ JA, JA, KN, AC, WN, WN, SH, WN, PF, TN, TN, TN, TN, KN, TN }, 	 //	 297	 100
{ JA, JA, KN, SK, TN, WN, SH, WN, QN, TN, TN, TN, TN, KN, TN }, 	 //	 298	 100
{ JA, JA, WN, QN, AC, WN, SH, TN, QN, LO, TN, TN, TN, SK, AC }, 	 //	 299	 100
{ JA, JA, TN, TN, PF, WN, SH, LO, TN, JA, TN, TN, JA, TN, TN }, 	 //	 300	 100
{ JA, JA, SK, KN, PF, WN, SH, JA, AC, JA, TN, TN, TN, PF, TN }, 	 //	 301	 100
{ JA, SH, KN, WN, KN, WN, TN, WN, QN, QN, TN, TN, TN, QN, PF }, 	 //	 302	 100
{ JA, SH, KN, AC, ST, WN, TN, WN, AC, AC, TN, TN, TN, PF, KN }, 	 //	 303	 100
{ JA, SH, WN, KN, KN, WN, TN, TN, AC, SK, TN, TN, TN, PF, QN }, 	 //	 304	 100
{ JA, SH, TN, JA, KN, WN, TN, LO, JA, KN, TN, TN, JA, SH, KN }, 	 //	 305	 100
{ JA, SH, TN, AC, AC, WN, TN, LO, KN, LO, TN, TN, JA, QN, AC }, 	 //	 306	 100
{ JA, SH, SK, QN, KN, WN, TN, JA, QN, AC, TN, TN, TN, QN, LO }, 	 //	 307	 100
{ JA, SH, JA, JA, KN, WN, TN, TN, TN, AC, TN, TN, AC, AC, LO }, 	 //	 308	 100
{ JA, SH, TN, SK, QN, WN, TN, AC, JA, KN, TN, TN, AC, JA, AC }, 	 //	 309	 100
{ JA, TN, KN, AC, TN, WN, TN, WN, PF, AC, TN, TN, TN, AC, AC }, 	 //	 310	 100
{ JA, TN, WN, AC, AC, WN, TN, TN, AC, AC, TN, TN, TN, LO, AC }, 	 //	 311	 100
{ JA, TN, WN, AC, SK, WN, TN, TN, LO, KN, TN, TN, TN, KN, KN }, 	 //	 312	 100
{ JA, TN, TN, WN, KN, WN, TN, TN, QN, KN, TN, TN, LO, QN, KN }, 	 //	 313	 100
{ JA, TN, TN, AC, CR, WN, TN, LO, PF, QN, TN, TN, JA, AC, KN }, 	 //	 314	 100
{ JA, TN, TN, KN, QN, WN, TN, LO, SK, QN, TN, TN, JA, QN, SH }, 	 //	 315	 100
{ JA, TN, TN, SK, AC, WN, TN, LO, QN, SK, TN, TN, JA, KN, KN }, 	 //	 316	 100
{ JA, TN, TN, QN, QN, WN, TN, AC, ST, QN, TN, TN, AC, JA, SH }, 	 //	 317	 100
{ JA, TN, TN, AC, KN, WN, TN, AC, AC, QN, TN, TN, AC, AC, PF }, 	 //	 318	 100
{ JA, TN, TN, AC, QN, WN, TN, TN, PF, SH, TN, WN, TN, AC, JA }, 	 //	 319	 100
{ JA, TN, TN, AC, AC, WN, TN, TN, AC, AC, TN, WN, TN, LO, SK }, 	 //	 320	 100
{ JA, TN, TN, AC, AC, WN, TN, TN, AC, AC, TN, WN, TN, PF, SK }, 	 //	 321	 100
{ JA, TN, TN, PF, TN, WN, TN, TN, KN, TN, TN, WN, TN, KN, TN }, 	 //	 322	 100
{ JA, TN, TN, AC, JA, WN, TN, TN, AC, JA, TN, WN, LO, LO, WN }, 	 //	 323	 100
{ JA, TN, TN, WN, SK, WN, TN, TN, QN, QN, TN, WN, LO, QN, QN }, 	 //	 324	 100
{ JA, TN, TN, KN, TN, WN, TN, TN, KN, TN, TN, WN, LO, KN, TN }, 	 //	 325	 100
{ JA, TN, TN, QN, CR, WN, TN, LO, QN, QN, TN, WN, JA, SK, KN }, 	 //	 326	 100
{ JA, TN, SK, TN, AC, WN, TN, JA, TN, KN, TN, WN, TN, WN, QN }, 	 //	 327	 100
{ JA, TN, JA, TN, KN, WN, TN, TN, TN, AC, TN, WN, AC, WN, LO }, 	 //	 328	 100
{ JA, ST, KN, JA, AC, WN, JA, WN, TN, SK, TN, TN, TN, AC, KN }, 	 //	 329	 100
{ JA, ST, KN, KN, QN, WN, JA, WN, KN, SH, TN, TN, TN, KN, JA }, 	 //	 330	 100
{ JA, ST, WN, PF, ST, WN, JA, TN, AC, AC, TN, TN, TN, AC, KN }, 	 //	 331	 100
{ JA, ST, WN, AC, QN, WN, JA, TN, LO, SH, TN, TN, TN, KN, JA }, 	 //	 332	 100
{ JA, ST, WN, KN, QN, WN, JA, TN, WN, SH, TN, TN, TN, QN, JA }, 	 //	 333	 100
{ JA, ST, WN, PF, JA, WN, JA, TN, KN, JA, TN, TN, TN, KN, WN }, 	 //	 334	 100
{ JA, ST, TN, SK, AC, WN, JA, TN, QN, SK, TN, TN, TN, KN, KN }, 	 //	 335	 100
{ JA, ST, SK, AC, AC, WN, JA, JA, AC, AC, TN, TN, TN, AC, AC }, 	 //	 336	 100
{ JA, ST, SK, KN, QN, WN, JA, JA, AC, QN, TN, TN, TN, PF, SH }, 	 //	 337	 100
{ JA, JA, TN, KN, TN, WN, TN, TN, KN, ST, TN, AC, TN, WN, AC }, 	 //	 338	 100
{ JA, JA, TN, JA, SK, WN, TN, TN, JA, QN, TN, AC, TN, JA, QN }, 	 //	 339	 100
{ JA, JA, TN, ST, QN, WN, TN, LO, JA, SH, TN, AC, JA, TN, JA }, 	 //	 340	 100
{ JA, JA, TN, PF, AC, WN, TN, LO, KN, SK, TN, AC, JA, KN, KN }, 	 //	 341	 100
{ JA, JA, TN, QN, PF, WN, TN, AC, QN, JA, TN, AC, AC, QN, TN }, 	 //	 342	 100
{ JA, JA, TN, QN, AC, WN, TN, AC, ST, SK, TN, AC, AC, JA, KN }, 	 //	 343	 100
{ JA, KN, TN, TN, TN, WN, KN, TN, WN, ST, TN, SK, LO, AC, AC }, 	 //	 344	 100
{ JA, KN, WN, ST, JA, WN, SK, TN, JA, WN, TN, QN, TN, TN, TN }, 	 //	 345	 100
{ JA, QN, KN, SH, TN, WN, KN, WN, TN, TN, TN, AC, TN, TN, ST }, 	 //	 346	 100
{ JA, KN, TN, ST, WN, WN, AC, TN, JA, TN, TN, SH, TN, TN, TN }, 	 //	 347	 100
{ WN, AC, TN, TN, TN, TN, LO, TN, WN, AC, TN, KN, LO, AC, AC }, 	 //	 348	 100
{ WN, LO, TN, SH, TN, TN, KN, TN, TN, AC, TN, KN, TN, TN, AC }, 	 //	 349	 100
{ WN, KN, TN, JA, TN, TN, ST, TN, TN, TN, TN, QN, LO, AC, ST }, 	 //	 350	 100
{ WN, JA, TN, TN, TN, TN, JA, AC, TN, AC, TN, SH, AC, WN, AC }, 	 //	 351	 100
{ WN, JA, KN, AC, JA, TN, SH, WN, LO, JA, TN, TN, TN, KN, WN }, 	 //	 352	 100
{ WN, JA, TN, QN, QN, TN, SH, TN, ST, PF, TN, TN, TN, JA, JA }, 	 //	 353	 100
{ WN, JA, TN, AC, AC, TN, SH, TN, PF, AC, TN, TN, TN, KN, SK }, 	 //	 354	 100
{ WN, SH, KN, AC, SK, TN, TN, WN, KN, QN, TN, TN, TN, QN, QN }, 	 //	 355	 100
{ WN, SH, KN, TN, JA, TN, TN, WN, AC, JA, TN, TN, TN, AC, JA }, 	 //	 356	 100
{ WN, SH, TN, KN, JA, TN, TN, LO, KN, JA, TN, TN, JA, KN, WN }, 	 //	 357	 100
{ WN, SH, SK, AC, KN, TN, TN, JA, KN, KN, TN, TN, TN, QN, KN }, 	 //	 358	 100
{ WN, SH, SK, PF, TN, TN, TN, JA, KN, ST, TN, TN, TN, KN, AC }, 	 //	 359	 100
{ WN, SH, JA, PF, SK, TN, TN, TN, KN, KN, TN, TN, AC, KN, KN }, 	 //	 360	 100
{ WN, SH, TN, WN, SK, TN, TN, AC, AC, QN, TN, TN, AC, KN, QN }, 	 //	 361	 100
{ WN, SH, TN, KN, CR, TN, TN, AC, AC, QN, TN, TN, AC, PF, KN }, 	 //	 362	 100
{ WN, TN, KN, KN, AC, TN, TN, WN, AC, SK, TN, TN, TN, PF, KN }, 	 //	 363	 100
{ WN, TN, SK, KN, WN, TN, TN, JA, WN, TN, TN, TN, TN, QN, TN }, 	 //	 364	 100
{ WN, TN, SK, KN, TN, TN, TN, JA, WN, TN, TN, TN, TN, QN, TN }, 	 //	 365	 100
{ WN, TN, JA, QN, SH, TN, TN, TN, QN, JA, TN, TN, AC, SK, JA }, 	 //	 366	 100
{ WN, TN, TN, AC, CR, TN, TN, AC, LO, KN, TN, TN, AC, KN, KN }, 	 //	 367	 100
{ WN, TN, TN, QN, CR, TN, TN, AC, QN, QN, TN, TN, AC, SK, KN }, 	 //	 368	 100
{ WN, TN, TN, PF, AC, TN, TN, AC, KN, AC, TN, TN, AC, KN, CR }, 	 //	 369	 100
{ WN, TN, TN, KN, QN, TN, TN, AC, KN, PF, TN, TN, AC, KN, JA }, 	 //	 370	 100
{ WN, TN, WN, AC, SK, TN, TN, TN, LO, QN, TN, WN, TN, KN, QN }, 	 //	 371	 100
{ WN, TN, WN, WN, CR, TN, TN, TN, QN, KN, TN, WN, TN, QN, KN }, 	 //	 372	 100
{ WN, TN, WN, TN, KN, TN, TN, TN, WN, AC, TN, WN, TN, AC, LO }, 	 //	 373	 100
{ WN, TN, WN, SK, KN, TN, TN, TN, QN, QN, TN, WN, TN, KN, PF }, 	 //	 374	 100
{ WN, TN, WN, KN, SK, TN, TN, TN, AC, KN, TN, WN, TN, PF, KN }, 	 //	 375	 100
{ WN, TN, TN, QN, JA, TN, TN, LO, KN, TN, TN, WN, JA, AC, AC }, 	 //	 376	 100
{ WN, TN, SK, TN, KN, TN, TN, JA, TN, SK, TN, WN, TN, TN, QN }, 	 //	 377	 100
{ WN, TN, JA, AC, SK, TN, TN, TN, PF, KN, TN, WN, AC, AC, KN }, 	 //	 378	 100
{ WN, TN, JA, JA, KN, TN, TN, TN, JA, KN, TN, WN, AC, SH, KN }, 	 //	 379	 100
{ WN, TN, JA, KN, PF, TN, TN, TN, KN, JA, TN, WN, AC, SK, TN }, 	 //	 380	 100
{ WN, TN, TN, PF, CR, TN, TN, AC, AC, KN, TN, WN, AC, AC, KN }, 	 //	 381	 100
{ WN, TN, TN, KN, JA, TN, TN, AC, SK, JA, TN, WN, AC, QN, WN }, 	 //	 382	 100
{ WN, TN, TN, TN, JA, TN, WN, AC, TN, JA, TN, AC, AC, TN, WN }, 	 //	 383	 100
{ WN, AC, TN, JA, JA, TN, KN, TN, TN, WN, TN, QN, TN, AC, TN }, 	 //	 384	 100
{ WN, ST, KN, QN, QN, TN, JA, WN, SK, QN, TN, TN, TN, JA, SH }, 	 //	 385	 100
{ WN, ST, KN, AC, TN, TN, JA, WN, PF, TN, TN, TN, TN, KN, ST }, 	 //	 386	 100
{ WN, ST, WN, QN, LO, TN, JA, TN, SK, AC, TN, TN, TN, JA, AC }, 	 //	 387	 100
{ WN, ST, WN, AC, SK, TN, JA, TN, AC, QN, TN, TN, TN, PF, QN }, 	 //	 388	 100
{ WN, ST, TN, QN, QN, TN, JA, TN, KN, QN, TN, TN, TN, AC, SH }, 	 //	 389	 100
{ WN, ST, SK, AC, SK, TN, JA, JA, LO, KN, TN, TN, TN, KN, KN }, 	 //	 390	 100
{ WN, ST, SK, TN, AC, TN, JA, JA, WN, AC, TN, TN, TN, AC, AC }, 	 //	 391	 100
{ WN, ST, SK, AC, AC, TN, JA, JA, AC, AC, TN, TN, TN, PF, AC }, 	 //	 392	 100
{ WN, ST, SK, QN, SK, TN, JA, JA, KN, QN, TN, TN, TN, AC, QN }, 	 //	 393	 100
{ WN, JA, WN, WN, SK, TN, TN, TN, QN, KN, TN, AC, TN, QN, KN }, 	 //	 394	 100
{ WN, JA, WN, KN, AC, TN, TN, TN, KN, KN, TN, AC, TN, SK, QN }, 	 //	 395	 100
{ WN, JA, TN, PF, KN, TN, TN, LO, AC, SK, TN, AC, JA, AC, QN }, 	 //	 396	 100
{ WN, JA, TN, LO, QN, TN, TN, LO, KN, QN, TN, AC, JA, KN, QN }, 	 //	 397	 100
{ WN, JA, TN, KN, KN, TN, TN, LO, KN, KN, TN, AC, JA, KN, KN }, 	 //	 398	 100
{ WN, JA, JA, KN, QN, TN, TN, TN, KN, QN, TN, AC, AC, KN, SH }, 	 //	 399	 100
{ WN, JA, JA, KN, LO, TN, TN, TN, QN, AC, TN, AC, AC, ST, AC }, 	 //	 400	 100
{ WN, JA, TN, QN, CR, TN, TN, AC, ST, QN, TN, AC, AC, JA, KN }, 	 //	 401	 100
{ WN, JA, TN, SK, KN, TN, TN, AC, QN, AC, TN, AC, AC, KN, LO }, 	 //	 402	 100
{ WN, AC, TN, TN, PF, TN, AC, TN, TN, JA, TN, PF, LO, WN, TN }, 	 //	 403	 100
{ WN, AC, SK, TN, TN, TN, AC, JA, TN, AC, TN, PF, TN, WN, AC }, 	 //	 404	 100
{ WN, KN, TN, TN, TN, TN, SK, TN, TN, ST, TN, QN, LO, WN, AC }, 	 //	 405	 100
{ WN, KN, TN, JA, PF, TN, AC, LO, TN, JA, TN, SH, JA, AC, TN }, 	 //	 406	 100
{ TN, AC, KN, ST, JA, TN, AC, WN, JA, WN, TN, AC, TN, TN, TN }, 	 //	 407	 100
{ TN, AC, SK, SH, WN, TN, AC, JA, TN, TN, TN, AC, TN, TN, TN }, 	 //	 408	 100
{ TN, AC, TN, TN, PF, TN, AC, AC, TN, JA, TN, AC, AC, TN, TN }, 	 //	 409	 100
{ TN, AC, KN, TN, JA, TN, AC, WN, TN, WN, TN, LO, TN, TN, TN }, 	 //	 410	 100
{ TN, LO, KN, JA, JA, TN, KN, WN, SH, WN, TN, KN, TN, TN, TN }, 	 //	 411	 100
{ TN, LO, TN, ST, PF, TN, KN, TN, JA, JA, TN, KN, TN, TN, TN }, 	 //	 412	 100
{ TN, LO, TN, TN, TN, TN, KN, TN, TN, ST, TN, KN, LO, TN, AC }, 	 //	 413	 100
{ TN, JA, TN, TN, TN, TN, JA, TN, WN, AC, TN, JA, LO, AC, AC }, 	 //	 414	 100
{ TN, JA, KN, QN, SK, TN, SH, WN, QN, KN, TN, TN, TN, QN, KN }, 	 //	 415	 100
{ TN, JA, KN, TN, AC, TN, SH, WN, WN, AC, TN, TN, TN, AC, SK }, 	 //	 416	 100
{ TN, JA, KN, AC, KN, TN, SH, WN, KN, SK, TN, TN, TN, QN, QN }, 	 //	 417	 100
{ TN, JA, KN, AC, AC, TN, SH, WN, PF, AC, TN, TN, TN, KN, SK }, 	 //	 418	 100
{ TN, JA, KN, SK, AC, TN, SH, WN, QN, KN, TN, TN, TN, KN, QN }, 	 //	 419	 100
{ TN, JA, WN, AC, QN, TN, SH, TN, PF, KN, TN, TN, TN, AC, AC }, 	 //	 420	 100
{ TN, JA, WN, LO, CR, TN, SH, TN, KN, KN, TN, TN, TN, KN, KN }, 	 //	 421	 100
{ TN, JA, WN, LO, QN, TN, SH, TN, KN, QN, TN, TN, TN, KN, SH }, 	 //	 422	 100
{ TN, JA, TN, AC, AC, TN, SH, TN, AC, AC, TN, TN, TN, AC, CR }, 	 //	 423	 100
{ TN, JA, TN, AC, QN, TN, SH, TN, AC, QN, TN, TN, TN, AC, QN }, 	 //	 424	 100
{ TN, JA, TN, AC, AC, TN, SH, TN, PF, SK, TN, TN, TN, KN, KN }, 	 //	 425	 100
{ TN, JA, TN, QN, KN, TN, SH, TN, KN, SK, TN, TN, TN, AC, QN }, 	 //	 426	 100
{ TN, JA, TN, KN, AC, TN, SH, TN, AC, KN, TN, TN, TN, PF, QN }, 	 //	 427	 100
{ TN, JA, SK, JA, KN, TN, SH, JA, JA, QN, TN, TN, TN, JA, PF }, 	 //	 428	 100
{ TN, JA, SK, TN, AC, TN, SH, JA, TN, AC, TN, TN, TN, WN, SK }, 	 //	 429	 100
{ TN, JA, SK, QN, AC, TN, SH, JA, ST, AC, TN, TN, TN, JA, AC }, 	 //	 430	 100
{ TN, SH, JA, QN, CR, TN, TN, TN, QN, KN, TN, TN, AC, QN, KN }, 	 //	 431	 100
{ TN, SH, JA, JA, SK, TN, TN, TN, JA, QN, TN, TN, AC, SH, QN }, 	 //	 432	 100
{ TN, SH, JA, AC, KN, TN, TN, TN, AC, KN, TN, TN, AC, AC, KN }, 	 //	 433	 100
{ TN, SH, JA, AC, TN, TN, TN, TN, PF, AC, TN, TN, AC, KN, AC }, 	 //	 434	 100
{ TN, SH, JA, PF, JA, TN, TN, TN, KN, JA, TN, TN, AC, KN, JA }, 	 //	 435	 100
{ TN, SH, TN, ST, KN, TN, TN, AC, JA, SK, TN, TN, AC, TN, QN }, 	 //	 436	 100
{ TN, SH, TN, TN, QN, TN, TN, AC, AC, PF, TN, TN, AC, AC, JA }, 	 //	 437	 100
{ TN, TN, JA, KN, TN, TN, TN, TN, KN, AC, TN, TN, AC, WN, AC }, 	 //	 438	 100
{ TN, TN, JA, KN, JA, TN, TN, TN, SK, TN, TN, TN, AC, QN, AC }, 	 //	 439	 100
{ TN, TN, KN, TN, CR, TN, TN, WN, WN, KN, TN, WN, TN, AC, KN }, 	 //	 440	 100
{ TN, TN, KN, AC, KN, TN, TN, WN, PF, KN, TN, WN, TN, KN, CR }, 	 //	 441	 100
{ TN, TN, SK, AC, JA, TN, TN, JA, AC, TN, TN, WN, TN, AC, AC }, 	 //	 442	 100
{ TN, TN, SK, AC, TN, TN, TN, JA, KN, TN, TN, WN, TN, QN, ST }, 	 //	 443	 100
{ TN, TN, JA, AC, AC, TN, TN, TN, PF, SK, TN, WN, AC, AC, KN }, 	 //	 444	 100
{ TN, TN, JA, KN, AC, TN, TN, TN, KN, AC, TN, WN, AC, WN, AC }, 	 //	 445	 100
{ TN, TN, JA, ST, CR, TN, TN, TN, JA, KN, TN, WN, AC, TN, KN }, 	 //	 446	 100
{ TN, TN, JA, KN, CR, TN, TN, TN, AC, KN, TN, WN, AC, PF, KN }, 	 //	 447	 100
{ TN, TN, TN, QN, PF, TN, WN, TN, ST, JA, TN, AC, TN, JA, TN }, 	 //	 448	 100
{ TN, TN, TN, AC, JA, TN, WN, TN, LO, JA, TN, AC, LO, KN, WN }, 	 //	 449	 100
{ TN, TN, TN, WN, CR, TN, WN, TN, QN, QN, TN, AC, LO, QN, KN }, 	 //	 450	 100
{ TN, TN, TN, JA, AC, TN, WN, TN, TN, AC, TN, AC, LO, AC, SK }, 	 //	 451	 100
{ TN, TN, TN, QN, AC, TN, WN, LO, QN, LO, TN, AC, JA, SK, AC }, 	 //	 452	 100
{ TN, TN, TN, JA, QN, TN, WN, LO, JA, KN, TN, AC, JA, SH, AC }, 	 //	 453	 100
{ TN, TN, TN, QN, WN, TN, WN, AC, QN, TN, TN, AC, AC, SK, TN }, 	 //	 454	 100
{ TN, TN, TN, ST, JA, TN, WN, AC, JA, TN, TN, AC, AC, TN, AC }, 	 //	 455	 100
{ TN, WN, TN, JA, JA, TN, AC, AC, TN, WN, TN, KN, AC, AC, TN }, 	 //	 456	 100
{ TN, ST, KN, JA, KN, TN, JA, WN, JA, AC, TN, TN, TN, SH, LO }, 	 //	 457	 100
{ TN, ST, KN, AC, KN, TN, JA, WN, AC, QN, TN, TN, TN, AC, PF }, 	 //	 458	 100
{ TN, ST, WN, WN, SK, TN, JA, TN, QN, QN, TN, TN, TN, QN, QN }, 	 //	 459	 100
{ TN, ST, WN, QN, KN, TN, JA, TN, KN, KN, TN, TN, TN, AC, CR }, 	 //	 460	 100
{ TN, ST, TN, AC, QN, TN, JA, TN, AC, PF, TN, TN, TN, AC, JA }, 	 //	 461	 100
{ TN, ST, TN, KN, KN, TN, JA, TN, SK, QN, TN, TN, TN, QN, PF }, 	 //	 462	 100
{ TN, ST, SK, TN, JA, TN, JA, JA, WN, JA, TN, TN, TN, AC, JA }, 	 //	 463	 100
{ TN, ST, SK, AC, JA, TN, JA, JA, KN, JA, TN, TN, TN, QN, JA }, 	 //	 464	 100
{ TN, JA, KN, AC, JA, TN, TN, WN, AC, TN, TN, AC, TN, LO, AC }, 	 //	 465	 100
{ TN, JA, KN, QN, AC, TN, TN, WN, SK, AC, TN, AC, TN, JA, CR }, 	 //	 466	 100
{ TN, JA, KN, TN, KN, TN, TN, WN, AC, KN, TN, AC, TN, AC, KN }, 	 //	 467	 100
{ TN, JA, TN, AC, PF, TN, TN, LO, AC, JA, TN, AC, JA, AC, TN }, 	 //	 468	 100
{ TN, JA, JA, WN, AC, TN, TN, TN, QN, AC, TN, AC, AC, QN, AC }, 	 //	 469	 100
{ TN, JA, TN, WN, KN, TN, TN, AC, AC, KN, TN, AC, AC, KN, CR }, 	 //	 470	 100
{ TN, TN, TN, QN, JA, TN, AC, TN, KN, WN, TN, AC, LO, AC, TN }, 	 //	 471	 100
{ TN, TN, TN, QN, SK, TN, AC, LO, QN, KN, TN, AC, JA, SK, KN }, 	 //	 472	 100
{ TN, TN, TN, ST, KN, TN, AC, LO, JA, SK, TN, AC, JA, TN, QN }, 	 //	 473	 100
{ TN, KN, SK, ST, WN, TN, KN, JA, JA, TN, TN, KN, TN, TN, TN }, 	 //	 474	 100
{ TN, KN, TN, JA, PF, TN, AC, TN, TN, JA, TN, SH, LO, AC, TN }, 	 //	 475	 100
{ TN, ST, JA, SH, TN, TN, QN, TN, TN, TN, ST, QN, AC, TN, TN }, 	 //	 476	 100
{ TN, QN, KN, TN, WN, TN, QN, WN, TN, TN, ST, QN, TN, TN, TN }, 	 //	 477	 100
{ TN, QN, KN, TN, TN, TN, QN, WN, TN, ST, ST, SK, TN, TN, AC }, 	 //	 478	 100
{ TN, QN, TN, TN, TN, TN, QN, TN, WN, TN, ST, SK, TN, AC, TN }, 	 //	 479	 100
{ TN, QN, TN, TN, JA, TN, SK, TN, TN, TN, ST, JA, LO, TN, AC }, 	 //	 480	 100
{ TN, SK, TN, TN, TN, TN, JA, LO, WN, TN, ST, JA, JA, AC, TN }, 	 //	 481	 100
{ TN, SH, TN, QN, QN, TN, TN, TN, KN, QN, ST, TN, LO, AC, QN }, 	 //	 482	 100
{ TN, SH, SK, AC, JA, TN, TN, JA, AC, TN, ST, TN, TN, LO, AC }, 	 //	 483	 100
{ TN, SH, SK, KN, JA, TN, TN, JA, KN, JA, ST, TN, TN, WN, JA }, 	 //	 484	 100
{ TN, SH, SK, WN, KN, TN, TN, JA, AC, QN, ST, TN, TN, KN, PF }, 	 //	 485	 100
{ TN, SH, JA, QN, KN, TN, TN, TN, QN, KN, ST, TN, AC, SK, CR }, 	 //	 486	 100
{ TN, SH, JA, KN, QN, TN, TN, TN, AC, QN, ST, TN, AC, PF, QN }, 	 //	 487	 100
{ TN, TN, KN, AC, QN, TN, TN, WN, AC, QN, ST, TN, TN, LO, SH }, 	 //	 488	 100
{ TN, TN, SK, QN, JA, TN, TN, JA, KN, WN, ST, TN, TN, AC, TN }, 	 //	 489	 100
{ TN, TN, JA, WN, JA, TN, TN, TN, AC, WN, ST, TN, AC, KN, TN }, 	 //	 490	 100
{ TN, TN, JA, AC, JA, TN, TN, TN, AC, JA, ST, TN, AC, AC, WN }, 	 //	 491	 100
{ TN, TN, KN, TN, QN, TN, TN, WN, WN, KN, ST, WN, TN, AC, AC }, 	 //	 492	 100
{ TN, TN, KN, WN, ST, TN, TN, WN, AC, AC, ST, WN, TN, KN, KN }, 	 //	 493	 100
{ TN, TN, SK, WN, SK, TN, TN, JA, AC, QN, ST, WN, TN, KN, QN }, 	 //	 494	 100
{ TN, TN, JA, KN, JA, TN, TN, TN, KN, WN, ST, WN, AC, WN, TN }, 	 //	 495	 100
{ TN, TN, JA, QN, TN, TN, TN, TN, QN, ST, ST, WN, AC, QN, AC }, 	 //	 496	 100
{ TN, TN, JA, KN, KN, TN, TN, TN, SK, QN, ST, WN, AC, QN, PF }, 	 //	 497	 100
{ TN, TN, TN, KN, WN, TN, TN, AC, KN, TN, ST, WN, AC, SK, TN }, 	 //	 498	 100
{ TN, TN, TN, QN, AC, TN, WN, TN, QN, AC, ST, AC, TN, QN, AC }, 	 //	 499	 100
{ TN, TN, TN, SK, CR, TN, WN, TN, JA, KN, ST, AC, TN, JA, KN }, 	 //	 500	 100
{ TN, TN, TN, AC, TN, TN, WN, TN, AC, TN, ST, AC, LO, PF, ST }, 	 //	 501	 100
{ TN, TN, TN, WN, SK, TN, WN, LO, QN, QN, ST, AC, JA, QN, QN }, 	 //	 502	 100
{ TN, TN, TN, KN, KN, TN, WN, LO, SK, KN, ST, AC, JA, QN, KN }, 	 //	 503	 100
{ TN, TN, TN, KN, AC, TN, WN, AC, KN, AC, ST, AC, AC, WN, AC }, 	 //	 504	 100
{ TN, TN, TN, JA, KN, TN, WN, AC, SH, SK, ST, AC, AC, TN, QN }, 	 //	 505	 100
{ TN, TN, TN, PF, JA, TN, WN, AC, KN, JA, ST, AC, AC, KN, WN }, 	 //	 506	 100
{ TN, AC, TN, TN, WN, TN, KN, AC, TN, TN, ST, QN, AC, WN, TN }, 	 //	 507	 100
{ TN, KN, TN, TN, TN, TN, QN, TN, WN, TN, ST, ST, TN, AC, ST }, 	 //	 508	 100
{ TN, ST, WN, JA, KN, TN, JA, TN, SH, KN, ST, TN, TN, TN, SK }, 	 //	 509	 100
{ TN, JA, KN, KN, SH, TN, TN, WN, KN, JA, ST, AC, TN, KN, JA }, 	 //	 510	 100
{ TN, JA, KN, QN, AC, TN, TN, WN, SK, LO, ST, AC, TN, JA, AC }, 	 //	 511	 100
{ TN, JA, KN, QN, QN, TN, TN, WN, SK, SH, ST, AC, TN, JA, JA }, 	 //	 512	 100
{ TN, JA, KN, AC, SK, TN, TN, WN, PF, QN, ST, AC, TN, KN, QN }, 	 //	 513	 100
{ TN, JA, TN, KN, KN, TN, TN, TN, KN, QN, ST, AC, LO, WN, PF }, 	 //	 514	 100
{ TN, JA, SK, QN, TN, TN, TN, JA, ST, TN, ST, AC, TN, JA, TN }, 	 //	 515	 100
{ TN, JA, SK, QN, KN, TN, TN, JA, KN, KN, ST, AC, TN, AC, SK }, 	 //	 516	 100
{ TN, JA, JA, QN, CR, TN, TN, TN, QN, QN, ST, AC, AC, QN, KN }, 	 //	 517	 100
{ TN, JA, JA, PF, WN, TN, TN, TN, KN, TN, ST, AC, AC, KN, TN }, 	 //	 518	 100
{ TN, TN, TN, AC, TN, TN, AC, TN, PF, TN, ST, AC, TN, AC, TN }, 	 //	 519	 100
{ TN, TN, TN, KN, AC, TN, AC, TN, KN, KN, ST, AC, TN, KN, QN }, 	 //	 520	 100
{ TN, TN, TN, AC, AC, TN, AC, TN, AC, AC, ST, AC, LO, AC, AC }, 	 //	 521	 100
{ TN, TN, TN, AC, SK, TN, AC, TN, AC, KN, ST, AC, LO, LO, KN }, 	 //	 522	 100
{ TN, TN, TN, AC, JA, TN, AC, TN, PF, TN, ST, AC, LO, KN, AC }, 	 //	 523	 100
{ TN, TN, TN, JA, PF, TN, AC, AC, SH, JA, ST, AC, AC, TN, TN }, 	 //	 524	 100
{ TN, TN, TN, ST, JA, TN, AC, AC, JA, JA, ST, AC, AC, TN, JA }, 	 //	 525	 100
{ TN, KN, TN, ST, PF, TN, SK, TN, JA, JA, ST, QN, TN, TN, TN }, 	 //	 526	 100
{ TN, SK, JA, TN, JA, TN, QN, TN, TN, TN, ST, KN, AC, WN, AC }, 	 //	 527	 100
{ TN, QN, TN, SH, TN, TN, KN, LO, TN, TN, ST, AC, JA, TN, TN }, 	 //	 528	 100
{ TN, AC, TN, SH, TN, ST, AC, LO, TN, TN, AC, LO, JA, TN, TN }, 	 //	 529	 100
{ TN, AC, SK, SH, TN, ST, LO, JA, TN, TN, AC, KN, TN, TN, ST }, 	 //	 530	 100
{ TN, KN, TN, TN, JA, ST, KN, TN, TN, WN, AC, ST, TN, WN, TN }, 	 //	 531	 100
{ TN, KN, TN, TN, JA, ST, ST, TN, TN, WN, AC, QN, TN, WN, TN }, 	 //	 532	 100
{ TN, KN, JA, SH, JA, ST, ST, TN, TN, TN, AC, QN, AC, TN, AC }, 	 //	 533	 100
{ TN, JA, KN, JA, PF, ST, JA, WN, SH, JA, AC, JA, TN, TN, TN }, 	 //	 534	 100
{ TN, JA, TN, SH, JA, ST, JA, TN, TN, WN, AC, SH, LO, TN, TN }, 	 //	 535	 100
{ TN, SH, KN, WN, QN, ST, TN, WN, QN, KN, AC, TN, TN, QN, AC }, 	 //	 536	 100
{ TN, SH, KN, JA, TN, ST, TN, WN, JA, TN, AC, TN, TN, SH, ST }, 	 //	 537	 100
{ TN, SH, TN, AC, JA, ST, TN, TN, AC, JA, AC, TN, TN, LO, JA }, 	 //	 538	 100
{ TN, SH, TN, PF, KN, ST, TN, TN, KN, SK, AC, TN, TN, KN, QN }, 	 //	 539	 100
{ TN, SH, TN, KN, KN, ST, TN, TN, SK, AC, AC, TN, TN, QN, LO }, 	 //	 540	 100
{ TN, SH, SK, AC, WN, ST, TN, JA, LO, TN, AC, TN, TN, KN, TN }, 	 //	 541	 100
{ TN, SH, SK, KN, QN, ST, TN, JA, KN, QN, AC, TN, TN, KN, SH }, 	 //	 542	 100
{ TN, SH, JA, TN, KN, ST, TN, TN, TN, KN, AC, TN, AC, TN, CR }, 	 //	 543	 100
{ TN, SH, TN, SH, KN, ST, TN, AC, TN, KN, AC, TN, AC, TN, KN }, 	 //	 544	 100
{ TN, TN, TN, AC, AC, ST, TN, TN, KN, AC, AC, TN, LO, QN, CR }, 	 //	 545	 100
{ TN, TN, TN, KN, JA, ST, TN, TN, SK, JA, AC, TN, LO, QN, WN }, 	 //	 546	 100
{ TN, TN, SK, AC, JA, ST, TN, JA, KN, JA, AC, TN, TN, QN, JA }, 	 //	 547	 100
{ TN, TN, SK, KN, AC, ST, TN, JA, KN, KN, AC, TN, TN, SK, QN }, 	 //	 548	 100
{ TN, TN, JA, SH, AC, ST, TN, TN, TN, AC, AC, TN, AC, TN, CR }, 	 //	 549	 100
{ TN, TN, TN, JA, AC, ST, TN, AC, JA, LO, AC, TN, AC, JA, AC }, 	 //	 550	 100
{ TN, TN, TN, PF, CR, ST, TN, AC, KN, QN, AC, TN, AC, KN, KN }, 	 //	 551	 100
{ TN, TN, TN, KN, SH, ST, TN, AC, KN, JA, AC, TN, AC, KN, JA }, 	 //	 552	 100
{ TN, TN, KN, QN, JA, ST, TN, WN, KN, TN, AC, WN, TN, AC, AC }, 	 //	 553	 100
{ TN, TN, WN, KN, ST, ST, TN, TN, WN, AC, AC, WN, TN, QN, KN }, 	 //	 554	 100
{ TN, TN, TN, AC, SK, ST, TN, TN, PF, KN, AC, WN, LO, AC, KN }, 	 //	 555	 100
{ TN, TN, TN, JA, AC, ST, TN, TN, SH, SK, AC, WN, LO, TN, KN }, 	 //	 556	 100
{ TN, TN, TN, AC, QN, ST, TN, TN, KN, QN, AC, WN, LO, QN, QN }, 	 //	 557	 100
{ TN, TN, TN, AC, AC, ST, TN, LO, AC, AC, AC, WN, JA, LO, SK }, 	 //	 558	 100
{ TN, TN, TN, AC, TN, ST, TN, AC, AC, TN, AC, WN, AC, LO, TN }, 	 //	 559	 100
{ TN, TN, TN, QN, KN, ST, TN, AC, SK, AC, AC, WN, AC, JA, LO }, 	 //	 560	 100
{ TN, TN, TN, WN, JA, ST, TN, AC, AC, TN, AC, WN, AC, KN, AC }, 	 //	 561	 100
{ TN, TN, TN, KN, PF, ST, TN, AC, KN, JA, AC, WN, AC, SK, TN }, 	 //	 562	 100
{ TN, TN, TN, AC, ST, ST, WN, TN, AC, AC, AC, AC, TN, AC, KN }, 	 //	 563	 100
{ TN, TN, TN, JA, JA, ST, WN, TN, JA, WN, AC, AC, TN, SH, TN }, 	 //	 564	 100
{ TN, TN, TN, KN, TN, ST, WN, TN, QN, TN, AC, AC, TN, ST, ST }, 	 //	 565	 100
{ TN, TN, TN, LO, CR, ST, WN, TN, KN, KN, AC, AC, LO, KN, KN }, 	 //	 566	 100
{ TN, TN, TN, WN, JA, ST, WN, TN, AC, JA, AC, AC, LO, KN, JA }, 	 //	 567	 100
{ TN, TN, TN, JA, QN, ST, WN, TN, TN, KN, AC, AC, LO, AC, AC }, 	 //	 568	 100
{ TN, TN, TN, WN, JA, ST, WN, LO, QN, JA, AC, AC, JA, QN, WN }, 	 //	 569	 100
{ TN, TN, TN, WN, KN, ST, WN, LO, AC, SK, AC, AC, JA, KN, QN }, 	 //	 570	 100
{ TN, TN, TN, AC, KN, ST, WN, LO, AC, QN, AC, AC, JA, AC, PF }, 	 //	 571	 100
{ TN, ST, WN, ST, AC, ST, JA, TN, JA, AC, AC, TN, TN, TN, CR }, 	 //	 572	 100
{ TN, ST, SK, SH, SK, ST, JA, JA, TN, QN, AC, TN, TN, TN, QN }, 	 //	 573	 100
{ TN, JA, KN, SK, AC, ST, TN, WN, JA, SK, AC, AC, TN, JA, KN }, 	 //	 574	 100
{ TN, JA, KN, KN, SK, ST, TN, WN, KN, QN, AC, AC, TN, KN, QN }, 	 //	 575	 100
{ TN, JA, WN, JA, KN, ST, TN, TN, JA, KN, AC, AC, TN, JA, CR }, 	 //	 576	 100
{ TN, JA, TN, JA, WN, ST, TN, TN, JA, TN, AC, AC, TN, JA, TN }, 	 //	 577	 100
{ TN, JA, SK, ST, KN, ST, TN, JA, JA, KN, AC, AC, TN, TN, KN }, 	 //	 578	 100
{ TN, TN, TN, AC, QN, ST, AC, TN, LO, KN, AC, AC, TN, KN, AC }, 	 //	 579	 100
{ TN, TN, TN, KN, AC, ST, AC, TN, KN, AC, AC, AC, TN, WN, SK }, 	 //	 580	 100
{ TN, TN, TN, KN, CR, ST, AC, LO, KN, KN, AC, AC, JA, KN, KN }, 	 //	 581	 100
{ TN, TN, TN, AC, KN, ST, AC, LO, AC, AC, AC, AC, JA, AC, LO }, 	 //	 582	 100
{ TN, TN, TN, KN, KN, ST, AC, LO, KN, QN, AC, AC, JA, KN, PF }, 	 //	 583	 100
{ TN, AC, SK, TN, PF, ST, AC, JA, TN, JA, AC, AC, TN, TN, TN }, 	 //	 584	 100
{ TN, AC, KN, TN, TN, ST, PF, WN, TN, AC, AC, KN, TN, WN, AC }, 	 //	 585	 100
{ TN, SK, TN, TN, JA, ST, QN, TN, TN, TN, AC, KN, TN, TN, AC }, 	 //	 586	 100
{ ST, KN, TN, SH, PF, AC, ST, AC, TN, JA, KN, QN, AC, TN, TN }, 	 //	 587	 100
{ ST, QN, TN, JA, JA, AC, QN, TN, TN, TN, KN, SK, TN, AC, AC }, 	 //	 588	 100
{ ST, QN, WN, JA, TN, AC, SK, TN, TN, AC, KN, JA, TN, AC, AC }, 	 //	 589	 100
{ ST, JA, TN, TN, TN, AC, JA, LO, WN, TN, KN, JA, JA, AC, ST }, 	 //	 590	 100
{ ST, TN, TN, TN, QN, AC, TN, TN, WN, PF, KN, TN, LO, AC, JA }, 	 //	 591	 100
{ ST, TN, TN, TN, AC, AC, WN, TN, TN, AC, KN, AC, LO, TN, AC }, 	 //	 592	 100
{ ST, TN, TN, TN, KN, AC, WN, TN, TN, AC, KN, AC, LO, TN, LO }, 	 //	 593	 100
{ ST, QN, TN, SH, TN, AC, ST, TN, TN, TN, KN, JA, LO, TN, ST }, 	 //	 594	 100
{ ST, ST, WN, SH, QN, AC, JA, TN, TN, SH, KN, TN, TN, TN, JA }, 	 //	 595	 100
{ ST, AC, WN, JA, WN, AC, AC, TN, TN, TN, KN, AC, TN, AC, TN }, 	 //	 596	 100
{ ST, KN, TN, TN, WN, AC, KN, AC, TN, TN, KN, KN, AC, WN, TN }, 	 //	 597	 100
{ AC, AC, TN, TN, TN, KN, AC, TN, TN, AC, QN, LO, LO, WN, AC }, 	 //	 598	 100
{ AC, AC, TN, ST, PF, KN, LO, TN, JA, JA, QN, KN, TN, TN, TN }, 	 //	 599	 100
{ AC, LO, WN, ST, WN, KN, KN, TN, JA, TN, QN, KN, TN, TN, TN }, 	 //	 600	 100
{ AC, KN, TN, TN, WN, KN, KN, AC, TN, TN, QN, KN, AC, WN, TN }, 	 //	 601	 100
{ AC, KN, TN, TN, TN, KN, KN, AC, TN, AC, QN, KN, AC, WN, AC }, 	 //	 602	 100
{ AC, KN, TN, SH, TN, KN, ST, TN, TN, TN, QN, QN, LO, TN, ST }, 	 //	 603	 100
{ AC, ST, SK, JA, TN, KN, QN, JA, TN, ST, QN, QN, TN, AC, AC }, 	 //	 604	 100
{ AC, JA, TN, TN, JA, KN, JA, TN, TN, TN, QN, JA, LO, WN, AC }, 	 //	 605	 100
{ AC, JA, KN, SH, ST, KN, SH, WN, TN, AC, QN, TN, TN, TN, KN }, 	 //	 606	 100
{ AC, JA, SK, TN, QN, KN, SH, JA, TN, SH, QN, TN, TN, TN, JA }, 	 //	 607	 100
{ AC, JA, SK, ST, AC, KN, SH, JA, JA, KN, QN, TN, TN, TN, QN }, 	 //	 608	 100
{ AC, JA, SK, JA, TN, KN, SH, JA, TN, ST, QN, TN, TN, AC, AC }, 	 //	 609	 100
{ AC, SH, TN, SH, TN, KN, TN, LO, TN, TN, QN, TN, JA, TN, ST }, 	 //	 610	 100
{ AC, SH, JA, TN, KN, KN, TN, TN, TN, SK, QN, TN, AC, WN, QN }, 	 //	 611	 100
{ AC, TN, KN, TN, SH, KN, TN, WN, TN, JA, QN, TN, TN, WN, JA }, 	 //	 612	 100
{ AC, TN, WN, ST, QN, KN, TN, TN, JA, KN, QN, TN, TN, TN, AC }, 	 //	 613	 100
{ AC, TN, TN, JA, TN, KN, TN, LO, TN, AC, QN, WN, JA, AC, AC }, 	 //	 614	 100
{ AC, TN, TN, TN, SK, KN, WN, TN, AC, QN, QN, AC, LO, AC, QN }, 	 //	 615	 100
{ AC, WN, TN, SH, PF, KN, AC, LO, TN, JA, QN, KN, JA, TN, TN }, 	 //	 616	 100
{ AC, JA, SK, SH, QN, KN, TN, JA, TN, QN, QN, AC, TN, TN, SH }, 	 //	 617	 100
{ AC, JA, SK, JA, JA, KN, TN, JA, TN, JA, QN, AC, TN, AC, JA }, 	 //	 618	 100
{ AC, PF, JA, TN, WN, KN, KN, TN, TN, TN, QN, KN, AC, WN, TN }, 	 //	 619	 100
{ KN, KN, TN, TN, JA, QN, KN, TN, TN, WN, PF, KN, LO, WN, TN }, 	 //	 620	 100
{ KN, QN, KN, TN, TN, QN, QN, WN, TN, ST, PF, SK, TN, WN, AC }, 	 //	 621	 100
{ KN, SH, WN, JA, AC, QN, TN, TN, SH, SK, PF, TN, TN, TN, KN }, 	 //	 622	 100
{ KN, TN, TN, JA, TN, QN, TN, TN, SH, TN, PF, TN, TN, TN, ST }, 	 //	 623	 100
{ KN, TN, TN, TN, JA, QN, TN, LO, AC, TN, PF, TN, JA, AC, AC }, 	 //	 624	 100
{ KN, TN, TN, TN, LO, QN, WN, LO, TN, AC, PF, AC, JA, TN, AC }, 	 //	 625	 100
{ KN, JA, SK, TN, JA, QN, TN, JA, TN, JA, PF, AC, TN, TN, WN }, 	 //	 626	 100
{ KN, JA, TN, SH, AC, QN, TN, AC, TN, KN, PF, AC, AC, TN, QN }, 	 //	 627	 100
{ KN, TN, TN, TN, AC, QN, AC, TN, AC, AC, PF, AC, TN, AC, CR }, 	 //	 628	 100
{ KN, TN, TN, TN, JA, QN, AC, LO, WN, WN, PF, AC, JA, AC, TN }, 	 //	 629	 100
{ KN, AC, WN, JA, WN, QN, PF, TN, SH, TN, PF, KN, TN, TN, TN }, 	 //	 630	 100
{ KN, PF, TN, JA, JA, QN, KN, TN, SH, WN, PF, KN, TN, TN, TN }, 	 //	 631	 100
{ KN, KN, TN, TN, TN, QN, KN, LO, AC, TN, PF, KN, JA, AC, TN }, 	 //	 632	 100
{ KN, KN, WN, ST, JA, QN, SK, TN, JA, WN, PF, QN, TN, TN, TN }, 	 //	 633	 100
{ KN, QN, SK, ST, TN, QN, KN, JA, JA, TN, PF, AC, TN, TN, TN }, 	 //	 634	 100
{ KN, KN, WN, TN, WN, QN, AC, TN, TN, TN, PF, SH, TN, WN, TN }, 	 //	 635	 100
{ QN, AC, WN, JA, TN, PF, SH, TN, TN, AC, JA, AC, TN, AC, AC }, 	 //	 636	 100
{ QN, AC, JA, TN, JA, PF, SH, TN, TN, TN, JA, AC, AC, WN, AC }, 	 //	 637	 100
{ QN, AC, WN, SH, JA, PF, LO, TN, TN, WN, JA, KN, TN, TN, TN }, 	 //	 638	 100
{ QN, LO, TN, TN, TN, PF, KN, AC, WN, TN, JA, KN, AC, AC, ST }, 	 //	 639	 100
{ QN, KN, SK, TN, TN, PF, KN, JA, TN, AC, JA, KN, TN, TN, AC }, 	 //	 640	 100
{ QN, QN, TN, SH, WN, PF, SK, AC, TN, TN, JA, JA, AC, TN, TN }, 	 //	 641	 100
{ QN, JA, WN, TN, QN, PF, SH, TN, TN, QN, JA, TN, TN, TN, SH }, 	 //	 642	 100
{ QN, JA, TN, TN, JA, PF, SH, TN, TN, WN, JA, TN, TN, WN, TN }, 	 //	 643	 100
{ QN, SH, SK, JA, KN, PF, TN, JA, SH, QN, JA, TN, TN, TN, PF }, 	 //	 644	 100
{ QN, SH, JA, TN, QN, PF, TN, TN, TN, PF, JA, TN, AC, WN, JA }, 	 //	 645	 100
{ QN, TN, KN, JA, JA, PF, TN, WN, TN, TN, JA, TN, TN, AC, AC }, 	 //	 646	 100
{ QN, TN, TN, TN, QN, PF, TN, LO, WN, KN, JA, TN, JA, AC, AC }, 	 //	 647	 100
{ QN, TN, SK, JA, PF, PF, TN, JA, TN, JA, JA, TN, TN, AC, TN }, 	 //	 648	 100
{ QN, TN, KN, TN, JA, PF, TN, WN, TN, JA, JA, WN, TN, WN, JA }, 	 //	 649	 100
{ QN, TN, JA, SH, QN, PF, TN, TN, TN, SH, JA, WN, AC, TN, JA }, 	 //	 650	 100
{ QN, WN, TN, TN, TN, PF, AC, LO, TN, ST, JA, KN, JA, TN, AC }, 	 //	 651	 100
{ QN, AC, TN, ST, JA, PF, KN, TN, JA, WN, JA, QN, TN, TN, TN }, 	 //	 652	 100
{ QN, ST, KN, ST, TN, PF, JA, WN, JA, AC, JA, TN, TN, TN, AC }, 	 //	 653	 100
{ QN, ST, TN, SH, SH, PF, JA, TN, TN, JA, JA, TN, TN, TN, JA }, 	 //	 654	 100
{ QN, JA, KN, TN, QN, PF, TN, WN, TN, QN, JA, AC, TN, TN, QN }, 	 //	 655	 100
{ QN, TN, KN, JA, TN, PF, AC, WN, TN, AC, JA, AC, TN, AC, AC }, 	 //	 656	 100
{ QN, KN, TN, TN, TN, PF, KN, LO, TN, ST, JA, KN, JA, TN, AC }, 	 //	 657	 100
{ QN, KN, TN, TN, JA, PF, AC, TN, TN, WN, JA, SH, TN, WN, TN }, 	 //	 658	 100
{ PF, SH, KN, JA, TN, JA, AC, WN, TN, AC, TN, AC, TN, AC, AC }, 	 //	 659	 100
{ PF, AC, TN, JA, JA, JA, AC, TN, TN, WN, TN, AC, LO, AC, TN }, 	 //	 660	 100
{ PF, AC, WN, SH, TN, JA, AC, TN, TN, ST, TN, LO, TN, TN, AC }, 	 //	 661	 100
{ PF, AC, KN, TN, TN, JA, LO, WN, TN, ST, TN, KN, TN, WN, AC }, 	 //	 662	 100
{ PF, KN, TN, TN, PF, JA, KN, TN, TN, JA, TN, KN, LO, TN, TN }, 	 //	 663	 100
{ PF, KN, TN, TN, TN, JA, ST, TN, WN, ST, TN, QN, LO, AC, AC }, 	 //	 664	 100
{ PF, QN, KN, SH, WN, JA, SK, WN, TN, TN, TN, JA, TN, TN, TN }, 	 //	 665	 100
{ PF, SK, JA, TN, JA, JA, JA, TN, TN, TN, TN, JA, AC, WN, AC }, 	 //	 666	 100
{ PF, JA, KN, WN, PF, JA, SH, WN, AC, JA, TN, TN, TN, KN, TN }, 	 //	 667	 100
{ PF, JA, WN, JA, QN, JA, SH, TN, JA, PF, TN, TN, TN, SH, JA }, 	 //	 668	 100
{ PF, JA, WN, JA, AC, JA, SH, TN, TN, LO, TN, TN, TN, AC, AC }, 	 //	 669	 100
{ PF, JA, TN, TN, QN, JA, SH, TN, AC, QN, TN, TN, TN, AC, SH }, 	 //	 670	 100
{ PF, JA, TN, KN, JA, JA, SH, TN, KN, TN, TN, TN, TN, SK, AC }, 	 //	 671	 100
{ PF, JA, TN, QN, JA, JA, SH, TN, KN, WN, TN, TN, TN, AC, TN }, 	 //	 672	 100
{ PF, JA, SK, QN, TN, JA, SH, JA, QN, TN, TN, TN, TN, SK, TN }, 	 //	 673	 100
{ PF, JA, SK, QN, KN, JA, SH, JA, QN, AC, TN, TN, TN, SK, LO }, 	 //	 674	 100
{ PF, SH, WN, TN, WN, JA, TN, TN, AC, TN, TN, TN, TN, AC, TN }, 	 //	 675	 100
{ PF, SH, TN, QN, JA, JA, TN, TN, QN, JA, TN, TN, LO, QN, JA }, 	 //	 676	 100
{ PF, SH, TN, PF, KN, JA, TN, LO, KN, KN, TN, TN, JA, KN, KN }, 	 //	 677	 100
{ PF, SH, SK, AC, QN, JA, TN, JA, PF, PF, TN, TN, TN, AC, JA }, 	 //	 678	 100
{ PF, SH, SK, KN, AC, JA, TN, JA, KN, AC, TN, TN, TN, SK, AC }, 	 //	 679	 100
{ PF, TN, KN, PF, KN, JA, TN, WN, AC, QN, TN, TN, TN, AC, PF }, 	 //	 680	 100
{ PF, TN, KN, PF, AC, JA, TN, WN, KN, KN, TN, TN, TN, KN, QN }, 	 //	 681	 100
{ PF, TN, WN, KN, KN, JA, TN, TN, WN, KN, TN, TN, TN, QN, KN }, 	 //	 682	 100
{ PF, TN, WN, QN, AC, JA, TN, TN, ST, AC, TN, TN, TN, JA, AC }, 	 //	 683	 100
{ PF, TN, TN, AC, TN, JA, TN, LO, AC, TN, TN, TN, JA, AC, TN }, 	 //	 684	 100
{ PF, TN, TN, LO, JA, JA, TN, LO, KN, TN, TN, TN, JA, KN, AC }, 	 //	 685	 100
{ PF, TN, TN, KN, TN, JA, TN, LO, QN, TN, TN, TN, JA, ST, ST }, 	 //	 686	 100
{ PF, TN, TN, AC, QN, JA, TN, LO, PF, QN, TN, TN, JA, KN, SH }, 	 //	 687	 100
{ PF, TN, TN, AC, AC, JA, TN, LO, PF, AC, TN, TN, JA, KN, SK }, 	 //	 688	 100
{ PF, TN, TN, QN, KN, JA, TN, LO, KN, KN, TN, TN, JA, AC, KN }, 	 //	 689	 100
{ PF, TN, SK, KN, SH, JA, TN, JA, WN, JA, TN, TN, TN, QN, JA }, 	 //	 690	 100
{ PF, TN, TN, AC, JA, JA, TN, AC, AC, JA, TN, TN, AC, LO, WN }, 	 //	 691	 100
{ PF, TN, TN, WN, QN, JA, TN, AC, AC, SH, TN, TN, AC, KN, JA }, 	 //	 692	 100
{ PF, TN, TN, AC, JA, JA, TN, AC, AC, JA, TN, TN, AC, PF, JA }, 	 //	 693	 100
{ PF, TN, TN, AC, PF, JA, TN, TN, AC, JA, TN, WN, TN, AC, TN }, 	 //	 694	 100
{ PF, TN, TN, QN, QN, JA, TN, TN, QN, PF, TN, WN, TN, QN, JA }, 	 //	 695	 100
{ PF, TN, TN, WN, QN, JA, TN, TN, AC, QN, TN, WN, LO, KN, SH }, 	 //	 696	 100
{ PF, TN, TN, KN, KN, JA, TN, TN, AC, AC, TN, WN, LO, PF, LO }, 	 //	 697	 100
{ PF, TN, TN, KN, JA, JA, TN, AC, WN, TN, TN, WN, AC, QN, AC }, 	 //	 698	 100
{ PF, TN, TN, WN, QN, JA, TN, AC, QN, QN, TN, WN, AC, QN, QN }, 	 //	 699	 100
{ PF, TN, TN, WN, KN, JA, TN, AC, AC, KN, TN, WN, AC, KN, KN }, 	 //	 700	 100
{ PF, TN, TN, ST, KN, JA, TN, AC, JA, KN, TN, WN, AC, TN, SK }, 	 //	 701	 100
{ PF, TN, TN, AC, SH, JA, TN, AC, PF, JA, TN, WN, AC, KN, JA }, 	 //	 702	 100
{ PF, TN, TN, SK, JA, JA, TN, AC, QN, TN, TN, WN, AC, KN, AC }, 	 //	 703	 100
{ PF, TN, TN, TN, KN, JA, WN, TN, TN, KN, TN, AC, LO, TN, KN }, 	 //	 704	 100
{ PF, KN, TN, TN, JA, JA, QN, TN, TN, WN, TN, ST, LO, WN, TN }, 	 //	 705	 100
{ PF, ST, KN, AC, AC, JA, JA, WN, LO, LO, TN, TN, TN, KN, AC }, 	 //	 706	 100
{ PF, ST, KN, WN, TN, JA, JA, WN, AC, ST, TN, TN, TN, KN, AC }, 	 //	 707	 100
{ PF, ST, KN, JA, KN, JA, JA, WN, TN, AC, TN, TN, TN, AC, LO }, 	 //	 708	 100
{ PF, ST, WN, KN, PF, JA, JA, TN, KN, JA, TN, TN, TN, WN, TN }, 	 //	 709	 100
{ PF, ST, WN, TN, CR, JA, JA, TN, AC, KN, TN, TN, TN, AC, KN }, 	 //	 710	 100
{ PF, ST, TN, KN, KN, JA, JA, TN, KN, KN, TN, TN, TN, WN, KN }, 	 //	 711	 100
{ PF, ST, TN, KN, JA, JA, JA, TN, QN, JA, TN, TN, TN, ST, WN }, 	 //	 712	 100
{ PF, ST, TN, AC, AC, JA, JA, TN, AC, AC, TN, TN, TN, AC, AC }, 	 //	 713	 100
{ PF, ST, TN, KN, CR, JA, JA, TN, KN, KN, TN, TN, TN, SK, KN }, 	 //	 714	 100
{ PF, ST, TN, KN, AC, JA, JA, TN, AC, AC, TN, TN, TN, PF, SK }, 	 //	 715	 100
{ PF, JA, TN, AC, SK, JA, TN, TN, PF, QN, TN, AC, TN, AC, QN }, 	 //	 716	 100
{ PF, JA, TN, AC, JA, JA, TN, TN, LO, JA, TN, AC, TN, KN, JA }, 	 //	 717	 100
{ PF, JA, TN, AC, KN, JA, TN, TN, KN, KN, TN, AC, TN, QN, KN }, 	 //	 718	 100
{ PF, JA, TN, JA, WN, JA, TN, LO, JA, TN, TN, AC, JA, SH, TN }, 	 //	 719	 100
{ PF, JA, TN, AC, JA, JA, TN, AC, KN, WN, TN, AC, AC, QN, TN }, 	 //	 720	 100
{ PF, JA, TN, KN, KN, JA, TN, AC, KN, AC, TN, AC, AC, KN, LO }, 	 //	 721	 100
{ PF, KN, SK, SH, TN, JA, KN, JA, TN, ST, TN, SK, TN, TN, AC }, 	 //	 722	 100
{ JA, AC, SK, TN, TN, TN, SH, JA, TN, TN, AC, AC, TN, WN, ST }, 	 //	 723	 100
{ JA, KN, KN, SH, TN, TN, KN, WN, TN, AC, AC, ST, TN, TN, AC }, 	 //	 724	 100
{ JA, KN, TN, JA, PF, TN, KN, LO, TN, JA, AC, ST, JA, AC, TN }, 	 //	 725	 100
{ JA, KN, TN, TN, TN, TN, ST, TN, WN, TN, AC, QN, TN, AC, TN }, 	 //	 726	 100
{ JA, QN, JA, JA, TN, TN, SK, TN, TN, TN, AC, JA, AC, AC, TN }, 	 //	 727	 100
{ JA, JA, TN, TN, PF, TN, JA, AC, TN, JA, AC, SH, AC, TN, TN }, 	 //	 728	 100
{ JA, JA, TN, TN, JA, TN, SH, TN, TN, JA, AC, TN, TN, TN, JA }, 	 //	 729	 100
{ JA, SH, WN, KN, TN, TN, TN, TN, KN, AC, AC, TN, TN, KN, AC }, 	 //	 730	 100
{ JA, SH, TN, SK, KN, TN, TN, TN, QN, KN, AC, TN, TN, KN, CR }, 	 //	 731	 100
{ JA, SH, JA, QN, LO, TN, TN, TN, QN, AC, AC, TN, AC, QN, AC }, 	 //	 732	 100
{ JA, SH, JA, KN, KN, TN, TN, TN, KN, KN, AC, TN, AC, KN, SK }, 	 //	 733	 100
{ JA, TN, WN, AC, KN, TN, TN, TN, KN, KN, AC, TN, TN, QN, KN }, 	 //	 734	 100
{ JA, TN, WN, AC, CR, TN, TN, TN, AC, KN, AC, TN, TN, AC, KN }, 	 //	 735	 100
{ JA, TN, WN, PF, CR, TN, TN, TN, KN, KN, AC, TN, TN, KN, KN }, 	 //	 736	 100
{ JA, TN, TN, AC, TN, TN, TN, TN, AC, AC, AC, TN, TN, LO, AC }, 	 //	 737	 100
{ JA, TN, TN, PF, SK, TN, TN, TN, AC, KN, AC, TN, LO, AC, KN }, 	 //	 738	 100
{ JA, TN, TN, JA, JA, TN, TN, TN, JA, JA, AC, TN, LO, SH, WN }, 	 //	 739	 100
{ JA, TN, KN, TN, CR, TN, TN, WN, TN, QN, AC, WN, TN, WN, KN }, 	 //	 740	 100
{ JA, TN, WN, JA, TN, TN, TN, TN, JA, ST, AC, WN, TN, JA, AC }, 	 //	 741	 100
{ JA, TN, WN, ST, LO, TN, TN, TN, JA, AC, AC, WN, TN, TN, AC }, 	 //	 742	 100
{ JA, TN, TN, WN, QN, TN, TN, TN, QN, QN, AC, WN, TN, QN, SH }, 	 //	 743	 100
{ JA, TN, TN, JA, QN, TN, TN, TN, SH, QN, AC, WN, TN, TN, SH }, 	 //	 744	 100
{ JA, TN, TN, AC, SH, TN, TN, TN, AC, JA, AC, WN, LO, AC, JA }, 	 //	 745	 100
{ JA, TN, TN, SH, LO, TN, TN, LO, TN, AC, AC, WN, JA, TN, AC }, 	 //	 746	 100
{ JA, TN, TN, TN, LO, TN, TN, LO, WN, AC, AC, WN, JA, AC, AC }, 	 //	 747	 100
{ JA, TN, SK, SH, SK, TN, TN, JA, TN, KN, AC, WN, TN, TN, KN }, 	 //	 748	 100
{ JA, TN, JA, AC, QN, TN, TN, TN, LO, QN, AC, WN, AC, KN, QN }, 	 //	 749	 100
{ JA, TN, JA, KN, LO, TN, TN, TN, AC, AC, AC, WN, AC, PF, AC }, 	 //	 750	 100
{ JA, TN, TN, TN, SK, TN, WN, TN, WN, KN, AC, AC, TN, AC, KN }, 	 //	 751	 100
{ JA, TN, TN, TN, AC, TN, WN, TN, TN, LO, AC, AC, LO, WN, AC }, 	 //	 752	 100
{ JA, WN, KN, JA, TN, TN, AC, WN, TN, TN, AC, KN, TN, AC, TN }, 	 //	 753	 100
{ JA, WN, TN, TN, TN, TN, AC, LO, TN, ST, AC, KN, JA, TN, AC }, 	 //	 754	 100
{ JA, WN, SK, TN, TN, TN, AC, JA, TN, TN, AC, KN, TN, WN, TN }, 	 //	 755	 100
{ JA, WN, TN, SH, WN, TN, AC, AC, TN, TN, AC, KN, AC, TN, TN }, 	 //	 756	 100
{ JA, AC, TN, JA, TN, TN, KN, AC, TN, TN, AC, QN, AC, AC, TN }, 	 //	 757	 100
{ JA, ST, TN, JA, AC, TN, JA, TN, SH, AC, AC, TN, TN, TN, SK }, 	 //	 758	 100
{ JA, ST, TN, TN, TN, TN, JA, TN, WN, ST, AC, TN, LO, AC, AC }, 	 //	 759	 100
{ JA, ST, SK, JA, KN, TN, JA, JA, SH, KN, AC, TN, TN, TN, KN }, 	 //	 760	 100
{ JA, ST, TN, SH, PF, TN, JA, AC, TN, JA, AC, TN, AC, TN, TN }, 	 //	 761	 100
{ JA, ST, TN, JA, JA, TN, JA, AC, TN, WN, AC, TN, AC, AC, TN }, 	 //	 762	 100
{ JA, JA, WN, ST, QN, TN, TN, TN, JA, PF, AC, AC, TN, TN, JA }, 	 //	 763	 100
{ JA, JA, TN, AC, AC, TN, TN, TN, LO, LO, AC, AC, TN, KN, AC }, 	 //	 764	 100
{ JA, JA, TN, LO, QN, TN, TN, TN, KN, QN, AC, AC, TN, KN, SH }, 	 //	 765	 100
{ JA, JA, TN, SK, SH, TN, TN, TN, JA, JA, AC, AC, TN, JA, JA }, 	 //	 766	 100
{ JA, JA, TN, KN, AC, TN, TN, TN, QN, AC, AC, AC, TN, ST, AC }, 	 //	 767	 100
{ JA, JA, TN, QN, CR, TN, TN, TN, ST, KN, AC, AC, TN, JA, KN }, 	 //	 768	 100
{ JA, JA, TN, ST, ST, TN, TN, TN, JA, AC, AC, AC, TN, TN, KN }, 	 //	 769	 100
{ JA, TN, KN, TN, WN, TN, AC, WN, TN, TN, AC, AC, TN, TN, TN }, 	 //	 770	 100
{ JA, AC, WN, TN, TN, TN, AC, TN, TN, ST, AC, PF, TN, TN, AC }, 	 //	 771	 100
{ JA, AC, TN, TN, PF, TN, PF, AC, TN, JA, AC, KN, AC, WN, TN }, 	 //	 772	 100
{ JA, PF, TN, TN, TN, TN, KN, LO, AC, ST, AC, KN, JA, AC, AC }, 	 //	 773	 100
{ JA, KN, TN, TN, JA, TN, SK, LO, TN, WN, AC, QN, JA, TN, TN }, 	 //	 774	 100
{ JA, QN, TN, TN, TN, TN, KN, TN, AC, TN, AC, AC, LO, AC, ST }, 	 //	 775	 100
{ TN, SH, TN, JA, PF, AC, AC, TN, TN, JA, AC, AC, TN, AC, TN }, 	 //	 776	 100
{ TN, SH, TN, TN, TN, AC, AC, TN, WN, TN, AC, AC, LO, AC, ST }, 	 //	 777	 100
{ TN, SH, TN, TN, WN, AC, AC, LO, TN, TN, AC, AC, JA, WN, TN }, 	 //	 778	 100
{ TN, QN, TN, JA, JA, AC, QN, TN, SH, WN, AC, SK, TN, TN, TN }, 	 //	 779	 100
{ TN, JA, TN, JA, JA, AC, JA, LO, TN, WN, AC, SH, JA, AC, TN }, 	 //	 780	 100
{ TN, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, LO, CR }, 	 //	 781	 100
{ TN, SH, TN, AC, JA, AC, TN, TN, AC, WN, AC, TN, TN, PF, TN }, 	 //	 782	 100
{ TN, SH, TN, AC, ST, AC, TN, TN, AC, AC, AC, TN, TN, PF, KN }, 	 //	 783	 100
{ TN, SH, SK, PF, TN, AC, TN, JA, AC, AC, AC, TN, TN, AC, AC }, 	 //	 784	 100
{ TN, SH, SK, PF, TN, AC, TN, JA, KN, TN, AC, TN, TN, KN, TN }, 	 //	 785	 100
{ TN, SH, SK, KN, QN, AC, TN, JA, KN, QN, AC, TN, TN, KN, QN }, 	 //	 786	 100
{ TN, TN, KN, TN, CR, AC, TN, WN, WN, QN, AC, TN, TN, AC, KN }, 	 //	 787	 100
{ TN, TN, WN, WN, KN, AC, TN, TN, QN, SK, AC, TN, TN, QN, QN }, 	 //	 788	 100
{ TN, TN, TN, PF, KN, AC, TN, LO, KN, KN, AC, TN, JA, KN, SK }, 	 //	 789	 100
{ TN, TN, SK, KN, KN, AC, TN, JA, KN, QN, AC, TN, TN, KN, PF }, 	 //	 790	 100
{ TN, TN, SK, JA, KN, AC, TN, JA, JA, KN, AC, TN, TN, JA, SK }, 	 //	 791	 100
{ TN, TN, TN, AC, JA, AC, TN, AC, LO, TN, AC, TN, AC, KN, AC }, 	 //	 792	 100
{ TN, TN, KN, AC, KN, AC, TN, WN, PF, KN, AC, WN, TN, AC, KN }, 	 //	 793	 100
{ TN, TN, KN, KN, AC, AC, TN, WN, KN, KN, AC, WN, TN, KN, QN }, 	 //	 794	 100
{ TN, TN, TN, KN, TN, AC, TN, TN, KN, TN, AC, WN, LO, WN, ST }, 	 //	 795	 100
{ TN, TN, TN, QN, SK, AC, TN, TN, QN, QN, AC, WN, LO, SK, QN }, 	 //	 796	 100
{ TN, TN, TN, AC, JA, AC, TN, TN, AC, WN, AC, WN, LO, PF, TN }, 	 //	 797	 100
{ TN, TN, SK, AC, AC, AC, TN, JA, AC, AC, AC, WN, TN, AC, CR }, 	 //	 798	 100
{ TN, TN, SK, AC, KN, AC, TN, JA, AC, KN, AC, WN, TN, LO, KN }, 	 //	 799	 100
{ TN, TN, TN, JA, AC, AC, TN, AC, JA, AC, AC, WN, AC, JA, AC }, 	 //	 800	 100
{ TN, TN, TN, WN, KN, AC, TN, AC, AC, KN, AC, WN, AC, KN, KN }, 	 //	 801	 100
{ TN, TN, TN, AC, TN, AC, WN, TN, AC, TN, AC, AC, TN, PF, TN }, 	 //	 802	 100
{ TN, ST, KN, JA, QN, AC, JA, WN, SH, KN, AC, TN, TN, TN, AC }, 	 //	 803	 100
{ TN, ST, TN, JA, QN, AC, JA, TN, SH, SH, AC, TN, TN, TN, JA }, 	 //	 804	 100
{ TN, JA, KN, QN, KN, AC, TN, WN, QN, QN, AC, AC, TN, SK, PF }, 	 //	 805	 100
{ TN, JA, KN, KN, QN, AC, TN, WN, QN, QN, AC, AC, TN, ST, QN }, 	 //	 806	 100
{ TN, JA, WN, QN, TN, AC, TN, TN, QN, TN, AC, AC, TN, QN, ST }, 	 //	 807	 100
{ TN, JA, WN, QN, PF, AC, TN, TN, QN, JA, AC, AC, TN, SK, TN }, 	 //	 808	 100
{ TN, JA, WN, SK, CR, AC, TN, TN, JA, QN, AC, AC, TN, JA, KN }, 	 //	 809	 100
{ TN, JA, TN, AC, QN, AC, TN, TN, PF, PF, AC, AC, TN, KN, JA }, 	 //	 810	 100
{ TN, JA, TN, TN, TN, AC, TN, LO, AC, ST, AC, AC, JA, AC, AC }, 	 //	 811	 100
{ TN, JA, SK, KN, KN, AC, TN, JA, QN, KN, AC, AC, TN, ST, KN }, 	 //	 812	 100
{ TN, JA, SK, AC, QN, AC, TN, JA, AC, SH, AC, AC, TN, AC, JA }, 	 //	 813	 100
{ TN, TN, TN, ST, JA, AC, AC, TN, JA, JA, AC, AC, LO, TN, WN }, 	 //	 814	 100
{ TN, TN, TN, QN, JA, AC, AC, LO, KN, TN, AC, AC, JA, AC, AC }, 	 //	 815	 100
{ TN, TN, TN, QN, AC, AC, AC, LO, KN, AC, AC, AC, JA, AC, SK }, 	 //	 816	 100
{ TN, TN, TN, KN, KN, AC, AC, LO, AC, KN, AC, AC, JA, PF, KN }, 	 //	 817	 100
{ TN, AC, TN, SH, TN, AC, AC, LO, TN, TN, AC, AC, JA, TN, TN }, 	 //	 818	 100
{ TN, AC, KN, SH, JA, AC, PF, WN, TN, WN, AC, KN, TN, TN, TN }, 	 //	 819	 100
{ TN, AC, TN, TN, TN, AC, PF, TN, AC, TN, AC, KN, TN, AC, TN }, 	 //	 820	 100
{ TN, SK, TN, SH, JA, AC, QN, TN, TN, WN, AC, KN, LO, TN, TN }, 	 //	 821	 100
{ TN, QN, TN, TN, TN, AC, KN, LO, TN, ST, AC, AC, JA, WN, AC }, 	 //	 822	 100
{ TN, KN, KN, TN, TN, AC, AC, WN, TN, ST, AC, SH, TN, WN, AC }, 	 //	 823	 100
{ AC, AC, SK, TN, TN, AC, SH, JA, TN, ST, AC, AC, TN, TN, AC }, 	 //	 824	 100
{ AC, LO, TN, TN, PF, AC, KN, AC, TN, JA, AC, KN, AC, WN, TN }, 	 //	 825	 100
{ AC, QN, JA, TN, TN, AC, QN, TN, TN, TN, AC, SK, AC, WN, TN }, 	 //	 826	 100
{ AC, JA, KN, TN, TN, AC, JA, WN, TN, AC, AC, JA, TN, TN, AC }, 	 //	 827	 100
{ AC, JA, TN, TN, PF, AC, JA, TN, TN, JA, AC, SH, TN, WN, TN }, 	 //	 828	 100
{ AC, JA, KN, JA, AC, AC, SH, WN, SH, AC, AC, TN, TN, TN, AC }, 	 //	 829	 100
{ AC, JA, WN, SH, AC, AC, SH, TN, TN, AC, AC, TN, TN, TN, SK }, 	 //	 830	 100
{ AC, JA, TN, ST, KN, AC, SH, TN, JA, SK, AC, TN, TN, TN, QN }, 	 //	 831	 100
{ AC, SH, TN, TN, SH, AC, TN, LO, TN, JA, AC, TN, JA, WN, JA }, 	 //	 832	 100
{ AC, SH, JA, SH, SK, AC, TN, TN, TN, KN, AC, TN, AC, TN, KN }, 	 //	 833	 100
{ AC, SH, JA, TN, AC, AC, TN, TN, TN, AC, AC, TN, AC, TN, AC }, 	 //	 834	 100
{ AC, TN, TN, TN, ST, AC, TN, LO, WN, AC, AC, TN, JA, AC, KN }, 	 //	 835	 100
{ AC, TN, JA, TN, QN, AC, TN, TN, TN, KN, AC, TN, AC, TN, AC }, 	 //	 836	 100
{ AC, TN, TN, TN, KN, AC, WN, LO, TN, KN, AC, AC, JA, TN, KN }, 	 //	 837	 100
{ AC, KN, TN, TN, TN, AC, QN, AC, WN, TN, AC, ST, AC, AC, TN }, 	 //	 838	 100
{ AC, ST, WN, TN, QN, AC, JA, TN, TN, SH, AC, TN, TN, TN, JA }, 	 //	 839	 100
{ AC, JA, SK, TN, AC, AC, TN, JA, TN, AC, AC, AC, TN, TN, AC }, 	 //	 840	 100
{ AC, TN, WN, TN, WN, AC, AC, TN, TN, TN, AC, AC, TN, WN, TN }, 	 //	 841	 100
{ AC, AC, SK, TN, TN, AC, PF, JA, TN, AC, AC, KN, TN, TN, AC }, 	 //	 842	 100
{ AC, KN, SK, JA, JA, AC, KN, JA, SH, WN, AC, KN, TN, TN, TN }, 	 //	 843	 100
{ AC, KN, TN, JA, PF, AC, SK, TN, TN, JA, AC, QN, LO, AC, TN }, 	 //	 844	 100
{ AC, SK, KN, SH, JA, AC, QN, WN, TN, WN, AC, KN, TN, TN, TN }, 	 //	 845	 100
{ AC, QN, TN, SH, TN, AC, QN, AC, TN, TN, SK, QN, AC, TN, TN }, 	 //	 846	 100
{ AC, SK, WN, SH, JA, AC, JA, TN, TN, WN, SK, JA, TN, TN, TN }, 	 //	 847	 100
{ AC, JA, WN, TN, SH, AC, SH, TN, TN, JA, SK, TN, TN, TN, JA }, 	 //	 848	 100
{ AC, SH, KN, JA, KN, AC, TN, WN, SH, KN, SK, TN, TN, TN, SK }, 	 //	 849	 100
{ AC, SH, TN, TN, SK, AC, TN, LO, TN, QN, SK, TN, JA, TN, QN }, 	 //	 850	 100
{ AC, SH, TN, TN, ST, AC, TN, LO, TN, AC, SK, TN, JA, TN, KN }, 	 //	 851	 100
{ AC, TN, KN, TN, CR, AC, TN, WN, TN, QN, SK, TN, TN, WN, KN }, 	 //	 852	 100
{ AC, TN, KN, JA, AC, AC, TN, WN, TN, AC, SK, TN, TN, AC, SK }, 	 //	 853	 100
{ AC, TN, TN, TN, WN, AC, WN, TN, WN, TN, SK, AC, TN, AC, TN }, 	 //	 854	 100
{ AC, JA, KN, SH, JA, AC, TN, WN, TN, JA, SK, AC, TN, TN, WN }, 	 //	 855	 100
{ AC, JA, JA, TN, TN, AC, TN, TN, TN, AC, SK, AC, AC, TN, AC }, 	 //	 856	 100
{ AC, TN, TN, TN, SH, AC, AC, TN, TN, JA, SK, AC, LO, WN, JA }, 	 //	 857	 100
{ AC, AC, SK, JA, TN, AC, PF, JA, TN, TN, SK, KN, TN, AC, ST }, 	 //	 858	 100
{ AC, PF, JA, TN, WN, AC, KN, TN, TN, TN, SK, KN, AC, TN, TN }, 	 //	 859	 100
{ AC, SK, JA, TN, TN, AC, QN, TN, TN, TN, SK, KN, AC, TN, TN }, 	 //	 860	 100
{ AC, SH, TN, JA, JA, SK, AC, TN, TN, WN, KN, AC, LO, AC, TN }, 	 //	 861	 100
{ AC, QN, JA, TN, WN, SK, QN, TN, TN, TN, KN, QN, AC, TN, TN }, 	 //	 862	 100
{ AC, JA, KN, TN, TN, SK, JA, WN, TN, AC, KN, SH, TN, TN, AC }, 	 //	 863	 100
{ AC, TN, TN, JA, KN, SK, TN, LO, TN, KN, KN, WN, JA, AC, KN }, 	 //	 864	 100
{ AC, TN, TN, TN, KN, SK, WN, TN, TN, KN, KN, AC, TN, WN, SK }, 	 //	 865	 100
{ AC, AC, SK, TN, PF, SK, KN, JA, TN, JA, KN, QN, TN, TN, TN }, 	 //	 866	 100
{ AC, ST, KN, TN, JA, SK, JA, WN, TN, JA, KN, TN, TN, TN, JA }, 	 //	 867	 100
{ AC, ST, TN, JA, KN, SK, JA, TN, SH, KN, KN, TN, TN, TN, KN }, 	 //	 868	 100
{ AC, TN, TN, TN, WN, SK, AC, LO, AC, TN, KN, AC, JA, AC, TN }, 	 //	 869	 100
{ AC, AC, TN, TN, TN, SK, PF, LO, TN, ST, KN, KN, JA, WN, AC }, 	 //	 870	 100
{ SK, KN, SK, SH, JA, KN, ST, JA, TN, WN, KN, QN, TN, TN, TN }, 	 //	 871	 100
{ SK, QN, SK, TN, WN, KN, QN, JA, TN, TN, KN, QN, TN, TN, TN }, 	 //	 872	 100
{ SK, QN, TN, JA, PF, KN, QN, AC, TN, JA, KN, SK, AC, AC, TN }, 	 //	 873	 100
{ SK, JA, TN, TN, PF, KN, JA, TN, TN, JA, KN, SH, TN, WN, TN }, 	 //	 874	 100
{ SK, TN, TN, JA, KN, KN, TN, LO, TN, KN, KN, TN, JA, AC, KN }, 	 //	 875	 100
{ SK, TN, TN, JA, QN, KN, TN, LO, TN, KN, KN, WN, JA, AC, AC }, 	 //	 876	 100
{ SK, TN, TN, TN, SH, KN, WN, LO, WN, JA, KN, AC, JA, AC, JA }, 	 //	 877	 100
{ SK, KN, TN, JA, JA, KN, QN, TN, TN, TN, KN, ST, TN, AC, AC }, 	 //	 878	 100
{ SK, KN, TN, TN, TN, KN, QN, TN, TN, AC, KN, ST, LO, WN, AC }, 	 //	 879	 100
{ SK, QN, TN, TN, WN, KN, ST, AC, TN, TN, KN, JA, AC, WN, TN }, 	 //	 880	 100
{ SK, ST, WN, SH, AC, KN, JA, TN, TN, AC, KN, TN, TN, TN, CR }, 	 //	 881	 100
{ SK, ST, TN, TN, SK, KN, JA, TN, TN, QN, KN, TN, TN, TN, QN }, 	 //	 882	 100
{ SK, JA, JA, TN, QN, KN, TN, TN, TN, KN, KN, AC, AC, WN, AC }, 	 //	 883	 100
{ SK, TN, TN, ST, JA, KN, AC, TN, JA, WN, KN, AC, TN, TN, TN }, 	 //	 884	 100
{ SK, TN, TN, TN, QN, KN, AC, TN, AC, QN, KN, AC, TN, AC, QN }, 	 //	 885	 100
{ SK, TN, TN, TN, JA, KN, AC, LO, WN, JA, KN, AC, JA, AC, WN }, 	 //	 886	 100
{ SK, KN, TN, TN, TN, KN, KN, LO, TN, ST, KN, KN, JA, TN, AC }, 	 //	 887	 100
{ KN, SH, TN, TN, WN, KN, AC, AC, TN, TN, KN, AC, AC, WN, TN }, 	 //	 888	 100
{ KN, KN, JA, TN, TN, KN, ST, TN, TN, TN, KN, QN, AC, TN, ST }, 	 //	 889	 100
{ KN, JA, KN, SH, JA, KN, JA, WN, TN, WN, KN, JA, TN, TN, TN }, 	 //	 890	 100
{ KN, JA, WN, JA, AC, KN, SH, TN, SH, KN, KN, TN, TN, TN, QN }, 	 //	 891	 100
{ KN, JA, TN, SH, QN, KN, SH, TN, TN, KN, KN, TN, TN, TN, AC }, 	 //	 892	 100
{ KN, JA, TN, SH, JA, KN, SH, LO, TN, WN, KN, TN, JA, TN, TN }, 	 //	 893	 100
{ KN, TN, KN, JA, AC, KN, TN, WN, SH, AC, KN, TN, TN, TN, AC }, 	 //	 894	 100
{ KN, TN, JA, SH, ST, KN, TN, TN, TN, AC, KN, TN, AC, TN, KN }, 	 //	 895	 100
{ KN, TN, TN, TN, KN, KN, TN, AC, AC, KN, KN, TN, AC, AC, SK }, 	 //	 896	 100
{ KN, TN, TN, TN, AC, KN, WN, TN, TN, KN, KN, AC, LO, WN, QN }, 	 //	 897	 100
{ KN, TN, SK, SH, TN, KN, WN, JA, TN, AC, KN, AC, TN, TN, AC }, 	 //	 898	 100
{ KN, TN, TN, TN, JA, KN, WN, AC, TN, JA, KN, AC, AC, TN, JA }, 	 //	 899	 100
{ KN, ST, TN, ST, JA, KN, JA, TN, JA, TN, KN, TN, TN, TN, AC }, 	 //	 900	 100
{ KN, ST, TN, TN, JA, KN, JA, TN, TN, TN, KN, TN, LO, TN, AC }, 	 //	 901	 100
{ KN, TN, TN, SH, JA, KN, AC, LO, TN, WN, KN, AC, JA, TN, TN }, 	 //	 902	 100
{ KN, TN, TN, TN, CR, KN, AC, LO, TN, KN, KN, AC, JA, TN, KN }, 	 //	 903	 100
{ KN, TN, TN, TN, KN, KN, AC, LO, TN, KN, KN, AC, JA, WN, KN }, 	 //	 904	 100
{ KN, AC, WN, JA, TN, KN, AC, TN, TN, AC, KN, PF, TN, AC, AC }, 	 //	 905	 100
{ KN, PF, TN, TN, TN, KN, KN, TN, AC, AC, KN, KN, TN, AC, AC }, 	 //	 906	 100
{ KN, SK, KN, JA, TN, KN, QN, WN, SH, TN, KN, KN, TN, TN, TN }, 	 //	 907	 100
{ KN, KN, SK, ST, WN, KN, AC, JA, JA, TN, KN, SH, TN, TN, TN }, 	 //	 908	 100
{ KN, AC, TN, TN, TN, KN, LO, TN, AC, TN, WN, KN, TN, AC, ST }, 	 //	 909	 100
{ KN, AC, TN, TN, JA, KN, LO, TN, TN, WN, WN, KN, LO, TN, TN }, 	 //	 910	 100
{ KN, ST, KN, SH, PF, KN, QN, WN, TN, JA, WN, QN, TN, TN, TN }, 	 //	 911	 100
{ KN, QN, JA, JA, TN, KN, QN, TN, TN, TN, WN, SK, AC, AC, TN }, 	 //	 912	 100
{ KN, QN, JA, TN, TN, KN, SK, TN, TN, TN, WN, JA, AC, WN, ST }, 	 //	 913	 100
{ KN, JA, KN, SH, AC, KN, SH, WN, TN, AC, WN, TN, TN, TN, SK }, 	 //	 914	 100
{ KN, JA, KN, TN, JA, KN, SH, WN, TN, JA, WN, TN, TN, TN, WN }, 	 //	 915	 100
{ KN, JA, WN, SH, SK, KN, SH, TN, TN, QN, WN, TN, TN, TN, QN }, 	 //	 916	 100
{ KN, SH, SK, TN, AC, KN, TN, JA, TN, AC, WN, TN, TN, WN, AC }, 	 //	 917	 100
{ KN, SH, TN, TN, JA, KN, TN, AC, TN, TN, WN, TN, AC, WN, AC }, 	 //	 918	 100
{ KN, SH, TN, JA, KN, KN, TN, AC, TN, AC, WN, TN, AC, AC, LO }, 	 //	 919	 100
{ KN, TN, WN, JA, AC, KN, TN, TN, SH, KN, WN, TN, TN, TN, QN }, 	 //	 920	 100
{ KN, TN, KN, JA, AC, KN, TN, WN, TN, AC, WN, WN, TN, AC, CR }, 	 //	 921	 100
{ KN, KN, WN, JA, PF, KN, QN, TN, SH, JA, WN, ST, TN, TN, TN }, 	 //	 922	 100
{ KN, ST, SK, TN, AC, KN, JA, JA, TN, SK, WN, TN, TN, TN, KN }, 	 //	 923	 100
{ KN, ST, JA, TN, JA, KN, JA, TN, TN, TN, WN, TN, AC, TN, AC }, 	 //	 924	 100
{ KN, JA, TN, SH, TN, KN, TN, LO, TN, ST, WN, AC, JA, TN, AC }, 	 //	 925	 100
{ KN, TN, TN, TN, KN, KN, AC, LO, AC, KN, WN, AC, JA, AC, KN }, 	 //	 926	 100
{ KN, TN, TN, TN, QN, KN, AC, LO, AC, KN, WN, AC, JA, AC, AC }, 	 //	 927	 100
{ KN, AC, TN, SH, JA, KN, AC, AC, TN, WN, WN, PF, AC, TN, TN }, 	 //	 928	 100
{ KN, AC, JA, TN, WN, KN, PF, TN, TN, TN, WN, KN, AC, TN, TN }, 	 //	 929	 100
{ KN, KN, TN, TN, TN, KN, KN, TN, AC, TN, WN, KN, LO, AC, ST }, 	 //	 930	 100
{ KN, KN, SK, TN, WN, KN, KN, JA, TN, TN, WN, KN, TN, TN, TN }, 	 //	 931	 100
{ KN, SK, TN, TN, TN, KN, QN, LO, TN, AC, WN, KN, JA, TN, AC }, 	 //	 932	 100
{ KN, SK, TN, SH, TN, KN, QN, AC, TN, TN, WN, KN, AC, TN, TN }, 	 //	 933	 100
{ KN, AC, KN, TN, TN, WN, AC, WN, TN, ST, QN, AC, TN, TN, AC }, 	 //	 934	 100
{ KN, AC, TN, TN, TN, WN, AC, TN, TN, ST, QN, AC, LO, TN, AC }, 	 //	 935	 100
{ KN, KN, TN, TN, TN, WN, KN, LO, TN, ST, QN, KN, JA, WN, AC }, 	 //	 936	 100
{ KN, KN, TN, TN, TN, WN, KN, TN, AC, TN, QN, ST, LO, AC, ST }, 	 //	 937	 100
{ KN, KN, TN, TN, TN, WN, KN, LO, WN, TN, QN, ST, JA, AC, TN }, 	 //	 938	 100
{ KN, QN, JA, TN, TN, WN, QN, TN, TN, TN, QN, QN, AC, TN, TN }, 	 //	 939	 100
{ KN, SH, TN, SH, KN, WN, TN, AC, TN, KN, QN, TN, AC, TN, KN }, 	 //	 940	 100
{ KN, TN, TN, TN, KN, WN, TN, TN, AC, KN, QN, TN, TN, AC, CR }, 	 //	 941	 100
{ KN, TN, TN, TN, KN, WN, TN, TN, AC, KN, QN, TN, LO, AC, KN }, 	 //	 942	 100
{ KN, TN, TN, JA, ST, WN, TN, LO, TN, AC, QN, TN, JA, AC, KN }, 	 //	 943	 100
{ KN, TN, TN, TN, KN, WN, TN, LO, AC, KN, QN, TN, JA, AC, SK }, 	 //	 944	 100
{ KN, TN, TN, TN, SK, WN, TN, LO, AC, KN, QN, TN, JA, AC, KN }, 	 //	 945	 100
{ KN, TN, JA, SH, QN, WN, TN, TN, TN, SH, QN, TN, AC, TN, JA }, 	 //	 946	 100
{ KN, TN, SK, TN, QN, WN, TN, JA, TN, KN, QN, WN, TN, TN, AC }, 	 //	 947	 100
{ KN, WN, TN, TN, TN, WN, AC, TN, WN, TN, QN, KN, TN, AC, ST }, 	 //	 948	 100
{ KN, WN, SK, TN, PF, WN, AC, JA, TN, JA, QN, KN, TN, TN, TN }, 	 //	 949	 100
{ KN, QN, SK, TN, JA, WN, ST, JA, TN, WN, QN, JA, TN, TN, TN }, 	 //	 950	 100
{ KN, ST, KN, JA, ST, WN, JA, WN, SH, AC, QN, TN, TN, TN, KN }, 	 //	 951	 100
{ KN, JA, KN, SH, QN, WN, TN, WN, TN, PF, QN, AC, TN, TN, JA }, 	 //	 952	 100
{ KN, AC, TN, TN, TN, WN, PF, TN, TN, ST, QN, KN, LO, TN, AC }, 	 //	 953	 100
{ KN, KN, TN, TN, PF, WN, KN, TN, TN, JA, QN, SK, TN, WN, TN }, 	 //	 954	 100
{ KN, KN, TN, JA, PF, WN, KN, LO, TN, JA, QN, SK, JA, AC, TN }, 	 //	 955	 100
{ WN, AC, TN, TN, PF, QN, SH, LO, TN, JA, KN, AC, JA, TN, TN }, 	 //	 956	 100
{ WN, AC, SK, JA, TN, QN, AC, JA, TN, ST, KN, AC, TN, AC, AC }, 	 //	 957	 100
{ WN, KN, JA, TN, TN, QN, ST, TN, TN, TN, KN, QN, AC, WN, TN }, 	 //	 958	 100
{ WN, KN, TN, TN, TN, QN, ST, AC, WN, TN, KN, QN, AC, AC, ST }, 	 //	 959	 100
{ WN, QN, WN, TN, TN, QN, QN, TN, TN, AC, KN, QN, TN, WN, AC }, 	 //	 960	 100
{ WN, SK, TN, TN, TN, QN, JA, AC, AC, TN, KN, JA, AC, AC, TN }, 	 //	 961	 100
{ WN, JA, WN, SH, QN, QN, SH, TN, TN, SH, KN, TN, TN, TN, JA }, 	 //	 962	 100
{ WN, SH, TN, SH, QN, QN, TN, AC, TN, QN, KN, TN, AC, TN, QN }, 	 //	 963	 100
{ WN, TN, TN, JA, AC, QN, TN, LO, TN, LO, KN, WN, JA, AC, AC }, 	 //	 964	 100
{ WN, TN, JA, TN, KN, QN, TN, TN, TN, KN, KN, WN, AC, WN, CR }, 	 //	 965	 100
{ WN, TN, JA, SH, TN, QN, WN, TN, TN, TN, KN, AC, AC, TN, ST }, 	 //	 966	 100
{ WN, AC, TN, TN, PF, QN, KN, TN, TN, JA, KN, QN, LO, WN, TN }, 	 //	 967	 100
{ WN, KN, TN, JA, JA, QN, QN, TN, TN, WN, KN, ST, LO, AC, TN }, 	 //	 968	 100
{ WN, QN, TN, TN, TN, QN, ST, AC, WN, TN, KN, JA, AC, AC, TN }, 	 //	 969	 100
{ WN, ST, KN, ST, TN, QN, JA, WN, JA, AC, KN, TN, TN, TN, AC }, 	 //	 970	 100
{ WN, ST, TN, SH, JA, QN, JA, TN, TN, WN, KN, TN, LO, TN, TN }, 	 //	 971	 100
{ WN, JA, KN, TN, KN, QN, TN, WN, TN, KN, KN, AC, TN, WN, KN }, 	 //	 972	 100
{ WN, JA, SK, TN, JA, QN, TN, JA, TN, TN, KN, AC, TN, WN, AC }, 	 //	 973	 100
{ WN, AC, WN, JA, TN, QN, AC, TN, SH, TN, KN, PF, TN, TN, TN }, 	 //	 974	 100
{ WN, KN, WN, SH, JA, QN, KN, TN, TN, WN, KN, SK, TN, TN, TN }, 	 //	 975	 100
{ WN, KN, TN, TN, PF, QN, KN, TN, TN, JA, KN, SK, LO, TN, TN }, 	 //	 976	 100
{ QN, AC, WN, SH, JA, KN, AC, TN, TN, TN, AC, AC, TN, TN, AC }, 	 //	 977	 100
{ QN, AC, TN, TN, JA, KN, AC, TN, TN, TN, AC, AC, LO, WN, AC }, 	 //	 978	 100
{ QN, AC, TN, TN, TN, KN, AC, TN, AC, AC, AC, LO, TN, AC, AC }, 	 //	 979	 100
{ QN, AC, TN, TN, TN, KN, LO, AC, TN, AC, AC, KN, AC, TN, AC }, 	 //	 980	 100
{ QN, QN, KN, TN, TN, KN, QN, WN, TN, ST, AC, QN, TN, WN, AC }, 	 //	 981	 100
{ QN, QN, WN, SH, JA, KN, SK, TN, TN, WN, AC, JA, TN, TN, TN }, 	 //	 982	 100
{ QN, QN, TN, JA, JA, KN, SK, TN, TN, TN, AC, JA, TN, AC, AC }, 	 //	 983	 100
{ QN, JA, WN, TN, KN, KN, SH, TN, TN, SK, AC, TN, TN, TN, QN }, 	 //	 984	 100
{ QN, SH, KN, JA, LO, KN, TN, WN, TN, AC, AC, TN, TN, AC, AC }, 	 //	 985	 100
{ QN, TN, SK, TN, PF, KN, TN, JA, TN, JA, AC, TN, TN, WN, TN }, 	 //	 986	 100
{ QN, TN, JA, SH, QN, KN, TN, TN, TN, SH, AC, TN, AC, TN, JA }, 	 //	 987	 100
{ QN, TN, TN, TN, KN, KN, TN, TN, WN, KN, AC, WN, TN, AC, KN }, 	 //	 988	 100
{ QN, TN, SK, JA, AC, KN, TN, JA, TN, SK, AC, WN, TN, AC, KN }, 	 //	 989	 100
{ QN, TN, JA, TN, AC, KN, TN, TN, TN, LO, AC, WN, AC, WN, AC }, 	 //	 990	 100
{ QN, AC, TN, TN, TN, KN, KN, TN, TN, AC, AC, QN, LO, WN, AC }, 	 //	 991	 100
{ QN, KN, WN, ST, TN, KN, QN, TN, JA, TN, AC, ST, TN, TN, TN }, 	 //	 992	 100
{ QN, QN, TN, TN, TN, KN, ST, TN, WN, TN, AC, JA, LO, AC, TN }, 	 //	 993	 100
{ QN, ST, SK, TN, CR, KN, JA, JA, TN, QN, AC, TN, TN, TN, KN }, 	 //	 994	 100
{ QN, TN, TN, TN, AC, KN, AC, LO, TN, SK, AC, AC, JA, WN, KN }, 	 //	 995	 100
{ QN, AC, KN, SH, TN, KN, PF, WN, TN, AC, AC, KN, TN, TN, AC }, 	 //	 996	 100
{ QN, AC, SK, SH, TN, KN, PF, JA, TN, ST, AC, KN, TN, TN, AC }, 	 //	 997	 100
{ QN, AC, SK, SH, PF, KN, PF, JA, TN, JA, AC, KN, TN, TN, TN }, 	 //	 998	 100
{ QN, PF, TN, JA, WN, KN, KN, TN, SH, TN, AC, KN, TN, TN, TN }, 	 //	 999	 100
{ QN, PF, TN, SH, TN, KN, KN, TN, TN, AC, AC, KN, TN, TN, AC }};	 //	 1000	 100
