#include "ReelDefine.h"

unsigned char L5_Outcome_11500[1000][15]={	 //	 0	 11500
{ AC, SH, SH, PF, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 1	 11500
{ AC, SH, SH, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 2	 11500
{ AC, SH, SH, TN, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 3	 11500
{ AC, SH, TN, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 4	 11500
{ AC, SH, TN, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 5	 11500
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 6	 11500
{ AC, SH, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 7	 11500
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 8	 11500
{ AC, AC, SH, TN, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 9	 11500
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 10	 11500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 11	 11500
{ AC, AC, AC, WN, JA, LO, AC, AC, AC, TN, AC, AC, AC, KN, AC }, 	 //	 12	 11500
{ AC, AC, AC, WN, QN, LO, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 13	 11500
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 14	 11500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 15	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 16	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, LO, AC }, 	 //	 17	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 18	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, PF, AC }, 	 //	 19	 11500
{ AC, AC, TN, PF, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 20	 11500
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 21	 11500
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 22	 11500
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 23	 11500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 24	 11500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 25	 11500
{ AC, AC, AC, WN, QN, LO, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 26	 11500
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 27	 11500
{ AC, AC, AC, KN, JA, LO, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 28	 11500
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 29	 11500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 30	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, WN, AC, AC }, 	 //	 31	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 32	 11500
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 33	 11500
{ AC, AC, AC, TN, JA, LO, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 34	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, LO, PF, AC, AC }, 	 //	 35	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, LO, PF, PF, AC }, 	 //	 36	 11500
{ AC, AC, AC, PF, JA, LO, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 37	 11500
{ AC, AC, AC, PF, QN, LO, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 38	 11500
{ AC, AC, AC, TN, JA, LO, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 39	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, LO, WN, AC, AC }, 	 //	 40	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, LO, WN, PF, AC }, 	 //	 41	 11500
{ AC, WN, AC, WN, AC, LO, AC, AC, AC, LO, AC, KN, AC, KN, AC }, 	 //	 42	 11500
{ AC, WN, AC, KN, AC, LO, AC, AC, AC, LO, AC, KN, AC, PF, AC }, 	 //	 43	 11500
{ AC, TN, SH, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 44	 11500
{ AC, TN, SH, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 45	 11500
{ AC, TN, TN, PF, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 46	 11500
{ AC, TN, TN, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 47	 11500
{ AC, TN, TN, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 48	 11500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, KN, AC, AC, AC, LO, QN }, 	 //	 49	 11500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 50	 11500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 51	 11500
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 52	 11500
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 53	 11500
{ AC, AC, AC, WN, TN, LO, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 54	 11500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 55	 11500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 56	 11500
{ AC, AC, AC, KN, TN, LO, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 57	 11500
{ AC, AC, AC, KN, JA, LO, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 58	 11500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 59	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 60	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, LO, AC }, 	 //	 61	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, PF, PF, AC }, 	 //	 62	 11500
{ AC, AC, AC, WN, QN, LO, AC, AC, AC, KN, AC, AC, AC, KN, AC }, 	 //	 63	 11500
{ AC, AC, AC, KN, TN, LO, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 64	 11500
{ AC, AC, AC, KN, QN, LO, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 65	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, AC, WN, PF, AC }, 	 //	 66	 11500
{ AC, AC, AC, PF, QN, LO, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 67	 11500
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 68	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, PF, PF, LO, AC }, 	 //	 69	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, PF, PF, AC, AC }, 	 //	 70	 11500
{ AC, AC, AC, PF, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 71	 11500
{ AC, AC, AC, PF, QN, LO, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 72	 11500
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 73	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, PF, WN, AC, AC }, 	 //	 74	 11500
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, LO, AC, PF, WN, LO, AC }, 	 //	 75	 11500
{ LO, AC, AC, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 76	 11500
{ LO, AC, AC, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 77	 11500
{ LO, SH, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 78	 11500
{ LO, SH, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 79	 11500
{ LO, SH, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 80	 11500
{ LO, SH, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 81	 11500
{ LO, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 82	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 83	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 84	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 85	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 86	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 87	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 88	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 89	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 90	 11500
{ LO, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 91	 11500
{ LO, AC, SH, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 92	 11500
{ LO, AC, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 93	 11500
{ LO, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 94	 11500
{ LO, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 95	 11500
{ LO, AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 96	 11500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 97	 11500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 98	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 99	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 100	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 101	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 102	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 103	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 104	 11500
{ LO, AC, TN, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 105	 11500
{ LO, AC, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 106	 11500
{ LO, AC, TN, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 107	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 108	 11500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 109	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 110	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 111	 11500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 112	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 113	 11500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 114	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 115	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 116	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 117	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 118	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 119	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 120	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 121	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 122	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 123	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 124	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 125	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 126	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 127	 11500
{ LO, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 128	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 129	 11500
{ LO, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 130	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 131	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 132	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 133	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 134	 11500
{ LO, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 135	 11500
{ LO, WN, AC, WN, LO, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 136	 11500
{ LO, WN, AC, WN, TN, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 137	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 138	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, AC }, 	 //	 139	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, AC }, 	 //	 140	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 141	 11500
{ LO, WN, AC, AC, LO, AC, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 142	 11500
{ LO, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 143	 11500
{ LO, WN, AC, WN, LO, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 144	 11500
{ LO, WN, AC, WN, TN, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 145	 11500
{ LO, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 146	 11500
{ LO, WN, AC, KN, LO, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 147	 11500
{ LO, WN, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 148	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 149	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 150	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 151	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 152	 11500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 153	 11500
{ LO, TN, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 154	 11500
{ LO, TN, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 155	 11500
{ LO, TN, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 156	 11500
{ LO, TN, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 157	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 158	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 159	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 160	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 161	 11500
{ LO, TN, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 162	 11500
{ LO, TN, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 163	 11500
{ LO, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 164	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 165	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 166	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 167	 11500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 168	 11500
{ LO, AC, SH, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 169	 11500
{ LO, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 170	 11500
{ LO, AC, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 171	 11500
{ LO, AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 172	 11500
{ LO, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 173	 11500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 174	 11500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 175	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 176	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 177	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 178	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 179	 11500
{ LO, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 180	 11500
{ LO, AC, TN, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 181	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 182	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 183	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 184	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 185	 11500
{ LO, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 186	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 187	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 188	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 189	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 190	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 191	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 192	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 193	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 194	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 195	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 196	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 197	 11500
{ LO, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 198	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 199	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 200	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 201	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 202	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 203	 11500
{ LO, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 204	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 205	 11500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 206	 11500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 207	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 208	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 209	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 210	 11500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 211	 11500
{ LO, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 212	 11500
{ LO, KN, AC, AC, LO, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 213	 11500
{ LO, KN, AC, WN, TN, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 214	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 215	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 216	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, LO, AC }, 	 //	 217	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, PF, AC }, 	 //	 218	 11500
{ LO, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 219	 11500
{ LO, KN, AC, WN, LO, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 220	 11500
{ LO, KN, AC, WN, TN, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 221	 11500
{ LO, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 222	 11500
{ LO, KN, AC, KN, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 223	 11500
{ LO, KN, AC, KN, TN, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 224	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 225	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 226	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, PF, AC }, 	 //	 227	 11500
{ LO, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, PF, AC }, 	 //	 228	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 229	 11500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 230	 11500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 231	 11500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 232	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 233	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 234	 11500
{ AC, SH, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 235	 11500
{ AC, SH, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 236	 11500
{ AC, SH, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 237	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 238	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 239	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 240	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 241	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 242	 11500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 243	 11500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 244	 11500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 245	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 246	 11500
{ AC, SH, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 247	 11500
{ AC, SH, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 248	 11500
{ AC, SH, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 249	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 250	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 251	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 252	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 253	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 254	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 255	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 256	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 257	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 258	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 259	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 260	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 261	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 262	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 263	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 264	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 265	 11500
{ AC, AC, AC, AC, LO, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 266	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 267	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 268	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 269	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 270	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 271	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 272	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 273	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 274	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 275	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 276	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 277	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 278	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 279	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 280	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 281	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 282	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 283	 11500
{ AC, AC, AC, AC, LO, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 284	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, CR }, 	 //	 285	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 286	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, SK }, 	 //	 287	 11500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 288	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 289	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 290	 11500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 291	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 292	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 293	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 294	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 295	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 296	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 297	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 298	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 299	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 300	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 301	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 302	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 303	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 304	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 305	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 306	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 307	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, PF, KN, AC }, 	 //	 308	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, PF, KN, AC }, 	 //	 309	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 310	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 311	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 312	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 313	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 314	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 315	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 316	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 317	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 318	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 319	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 320	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 321	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 322	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 323	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 324	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 325	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 326	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 327	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 328	 11500
{ AC, WN, SH, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 329	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 330	 11500
{ AC, WN, SH, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 331	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 332	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 333	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 334	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, AC }, 	 //	 335	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 336	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 337	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, PF, AC }, 	 //	 338	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, PF, AC }, 	 //	 339	 11500
{ AC, WN, TN, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 340	 11500
{ AC, WN, TN, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 341	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 342	 11500
{ AC, WN, TN, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 343	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 344	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 345	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 346	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 347	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 348	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, PF, AC }, 	 //	 349	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 350	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 351	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 352	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 353	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 354	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 355	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 356	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 357	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 358	 11500
{ AC, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 359	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 360	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 361	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 362	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 363	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 364	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 365	 11500
{ AC, TN, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 366	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 367	 11500
{ AC, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 368	 11500
{ AC, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 369	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 370	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 371	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 372	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 373	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 374	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 375	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 376	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 377	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 378	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 379	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 380	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 381	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, CR }, 	 //	 382	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 383	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 384	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 385	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 386	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 387	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 388	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 389	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 390	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 391	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 392	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 393	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 394	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 395	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 396	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 397	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, CR }, 	 //	 398	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 399	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, SK }, 	 //	 400	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, SK, AC, AC, AC, AC, KN }, 	 //	 401	 11500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 402	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 403	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 404	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 405	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 406	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 407	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 408	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 409	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 410	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 411	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 412	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 413	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 414	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 415	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 416	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 417	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, PF, KN, AC }, 	 //	 418	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 419	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 420	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 421	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 422	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 423	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 424	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 425	 11500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 426	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, WN, KN, AC }, 	 //	 427	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 428	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 429	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 430	 11500
{ AC, KN, SH, PF, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 431	 11500
{ AC, KN, SH, PF, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 432	 11500
{ AC, KN, SH, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 433	 11500
{ AC, KN, SH, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 434	 11500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 435	 11500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 436	 11500
{ AC, KN, TN, PF, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 437	 11500
{ AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 438	 11500
{ AC, KN, TN, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 439	 11500
{ AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 440	 11500
{ AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 441	 11500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 442	 11500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, LO, AC }, 	 //	 443	 11500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, PF, AC }, 	 //	 444	 11500
{ AC, AC, AC, AC, AC, AC, SH, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 445	 11500
{ AC, AC, AC, AC, AC, AC, SH, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 446	 11500
{ AC, AC, AC, AC, AC, AC, SH, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 447	 11500
{ AC, SH, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 448	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 449	 11500
{ AC, SH, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 450	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 451	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 452	 11500
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, CR }, 	 //	 453	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 454	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 455	 11500
{ AC, SH, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, CR }, 	 //	 456	 11500
{ AC, SH, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, SK }, 	 //	 457	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 458	 11500
{ AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 459	 11500
{ AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 460	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 461	 11500
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, CR }, 	 //	 462	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 463	 11500
{ AC, SH, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, SK }, 	 //	 464	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 465	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 466	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 467	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 468	 11500
{ AC, AC, AC, PF, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 469	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 470	 11500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 471	 11500
{ AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 472	 11500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 473	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, SK }, 	 //	 474	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, CR }, 	 //	 475	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 476	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 477	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 478	 11500
{ AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 479	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 480	 11500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 481	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, LO, CR }, 	 //	 482	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, LO, SK }, 	 //	 483	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, SK }, 	 //	 484	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, PF, SK }, 	 //	 485	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 486	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 487	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 488	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 489	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, AC, SK }, 	 //	 490	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, LO, CR }, 	 //	 491	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, PF, PF, SK }, 	 //	 492	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 493	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, LO, AC, AC, AC }, 	 //	 494	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, AC, SK }, 	 //	 495	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, LO, CR }, 	 //	 496	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, LO, WN, PF, CR }, 	 //	 497	 11500
{ AC, WN, SH, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 498	 11500
{ AC, WN, SH, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 499	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 500	 11500
{ AC, WN, SH, TN, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 501	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 502	 11500
{ AC, WN, AC, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, CR }, 	 //	 503	 11500
{ AC, WN, AC, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, SK }, 	 //	 504	 11500
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, ST, KN, AC, KN, CR }, 	 //	 505	 11500
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, ST, KN, AC, KN, SK }, 	 //	 506	 11500
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, CR }, 	 //	 507	 11500
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, SK }, 	 //	 508	 11500
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, ST, KN, AC, PF, CR }, 	 //	 509	 11500
{ AC, WN, TN, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 510	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 511	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 512	 11500
{ AC, WN, AC, PF, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, SK }, 	 //	 513	 11500
{ AC, WN, AC, WN, AC, AC, AC, AC, AC, AC, ST, KN, AC, KN, CR }, 	 //	 514	 11500
{ AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, ST, KN, AC, AC, SK }, 	 //	 515	 11500
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, ST, KN, AC, PF, CR }, 	 //	 516	 11500
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, ST, KN, AC, PF, SK }, 	 //	 517	 11500
{ AC, TN, SH, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 518	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 519	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 520	 11500
{ AC, TN, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 521	 11500
{ AC, TN, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 522	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 523	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 524	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 525	 11500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, CR }, 	 //	 526	 11500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, SK }, 	 //	 527	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 528	 11500
{ AC, TN, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, CR }, 	 //	 529	 11500
{ AC, TN, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 530	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 531	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 532	 11500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, CR }, 	 //	 533	 11500
{ AC, TN, AC, WN, AC, AC, AC, AC, AC, AC, ST, AC, AC, KN, SK }, 	 //	 534	 11500
{ AC, TN, AC, KN, AC, AC, AC, AC, AC, AC, ST, AC, AC, PF, SK }, 	 //	 535	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 536	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 537	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 538	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 539	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, SK, ST, AC, AC, AC, KN }, 	 //	 540	 11500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 541	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, LO, CR }, 	 //	 542	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, AC, CR }, 	 //	 543	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, AC, SK }, 	 //	 544	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, PF, PF, SK }, 	 //	 545	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 546	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 547	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 548	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 549	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 550	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, KN, ST, AC, AC, AC, QN }, 	 //	 551	 11500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 552	 11500
{ AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, ST, AC, AC, AC, KN }, 	 //	 553	 11500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, ST, AC, AC, AC, LO }, 	 //	 554	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, SK }, 	 //	 555	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, CR }, 	 //	 556	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, AC, SK }, 	 //	 557	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, AC, WN, PF, SK }, 	 //	 558	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 559	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 560	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 561	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, PF, AC, CR }, 	 //	 562	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, PF, AC, CR }, 	 //	 563	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 564	 11500
{ AC, AC, TN, PF, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 565	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 566	 11500
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, ST, PF, AC, AC, AC }, 	 //	 567	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, AC, SK }, 	 //	 568	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, LO, CR }, 	 //	 569	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, ST, PF, WN, PF, SK }, 	 //	 570	 11500
{ AC, KN, SH, AC, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 571	 11500
{ AC, KN, SH, TN, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 572	 11500
{ AC, KN, SH, AC, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 573	 11500
{ AC, KN, AC, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, CR }, 	 //	 574	 11500
{ AC, KN, AC, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, SK }, 	 //	 575	 11500
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, ST, SH, AC, KN, CR }, 	 //	 576	 11500
{ AC, KN, AC, TN, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, SK }, 	 //	 577	 11500
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, ST, SH, AC, PF, CR }, 	 //	 578	 11500
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, ST, SH, AC, PF, SK }, 	 //	 579	 11500
{ AC, KN, TN, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 580	 11500
{ AC, KN, TN, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 581	 11500
{ AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 582	 11500
{ AC, KN, TN, TN, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 583	 11500
{ AC, KN, AC, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, CR }, 	 //	 584	 11500
{ AC, KN, AC, PF, AC, AC, AC, AC, AC, AC, ST, SH, AC, AC, SK }, 	 //	 585	 11500
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, ST, SH, AC, KN, CR }, 	 //	 586	 11500
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, AC, ST, SH, AC, KN, SK }, 	 //	 587	 11500
{ AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, ST, SH, AC, PF, CR }, 	 //	 588	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 589	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 590	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 591	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 592	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 593	 11500
{ AC, AC, AC, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 594	 11500
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 595	 11500
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 596	 11500
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 597	 11500
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 598	 11500
{ AC, SH, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 599	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 600	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 601	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 602	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 603	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, LO, AC, AC, AC }, 	 //	 604	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, LO, KN, LO, AC, AC, AC }, 	 //	 605	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, LO, AC, AC, AC }, 	 //	 606	 11500
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, LO, KN, KN, AC, AC, AC }, 	 //	 607	 11500
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, LO, KN, KN, AC, AC, AC }, 	 //	 608	 11500
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 609	 11500
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 610	 11500
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 611	 11500
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 612	 11500
{ AC, TN, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 613	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 614	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 615	 11500
{ AC, AC, AC, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 616	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 617	 11500
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, PF, AC, AC, AC }, 	 //	 618	 11500
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 619	 11500
{ AC, KN, AC, AC, AC, ST, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 620	 11500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 621	 11500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 622	 11500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 623	 11500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 624	 11500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 625	 11500
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 626	 11500
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 627	 11500
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 628	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 629	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 630	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 631	 11500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 632	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 633	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 634	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 635	 11500
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 636	 11500
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 637	 11500
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 638	 11500
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, LO, AC, AC, AC, LO, AC }, 	 //	 639	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 640	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 641	 11500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 642	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 643	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 644	 11500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 645	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 646	 11500
{ TN, AC, AC, AC, TN, ST, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 647	 11500
{ TN, AC, AC, AC, LO, ST, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 648	 11500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 649	 11500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 650	 11500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 651	 11500
{ TN, KN, AC, AC, AC, ST, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 652	 11500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 653	 11500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 654	 11500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 655	 11500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 656	 11500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 657	 11500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 658	 11500
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 659	 11500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 660	 11500
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 661	 11500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 662	 11500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 663	 11500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 664	 11500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 665	 11500
{ ST, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 666	 11500
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 667	 11500
{ AC, AC, AC, AC, AC, KN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 668	 11500
{ AC, AC, AC, AC, AC, KN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 669	 11500
{ AC, AC, AC, AC, AC, KN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 670	 11500
{ AC, AC, AC, AC, AC, KN, SH, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 671	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 672	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 673	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 674	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 675	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 676	 11500
{ AC, SH, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 677	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 678	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 679	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 680	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 681	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 682	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, LO, QN, LO, AC, AC, AC }, 	 //	 683	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, LO, QN, LO, AC, AC, AC }, 	 //	 684	 11500
{ AC, WN, AC, AC, AC, KN, AC, AC, AC, LO, QN, KN, AC, AC, AC }, 	 //	 685	 11500
{ AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 686	 11500
{ AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 687	 11500
{ AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 688	 11500
{ AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 689	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 690	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 691	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 692	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 693	 11500
{ AC, AC, AC, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 694	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, LO, QN, PF, AC, AC, AC }, 	 //	 695	 11500
{ AC, AC, AC, PF, AC, KN, AC, AC, AC, LO, QN, PF, AC, AC, AC }, 	 //	 696	 11500
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, LO, QN, SH, AC, AC, AC }, 	 //	 697	 11500
{ JA, AC, AC, AC, AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 698	 11500
{ JA, AC, AC, AC, AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 699	 11500
{ JA, AC, AC, AC, AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 700	 11500
{ JA, AC, AC, AC, AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 701	 11500
{ JA, SH, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 702	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 703	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 704	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 705	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 706	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 707	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 708	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 709	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 710	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 711	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 712	 11500
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 713	 11500
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 714	 11500
{ JA, WN, AC, AC, AC, TN, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 715	 11500
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 716	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 717	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 718	 11500
{ JA, AC, AC, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 719	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 720	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 721	 11500
{ JA, AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 722	 11500
{ JA, KN, AC, AC, AC, TN, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 723	 11500
{ TN, AC, AC, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 724	 11500
{ TN, AC, AC, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 725	 11500
{ TN, AC, AC, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 726	 11500
{ TN, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 727	 11500
{ TN, SH, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 728	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 729	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 730	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 731	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 732	 11500
{ TN, SH, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 733	 11500
{ TN, SH, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 734	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 735	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 736	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 737	 11500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 738	 11500
{ TN, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 739	 11500
{ TN, AC, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 740	 11500
{ TN, AC, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 741	 11500
{ TN, AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 742	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, LO, AC }, 	 //	 743	 11500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 744	 11500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 745	 11500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 746	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 747	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 748	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 749	 11500
{ TN, AC, TN, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 750	 11500
{ TN, AC, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 751	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 752	 11500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 753	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 754	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 755	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 756	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 757	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 758	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 759	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, AC, AC, AC }, 	 //	 760	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 761	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, LO, AC }, 	 //	 762	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 763	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 764	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 765	 11500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 766	 11500
{ TN, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, LO, AC, KN, AC }, 	 //	 767	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, AC, AC, AC }, 	 //	 768	 11500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 769	 11500
{ TN, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 770	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 771	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 772	 11500
{ TN, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 773	 11500
{ TN, WN, AC, WN, LO, AC, AC, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 774	 11500
{ TN, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 775	 11500
{ TN, WN, AC, KN, LO, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 776	 11500
{ TN, WN, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 777	 11500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 778	 11500
{ TN, WN, AC, AC, LO, AC, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 779	 11500
{ TN, WN, AC, AC, LO, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 780	 11500
{ TN, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 781	 11500
{ TN, WN, AC, KN, TN, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 782	 11500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 783	 11500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 784	 11500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 785	 11500
{ TN, TN, SH, PF, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 786	 11500
{ TN, TN, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 787	 11500
{ TN, TN, SH, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 788	 11500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 789	 11500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 790	 11500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 791	 11500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 792	 11500
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 793	 11500
{ TN, AC, SH, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 794	 11500
{ TN, AC, SH, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 795	 11500
{ TN, AC, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 796	 11500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO, KN }, 	 //	 797	 11500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 798	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 799	 11500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 800	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 801	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 802	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 803	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 804	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 805	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 806	 11500
{ TN, AC, TN, PF, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 807	 11500
{ TN, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 808	 11500
{ TN, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 809	 11500
{ TN, AC, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 810	 11500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 811	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 812	 11500
{ TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN }, 	 //	 813	 11500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 814	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 815	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 816	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 817	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 818	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 819	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 820	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 821	 11500
{ TN, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, PF, AC, KN, AC }, 	 //	 822	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 823	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 824	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 825	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, PF, LO, AC }, 	 //	 826	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 827	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC, AC }, 	 //	 828	 11500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 829	 11500
{ TN, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 830	 11500
{ TN, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, PF, AC, PF, AC }, 	 //	 831	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 832	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, LO, AC }, 	 //	 833	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 834	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, AC, AC }, 	 //	 835	 11500
{ TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 836	 11500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, WN, PF, AC }, 	 //	 837	 11500
{ TN, KN, AC, WN, TN, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 838	 11500
{ TN, KN, AC, AC, LO, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 839	 11500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 840	 11500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, PF, AC, AC }, 	 //	 841	 11500
{ TN, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 842	 11500
{ TN, KN, AC, WN, LO, AC, AC, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 843	 11500
{ TN, KN, AC, AC, TN, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 844	 11500
{ TN, KN, AC, KN, TN, AC, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 845	 11500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 846	 11500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, LO, AC }, 	 //	 847	 11500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 848	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 849	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 850	 11500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 851	 11500
{ AC, SH, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 852	 11500
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 853	 11500
{ AC, SH, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 854	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 855	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 856	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 857	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 858	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 859	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 860	 11500
{ AC, SH, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 861	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 862	 11500
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 863	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 864	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 865	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 866	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 867	 11500
{ AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 868	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 869	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 870	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 871	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 872	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 873	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 874	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 875	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 876	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 877	 11500
{ AC, AC, AC, AC, LO, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 878	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 879	 11500
{ AC, AC, AC, AC, TN, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 880	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, SK, AC, AC, AC, AC, KN }, 	 //	 881	 11500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 882	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 883	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 884	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 885	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 886	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 887	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 888	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 889	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 890	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }, 	 //	 891	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 892	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 893	 11500
{ AC, AC, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 894	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 895	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 896	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 897	 11500
{ AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 898	 11500
{ AC, AC, AC, AC, LO, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 899	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, CR }, 	 //	 900	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 901	 11500
{ AC, AC, AC, AC, TN, AC, AC, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 902	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, SK }, 	 //	 903	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, SK, AC, AC, AC, AC, KN }, 	 //	 904	 11500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 905	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 906	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 907	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 908	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, WN, KN, AC }, 	 //	 909	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 910	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 911	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 912	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 913	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 914	 11500
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 915	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 916	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 917	 11500
{ AC, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 918	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 919	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, LO, PF, KN, AC }, 	 //	 920	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 921	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 922	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 923	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, PF, PF, AC }, 	 //	 924	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 925	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 926	 11500
{ AC, AC, AC, PF, LO, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 927	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 928	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 929	 11500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, WN, KN, AC }, 	 //	 930	 11500
{ AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 931	 11500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 932	 11500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 933	 11500
{ AC, AC, AC, KN, LO, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 934	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 935	 11500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, LO, WN, PF, AC }, 	 //	 936	 11500
{ AC, WN, SH, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 937	 11500
{ AC, WN, SH, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 938	 11500
{ AC, WN, SH, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 939	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 940	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, AC }, 	 //	 941	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 942	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 943	 11500
{ AC, WN, TN, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 944	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 945	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 946	 11500
{ AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 947	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, LO, AC }, 	 //	 948	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 949	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, PF, AC }, 	 //	 950	 11500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, WN, PF, AC }, 	 //	 951	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 952	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 953	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 954	 11500
{ AC, TN, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 955	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 956	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 957	 11500
{ AC, TN, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 958	 11500
{ AC, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 959	 11500
{ AC, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 960	 11500
{ AC, TN, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 961	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 962	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 963	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 964	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 965	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 966	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 967	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 968	 11500
{ AC, TN, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 969	 11500
{ AC, TN, TN, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 970	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 971	 11500
{ AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 972	 11500
{ AC, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 973	 11500
{ AC, TN, TN, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 974	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 975	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 976	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 977	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 978	 11500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 979	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 980	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 981	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 982	 11500
{ AC, AC, SH, WN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 983	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 984	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 985	 11500
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 986	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 987	 11500
{ AC, AC, SH, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 988	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, AC, CR }, 	 //	 989	 11500
{ AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC, AC, AC, QN }, 	 //	 990	 11500
{ AC, AC, AC, AC, JA, AC, AC, AC, PF, TN, AC, AC, AC, AC, AC }, 	 //	 991	 11500
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 992	 11500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 993	 11500
{ AC, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 994	 11500
{ AC, AC, AC, WN, LO, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 995	 11500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC }, 	 //	 996	 11500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, AC }, 	 //	 997	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 998	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 999	 11500
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK }};	 //	 1000	 11500
