unsigned char L5_Outcome_4500[1000][15]={	 //	 0	 4500
{ AC, AC, AC, KN, QN, LO, SH, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 1	 4500
{ AC, SH, AC, JA, AC, LO, AC, AC, JA, LO, AC, AC, AC, SH, AC }, 	 //	 2	 4500
{ AC, SH, AC, JA, JA, LO, AC, AC, JA, JA, AC, AC, AC, SH, WN }, 	 //	 3	 4500
{ AC, SH, AC, JA, KN, LO, AC, AC, JA, KN, AC, AC, AC, SH, CR }, 	 //	 4	 4500
{ AC, SH, AC, JA, KN, LO, AC, AC, SH, AC, AC, AC, AC, TN, LO }, 	 //	 5	 4500
{ AC, SH, AC, KN, TN, LO, AC, AC, SK, ST, AC, AC, AC, QN, AC }, 	 //	 6	 4500
{ AC, SH, AC, SK, AC, LO, AC, AC, QN, SK, AC, AC, AC, KN, KN }, 	 //	 7	 4500
{ AC, AC, AC, WN, CR, LO, AC, WN, AC, KN, AC, AC, KN, KN, KN }, 	 //	 8	 4500
{ AC, AC, AC, KN, JA, LO, AC, AC, KN, JA, AC, LO, AC, KN, WN }, 	 //	 9	 4500
{ AC, AC, AC, QN, KN, LO, AC, AC, KN, KN, AC, LO, AC, AC, CR }, 	 //	 10	 4500
{ AC, AC, AC, KN, JA, LO, AC, AC, WN, WN, AC, LO, AC, QN, TN }, 	 //	 11	 4500
{ AC, AC, AC, TN, KN, LO, AC, AC, TN, KN, AC, LO, AC, TN, SK }, 	 //	 12	 4500
{ AC, AC, AC, PF, QN, LO, AC, AC, KN, QN, AC, LO, AC, KN, SH }, 	 //	 13	 4500
{ AC, AC, AC, PF, TN, LO, AC, AC, KN, TN, AC, LO, AC, KN, ST }, 	 //	 14	 4500
{ AC, AC, AC, AC, CR, LO, AC, WN, LO, QN, AC, LO, KN, KN, KN }, 	 //	 15	 4500
{ AC, LO, AC, WN, AC, LO, KN, AC, AC, AC, AC, KN, AC, KN, AC }, 	 //	 16	 4500
{ AC, KN, AC, AC, AC, LO, ST, AC, AC, AC, AC, QN, AC, AC, CR }, 	 //	 17	 4500
{ AC, KN, AC, AC, TN, LO, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 18	 4500
{ AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, PF, CR }, 	 //	 19	 4500
{ AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, SK, PF, LO, AC }, 	 //	 20	 4500
{ AC, SK, AC, TN, LO, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 21	 4500
{ AC, JA, AC, AC, AC, LO, SH, AC, AC, LO, AC, TN, AC, LO, AC }, 	 //	 22	 4500
{ AC, TN, AC, KN, KN, LO, AC, AC, WN, KN, AC, AC, AC, QN, SK }, 	 //	 23	 4500
{ AC, TN, AC, JA, KN, LO, AC, AC, JA, KN, AC, AC, AC, JA, SK }, 	 //	 24	 4500
{ AC, TN, AC, PF, TN, LO, AC, AC, KN, ST, AC, AC, AC, KN, AC }, 	 //	 25	 4500
{ AC, TN, AC, SK, KN, LO, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 26	 4500
{ AC, TN, AC, LO, KN, LO, AC, AC, KN, KN, AC, AC, AC, KN, SK }, 	 //	 27	 4500
{ AC, AC, AC, LO, JA, LO, AC, AC, KN, JA, AC, PF, AC, KN, WN }, 	 //	 28	 4500
{ AC, AC, AC, KN, KN, LO, AC, AC, WN, SK, AC, PF, AC, QN, QN }, 	 //	 29	 4500
{ AC, AC, AC, KN, AC, LO, AC, AC, KN, LO, AC, PF, AC, KN, AC }, 	 //	 30	 4500
{ AC, AC, AC, KN, QN, LO, AC, AC, SK, QN, AC, PF, AC, QN, QN }, 	 //	 31	 4500
{ AC, AC, AC, KN, LO, LO, PF, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 32	 4500
{ AC, KN, AC, AC, LO, LO, SK, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 33	 4500
{ LO, SH, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 34	 4500
{ LO, SH, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, SK, JA }, 	 //	 35	 4500
{ LO, SH, AC, SK, PF, AC, AC, AC, JA, JA, AC, AC, AC, JA, TN }, 	 //	 36	 4500
{ LO, SH, AC, TN, QN, AC, AC, AC, TN, PF, AC, AC, AC, TN, JA }, 	 //	 37	 4500
{ LO, AC, AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, SK, AC }, 	 //	 38	 4500
{ LO, AC, AC, QN, AC, AC, AC, AC, QN, SK, AC, AC, AC, SK, KN }, 	 //	 39	 4500
{ LO, AC, AC, QN, TN, AC, AC, AC, SK, TN, AC, AC, AC, JA, ST }, 	 //	 40	 4500
{ LO, AC, AC, SK, PF, AC, AC, AC, JA, JA, AC, AC, AC, JA, TN }, 	 //	 41	 4500
{ LO, AC, AC, JA, SK, AC, AC, AC, JA, KN, AC, AC, AC, SH, KN }, 	 //	 42	 4500
{ LO, AC, AC, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, WN, JA }, 	 //	 43	 4500
{ LO, AC, AC, KN, TN, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC }, 	 //	 44	 4500
{ LO, AC, AC, QN, CR, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 45	 4500
{ LO, AC, AC, JA, ST, AC, AC, AC, SH, AC, AC, AC, AC, TN, KN }, 	 //	 46	 4500
{ LO, AC, AC, JA, KN, AC, AC, AC, SH, KN, AC, AC, AC, TN, KN }, 	 //	 47	 4500
{ LO, AC, AC, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 48	 4500
{ LO, AC, AC, AC, WN, AC, AC, AC, LO, TN, AC, LO, AC, KN, TN }, 	 //	 49	 4500
{ LO, AC, AC, AC, KN, AC, AC, AC, PF, KN, AC, LO, AC, KN, CR }, 	 //	 50	 4500
{ LO, KN, SH, AC, AC, AC, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 51	 4500
{ LO, KN, AC, WN, AC, AC, ST, AC, AC, AC, AC, QN, AC, KN, AC }, 	 //	 52	 4500
{ LO, ST, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, PF, AC, AC }, 	 //	 53	 4500
{ LO, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, WN, LO, AC }, 	 //	 54	 4500
{ LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, CR }, 	 //	 55	 4500
{ LO, TN, AC, WN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN, QN }, 	 //	 56	 4500
{ LO, TN, AC, SK, KN, AC, AC, AC, JA, SK, AC, AC, AC, JA, QN }, 	 //	 57	 4500
{ LO, TN, AC, QN, WN, AC, AC, AC, ST, TN, AC, AC, AC, JA, TN }, 	 //	 58	 4500
{ LO, TN, AC, ST, SK, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN }, 	 //	 59	 4500
{ LO, TN, AC, AC, SK, AC, AC, AC, LO, KN, AC, AC, AC, KN, KN }, 	 //	 60	 4500
{ LO, TN, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, AC }, 	 //	 61	 4500
{ LO, TN, AC, JA, SH, AC, AC, AC, JA, JA, AC, AC, AC, JA, JA }, 	 //	 62	 4500
{ LO, TN, AC, QN, AC, AC, AC, AC, ST, AC, AC, AC, AC, JA, AC }, 	 //	 63	 4500
{ LO, TN, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, SK }, 	 //	 64	 4500
{ LO, AC, AC, WN, AC, AC, AC, AC, QN, SK, AC, AC, AC, QN, KN }, 	 //	 65	 4500
{ LO, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC }, 	 //	 66	 4500
{ LO, AC, AC, AC, KN, AC, AC, AC, KN, KN, AC, AC, PF, QN, KN }, 	 //	 67	 4500
{ LO, AC, AC, SH, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA }, 	 //	 68	 4500
{ LO, AC, AC, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 69	 4500
{ LO, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, SK, JA }, 	 //	 70	 4500
{ LO, AC, AC, AC, KN, AC, AC, AC, PF, QN, AC, AC, WN, AC, PF }, 	 //	 71	 4500
{ LO, AC, AC, QN, QN, AC, AC, AC, KN, KN, AC, PF, AC, AC, AC }, 	 //	 72	 4500
{ LO, AC, AC, AC, KN, AC, AC, AC, LO, QN, AC, PF, AC, KN, PF }, 	 //	 73	 4500
{ LO, AC, AC, AC, KN, AC, AC, AC, PF, SK, AC, PF, WN, KN, QN }, 	 //	 74	 4500
{ LO, AC, AC, PF, AC, AC, PF, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 75	 4500
{ LO, PF, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 76	 4500
{ LO, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 77	 4500
{ LO, KN, AC, PF, AC, AC, KN, AC, AC, LO, AC, SK, AC, AC, AC }, 	 //	 78	 4500
{ LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, WN, PF, AC }, 	 //	 79	 4500
{ LO, KN, AC, AC, LO, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 80	 4500
{ LO, SK, AC, AC, LO, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 81	 4500
{ LO, QN, SH, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 82	 4500
{ LO, KN, AC, AC, AC, AC, AC, AC, PF, KN, AC, SH, AC, AC, QN }, 	 //	 83	 4500
{ AC, AC, AC, WN, ST, AC, SH, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 84	 4500
{ AC, SH, SH, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, WN, JA }, 	 //	 85	 4500
{ AC, SH, SH, QN, JA, AC, AC, AC, SK, TN, AC, AC, AC, JA, AC }, 	 //	 86	 4500
{ AC, SH, SH, SK, KN, AC, AC, AC, JA, QN, AC, AC, AC, JA, PF }, 	 //	 87	 4500
{ AC, SH, SH, AC, TN, AC, AC, AC, KN, ST, AC, AC, AC, QN, AC }, 	 //	 88	 4500
{ AC, SH, SH, ST, QN, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN }, 	 //	 89	 4500
{ AC, SH, SH, PF, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN }, 	 //	 90	 4500
{ AC, SH, SH, KN, JA, AC, AC, AC, SK, JA, AC, AC, AC, QN, JA }, 	 //	 91	 4500
{ AC, SH, TN, JA, AC, AC, AC, AC, JA, KN, AC, AC, AC, JA, QN }, 	 //	 92	 4500
{ AC, SH, TN, KN, CR, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 93	 4500
{ AC, SH, TN, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, CR }, 	 //	 94	 4500
{ AC, AC, SH, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN, AC }, 	 //	 95	 4500
{ AC, AC, SH, SK, AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC }, 	 //	 96	 4500
{ AC, AC, SH, JA, CR, AC, AC, AC, JA, QN, AC, AC, AC, SH, KN }, 	 //	 97	 4500
{ AC, AC, SH, SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, WN }, 	 //	 98	 4500
{ AC, AC, AC, KN, CR, AC, AC, AC, KN, QN, AC, AC, PF, KN, KN }, 	 //	 99	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, AC, PF, QN, KN }, 	 //	 100	 4500
{ AC, AC, AC, WN, PF, AC, AC, AC, QN, JA, AC, AC, PF, QN, TN }, 	 //	 101	 4500
{ AC, AC, AC, SK, AC, AC, AC, AC, JA, LO, AC, AC, PF, JA, AC }, 	 //	 102	 4500
{ AC, AC, AC, QN, KN, AC, AC, AC, KN, KN, AC, AC, PF, AC, KN }, 	 //	 103	 4500
{ AC, AC, AC, QN, KN, AC, AC, AC, KN, KN, AC, AC, PF, AC, CR }, 	 //	 104	 4500
{ AC, AC, TN, WN, SK, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN }, 	 //	 105	 4500
{ AC, AC, TN, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, SH, WN }, 	 //	 106	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, WN, WN, SH }, 	 //	 107	 4500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, WN, SK, AC }, 	 //	 108	 4500
{ AC, AC, AC, SK, TN, AC, AC, AC, JA, TN, AC, AC, WN, JA, ST }, 	 //	 109	 4500
{ AC, AC, AC, TN, SK, AC, AC, AC, TN, QN, AC, AC, WN, WN, QN }, 	 //	 110	 4500
{ AC, AC, AC, TN, JA, AC, AC, AC, WN, JA, AC, AC, WN, AC, WN }, 	 //	 111	 4500
{ AC, AC, AC, ST, SK, AC, AC, AC, JA, QN, AC, AC, WN, TN, QN }, 	 //	 112	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, QN, AC, LO, PF, WN, PF }, 	 //	 113	 4500
{ AC, AC, AC, KN, AC, AC, AC, AC, WN, KN, AC, LO, PF, QN, QN }, 	 //	 114	 4500
{ AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, AC, LO, PF, JA, KN }, 	 //	 115	 4500
{ AC, AC, AC, PF, CR, AC, AC, AC, KN, QN, AC, LO, PF, KN, KN }, 	 //	 116	 4500
{ AC, AC, AC, SK, TN, AC, AC, AC, QN, TN, AC, LO, PF, KN, ST }, 	 //	 117	 4500
{ AC, AC, AC, KN, TN, AC, AC, AC, WN, TN, AC, LO, WN, QN, TN }, 	 //	 118	 4500
{ AC, AC, AC, WN, TN, AC, AC, AC, QN, AC, AC, LO, WN, QN, AC }, 	 //	 119	 4500
{ AC, AC, AC, JA, QN, AC, AC, AC, TN, SH, AC, LO, WN, AC, JA }, 	 //	 120	 4500
{ AC, AC, AC, PF, KN, AC, LO, WN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 121	 4500
{ AC, LO, AC, TN, AC, AC, KN, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 122	 4500
{ AC, KN, SH, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 123	 4500
{ AC, QN, AC, PF, AC, AC, QN, AC, AC, LO, AC, QN, AC, AC, AC }, 	 //	 124	 4500
{ AC, QN, AC, PF, AC, AC, QN, AC, AC, LO, AC, SK, AC, AC, AC }, 	 //	 125	 4500
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, WN, AC, AC }, 	 //	 126	 4500
{ AC, QN, AC, PF, TN, AC, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 127	 4500
{ AC, JA, AC, AC, AC, AC, SH, AC, AC, LO, AC, TN, AC, PF, AC }, 	 //	 128	 4500
{ AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, AC, AC, SK }, 	 //	 129	 4500
{ AC, SH, AC, AC, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 130	 4500
{ AC, TN, AC, AC, AC, AC, WN, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 131	 4500
{ AC, WN, AC, KN, TN, AC, AC, AC, KN, AC, AC, KN, AC, WN, AC }, 	 //	 132	 4500
{ AC, WN, AC, TN, KN, AC, AC, AC, TN, KN, AC, KN, AC, TN, KN }, 	 //	 133	 4500
{ AC, WN, AC, TN, SH, AC, AC, AC, TN, JA, AC, KN, AC, TN, JA }, 	 //	 134	 4500
{ AC, WN, AC, KN, CR, AC, AC, AC, QN, QN, AC, KN, AC, ST, KN }, 	 //	 135	 4500
{ AC, WN, AC, ST, KN, AC, AC, AC, JA, SK, AC, KN, AC, TN, QN }, 	 //	 136	 4500
{ AC, WN, AC, KN, KN, AC, AC, AC, KN, QN, AC, KN, AC, KN, PF }, 	 //	 137	 4500
{ AC, WN, AC, QN, KN, AC, AC, AC, KN, KN, AC, KN, AC, AC, SK }, 	 //	 138	 4500
{ AC, WN, AC, QN, CR, AC, AC, AC, QN, QN, AC, KN, AC, SK, KN }, 	 //	 139	 4500
{ AC, WN, AC, SK, KN, AC, AC, AC, JA, KN, AC, KN, AC, JA, KN }, 	 //	 140	 4500
{ AC, WN, AC, SK, KN, AC, AC, AC, JA, AC, AC, KN, AC, JA, LO }, 	 //	 141	 4500
{ AC, WN, AC, TN, CR, AC, AC, AC, WN, KN, AC, KN, AC, AC, KN }, 	 //	 142	 4500
{ AC, QN, AC, AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, PF, SK }, 	 //	 143	 4500
{ AC, TN, KN, KN, KN, AC, AC, SH, AC, AC, AC, AC, AC, PF, LO }, 	 //	 144	 4500
{ AC, TN, SH, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA }, 	 //	 145	 4500
{ AC, TN, SH, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, SH, WN }, 	 //	 146	 4500
{ AC, TN, SH, AC, SH, AC, AC, AC, KN, JA, AC, AC, AC, QN, JA }, 	 //	 147	 4500
{ AC, TN, SH, QN, TN, AC, AC, AC, ST, ST, AC, AC, AC, JA, AC }, 	 //	 148	 4500
{ AC, TN, TN, WN, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN, LO }, 	 //	 149	 4500
{ AC, TN, TN, JA, PF, AC, AC, AC, JA, JA, AC, AC, AC, SH, TN }, 	 //	 150	 4500
{ AC, TN, TN, JA, AC, AC, AC, AC, SH, SK, AC, AC, AC, TN, KN }, 	 //	 151	 4500
{ AC, TN, TN, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, ST, SK }, 	 //	 152	 4500
{ AC, TN, TN, AC, KN, AC, AC, AC, PF, SK, AC, AC, AC, KN, QN }, 	 //	 153	 4500
{ AC, AC, SH, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, SH, SK }, 	 //	 154	 4500
{ AC, AC, SH, JA, JA, AC, AC, AC, SH, WN, AC, AC, AC, TN, TN }, 	 //	 155	 4500
{ AC, AC, SH, QN, AC, AC, AC, AC, ST, KN, AC, AC, AC, JA, QN }, 	 //	 156	 4500
{ AC, AC, SH, ST, SH, AC, AC, AC, JA, JA, AC, AC, AC, TN, JA }, 	 //	 157	 4500
{ AC, AC, SH, SK, TN, AC, AC, AC, QN, ST, AC, AC, AC, KN, AC }, 	 //	 158	 4500
{ AC, AC, AC, WN, KN, AC, AC, AC, QN, SK, AC, AC, PF, QN, QN }, 	 //	 159	 4500
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN, CR }, 	 //	 160	 4500
{ AC, AC, AC, TN, KN, AC, AC, AC, WN, KN, AC, AC, PF, AC, CR }, 	 //	 161	 4500
{ AC, AC, AC, JA, KN, AC, AC, AC, TN, KN, AC, AC, PF, AC, SK }, 	 //	 162	 4500
{ AC, AC, TN, WN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN }, 	 //	 163	 4500
{ AC, AC, TN, PF, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, WN }, 	 //	 164	 4500
{ AC, AC, TN, PF, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN }, 	 //	 165	 4500
{ AC, AC, TN, SK, KN, AC, AC, AC, QN, QN, AC, AC, AC, KN, PF }, 	 //	 166	 4500
{ AC, AC, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, WN, QN, AC }, 	 //	 167	 4500
{ AC, AC, AC, SH, KN, AC, AC, AC, TN, KN, AC, AC, WN, TN, CR }, 	 //	 168	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, SK, KN, AC, AC, WN, QN, AC }, 	 //	 169	 4500
{ AC, AC, AC, SK, JA, AC, AC, AC, QN, JA, AC, AC, WN, KN, JA }, 	 //	 170	 4500
{ AC, AC, AC, AC, ST, AC, AC, WN, PF, AC, AC, AC, KN, KN, KN }, 	 //	 171	 4500
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, KN, AC, PF, PF, QN, QN }, 	 //	 172	 4500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, KN, AC, PF, WN, KN, QN }, 	 //	 173	 4500
{ AC, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, PF, WN, WN, AC }, 	 //	 174	 4500
{ AC, AC, AC, TN, QN, AC, AC, AC, WN, KN, AC, PF, WN, AC, AC }, 	 //	 175	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, QN, QN, AC, PF, WN, ST, SH }, 	 //	 176	 4500
{ AC, AC, AC, JA, JA, AC, AC, AC, TN, TN, AC, PF, WN, AC, AC }, 	 //	 177	 4500
{ AC, AC, AC, AC, KN, AC, AC, WN, KN, AC, AC, PF, KN, QN, LO }, 	 //	 178	 4500
{ AC, KN, SH, AC, AC, AC, AC, AC, PF, AC, AC, SH, AC, AC, AC }, 	 //	 179	 4500
{ AC, KN, AC, KN, KN, AC, AC, AC, QN, KN, AC, SH, AC, ST, SK }, 	 //	 180	 4500
{ AC, KN, AC, QN, TN, AC, AC, AC, ST, TN, AC, SH, AC, JA, TN }, 	 //	 181	 4500
{ AC, KN, AC, PF, QN, AC, AC, AC, KN, SH, AC, SH, AC, KN, JA }, 	 //	 182	 4500
{ AC, KN, AC, PF, KN, AC, AC, AC, KN, KN, AC, SH, AC, KN, CR }, 	 //	 183	 4500
{ AC, KN, AC, AC, ST, AC, AC, AC, KN, AC, AC, SH, AC, QN, KN }, 	 //	 184	 4500
{ AC, KN, AC, PF, AC, AC, AC, AC, KN, AC, AC, SH, AC, KN, CR }, 	 //	 185	 4500
{ AC, KN, AC, AC, AC, AC, AC, AC, PF, AC, AC, SH, WN, KN, SK }, 	 //	 186	 4500
{ AC, AC, AC, PF, AC, AC, SH, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 187	 4500
{ AC, SH, AC, JA, QN, AC, AC, AC, TN, PF, ST, AC, AC, AC, JA }, 	 //	 188	 4500
{ AC, AC, AC, ST, KN, AC, AC, AC, JA, KN, ST, AC, AC, TN, CR }, 	 //	 189	 4500
{ AC, AC, AC, PF, KN, AC, AC, AC, KN, SK, ST, AC, AC, KN, QN }, 	 //	 190	 4500
{ AC, AC, TN, TN, SH, AC, AC, AC, WN, JA, ST, AC, AC, AC, JA }, 	 //	 191	 4500
{ AC, AC, TN, TN, JA, AC, AC, AC, WN, JA, ST, AC, AC, AC, JA }, 	 //	 192	 4500
{ AC, AC, AC, LO, KN, AC, AC, AC, KN, KN, ST, AC, AC, KN, SK }, 	 //	 193	 4500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, AC, ST, AC, AC, QN, AC }, 	 //	 194	 4500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, QN, ST, AC, AC, QN, KN }, 	 //	 195	 4500
{ AC, AC, AC, JA, SK, AC, AC, AC, JA, QN, ST, AC, AC, JA, QN }, 	 //	 196	 4500
{ AC, AC, AC, QN, KN, AC, AC, AC, ST, AC, ST, AC, AC, JA, LO }, 	 //	 197	 4500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, ST, AC, AC, TN, CR }, 	 //	 198	 4500
{ AC, AC, AC, JA, JA, AC, AC, AC, JA, WN, ST, LO, AC, SH, TN }, 	 //	 199	 4500
{ AC, AC, AC, JA, ST, AC, AC, AC, SH, AC, ST, LO, AC, TN, KN }, 	 //	 200	 4500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, ST, LO, AC, TN, AC }, 	 //	 201	 4500
{ AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, ST, LO, AC, AC, CR }, 	 //	 202	 4500
{ AC, AC, AC, SH, AC, AC, AC, AC, TN, AC, ST, LO, AC, TN, CR }, 	 //	 203	 4500
{ AC, AC, AC, ST, KN, AC, AC, AC, JA, KN, ST, LO, AC, TN, CR }, 	 //	 204	 4500
{ AC, AC, AC, WN, AC, AC, LO, AC, AC, LO, ST, KN, AC, KN, AC }, 	 //	 205	 4500
{ AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 206	 4500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, ST, KN, AC, PF, AC }, 	 //	 207	 4500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, LO, ST, TN, AC, LO, AC }, 	 //	 208	 4500
{ AC, TN, AC, AC, LO, AC, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 209	 4500
{ AC, AC, TN, TN, AC, AC, KN, AC, AC, AC, ST, QN, AC, AC, AC }, 	 //	 210	 4500
{ AC, TN, SH, AC, QN, AC, AC, AC, PF, PF, ST, AC, AC, AC, JA }, 	 //	 211	 4500
{ AC, TN, SH, QN, JA, AC, AC, AC, KN, JA, ST, AC, AC, AC, JA }, 	 //	 212	 4500
{ AC, TN, AC, TN, JA, AC, AC, AC, WN, JA, ST, AC, AC, AC, JA }, 	 //	 213	 4500
{ AC, TN, AC, AC, AC, AC, AC, AC, PF, LO, ST, AC, AC, KN, AC }, 	 //	 214	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, ST, AC, AC, SK, JA }, 	 //	 215	 4500
{ AC, AC, AC, WN, TN, AC, AC, AC, QN, TN, ST, AC, AC, QN, ST }, 	 //	 216	 4500
{ AC, AC, AC, TN, JA, AC, AC, AC, TN, WN, ST, AC, AC, TN, TN }, 	 //	 217	 4500
{ AC, AC, AC, SK, KN, AC, AC, AC, QN, QN, ST, AC, AC, KN, PF }, 	 //	 218	 4500
{ AC, AC, SH, TN, JA, AC, AC, AC, WN, TN, ST, PF, AC, AC, AC }, 	 //	 219	 4500
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, SK, ST, PF, AC, SK, KN }, 	 //	 220	 4500
{ AC, AC, AC, JA, QN, AC, AC, AC, TN, QN, ST, PF, AC, AC, QN }, 	 //	 221	 4500
{ AC, AC, AC, LO, QN, AC, AC, AC, KN, KN, ST, PF, AC, KN, AC }, 	 //	 222	 4500
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, LO, ST, PF, AC, SK, AC }, 	 //	 223	 4500
{ AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, ST, PF, AC, KN, AC }, 	 //	 224	 4500
{ AC, AC, AC, SK, AC, AC, AC, AC, QN, KN, ST, PF, AC, KN, QN }, 	 //	 225	 4500
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, ST, QN, PF, PF, AC }, 	 //	 226	 4500
{ AC, KN, AC, QN, LO, AC, AC, AC, KN, AC, ST, SH, AC, AC, AC }, 	 //	 227	 4500
{ AC, AC, SH, AC, AC, ST, SH, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 228	 4500
{ AC, AC, AC, TN, AC, ST, SH, AC, AC, AC, KN, AC, WN, AC, AC }, 	 //	 229	 4500
{ AC, AC, AC, TN, SK, ST, AC, AC, WN, KN, KN, AC, AC, AC, KN }, 	 //	 230	 4500
{ AC, AC, AC, QN, PF, ST, AC, AC, KN, JA, KN, AC, AC, AC, TN }, 	 //	 231	 4500
{ AC, AC, AC, WN, QN, ST, AC, AC, AC, PF, KN, AC, WN, KN, JA }, 	 //	 232	 4500
{ AC, QN, AC, AC, TN, ST, QN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 233	 4500
{ AC, JA, AC, TN, AC, ST, JA, AC, AC, LO, KN, JA, AC, AC, AC }, 	 //	 234	 4500
{ AC, JA, AC, AC, AC, ST, JA, AC, AC, AC, KN, SH, AC, AC, CR }, 	 //	 235	 4500
{ AC, AC, AC, TN, QN, ST, AC, AC, WN, QN, KN, AC, AC, AC, QN }, 	 //	 236	 4500
{ AC, AC, AC, JA, KN, ST, AC, AC, TN, KN, KN, AC, AC, AC, KN }, 	 //	 237	 4500
{ AC, AC, AC, QN, PF, ST, AC, AC, KN, JA, KN, AC, AC, AC, TN }, 	 //	 238	 4500
{ AC, KN, SH, AC, AC, ST, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 239	 4500
{ AC, KN, AC, AC, AC, ST, SK, AC, AC, AC, KN, QN, PF, LO, AC }, 	 //	 240	 4500
{ AC, SK, AC, AC, AC, ST, QN, AC, AC, AC, KN, KN, WN, PF, AC }, 	 //	 241	 4500
{ AC, QN, AC, AC, AC, ST, KN, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 242	 4500
{ ST, SH, AC, WN, QN, KN, AC, AC, AC, SH, KN, AC, AC, KN, JA }, 	 //	 243	 4500
{ ST, SH, AC, KN, KN, KN, AC, AC, AC, KN, KN, AC, AC, PF, KN }, 	 //	 244	 4500
{ ST, SH, AC, KN, JA, KN, AC, AC, AC, WN, KN, AC, AC, PF, TN }, 	 //	 245	 4500
{ ST, SH, TN, PF, WN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 246	 4500
{ ST, SH, TN, AC, SK, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 247	 4500
{ ST, SH, AC, KN, QN, KN, AC, AC, AC, QN, KN, AC, AC, PF, SH }, 	 //	 248	 4500
{ ST, AC, SH, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 249	 4500
{ ST, AC, AC, AC, AC, KN, LO, WN, AC, AC, KN, KN, KN, LO, AC }, 	 //	 250	 4500
{ ST, AC, AC, AC, KN, KN, LO, WN, PF, KN, KN, KN, KN, KN, KN }, 	 //	 251	 4500
{ ST, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, ST, AC, PF, SK }, 	 //	 252	 4500
{ ST, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, SK }, 	 //	 253	 4500
{ ST, WN, AC, AC, WN, KN, AC, AC, AC, TN, KN, KN, AC, AC, TN }, 	 //	 254	 4500
{ ST, WN, AC, AC, AC, KN, AC, WN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 255	 4500
{ ST, KN, AC, AC, AC, KN, QN, AC, AC, LO, KN, ST, AC, PF, AC }, 	 //	 256	 4500
{ ST, AC, AC, AC, CR, KN, AC, AC, AC, QN, KN, AC, PF, LO, KN }, 	 //	 257	 4500
{ ST, AC, TN, PF, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 258	 4500
{ ST, AC, AC, AC, PF, KN, AC, AC, AC, JA, KN, AC, WN, AC, TN }, 	 //	 259	 4500
{ ST, AC, AC, TN, KN, KN, AC, AC, AC, KN, KN, PF, AC, AC, SK }, 	 //	 260	 4500
{ ST, AC, AC, AC, SH, KN, AC, AC, AC, JA, KN, PF, PF, AC, JA }, 	 //	 261	 4500
{ ST, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, PF, PF, AC, SK }, 	 //	 262	 4500
{ ST, AC, AC, AC, KN, KN, PF, WN, PF, KN, KN, KN, KN, KN, KN }, 	 //	 263	 4500
{ ST, SK, AC, AC, LO, KN, QN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 264	 4500
{ ST, QN, AC, AC, AC, KN, KN, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 265	 4500
{ ST, KN, AC, WN, QN, KN, AC, AC, AC, SH, KN, SH, AC, KN, JA }, 	 //	 266	 4500
{ ST, KN, AC, PF, CR, KN, AC, AC, AC, KN, KN, SH, AC, AC, KN }, 	 //	 267	 4500
{ KN, SH, SH, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 268	 4500
{ KN, SH, TN, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 269	 4500
{ KN, SH, AC, KN, QN, KN, AC, AC, AC, QN, KN, AC, AC, PF, SH }, 	 //	 270	 4500
{ KN, AC, AC, PF, QN, KN, AC, AC, AC, PF, KN, LO, AC, AC, JA }, 	 //	 271	 4500
{ KN, LO, AC, WN, AC, KN, KN, AC, AC, AC, KN, KN, AC, KN, AC }, 	 //	 272	 4500
{ KN, KN, AC, WN, AC, KN, KN, WN, AC, AC, KN, KN, KN, KN, AC }, 	 //	 273	 4500
{ KN, KN, QN, WN, AC, KN, KN, AC, AC, AC, KN, KN, KN, KN, AC }, 	 //	 274	 4500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, ST, PF, AC, AC }, 	 //	 275	 4500
{ KN, QN, TN, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 276	 4500
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SK, WN, AC, AC }, 	 //	 277	 4500
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, LO, KN, JA, AC, PF, AC }, 	 //	 278	 4500
{ KN, WN, AC, KN, KN, KN, AC, AC, AC, KN, KN, KN, AC, PF, KN }, 	 //	 279	 4500
{ KN, AC, AC, AC, SK, KN, KN, KN, KN, QN, KN, QN, QN, QN, QN }, 	 //	 280	 4500
{ KN, ST, TN, TN, AC, KN, JA, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 281	 4500
{ KN, JA, SH, TN, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 282	 4500
{ KN, TN, AC, KN, JA, KN, AC, AC, AC, JA, KN, AC, AC, PF, WN }, 	 //	 283	 4500
{ KN, TN, TN, PF, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 284	 4500
{ KN, PF, AC, PF, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 285	 4500
{ KN, PF, AC, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 286	 4500
{ KN, KN, AC, KN, KN, KN, AC, AC, AC, KN, KN, SH, AC, PF, CR }, 	 //	 287	 4500
{ KN, SH, AC, KN, KN, KN, AC, AC, AC, KN, SK, AC, AC, PF, KN }, 	 //	 288	 4500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, PF, SK, AC, WN, PF, JA }, 	 //	 289	 4500
{ KN, AC, AC, PF, QN, KN, AC, AC, AC, QN, SK, LO, AC, AC, QN }, 	 //	 290	 4500
{ KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK, TN, WN, LO, AC }, 	 //	 291	 4500
{ KN, WN, AC, WN, KN, KN, AC, AC, AC, SK, SK, KN, AC, KN, QN }, 	 //	 292	 4500
{ KN, AC, AC, AC, KN, KN, KN, KN, KN, KN, SK, QN, WN, QN, CR }, 	 //	 293	 4500
{ KN, TN, SH, PF, PF, KN, AC, AC, AC, JA, SK, AC, AC, AC, TN }, 	 //	 294	 4500
{ KN, TN, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, PF, QN }, 	 //	 295	 4500
{ KN, AC, SH, AC, QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, SH }, 	 //	 296	 4500
{ KN, AC, AC, AC, CR, KN, AC, AC, AC, QN, SK, AC, PF, PF, KN }, 	 //	 297	 4500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, SK, AC, WN, LO, KN }, 	 //	 298	 4500
{ KN, AC, AC, KN, KN, KN, AC, AC, AC, KN, SK, PF, AC, PF, KN }, 	 //	 299	 4500
{ KN, KN, AC, AC, PF, KN, AC, AC, AC, JA, SK, SH, AC, AC, TN }, 	 //	 300	 4500
{ KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, PF, AC, QN }, 	 //	 301	 4500
{ KN, AC, AC, TN, SH, SK, AC, AC, AC, JA, QN, LO, AC, AC, JA }, 	 //	 302	 4500
{ KN, AC, AC, TN, SK, SK, AC, AC, AC, KN, QN, LO, AC, AC, KN }, 	 //	 303	 4500
{ KN, LO, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, PF, PF, AC }, 	 //	 304	 4500
{ KN, QN, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN, PF, AC, AC }, 	 //	 305	 4500
{ KN, TN, AC, AC, AC, SK, WN, AC, AC, AC, QN, AC, PF, PF, AC }, 	 //	 306	 4500
{ KN, WN, AC, TN, PF, SK, AC, AC, AC, JA, QN, KN, AC, AC, TN }, 	 //	 307	 4500
{ KN, TN, AC, AC, PF, SK, AC, AC, AC, JA, QN, AC, AC, LO, TN }, 	 //	 308	 4500
{ KN, TN, TN, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 309	 4500
{ KN, AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, PF, PF, AC, KN }, 	 //	 310	 4500
{ KN, AC, AC, TN, QN, SK, AC, AC, AC, QN, QN, PF, AC, AC, SH }, 	 //	 311	 4500
{ KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK, AC, AC, SK }, 	 //	 312	 4500
{ KN, QN, AC, AC, AC, SK, KN, AC, AC, LO, QN, AC, AC, PF, AC }, 	 //	 313	 4500
{ KN, QN, AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, AC, PF, SK }, 	 //	 314	 4500
{ KN, QN, AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 315	 4500
{ KN, KN, SH, PF, QN, SK, AC, AC, AC, KN, QN, SH, AC, AC, AC }, 	 //	 316	 4500
{ KN, KN, AC, AC, SK, SK, AC, AC, AC, QN, QN, SH, AC, AC, QN }, 	 //	 317	 4500
{ KN, KN, AC, TN, KN, SK, AC, AC, AC, SK, QN, SH, AC, AC, QN }, 	 //	 318	 4500
{ SK, AC, AC, AC, LO, QN, SH, AC, AC, AC, QN, AC, AC, LO, AC }, 	 //	 319	 4500
{ SK, SH, TN, PF, CR, QN, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 320	 4500
{ SK, SH, TN, TN, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 321	 4500
{ SK, SH, AC, WN, QN, QN, AC, AC, AC, QN, QN, AC, AC, KN, SH }, 	 //	 322	 4500
{ SK, AC, SH, PF, SK, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 323	 4500
{ SK, AC, SH, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 324	 4500
{ SK, AC, AC, TN, CR, QN, AC, AC, AC, QN, QN, LO, AC, AC, KN }, 	 //	 325	 4500
{ SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, LO, PF, LO, WN }, 	 //	 326	 4500
{ SK, LO, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, CR }, 	 //	 327	 4500
{ SK, KN, SH, TN, AC, QN, ST, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 328	 4500
{ SK, SH, TN, PF, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 329	 4500
{ SK, TN, SH, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 330	 4500
{ SK, WN, AC, AC, KN, QN, AC, AC, AC, KN, QN, KN, AC, PF, KN }, 	 //	 331	 4500
{ SK, WN, TN, AC, QN, QN, AC, AC, AC, KN, QN, KN, AC, AC, AC }, 	 //	 332	 4500
{ SK, WN, AC, AC, AC, QN, AC, AC, AC, SK, QN, KN, WN, AC, KN }, 	 //	 333	 4500
{ SK, QN, AC, AC, AC, QN, ST, AC, AC, AC, QN, JA, AC, LO, CR }, 	 //	 334	 4500
{ SK, ST, AC, TN, LO, QN, JA, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 335	 4500
{ SK, ST, AC, AC, AC, QN, JA, AC, AC, AC, QN, TN, WN, PF, AC }, 	 //	 336	 4500
{ SK, TN, SH, AC, PF, QN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 337	 4500
{ SK, AC, SH, AC, KN, QN, AC, AC, AC, SK, QN, AC, AC, AC, QN }, 	 //	 338	 4500
{ SK, AC, AC, WN, PF, QN, AC, AC, AC, JA, QN, AC, AC, KN, TN }, 	 //	 339	 4500
{ SK, AC, TN, AC, SK, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 340	 4500
{ SK, AC, AC, KN, SH, QN, AC, AC, AC, JA, QN, AC, AC, PF, JA }, 	 //	 341	 4500
{ SK, AC, AC, KN, SK, QN, AC, AC, AC, QN, QN, PF, AC, PF, QN }, 	 //	 342	 4500
{ SK, AC, AC, AC, JA, QN, PF, AC, AC, TN, QN, KN, AC, AC, AC }, 	 //	 343	 4500
{ SK, KN, AC, AC, AC, QN, AC, AC, AC, KN, QN, SH, PF, AC, QN }, 	 //	 344	 4500
{ QN, SH, SH, AC, WN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 345	 4500
{ QN, SH, TN, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 346	 4500
{ QN, SH, AC, AC, SK, QN, AC, AC, AC, QN, QN, AC, AC, LO, QN }, 	 //	 347	 4500
{ QN, AC, TN, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 348	 4500
{ QN, AC, AC, AC, QN, QN, AC, AC, AC, QN, QN, AC, WN, LO, SH }, 	 //	 349	 4500
{ QN, AC, TN, AC, QN, QN, AC, AC, AC, KN, QN, LO, AC, AC, AC }, 	 //	 350	 4500
{ QN, KN, AC, PF, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 351	 4500
{ QN, QN, TN, PF, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 352	 4500
{ QN, WN, AC, AC, TN, QN, AC, AC, AC, TN, QN, KN, AC, LO, TN }, 	 //	 353	 4500
{ QN, WN, AC, WN, SH, QN, AC, AC, AC, JA, QN, KN, AC, KN, JA }, 	 //	 354	 4500
{ QN, WN, AC, PF, KN, QN, AC, AC, AC, KN, QN, KN, AC, AC, SK }, 	 //	 355	 4500
{ QN, WN, AC, AC, KN, QN, AC, AC, AC, SK, QN, KN, AC, AC, QN }, 	 //	 356	 4500
{ QN, WN, AC, KN, KN, QN, AC, AC, AC, KN, QN, KN, AC, PF, KN }, 	 //	 357	 4500
{ QN, WN, AC, KN, CR, QN, AC, AC, AC, QN, QN, KN, AC, PF, KN }, 	 //	 358	 4500
{ QN, ST, TN, AC, AC, QN, JA, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 359	 4500
{ QN, TN, AC, AC, PF, QN, AC, AC, AC, JA, QN, AC, AC, LO, TN }, 	 //	 360	 4500
{ QN, AC, SH, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 361	 4500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, PF, LO, KN }, 	 //	 362	 4500
{ QN, AC, AC, TN, LO, QN, PF, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 363	 4500
{ QN, SK, AC, TN, AC, QN, QN, AC, AC, LO, QN, KN, AC, AC, AC }, 	 //	 364	 4500
{ QN, KN, AC, AC, QN, QN, AC, AC, AC, SH, QN, SH, AC, PF, JA }, 	 //	 365	 4500
{ QN, KN, AC, KN, WN, QN, AC, AC, AC, TN, QN, SH, AC, PF, TN }, 	 //	 366	 4500
{ QN, AC, AC, AC, KN, QN, SH, AC, AC, AC, SH, AC, AC, AC, LO }, 	 //	 367	 4500
{ QN, SH, SH, PF, QN, QN, AC, AC, AC, QN, SH, AC, AC, AC, QN }, 	 //	 368	 4500
{ QN, SH, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, LO, KN }, 	 //	 369	 4500
{ QN, AC, SH, PF, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, ST }, 	 //	 370	 4500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, LO, PF, AC, KN }, 	 //	 371	 4500
{ QN, AC, AC, WN, TN, QN, AC, AC, AC, TN, SH, LO, AC, KN, TN }, 	 //	 372	 4500
{ QN, QN, SH, AC, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC }, 	 //	 373	 4500
{ QN, SK, AC, KN, AC, QN, JA, AC, AC, AC, SH, JA, AC, PF, AC }, 	 //	 374	 4500
{ QN, JA, AC, AC, AC, QN, SH, AC, AC, AC, SH, TN, AC, AC, CR }, 	 //	 375	 4500
{ QN, WN, AC, WN, QN, QN, AC, AC, AC, PF, SH, KN, AC, KN, JA }, 	 //	 376	 4500
{ QN, AC, SH, AC, AC, QN, KN, AC, AC, AC, SH, QN, AC, AC, AC }, 	 //	 377	 4500
{ QN, KN, TN, AC, AC, QN, QN, AC, AC, AC, SH, ST, AC, AC, AC }, 	 //	 378	 4500
{ QN, JA, AC, AC, AC, QN, TN, AC, AC, AC, SH, AC, PF, AC, AC }, 	 //	 379	 4500
{ QN, TN, AC, KN, JA, QN, AC, AC, AC, JA, SH, AC, AC, PF, JA }, 	 //	 380	 4500
{ QN, TN, AC, AC, WN, QN, AC, AC, AC, TN, SH, AC, AC, PF, TN }, 	 //	 381	 4500
{ QN, AC, TN, AC, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 382	 4500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, WN, SH, AC, WN, LO, TN }, 	 //	 383	 4500
{ QN, AC, AC, WN, AC, QN, PF, AC, AC, AC, SH, KN, AC, KN, AC }, 	 //	 384	 4500
{ QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SH, SK, AC, LO, SK }, 	 //	 385	 4500
{ QN, SK, TN, AC, AC, QN, QN, AC, AC, AC, SH, KN, AC, AC, AC }, 	 //	 386	 4500
{ QN, KN, AC, PF, SK, QN, AC, AC, AC, QN, SH, SH, AC, AC, QN }, 	 //	 387	 4500
{ QN, KN, AC, WN, JA, QN, AC, AC, AC, JA, SH, SH, AC, KN, WN }, 	 //	 388	 4500
{ QN, AC, SH, PF, CR, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 389	 4500
{ QN, AC, SH, PF, AC, SH, LO, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 390	 4500
{ QN, KN, AC, AC, LO, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 391	 4500
{ QN, KN, AC, AC, AC, SH, KN, AC, AC, LO, JA, KN, AC, LO, AC }, 	 //	 392	 4500
{ QN, ST, AC, KN, AC, SH, QN, AC, AC, AC, JA, QN, AC, PF, AC }, 	 //	 393	 4500
{ QN, JA, AC, AC, AC, SH, JA, AC, AC, AC, JA, JA, AC, PF, CR }, 	 //	 394	 4500
{ QN, QN, AC, TN, AC, SH, ST, AC, AC, LO, JA, JA, AC, AC, AC }, 	 //	 395	 4500
{ QN, JA, TN, TN, AC, SH, TN, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 396	 4500
{ QN, AC, AC, AC, JA, SH, AC, AC, AC, WN, JA, PF, PF, AC, TN }, 	 //	 397	 4500
{ QN, PF, SH, AC, AC, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 398	 4500
{ QN, KN, AC, AC, KN, SH, AC, AC, AC, QN, JA, SH, AC, AC, PF }, 	 //	 399	 4500
{ SH, AC, AC, WN, SK, JA, AC, AC, AC, QN, JA, AC, AC, KN, QN }, 	 //	 400	 4500
{ SH, AC, AC, AC, TN, JA, LO, AC, AC, AC, JA, KN, PF, LO, AC }, 	 //	 401	 4500
{ SH, AC, AC, TN, AC, JA, LO, AC, AC, LO, JA, KN, AC, AC, AC }, 	 //	 402	 4500
{ SH, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, SK }, 	 //	 403	 4500
{ SH, QN, SH, PF, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC }, 	 //	 404	 4500
{ SH, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA, JA, WN, AC, AC }, 	 //	 405	 4500
{ SH, JA, TN, AC, AC, JA, SH, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 406	 4500
{ SH, WN, AC, TN, SK, JA, AC, AC, AC, KN, JA, KN, AC, AC, KN }, 	 //	 407	 4500
{ SH, AC, AC, AC, QN, JA, KN, AC, AC, KN, JA, QN, AC, AC, AC }, 	 //	 408	 4500
{ SH, QN, SH, AC, AC, JA, ST, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 409	 4500
{ SH, QN, AC, AC, AC, JA, ST, AC, AC, AC, JA, JA, PF, AC, AC }, 	 //	 410	 4500
{ SH, JA, AC, PF, AC, JA, TN, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 411	 4500
{ SH, TN, AC, WN, KN, JA, AC, AC, AC, KN, JA, AC, AC, KN, KN }, 	 //	 412	 4500
{ SH, AC, SH, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 413	 4500
{ SH, AC, SH, AC, WN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 414	 4500
{ SH, AC, AC, KN, WN, JA, AC, AC, AC, TN, JA, AC, AC, PF, TN }, 	 //	 415	 4500
{ SH, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, PF, WN, PF, SH }, 	 //	 416	 4500
{ SH, PF, AC, KN, AC, JA, KN, AC, AC, AC, JA, KN, AC, PF, AC }, 	 //	 417	 4500
{ SH, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, SK, WN, AC, AC }, 	 //	 418	 4500
{ SH, KN, TN, AC, JA, JA, AC, AC, AC, TN, JA, SH, AC, AC, AC }, 	 //	 419	 4500
{ SH, KN, AC, WN, CR, JA, AC, AC, AC, KN, JA, SH, AC, KN, KN }, 	 //	 420	 4500
{ SH, KN, AC, AC, JA, JA, AC, AC, AC, JA, JA, SH, AC, PF, WN }, 	 //	 421	 4500
{ JA, SH, TN, AC, PF, JA, AC, AC, AC, JA, JA, AC, AC, AC, TN }, 	 //	 422	 4500
{ JA, SH, AC, WN, PF, JA, AC, AC, AC, JA, JA, AC, AC, KN, TN }, 	 //	 423	 4500
{ JA, AC, TN, TN, CR, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 424	 4500
{ JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, LO, CR }, 	 //	 425	 4500
{ JA, QN, AC, AC, TN, JA, SK, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 426	 4500
{ JA, AC, AC, AC, TN, JA, KN, AC, AC, ST, JA, QN, AC, AC, AC }, 	 //	 427	 4500
{ JA, KN, AC, AC, AC, JA, QN, AC, AC, LO, JA, ST, AC, PF, AC }, 	 //	 428	 4500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, PF, PF, CR }, 	 //	 429	 4500
{ JA, AC, TN, PF, QN, JA, AC, AC, AC, PF, JA, AC, AC, AC, JA }, 	 //	 430	 4500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, WN, LO, KN }, 	 //	 431	 4500
{ JA, AC, AC, KN, QN, JA, AC, AC, AC, SH, JA, PF, AC, PF, JA }, 	 //	 432	 4500
{ JA, AC, AC, AC, PF, JA, AC, AC, AC, JA, JA, PF, WN, AC, TN }, 	 //	 433	 4500
{ JA, AC, AC, AC, TN, JA, PF, AC, AC, AC, JA, KN, WN, AC, AC }, 	 //	 434	 4500
{ JA, KN, AC, AC, TN, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 435	 4500
{ JA, KN, AC, KN, AC, JA, SK, AC, AC, AC, JA, QN, AC, PF, AC }, 	 //	 436	 4500
{ JA, KN, AC, AC, CR, JA, AC, AC, AC, KN, JA, SH, AC, AC, KN }, 	 //	 437	 4500
{ JA, AC, SH, PF, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, CR }, 	 //	 438	 4500
{ JA, AC, SH, AC, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, CR }, 	 //	 439	 4500
{ JA, AC, AC, WN, CR, JA, AC, AC, AC, QN, WN, AC, AC, KN, KN }, 	 //	 440	 4500
{ JA, AC, AC, AC, PF, JA, AC, AC, AC, JA, WN, LO, WN, AC, TN }, 	 //	 441	 4500
{ JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN, ST, AC, AC, CR }, 	 //	 442	 4500
{ JA, ST, AC, TN, LO, JA, QN, AC, AC, AC, WN, QN, AC, AC, AC }, 	 //	 443	 4500
{ JA, QN, SH, AC, AC, JA, SK, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 444	 4500
{ JA, SK, AC, PF, AC, JA, JA, AC, AC, LO, WN, JA, AC, AC, AC }, 	 //	 445	 4500
{ JA, JA, TN, PF, AC, JA, SH, AC, AC, AC, WN, TN, AC, AC, AC }, 	 //	 446	 4500
{ JA, WN, AC, AC, SK, JA, AC, AC, AC, KN, WN, KN, AC, AC, KN }, 	 //	 447	 4500
{ JA, WN, AC, AC, KN, JA, AC, AC, AC, KN, WN, KN, AC, LO, KN }, 	 //	 448	 4500
{ JA, QN, AC, AC, AC, JA, ST, AC, AC, AC, WN, JA, PF, LO, AC }, 	 //	 449	 4500
{ JA, ST, SH, AC, AC, JA, JA, AC, AC, AC, WN, TN, AC, AC, AC }, 	 //	 450	 4500
{ JA, AC, SH, PF, QN, JA, AC, AC, AC, KN, WN, PF, AC, AC, AC }, 	 //	 451	 4500
{ JA, AC, AC, PF, QN, JA, AC, AC, AC, SH, WN, PF, AC, AC, JA }, 	 //	 452	 4500
{ JA, QN, AC, AC, AC, JA, KN, AC, AC, AC, WN, AC, PF, LO, AC }, 	 //	 453	 4500
{ JA, KN, AC, AC, JA, JA, AC, AC, AC, WN, WN, SH, AC, LO, TN }, 	 //	 454	 4500
{ JA, SH, AC, AC, AC, WN, AC, AC, AC, SK, TN, AC, PF, LO, KN }, 	 //	 455	 4500
{ JA, AC, SH, AC, QN, WN, AC, AC, AC, SH, TN, AC, AC, AC, JA }, 	 //	 456	 4500
{ JA, AC, AC, WN, QN, WN, AC, AC, AC, SH, TN, AC, AC, KN, JA }, 	 //	 457	 4500
{ JA, AC, AC, AC, KN, WN, AC, AC, AC, SK, TN, AC, WN, PF, QN }, 	 //	 458	 4500
{ JA, AC, AC, KN, QN, WN, AC, AC, AC, QN, TN, LO, AC, PF, QN }, 	 //	 459	 4500
{ JA, AC, AC, TN, QN, WN, AC, AC, AC, SH, TN, LO, AC, AC, JA }, 	 //	 460	 4500
{ JA, LO, SH, PF, AC, WN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 461	 4500
{ JA, KN, AC, PF, TN, WN, KN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 462	 4500
{ JA, QN, TN, AC, AC, WN, SK, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 463	 4500
{ JA, JA, AC, AC, AC, WN, SH, AC, AC, AC, TN, TN, WN, AC, AC }, 	 //	 464	 4500
{ JA, TN, SH, TN, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 465	 4500
{ JA, WN, AC, PF, CR, WN, AC, AC, AC, KN, TN, KN, AC, AC, KN }, 	 //	 466	 4500
{ JA, WN, AC, AC, PF, WN, AC, AC, AC, JA, TN, KN, AC, AC, TN }, 	 //	 467	 4500
{ JA, ST, TN, PF, AC, WN, JA, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 468	 4500
{ JA, TN, SH, PF, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 469	 4500
{ JA, AC, TN, AC, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 470	 4500
{ JA, AC, AC, PF, KN, WN, AC, AC, AC, SK, TN, PF, AC, AC, QN }, 	 //	 471	 4500
{ JA, AC, AC, TN, QN, WN, AC, AC, AC, QN, TN, PF, AC, AC, SH }, 	 //	 472	 4500
{ JA, KN, SH, AC, AC, WN, SK, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 473	 4500
{ JA, KN, AC, AC, KN, WN, AC, AC, AC, KN, TN, SH, AC, AC, CR }, 	 //	 474	 4500
{ WN, AC, AC, PF, AC, TN, SH, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 475	 4500
{ WN, AC, AC, PF, KN, TN, AC, AC, AC, SK, TN, LO, AC, AC, QN }, 	 //	 476	 4500
{ WN, AC, AC, PF, TN, TN, LO, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 477	 4500
{ WN, LO, AC, AC, TN, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 478	 4500
{ WN, JA, AC, AC, AC, TN, SH, AC, AC, LO, TN, TN, AC, LO, AC }, 	 //	 479	 4500
{ WN, TN, AC, AC, AC, TN, WN, AC, AC, AC, TN, AC, AC, LO, CR }, 	 //	 480	 4500
{ WN, TN, AC, AC, AC, TN, WN, AC, AC, LO, TN, AC, AC, PF, AC }, 	 //	 481	 4500
{ WN, KN, AC, AC, TN, TN, QN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 482	 4500
{ WN, TN, SH, PF, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 483	 4500
{ WN, TN, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, PF, KN }, 	 //	 484	 4500
{ WN, AC, TN, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 485	 4500
{ WN, AC, AC, KN, SK, TN, AC, AC, AC, QN, TN, AC, AC, PF, QN }, 	 //	 486	 4500
{ WN, AC, AC, TN, SK, TN, AC, AC, AC, KN, TN, PF, AC, AC, KN }, 	 //	 487	 4500
{ WN, PF, AC, PF, LO, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 488	 4500
{ WN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, SK, AC, PF, CR }, 	 //	 489	 4500
{ WN, QN, AC, TN, AC, TN, KN, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 490	 4500
{ WN, KN, AC, AC, CR, TN, AC, AC, AC, QN, TN, SH, AC, AC, KN }, 	 //	 491	 4500
{ TN, SH, TN, TN, SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 492	 4500
{ TN, AC, SH, AC, CR, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN }, 	 //	 493	 4500
{ TN, AC, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, WN, AC, TN }, 	 //	 494	 4500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, WN, AC, CR }, 	 //	 495	 4500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, QN, TN, LO, PF, AC, PF }, 	 //	 496	 4500
{ TN, AC, AC, WN, QN, TN, AC, AC, AC, QN, TN, LO, AC, KN, QN }, 	 //	 497	 4500
{ TN, KN, AC, WN, AC, TN, KN, AC, AC, AC, TN, KN, AC, KN, AC }, 	 //	 498	 4500
{ TN, KN, AC, AC, LO, TN, ST, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 499	 4500
{ TN, KN, TN, PF, AC, TN, ST, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 500	 4500
{ TN, SK, AC, AC, AC, TN, JA, AC, AC, LO, TN, JA, AC, PF, AC }, 	 //	 501	 4500
{ TN, TN, AC, WN, AC, TN, WN, AC, AC, AC, TN, AC, AC, KN, AC }, 	 //	 502	 4500
{ TN, WN, AC, TN, SH, TN, AC, AC, AC, JA, TN, KN, AC, AC, JA }, 	 //	 503	 4500
{ TN, WN, AC, KN, PF, TN, AC, AC, AC, JA, TN, KN, AC, PF, TN }, 	 //	 504	 4500
{ TN, WN, AC, AC, KN, TN, AC, AC, AC, KN, TN, KN, AC, PF, KN }, 	 //	 505	 4500
{ TN, QN, AC, TN, LO, TN, ST, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 506	 4500
{ TN, QN, AC, AC, AC, TN, ST, AC, AC, LO, TN, JA, AC, PF, AC }, 	 //	 507	 4500
{ TN, JA, AC, AC, AC, TN, TN, AC, AC, AC, TN, AC, WN, AC, AC }, 	 //	 508	 4500
{ TN, AC, SH, PF, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 509	 4500
{ TN, AC, TN, TN, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA }, 	 //	 510	 4500
{ TN, AC, AC, AC, LO, TN, PF, AC, AC, AC, TN, KN, WN, PF, AC }, 	 //	 511	 4500
{ TN, QN, AC, TN, AC, TN, KN, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 512	 4500
{ TN, KN, AC, PF, SH, TN, AC, AC, AC, JA, TN, SH, AC, AC, JA }, 	 //	 513	 4500
{ TN, SH, AC, AC, QN, TN, AC, AC, AC, PF, ST, AC, AC, PF, JA }, 	 //	 514	 4500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, QN, ST, AC, PF, AC, SH }, 	 //	 515	 4500
{ TN, AC, TN, TN, CR, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 516	 4500
{ TN, AC, AC, AC, CR, TN, AC, AC, AC, QN, ST, AC, WN, LO, KN }, 	 //	 517	 4500
{ TN, AC, TN, AC, TN, TN, AC, AC, AC, ST, ST, LO, AC, AC, AC }, 	 //	 518	 4500
{ TN, KN, TN, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 519	 4500
{ TN, QN, AC, KN, AC, TN, QN, AC, AC, AC, ST, QN, AC, PF, AC }, 	 //	 520	 4500
{ TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST, SH, AC, AC, CR }, 	 //	 521	 4500
{ TN, AC, TN, PF, AC, TN, KN, AC, AC, AC, ST, QN, AC, AC, AC }, 	 //	 522	 4500
{ TN, KN, AC, WN, AC, TN, QN, AC, AC, AC, ST, ST, AC, KN, AC }, 	 //	 523	 4500
{ TN, JA, AC, PF, AC, TN, TN, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 524	 4500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, QN, ST, AC, WN, LO, QN }, 	 //	 525	 4500
{ TN, AC, AC, TN, KN, TN, AC, AC, AC, KN, ST, PF, AC, AC, CR }, 	 //	 526	 4500
{ TN, AC, SH, AC, AC, TN, PF, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 527	 4500
{ TN, AC, TN, AC, AC, TN, PF, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 528	 4500
{ TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, LO, CR }, 	 //	 529	 4500
{ TN, SK, AC, PF, AC, TN, QN, AC, AC, LO, ST, KN, AC, AC, AC }, 	 //	 530	 4500
{ TN, AC, SH, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 531	 4500
{ TN, AC, SH, AC, JA, ST, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 532	 4500
{ TN, AC, AC, AC, SH, ST, AC, AC, LO, JA, AC, AC, AC, KN, JA }, 	 //	 533	 4500
{ TN, AC, AC, AC, TN, ST, AC, AC, PF, TN, AC, AC, AC, KN, ST }, 	 //	 534	 4500
{ TN, KN, AC, WN, AC, ST, KN, AC, AC, AC, AC, ST, AC, KN, AC }, 	 //	 535	 4500
{ TN, QN, AC, AC, AC, ST, QN, AC, AC, AC, AC, QN, WN, AC, AC }, 	 //	 536	 4500
{ TN, QN, AC, AC, AC, ST, QN, AC, AC, LO, AC, SK, AC, LO, AC }, 	 //	 537	 4500
{ TN, QN, AC, AC, AC, ST, SK, AC, AC, LO, AC, JA, AC, PF, AC }, 	 //	 538	 4500
{ TN, QN, AC, TN, AC, ST, SK, AC, AC, LO, AC, JA, AC, AC, AC }, 	 //	 539	 4500
{ TN, TN, SH, KN, QN, ST, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 540	 4500
{ TN, TN, AC, AC, AC, ST, AC, AC, PF, AC, AC, AC, AC, KN, SK }, 	 //	 541	 4500
{ TN, AC, SH, WN, SK, ST, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 542	 4500
{ TN, AC, TN, WN, CR, ST, AC, AC, AC, QN, AC, AC, AC, KN, KN }, 	 //	 543	 4500
{ TN, AC, AC, AC, TN, ST, AC, AC, KN, AC, AC, AC, AC, QN, AC }, 	 //	 544	 4500
{ TN, AC, AC, PF, LO, ST, PF, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 545	 4500
{ TN, AC, AC, AC, LO, ST, PF, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 546	 4500
{ ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN, AC, AC, SK }, 	 //	 547	 4500
{ ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN, WN, AC, AC }, 	 //	 548	 4500
{ ST, TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN, AC, LO, SK }, 	 //	 549	 4500
{ ST, TN, AC, TN, TN, AC, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 550	 4500
{ ST, TN, AC, AC, AC, AC, TN, AC, AC, LO, KN, WN, AC, LO, AC }, 	 //	 551	 4500
{ ST, WN, ST, AC, KN, AC, AC, AC, LO, KN, KN, KN, KN, KN, KN }, 	 //	 552	 4500
{ ST, AC, AC, KN, AC, AC, KN, AC, AC, AC, KN, QN, AC, PF, AC }, 	 //	 553	 4500
{ ST, KN, AC, PF, TN, AC, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 554	 4500
{ ST, AC, AC, AC, LO, AC, PF, AC, AC, AC, KN, KN, WN, LO, AC }, 	 //	 555	 4500
{ ST, AC, AC, AC, TN, AC, PF, AC, AC, AC, KN, KN, WN, LO, AC }, 	 //	 556	 4500
{ AC, AC, TN, AC, AC, KN, SH, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 557	 4500
{ AC, AC, AC, KN, AC, KN, LO, AC, AC, AC, QN, KN, WN, PF, AC }, 	 //	 558	 4500
{ AC, QN, AC, TN, TN, KN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 559	 4500
{ AC, KN, AC, AC, AC, KN, QN, AC, AC, AC, QN, ST, PF, AC, AC }, 	 //	 560	 4500
{ AC, KN, TN, AC, AC, KN, QN, AC, AC, AC, QN, ST, AC, AC, AC }, 	 //	 561	 4500
{ AC, QN, TN, AC, AC, KN, ST, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 562	 4500
{ AC, PF, AC, AC, LO, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 563	 4500
{ AC, PF, AC, WN, AC, KN, KN, AC, AC, AC, QN, KN, AC, KN, AC }, 	 //	 564	 4500
{ AC, KN, AC, AC, AC, KN, AC, AC, AC, KN, QN, SH, WN, PF, QN }, 	 //	 565	 4500
{ KN, AC, SH, AC, JA, QN, AC, AC, AC, JA, PF, AC, AC, AC, JA }, 	 //	 566	 4500
{ KN, AC, TN, AC, KN, QN, AC, AC, AC, SK, PF, AC, AC, AC, QN }, 	 //	 567	 4500
{ KN, AC, AC, KN, QN, QN, AC, AC, AC, QN, PF, LO, AC, PF, QN }, 	 //	 568	 4500
{ KN, AC, AC, AC, TN, QN, LO, AC, AC, AC, PF, KN, WN, LO, AC }, 	 //	 569	 4500
{ KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF, ST, AC, LO, CR }, 	 //	 570	 4500
{ KN, QN, QN, QN, QN, QN, QN, QN, QN, QN, PF, SK, QN, SK, QN }, 	 //	 571	 4500
{ KN, JA, AC, AC, AC, QN, JA, AC, AC, AC, PF, SH, WN, AC, AC }, 	 //	 572	 4500
{ KN, SH, AC, AC, AC, QN, TN, AC, AC, AC, PF, TN, AC, LO, CR }, 	 //	 573	 4500
{ KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF, TN, AC, AC, SK }, 	 //	 574	 4500
{ KN, TN, TN, AC, AC, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC }, 	 //	 575	 4500
{ KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF, WN, AC, PF, SK }, 	 //	 576	 4500
{ KN, TN, AC, PF, AC, QN, WN, AC, AC, AC, PF, AC, AC, AC, CR }, 	 //	 577	 4500
{ KN, ST, AC, PF, TN, QN, JA, AC, AC, AC, PF, TN, AC, AC, AC }, 	 //	 578	 4500
{ KN, JA, TN, AC, AC, QN, TN, AC, AC, AC, PF, AC, AC, AC, CR }, 	 //	 579	 4500
{ KN, AC, AC, AC, KN, QN, AC, AC, AC, SK, PF, AC, PF, LO, QN }, 	 //	 580	 4500
{ KN, AC, TN, AC, SK, QN, AC, AC, AC, KN, PF, AC, AC, AC, KN }, 	 //	 581	 4500
{ KN, AC, AC, AC, TN, QN, PF, AC, AC, ST, PF, KN, AC, AC, AC }, 	 //	 582	 4500
{ KN, AC, AC, AC, TN, QN, PF, AC, AC, AC, PF, KN, WN, LO, AC }, 	 //	 583	 4500
{ KN, PF, TN, AC, AC, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 584	 4500
{ KN, KN, AC, AC, TN, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 585	 4500
{ KN, KN, AC, WN, KN, QN, AC, AC, AC, KN, PF, SH, AC, KN, KN }, 	 //	 586	 4500
{ KN, KN, AC, AC, KN, QN, AC, AC, AC, KN, PF, SH, AC, AC, KN }, 	 //	 587	 4500
{ KN, KN, AC, KN, JA, QN, AC, AC, AC, JA, PF, SH, AC, PF, JA }, 	 //	 588	 4500
{ QN, SH, AC, AC, AC, PF, AC, AC, AC, SK, JA, AC, PF, LO, KN }, 	 //	 589	 4500
{ QN, AC, SH, TN, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 590	 4500
{ QN, AC, AC, TN, KN, PF, AC, AC, AC, QN, JA, LO, AC, AC, PF }, 	 //	 591	 4500
{ QN, AC, AC, AC, JA, PF, AC, AC, AC, WN, JA, LO, PF, AC, TN }, 	 //	 592	 4500
{ QN, AC, AC, AC, QN, PF, AC, AC, AC, SH, JA, LO, WN, PF, JA }, 	 //	 593	 4500
{ QN, KN, AC, AC, LO, PF, ST, AC, AC, AC, JA, QN, AC, AC, AC }, 	 //	 594	 4500
{ QN, ST, AC, AC, AC, PF, QN, AC, AC, AC, JA, QN, AC, PF, CR }, 	 //	 595	 4500
{ QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA, QN, AC, AC, SK }, 	 //	 596	 4500
{ QN, SK, AC, AC, AC, PF, JA, AC, AC, AC, JA, JA, PF, AC, AC }, 	 //	 597	 4500
{ QN, TN, AC, AC, AC, PF, TN, AC, AC, AC, JA, WN, AC, AC, SK }, 	 //	 598	 4500
{ QN, TN, AC, PF, AC, PF, WN, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 599	 4500
{ QN, WN, AC, AC, QN, PF, AC, AC, AC, SH, JA, KN, AC, LO, JA }, 	 //	 600	 4500
{ QN, WN, AC, KN, QN, PF, AC, AC, AC, QN, JA, KN, AC, PF, SH }, 	 //	 601	 4500
{ QN, KN, AC, AC, AC, PF, QN, AC, AC, AC, JA, ST, WN, AC, AC }, 	 //	 602	 4500
{ QN, QN, AC, TN, TN, PF, ST, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 603	 4500
{ QN, ST, AC, KN, AC, PF, JA, AC, AC, AC, JA, TN, AC, PF, AC }, 	 //	 604	 4500
{ QN, ST, AC, WN, AC, PF, JA, AC, AC, AC, JA, TN, AC, KN, AC }, 	 //	 605	 4500
{ QN, JA, AC, AC, AC, PF, TN, AC, AC, AC, JA, AC, PF, LO, AC }, 	 //	 606	 4500
{ QN, TN, TN, AC, KN, PF, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 607	 4500
{ QN, AC, SH, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 608	 4500
{ QN, KN, AC, AC, AC, PF, SK, AC, AC, AC, JA, QN, AC, PF, CR }, 	 //	 609	 4500
{ QN, KN, AC, AC, KN, PF, AC, AC, AC, QN, JA, SH, AC, AC, PF }, 	 //	 610	 4500
{ QN, KN, AC, AC, KN, PF, AC, AC, AC, KN, JA, SH, AC, LO, CR }, 	 //	 611	 4500
{ QN, KN, AC, WN, SH, PF, AC, AC, AC, JA, JA, SH, AC, KN, JA }, 	 //	 612	 4500
{ PF, SH, TN, TN, SK, JA, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 613	 4500
{ PF, SH, TN, AC, CR, JA, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 614	 4500
{ PF, SH, AC, AC, AC, JA, AC, AC, AC, SK, TN, AC, WN, AC, KN }, 	 //	 615	 4500
{ PF, AC, AC, AC, CR, JA, AC, AC, AC, KN, TN, AC, PF, AC, KN }, 	 //	 616	 4500
{ PF, AC, TN, PF, JA, JA, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 617	 4500
{ PF, AC, TN, AC, JA, JA, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 618	 4500
{ PF, AC, SH, TN, JA, JA, AC, AC, AC, TN, TN, LO, AC, AC, AC }, 	 //	 619	 4500
{ PF, AC, AC, TN, PF, JA, AC, AC, AC, JA, TN, LO, AC, AC, TN }, 	 //	 620	 4500
{ PF, AC, AC, AC, JA, JA, LO, AC, AC, TN, TN, KN, AC, AC, AC }, 	 //	 621	 4500
{ PF, JA, SH, AC, AC, JA, SH, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 622	 4500
{ PF, SH, AC, PF, LO, JA, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 623	 4500
{ PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN, TN, PF, AC, AC }, 	 //	 624	 4500
{ PF, WN, AC, AC, KN, JA, AC, AC, AC, QN, TN, KN, AC, LO, PF }, 	 //	 625	 4500
{ PF, WN, AC, AC, PF, JA, AC, AC, AC, JA, TN, KN, AC, LO, TN }, 	 //	 626	 4500
{ PF, AC, TN, TN, AC, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 627	 4500
{ PF, TN, SH, AC, CR, JA, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 628	 4500
{ PF, AC, AC, WN, QN, JA, AC, AC, AC, QN, TN, AC, AC, KN, SH }, 	 //	 629	 4500
{ PF, AC, AC, TN, CR, JA, AC, AC, AC, KN, TN, PF, AC, AC, KN }, 	 //	 630	 4500
{ PF, KN, AC, AC, TN, JA, KN, AC, AC, AC, TN, SK, AC, AC, AC }, 	 //	 631	 4500
{ PF, KN, AC, WN, AC, JA, SK, AC, AC, AC, TN, QN, AC, KN, AC }, 	 //	 632	 4500
{ PF, KN, AC, TN, TN, JA, AC, AC, AC, TN, TN, SH, AC, AC, TN }, 	 //	 633	 4500
{ JA, AC, SH, KN, AC, TN, SH, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 634	 4500
{ JA, AC, AC, AC, LO, TN, LO, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 635	 4500
{ JA, LO, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 636	 4500
{ JA, LO, TN, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 637	 4500
{ JA, KN, AC, KN, AC, TN, KN, AC, AC, AC, AC, ST, AC, PF, AC }, 	 //	 638	 4500
{ JA, KN, AC, AC, TN, TN, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 639	 4500
{ JA, KN, AC, AC, LO, TN, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 640	 4500
{ JA, ST, AC, PF, TN, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 641	 4500
{ JA, SK, AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, PF, PF, AC }, 	 //	 642	 4500
{ JA, JA, SH, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 643	 4500
{ JA, JA, TN, TN, AC, TN, JA, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 644	 4500
{ JA, TN, AC, PF, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 645	 4500
{ JA, TN, AC, WN, AC, TN, WN, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 646	 4500
{ JA, TN, AC, WN, TN, TN, WN, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 647	 4500
{ JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC, ST, PF, AC, AC }, 	 //	 648	 4500
{ JA, TN, SH, KN, QN, TN, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 649	 4500
{ JA, AC, SH, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 650	 4500
{ JA, AC, AC, AC, JA, TN, AC, AC, LO, JA, AC, AC, AC, KN, WN }, 	 //	 651	 4500
{ JA, AC, AC, AC, KN, TN, AC, AC, LO, AC, AC, AC, AC, KN, LO }, 	 //	 652	 4500
{ JA, AC, AC, AC, QN, TN, AC, AC, KN, SH, AC, AC, AC, QN, JA }, 	 //	 653	 4500
{ JA, AC, AC, AC, TN, TN, AC, AC, PF, ST, AC, PF, AC, AC, AC }, 	 //	 654	 4500
{ JA, QN, AC, WN, AC, TN, KN, AC, AC, LO, AC, AC, AC, KN, AC }, 	 //	 655	 4500
{ TN, AC, TN, AC, AC, AC, SH, AC, AC, AC, AC, AC, AC, LO, CR }, 	 //	 656	 4500
{ TN, SH, AC, LO, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN }, 	 //	 657	 4500
{ TN, SH, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN }, 	 //	 658	 4500
{ TN, SH, AC, QN, QN, AC, AC, AC, ST, SH, AC, AC, AC, JA, JA }, 	 //	 659	 4500
{ TN, SH, AC, ST, KN, AC, AC, AC, JA, KN, AC, AC, AC, TN, CR }, 	 //	 660	 4500
{ TN, SH, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 661	 4500
{ TN, SH, AC, KN, CR, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN }, 	 //	 662	 4500
{ TN, SH, AC, QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, SK, QN }, 	 //	 663	 4500
{ TN, SH, AC, QN, SH, AC, AC, AC, QN, JA, AC, AC, AC, SK, JA }, 	 //	 664	 4500
{ TN, SH, AC, JA, KN, AC, AC, AC, JA, AC, AC, AC, AC, JA, LO }, 	 //	 665	 4500
{ TN, AC, AC, KN, CR, AC, AC, AC, KN, QN, AC, AC, AC, KN, KN }, 	 //	 666	 4500
{ TN, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC, QN, CR }, 	 //	 667	 4500
{ TN, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, WN }, 	 //	 668	 4500
{ TN, AC, AC, KN, WN, AC, AC, AC, QN, TN, AC, AC, AC, ST, TN }, 	 //	 669	 4500
{ TN, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, CR }, 	 //	 670	 4500
{ TN, AC, AC, PF, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, WN }, 	 //	 671	 4500
{ TN, AC, AC, AC, QN, AC, AC, AC, PF, PF, AC, LO, AC, AC, JA }, 	 //	 672	 4500
{ TN, AC, AC, AC, WN, AC, AC, AC, LO, TN, AC, LO, WN, KN, TN }, 	 //	 673	 4500
{ TN, QN, AC, TN, TN, AC, QN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 674	 4500
{ TN, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, CR }, 	 //	 675	 4500
{ TN, JA, AC, WN, AC, AC, JA, AC, AC, AC, AC, SH, AC, KN, AC }, 	 //	 676	 4500
{ TN, QN, AC, AC, AC, AC, ST, AC, AC, AC, AC, JA, PF, AC, AC }, 	 //	 677	 4500
{ TN, ST, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, SK }, 	 //	 678	 4500
{ TN, JA, AC, WN, AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 679	 4500
{ TN, TN, AC, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, SH, JA }, 	 //	 680	 4500
{ TN, TN, AC, QN, ST, AC, AC, AC, ST, AC, AC, AC, AC, JA, KN }, 	 //	 681	 4500
{ TN, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, WN, QN }, 	 //	 682	 4500
{ TN, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, AC }, 	 //	 683	 4500
{ TN, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SH }, 	 //	 684	 4500
{ TN, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, WN, KN, WN }, 	 //	 685	 4500
{ TN, AC, AC, AC, TN, AC, AC, AC, PF, ST, AC, PF, AC, KN, AC }, 	 //	 686	 4500
{ TN, AC, AC, AC, TN, AC, AC, AC, PF, ST, AC, PF, WN, AC, AC }, 	 //	 687	 4500
{ TN, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, PF, WN, KN, JA }, 	 //	 688	 4500
{ TN, AC, AC, AC, TN, AC, AC, AC, PF, TN, AC, PF, WN, KN, ST }, 	 //	 689	 4500
{ TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, PF, AC, AC }, 	 //	 690	 4500
{ TN, QN, AC, AC, AC, AC, KN, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 691	 4500
{ TN, KN, AC, TN, LO, AC, AC, AC, WN, AC, AC, SH, AC, AC, AC }, 	 //	 692	 4500
{ TN, KN, AC, JA, AC, AC, AC, AC, TN, AC, AC, SH, AC, AC, AC }, 	 //	 693	 4500
{ AC, SH, SH, LO, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 694	 4500
{ AC, SH, SH, WN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, WN }, 	 //	 695	 4500
{ AC, SH, SH, SK, CR, AC, AC, AC, JA, QN, AC, AC, AC, JA, KN }, 	 //	 696	 4500
{ AC, SH, SH, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC, ST, AC }, 	 //	 697	 4500
{ AC, SH, SH, QN, TN, AC, AC, AC, ST, AC, AC, AC, AC, JA, AC }, 	 //	 698	 4500
{ AC, SH, SH, KN, QN, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 699	 4500
{ AC, SH, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, KN, CR }, 	 //	 700	 4500
{ AC, SH, TN, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, WN, KN }, 	 //	 701	 4500
{ AC, SH, TN, KN, KN, AC, AC, AC, WN, KN, AC, AC, AC, QN, SK }, 	 //	 702	 4500
{ AC, SH, TN, QN, PF, AC, AC, AC, QN, JA, AC, AC, AC, QN, TN }, 	 //	 703	 4500
{ AC, SH, TN, QN, AC, AC, AC, AC, SK, KN, AC, AC, AC, JA, QN }, 	 //	 704	 4500
{ AC, SH, TN, SK, SH, AC, AC, AC, JA, JA, AC, AC, AC, JA, JA }, 	 //	 705	 4500
{ AC, SH, TN, AC, JA, AC, AC, AC, KN, WN, AC, AC, AC, QN, TN }, 	 //	 706	 4500
{ AC, AC, SH, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN }, 	 //	 707	 4500
{ AC, AC, SH, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC, QN, CR }, 	 //	 708	 4500
{ AC, AC, SH, WN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN }, 	 //	 709	 4500
{ AC, AC, SH, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC }, 	 //	 710	 4500
{ AC, AC, SH, AC, LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC }, 	 //	 711	 4500
{ AC, AC, SH, AC, SK, AC, AC, AC, KN, KN, AC, AC, AC, QN, KN }, 	 //	 712	 4500
{ AC, AC, SH, ST, SK, AC, AC, AC, JA, KN, AC, AC, AC, TN, KN }, 	 //	 713	 4500
{ AC, AC, SH, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SH }, 	 //	 714	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, WN, QN, AC, AC, PF, QN, PF }, 	 //	 715	 4500
{ AC, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, PF, WN, AC }, 	 //	 716	 4500
{ AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, SK }, 	 //	 717	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, WN, SK, AC, AC, WN, QN, QN }, 	 //	 718	 4500
{ AC, AC, AC, TN, AC, AC, AC, AC, WN, LO, AC, AC, WN, AC, AC }, 	 //	 719	 4500
{ AC, AC, AC, LO, LO, AC, AC, AC, KN, AC, AC, LO, PF, KN, AC }, 	 //	 720	 4500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, LO, PF, SK, ST }, 	 //	 721	 4500
{ AC, AC, AC, QN, CR, AC, AC, AC, SK, KN, AC, LO, PF, JA, KN }, 	 //	 722	 4500
{ AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, LO, PF, KN, TN }, 	 //	 723	 4500
{ AC, AC, AC, LO, TN, AC, AC, AC, KN, TN, AC, LO, WN, KN, ST }, 	 //	 724	 4500
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, LO, WN, JA, KN }, 	 //	 725	 4500
{ AC, AC, AC, SK, QN, AC, AC, AC, JA, QN, AC, LO, WN, JA, SH }, 	 //	 726	 4500
{ AC, AC, AC, QN, TN, AC, AC, AC, KN, AC, AC, LO, WN, AC, AC }, 	 //	 727	 4500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, ST, AC, AC, SK }, 	 //	 728	 4500
{ AC, KN, AC, TN, AC, AC, ST, AC, AC, LO, AC, QN, AC, AC, AC }, 	 //	 729	 4500
{ AC, QN, SH, PF, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 730	 4500
{ AC, QN, SH, AC, AC, AC, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 731	 4500
{ AC, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, WN, AC, AC }, 	 //	 732	 4500
{ AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, SH, WN, AC, AC }, 	 //	 733	 4500
{ AC, SH, AC, AC, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 734	 4500
{ AC, TN, AC, AC, AC, AC, WN, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 735	 4500
{ AC, TN, TN, AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 736	 4500
{ AC, TN, AC, WN, AC, AC, WN, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 737	 4500
{ AC, TN, AC, AC, AC, AC, WN, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 738	 4500
{ AC, WN, AC, AC, KN, AC, AC, AC, LO, KN, AC, KN, AC, KN, SK }, 	 //	 739	 4500
{ AC, WN, AC, AC, JA, AC, AC, AC, LO, TN, AC, KN, AC, KN, AC }, 	 //	 740	 4500
{ AC, WN, AC, KN, TN, AC, AC, AC, KN, TN, AC, KN, AC, KN, TN }, 	 //	 741	 4500
{ AC, WN, AC, KN, JA, AC, AC, AC, KN, TN, AC, KN, AC, KN, AC }, 	 //	 742	 4500
{ AC, WN, AC, QN, AC, AC, AC, AC, QN, AC, AC, KN, AC, SK, AC }, 	 //	 743	 4500
{ AC, WN, AC, TN, KN, AC, AC, AC, WN, KN, AC, KN, AC, AC, KN }, 	 //	 744	 4500
{ AC, WN, AC, KN, JA, AC, AC, AC, SK, TN, AC, KN, AC, QN, AC }, 	 //	 745	 4500
{ AC, WN, AC, AC, AC, AC, AC, AC, PF, AC, AC, KN, PF, KN, AC }, 	 //	 746	 4500
{ AC, WN, AC, KN, KN, AC, AC, AC, WN, KN, AC, KN, AC, QN, KN }, 	 //	 747	 4500
{ AC, WN, AC, QN, JA, AC, AC, AC, SK, JA, AC, KN, AC, JA, WN }, 	 //	 748	 4500
{ AC, AC, AC, TN, QN, AC, KN, AC, AC, KN, AC, QN, AC, AC, AC }, 	 //	 749	 4500
{ AC, TN, SH, SK, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, ST }, 	 //	 750	 4500
{ AC, TN, SH, TN, QN, AC, AC, AC, TN, PF, AC, AC, AC, TN, JA }, 	 //	 751	 4500
{ AC, TN, SH, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN, QN }, 	 //	 752	 4500
{ AC, TN, SH, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, ST }, 	 //	 753	 4500
{ AC, TN, TN, KN, QN, AC, AC, AC, KN, PF, AC, AC, AC, WN, JA }, 	 //	 754	 4500
{ AC, TN, TN, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC, QN, AC }, 	 //	 755	 4500
{ AC, AC, SH, KN, CR, AC, AC, AC, WN, KN, AC, AC, AC, QN, KN }, 	 //	 756	 4500
{ AC, AC, SH, SK, QN, AC, AC, AC, JA, PF, AC, AC, AC, JA, JA }, 	 //	 757	 4500
{ AC, AC, SH, AC, KN, AC, AC, AC, KN, KN, AC, AC, AC, QN, KN }, 	 //	 758	 4500
{ AC, AC, AC, LO, CR, AC, AC, AC, KN, KN, AC, AC, PF, KN, KN }, 	 //	 759	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, SK, AC, AC, PF, KN, QN }, 	 //	 760	 4500
{ AC, AC, AC, KN, JA, AC, AC, AC, KN, WN, AC, AC, PF, KN, TN }, 	 //	 761	 4500
{ AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, PF, WN, AC }, 	 //	 762	 4500
{ AC, AC, AC, SH, WN, AC, AC, AC, TN, TN, AC, AC, PF, TN, TN }, 	 //	 763	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, PF, SK, JA }, 	 //	 764	 4500
{ AC, AC, TN, LO, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN }, 	 //	 765	 4500
{ AC, AC, TN, AC, TN, AC, AC, AC, PF, AC, AC, AC, AC, KN, AC }, 	 //	 766	 4500
{ AC, AC, TN, PF, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, CR }, 	 //	 767	 4500
{ AC, AC, TN, PF, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN }, 	 //	 768	 4500
{ AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC }, 	 //	 769	 4500
{ AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, WN, WN, AC }, 	 //	 770	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, QN, QN, AC, AC, WN, ST, SH }, 	 //	 771	 4500
{ AC, AC, AC, KN, WN, AC, AC, AC, QN, TN, AC, AC, WN, ST, TN }, 	 //	 772	 4500
{ AC, AC, AC, PF, KN, AC, AC, AC, KN, SK, AC, AC, WN, KN, QN }, 	 //	 773	 4500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, AC, AC, PF, PF, KN, AC }, 	 //	 774	 4500
{ AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, PF, PF, SK, AC }, 	 //	 775	 4500
{ AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, PF, PF, KN, WN }, 	 //	 776	 4500
{ AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, AC, PF, PF, SK, QN }, 	 //	 777	 4500
{ AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, PF, WN, TN, CR }, 	 //	 778	 4500
{ AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, PF, WN, TN, SK }, 	 //	 779	 4500
{ AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, PF, WN, WN, CR }, 	 //	 780	 4500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, PF, WN, KN, JA }, 	 //	 781	 4500
{ AC, AC, AC, KN, JA, AC, AC, AC, KN, TN, AC, PF, WN, KN, AC }, 	 //	 782	 4500
{ AC, PF, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, PF, LO, AC }, 	 //	 783	 4500
{ AC, KN, AC, JA, JA, AC, AC, AC, JA, WN, AC, SH, AC, SH, TN }, 	 //	 784	 4500
{ AC, KN, AC, TN, SK, AC, AC, AC, WN, QN, AC, SH, AC, AC, QN }, 	 //	 785	 4500
{ AC, KN, AC, AC, PF, AC, AC, AC, PF, JA, AC, SH, AC, KN, TN }, 	 //	 786	 4500
{ AC, KN, AC, PF, TN, AC, AC, AC, KN, TN, AC, SH, AC, KN, TN }, 	 //	 787	 4500
{ AC, KN, AC, KN, JA, AC, AC, AC, KN, JA, AC, SH, AC, SK, WN }, 	 //	 788	 4500
{ AC, SH, AC, QN, KN, AC, AC, AC, KN, KN, SK, AC, AC, AC, SK }, 	 //	 789	 4500
{ AC, SH, AC, QN, KN, AC, AC, AC, KN, AC, SK, AC, AC, AC, LO }, 	 //	 790	 4500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, SK, AC, AC, KN, CR }, 	 //	 791	 4500
{ AC, AC, AC, SK, KN, AC, AC, AC, JA, SK, SK, AC, AC, JA, QN }, 	 //	 792	 4500
{ AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, SK, AC, AC, JA, CR }, 	 //	 793	 4500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, SK, AC, AC, TN, AC }, 	 //	 794	 4500
{ AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, SK, AC, AC, KN, CR }, 	 //	 795	 4500
{ AC, AC, AC, QN, JA, AC, AC, AC, SK, TN, SK, AC, AC, JA, AC }, 	 //	 796	 4500
{ AC, AC, AC, JA, TN, AC, AC, AC, SH, ST, SK, AC, AC, TN, AC }, 	 //	 797	 4500
{ AC, AC, AC, JA, JA, AC, AC, AC, SH, TN, SK, AC, AC, TN, AC }, 	 //	 798	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, SK, LO, AC, WN, KN }, 	 //	 799	 4500
{ AC, AC, AC, JA, ST, AC, AC, AC, JA, AC, SK, LO, AC, SH, KN }, 	 //	 800	 4500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, SK, LO, AC, KN, AC }, 	 //	 801	 4500
{ AC, AC, AC, WN, PF, AC, AC, AC, QN, JA, SK, LO, AC, QN, TN }, 	 //	 802	 4500
{ AC, KN, AC, AC, AC, AC, ST, AC, AC, AC, SK, QN, WN, AC, AC }, 	 //	 803	 4500
{ AC, ST, AC, AC, AC, AC, QN, AC, AC, AC, SK, QN, PF, PF, AC }, 	 //	 804	 4500
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, SK, QN, AC, PF, AC }, 	 //	 805	 4500
{ AC, QN, TN, PF, AC, AC, QN, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 806	 4500
{ AC, JA, AC, WN, AC, AC, SH, AC, AC, AC, SK, TN, AC, KN, AC }, 	 //	 807	 4500
{ AC, AC, AC, TN, QN, AC, KN, AC, AC, KN, SK, QN, AC, AC, AC }, 	 //	 808	 4500
{ AC, AC, AC, KN, AC, AC, KN, AC, AC, AC, SK, QN, WN, PF, AC }, 	 //	 809	 4500
{ AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK, ST, AC, AC, CR }, 	 //	 810	 4500
{ AC, QN, AC, AC, LO, AC, ST, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 811	 4500
{ AC, TN, AC, QN, AC, AC, AC, AC, KN, SK, SK, AC, AC, AC, KN }, 	 //	 812	 4500
{ AC, AC, SH, JA, KN, AC, AC, AC, TN, AC, SK, AC, AC, AC, LO }, 	 //	 813	 4500
{ AC, AC, AC, QN, QN, AC, AC, AC, SK, KN, SK, AC, AC, JA, AC }, 	 //	 814	 4500
{ AC, AC, AC, KN, JA, AC, AC, AC, SK, JA, SK, AC, AC, QN, JA }, 	 //	 815	 4500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, SK, AC, AC, WN, CR }, 	 //	 816	 4500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, KN, SK, AC, AC, SK, KN }, 	 //	 817	 4500
{ AC, AC, AC, ST, CR, AC, AC, AC, JA, QN, SK, AC, AC, TN, KN }, 	 //	 818	 4500
{ AC, AC, AC, LO, KN, AC, AC, AC, KN, KN, SK, PF, AC, KN, KN }, 	 //	 819	 4500
{ AC, AC, AC, LO, KN, AC, AC, AC, KN, AC, SK, PF, AC, KN, LO }, 	 //	 820	 4500
{ AC, AC, AC, QN, JA, AC, AC, AC, QN, WN, SK, PF, AC, QN, TN }, 	 //	 821	 4500
{ AC, AC, AC, KN, TN, AC, AC, AC, QN, ST, SK, PF, AC, ST, AC }, 	 //	 822	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, SK, SK, PF, AC, KN, QN }, 	 //	 823	 4500
{ AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, SK, PF, AC, KN, AC }, 	 //	 824	 4500
{ AC, AC, AC, KN, KN, AC, AC, AC, QN, KN, SK, PF, AC, ST, SK }, 	 //	 825	 4500
{ AC, PF, AC, AC, AC, AC, KN, AC, AC, AC, SK, KN, AC, LO, SK }, 	 //	 826	 4500
{ AC, PF, AC, WN, AC, AC, KN, AC, AC, AC, SK, KN, AC, KN, AC }, 	 //	 827	 4500
{ AC, PF, AC, TN, TN, AC, KN, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 828	 4500
{ AC, KN, TN, TN, AC, AC, AC, AC, WN, LO, SK, SH, AC, AC, AC }, 	 //	 829	 4500
{ AC, AC, AC, WN, WN, SK, AC, AC, AC, TN, KN, AC, PF, KN, TN }, 	 //	 830	 4500
{ AC, AC, AC, QN, SK, SK, AC, AC, KN, KN, KN, AC, AC, AC, KN }, 	 //	 831	 4500
{ AC, AC, AC, QN, TN, SK, AC, AC, KN, ST, KN, LO, AC, AC, AC }, 	 //	 832	 4500
{ AC, KN, AC, PF, AC, SK, ST, AC, AC, LO, KN, QN, AC, AC, AC }, 	 //	 833	 4500
{ AC, KN, AC, AC, AC, SK, ST, AC, AC, AC, KN, QN, AC, PF, CR }, 	 //	 834	 4500
{ AC, ST, AC, AC, TN, SK, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 835	 4500
{ AC, QN, AC, AC, AC, SK, QN, AC, AC, AC, KN, SK, WN, AC, AC }, 	 //	 836	 4500
{ AC, JA, AC, AC, AC, SK, JA, AC, AC, AC, KN, JA, WN, AC, AC }, 	 //	 837	 4500
{ AC, TN, AC, AC, AC, SK, WN, AC, AC, AC, KN, AC, PF, LO, AC }, 	 //	 838	 4500
{ AC, AC, AC, QN, KN, SK, AC, AC, KN, KN, KN, AC, AC, AC, KN }, 	 //	 839	 4500
{ AC, AC, AC, WN, JA, SK, AC, AC, AC, JA, KN, AC, PF, KN, WN }, 	 //	 840	 4500
{ AC, AC, AC, KN, TN, SK, AC, AC, AC, TN, KN, AC, WN, PF, ST }, 	 //	 841	 4500
{ AC, AC, TN, AC, AC, SK, PF, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 842	 4500
{ AC, KN, AC, WN, AC, SK, KN, AC, AC, AC, KN, KN, AC, KN, AC }, 	 //	 843	 4500
{ SK, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, PF, PF, ST }, 	 //	 844	 4500
{ SK, AC, TN, TN, JA, KN, AC, AC, AC, TN, KN, LO, AC, AC, AC }, 	 //	 845	 4500
{ SK, KN, SH, TN, AC, KN, KN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 846	 4500
{ SK, KN, AC, AC, AC, KN, ST, AC, AC, AC, KN, QN, AC, AC, CR }, 	 //	 847	 4500
{ SK, QN, AC, TN, LO, KN, QN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 848	 4500
{ SK, WN, AC, AC, QN, KN, AC, AC, AC, QN, KN, KN, AC, AC, SH }, 	 //	 849	 4500
{ SK, WN, AC, AC, KN, KN, AC, AC, AC, QN, KN, KN, AC, LO, PF }, 	 //	 850	 4500
{ SK, QN, AC, AC, AC, KN, ST, AC, AC, AC, KN, JA, AC, PF, SK }, 	 //	 851	 4500
{ SK, JA, AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, LO, SK }, 	 //	 852	 4500
{ SK, TN, SH, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 853	 4500
{ SK, AC, TN, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 854	 4500
{ SK, AC, AC, KN, KN, KN, AC, AC, AC, KN, KN, AC, AC, PF, KN }, 	 //	 855	 4500
{ SK, AC, AC, PF, JA, KN, AC, AC, AC, WN, KN, PF, AC, AC, TN }, 	 //	 856	 4500
{ SK, AC, AC, WN, KN, KN, AC, AC, AC, KN, KN, PF, AC, KN, SK }, 	 //	 857	 4500
{ SK, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, PF, WN, PF, KN }, 	 //	 858	 4500
{ SK, KN, AC, TN, JA, KN, AC, AC, AC, WN, KN, SH, AC, AC, TN }, 	 //	 859	 4500
{ KN, SH, AC, WN, JA, KN, AC, AC, AC, WN, KN, AC, AC, KN, TN }, 	 //	 860	 4500
{ KN, SH, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, PF, ST }, 	 //	 861	 4500
{ KN, SH, TN, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 862	 4500
{ KN, AC, AC, AC, PF, KN, AC, AC, AC, JA, KN, AC, PF, AC, TN }, 	 //	 863	 4500
{ KN, AC, TN, TN, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 864	 4500
{ KN, AC, AC, KN, QN, KN, AC, AC, AC, SH, KN, AC, AC, PF, JA }, 	 //	 865	 4500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, KN, LO, PF, AC, KN }, 	 //	 866	 4500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, ST, AC, LO, SK }, 	 //	 867	 4500
{ KN, JA, AC, KN, AC, KN, JA, AC, AC, AC, KN, JA, AC, PF, AC }, 	 //	 868	 4500
{ KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, SH, WN, AC, AC }, 	 //	 869	 4500
{ KN, WN, AC, PF, CR, KN, AC, AC, AC, KN, KN, KN, AC, AC, KN }, 	 //	 870	 4500
{ KN, WN, AC, KN, CR, KN, AC, AC, AC, KN, KN, KN, AC, PF, KN }, 	 //	 871	 4500
{ KN, AC, AC, TN, LO, KN, KN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 872	 4500
{ KN, QN, AC, AC, AC, KN, ST, AC, AC, AC, KN, JA, WN, AC, AC }, 	 //	 873	 4500
{ KN, AC, AC, AC, PF, KN, AC, AC, AC, JA, KN, AC, PF, AC, TN }, 	 //	 874	 4500
{ KN, KN, AC, KN, AC, KN, KN, AC, AC, AC, KN, SK, AC, PF, AC }, 	 //	 875	 4500
{ KN, KN, KN, KN, KN, KN, AC, SH, AC, KN, KN, SH, AC, PF, KN }, 	 //	 876	 4500
{ KN, KN, AC, TN, JA, KN, AC, AC, AC, JA, KN, SH, AC, AC, JA }, 	 //	 877	 4500
{ KN, KN, AC, TN, KN, KN, AC, AC, AC, QN, KN, SH, AC, AC, PF }, 	 //	 878	 4500
{ KN, KN, AC, KN, TN, KN, AC, AC, AC, TN, KN, SH, AC, PF, ST }, 	 //	 879	 4500
{ KN, KN, AC, TN, SH, KN, AC, AC, AC, JA, KN, SH, AC, AC, JA }, 	 //	 880	 4500
{ KN, SH, AC, AC, SH, KN, AC, AC, AC, JA, WN, AC, AC, PF, JA }, 	 //	 881	 4500
{ KN, SH, AC, KN, WN, KN, AC, AC, AC, TN, WN, AC, AC, PF, TN }, 	 //	 882	 4500
{ KN, AC, TN, AC, JA, KN, AC, AC, AC, JA, WN, AC, AC, AC, WN }, 	 //	 883	 4500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, WN, LO, PF, AC, QN }, 	 //	 884	 4500
{ KN, AC, AC, KN, SK, KN, AC, AC, AC, QN, WN, LO, AC, PF, QN }, 	 //	 885	 4500
{ KN, LO, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, LO, SK }, 	 //	 886	 4500
{ KN, LO, AC, KN, AC, KN, KN, AC, AC, AC, WN, KN, AC, PF, AC }, 	 //	 887	 4500
{ KN, QN, AC, TN, AC, KN, QN, AC, AC, LO, WN, SK, AC, AC, AC }, 	 //	 888	 4500
{ KN, WN, SH, PF, QN, KN, AC, AC, AC, KN, WN, KN, AC, AC, AC }, 	 //	 889	 4500
{ KN, AC, AC, AC, AC, KN, KN, KN, AC, AC, WN, QN, QN, PF, AC }, 	 //	 890	 4500
{ KN, AC, AC, AC, AC, KN, KN, KN, AC, AC, WN, QN, WN, AC, AC }, 	 //	 891	 4500
{ KN, JA, AC, AC, AC, KN, TN, AC, AC, AC, WN, AC, PF, LO, AC }, 	 //	 892	 4500
{ KN, TN, SH, TN, SH, KN, AC, AC, AC, JA, WN, AC, AC, AC, JA }, 	 //	 893	 4500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, SK, WN, AC, WN, AC, KN }, 	 //	 894	 4500
{ KN, AC, TN, TN, KN, KN, AC, AC, AC, KN, WN, AC, AC, AC, KN }, 	 //	 895	 4500
{ KN, AC, AC, KN, KN, KN, AC, AC, AC, SK, WN, AC, AC, PF, QN }, 	 //	 896	 4500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, WN, PF, WN, AC, QN }, 	 //	 897	 4500
{ KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, WN, PF, WN, LO, WN }, 	 //	 898	 4500
{ KN, KN, SH, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 899	 4500
{ KN, KN, AC, WN, AC, KN, KN, AC, AC, AC, WN, SK, AC, KN, AC }, 	 //	 900	 4500
{ KN, KN, TN, TN, AC, KN, SK, AC, AC, AC, WN, QN, AC, AC, AC }, 	 //	 901	 4500
{ KN, KN, AC, AC, SK, KN, AC, AC, AC, QN, WN, SH, AC, AC, QN }, 	 //	 902	 4500
{ KN, SH, AC, AC, QN, WN, AC, AC, AC, SH, QN, AC, AC, LO, JA }, 	 //	 903	 4500
{ KN, SH, TN, PF, KN, WN, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 904	 4500
{ KN, AC, AC, AC, WN, WN, AC, AC, AC, TN, QN, LO, PF, AC, TN }, 	 //	 905	 4500
{ KN, QN, AC, AC, AC, WN, SK, AC, AC, AC, QN, JA, PF, PF, AC }, 	 //	 906	 4500
{ KN, JA, TN, PF, AC, WN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 907	 4500
{ KN, WN, AC, PF, KN, WN, AC, AC, AC, KN, QN, KN, AC, AC, SK }, 	 //	 908	 4500
{ KN, JA, AC, AC, AC, WN, TN, AC, AC, SK, QN, AC, AC, AC, KN }, 	 //	 909	 4500
{ KN, AC, TN, PF, PF, WN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 910	 4500
{ KN, AC, AC, AC, CR, WN, AC, AC, AC, QN, QN, AC, WN, PF, KN }, 	 //	 911	 4500
{ KN, AC, AC, KN, TN, WN, AC, AC, AC, TN, QN, PF, AC, PF, TN }, 	 //	 912	 4500
{ KN, AC, AC, WN, AC, WN, PF, AC, AC, AC, QN, KN, AC, KN, AC }, 	 //	 913	 4500
{ KN, KN, SH, TN, AC, WN, KN, AC, AC, AC, QN, SK, AC, AC, AC }, 	 //	 914	 4500
{ KN, KN, AC, AC, CR, WN, AC, AC, AC, KN, QN, SH, AC, AC, KN }, 	 //	 915	 4500
{ KN, KN, AC, AC, SK, WN, AC, AC, AC, QN, QN, SH, AC, AC, QN }, 	 //	 916	 4500
{ KN, KN, AC, AC, WN, WN, AC, AC, AC, TN, QN, SH, AC, AC, TN }, 	 //	 917	 4500
{ WN, SH, SH, AC, SK, QN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 918	 4500
{ WN, SH, AC, WN, KN, QN, AC, AC, AC, SK, KN, AC, AC, KN, QN }, 	 //	 919	 4500
{ WN, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, PF, LO, QN }, 	 //	 920	 4500
{ WN, AC, AC, KN, KN, QN, AC, AC, AC, KN, KN, LO, AC, PF, SK }, 	 //	 921	 4500
{ WN, AC, AC, KN, QN, QN, AC, AC, AC, PF, KN, LO, AC, PF, JA }, 	 //	 922	 4500
{ WN, LO, AC, TN, TN, QN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 923	 4500
{ WN, ST, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN, AC, PF, SK }, 	 //	 924	 4500
{ WN, JA, AC, AC, TN, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 925	 4500
{ WN, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 926	 4500
{ WN, JA, AC, TN, AC, QN, JA, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 927	 4500
{ WN, TN, AC, AC, AC, QN, TN, AC, AC, AC, KN, WN, AC, AC, CR }, 	 //	 928	 4500
{ WN, WN, AC, PF, SK, QN, AC, AC, AC, QN, KN, KN, AC, AC, QN }, 	 //	 929	 4500
{ WN, AC, SH, AC, CR, QN, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 930	 4500
{ WN, AC, AC, AC, CR, QN, AC, AC, AC, KN, KN, AC, WN, AC, KN }, 	 //	 931	 4500
{ WN, KN, TN, TN, AC, QN, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 932	 4500
{ QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC, ST, PF, LO, AC }, 	 //	 933	 4500
{ QN, KN, AC, PF, LO, KN, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 934	 4500
{ QN, QN, AC, AC, AC, KN, QN, AC, AC, AC, AC, SK, AC, LO, SK }, 	 //	 935	 4500
{ QN, JA, AC, AC, AC, KN, JA, AC, AC, LO, AC, SH, AC, LO, AC }, 	 //	 936	 4500
{ QN, JA, SH, TN, AC, KN, SH, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 937	 4500
{ QN, SH, AC, AC, AC, KN, TN, AC, AC, AC, AC, TN, PF, AC, AC }, 	 //	 938	 4500
{ QN, TN, TN, KN, KN, KN, AC, AC, AC, SK, AC, AC, AC, PF, QN }, 	 //	 939	 4500
{ QN, AC, SH, WN, TN, KN, AC, AC, AC, TN, AC, AC, AC, KN, ST }, 	 //	 940	 4500
{ QN, AC, AC, AC, LO, KN, AC, AC, LO, AC, AC, AC, AC, KN, AC }, 	 //	 941	 4500
{ QN, QN, KN, KN, KN, KN, KN, SH, KN, KN, AC, AC, AC, KN, KN }, 	 //	 942	 4500
{ QN, QN, AC, WN, AC, KN, KN, AC, AC, LO, AC, AC, AC, KN, AC }, 	 //	 943	 4500
{ KN, AC, AC, AC, ST, AC, SH, AC, AC, AC, LO, AC, AC, AC, KN }, 	 //	 944	 4500
{ KN, AC, AC, TN, AC, AC, SH, AC, AC, AC, LO, AC, AC, AC, SK }, 	 //	 945	 4500
{ KN, AC, AC, AC, KN, AC, AC, AC, PF, KN, LO, AC, AC, AC, KN }, 	 //	 946	 4500
{ KN, LO, TN, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC }, 	 //	 947	 4500
{ KN, QN, AC, KN, AC, AC, QN, AC, AC, AC, LO, SK, AC, PF, AC }, 	 //	 948	 4500
{ KN, QN, AC, AC, AC, AC, SK, AC, AC, LO, LO, JA, AC, LO, AC }, 	 //	 949	 4500
{ KN, JA, AC, AC, AC, AC, JA, AC, AC, AC, LO, SH, AC, PF, SK }, 	 //	 950	 4500
{ KN, SH, TN, PF, AC, AC, TN, AC, AC, AC, LO, TN, AC, AC, AC }, 	 //	 951	 4500
{ KN, AC, AC, AC, AC, AC, KN, WN, AC, LO, LO, QN, KN, AC, AC }, 	 //	 952	 4500
{ KN, KN, SH, AC, AC, AC, QN, AC, AC, AC, LO, ST, AC, AC, AC }, 	 //	 953	 4500
{ KN, JA, TN, AC, AC, AC, TN, AC, AC, AC, LO, AC, AC, AC, CR }, 	 //	 954	 4500
{ KN, AC, AC, AC, SK, AC, AC, AC, PF, QN, LO, AC, AC, AC, QN }, 	 //	 955	 4500
{ KN, SK, AC, AC, AC, AC, QN, AC, AC, AC, LO, KN, PF, LO, AC }, 	 //	 956	 4500
{ KN, SK, AC, AC, AC, AC, QN, AC, AC, AC, LO, KN, WN, AC, AC }, 	 //	 957	 4500
