#include "ReelDefine.h"

unsigned char L5_Outcome_9000[1000][15]={	 //	 0	 9000
{ AC, SH, SH, TN, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 1	 9000
{ AC, SH, SH, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 2	 9000
{ AC, SH, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 3	 9000
{ AC, SH, TN, PF, TN, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 4	 9000
{ AC, SH, TN, AC, LO, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 5	 9000
{ AC, AC, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 6	 9000
{ AC, AC, AC, PF, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 7	 9000
{ AC, AC, AC, PF, SH, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 8	 9000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, LO, WN }, 	 //	 9	 9000
{ AC, AC, AC, AC, WN, LO, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 10	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, LO, ST }, 	 //	 11	 9000
{ AC, AC, AC, WN, ST, LO, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 12	 9000
{ AC, AC, AC, TN, CR, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 13	 9000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, PF, SH }, 	 //	 14	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 15	 9000
{ AC, AC, AC, KN, KN, LO, AC, AC, AC, AC, AC, AC, AC, PF, LO }, 	 //	 16	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 17	 9000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 18	 9000
{ AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 19	 9000
{ AC, AC, AC, PF, QN, LO, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 20	 9000
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, LO, SK }, 	 //	 21	 9000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, PF, AC, AC, AC, LO, JA }, 	 //	 22	 9000
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, LO, CR }, 	 //	 23	 9000
{ AC, AC, AC, TN, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 24	 9000
{ AC, AC, AC, TN, PF, LO, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 25	 9000
{ AC, AC, AC, TN, SK, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 26	 9000
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 27	 9000
{ AC, AC, AC, AC, SH, LO, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 28	 9000
{ AC, AC, AC, AC, WN, LO, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 29	 9000
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, QN, AC, AC, AC, PF, PF }, 	 //	 30	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, WN, AC, AC }, 	 //	 31	 9000
{ AC, AC, AC, AC, LO, LO, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 32	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 33	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, LO, WN, LO, AC }, 	 //	 34	 9000
{ AC, KN, KN, KN, KN, LO, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 35	 9000
{ AC, KN, KN, KN, KN, LO, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 36	 9000
{ AC, WN, AC, PF, AC, LO, AC, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 37	 9000
{ AC, WN, AC, AC, LO, LO, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 38	 9000
{ AC, WN, AC, AC, LO, LO, AC, AC, AC, AC, AC, KN, AC, LO, AC }, 	 //	 39	 9000
{ AC, WN, AC, TN, AC, LO, AC, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 40	 9000
{ AC, WN, AC, AC, TN, LO, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 41	 9000
{ AC, TN, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 42	 9000
{ AC, TN, SH, AC, LO, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 43	 9000
{ AC, TN, SH, AC, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 44	 9000
{ AC, AC, SH, PF, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 45	 9000
{ AC, AC, SH, TN, LO, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 46	 9000
{ AC, AC, AC, PF, KN, LO, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 47	 9000
{ AC, AC, AC, PF, QN, LO, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 48	 9000
{ AC, AC, AC, PF, CR, LO, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 49	 9000
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, LO, SH }, 	 //	 50	 9000
{ AC, AC, AC, WN, ST, LO, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 51	 9000
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 52	 9000
{ AC, AC, AC, TN, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 53	 9000
{ AC, AC, AC, AC, SH, LO, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 54	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 55	 9000
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, PF, CR }, 	 //	 56	 9000
{ AC, AC, AC, AC, LO, LO, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 57	 9000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, LO, CR }, 	 //	 58	 9000
{ AC, AC, TN, PF, LO, LO, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 59	 9000
{ AC, AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 60	 9000
{ AC, AC, AC, PF, PF, LO, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 61	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 62	 9000
{ AC, AC, AC, TN, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 63	 9000
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 64	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 65	 9000
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, AC, AC, AC, WN, LO, AC }, 	 //	 66	 9000
{ AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, PF, WN, AC, SK }, 	 //	 67	 9000
{ AC, PF, KN, KN, KN, LO, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 68	 9000
{ AC, KN, AC, AC, TN, LO, AC, AC, AC, AC, AC, SH, AC, LO, AC }, 	 //	 69	 9000
{ AC, KN, AC, TN, AC, LO, AC, AC, AC, AC, AC, SH, AC, AC, CR }, 	 //	 70	 9000
{ AC, KN, AC, AC, LO, LO, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 71	 9000
{ LO, SH, SH, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 72	 9000
{ LO, SH, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 73	 9000
{ LO, SH, TN, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 74	 9000
{ LO, SH, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 75	 9000
{ LO, AC, SH, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 76	 9000
{ LO, AC, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 77	 9000
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 78	 9000
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 79	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 80	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 81	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 82	 9000
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 83	 9000
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 84	 9000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, LO, AC, LO, AC, KN, AC }, 	 //	 85	 9000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, AC, KN, CR }, 	 //	 86	 9000
{ LO, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, CR }, 	 //	 87	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, AC, CR }, 	 //	 88	 9000
{ LO, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, SK }, 	 //	 89	 9000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, CR }, 	 //	 90	 9000
{ LO, WN, AC, PF, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 91	 9000
{ LO, WN, AC, WN, AC, AC, AC, AC, AC, LO, AC, KN, AC, KN, AC }, 	 //	 92	 9000
{ LO, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, CR }, 	 //	 93	 9000
{ LO, TN, SH, PF, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 94	 9000
{ LO, AC, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 95	 9000
{ LO, AC, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 96	 9000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 97	 9000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 98	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 99	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, LO, SK }, 	 //	 100	 9000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 101	 9000
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 102	 9000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 103	 9000
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 104	 9000
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 105	 9000
{ LO, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, PF, AC, KN, CR }, 	 //	 106	 9000
{ LO, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, SK }, 	 //	 107	 9000
{ LO, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, AC, PF, CR }, 	 //	 108	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, PF, WN, AC, AC }, 	 //	 109	 9000
{ LO, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, AC, SK }, 	 //	 110	 9000
{ LO, KN, AC, TN, AC, AC, AC, AC, AC, AC, AC, SH, AC, AC, SK }, 	 //	 111	 9000
{ AC, SH, SH, PF, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 112	 9000
{ AC, SH, SH, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 113	 9000
{ AC, SH, SH, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 114	 9000
{ AC, SH, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 115	 9000
{ AC, SH, TN, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 116	 9000
{ AC, AC, SH, PF, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 117	 9000
{ AC, AC, SH, TN, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 118	 9000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, SH, AC, AC, AC, KN, JA }, 	 //	 119	 9000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, ST }, 	 //	 120	 9000
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 121	 9000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, QN, AC, AC, AC, PF, PF }, 	 //	 122	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, PF, AC, AC }, 	 //	 123	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, PF, AC, KN }, 	 //	 124	 9000
{ AC, AC, TN, PF, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 125	 9000
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, QN, AC, AC, AC, KN, PF }, 	 //	 126	 9000
{ AC, AC, AC, WN, CR, AC, AC, AC, AC, QN, AC, AC, AC, KN, KN }, 	 //	 127	 9000
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 128	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, WN, AC, KN }, 	 //	 129	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, WN, LO, AC }, 	 //	 130	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, WN, AC, AC }, 	 //	 131	 9000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, WN, AC, KN }, 	 //	 132	 9000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, LO, PF, AC, KN }, 	 //	 133	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, PF, LO, AC }, 	 //	 134	 9000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, LO, PF, AC, KN }, 	 //	 135	 9000
{ AC, WN, AC, AC, TN, AC, AC, AC, AC, ST, AC, KN, AC, PF, AC }, 	 //	 136	 9000
{ AC, WN, AC, AC, ST, AC, AC, AC, AC, AC, AC, KN, AC, LO, KN }, 	 //	 137	 9000
{ AC, WN, AC, WN, KN, AC, AC, AC, AC, AC, AC, KN, AC, KN, LO }, 	 //	 138	 9000
{ AC, WN, AC, KN, TN, AC, AC, AC, AC, ST, AC, KN, AC, PF, AC }, 	 //	 139	 9000
{ AC, TN, SH, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 140	 9000
{ AC, TN, SH, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 141	 9000
{ AC, TN, TN, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 142	 9000
{ AC, TN, TN, PF, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 143	 9000
{ AC, TN, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 144	 9000
{ AC, TN, TN, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 145	 9000
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 146	 9000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 147	 9000
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 148	 9000
{ AC, AC, AC, WN, SH, AC, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 149	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, PF, AC, AC }, 	 //	 150	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, PF, PF, KN }, 	 //	 151	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, PF, LO }, 	 //	 152	 9000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 153	 9000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, SH, AC, AC, AC, KN, JA }, 	 //	 154	 9000
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 155	 9000
{ AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 156	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, WN, LO, QN }, 	 //	 157	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, WN, PF, QN }, 	 //	 158	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, PF, AC, AC }, 	 //	 159	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, PF, PF, AC, LO }, 	 //	 160	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, WN, AC, AC }, 	 //	 161	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, PF, WN, PF, AC }, 	 //	 162	 9000
{ AC, PF, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 163	 9000
{ AC, PF, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 164	 9000
{ AC, KN, AC, PF, ST, AC, AC, AC, AC, AC, AC, SH, AC, AC, KN }, 	 //	 165	 9000
{ AC, KN, AC, TN, AC, AC, AC, AC, AC, SK, AC, SH, AC, AC, KN }, 	 //	 166	 9000
{ AC, KN, AC, AC, ST, AC, AC, AC, AC, AC, AC, SH, AC, AC, KN }, 	 //	 167	 9000
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, ST, AC, SH, AC, PF, AC }, 	 //	 168	 9000
{ AC, KN, AC, KN, JA, AC, AC, AC, AC, TN, AC, SH, AC, PF, AC }, 	 //	 169	 9000
{ AC, KN, AC, AC, JA, AC, AC, AC, AC, TN, AC, SH, AC, PF, AC }, 	 //	 170	 9000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 171	 9000
{ AC, SH, SH, TN, TN, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 172	 9000
{ AC, SH, AC, WN, AC, AC, AC, AC, AC, LO, ST, AC, AC, KN, AC }, 	 //	 173	 9000
{ AC, SH, TN, PF, AC, AC, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 174	 9000
{ AC, AC, SH, PF, LO, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 175	 9000
{ AC, AC, SH, AC, TN, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 176	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, ST, AC, AC, AC, SH }, 	 //	 177	 9000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 178	 9000
{ AC, AC, TN, TN, AC, AC, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 179	 9000
{ AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 180	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 181	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 182	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 183	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 184	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 185	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, ST, LO, WN, AC, AC }, 	 //	 186	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, ST, LO, WN, PF, AC }, 	 //	 187	 9000
{ AC, LO, KN, KN, KN, AC, KN, KN, KN, KN, ST, KN, KN, KN, KN }, 	 //	 188	 9000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, ST, ST, KN, KN, KN }, 	 //	 189	 9000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, ST, ST, KN, KN, KN }, 	 //	 190	 9000
{ AC, WN, AC, AC, LO, AC, AC, AC, AC, AC, ST, KN, AC, LO, AC }, 	 //	 191	 9000
{ AC, WN, AC, WN, LO, AC, AC, AC, AC, AC, ST, KN, AC, KN, AC }, 	 //	 192	 9000
{ AC, TN, SH, PF, AC, AC, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 193	 9000
{ AC, TN, AC, AC, TN, AC, AC, AC, AC, AC, ST, AC, AC, PF, AC }, 	 //	 194	 9000
{ AC, TN, TN, PF, LO, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 195	 9000
{ AC, TN, TN, PF, TN, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 196	 9000
{ AC, TN, TN, AC, LO, AC, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 197	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, ST, AC, AC, AC, QN }, 	 //	 198	 9000
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 199	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 200	 9000
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, ST, AC, AC, AC, KN }, 	 //	 201	 9000
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 202	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, ST, AC, AC, AC, ST }, 	 //	 203	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 204	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, ST, AC, PF, LO, AC }, 	 //	 205	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, ST, AC, PF, PF, AC }, 	 //	 206	 9000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 207	 9000
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 208	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, ST, AC, AC, AC, TN }, 	 //	 209	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 210	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 211	 9000
{ AC, AC, AC, AC, LO, AC, AC, AC, AC, AC, ST, PF, PF, LO, AC }, 	 //	 212	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, ST, PF, PF, AC, AC }, 	 //	 213	 9000
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, ST, PF, AC, AC, AC }, 	 //	 214	 9000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, ST, SK, KN, KN, KN }, 	 //	 215	 9000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, ST, SK, KN, KN, KN }, 	 //	 216	 9000
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, AC, ST, SH, AC, LO, AC }, 	 //	 217	 9000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, ST, SH, AC, PF, AC }, 	 //	 218	 9000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, ST, SH, AC, PF, AC }, 	 //	 219	 9000
{ AC, SH, SH, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 220	 9000
{ AC, AC, SH, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 221	 9000
{ AC, AC, AC, PF, TN, ST, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 222	 9000
{ AC, AC, AC, AC, ST, ST, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 223	 9000
{ AC, AC, AC, TN, TN, ST, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 224	 9000
{ AC, AC, AC, AC, TN, ST, AC, AC, AC, ST, KN, LO, AC, AC, AC }, 	 //	 225	 9000
{ AC, LO, KN, LO, CR, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 226	 9000
{ AC, LO, KN, LO, SK, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 227	 9000
{ AC, LO, KN, KN, CR, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 228	 9000
{ AC, KN, KN, KN, ST, ST, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 229	 9000
{ AC, AC, KN, KN, KN, ST, KN, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 230	 9000
{ AC, TN, TN, PF, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 231	 9000
{ AC, AC, SH, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 232	 9000
{ AC, AC, AC, PF, QN, ST, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 233	 9000
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 234	 9000
{ AC, AC, TN, TN, AC, ST, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 235	 9000
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, KN, KN, PF, AC, AC, AC }, 	 //	 236	 9000
{ AC, AC, AC, TN, LO, ST, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 237	 9000
{ AC, AC, AC, AC, AC, ST, AC, AC, AC, AC, KN, PF, PF, AC, AC }, 	 //	 238	 9000
{ AC, PF, KN, KN, KN, ST, KN, KN, KN, KN, KN, KN, KN, SK, KN }, 	 //	 239	 9000
{ AC, KN, KN, LO, CR, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 240	 9000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 241	 9000
{ AC, KN, KN, PF, SK, ST, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 242	 9000
{ AC, KN, KN, KN, ST, ST, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 243	 9000
{ ST, SH, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 244	 9000
{ ST, LO, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 245	 9000
{ ST, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, SK }, 	 //	 246	 9000
{ ST, LO, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 247	 9000
{ ST, LO, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 248	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, WN, PF }, 	 //	 249	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, WN, LO }, 	 //	 250	 9000
{ ST, KN, KN, PF, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 251	 9000
{ ST, KN, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 252	 9000
{ ST, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 253	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, SK, PF }, 	 //	 254	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, KN, SK }, 	 //	 255	 9000
{ ST, KN, KN, KN, CR, KN, KN, KN, KN, KN, KN, ST, KN, KN, KN }, 	 //	 256	 9000
{ ST, KN, KN, KN, SK, KN, KN, KN, KN, KN, KN, ST, KN, KN, KN }, 	 //	 257	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, KN, KN, SK }, 	 //	 258	 9000
{ ST, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 259	 9000
{ ST, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 260	 9000
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 261	 9000
{ ST, PF, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 262	 9000
{ ST, PF, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK }, 	 //	 263	 9000
{ ST, PF, KN, LO, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 264	 9000
{ ST, PF, KN, PF, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 265	 9000
{ ST, KN, KN, PF, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 266	 9000
{ ST, KN, KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 267	 9000
{ ST, KN, KN, KN, CR, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN }, 	 //	 268	 9000
{ ST, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, CR }, 	 //	 269	 9000
{ ST, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, WN, KN }, 	 //	 270	 9000
{ ST, QN, KN, PF, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 271	 9000
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 272	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 273	 9000
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 274	 9000
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 275	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, LO, AC, AC, AC }, 	 //	 276	 9000
{ KN, LO, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 277	 9000
{ KN, LO, KN, AC, SK, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN }, 	 //	 278	 9000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 279	 9000
{ KN, LO, KN, LO, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 280	 9000
{ KN, LO, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, CR }, 	 //	 281	 9000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 282	 9000
{ KN, LO, KN, PF, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 283	 9000
{ KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 284	 9000
{ KN, KN, KN, LO, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 285	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, QN }, 	 //	 286	 9000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN }, 	 //	 287	 9000
{ KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, WN, ST }, 	 //	 288	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, QN, KN, KN, KN, QN, PF }, 	 //	 289	 9000
{ KN, KN, KN, AC, CR, KN, KN, KN, KN, QN, KN, KN, KN, QN, KN }, 	 //	 290	 9000
{ KN, KN, KN, PF, TN, KN, KN, KN, KN, ST, KN, KN, KN, KN, AC }, 	 //	 291	 9000
{ KN, KN, KN, PF, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA }, 	 //	 292	 9000
{ KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, SK, QN }, 	 //	 293	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, SK, QN }, 	 //	 294	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SH, KN, KN }, 	 //	 295	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SH, SK, KN }, 	 //	 296	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 297	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, WN, AC }, 	 //	 298	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, WN, CR }, 	 //	 299	 9000
{ KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, WN, QN }, 	 //	 300	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, WN, JA }, 	 //	 301	 9000
{ KN, KN, KN, AC, CR, KN, KN, KN, KN, QN, KN, KN, KN, QN, KN }, 	 //	 302	 9000
{ KN, KN, KN, AC, QN, KN, KN, KN, KN, KN, KN, KN, KN, QN, AC }, 	 //	 303	 9000
{ KN, KN, KN, PF, LO, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 304	 9000
{ KN, KN, KN, PF, SH, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA }, 	 //	 305	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, SK, SH }, 	 //	 306	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, KN, KN, SK, JA }, 	 //	 307	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, SK, KN, KN, KN, AC, QN }, 	 //	 308	 9000
{ KN, KN, KN, QN, QN, KN, KN, KN, KN, KN, KN, KN, KN, AC, AC }, 	 //	 309	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, ST, KN, KN, AC }, 	 //	 310	 9000
{ KN, KN, KN, AC, CR, KN, KN, KN, KN, KN, KN, ST, KN, QN, KN }, 	 //	 311	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, SH, KN, KN }, 	 //	 312	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, PF, WN, KN }, 	 //	 313	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 314	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 315	 9000
{ KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, SK }, 	 //	 316	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 317	 9000
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 318	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, PF, AC, AC, AC }, 	 //	 319	 9000
{ KN, PF, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 320	 9000
{ KN, PF, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 321	 9000
{ KN, PF, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, CR }, 	 //	 322	 9000
{ KN, PF, KN, PF, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN }, 	 //	 323	 9000
{ KN, PF, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN }, 	 //	 324	 9000
{ KN, PF, KN, KN, CR, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN }, 	 //	 325	 9000
{ KN, PF, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, WN, QN }, 	 //	 326	 9000
{ KN, PF, KN, PF, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN }, 	 //	 327	 9000
{ KN, PF, KN, PF, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 328	 9000
{ KN, PF, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 329	 9000
{ KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 330	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 331	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, WN, TN }, 	 //	 332	 9000
{ KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, WN, TN }, 	 //	 333	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, WN, JA }, 	 //	 334	 9000
{ KN, KN, KN, KN, PF, KN, KN, KN, KN, JA, KN, KN, KN, WN, TN }, 	 //	 335	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, QN, KN, KN, KN, QN, PF }, 	 //	 336	 9000
{ KN, KN, KN, PF, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 337	 9000
{ KN, KN, KN, PF, WN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN }, 	 //	 338	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, SK }, 	 //	 339	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, SK, CR }, 	 //	 340	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, SK, TN }, 	 //	 341	 9000
{ KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, SK, TN }, 	 //	 342	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, SK, JA }, 	 //	 343	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, AC, KN, KN, KN, AC, LO }, 	 //	 344	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SH, SK, KN }, 	 //	 345	 9000
{ KN, KN, WN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 346	 9000
{ KN, KN, KN, AC, ST, KN, KN, KN, KN, AC, KN, KN, KN, QN, KN }, 	 //	 347	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, CR }, 	 //	 348	 9000
{ KN, KN, KN, PF, PF, KN, KN, KN, KN, JA, KN, KN, KN, KN, TN }, 	 //	 349	 9000
{ KN, KN, KN, PF, JA, KN, KN, KN, KN, TN, KN, KN, KN, KN, AC }, 	 //	 350	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, SK, TN }, 	 //	 351	 9000
{ KN, KN, KN, QN, AC, KN, KN, KN, KN, KN, KN, KN, KN, AC, QN }, 	 //	 352	 9000
{ KN, KN, KN, QN, QN, KN, KN, KN, KN, KN, KN, KN, KN, AC, AC }, 	 //	 353	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, SH, SK, KN }, 	 //	 354	 9000
{ KN, KN, KN, LO, CR, KN, KN, KN, KN, QN, KN, SK, KN, KN, KN }, 	 //	 355	 9000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, QN, KN, SK, KN, KN, KN }, 	 //	 356	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, SK, KN, SK, QN }, 	 //	 357	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, SK, KN, SK, KN }, 	 //	 358	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, PF, WN, KN }, 	 //	 359	 9000
{ KN, QN, KN, LO, SK, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 360	 9000
{ KN, QN, KN, KN, CR, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 361	 9000
{ KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, CR }, 	 //	 362	 9000
{ KN, QN, KN, QN, KN, KN, KN, KN, KN, KN, KN, AC, KN, AC, KN }, 	 //	 363	 9000
{ KN, QN, KN, KN, SK, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 364	 9000
{ KN, QN, KN, KN, SK, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 365	 9000
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 366	 9000
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, LO, SK, AC, AC, AC, AC }, 	 //	 367	 9000
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 368	 9000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, SK }, 	 //	 369	 9000
{ KN, LO, KN, PF, SK, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 370	 9000
{ KN, LO, KN, KN, CR, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 371	 9000
{ KN, LO, KN, KN, SK, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 372	 9000
{ KN, KN, KN, KN, SK, KN, KN, KN, KN, KN, SK, KN, KN, WN, KN }, 	 //	 373	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, SK, KN, KN, KN, QN }, 	 //	 374	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, SK, KN, KN, SK, QN }, 	 //	 375	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, SK, KN, KN, SK, PF }, 	 //	 376	 9000
{ KN, KN, KN, LO, ST, KN, KN, KN, KN, AC, SK, KN, KN, KN, KN }, 	 //	 377	 9000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, KN, SK, KN, KN, SK, KN }, 	 //	 378	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, SK, KN, KN, SK, QN }, 	 //	 379	 9000
{ KN, KN, KN, LO, SK, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 380	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, SK, ST, KN, QN, KN }, 	 //	 381	 9000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 382	 9000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, KN, SK, ST, KN, SK, KN }, 	 //	 383	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, SK, ST, KN, AC, KN }, 	 //	 384	 9000
{ KN, KN, KN, LO, SK, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 385	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, SK, ST, KN, WN, QN }, 	 //	 386	 9000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 387	 9000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, SK, ST, KN, KN, KN }, 	 //	 388	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, SK, ST, KN, SK, PF }, 	 //	 389	 9000
{ KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, SK, QN, KN, SK, KN }, 	 //	 390	 9000
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 391	 9000
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 392	 9000
{ KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, SK }, 	 //	 393	 9000
{ KN, PF, KN, KN, CR, KN, KN, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 394	 9000
{ KN, KN, KN, LO, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, SK }, 	 //	 395	 9000
{ KN, KN, KN, LO, ST, KN, KN, KN, KN, AC, SK, KN, KN, KN, KN }, 	 //	 396	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, SK, KN, KN, KN, QN }, 	 //	 397	 9000
{ KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, SK, AC, KN, WN, KN }, 	 //	 398	 9000
{ KN, SH, AC, AC, AC, SK, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 399	 9000
{ KN, LO, KN, LO, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 400	 9000
{ KN, LO, KN, LO, KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 401	 9000
{ KN, KN, KN, LO, CR, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 402	 9000
{ KN, KN, KN, KN, ST, SK, KN, KN, KN, AC, QN, KN, KN, KN, KN }, 	 //	 403	 9000
{ KN, KN, KN, KN, ST, SK, KN, KN, KN, AC, QN, KN, KN, KN, KN }, 	 //	 404	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, QN, QN, KN, KN, KN, PF }, 	 //	 405	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, SK, QN, KN, KN, KN, QN }, 	 //	 406	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, AC, QN, KN, KN, KN, LO }, 	 //	 407	 9000
{ KN, TN, AC, AC, AC, SK, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 408	 9000
{ KN, AC, AC, AC, LO, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 409	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, KN, KN, WN, SK }, 	 //	 410	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, QN, QN, KN, KN, KN, PF }, 	 //	 411	 9000
{ KN, KN, KN, KN, CR, SK, KN, KN, KN, QN, QN, KN, KN, KN, KN }, 	 //	 412	 9000
{ KN, KN, KN, PF, CR, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 413	 9000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, SK, KN, WN, SK }, 	 //	 414	 9000
{ KN, KN, AC, AC, AC, SK, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 415	 9000
{ KN, KN, AC, AC, AC, SK, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 416	 9000
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 417	 9000
{ SK, LO, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 418	 9000
{ SK, WN, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 419	 9000
{ SK, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 420	 9000
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 421	 9000
{ SK, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 422	 9000
{ SK, AC, AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 423	 9000
{ SK, PF, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 424	 9000
{ SK, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 425	 9000
{ SK, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 426	 9000
{ QN, LO, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 427	 9000
{ QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, ST, KN, KN, KN }, 	 //	 428	 9000
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 429	 9000
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 430	 9000
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 431	 9000
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 432	 9000
{ QN, KN, AC, AC, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 433	 9000
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, CR }, 	 //	 434	 9000
{ QN, LO, KN, KN, KN, QN, KN, KN, KN, KN, SH, KN, KN, KN, KN }, 	 //	 435	 9000
{ QN, LO, KN, KN, KN, QN, KN, KN, KN, KN, SH, KN, KN, KN, KN }, 	 //	 436	 9000
{ QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH, ST, KN, KN, KN }, 	 //	 437	 9000
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, CR }, 	 //	 438	 9000
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 439	 9000
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, SK }, 	 //	 440	 9000
{ QN, AC, AC, AC, LO, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 441	 9000
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, LO, JA, LO, AC, AC, AC }, 	 //	 442	 9000
{ QN, LO, KN, KN, KN, SH, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 443	 9000
{ QN, LO, KN, KN, KN, SH, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 444	 9000
{ QN, KN, KN, KN, KN, SH, KN, KN, KN, KN, JA, ST, KN, KN, KN }, 	 //	 445	 9000
{ QN, WN, AC, AC, AC, SH, AC, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 446	 9000
{ QN, KN, KN, KN, KN, SH, KN, KN, KN, KN, JA, SK, KN, KN, KN }, 	 //	 447	 9000
{ SH, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, ST, KN, KN, KN }, 	 //	 448	 9000
{ SH, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, ST, KN, KN, KN }, 	 //	 449	 9000
{ SH, PF, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 450	 9000
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 451	 9000
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 452	 9000
{ JA, AC, AC, AC, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 453	 9000
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 454	 9000
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 455	 9000
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA, LO, AC, AC, AC }, 	 //	 456	 9000
{ JA, LO, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 457	 9000
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 458	 9000
{ JA, PF, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 459	 9000
{ JA, AC, AC, AC, LO, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 460	 9000
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 461	 9000
{ JA, KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, ST, KN, KN, KN }, 	 //	 462	 9000
{ JA, KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, SK, KN, KN, KN }, 	 //	 463	 9000
{ JA, KN, AC, AC, AC, JA, AC, AC, AC, AC, WN, SH, AC, AC, AC }, 	 //	 464	 9000
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 465	 9000
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 466	 9000
{ JA, LO, KN, KN, KN, WN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 467	 9000
{ JA, WN, AC, AC, AC, WN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 468	 9000
{ JA, PF, KN, KN, KN, WN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 469	 9000
{ JA, KN, KN, KN, KN, WN, KN, KN, KN, KN, TN, SK, KN, KN, KN }, 	 //	 470	 9000
{ JA, KN, KN, KN, KN, WN, KN, KN, KN, KN, TN, SK, KN, KN, KN }, 	 //	 471	 9000
{ JA, KN, AC, AC, AC, WN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 472	 9000
{ JA, KN, AC, AC, AC, WN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 473	 9000
{ JA, KN, AC, AC, AC, WN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 474	 9000
{ WN, SH, AC, AC, AC, TN, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 475	 9000
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 476	 9000
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 477	 9000
{ WN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, ST, KN, KN, KN }, 	 //	 478	 9000
{ WN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, ST, KN, KN, KN }, 	 //	 479	 9000
{ WN, WN, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 480	 9000
{ WN, WN, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 481	 9000
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 482	 9000
{ WN, PF, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 483	 9000
{ WN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, SK, KN, KN, KN }, 	 //	 484	 9000
{ TN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 485	 9000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 486	 9000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, PF, AC, AC, AC }, 	 //	 487	 9000
{ TN, PF, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 488	 9000
{ TN, PF, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 489	 9000
{ TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, SK, KN, KN, KN }, 	 //	 490	 9000
{ TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 491	 9000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 492	 9000
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 493	 9000
{ TN, AC, AC, AC, LO, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 494	 9000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, SK }, 	 //	 495	 9000
{ TN, LO, KN, KN, KN, TN, KN, KN, KN, KN, ST, KN, KN, KN, KN }, 	 //	 496	 9000
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 497	 9000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, ST, PF, AC, AC, AC }, 	 //	 498	 9000
{ TN, PF, KN, KN, KN, TN, KN, KN, KN, KN, ST, KN, KN, KN, KN }, 	 //	 499	 9000
{ TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 500	 9000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 501	 9000
{ TN, SH, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 502	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, LO, AC }, 	 //	 503	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 504	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 505	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 506	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, LO, PF, AC, AC }, 	 //	 507	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, LO, WN, AC, AC }, 	 //	 508	 9000
{ TN, KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 509	 9000
{ TN, WN, AC, KN, AC, ST, AC, AC, AC, AC, AC, KN, AC, PF, AC }, 	 //	 510	 9000
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 511	 9000
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 512	 9000
{ TN, AC, TN, TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 513	 9000
{ TN, AC, AC, AC, ST, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 514	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, WN, PF, AC }, 	 //	 515	 9000
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, PF, PF, AC, AC }, 	 //	 516	 9000
{ TN, KN, AC, KN, AC, ST, AC, AC, AC, AC, AC, SH, AC, PF, AC }, 	 //	 517	 9000
{ ST, SH, SH, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 518	 9000
{ ST, SH, SH, TN, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 519	 9000
{ ST, SH, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 520	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 521	 9000
{ ST, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 522	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, LO, AC }, 	 //	 523	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 524	 9000
{ ST, AC, TN, PF, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 525	 9000
{ ST, AC, AC, AC, TN, AC, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 526	 9000
{ ST, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, LO, AC, PF, AC }, 	 //	 527	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO, PF, LO, AC }, 	 //	 528	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO, WN, AC, AC }, 	 //	 529	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO, WN, AC, AC }, 	 //	 530	 9000
{ ST, LO, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, SK }, 	 //	 531	 9000
{ ST, LO, KN, LO, SK, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 532	 9000
{ ST, LO, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, SK }, 	 //	 533	 9000
{ ST, LO, KN, KN, SK, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 534	 9000
{ ST, KN, KN, PF, SK, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 535	 9000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 536	 9000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 537	 9000
{ ST, KN, KN, KN, CR, AC, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 538	 9000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, ST, KN, SK, KN }, 	 //	 539	 9000
{ ST, WN, AC, KN, AC, AC, AC, AC, AC, AC, KN, KN, AC, PF, AC }, 	 //	 540	 9000
{ ST, AC, KN, KN, KN, AC, KN, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 541	 9000
{ ST, AC, KN, KN, KN, AC, KN, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 542	 9000
{ ST, TN, AC, WN, AC, AC, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 543	 9000
{ ST, AC, AC, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 544	 9000
{ ST, AC, TN, PF, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 545	 9000
{ ST, AC, AC, AC, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 546	 9000
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, WN, PF, AC }, 	 //	 547	 9000
{ ST, PF, KN, LO, CR, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 548	 9000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 549	 9000
{ ST, KN, KN, KN, ST, AC, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 550	 9000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 551	 9000
{ ST, QN, KN, KN, KN, AC, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 552	 9000
{ ST, KN, AC, WN, AC, AC, AC, AC, AC, AC, KN, SH, AC, KN, AC }, 	 //	 553	 9000
{ ST, KN, AC, AC, AC, AC, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 554	 9000
{ AC, SH, SH, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 555	 9000
{ AC, SH, SH, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 556	 9000
{ AC, SH, TN, PF, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 557	 9000
{ AC, AC, AC, PF, QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 558	 9000
{ AC, AC, TN, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 559	 9000
{ AC, AC, TN, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 560	 9000
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, WN, AC, AC }, 	 //	 561	 9000
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, WN, AC, AC }, 	 //	 562	 9000
{ AC, AC, AC, PF, TN, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 563	 9000
{ AC, AC, AC, AC, JA, KN, AC, AC, AC, TN, QN, LO, AC, AC, AC }, 	 //	 564	 9000
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, LO, WN, AC, AC }, 	 //	 565	 9000
{ AC, KN, KN, LO, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 566	 9000
{ AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, WN, KN }, 	 //	 567	 9000
{ AC, AC, SH, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 568	 9000
{ AC, AC, SH, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 569	 9000
{ AC, AC, TN, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 570	 9000
{ AC, AC, TN, TN, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 571	 9000
{ AC, AC, AC, PF, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 572	 9000
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, WN, LO, AC }, 	 //	 573	 9000
{ AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 574	 9000
{ AC, AC, AC, AC, QN, KN, AC, AC, AC, KN, QN, PF, AC, AC, AC }, 	 //	 575	 9000
{ AC, AC, AC, AC, TN, KN, AC, AC, AC, ST, QN, PF, AC, AC, AC }, 	 //	 576	 9000
{ AC, KN, KN, KN, CR, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 577	 9000
{ AC, KN, KN, PF, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 578	 9000
{ AC, KN, KN, KN, CR, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 579	 9000
{ AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, SK, KN, WN, KN }, 	 //	 580	 9000
{ AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, SK, KN, SK, KN }, 	 //	 581	 9000
{ AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, SK, KN, WN, KN }, 	 //	 582	 9000
{ AC, KN, AC, WN, AC, KN, AC, AC, AC, AC, QN, SH, AC, KN, AC }, 	 //	 583	 9000
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, CR }, 	 //	 584	 9000
{ KN, AC, AC, AC, TN, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 585	 9000
{ KN, KN, KN, KN, CR, QN, KN, KN, KN, QN, PF, KN, KN, KN, KN }, 	 //	 586	 9000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, AC, PF, KN, KN, KN, LO }, 	 //	 587	 9000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, QN, PF, KN, KN, KN, PF }, 	 //	 588	 9000
{ KN, KN, KN, KN, CR, QN, KN, KN, KN, QN, PF, KN, KN, KN, KN }, 	 //	 589	 9000
{ KN, KN, KN, KN, CR, QN, KN, KN, KN, KN, PF, ST, KN, KN, KN }, 	 //	 590	 9000
{ KN, KN, KN, KN, CR, QN, KN, KN, KN, KN, PF, ST, KN, KN, KN }, 	 //	 591	 9000
{ KN, WN, AC, AC, AC, QN, AC, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 592	 9000
{ KN, WN, AC, AC, AC, QN, AC, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 593	 9000
{ KN, AC, KN, KN, KN, QN, KN, KN, KN, KN, PF, QN, KN, KN, KN }, 	 //	 594	 9000
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, CR }, 	 //	 595	 9000
{ KN, PF, KN, PF, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 596	 9000
{ KN, PF, KN, LO, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 597	 9000
{ KN, KN, KN, LO, CR, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN }, 	 //	 598	 9000
{ KN, KN, KN, KN, ST, QN, KN, KN, KN, AC, PF, KN, KN, KN, KN }, 	 //	 599	 9000
{ KN, KN, KN, KN, ST, QN, KN, KN, KN, AC, PF, KN, KN, KN, KN }, 	 //	 600	 9000
{ KN, KN, KN, KN, ST, QN, KN, KN, KN, AC, PF, KN, KN, KN, KN }, 	 //	 601	 9000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, AC, PF, KN, KN, KN, LO }, 	 //	 602	 9000
{ KN, QN, KN, KN, KN, QN, KN, KN, KN, KN, PF, AC, KN, KN, KN }, 	 //	 603	 9000
{ QN, SH, AC, AC, AC, PF, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 604	 9000
{ QN, AC, AC, AC, LO, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 605	 9000
{ QN, LO, KN, KN, KN, PF, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 606	 9000
{ QN, LO, KN, KN, KN, PF, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 607	 9000
{ QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA, ST, KN, KN, KN }, 	 //	 608	 9000
{ QN, WN, AC, AC, AC, PF, AC, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 609	 9000
{ QN, TN, AC, AC, AC, PF, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 610	 9000
{ QN, PF, KN, KN, KN, PF, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 611	 9000
{ QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA, SK, KN, KN, KN }, 	 //	 612	 9000
{ QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA, SK, KN, KN, KN }, 	 //	 613	 9000
{ PF, AC, AC, AC, LO, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 614	 9000
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, LO, TN, LO, AC, AC, AC }, 	 //	 615	 9000
{ PF, TN, AC, AC, AC, JA, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 616	 9000
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 617	 9000
{ PF, PF, KN, KN, KN, JA, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 618	 9000
{ PF, KN, KN, KN, KN, JA, KN, KN, KN, KN, TN, SK, KN, KN, KN }, 	 //	 619	 9000
{ PF, KN, AC, AC, AC, JA, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 620	 9000
{ JA, SH, SH, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 621	 9000
{ JA, SH, TN, PF, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 622	 9000
{ JA, AC, SH, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 623	 9000
{ JA, AC, SH, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 624	 9000
{ JA, AC, TN, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 625	 9000
{ JA, AC, AC, KN, AC, TN, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 626	 9000
{ JA, LO, KN, KN, KN, TN, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 627	 9000
{ JA, KN, KN, KN, KN, TN, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 628	 9000
{ JA, TN, TN, PF, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC }, 	 //	 629	 9000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 630	 9000
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, SK }, 	 //	 631	 9000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 632	 9000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC }, 	 //	 633	 9000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 634	 9000
{ JA, AC, AC, AC, AC, TN, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 635	 9000
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 636	 9000
{ TN, SH, SH, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 637	 9000
{ TN, SH, SH, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 638	 9000
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, LO, KN }, 	 //	 639	 9000
{ TN, AC, SH, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 640	 9000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 641	 9000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 642	 9000
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 643	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, PF, AC, AC }, 	 //	 644	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, AC, SK }, 	 //	 645	 9000
{ TN, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 646	 9000
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 647	 9000
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 648	 9000
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 649	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, LO, SK }, 	 //	 650	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, PF, PF, CR }, 	 //	 651	 9000
{ TN, AC, AC, PF, AC, AC, AC, AC, AC, AC, AC, LO, AC, AC, CR }, 	 //	 652	 9000
{ TN, LO, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 653	 9000
{ TN, TN, SH, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, AC }, 	 //	 654	 9000
{ TN, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 655	 9000
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 656	 9000
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 657	 9000
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 658	 9000
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 659	 9000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 660	 9000
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 661	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, PF, SK }, 	 //	 662	 9000
{ TN, AC, TN, PF, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 663	 9000
{ TN, AC, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 664	 9000
{ TN, AC, TN, TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 665	 9000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 666	 9000
{ TN, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 667	 9000
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 668	 9000
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 669	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, WN, PF, SK }, 	 //	 670	 9000
{ TN, AC, AC, WN, AC, AC, AC, AC, AC, LO, AC, PF, AC, KN, AC }, 	 //	 671	 9000
{ TN, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, CR }, 	 //	 672	 9000
{ TN, AC, AC, AC, AC, AC, AC, AC, AC, AC, AC, PF, WN, PF, CR }, 	 //	 673	 9000
{ TN, KN, AC, WN, AC, AC, AC, AC, AC, AC, AC, SH, AC, KN, SK }, 	 //	 674	 9000
{ AC, AC, SH, PF, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 675	 9000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 676	 9000
{ AC, AC, SH, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC, AC }, 	 //	 677	 9000
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 678	 9000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, CR }, 	 //	 679	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, AC, PF, LO, AC }, 	 //	 680	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, PF, PF, AC }, 	 //	 681	 9000
{ AC, AC, TN, PF, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 682	 9000
{ AC, AC, AC, WN, SK, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN }, 	 //	 683	 9000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 684	 9000
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, WN, AC, AC, AC, PF, TN }, 	 //	 685	 9000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, QN, AC, AC, AC, PF, PF }, 	 //	 686	 9000
{ AC, AC, AC, KN, PF, AC, AC, AC, AC, JA, AC, AC, AC, PF, TN }, 	 //	 687	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, WN, AC, AC }, 	 //	 688	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, WN, AC, QN }, 	 //	 689	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, PF, AC, LO }, 	 //	 690	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, LO, PF, LO, AC }, 	 //	 691	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, LO, PF, AC, LO }, 	 //	 692	 9000
{ AC, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, LO, WN, AC, KN }, 	 //	 693	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, LO, WN, AC, QN }, 	 //	 694	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, LO, WN, AC, AC }, 	 //	 695	 9000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 696	 9000
{ AC, WN, AC, PF, KN, AC, AC, AC, AC, AC, AC, KN, AC, AC, LO }, 	 //	 697	 9000
{ AC, WN, AC, KN, AC, AC, AC, AC, AC, SK, AC, KN, AC, PF, KN }, 	 //	 698	 9000
{ AC, WN, AC, KN, KN, AC, AC, AC, AC, AC, AC, KN, AC, PF, LO }, 	 //	 699	 9000
{ AC, TN, SH, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 700	 9000
{ AC, TN, SH, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 701	 9000
{ AC, TN, TN, PF, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 702	 9000
{ AC, TN, TN, PF, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 703	 9000
{ AC, TN, TN, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 704	 9000
{ AC, TN, TN, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 705	 9000
{ AC, TN, TN, AC, KN, AC, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 706	 9000
{ AC, AC, SH, AC, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 707	 9000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, JA, AC, AC, AC, KN, WN }, 	 //	 708	 9000
{ AC, AC, AC, WN, WN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 709	 9000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, PF, AC, AC, AC, KN, JA }, 	 //	 710	 9000
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 711	 9000
{ AC, AC, AC, KN, PF, AC, AC, AC, AC, JA, AC, AC, AC, PF, TN }, 	 //	 712	 9000
{ AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 713	 9000
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, CR }, 	 //	 714	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, PF, LO, KN }, 	 //	 715	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, PF, PF, AC }, 	 //	 716	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, PF, PF, AC }, 	 //	 717	 9000
{ AC, AC, TN, PF, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 718	 9000
{ AC, AC, TN, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 719	 9000
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, WN, AC, AC, AC, KN, TN }, 	 //	 720	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, WN, AC, AC }, 	 //	 721	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, WN, LO, AC }, 	 //	 722	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, WN, LO, LO }, 	 //	 723	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, WN, AC, KN }, 	 //	 724	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, WN, PF, KN }, 	 //	 725	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, WN, PF, AC }, 	 //	 726	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, PF, LO, AC }, 	 //	 727	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, AC, AC, PF, PF, LO, LO }, 	 //	 728	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, PF, AC, AC }, 	 //	 729	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, PF, AC, AC }, 	 //	 730	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, WN, LO, AC }, 	 //	 731	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, SK, AC, PF, WN, LO, KN }, 	 //	 732	 9000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, KN, AC, SH, AC, KN, QN }, 	 //	 733	 9000
{ AC, KN, AC, KN, ST, AC, AC, AC, AC, AC, AC, SH, AC, PF, KN }, 	 //	 734	 9000
{ AC, KN, AC, PF, ST, AC, AC, AC, AC, AC, AC, SH, AC, AC, KN }, 	 //	 735	 9000
{ AC, KN, AC, AC, QN, AC, AC, AC, AC, KN, AC, SH, AC, LO, AC }, 	 //	 736	 9000
{ AC, KN, AC, AC, KN, AC, AC, AC, AC, AC, AC, SH, AC, LO, LO }, 	 //	 737	 9000
{ AC, KN, AC, WN, TN, AC, AC, AC, AC, ST, AC, SH, AC, KN, AC }, 	 //	 738	 9000
{ AC, KN, AC, TN, AC, AC, AC, AC, AC, SK, AC, SH, AC, AC, KN }, 	 //	 739	 9000
{ AC, KN, AC, AC, JA, AC, AC, AC, AC, TN, AC, SH, AC, PF, AC }, 	 //	 740	 9000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 741	 9000
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 742	 9000
{ AC, SH, TN, TN, LO, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 743	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, SK, AC, AC, AC, PF }, 	 //	 744	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 745	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN }, 	 //	 746	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 747	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, SK, AC, AC, AC, TN }, 	 //	 748	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 749	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK, AC, WN, PF, AC }, 	 //	 750	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, SK, AC, WN, PF, AC }, 	 //	 751	 9000
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, SK, LO, AC, AC, AC }, 	 //	 752	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK, LO, PF, PF, AC }, 	 //	 753	 9000
{ AC, WN, AC, AC, LO, AC, AC, AC, AC, AC, SK, KN, AC, PF, AC }, 	 //	 754	 9000
{ AC, TN, SH, TN, TN, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 755	 9000
{ AC, TN, AC, AC, LO, AC, AC, AC, AC, AC, SK, AC, AC, LO, AC }, 	 //	 756	 9000
{ AC, TN, TN, PF, TN, AC, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 757	 9000
{ AC, AC, SH, PF, AC, AC, AC, AC, AC, LO, SK, AC, AC, AC, AC }, 	 //	 758	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, SK, AC, AC, AC, PF }, 	 //	 759	 9000
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, SK, AC, AC, AC, JA }, 	 //	 760	 9000
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, SK, AC, AC, AC, KN }, 	 //	 761	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 762	 9000
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN }, 	 //	 763	 9000
{ AC, AC, TN, AC, AC, AC, AC, AC, AC, LO, SK, AC, AC, AC, AC }, 	 //	 764	 9000
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 765	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 766	 9000
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, WN }, 	 //	 767	 9000
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, ST, SK, PF, AC, AC, AC }, 	 //	 768	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK, PF, PF, LO, AC }, 	 //	 769	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK, PF, WN, AC, AC }, 	 //	 770	 9000
{ AC, AC, AC, AC, AC, AC, AC, AC, AC, LO, SK, PF, WN, LO, AC }, 	 //	 771	 9000
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, AC, SK, PF, WN, PF, AC }, 	 //	 772	 9000
{ AC, PF, KN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 773	 9000
{ AC, KN, AC, WN, AC, AC, AC, AC, AC, LO, SK, SH, AC, KN, AC }, 	 //	 774	 9000
{ AC, KN, AC, WN, LO, AC, AC, AC, AC, AC, SK, SH, AC, KN, AC }, 	 //	 775	 9000
{ AC, KN, AC, AC, LO, AC, AC, AC, AC, AC, SK, SH, AC, PF, AC }, 	 //	 776	 9000
{ AC, SH, SH, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 777	 9000
{ AC, SH, SH, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 778	 9000
{ AC, SH, TN, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 779	 9000
{ AC, SH, AC, KN, AC, SK, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 780	 9000
{ AC, AC, SH, PF, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 781	 9000
{ AC, AC, SH, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 782	 9000
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 783	 9000
{ AC, AC, AC, AC, ST, SK, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 784	 9000
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, PF, PF, AC }, 	 //	 785	 9000
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, WN, PF, AC }, 	 //	 786	 9000
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, LO, PF, LO, AC }, 	 //	 787	 9000
{ AC, AC, AC, PF, LO, SK, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 788	 9000
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, LO, WN, AC, AC }, 	 //	 789	 9000
{ AC, LO, KN, KN, KN, SK, KN, KN, KN, KN, KN, KN, KN, SK, KN }, 	 //	 790	 9000
{ AC, LO, KN, LO, CR, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 791	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 792	 9000
{ AC, KN, KN, KN, AC, SK, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 793	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 794	 9000
{ AC, WN, AC, KN, AC, SK, AC, AC, AC, AC, KN, KN, AC, PF, AC }, 	 //	 795	 9000
{ AC, TN, TN, PF, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 796	 9000
{ AC, TN, TN, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 797	 9000
{ AC, TN, AC, KN, AC, SK, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 798	 9000
{ AC, TN, AC, KN, AC, SK, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 799	 9000
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 800	 9000
{ AC, AC, TN, TN, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 801	 9000
{ AC, AC, AC, TN, JA, SK, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 802	 9000
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 803	 9000
{ AC, AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, WN, AC, AC }, 	 //	 804	 9000
{ AC, AC, AC, TN, TN, SK, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 805	 9000
{ AC, AC, AC, AC, TN, SK, AC, AC, AC, ST, KN, PF, AC, AC, AC }, 	 //	 806	 9000
{ AC, PF, KN, LO, CR, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 807	 9000
{ AC, PF, KN, KN, SK, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 808	 9000
{ AC, PF, KN, KN, KN, SK, KN, KN, KN, KN, KN, KN, KN, WN, KN }, 	 //	 809	 9000
{ AC, PF, KN, PF, CR, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 810	 9000
{ AC, PF, KN, KN, CR, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 811	 9000
{ AC, KN, KN, LO, CR, SK, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 812	 9000
{ AC, KN, KN, KN, CR, SK, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 813	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 814	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN, KN, KN, WN, SK }, 	 //	 815	 9000
{ AC, KN, KN, KN, ST, SK, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 816	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 817	 9000
{ AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN, SK, KN, WN, KN }, 	 //	 818	 9000
{ AC, QN, KN, KN, KN, SK, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 819	 9000
{ AC, KN, AC, KN, AC, SK, AC, AC, AC, AC, KN, SH, AC, PF, AC }, 	 //	 820	 9000
{ SK, SH, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 821	 9000
{ SK, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 822	 9000
{ SK, LO, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 823	 9000
{ SK, LO, KN, LO, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 824	 9000
{ SK, LO, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 825	 9000
{ SK, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 826	 9000
{ SK, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN }, 	 //	 827	 9000
{ SK, KN, KN, PF, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 828	 9000
{ SK, KN, KN, PF, CR, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 829	 9000
{ SK, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, SK, QN }, 	 //	 830	 9000
{ SK, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, WN, LO }, 	 //	 831	 9000
{ SK, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN }, 	 //	 832	 9000
{ SK, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 833	 9000
{ SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 834	 9000
{ SK, PF, KN, LO, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 835	 9000
{ SK, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, WN, SK }, 	 //	 836	 9000
{ SK, PF, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN }, 	 //	 837	 9000
{ SK, PF, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN }, 	 //	 838	 9000
{ SK, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 839	 9000
{ SK, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, KN }, 	 //	 840	 9000
{ SK, KN, KN, PF, AC, KN, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 841	 9000
{ SK, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 842	 9000
{ SK, KN, KN, KN, SK, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN }, 	 //	 843	 9000
{ SK, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN, WN, QN }, 	 //	 844	 9000
{ SK, KN, KN, PF, ST, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 845	 9000
{ SK, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN }, 	 //	 846	 9000
{ SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, WN, SK }, 	 //	 847	 9000
{ SK, KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN }, 	 //	 848	 9000
{ SK, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, SK, CR }, 	 //	 849	 9000
{ SK, KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, KN }, 	 //	 850	 9000
{ SK, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, WN, KN }, 	 //	 851	 9000
{ SK, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 852	 9000
{ KN, LO, PF, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 853	 9000
{ KN, LO, KN, KN, CR, KN, KN, KN, KN, KN, KN, KN, KN, WN, KN }, 	 //	 854	 9000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, WN, PF }, 	 //	 855	 9000
{ KN, LO, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, CR }, 	 //	 856	 9000
{ KN, LO, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 857	 9000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, WN, PF }, 	 //	 858	 9000
{ KN, LO, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, CR }, 	 //	 859	 9000
{ KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 860	 9000
{ KN, KN, PF, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 861	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 862	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, LO, KN, KN, KN, WN, AC }, 	 //	 863	 9000
{ KN, KN, KN, KN, LO, KN, KN, KN, KN, AC, KN, KN, KN, WN, AC }, 	 //	 864	 9000
{ KN, KN, KN, PF, SH, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA }, 	 //	 865	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, LO, KN, KN, KN, SK, AC }, 	 //	 866	 9000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, SK, AC }, 	 //	 867	 9000
{ KN, KN, KN, QN, CR, KN, KN, KN, KN, QN, KN, KN, KN, AC, KN }, 	 //	 868	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SH, KN, KN }, 	 //	 869	 9000
{ KN, KN, KN, LO, JA, KN, KN, KN, KN, WN, KN, KN, KN, KN, TN }, 	 //	 870	 9000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, ST }, 	 //	 871	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA }, 	 //	 872	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, WN, TN }, 	 //	 873	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, SK, KN, KN, KN, QN, QN }, 	 //	 874	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, CR }, 	 //	 875	 9000
{ KN, KN, KN, PF, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 876	 9000
{ KN, KN, KN, KN, SH, KN, KN, KN, KN, JA, KN, KN, KN, SK, JA }, 	 //	 877	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, SK, KN, KN, KN, AC, QN }, 	 //	 878	 9000
{ KN, KN, KN, LO, KN, KN, KN, KN, KN, KN, KN, ST, KN, KN, CR }, 	 //	 879	 9000
{ KN, KN, KN, LO, CR, KN, KN, KN, KN, QN, KN, ST, KN, KN, KN }, 	 //	 880	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, ST, KN, QN, SK }, 	 //	 881	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, SK, KN, ST, KN, KN, KN }, 	 //	 882	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, SH, SK, KN }, 	 //	 883	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, ST, KN, WN, AC }, 	 //	 884	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, ST, KN, QN, SK }, 	 //	 885	 9000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, QN, KN, ST, KN, KN, KN }, 	 //	 886	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, ST, KN, AC, CR }, 	 //	 887	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, ST, PF, WN, KN }, 	 //	 888	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 889	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 890	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 891	 9000
{ KN, AC, KN, LO, CR, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 892	 9000
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 893	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, PF, AC, AC, AC }, 	 //	 894	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, PF, AC, AC, AC }, 	 //	 895	 9000
{ KN, PF, PF, LO, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 896	 9000
{ KN, PF, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 897	 9000
{ KN, PF, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, WN, LO }, 	 //	 898	 9000
{ KN, PF, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 899	 9000
{ KN, PF, WN, PF, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 900	 9000
{ KN, PF, KN, LO, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 901	 9000
{ KN, PF, KN, LO, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 902	 9000
{ KN, KN, KN, LO, LO, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 903	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, QN }, 	 //	 904	 9000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, ST, KN, KN, KN, KN, AC }, 	 //	 905	 9000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, WN, TN }, 	 //	 906	 9000
{ KN, KN, KN, AC, AC, KN, KN, KN, KN, KN, KN, KN, KN, QN, QN }, 	 //	 907	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, QN, KN, KN, KN, QN, PF }, 	 //	 908	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, SK, QN }, 	 //	 909	 9000
{ KN, KN, KN, LO, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH }, 	 //	 910	 9000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 911	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, WN, QN }, 	 //	 912	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, LO, KN, KN, KN, KN, AC }, 	 //	 913	 9000
{ KN, KN, KN, PF, SH, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA }, 	 //	 914	 9000
{ KN, KN, KN, PF, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA }, 	 //	 915	 9000
{ KN, KN, KN, PF, JA, KN, KN, KN, KN, TN, KN, KN, KN, KN, AC }, 	 //	 916	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, SK, SH }, 	 //	 917	 9000
{ KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, SK, TN }, 	 //	 918	 9000
{ KN, KN, KN, QN, CR, KN, KN, KN, KN, QN, KN, KN, KN, AC, KN }, 	 //	 919	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, PF, WN, KN }, 	 //	 920	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, SK, KN, WN, AC }, 	 //	 921	 9000
{ KN, KN, KN, QN, SK, KN, KN, KN, KN, KN, KN, SK, KN, AC, KN }, 	 //	 922	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, SH, WN, KN }, 	 //	 923	 9000
{ KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, SK, KN, WN, AC }, 	 //	 924	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, SK, KN, SK, KN, KN, KN }, 	 //	 925	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, PF, KN, KN }, 	 //	 926	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, PF, KN, KN }, 	 //	 927	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, PF, WN, KN }, 	 //	 928	 9000
{ KN, QN, KN, KN, CR, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 929	 9000
{ KN, QN, KN, LO, SK, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 930	 9000
{ KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, SK }, 	 //	 931	 9000
{ KN, QN, KN, PF, CR, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 932	 9000
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 933	 9000
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 934	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 935	 9000
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 936	 9000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, WN, KN, KN, KN, CR }, 	 //	 937	 9000
{ KN, LO, KN, PF, SK, KN, KN, KN, KN, KN, WN, KN, KN, KN, KN }, 	 //	 938	 9000
{ KN, LO, KN, KN, SK, KN, KN, KN, KN, KN, WN, KN, KN, KN, KN }, 	 //	 939	 9000
{ KN, KN, KN, LO, KN, KN, KN, KN, KN, KN, WN, KN, KN, KN, SK }, 	 //	 940	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, WN, KN, KN, QN, KN }, 	 //	 941	 9000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, SK, WN, KN, KN, KN, KN }, 	 //	 942	 9000
{ KN, KN, KN, LO, AC, KN, KN, KN, KN, SK, WN, KN, KN, KN, KN }, 	 //	 943	 9000
{ KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, WN, KN, KN, QN, KN }, 	 //	 944	 9000
{ KN, KN, KN, PF, KN, KN, KN, KN, KN, KN, WN, KN, KN, KN, CR }, 	 //	 945	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, WN, ST, KN, KN, QN }, 	 //	 946	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, WN, ST, KN, SK, PF }, 	 //	 947	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, WN, ST, KN, WN, QN }, 	 //	 948	 9000
{ KN, KN, KN, KN, SK, KN, KN, KN, KN, KN, WN, ST, KN, WN, KN }, 	 //	 949	 9000
{ KN, KN, KN, PF, CR, KN, KN, KN, KN, KN, WN, ST, KN, KN, KN }, 	 //	 950	 9000
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 951	 9000
{ KN, AC, KN, LO, KN, KN, KN, KN, KN, KN, WN, QN, KN, KN, KN }, 	 //	 952	 9000
{ KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, WN, QN, KN, SK, KN }, 	 //	 953	 9000
{ KN, AC, KN, KN, KN, KN, KN, KN, KN, KN, WN, QN, KN, WN, KN }, 	 //	 954	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, WN, PF, AC, AC, AC }, 	 //	 955	 9000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, WN, PF, AC, AC, AC }, 	 //	 956	 9000
{ KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, WN, KN, KN, WN, KN }, 	 //	 957	 9000
{ KN, PF, KN, KN, KN, KN, KN, KN, KN, KN, WN, KN, KN, SK, KN }, 	 //	 958	 9000
{ KN, PF, KN, LO, SK, KN, KN, KN, KN, KN, WN, KN, KN, KN, KN }, 	 //	 959	 9000
{ KN, KN, KN, PF, KN, KN, KN, KN, KN, KN, WN, KN, KN, KN, SK }, 	 //	 960	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, WN, KN, KN, SK, PF }, 	 //	 961	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, SK, WN, SK, KN, WN, QN }, 	 //	 962	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, AC, WN, SK, KN, KN, LO }, 	 //	 963	 9000
{ KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, WN, SK, KN, KN, KN }, 	 //	 964	 9000
{ KN, KN, KN, KN, CR, KN, KN, KN, KN, KN, WN, SK, KN, WN, KN }, 	 //	 965	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, WN, SK, KN, WN, PF }, 	 //	 966	 9000
{ KN, KN, KN, KN, KN, KN, KN, KN, KN, QN, WN, SK, KN, KN, PF }, 	 //	 967	 9000
{ KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, WN, SK, KN, AC, KN }, 	 //	 968	 9000
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, WN, SH, AC, AC, AC }, 	 //	 969	 9000
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 970	 9000
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, LO, QN, LO, AC, AC, AC }, 	 //	 971	 9000
{ KN, LO, KN, PF, KN, WN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 972	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, KN, QN, KN, KN, WN, CR }, 	 //	 973	 9000
{ KN, KN, KN, KN, AC, WN, KN, KN, KN, SK, QN, KN, KN, KN, KN }, 	 //	 974	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, KN, QN, ST, KN, WN, SK }, 	 //	 975	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, KN, QN, ST, KN, WN, CR }, 	 //	 976	 9000
{ KN, KN, KN, KN, CR, WN, KN, KN, KN, KN, QN, ST, KN, KN, KN }, 	 //	 977	 9000
{ KN, KN, KN, KN, SK, WN, KN, KN, KN, KN, QN, ST, KN, KN, KN }, 	 //	 978	 9000
{ KN, AC, AC, AC, LO, WN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 979	 9000
{ KN, KN, KN, LO, CR, WN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 980	 9000
{ KN, KN, KN, LO, SK, WN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 981	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, QN, QN, KN, KN, KN, PF }, 	 //	 982	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, AC, QN, KN, KN, KN, LO }, 	 //	 983	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, KN, QN, KN, KN, WN, SK }, 	 //	 984	 9000
{ KN, KN, KN, PF, CR, WN, KN, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 985	 9000
{ KN, KN, KN, KN, ST, WN, KN, KN, KN, AC, QN, KN, KN, KN, KN }, 	 //	 986	 9000
{ KN, KN, KN, PF, KN, WN, KN, KN, KN, KN, QN, SK, KN, KN, KN }, 	 //	 987	 9000
{ KN, KN, KN, KN, KN, WN, KN, KN, KN, KN, QN, SK, KN, KN, CR }, 	 //	 988	 9000
{ KN, KN, AC, AC, AC, WN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 989	 9000
{ KN, KN, AC, AC, AC, WN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 990	 9000
{ WN, AC, AC, AC, TN, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 991	 9000
{ WN, LO, KN, KN, CR, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 992	 9000
{ WN, LO, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 993	 9000
{ WN, LO, KN, LO, CR, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 994	 9000
{ WN, KN, KN, LO, CR, QN, KN, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 995	 9000
{ WN, KN, KN, KN, KN, QN, KN, KN, KN, AC, KN, KN, KN, KN, LO }, 	 //	 996	 9000
{ WN, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, ST, KN, SK, KN }, 	 //	 997	 9000
{ WN, WN, AC, AC, AC, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 998	 9000
{ WN, WN, AC, AC, AC, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 999	 9000
{ WN, TN, AC, AC, AC, QN, AC, AC, AC, LO, KN, AC, AC, AC, AC }};	 //	 1000	 9000
