#include "ReelDefine.h"

unsigned char L5_Outcome_0760[1000][15]={	 //	 0	 760
{ AC, SH, QN, QN, QN, LO, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 1	 760
{ AC, KN, QN, QN, QN, LO, KN, SK, SK, PF, AC, ST, JA, JA, JA }, 	 //	 2	 760
{ AC, KN, QN, QN, QN, LO, ST, SK, SK, SH, AC, QN, JA, JA, JA }, 	 //	 3	 760
{ AC, KN, QN, QN, QN, LO, ST, SK, SK, PF, AC, QN, JA, JA, JA }, 	 //	 4	 760
{ AC, QN, QN, QN, KN, LO, SK, SK, ST, QN, AC, JA, JA, JA, PF }, 	 //	 5	 760
{ AC, QN, QN, QN, PF, LO, SK, SK, ST, JA, AC, JA, JA, JA, TN }, 	 //	 6	 760
{ AC, QN, QN, QN, TN, LO, SK, SK, ST, AC, AC, JA, JA, JA, AC }, 	 //	 7	 760
{ AC, QN, QN, QN, KN, LO, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 8	 760
{ AC, SK, QN, QN, QN, LO, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 9	 760
{ AC, JA, QN, QN, QN, LO, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 10	 760
{ AC, JA, QN, QN, QN, LO, JA, SK, SK, QN, AC, JA, JA, JA, SH }, 	 //	 11	 760
{ AC, JA, QN, QN, QN, LO, SH, SK, SK, SH, AC, TN, JA, JA, JA }, 	 //	 12	 760
{ AC, JA, QN, QN, QN, LO, SH, SK, SK, PF, AC, TN, JA, JA, JA }, 	 //	 13	 760
{ AC, QN, QN, QN, CR, LO, ST, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 14	 760
{ AC, QN, QN, QN, JA, LO, ST, SK, SK, TN, AC, JA, JA, JA, AC }, 	 //	 15	 760
{ AC, ST, QN, QN, QN, LO, JA, SK, SK, PF, AC, TN, JA, JA, JA }, 	 //	 16	 760
{ AC, AC, QN, QN, QN, LO, AC, SK, SK, PF, AC, PF, JA, JA, JA }, 	 //	 17	 760
{ AC, AC, QN, QN, QN, LO, PF, SK, SK, PF, AC, KN, JA, JA, JA }, 	 //	 18	 760
{ AC, KN, QN, QN, QN, LO, KN, SK, SK, PF, AC, SK, JA, JA, JA }, 	 //	 19	 760
{ AC, SK, QN, QN, QN, LO, QN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 20	 760
{ LO, AC, QN, QN, QN, AC, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 21	 760
{ LO, ST, QN, QN, QN, AC, QN, SK, SK, SH, AC, QN, JA, JA, JA }, 	 //	 22	 760
{ LO, QN, QN, QN, SH, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA }, 	 //	 23	 760
{ LO, QN, QN, QN, AC, AC, SK, SK, ST, LO, AC, JA, JA, JA, AC }, 	 //	 24	 760
{ LO, QN, QN, QN, AC, AC, SK, SK, ST, AC, AC, JA, JA, JA, CR }, 	 //	 25	 760
{ LO, QN, QN, QN, KN, AC, SK, SK, ST, KN, AC, JA, JA, JA, SK }, 	 //	 26	 760
{ LO, QN, QN, QN, WN, AC, SK, SK, ST, TN, AC, JA, JA, JA, TN }, 	 //	 27	 760
{ LO, QN, QN, QN, TN, AC, SK, SK, ST, TN, AC, JA, JA, JA, ST }, 	 //	 28	 760
{ LO, QN, QN, QN, SK, AC, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 29	 760
{ LO, QN, QN, QN, KN, AC, SK, SK, ST, KN, AC, JA, JA, JA, CR }, 	 //	 30	 760
{ LO, QN, QN, QN, KN, AC, ST, SK, SK, QN, AC, JA, JA, JA, PF }, 	 //	 31	 760
{ LO, ST, QN, QN, QN, AC, JA, SK, SK, SH, AC, TN, JA, JA, JA }, 	 //	 32	 760
{ LO, AC, QN, QN, QN, AC, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 33	 760
{ LO, AC, QN, QN, QN, AC, AC, SK, SK, SH, AC, PF, JA, JA, JA }, 	 //	 34	 760
{ LO, KN, QN, QN, QN, AC, SK, SK, ST, PF, AC, QN, JA, JA, JA }, 	 //	 35	 760
{ AC, KN, QN, QN, QN, AC, KN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 36	 760
{ AC, QN, QN, QN, AC, AC, SK, SK, ST, AC, AC, JA, JA, JA, CR }, 	 //	 37	 760
{ AC, QN, QN, QN, AC, AC, SK, SK, ST, KN, AC, JA, JA, JA, QN }, 	 //	 38	 760
{ AC, QN, QN, QN, KN, AC, SK, SK, ST, QN, AC, JA, JA, JA, PF }, 	 //	 39	 760
{ AC, QN, QN, QN, KN, AC, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 40	 760
{ AC, QN, QN, QN, CR, AC, SK, SK, ST, QN, AC, JA, JA, JA, KN }, 	 //	 41	 760
{ AC, QN, QN, QN, KN, AC, SK, SK, ST, AC, AC, JA, JA, JA, LO }, 	 //	 42	 760
{ AC, JA, QN, QN, QN, AC, JA, SK, SK, SH, AC, SH, JA, JA, JA }, 	 //	 43	 760
{ AC, TN, QN, QN, QN, AC, TN, SK, SK, PF, AC, WN, JA, JA, JA }, 	 //	 44	 760
{ AC, TN, QN, QN, QN, AC, WN, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 45	 760
{ AC, AC, QN, QN, QN, AC, KN, SK, SK, SH, AC, QN, JA, JA, JA }, 	 //	 46	 760
{ AC, QN, QN, QN, KN, AC, ST, SK, SK, AC, AC, JA, JA, JA, LO }, 	 //	 47	 760
{ AC, AC, QN, QN, QN, AC, AC, SK, SK, SH, AC, PF, JA, JA, JA }, 	 //	 48	 760
{ AC, PF, QN, QN, QN, AC, KN, SK, SK, PF, AC, KN, JA, JA, JA }, 	 //	 49	 760
{ AC, KN, QN, QN, QN, AC, SK, SK, ST, PF, AC, QN, JA, JA, JA }, 	 //	 50	 760
{ AC, AC, QN, QN, QN, AC, SH, SK, SK, PF, ST, AC, JA, JA, JA }, 	 //	 51	 760
{ AC, KN, QN, QN, QN, AC, KN, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 52	 760
{ AC, QN, QN, QN, SH, AC, QN, SK, SK, JA, ST, QN, JA, JA, JA }, 	 //	 53	 760
{ AC, QN, QN, QN, SH, AC, QN, SK, SK, JA, ST, SK, JA, JA, JA }, 	 //	 54	 760
{ AC, QN, QN, QN, TN, AC, SK, SK, ST, TN, ST, JA, JA, JA, TN }, 	 //	 55	 760
{ AC, QN, QN, QN, PF, AC, SK, SK, ST, JA, ST, JA, JA, JA, TN }, 	 //	 56	 760
{ AC, QN, QN, QN, AC, AC, SK, SK, ST, AC, ST, JA, JA, JA, AC }, 	 //	 57	 760
{ AC, QN, QN, QN, KN, AC, SK, SK, ST, KN, ST, JA, JA, JA, KN }, 	 //	 58	 760
{ AC, SK, QN, QN, QN, AC, JA, SK, SK, QN, ST, JA, JA, JA, QN }, 	 //	 59	 760
{ AC, SK, QN, QN, QN, AC, JA, SK, SK, QN, ST, JA, JA, JA, SH }, 	 //	 60	 760
{ AC, JA, QN, QN, QN, AC, JA, SK, SK, QN, ST, JA, JA, JA, SH }, 	 //	 61	 760
{ AC, JA, QN, QN, QN, AC, JA, SK, SK, KN, ST, JA, JA, JA, AC }, 	 //	 62	 760
{ AC, TN, QN, QN, QN, AC, TN, SK, SK, PF, ST, TN, JA, JA, JA }, 	 //	 63	 760
{ AC, TN, QN, QN, QN, AC, WN, SK, SK, SH, ST, AC, JA, JA, JA }, 	 //	 64	 760
{ AC, WN, QN, QN, QN, AC, AC, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 65	 760
{ AC, KN, QN, QN, QN, AC, QN, SK, SK, SH, ST, ST, JA, JA, JA }, 	 //	 66	 760
{ AC, QN, QN, QN, TN, AC, ST, SK, SK, TN, ST, JA, JA, JA, ST }, 	 //	 67	 760
{ AC, QN, QN, QN, TN, AC, ST, SK, SK, AC, ST, JA, JA, JA, AC }, 	 //	 68	 760
{ AC, QN, QN, QN, AC, AC, ST, SK, SK, AC, ST, JA, JA, JA, AC }, 	 //	 69	 760
{ AC, JA, QN, QN, QN, AC, TN, SK, SK, PF, ST, AC, JA, JA, JA }, 	 //	 70	 760
{ AC, AC, QN, QN, QN, AC, AC, SK, SK, PF, ST, AC, JA, JA, JA }, 	 //	 71	 760
{ AC, AC, QN, QN, QN, AC, PF, SK, SK, SH, ST, KN, JA, JA, JA }, 	 //	 72	 760
{ AC, KN, QN, QN, QN, AC, SK, SK, ST, PF, ST, QN, JA, JA, JA }, 	 //	 73	 760
{ AC, KN, QN, QN, QN, AC, AC, SK, SK, PF, ST, SH, JA, JA, JA }, 	 //	 74	 760
{ AC, SH, QN, QN, QN, ST, AC, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 75	 760
{ AC, KN, QN, QN, QN, ST, ST, SK, SK, PF, KN, QN, JA, JA, JA }, 	 //	 76	 760
{ AC, ST, QN, QN, QN, ST, QN, SK, SK, SH, KN, QN, JA, JA, JA }, 	 //	 77	 760
{ AC, QN, QN, QN, AC, ST, SK, SK, ST, AC, KN, JA, JA, JA, CR }, 	 //	 78	 760
{ AC, QN, QN, QN, SK, ST, SK, SK, ST, QN, KN, JA, JA, JA, QN }, 	 //	 79	 760
{ AC, QN, QN, QN, TN, ST, SK, SK, ST, TN, KN, JA, JA, JA, TN }, 	 //	 80	 760
{ AC, QN, QN, QN, ST, ST, SK, SK, ST, AC, KN, JA, JA, JA, KN }, 	 //	 81	 760
{ AC, QN, QN, QN, PF, ST, SK, SK, ST, JA, KN, JA, JA, JA, TN }, 	 //	 82	 760
{ AC, QN, QN, QN, TN, ST, SK, SK, ST, AC, KN, JA, JA, JA, AC }, 	 //	 83	 760
{ AC, SK, QN, QN, QN, ST, JA, SK, SK, QN, KN, JA, JA, JA, SH }, 	 //	 84	 760
{ AC, JA, QN, QN, QN, ST, JA, SK, SK, PF, KN, SH, JA, JA, JA }, 	 //	 85	 760
{ AC, TN, QN, QN, QN, ST, TN, SK, SK, PF, KN, TN, JA, JA, JA }, 	 //	 86	 760
{ AC, QN, QN, QN, JA, ST, ST, SK, SK, WN, KN, JA, JA, JA, TN }, 	 //	 87	 760
{ AC, QN, QN, QN, TN, ST, ST, SK, SK, ST, KN, JA, JA, JA, AC }, 	 //	 88	 760
{ AC, QN, QN, QN, ST, ST, ST, SK, SK, AC, KN, JA, JA, JA, KN }, 	 //	 89	 760
{ AC, QN, QN, QN, CR, ST, ST, SK, SK, QN, KN, JA, JA, JA, KN }, 	 //	 90	 760
{ AC, JA, QN, QN, QN, ST, TN, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 91	 760
{ AC, JA, QN, QN, QN, ST, TN, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 92	 760
{ AC, KN, QN, QN, QN, ST, KN, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 93	 760
{ AC, KN, QN, QN, QN, ST, KN, SK, SK, SH, KN, SK, JA, JA, JA }, 	 //	 94	 760
{ AC, KN, QN, QN, QN, ST, KN, SK, SK, PF, KN, SK, JA, JA, JA }, 	 //	 95	 760
{ ST, SH, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 96	 760
{ ST, SH, QN, QN, QN, KN, AC, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 97	 760
{ ST, AC, QN, QN, QN, KN, AC, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 98	 760
{ ST, AC, QN, QN, QN, KN, LO, SK, SK, PF, KN, KN, JA, JA, JA }, 	 //	 99	 760
{ ST, KN, QN, QN, QN, KN, ST, SK, SK, SH, KN, QN, JA, JA, JA }, 	 //	 100	 760
{ ST, KN, QN, QN, QN, KN, ST, SK, SK, PF, KN, QN, JA, JA, JA }, 	 //	 101	 760
{ ST, ST, QN, QN, QN, KN, QN, SK, SK, SH, KN, QN, JA, JA, JA }, 	 //	 102	 760
{ ST, ST, QN, QN, QN, KN, QN, SK, SK, PF, KN, QN, JA, JA, JA }, 	 //	 103	 760
{ ST, QN, QN, QN, SK, KN, SK, SK, ST, QN, KN, JA, JA, JA, QN }, 	 //	 104	 760
{ ST, QN, QN, QN, AC, KN, SK, SK, ST, KN, KN, JA, JA, JA, QN }, 	 //	 105	 760
{ ST, QN, QN, QN, JA, KN, SK, SK, ST, TN, KN, JA, JA, JA, AC }, 	 //	 106	 760
{ ST, QN, QN, QN, KN, KN, SK, SK, ST, KN, KN, JA, JA, JA, KN }, 	 //	 107	 760
{ ST, JA, QN, QN, QN, KN, JA, SK, SK, SH, KN, SH, JA, JA, JA }, 	 //	 108	 760
{ ST, JA, QN, QN, QN, KN, SH, SK, SK, SH, KN, TN, JA, JA, JA }, 	 //	 109	 760
{ ST, TN, QN, QN, QN, KN, TN, SK, SK, PF, KN, TN, JA, JA, JA }, 	 //	 110	 760
{ ST, TN, QN, QN, QN, KN, TN, SK, SK, SH, KN, WN, JA, JA, JA }, 	 //	 111	 760
{ ST, TN, QN, QN, QN, KN, WN, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 112	 760
{ ST, KN, QN, QN, QN, KN, QN, SK, SK, SH, KN, ST, JA, JA, JA }, 	 //	 113	 760
{ ST, QN, QN, QN, AC, KN, ST, SK, SK, AC, KN, JA, JA, JA, CR }, 	 //	 114	 760
{ ST, QN, QN, QN, JA, KN, ST, SK, SK, JA, KN, JA, JA, JA, WN }, 	 //	 115	 760
{ ST, QN, QN, QN, TN, KN, ST, SK, SK, ST, KN, JA, JA, JA, AC }, 	 //	 116	 760
{ ST, QN, QN, QN, CR, KN, ST, SK, SK, QN, KN, JA, JA, JA, KN }, 	 //	 117	 760
{ ST, JA, QN, QN, QN, KN, TN, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 118	 760
{ ST, TN, QN, QN, QN, KN, AC, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 119	 760
{ ST, KN, QN, QN, QN, KN, KN, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 120	 760
{ ST, KN, QN, QN, QN, KN, KN, SK, SK, PF, KN, KN, JA, JA, JA }, 	 //	 121	 760
{ ST, KN, QN, QN, QN, KN, KN, SK, SK, SH, KN, SK, JA, JA, JA }, 	 //	 122	 760
{ ST, KN, QN, QN, QN, KN, SK, SK, ST, PF, KN, QN, JA, JA, JA }, 	 //	 123	 760
{ KN, SH, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 124	 760
{ KN, AC, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 125	 760
{ KN, KN, QN, QN, QN, KN, ST, SK, SK, SH, KN, QN, JA, JA, JA }, 	 //	 126	 760
{ KN, QN, QN, QN, AC, KN, SK, SK, ST, LO, KN, JA, JA, JA, AC }, 	 //	 127	 760
{ KN, QN, QN, QN, LO, KN, SK, SK, ST, AC, KN, JA, JA, JA, AC }, 	 //	 128	 760
{ KN, QN, QN, QN, JA, KN, SK, SK, ST, WN, KN, JA, JA, JA, TN }, 	 //	 129	 760
{ KN, QN, QN, QN, ST, KN, SK, SK, ST, AC, KN, JA, JA, JA, KN }, 	 //	 130	 760
{ KN, QN, QN, QN, AC, KN, SK, SK, ST, SK, KN, JA, JA, JA, KN }, 	 //	 131	 760
{ KN, QN, QN, QN, JA, KN, ST, SK, SK, JA, KN, JA, JA, JA, WN }, 	 //	 132	 760
{ KN, QN, QN, QN, TN, KN, ST, SK, SK, AC, KN, JA, JA, JA, AC }, 	 //	 133	 760
{ KN, PF, QN, QN, QN, KN, KN, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 134	 760
{ KN, SK, QN, QN, QN, KN, QN, SK, SK, PF, KN, KN, JA, JA, JA }, 	 //	 135	 760
{ KN, QN, QN, QN, JA, KN, KN, SK, SK, JA, KN, AC, JA, JA, JA }, 	 //	 136	 760
{ KN, AC, QN, QN, QN, KN, AC, SK, SK, PF, SK, AC, JA, JA, JA }, 	 //	 137	 760
{ KN, KN, QN, QN, QN, KN, ST, SK, SK, SH, SK, QN, JA, JA, JA }, 	 //	 138	 760
{ KN, ST, QN, QN, QN, KN, QN, SK, SK, PF, SK, QN, JA, JA, JA }, 	 //	 139	 760
{ KN, QN, QN, QN, SH, KN, QN, SK, ST, JA, SK, SK, JA, JA, JA }, 	 //	 140	 760
{ KN, JA, QN, QN, QN, KN, SH, SK, SK, PF, SK, TN, JA, JA, JA }, 	 //	 141	 760
{ KN, TN, QN, QN, QN, KN, TN, SK, SK, SH, SK, TN, JA, JA, JA }, 	 //	 142	 760
{ KN, TN, QN, QN, QN, KN, TN, SK, SK, PF, SK, TN, JA, JA, JA }, 	 //	 143	 760
{ KN, TN, QN, QN, QN, KN, TN, SK, SK, PF, SK, WN, JA, JA, JA }, 	 //	 144	 760
{ KN, TN, QN, QN, QN, KN, WN, SK, SK, SH, SK, AC, JA, JA, JA }, 	 //	 145	 760
{ KN, TN, QN, QN, QN, KN, WN, SK, SK, PF, SK, AC, JA, JA, JA }, 	 //	 146	 760
{ KN, AC, QN, QN, QN, KN, KN, SK, SK, SH, SK, QN, JA, JA, JA }, 	 //	 147	 760
{ KN, KN, QN, QN, QN, KN, QN, SK, SK, PF, SK, ST, JA, JA, JA }, 	 //	 148	 760
{ KN, QN, QN, QN, LO, KN, ST, SK, SK, AC, SK, JA, JA, JA, AC }, 	 //	 149	 760
{ KN, QN, QN, QN, AC, KN, ST, SK, SK, AC, SK, JA, JA, JA, AC }, 	 //	 150	 760
{ KN, QN, QN, QN, CR, KN, ST, SK, SK, KN, SK, JA, JA, JA, KN }, 	 //	 151	 760
{ KN, QN, QN, QN, JA, KN, ST, SK, SK, JA, SK, JA, JA, JA, WN }, 	 //	 152	 760
{ KN, QN, QN, QN, TN, KN, ST, SK, SK, AC, SK, JA, JA, JA, AC }, 	 //	 153	 760
{ KN, QN, QN, QN, KN, KN, ST, SK, SK, KN, SK, JA, JA, JA, KN }, 	 //	 154	 760
{ KN, QN, QN, QN, KN, KN, ST, SK, SK, AC, SK, JA, JA, JA, LO }, 	 //	 155	 760
{ KN, JA, QN, QN, QN, KN, TN, SK, SK, PF, SK, AC, JA, JA, JA }, 	 //	 156	 760
{ KN, AC, QN, QN, QN, KN, AC, SK, SK, SH, SK, PF, JA, JA, JA }, 	 //	 157	 760
{ KN, PF, QN, QN, QN, KN, KN, SK, SK, PF, SK, KN, JA, JA, JA }, 	 //	 158	 760
{ KN, SK, QN, QN, QN, KN, QN, SK, SK, SH, SK, KN, JA, JA, JA }, 	 //	 159	 760
{ KN, SH, QN, QN, QN, SK, AC, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 160	 760
{ KN, AC, QN, QN, QN, SK, AC, SK, SK, PF, QN, AC, JA, JA, JA }, 	 //	 161	 760
{ KN, KN, QN, QN, QN, SK, KN, SK, SK, SH, QN, ST, JA, JA, JA }, 	 //	 162	 760
{ KN, ST, QN, QN, JA, SK, QN, SK, SK, JA, QN, QN, JA, JA, JA }, 	 //	 163	 760
{ KN, JA, QN, QN, QN, SK, SH, SK, SK, PF, QN, TN, JA, JA, JA }, 	 //	 164	 760
{ KN, SH, QN, QN, QN, SK, TN, SK, SK, SH, QN, TN, JA, JA, JA }, 	 //	 165	 760
{ KN, TN, QN, QN, QN, SK, TN, SK, SK, PF, QN, TN, JA, JA, JA }, 	 //	 166	 760
{ KN, TN, QN, QN, QN, SK, TN, SK, SK, PF, QN, WN, JA, JA, JA }, 	 //	 167	 760
{ KN, KN, QN, QN, SH, SK, QN, SK, SK, JA, QN, ST, JA, JA, JA }, 	 //	 168	 760
{ KN, KN, QN, QN, JA, SK, QN, SK, SK, JA, QN, ST, JA, JA, JA }, 	 //	 169	 760
{ KN, QN, QN, QN, JA, SK, ST, SK, SK, JA, QN, JA, JA, JA, WN }, 	 //	 170	 760
{ KN, QN, QN, QN, JA, SK, ST, SK, SK, TN, QN, JA, JA, JA, AC }, 	 //	 171	 760
{ KN, QN, QN, QN, AC, SK, ST, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 172	 760
{ KN, TN, QN, QN, QN, SK, AC, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 173	 760
{ KN, AC, QN, QN, QN, SK, AC, SK, SK, PF, QN, AC, JA, JA, JA }, 	 //	 174	 760
{ KN, AC, QN, QN, QN, SK, AC, SK, SK, SH, QN, PF, JA, JA, JA }, 	 //	 175	 760
{ KN, AC, QN, QN, QN, SK, PF, SK, SK, SH, QN, KN, JA, JA, JA }, 	 //	 176	 760
{ KN, SK, QN, QN, JA, SK, QN, SK, SK, JA, QN, KN, JA, JA, JA }, 	 //	 177	 760
{ KN, KN, QN, QN, QN, SK, AC, SK, SK, PF, QN, SH, JA, JA, JA }, 	 //	 178	 760
{ SK, AC, QN, QN, QN, QN, SH, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 179	 760
{ SK, AC, QN, QN, QN, QN, SH, SK, SK, PF, QN, AC, JA, JA, JA }, 	 //	 180	 760
{ SK, SH, QN, QN, QN, QN, AC, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 181	 760
{ SK, KN, QN, QN, QN, QN, KN, SK, SK, PF, QN, KN, JA, JA, JA }, 	 //	 182	 760
{ SK, KN, QN, QN, QN, QN, KN, SK, SK, SH, QN, ST, JA, JA, JA }, 	 //	 183	 760
{ SK, KN, QN, QN, QN, QN, ST, SK, SK, SH, QN, QN, JA, JA, JA }, 	 //	 184	 760
{ SK, TN, QN, QN, QN, QN, WN, SK, SK, PF, QN, AC, JA, JA, JA }, 	 //	 185	 760
{ SK, AC, QN, QN, QN, QN, KN, SK, SK, SH, QN, QN, JA, JA, JA }, 	 //	 186	 760
{ SK, QN, QN, QN, LO, QN, ST, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 187	 760
{ SK, QN, QN, QN, CR, QN, ST, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 188	 760
{ SK, QN, QN, QN, TN, QN, ST, SK, SK, ST, QN, JA, JA, JA, AC }, 	 //	 189	 760
{ SK, QN, QN, QN, ST, QN, ST, SK, SK, AC, QN, JA, JA, JA, KN }, 	 //	 190	 760
{ SK, QN, QN, QN, KN, QN, ST, SK, SK, QN, QN, JA, JA, JA, PF }, 	 //	 191	 760
{ SK, QN, QN, QN, JA, QN, ST, SK, SK, TN, QN, JA, JA, JA, AC }, 	 //	 192	 760
{ SK, QN, QN, QN, KN, QN, ST, SK, SK, KN, QN, JA, JA, JA, CR }, 	 //	 193	 760
{ SK, ST, QN, QN, QN, QN, JA, SK, SK, PF, QN, TN, JA, JA, JA }, 	 //	 194	 760
{ SK, TN, QN, QN, QN, QN, AC, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 195	 760
{ SK, AC, QN, QN, QN, QN, AC, SK, SK, PF, QN, AC, JA, JA, JA }, 	 //	 196	 760
{ SK, KN, QN, QN, QN, QN, KN, SK, SK, SH, QN, KN, JA, JA, JA }, 	 //	 197	 760
{ SK, SK, QN, JA, JA, QN, QN, SK, JA, JA, QN, KN, JA, JA, WN }, 	 //	 198	 760
{ SK, SK, QN, JA, JA, QN, QN, SK, JA, WN, QN, KN, JA, JA, TN }, 	 //	 199	 760
{ SK, SK, QN, QN, SH, QN, QN, SK, ST, JA, QN, KN, JA, JA, JA }, 	 //	 200	 760
{ SK, SK, QN, ST, JA, QN, QN, SK, JA, WN, QN, KN, JA, TN, TN }, 	 //	 201	 760
{ QN, AC, QN, QN, QN, QN, SH, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 202	 760
{ QN, AC, QN, QN, QN, QN, LO, SK, SK, PF, QN, KN, JA, JA, JA }, 	 //	 203	 760
{ QN, QN, QN, SK, QN, QN, SK, SK, JA, QN, QN, JA, JA, JA, QN }, 	 //	 204	 760
{ QN, QN, QN, SK, ST, QN, SK, SK, JA, AC, QN, JA, JA, JA, KN }, 	 //	 205	 760
{ QN, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, CR }, 	 //	 206	 760
{ QN, QN, QN, JA, SK, QN, SK, SK, JA, QN, QN, JA, JA, JA, QN }, 	 //	 207	 760
{ QN, QN, QN, JA, TN, QN, SK, SK, JA, ST, QN, JA, JA, JA, AC }, 	 //	 208	 760
{ QN, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 209	 760
{ QN, QN, QN, JA, CR, QN, SK, SK, JA, QN, QN, JA, JA, JA, KN }, 	 //	 210	 760
{ QN, QN, QN, JA, QN, QN, SK, SK, JA, KN, QN, JA, JA, JA, AC }, 	 //	 211	 760
{ QN, QN, QN, JA, JA, QN, SK, SK, JA, WN, QN, JA, JA, SH, TN }, 	 //	 212	 760
{ QN, QN, QN, ST, JA, QN, SK, SK, JA, JA, QN, JA, JA, TN, JA }, 	 //	 213	 760
{ QN, QN, QN, ST, JA, QN, SK, SK, JA, JA, QN, JA, JA, TN, WN }, 	 //	 214	 760
{ QN, JA, QN, QN, QN, QN, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 215	 760
{ QN, JA, QN, QN, QN, QN, SH, SK, SK, SH, QN, TN, JA, JA, JA }, 	 //	 216	 760
{ QN, SH, QN, QN, QN, QN, TN, SK, SK, PF, QN, TN, JA, JA, JA }, 	 //	 217	 760
{ QN, AC, QN, QN, QN, QN, KN, SK, SK, SH, QN, QN, JA, JA, JA }, 	 //	 218	 760
{ QN, AC, QN, QN, QN, QN, KN, SK, SK, PF, QN, QN, JA, JA, JA }, 	 //	 219	 760
{ QN, KN, QN, QN, SH, QN, QN, SK, SK, JA, QN, ST, JA, JA, JA }, 	 //	 220	 760
{ QN, AC, QN, QN, QN, QN, PF, SK, SK, SH, QN, KN, JA, JA, JA }, 	 //	 221	 760
{ QN, AC, QN, QN, QN, QN, SH, SK, SK, PF, SH, AC, JA, JA, JA }, 	 //	 222	 760
{ QN, LO, QN, QN, QN, QN, KN, SK, SK, PF, SH, KN, JA, JA, JA }, 	 //	 223	 760
{ QN, QN, QN, SK, AC, QN, SK, SK, JA, LO, SH, JA, JA, JA, AC }, 	 //	 224	 760
{ QN, QN, QN, SK, QN, QN, SK, SK, JA, QN, SH, JA, JA, JA, QN }, 	 //	 225	 760
{ QN, QN, QN, SK, WN, QN, SK, SK, JA, TN, SH, JA, JA, JA, TN }, 	 //	 226	 760
{ QN, QN, QN, SK, TN, QN, SK, SK, JA, TN, SH, JA, JA, JA, ST }, 	 //	 227	 760
{ QN, QN, QN, SK, KN, QN, SK, SK, JA, KN, SH, JA, JA, JA, KN }, 	 //	 228	 760
{ QN, QN, QN, SK, QN, QN, SK, SK, JA, KN, SH, JA, JA, JA, AC }, 	 //	 229	 760
{ QN, QN, QN, JA, LO, QN, SK, SK, JA, AC, SH, JA, JA, JA, AC }, 	 //	 230	 760
{ QN, QN, QN, JA, AC, QN, SK, SK, JA, AC, SH, JA, JA, JA, CR }, 	 //	 231	 760
{ QN, QN, QN, JA, WN, QN, SK, SK, JA, TN, SH, JA, JA, JA, TN }, 	 //	 232	 760
{ QN, QN, QN, JA, TN, QN, SK, SK, JA, ST, SH, JA, JA, JA, AC }, 	 //	 233	 760
{ QN, QN, QN, JA, KN, QN, SK, SK, JA, QN, SH, JA, JA, JA, PF }, 	 //	 234	 760
{ QN, QN, QN, JA, TN, QN, SK, SK, JA, AC, SH, JA, JA, JA, AC }, 	 //	 235	 760
{ QN, QN, QN, JA, JA, QN, SK, SK, JA, JA, SH, JA, JA, SH, WN }, 	 //	 236	 760
{ QN, SK, QN, QN, QN, QN, JA, SK, SK, QN, SH, JA, JA, JA, QN }, 	 //	 237	 760
{ QN, SK, QN, QN, QN, QN, JA, SK, SK, QN, SH, JA, JA, JA, SH }, 	 //	 238	 760
{ QN, JA, QN, QN, QN, QN, JA, SK, SK, KN, SH, JA, JA, JA, AC }, 	 //	 239	 760
{ QN, JA, QN, QN, QN, QN, JA, SK, SK, PF, SH, SH, JA, JA, JA }, 	 //	 240	 760
{ QN, SH, QN, QN, QN, QN, TN, SK, SK, SH, SH, TN, JA, JA, JA }, 	 //	 241	 760
{ QN, TN, QN, QN, QN, QN, WN, SK, SK, SH, SH, AC, JA, JA, JA }, 	 //	 242	 760
{ QN, TN, QN, QN, QN, QN, WN, SK, SK, PF, SH, AC, JA, JA, JA }, 	 //	 243	 760
{ QN, QN, QN, SK, SK, QN, ST, SK, JA, KN, SH, JA, JA, JA, KN }, 	 //	 244	 760
{ QN, KN, QN, QN, QN, QN, KN, SK, SK, SH, SH, KN, JA, JA, JA }, 	 //	 245	 760
{ QN, KN, QN, QN, QN, QN, AC, SK, SK, PF, SH, SH, JA, JA, JA }, 	 //	 246	 760
{ QN, KN, QN, QN, QN, SH, KN, SK, SK, SH, JA, ST, JA, JA, JA }, 	 //	 247	 760
{ QN, ST, QN, QN, QN, SH, QN, SK, SK, SH, JA, QN, JA, JA, JA }, 	 //	 248	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, PF, AC, JA, JA, JA, AC, CR }, 	 //	 249	 760
{ QN, QN, QN, AC, JA, SH, SK, SK, PF, JA, JA, JA, JA, AC, WN }, 	 //	 250	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, PF, AC, JA, JA, JA, AC, AC }, 	 //	 251	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, PF, KN, JA, JA, JA, AC, KN }, 	 //	 252	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, PF, KN, JA, JA, JA, AC, CR }, 	 //	 253	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, PF, AC, JA, JA, JA, AC, LO }, 	 //	 254	 760
{ QN, QN, QN, PF, AC, SH, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 255	 760
{ QN, QN, QN, PF, TN, SH, SK, SK, AC, ST, JA, JA, JA, AC, AC }, 	 //	 256	 760
{ QN, QN, QN, PF, PF, SH, SK, SK, AC, JA, JA, JA, JA, AC, TN }, 	 //	 257	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, AC, JA, JA, JA, AC, CR }, 	 //	 258	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, SK, JA, JA, JA, AC, QN }, 	 //	 259	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, AC, QN, JA, JA, JA, AC, SH }, 	 //	 260	 760
{ QN, QN, QN, AC, JA, SH, SK, SK, AC, JA, JA, JA, JA, AC, WN }, 	 //	 261	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, QN, JA, JA, JA, AC, PF }, 	 //	 262	 760
{ QN, QN, QN, AC, PF, SH, SK, SK, AC, JA, JA, JA, JA, AC, TN }, 	 //	 263	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, AC, JA, JA, JA, AC, SK }, 	 //	 264	 760
{ QN, QN, QN, AC, CR, SH, SK, SK, AC, QN, JA, JA, JA, AC, KN }, 	 //	 265	 760
{ QN, QN, QN, AC, SK, SH, SK, SK, AC, QN, JA, JA, JA, LO, QN }, 	 //	 266	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, AC, QN, JA, JA, JA, LO, QN }, 	 //	 267	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, AC, SH, JA, JA, JA, LO, JA }, 	 //	 268	 760
{ QN, QN, QN, AC, ST, SH, SK, SK, AC, AC, JA, JA, JA, LO, KN }, 	 //	 269	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, KN, JA, JA, JA, LO, QN }, 	 //	 270	 760
{ QN, QN, QN, AC, JA, SH, SK, SK, AC, TN, JA, JA, JA, LO, AC }, 	 //	 271	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, AC, JA, JA, JA, LO, SK }, 	 //	 272	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, SK, JA, JA, JA, LO, KN }, 	 //	 273	 760
{ QN, QN, QN, AC, CR, SH, SK, SK, AC, QN, JA, JA, JA, LO, KN }, 	 //	 274	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, LO, KN, JA, JA, JA, KN, KN }, 	 //	 275	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, LO, KN, JA, JA, JA, KN, SK }, 	 //	 276	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, LO, SK, JA, JA, JA, KN, QN }, 	 //	 277	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, LO, SH, JA, JA, JA, KN, JA }, 	 //	 278	 760
{ QN, QN, QN, AC, SH, SH, SK, SK, LO, JA, JA, JA, JA, KN, JA }, 	 //	 279	 760
{ QN, QN, QN, AC, WN, SH, SK, SK, LO, TN, JA, JA, JA, KN, TN }, 	 //	 280	 760
{ QN, QN, QN, LO, TN, SH, SK, SK, KN, TN, JA, JA, JA, KN, TN }, 	 //	 281	 760
{ QN, QN, QN, LO, KN, SH, SK, SK, KN, QN, JA, JA, JA, KN, PF }, 	 //	 282	 760
{ QN, QN, QN, LO, SK, SH, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 283	 760
{ QN, QN, QN, LO, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, CR }, 	 //	 284	 760
{ QN, QN, QN, KN, AC, SH, SK, SK, KN, AC, JA, JA, JA, KN, CR }, 	 //	 285	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, KN, QN, JA, JA, JA, KN, QN }, 	 //	 286	 760
{ QN, QN, QN, KN, ST, SH, SK, SK, KN, AC, JA, JA, JA, KN, KN }, 	 //	 287	 760
{ QN, QN, QN, KN, JA, SH, SK, SK, KN, TN, JA, JA, JA, KN, AC }, 	 //	 288	 760
{ QN, QN, QN, KN, AC, SH, SK, SK, KN, AC, JA, JA, JA, WN, CR }, 	 //	 289	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, KN, SH, JA, JA, JA, WN, JA }, 	 //	 290	 760
{ QN, QN, QN, KN, JA, SH, SK, SK, KN, JA, JA, JA, JA, WN, JA }, 	 //	 291	 760
{ QN, QN, QN, KN, PF, SH, SK, SK, KN, JA, JA, JA, JA, WN, TN }, 	 //	 292	 760
{ QN, QN, QN, KN, TN, SH, SK, SK, KN, AC, JA, JA, JA, WN, AC }, 	 //	 293	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, KN, KN, JA, JA, JA, WN, KN }, 	 //	 294	 760
{ QN, QN, QN, KN, AC, SH, SK, SK, WN, LO, JA, JA, JA, QN, AC }, 	 //	 295	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, WN, KN, JA, JA, JA, QN, SK }, 	 //	 296	 760
{ QN, QN, QN, KN, SK, SH, SK, SK, WN, QN, JA, JA, JA, QN, QN }, 	 //	 297	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, WN, QN, JA, JA, JA, QN, QN }, 	 //	 298	 760
{ QN, QN, QN, KN, JA, SH, SK, SK, WN, WN, JA, JA, JA, QN, TN }, 	 //	 299	 760
{ QN, QN, QN, KN, PF, SH, SK, SK, WN, JA, JA, JA, JA, QN, TN }, 	 //	 300	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, WN, KN, JA, JA, JA, QN, KN }, 	 //	 301	 760
{ QN, QN, QN, WN, KN, SH, SK, SK, QN, KN, JA, JA, JA, QN, KN }, 	 //	 302	 760
{ QN, QN, QN, WN, SH, SH, SK, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 303	 760
{ QN, QN, QN, WN, JA, SH, SK, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 304	 760
{ QN, QN, QN, WN, JA, SH, SK, SK, QN, JA, JA, JA, JA, QN, WN }, 	 //	 305	 760
{ QN, QN, QN, WN, PF, SH, SK, SK, QN, JA, JA, JA, JA, QN, TN }, 	 //	 306	 760
{ QN, QN, QN, WN, AC, SH, SK, SK, QN, SK, JA, JA, JA, QN, KN }, 	 //	 307	 760
{ QN, QN, QN, JA, KN, SH, SK, SK, JA, KN, JA, JA, JA, SH, KN }, 	 //	 308	 760
{ QN, QN, QN, JA, KN, SH, SK, SK, JA, KN, JA, JA, JA, SH, SK }, 	 //	 309	 760
{ QN, QN, QN, JA, CR, SH, SK, SK, SH, KN, JA, JA, JA, TN, KN }, 	 //	 310	 760
{ QN, QN, QN, JA, KN, SH, SK, SK, SH, KN, JA, JA, JA, TN, KN }, 	 //	 311	 760
{ QN, QN, QN, JA, SK, SH, SK, SK, SH, QN, JA, JA, JA, TN, QN }, 	 //	 312	 760
{ QN, QN, QN, JA, QN, SH, SK, SK, SH, SH, JA, JA, JA, TN, JA }, 	 //	 313	 760
{ QN, QN, QN, JA, AC, SH, SK, SK, SH, KN, JA, JA, JA, TN, QN }, 	 //	 314	 760
{ QN, QN, QN, JA, SK, SH, SK, SK, SH, KN, JA, JA, JA, TN, KN }, 	 //	 315	 760
{ QN, QN, QN, SH, JA, SH, SK, SK, TN, JA, JA, JA, JA, TN, JA }, 	 //	 316	 760
{ QN, QN, QN, SH, TN, SH, SK, SK, TN, TN, JA, JA, JA, TN, TN }, 	 //	 317	 760
{ QN, QN, QN, SH, PF, SH, SK, SK, TN, JA, JA, JA, JA, TN, TN }, 	 //	 318	 760
{ QN, QN, QN, SH, AC, SH, SK, SK, TN, SK, JA, JA, JA, TN, KN }, 	 //	 319	 760
{ QN, QN, QN, TN, QN, SH, SK, SK, TN, QN, JA, JA, JA, TN, QN }, 	 //	 320	 760
{ QN, QN, QN, TN, JA, SH, SK, SK, TN, JA, JA, JA, JA, TN, JA }, 	 //	 321	 760
{ QN, QN, QN, TN, TN, SH, SK, SK, TN, TN, JA, JA, JA, TN, TN }, 	 //	 322	 760
{ QN, QN, QN, TN, JA, SH, SK, SK, TN, TN, JA, JA, JA, TN, AC }, 	 //	 323	 760
{ QN, QN, QN, TN, TN, SH, SK, SK, TN, AC, JA, JA, JA, TN, AC }, 	 //	 324	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, TN, AC, JA, JA, JA, TN, LO }, 	 //	 325	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, TN, KN, JA, JA, JA, WN, SK }, 	 //	 326	 760
{ QN, QN, QN, TN, JA, SH, SK, SK, TN, JA, JA, JA, JA, WN, JA }, 	 //	 327	 760
{ QN, QN, QN, TN, AC, SH, SK, SK, TN, KN, JA, JA, JA, WN, QN }, 	 //	 328	 760
{ QN, QN, QN, TN, TN, SH, SK, SK, TN, AC, JA, JA, JA, WN, AC }, 	 //	 329	 760
{ QN, QN, QN, TN, SK, SH, SK, SK, TN, KN, JA, JA, JA, WN, KN }, 	 //	 330	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, WN, KN, JA, JA, JA, AC, SK }, 	 //	 331	 760
{ QN, QN, QN, TN, JA, SH, SK, SK, WN, JA, JA, JA, JA, AC, WN }, 	 //	 332	 760
{ QN, QN, QN, TN, QN, SH, SK, SK, WN, PF, JA, JA, JA, AC, JA }, 	 //	 333	 760
{ QN, QN, QN, TN, CR, SH, SK, SK, WN, QN, JA, JA, JA, AC, KN }, 	 //	 334	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, WN, AC, JA, JA, JA, AC, LO }, 	 //	 335	 760
{ QN, QN, QN, WN, CR, SH, SK, SK, AC, KN, JA, JA, JA, KN, KN }, 	 //	 336	 760
{ QN, QN, QN, WN, KN, SH, SK, SK, AC, KN, JA, JA, JA, KN, KN }, 	 //	 337	 760
{ QN, QN, QN, WN, QN, SH, SK, SK, AC, PF, JA, JA, JA, KN, JA }, 	 //	 338	 760
{ QN, QN, QN, WN, CR, SH, SK, SK, AC, QN, JA, JA, JA, KN, KN }, 	 //	 339	 760
{ QN, QN, QN, AC, LO, SH, SK, SK, KN, AC, JA, JA, JA, QN, AC }, 	 //	 340	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, KN, KN, JA, JA, JA, QN, SK }, 	 //	 341	 760
{ QN, QN, QN, AC, SH, SH, SK, SK, KN, JA, JA, JA, JA, QN, JA }, 	 //	 342	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, KN, QN, JA, JA, JA, QN, PF }, 	 //	 343	 760
{ QN, QN, QN, AC, TN, SH, SK, SK, KN, AC, JA, JA, JA, QN, AC }, 	 //	 344	 760
{ QN, QN, QN, KN, TN, SH, SK, SK, QN, TN, JA, JA, JA, ST, ST }, 	 //	 345	 760
{ QN, QN, QN, KN, PF, SH, SK, SK, QN, JA, JA, JA, JA, ST, TN }, 	 //	 346	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, QN, KN, JA, JA, JA, ST, KN }, 	 //	 347	 760
{ QN, QN, QN, KN, CR, SH, SK, SK, QN, QN, JA, JA, JA, ST, KN }, 	 //	 348	 760
{ QN, QN, QN, ST, AC, SH, SK, SK, JA, LO, JA, JA, JA, TN, AC }, 	 //	 349	 760
{ QN, QN, QN, ST, KN, SH, SK, SK, JA, KN, JA, JA, JA, TN, SK }, 	 //	 350	 760
{ QN, QN, QN, ST, SK, SH, SK, SK, JA, QN, JA, JA, JA, TN, QN }, 	 //	 351	 760
{ QN, QN, QN, ST, QN, SH, SK, SK, JA, QN, JA, JA, JA, TN, SH }, 	 //	 352	 760
{ QN, QN, QN, ST, QN, SH, SK, SK, JA, SH, JA, JA, JA, TN, JA }, 	 //	 353	 760
{ QN, QN, QN, ST, TN, SH, SK, SK, JA, ST, JA, JA, JA, TN, AC }, 	 //	 354	 760
{ QN, QN, QN, ST, AC, SH, SK, SK, JA, SK, JA, JA, JA, TN, KN }, 	 //	 355	 760
{ QN, QN, QN, JA, KN, SH, SK, SK, TN, KN, JA, JA, JA, AC, SK }, 	 //	 356	 760
{ QN, QN, QN, JA, KN, SH, SK, SK, TN, SK, JA, JA, JA, AC, QN }, 	 //	 357	 760
{ QN, QN, QN, JA, QN, SH, SK, SK, TN, QN, JA, JA, JA, AC, SH }, 	 //	 358	 760
{ QN, QN, QN, JA, JA, SH, SK, SK, TN, JA, JA, JA, JA, AC, JA }, 	 //	 359	 760
{ QN, QN, QN, JA, JA, SH, SK, SK, TN, JA, JA, JA, JA, AC, WN }, 	 //	 360	 760
{ QN, QN, QN, JA, TN, SH, SK, SK, TN, TN, JA, JA, JA, AC, TN }, 	 //	 361	 760
{ QN, QN, QN, JA, QN, SH, SK, SK, TN, PF, JA, JA, JA, AC, JA }, 	 //	 362	 760
{ QN, QN, QN, TN, AC, SH, SK, SK, AC, AC, JA, JA, JA, AC, CR }, 	 //	 363	 760
{ QN, QN, QN, TN, QN, SH, SK, SK, AC, QN, JA, JA, JA, AC, QN }, 	 //	 364	 760
{ QN, QN, QN, TN, QN, SH, SK, SK, AC, QN, JA, JA, JA, AC, SH }, 	 //	 365	 760
{ QN, QN, QN, TN, WN, SH, SK, SK, AC, TN, JA, JA, JA, AC, TN }, 	 //	 366	 760
{ QN, QN, QN, TN, PF, SH, SK, SK, AC, JA, JA, JA, JA, AC, TN }, 	 //	 367	 760
{ QN, QN, QN, TN, AC, SH, SK, SK, AC, SK, JA, JA, JA, AC, KN }, 	 //	 368	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, AC, KN, JA, JA, JA, AC, KN }, 	 //	 369	 760
{ QN, QN, QN, TN, KN, SH, SK, SK, AC, KN, JA, JA, JA, AC, CR }, 	 //	 370	 760
{ QN, QN, QN, AC, TN, SH, SK, SK, AC, TN, JA, JA, JA, AC, ST }, 	 //	 371	 760
{ QN, QN, QN, AC, ST, SH, SK, SK, AC, AC, JA, JA, JA, AC, KN }, 	 //	 372	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 373	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, KN, JA, JA, JA, AC, KN }, 	 //	 374	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, KN, JA, JA, JA, AC, CR }, 	 //	 375	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, KN, JA, JA, JA, PF, KN }, 	 //	 376	 760
{ QN, QN, QN, AC, KN, SH, SK, SK, AC, KN, JA, JA, JA, PF, SK }, 	 //	 377	 760
{ QN, QN, QN, AC, SK, SH, SK, SK, AC, QN, JA, JA, JA, PF, QN }, 	 //	 378	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, AC, QN, JA, JA, JA, PF, QN }, 	 //	 379	 760
{ QN, QN, QN, AC, PF, SH, SK, SK, AC, JA, JA, JA, JA, PF, TN }, 	 //	 380	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, AC, AC, JA, JA, JA, PF, AC }, 	 //	 381	 760
{ QN, QN, QN, AC, AC, SH, SK, SK, PF, LO, JA, JA, JA, KN, AC }, 	 //	 382	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, PF, QN, JA, JA, JA, KN, QN }, 	 //	 383	 760
{ QN, QN, QN, AC, ST, SH, SK, SK, PF, AC, JA, JA, JA, KN, KN }, 	 //	 384	 760
{ QN, QN, QN, AC, QN, SH, SK, SK, PF, PF, JA, JA, JA, KN, JA }, 	 //	 385	 760
{ QN, QN, QN, AC, TN, SH, SK, SK, PF, AC, JA, JA, JA, KN, AC }, 	 //	 386	 760
{ QN, QN, QN, PF, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 387	 760
{ QN, QN, QN, PF, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, SK }, 	 //	 388	 760
{ QN, QN, QN, PF, SK, SH, SK, SK, KN, QN, JA, JA, JA, KN, QN }, 	 //	 389	 760
{ QN, QN, QN, PF, WN, SH, SK, SK, KN, TN, JA, JA, JA, KN, TN }, 	 //	 390	 760
{ QN, QN, QN, PF, ST, SH, SK, SK, KN, AC, JA, JA, JA, KN, KN }, 	 //	 391	 760
{ QN, QN, QN, PF, JA, SH, SK, SK, KN, TN, JA, JA, JA, KN, AC }, 	 //	 392	 760
{ QN, QN, QN, PF, SK, SH, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 393	 760
{ QN, QN, QN, PF, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, CR }, 	 //	 394	 760
{ QN, QN, QN, KN, CR, SH, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 395	 760
{ QN, QN, QN, KN, TN, SH, SK, SK, KN, TN, JA, JA, JA, KN, ST }, 	 //	 396	 760
{ QN, QN, QN, KN, PF, SH, SK, SK, KN, JA, JA, JA, JA, KN, TN }, 	 //	 397	 760
{ QN, QN, QN, KN, AC, SH, SK, SK, KN, AC, JA, JA, JA, KN, SK }, 	 //	 398	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 399	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, KN, KN, JA, JA, JA, KN, CR }, 	 //	 400	 760
{ QN, QN, QN, KN, CR, SH, SK, SK, KN, QN, JA, JA, JA, KN, KN }, 	 //	 401	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, KN, KN, JA, JA, JA, KN, AC }, 	 //	 402	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, KN, AC, JA, JA, JA, KN, LO }, 	 //	 403	 760
{ QN, QN, QN, KN, KN, SH, SK, SK, KN, KN, JA, JA, JA, SK, KN }, 	 //	 404	 760
{ QN, QN, QN, KN, SK, SH, SK, SK, KN, QN, JA, JA, JA, SK, QN }, 	 //	 405	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, KN, QN, JA, JA, JA, SK, QN }, 	 //	 406	 760
{ QN, QN, QN, KN, JA, SH, SK, SK, KN, JA, JA, JA, JA, SK, JA }, 	 //	 407	 760
{ QN, QN, QN, KN, CR, SH, SK, SK, KN, QN, JA, JA, JA, SK, KN }, 	 //	 408	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, KN, KN, JA, JA, JA, SK, AC }, 	 //	 409	 760
{ QN, QN, QN, SK, AC, SH, SK, SK, QN, AC, JA, JA, JA, KN, CR }, 	 //	 410	 760
{ QN, QN, QN, SK, SH, SH, SK, SK, QN, JA, JA, JA, JA, KN, JA }, 	 //	 411	 760
{ QN, QN, QN, SK, JA, SH, SK, SK, QN, JA, JA, JA, JA, KN, JA }, 	 //	 412	 760
{ QN, QN, QN, SK, TN, SH, SK, SK, QN, TN, JA, JA, JA, KN, TN }, 	 //	 413	 760
{ QN, QN, QN, SK, KN, SH, SK, SK, QN, QN, JA, JA, JA, KN, PF }, 	 //	 414	 760
{ QN, QN, QN, SK, JA, SH, SK, SK, QN, TN, JA, JA, JA, KN, AC }, 	 //	 415	 760
{ QN, QN, QN, SK, AC, SH, SK, SK, QN, AC, JA, JA, JA, KN, SK }, 	 //	 416	 760
{ QN, QN, QN, SK, KN, SH, SK, SK, QN, KN, JA, JA, JA, KN, CR }, 	 //	 417	 760
{ QN, QN, QN, KN, QN, SH, SK, SK, AC, SH, JA, JA, JA, PF, JA }, 	 //	 418	 760
{ QN, QN, QN, KN, TN, SH, SK, SK, AC, TN, JA, JA, JA, PF, ST }, 	 //	 419	 760
{ QN, QN, QN, KN, ST, SH, SK, SK, AC, AC, JA, JA, JA, PF, KN }, 	 //	 420	 760
{ QN, QN, QN, KN, TN, SH, SK, SK, AC, AC, JA, JA, JA, PF, AC }, 	 //	 421	 760
{ QN, JA, QN, QN, QN, SH, JA, SK, SK, PF, JA, SH, JA, JA, JA }, 	 //	 422	 760
{ QN, SH, QN, QN, QN, SH, TN, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 423	 760
{ QN, TN, QN, QN, QN, SH, TN, SK, SK, PF, JA, WN, JA, JA, JA }, 	 //	 424	 760
{ QN, TN, QN, QN, QN, SH, WN, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 425	 760
{ QN, WN, QN, QN, QN, SH, AC, SK, SK, SH, JA, KN, JA, JA, JA }, 	 //	 426	 760
{ QN, QN, QN, KN, CR, SH, ST, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 427	 760
{ QN, QN, QN, KN, KN, SH, ST, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 428	 760
{ QN, QN, QN, KN, TN, SH, ST, SK, SK, TN, JA, JA, JA, QN, TN }, 	 //	 429	 760
{ QN, QN, QN, SK, SK, SH, ST, SK, QN, KN, JA, JA, JA, KN, KN }, 	 //	 430	 760
{ QN, ST, QN, QN, QN, SH, JA, SK, SK, SH, JA, TN, JA, JA, JA }, 	 //	 431	 760
{ QN, TN, QN, QN, QN, SH, AC, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 432	 760
{ QN, AC, QN, QN, QN, SH, AC, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 433	 760
{ QN, KN, QN, QN, QN, SH, KN, SK, SK, PF, JA, SK, JA, JA, JA }, 	 //	 434	 760
{ SH, AC, QN, QN, QN, JA, SH, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 435	 760
{ SH, AC, QN, QN, QN, JA, AC, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 436	 760
{ SH, AC, QN, QN, QN, JA, AC, SK, SK, PF, JA, AC, JA, JA, JA }, 	 //	 437	 760
{ SH, AC, QN, QN, QN, JA, LO, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 438	 760
{ SH, QN, QN, QN, SH, JA, QN, SK, SK, JA, JA, SK, JA, JA, JA }, 	 //	 439	 760
{ SH, QN, QN, QN, JA, JA, SK, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 440	 760
{ SH, QN, QN, QN, AC, JA, SK, SK, QN, LO, JA, JA, JA, SK, AC }, 	 //	 441	 760
{ SH, QN, QN, QN, TN, JA, SK, SK, QN, TN, JA, JA, JA, SK, TN }, 	 //	 442	 760
{ SH, QN, QN, QN, AC, JA, SK, SK, QN, SK, JA, JA, JA, SK, KN }, 	 //	 443	 760
{ SH, QN, QN, QN, KN, JA, SK, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 444	 760
{ SH, QN, QN, KN, KN, JA, SK, SK, QN, SK, JA, JA, JA, ST, QN }, 	 //	 445	 760
{ SH, QN, QN, KN, AC, JA, SK, SK, QN, KN, JA, JA, JA, ST, QN }, 	 //	 446	 760
{ SH, QN, QN, SK, KN, JA, SK, SK, QN, SK, JA, JA, JA, KN, QN }, 	 //	 447	 760
{ SH, QN, QN, SK, QN, JA, SK, SK, QN, QN, JA, JA, JA, KN, QN }, 	 //	 448	 760
{ SH, QN, QN, QN, TN, JA, SK, SK, KN, ST, JA, JA, JA, AC, AC }, 	 //	 449	 760
{ SH, QN, QN, QN, AC, JA, SK, SK, KN, KN, JA, JA, JA, AC, QN }, 	 //	 450	 760
{ SH, QN, QN, QN, AC, JA, SK, SK, KN, AC, JA, JA, JA, AC, SK }, 	 //	 451	 760
{ SH, QN, QN, QN, AC, JA, SK, SK, KN, SK, JA, JA, JA, AC, KN }, 	 //	 452	 760
{ SH, QN, QN, QN, CR, JA, SK, SK, KN, QN, JA, JA, JA, AC, KN }, 	 //	 453	 760
{ SH, JA, QN, QN, QN, JA, JA, SK, SK, SH, JA, SH, JA, JA, JA }, 	 //	 454	 760
{ SH, SH, QN, QN, QN, JA, TN, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 455	 760
{ SH, TN, QN, QN, QN, JA, TN, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 456	 760
{ SH, TN, QN, QN, QN, JA, TN, SK, SK, SH, JA, WN, JA, JA, JA }, 	 //	 457	 760
{ SH, TN, QN, QN, QN, JA, WN, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 458	 760
{ SH, KN, QN, QN, QN, JA, QN, SK, SK, PF, JA, ST, JA, JA, JA }, 	 //	 459	 760
{ SH, ST, QN, QN, QN, JA, JA, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 460	 760
{ SH, KN, QN, QN, QN, JA, SK, SK, ST, PF, JA, QN, JA, JA, JA }, 	 //	 461	 760
{ JA, AC, QN, QN, QN, JA, LO, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 462	 760
{ JA, QN, QN, QN, AC, JA, SK, SK, QN, LO, JA, JA, JA, QN, AC }, 	 //	 463	 760
{ JA, QN, QN, QN, SH, JA, SK, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 464	 760
{ JA, QN, QN, QN, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN, TN }, 	 //	 465	 760
{ JA, QN, QN, QN, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN, KN }, 	 //	 466	 760
{ JA, QN, QN, QN, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN, CR }, 	 //	 467	 760
{ JA, QN, QN, QN, AC, JA, SK, SK, QN, LO, JA, JA, JA, SK, AC }, 	 //	 468	 760
{ JA, QN, QN, QN, ST, JA, SK, SK, QN, AC, JA, JA, JA, SK, KN }, 	 //	 469	 760
{ JA, QN, QN, QN, PF, JA, SK, SK, QN, JA, JA, JA, JA, SK, TN }, 	 //	 470	 760
{ JA, QN, QN, QN, SK, JA, SK, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 471	 760
{ JA, QN, QN, QN, KN, JA, SK, SK, QN, KN, JA, JA, JA, SK, CR }, 	 //	 472	 760
{ JA, QN, QN, QN, CR, JA, SK, SK, QN, QN, JA, JA, JA, SK, KN }, 	 //	 473	 760
{ JA, QN, QN, KN, AC, JA, SK, SK, QN, KN, JA, JA, JA, ST, QN }, 	 //	 474	 760
{ JA, QN, QN, QN, LO, JA, SK, SK, KN, AC, JA, JA, JA, AC, AC }, 	 //	 475	 760
{ JA, QN, QN, QN, KN, JA, SK, SK, KN, KN, JA, JA, JA, AC, SK }, 	 //	 476	 760
{ JA, QN, QN, QN, AC, JA, SK, SK, KN, KN, JA, JA, JA, AC, QN }, 	 //	 477	 760
{ JA, QN, QN, QN, AC, JA, SK, SK, KN, AC, JA, JA, JA, AC, SK }, 	 //	 478	 760
{ JA, QN, QN, QN, KN, JA, SK, SK, KN, KN, JA, JA, JA, AC, CR }, 	 //	 479	 760
{ JA, SK, SK, ST, PF, JA, JA, JA, JA, JA, JA, JA, TN, TN, TN }, 	 //	 480	 760
{ JA, TN, QN, QN, QN, JA, WN, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 481	 760
{ JA, KN, QN, QN, QN, JA, QN, SK, SK, PF, JA, ST, JA, JA, JA }, 	 //	 482	 760
{ JA, QN, QN, SK, SK, JA, ST, SK, QN, QN, JA, JA, JA, KN, QN }, 	 //	 483	 760
{ JA, AC, QN, QN, QN, JA, AC, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 484	 760
{ JA, PF, QN, QN, QN, JA, KN, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 485	 760
{ JA, SK, QN, QN, QN, JA, QN, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 486	 760
{ JA, SH, QN, QN, QN, JA, AC, SK, SK, PF, WN, AC, JA, JA, JA }, 	 //	 487	 760
{ JA, AC, QN, QN, QN, JA, AC, SK, SK, PF, WN, AC, JA, JA, JA }, 	 //	 488	 760
{ JA, LO, QN, QN, QN, JA, KN, SK, SK, SH, WN, KN, JA, JA, JA }, 	 //	 489	 760
{ JA, LO, QN, QN, QN, JA, KN, SK, SK, PF, WN, KN, JA, JA, JA }, 	 //	 490	 760
{ JA, KN, QN, QN, QN, JA, KN, SK, SK, PF, WN, KN, JA, JA, JA }, 	 //	 491	 760
{ JA, QN, QN, QN, AC, JA, SK, SK, ST, AC, WN, JA, JA, JA, AC }, 	 //	 492	 760
{ JA, QN, QN, QN, TN, JA, SK, SK, ST, TN, WN, JA, JA, JA, ST }, 	 //	 493	 760
{ JA, QN, QN, QN, PF, JA, SK, SK, ST, JA, WN, JA, JA, JA, TN }, 	 //	 494	 760
{ JA, QN, QN, QN, TN, JA, SK, SK, ST, AC, WN, JA, JA, JA, AC }, 	 //	 495	 760
{ JA, QN, QN, QN, SK, JA, SK, SK, ST, KN, WN, JA, JA, JA, KN }, 	 //	 496	 760
{ JA, JA, QN, QN, QN, JA, JA, SK, SK, KN, WN, SH, JA, JA, AC }, 	 //	 497	 760
{ JA, TN, QN, QN, QN, JA, TN, SK, SK, SH, WN, WN, JA, JA, JA }, 	 //	 498	 760
{ JA, WN, QN, QN, QN, JA, AC, SK, SK, PF, WN, KN, JA, JA, JA }, 	 //	 499	 760
{ JA, AC, QN, QN, QN, JA, KN, SK, SK, SH, WN, QN, JA, JA, JA }, 	 //	 500	 760
{ JA, KN, QN, QN, QN, JA, QN, SK, SK, PF, WN, ST, JA, JA, JA }, 	 //	 501	 760
{ JA, QN, QN, QN, JA, JA, ST, SK, SK, JA, WN, JA, JA, JA, WN }, 	 //	 502	 760
{ JA, QN, QN, QN, KN, JA, ST, SK, SK, QN, WN, JA, JA, JA, PF }, 	 //	 503	 760
{ JA, QN, QN, QN, JA, JA, ST, SK, SK, TN, WN, JA, JA, JA, AC }, 	 //	 504	 760
{ JA, PF, QN, QN, QN, JA, KN, SK, SK, PF, WN, KN, JA, JA, JA }, 	 //	 505	 760
{ JA, KN, QN, QN, QN, JA, KN, SK, SK, SH, WN, SK, JA, JA, JA }, 	 //	 506	 760
{ JA, SK, QN, QN, QN, JA, QN, SK, SK, SH, WN, KN, JA, JA, JA }, 	 //	 507	 760
{ JA, QN, QN, QN, JA, JA, KN, SK, SK, JA, WN, AC, JA, JA, JA }, 	 //	 508	 760
{ JA, KN, QN, QN, QN, JA, AC, SK, SK, SH, WN, SH, JA, JA, JA }, 	 //	 509	 760
{ JA, AC, QN, QN, QN, WN, SH, SK, SK, SH, TN, AC, JA, JA, JA }, 	 //	 510	 760
{ JA, LO, QN, QN, QN, WN, KN, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 511	 760
{ JA, KN, QN, QN, QN, WN, KN, SK, SK, SH, TN, ST, JA, JA, JA }, 	 //	 512	 760
{ JA, KN, QN, QN, QN, WN, KN, SK, SK, PF, TN, ST, JA, JA, JA }, 	 //	 513	 760
{ JA, QN, QN, QN, SH, WN, QN, SK, SK, JA, TN, QN, JA, JA, JA }, 	 //	 514	 760
{ JA, QN, QN, QN, JA, WN, QN, SK, SK, JA, TN, QN, JA, JA, JA }, 	 //	 515	 760
{ JA, QN, QN, QN, ST, WN, SK, SK, ST, AC, TN, JA, JA, JA, KN }, 	 //	 516	 760
{ JA, QN, QN, QN, SK, WN, SK, SK, ST, KN, TN, JA, JA, JA, KN }, 	 //	 517	 760
{ JA, QN, QN, QN, CR, WN, SK, SK, ST, QN, TN, JA, JA, JA, KN }, 	 //	 518	 760
{ JA, JA, QN, SK, SK, WN, JA, SK, QN, QN, TN, SH, JA, KN, QN }, 	 //	 519	 760
{ JA, JA, QN, QN, QN, WN, SH, SK, SK, SH, TN, TN, JA, JA, JA }, 	 //	 520	 760
{ JA, AC, QN, QN, QN, WN, KN, SK, SK, PF, TN, QN, JA, JA, JA }, 	 //	 521	 760
{ JA, QN, QN, QN, LO, WN, ST, SK, SK, AC, TN, JA, JA, JA, AC }, 	 //	 522	 760
{ JA, QN, QN, QN, AC, WN, ST, SK, SK, AC, TN, JA, JA, JA, CR }, 	 //	 523	 760
{ JA, QN, QN, QN, CR, WN, ST, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 524	 760
{ JA, QN, QN, QN, WN, WN, ST, SK, SK, TN, TN, JA, JA, JA, TN }, 	 //	 525	 760
{ JA, QN, QN, QN, TN, WN, ST, SK, SK, TN, TN, JA, JA, JA, TN }, 	 //	 526	 760
{ JA, AC, QN, QN, QN, WN, AC, SK, SK, SH, TN, PF, JA, JA, JA }, 	 //	 527	 760
{ JA, AC, QN, QN, QN, WN, PF, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 528	 760
{ JA, QN, QN, QN, JA, WN, KN, SK, SK, JA, TN, AC, JA, JA, JA }, 	 //	 529	 760
{ WN, AC, QN, QN, QN, TN, AC, SK, SK, SH, TN, LO, JA, JA, JA }, 	 //	 530	 760
{ WN, AC, QN, QN, QN, TN, LO, SK, SK, PF, TN, KN, JA, JA, JA }, 	 //	 531	 760
{ WN, QN, QN, QN, SH, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA }, 	 //	 532	 760
{ WN, QN, QN, QN, PF, TN, SK, SK, ST, JA, TN, JA, JA, JA, TN }, 	 //	 533	 760
{ WN, QN, QN, QN, JA, TN, SK, SK, ST, TN, TN, JA, JA, JA, AC }, 	 //	 534	 760
{ WN, QN, QN, QN, KN, TN, SK, SK, ST, KN, TN, JA, JA, JA, KN }, 	 //	 535	 760
{ WN, QN, QN, QN, KN, TN, SK, SK, ST, AC, TN, JA, JA, JA, LO }, 	 //	 536	 760
{ WN, SK, QN, QN, QN, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 537	 760
{ WN, SH, QN, QN, QN, TN, TN, SK, SK, SH, TN, TN, JA, JA, JA }, 	 //	 538	 760
{ WN, TN, QN, QN, QN, TN, TN, SK, SK, SH, TN, TN, JA, JA, JA }, 	 //	 539	 760
{ WN, WN, QN, QN, QN, TN, AC, SK, SK, PF, TN, KN, JA, JA, JA }, 	 //	 540	 760
{ WN, QN, QN, QN, LO, TN, ST, SK, SK, AC, TN, JA, JA, JA, AC }, 	 //	 541	 760
{ WN, QN, QN, QN, AC, TN, ST, SK, SK, AC, TN, JA, JA, JA, CR }, 	 //	 542	 760
{ WN, AC, QN, QN, QN, TN, PF, SK, SK, PF, TN, KN, JA, JA, JA }, 	 //	 543	 760
{ WN, KN, QN, QN, QN, TN, KN, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 544	 760
{ WN, KN, QN, QN, QN, TN, SK, SK, ST, PF, TN, QN, JA, JA, JA }, 	 //	 545	 760
{ TN, AC, QN, QN, QN, TN, AC, SK, SK, PF, TN, LO, JA, JA, JA }, 	 //	 546	 760
{ TN, LO, QN, QN, QN, TN, KN, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 547	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, PF, TN, ST, JA, JA, JA }, 	 //	 548	 760
{ TN, QN, QN, QN, JA, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA }, 	 //	 549	 760
{ TN, QN, QN, QN, AC, TN, SK, SK, ST, LO, TN, JA, JA, JA, AC }, 	 //	 550	 760
{ TN, QN, QN, QN, ST, TN, SK, SK, ST, AC, TN, JA, JA, JA, KN }, 	 //	 551	 760
{ TN, JA, QN, QN, QN, TN, JA, SK, SK, PF, TN, SH, JA, JA, JA }, 	 //	 552	 760
{ TN, JA, QN, QN, QN, TN, SH, SK, SK, PF, TN, TN, JA, JA, JA }, 	 //	 553	 760
{ TN, QN, QN, QN, WN, TN, ST, SK, SK, TN, TN, JA, JA, JA, TN }, 	 //	 554	 760
{ TN, QN, QN, QN, TN, TN, ST, SK, SK, TN, TN, JA, JA, JA, ST }, 	 //	 555	 760
{ TN, QN, QN, QN, ST, TN, ST, SK, SK, AC, TN, JA, JA, JA, KN }, 	 //	 556	 760
{ TN, QN, QN, QN, AC, TN, ST, SK, SK, AC, TN, JA, JA, JA, AC }, 	 //	 557	 760
{ TN, QN, QN, QN, KN, TN, ST, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 558	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 559	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, SH, TN, SK, JA, JA, JA }, 	 //	 560	 760
{ TN, QN, QN, QN, JA, TN, KN, SK, SK, JA, TN, AC, JA, JA, JA }, 	 //	 561	 760
{ TN, AC, QN, QN, QN, TN, LO, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 562	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 563	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, PF, ST, ST, JA, JA, JA }, 	 //	 564	 760
{ TN, QN, QN, QN, TN, TN, SK, SK, ST, TN, ST, JA, JA, JA, TN }, 	 //	 565	 760
{ TN, QN, QN, QN, TN, TN, SK, SK, ST, TN, ST, JA, JA, JA, ST }, 	 //	 566	 760
{ TN, QN, QN, QN, PF, TN, SK, SK, ST, JA, ST, JA, JA, JA, TN }, 	 //	 567	 760
{ TN, QN, QN, QN, AC, TN, SK, SK, ST, AC, ST, JA, JA, JA, AC }, 	 //	 568	 760
{ TN, QN, QN, QN, SK, TN, SK, SK, ST, KN, ST, JA, JA, JA, KN }, 	 //	 569	 760
{ TN, SH, QN, QN, QN, TN, TN, SK, SK, SH, ST, TN, JA, JA, JA }, 	 //	 570	 760
{ TN, QN, QN, QN, LO, TN, ST, SK, SK, AC, ST, JA, JA, JA, AC }, 	 //	 571	 760
{ TN, QN, QN, QN, TN, TN, ST, SK, SK, TN, ST, JA, JA, JA, TN }, 	 //	 572	 760
{ TN, QN, QN, QN, PF, TN, ST, SK, SK, JA, ST, JA, JA, JA, TN }, 	 //	 573	 760
{ TN, QN, QN, QN, KN, TN, ST, SK, SK, AC, ST, JA, JA, JA, LO }, 	 //	 574	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 575	 760
{ TN, KN, QN, QN, QN, TN, KN, SK, SK, SH, ST, SK, JA, JA, JA }, 	 //	 576	 760
{ TN, KN, QN, QN, QN, TN, SK, SK, ST, SH, ST, QN, JA, JA, JA }, 	 //	 577	 760
{ TN, SK, QN, QN, QN, TN, QN, SK, SK, SH, ST, KN, JA, JA, JA }, 	 //	 578	 760
{ TN, SK, QN, QN, QN, TN, QN, SK, SK, PF, ST, KN, JA, JA, JA }, 	 //	 579	 760
{ TN, KN, QN, QN, QN, TN, AC, SK, SK, SH, ST, SH, JA, JA, JA }, 	 //	 580	 760
{ TN, SH, QN, QN, QN, ST, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 581	 760
{ TN, AC, QN, QN, QN, ST, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 582	 760
{ TN, AC, QN, QN, QN, ST, AC, SK, SK, SH, AC, LO, JA, JA, JA }, 	 //	 583	 760
{ TN, LO, QN, QN, QN, ST, KN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 584	 760
{ TN, KN, QN, QN, QN, ST, KN, SK, SK, SH, AC, ST, JA, JA, JA }, 	 //	 585	 760
{ TN, QN, QN, QN, JA, ST, QN, SK, SK, JA, AC, QN, JA, JA, JA }, 	 //	 586	 760
{ TN, QN, QN, QN, LO, ST, SK, SK, ST, AC, AC, JA, JA, JA, AC }, 	 //	 587	 760
{ TN, QN, QN, QN, ST, ST, SK, SK, ST, AC, AC, JA, JA, JA, KN }, 	 //	 588	 760
{ TN, QN, QN, QN, AC, ST, SK, SK, ST, KN, AC, JA, JA, JA, QN }, 	 //	 589	 760
{ TN, QN, QN, QN, PF, ST, SK, SK, ST, JA, AC, JA, JA, JA, TN }, 	 //	 590	 760
{ TN, QN, QN, QN, CR, ST, SK, SK, ST, QN, AC, JA, JA, JA, KN }, 	 //	 591	 760
{ TN, TN, QN, QN, QN, ST, TN, SK, SK, SH, AC, WN, JA, JA, JA }, 	 //	 592	 760
{ TN, TN, QN, QN, QN, ST, TN, SK, SK, PF, AC, WN, JA, JA, JA }, 	 //	 593	 760
{ TN, KN, QN, QN, QN, ST, QN, SK, SK, SH, AC, ST, JA, JA, JA }, 	 //	 594	 760
{ TN, QN, QN, QN, LO, ST, ST, SK, SK, AC, AC, JA, JA, JA, AC }, 	 //	 595	 760
{ TN, QN, QN, QN, PF, ST, ST, SK, SK, JA, AC, JA, JA, JA, TN }, 	 //	 596	 760
{ TN, QN, QN, QN, KN, ST, ST, SK, SK, AC, AC, JA, JA, JA, LO }, 	 //	 597	 760
{ TN, ST, QN, QN, QN, ST, JA, SK, SK, PF, AC, TN, JA, JA, JA }, 	 //	 598	 760
{ TN, TN, QN, QN, QN, ST, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 599	 760
{ TN, AC, QN, QN, QN, ST, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 600	 760
{ TN, PF, QN, QN, QN, ST, KN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 601	 760
{ TN, KN, QN, QN, QN, ST, SK, SK, ST, PF, AC, QN, JA, JA, JA }, 	 //	 602	 760
{ ST, AC, QN, QN, QN, AC, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 603	 760
{ ST, QN, QN, QN, AC, AC, SK, SK, ST, AC, KN, JA, JA, JA, CR }, 	 //	 604	 760
{ ST, QN, QN, QN, JA, AC, SK, SK, ST, WN, KN, JA, JA, JA, TN }, 	 //	 605	 760
{ ST, QN, QN, QN, PF, AC, SK, SK, ST, JA, KN, JA, JA, JA, TN }, 	 //	 606	 760
{ ST, QN, QN, QN, AC, AC, SK, SK, ST, AC, KN, JA, JA, JA, AC }, 	 //	 607	 760
{ ST, QN, QN, QN, AC, AC, SK, SK, ST, SK, KN, JA, JA, JA, KN }, 	 //	 608	 760
{ ST, JA, QN, QN, QN, AC, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 609	 760
{ ST, WN, QN, QN, QN, AC, AC, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 610	 760
{ ST, WN, QN, QN, QN, AC, AC, SK, SK, PF, KN, KN, JA, JA, JA }, 	 //	 611	 760
{ ST, KN, QN, QN, QN, AC, QN, SK, SK, PF, KN, ST, JA, JA, JA }, 	 //	 612	 760
{ ST, QN, QN, QN, TN, AC, ST, SK, SK, TN, KN, JA, JA, JA, TN }, 	 //	 613	 760
{ ST, QN, QN, QN, TN, AC, ST, SK, SK, ST, KN, JA, JA, JA, AC }, 	 //	 614	 760
{ ST, QN, QN, QN, ST, AC, ST, SK, SK, AC, KN, JA, JA, JA, KN }, 	 //	 615	 760
{ ST, QN, QN, QN, AC, AC, ST, SK, SK, KN, KN, JA, JA, JA, QN }, 	 //	 616	 760
{ ST, QN, QN, QN, JA, AC, ST, SK, SK, TN, KN, JA, JA, JA, AC }, 	 //	 617	 760
{ ST, QN, QN, QN, TN, AC, ST, SK, SK, AC, KN, JA, JA, JA, AC }, 	 //	 618	 760
{ ST, QN, QN, QN, CR, AC, ST, SK, SK, QN, KN, JA, JA, JA, KN }, 	 //	 619	 760
{ ST, JA, QN, QN, QN, AC, TN, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 620	 760
{ ST, KN, QN, QN, QN, AC, KN, SK, SK, SH, KN, SK, JA, JA, JA }, 	 //	 621	 760
{ AC, SH, QN, QN, QN, KN, AC, SK, SK, SH, QN, AC, JA, JA, JA }, 	 //	 622	 760
{ AC, ST, QN, QN, SH, KN, QN, SK, SK, JA, QN, QN, JA, JA, JA }, 	 //	 623	 760
{ AC, QN, QN, QN, SK, KN, SK, SK, ST, QN, QN, JA, JA, JA, QN }, 	 //	 624	 760
{ AC, QN, QN, QN, JA, KN, SK, SK, ST, JA, QN, JA, JA, JA, WN }, 	 //	 625	 760
{ AC, QN, QN, QN, PF, KN, SK, SK, ST, JA, QN, JA, JA, JA, TN }, 	 //	 626	 760
{ AC, QN, QN, QN, SK, KN, SK, SK, ST, KN, QN, JA, JA, JA, KN }, 	 //	 627	 760
{ AC, SK, QN, QN, QN, KN, JA, SK, SK, KN, QN, JA, JA, JA, AC }, 	 //	 628	 760
{ AC, JA, QN, QN, QN, KN, JA, SK, SK, QN, QN, JA, JA, JA, SH }, 	 //	 629	 760
{ AC, JA, QN, QN, QN, KN, JA, SK, SK, KN, QN, JA, JA, JA, AC }, 	 //	 630	 760
{ AC, TN, QN, QN, QN, KN, TN, SK, SK, PF, QN, WN, JA, JA, JA }, 	 //	 631	 760
{ AC, AC, QN, QN, QN, KN, KN, SK, SK, PF, QN, QN, JA, JA, JA }, 	 //	 632	 760
{ AC, KN, QN, QN, SH, KN, QN, SK, SK, JA, QN, ST, JA, JA, JA }, 	 //	 633	 760
{ AC, QN, QN, QN, TN, KN, ST, SK, SK, TN, QN, JA, JA, JA, TN }, 	 //	 634	 760
{ AC, QN, QN, QN, ST, KN, ST, SK, SK, AC, QN, JA, JA, JA, KN }, 	 //	 635	 760
{ AC, AC, QN, QN, QN, KN, AC, SK, SK, PF, QN, PF, JA, JA, JA }, 	 //	 636	 760
{ AC, KN, QN, QN, QN, KN, SK, SK, ST, PF, QN, QN, JA, JA, JA }, 	 //	 637	 760
{ KN, AC, QN, QN, QN, QN, LO, SK, SK, SH, PF, KN, JA, JA, JA }, 	 //	 638	 760
{ KN, KN, QN, QN, QN, QN, KN, SK, SK, SH, PF, ST, JA, JA, JA }, 	 //	 639	 760
{ KN, ST, QN, QN, QN, QN, QN, SK, SK, SH, PF, QN, JA, JA, JA }, 	 //	 640	 760
{ KN, QN, QN, QN, LO, QN, SK, SK, ST, AC, PF, JA, JA, JA, AC }, 	 //	 641	 760
{ KN, QN, QN, QN, KN, QN, SK, SK, ST, SK, PF, JA, JA, JA, QN }, 	 //	 642	 760
{ KN, QN, QN, QN, SK, QN, SK, SK, ST, KN, PF, JA, JA, JA, KN }, 	 //	 643	 760
{ KN, QN, QN, QN, CR, QN, SK, SK, ST, QN, PF, JA, JA, JA, KN }, 	 //	 644	 760
{ KN, SK, QN, QN, QN, QN, JA, SK, SK, KN, PF, JA, JA, JA, AC }, 	 //	 645	 760
{ KN, TN, QN, QN, QN, QN, TN, SK, SK, SH, PF, WN, JA, JA, JA }, 	 //	 646	 760
{ KN, TN, QN, QN, QN, QN, TN, SK, SK, PF, PF, WN, JA, JA, JA }, 	 //	 647	 760
{ KN, TN, QN, QN, QN, QN, WN, SK, SK, SH, PF, AC, JA, JA, JA }, 	 //	 648	 760
{ KN, WN, QN, QN, QN, QN, AC, SK, SK, SH, PF, KN, JA, JA, JA }, 	 //	 649	 760
{ KN, QN, QN, QN, AC, QN, ST, SK, SK, AC, PF, JA, JA, JA, CR }, 	 //	 650	 760
{ KN, QN, QN, QN, PF, QN, ST, SK, SK, JA, PF, JA, JA, JA, TN }, 	 //	 651	 760
{ KN, QN, QN, QN, KN, QN, ST, SK, SK, KN, PF, JA, JA, JA, KN }, 	 //	 652	 760
{ KN, QN, QN, QN, CR, QN, ST, SK, SK, QN, PF, JA, JA, JA, KN }, 	 //	 653	 760
{ KN, JA, QN, QN, QN, QN, TN, SK, SK, SH, PF, AC, JA, JA, JA }, 	 //	 654	 760
{ KN, KN, QN, QN, QN, QN, KN, SK, SK, SH, PF, KN, JA, JA, JA }, 	 //	 655	 760
{ KN, SK, QN, QN, QN, QN, QN, SK, SK, PF, PF, KN, JA, JA, JA }, 	 //	 656	 760
{ KN, QN, QN, QN, JA, QN, KN, SK, SK, JA, PF, AC, JA, JA, JA }, 	 //	 657	 760
{ QN, AC, QN, QN, QN, PF, AC, SK, SK, PF, JA, LO, JA, JA, JA }, 	 //	 658	 760
{ QN, LO, QN, QN, QN, PF, KN, SK, SK, SH, JA, KN, JA, JA, JA }, 	 //	 659	 760
{ QN, KN, QN, QN, QN, PF, KN, SK, SK, SH, JA, KN, JA, JA, JA }, 	 //	 660	 760
{ QN, KN, QN, QN, QN, PF, ST, SK, SK, PF, JA, QN, JA, JA, JA }, 	 //	 661	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, PF, LO, JA, JA, JA, AC, AC }, 	 //	 662	 760
{ QN, QN, QN, AC, ST, PF, SK, SK, PF, AC, JA, JA, JA, AC, KN }, 	 //	 663	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, PF, KN, JA, JA, JA, AC, QN }, 	 //	 664	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, PF, QN, JA, JA, JA, AC, PF }, 	 //	 665	 760
{ QN, QN, QN, AC, PF, PF, SK, SK, PF, JA, JA, JA, JA, AC, TN }, 	 //	 666	 760
{ QN, QN, QN, AC, SK, PF, SK, SK, PF, KN, JA, JA, JA, AC, KN }, 	 //	 667	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, PF, KN, JA, JA, JA, AC, KN }, 	 //	 668	 760
{ QN, QN, QN, PF, LO, PF, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 669	 760
{ QN, QN, QN, PF, KN, PF, SK, SK, AC, SK, JA, JA, JA, AC, QN }, 	 //	 670	 760
{ QN, QN, QN, PF, QN, PF, SK, SK, AC, SH, JA, JA, JA, AC, JA }, 	 //	 671	 760
{ QN, QN, QN, PF, WN, PF, SK, SK, AC, TN, JA, JA, JA, AC, TN }, 	 //	 672	 760
{ QN, QN, QN, PF, TN, PF, SK, SK, AC, TN, JA, JA, JA, AC, ST }, 	 //	 673	 760
{ QN, QN, QN, PF, TN, PF, SK, SK, AC, ST, JA, JA, JA, AC, AC }, 	 //	 674	 760
{ QN, QN, QN, PF, TN, PF, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 675	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, LO, JA, JA, JA, AC, AC }, 	 //	 676	 760
{ QN, QN, QN, AC, LO, PF, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 677	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, AC, JA, JA, JA, AC, CR }, 	 //	 678	 760
{ QN, QN, QN, AC, SK, PF, SK, SK, AC, QN, JA, JA, JA, AC, QN }, 	 //	 679	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, AC, ST, JA, JA, JA, AC, AC }, 	 //	 680	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, KN, JA, JA, JA, AC, QN }, 	 //	 681	 760
{ QN, QN, QN, AC, SK, PF, SK, SK, AC, KN, JA, JA, JA, AC, KN }, 	 //	 682	 760
{ QN, QN, QN, AC, LO, PF, SK, SK, AC, AC, JA, JA, JA, LO, AC }, 	 //	 683	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, AC, JA, JA, JA, LO, AC }, 	 //	 684	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, AC, KN, JA, JA, JA, LO, KN }, 	 //	 685	 760
{ QN, QN, QN, AC, SH, PF, SK, SK, AC, JA, JA, JA, JA, LO, JA }, 	 //	 686	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, AC, TN, JA, JA, JA, LO, TN }, 	 //	 687	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, AC, TN, JA, JA, JA, LO, ST }, 	 //	 688	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, AC, ST, JA, JA, JA, LO, AC }, 	 //	 689	 760
{ QN, QN, QN, AC, PF, PF, SK, SK, AC, JA, JA, JA, JA, LO, TN }, 	 //	 690	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, LO, SK, JA, JA, JA, KN, QN }, 	 //	 691	 760
{ QN, QN, QN, AC, QN, PF, SK, SK, LO, SH, JA, JA, JA, KN, JA }, 	 //	 692	 760
{ QN, QN, QN, AC, JA, PF, SK, SK, LO, JA, JA, JA, JA, KN, JA }, 	 //	 693	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, LO, KN, JA, JA, JA, KN, QN }, 	 //	 694	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, LO, QN, JA, JA, JA, KN, PF }, 	 //	 695	 760
{ QN, QN, QN, AC, QN, PF, SK, SK, LO, PF, JA, JA, JA, KN, JA }, 	 //	 696	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, LO, AC, JA, JA, JA, KN, AC }, 	 //	 697	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, LO, AC, JA, JA, JA, KN, AC }, 	 //	 698	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, LO, AC, JA, JA, JA, KN, SK }, 	 //	 699	 760
{ QN, QN, QN, AC, QN, PF, SK, SK, LO, KN, JA, JA, JA, KN, AC }, 	 //	 700	 760
{ QN, QN, QN, LO, AC, PF, SK, SK, KN, LO, JA, JA, JA, KN, AC }, 	 //	 701	 760
{ QN, QN, QN, LO, AC, PF, SK, SK, KN, AC, JA, JA, JA, KN, CR }, 	 //	 702	 760
{ QN, QN, QN, LO, CR, PF, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 703	 760
{ QN, QN, QN, LO, KN, PF, SK, SK, KN, SK, JA, JA, JA, KN, QN }, 	 //	 704	 760
{ QN, QN, QN, LO, JA, PF, SK, SK, KN, JA, JA, JA, JA, KN, JA }, 	 //	 705	 760
{ QN, QN, QN, LO, WN, PF, SK, SK, KN, TN, JA, JA, JA, KN, TN }, 	 //	 706	 760
{ QN, QN, QN, LO, TN, PF, SK, SK, KN, ST, JA, JA, JA, KN, AC }, 	 //	 707	 760
{ QN, QN, QN, LO, JA, PF, SK, SK, KN, TN, JA, JA, JA, KN, AC }, 	 //	 708	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 709	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, SK, JA, JA, JA, KN, QN }, 	 //	 710	 760
{ QN, QN, QN, KN, WN, PF, SK, SK, KN, TN, JA, JA, JA, KN, TN }, 	 //	 711	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, KN, AC }, 	 //	 712	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, KN, KN, JA, JA, JA, KN, AC }, 	 //	 713	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, LO, JA, JA, JA, WN, AC }, 	 //	 714	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, WN, AC }, 	 //	 715	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, WN, CR }, 	 //	 716	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, SK, JA, JA, JA, WN, QN }, 	 //	 717	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, KN, QN, JA, JA, JA, WN, SH }, 	 //	 718	 760
{ QN, QN, QN, KN, TN, PF, SK, SK, KN, TN, JA, JA, JA, WN, ST }, 	 //	 719	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, KN, PF, JA, JA, JA, WN, JA }, 	 //	 720	 760
{ QN, QN, QN, KN, PF, PF, SK, SK, KN, JA, JA, JA, JA, WN, TN }, 	 //	 721	 760
{ QN, QN, QN, KN, TN, PF, SK, SK, KN, AC, JA, JA, JA, WN, AC }, 	 //	 722	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, SK, JA, JA, JA, WN, KN }, 	 //	 723	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, KN, JA, JA, JA, WN, CR }, 	 //	 724	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, AC, JA, JA, JA, WN, LO }, 	 //	 725	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, WN, SK, JA, JA, JA, QN, QN }, 	 //	 726	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, WN, PF, JA, JA, JA, QN, JA }, 	 //	 727	 760
{ QN, QN, QN, KN, SK, PF, SK, SK, WN, KN, JA, JA, JA, QN, KN }, 	 //	 728	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, WN, KN, JA, JA, JA, QN, KN }, 	 //	 729	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, WN, KN, JA, JA, JA, QN, CR }, 	 //	 730	 760
{ QN, QN, QN, KN, CR, PF, SK, SK, WN, QN, JA, JA, JA, QN, KN }, 	 //	 731	 760
{ QN, QN, QN, WN, AC, PF, SK, SK, QN, LO, JA, JA, JA, QN, AC }, 	 //	 732	 760
{ QN, QN, QN, WN, JA, PF, SK, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 733	 760
{ QN, QN, QN, WN, TN, PF, SK, SK, QN, TN, JA, JA, JA, QN, ST }, 	 //	 734	 760
{ QN, QN, QN, WN, TN, PF, SK, SK, QN, ST, JA, JA, JA, QN, AC }, 	 //	 735	 760
{ QN, QN, QN, WN, KN, PF, SK, SK, QN, KN, JA, JA, JA, QN, KN }, 	 //	 736	 760
{ QN, QN, QN, WN, KN, PF, SK, SK, QN, AC, JA, JA, JA, QN, LO }, 	 //	 737	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, JA, AC, JA, JA, JA, SH, CR }, 	 //	 738	 760
{ QN, QN, QN, JA, KN, PF, SK, SK, JA, SK, JA, JA, JA, SH, QN }, 	 //	 739	 760
{ QN, QN, QN, JA, QN, PF, SK, SK, JA, SH, JA, JA, JA, SH, JA }, 	 //	 740	 760
{ QN, QN, QN, JA, TN, PF, SK, SK, JA, TN, JA, JA, JA, SH, TN }, 	 //	 741	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, JA, KN, JA, JA, JA, SH, QN }, 	 //	 742	 760
{ QN, QN, QN, JA, KN, PF, SK, SK, JA, QN, JA, JA, JA, SH, PF }, 	 //	 743	 760
{ QN, QN, QN, JA, PF, PF, SK, SK, JA, JA, JA, JA, JA, SH, TN }, 	 //	 744	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, JA, SK, JA, JA, JA, SH, KN }, 	 //	 745	 760
{ QN, QN, QN, JA, JA, PF, SK, SK, SH, JA, JA, JA, JA, TN, JA }, 	 //	 746	 760
{ QN, QN, QN, JA, JA, PF, SK, SK, SH, JA, JA, JA, JA, TN, WN }, 	 //	 747	 760
{ QN, QN, QN, JA, ST, PF, SK, SK, SH, AC, JA, JA, JA, TN, KN }, 	 //	 748	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, SH, KN, JA, JA, JA, TN, QN }, 	 //	 749	 760
{ QN, QN, QN, JA, PF, PF, SK, SK, SH, JA, JA, JA, JA, TN, TN }, 	 //	 750	 760
{ QN, QN, QN, JA, TN, PF, SK, SK, SH, AC, JA, JA, JA, TN, AC }, 	 //	 751	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, SH, SK, JA, JA, JA, TN, KN }, 	 //	 752	 760
{ QN, QN, QN, JA, CR, PF, SK, SK, SH, QN, JA, JA, JA, TN, KN }, 	 //	 753	 760
{ QN, QN, QN, JA, QN, PF, SK, SK, SH, KN, JA, JA, JA, TN, AC }, 	 //	 754	 760
{ QN, QN, QN, SH, LO, PF, SK, SK, TN, AC, JA, JA, JA, TN, AC }, 	 //	 755	 760
{ QN, QN, QN, SH, KN, PF, SK, SK, TN, SK, JA, JA, JA, TN, QN }, 	 //	 756	 760
{ QN, QN, QN, SH, WN, PF, SK, SK, TN, TN, JA, JA, JA, TN, TN }, 	 //	 757	 760
{ QN, QN, QN, SH, PF, PF, SK, SK, TN, JA, JA, JA, JA, TN, TN }, 	 //	 758	 760
{ QN, QN, QN, SH, AC, PF, SK, SK, TN, AC, JA, JA, JA, TN, SK }, 	 //	 759	 760
{ QN, QN, QN, SH, KN, PF, SK, SK, TN, KN, JA, JA, JA, TN, CR }, 	 //	 760	 760
{ QN, QN, QN, TN, SH, PF, SK, SK, TN, JA, JA, JA, JA, TN, JA }, 	 //	 761	 760
{ QN, QN, QN, TN, ST, PF, SK, SK, TN, AC, JA, JA, JA, TN, KN }, 	 //	 762	 760
{ QN, QN, QN, TN, AC, PF, SK, SK, TN, KN, JA, JA, JA, TN, QN }, 	 //	 763	 760
{ QN, QN, QN, TN, KN, PF, SK, SK, TN, SK, JA, JA, JA, WN, QN }, 	 //	 764	 760
{ QN, QN, QN, TN, QN, PF, SK, SK, TN, SH, JA, JA, JA, WN, JA }, 	 //	 765	 760
{ QN, QN, QN, TN, TN, PF, SK, SK, TN, TN, JA, JA, JA, WN, TN }, 	 //	 766	 760
{ QN, QN, QN, TN, KN, PF, SK, SK, TN, QN, JA, JA, JA, WN, PF }, 	 //	 767	 760
{ QN, QN, QN, TN, QN, PF, SK, SK, TN, PF, JA, JA, JA, WN, JA }, 	 //	 768	 760
{ QN, QN, QN, TN, KN, PF, SK, SK, WN, KN, JA, JA, JA, AC, KN }, 	 //	 769	 760
{ QN, QN, QN, TN, JA, PF, SK, SK, WN, JA, JA, JA, JA, AC, JA }, 	 //	 770	 760
{ QN, QN, QN, TN, WN, PF, SK, SK, WN, TN, JA, JA, JA, AC, TN }, 	 //	 771	 760
{ QN, QN, QN, TN, TN, PF, SK, SK, WN, TN, JA, JA, JA, AC, ST }, 	 //	 772	 760
{ QN, QN, QN, TN, TN, PF, SK, SK, WN, ST, JA, JA, JA, AC, AC }, 	 //	 773	 760
{ QN, QN, QN, TN, PF, PF, SK, SK, WN, JA, JA, JA, JA, AC, TN }, 	 //	 774	 760
{ QN, QN, QN, WN, AC, PF, SK, SK, AC, AC, JA, JA, JA, KN, AC }, 	 //	 775	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, KN, AC, JA, JA, JA, QN, CR }, 	 //	 776	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, KN, KN, JA, JA, JA, QN, KN }, 	 //	 777	 760
{ QN, QN, QN, AC, SH, PF, SK, SK, KN, JA, JA, JA, JA, QN, JA }, 	 //	 778	 760
{ QN, QN, QN, AC, JA, PF, SK, SK, KN, JA, JA, JA, JA, QN, WN }, 	 //	 779	 760
{ QN, QN, QN, KN, CR, PF, SK, SK, QN, KN, JA, JA, JA, ST, KN }, 	 //	 780	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, QN, KN, JA, JA, JA, ST, SK }, 	 //	 781	 760
{ QN, QN, QN, KN, TN, PF, SK, SK, QN, ST, JA, JA, JA, ST, AC }, 	 //	 782	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, QN, AC, JA, JA, JA, ST, SK }, 	 //	 783	 760
{ QN, QN, QN, KN, SK, PF, SK, SK, QN, KN, JA, JA, JA, ST, KN }, 	 //	 784	 760
{ QN, QN, QN, ST, AC, PF, SK, SK, JA, AC, JA, JA, JA, TN, CR }, 	 //	 785	 760
{ QN, QN, QN, ST, CR, PF, SK, SK, JA, KN, JA, JA, JA, TN, KN }, 	 //	 786	 760
{ QN, QN, QN, ST, KN, PF, SK, SK, JA, KN, JA, JA, JA, TN, KN }, 	 //	 787	 760
{ QN, QN, QN, ST, AC, PF, SK, SK, JA, AC, JA, JA, JA, TN, AC }, 	 //	 788	 760
{ QN, QN, QN, JA, KN, PF, SK, SK, TN, KN, JA, JA, JA, AC, SK }, 	 //	 789	 760
{ QN, QN, QN, JA, JA, PF, SK, SK, TN, JA, JA, JA, JA, AC, JA }, 	 //	 790	 760
{ QN, QN, QN, JA, WN, PF, SK, SK, TN, TN, JA, JA, JA, AC, TN }, 	 //	 791	 760
{ QN, QN, QN, JA, TN, PF, SK, SK, TN, TN, JA, JA, JA, AC, ST }, 	 //	 792	 760
{ QN, QN, QN, JA, PF, PF, SK, SK, TN, JA, JA, JA, JA, AC, TN }, 	 //	 793	 760
{ QN, QN, QN, JA, AC, PF, SK, SK, TN, AC, JA, JA, JA, AC, SK }, 	 //	 794	 760
{ QN, QN, QN, JA, KN, PF, SK, SK, TN, KN, JA, JA, JA, AC, KN }, 	 //	 795	 760
{ QN, QN, QN, TN, LO, PF, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 796	 760
{ QN, QN, QN, TN, AC, PF, SK, SK, AC, AC, JA, JA, JA, AC, AC }, 	 //	 797	 760
{ QN, QN, QN, TN, AC, PF, SK, SK, AC, AC, JA, JA, JA, AC, CR }, 	 //	 798	 760
{ QN, QN, QN, TN, KN, PF, SK, SK, AC, KN, JA, JA, JA, AC, KN }, 	 //	 799	 760
{ QN, QN, QN, TN, QN, PF, SK, SK, AC, QN, JA, JA, JA, AC, SH }, 	 //	 800	 760
{ QN, QN, QN, TN, JA, PF, SK, SK, AC, WN, JA, JA, JA, AC, TN }, 	 //	 801	 760
{ QN, QN, QN, TN, SK, PF, SK, SK, AC, KN, JA, JA, JA, AC, KN }, 	 //	 802	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, AC, SK, JA, JA, JA, AC, QN }, 	 //	 803	 760
{ QN, QN, QN, AC, JA, PF, SK, SK, AC, WN, JA, JA, JA, AC, TN }, 	 //	 804	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, KN, JA, JA, JA, AC, QN }, 	 //	 805	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, AC, QN, JA, JA, JA, AC, PF }, 	 //	 806	 760
{ QN, QN, QN, AC, PF, PF, SK, SK, AC, JA, JA, JA, JA, AC, TN }, 	 //	 807	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, AC, SK, JA, JA, JA, PF, QN }, 	 //	 808	 760
{ QN, QN, QN, AC, QN, PF, SK, SK, AC, QN, JA, JA, JA, PF, QN }, 	 //	 809	 760
{ QN, QN, QN, AC, PF, PF, SK, SK, AC, JA, JA, JA, JA, PF, TN }, 	 //	 810	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, AC, AC, JA, JA, JA, PF, AC }, 	 //	 811	 760
{ QN, QN, QN, AC, AC, PF, SK, SK, AC, AC, JA, JA, JA, PF, AC }, 	 //	 812	 760
{ QN, QN, QN, AC, JA, PF, SK, SK, PF, JA, JA, JA, JA, KN, WN }, 	 //	 813	 760
{ QN, QN, QN, AC, TN, PF, SK, SK, PF, TN, JA, JA, JA, KN, TN }, 	 //	 814	 760
{ QN, QN, QN, AC, JA, PF, SK, SK, PF, TN, JA, JA, JA, KN, AC }, 	 //	 815	 760
{ QN, QN, QN, AC, KN, PF, SK, SK, PF, KN, JA, JA, JA, KN, CR }, 	 //	 816	 760
{ QN, QN, QN, PF, QN, PF, SK, SK, KN, QN, JA, JA, JA, KN, SH }, 	 //	 817	 760
{ QN, QN, QN, PF, TN, PF, SK, SK, KN, TN, JA, JA, JA, KN, ST }, 	 //	 818	 760
{ QN, QN, QN, PF, AC, PF, SK, SK, KN, SK, JA, JA, JA, KN, KN }, 	 //	 819	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, KN, CR }, 	 //	 820	 760
{ QN, QN, QN, KN, CR, PF, SK, SK, KN, KN, JA, JA, JA, KN, KN }, 	 //	 821	 760
{ QN, QN, QN, KN, WN, PF, SK, SK, KN, TN, JA, JA, JA, KN, TN }, 	 //	 822	 760
{ QN, QN, QN, KN, TN, PF, SK, SK, KN, ST, JA, JA, JA, KN, AC }, 	 //	 823	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, KN, AC }, 	 //	 824	 760
{ QN, QN, QN, KN, LO, PF, SK, SK, KN, AC, JA, JA, JA, SK, AC }, 	 //	 825	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, AC, JA, JA, JA, SK, CR }, 	 //	 826	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, KN, SH, JA, JA, JA, SK, JA }, 	 //	 827	 760
{ QN, QN, QN, KN, WN, PF, SK, SK, KN, TN, JA, JA, JA, SK, TN }, 	 //	 828	 760
{ QN, QN, QN, KN, JA, PF, SK, SK, KN, TN, JA, JA, JA, SK, AC }, 	 //	 829	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, KN, SK, JA, JA, JA, SK, KN }, 	 //	 830	 760
{ QN, QN, QN, KN, SK, PF, SK, SK, KN, KN, JA, JA, JA, SK, KN }, 	 //	 831	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, KN, KN, JA, JA, JA, SK, KN }, 	 //	 832	 760
{ QN, QN, QN, KN, QN, PF, SK, SK, KN, KN, JA, JA, JA, SK, AC }, 	 //	 833	 760
{ QN, QN, QN, SK, AC, PF, SK, SK, QN, AC, JA, JA, JA, KN, AC }, 	 //	 834	 760
{ QN, QN, QN, SK, AC, PF, SK, SK, QN, AC, JA, JA, JA, KN, CR }, 	 //	 835	 760
{ QN, QN, QN, SK, KN, PF, SK, SK, QN, KN, JA, JA, JA, KN, SK }, 	 //	 836	 760
{ QN, QN, QN, SK, QN, PF, SK, SK, QN, SH, JA, JA, JA, KN, JA }, 	 //	 837	 760
{ QN, QN, QN, SK, SH, PF, SK, SK, QN, JA, JA, JA, JA, KN, JA }, 	 //	 838	 760
{ QN, QN, QN, SK, KN, PF, SK, SK, QN, QN, JA, JA, JA, KN, PF }, 	 //	 839	 760
{ QN, QN, QN, SK, JA, PF, SK, SK, QN, TN, JA, JA, JA, KN, AC }, 	 //	 840	 760
{ QN, QN, QN, SK, AC, PF, SK, SK, QN, AC, JA, JA, JA, KN, AC }, 	 //	 841	 760
{ QN, QN, QN, SK, AC, PF, SK, SK, QN, AC, JA, JA, JA, KN, SK }, 	 //	 842	 760
{ QN, QN, QN, KN, AC, PF, SK, SK, AC, LO, JA, JA, JA, PF, AC }, 	 //	 843	 760
{ QN, QN, QN, KN, KN, PF, SK, SK, AC, KN, JA, JA, JA, PF, KN }, 	 //	 844	 760
{ QN, QN, QN, KN, JA, PF, SK, SK, AC, WN, JA, JA, JA, PF, TN }, 	 //	 845	 760
{ QN, QN, QN, KN, JA, PF, SK, SK, AC, TN, JA, JA, JA, PF, AC }, 	 //	 846	 760
{ QN, QN, QN, KN, TN, PF, SK, SK, AC, AC, JA, JA, JA, PF, AC }, 	 //	 847	 760
{ QN, QN, QN, KN, CR, PF, SK, SK, AC, QN, JA, JA, JA, PF, KN }, 	 //	 848	 760
{ QN, SK, QN, SK, SK, PF, JA, SK, QN, QN, JA, JA, JA, KN, QN }, 	 //	 849	 760
{ QN, SH, QN, QN, QN, PF, TN, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 850	 760
{ QN, WN, QN, QN, QN, PF, AC, SK, SK, SH, JA, KN, JA, JA, JA }, 	 //	 851	 760
{ QN, KN, QN, QN, QN, PF, QN, SK, SK, SH, JA, ST, JA, JA, JA }, 	 //	 852	 760
{ QN, QN, QN, KN, AC, PF, ST, SK, KN, AC, JA, JA, JA, SK, SK }, 	 //	 853	 760
{ QN, QN, QN, KN, QN, PF, ST, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 854	 760
{ QN, QN, QN, KN, QN, PF, ST, SK, SK, SH, JA, JA, JA, QN, JA }, 	 //	 855	 760
{ QN, QN, QN, KN, WN, PF, ST, SK, SK, TN, JA, JA, JA, QN, TN }, 	 //	 856	 760
{ QN, QN, QN, KN, TN, PF, ST, SK, SK, TN, JA, JA, JA, QN, ST }, 	 //	 857	 760
{ QN, QN, QN, KN, ST, PF, ST, SK, SK, AC, JA, JA, JA, QN, KN }, 	 //	 858	 760
{ QN, QN, QN, KN, JA, PF, ST, SK, SK, TN, JA, JA, JA, QN, AC }, 	 //	 859	 760
{ QN, QN, QN, KN, AC, PF, ST, SK, SK, AC, JA, JA, JA, QN, AC }, 	 //	 860	 760
{ QN, ST, QN, QN, QN, PF, JA, SK, SK, PF, JA, TN, JA, JA, JA }, 	 //	 861	 760
{ QN, TN, QN, QN, QN, PF, AC, SK, SK, SH, JA, AC, JA, JA, JA }, 	 //	 862	 760
{ QN, AC, QN, QN, QN, PF, AC, SK, SK, SH, JA, PF, JA, JA, JA }, 	 //	 863	 760
{ QN, PF, QN, QN, QN, PF, KN, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 864	 760
{ QN, KN, QN, QN, QN, PF, SK, SK, ST, SH, JA, QN, JA, JA, JA }, 	 //	 865	 760
{ QN, SK, QN, QN, QN, PF, QN, SK, SK, PF, JA, KN, JA, JA, JA }, 	 //	 866	 760
{ PF, AC, QN, QN, QN, JA, AC, SK, SK, PF, TN, AC, JA, JA, JA }, 	 //	 867	 760
{ PF, AC, QN, QN, QN, JA, LO, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 868	 760
{ PF, LO, QN, QN, QN, JA, KN, SK, SK, PF, TN, KN, JA, JA, JA }, 	 //	 869	 760
{ PF, KN, QN, QN, QN, JA, KN, SK, SK, SH, TN, KN, JA, JA, JA }, 	 //	 870	 760
{ PF, QN, QN, QN, KN, JA, SK, SK, ST, QN, TN, JA, JA, JA, PF }, 	 //	 871	 760
{ PF, QN, QN, QN, AC, JA, SK, SK, ST, AC, TN, JA, JA, JA, SK }, 	 //	 872	 760
{ PF, SK, QN, QN, QN, JA, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 873	 760
{ PF, SK, QN, QN, QN, JA, JA, SK, SK, KN, TN, JA, JA, JA, AC }, 	 //	 874	 760
{ PF, JA, QN, QN, QN, JA, JA, SK, SK, QN, TN, JA, JA, JA, SH }, 	 //	 875	 760
{ PF, TN, QN, QN, QN, JA, TN, SK, SK, SH, TN, TN, JA, JA, JA }, 	 //	 876	 760
{ PF, TN, QN, QN, QN, JA, TN, SK, SK, SH, TN, WN, JA, JA, JA }, 	 //	 877	 760
{ PF, TN, QN, QN, QN, JA, TN, SK, SK, PF, TN, WN, JA, JA, JA }, 	 //	 878	 760
{ PF, AC, QN, QN, QN, JA, KN, SK, SK, SH, TN, QN, JA, JA, JA }, 	 //	 879	 760
{ PF, QN, QN, QN, KN, JA, ST, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 880	 760
{ PF, QN, QN, QN, KN, JA, ST, SK, SK, QN, TN, JA, JA, JA, PF }, 	 //	 881	 760
{ PF, QN, QN, QN, KN, JA, ST, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 882	 760
{ PF, QN, QN, QN, KN, JA, ST, SK, SK, KN, TN, JA, JA, JA, CR }, 	 //	 883	 760
{ PF, ST, SK, SK, SH, JA, JA, JA, JA, JA, TN, TN, TN, JA, JA }, 	 //	 884	 760
{ PF, ST, SK, SK, JA, JA, JA, JA, JA, JA, TN, TN, TN, JA, WN }, 	 //	 885	 760
{ PF, JA, QN, QN, QN, JA, TN, SK, SK, SH, TN, AC, JA, JA, JA }, 	 //	 886	 760
{ PF, TN, QN, QN, QN, JA, AC, SK, SK, SH, TN, AC, JA, JA, JA }, 	 //	 887	 760
{ PF, QN, QN, QN, SH, JA, KN, SK, SK, JA, TN, AC, JA, JA, JA }, 	 //	 888	 760
{ JA, AC, QN, QN, QN, TN, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 889	 760
{ JA, AC, QN, QN, QN, TN, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 890	 760
{ JA, LO, QN, QN, QN, TN, KN, SK, SK, PF, AC, KN, JA, JA, JA }, 	 //	 891	 760
{ JA, KN, QN, QN, QN, TN, KN, SK, SK, PF, AC, ST, JA, JA, JA }, 	 //	 892	 760
{ JA, KN, QN, QN, QN, TN, ST, SK, SK, PF, AC, QN, JA, JA, JA }, 	 //	 893	 760
{ JA, QN, QN, QN, JA, TN, QN, SK, SK, JA, AC, SK, JA, JA, JA }, 	 //	 894	 760
{ JA, JA, QN, QN, QN, TN, JA, SK, SK, QN, AC, SH, JA, JA, SH }, 	 //	 895	 760
{ JA, TN, QN, QN, QN, TN, TN, SK, SK, SH, AC, WN, JA, JA, JA }, 	 //	 896	 760
{ JA, AC, QN, QN, QN, TN, KN, SK, SK, PF, AC, QN, JA, JA, JA }, 	 //	 897	 760
{ JA, QN, QN, QN, LO, TN, ST, SK, SK, AC, AC, JA, JA, JA, AC }, 	 //	 898	 760
{ JA, QN, QN, QN, AC, TN, ST, SK, SK, AC, AC, JA, JA, JA, CR }, 	 //	 899	 760
{ JA, QN, QN, QN, KN, TN, ST, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 900	 760
{ JA, QN, QN, QN, TN, TN, ST, SK, SK, TN, AC, JA, JA, JA, TN }, 	 //	 901	 760
{ JA, QN, QN, QN, JA, TN, ST, SK, SK, TN, AC, JA, JA, JA, AC }, 	 //	 902	 760
{ JA, QN, QN, QN, CR, TN, ST, SK, SK, QN, AC, JA, JA, JA, KN }, 	 //	 903	 760
{ JA, JA, QN, QN, QN, TN, TN, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 904	 760
{ JA, PF, QN, QN, QN, TN, KN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 905	 760
{ JA, KN, QN, QN, QN, TN, SK, SK, ST, PF, AC, QN, JA, JA, JA }, 	 //	 906	 760
{ JA, SK, QN, QN, QN, TN, QN, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 907	 760
{ JA, KN, QN, QN, QN, TN, AC, SK, SK, PF, AC, SH, JA, JA, JA }, 	 //	 908	 760
{ TN, SH, QN, QN, QN, AC, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 909	 760
{ TN, KN, QN, QN, QN, AC, KN, SK, SK, PF, AC, ST, JA, JA, JA }, 	 //	 910	 760
{ TN, KN, QN, QN, QN, AC, ST, SK, SK, SH, AC, QN, JA, JA, JA }, 	 //	 911	 760
{ TN, QN, QN, QN, SH, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA }, 	 //	 912	 760
{ TN, QN, QN, QN, SH, AC, QN, SK, SK, JA, AC, SK, JA, JA, JA }, 	 //	 913	 760
{ TN, QN, QN, QN, AC, AC, SK, SK, ST, LO, AC, JA, JA, JA, AC }, 	 //	 914	 760
{ TN, QN, QN, QN, KN, AC, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 915	 760
{ TN, QN, QN, QN, TN, AC, SK, SK, ST, ST, AC, JA, JA, JA, AC }, 	 //	 916	 760
{ TN, QN, QN, QN, AC, AC, SK, SK, ST, KN, AC, JA, JA, JA, QN }, 	 //	 917	 760
{ TN, QN, QN, QN, AC, AC, SK, SK, ST, AC, AC, JA, JA, JA, AC }, 	 //	 918	 760
{ TN, QN, QN, QN, AC, AC, SK, SK, ST, SK, AC, JA, JA, JA, KN }, 	 //	 919	 760
{ TN, SK, QN, QN, QN, AC, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 920	 760
{ TN, JA, QN, QN, QN, AC, JA, SK, SK, QN, AC, JA, JA, JA, SH }, 	 //	 921	 760
{ TN, TN, QN, QN, QN, AC, WN, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 922	 760
{ TN, KN, QN, QN, QN, AC, QN, SK, SK, SH, AC, ST, JA, JA, JA }, 	 //	 923	 760
{ TN, QN, QN, QN, CR, AC, ST, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 924	 760
{ TN, QN, QN, QN, ST, AC, ST, SK, SK, AC, AC, JA, JA, JA, KN }, 	 //	 925	 760
{ TN, QN, QN, QN, KN, AC, ST, SK, SK, AC, AC, JA, JA, JA, LO }, 	 //	 926	 760
{ TN, AC, QN, QN, QN, AC, PF, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 927	 760
{ TN, KN, QN, QN, QN, AC, KN, SK, SK, PF, AC, KN, JA, JA, JA }, 	 //	 928	 760
{ TN, KN, QN, QN, QN, AC, KN, SK, SK, SH, AC, SK, JA, JA, JA }, 	 //	 929	 760
{ TN, QN, QN, QN, JA, AC, KN, SK, SK, JA, AC, AC, JA, JA, JA }, 	 //	 930	 760
{ TN, KN, QN, QN, QN, AC, AC, SK, SK, PF, AC, SH, JA, JA, JA }, 	 //	 931	 760
{ AC, SH, QN, QN, QN, AC, AC, SK, SK, PF, AC, AC, JA, JA, JA }, 	 //	 932	 760
{ AC, AC, QN, QN, QN, AC, AC, SK, SK, SH, AC, LO, JA, JA, JA }, 	 //	 933	 760
{ AC, LO, QN, QN, QN, AC, KN, SK, SK, PF, AC, KN, JA, JA, JA }, 	 //	 934	 760
{ AC, QN, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA }, 	 //	 935	 760
{ AC, QN, QN, QN, SH, AC, QN, SK, SK, JA, AC, SK, JA, JA, JA }, 	 //	 936	 760
{ AC, QN, QN, QN, CR, AC, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 937	 760
{ AC, QN, QN, QN, WN, AC, SK, SK, ST, TN, AC, JA, JA, JA, TN }, 	 //	 938	 760
{ AC, QN, QN, QN, TN, AC, SK, SK, ST, TN, AC, JA, JA, JA, ST }, 	 //	 939	 760
{ AC, QN, QN, QN, PF, AC, SK, SK, ST, JA, AC, JA, JA, JA, TN }, 	 //	 940	 760
{ AC, QN, QN, QN, JA, AC, SK, SK, ST, TN, AC, JA, JA, JA, AC }, 	 //	 941	 760
{ AC, QN, QN, QN, AC, AC, SK, SK, ST, AC, AC, JA, JA, JA, AC }, 	 //	 942	 760
{ AC, QN, QN, QN, SK, AC, SK, SK, ST, KN, AC, JA, JA, JA, KN }, 	 //	 943	 760
{ AC, SK, QN, QN, QN, AC, JA, SK, SK, QN, AC, JA, JA, JA, SH }, 	 //	 944	 760
{ AC, JA, QN, QN, QN, AC, JA, SK, SK, SH, AC, SH, JA, JA, JA }, 	 //	 945	 760
{ AC, JA, QN, QN, QN, AC, SH, SK, SK, SH, AC, TN, JA, JA, JA }, 	 //	 946	 760
{ AC, JA, QN, QN, QN, AC, SH, SK, SK, PF, AC, TN, JA, JA, JA }, 	 //	 947	 760
{ AC, TN, QN, QN, QN, AC, TN, SK, SK, PF, AC, TN, JA, JA, JA }, 	 //	 948	 760
{ AC, WN, QN, QN, QN, AC, AC, SK, SK, SH, AC, KN, JA, JA, JA }, 	 //	 949	 760
{ AC, KN, QN, QN, QN, AC, QN, SK, SK, SH, AC, ST, JA, JA, JA }, 	 //	 950	 760
{ AC, QN, QN, QN, AC, AC, ST, SK, SK, AC, AC, JA, JA, JA, CR }, 	 //	 951	 760
{ AC, QN, QN, QN, KN, AC, ST, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 952	 760
{ AC, QN, QN, QN, AC, AC, ST, SK, SK, AC, AC, JA, JA, JA, AC }, 	 //	 953	 760
{ AC, JA, QN, QN, QN, AC, TN, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 954	 760
{ AC, AC, QN, QN, QN, AC, AC, SK, SK, SH, AC, AC, JA, JA, JA }, 	 //	 955	 760
{ AC, AC, QN, QN, QN, AC, SH, SK, SK, PF, SK, AC, JA, JA, JA }, 	 //	 956	 760
{ AC, AC, QN, QN, QN, AC, LO, SK, SK, SH, SK, KN, JA, JA, JA }, 	 //	 957	 760
{ AC, KN, QN, QN, QN, AC, KN, SK, SK, SH, SK, KN, JA, JA, JA }, 	 //	 958	 760
{ AC, KN, QN, QN, QN, AC, ST, SK, SK, PF, SK, QN, JA, JA, JA }, 	 //	 959	 760
{ AC, JA, QN, QN, QN, AC, JA, SK, SK, QN, SK, JA, JA, JA, SH }, 	 //	 960	 760
{ AC, QN, QN, QN, CR, AC, ST, SK, SK, KN, SK, JA, JA, JA, KN }, 	 //	 961	 760
{ AC, QN, QN, QN, JA, AC, ST, SK, SK, JA, SK, JA, JA, JA, WN }, 	 //	 962	 760
{ AC, QN, QN, QN, TN, AC, ST, SK, SK, ST, SK, JA, JA, JA, AC }, 	 //	 963	 760
{ AC, QN, QN, QN, AC, AC, ST, SK, SK, KN, SK, JA, JA, JA, QN }, 	 //	 964	 760
{ AC, QN, QN, QN, KN, AC, ST, SK, SK, QN, SK, JA, JA, JA, PF }, 	 //	 965	 760
{ AC, ST, QN, QN, QN, AC, JA, SK, SK, PF, SK, TN, JA, JA, JA }, 	 //	 966	 760
{ AC, AC, QN, QN, QN, AC, PF, SK, SK, SH, SK, KN, JA, JA, JA }, 	 //	 967	 760
{ AC, AC, QN, QN, QN, AC, PF, SK, SK, PF, SK, KN, JA, JA, JA }, 	 //	 968	 760
{ AC, LO, QN, QN, QN, SK, KN, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 969	 760
{ AC, KN, QN, QN, QN, SK, ST, SK, SK, SH, KN, QN, JA, JA, JA }, 	 //	 970	 760
{ AC, KN, QN, QN, QN, SK, ST, SK, SK, PF, KN, QN, JA, JA, JA }, 	 //	 971	 760
{ AC, QN, QN, QN, SH, SK, QN, SK, SK, JA, KN, SK, JA, JA, JA }, 	 //	 972	 760
{ AC, SK, QN, QN, QN, SK, JA, SK, SK, KN, KN, JA, JA, JA, AC }, 	 //	 973	 760
{ AC, JA, QN, QN, QN, SK, JA, SK, SK, QN, KN, JA, JA, JA, SH }, 	 //	 974	 760
{ AC, JA, QN, QN, QN, SK, JA, SK, SK, SH, KN, SH, JA, JA, JA }, 	 //	 975	 760
{ AC, TN, QN, QN, QN, SK, TN, SK, SK, SH, KN, TN, JA, JA, JA }, 	 //	 976	 760
{ AC, QN, QN, QN, AC, SK, ST, SK, SK, AC, KN, JA, JA, JA, CR }, 	 //	 977	 760
{ AC, QN, QN, QN, KN, SK, ST, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 978	 760
{ AC, QN, QN, QN, ST, SK, ST, SK, SK, AC, KN, JA, JA, JA, KN }, 	 //	 979	 760
{ AC, TN, QN, QN, QN, SK, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 980	 760
{ AC, AC, QN, QN, QN, SK, AC, SK, SK, SH, KN, PF, JA, JA, JA }, 	 //	 981	 760
{ AC, KN, QN, QN, QN, SK, KN, SK, SK, SH, KN, SK, JA, JA, JA }, 	 //	 982	 760
{ SK, AC, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 983	 760
{ SK, AC, QN, QN, QN, KN, LO, SK, SK, PF, KN, KN, JA, JA, JA }, 	 //	 984	 760
{ SK, LO, QN, QN, QN, KN, KN, SK, SK, SH, KN, KN, JA, JA, JA }, 	 //	 985	 760
{ SK, ST, QN, QN, QN, KN, QN, SK, SK, PF, KN, QN, JA, JA, JA }, 	 //	 986	 760
{ SK, QN, QN, QN, SH, KN, QN, SK, SK, JA, KN, SK, JA, JA, JA }, 	 //	 987	 760
{ SK, JA, QN, QN, QN, KN, JA, SK, SK, SH, KN, SH, JA, JA, JA }, 	 //	 988	 760
{ SK, TN, QN, QN, QN, KN, TN, SK, SK, SH, KN, TN, JA, JA, JA }, 	 //	 989	 760
{ SK, TN, QN, QN, QN, KN, WN, SK, SK, PF, KN, AC, JA, JA, JA }, 	 //	 990	 760
{ SK, QN, QN, QN, AC, KN, ST, SK, SK, LO, KN, JA, JA, JA, AC }, 	 //	 991	 760
{ SK, QN, QN, QN, AC, KN, ST, SK, SK, AC, KN, JA, JA, JA, CR }, 	 //	 992	 760
{ SK, TN, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 993	 760
{ SK, AC, QN, QN, QN, KN, AC, SK, SK, SH, KN, PF, JA, JA, JA }, 	 //	 994	 760
{ SK, AC, QN, QN, QN, KN, AC, SK, SK, PF, KN, PF, JA, JA, JA }, 	 //	 995	 760
{ SK, SK, QN, QN, QN, KN, QN, SK, ST, SH, KN, KN, JA, JA, JA }, 	 //	 996	 760
{ SK, QN, QN, QN, SH, KN, KN, SK, SK, JA, KN, AC, JA, JA, JA }, 	 //	 997	 760
{ SK, KN, QN, QN, QN, KN, AC, SK, SK, SH, KN, SH, JA, JA, JA }, 	 //	 998	 760
{ KN, SH, QN, QN, QN, KN, AC, SK, SK, SH, KN, AC, JA, JA, JA }, 	 //	 999	 760
{ KN, AC, QN, QN, QN, KN, AC, SK, SK, PF, KN, AC, JA, JA, JA }};	 //	 1000	 760
