unsigned char L5_Outcome_0800[1000][15]={	 //	 0	 800
{ AC, AC, JA, JA, JA, LO, LO, JA, JA, JA, AC, KN, JA, SH, JA }, 	 //	 1	 800
{ AC, SK, LO, SK, JA, LO, JA, JA, JA, WN, AC, JA, JA, JA, TN }, 	 //	 2	 800
{ AC, SK, LO, JA, JA, LO, JA, JA, JA, WN, AC, JA, JA, JA, TN }, 	 //	 3	 800
{ AC, SK, LO, JA, JA, LO, JA, JA, JA, JA, AC, JA, JA, SH, WN }, 	 //	 4	 800
{ AC, SK, JA, JA, LO, LO, JA, JA, JA, AC, AC, JA, JA, JA, AC }, 	 //	 5	 800
{ AC, SK, JA, JA, KN, LO, JA, JA, JA, SK, AC, JA, JA, JA, QN }, 	 //	 6	 800
{ AC, SK, JA, JA, QN, LO, JA, JA, JA, KN, AC, JA, JA, JA, AC }, 	 //	 7	 800
{ AC, JA, JA, SK, AC, LO, JA, JA, JA, LO, AC, JA, JA, JA, AC }, 	 //	 8	 800
{ AC, JA, JA, JA, KN, LO, JA, JA, JA, SK, AC, JA, JA, SH, QN }, 	 //	 9	 800
{ AC, JA, JA, JA, QN, LO, JA, JA, JA, QN, AC, JA, JA, SH, QN }, 	 //	 10	 800
{ AC, JA, JA, JA, KN, LO, JA, JA, JA, KN, AC, JA, JA, SH, CR }, 	 //	 11	 800
{ AC, JA, JA, JA, QN, LO, JA, JA, JA, PF, AC, JA, ST, SH, JA }, 	 //	 12	 800
{ AC, JA, JA, JA, AC, LO, JA, JA, JA, SK, AC, SH, JA, JA, KN }, 	 //	 13	 800
{ AC, JA, JA, JA, QN, LO, JA, JA, JA, KN, AC, SH, JA, JA, AC }, 	 //	 14	 800
{ AC, JA, JA, JA, SK, LO, JA, JA, JA, QN, AC, SH, JA, SH, QN }, 	 //	 15	 800
{ AC, JA, JA, JA, TN, LO, JA, JA, JA, TN, AC, SH, JA, SH, TN }, 	 //	 16	 800
{ AC, JA, JA, JA, KN, LO, JA, JA, JA, KN, AC, SH, JA, SH, KN }, 	 //	 17	 800
{ AC, JA, JA, JA, JA, LO, JA, JA, JA, TN, AC, SH, ST, SH, AC }, 	 //	 18	 800
{ AC, TN, JA, SK, JA, LO, WN, JA, JA, JA, AC, AC, JA, JA, JA }, 	 //	 19	 800
{ AC, KN, JA, SK, JA, LO, QN, JA, JA, JA, AC, ST, JA, JA, JA }, 	 //	 20	 800
{ AC, QN, JA, JA, SH, LO, ST, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 21	 800
{ AC, QN, JA, JA, JA, LO, ST, JA, JA, JA, AC, JA, JA, JA, WN }, 	 //	 22	 800
{ LO, SK, JA, SK, CR, AC, JA, JA, JA, KN, AC, JA, JA, JA, KN }, 	 //	 23	 800
{ LO, SK, JA, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, JA, QN }, 	 //	 24	 800
{ LO, SK, JA, SK, AC, AC, JA, JA, JA, SK, AC, JA, JA, JA, KN }, 	 //	 25	 800
{ LO, SK, QN, JA, JA, AC, JA, SK, JA, JA, AC, JA, JA, JA, JA }, 	 //	 26	 800
{ LO, JA, JA, SK, AC, AC, JA, JA, JA, AC, AC, JA, JA, JA, CR }, 	 //	 27	 800
{ LO, JA, LO, JA, JA, AC, JA, JA, JA, JA, AC, SH, JA, SH, WN }, 	 //	 28	 800
{ LO, JA, JA, JA, QN, AC, JA, JA, JA, SH, AC, SH, ST, JA, JA }, 	 //	 29	 800
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, WN, AC, SH, ST, SH, TN }, 	 //	 30	 800
{ LO, SK, JA, JA, JA, AC, QN, JA, JA, JA, AC, KN, JA, SH, JA }, 	 //	 31	 800
{ LO, QN, JA, JA, JA, AC, KN, JA, JA, JA, AC, AC, JA, SH, JA }, 	 //	 32	 800
{ AC, SK, LO, JA, QN, AC, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 33	 800
{ AC, SK, JA, ST, QN, AC, JA, JA, JA, PF, AC, JA, JA, TN, JA }, 	 //	 34	 800
{ AC, SK, JA, ST, JA, AC, JA, JA, JA, TN, AC, JA, JA, TN, AC }, 	 //	 35	 800
{ AC, JA, JA, SK, AC, AC, JA, JA, JA, AC, AC, JA, JA, JA, AC }, 	 //	 36	 800
{ AC, JA, JA, SK, KN, AC, JA, JA, JA, KN, AC, JA, JA, JA, SK }, 	 //	 37	 800
{ AC, JA, JA, JA, KN, AC, JA, JA, JA, SK, AC, JA, JA, SH, QN }, 	 //	 38	 800
{ AC, JA, JA, JA, ST, AC, JA, JA, JA, AC, AC, SH, JA, SH, KN }, 	 //	 39	 800
{ AC, JA, JA, ST, JA, AC, JA, JA, JA, TN, AC, SH, JA, TN, AC }, 	 //	 40	 800
{ AC, JA, JA, JA, PF, AC, JA, JA, JA, JA, AC, SH, ST, JA, TN }, 	 //	 41	 800
{ AC, ST, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, ST, JA, WN }, 	 //	 42	 800
{ AC, KN, JA, SK, JA, AC, KN, JA, JA, JA, AC, KN, JA, JA, JA }, 	 //	 43	 800
{ AC, KN, JA, JA, JA, AC, KN, JA, JA, JA, AC, SK, JA, SH, JA }, 	 //	 44	 800
{ AC, QN, JA, JA, SH, AC, SK, JA, JA, JA, ST, JA, JA, JA, JA }, 	 //	 45	 800
{ AC, QN, QN, QN, AC, AC, SK, QN, QN, AC, ST, JA, SK, SK, SK }, 	 //	 46	 800
{ AC, QN, QN, QN, AC, AC, SK, QN, SK, AC, ST, JA, SK, JA, SK }, 	 //	 47	 800
{ AC, SK, JA, SK, AC, AC, JA, JA, JA, LO, ST, JA, JA, JA, AC }, 	 //	 48	 800
{ AC, SK, JA, SK, KN, AC, JA, JA, JA, KN, ST, JA, JA, JA, KN }, 	 //	 49	 800
{ AC, SK, JA, SK, KN, AC, JA, JA, JA, KN, ST, JA, JA, JA, CR }, 	 //	 50	 800
{ AC, SK, JA, JA, KN, AC, JA, JA, JA, KN, ST, JA, JA, JA, SK }, 	 //	 51	 800
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, KN, ST, JA, JA, JA, AC }, 	 //	 52	 800
{ AC, SK, JA, ST, QN, AC, JA, JA, JA, SH, ST, JA, JA, TN, JA }, 	 //	 53	 800
{ AC, SK, JA, JA, SH, AC, JA, JA, JA, JA, ST, JA, ST, SH, JA }, 	 //	 54	 800
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, ST, JA, ST, JA, TN }, 	 //	 55	 800
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, ST, JA, ST, SH, TN }, 	 //	 56	 800
{ AC, JA, JA, JA, PF, AC, JA, JA, JA, JA, ST, JA, ST, SH, TN }, 	 //	 57	 800
{ AC, JA, LO, ST, JA, AC, JA, JA, JA, JA, ST, SH, JA, TN, JA }, 	 //	 58	 800
{ AC, JA, JA, JA, AC, AC, JA, JA, JA, AC, ST, SH, JA, JA, AC }, 	 //	 59	 800
{ AC, JA, JA, JA, KN, AC, JA, JA, JA, KN, ST, SH, JA, SH, KN }, 	 //	 60	 800
{ AC, JA, JA, JA, CR, AC, JA, JA, JA, QN, ST, SH, JA, SH, KN }, 	 //	 61	 800
{ AC, JA, JA, SK, SH, AC, JA, JA, JA, JA, ST, SH, ST, JA, JA }, 	 //	 62	 800
{ AC, AC, JA, SK, JA, AC, KN, JA, JA, JA, ST, QN, JA, JA, JA }, 	 //	 63	 800
{ AC, ST, JA, JA, SH, AC, JA, JA, JA, JA, ST, TN, ST, JA, JA }, 	 //	 64	 800
{ AC, TN, JA, JA, JA, AC, AC, JA, JA, JA, ST, AC, JA, SH, JA }, 	 //	 65	 800
{ AC, QN, JA, SK, JA, AC, KN, JA, JA, JA, ST, AC, JA, JA, JA }, 	 //	 66	 800
{ AC, SK, JA, SK, QN, ST, JA, JA, JA, QN, KN, JA, JA, JA, QN }, 	 //	 67	 800
{ AC, SK, JA, SK, KN, ST, JA, JA, JA, KN, KN, JA, JA, JA, CR }, 	 //	 68	 800
{ AC, SK, JA, SK, KN, ST, JA, JA, JA, AC, KN, JA, JA, JA, LO }, 	 //	 69	 800
{ AC, SK, JA, JA, KN, ST, JA, JA, JA, KN, KN, JA, JA, JA, KN }, 	 //	 70	 800
{ AC, SK, JA, JA, QN, ST, JA, JA, JA, QN, KN, JA, JA, JA, SH }, 	 //	 71	 800
{ AC, SK, JA, JA, AC, ST, JA, JA, JA, AC, KN, JA, JA, JA, AC }, 	 //	 72	 800
{ AC, JA, JA, SK, AC, ST, JA, JA, JA, KN, KN, JA, JA, JA, QN }, 	 //	 73	 800
{ AC, JA, JA, JA, KN, ST, JA, JA, JA, KN, KN, JA, JA, SH, KN }, 	 //	 74	 800
{ AC, JA, QN, JA, JA, ST, JA, SK, JA, JA, KN, JA, JA, JA, JA }, 	 //	 75	 800
{ AC, JA, JA, JA, TN, ST, JA, JA, JA, ST, KN, SH, JA, JA, AC }, 	 //	 76	 800
{ AC, JA, JA, JA, AC, ST, JA, JA, JA, AC, KN, SH, JA, JA, SK }, 	 //	 77	 800
{ AC, JA, JA, JA, KN, ST, JA, JA, JA, KN, KN, SH, JA, JA, KN }, 	 //	 78	 800
{ AC, JA, JA, JA, CR, ST, JA, JA, JA, KN, KN, SH, JA, SH, KN }, 	 //	 79	 800
{ AC, JA, JA, ST, JA, ST, JA, JA, JA, WN, KN, SH, JA, TN, TN }, 	 //	 80	 800
{ AC, TN, TN, TN, TN, ST, TN, TN, TN, TN, KN, WN, TN, WN, TN }, 	 //	 81	 800
{ AC, ST, JA, SK, JA, ST, JA, JA, JA, JA, KN, TN, ST, JA, JA }, 	 //	 82	 800
{ AC, ST, JA, ST, SH, ST, JA, JA, JA, JA, KN, TN, ST, TN, JA }, 	 //	 83	 800
{ AC, AC, JA, SK, JA, ST, AC, JA, JA, JA, KN, PF, JA, JA, JA }, 	 //	 84	 800
{ ST, SK, TN, SK, JA, KN, JA, LO, JA, JA, KN, JA, JA, JA, JA }, 	 //	 85	 800
{ ST, SK, JA, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, JA, QN }, 	 //	 86	 800
{ ST, SK, JA, SK, KN, KN, JA, JA, JA, KN, KN, JA, JA, JA, CR }, 	 //	 87	 800
{ ST, SK, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, ST, SH, WN }, 	 //	 88	 800
{ ST, JA, JA, SK, ST, KN, JA, JA, JA, AC, KN, JA, JA, JA, KN }, 	 //	 89	 800
{ ST, JA, LO, SK, SH, KN, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 90	 800
{ ST, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN, SH, JA, JA, AC }, 	 //	 91	 800
{ ST, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN, SH, JA, SH, CR }, 	 //	 92	 800
{ ST, JA, JA, JA, TN, KN, JA, JA, JA, TN, KN, SH, JA, SH, TN }, 	 //	 93	 800
{ ST, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN, SH, JA, SH, AC }, 	 //	 94	 800
{ ST, JA, JA, JA, SK, KN, JA, JA, JA, KN, KN, SH, JA, SH, KN }, 	 //	 95	 800
{ ST, TN, TN, SH, TN, KN, TN, TN, TN, TN, KN, TN, TN, TN, TN }, 	 //	 96	 800
{ ST, TN, JA, SK, JA, KN, TN, JA, JA, JA, KN, WN, JA, JA, JA }, 	 //	 97	 800
{ ST, KN, JA, JA, JA, KN, SK, JA, JA, JA, KN, QN, JA, SH, JA }, 	 //	 98	 800
{ KN, SH, JA, SK, JA, KN, AC, JA, JA, JA, KN, AC, JA, JA, JA }, 	 //	 99	 800
{ KN, QN, JA, JA, JA, KN, QN, JA, JA, JA, KN, SK, JA, SH, JA }, 	 //	 100	 800
{ KN, SK, JA, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, JA, QN }, 	 //	 101	 800
{ KN, SK, JA, SK, QN, KN, JA, JA, JA, KN, KN, JA, JA, JA, AC }, 	 //	 102	 800
{ KN, SK, JA, JA, KN, KN, JA, JA, JA, AC, KN, JA, JA, JA, LO }, 	 //	 103	 800
{ KN, SK, JA, ST, JA, KN, JA, JA, JA, WN, KN, JA, JA, TN, TN }, 	 //	 104	 800
{ KN, JA, LO, ST, JA, KN, JA, JA, JA, JA, KN, JA, JA, TN, WN }, 	 //	 105	 800
{ KN, JA, JA, SK, TN, KN, JA, JA, JA, TN, KN, JA, JA, JA, TN }, 	 //	 106	 800
{ KN, JA, JA, SK, AC, KN, JA, JA, JA, AC, KN, JA, JA, JA, SK }, 	 //	 107	 800
{ KN, JA, JA, JA, LO, KN, JA, JA, JA, AC, KN, JA, JA, SH, AC }, 	 //	 108	 800
{ KN, JA, JA, JA, CR, KN, JA, JA, JA, KN, KN, JA, JA, SH, KN }, 	 //	 109	 800
{ KN, JA, JA, JA, WN, KN, JA, JA, JA, TN, KN, JA, JA, SH, TN }, 	 //	 110	 800
{ KN, JA, JA, JA, SK, KN, JA, JA, JA, KN, KN, SH, JA, JA, KN }, 	 //	 111	 800
{ KN, JA, JA, JA, LO, KN, JA, JA, JA, AC, KN, SH, JA, SH, AC }, 	 //	 112	 800
{ KN, JA, JA, JA, SK, KN, JA, JA, JA, QN, KN, SH, JA, SH, QN }, 	 //	 113	 800
{ KN, JA, JA, JA, WN, KN, JA, JA, JA, TN, KN, SH, JA, SH, TN }, 	 //	 114	 800
{ KN, TN, JA, SK, JA, KN, TN, JA, JA, JA, KN, WN, JA, JA, JA }, 	 //	 115	 800
{ KN, ST, LO, SK, SH, KN, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 116	 800
{ KN, ST, LO, JA, JA, KN, JA, JA, JA, JA, KN, TN, JA, JA, WN }, 	 //	 117	 800
{ KN, ST, JA, SK, JA, KN, JA, JA, JA, WN, KN, TN, JA, JA, TN }, 	 //	 118	 800
{ KN, ST, JA, JA, QN, KN, JA, JA, JA, SH, KN, TN, JA, SH, JA }, 	 //	 119	 800
{ KN, ST, JA, ST, JA, KN, JA, JA, JA, WN, KN, TN, JA, TN, TN }, 	 //	 120	 800
{ KN, ST, JA, JA, SH, KN, JA, JA, JA, JA, KN, TN, ST, SH, JA }, 	 //	 121	 800
{ KN, SH, JA, JA, JA, KN, AC, JA, JA, JA, SK, AC, JA, SH, JA }, 	 //	 122	 800
{ KN, AC, JA, SK, JA, KN, AC, JA, JA, JA, SK, AC, JA, JA, JA }, 	 //	 123	 800
{ KN, QN, QN, QN, KN, KN, SK, QN, SK, KN, SK, JA, SK, JA, KN }, 	 //	 124	 800
{ KN, QN, QN, QN, KN, KN, SK, QN, SK, KN, SK, JA, SK, JA, CR }, 	 //	 125	 800
{ KN, SK, LO, JA, JA, KN, JA, JA, JA, JA, SK, JA, JA, SH, JA }, 	 //	 126	 800
{ KN, SK, JA, JA, CR, KN, JA, JA, JA, QN, SK, JA, JA, JA, KN }, 	 //	 127	 800
{ KN, SK, JA, JA, JA, KN, JA, JA, JA, JA, SK, JA, ST, JA, WN }, 	 //	 128	 800
{ KN, JA, JA, SK, QN, KN, JA, JA, JA, QN, SK, JA, JA, JA, QN }, 	 //	 129	 800
{ KN, JA, JA, SK, KN, KN, JA, JA, JA, AC, SK, JA, JA, JA, LO }, 	 //	 130	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, SK, SK, JA, JA, SH, QN }, 	 //	 131	 800
{ KN, JA, JA, JA, TN, KN, JA, JA, JA, AC, SK, JA, JA, SH, AC }, 	 //	 132	 800
{ KN, JA, JA, JA, SK, KN, JA, JA, JA, KN, SK, JA, JA, SH, KN }, 	 //	 133	 800
{ KN, JA, JA, SK, SH, KN, JA, JA, JA, JA, SK, JA, ST, JA, JA }, 	 //	 134	 800
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, PF, SK, JA, ST, JA, JA }, 	 //	 135	 800
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, PF, SK, JA, ST, SH, JA }, 	 //	 136	 800
{ KN, JA, QN, SK, JA, KN, JA, SK, JA, JA, SK, JA, JA, JA, JA }, 	 //	 137	 800
{ KN, JA, JA, JA, JA, KN, JA, TN, JA, JA, SK, JA, AC, SH, JA }, 	 //	 138	 800
{ KN, JA, JA, SK, JA, KN, JA, JA, JA, WN, SK, SH, JA, JA, TN }, 	 //	 139	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, KN, SK, SH, JA, SH, CR }, 	 //	 140	 800
{ KN, ST, JA, SK, JA, KN, JA, JA, JA, WN, SK, TN, JA, JA, TN }, 	 //	 141	 800
{ KN, ST, JA, JA, QN, KN, JA, JA, JA, PF, SK, TN, JA, SH, JA }, 	 //	 142	 800
{ KN, ST, JA, ST, JA, KN, JA, JA, JA, JA, SK, TN, ST, TN, JA }, 	 //	 143	 800
{ KN, JA, JA, JA, SH, KN, TN, JA, JA, JA, SK, AC, JA, JA, JA }, 	 //	 144	 800
{ KN, AC, JA, JA, JA, KN, AC, JA, JA, JA, SK, AC, JA, SH, JA }, 	 //	 145	 800
{ KN, AC, JA, JA, JA, KN, PF, JA, JA, JA, SK, KN, JA, SH, JA }, 	 //	 146	 800
{ KN, KN, QN, QN, QN, KN, SK, SK, SK, QN, SK, QN, JA, JA, QN }, 	 //	 147	 800
{ KN, KN, JA, SK, JA, KN, AC, JA, JA, JA, SK, SH, JA, JA, JA }, 	 //	 148	 800
{ KN, QN, QN, QN, AC, SK, SK, QN, SK, KN, QN, JA, SK, JA, QN }, 	 //	 149	 800
{ KN, SK, JA, SK, LO, SK, JA, JA, JA, AC, QN, JA, JA, JA, AC }, 	 //	 150	 800
{ KN, SK, JA, SK, TN, SK, JA, JA, JA, TN, QN, JA, JA, JA, TN }, 	 //	 151	 800
{ KN, SK, JA, SK, KN, SK, JA, JA, JA, KN, QN, JA, JA, JA, KN }, 	 //	 152	 800
{ KN, SK, JA, JA, AC, SK, JA, JA, JA, AC, QN, JA, JA, JA, CR }, 	 //	 153	 800
{ KN, SK, JA, JA, SK, SK, JA, JA, JA, QN, QN, JA, JA, JA, QN }, 	 //	 154	 800
{ KN, SK, JA, JA, QN, SK, JA, JA, JA, QN, QN, JA, JA, JA, SH }, 	 //	 155	 800
{ KN, SK, JA, JA, CR, SK, JA, JA, JA, QN, QN, JA, JA, JA, KN }, 	 //	 156	 800
{ KN, JA, LO, SK, QN, SK, JA, JA, JA, SH, QN, JA, JA, JA, JA }, 	 //	 157	 800
{ KN, JA, LO, SK, QN, SK, JA, JA, JA, PF, QN, JA, JA, JA, JA }, 	 //	 158	 800
{ KN, JA, JA, SK, KN, SK, JA, JA, JA, SK, QN, JA, JA, JA, QN }, 	 //	 159	 800
{ KN, JA, JA, SK, AC, SK, JA, JA, JA, KN, QN, JA, JA, JA, QN }, 	 //	 160	 800
{ KN, JA, JA, JA, AC, SK, JA, JA, JA, KN, QN, JA, JA, SH, QN }, 	 //	 161	 800
{ KN, JA, JA, JA, AC, SK, JA, JA, JA, AC, QN, JA, JA, SH, SK }, 	 //	 162	 800
{ KN, JA, JA, JA, QN, SK, JA, JA, JA, KN, QN, JA, JA, SH, AC }, 	 //	 163	 800
{ KN, JA, JA, ST, QN, SK, JA, JA, JA, SH, QN, JA, JA, TN, JA }, 	 //	 164	 800
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA, ST, JA, AC }, 	 //	 165	 800
{ KN, JA, JA, ST, JA, SK, JA, JA, JA, JA, QN, JA, ST, TN, JA }, 	 //	 166	 800
{ KN, JA, JA, JA, KN, SK, JA, JA, JA, KN, QN, SH, JA, JA, KN }, 	 //	 167	 800
{ KN, JA, JA, JA, TN, SK, JA, JA, JA, TN, QN, SH, JA, JA, TN }, 	 //	 168	 800
{ KN, JA, JA, JA, KN, SK, JA, JA, JA, SK, QN, SH, JA, SH, QN }, 	 //	 169	 800
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, WN, QN, SH, ST, SH, TN }, 	 //	 170	 800
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, SH, ST, SH, AC }, 	 //	 171	 800
{ KN, JA, JA, JA, JA, SK, SH, JA, JA, JA, QN, TN, JA, JA, WN }, 	 //	 172	 800
{ KN, TN, JA, SK, JA, SK, WN, JA, JA, JA, QN, AC, JA, JA, JA }, 	 //	 173	 800
{ KN, QN, LO, SK, JA, SK, ST, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 174	 800
{ KN, ST, LO, JA, JA, SK, JA, JA, JA, JA, QN, TN, JA, SH, WN }, 	 //	 175	 800
{ KN, KN, JA, SK, JA, SK, KN, JA, JA, JA, QN, KN, JA, JA, JA }, 	 //	 176	 800
{ KN, KN, JA, SK, JA, SK, KN, JA, JA, JA, QN, SK, JA, JA, JA }, 	 //	 177	 800
{ SK, QN, QN, QN, AC, QN, SK, QN, QN, AC, QN, JA, SK, SK, AC }, 	 //	 178	 800
{ SK, JA, JA, SK, AC, QN, JA, JA, JA, AC, QN, JA, JA, JA, SK }, 	 //	 179	 800
{ SK, JA, JA, JA, AC, QN, JA, JA, JA, AC, QN, JA, JA, SH, CR }, 	 //	 180	 800
{ SK, JA, JA, JA, KN, QN, JA, JA, JA, KN, QN, JA, JA, SH, KN }, 	 //	 181	 800
{ SK, JA, LO, SK, JA, QN, JA, JA, JA, JA, QN, SH, JA, JA, WN }, 	 //	 182	 800
{ SK, JA, JA, SK, JA, QN, JA, JA, JA, WN, QN, SH, JA, JA, TN }, 	 //	 183	 800
{ SK, JA, JA, JA, AC, QN, JA, JA, JA, LO, QN, SH, JA, JA, AC }, 	 //	 184	 800
{ SK, JA, JA, JA, LO, QN, JA, JA, JA, AC, QN, SH, JA, JA, AC }, 	 //	 185	 800
{ SK, JA, JA, JA, QN, QN, JA, JA, JA, QN, QN, SH, JA, SH, QN }, 	 //	 186	 800
{ SK, JA, JA, JA, KN, QN, JA, JA, JA, KN, QN, SH, JA, SH, CR }, 	 //	 187	 800
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, WN, QN, SH, ST, JA, TN }, 	 //	 188	 800
{ SK, JA, JA, JA, QN, QN, JA, JA, JA, PF, QN, SH, ST, JA, JA }, 	 //	 189	 800
{ SK, JA, JA, JA, JA, QN, JA, ST, JA, JA, QN, SH, AC, SH, JA }, 	 //	 190	 800
{ SK, ST, JA, ST, SH, QN, JA, JA, JA, JA, QN, TN, ST, TN, JA }, 	 //	 191	 800
{ QN, AC, JA, JA, JA, QN, SH, JA, JA, JA, QN, AC, JA, SH, JA }, 	 //	 192	 800
{ QN, SK, JA, SK, QN, QN, JA, JA, JA, QN, QN, JA, JA, JA, SH }, 	 //	 193	 800
{ QN, SK, JA, SK, TN, QN, JA, JA, JA, TN, QN, JA, JA, JA, TN }, 	 //	 194	 800
{ QN, SK, JA, ST, QN, QN, JA, JA, JA, SH, QN, JA, JA, TN, JA }, 	 //	 195	 800
{ QN, SK, JA, ST, QN, QN, JA, JA, JA, PF, QN, JA, JA, TN, JA }, 	 //	 196	 800
{ QN, SK, JA, ST, JA, QN, JA, JA, JA, JA, QN, JA, ST, TN, JA }, 	 //	 197	 800
{ QN, JA, LO, SK, JA, QN, JA, JA, JA, WN, QN, JA, JA, JA, TN }, 	 //	 198	 800
{ QN, JA, JA, JA, CR, QN, JA, JA, JA, KN, QN, JA, JA, SH, KN }, 	 //	 199	 800
{ QN, JA, LO, JA, JA, QN, JA, JA, JA, JA, QN, SH, JA, JA, WN }, 	 //	 200	 800
{ QN, JA, JA, SK, PF, QN, JA, JA, JA, JA, QN, SH, JA, JA, TN }, 	 //	 201	 800
{ QN, JA, JA, JA, AC, QN, JA, JA, JA, AC, QN, SH, JA, JA, CR }, 	 //	 202	 800
{ QN, JA, JA, JA, ST, QN, JA, JA, JA, AC, QN, SH, JA, SH, KN }, 	 //	 203	 800
{ QN, JA, JA, ST, QN, QN, JA, JA, JA, PF, QN, SH, JA, TN, JA }, 	 //	 204	 800
{ QN, JA, JA, SK, JA, QN, SH, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 205	 800
{ QN, JA, JA, JA, SH, QN, SH, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 206	 800
{ QN, SH, JA, JA, JA, QN, TN, JA, JA, JA, QN, TN, JA, SH, JA }, 	 //	 207	 800
{ QN, TN, TN, TN, WN, QN, TN, TN, TN, TN, QN, TN, TN, TN, TN }, 	 //	 208	 800
{ QN, AC, JA, JA, JA, QN, KN, JA, JA, JA, QN, QN, JA, SH, JA }, 	 //	 209	 800
{ QN, JA, JA, JA, SH, QN, TN, JA, JA, JA, QN, AC, JA, JA, JA }, 	 //	 210	 800
{ QN, SH, JA, SK, JA, QN, AC, JA, JA, JA, SH, AC, JA, JA, JA }, 	 //	 211	 800
{ QN, KN, JA, JA, JA, QN, KN, JA, JA, JA, SH, ST, JA, SH, JA }, 	 //	 212	 800
{ QN, QN, QN, KN, AC, QN, SK, QN, SK, SK, SH, JA, SK, QN, KN }, 	 //	 213	 800
{ QN, SK, JA, SK, KN, QN, JA, JA, JA, KN, SH, JA, JA, JA, KN }, 	 //	 214	 800
{ QN, SK, JA, SK, KN, QN, JA, JA, JA, AC, SH, JA, JA, JA, LO }, 	 //	 215	 800
{ QN, SK, JA, JA, ST, QN, JA, JA, JA, AC, SH, JA, JA, JA, KN }, 	 //	 216	 800
{ QN, SK, JA, JA, TN, QN, JA, JA, JA, AC, SH, JA, JA, JA, AC }, 	 //	 217	 800
{ QN, SK, JA, SK, SH, QN, JA, JA, JA, JA, SH, JA, ST, JA, JA }, 	 //	 218	 800
{ QN, JA, LO, SK, JA, QN, JA, JA, JA, WN, SH, JA, JA, JA, TN }, 	 //	 219	 800
{ QN, JA, LO, JA, QN, QN, JA, JA, JA, PF, SH, JA, JA, JA, JA }, 	 //	 220	 800
{ QN, JA, JA, SK, KN, QN, JA, JA, JA, KN, SH, JA, JA, JA, KN }, 	 //	 221	 800
{ QN, JA, JA, SK, TN, QN, JA, JA, JA, TN, SH, JA, JA, JA, ST }, 	 //	 222	 800
{ QN, JA, JA, JA, KN, QN, JA, JA, JA, SK, SH, JA, JA, SH, QN }, 	 //	 223	 800
{ QN, JA, QN, SK, JA, QN, JA, SK, JA, JA, SH, JA, JA, JA, JA }, 	 //	 224	 800
{ QN, JA, LO, JA, JA, QN, JA, JA, JA, JA, SH, SH, JA, SH, WN }, 	 //	 225	 800
{ QN, JA, JA, JA, CR, QN, JA, JA, JA, QN, SH, SH, JA, JA, KN }, 	 //	 226	 800
{ QN, JA, JA, JA, KN, QN, JA, JA, JA, KN, SH, SH, JA, SH, KN }, 	 //	 227	 800
{ QN, JA, JA, JA, TN, QN, JA, JA, JA, TN, SH, SH, JA, SH, ST }, 	 //	 228	 800
{ QN, JA, JA, JA, QN, QN, JA, JA, JA, PF, SH, SH, ST, JA, JA }, 	 //	 229	 800
{ QN, ST, LO, JA, JA, QN, JA, JA, JA, JA, SH, TN, JA, SH, JA }, 	 //	 230	 800
{ QN, JA, JA, JA, JA, QN, TN, JA, JA, JA, SH, AC, ST, JA, JA }, 	 //	 231	 800
{ QN, AC, JA, JA, JA, QN, PF, JA, JA, JA, SH, KN, JA, SH, JA }, 	 //	 232	 800
{ QN, SK, JA, JA, JA, QN, QN, JA, JA, JA, SH, KN, JA, SH, JA }, 	 //	 233	 800
{ QN, AC, JA, JA, JA, SH, AC, JA, JA, JA, JA, AC, JA, SH, JA }, 	 //	 234	 800
{ QN, QN, JA, ST, JA, SH, SK, JA, JA, JA, JA, JA, JA, TN, JA }, 	 //	 235	 800
{ QN, SK, TN, JA, JA, SH, JA, LO, JA, WN, JA, JA, JA, JA, TN }, 	 //	 236	 800
{ QN, SK, LO, SK, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 237	 800
{ QN, SK, LO, JA, QN, SH, JA, JA, JA, QN, JA, JA, JA, JA, SH }, 	 //	 238	 800
{ QN, SK, LO, ST, PF, SH, JA, JA, JA, JA, JA, JA, JA, TN, TN }, 	 //	 239	 800
{ QN, SK, JA, SK, QN, SH, JA, JA, JA, PF, JA, JA, ST, JA, JA }, 	 //	 240	 800
{ QN, SK, JA, JA, JA, SH, JA, JA, JA, TN, JA, JA, ST, JA, AC }, 	 //	 241	 800
{ QN, JA, TN, SK, JA, SH, JA, LO, JA, TN, JA, JA, JA, JA, AC }, 	 //	 242	 800
{ QN, JA, LO, SK, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 243	 800
{ QN, JA, LO, SK, QN, SH, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 244	 800
{ QN, JA, LO, JA, AC, SH, JA, JA, JA, AC, JA, JA, JA, JA, SK }, 	 //	 245	 800
{ QN, JA, LO, JA, SK, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 246	 800
{ QN, JA, LO, JA, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, CR }, 	 //	 247	 800
{ QN, JA, JA, QN, SH, SH, JA, JA, SK, JA, JA, JA, JA, JA, JA }, 	 //	 248	 800
{ QN, JA, JA, QN, QN, SH, JA, JA, ST, PF, JA, JA, JA, JA, JA }, 	 //	 249	 800
{ QN, JA, JA, JA, LO, SH, JA, JA, JA, AC, JA, JA, ST, JA, AC }, 	 //	 250	 800
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, KN, JA, JA, ST, JA, SK }, 	 //	 251	 800
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, KN, JA, JA, ST, SH, CR }, 	 //	 252	 800
{ QN, JA, JA, JA, QN, SH, JA, ST, JA, PF, JA, JA, AC, JA, JA }, 	 //	 253	 800
{ QN, JA, JA, JA, JA, SH, JA, TN, JA, WN, JA, JA, AC, SH, TN }, 	 //	 254	 800
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, KN, JA, SH, ST, JA, KN }, 	 //	 255	 800
{ QN, JA, JA, JA, CR, SH, JA, JA, JA, QN, JA, SH, ST, SH, KN }, 	 //	 256	 800
{ QN, JA, JA, JA, JA, SH, SH, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 257	 800
{ QN, QN, JA, JA, JA, SH, ST, JA, JA, WN, JA, JA, JA, JA, TN }, 	 //	 258	 800
{ QN, ST, JA, SK, KN, SH, JA, JA, JA, SK, JA, TN, JA, JA, QN }, 	 //	 259	 800
{ QN, ST, JA, JA, KN, SH, JA, JA, JA, KN, JA, TN, JA, JA, CR }, 	 //	 260	 800
{ QN, ST, JA, ST, AC, SH, JA, JA, JA, KN, JA, TN, JA, TN, QN }, 	 //	 261	 800
{ QN, ST, JA, JA, JA, SH, JA, ST, JA, JA, JA, TN, AC, JA, JA }, 	 //	 262	 800
{ QN, KN, JA, SK, JA, SH, SK, JA, JA, JA, JA, QN, JA, JA, JA }, 	 //	 263	 800
{ SH, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, LO, JA, SH, JA }, 	 //	 264	 800
{ SH, QN, JA, SK, JA, JA, QN, JA, JA, JA, JA, SK, JA, JA, JA }, 	 //	 265	 800
{ SH, QN, QN, QN, SK, JA, QN, QN, SK, QN, JA, SK, SK, JA, QN }, 	 //	 266	 800
{ SH, QN, JA, ST, JA, JA, SK, JA, JA, JA, JA, JA, JA, TN, JA }, 	 //	 267	 800
{ SH, SK, LO, JA, TN, JA, JA, JA, JA, ST, JA, JA, JA, SH, AC }, 	 //	 268	 800
{ SH, SK, LO, ST, KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN }, 	 //	 269	 800
{ SH, SK, LO, ST, TN, JA, JA, JA, JA, ST, JA, JA, JA, TN, AC }, 	 //	 270	 800
{ SH, SK, JA, QN, AC, JA, JA, JA, SK, AC, JA, JA, JA, JA, AC }, 	 //	 271	 800
{ SH, SK, JA, QN, QN, JA, JA, JA, ST, QN, JA, JA, JA, JA, SH }, 	 //	 272	 800
{ SH, SK, JA, SK, QN, JA, JA, JA, JA, QN, JA, JA, ST, JA, QN }, 	 //	 273	 800
{ SH, SK, JA, JA, AC, JA, JA, JA, JA, AC, JA, JA, ST, JA, CR }, 	 //	 274	 800
{ SH, SK, JA, JA, WN, JA, JA, JA, JA, TN, JA, JA, ST, SH, TN }, 	 //	 275	 800
{ SH, SK, JA, JA, KN, JA, JA, JA, JA, KN, JA, JA, ST, SH, CR }, 	 //	 276	 800
{ SH, SK, JA, ST, AC, JA, JA, JA, JA, AC, JA, JA, ST, TN, CR }, 	 //	 277	 800
{ SH, JA, LO, JA, AC, JA, JA, JA, JA, AC, JA, JA, JA, SH, AC }, 	 //	 278	 800
{ SH, JA, LO, ST, KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN }, 	 //	 279	 800
{ SH, JA, JA, JA, AC, JA, JA, JA, SH, KN, JA, JA, JA, TN, QN }, 	 //	 280	 800
{ SH, JA, JA, QN, AC, JA, JA, JA, ST, AC, JA, JA, JA, JA, SK }, 	 //	 281	 800
{ SH, JA, JA, JA, ST, JA, JA, JA, TN, AC, JA, JA, JA, AC, KN }, 	 //	 282	 800
{ SH, JA, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, JA, AC, AC }, 	 //	 283	 800
{ SH, JA, JA, ST, AC, JA, JA, JA, JA, KN, JA, JA, ST, TN, QN }, 	 //	 284	 800
{ SH, JA, JA, JA, JA, JA, JA, TN, JA, TN, JA, JA, AC, SH, AC }, 	 //	 285	 800
{ SH, JA, LO, SK, JA, JA, JA, JA, JA, TN, JA, SH, JA, JA, AC }, 	 //	 286	 800
{ SH, JA, JA, JA, JA, JA, JA, JA, TN, JA, JA, SH, JA, AC, JA }, 	 //	 287	 800
{ SH, JA, JA, SK, TN, JA, JA, JA, JA, TN, JA, SH, ST, JA, TN }, 	 //	 288	 800
{ SH, JA, JA, ST, TN, JA, JA, JA, JA, TN, JA, SH, ST, TN, TN }, 	 //	 289	 800
{ SH, JA, JA, JA, JA, JA, JA, JA, TN, JA, JA, SH, ST, AC, WN }, 	 //	 290	 800
{ SH, JA, JA, JA, JA, JA, JA, JA, TN, WN, JA, SH, ST, AC, TN }, 	 //	 291	 800
{ SH, JA, JA, JA, JA, JA, JA, JA, TN, TN, JA, SH, ST, AC, AC }, 	 //	 292	 800
{ SH, JA, JA, JA, SH, JA, JA, TN, JA, JA, JA, SH, AC, SH, JA }, 	 //	 293	 800
{ SH, JA, JA, JA, JA, JA, JA, TN, JA, WN, JA, SH, AC, SH, TN }, 	 //	 294	 800
{ SH, ST, LO, JA, PF, JA, JA, JA, JA, JA, JA, TN, JA, JA, TN }, 	 //	 295	 800
{ SH, ST, LO, JA, SH, JA, JA, JA, JA, JA, JA, TN, JA, SH, JA }, 	 //	 296	 800
{ SH, ST, JA, JA, SK, JA, JA, JA, JA, KN, JA, TN, ST, JA, KN }, 	 //	 297	 800
{ SH, ST, JA, JA, KN, JA, JA, JA, JA, AC, JA, TN, ST, JA, LO }, 	 //	 298	 800
{ SH, ST, JA, ST, TN, JA, JA, JA, JA, AC, JA, TN, ST, TN, AC }, 	 //	 299	 800
{ SH, ST, JA, ST, AC, JA, JA, JA, JA, SK, JA, TN, ST, TN, KN }, 	 //	 300	 800
{ SH, ST, JA, ST, QN, JA, JA, JA, JA, KN, JA, TN, ST, TN, AC }, 	 //	 301	 800
{ SH, JA, JA, JA, JA, JA, TN, JA, JA, JA, JA, AC, ST, JA, JA }, 	 //	 302	 800
{ JA, QN, TN, SK, JA, JA, SK, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 303	 800
{ JA, QN, JA, JA, QN, JA, SK, JA, JA, PF, JA, JA, JA, JA, JA }, 	 //	 304	 800
{ JA, SK, TN, SK, KN, JA, JA, LO, JA, KN, JA, JA, JA, JA, KN }, 	 //	 305	 800
{ JA, SK, TN, JA, SK, JA, JA, LO, JA, QN, JA, JA, JA, JA, QN }, 	 //	 306	 800
{ JA, SK, TN, JA, JA, JA, JA, LO, JA, JA, JA, JA, JA, SH, JA }, 	 //	 307	 800
{ JA, SK, LO, QN, KN, JA, JA, JA, SK, KN, JA, JA, JA, JA, KN }, 	 //	 308	 800
{ JA, SK, LO, QN, PF, JA, JA, JA, SK, JA, JA, JA, JA, JA, TN }, 	 //	 309	 800
{ JA, SK, LO, QN, KN, JA, JA, JA, SK, KN, JA, JA, JA, JA, CR }, 	 //	 310	 800
{ JA, SK, LO, QN, SK, JA, JA, JA, ST, QN, JA, JA, JA, JA, QN }, 	 //	 311	 800
{ JA, SK, LO, QN, TN, JA, JA, JA, ST, AC, JA, JA, JA, JA, AC }, 	 //	 312	 800
{ JA, SK, LO, QN, AC, JA, JA, JA, ST, SK, JA, JA, JA, JA, KN }, 	 //	 313	 800
{ JA, SK, LO, QN, CR, JA, JA, JA, ST, QN, JA, JA, JA, JA, KN }, 	 //	 314	 800
{ JA, SK, JA, AC, AC, JA, JA, JA, PF, LO, JA, JA, JA, AC, AC }, 	 //	 315	 800
{ JA, SK, JA, AC, AC, JA, JA, JA, PF, AC, JA, JA, JA, AC, AC }, 	 //	 316	 800
{ JA, SK, JA, AC, JA, JA, JA, JA, PF, JA, JA, JA, JA, AC, JA }, 	 //	 317	 800
{ JA, SK, JA, AC, TN, JA, JA, JA, PF, TN, JA, JA, JA, AC, ST }, 	 //	 318	 800
{ JA, SK, JA, AC, KN, JA, JA, JA, PF, AC, JA, JA, JA, AC, LO }, 	 //	 319	 800
{ JA, SK, JA, PF, AC, JA, JA, JA, AC, KN, JA, JA, JA, AC, QN }, 	 //	 320	 800
{ JA, SK, JA, AC, KN, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN }, 	 //	 321	 800
{ JA, SK, JA, AC, QN, JA, JA, JA, AC, KN, JA, JA, JA, AC, AC }, 	 //	 322	 800
{ JA, SK, JA, AC, AC, JA, JA, JA, LO, LO, JA, JA, JA, KN, AC }, 	 //	 323	 800
{ JA, SK, JA, AC, AC, JA, JA, JA, LO, AC, JA, JA, JA, KN, AC }, 	 //	 324	 800
{ JA, SK, JA, AC, WN, JA, JA, JA, LO, TN, JA, JA, JA, KN, TN }, 	 //	 325	 800
{ JA, SK, JA, LO, KN, JA, JA, JA, KN, KN, JA, JA, JA, KN, CR }, 	 //	 326	 800
{ JA, SK, JA, KN, KN, JA, JA, JA, KN, QN, JA, JA, JA, KN, PF }, 	 //	 327	 800
{ JA, SK, JA, KN, KN, JA, JA, JA, KN, SK, JA, JA, JA, WN, QN }, 	 //	 328	 800
{ JA, SK, JA, QN, CR, JA, JA, JA, QN, KN, JA, JA, JA, QN, KN }, 	 //	 329	 800
{ JA, SK, JA, QN, JA, JA, JA, JA, QN, TN, JA, JA, JA, QN, AC }, 	 //	 330	 800
{ JA, SK, JA, QN, AC, JA, JA, JA, QN, SK, JA, JA, JA, QN, KN }, 	 //	 331	 800
{ JA, SK, JA, JA, KN, JA, JA, JA, SH, SK, JA, JA, JA, TN, QN }, 	 //	 332	 800
{ JA, SK, JA, JA, SK, JA, JA, JA, SH, KN, JA, JA, JA, TN, KN }, 	 //	 333	 800
{ JA, SK, JA, SH, PF, JA, JA, JA, TN, JA, JA, JA, JA, TN, TN }, 	 //	 334	 800
{ JA, SK, JA, TN, QN, JA, JA, JA, TN, PF, JA, JA, JA, TN, JA }, 	 //	 335	 800
{ JA, SK, JA, TN, AC, JA, JA, JA, TN, AC, JA, JA, JA, TN, SK }, 	 //	 336	 800
{ JA, SK, JA, TN, AC, JA, JA, JA, WN, AC, JA, JA, JA, AC, CR }, 	 //	 337	 800
{ JA, SK, JA, TN, SK, JA, JA, JA, WN, QN, JA, JA, JA, AC, QN }, 	 //	 338	 800
{ JA, SK, JA, TN, WN, JA, JA, JA, WN, TN, JA, JA, JA, AC, TN }, 	 //	 339	 800
{ JA, SK, JA, TN, KN, JA, JA, JA, WN, QN, JA, JA, JA, AC, PF }, 	 //	 340	 800
{ JA, SK, JA, TN, AC, JA, JA, JA, WN, AC, JA, JA, JA, AC, SK }, 	 //	 341	 800
{ JA, SK, JA, WN, CR, JA, JA, JA, AC, QN, JA, JA, JA, KN, KN }, 	 //	 342	 800
{ JA, SK, JA, AC, SH, JA, JA, JA, KN, JA, JA, JA, JA, QN, JA }, 	 //	 343	 800
{ JA, SK, JA, AC, TN, JA, JA, JA, KN, TN, JA, JA, JA, QN, TN }, 	 //	 344	 800
{ JA, SK, JA, AC, SK, JA, JA, JA, KN, KN, JA, JA, JA, QN, KN }, 	 //	 345	 800
{ JA, SK, JA, KN, QN, JA, JA, JA, QN, QN, JA, JA, JA, ST, QN }, 	 //	 346	 800
{ JA, SK, JA, JA, QN, JA, JA, JA, TN, QN, JA, JA, JA, AC, QN }, 	 //	 347	 800
{ JA, SK, JA, JA, CR, JA, JA, JA, TN, QN, JA, JA, JA, AC, KN }, 	 //	 348	 800
{ JA, SK, JA, TN, SK, JA, JA, JA, AC, QN, JA, JA, JA, AC, QN }, 	 //	 349	 800
{ JA, SK, JA, TN, QN, JA, JA, JA, AC, SH, JA, JA, JA, AC, JA }, 	 //	 350	 800
{ JA, SK, JA, TN, JA, JA, JA, JA, AC, WN, JA, JA, JA, AC, TN }, 	 //	 351	 800
{ JA, SK, JA, AC, SK, JA, JA, JA, AC, QN, JA, JA, JA, AC, QN }, 	 //	 352	 800
{ JA, SK, JA, AC, QN, JA, JA, JA, AC, KN, JA, JA, JA, AC, AC }, 	 //	 353	 800
{ JA, SK, JA, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA, PF, AC }, 	 //	 354	 800
{ JA, SK, JA, AC, SK, JA, JA, JA, AC, KN, JA, JA, JA, PF, KN }, 	 //	 355	 800
{ JA, SK, JA, AC, KN, JA, JA, JA, AC, KN, JA, JA, JA, PF, KN }, 	 //	 356	 800
{ JA, SK, JA, AC, AC, JA, JA, JA, PF, KN, JA, JA, JA, KN, QN }, 	 //	 357	 800
{ JA, SK, JA, PF, CR, JA, JA, JA, KN, KN, JA, JA, JA, KN, KN }, 	 //	 358	 800
{ JA, SK, JA, PF, AC, JA, JA, JA, KN, AC, JA, JA, JA, KN, AC }, 	 //	 359	 800
{ JA, SK, JA, KN, TN, JA, JA, JA, KN, ST, JA, JA, JA, KN, AC }, 	 //	 360	 800
{ JA, SK, JA, KN, AC, JA, JA, JA, KN, KN, JA, JA, JA, KN, QN }, 	 //	 361	 800
{ JA, SK, JA, KN, KN, JA, JA, JA, SK, QN, JA, JA, JA, QN, PF }, 	 //	 362	 800
{ JA, SK, JA, SK, TN, JA, JA, JA, QN, ST, JA, JA, JA, KN, AC }, 	 //	 363	 800
{ JA, SK, JA, QN, KN, JA, JA, JA, KN, SK, JA, JA, JA, AC, QN }, 	 //	 364	 800
{ JA, SK, JA, QN, QN, JA, JA, JA, KN, QN, JA, JA, JA, AC, SH }, 	 //	 365	 800
{ JA, SK, JA, QN, SH, JA, JA, JA, KN, JA, JA, JA, JA, AC, JA }, 	 //	 366	 800
{ JA, SK, JA, KN, QN, JA, JA, JA, AC, QN, JA, JA, JA, PF, QN }, 	 //	 367	 800
{ JA, SK, JA, SK, QN, JA, JA, JA, JA, QN, JA, JA, ST, JA, SH }, 	 //	 368	 800
{ JA, SK, JA, SK, AC, JA, JA, JA, JA, KN, JA, JA, ST, JA, QN }, 	 //	 369	 800
{ JA, SK, JA, SK, KN, JA, JA, JA, JA, KN, JA, JA, ST, JA, KN }, 	 //	 370	 800
{ JA, SK, JA, JA, SK, JA, JA, JA, JA, QN, JA, JA, ST, JA, QN }, 	 //	 371	 800
{ JA, SK, JA, JA, TN, JA, JA, JA, JA, AC, JA, JA, ST, JA, AC }, 	 //	 372	 800
{ JA, SK, JA, JA, TN, JA, JA, JA, JA, TN, JA, JA, ST, SH, ST }, 	 //	 373	 800
{ JA, SK, JA, JA, AC, JA, JA, JA, JA, AC, JA, JA, ST, SH, SK }, 	 //	 374	 800
{ JA, SK, JA, ST, AC, JA, JA, JA, JA, KN, JA, JA, ST, TN, QN }, 	 //	 375	 800
{ JA, SK, JA, JA, JA, JA, JA, ST, JA, JA, JA, JA, AC, SH, JA }, 	 //	 376	 800
{ JA, SK, QN, SK, KN, JA, JA, SK, JA, KN, JA, JA, JA, JA, KN }, 	 //	 377	 800
{ JA, SK, QN, SK, CR, JA, JA, SK, JA, QN, JA, JA, JA, JA, KN }, 	 //	 378	 800
{ JA, JA, TN, QN, SH, JA, JA, LO, ST, JA, JA, JA, JA, JA, JA }, 	 //	 379	 800
{ JA, JA, LO, QN, AC, JA, JA, JA, SK, KN, JA, JA, JA, JA, QN }, 	 //	 380	 800
{ JA, JA, LO, QN, AC, JA, JA, JA, ST, LO, JA, JA, JA, JA, AC }, 	 //	 381	 800
{ JA, JA, LO, QN, QN, JA, JA, JA, ST, QN, JA, JA, JA, JA, QN }, 	 //	 382	 800
{ JA, JA, JA, JA, WN, JA, JA, JA, SH, TN, JA, JA, ST, TN, TN }, 	 //	 383	 800
{ JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA, JA, ST, AC, QN }, 	 //	 384	 800
{ JA, JA, JA, JA, TN, JA, JA, JA, TN, TN, JA, JA, ST, AC, ST }, 	 //	 385	 800
{ JA, JA, JA, JA, AC, JA, JA, ST, JA, LO, JA, JA, AC, JA, AC }, 	 //	 386	 800
{ JA, JA, JA, JA, CR, JA, JA, ST, JA, QN, JA, JA, AC, JA, KN }, 	 //	 387	 800
{ JA, JA, QN, JA, TN, JA, JA, SK, JA, AC, JA, JA, JA, JA, AC }, 	 //	 388	 800
{ JA, JA, JA, JA, QN, JA, JA, TN, JA, KN, JA, JA, AC, JA, AC }, 	 //	 389	 800
{ JA, JA, JA, JA, QN, JA, JA, TN, JA, QN, JA, JA, AC, SH, QN }, 	 //	 390	 800
{ JA, JA, JA, JA, ST, JA, JA, TN, JA, AC, JA, JA, AC, SH, KN }, 	 //	 391	 800
{ JA, JA, JA, JA, AC, JA, JA, TN, JA, SK, JA, JA, AC, SH, KN }, 	 //	 392	 800
{ JA, JA, JA, ST, SH, JA, JA, TN, JA, JA, JA, JA, AC, TN, JA }, 	 //	 393	 800
{ JA, JA, LO, JA, TN, JA, JA, JA, JA, TN, JA, SH, JA, SH, TN }, 	 //	 394	 800
{ JA, JA, JA, PF, CR, JA, JA, JA, AC, KN, JA, SH, JA, AC, KN }, 	 //	 395	 800
{ JA, JA, JA, PF, WN, JA, JA, JA, AC, TN, JA, SH, JA, AC, TN }, 	 //	 396	 800
{ JA, JA, JA, PF, JA, JA, JA, JA, AC, TN, JA, SH, JA, AC, AC }, 	 //	 397	 800
{ JA, JA, JA, PF, AC, JA, JA, JA, AC, SK, JA, SH, JA, AC, KN }, 	 //	 398	 800
{ JA, JA, JA, AC, AC, JA, JA, JA, AC, AC, JA, SH, JA, LO, SK }, 	 //	 399	 800
{ JA, JA, JA, LO, AC, JA, JA, JA, KN, AC, JA, SH, JA, KN, AC }, 	 //	 400	 800
{ JA, JA, JA, LO, AC, JA, JA, JA, KN, AC, JA, SH, JA, KN, CR }, 	 //	 401	 800
{ JA, JA, JA, LO, SK, JA, JA, JA, KN, QN, JA, SH, JA, KN, QN }, 	 //	 402	 800
{ JA, JA, JA, LO, QN, JA, JA, JA, KN, SH, JA, SH, JA, KN, JA }, 	 //	 403	 800
{ JA, JA, JA, LO, TN, JA, JA, JA, KN, AC, JA, SH, JA, KN, AC }, 	 //	 404	 800
{ JA, JA, JA, LO, AC, JA, JA, JA, KN, SK, JA, SH, JA, KN, KN }, 	 //	 405	 800
{ JA, JA, JA, KN, KN, JA, JA, JA, KN, KN, JA, SH, JA, KN, KN }, 	 //	 406	 800
{ JA, JA, JA, KN, KN, JA, JA, JA, WN, KN, JA, SH, JA, QN, KN }, 	 //	 407	 800
{ JA, JA, JA, WN, LO, JA, JA, JA, QN, AC, JA, SH, JA, QN, AC }, 	 //	 408	 800
{ JA, JA, JA, WN, AC, JA, JA, JA, QN, AC, JA, SH, JA, QN, CR }, 	 //	 409	 800
{ JA, JA, JA, WN, AC, JA, JA, JA, QN, AC, JA, SH, JA, QN, SK }, 	 //	 410	 800
{ JA, JA, JA, QN, JA, JA, JA, JA, QN, TN, JA, SH, JA, QN, AC }, 	 //	 411	 800
{ JA, JA, JA, SH, SK, JA, JA, JA, TN, QN, JA, SH, JA, TN, QN }, 	 //	 412	 800
{ JA, JA, JA, SH, QN, JA, JA, JA, TN, QN, JA, SH, JA, TN, QN }, 	 //	 413	 800
{ JA, JA, JA, TN, AC, JA, JA, JA, TN, LO, JA, SH, JA, TN, AC }, 	 //	 414	 800
{ JA, JA, JA, TN, KN, JA, JA, JA, TN, KN, JA, SH, JA, TN, KN }, 	 //	 415	 800
{ JA, JA, JA, TN, ST, JA, JA, JA, TN, AC, JA, SH, JA, TN, KN }, 	 //	 416	 800
{ JA, JA, JA, TN, JA, JA, JA, JA, TN, TN, JA, SH, JA, TN, AC }, 	 //	 417	 800
{ JA, JA, JA, TN, CR, JA, JA, JA, TN, KN, JA, SH, JA, WN, KN }, 	 //	 418	 800
{ JA, JA, JA, TN, SH, JA, JA, JA, TN, JA, JA, SH, JA, WN, JA }, 	 //	 419	 800
{ JA, JA, JA, WN, KN, JA, JA, JA, AC, SK, JA, SH, JA, KN, QN }, 	 //	 420	 800
{ JA, JA, JA, WN, QN, JA, JA, JA, AC, KN, JA, SH, JA, KN, AC }, 	 //	 421	 800
{ JA, JA, JA, WN, KN, JA, JA, JA, AC, AC, JA, SH, JA, KN, LO }, 	 //	 422	 800
{ JA, JA, JA, AC, AC, JA, JA, JA, KN, AC, JA, SH, JA, QN, CR }, 	 //	 423	 800
{ JA, JA, JA, AC, KN, JA, JA, JA, KN, KN, JA, SH, JA, QN, KN }, 	 //	 424	 800
{ JA, JA, JA, AC, TN, JA, JA, JA, KN, AC, JA, SH, JA, QN, AC }, 	 //	 425	 800
{ JA, JA, JA, KN, AC, JA, JA, JA, QN, LO, JA, SH, JA, ST, AC }, 	 //	 426	 800
{ JA, JA, JA, KN, QN, JA, JA, JA, QN, KN, JA, SH, JA, ST, AC }, 	 //	 427	 800
{ JA, JA, JA, QN, JA, JA, JA, JA, ST, JA, JA, SH, JA, JA, WN }, 	 //	 428	 800
{ JA, JA, JA, TN, AC, JA, JA, JA, AC, KN, JA, SH, JA, AC, QN }, 	 //	 429	 800
{ JA, JA, JA, TN, QN, JA, JA, JA, AC, PF, JA, SH, JA, AC, JA }, 	 //	 430	 800
{ JA, JA, JA, TN, QN, JA, JA, JA, AC, KN, JA, SH, JA, AC, AC }, 	 //	 431	 800
{ JA, JA, JA, AC, LO, JA, JA, JA, AC, AC, JA, SH, JA, AC, AC }, 	 //	 432	 800
{ JA, JA, JA, AC, SK, JA, JA, JA, PF, KN, JA, SH, JA, KN, KN }, 	 //	 433	 800
{ JA, JA, JA, KN, QN, JA, JA, JA, KN, SH, JA, SH, JA, KN, JA }, 	 //	 434	 800
{ JA, JA, JA, KN, QN, JA, JA, JA, KN, PF, JA, SH, JA, KN, JA }, 	 //	 435	 800
{ JA, JA, JA, KN, KN, JA, JA, JA, KN, KN, JA, SH, JA, KN, KN }, 	 //	 436	 800
{ JA, JA, JA, KN, AC, JA, JA, JA, KN, AC, JA, SH, JA, SK, AC }, 	 //	 437	 800
{ JA, JA, JA, KN, AC, JA, JA, JA, KN, SK, JA, SH, JA, SK, KN }, 	 //	 438	 800
{ JA, JA, JA, KN, QN, JA, JA, JA, SK, KN, JA, SH, JA, QN, AC }, 	 //	 439	 800
{ JA, JA, JA, SK, QN, JA, JA, JA, QN, PF, JA, SH, JA, KN, JA }, 	 //	 440	 800
{ JA, JA, JA, QN, LO, JA, JA, JA, KN, AC, JA, SH, JA, AC, AC }, 	 //	 441	 800
{ JA, JA, JA, QN, QN, JA, JA, JA, KN, SH, JA, SH, JA, AC, JA }, 	 //	 442	 800
{ JA, JA, JA, QN, KN, JA, JA, JA, KN, QN, JA, SH, JA, AC, PF }, 	 //	 443	 800
{ JA, JA, JA, QN, JA, JA, JA, JA, KN, TN, JA, SH, JA, AC, AC }, 	 //	 444	 800
{ JA, JA, JA, JA, TN, JA, JA, JA, SH, TN, JA, SH, ST, TN, ST }, 	 //	 445	 800
{ JA, JA, JA, JA, WN, JA, JA, JA, TN, TN, JA, SH, ST, AC, TN }, 	 //	 446	 800
{ JA, JA, JA, JA, TN, JA, JA, JA, TN, AC, JA, SH, ST, AC, AC }, 	 //	 447	 800
{ JA, JA, JA, SK, JA, JA, JA, ST, JA, JA, JA, SH, AC, JA, JA }, 	 //	 448	 800
{ JA, JA, JA, JA, KN, JA, JA, ST, JA, SK, JA, SH, AC, JA, QN }, 	 //	 449	 800
{ JA, JA, JA, JA, PF, JA, JA, ST, JA, JA, JA, SH, AC, JA, TN }, 	 //	 450	 800
{ JA, JA, JA, JA, AC, JA, JA, ST, JA, AC, JA, SH, AC, JA, SK }, 	 //	 451	 800
{ JA, JA, JA, JA, AC, JA, JA, ST, JA, LO, JA, SH, AC, SH, AC }, 	 //	 452	 800
{ JA, JA, JA, JA, KN, JA, JA, ST, JA, KN, JA, SH, AC, SH, KN }, 	 //	 453	 800
{ JA, JA, JA, JA, KN, JA, JA, ST, JA, SK, JA, SH, AC, SH, QN }, 	 //	 454	 800
{ JA, JA, JA, JA, AC, JA, JA, ST, JA, KN, JA, SH, AC, SH, QN }, 	 //	 455	 800
{ JA, JA, JA, SK, SH, JA, JA, TN, JA, JA, JA, SH, AC, JA, JA }, 	 //	 456	 800
{ JA, JA, JA, JA, AC, JA, JA, TN, JA, AC, JA, SH, AC, JA, AC }, 	 //	 457	 800
{ JA, JA, JA, JA, QN, JA, JA, TN, JA, KN, JA, SH, AC, JA, AC }, 	 //	 458	 800
{ JA, JA, JA, JA, JA, JA, SH, JA, JA, TN, JA, TN, JA, JA, AC }, 	 //	 459	 800
{ JA, SH, JA, SK, JA, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA }, 	 //	 460	 800
{ JA, ST, LO, SK, LO, JA, JA, JA, JA, AC, JA, TN, JA, JA, AC }, 	 //	 461	 800
{ JA, ST, LO, SK, ST, JA, JA, JA, JA, AC, JA, TN, JA, JA, KN }, 	 //	 462	 800
{ JA, ST, LO, JA, QN, JA, JA, JA, JA, QN, JA, TN, JA, SH, SH }, 	 //	 463	 800
{ JA, ST, LO, ST, AC, JA, JA, JA, JA, AC, JA, TN, JA, TN, AC }, 	 //	 464	 800
{ JA, ST, JA, JA, JA, JA, JA, JA, TN, JA, JA, TN, JA, AC, JA }, 	 //	 465	 800
{ JA, ST, JA, SK, TN, JA, JA, JA, JA, TN, JA, TN, ST, JA, TN }, 	 //	 466	 800
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, KN, JA, TN, ST, JA, SK }, 	 //	 467	 800
{ JA, ST, JA, JA, AC, JA, JA, JA, JA, LO, JA, TN, ST, SH, AC }, 	 //	 468	 800
{ JA, ST, JA, ST, JA, JA, JA, JA, JA, TN, JA, TN, ST, TN, AC }, 	 //	 469	 800
{ JA, SK, JA, JA, JA, JA, QN, JA, JA, JA, JA, KN, JA, SH, JA }, 	 //	 470	 800
{ JA, SK, LO, JA, QN, JA, JA, JA, JA, SH, WN, JA, JA, SH, JA }, 	 //	 471	 800
{ JA, SK, JA, ST, PF, JA, JA, JA, JA, JA, WN, JA, ST, TN, TN }, 	 //	 472	 800
{ JA, JA, LO, QN, SH, JA, JA, JA, ST, JA, WN, JA, JA, JA, JA }, 	 //	 473	 800
{ JA, JA, JA, JA, QN, JA, JA, JA, SH, QN, WN, JA, JA, TN, QN }, 	 //	 474	 800
{ JA, JA, JA, JA, TN, JA, JA, JA, SH, AC, WN, JA, JA, TN, AC }, 	 //	 475	 800
{ JA, JA, JA, QN, QN, JA, JA, JA, ST, QN, WN, JA, JA, JA, SH }, 	 //	 476	 800
{ JA, JA, JA, QN, JA, JA, JA, JA, ST, WN, WN, JA, JA, JA, TN }, 	 //	 477	 800
{ JA, JA, JA, QN, KN, JA, JA, JA, ST, AC, WN, JA, JA, JA, LO }, 	 //	 478	 800
{ JA, JA, JA, JA, CR, JA, JA, JA, TN, QN, WN, JA, JA, AC, KN }, 	 //	 479	 800
{ JA, JA, JA, SK, AC, JA, JA, JA, JA, AC, WN, JA, ST, JA, AC }, 	 //	 480	 800
{ JA, JA, JA, ST, WN, JA, JA, JA, JA, TN, WN, JA, ST, TN, TN }, 	 //	 481	 800
{ JA, JA, JA, ST, TN, JA, JA, JA, JA, ST, WN, JA, ST, TN, AC }, 	 //	 482	 800
{ JA, JA, JA, ST, ST, JA, JA, JA, JA, AC, WN, JA, ST, TN, KN }, 	 //	 483	 800
{ JA, JA, JA, ST, KN, JA, JA, JA, JA, QN, WN, JA, ST, TN, PF }, 	 //	 484	 800
{ JA, JA, JA, JA, JA, JA, JA, ST, JA, TN, WN, JA, AC, JA, AC }, 	 //	 485	 800
{ JA, JA, QN, JA, QN, JA, JA, SK, JA, PF, WN, JA, JA, JA, JA }, 	 //	 486	 800
{ JA, JA, LO, SK, CR, JA, JA, JA, JA, QN, WN, SH, JA, JA, KN }, 	 //	 487	 800
{ JA, JA, LO, JA, KN, JA, JA, JA, JA, QN, WN, SH, JA, JA, PF }, 	 //	 488	 800
{ JA, JA, LO, ST, QN, JA, JA, JA, JA, SH, WN, SH, JA, TN, JA }, 	 //	 489	 800
{ JA, JA, JA, JA, KN, JA, JA, JA, SH, SK, WN, SH, JA, TN, QN }, 	 //	 490	 800
{ JA, JA, JA, JA, TN, JA, JA, JA, SH, AC, WN, SH, JA, TN, AC }, 	 //	 491	 800
{ JA, JA, JA, JA, AC, JA, JA, JA, TN, KN, WN, SH, JA, AC, QN }, 	 //	 492	 800
{ JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, WN, SH, JA, AC, KN }, 	 //	 493	 800
{ JA, JA, JA, JA, JA, JA, JA, JA, SH, JA, WN, SH, ST, TN, WN }, 	 //	 494	 800
{ JA, JA, JA, ST, ST, JA, JA, JA, JA, AC, WN, SH, ST, TN, KN }, 	 //	 495	 800
{ JA, JA, JA, JA, SH, JA, JA, TN, JA, JA, WN, SH, AC, JA, JA }, 	 //	 496	 800
{ JA, JA, JA, JA, QN, JA, JA, TN, JA, SH, WN, SH, AC, SH, JA }, 	 //	 497	 800
{ JA, TN, TN, TN, TN, JA, TN, TN, TN, TN, WN, TN, TN, WN, TN }, 	 //	 498	 800
{ JA, WN, JA, SK, JA, JA, AC, JA, JA, JA, WN, KN, JA, JA, JA }, 	 //	 499	 800
{ JA, AC, JA, JA, JA, JA, KN, JA, JA, JA, WN, QN, JA, SH, JA }, 	 //	 500	 800
{ JA, ST, LO, JA, AC, JA, JA, JA, JA, AC, WN, TN, JA, JA, AC }, 	 //	 501	 800
{ JA, ST, LO, JA, TN, JA, JA, JA, JA, TN, WN, TN, JA, JA, TN }, 	 //	 502	 800
{ JA, ST, LO, JA, QN, JA, JA, JA, JA, QN, WN, TN, JA, SH, SH }, 	 //	 503	 800
{ JA, ST, QN, SK, JA, JA, JA, SK, JA, JA, WN, TN, JA, JA, JA }, 	 //	 504	 800
{ JA, JA, JA, JA, JA, JA, TN, JA, JA, WN, WN, AC, JA, JA, TN }, 	 //	 505	 800
{ JA, TN, JA, SK, JA, JA, AC, JA, JA, JA, WN, AC, JA, JA, JA }, 	 //	 506	 800
{ JA, QN, JA, JA, JA, JA, KN, JA, JA, JA, WN, AC, JA, SH, JA }, 	 //	 507	 800
{ JA, QN, QN, QN, KN, WN, SK, QN, SK, KN, TN, JA, SK, JA, SK }, 	 //	 508	 800
{ JA, SK, LO, SK, AC, WN, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 509	 800
{ JA, SK, LO, SK, QN, WN, JA, JA, JA, QN, TN, JA, JA, JA, SH }, 	 //	 510	 800
{ JA, SK, LO, SK, CR, WN, JA, JA, JA, QN, TN, JA, JA, JA, KN }, 	 //	 511	 800
{ JA, SK, LO, JA, SH, WN, JA, JA, JA, JA, TN, JA, JA, SH, JA }, 	 //	 512	 800
{ JA, SK, LO, JA, PF, WN, JA, JA, JA, JA, TN, JA, JA, SH, TN }, 	 //	 513	 800
{ JA, SK, JA, JA, CR, WN, JA, JA, JA, KN, TN, JA, JA, SH, KN }, 	 //	 514	 800
{ JA, SK, JA, ST, SK, WN, JA, JA, JA, QN, TN, JA, JA, TN, QN }, 	 //	 515	 800
{ JA, SK, JA, ST, AC, WN, JA, JA, JA, KN, TN, JA, JA, TN, QN }, 	 //	 516	 800
{ JA, SK, JA, ST, AC, WN, JA, JA, JA, AC, TN, JA, JA, TN, SK }, 	 //	 517	 800
{ JA, SK, JA, SK, JA, WN, JA, JA, JA, JA, TN, JA, ST, JA, JA }, 	 //	 518	 800
{ JA, JA, TN, SK, QN, WN, JA, LO, JA, PF, TN, JA, JA, JA, JA }, 	 //	 519	 800
{ JA, JA, LO, SK, TN, WN, JA, JA, JA, TN, TN, JA, JA, JA, ST }, 	 //	 520	 800
{ JA, JA, JA, QN, QN, WN, JA, JA, SK, PF, TN, JA, JA, JA, JA }, 	 //	 521	 800
{ JA, JA, JA, JA, KN, WN, JA, JA, JA, SK, TN, JA, ST, JA, QN }, 	 //	 522	 800
{ JA, JA, JA, JA, SK, WN, JA, JA, JA, KN, TN, JA, ST, JA, KN }, 	 //	 523	 800
{ JA, JA, JA, JA, AC, WN, JA, JA, JA, AC, TN, JA, ST, SH, AC }, 	 //	 524	 800
{ JA, JA, JA, JA, JA, WN, JA, ST, JA, TN, TN, JA, AC, SH, AC }, 	 //	 525	 800
{ JA, JA, JA, JA, QN, WN, JA, TN, JA, SH, TN, JA, AC, SH, JA }, 	 //	 526	 800
{ JA, JA, LO, SK, PF, WN, JA, JA, JA, JA, TN, SH, JA, JA, TN }, 	 //	 527	 800
{ JA, JA, JA, JA, CR, WN, JA, JA, JA, QN, TN, SH, ST, JA, KN }, 	 //	 528	 800
{ JA, SH, TN, TN, TN, WN, TN, TN, TN, TN, TN, TN, TN, WN, ST }, 	 //	 529	 800
{ JA, TN, TN, TN, JA, WN, TN, TN, TN, TN, TN, TN, TN, TN, AC }, 	 //	 530	 800
{ JA, KN, JA, JA, JA, WN, QN, JA, JA, JA, TN, ST, JA, SH, JA }, 	 //	 531	 800
{ JA, ST, LO, SK, JA, WN, JA, JA, JA, WN, TN, TN, JA, JA, TN }, 	 //	 532	 800
{ JA, ST, JA, SK, AC, WN, JA, JA, JA, SK, TN, TN, JA, JA, KN }, 	 //	 533	 800
{ JA, ST, JA, SK, CR, WN, JA, JA, JA, QN, TN, TN, JA, JA, KN }, 	 //	 534	 800
{ JA, ST, JA, JA, TN, WN, JA, JA, JA, TN, TN, TN, JA, JA, ST }, 	 //	 535	 800
{ JA, ST, JA, JA, SK, WN, JA, JA, JA, KN, TN, TN, JA, JA, KN }, 	 //	 536	 800
{ JA, ST, JA, JA, QN, WN, JA, JA, JA, QN, TN, TN, JA, SH, QN }, 	 //	 537	 800
{ JA, ST, JA, JA, KN, WN, JA, JA, JA, KN, TN, TN, JA, SH, KN }, 	 //	 538	 800
{ JA, ST, JA, ST, SK, WN, JA, JA, JA, KN, TN, TN, JA, TN, KN }, 	 //	 539	 800
{ JA, KN, JA, SK, JA, WN, SK, JA, JA, JA, TN, QN, JA, JA, JA }, 	 //	 540	 800
{ JA, SK, JA, JA, JA, WN, QN, JA, JA, JA, TN, KN, JA, SH, JA }, 	 //	 541	 800
{ WN, SH, JA, JA, JA, TN, AC, JA, JA, JA, TN, AC, JA, SH, JA }, 	 //	 542	 800
{ WN, SK, TN, SK, JA, TN, JA, LO, JA, JA, TN, JA, JA, JA, JA }, 	 //	 543	 800
{ WN, SK, LO, SK, JA, TN, JA, JA, JA, TN, TN, JA, JA, JA, AC }, 	 //	 544	 800
{ WN, SK, JA, SK, AC, TN, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 545	 800
{ WN, SK, JA, JA, QN, TN, JA, JA, JA, QN, TN, JA, JA, JA, SH }, 	 //	 546	 800
{ WN, JA, JA, SK, TN, TN, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 547	 800
{ WN, JA, JA, JA, LO, TN, JA, JA, JA, AC, TN, JA, JA, SH, AC }, 	 //	 548	 800
{ WN, JA, JA, JA, AC, TN, JA, JA, JA, AC, TN, JA, JA, SH, CR }, 	 //	 549	 800
{ WN, JA, JA, JA, CR, TN, JA, JA, JA, QN, TN, JA, JA, SH, KN }, 	 //	 550	 800
{ WN, JA, JA, ST, JA, TN, JA, JA, JA, TN, TN, JA, JA, TN, AC }, 	 //	 551	 800
{ WN, JA, JA, JA, JA, TN, JA, TN, JA, JA, TN, JA, AC, JA, JA }, 	 //	 552	 800
{ WN, JA, JA, JA, KN, TN, JA, JA, JA, SK, TN, SH, JA, JA, QN }, 	 //	 553	 800
{ WN, JA, JA, JA, SK, TN, JA, JA, JA, KN, TN, SH, JA, JA, KN }, 	 //	 554	 800
{ WN, JA, JA, ST, QN, TN, JA, JA, JA, PF, TN, SH, JA, TN, JA }, 	 //	 555	 800
{ WN, JA, JA, JA, SH, TN, SH, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 556	 800
{ WN, TN, TN, SH, TN, TN, TN, TN, TN, ST, TN, TN, TN, TN, AC }, 	 //	 557	 800
{ WN, TN, TN, TN, LO, TN, TN, TN, TN, AC, TN, TN, TN, TN, AC }, 	 //	 558	 800
{ WN, AC, JA, SK, JA, TN, KN, JA, JA, JA, TN, QN, JA, JA, JA }, 	 //	 559	 800
{ WN, KN, JA, JA, JA, TN, QN, JA, JA, JA, TN, ST, JA, SH, JA }, 	 //	 560	 800
{ WN, ST, JA, ST, JA, TN, JA, JA, JA, WN, TN, TN, JA, TN, TN }, 	 //	 561	 800
{ WN, ST, JA, JA, SH, TN, JA, JA, JA, JA, TN, TN, ST, SH, JA }, 	 //	 562	 800
{ WN, JA, TN, TN, TN, TN, TN, TN, TN, TN, TN, AC, TN, WN, ST }, 	 //	 563	 800
{ TN, SH, JA, JA, JA, TN, AC, JA, JA, JA, TN, AC, JA, SH, JA }, 	 //	 564	 800
{ TN, AC, JA, SK, JA, TN, AC, JA, JA, JA, TN, LO, JA, JA, JA }, 	 //	 565	 800
{ TN, QN, QN, QN, SK, TN, QN, QN, SK, KN, TN, SK, SK, JA, KN }, 	 //	 566	 800
{ TN, QN, JA, JA, SH, TN, SK, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 567	 800
{ TN, SK, JA, SK, ST, TN, JA, JA, JA, AC, TN, JA, JA, JA, KN }, 	 //	 568	 800
{ TN, SK, JA, JA, KN, TN, JA, JA, JA, KN, TN, JA, JA, JA, SK }, 	 //	 569	 800
{ TN, SK, JA, JA, WN, TN, JA, JA, JA, TN, TN, JA, JA, JA, TN }, 	 //	 570	 800
{ TN, SK, JA, JA, AC, TN, JA, JA, JA, SK, TN, JA, JA, JA, KN }, 	 //	 571	 800
{ TN, JA, LO, SK, JA, TN, JA, JA, JA, WN, TN, JA, JA, JA, TN }, 	 //	 572	 800
{ TN, JA, JA, SK, TN, TN, JA, JA, JA, TN, TN, JA, JA, JA, ST }, 	 //	 573	 800
{ TN, JA, JA, JA, KN, TN, JA, JA, JA, QN, TN, JA, JA, SH, PF }, 	 //	 574	 800
{ TN, JA, JA, JA, QN, TN, JA, JA, JA, KN, TN, JA, JA, SH, AC }, 	 //	 575	 800
{ TN, JA, JA, JA, ST, TN, JA, JA, JA, AC, TN, SH, JA, JA, KN }, 	 //	 576	 800
{ TN, JA, JA, JA, AC, TN, JA, JA, JA, KN, TN, SH, JA, SH, QN }, 	 //	 577	 800
{ TN, JA, JA, JA, KN, TN, JA, JA, JA, KN, TN, SH, JA, SH, CR }, 	 //	 578	 800
{ TN, JA, JA, ST, QN, TN, JA, JA, JA, SH, TN, SH, JA, TN, JA }, 	 //	 579	 800
{ TN, JA, JA, SK, SH, TN, JA, JA, JA, JA, TN, SH, ST, JA, JA }, 	 //	 580	 800
{ TN, JA, JA, JA, JA, TN, SH, JA, JA, JA, TN, TN, ST, SH, JA }, 	 //	 581	 800
{ TN, SH, TN, SH, QN, TN, TN, TN, TN, QN, TN, TN, TN, TN, SH }, 	 //	 582	 800
{ TN, SH, TN, SH, QN, TN, TN, TN, TN, KN, TN, TN, TN, TN, AC }, 	 //	 583	 800
{ TN, SH, TN, TN, KN, TN, TN, TN, TN, KN, TN, TN, TN, TN, KN }, 	 //	 584	 800
{ TN, TN, TN, JA, QN, TN, TN, TN, TN, QN, TN, TN, TN, AC, SH }, 	 //	 585	 800
{ TN, TN, TN, JA, KN, TN, TN, TN, TN, AC, TN, TN, TN, AC, LO }, 	 //	 586	 800
{ TN, TN, TN, TN, AC, TN, TN, TN, TN, LO, TN, WN, TN, TN, AC }, 	 //	 587	 800
{ TN, TN, TN, TN, JA, TN, TN, TN, TN, JA, TN, WN, TN, TN, WN }, 	 //	 588	 800
{ TN, TN, TN, TN, KN, TN, TN, TN, TN, QN, TN, WN, TN, WN, PF }, 	 //	 589	 800
{ TN, TN, JA, SK, JA, TN, WN, JA, JA, JA, TN, AC, JA, JA, JA }, 	 //	 590	 800
{ TN, ST, JA, JA, QN, TN, JA, JA, JA, SH, TN, TN, JA, SH, JA }, 	 //	 591	 800
{ TN, ST, JA, JA, SH, TN, JA, JA, JA, JA, TN, TN, ST, JA, JA }, 	 //	 592	 800
{ TN, JA, TN, TN, JA, TN, TN, TN, TN, WN, TN, AC, TN, TN, TN }, 	 //	 593	 800
{ TN, AC, JA, SK, JA, TN, PF, JA, JA, JA, TN, KN, JA, JA, JA }, 	 //	 594	 800
{ TN, KN, JA, SK, JA, TN, KN, JA, JA, JA, TN, SK, JA, JA, JA }, 	 //	 595	 800
{ TN, AC, JA, SK, JA, TN, AC, JA, JA, JA, ST, AC, JA, JA, JA }, 	 //	 596	 800
{ TN, KN, JA, JA, JA, TN, ST, JA, JA, JA, ST, QN, JA, SH, JA }, 	 //	 597	 800
{ TN, SK, JA, SK, CR, TN, JA, JA, JA, KN, ST, JA, JA, JA, KN }, 	 //	 598	 800
{ TN, SK, JA, SK, ST, TN, JA, JA, JA, AC, ST, JA, JA, JA, KN }, 	 //	 599	 800
{ TN, SK, JA, SK, CR, TN, JA, JA, JA, QN, ST, JA, JA, JA, KN }, 	 //	 600	 800
{ TN, SK, JA, ST, JA, TN, JA, JA, JA, WN, ST, JA, JA, TN, TN }, 	 //	 601	 800
{ TN, JA, TN, SK, JA, TN, JA, LO, JA, JA, ST, JA, JA, JA, JA }, 	 //	 602	 800
{ TN, JA, JA, SK, ST, TN, JA, JA, JA, AC, ST, JA, JA, JA, KN }, 	 //	 603	 800
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, WN, ST, JA, ST, JA, TN }, 	 //	 604	 800
{ TN, JA, JA, JA, KN, TN, JA, JA, JA, KN, ST, SH, JA, SH, CR }, 	 //	 605	 800
{ TN, JA, JA, JA, CR, TN, JA, JA, JA, QN, ST, SH, JA, SH, KN }, 	 //	 606	 800
{ TN, JA, JA, JA, QN, TN, JA, JA, JA, KN, ST, SH, JA, SH, AC }, 	 //	 607	 800
{ TN, JA, JA, JA, PF, TN, JA, JA, JA, JA, ST, SH, ST, JA, TN }, 	 //	 608	 800
{ TN, JA, JA, JA, JA, TN, SH, JA, JA, JA, ST, TN, JA, SH, WN }, 	 //	 609	 800
{ TN, TN, TN, TN, SK, TN, TN, TN, TN, QN, ST, TN, TN, TN, QN }, 	 //	 610	 800
{ TN, TN, TN, TN, AC, TN, TN, TN, TN, AC, ST, TN, TN, TN, SK }, 	 //	 611	 800
{ TN, TN, JA, JA, JA, TN, TN, JA, JA, JA, ST, WN, JA, SH, JA }, 	 //	 612	 800
{ TN, QN, JA, JA, JA, TN, ST, JA, JA, JA, ST, JA, JA, JA, WN }, 	 //	 613	 800
{ TN, ST, LO, SK, JA, TN, JA, JA, JA, JA, ST, TN, JA, JA, WN }, 	 //	 614	 800
{ TN, JA, TN, TN, TN, TN, TN, TN, TN, TN, ST, AC, TN, WN, ST }, 	 //	 615	 800
{ TN, AC, JA, JA, JA, TN, AC, JA, JA, JA, ST, AC, JA, SH, JA }, 	 //	 616	 800
{ TN, SK, JA, SK, JA, TN, QN, JA, JA, JA, ST, KN, JA, JA, JA }, 	 //	 617	 800
{ TN, AC, JA, JA, JA, ST, AC, JA, JA, JA, AC, LO, JA, SH, JA }, 	 //	 618	 800
{ TN, AC, JA, JA, JA, ST, LO, JA, JA, JA, AC, KN, JA, SH, JA }, 	 //	 619	 800
{ TN, QN, JA, JA, SH, ST, SK, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 620	 800
{ TN, QN, QN, QN, AC, ST, SK, QN, QN, AC, AC, JA, SK, SK, SK }, 	 //	 621	 800
{ TN, SK, LO, SK, QN, ST, JA, JA, JA, PF, AC, JA, JA, JA, JA }, 	 //	 622	 800
{ TN, SK, LO, JA, JA, ST, JA, JA, JA, JA, AC, JA, JA, SH, JA }, 	 //	 623	 800
{ TN, SK, JA, SK, AC, ST, JA, JA, JA, LO, AC, JA, JA, JA, AC }, 	 //	 624	 800
{ TN, SK, JA, SK, KN, ST, JA, JA, JA, KN, AC, JA, JA, JA, KN }, 	 //	 625	 800
{ TN, SK, JA, JA, QN, ST, JA, JA, JA, QN, AC, JA, JA, JA, SH }, 	 //	 626	 800
{ TN, SK, JA, JA, AC, ST, JA, JA, JA, SK, AC, JA, JA, JA, KN }, 	 //	 627	 800
{ TN, SK, JA, JA, QN, ST, JA, JA, JA, SH, AC, JA, JA, SH, JA }, 	 //	 628	 800
{ TN, JA, JA, SK, LO, ST, JA, JA, JA, AC, AC, JA, JA, JA, AC }, 	 //	 629	 800
{ TN, JA, JA, SK, KN, ST, JA, JA, JA, KN, AC, JA, JA, JA, KN }, 	 //	 630	 800
{ TN, JA, JA, SK, KN, ST, JA, JA, JA, KN, AC, JA, JA, JA, CR }, 	 //	 631	 800
{ TN, JA, JA, JA, ST, ST, JA, JA, JA, AC, AC, JA, JA, SH, KN }, 	 //	 632	 800
{ TN, JA, JA, JA, AC, ST, JA, JA, JA, SK, AC, JA, JA, SH, KN }, 	 //	 633	 800
{ TN, JA, JA, JA, QN, ST, JA, JA, JA, SH, AC, JA, ST, SH, JA }, 	 //	 634	 800
{ TN, JA, JA, JA, QN, ST, JA, JA, JA, QN, AC, SH, JA, JA, SH }, 	 //	 635	 800
{ TN, JA, JA, JA, AC, ST, JA, JA, JA, AC, AC, SH, JA, SH, AC }, 	 //	 636	 800
{ TN, JA, JA, ST, QN, ST, JA, JA, JA, SH, AC, SH, JA, TN, JA }, 	 //	 637	 800
{ TN, JA, JA, ST, JA, ST, JA, JA, JA, WN, AC, SH, JA, TN, TN }, 	 //	 638	 800
{ TN, JA, JA, SK, SH, ST, JA, JA, JA, JA, AC, SH, ST, JA, JA }, 	 //	 639	 800
{ TN, TN, JA, JA, JA, ST, TN, JA, JA, JA, AC, WN, JA, SH, JA }, 	 //	 640	 800
{ TN, QN, JA, JA, JA, ST, ST, JA, JA, JA, AC, JA, JA, JA, WN }, 	 //	 641	 800
{ TN, QN, JA, JA, JA, ST, ST, JA, JA, JA, AC, JA, JA, SH, JA }, 	 //	 642	 800
{ TN, ST, LO, JA, JA, ST, JA, JA, JA, JA, AC, TN, JA, SH, JA }, 	 //	 643	 800
{ TN, ST, LO, ST, JA, ST, JA, JA, JA, JA, AC, TN, JA, TN, JA }, 	 //	 644	 800
{ TN, KN, JA, SK, JA, ST, AC, JA, JA, JA, AC, SH, JA, JA, JA }, 	 //	 645	 800
{ ST, QN, JA, JA, SH, AC, SK, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 646	 800
{ ST, QN, QN, QN, AC, AC, SK, QN, QN, AC, KN, JA, SK, SK, SK }, 	 //	 647	 800
{ ST, SK, JA, JA, KN, AC, JA, JA, JA, QN, KN, JA, JA, JA, PF }, 	 //	 648	 800
{ ST, SK, JA, JA, SK, AC, JA, JA, JA, KN, KN, JA, JA, JA, KN }, 	 //	 649	 800
{ ST, SK, JA, JA, KN, AC, JA, JA, JA, AC, KN, JA, JA, JA, LO }, 	 //	 650	 800
{ ST, JA, LO, SK, JA, AC, JA, JA, JA, WN, KN, JA, JA, JA, TN }, 	 //	 651	 800
{ ST, JA, JA, SK, TN, AC, JA, JA, JA, TN, KN, JA, JA, JA, TN }, 	 //	 652	 800
{ ST, JA, JA, SK, CR, AC, JA, JA, JA, QN, KN, JA, JA, JA, KN }, 	 //	 653	 800
{ ST, JA, JA, JA, WN, AC, JA, JA, JA, TN, KN, JA, JA, SH, TN }, 	 //	 654	 800
{ ST, JA, JA, JA, AC, AC, JA, JA, JA, SK, KN, JA, JA, SH, KN }, 	 //	 655	 800
{ ST, JA, JA, ST, QN, AC, JA, JA, JA, SH, KN, JA, JA, TN, JA }, 	 //	 656	 800
{ ST, JA, JA, SK, JA, AC, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 657	 800
{ ST, JA, LO, SK, SH, AC, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 658	 800
{ ST, JA, JA, JA, JA, AC, JA, JA, JA, WN, KN, SH, ST, SH, TN }, 	 //	 659	 800
{ ST, JA, JA, JA, JA, AC, SH, JA, JA, JA, KN, TN, ST, SH, JA }, 	 //	 660	 800
{ ST, AC, JA, JA, JA, AC, KN, JA, JA, JA, KN, QN, JA, SH, JA }, 	 //	 661	 800
{ ST, ST, LO, JA, SH, AC, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 662	 800
{ ST, ST, LO, ST, JA, AC, JA, JA, JA, JA, KN, TN, JA, TN, JA }, 	 //	 663	 800
{ ST, KN, JA, JA, JA, AC, KN, JA, JA, JA, KN, KN, JA, SH, JA }, 	 //	 664	 800
{ AC, QN, QN, QN, KN, KN, SK, QN, SK, KN, QN, JA, SK, JA, SK }, 	 //	 665	 800
{ AC, SK, JA, JA, AC, KN, JA, JA, JA, LO, QN, JA, JA, JA, AC }, 	 //	 666	 800
{ AC, SK, JA, JA, QN, KN, JA, JA, JA, KN, QN, JA, JA, JA, AC }, 	 //	 667	 800
{ AC, JA, JA, SK, KN, KN, JA, JA, JA, SK, QN, JA, JA, JA, QN }, 	 //	 668	 800
{ AC, JA, JA, SK, KN, KN, JA, JA, JA, QN, QN, JA, JA, JA, PF }, 	 //	 669	 800
{ AC, JA, JA, SK, TN, KN, JA, JA, JA, AC, QN, JA, JA, JA, AC }, 	 //	 670	 800
{ AC, JA, JA, SK, KN, KN, JA, JA, JA, AC, QN, JA, JA, JA, LO }, 	 //	 671	 800
{ AC, JA, JA, ST, PF, KN, JA, JA, JA, JA, QN, JA, JA, TN, TN }, 	 //	 672	 800
{ AC, JA, JA, JA, QN, KN, JA, JA, JA, QN, QN, SH, JA, SH, SH }, 	 //	 673	 800
{ AC, JA, JA, ST, QN, KN, JA, JA, JA, SH, QN, SH, JA, TN, JA }, 	 //	 674	 800
{ AC, JA, JA, JA, QN, KN, JA, JA, JA, SH, QN, SH, ST, JA, JA }, 	 //	 675	 800
{ AC, JA, JA, JA, JA, KN, JA, TN, JA, JA, QN, SH, AC, SH, JA }, 	 //	 676	 800
{ AC, JA, JA, JA, JA, KN, SH, JA, JA, JA, QN, TN, JA, JA, WN }, 	 //	 677	 800
{ AC, TN, TN, TN, TN, KN, TN, TN, TN, TN, QN, TN, TN, TN, ST }, 	 //	 678	 800
{ AC, QN, LO, SK, JA, KN, ST, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 679	 800
{ AC, ST, LO, JA, JA, KN, JA, JA, JA, JA, QN, TN, JA, SH, JA }, 	 //	 680	 800
{ AC, ST, JA, ST, PF, KN, JA, JA, JA, JA, QN, TN, JA, TN, TN }, 	 //	 681	 800
{ AC, KN, JA, SK, JA, KN, KN, JA, JA, JA, QN, SK, JA, JA, JA }, 	 //	 682	 800
{ KN, SH, JA, JA, JA, QN, AC, JA, JA, JA, PF, AC, JA, SH, JA }, 	 //	 683	 800
{ KN, QN, JA, SK, SH, QN, SK, JA, JA, JA, PF, JA, JA, JA, JA }, 	 //	 684	 800
{ KN, SK, JA, SK, LO, QN, JA, JA, JA, AC, PF, JA, JA, JA, AC }, 	 //	 685	 800
{ KN, SK, JA, JA, AC, QN, JA, JA, JA, AC, PF, JA, JA, JA, AC }, 	 //	 686	 800
{ KN, SK, JA, JA, TN, QN, JA, JA, JA, AC, PF, JA, JA, JA, AC }, 	 //	 687	 800
{ KN, SK, JA, JA, AC, QN, JA, JA, JA, AC, PF, JA, JA, JA, SK }, 	 //	 688	 800
{ KN, SK, JA, ST, JA, QN, JA, JA, JA, WN, PF, JA, JA, TN, TN }, 	 //	 689	 800
{ KN, SK, JA, SK, JA, QN, JA, JA, JA, JA, PF, JA, ST, JA, JA }, 	 //	 690	 800
{ KN, JA, JA, SK, TN, QN, JA, JA, JA, ST, PF, JA, JA, JA, AC }, 	 //	 691	 800
{ KN, JA, JA, JA, QN, QN, JA, JA, JA, SH, PF, JA, ST, SH, JA }, 	 //	 692	 800
{ KN, JA, JA, JA, TN, QN, JA, JA, JA, TN, PF, SH, JA, JA, TN }, 	 //	 693	 800
{ KN, JA, JA, JA, KN, QN, JA, JA, JA, KN, PF, SH, JA, SH, KN }, 	 //	 694	 800
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, WN, PF, SH, ST, SH, TN }, 	 //	 695	 800
{ KN, JA, JA, ST, SH, QN, JA, JA, JA, JA, PF, SH, ST, TN, JA }, 	 //	 696	 800
{ KN, AC, JA, SK, JA, QN, KN, JA, JA, JA, PF, QN, JA, JA, JA }, 	 //	 697	 800
{ KN, ST, LO, ST, JA, QN, JA, JA, JA, JA, PF, TN, JA, TN, WN }, 	 //	 698	 800
{ KN, ST, JA, ST, JA, QN, JA, JA, JA, WN, PF, TN, JA, TN, TN }, 	 //	 699	 800
{ KN, JA, JA, JA, JA, QN, TN, JA, JA, JA, PF, AC, JA, JA, WN }, 	 //	 700	 800
{ QN, SH, JA, SK, JA, PF, AC, JA, JA, JA, JA, AC, JA, JA, JA }, 	 //	 701	 800
{ QN, KN, JA, JA, JA, PF, KN, JA, JA, JA, JA, ST, JA, SH, JA }, 	 //	 702	 800
{ QN, QN, JA, JA, JA, PF, SK, JA, JA, WN, JA, JA, JA, JA, TN }, 	 //	 703	 800
{ QN, QN, QN, KN, KN, PF, SK, QN, KN, KN, JA, JA, SK, SK, SK }, 	 //	 704	 800
{ QN, SK, LO, SK, AC, PF, JA, JA, JA, AC, JA, JA, JA, JA, CR }, 	 //	 705	 800
{ QN, SK, LO, SK, QN, PF, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 706	 800
{ QN, SK, LO, SK, KN, PF, JA, JA, JA, QN, JA, JA, JA, JA, PF }, 	 //	 707	 800
{ QN, SK, JA, JA, QN, PF, JA, JA, JA, PF, JA, JA, ST, SH, JA }, 	 //	 708	 800
{ QN, JA, TN, JA, SH, PF, JA, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 709	 800
{ QN, JA, TN, JA, JA, PF, JA, LO, JA, WN, JA, JA, JA, JA, TN }, 	 //	 710	 800
{ QN, JA, LO, JA, AC, PF, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 711	 800
{ QN, JA, LO, JA, SK, PF, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 712	 800
{ QN, JA, LO, ST, SH, PF, JA, JA, JA, JA, JA, JA, JA, TN, JA }, 	 //	 713	 800
{ QN, JA, JA, QN, QN, PF, JA, JA, SK, PF, JA, JA, JA, JA, JA }, 	 //	 714	 800
{ QN, JA, JA, QN, JA, PF, JA, JA, ST, JA, JA, JA, JA, JA, JA }, 	 //	 715	 800
{ QN, JA, JA, JA, JA, PF, JA, JA, TN, JA, JA, JA, JA, AC, JA }, 	 //	 716	 800
{ QN, JA, JA, JA, KN, PF, JA, JA, JA, SK, JA, JA, ST, SH, QN }, 	 //	 717	 800
{ QN, JA, JA, JA, TN, PF, JA, JA, JA, ST, JA, JA, ST, SH, AC }, 	 //	 718	 800
{ QN, JA, JA, JA, QN, PF, JA, ST, JA, SH, JA, JA, AC, SH, JA }, 	 //	 719	 800
{ QN, JA, LO, JA, JA, PF, JA, JA, JA, JA, JA, SH, JA, JA, WN }, 	 //	 720	 800
{ QN, JA, JA, SK, AC, PF, JA, JA, JA, AC, JA, SH, JA, JA, AC }, 	 //	 721	 800
{ QN, JA, JA, SK, AC, PF, JA, JA, JA, KN, JA, SH, JA, JA, QN }, 	 //	 722	 800
{ QN, JA, JA, ST, QN, PF, JA, JA, JA, QN, JA, SH, JA, TN, QN }, 	 //	 723	 800
{ QN, JA, JA, ST, AC, PF, JA, JA, JA, SK, JA, SH, JA, TN, KN }, 	 //	 724	 800
{ QN, JA, JA, SK, QN, PF, JA, JA, JA, SH, JA, SH, ST, JA, JA }, 	 //	 725	 800
{ QN, JA, JA, JA, KN, PF, JA, JA, JA, AC, JA, SH, ST, JA, LO }, 	 //	 726	 800
{ QN, JA, JA, JA, ST, PF, JA, JA, JA, AC, JA, SH, ST, SH, KN }, 	 //	 727	 800
{ QN, JA, JA, JA, AC, PF, JA, JA, JA, AC, JA, SH, ST, SH, AC }, 	 //	 728	 800
{ QN, JA, JA, ST, JA, PF, JA, JA, JA, JA, JA, SH, ST, TN, WN }, 	 //	 729	 800
{ QN, JA, JA, JA, JA, PF, SH, JA, JA, JA, JA, TN, JA, JA, WN }, 	 //	 730	 800
{ QN, JA, JA, JA, JA, PF, SH, JA, JA, JA, JA, TN, ST, SH, JA }, 	 //	 731	 800
{ QN, AC, JA, JA, JA, PF, KN, JA, JA, JA, JA, QN, JA, SH, JA }, 	 //	 732	 800
{ QN, KN, JA, SK, JA, PF, QN, JA, JA, JA, JA, ST, JA, JA, JA }, 	 //	 733	 800
{ QN, QN, TN, SK, JA, PF, ST, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 734	 800
{ QN, QN, JA, JA, JA, PF, ST, JA, JA, WN, JA, JA, JA, JA, TN }, 	 //	 735	 800
{ QN, ST, JA, SK, CR, PF, JA, JA, JA, KN, JA, TN, JA, JA, KN }, 	 //	 736	 800
{ QN, ST, JA, JA, AC, PF, JA, JA, JA, AC, JA, TN, JA, SH, AC }, 	 //	 737	 800
{ QN, ST, JA, JA, AC, PF, JA, JA, JA, AC, JA, TN, JA, SH, SK }, 	 //	 738	 800
{ QN, ST, JA, JA, AC, PF, JA, JA, JA, SK, JA, TN, JA, SH, KN }, 	 //	 739	 800
{ QN, ST, JA, ST, CR, PF, JA, JA, JA, KN, JA, TN, JA, TN, KN }, 	 //	 740	 800
{ QN, TN, JA, JA, JA, PF, AC, JA, JA, JA, JA, AC, JA, SH, JA }, 	 //	 741	 800
{ QN, PF, JA, SK, JA, PF, KN, JA, JA, JA, JA, KN, JA, JA, JA }, 	 //	 742	 800
{ PF, KN, JA, SK, JA, JA, ST, JA, JA, JA, TN, QN, JA, JA, JA }, 	 //	 743	 800
{ PF, SK, LO, SK, TN, JA, JA, JA, JA, ST, TN, JA, JA, JA, AC }, 	 //	 744	 800
{ PF, SK, LO, SK, ST, JA, JA, JA, JA, AC, TN, JA, JA, JA, KN }, 	 //	 745	 800
{ PF, SK, LO, SK, AC, JA, JA, JA, JA, SK, TN, JA, JA, JA, KN }, 	 //	 746	 800
{ PF, SK, LO, JA, CR, JA, JA, JA, JA, QN, TN, JA, JA, JA, KN }, 	 //	 747	 800
{ PF, SK, JA, JA, KN, JA, JA, JA, JA, SK, TN, JA, JA, SH, QN }, 	 //	 748	 800
{ PF, SK, JA, JA, WN, JA, JA, JA, JA, TN, TN, JA, JA, SH, TN }, 	 //	 749	 800
{ PF, SK, JA, JA, KN, JA, JA, JA, JA, KN, TN, JA, JA, SH, KN }, 	 //	 750	 800
{ PF, SK, JA, ST, KN, JA, JA, JA, JA, KN, TN, JA, JA, TN, SK }, 	 //	 751	 800
{ PF, SK, JA, ST, QN, JA, JA, JA, JA, QN, TN, JA, JA, TN, QN }, 	 //	 752	 800
{ PF, SK, JA, ST, WN, JA, JA, JA, JA, TN, TN, JA, JA, TN, TN }, 	 //	 753	 800
{ PF, SK, JA, ST, AC, JA, JA, JA, JA, SK, TN, JA, JA, TN, KN }, 	 //	 754	 800
{ PF, SK, JA, SK, QN, JA, JA, JA, JA, PF, TN, JA, ST, JA, JA }, 	 //	 755	 800
{ PF, SK, JA, JA, QN, JA, JA, JA, JA, SH, TN, JA, ST, JA, JA }, 	 //	 756	 800
{ PF, JA, LO, JA, AC, JA, JA, JA, JA, LO, TN, JA, JA, JA, AC }, 	 //	 757	 800
{ PF, JA, LO, JA, LO, JA, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 758	 800
{ PF, JA, LO, JA, CR, JA, JA, JA, JA, QN, TN, JA, JA, JA, KN }, 	 //	 759	 800
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, ST, JA, AC }, 	 //	 760	 800
{ PF, JA, JA, JA, CR, JA, JA, JA, JA, KN, TN, JA, ST, JA, KN }, 	 //	 761	 800
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, ST, JA, AC }, 	 //	 762	 800
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, ST, SH, AC }, 	 //	 763	 800
{ PF, JA, JA, JA, KN, JA, JA, JA, JA, SK, TN, JA, ST, SH, QN }, 	 //	 764	 800
{ PF, JA, JA, JA, TN, JA, JA, JA, JA, ST, TN, JA, ST, SH, AC }, 	 //	 765	 800
{ PF, JA, JA, JA, ST, JA, JA, JA, JA, AC, TN, JA, ST, SH, KN }, 	 //	 766	 800
{ PF, JA, JA, ST, QN, JA, JA, JA, JA, SH, TN, JA, ST, TN, JA }, 	 //	 767	 800
{ PF, JA, JA, ST, PF, JA, JA, JA, JA, JA, TN, JA, ST, TN, TN }, 	 //	 768	 800
{ PF, JA, LO, ST, SH, JA, JA, JA, JA, JA, TN, SH, JA, TN, JA }, 	 //	 769	 800
{ PF, JA, JA, SK, KN, JA, JA, JA, JA, SK, TN, SH, JA, JA, QN }, 	 //	 770	 800
{ PF, JA, JA, ST, QN, JA, JA, JA, JA, QN, TN, SH, JA, TN, SH }, 	 //	 771	 800
{ PF, JA, JA, ST, WN, JA, JA, JA, JA, TN, TN, SH, JA, TN, TN }, 	 //	 772	 800
{ PF, JA, JA, ST, TN, JA, JA, JA, JA, ST, TN, SH, JA, TN, AC }, 	 //	 773	 800
{ PF, JA, JA, ST, ST, JA, JA, JA, JA, AC, TN, SH, JA, TN, KN }, 	 //	 774	 800
{ PF, JA, JA, SK, QN, JA, JA, JA, JA, SH, TN, SH, ST, JA, JA }, 	 //	 775	 800
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, QN, TN, SH, ST, JA, SH }, 	 //	 776	 800
{ PF, JA, JA, JA, LO, JA, JA, JA, JA, AC, TN, SH, ST, SH, AC }, 	 //	 777	 800
{ PF, JA, JA, JA, SK, JA, JA, JA, JA, QN, TN, SH, ST, SH, QN }, 	 //	 778	 800
{ PF, JA, JA, ST, QN, JA, JA, JA, JA, PF, TN, SH, ST, TN, JA }, 	 //	 779	 800
{ PF, JA, JA, SK, JA, JA, SH, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 780	 800
{ PF, TN, TN, TN, WN, JA, TN, TN, TN, TN, TN, WN, TN, TN, TN }, 	 //	 781	 800
{ PF, TN, TN, TN, TN, JA, TN, TN, TN, TN, TN, WN, TN, WN, ST }, 	 //	 782	 800
{ PF, ST, JA, JA, LO, JA, JA, JA, JA, AC, TN, TN, JA, JA, AC }, 	 //	 783	 800
{ PF, ST, JA, JA, TN, JA, JA, JA, JA, TN, TN, TN, JA, JA, TN }, 	 //	 784	 800
{ PF, ST, JA, JA, QN, JA, JA, JA, JA, QN, TN, TN, JA, SH, QN }, 	 //	 785	 800
{ PF, ST, JA, JA, SK, JA, JA, JA, JA, KN, TN, TN, JA, SH, KN }, 	 //	 786	 800
{ PF, ST, JA, ST, AC, JA, JA, JA, JA, LO, TN, TN, JA, TN, AC }, 	 //	 787	 800
{ PF, ST, JA, ST, SK, JA, JA, JA, JA, QN, TN, TN, JA, TN, QN }, 	 //	 788	 800
{ PF, ST, JA, JA, PF, JA, JA, JA, JA, JA, TN, TN, ST, JA, TN }, 	 //	 789	 800
{ PF, TN, JA, SK, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, JA }, 	 //	 790	 800
{ JA, AC, JA, JA, JA, TN, SH, JA, JA, JA, AC, AC, JA, SH, JA }, 	 //	 791	 800
{ JA, LO, JA, SK, JA, TN, KN, JA, JA, JA, AC, KN, JA, JA, JA }, 	 //	 792	 800
{ JA, QN, JA, SK, SH, TN, SK, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 793	 800
{ JA, QN, QN, QN, KN, TN, SK, QN, QN, KN, AC, JA, SK, SK, SK }, 	 //	 794	 800
{ JA, SK, LO, SK, AC, TN, JA, JA, JA, AC, AC, JA, JA, JA, SK }, 	 //	 795	 800
{ JA, SK, LO, JA, KN, TN, JA, JA, JA, SK, AC, JA, JA, JA, QN }, 	 //	 796	 800
{ JA, SK, JA, ST, QN, TN, JA, JA, JA, QN, AC, JA, JA, TN, SH }, 	 //	 797	 800
{ JA, SK, JA, ST, ST, TN, JA, JA, JA, AC, AC, JA, JA, TN, KN }, 	 //	 798	 800
{ JA, SK, JA, JA, JA, TN, JA, JA, JA, JA, AC, JA, ST, SH, WN }, 	 //	 799	 800
{ JA, SK, JA, ST, SH, TN, JA, JA, JA, JA, AC, JA, ST, TN, JA }, 	 //	 800	 800
{ JA, SK, QN, SK, QN, TN, JA, SK, JA, SH, AC, JA, JA, JA, JA }, 	 //	 801	 800
{ JA, JA, TN, SK, SH, TN, JA, LO, JA, JA, AC, JA, JA, JA, JA }, 	 //	 802	 800
{ JA, JA, LO, SK, WN, TN, JA, JA, JA, TN, AC, JA, JA, JA, TN }, 	 //	 803	 800
{ JA, JA, LO, JA, KN, TN, JA, JA, JA, QN, AC, JA, JA, JA, PF }, 	 //	 804	 800
{ JA, JA, LO, JA, SK, TN, JA, JA, JA, KN, AC, JA, JA, JA, KN }, 	 //	 805	 800
{ JA, JA, JA, JA, TN, TN, JA, JA, JA, ST, AC, JA, ST, JA, AC }, 	 //	 806	 800
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, JA, ST, JA, AC }, 	 //	 807	 800
{ JA, JA, JA, JA, CR, TN, JA, JA, JA, QN, AC, JA, ST, SH, KN }, 	 //	 808	 800
{ JA, JA, JA, JA, SH, TN, JA, ST, JA, JA, AC, JA, AC, JA, JA }, 	 //	 809	 800
{ JA, JA, JA, JA, QN, TN, JA, TN, JA, SH, AC, JA, AC, SH, JA }, 	 //	 810	 800
{ JA, JA, TN, SK, JA, TN, JA, LO, JA, JA, AC, SH, JA, JA, JA }, 	 //	 811	 800
{ JA, JA, LO, JA, QN, TN, JA, JA, JA, PF, AC, SH, JA, JA, JA }, 	 //	 812	 800
{ JA, JA, LO, JA, PF, TN, JA, JA, JA, JA, AC, SH, JA, JA, TN }, 	 //	 813	 800
{ JA, JA, JA, JA, TN, TN, JA, JA, JA, TN, AC, SH, ST, JA, TN }, 	 //	 814	 800
{ JA, JA, JA, JA, ST, TN, JA, JA, JA, AC, AC, SH, ST, JA, KN }, 	 //	 815	 800
{ JA, JA, JA, ST, JA, TN, JA, JA, JA, JA, AC, SH, ST, TN, WN }, 	 //	 816	 800
{ JA, JA, JA, JA, JA, TN, JA, ST, JA, WN, AC, SH, AC, JA, TN }, 	 //	 817	 800
{ JA, JA, JA, JA, SH, TN, SH, JA, JA, JA, AC, TN, JA, SH, JA }, 	 //	 818	 800
{ JA, ST, LO, JA, SH, TN, JA, JA, JA, JA, AC, TN, JA, SH, JA }, 	 //	 819	 800
{ JA, ST, JA, SK, LO, TN, JA, JA, JA, AC, AC, TN, JA, JA, AC }, 	 //	 820	 800
{ JA, ST, JA, JA, WN, TN, JA, JA, JA, TN, AC, TN, JA, SH, TN }, 	 //	 821	 800
{ JA, ST, JA, JA, TN, TN, JA, JA, JA, TN, AC, TN, JA, SH, TN }, 	 //	 822	 800
{ JA, ST, JA, ST, KN, TN, JA, JA, JA, SK, AC, TN, JA, TN, QN }, 	 //	 823	 800
{ JA, ST, JA, ST, AC, TN, JA, JA, JA, KN, AC, TN, JA, TN, QN }, 	 //	 824	 800
{ JA, ST, JA, ST, SK, TN, JA, JA, JA, KN, AC, TN, JA, TN, KN }, 	 //	 825	 800
{ JA, JA, JA, JA, SH, TN, TN, JA, JA, JA, AC, AC, ST, JA, JA }, 	 //	 826	 800
{ TN, KN, JA, SK, JA, AC, KN, JA, JA, JA, AC, ST, JA, JA, JA }, 	 //	 827	 800
{ TN, QN, QN, QN, KN, AC, SK, QN, SK, KN, AC, JA, SK, JA, SK }, 	 //	 828	 800
{ TN, SK, JA, SK, QN, AC, JA, JA, JA, QN, AC, JA, JA, JA, QN }, 	 //	 829	 800
{ TN, JA, JA, SK, TN, AC, JA, JA, JA, TN, AC, JA, JA, JA, ST }, 	 //	 830	 800
{ TN, JA, JA, SK, AC, AC, JA, JA, JA, SK, AC, JA, JA, JA, KN }, 	 //	 831	 800
{ TN, JA, JA, ST, JA, AC, JA, JA, JA, JA, AC, JA, ST, TN, JA }, 	 //	 832	 800
{ TN, JA, JA, JA, ST, AC, JA, JA, JA, AC, AC, SH, JA, JA, KN }, 	 //	 833	 800
{ TN, JA, JA, JA, KN, AC, JA, JA, JA, KN, AC, SH, JA, JA, CR }, 	 //	 834	 800
{ TN, JA, JA, JA, AC, AC, JA, JA, JA, AC, AC, SH, JA, SH, AC }, 	 //	 835	 800
{ TN, JA, JA, JA, JA, AC, JA, ST, JA, JA, AC, SH, AC, SH, JA }, 	 //	 836	 800
{ TN, QN, LO, JA, JA, AC, ST, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 837	 800
{ TN, QN, JA, JA, SH, AC, ST, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 838	 800
{ TN, ST, JA, ST, PF, AC, JA, JA, JA, JA, AC, TN, JA, TN, TN }, 	 //	 839	 800
{ TN, JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, JA, JA, WN }, 	 //	 840	 800
{ TN, QN, JA, JA, JA, AC, KN, JA, JA, JA, AC, AC, JA, SH, JA }, 	 //	 841	 800
{ AC, SH, JA, SK, JA, AC, AC, JA, JA, JA, AC, AC, JA, JA, JA }, 	 //	 842	 800
{ AC, AC, JA, JA, JA, AC, LO, JA, JA, JA, AC, KN, JA, SH, JA }, 	 //	 843	 800
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, QN, AC, JA, JA, JA, QN }, 	 //	 844	 800
{ AC, SK, JA, JA, AC, AC, JA, JA, JA, KN, AC, JA, JA, JA, QN }, 	 //	 845	 800
{ AC, SK, JA, JA, KN, AC, JA, JA, JA, KN, AC, JA, JA, JA, CR }, 	 //	 846	 800
{ AC, SK, JA, JA, SH, AC, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 847	 800
{ AC, JA, JA, SK, AC, AC, JA, JA, JA, SK, AC, JA, JA, JA, KN }, 	 //	 848	 800
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, PF, AC, JA, ST, SH, JA }, 	 //	 849	 800
{ AC, JA, JA, JA, AC, AC, JA, JA, JA, AC, AC, SH, JA, JA, AC }, 	 //	 850	 800
{ AC, JA, JA, JA, AC, AC, JA, JA, JA, AC, AC, SH, JA, JA, SK }, 	 //	 851	 800
{ AC, JA, JA, JA, CR, AC, JA, JA, JA, QN, AC, SH, JA, JA, KN }, 	 //	 852	 800
{ AC, JA, JA, JA, TN, AC, JA, JA, JA, AC, AC, SH, JA, SH, AC }, 	 //	 853	 800
{ AC, TN, TN, TN, TN, AC, TN, TN, TN, TN, AC, WN, TN, WN, TN }, 	 //	 854	 800
{ AC, ST, JA, JA, QN, AC, JA, JA, JA, PF, AC, TN, JA, SH, JA }, 	 //	 855	 800
{ AC, ST, JA, JA, SH, AC, JA, JA, JA, JA, AC, TN, ST, SH, JA }, 	 //	 856	 800
{ AC, AC, JA, SK, JA, AC, AC, JA, JA, JA, AC, PF, JA, JA, JA }, 	 //	 857	 800
{ AC, QN, QN, QN, PF, AC, QN, QN, SK, JA, SK, SK, SK, JA, TN }, 	 //	 858	 800
{ AC, QN, QN, QN, KN, AC, QN, SK, SK, SK, SK, SK, JA, JA, QN }, 	 //	 859	 800
{ AC, QN, QN, QN, KN, AC, SK, QN, SK, KN, SK, JA, SK, JA, CR }, 	 //	 860	 800
{ AC, SK, LO, ST, JA, AC, JA, JA, JA, JA, SK, JA, JA, TN, JA }, 	 //	 861	 800
{ AC, SK, JA, SK, KN, AC, JA, JA, JA, KN, SK, JA, JA, JA, KN }, 	 //	 862	 800
{ AC, SK, JA, SK, AC, AC, JA, JA, JA, AC, SK, JA, JA, JA, SK }, 	 //	 863	 800
{ AC, SK, JA, JA, ST, AC, JA, JA, JA, AC, SK, JA, JA, JA, KN }, 	 //	 864	 800
{ AC, SK, JA, JA, AC, AC, JA, JA, JA, AC, SK, JA, JA, JA, SK }, 	 //	 865	 800
{ AC, SK, JA, ST, PF, AC, JA, JA, JA, JA, SK, JA, JA, TN, TN }, 	 //	 866	 800
{ AC, JA, TN, SK, JA, AC, JA, LO, JA, JA, SK, JA, JA, JA, JA }, 	 //	 867	 800
{ AC, JA, JA, JA, AC, AC, JA, JA, JA, LO, SK, JA, JA, SH, AC }, 	 //	 868	 800
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, KN, SK, JA, JA, SH, AC }, 	 //	 869	 800
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, TN, SK, JA, ST, JA, AC }, 	 //	 870	 800
{ AC, JA, JA, JA, KN, AC, JA, JA, JA, SK, SK, SH, JA, JA, QN }, 	 //	 871	 800
{ AC, SH, TN, SH, TN, AC, TN, TN, TN, TN, SK, TN, TN, TN, TN }, 	 //	 872	 800
{ AC, KN, QN, QN, QN, AC, SK, SK, SK, KN, SK, QN, JA, JA, AC }, 	 //	 873	 800
{ AC, SK, JA, SK, JA, AC, QN, JA, JA, JA, SK, KN, JA, JA, JA }, 	 //	 874	 800
{ AC, KN, JA, JA, JA, AC, AC, JA, JA, JA, SK, SH, JA, SH, JA }, 	 //	 875	 800
{ AC, QN, QN, QN, SK, SK, SK, QN, SK, KN, KN, JA, SK, JA, KN }, 	 //	 876	 800
{ AC, QN, QN, QN, CR, SK, SK, QN, SK, QN, KN, JA, SK, JA, KN }, 	 //	 877	 800
{ AC, SK, LO, JA, QN, SK, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 878	 800
{ AC, SK, LO, JA, JA, SK, JA, JA, JA, TN, KN, JA, JA, JA, AC }, 	 //	 879	 800
{ AC, SK, JA, SK, KN, SK, JA, JA, JA, KN, KN, JA, JA, JA, KN }, 	 //	 880	 800
{ AC, SK, JA, ST, QN, SK, JA, JA, JA, PF, KN, JA, JA, TN, JA }, 	 //	 881	 800
{ AC, JA, LO, JA, QN, SK, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 882	 800
{ AC, JA, JA, JA, KN, SK, JA, JA, JA, KN, KN, JA, JA, SH, KN }, 	 //	 883	 800
{ AC, JA, LO, JA, SH, SK, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 884	 800
{ AC, JA, JA, JA, LO, SK, JA, JA, JA, AC, KN, SH, JA, JA, AC }, 	 //	 885	 800
{ AC, JA, JA, JA, AC, SK, JA, JA, JA, LO, KN, SH, JA, SH, AC }, 	 //	 886	 800
{ AC, JA, JA, JA, QN, SK, JA, JA, JA, KN, KN, SH, JA, SH, AC }, 	 //	 887	 800
{ AC, TN, TN, SH, TN, SK, TN, TN, TN, TN, KN, TN, TN, TN, TN }, 	 //	 888	 800
{ AC, ST, JA, JA, PF, SK, JA, JA, JA, JA, KN, TN, JA, SH, TN }, 	 //	 889	 800
{ AC, KN, QN, QN, QN, SK, SK, QN, SK, KN, KN, QN, SK, JA, AC }, 	 //	 890	 800
{ SK, QN, QN, QN, SK, KN, QN, QN, SK, KN, KN, SK, SK, JA, KN }, 	 //	 891	 800
{ SK, QN, QN, QN, AC, KN, SK, QN, QN, SK, KN, JA, SK, SK, KN }, 	 //	 892	 800
{ SK, JA, LO, SK, QN, KN, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 893	 800
{ SK, JA, JA, SK, KN, KN, JA, JA, JA, KN, KN, JA, JA, JA, KN }, 	 //	 894	 800
{ SK, JA, JA, JA, KN, KN, JA, JA, JA, KN, KN, JA, JA, SH, SK }, 	 //	 895	 800
{ SK, JA, JA, ST, SH, KN, JA, JA, JA, JA, KN, JA, ST, TN, JA }, 	 //	 896	 800
{ SK, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN, SH, JA, JA, CR }, 	 //	 897	 800
{ SK, JA, JA, JA, AC, KN, JA, JA, JA, AC, KN, SH, JA, JA, AC }, 	 //	 898	 800
{ SK, JA, JA, JA, CR, KN, JA, JA, JA, QN, KN, SH, JA, JA, KN }, 	 //	 899	 800
{ SK, JA, JA, JA, AC, KN, JA, JA, JA, LO, KN, SH, JA, SH, AC }, 	 //	 900	 800
{ SK, JA, JA, JA, TN, KN, JA, JA, JA, ST, KN, SH, JA, SH, AC }, 	 //	 901	 800
{ SK, AC, JA, JA, JA, KN, KN, JA, JA, JA, KN, QN, JA, SH, JA }, 	 //	 902	 800
{ SK, ST, LO, JA, SH, KN, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 903	 800
{ SK, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, JA, JA, WN }, 	 //	 904	 800
{ SK, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, ST, JA, JA }, 	 //	 905	 800
{ SK, AC, JA, JA, JA, KN, AC, JA, JA, JA, KN, AC, JA, SH, JA }, 	 //	 906	 800
{ SK, AC, JA, JA, JA, KN, AC, JA, JA, JA, KN, PF, JA, SH, JA }, 	 //	 907	 800
{ SK, PF, JA, SK, JA, KN, KN, JA, JA, JA, KN, KN, JA, JA, JA }, 	 //	 908	 800
{ KN, AC, JA, SK, JA, KN, AC, JA, JA, JA, KN, AC, JA, JA, JA }, 	 //	 909	 800
{ KN, SK, JA, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, JA, QN }, 	 //	 910	 800
{ KN, SK, JA, SK, AC, KN, JA, JA, JA, KN, KN, JA, JA, JA, QN }, 	 //	 911	 800
{ KN, SK, JA, SK, TN, KN, JA, JA, JA, AC, KN, JA, JA, JA, AC }, 	 //	 912	 800
{ KN, SK, JA, JA, KN, KN, JA, JA, JA, KN, KN, JA, JA, JA, SK }, 	 //	 913	 800
{ KN, JA, JA, SK, KN, KN, JA, JA, JA, KN, KN, JA, JA, JA, KN }, 	 //	 914	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, QN, KN, JA, JA, SH, PF }, 	 //	 915	 800
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, KN, KN, JA, JA, SH, AC }, 	 //	 916	 800
{ KN, JA, JA, ST, JA, KN, JA, JA, JA, TN, KN, JA, JA, TN, AC }, 	 //	 917	 800
{ KN, JA, JA, SK, JA, KN, JA, JA, JA, TN, KN, SH, JA, JA, AC }, 	 //	 918	 800
{ KN, JA, JA, JA, LO, KN, JA, JA, JA, AC, KN, SH, JA, JA, AC }, 	 //	 919	 800
{ KN, JA, JA, JA, TN, KN, JA, JA, JA, ST, KN, SH, JA, SH, AC }, 	 //	 920	 800
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, SH, ST, JA, AC }, 	 //	 921	 800
{ KN, ST, LO, SK, SH, KN, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 922	 800
{ KN, ST, JA, ST, JA, KN, JA, JA, JA, WN, KN, TN, JA, TN, TN }, 	 //	 923	 800
{ KN, ST, JA, ST, SH, KN, JA, JA, JA, JA, KN, TN, ST, TN, JA }, 	 //	 924	 800
{ KN, AC, JA, SK, JA, KN, AC, JA, JA, JA, WN, LO, JA, JA, JA }, 	 //	 925	 800
{ KN, AC, JA, SK, JA, KN, LO, JA, JA, JA, WN, KN, JA, JA, JA }, 	 //	 926	 800
{ KN, KN, JA, JA, JA, KN, KN, JA, JA, JA, WN, ST, JA, SH, JA }, 	 //	 927	 800
{ KN, QN, JA, JA, SH, KN, SK, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 928	 800
{ KN, SK, JA, JA, QN, KN, JA, JA, JA, QN, WN, JA, JA, JA, QN }, 	 //	 929	 800
{ KN, SK, JA, JA, QN, KN, JA, JA, JA, KN, WN, JA, JA, JA, AC }, 	 //	 930	 800
{ KN, JA, LO, JA, JA, KN, JA, JA, JA, JA, WN, JA, JA, SH, WN }, 	 //	 931	 800
{ KN, JA, JA, JA, AC, KN, JA, JA, JA, AC, WN, JA, JA, SH, SK }, 	 //	 932	 800
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, PF, WN, JA, ST, SH, JA }, 	 //	 933	 800
{ KN, JA, LO, ST, JA, KN, JA, JA, JA, JA, WN, SH, JA, TN, JA }, 	 //	 934	 800
{ KN, JA, JA, JA, SK, KN, JA, JA, JA, QN, WN, SH, JA, JA, QN }, 	 //	 935	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, QN, WN, SH, JA, JA, PF }, 	 //	 936	 800
{ KN, JA, JA, JA, AC, KN, JA, JA, JA, AC, WN, SH, JA, JA, AC }, 	 //	 937	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, KN, WN, SH, JA, JA, CR }, 	 //	 938	 800
{ KN, JA, JA, JA, CR, KN, JA, JA, JA, QN, WN, SH, JA, JA, KN }, 	 //	 939	 800
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, KN, WN, SH, JA, JA, AC }, 	 //	 940	 800
{ KN, JA, JA, JA, KN, KN, JA, JA, JA, KN, WN, SH, JA, SH, CR }, 	 //	 941	 800
{ KN, AC, JA, JA, JA, KN, KN, JA, JA, JA, WN, QN, JA, SH, JA }, 	 //	 942	 800
{ KN, QN, JA, JA, SH, KN, ST, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 943	 800
{ KN, ST, JA, ST, QN, KN, JA, JA, JA, SH, WN, TN, JA, TN, JA }, 	 //	 944	 800
{ KN, ST, JA, ST, PF, KN, JA, JA, JA, JA, WN, TN, JA, TN, TN }, 	 //	 945	 800
{ KN, PF, JA, SK, JA, KN, KN, JA, JA, JA, WN, KN, JA, JA, JA }, 	 //	 946	 800
{ KN, SK, JA, JA, JA, KN, QN, JA, JA, JA, WN, KN, JA, SH, JA }, 	 //	 947	 800
{ KN, KN, JA, JA, JA, WN, KN, JA, JA, JA, QN, ST, JA, SH, JA }, 	 //	 948	 800
{ KN, QN, JA, SK, JA, WN, QN, JA, JA, JA, QN, SK, JA, JA, JA }, 	 //	 949	 800
{ KN, QN, QN, QN, AC, WN, SK, QN, SK, AC, QN, JA, SK, JA, SK }, 	 //	 950	 800
{ KN, SK, JA, JA, AC, WN, JA, JA, JA, LO, QN, JA, JA, JA, AC }, 	 //	 951	 800
{ KN, SK, JA, SK, JA, WN, JA, JA, JA, JA, QN, JA, ST, JA, JA }, 	 //	 952	 800
{ KN, SK, JA, JA, SH, WN, JA, JA, JA, JA, QN, JA, ST, SH, JA }, 	 //	 953	 800
{ KN, JA, LO, SK, QN, WN, JA, JA, JA, SH, QN, JA, JA, JA, JA }, 	 //	 954	 800
{ KN, JA, JA, SK, AC, WN, JA, JA, JA, LO, QN, JA, JA, JA, AC }, 	 //	 955	 800
{ KN, JA, JA, SK, WN, WN, JA, JA, JA, TN, QN, JA, JA, JA, TN }, 	 //	 956	 800
{ KN, JA, JA, JA, TN, WN, JA, JA, JA, TN, QN, JA, JA, SH, ST }, 	 //	 957	 800
{ KN, JA, JA, SK, SH, WN, JA, JA, JA, JA, QN, JA, ST, JA, JA }, 	 //	 958	 800
{ KN, JA, JA, JA, CR, WN, JA, JA, JA, KN, QN, SH, JA, JA, KN }, 	 //	 959	 800
{ KN, JA, JA, JA, TN, WN, JA, JA, JA, TN, QN, SH, JA, JA, TN }, 	 //	 960	 800
{ KN, JA, JA, JA, LO, WN, JA, JA, JA, AC, QN, SH, JA, SH, AC }, 	 //	 961	 800
{ KN, JA, JA, JA, KN, WN, JA, JA, JA, AC, QN, SH, JA, SH, LO }, 	 //	 962	 800
{ KN, JA, JA, ST, JA, WN, JA, JA, JA, WN, QN, SH, JA, TN, TN }, 	 //	 963	 800
{ KN, JA, JA, ST, QN, WN, JA, JA, JA, PF, QN, SH, JA, TN, JA }, 	 //	 964	 800
{ KN, JA, JA, JA, JA, WN, JA, JA, JA, WN, QN, SH, ST, JA, TN }, 	 //	 965	 800
{ KN, JA, JA, JA, QN, WN, JA, JA, JA, PF, QN, SH, ST, JA, JA }, 	 //	 966	 800
{ KN, JA, JA, JA, QN, WN, JA, JA, JA, PF, QN, SH, ST, SH, JA }, 	 //	 967	 800
{ KN, TN, TN, TN, TN, WN, TN, TN, TN, TN, QN, WN, TN, WN, TN }, 	 //	 968	 800
{ KN, QN, JA, JA, JA, WN, ST, JA, JA, JA, QN, JA, JA, JA, WN }, 	 //	 969	 800
{ KN, ST, LO, SK, JA, WN, JA, JA, JA, JA, QN, TN, JA, JA, WN }, 	 //	 970	 800
{ KN, AC, JA, JA, JA, WN, PF, JA, JA, JA, QN, KN, JA, SH, JA }, 	 //	 971	 800
{ KN, KN, JA, SK, JA, WN, KN, JA, JA, JA, QN, KN, JA, JA, JA }, 	 //	 972	 800
{ WN, AC, JA, SK, JA, QN, SH, JA, JA, JA, KN, AC, JA, JA, JA }, 	 //	 973	 800
{ WN, AC, JA, JA, JA, QN, LO, JA, JA, JA, KN, KN, JA, SH, JA }, 	 //	 974	 800
{ WN, KN, JA, SK, JA, QN, KN, JA, JA, JA, KN, ST, JA, JA, JA }, 	 //	 975	 800
{ WN, SK, TN, SK, JA, QN, JA, LO, JA, JA, KN, JA, JA, JA, JA }, 	 //	 976	 800
{ WN, SK, JA, SK, QN, QN, JA, JA, JA, QN, KN, JA, JA, JA, QN }, 	 //	 977	 800
{ WN, SK, JA, JA, QN, QN, JA, JA, JA, QN, KN, JA, JA, JA, QN }, 	 //	 978	 800
{ WN, SK, JA, SK, SH, QN, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 979	 800
{ WN, SK, JA, JA, JA, QN, JA, JA, JA, JA, KN, JA, ST, JA, WN }, 	 //	 980	 800
{ WN, JA, LO, ST, JA, QN, JA, JA, JA, JA, KN, JA, JA, TN, JA }, 	 //	 981	 800
{ WN, JA, JA, JA, QN, QN, JA, JA, JA, QN, KN, JA, JA, SH, QN }, 	 //	 982	 800
{ WN, JA, JA, JA, AC, QN, JA, JA, JA, AC, KN, SH, JA, JA, AC }, 	 //	 983	 800
{ WN, JA, JA, JA, AC, QN, JA, JA, JA, AC, KN, SH, JA, JA, CR }, 	 //	 984	 800
{ WN, JA, JA, JA, PF, QN, JA, JA, JA, JA, KN, SH, ST, JA, TN }, 	 //	 985	 800
{ WN, JA, JA, JA, QN, QN, JA, JA, JA, SH, KN, SH, ST, SH, JA }, 	 //	 986	 800
{ WN, JA, JA, JA, QN, QN, JA, JA, JA, PF, KN, SH, ST, SH, JA }, 	 //	 987	 800
{ WN, TN, TN, TN, WN, QN, TN, TN, TN, TN, KN, TN, TN, TN, TN }, 	 //	 988	 800
{ WN, ST, LO, ST, JA, QN, JA, JA, JA, JA, KN, TN, JA, TN, WN }, 	 //	 989	 800
{ QN, AC, JA, SK, JA, KN, AC, JA, JA, JA, AC, AC, JA, JA, JA }, 	 //	 990	 800
{ QN, QN, QN, KN, KN, KN, SK, SK, SK, KN, AC, JA, JA, QN, SK }, 	 //	 991	 800
{ QN, SK, TN, JA, JA, KN, JA, LO, JA, JA, AC, JA, JA, JA, JA }, 	 //	 992	 800
{ QN, SK, JA, ST, QN, KN, JA, JA, JA, PF, AC, JA, JA, TN, JA }, 	 //	 993	 800
{ QN, JA, JA, SK, AC, KN, JA, JA, JA, LO, AC, JA, JA, JA, AC }, 	 //	 994	 800
{ QN, JA, JA, SK, QN, KN, JA, JA, JA, QN, AC, JA, JA, JA, SH }, 	 //	 995	 800
{ QN, JA, JA, SK, QN, KN, JA, JA, JA, KN, AC, JA, JA, JA, AC }, 	 //	 996	 800
{ QN, JA, JA, JA, KN, KN, JA, JA, JA, KN, AC, JA, JA, SH, KN }, 	 //	 997	 800
{ QN, JA, JA, JA, TN, KN, JA, JA, JA, TN, AC, JA, JA, SH, ST }, 	 //	 998	 800
{ QN, JA, JA, JA, AC, KN, JA, JA, JA, SK, AC, JA, JA, SH, KN }, 	 //	 999	 800
{ QN, JA, JA, JA, JA, KN, JA, JA, JA, TN, AC, JA, ST, SH, AC }};	 //	 1000	 800
