#include "ReelDefine.h"

unsigned char L5_Outcome_1200[1000][15]={	 //	 0	 1200
{ AC, SK, JA, JA, QN, LO, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 1	 1200
{ AC, SK, JA, JA, JA, LO, JA, JA, JA, WN, AC, JA, JA, JA, TN }, 	 //	 2	 1200
{ AC, SK, JA, JA, JA, LO, JA, JA, JA, TN, AC, JA, JA, JA, AC }, 	 //	 3	 1200
{ AC, JA, LO, SK, JA, LO, JA, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 4	 1200
{ AC, JA, JA, SK, QN, LO, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 5	 1200
{ AC, JA, JA, SK, QN, LO, JA, JA, JA, PF, AC, JA, JA, JA, JA }, 	 //	 6	 1200
{ AC, JA, JA, ST, JA, LO, JA, JA, JA, JA, AC, JA, JA, TN, JA }, 	 //	 7	 1200
{ AC, JA, JA, JA, JA, LO, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 8	 1200
{ AC, JA, JA, JA, JA, LO, JA, JA, JA, TN, AC, SH, JA, JA, AC }, 	 //	 9	 1200
{ AC, QN, QN, QN, QN, LO, ST, SK, ST, QN, AC, JA, JA, JA, SH }, 	 //	 10	 1200
{ LO, QN, QN, QN, QN, AC, QN, SK, ST, SH, AC, SK, JA, JA, JA }, 	 //	 11	 1200
{ LO, SK, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, JA, SH, WN }, 	 //	 12	 1200
{ LO, JA, JA, JA, PF, AC, JA, JA, JA, JA, AC, JA, JA, JA, TN }, 	 //	 13	 1200
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, SH, AC }, 	 //	 14	 1200
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, ST, JA, JA }, 	 //	 15	 1200
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 16	 1200
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, WN, AC, SH, JA, JA, TN }, 	 //	 17	 1200
{ LO, JA, JA, JA, JA, AC, JA, JA, JA, TN, AC, SH, JA, JA, AC }, 	 //	 18	 1200
{ LO, JA, JA, JA, JA, AC, SH, JA, JA, JA, AC, TN, JA, JA, JA }, 	 //	 19	 1200
{ LO, QN, QN, QN, QN, AC, KN, SK, ST, PF, AC, AC, JA, JA, JA }, 	 //	 20	 1200
{ AC, QN, JA, JA, JA, AC, SK, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 21	 1200
{ AC, SK, JA, SK, JA, AC, JA, JA, JA, JA, AC, JA, JA, JA, WN }, 	 //	 22	 1200
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 23	 1200
{ AC, SK, JA, JA, JA, AC, JA, JA, JA, WN, AC, JA, JA, JA, TN }, 	 //	 24	 1200
{ AC, JA, JA, JA, SH, AC, JA, JA, JA, JA, AC, JA, JA, SH, JA }, 	 //	 25	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, AC, JA, JA, SH, TN }, 	 //	 26	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 27	 1200
{ AC, JA, JA, SK, SH, AC, JA, JA, JA, JA, AC, SH, JA, JA, JA }, 	 //	 28	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, AC, SH, JA, JA, TN }, 	 //	 29	 1200
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, PF, AC, SH, JA, JA, JA }, 	 //	 30	 1200
{ AC, JA, JA, JA, SH, AC, JA, JA, JA, JA, AC, SH, JA, SH, JA }, 	 //	 31	 1200
{ AC, ST, JA, JA, SH, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA }, 	 //	 32	 1200
{ AC, JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, JA, JA, JA }, 	 //	 33	 1200
{ AC, QN, QN, QN, QN, AC, QN, SK, ST, PF, ST, QN, JA, JA, JA }, 	 //	 34	 1200
{ AC, QN, QN, QN, QN, AC, QN, SK, ST, SH, ST, SK, JA, JA, JA }, 	 //	 35	 1200
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, SH, ST, JA, JA, JA, JA }, 	 //	 36	 1200
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, PF, ST, JA, JA, JA, JA }, 	 //	 37	 1200
{ AC, SK, JA, JA, JA, AC, JA, JA, JA, JA, ST, JA, JA, SH, WN }, 	 //	 38	 1200
{ AC, JA, LO, JA, JA, AC, JA, JA, JA, JA, ST, JA, JA, JA, JA }, 	 //	 39	 1200
{ AC, JA, JA, SK, JA, AC, JA, JA, JA, JA, ST, JA, JA, JA, WN }, 	 //	 40	 1200
{ AC, JA, JA, JA, SH, AC, JA, JA, JA, JA, ST, JA, JA, SH, JA }, 	 //	 41	 1200
{ AC, JA, JA, SK, SH, AC, JA, JA, JA, JA, ST, SH, JA, JA, JA }, 	 //	 42	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, ST, SH, JA, JA, TN }, 	 //	 43	 1200
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, PF, ST, SH, JA, JA, JA }, 	 //	 44	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, ST, SH, ST, SH, JA }, 	 //	 45	 1200
{ AC, QN, JA, JA, JA, AC, ST, JA, JA, JA, ST, JA, JA, JA, JA }, 	 //	 46	 1200
{ AC, ST, JA, ST, JA, AC, JA, JA, JA, JA, ST, TN, JA, TN, JA }, 	 //	 47	 1200
{ AC, KN, KN, TN, TN, ST, KN, WN, TN, TN, KN, ST, TN, TN, TN }, 	 //	 48	 1200
{ AC, QN, QN, QN, QN, ST, QN, SK, ST, PF, KN, SK, JA, JA, JA }, 	 //	 49	 1200
{ AC, SK, LO, JA, JA, ST, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 50	 1200
{ AC, SK, JA, SK, JA, ST, JA, JA, JA, JA, KN, JA, JA, JA, WN }, 	 //	 51	 1200
{ AC, SK, JA, SK, QN, ST, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 52	 1200
{ AC, JA, JA, SK, JA, ST, JA, JA, JA, JA, KN, JA, JA, JA, WN }, 	 //	 53	 1200
{ AC, JA, JA, JA, SH, ST, JA, JA, JA, JA, KN, JA, JA, SH, JA }, 	 //	 54	 1200
{ AC, JA, JA, JA, JA, ST, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 55	 1200
{ AC, JA, JA, JA, JA, ST, JA, JA, JA, TN, KN, SH, JA, SH, AC }, 	 //	 56	 1200
{ AC, JA, JA, ST, JA, ST, JA, JA, JA, JA, KN, SH, JA, TN, JA }, 	 //	 57	 1200
{ AC, JA, JA, JA, JA, ST, JA, JA, JA, JA, KN, SH, ST, JA, JA }, 	 //	 58	 1200
{ AC, JA, JA, JA, JA, ST, JA, JA, JA, JA, KN, SH, ST, SH, JA }, 	 //	 59	 1200
{ AC, JA, JA, JA, JA, ST, SH, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 60	 1200
{ AC, AC, KN, SH, TN, ST, KN, WN, TN, TN, KN, QN, TN, TN, TN }, 	 //	 61	 1200
{ AC, ST, JA, SK, SH, ST, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 62	 1200
{ AC, ST, JA, ST, JA, ST, JA, JA, JA, JA, KN, TN, JA, TN, JA }, 	 //	 63	 1200
{ AC, PF, KN, TN, TN, ST, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 64	 1200
{ AC, KN, KN, SH, TN, ST, KN, WN, TN, TN, KN, SK, TN, TN, TN }, 	 //	 65	 1200
{ AC, QN, KN, SH, TN, ST, KN, WN, TN, TN, KN, AC, TN, TN, TN }, 	 //	 66	 1200
{ AC, QN, KN, TN, TN, ST, KN, WN, TN, TN, KN, AC, TN, TN, TN }, 	 //	 67	 1200
{ AC, QN, QN, QN, QN, ST, KN, SK, ST, SH, KN, AC, JA, JA, JA }, 	 //	 68	 1200
{ ST, LO, KN, TN, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 69	 1200
{ ST, KN, KN, TN, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 70	 1200
{ ST, QN, QN, QN, QN, KN, QN, SK, ST, SH, KN, QN, JA, JA, JA }, 	 //	 71	 1200
{ ST, QN, QN, QN, QN, KN, QN, SK, ST, PF, KN, QN, JA, JA, JA }, 	 //	 72	 1200
{ ST, QN, QN, QN, QN, KN, QN, SK, ST, SH, KN, SK, JA, JA, JA }, 	 //	 73	 1200
{ ST, QN, QN, QN, QN, KN, QN, SK, ST, PF, KN, SK, JA, JA, JA }, 	 //	 74	 1200
{ ST, QN, JA, JA, JA, KN, SK, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 75	 1200
{ ST, SK, LO, JA, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 76	 1200
{ ST, SK, JA, JA, QN, KN, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 77	 1200
{ ST, JA, JA, SK, QN, KN, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 78	 1200
{ ST, JA, JA, JA, JA, KN, JA, JA, JA, WN, KN, JA, JA, SH, TN }, 	 //	 79	 1200
{ ST, JA, JA, SK, SH, KN, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 80	 1200
{ ST, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, SH, JA, JA, AC }, 	 //	 81	 1200
{ ST, JA, JA, JA, SH, KN, JA, JA, JA, JA, KN, SH, JA, SH, JA }, 	 //	 82	 1200
{ ST, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, SH, JA, SH, AC }, 	 //	 83	 1200
{ ST, QN, QN, QN, QN, KN, ST, SK, ST, QN, KN, JA, JA, JA, SH }, 	 //	 84	 1200
{ ST, ST, JA, ST, JA, KN, JA, JA, JA, JA, KN, TN, JA, TN, JA }, 	 //	 85	 1200
{ ST, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, JA, JA, JA }, 	 //	 86	 1200
{ ST, KN, KN, TN, TN, KN, KN, WN, TN, TN, KN, SK, TN, TN, TN }, 	 //	 87	 1200
{ ST, QN, KN, TN, TN, KN, KN, WN, TN, TN, KN, AC, TN, TN, TN }, 	 //	 88	 1200
{ ST, QN, QN, QN, QN, KN, KN, SK, ST, PF, KN, AC, JA, JA, JA }, 	 //	 89	 1200
{ KN, KN, KN, SH, TN, KN, ST, WN, TN, TN, KN, QN, TN, TN, TN }, 	 //	 90	 1200
{ KN, KN, KN, TN, TN, KN, ST, WN, TN, TN, KN, QN, TN, TN, TN }, 	 //	 91	 1200
{ KN, SK, JA, SK, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, WN }, 	 //	 92	 1200
{ KN, SK, JA, JA, JA, KN, JA, JA, JA, TN, KN, JA, JA, JA, AC }, 	 //	 93	 1200
{ KN, JA, LO, SK, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 94	 1200
{ KN, JA, JA, SK, QN, KN, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 95	 1200
{ KN, JA, JA, JA, PF, KN, JA, JA, JA, JA, KN, JA, JA, JA, TN }, 	 //	 96	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, KN, JA, JA, SH, TN }, 	 //	 97	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 98	 1200
{ KN, JA, JA, JA, JA, KN, SH, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 99	 1200
{ KN, QN, QN, QN, QN, KN, ST, SK, ST, QN, KN, JA, JA, JA, QN }, 	 //	 100	 1200
{ KN, QN, QN, QN, QN, KN, ST, SK, ST, QN, KN, JA, JA, JA, SH }, 	 //	 101	 1200
{ KN, QN, QN, QN, QN, KN, ST, SK, ST, KN, KN, JA, JA, JA, AC }, 	 //	 102	 1200
{ KN, PF, KN, SH, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 103	 1200
{ KN, PF, KN, TN, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 104	 1200
{ KN, KN, KN, TN, TN, KN, SK, WN, TN, TN, KN, QN, TN, TN, TN }, 	 //	 105	 1200
{ KN, KN, KN, SH, TN, KN, KN, WN, TN, TN, SK, KN, TN, TN, TN }, 	 //	 106	 1200
{ KN, KN, KN, SH, TN, KN, ST, WN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 107	 1200
{ KN, QN, QN, QN, QN, KN, QN, SK, ST, PF, SK, QN, JA, JA, JA }, 	 //	 108	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, SK, JA, JA, SH, TN }, 	 //	 109	 1200
{ KN, JA, JA, ST, JA, KN, JA, JA, JA, JA, SK, JA, JA, TN, JA }, 	 //	 110	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, SK, JA, ST, SH, JA }, 	 //	 111	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, SK, SH, JA, JA, TN }, 	 //	 112	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, SK, SH, JA, SH, AC }, 	 //	 113	 1200
{ KN, KN, KN, TN, TN, KN, QN, WN, TN, TN, SK, ST, TN, TN, TN }, 	 //	 114	 1200
{ KN, KN, KN, SH, TN, KN, KN, WN, TN, TN, SK, KN, TN, TN, TN }, 	 //	 115	 1200
{ KN, KN, KN, SH, TN, SK, KN, WN, TN, TN, QN, KN, TN, TN, TN }, 	 //	 116	 1200
{ KN, QN, QN, QN, SH, SK, QN, SK, ST, JA, QN, QN, JA, JA, JA }, 	 //	 117	 1200
{ KN, QN, QN, QN, SH, SK, QN, SK, ST, JA, QN, SK, JA, JA, JA }, 	 //	 118	 1200
{ KN, SK, LO, SK, JA, SK, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 119	 1200
{ KN, SK, JA, SK, QN, SK, JA, JA, JA, PF, QN, JA, JA, JA, JA }, 	 //	 120	 1200
{ KN, SK, JA, JA, QN, SK, JA, JA, JA, SH, QN, JA, JA, JA, JA }, 	 //	 121	 1200
{ KN, SK, JA, JA, JA, SK, JA, JA, JA, JA, QN, JA, JA, SH, WN }, 	 //	 122	 1200
{ KN, JA, LO, SK, JA, SK, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 123	 1200
{ KN, JA, LO, JA, JA, SK, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 124	 1200
{ KN, JA, JA, SK, QN, SK, JA, JA, JA, SH, QN, JA, JA, JA, JA }, 	 //	 125	 1200
{ KN, JA, JA, SK, QN, SK, JA, JA, JA, PF, QN, JA, JA, JA, JA }, 	 //	 126	 1200
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, JA, QN, JA, ST, JA, JA }, 	 //	 127	 1200
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, JA, QN, JA, ST, SH, JA }, 	 //	 128	 1200
{ KN, JA, JA, SK, SH, SK, JA, JA, JA, JA, QN, SH, JA, JA, JA }, 	 //	 129	 1200
{ KN, JA, JA, JA, QN, SK, JA, JA, JA, SH, QN, SH, JA, JA, JA }, 	 //	 130	 1200
{ KN, JA, JA, JA, QN, SK, JA, JA, JA, PF, QN, SH, JA, JA, JA }, 	 //	 131	 1200
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, SH, JA, SH, AC }, 	 //	 132	 1200
{ KN, JA, JA, JA, JA, SK, JA, JA, JA, JA, QN, SH, ST, JA, JA }, 	 //	 133	 1200
{ KN, JA, JA, JA, JA, SK, SH, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 134	 1200
{ KN, QN, QN, QN, QN, SK, ST, SK, ST, QN, QN, JA, JA, JA, SH }, 	 //	 135	 1200
{ KN, ST, JA, SK, SH, SK, JA, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 136	 1200
{ KN, ST, JA, ST, JA, SK, JA, JA, JA, JA, QN, TN, JA, TN, JA }, 	 //	 137	 1200
{ KN, KN, KN, SH, TN, SK, KN, WN, TN, TN, QN, SK, TN, TN, TN }, 	 //	 138	 1200
{ KN, SK, QN, QN, QN, SK, QN, SK, ST, SH, QN, KN, JA, JA, JA }, 	 //	 139	 1200
{ KN, KN, KN, TN, TN, SK, AC, WN, TN, TN, QN, SH, TN, TN, TN }, 	 //	 140	 1200
{ SK, ST, QN, QN, QN, QN, QN, SK, ST, SH, QN, QN, JA, JA, JA }, 	 //	 141	 1200
{ SK, QN, QN, QN, SH, QN, SK, SK, SK, JA, QN, JA, JA, JA, JA }, 	 //	 142	 1200
{ SK, JA, JA, SK, JA, QN, JA, JA, JA, JA, QN, JA, JA, JA, WN }, 	 //	 143	 1200
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, ST, JA, JA }, 	 //	 144	 1200
{ SK, JA, JA, JA, QN, QN, JA, JA, JA, SH, QN, SH, JA, JA, JA }, 	 //	 145	 1200
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, WN, QN, SH, JA, JA, TN }, 	 //	 146	 1200
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, TN, QN, SH, JA, JA, AC }, 	 //	 147	 1200
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, SH, ST, JA, JA }, 	 //	 148	 1200
{ SK, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, SH, ST, SH, JA }, 	 //	 149	 1200
{ SK, JA, JA, JA, JA, QN, SH, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 150	 1200
{ SK, KN, QN, QN, QN, QN, QN, SK, ST, PF, QN, ST, JA, JA, JA }, 	 //	 151	 1200
{ SK, QN, QN, QN, QN, QN, ST, SK, ST, QN, QN, JA, JA, JA, QN }, 	 //	 152	 1200
{ SK, ST, JA, SK, SH, QN, JA, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 153	 1200
{ SK, ST, JA, JA, JA, QN, JA, JA, JA, JA, QN, TN, JA, JA, WN }, 	 //	 154	 1200
{ SK, ST, JA, JA, JA, QN, JA, JA, JA, JA, QN, TN, JA, SH, WN }, 	 //	 155	 1200
{ SK, JA, JA, JA, JA, QN, TN, JA, JA, JA, QN, AC, JA, JA, JA }, 	 //	 156	 1200
{ QN, QN, QN, JA, QN, QN, QN, SK, JA, SH, QN, QN, JA, JA, JA }, 	 //	 157	 1200
{ QN, QN, QN, JA, JA, QN, QN, SK, JA, WN, QN, QN, JA, JA, TN }, 	 //	 158	 1200
{ QN, QN, QN, JA, JA, QN, QN, SK, JA, JA, QN, QN, JA, SH, JA }, 	 //	 159	 1200
{ QN, QN, QN, JA, JA, QN, QN, SK, JA, TN, QN, QN, JA, SH, AC }, 	 //	 160	 1200
{ QN, QN, QN, ST, JA, QN, QN, SK, JA, JA, QN, QN, JA, TN, WN }, 	 //	 161	 1200
{ QN, QN, QN, SK, JA, QN, QN, SK, JA, WN, QN, SK, JA, JA, TN }, 	 //	 162	 1200
{ QN, QN, QN, SK, JA, QN, QN, SK, JA, TN, QN, SK, JA, JA, AC }, 	 //	 163	 1200
{ QN, QN, QN, JA, SH, QN, QN, SK, JA, JA, QN, SK, JA, JA, JA }, 	 //	 164	 1200
{ QN, QN, QN, JA, QN, QN, QN, SK, JA, PF, QN, SK, JA, JA, JA }, 	 //	 165	 1200
{ QN, QN, QN, JA, JA, QN, QN, SK, JA, TN, QN, SK, JA, JA, AC }, 	 //	 166	 1200
{ QN, QN, QN, ST, JA, QN, QN, SK, JA, JA, QN, SK, JA, TN, JA }, 	 //	 167	 1200
{ QN, QN, QN, ST, JA, QN, QN, SK, JA, WN, QN, SK, JA, TN, TN }, 	 //	 168	 1200
{ QN, QN, JA, JA, JA, QN, SK, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 169	 1200
{ QN, SK, JA, SK, QN, QN, JA, JA, JA, SH, QN, JA, JA, JA, JA }, 	 //	 170	 1200
{ QN, SK, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, JA, SH, WN }, 	 //	 171	 1200
{ QN, SK, JA, ST, JA, QN, JA, JA, JA, JA, QN, JA, JA, TN, JA }, 	 //	 172	 1200
{ QN, JA, JA, SK, SH, QN, JA, JA, JA, JA, QN, SH, JA, JA, JA }, 	 //	 173	 1200
{ QN, JA, JA, JA, QN, QN, JA, JA, JA, SH, QN, SH, JA, JA, JA }, 	 //	 174	 1200
{ QN, JA, JA, JA, JA, QN, JA, JA, JA, WN, QN, SH, JA, JA, TN }, 	 //	 175	 1200
{ QN, JA, JA, JA, JA, QN, JA, JA, JA, WN, QN, SH, JA, SH, TN }, 	 //	 176	 1200
{ QN, JA, JA, JA, JA, QN, JA, JA, JA, TN, QN, SH, JA, SH, AC }, 	 //	 177	 1200
{ QN, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, SH, ST, SH, JA }, 	 //	 178	 1200
{ QN, QN, QN, QN, KN, QN, ST, SK, ST, KN, QN, JA, JA, JA, SK }, 	 //	 179	 1200
{ QN, QN, QN, QN, TN, QN, ST, SK, ST, TN, QN, JA, JA, JA, TN }, 	 //	 180	 1200
{ QN, QN, QN, QN, KN, QN, ST, SK, ST, QN, QN, JA, JA, JA, PF }, 	 //	 181	 1200
{ QN, QN, QN, QN, JA, QN, ST, SK, ST, TN, QN, JA, JA, JA, AC }, 	 //	 182	 1200
{ QN, QN, QN, QN, KN, QN, ST, SK, ST, KN, QN, JA, JA, JA, KN }, 	 //	 183	 1200
{ QN, QN, QN, QN, KN, QN, ST, SK, ST, KN, QN, JA, JA, JA, CR }, 	 //	 184	 1200
{ QN, ST, JA, JA, SH, QN, JA, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 185	 1200
{ QN, SK, QN, QN, QN, QN, QN, SK, ST, PF, QN, KN, JA, JA, JA }, 	 //	 186	 1200
{ QN, SK, JA, JA, QN, QN, JA, JA, JA, SH, SH, JA, JA, JA, JA }, 	 //	 187	 1200
{ QN, SK, JA, JA, JA, QN, JA, JA, JA, JA, SH, JA, JA, SH, WN }, 	 //	 188	 1200
{ QN, JA, JA, SK, JA, QN, JA, JA, JA, JA, SH, JA, JA, JA, WN }, 	 //	 189	 1200
{ QN, JA, JA, SK, QN, QN, JA, JA, JA, PF, SH, JA, JA, JA, JA }, 	 //	 190	 1200
{ QN, JA, JA, JA, JA, QN, JA, JA, JA, WN, SH, JA, JA, SH, TN }, 	 //	 191	 1200
{ QN, JA, JA, JA, QN, QN, JA, JA, JA, PF, SH, SH, JA, JA, JA }, 	 //	 192	 1200
{ QN, JA, JA, ST, JA, QN, JA, JA, JA, JA, SH, SH, JA, TN, JA }, 	 //	 193	 1200
{ QN, QN, JA, JA, JA, QN, ST, JA, JA, JA, SH, JA, JA, JA, JA }, 	 //	 194	 1200
{ QN, QN, QN, QN, AC, QN, ST, SK, ST, LO, SH, JA, JA, JA, AC }, 	 //	 195	 1200
{ QN, QN, QN, QN, CR, QN, ST, SK, ST, KN, SH, JA, JA, JA, KN }, 	 //	 196	 1200
{ QN, QN, QN, QN, KN, QN, ST, SK, ST, SK, SH, JA, JA, JA, QN }, 	 //	 197	 1200
{ QN, QN, QN, QN, WN, QN, ST, SK, ST, TN, SH, JA, JA, JA, TN }, 	 //	 198	 1200
{ QN, QN, QN, QN, ST, QN, ST, SK, ST, AC, SH, JA, JA, JA, KN }, 	 //	 199	 1200
{ QN, QN, QN, QN, JA, QN, ST, SK, ST, TN, SH, JA, JA, JA, AC }, 	 //	 200	 1200
{ QN, QN, QN, QN, AC, QN, ST, SK, ST, AC, SH, JA, JA, JA, AC }, 	 //	 201	 1200
{ QN, QN, QN, QN, CR, QN, ST, SK, ST, QN, SH, JA, JA, JA, KN }, 	 //	 202	 1200
{ QN, ST, JA, JA, JA, QN, JA, JA, JA, JA, SH, TN, JA, SH, WN }, 	 //	 203	 1200
{ QN, QN, QN, QN, SH, QN, KN, SK, ST, JA, SH, AC, JA, JA, JA }, 	 //	 204	 1200
{ QN, SK, LO, SK, SH, SH, JA, JA, JA, JA, JA, JA, JA, JA, JA }, 	 //	 205	 1200
{ QN, SK, LO, SK, JA, SH, JA, JA, JA, JA, JA, JA, JA, JA, WN }, 	 //	 206	 1200
{ QN, SK, JA, SK, AC, SH, JA, JA, JA, LO, JA, JA, JA, JA, AC }, 	 //	 207	 1200
{ QN, SK, JA, SK, CR, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 208	 1200
{ QN, SK, JA, SK, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 209	 1200
{ QN, SK, JA, SK, TN, SH, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 210	 1200
{ QN, SK, JA, SK, TN, SH, JA, JA, JA, ST, JA, JA, JA, JA, AC }, 	 //	 211	 1200
{ QN, SK, JA, SK, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 212	 1200
{ QN, SK, JA, SK, QN, SH, JA, JA, JA, KN, JA, JA, JA, JA, AC }, 	 //	 213	 1200
{ QN, SK, JA, JA, AC, SH, JA, JA, JA, AC, JA, JA, JA, JA, CR }, 	 //	 214	 1200
{ QN, SK, JA, JA, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, SK }, 	 //	 215	 1200
{ QN, SK, JA, JA, SK, SH, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 216	 1200
{ QN, SK, JA, JA, QN, SH, JA, JA, JA, QN, JA, JA, JA, JA, SH }, 	 //	 217	 1200
{ QN, SK, JA, JA, QN, SH, JA, JA, JA, KN, JA, JA, JA, JA, AC }, 	 //	 218	 1200
{ QN, SK, JA, ST, JA, SH, JA, JA, JA, WN, JA, JA, JA, TN, TN }, 	 //	 219	 1200
{ QN, SK, JA, ST, JA, SH, JA, JA, JA, TN, JA, JA, JA, TN, AC }, 	 //	 220	 1200
{ QN, SK, QN, QN, QN, SH, JA, SK, QN, QN, JA, JA, JA, SK, QN }, 	 //	 221	 1200
{ QN, JA, LO, SK, JA, SH, JA, JA, JA, JA, JA, JA, JA, JA, WN }, 	 //	 222	 1200
{ QN, JA, JA, SK, AC, SH, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 223	 1200
{ QN, JA, JA, SK, KN, SH, JA, JA, JA, KN, JA, JA, JA, JA, SK }, 	 //	 224	 1200
{ QN, JA, JA, SK, WN, SH, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 225	 1200
{ QN, JA, JA, SK, TN, SH, JA, JA, JA, ST, JA, JA, JA, JA, AC }, 	 //	 226	 1200
{ QN, JA, JA, SK, AC, SH, JA, JA, JA, KN, JA, JA, JA, JA, QN }, 	 //	 227	 1200
{ QN, JA, JA, SK, KN, SH, JA, JA, JA, QN, JA, JA, JA, JA, PF }, 	 //	 228	 1200
{ QN, JA, JA, SK, TN, SH, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 229	 1200
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, KN, JA, JA, JA, SH, SK }, 	 //	 230	 1200
{ QN, JA, JA, JA, QN, SH, JA, JA, JA, QN, JA, JA, JA, SH, SH }, 	 //	 231	 1200
{ QN, JA, JA, JA, TN, SH, JA, JA, JA, TN, JA, JA, JA, SH, TN }, 	 //	 232	 1200
{ QN, JA, JA, JA, AC, SH, JA, JA, JA, SK, JA, JA, JA, SH, KN }, 	 //	 233	 1200
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, KN, JA, JA, JA, SH, CR }, 	 //	 234	 1200
{ QN, JA, JA, JA, KN, SH, JA, JA, JA, AC, JA, JA, JA, SH, LO }, 	 //	 235	 1200
{ QN, JA, JA, ST, JA, SH, JA, JA, JA, TN, JA, JA, JA, TN, AC }, 	 //	 236	 1200
{ QN, JA, JA, JA, SH, SH, JA, JA, JA, JA, JA, JA, ST, JA, JA }, 	 //	 237	 1200
{ QN, JA, JA, SK, JA, SH, JA, JA, JA, JA, JA, SH, JA, JA, WN }, 	 //	 238	 1200
{ QN, JA, JA, JA, PF, SH, JA, JA, JA, JA, JA, SH, JA, JA, TN }, 	 //	 239	 1200
{ QN, QN, JA, SK, JA, SH, ST, JA, JA, JA, JA, JA, JA, JA, JA }, 	 //	 240	 1200
{ QN, QN, QN, WN, SK, SH, ST, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 241	 1200
{ QN, QN, QN, WN, QN, SH, ST, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 242	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, QN, QN, JA, JA, JA, QN, PF }, 	 //	 243	 1200
{ QN, QN, QN, QN, JA, SH, ST, SK, QN, TN, JA, JA, JA, QN, AC }, 	 //	 244	 1200
{ QN, QN, QN, QN, CR, SH, ST, SK, QN, QN, JA, JA, JA, QN, KN }, 	 //	 245	 1200
{ QN, QN, QN, QN, AC, SH, ST, SK, QN, LO, JA, JA, JA, SK, AC }, 	 //	 246	 1200
{ QN, QN, QN, QN, LO, SH, ST, SK, QN, AC, JA, JA, JA, SK, AC }, 	 //	 247	 1200
{ QN, QN, QN, QN, AC, SH, ST, SK, QN, AC, JA, JA, JA, SK, AC }, 	 //	 248	 1200
{ QN, QN, QN, QN, CR, SH, ST, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 249	 1200
{ QN, QN, QN, QN, JA, SH, ST, SK, QN, WN, JA, JA, JA, SK, TN }, 	 //	 250	 1200
{ QN, QN, QN, QN, WN, SH, ST, SK, QN, TN, JA, JA, JA, SK, TN }, 	 //	 251	 1200
{ QN, QN, QN, QN, TN, SH, ST, SK, QN, TN, JA, JA, JA, SK, ST }, 	 //	 252	 1200
{ QN, QN, QN, QN, TN, SH, ST, SK, QN, ST, JA, JA, JA, SK, AC }, 	 //	 253	 1200
{ QN, QN, QN, QN, JA, SH, ST, SK, QN, TN, JA, JA, JA, SK, AC }, 	 //	 254	 1200
{ QN, QN, QN, QN, AC, SH, ST, SK, QN, SK, JA, JA, JA, SK, KN }, 	 //	 255	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 256	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, QN, AC, JA, JA, JA, SK, LO }, 	 //	 257	 1200
{ QN, QN, QN, KN, SK, SH, ST, SK, QN, QN, JA, JA, JA, ST, QN }, 	 //	 258	 1200
{ QN, QN, QN, QN, LO, SH, ST, SK, KN, AC, JA, JA, JA, AC, AC }, 	 //	 259	 1200
{ QN, QN, QN, QN, CR, SH, ST, SK, KN, KN, JA, JA, JA, AC, KN }, 	 //	 260	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, KN, SK, JA, JA, JA, AC, QN }, 	 //	 261	 1200
{ QN, QN, QN, QN, SH, SH, ST, SK, KN, JA, JA, JA, JA, AC, JA }, 	 //	 262	 1200
{ QN, QN, QN, QN, JA, SH, ST, SK, KN, JA, JA, JA, JA, AC, WN }, 	 //	 263	 1200
{ QN, QN, QN, QN, TN, SH, ST, SK, KN, ST, JA, JA, JA, AC, AC }, 	 //	 264	 1200
{ QN, QN, QN, QN, AC, SH, ST, SK, KN, KN, JA, JA, JA, AC, QN }, 	 //	 265	 1200
{ QN, QN, QN, QN, AC, SH, ST, SK, KN, AC, JA, JA, JA, AC, SK }, 	 //	 266	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, KN, KN, JA, JA, JA, AC, KN }, 	 //	 267	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, KN, KN, JA, JA, JA, AC, CR }, 	 //	 268	 1200
{ QN, QN, QN, QN, KN, SH, ST, SK, KN, AC, JA, JA, JA, AC, LO }, 	 //	 269	 1200
{ QN, ST, JA, SK, JA, SH, JA, JA, JA, JA, JA, TN, JA, JA, WN }, 	 //	 270	 1200
{ QN, ST, JA, JA, QN, SH, JA, JA, JA, PF, JA, TN, JA, JA, JA }, 	 //	 271	 1200
{ QN, ST, JA, JA, JA, SH, JA, JA, JA, TN, JA, TN, JA, SH, AC }, 	 //	 272	 1200
{ QN, ST, JA, JA, JA, SH, JA, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 273	 1200
{ QN, QN, QN, QN, JA, SH, KN, SK, ST, JA, JA, AC, JA, JA, JA }, 	 //	 274	 1200
{ SH, SK, LO, SK, JA, JA, JA, JA, JA, WN, JA, JA, JA, JA, TN }, 	 //	 275	 1200
{ SH, SK, LO, JA, QN, JA, JA, JA, JA, PF, JA, JA, JA, JA, JA }, 	 //	 276	 1200
{ SH, SK, LO, ST, JA, JA, JA, JA, JA, JA, JA, JA, JA, TN, WN }, 	 //	 277	 1200
{ SH, SK, JA, JA, AC, JA, JA, JA, JA, AC, JA, JA, JA, SH, AC }, 	 //	 278	 1200
{ SH, SK, JA, JA, QN, JA, JA, JA, JA, QN, JA, JA, JA, SH, QN }, 	 //	 279	 1200
{ SH, SK, JA, JA, WN, JA, JA, JA, JA, TN, JA, JA, JA, SH, TN }, 	 //	 280	 1200
{ SH, SK, JA, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, SH, TN }, 	 //	 281	 1200
{ SH, SK, JA, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, SH, ST }, 	 //	 282	 1200
{ SH, SK, JA, JA, AC, JA, JA, JA, JA, AC, JA, JA, JA, SH, SK }, 	 //	 283	 1200
{ SH, SK, JA, ST, AC, JA, JA, JA, JA, LO, JA, JA, JA, TN, AC }, 	 //	 284	 1200
{ SH, SK, JA, ST, KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, SK }, 	 //	 285	 1200
{ SH, SK, JA, ST, KN, JA, JA, JA, JA, QN, JA, JA, JA, TN, PF }, 	 //	 286	 1200
{ SH, SK, JA, ST, AC, JA, JA, JA, JA, AC, JA, JA, JA, TN, SK }, 	 //	 287	 1200
{ SH, SK, JA, ST, SK, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN }, 	 //	 288	 1200
{ SH, SK, JA, SK, SH, JA, JA, JA, JA, JA, JA, JA, ST, JA, JA }, 	 //	 289	 1200
{ SH, SK, JA, JA, JA, JA, JA, JA, JA, JA, JA, JA, ST, JA, WN }, 	 //	 290	 1200
{ SH, SK, QN, QN, QN, JA, JA, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 291	 1200
{ SH, JA, LO, SK, PF, JA, JA, JA, JA, JA, JA, JA, JA, JA, TN }, 	 //	 292	 1200
{ SH, JA, LO, JA, QN, JA, JA, JA, JA, PF, JA, JA, JA, JA, JA }, 	 //	 293	 1200
{ SH, JA, JA, ST, AC, JA, JA, JA, JA, LO, JA, JA, JA, TN, AC }, 	 //	 294	 1200
{ SH, JA, JA, ST, KN, JA, JA, JA, JA, QN, JA, JA, JA, TN, PF }, 	 //	 295	 1200
{ SH, JA, JA, ST, AC, JA, JA, JA, JA, AC, JA, JA, JA, TN, SK }, 	 //	 296	 1200
{ SH, JA, JA, ST, KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN }, 	 //	 297	 1200
{ SH, JA, JA, ST, KN, JA, JA, JA, JA, AC, JA, JA, JA, TN, LO }, 	 //	 298	 1200
{ SH, JA, JA, JA, PF, JA, JA, JA, JA, JA, JA, JA, ST, SH, TN }, 	 //	 299	 1200
{ SH, JA, JA, ST, SH, JA, JA, JA, JA, JA, JA, JA, ST, TN, JA }, 	 //	 300	 1200
{ SH, JA, QN, QN, QN, JA, JA, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 301	 1200
{ SH, JA, QN, QN, QN, JA, JA, SK, QN, QN, JA, JA, JA, SK, QN }, 	 //	 302	 1200
{ SH, JA, LO, JA, JA, JA, JA, JA, JA, JA, JA, SH, JA, JA, JA }, 	 //	 303	 1200
{ SH, JA, JA, SK, PF, JA, JA, JA, JA, JA, JA, SH, JA, JA, TN }, 	 //	 304	 1200
{ SH, JA, JA, SK, JA, JA, JA, JA, JA, TN, JA, SH, JA, JA, AC }, 	 //	 305	 1200
{ SH, JA, JA, JA, CR, JA, JA, JA, JA, KN, JA, SH, JA, JA, KN }, 	 //	 306	 1200
{ SH, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, SH, JA, JA, SH }, 	 //	 307	 1200
{ SH, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, SH, JA, JA, ST }, 	 //	 308	 1200
{ SH, JA, JA, JA, AC, JA, JA, JA, JA, KN, JA, SH, JA, JA, QN }, 	 //	 309	 1200
{ SH, JA, JA, JA, SK, JA, JA, JA, JA, KN, JA, SH, JA, JA, KN }, 	 //	 310	 1200
{ SH, JA, JA, JA, QN, JA, JA, JA, JA, KN, JA, SH, JA, JA, AC }, 	 //	 311	 1200
{ SH, JA, JA, JA, KN, JA, JA, JA, JA, SK, JA, SH, JA, SH, QN }, 	 //	 312	 1200
{ SH, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, SH, JA, SH, SH }, 	 //	 313	 1200
{ SH, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, SH, JA, SH, TN }, 	 //	 314	 1200
{ SH, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, SH, JA, SH, ST }, 	 //	 315	 1200
{ SH, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, SH, JA, SH, AC }, 	 //	 316	 1200
{ SH, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, SH, JA, SH, KN }, 	 //	 317	 1200
{ SH, JA, JA, JA, KN, JA, JA, JA, JA, AC, JA, SH, JA, SH, LO }, 	 //	 318	 1200
{ SH, JA, JA, ST, QN, JA, JA, JA, JA, PF, JA, SH, JA, TN, JA }, 	 //	 319	 1200
{ SH, JA, JA, ST, PF, JA, JA, JA, JA, JA, JA, SH, JA, TN, TN }, 	 //	 320	 1200
{ SH, JA, JA, ST, JA, JA, JA, JA, JA, TN, JA, SH, JA, TN, AC }, 	 //	 321	 1200
{ SH, JA, JA, JA, QN, JA, JA, JA, JA, PF, JA, SH, ST, JA, JA }, 	 //	 322	 1200
{ SH, JA, JA, JA, JA, JA, JA, JA, JA, TN, JA, SH, ST, JA, AC }, 	 //	 323	 1200
{ SH, JA, JA, JA, QN, JA, JA, JA, JA, PF, JA, SH, ST, SH, JA }, 	 //	 324	 1200
{ SH, JA, JA, JA, PF, JA, JA, JA, JA, JA, JA, SH, ST, SH, TN }, 	 //	 325	 1200
{ SH, JA, JA, ST, JA, JA, JA, JA, JA, JA, JA, SH, ST, TN, JA }, 	 //	 326	 1200
{ SH, QN, JA, SK, JA, JA, ST, JA, JA, JA, JA, JA, JA, JA, JA }, 	 //	 327	 1200
{ SH, QN, QN, QN, QN, JA, ST, SK, QN, SH, JA, JA, JA, QN, JA }, 	 //	 328	 1200
{ SH, ST, LO, SK, JA, JA, JA, JA, JA, JA, JA, TN, JA, JA, JA }, 	 //	 329	 1200
{ SH, ST, JA, SK, PF, JA, JA, JA, JA, JA, JA, TN, JA, JA, TN }, 	 //	 330	 1200
{ SH, ST, JA, JA, PF, JA, JA, JA, JA, JA, JA, TN, JA, SH, TN }, 	 //	 331	 1200
{ SH, ST, JA, ST, QN, JA, JA, JA, JA, PF, JA, TN, JA, TN, JA }, 	 //	 332	 1200
{ SH, ST, JA, SK, SH, JA, JA, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 333	 1200
{ SH, ST, JA, SK, JA, JA, JA, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 334	 1200
{ SH, ST, JA, JA, SH, JA, JA, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 335	 1200
{ JA, QN, JA, SK, JA, JA, SK, JA, JA, JA, JA, JA, JA, JA, JA }, 	 //	 336	 1200
{ JA, QN, QN, QN, SK, JA, SK, SK, SK, KN, JA, JA, JA, JA, KN }, 	 //	 337	 1200
{ JA, SK, TN, SK, JA, JA, JA, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 338	 1200
{ JA, SK, TN, JA, JA, JA, JA, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 339	 1200
{ JA, SK, LO, SK, LO, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 340	 1200
{ JA, SK, LO, SK, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, CR }, 	 //	 341	 1200
{ JA, SK, LO, SK, QN, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 342	 1200
{ JA, SK, LO, SK, TN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 343	 1200
{ JA, SK, LO, SK, AC, JA, JA, JA, JA, KN, JA, JA, JA, JA, QN }, 	 //	 344	 1200
{ JA, SK, LO, SK, KN, JA, JA, JA, JA, QN, JA, JA, JA, JA, PF }, 	 //	 345	 1200
{ JA, SK, LO, SK, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, SK }, 	 //	 346	 1200
{ JA, SK, LO, SK, CR, JA, JA, JA, JA, QN, JA, JA, JA, JA, KN }, 	 //	 347	 1200
{ JA, SK, LO, SK, QN, JA, JA, JA, JA, KN, JA, JA, JA, JA, AC }, 	 //	 348	 1200
{ JA, SK, LO, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 349	 1200
{ JA, SK, LO, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, SK }, 	 //	 350	 1200
{ JA, SK, LO, JA, QN, JA, JA, JA, JA, QN, JA, JA, JA, JA, SH }, 	 //	 351	 1200
{ JA, SK, LO, JA, WN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 352	 1200
{ JA, SK, LO, JA, SK, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 353	 1200
{ JA, SK, LO, JA, CR, JA, JA, JA, JA, QN, JA, JA, JA, JA, KN }, 	 //	 354	 1200
{ JA, SK, LO, JA, KN, JA, JA, JA, JA, AC, JA, JA, JA, JA, LO }, 	 //	 355	 1200
{ JA, SK, LO, JA, JA, JA, JA, JA, JA, WN, JA, JA, JA, SH, TN }, 	 //	 356	 1200
{ JA, SK, JA, ST, SH, JA, JA, JA, JA, JA, JA, JA, ST, TN, JA }, 	 //	 357	 1200
{ JA, SK, QN, SK, JA, JA, JA, SK, JA, JA, JA, JA, JA, JA, JA }, 	 //	 358	 1200
{ JA, SK, QN, JA, JA, JA, JA, SK, JA, JA, JA, JA, JA, JA, JA }, 	 //	 359	 1200
{ JA, JA, TN, SK, JA, JA, JA, LO, JA, JA, JA, JA, JA, JA, JA }, 	 //	 360	 1200
{ JA, JA, LO, SK, AC, JA, JA, JA, JA, LO, JA, JA, JA, JA, AC }, 	 //	 361	 1200
{ JA, JA, LO, SK, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 362	 1200
{ JA, JA, LO, SK, CR, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 363	 1200
{ JA, JA, LO, SK, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 364	 1200
{ JA, JA, LO, SK, KN, JA, JA, JA, JA, SK, JA, JA, JA, JA, QN }, 	 //	 365	 1200
{ JA, JA, LO, SK, WN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 366	 1200
{ JA, JA, LO, SK, TN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 367	 1200
{ JA, JA, LO, SK, ST, JA, JA, JA, JA, AC, JA, JA, JA, JA, KN }, 	 //	 368	 1200
{ JA, JA, LO, SK, KN, JA, JA, JA, JA, QN, JA, JA, JA, JA, PF }, 	 //	 369	 1200
{ JA, JA, LO, SK, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 370	 1200
{ JA, JA, LO, SK, AC, JA, JA, JA, JA, SK, JA, JA, JA, JA, KN }, 	 //	 371	 1200
{ JA, JA, LO, JA, AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 372	 1200
{ JA, JA, LO, JA, CR, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 373	 1200
{ JA, JA, LO, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 374	 1200
{ JA, JA, LO, JA, KN, JA, JA, JA, JA, SK, JA, JA, JA, JA, QN }, 	 //	 375	 1200
{ JA, JA, LO, JA, QN, JA, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 376	 1200
{ JA, JA, LO, JA, TN, JA, JA, JA, JA, ST, JA, JA, JA, JA, AC }, 	 //	 377	 1200
{ JA, JA, LO, JA, KN, JA, JA, JA, JA, QN, JA, JA, JA, JA, PF }, 	 //	 378	 1200
{ JA, JA, LO, JA, TN, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 379	 1200
{ JA, JA, LO, JA, KN, JA, JA, JA, JA, AC, JA, JA, JA, JA, LO }, 	 //	 380	 1200
{ JA, JA, LO, JA, PF, JA, JA, JA, JA, JA, JA, JA, JA, SH, TN }, 	 //	 381	 1200
{ JA, JA, JA, QN, LO, JA, JA, JA, SK, AC, JA, JA, JA, JA, AC }, 	 //	 382	 1200
{ JA, JA, JA, QN, AC, JA, JA, JA, SK, AC, JA, JA, JA, JA, AC }, 	 //	 383	 1200
{ JA, JA, JA, QN, QN, JA, JA, JA, SK, QN, JA, JA, JA, JA, QN }, 	 //	 384	 1200
{ JA, JA, JA, QN, ST, JA, JA, JA, SK, AC, JA, JA, JA, JA, KN }, 	 //	 385	 1200
{ JA, JA, JA, QN, PF, JA, JA, JA, SK, JA, JA, JA, JA, JA, TN }, 	 //	 386	 1200
{ JA, JA, JA, QN, KN, JA, JA, JA, SK, AC, JA, JA, JA, JA, LO }, 	 //	 387	 1200
{ JA, JA, JA, JA, LO, JA, JA, JA, SH, AC, JA, JA, JA, TN, AC }, 	 //	 388	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, SH, SK, JA, JA, JA, TN, QN }, 	 //	 389	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, SH, QN, JA, JA, JA, TN, SH }, 	 //	 390	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, SH, ST, JA, JA, JA, TN, AC }, 	 //	 391	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, SH, KN, JA, JA, JA, TN, QN }, 	 //	 392	 1200
{ JA, JA, JA, JA, PF, JA, JA, JA, SH, JA, JA, JA, JA, TN, TN }, 	 //	 393	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, SH, AC, JA, JA, JA, TN, SK }, 	 //	 394	 1200
{ JA, JA, JA, JA, CR, JA, JA, JA, SH, QN, JA, JA, JA, TN, KN }, 	 //	 395	 1200
{ JA, JA, JA, QN, LO, JA, JA, JA, ST, AC, JA, JA, JA, JA, AC }, 	 //	 396	 1200
{ JA, JA, JA, QN, AC, JA, JA, JA, ST, AC, JA, JA, JA, JA, AC }, 	 //	 397	 1200
{ JA, JA, JA, QN, ST, JA, JA, JA, ST, AC, JA, JA, JA, JA, KN }, 	 //	 398	 1200
{ JA, JA, JA, QN, AC, JA, JA, JA, ST, KN, JA, JA, JA, JA, QN }, 	 //	 399	 1200
{ JA, JA, JA, QN, KN, JA, JA, JA, ST, QN, JA, JA, JA, JA, PF }, 	 //	 400	 1200
{ JA, JA, JA, QN, JA, JA, JA, JA, ST, TN, JA, JA, JA, JA, AC }, 	 //	 401	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, JA, AC, CR }, 	 //	 402	 1200
{ JA, JA, JA, JA, CR, JA, JA, JA, TN, KN, JA, JA, JA, AC, KN }, 	 //	 403	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, JA, JA, JA, AC, KN }, 	 //	 404	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, JA, JA, JA, AC, SK }, 	 //	 405	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, TN, QN, JA, JA, JA, AC, SH }, 	 //	 406	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, JA, AC, AC }, 	 //	 407	 1200
{ JA, JA, JA, JA, CR, JA, JA, JA, TN, QN, JA, JA, JA, AC, KN }, 	 //	 408	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, TN, AC, JA, JA, JA, AC, LO }, 	 //	 409	 1200
{ JA, JA, JA, SK, QN, JA, JA, JA, JA, SH, JA, JA, ST, JA, JA }, 	 //	 410	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, JA, ST, JA, KN }, 	 //	 411	 1200
{ JA, JA, JA, JA, WN, JA, JA, JA, JA, TN, JA, JA, ST, JA, TN }, 	 //	 412	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, JA, KN, JA, JA, ST, JA, QN }, 	 //	 413	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, JA, SK, JA, JA, ST, JA, KN }, 	 //	 414	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, AC, JA, JA, ST, JA, LO }, 	 //	 415	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, JA, ST, SH, KN }, 	 //	 416	 1200
{ JA, JA, JA, JA, SK, JA, JA, JA, JA, QN, JA, JA, ST, SH, QN }, 	 //	 417	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, JA, ST, SH, SH }, 	 //	 418	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, JA, ST, SH, TN }, 	 //	 419	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, JA, ST, JA, JA, ST, SH, AC }, 	 //	 420	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, JA, AC, JA, JA, ST, SH, AC }, 	 //	 421	 1200
{ JA, JA, JA, JA, CR, JA, JA, JA, JA, QN, JA, JA, ST, SH, KN }, 	 //	 422	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, AC, JA, JA, ST, SH, LO }, 	 //	 423	 1200
{ JA, JA, JA, ST, QN, JA, JA, JA, JA, SH, JA, JA, ST, TN, JA }, 	 //	 424	 1200
{ JA, JA, JA, ST, QN, JA, JA, JA, JA, PF, JA, JA, ST, TN, JA }, 	 //	 425	 1200
{ JA, JA, QN, JA, JA, JA, JA, SK, JA, JA, JA, JA, JA, JA, JA }, 	 //	 426	 1200
{ JA, JA, LO, JA, SH, JA, JA, JA, JA, JA, JA, SH, JA, JA, JA }, 	 //	 427	 1200
{ JA, JA, LO, JA, JA, JA, JA, JA, JA, JA, JA, SH, JA, JA, WN }, 	 //	 428	 1200
{ JA, JA, LO, ST, JA, JA, JA, JA, JA, JA, JA, SH, JA, TN, WN }, 	 //	 429	 1200
{ JA, JA, JA, JA, JA, JA, JA, JA, SH, TN, JA, SH, JA, TN, AC }, 	 //	 430	 1200
{ JA, JA, JA, JA, JA, JA, JA, JA, TN, WN, JA, SH, JA, AC, TN }, 	 //	 431	 1200
{ JA, JA, JA, SK, PF, JA, JA, JA, JA, JA, JA, SH, ST, JA, TN }, 	 //	 432	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, SH, ST, JA, CR }, 	 //	 433	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, SK, JA, SH, ST, JA, QN }, 	 //	 434	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, SH, ST, JA, QN }, 	 //	 435	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, JA, QN, JA, SH, ST, JA, SH }, 	 //	 436	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, JA, ST, JA, SH, ST, JA, AC }, 	 //	 437	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, JA, KN, JA, SH, ST, JA, QN }, 	 //	 438	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, SH, ST, JA, CR }, 	 //	 439	 1200
{ JA, JA, JA, JA, LO, JA, JA, JA, JA, AC, JA, SH, ST, SH, AC }, 	 //	 440	 1200
{ JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, JA, SH, ST, SH, AC }, 	 //	 441	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, SK, JA, SH, ST, SH, QN }, 	 //	 442	 1200
{ JA, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, SH, ST, SH, ST }, 	 //	 443	 1200
{ JA, JA, JA, JA, SK, JA, JA, JA, JA, KN, JA, SH, ST, SH, KN }, 	 //	 444	 1200
{ JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, SH, ST, SH, KN }, 	 //	 445	 1200
{ JA, JA, JA, JA, CR, JA, JA, JA, JA, QN, JA, SH, ST, SH, KN }, 	 //	 446	 1200
{ JA, JA, JA, ST, JA, JA, JA, JA, JA, JA, JA, SH, ST, TN, WN }, 	 //	 447	 1200
{ JA, JA, QN, QN, QN, JA, JA, SK, QN, QN, JA, SH, JA, SK, QN }, 	 //	 448	 1200
{ JA, JA, JA, JA, JA, JA, SH, JA, JA, JA, JA, TN, JA, SH, JA }, 	 //	 449	 1200
{ JA, QN, QN, QN, SK, JA, ST, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 450	 1200
{ JA, QN, QN, QN, QN, JA, ST, SK, QN, KN, JA, JA, JA, QN, AC }, 	 //	 451	 1200
{ JA, QN, QN, QN, KN, JA, ST, SK, QN, SK, JA, JA, JA, SK, QN }, 	 //	 452	 1200
{ JA, QN, QN, QN, AC, JA, ST, SK, QN, KN, JA, JA, JA, SK, QN }, 	 //	 453	 1200
{ JA, QN, QN, QN, QN, JA, ST, SK, KN, PF, JA, JA, JA, AC, JA }, 	 //	 454	 1200
{ JA, QN, QN, QN, QN, JA, ST, SK, KN, KN, JA, JA, JA, AC, AC }, 	 //	 455	 1200
{ JA, ST, LO, SK, JA, JA, JA, JA, JA, JA, JA, TN, JA, JA, WN }, 	 //	 456	 1200
{ JA, ST, LO, ST, JA, JA, JA, JA, JA, JA, JA, TN, JA, TN, JA }, 	 //	 457	 1200
{ JA, ST, JA, SK, AC, JA, JA, JA, JA, AC, JA, TN, JA, JA, AC }, 	 //	 458	 1200
{ JA, ST, JA, SK, CR, JA, JA, JA, JA, KN, JA, TN, JA, JA, KN }, 	 //	 459	 1200
{ JA, ST, JA, SK, KN, JA, JA, JA, JA, SK, JA, TN, JA, JA, QN }, 	 //	 460	 1200
{ JA, ST, JA, SK, QN, JA, JA, JA, JA, QN, JA, TN, JA, JA, SH }, 	 //	 461	 1200
{ JA, ST, JA, SK, KN, JA, JA, JA, JA, KN, JA, TN, JA, JA, KN }, 	 //	 462	 1200
{ JA, ST, JA, JA, AC, JA, JA, JA, JA, AC, JA, TN, JA, JA, AC }, 	 //	 463	 1200
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, KN, JA, TN, JA, JA, SK }, 	 //	 464	 1200
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, SK, JA, TN, JA, JA, QN }, 	 //	 465	 1200
{ JA, ST, JA, JA, QN, JA, JA, JA, JA, QN, JA, TN, JA, JA, QN }, 	 //	 466	 1200
{ JA, ST, JA, JA, TN, JA, JA, JA, JA, TN, JA, TN, JA, JA, TN }, 	 //	 467	 1200
{ JA, ST, JA, JA, TN, JA, JA, JA, JA, AC, JA, TN, JA, JA, AC }, 	 //	 468	 1200
{ JA, ST, JA, JA, SK, JA, JA, JA, JA, KN, JA, TN, JA, JA, KN }, 	 //	 469	 1200
{ JA, ST, JA, JA, CR, JA, JA, JA, JA, QN, JA, TN, JA, JA, KN }, 	 //	 470	 1200
{ JA, ST, JA, JA, QN, JA, JA, JA, JA, KN, JA, TN, JA, JA, AC }, 	 //	 471	 1200
{ JA, ST, JA, JA, AC, JA, JA, JA, JA, LO, JA, TN, JA, SH, AC }, 	 //	 472	 1200
{ JA, ST, JA, JA, AC, JA, JA, JA, JA, AC, JA, TN, JA, SH, AC }, 	 //	 473	 1200
{ JA, ST, JA, JA, AC, JA, JA, JA, JA, AC, JA, TN, JA, SH, SK }, 	 //	 474	 1200
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, KN, JA, TN, JA, SH, KN }, 	 //	 475	 1200
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, KN, JA, TN, JA, SH, CR }, 	 //	 476	 1200
{ JA, ST, JA, JA, KN, JA, JA, JA, JA, AC, JA, TN, JA, SH, LO }, 	 //	 477	 1200
{ JA, ST, JA, ST, QN, JA, JA, JA, JA, QN, JA, TN, JA, TN, SH }, 	 //	 478	 1200
{ JA, ST, JA, ST, WN, JA, JA, JA, JA, TN, JA, TN, JA, TN, TN }, 	 //	 479	 1200
{ JA, ST, JA, ST, KN, JA, JA, JA, JA, QN, JA, TN, JA, TN, PF }, 	 //	 480	 1200
{ JA, ST, JA, ST, AC, JA, JA, JA, JA, SK, JA, TN, JA, TN, KN }, 	 //	 481	 1200
{ JA, ST, JA, SK, SH, JA, JA, JA, JA, JA, JA, TN, ST, JA, JA }, 	 //	 482	 1200
{ JA, ST, JA, JA, SH, JA, JA, JA, JA, JA, JA, TN, ST, SH, JA }, 	 //	 483	 1200
{ JA, ST, JA, ST, JA, JA, JA, JA, JA, JA, JA, TN, ST, TN, JA }, 	 //	 484	 1200
{ JA, QN, QN, QN, QN, JA, KN, SK, ST, PF, JA, AC, JA, JA, JA }, 	 //	 485	 1200
{ JA, SK, LO, SK, QN, JA, JA, JA, JA, PF, WN, JA, JA, JA, JA }, 	 //	 486	 1200
{ JA, SK, LO, JA, QN, JA, JA, JA, JA, SH, WN, JA, JA, JA, JA }, 	 //	 487	 1200
{ JA, SK, LO, JA, QN, JA, JA, JA, JA, PF, WN, JA, JA, JA, JA }, 	 //	 488	 1200
{ JA, SK, LO, JA, JA, JA, JA, JA, JA, TN, WN, JA, JA, JA, AC }, 	 //	 489	 1200
{ JA, SK, LO, JA, JA, JA, JA, JA, JA, JA, WN, JA, JA, SH, WN }, 	 //	 490	 1200
{ JA, SK, JA, SK, AC, JA, JA, JA, JA, AC, WN, JA, JA, JA, AC }, 	 //	 491	 1200
{ JA, SK, JA, SK, CR, JA, JA, JA, JA, KN, WN, JA, JA, JA, KN }, 	 //	 492	 1200
{ JA, SK, JA, SK, KN, JA, JA, JA, JA, SK, WN, JA, JA, JA, QN }, 	 //	 493	 1200
{ JA, SK, JA, SK, TN, JA, JA, JA, JA, TN, WN, JA, JA, JA, ST }, 	 //	 494	 1200
{ JA, SK, JA, SK, AC, JA, JA, JA, JA, KN, WN, JA, JA, JA, QN }, 	 //	 495	 1200
{ JA, SK, JA, SK, AC, JA, JA, JA, JA, AC, WN, JA, JA, JA, SK }, 	 //	 496	 1200
{ JA, SK, JA, SK, KN, JA, JA, JA, JA, KN, WN, JA, JA, JA, KN }, 	 //	 497	 1200
{ JA, SK, JA, JA, AC, JA, JA, JA, JA, LO, WN, JA, JA, JA, AC }, 	 //	 498	 1200
{ JA, SK, JA, JA, KN, JA, JA, JA, JA, KN, WN, JA, JA, JA, KN }, 	 //	 499	 1200
{ JA, SK, JA, JA, TN, JA, JA, JA, JA, TN, WN, JA, JA, JA, ST }, 	 //	 500	 1200
{ JA, SK, JA, JA, CR, JA, JA, JA, JA, QN, WN, JA, JA, JA, KN }, 	 //	 501	 1200
{ JA, SK, JA, JA, QN, JA, JA, JA, JA, KN, WN, JA, JA, JA, AC }, 	 //	 502	 1200
{ JA, SK, JA, JA, KN, JA, JA, JA, JA, AC, WN, JA, JA, JA, LO }, 	 //	 503	 1200
{ JA, SK, JA, JA, PF, JA, JA, JA, JA, JA, WN, JA, JA, SH, TN }, 	 //	 504	 1200
{ JA, SK, JA, ST, QN, JA, JA, JA, JA, SH, WN, JA, JA, TN, JA }, 	 //	 505	 1200
{ JA, SK, JA, ST, PF, JA, JA, JA, JA, JA, WN, JA, JA, TN, TN }, 	 //	 506	 1200
{ JA, SK, JA, JA, JA, JA, JA, JA, JA, JA, WN, JA, ST, JA, JA }, 	 //	 507	 1200
{ JA, JA, LO, SK, QN, JA, JA, JA, JA, PF, WN, JA, JA, JA, JA }, 	 //	 508	 1200
{ JA, JA, LO, JA, JA, JA, JA, JA, JA, WN, WN, JA, JA, JA, TN }, 	 //	 509	 1200
{ JA, JA, LO, ST, JA, JA, JA, JA, JA, JA, WN, JA, JA, TN, JA }, 	 //	 510	 1200
{ JA, JA, JA, ST, AC, JA, JA, JA, JA, AC, WN, JA, JA, TN, CR }, 	 //	 511	 1200
{ JA, JA, JA, ST, KN, JA, JA, JA, JA, KN, WN, JA, JA, TN, KN }, 	 //	 512	 1200
{ JA, JA, JA, ST, QN, JA, JA, JA, JA, QN, WN, JA, JA, TN, QN }, 	 //	 513	 1200
{ JA, JA, JA, ST, KN, JA, JA, JA, JA, QN, WN, JA, JA, TN, PF }, 	 //	 514	 1200
{ JA, JA, JA, ST, KN, JA, JA, JA, JA, KN, WN, JA, JA, TN, CR }, 	 //	 515	 1200
{ JA, JA, JA, SK, JA, JA, JA, JA, JA, JA, WN, JA, ST, JA, JA }, 	 //	 516	 1200
{ JA, JA, JA, JA, JA, JA, JA, JA, JA, TN, WN, JA, ST, JA, AC }, 	 //	 517	 1200
{ JA, JA, JA, JA, QN, JA, JA, JA, JA, PF, WN, JA, ST, SH, JA }, 	 //	 518	 1200
{ JA, JA, JA, ST, SH, JA, JA, JA, JA, JA, WN, JA, ST, TN, JA }, 	 //	 519	 1200
{ JA, JA, QN, QN, QN, JA, JA, SK, QN, QN, WN, JA, JA, SK, QN }, 	 //	 520	 1200
{ JA, JA, LO, JA, JA, JA, JA, JA, JA, JA, WN, SH, JA, JA, WN }, 	 //	 521	 1200
{ JA, JA, LO, ST, JA, JA, JA, JA, JA, JA, WN, SH, JA, TN, WN }, 	 //	 522	 1200
{ JA, JA, JA, SK, AC, JA, JA, JA, JA, LO, WN, SH, JA, JA, AC }, 	 //	 523	 1200
{ JA, JA, JA, SK, CR, JA, JA, JA, JA, KN, WN, SH, JA, JA, KN }, 	 //	 524	 1200
{ JA, JA, JA, SK, QN, JA, JA, JA, JA, QN, WN, SH, JA, JA, QN }, 	 //	 525	 1200
{ JA, JA, JA, SK, TN, JA, JA, JA, JA, TN, WN, SH, JA, JA, TN }, 	 //	 526	 1200
{ JA, JA, JA, SK, TN, JA, JA, JA, JA, TN, WN, SH, JA, JA, ST }, 	 //	 527	 1200
{ JA, JA, JA, SK, ST, JA, JA, JA, JA, AC, WN, SH, JA, JA, KN }, 	 //	 528	 1200
{ JA, JA, JA, SK, TN, JA, JA, JA, JA, AC, WN, SH, JA, JA, AC }, 	 //	 529	 1200
{ JA, JA, JA, SK, AC, JA, JA, JA, JA, AC, WN, SH, JA, JA, SK }, 	 //	 530	 1200
{ JA, JA, JA, SK, QN, JA, JA, JA, JA, KN, WN, SH, JA, JA, AC }, 	 //	 531	 1200
{ JA, JA, JA, ST, AC, JA, JA, JA, JA, LO, WN, SH, JA, TN, AC }, 	 //	 532	 1200
{ JA, JA, JA, ST, LO, JA, JA, JA, JA, AC, WN, SH, JA, TN, AC }, 	 //	 533	 1200
{ JA, JA, JA, ST, AC, JA, JA, JA, JA, AC, WN, SH, JA, TN, CR }, 	 //	 534	 1200
{ JA, JA, JA, ST, KN, JA, JA, JA, JA, SK, WN, SH, JA, TN, QN }, 	 //	 535	 1200
{ JA, JA, JA, ST, TN, JA, JA, JA, JA, TN, WN, SH, JA, TN, TN }, 	 //	 536	 1200
{ JA, JA, JA, ST, TN, JA, JA, JA, JA, ST, WN, SH, JA, TN, AC }, 	 //	 537	 1200
{ JA, JA, JA, ST, AC, JA, JA, JA, JA, KN, WN, SH, JA, TN, QN }, 	 //	 538	 1200
{ JA, JA, JA, ST, AC, JA, JA, JA, JA, SK, WN, SH, JA, TN, KN }, 	 //	 539	 1200
{ JA, JA, JA, ST, CR, JA, JA, JA, JA, QN, WN, SH, JA, TN, KN }, 	 //	 540	 1200
{ JA, JA, JA, JA, JA, JA, JA, JA, JA, WN, WN, SH, ST, JA, TN }, 	 //	 541	 1200
{ JA, QN, QN, QN, QN, JA, ST, SK, ST, QN, WN, JA, JA, JA, QN }, 	 //	 542	 1200
{ JA, ST, LO, JA, SH, JA, JA, JA, JA, JA, WN, TN, JA, JA, JA }, 	 //	 543	 1200
{ JA, ST, JA, SK, JA, JA, JA, JA, JA, TN, WN, TN, JA, JA, AC }, 	 //	 544	 1200
{ JA, ST, JA, JA, QN, JA, JA, JA, JA, SH, WN, TN, JA, SH, JA }, 	 //	 545	 1200
{ JA, ST, JA, ST, QN, JA, JA, JA, JA, SH, WN, TN, JA, TN, JA }, 	 //	 546	 1200
{ JA, ST, JA, ST, JA, JA, JA, JA, JA, WN, WN, TN, JA, TN, TN }, 	 //	 547	 1200
{ JA, ST, JA, ST, QN, JA, JA, JA, JA, PF, WN, TN, JA, TN, JA }, 	 //	 548	 1200
{ JA, JA, JA, JA, JA, JA, TN, JA, JA, JA, WN, AC, JA, SH, JA }, 	 //	 549	 1200
{ JA, QN, QN, QN, QN, WN, QN, SK, ST, SH, TN, QN, JA, JA, JA }, 	 //	 550	 1200
{ JA, SK, JA, JA, JA, WN, JA, JA, JA, WN, TN, JA, JA, SH, TN }, 	 //	 551	 1200
{ JA, SK, JA, JA, JA, WN, JA, JA, JA, TN, TN, JA, JA, SH, AC }, 	 //	 552	 1200
{ JA, JA, LO, JA, JA, WN, JA, JA, JA, JA, TN, JA, JA, JA, WN }, 	 //	 553	 1200
{ JA, JA, JA, SK, AC, WN, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 554	 1200
{ JA, JA, JA, SK, CR, WN, JA, JA, JA, KN, TN, JA, JA, JA, KN }, 	 //	 555	 1200
{ JA, JA, JA, SK, QN, WN, JA, JA, JA, QN, TN, JA, JA, JA, QN }, 	 //	 556	 1200
{ JA, JA, JA, SK, QN, WN, JA, JA, JA, QN, TN, JA, JA, JA, SH }, 	 //	 557	 1200
{ JA, JA, JA, SK, WN, WN, JA, JA, JA, TN, TN, JA, JA, JA, TN }, 	 //	 558	 1200
{ JA, JA, JA, SK, TN, WN, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 559	 1200
{ JA, JA, JA, SK, AC, WN, JA, JA, JA, AC, TN, JA, JA, JA, SK }, 	 //	 560	 1200
{ JA, JA, JA, SK, KN, WN, JA, JA, JA, KN, TN, JA, JA, JA, KN }, 	 //	 561	 1200
{ JA, JA, JA, SK, KN, WN, JA, JA, JA, AC, TN, JA, JA, JA, LO }, 	 //	 562	 1200
{ JA, JA, JA, JA, LO, WN, JA, JA, JA, AC, TN, JA, JA, SH, AC }, 	 //	 563	 1200
{ JA, JA, JA, JA, AC, WN, JA, JA, JA, KN, TN, JA, JA, SH, QN }, 	 //	 564	 1200
{ JA, JA, JA, JA, KN, WN, JA, JA, JA, QN, TN, JA, JA, SH, PF }, 	 //	 565	 1200
{ JA, JA, JA, JA, QN, WN, JA, JA, JA, KN, TN, JA, JA, SH, AC }, 	 //	 566	 1200
{ JA, JA, JA, ST, QN, WN, JA, JA, JA, SH, TN, JA, JA, TN, JA }, 	 //	 567	 1200
{ JA, JA, JA, ST, PF, WN, JA, JA, JA, JA, TN, JA, JA, TN, TN }, 	 //	 568	 1200
{ JA, JA, JA, JA, SH, WN, JA, JA, JA, JA, TN, JA, ST, SH, JA }, 	 //	 569	 1200
{ JA, JA, LO, JA, JA, WN, JA, JA, JA, JA, TN, SH, JA, JA, JA }, 	 //	 570	 1200
{ JA, JA, JA, JA, LO, WN, JA, JA, JA, AC, TN, SH, JA, JA, AC }, 	 //	 571	 1200
{ JA, JA, JA, JA, QN, WN, JA, JA, JA, QN, TN, SH, JA, JA, QN }, 	 //	 572	 1200
{ JA, JA, JA, JA, TN, WN, JA, JA, JA, TN, TN, SH, JA, JA, TN }, 	 //	 573	 1200
{ JA, JA, JA, JA, TN, WN, JA, JA, JA, ST, TN, SH, JA, JA, AC }, 	 //	 574	 1200
{ JA, JA, JA, JA, AC, WN, JA, JA, JA, KN, TN, SH, JA, JA, QN }, 	 //	 575	 1200
{ JA, JA, JA, JA, KN, WN, JA, JA, JA, KN, TN, SH, JA, JA, KN }, 	 //	 576	 1200
{ JA, JA, JA, JA, CR, WN, JA, JA, JA, QN, TN, SH, JA, JA, KN }, 	 //	 577	 1200
{ JA, JA, JA, JA, QN, WN, JA, JA, JA, KN, TN, SH, JA, JA, AC }, 	 //	 578	 1200
{ JA, JA, JA, JA, AC, WN, JA, JA, JA, AC, TN, SH, JA, SH, CR }, 	 //	 579	 1200
{ JA, JA, JA, JA, CR, WN, JA, JA, JA, KN, TN, SH, JA, SH, KN }, 	 //	 580	 1200
{ JA, JA, JA, JA, WN, WN, JA, JA, JA, TN, TN, SH, JA, SH, TN }, 	 //	 581	 1200
{ JA, JA, JA, JA, TN, WN, JA, JA, JA, ST, TN, SH, JA, SH, AC }, 	 //	 582	 1200
{ JA, JA, JA, JA, AC, WN, JA, JA, JA, AC, TN, SH, JA, SH, SK }, 	 //	 583	 1200
{ JA, JA, JA, JA, KN, WN, JA, JA, JA, AC, TN, SH, JA, SH, LO }, 	 //	 584	 1200
{ JA, JA, JA, ST, PF, WN, JA, JA, JA, JA, TN, SH, JA, TN, TN }, 	 //	 585	 1200
{ JA, JA, JA, JA, SH, WN, JA, JA, JA, JA, TN, SH, ST, SH, JA }, 	 //	 586	 1200
{ JA, JA, QN, QN, QN, WN, JA, SK, QN, QN, TN, SH, JA, QN, QN }, 	 //	 587	 1200
{ JA, JA, QN, QN, QN, WN, JA, SK, QN, QN, TN, SH, JA, SK, QN }, 	 //	 588	 1200
{ JA, TN, TN, TN, TN, WN, TN, TN, TN, TN, TN, TN, TN, TN, TN }, 	 //	 589	 1200
{ JA, ST, LO, SK, JA, WN, JA, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 590	 1200
{ JA, ST, LO, JA, JA, WN, JA, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 591	 1200
{ JA, ST, JA, SK, JA, WN, JA, JA, JA, JA, TN, TN, JA, JA, WN }, 	 //	 592	 1200
{ JA, ST, JA, SK, QN, WN, JA, JA, JA, PF, TN, TN, JA, JA, JA }, 	 //	 593	 1200
{ JA, ST, JA, ST, SH, WN, JA, JA, JA, JA, TN, TN, JA, TN, JA }, 	 //	 594	 1200
{ WN, QN, QN, QN, QN, TN, QN, SK, ST, SH, TN, SK, JA, JA, JA }, 	 //	 595	 1200
{ WN, SK, LO, SK, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 596	 1200
{ WN, SK, JA, SK, QN, TN, JA, JA, JA, SH, TN, JA, JA, JA, JA }, 	 //	 597	 1200
{ WN, SK, JA, JA, QN, TN, JA, JA, JA, SH, TN, JA, JA, JA, JA }, 	 //	 598	 1200
{ WN, SK, JA, JA, JA, TN, JA, JA, JA, WN, TN, JA, JA, JA, TN }, 	 //	 599	 1200
{ WN, JA, LO, SK, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 600	 1200
{ WN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN, JA, ST, SH, JA }, 	 //	 601	 1200
{ WN, JA, JA, SK, SH, TN, JA, JA, JA, JA, TN, SH, JA, JA, JA }, 	 //	 602	 1200
{ WN, JA, JA, JA, JA, TN, JA, JA, JA, WN, TN, SH, JA, SH, TN }, 	 //	 603	 1200
{ WN, JA, JA, ST, JA, TN, JA, JA, JA, JA, TN, SH, JA, TN, JA }, 	 //	 604	 1200
{ WN, QN, QN, QN, QN, TN, ST, SK, ST, QN, TN, JA, JA, JA, QN }, 	 //	 605	 1200
{ WN, ST, JA, SK, SH, TN, JA, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 606	 1200
{ WN, JA, JA, JA, JA, TN, TN, JA, JA, JA, TN, AC, JA, JA, JA }, 	 //	 607	 1200
{ TN, QN, QN, QN, QN, TN, QN, SK, ST, PF, TN, QN, JA, JA, JA }, 	 //	 608	 1200
{ TN, QN, JA, JA, JA, TN, SK, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 609	 1200
{ TN, SK, LO, SK, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 610	 1200
{ TN, SK, JA, JA, QN, TN, JA, JA, JA, PF, TN, JA, JA, JA, JA }, 	 //	 611	 1200
{ TN, SK, JA, ST, JA, TN, JA, JA, JA, JA, TN, JA, JA, TN, JA }, 	 //	 612	 1200
{ TN, JA, JA, SK, QN, TN, JA, JA, JA, SH, TN, JA, JA, JA, JA }, 	 //	 613	 1200
{ TN, JA, JA, SK, JA, TN, JA, JA, JA, JA, TN, JA, JA, JA, WN }, 	 //	 614	 1200
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, WN, TN, JA, JA, SH, TN }, 	 //	 615	 1200
{ TN, JA, JA, SK, SH, TN, JA, JA, JA, JA, TN, SH, JA, JA, JA }, 	 //	 616	 1200
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN, SH, ST, JA, JA }, 	 //	 617	 1200
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, JA, TN, SH, ST, SH, JA }, 	 //	 618	 1200
{ TN, SH, KN, LO, ST, TN, TN, WN, KN, AC, TN, TN, TN, KN, KN }, 	 //	 619	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, KN, SK, TN, TN, TN, KN, QN }, 	 //	 620	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, KN, QN, TN, TN, TN, KN, PF }, 	 //	 621	 1200
{ TN, SH, KN, KN, CR, TN, TN, WN, KN, QN, TN, TN, TN, KN, KN }, 	 //	 622	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, KN, AC, TN, TN, TN, KN, LO }, 	 //	 623	 1200
{ TN, SH, KN, KN, SK, TN, TN, WN, KN, KN, TN, TN, TN, WN, KN }, 	 //	 624	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, WN, KN, TN, TN, TN, QN, KN }, 	 //	 625	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, WN, AC, TN, TN, TN, QN, LO }, 	 //	 626	 1200
{ TN, SH, KN, AC, KN, TN, TN, WN, KN, KN, TN, TN, TN, QN, KN }, 	 //	 627	 1200
{ TN, SH, KN, AC, ST, TN, TN, WN, KN, AC, TN, TN, TN, QN, KN }, 	 //	 628	 1200
{ TN, SH, KN, PF, SK, TN, TN, WN, KN, KN, TN, TN, TN, KN, KN }, 	 //	 629	 1200
{ TN, SH, KN, KN, CR, TN, TN, WN, KN, KN, TN, TN, TN, KN, KN }, 	 //	 630	 1200
{ TN, SH, KN, KN, CR, TN, TN, WN, KN, QN, TN, TN, TN, KN, KN }, 	 //	 631	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, KN, AC, TN, TN, TN, KN, LO }, 	 //	 632	 1200
{ TN, SH, KN, QN, KN, TN, TN, WN, KN, KN, TN, TN, TN, AC, KN }, 	 //	 633	 1200
{ TN, SH, KN, QN, AC, TN, TN, WN, KN, SK, TN, TN, TN, AC, KN }, 	 //	 634	 1200
{ TN, SH, KN, QN, KN, TN, TN, WN, KN, KN, TN, TN, TN, AC, KN }, 	 //	 635	 1200
{ TN, SH, KN, KN, KN, TN, TN, WN, AC, AC, TN, TN, TN, PF, LO }, 	 //	 636	 1200
{ TN, TN, KN, LO, AC, TN, TN, WN, KN, SK, TN, TN, TN, KN, KN }, 	 //	 637	 1200
{ TN, TN, KN, LO, CR, TN, TN, WN, KN, QN, TN, TN, TN, KN, KN }, 	 //	 638	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, KN, SK, TN, TN, TN, KN, QN }, 	 //	 639	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, KN, KN, TN, TN, TN, KN, CR }, 	 //	 640	 1200
{ TN, TN, KN, KN, ST, TN, TN, WN, KN, AC, TN, TN, TN, WN, KN }, 	 //	 641	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, KN, QN, TN, TN, TN, WN, PF }, 	 //	 642	 1200
{ TN, TN, KN, KN, SK, TN, TN, WN, KN, KN, TN, TN, TN, WN, KN }, 	 //	 643	 1200
{ TN, TN, KN, KN, CR, TN, TN, WN, KN, QN, TN, TN, TN, WN, KN }, 	 //	 644	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, WN, KN, TN, TN, TN, QN, CR }, 	 //	 645	 1200
{ TN, TN, KN, AC, CR, TN, TN, WN, KN, KN, TN, TN, TN, QN, KN }, 	 //	 646	 1200
{ TN, TN, KN, AC, KN, TN, TN, WN, KN, KN, TN, TN, TN, QN, KN }, 	 //	 647	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, QN, SK, TN, TN, TN, ST, QN }, 	 //	 648	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, QN, QN, TN, TN, TN, ST, PF }, 	 //	 649	 1200
{ TN, TN, KN, PF, AC, TN, TN, WN, KN, SK, TN, TN, TN, KN, KN }, 	 //	 650	 1200
{ TN, TN, KN, KN, CR, TN, TN, WN, KN, KN, TN, TN, TN, SK, KN }, 	 //	 651	 1200
{ TN, TN, KN, KN, AC, TN, TN, WN, KN, SK, TN, TN, TN, SK, KN }, 	 //	 652	 1200
{ TN, TN, KN, KN, CR, TN, TN, WN, KN, QN, TN, TN, TN, SK, KN }, 	 //	 653	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, AC, KN, TN, TN, TN, PF, KN }, 	 //	 654	 1200
{ TN, TN, KN, KN, KN, TN, TN, WN, AC, KN, TN, TN, TN, PF, KN }, 	 //	 655	 1200
{ TN, ST, JA, ST, JA, TN, JA, JA, JA, JA, TN, TN, JA, TN, JA }, 	 //	 656	 1200
{ TN, QN, QN, QN, QN, TN, KN, SK, ST, SH, TN, AC, JA, JA, JA }, 	 //	 657	 1200
{ TN, QN, QN, QN, QN, TN, QN, SK, ST, SH, ST, QN, JA, JA, JA }, 	 //	 658	 1200
{ TN, QN, QN, QN, QN, TN, QN, SK, ST, PF, ST, QN, JA, JA, JA }, 	 //	 659	 1200
{ TN, QN, QN, QN, QN, TN, QN, SK, ST, PF, ST, SK, JA, JA, JA }, 	 //	 660	 1200
{ TN, SK, JA, JA, QN, TN, JA, JA, JA, SH, ST, JA, JA, JA, JA }, 	 //	 661	 1200
{ TN, SK, JA, JA, JA, TN, JA, JA, JA, TN, ST, JA, JA, JA, AC }, 	 //	 662	 1200
{ TN, SK, JA, JA, JA, TN, JA, JA, JA, JA, ST, JA, JA, SH, WN }, 	 //	 663	 1200
{ TN, SK, JA, ST, JA, TN, JA, JA, JA, JA, ST, JA, JA, TN, JA }, 	 //	 664	 1200
{ TN, JA, JA, JA, PF, TN, JA, JA, JA, JA, ST, JA, JA, JA, TN }, 	 //	 665	 1200
{ TN, JA, JA, JA, SH, TN, JA, JA, JA, JA, ST, JA, JA, SH, JA }, 	 //	 666	 1200
{ TN, JA, JA, JA, QN, TN, JA, JA, JA, PF, ST, SH, JA, JA, JA }, 	 //	 667	 1200
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, WN, ST, SH, JA, SH, TN }, 	 //	 668	 1200
{ TN, JA, JA, JA, JA, TN, JA, JA, JA, TN, ST, SH, JA, SH, AC }, 	 //	 669	 1200
{ TN, QN, JA, JA, JA, TN, ST, JA, JA, JA, ST, JA, JA, JA, JA }, 	 //	 670	 1200
{ TN, QN, QN, QN, QN, TN, ST, SK, ST, QN, ST, JA, JA, JA, SH }, 	 //	 671	 1200
{ TN, ST, JA, JA, JA, TN, JA, JA, JA, JA, ST, TN, JA, JA, WN }, 	 //	 672	 1200
{ TN, ST, JA, JA, JA, TN, JA, JA, JA, JA, ST, TN, JA, SH, WN }, 	 //	 673	 1200
{ TN, JA, JA, JA, JA, TN, TN, JA, JA, JA, ST, AC, JA, JA, JA }, 	 //	 674	 1200
{ TN, QN, QN, QN, QN, TN, KN, SK, ST, SH, ST, AC, JA, JA, JA }, 	 //	 675	 1200
{ TN, QN, QN, QN, QN, ST, QN, SK, ST, SH, AC, QN, JA, JA, JA }, 	 //	 676	 1200
{ TN, QN, JA, JA, JA, ST, SK, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 677	 1200
{ TN, SK, JA, SK, QN, ST, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 678	 1200
{ TN, JA, LO, JA, JA, ST, JA, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 679	 1200
{ TN, JA, JA, JA, JA, ST, JA, JA, JA, WN, AC, JA, JA, SH, TN }, 	 //	 680	 1200
{ TN, JA, JA, ST, JA, ST, JA, JA, JA, JA, AC, JA, JA, TN, JA }, 	 //	 681	 1200
{ TN, JA, JA, JA, JA, ST, JA, JA, JA, JA, AC, JA, ST, JA, JA }, 	 //	 682	 1200
{ TN, JA, JA, JA, JA, ST, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 683	 1200
{ TN, JA, JA, JA, JA, ST, JA, JA, JA, WN, AC, SH, JA, JA, TN }, 	 //	 684	 1200
{ TN, JA, JA, JA, JA, ST, JA, JA, JA, TN, AC, SH, JA, SH, AC }, 	 //	 685	 1200
{ TN, JA, JA, ST, JA, ST, JA, JA, JA, JA, AC, SH, JA, TN, JA }, 	 //	 686	 1200
{ TN, QN, QN, QN, QN, ST, ST, SK, ST, QN, AC, JA, JA, JA, QN }, 	 //	 687	 1200
{ TN, JA, JA, JA, JA, ST, TN, JA, JA, JA, AC, AC, JA, JA, JA }, 	 //	 688	 1200
{ ST, KN, KN, TN, TN, AC, KN, WN, TN, TN, KN, ST, TN, TN, TN }, 	 //	 689	 1200
{ ST, SK, JA, SK, QN, AC, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 690	 1200
{ ST, SK, JA, SK, JA, AC, JA, JA, JA, JA, KN, JA, JA, JA, WN }, 	 //	 691	 1200
{ ST, SK, JA, SK, QN, AC, JA, JA, JA, PF, KN, JA, JA, JA, JA }, 	 //	 692	 1200
{ ST, SK, JA, JA, JA, AC, JA, JA, JA, TN, KN, JA, JA, JA, AC }, 	 //	 693	 1200
{ ST, SK, JA, ST, JA, AC, JA, JA, JA, JA, KN, JA, JA, TN, JA }, 	 //	 694	 1200
{ ST, JA, LO, SK, JA, AC, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 695	 1200
{ ST, JA, JA, SK, QN, AC, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 696	 1200
{ ST, JA, JA, JA, JA, AC, JA, JA, JA, TN, KN, JA, JA, SH, AC }, 	 //	 697	 1200
{ ST, JA, JA, JA, QN, AC, JA, JA, JA, SH, KN, SH, JA, JA, JA }, 	 //	 698	 1200
{ ST, JA, JA, JA, JA, AC, JA, JA, JA, TN, KN, SH, JA, SH, AC }, 	 //	 699	 1200
{ ST, JA, JA, JA, JA, AC, JA, JA, JA, JA, KN, SH, ST, JA, JA }, 	 //	 700	 1200
{ ST, PF, KN, TN, TN, AC, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 701	 1200
{ ST, KN, KN, SH, TN, AC, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 702	 1200
{ ST, KN, KN, TN, TN, AC, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 703	 1200
{ ST, QN, KN, TN, TN, AC, KN, WN, TN, TN, KN, AC, TN, TN, TN }, 	 //	 704	 1200
{ AC, ST, QN, QN, QN, KN, QN, SK, ST, PF, QN, QN, JA, JA, JA }, 	 //	 705	 1200
{ AC, QN, QN, QN, JA, KN, QN, SK, ST, JA, QN, SK, JA, JA, JA }, 	 //	 706	 1200
{ AC, SK, JA, JA, JA, KN, JA, JA, JA, WN, QN, JA, JA, JA, TN }, 	 //	 707	 1200
{ AC, SK, JA, ST, JA, KN, JA, JA, JA, JA, QN, JA, JA, TN, JA }, 	 //	 708	 1200
{ AC, JA, JA, SK, QN, KN, JA, JA, JA, PF, QN, JA, JA, JA, JA }, 	 //	 709	 1200
{ AC, JA, JA, JA, PF, KN, JA, JA, JA, JA, QN, JA, JA, JA, TN }, 	 //	 710	 1200
{ AC, JA, JA, ST, JA, KN, JA, JA, JA, JA, QN, JA, JA, TN, JA }, 	 //	 711	 1200
{ AC, JA, JA, JA, QN, KN, JA, JA, JA, SH, QN, SH, JA, JA, JA }, 	 //	 712	 1200
{ AC, JA, JA, JA, JA, KN, JA, JA, JA, TN, QN, SH, JA, SH, AC }, 	 //	 713	 1200
{ AC, KN, QN, QN, QN, KN, QN, SK, ST, PF, QN, ST, JA, JA, JA }, 	 //	 714	 1200
{ AC, QN, JA, JA, JA, KN, ST, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 715	 1200
{ AC, ST, JA, JA, SH, KN, JA, JA, JA, JA, QN, TN, JA, JA, JA }, 	 //	 716	 1200
{ AC, ST, JA, JA, JA, KN, JA, JA, JA, JA, QN, TN, JA, JA, WN }, 	 //	 717	 1200
{ AC, SK, QN, QN, QN, KN, QN, SK, ST, SH, QN, KN, JA, JA, JA }, 	 //	 718	 1200
{ KN, KN, KN, SH, TN, QN, KN, WN, TN, TN, PF, KN, TN, TN, TN }, 	 //	 719	 1200
{ KN, KN, KN, TN, TN, QN, KN, WN, TN, TN, PF, KN, TN, TN, TN }, 	 //	 720	 1200
{ KN, QN, QN, QN, QN, QN, QN, SK, ST, SH, PF, QN, JA, JA, JA }, 	 //	 721	 1200
{ KN, QN, JA, JA, JA, QN, SK, JA, JA, JA, PF, JA, JA, JA, JA }, 	 //	 722	 1200
{ KN, SK, JA, SK, QN, QN, JA, JA, JA, SH, PF, JA, JA, JA, JA }, 	 //	 723	 1200
{ KN, SK, JA, JA, JA, QN, JA, JA, JA, JA, PF, JA, JA, SH, WN }, 	 //	 724	 1200
{ KN, JA, LO, JA, JA, QN, JA, JA, JA, JA, PF, JA, JA, JA, JA }, 	 //	 725	 1200
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, WN, PF, JA, JA, SH, TN }, 	 //	 726	 1200
{ KN, JA, JA, ST, JA, QN, JA, JA, JA, JA, PF, JA, JA, TN, JA }, 	 //	 727	 1200
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, JA, PF, JA, ST, SH, JA }, 	 //	 728	 1200
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, TN, PF, SH, JA, JA, AC }, 	 //	 729	 1200
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, TN, PF, SH, JA, SH, AC }, 	 //	 730	 1200
{ KN, JA, JA, JA, JA, QN, JA, JA, JA, JA, PF, SH, ST, SH, JA }, 	 //	 731	 1200
{ KN, KN, KN, SH, TN, QN, QN, WN, TN, TN, PF, ST, TN, TN, TN }, 	 //	 732	 1200
{ KN, QN, QN, QN, QN, QN, ST, SK, ST, QN, PF, JA, JA, JA, QN }, 	 //	 733	 1200
{ KN, QN, QN, QN, QN, QN, ST, SK, ST, QN, PF, JA, JA, JA, SH }, 	 //	 734	 1200
{ KN, QN, QN, QN, QN, QN, ST, SK, ST, KN, PF, JA, JA, JA, AC }, 	 //	 735	 1200
{ KN, ST, JA, JA, JA, QN, JA, JA, JA, JA, PF, TN, JA, JA, WN }, 	 //	 736	 1200
{ KN, ST, JA, JA, JA, QN, JA, JA, JA, JA, PF, TN, JA, SH, WN }, 	 //	 737	 1200
{ KN, JA, JA, JA, JA, QN, TN, JA, JA, JA, PF, AC, JA, JA, JA }, 	 //	 738	 1200
{ QN, SK, JA, SK, AC, PF, JA, JA, JA, LO, JA, JA, JA, JA, AC }, 	 //	 739	 1200
{ QN, SK, JA, SK, KN, PF, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 740	 1200
{ QN, SK, JA, SK, QN, PF, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 741	 1200
{ QN, SK, JA, SK, TN, PF, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 742	 1200
{ QN, SK, JA, SK, TN, PF, JA, JA, JA, TN, JA, JA, JA, JA, ST }, 	 //	 743	 1200
{ QN, SK, JA, SK, ST, PF, JA, JA, JA, AC, JA, JA, JA, JA, KN }, 	 //	 744	 1200
{ QN, SK, JA, SK, CR, PF, JA, JA, JA, QN, JA, JA, JA, JA, KN }, 	 //	 745	 1200
{ QN, SK, JA, JA, AC, PF, JA, JA, JA, LO, JA, JA, JA, JA, AC }, 	 //	 746	 1200
{ QN, SK, JA, JA, AC, PF, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 747	 1200
{ QN, SK, JA, JA, SK, PF, JA, JA, JA, QN, JA, JA, JA, JA, QN }, 	 //	 748	 1200
{ QN, SK, JA, JA, TN, PF, JA, JA, JA, TN, JA, JA, JA, JA, ST }, 	 //	 749	 1200
{ QN, SK, JA, JA, AC, PF, JA, JA, JA, KN, JA, JA, JA, JA, QN }, 	 //	 750	 1200
{ QN, SK, JA, JA, TN, PF, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 751	 1200
{ QN, SK, JA, JA, KN, PF, JA, JA, JA, KN, JA, JA, JA, JA, KN }, 	 //	 752	 1200
{ QN, SK, JA, JA, QN, PF, JA, JA, JA, PF, JA, JA, JA, SH, JA }, 	 //	 753	 1200
{ QN, SK, QN, QN, QN, PF, JA, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 754	 1200
{ QN, SK, QN, QN, QN, PF, JA, SK, QN, QN, JA, JA, JA, SK, QN }, 	 //	 755	 1200
{ QN, JA, JA, SK, AC, PF, JA, JA, JA, AC, JA, JA, JA, JA, AC }, 	 //	 756	 1200
{ QN, JA, JA, SK, WN, PF, JA, JA, JA, TN, JA, JA, JA, JA, TN }, 	 //	 757	 1200
{ QN, JA, JA, SK, TN, PF, JA, JA, JA, ST, JA, JA, JA, JA, AC }, 	 //	 758	 1200
{ QN, JA, JA, JA, AC, PF, JA, JA, JA, LO, JA, JA, JA, SH, AC }, 	 //	 759	 1200
{ QN, JA, JA, JA, WN, PF, JA, JA, JA, TN, JA, JA, JA, SH, TN }, 	 //	 760	 1200
{ QN, JA, JA, JA, SK, PF, JA, JA, JA, KN, JA, JA, JA, SH, KN }, 	 //	 761	 1200
{ QN, JA, JA, JA, KN, PF, JA, JA, JA, AC, JA, JA, JA, SH, LO }, 	 //	 762	 1200
{ QN, JA, JA, ST, QN, PF, JA, JA, JA, SH, JA, JA, JA, TN, JA }, 	 //	 763	 1200
{ QN, JA, JA, SK, QN, PF, JA, JA, JA, SH, JA, SH, JA, JA, JA }, 	 //	 764	 1200
{ QN, JA, JA, JA, PF, PF, JA, JA, JA, JA, JA, SH, JA, JA, TN }, 	 //	 765	 1200
{ QN, JA, JA, JA, QN, PF, JA, JA, JA, SH, JA, SH, JA, SH, JA }, 	 //	 766	 1200
{ QN, JA, JA, JA, PF, PF, JA, JA, JA, JA, JA, SH, JA, SH, TN }, 	 //	 767	 1200
{ QN, JA, JA, ST, JA, PF, JA, JA, JA, JA, JA, SH, JA, TN, WN }, 	 //	 768	 1200
{ QN, JA, JA, JA, SH, PF, JA, JA, JA, JA, JA, SH, ST, SH, JA }, 	 //	 769	 1200
{ QN, JA, JA, JA, JA, PF, JA, JA, JA, JA, JA, SH, ST, SH, WN }, 	 //	 770	 1200
{ QN, QN, QN, WN, QN, PF, ST, SK, QN, QN, JA, JA, JA, QN, QN }, 	 //	 771	 1200
{ QN, QN, QN, QN, SH, PF, ST, SK, QN, JA, JA, JA, JA, QN, JA }, 	 //	 772	 1200
{ QN, QN, QN, QN, JA, PF, ST, SK, QN, JA, JA, JA, JA, QN, WN }, 	 //	 773	 1200
{ QN, QN, QN, QN, JA, PF, ST, SK, QN, WN, JA, JA, JA, QN, TN }, 	 //	 774	 1200
{ QN, QN, QN, QN, JA, PF, ST, SK, QN, TN, JA, JA, JA, QN, AC }, 	 //	 775	 1200
{ QN, QN, QN, QN, TN, PF, ST, SK, QN, AC, JA, JA, JA, QN, AC }, 	 //	 776	 1200
{ QN, QN, QN, QN, KN, PF, ST, SK, QN, KN, JA, JA, JA, QN, CR }, 	 //	 777	 1200
{ QN, QN, QN, QN, CR, PF, ST, SK, QN, QN, JA, JA, JA, QN, KN }, 	 //	 778	 1200
{ QN, QN, QN, QN, KN, PF, ST, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 779	 1200
{ QN, QN, QN, QN, JA, PF, ST, SK, QN, JA, JA, JA, JA, SK, JA }, 	 //	 780	 1200
{ QN, QN, QN, QN, WN, PF, ST, SK, QN, TN, JA, JA, JA, SK, TN }, 	 //	 781	 1200
{ QN, QN, QN, QN, ST, PF, ST, SK, QN, AC, JA, JA, JA, SK, KN }, 	 //	 782	 1200
{ QN, QN, QN, QN, TN, PF, ST, SK, QN, AC, JA, JA, JA, SK, AC }, 	 //	 783	 1200
{ QN, QN, QN, QN, AC, PF, ST, SK, QN, SK, JA, JA, JA, SK, KN }, 	 //	 784	 1200
{ QN, QN, QN, QN, SK, PF, ST, SK, QN, KN, JA, JA, JA, SK, KN }, 	 //	 785	 1200
{ QN, QN, QN, QN, KN, PF, ST, SK, QN, AC, JA, JA, JA, SK, LO }, 	 //	 786	 1200
{ QN, QN, QN, QN, AC, PF, ST, SK, KN, LO, JA, JA, JA, AC, AC }, 	 //	 787	 1200
{ QN, QN, QN, QN, LO, PF, ST, SK, KN, AC, JA, JA, JA, AC, AC }, 	 //	 788	 1200
{ QN, QN, QN, QN, KN, PF, ST, SK, KN, KN, JA, JA, JA, AC, KN }, 	 //	 789	 1200
{ QN, QN, QN, QN, TN, PF, ST, SK, KN, AC, JA, JA, JA, AC, AC }, 	 //	 790	 1200
{ QN, QN, QN, QN, AC, PF, ST, SK, KN, AC, JA, JA, JA, AC, SK }, 	 //	 791	 1200
{ QN, QN, QN, QN, AC, PF, ST, SK, KN, SK, JA, JA, JA, AC, KN }, 	 //	 792	 1200
{ QN, QN, QN, QN, KN, PF, ST, SK, KN, KN, JA, JA, JA, AC, KN }, 	 //	 793	 1200
{ QN, ST, JA, SK, QN, PF, JA, JA, JA, SH, JA, TN, JA, JA, JA }, 	 //	 794	 1200
{ QN, ST, JA, JA, JA, PF, JA, JA, JA, WN, JA, TN, JA, JA, TN }, 	 //	 795	 1200
{ QN, ST, JA, JA, JA, PF, JA, JA, JA, TN, JA, TN, JA, JA, AC }, 	 //	 796	 1200
{ QN, ST, JA, JA, SH, PF, JA, JA, JA, JA, JA, TN, JA, SH, JA }, 	 //	 797	 1200
{ QN, ST, JA, JA, JA, PF, JA, JA, JA, WN, JA, TN, JA, SH, TN }, 	 //	 798	 1200
{ QN, ST, JA, ST, SH, PF, JA, JA, JA, JA, JA, TN, JA, TN, JA }, 	 //	 799	 1200
{ QN, ST, JA, ST, JA, PF, JA, JA, JA, JA, JA, TN, JA, TN, WN }, 	 //	 800	 1200
{ PF, QN, JA, JA, JA, JA, SK, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 801	 1200
{ PF, SK, JA, SK, JA, JA, JA, JA, JA, WN, TN, JA, JA, JA, TN }, 	 //	 802	 1200
{ PF, SK, JA, JA, SH, JA, JA, JA, JA, JA, TN, JA, JA, SH, JA }, 	 //	 803	 1200
{ PF, SK, JA, JA, JA, JA, JA, JA, JA, TN, TN, JA, JA, SH, AC }, 	 //	 804	 1200
{ PF, JA, LO, SK, SH, JA, JA, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 805	 1200
{ PF, JA, LO, SK, JA, JA, JA, JA, JA, JA, TN, JA, JA, JA, WN }, 	 //	 806	 1200
{ PF, JA, LO, JA, SH, JA, JA, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 807	 1200
{ PF, JA, JA, SK, JA, JA, JA, JA, JA, WN, TN, JA, JA, JA, TN }, 	 //	 808	 1200
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 809	 1200
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA, CR }, 	 //	 810	 1200
{ PF, JA, JA, JA, CR, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN }, 	 //	 811	 1200
{ PF, JA, JA, JA, KN, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN }, 	 //	 812	 1200
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, QN, TN, JA, JA, JA, SH }, 	 //	 813	 1200
{ PF, JA, JA, JA, WN, JA, JA, JA, JA, TN, TN, JA, JA, JA, TN }, 	 //	 814	 1200
{ PF, JA, JA, JA, KN, JA, JA, JA, JA, QN, TN, JA, JA, JA, PF }, 	 //	 815	 1200
{ PF, JA, JA, JA, TN, JA, JA, JA, JA, AC, TN, JA, JA, JA, AC }, 	 //	 816	 1200
{ PF, JA, JA, JA, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA, SK }, 	 //	 817	 1200
{ PF, JA, JA, JA, SK, JA, JA, JA, JA, KN, TN, JA, JA, JA, KN }, 	 //	 818	 1200
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, SH, TN, JA, JA, SH, JA }, 	 //	 819	 1200
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, PF, TN, JA, JA, SH, JA }, 	 //	 820	 1200
{ PF, JA, JA, JA, JA, JA, JA, JA, JA, JA, TN, JA, ST, SH, WN }, 	 //	 821	 1200
{ PF, JA, LO, SK, JA, JA, JA, JA, JA, JA, TN, SH, JA, JA, JA }, 	 //	 822	 1200
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, SH, TN, SH, JA, SH, JA }, 	 //	 823	 1200
{ PF, JA, JA, JA, QN, JA, JA, JA, JA, PF, TN, SH, JA, SH, JA }, 	 //	 824	 1200
{ PF, JA, JA, ST, JA, JA, JA, JA, JA, JA, TN, SH, JA, TN, WN }, 	 //	 825	 1200
{ PF, TN, TN, TN, TN, JA, TN, TN, TN, TN, TN, TN, TN, TN, TN }, 	 //	 826	 1200
{ PF, QN, JA, JA, JA, JA, ST, JA, JA, JA, TN, JA, JA, JA, JA }, 	 //	 827	 1200
{ PF, QN, QN, QN, QN, JA, ST, SK, ST, QN, TN, JA, JA, JA, QN }, 	 //	 828	 1200
{ PF, QN, QN, QN, QN, JA, ST, SK, ST, KN, TN, JA, JA, JA, AC }, 	 //	 829	 1200
{ PF, ST, LO, SK, JA, JA, JA, JA, JA, JA, TN, TN, JA, JA, JA }, 	 //	 830	 1200
{ PF, ST, JA, SK, QN, JA, JA, JA, JA, SH, TN, TN, JA, JA, JA }, 	 //	 831	 1200
{ PF, ST, JA, ST, JA, JA, JA, JA, JA, JA, TN, TN, JA, TN, WN }, 	 //	 832	 1200
{ JA, QN, QN, QN, QN, TN, QN, SK, ST, PF, AC, QN, JA, JA, JA }, 	 //	 833	 1200
{ JA, QN, JA, JA, JA, TN, SK, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 834	 1200
{ JA, SK, JA, SK, JA, TN, JA, JA, JA, TN, AC, JA, JA, JA, AC }, 	 //	 835	 1200
{ JA, SK, JA, JA, SH, TN, JA, JA, JA, JA, AC, JA, JA, SH, JA }, 	 //	 836	 1200
{ JA, SK, JA, ST, SH, TN, JA, JA, JA, JA, AC, JA, JA, TN, JA }, 	 //	 837	 1200
{ JA, JA, LO, SK, SH, TN, JA, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 838	 1200
{ JA, JA, LO, JA, SH, TN, JA, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 839	 1200
{ JA, JA, JA, SK, CR, TN, JA, JA, JA, KN, AC, JA, JA, JA, KN }, 	 //	 840	 1200
{ JA, JA, JA, SK, ST, TN, JA, JA, JA, AC, AC, JA, JA, JA, KN }, 	 //	 841	 1200
{ JA, JA, JA, SK, AC, TN, JA, JA, JA, KN, AC, JA, JA, JA, QN }, 	 //	 842	 1200
{ JA, JA, JA, SK, KN, TN, JA, JA, JA, QN, AC, JA, JA, JA, PF }, 	 //	 843	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, LO, AC, JA, JA, SH, AC }, 	 //	 844	 1200
{ JA, JA, JA, JA, LO, TN, JA, JA, JA, AC, AC, JA, JA, SH, AC }, 	 //	 845	 1200
{ JA, JA, JA, JA, SK, TN, JA, JA, JA, QN, AC, JA, JA, SH, QN }, 	 //	 846	 1200
{ JA, JA, JA, JA, TN, TN, JA, JA, JA, TN, AC, JA, JA, SH, TN }, 	 //	 847	 1200
{ JA, JA, JA, JA, ST, TN, JA, JA, JA, AC, AC, JA, JA, SH, KN }, 	 //	 848	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, JA, JA, SH, AC }, 	 //	 849	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, SK, AC, JA, JA, SH, KN }, 	 //	 850	 1200
{ JA, JA, JA, ST, PF, TN, JA, JA, JA, JA, AC, JA, JA, TN, TN }, 	 //	 851	 1200
{ JA, JA, JA, JA, SH, TN, JA, JA, JA, JA, AC, JA, ST, SH, JA }, 	 //	 852	 1200
{ JA, JA, LO, JA, JA, TN, JA, JA, JA, JA, AC, SH, JA, JA, JA }, 	 //	 853	 1200
{ JA, JA, JA, SK, JA, TN, JA, JA, JA, WN, AC, SH, JA, JA, TN }, 	 //	 854	 1200
{ JA, JA, JA, SK, PF, TN, JA, JA, JA, JA, AC, SH, JA, JA, TN }, 	 //	 855	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, SH, JA, JA, AC }, 	 //	 856	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, SH, JA, JA, CR }, 	 //	 857	 1200
{ JA, JA, JA, JA, TN, TN, JA, JA, JA, TN, AC, SH, JA, JA, TN }, 	 //	 858	 1200
{ JA, JA, JA, JA, ST, TN, JA, JA, JA, AC, AC, SH, JA, JA, KN }, 	 //	 859	 1200
{ JA, JA, JA, JA, KN, TN, JA, JA, JA, QN, AC, SH, JA, JA, PF }, 	 //	 860	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, SH, JA, JA, AC }, 	 //	 861	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, AC, AC, SH, JA, JA, SK }, 	 //	 862	 1200
{ JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, SH, JA, JA, KN }, 	 //	 863	 1200
{ JA, JA, JA, JA, KN, TN, JA, JA, JA, AC, AC, SH, JA, JA, LO }, 	 //	 864	 1200
{ JA, JA, JA, JA, LO, TN, JA, JA, JA, AC, AC, SH, JA, SH, AC }, 	 //	 865	 1200
{ JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, SH, JA, SH, KN }, 	 //	 866	 1200
{ JA, JA, JA, JA, QN, TN, JA, JA, JA, QN, AC, SH, JA, SH, QN }, 	 //	 867	 1200
{ JA, JA, JA, JA, TN, TN, JA, JA, JA, TN, AC, SH, JA, SH, TN }, 	 //	 868	 1200
{ JA, JA, JA, JA, AC, TN, JA, JA, JA, SK, AC, SH, JA, SH, KN }, 	 //	 869	 1200
{ JA, JA, JA, JA, KN, TN, JA, JA, JA, KN, AC, SH, JA, SH, KN }, 	 //	 870	 1200
{ JA, JA, JA, JA, CR, TN, JA, JA, JA, QN, AC, SH, JA, SH, KN }, 	 //	 871	 1200
{ JA, JA, JA, JA, QN, TN, JA, JA, JA, KN, AC, SH, JA, SH, AC }, 	 //	 872	 1200
{ JA, JA, JA, JA, JA, TN, JA, JA, JA, JA, AC, SH, ST, SH, WN }, 	 //	 873	 1200
{ JA, JA, QN, QN, QN, TN, JA, SK, QN, QN, AC, SH, JA, SK, QN }, 	 //	 874	 1200
{ JA, QN, QN, QN, QN, TN, ST, SK, ST, QN, AC, JA, JA, JA, QN }, 	 //	 875	 1200
{ JA, QN, QN, QN, QN, TN, ST, SK, ST, QN, AC, JA, JA, JA, SH }, 	 //	 876	 1200
{ JA, ST, JA, JA, SH, TN, JA, JA, JA, JA, AC, TN, JA, SH, JA }, 	 //	 877	 1200
{ JA, ST, JA, JA, JA, TN, JA, JA, JA, WN, AC, TN, JA, SH, TN }, 	 //	 878	 1200
{ JA, ST, JA, JA, JA, TN, JA, JA, JA, TN, AC, TN, JA, SH, AC }, 	 //	 879	 1200
{ TN, SK, JA, JA, QN, AC, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 880	 1200
{ TN, SK, JA, JA, QN, AC, JA, JA, JA, PF, AC, JA, JA, JA, JA }, 	 //	 881	 1200
{ TN, JA, JA, SK, QN, AC, JA, JA, JA, SH, AC, JA, JA, JA, JA }, 	 //	 882	 1200
{ TN, JA, JA, SK, QN, AC, JA, JA, JA, PF, AC, JA, JA, JA, JA }, 	 //	 883	 1200
{ TN, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, SH, ST, SH, JA }, 	 //	 884	 1200
{ TN, QN, QN, QN, QN, AC, ST, SK, ST, QN, AC, JA, JA, JA, QN }, 	 //	 885	 1200
{ TN, ST, JA, SK, SH, AC, JA, JA, JA, JA, AC, TN, JA, JA, JA }, 	 //	 886	 1200
{ TN, QN, QN, QN, QN, AC, KN, SK, ST, PF, AC, AC, JA, JA, JA }, 	 //	 887	 1200
{ AC, QN, QN, QN, QN, AC, QN, SK, ST, SH, AC, QN, JA, JA, JA }, 	 //	 888	 1200
{ AC, QN, QN, QN, QN, AC, QN, SK, ST, SH, AC, SK, JA, JA, JA }, 	 //	 889	 1200
{ AC, SK, JA, JA, QN, AC, JA, JA, JA, PF, AC, JA, JA, JA, JA }, 	 //	 890	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, TN, AC, JA, JA, SH, AC }, 	 //	 891	 1200
{ AC, JA, JA, ST, JA, AC, JA, JA, JA, JA, AC, JA, JA, TN, JA }, 	 //	 892	 1200
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, SH, AC, SH, JA, JA, JA }, 	 //	 893	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, WN, AC, SH, JA, JA, TN }, 	 //	 894	 1200
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, PF, AC, SH, JA, JA, JA }, 	 //	 895	 1200
{ AC, JA, JA, ST, JA, AC, JA, JA, JA, JA, AC, SH, JA, TN, JA }, 	 //	 896	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, AC, SH, ST, JA, JA }, 	 //	 897	 1200
{ AC, QN, JA, JA, JA, AC, ST, JA, JA, JA, AC, JA, JA, JA, JA }, 	 //	 898	 1200
{ AC, QN, QN, QN, QN, AC, ST, SK, ST, QN, AC, JA, JA, JA, QN }, 	 //	 899	 1200
{ AC, QN, QN, QN, QN, AC, ST, SK, ST, QN, AC, JA, JA, JA, SH }, 	 //	 900	 1200
{ AC, QN, QN, QN, QN, AC, ST, SK, ST, KN, AC, JA, JA, JA, AC }, 	 //	 901	 1200
{ AC, QN, QN, QN, QN, AC, KN, SK, ST, PF, AC, AC, JA, JA, JA }, 	 //	 902	 1200
{ AC, QN, QN, QN, SH, AC, SK, SK, SK, JA, SK, JA, JA, JA, JA }, 	 //	 903	 1200
{ AC, QN, QN, QN, JA, AC, SK, SK, SK, JA, SK, JA, JA, JA, JA }, 	 //	 904	 1200
{ AC, SK, JA, SK, JA, AC, JA, JA, JA, JA, SK, JA, JA, JA, WN }, 	 //	 905	 1200
{ AC, JA, LO, SK, JA, AC, JA, JA, JA, JA, SK, JA, JA, JA, JA }, 	 //	 906	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, SK, JA, ST, JA, JA }, 	 //	 907	 1200
{ AC, JA, JA, JA, QN, AC, JA, JA, JA, SH, SK, SH, JA, JA, JA }, 	 //	 908	 1200
{ AC, JA, JA, JA, JA, AC, JA, JA, JA, JA, SK, SH, ST, SH, JA }, 	 //	 909	 1200
{ AC, ST, JA, SK, SH, AC, JA, JA, JA, JA, SK, TN, JA, JA, JA }, 	 //	 910	 1200
{ AC, ST, JA, JA, SH, AC, JA, JA, JA, JA, SK, TN, JA, JA, JA }, 	 //	 911	 1200
{ AC, ST, JA, JA, JA, AC, JA, JA, JA, JA, SK, TN, JA, JA, WN }, 	 //	 912	 1200
{ AC, LO, KN, TN, TN, SK, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 913	 1200
{ AC, KN, KN, SH, TN, SK, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 914	 1200
{ AC, QN, QN, QN, QN, SK, QN, SK, ST, SH, KN, QN, JA, JA, JA }, 	 //	 915	 1200
{ AC, QN, QN, QN, QN, SK, QN, SK, ST, PF, KN, QN, JA, JA, JA }, 	 //	 916	 1200
{ AC, QN, QN, QN, KN, SK, SK, SK, SK, SK, KN, JA, JA, JA, QN }, 	 //	 917	 1200
{ AC, SK, LO, SK, JA, SK, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 918	 1200
{ AC, JA, JA, JA, SH, SK, JA, JA, JA, JA, KN, JA, JA, SH, JA }, 	 //	 919	 1200
{ AC, JA, JA, JA, JA, SK, JA, JA, JA, WN, KN, JA, JA, SH, TN }, 	 //	 920	 1200
{ AC, JA, JA, ST, JA, SK, JA, JA, JA, JA, KN, JA, JA, TN, JA }, 	 //	 921	 1200
{ AC, JA, JA, JA, JA, SK, JA, JA, JA, JA, KN, JA, ST, SH, JA }, 	 //	 922	 1200
{ AC, JA, JA, SK, SH, SK, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 923	 1200
{ AC, JA, JA, JA, JA, SK, JA, JA, JA, WN, KN, SH, JA, JA, TN }, 	 //	 924	 1200
{ AC, JA, JA, JA, SH, SK, JA, JA, JA, JA, KN, SH, JA, SH, JA }, 	 //	 925	 1200
{ AC, JA, JA, ST, JA, SK, JA, JA, JA, JA, KN, SH, JA, TN, JA }, 	 //	 926	 1200
{ AC, JA, JA, JA, JA, SK, JA, JA, JA, JA, KN, SH, ST, SH, JA }, 	 //	 927	 1200
{ AC, JA, JA, JA, JA, SK, SH, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 928	 1200
{ AC, ST, JA, JA, SH, SK, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 929	 1200
{ AC, ST, JA, JA, JA, SK, JA, JA, JA, JA, KN, TN, JA, JA, WN }, 	 //	 930	 1200
{ AC, PF, KN, SH, TN, SK, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 931	 1200
{ AC, PF, KN, TN, TN, SK, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 932	 1200
{ AC, QN, QN, QN, QN, SK, KN, SK, ST, SH, KN, AC, JA, JA, JA }, 	 //	 933	 1200
{ SK, LO, KN, SH, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 934	 1200
{ SK, LO, KN, TN, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 935	 1200
{ SK, JA, JA, SK, QN, KN, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 936	 1200
{ SK, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 937	 1200
{ SK, JA, JA, SK, SH, KN, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 938	 1200
{ SK, JA, JA, JA, QN, KN, JA, JA, JA, PF, KN, SH, JA, JA, JA }, 	 //	 939	 1200
{ SK, JA, JA, JA, JA, KN, JA, JA, JA, TN, KN, SH, JA, JA, AC }, 	 //	 940	 1200
{ SK, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, SH, ST, JA, JA }, 	 //	 941	 1200
{ SK, QN, JA, JA, JA, KN, ST, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 942	 1200
{ SK, QN, QN, QN, QN, KN, ST, SK, ST, QN, KN, JA, JA, JA, SH }, 	 //	 943	 1200
{ SK, ST, JA, JA, SH, KN, JA, JA, JA, JA, KN, TN, JA, JA, JA }, 	 //	 944	 1200
{ SK, ST, JA, JA, JA, KN, JA, JA, JA, JA, KN, TN, JA, JA, WN }, 	 //	 945	 1200
{ SK, PF, KN, TN, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 946	 1200
{ SK, KN, KN, SH, TN, KN, KN, WN, TN, TN, KN, SK, TN, TN, TN }, 	 //	 947	 1200
{ SK, KN, KN, TN, TN, KN, KN, WN, TN, TN, KN, SK, TN, TN, TN }, 	 //	 948	 1200
{ SK, QN, QN, QN, QN, KN, KN, SK, ST, PF, KN, AC, JA, JA, JA }, 	 //	 949	 1200
{ KN, QN, QN, QN, QN, KN, QN, SK, ST, SH, KN, QN, JA, JA, JA }, 	 //	 950	 1200
{ KN, QN, QN, QN, QN, KN, QN, SK, ST, SH, KN, SK, JA, JA, JA }, 	 //	 951	 1200
{ KN, SK, JA, JA, QN, KN, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 952	 1200
{ KN, SK, JA, JA, JA, KN, JA, JA, JA, TN, KN, JA, JA, JA, AC }, 	 //	 953	 1200
{ KN, JA, LO, SK, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, JA }, 	 //	 954	 1200
{ KN, JA, JA, SK, QN, KN, JA, JA, JA, SH, KN, JA, JA, JA, JA }, 	 //	 955	 1200
{ KN, JA, JA, SK, JA, KN, JA, JA, JA, JA, KN, JA, JA, JA, WN }, 	 //	 956	 1200
{ KN, JA, JA, JA, PF, KN, JA, JA, JA, JA, KN, JA, JA, JA, TN }, 	 //	 957	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, KN, JA, JA, SH, TN }, 	 //	 958	 1200
{ KN, JA, JA, ST, JA, KN, JA, JA, JA, JA, KN, JA, JA, TN, JA }, 	 //	 959	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, JA, ST, JA, JA }, 	 //	 960	 1200
{ KN, JA, JA, SK, SH, KN, JA, JA, JA, JA, KN, SH, JA, JA, JA }, 	 //	 961	 1200
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, PF, KN, SH, JA, JA, JA }, 	 //	 962	 1200
{ KN, JA, JA, JA, SH, KN, JA, JA, JA, JA, KN, SH, JA, SH, JA }, 	 //	 963	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, KN, SH, JA, SH, TN }, 	 //	 964	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, JA, KN, SH, ST, JA, JA }, 	 //	 965	 1200
{ KN, AC, KN, TN, TN, KN, KN, WN, TN, TN, KN, QN, TN, TN, TN }, 	 //	 966	 1200
{ KN, QN, QN, QN, QN, KN, ST, SK, ST, QN, KN, JA, JA, JA, QN }, 	 //	 967	 1200
{ KN, ST, JA, ST, JA, KN, JA, JA, JA, JA, KN, TN, JA, TN, JA }, 	 //	 968	 1200
{ KN, PF, KN, SH, TN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN }, 	 //	 969	 1200
{ KN, QN, KN, TN, TN, KN, KN, WN, TN, TN, KN, AC, TN, TN, TN }, 	 //	 970	 1200
{ KN, QN, QN, QN, QN, KN, KN, SK, ST, SH, KN, AC, JA, JA, JA }, 	 //	 971	 1200
{ KN, KN, KN, SH, TN, KN, AC, WN, TN, TN, KN, SH, TN, TN, TN }, 	 //	 972	 1200
{ KN, KN, KN, SH, TN, KN, KN, WN, TN, TN, WN, KN, TN, TN, TN }, 	 //	 973	 1200
{ KN, KN, KN, SH, TN, KN, ST, WN, TN, TN, WN, QN, TN, TN, TN }, 	 //	 974	 1200
{ KN, QN, QN, QN, QN, KN, QN, SK, ST, SH, WN, SK, JA, JA, JA }, 	 //	 975	 1200
{ KN, QN, JA, JA, JA, KN, SK, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 976	 1200
{ KN, SK, JA, SK, JA, KN, JA, JA, JA, JA, WN, JA, JA, JA, WN }, 	 //	 977	 1200
{ KN, JA, LO, SK, JA, KN, JA, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 978	 1200
{ KN, JA, LO, JA, JA, KN, JA, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 979	 1200
{ KN, JA, JA, JA, PF, KN, JA, JA, JA, JA, WN, JA, JA, JA, TN }, 	 //	 980	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, TN, WN, JA, JA, SH, AC }, 	 //	 981	 1200
{ KN, JA, JA, JA, QN, KN, JA, JA, JA, SH, WN, SH, JA, JA, JA }, 	 //	 982	 1200
{ KN, JA, JA, JA, JA, KN, JA, JA, JA, WN, WN, SH, JA, JA, TN }, 	 //	 983	 1200
{ KN, JA, JA, JA, JA, KN, SH, JA, JA, JA, WN, TN, JA, JA, JA }, 	 //	 984	 1200
{ KN, QN, JA, JA, JA, KN, ST, JA, JA, JA, WN, JA, JA, JA, JA }, 	 //	 985	 1200
{ KN, ST, JA, SK, SH, KN, JA, JA, JA, JA, WN, TN, JA, JA, JA }, 	 //	 986	 1200
{ KN, KN, KN, SH, TN, KN, KN, WN, TN, TN, WN, KN, TN, TN, TN }, 	 //	 987	 1200
{ KN, KN, KN, SH, TN, KN, KN, WN, TN, TN, WN, SK, TN, TN, TN }, 	 //	 988	 1200
{ KN, KN, KN, TN, TN, KN, SK, WN, TN, TN, WN, QN, TN, TN, TN }, 	 //	 989	 1200
{ KN, KN, KN, TN, TN, KN, AC, WN, TN, TN, WN, SH, TN, TN, TN }, 	 //	 990	 1200
{ KN, QN, QN, QN, JA, WN, QN, SK, ST, JA, QN, QN, JA, JA, JA }, 	 //	 991	 1200
{ KN, QN, JA, JA, JA, WN, SK, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 992	 1200
{ KN, SK, LO, SK, JA, WN, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 993	 1200
{ KN, SK, JA, SK, QN, WN, JA, JA, JA, PF, QN, JA, JA, JA, JA }, 	 //	 994	 1200
{ KN, JA, LO, SK, JA, WN, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 995	 1200
{ KN, JA, LO, JA, JA, WN, JA, JA, JA, JA, QN, JA, JA, JA, JA }, 	 //	 996	 1200
{ KN, JA, JA, SK, JA, WN, JA, JA, JA, JA, QN, JA, JA, JA, WN }, 	 //	 997	 1200
{ KN, JA, JA, JA, PF, WN, JA, JA, JA, JA, QN, JA, JA, JA, TN }, 	 //	 998	 1200
{ KN, JA, JA, JA, QN, WN, JA, JA, JA, SH, QN, SH, JA, JA, JA }, 	 //	 999	 1200
{ KN, JA, JA, ST, JA, WN, JA, JA, JA, JA, QN, SH, JA, TN, JA }};	 //	 1000	 1200
