unsigned char L5_Outcome_1120[1000][15]={	 //	 0	 1120
{ AC, QN, QN, QN, QN, LO, QN, QN, SK, QN, AC, SK, SK, JA, QN }, 	 //	 1	 1120
{ AC, QN, QN, QN, QN, LO, QN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 2	 1120
{ AC, QN, QN, QN, QN, LO, SK, QN, QN, PF, AC, JA, SK, SK, JA }, 	 //	 3	 1120
{ AC, QN, QN, QN, CR, LO, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 4	 1120
{ AC, QN, QN, QN, QN, LO, SK, QN, QN, KN, AC, JA, SK, SK, AC }, 	 //	 5	 1120
{ AC, QN, QN, SK, SK, LO, SK, QN, QN, QN, AC, JA, SK, KN, QN }, 	 //	 6	 1120
{ AC, KN, QN, QN, SK, LO, SK, QN, QN, QN, AC, QN, SK, SK, QN }, 	 //	 7	 1120
{ LO, QN, QN, QN, QN, AC, QN, QN, SK, QN, AC, SK, SK, JA, SH }, 	 //	 8	 1120
{ LO, QN, QN, QN, QN, AC, QN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 9	 1120
{ LO, QN, QN, QN, QN, AC, QN, QN, SK, PF, AC, SK, SK, JA, JA }, 	 //	 10	 1120
{ LO, QN, QN, QN, QN, AC, QN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 11	 1120
{ LO, QN, QN, QN, KN, AC, SK, QN, QN, SK, AC, JA, SK, SK, QN }, 	 //	 12	 1120
{ LO, QN, QN, QN, QN, AC, SK, QN, QN, SH, AC, JA, SK, SK, JA }, 	 //	 13	 1120
{ LO, QN, QN, QN, AC, AC, SK, QN, QN, KN, AC, JA, SK, SK, QN }, 	 //	 14	 1120
{ LO, QN, QN, QN, KN, AC, SK, QN, QN, QN, AC, JA, SK, SK, PF }, 	 //	 15	 1120
{ LO, QN, QN, QN, QN, AC, SK, QN, QN, PF, AC, JA, SK, SK, JA }, 	 //	 16	 1120
{ LO, QN, QN, QN, CR, AC, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 17	 1120
{ LO, QN, QN, SK, SK, AC, SK, QN, QN, QN, AC, JA, SK, KN, QN }, 	 //	 18	 1120
{ LO, KN, QN, SK, SK, AC, KN, QN, QN, QN, AC, SK, SK, KN, QN }, 	 //	 19	 1120
{ LO, KN, QN, QN, SK, AC, SK, QN, QN, QN, AC, QN, SK, SK, QN }, 	 //	 20	 1120
{ LO, KN, QN, SK, SK, AC, SK, QN, QN, QN, AC, QN, SK, KN, QN }, 	 //	 21	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 22	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, PF, AC, SK, SK, JA, JA }, 	 //	 23	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 24	 1120
{ AC, QN, QN, SK, SK, AC, QN, QN, QN, KN, AC, SK, SK, KN, KN }, 	 //	 25	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, SH, AC, JA, SK, SK, JA }, 	 //	 26	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, KN, AC, JA, SK, SK, AC }, 	 //	 27	 1120
{ AC, KN, QN, QN, QN, AC, SK, QN, QN, QN, AC, QN, SK, SK, SH }, 	 //	 28	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, QN, ST, SK, SK, JA, QN }, 	 //	 29	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, SH, ST, SK, SK, JA, JA }, 	 //	 30	 1120
{ AC, QN, QN, SK, SK, AC, QN, QN, QN, KN, ST, SK, SK, KN, KN }, 	 //	 31	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, SH, ST, JA, SK, SK, JA }, 	 //	 32	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, PF, ST, JA, SK, SK, JA }, 	 //	 33	 1120
{ AC, QN, QN, QN, CR, AC, SK, QN, QN, QN, ST, JA, SK, SK, KN }, 	 //	 34	 1120
{ AC, QN, QN, SK, SK, AC, SK, QN, QN, QN, ST, JA, SK, KN, QN }, 	 //	 35	 1120
{ AC, KN, QN, SK, SK, AC, KN, QN, QN, QN, ST, SK, SK, KN, QN }, 	 //	 36	 1120
{ AC, KN, QN, QN, SK, AC, SK, QN, QN, QN, ST, QN, SK, SK, QN }, 	 //	 37	 1120
{ AC, KN, QN, QN, QN, AC, SK, QN, QN, QN, ST, QN, SK, SK, SH }, 	 //	 38	 1120
{ AC, QN, QN, QN, QN, ST, QN, QN, SK, QN, KN, SK, SK, JA, QN }, 	 //	 39	 1120
{ AC, QN, QN, QN, QN, ST, QN, QN, SK, SH, KN, SK, SK, JA, JA }, 	 //	 40	 1120
{ AC, QN, QN, QN, QN, ST, QN, QN, SK, KN, KN, SK, SK, JA, AC }, 	 //	 41	 1120
{ AC, QN, QN, QN, KN, ST, SK, QN, QN, SK, KN, JA, SK, SK, QN }, 	 //	 42	 1120
{ AC, QN, QN, QN, QN, ST, SK, QN, QN, SH, KN, JA, SK, SK, JA }, 	 //	 43	 1120
{ AC, QN, QN, QN, AC, ST, SK, QN, QN, KN, KN, JA, SK, SK, QN }, 	 //	 44	 1120
{ AC, QN, QN, QN, KN, ST, SK, QN, QN, QN, KN, JA, SK, SK, PF }, 	 //	 45	 1120
{ AC, QN, QN, QN, QN, ST, SK, QN, QN, PF, KN, JA, SK, SK, JA }, 	 //	 46	 1120
{ AC, QN, QN, QN, CR, ST, SK, QN, QN, QN, KN, JA, SK, SK, KN }, 	 //	 47	 1120
{ AC, QN, QN, SK, SK, ST, SK, QN, QN, QN, KN, JA, SK, KN, QN }, 	 //	 48	 1120
{ AC, KN, QN, SK, SK, ST, KN, QN, QN, QN, KN, SK, SK, KN, QN }, 	 //	 49	 1120
{ ST, QN, QN, QN, QN, KN, QN, QN, SK, QN, KN, SK, SK, JA, SH }, 	 //	 50	 1120
{ ST, QN, QN, QN, QN, KN, QN, QN, SK, SH, KN, SK, SK, JA, JA }, 	 //	 51	 1120
{ ST, QN, QN, QN, QN, KN, QN, QN, SK, PF, KN, SK, SK, JA, JA }, 	 //	 52	 1120
{ ST, QN, QN, SK, SK, KN, QN, QN, QN, KN, KN, SK, SK, KN, KN }, 	 //	 53	 1120
{ ST, QN, QN, QN, QN, KN, SK, QN, QN, SH, KN, JA, SK, SK, JA }, 	 //	 54	 1120
{ ST, QN, QN, QN, AC, KN, SK, QN, QN, KN, KN, JA, SK, SK, QN }, 	 //	 55	 1120
{ ST, QN, QN, QN, QN, KN, SK, QN, QN, PF, KN, JA, SK, SK, JA }, 	 //	 56	 1120
{ ST, QN, QN, QN, QN, KN, SK, QN, QN, KN, KN, JA, SK, SK, AC }, 	 //	 57	 1120
{ ST, QN, QN, SK, SK, KN, SK, QN, QN, QN, KN, JA, SK, KN, QN }, 	 //	 58	 1120
{ ST, KN, QN, SK, SK, KN, KN, QN, QN, QN, KN, SK, SK, KN, QN }, 	 //	 59	 1120
{ KN, QN, QN, QN, QN, KN, QN, QN, SK, SH, KN, SK, SK, JA, JA }, 	 //	 60	 1120
{ KN, QN, QN, QN, QN, KN, QN, QN, SK, KN, KN, SK, SK, JA, AC }, 	 //	 61	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, QN, SH, KN, JA, SK, SK, JA }, 	 //	 62	 1120
{ KN, QN, QN, QN, AC, KN, SK, QN, QN, KN, KN, JA, SK, SK, QN }, 	 //	 63	 1120
{ KN, QN, QN, QN, KN, KN, SK, QN, QN, QN, KN, JA, SK, SK, PF }, 	 //	 64	 1120
{ KN, QN, QN, SK, SK, KN, SK, QN, QN, QN, KN, JA, SK, KN, QN }, 	 //	 65	 1120
{ KN, KN, QN, QN, QN, KN, SK, QN, QN, QN, KN, QN, SK, SK, SH }, 	 //	 66	 1120
{ KN, KN, QN, SK, SK, KN, SK, QN, QN, QN, KN, QN, SK, KN, QN }, 	 //	 67	 1120
{ KN, QN, ST, KN, KN, KN, QN, AC, KN, KN, SK, SK, KN, SK, SK }, 	 //	 68	 1120
{ KN, QN, KN, KN, KN, KN, QN, QN, SK, KN, SK, SK, PF, QN, SK }, 	 //	 69	 1120
{ KN, QN, QN, QN, AC, KN, QN, PF, QN, AC, SK, SK, KN, SK, SK }, 	 //	 70	 1120
{ KN, QN, QN, SK, SK, KN, QN, PF, QN, QN, SK, SK, KN, KN, QN }, 	 //	 71	 1120
{ KN, QN, KN, KN, KN, KN, QN, KN, SK, KN, SK, SK, KN, QN, SK }, 	 //	 72	 1120
{ KN, QN, KN, SK, SK, KN, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 73	 1120
{ KN, QN, KN, KN, KN, KN, QN, SH, KN, KN, SK, SK, AC, SK, SK }, 	 //	 74	 1120
{ KN, QN, PF, QN, AC, KN, QN, QN, QN, AC, SK, SK, QN, SK, SK }, 	 //	 75	 1120
{ KN, QN, PF, SK, SK, KN, QN, QN, QN, KN, SK, SK, QN, KN, KN }, 	 //	 76	 1120
{ KN, QN, QN, QN, AC, KN, QN, SK, QN, AC, SK, SK, JA, SK, SK }, 	 //	 77	 1120
{ KN, QN, QN, QN, QN, KN, QN, SK, SK, QN, SK, SK, JA, JA, QN }, 	 //	 78	 1120
{ KN, QN, WN, SK, SK, KN, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 79	 1120
{ KN, QN, KN, KN, KN, KN, QN, KN, SK, KN, SK, SK, KN, QN, SK }, 	 //	 80	 1120
{ KN, QN, KN, SK, SK, KN, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 81	 1120
{ KN, QN, KN, KN, KN, KN, QN, KN, SK, KN, SK, SK, PF, QN, SK }, 	 //	 82	 1120
{ KN, QN, KN, KN, KN, KN, QN, PF, KN, KN, SK, SK, QN, SK, SK }, 	 //	 83	 1120
{ KN, QN, QN, QN, KN, KN, QN, AC, QN, KN, SK, SK, KN, SK, SK }, 	 //	 84	 1120
{ KN, QN, QN, QN, AC, KN, QN, AC, QN, AC, SK, SK, KN, SK, SK }, 	 //	 85	 1120
{ KN, QN, QN, SK, SK, KN, QN, AC, QN, QN, SK, SK, KN, KN, QN }, 	 //	 86	 1120
{ KN, QN, AC, KN, KN, KN, QN, KN, KN, KN, SK, SK, WN, SK, SK }, 	 //	 87	 1120
{ KN, QN, KN, KN, KN, KN, SK, WN, SK, KN, SK, JA, TN, QN, SK }, 	 //	 88	 1120
{ KN, QN, KN, KN, KN, KN, SK, WN, SK, SK, SK, JA, TN, QN, QN }, 	 //	 89	 1120
{ KN, QN, ST, KN, KN, KN, SK, AC, KN, KN, SK, JA, KN, SK, SK }, 	 //	 90	 1120
{ KN, QN, ST, SK, SK, KN, SK, AC, QN, KN, SK, JA, KN, KN, KN }, 	 //	 91	 1120
{ KN, QN, KN, KN, KN, KN, SK, QN, KN, KN, SK, JA, PF, SK, SK }, 	 //	 92	 1120
{ KN, QN, KN, KN, KN, KN, SK, QN, SK, SK, SK, JA, PF, QN, QN }, 	 //	 93	 1120
{ KN, QN, QN, KN, KN, KN, SK, PF, KN, KN, SK, JA, KN, SK, SK }, 	 //	 94	 1120
{ KN, QN, QN, SK, SK, KN, SK, PF, QN, KN, SK, JA, KN, KN, KN }, 	 //	 95	 1120
{ KN, QN, PF, SK, SK, KN, SK, KN, QN, KN, SK, JA, KN, KN, KN }, 	 //	 96	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, KN, SK, JA, KN, QN, SK }, 	 //	 97	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, KN, SK, JA, SH, QN, SK }, 	 //	 98	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, SK, SK, JA, SH, QN, QN }, 	 //	 99	 1120
{ KN, QN, KN, KN, KN, KN, SK, SH, KN, KN, SK, JA, AC, SK, SK }, 	 //	 100	 1120
{ KN, QN, KN, KN, KN, KN, SK, SH, SK, SK, SK, JA, AC, QN, QN }, 	 //	 101	 1120
{ KN, QN, QN, WN, SK, KN, SK, QN, QN, QN, SK, JA, SK, QN, QN }, 	 //	 102	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, QN, PF, SK, JA, SK, QN, JA }, 	 //	 103	 1120
{ KN, QN, QN, QN, CR, KN, SK, QN, QN, QN, SK, JA, SK, QN, KN }, 	 //	 104	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, QN, KN, SK, JA, SK, QN, AC }, 	 //	 105	 1120
{ KN, QN, QN, KN, QN, KN, SK, QN, QN, QN, SK, JA, SK, ST, QN }, 	 //	 106	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, ST, SH, SK, JA, SK, JA, JA }, 	 //	 107	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, ST, PF, SK, JA, SK, JA, JA }, 	 //	 108	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, ST, KN, SK, JA, SK, JA, AC }, 	 //	 109	 1120
{ KN, QN, QN, SK, QN, KN, SK, QN, QN, QN, SK, JA, SK, KN, QN }, 	 //	 110	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, KN, QN, SK, JA, SK, AC, SH }, 	 //	 111	 1120
{ KN, QN, QN, QN, QN, KN, SK, QN, KN, PF, SK, JA, SK, AC, JA }, 	 //	 112	 1120
{ KN, QN, QN, QN, SK, KN, SK, SK, QN, QN, SK, JA, JA, QN, QN }, 	 //	 113	 1120
{ KN, QN, QN, QN, QN, KN, SK, SK, QN, QN, SK, JA, JA, QN, SH }, 	 //	 114	 1120
{ KN, QN, QN, QN, QN, KN, SK, SK, QN, SH, SK, JA, JA, SK, JA }, 	 //	 115	 1120
{ KN, QN, QN, QN, QN, KN, SK, SK, QN, KN, SK, JA, JA, SK, AC }, 	 //	 116	 1120
{ KN, QN, QN, QN, QN, KN, SK, SK, KN, QN, SK, JA, JA, AC, QN }, 	 //	 117	 1120
{ KN, QN, QN, QN, QN, KN, SK, SK, KN, QN, SK, JA, JA, AC, SH }, 	 //	 118	 1120
{ KN, QN, WN, SK, SK, KN, SK, KN, QN, KN, SK, JA, KN, KN, KN }, 	 //	 119	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, SK, SK, JA, KN, QN, QN }, 	 //	 120	 1120
{ KN, QN, KN, SK, SK, KN, SK, KN, QN, KN, SK, JA, KN, KN, KN }, 	 //	 121	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, KN, SK, JA, PF, QN, SK }, 	 //	 122	 1120
{ KN, QN, KN, KN, KN, KN, SK, KN, SK, SK, SK, JA, PF, QN, QN }, 	 //	 123	 1120
{ KN, QN, KN, KN, KN, KN, SK, PF, KN, KN, SK, JA, QN, SK, SK }, 	 //	 124	 1120
{ KN, QN, KN, KN, KN, KN, SK, PF, SK, KN, SK, JA, QN, QN, SK }, 	 //	 125	 1120
{ KN, QN, QN, KN, KN, KN, SK, AC, KN, KN, SK, JA, KN, SK, SK }, 	 //	 126	 1120
{ KN, QN, QN, SK, SK, KN, SK, AC, QN, KN, SK, JA, KN, KN, KN }, 	 //	 127	 1120
{ KN, QN, AC, KN, KN, KN, SK, KN, KN, KN, SK, JA, WN, SK, SK }, 	 //	 128	 1120
{ KN, KN, KN, QN, KN, KN, KN, WN, QN, KN, SK, SK, TN, SK, SK }, 	 //	 129	 1120
{ KN, KN, KN, QN, AC, KN, KN, WN, QN, AC, SK, SK, TN, SK, SK }, 	 //	 130	 1120
{ KN, KN, KN, QN, KN, KN, KN, WN, SK, KN, SK, SK, TN, JA, SK }, 	 //	 131	 1120
{ KN, KN, KN, QN, KN, KN, KN, WN, SK, SK, SK, SK, TN, JA, QN }, 	 //	 132	 1120
{ KN, KN, KN, QN, AC, KN, KN, WN, SK, AC, SK, SK, TN, JA, SK }, 	 //	 133	 1120
{ KN, KN, KN, SK, SK, KN, KN, WN, JA, KN, SK, SK, TN, JA, KN }, 	 //	 134	 1120
{ KN, KN, KN, SK, SK, KN, KN, WN, QN, KN, SK, SK, TN, KN, KN }, 	 //	 135	 1120
{ KN, KN, ST, QN, AC, KN, KN, AC, QN, AC, SK, SK, KN, SK, SK }, 	 //	 136	 1120
{ KN, KN, ST, QN, KN, KN, KN, AC, SK, KN, SK, SK, KN, JA, SK }, 	 //	 137	 1120
{ KN, KN, ST, QN, SK, KN, KN, AC, SK, QN, SK, SK, KN, JA, QN }, 	 //	 138	 1120
{ KN, KN, ST, QN, AC, KN, KN, AC, SK, AC, SK, SK, KN, JA, SK }, 	 //	 139	 1120
{ KN, KN, ST, QN, AC, KN, KN, AC, SK, SK, SK, SK, KN, JA, KN }, 	 //	 140	 1120
{ KN, KN, ST, QN, SK, KN, KN, AC, SK, KN, SK, SK, KN, JA, KN }, 	 //	 141	 1120
{ KN, KN, ST, SK, SK, KN, KN, AC, JA, QN, SK, SK, KN, JA, QN }, 	 //	 142	 1120
{ KN, KN, ST, KN, KN, KN, KN, AC, SK, KN, SK, SK, KN, QN, SK }, 	 //	 143	 1120
{ KN, KN, ST, KN, SK, KN, KN, AC, SK, QN, SK, SK, KN, QN, QN }, 	 //	 144	 1120
{ KN, KN, ST, KN, SK, KN, KN, AC, SK, KN, SK, SK, KN, QN, KN }, 	 //	 145	 1120
{ KN, KN, AC, QN, KN, KN, KN, KN, QN, KN, SK, SK, QN, SK, SK }, 	 //	 146	 1120
{ KN, KN, AC, QN, KN, KN, KN, KN, SK, KN, SK, SK, QN, JA, SK }, 	 //	 147	 1120
{ KN, KN, AC, QN, KN, KN, KN, KN, SK, SK, SK, SK, QN, JA, QN }, 	 //	 148	 1120
{ KN, KN, AC, QN, SK, KN, KN, KN, SK, QN, SK, SK, QN, JA, QN }, 	 //	 149	 1120
{ KN, KN, AC, QN, AC, KN, KN, KN, SK, AC, SK, SK, QN, JA, SK }, 	 //	 150	 1120
{ KN, KN, AC, QN, AC, KN, KN, KN, SK, SK, SK, SK, QN, JA, KN }, 	 //	 151	 1120
{ KN, KN, AC, QN, SK, KN, KN, KN, SK, KN, SK, SK, QN, JA, KN }, 	 //	 152	 1120
{ KN, KN, AC, KN, KN, KN, KN, KN, SK, KN, SK, SK, QN, QN, SK }, 	 //	 153	 1120
{ KN, KN, AC, KN, AC, KN, KN, KN, SK, AC, SK, SK, QN, QN, SK }, 	 //	 154	 1120
{ KN, KN, AC, SK, SK, KN, KN, KN, QN, QN, SK, SK, QN, KN, QN }, 	 //	 155	 1120
{ KN, KN, KN, QN, AC, KN, KN, QN, QN, AC, SK, SK, PF, SK, SK }, 	 //	 156	 1120
{ KN, KN, KN, QN, KN, KN, KN, QN, SK, KN, SK, SK, PF, JA, SK }, 	 //	 157	 1120
{ KN, KN, KN, QN, KN, KN, KN, QN, SK, SK, SK, SK, PF, JA, QN }, 	 //	 158	 1120
{ KN, KN, KN, QN, SK, KN, KN, QN, SK, QN, SK, SK, PF, JA, QN }, 	 //	 159	 1120
{ KN, KN, KN, QN, SK, KN, KN, QN, SK, KN, SK, SK, PF, JA, KN }, 	 //	 160	 1120
{ KN, KN, KN, SK, SK, KN, KN, QN, JA, KN, SK, SK, PF, JA, KN }, 	 //	 161	 1120
{ KN, KN, KN, SK, SK, KN, KN, QN, QN, KN, SK, SK, PF, KN, KN }, 	 //	 162	 1120
{ KN, KN, QN, QN, KN, KN, KN, PF, QN, KN, SK, SK, KN, SK, SK }, 	 //	 163	 1120
{ KN, KN, QN, QN, AC, KN, KN, PF, QN, AC, SK, SK, KN, SK, SK }, 	 //	 164	 1120
{ KN, KN, QN, QN, KN, KN, KN, PF, SK, KN, SK, SK, KN, JA, SK }, 	 //	 165	 1120
{ KN, KN, QN, QN, SK, KN, KN, PF, SK, QN, SK, SK, KN, JA, QN }, 	 //	 166	 1120
{ KN, KN, QN, QN, AC, KN, KN, PF, SK, AC, SK, SK, KN, JA, SK }, 	 //	 167	 1120
{ KN, KN, QN, QN, AC, KN, KN, PF, SK, SK, SK, SK, KN, JA, KN }, 	 //	 168	 1120
{ KN, KN, QN, SK, SK, KN, KN, PF, JA, QN, SK, SK, KN, JA, QN }, 	 //	 169	 1120
{ KN, KN, QN, KN, KN, KN, KN, PF, SK, KN, SK, SK, KN, QN, SK }, 	 //	 170	 1120
{ KN, KN, QN, KN, AC, KN, KN, PF, SK, SK, SK, SK, KN, QN, KN }, 	 //	 171	 1120
{ KN, KN, KN, QN, KN, KN, KN, SH, QN, KN, SK, SK, AC, SK, SK }, 	 //	 172	 1120
{ KN, KN, KN, QN, AC, KN, KN, SH, QN, AC, SK, SK, AC, SK, SK }, 	 //	 173	 1120
{ KN, KN, KN, QN, KN, KN, KN, SH, SK, SK, SK, SK, AC, JA, QN }, 	 //	 174	 1120
{ KN, KN, KN, QN, AC, KN, KN, SH, SK, AC, SK, SK, AC, JA, SK }, 	 //	 175	 1120
{ KN, KN, KN, QN, AC, KN, KN, SH, SK, SK, SK, SK, AC, JA, KN }, 	 //	 176	 1120
{ KN, KN, KN, QN, SK, KN, KN, SH, SK, KN, SK, SK, AC, JA, KN }, 	 //	 177	 1120
{ KN, KN, AC, QN, KN, KN, KN, WN, QN, KN, SK, SK, KN, SK, SK }, 	 //	 178	 1120
{ KN, KN, AC, QN, AC, KN, KN, WN, QN, AC, SK, SK, KN, SK, SK }, 	 //	 179	 1120
{ KN, KN, AC, QN, KN, KN, KN, WN, SK, KN, SK, SK, KN, JA, SK }, 	 //	 180	 1120
{ KN, KN, AC, QN, KN, KN, KN, WN, SK, SK, SK, SK, KN, JA, QN }, 	 //	 181	 1120
{ KN, KN, AC, QN, SK, KN, KN, WN, SK, QN, SK, SK, KN, JA, QN }, 	 //	 182	 1120
{ KN, KN, AC, QN, AC, KN, KN, WN, SK, AC, SK, SK, KN, JA, SK }, 	 //	 183	 1120
{ KN, KN, AC, QN, SK, KN, KN, WN, SK, KN, SK, SK, KN, JA, KN }, 	 //	 184	 1120
{ KN, KN, AC, SK, SK, KN, KN, WN, JA, KN, SK, SK, KN, JA, KN }, 	 //	 185	 1120
{ KN, KN, AC, KN, SK, KN, KN, WN, SK, QN, SK, SK, KN, QN, QN }, 	 //	 186	 1120
{ KN, KN, AC, KN, AC, KN, KN, WN, SK, SK, SK, SK, KN, QN, KN }, 	 //	 187	 1120
{ KN, KN, KN, QN, KN, KN, KN, PF, QN, KN, SK, SK, QN, SK, SK }, 	 //	 188	 1120
{ KN, KN, KN, QN, AC, KN, KN, PF, QN, AC, SK, SK, QN, SK, SK }, 	 //	 189	 1120
{ KN, KN, KN, QN, KN, KN, KN, PF, SK, SK, SK, SK, QN, JA, QN }, 	 //	 190	 1120
{ KN, KN, KN, QN, SK, KN, KN, PF, SK, QN, SK, SK, QN, JA, QN }, 	 //	 191	 1120
{ KN, KN, KN, QN, AC, KN, KN, PF, SK, SK, SK, SK, QN, JA, KN }, 	 //	 192	 1120
{ KN, KN, KN, SK, SK, KN, KN, PF, JA, QN, SK, SK, QN, JA, QN }, 	 //	 193	 1120
{ KN, KN, KN, SK, SK, KN, KN, PF, QN, KN, SK, SK, QN, KN, KN }, 	 //	 194	 1120
{ KN, KN, QN, QN, KN, KN, KN, AC, QN, KN, SK, SK, KN, SK, SK }, 	 //	 195	 1120
{ KN, KN, QN, QN, AC, KN, KN, AC, QN, AC, SK, SK, KN, SK, SK }, 	 //	 196	 1120
{ KN, KN, QN, QN, AC, KN, KN, AC, SK, AC, SK, SK, KN, JA, SK }, 	 //	 197	 1120
{ KN, KN, QN, QN, AC, KN, KN, AC, SK, SK, SK, SK, KN, JA, KN }, 	 //	 198	 1120
{ KN, KN, QN, QN, SK, KN, KN, AC, SK, KN, SK, SK, KN, JA, KN }, 	 //	 199	 1120
{ KN, KN, QN, KN, KN, KN, KN, AC, SK, KN, SK, SK, KN, QN, SK }, 	 //	 200	 1120
{ KN, KN, QN, KN, KN, KN, KN, AC, SK, SK, SK, SK, KN, QN, QN }, 	 //	 201	 1120
{ KN, KN, QN, KN, AC, KN, KN, AC, SK, SK, SK, SK, KN, QN, KN }, 	 //	 202	 1120
{ KN, KN, AC, QN, AC, KN, KN, KN, QN, AC, SK, SK, WN, SK, SK }, 	 //	 203	 1120
{ KN, KN, AC, QN, SK, KN, KN, KN, SK, QN, SK, SK, WN, JA, QN }, 	 //	 204	 1120
{ KN, KN, AC, QN, SK, KN, KN, KN, SK, KN, SK, SK, WN, JA, KN }, 	 //	 205	 1120
{ KN, KN, AC, SK, SK, KN, KN, KN, JA, QN, SK, SK, WN, JA, QN }, 	 //	 206	 1120
{ KN, KN, AC, SK, SK, KN, KN, KN, JA, KN, SK, SK, WN, JA, KN }, 	 //	 207	 1120
{ KN, KN, AC, KN, KN, KN, KN, KN, SK, KN, SK, SK, WN, QN, SK }, 	 //	 208	 1120
{ KN, KN, AC, SK, SK, KN, KN, KN, QN, QN, SK, SK, WN, KN, QN }, 	 //	 209	 1120
{ KN, KN, AC, SK, SK, KN, KN, KN, QN, KN, SK, SK, WN, KN, KN }, 	 //	 210	 1120
{ KN, KN, KN, QN, KN, KN, SK, WN, QN, KN, SK, QN, TN, SK, SK }, 	 //	 211	 1120
{ KN, KN, KN, QN, KN, KN, SK, WN, SK, KN, SK, QN, TN, JA, SK }, 	 //	 212	 1120
{ KN, KN, KN, QN, SK, KN, SK, WN, SK, QN, SK, QN, TN, JA, QN }, 	 //	 213	 1120
{ KN, KN, KN, QN, SK, KN, SK, WN, SK, KN, SK, QN, TN, JA, KN }, 	 //	 214	 1120
{ KN, KN, KN, SK, SK, KN, SK, WN, QN, KN, SK, QN, TN, KN, KN }, 	 //	 215	 1120
{ KN, KN, ST, SK, SK, KN, SK, AC, QN, KN, SK, QN, KN, KN, KN }, 	 //	 216	 1120
{ KN, KN, AC, KN, KN, KN, SK, KN, SK, SK, SK, QN, QN, QN, QN }, 	 //	 217	 1120
{ KN, KN, AC, KN, SK, KN, SK, KN, SK, QN, SK, QN, QN, QN, QN }, 	 //	 218	 1120
{ KN, KN, KN, QN, KN, KN, SK, QN, QN, KN, SK, QN, PF, SK, SK }, 	 //	 219	 1120
{ KN, KN, KN, QN, KN, KN, SK, QN, SK, SK, SK, QN, PF, JA, QN }, 	 //	 220	 1120
{ KN, KN, KN, QN, AC, KN, SK, QN, SK, SK, SK, QN, PF, JA, KN }, 	 //	 221	 1120
{ KN, KN, KN, QN, SK, KN, SK, QN, SK, KN, SK, QN, PF, JA, KN }, 	 //	 222	 1120
{ KN, KN, KN, SK, SK, KN, SK, QN, JA, QN, SK, QN, PF, JA, QN }, 	 //	 223	 1120
{ KN, KN, KN, SK, SK, KN, SK, QN, JA, KN, SK, QN, PF, JA, KN }, 	 //	 224	 1120
{ KN, KN, QN, KN, KN, KN, SK, PF, KN, KN, SK, QN, KN, SK, SK }, 	 //	 225	 1120
{ KN, KN, KN, QN, KN, KN, SK, KN, QN, KN, SK, QN, KN, SK, SK }, 	 //	 226	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, QN, AC, SK, QN, KN, SK, SK }, 	 //	 227	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, SK, AC, SK, QN, KN, JA, SK }, 	 //	 228	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, SK, SK, SK, QN, KN, JA, KN }, 	 //	 229	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, KN, SK, QN, KN, JA, KN }, 	 //	 230	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, QN, AC, SK, QN, SH, SK, SK }, 	 //	 231	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, QN, SK, QN, SH, JA, QN }, 	 //	 232	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, SK, AC, SK, QN, SH, JA, SK }, 	 //	 233	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, JA, QN, SK, QN, SH, JA, QN }, 	 //	 234	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, QN, QN, SK, QN, SH, KN, QN }, 	 //	 235	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, QN, KN, SK, QN, SH, KN, KN }, 	 //	 236	 1120
{ KN, KN, KN, QN, AC, KN, SK, SH, QN, AC, SK, QN, AC, SK, SK }, 	 //	 237	 1120
{ KN, KN, KN, QN, KN, KN, SK, SH, SK, KN, SK, QN, AC, JA, SK }, 	 //	 238	 1120
{ KN, KN, KN, QN, SK, KN, SK, SH, SK, QN, SK, QN, AC, JA, QN }, 	 //	 239	 1120
{ KN, KN, KN, SK, SK, KN, SK, SH, JA, QN, SK, QN, AC, JA, QN }, 	 //	 240	 1120
{ KN, KN, KN, SK, SK, KN, SK, SH, QN, QN, SK, QN, AC, KN, QN }, 	 //	 241	 1120
{ KN, KN, QN, KN, SK, KN, SK, QN, SK, QN, SK, QN, QN, QN, QN }, 	 //	 242	 1120
{ KN, KN, QN, SK, SK, KN, SK, QN, QN, QN, SK, QN, QN, KN, QN }, 	 //	 243	 1120
{ KN, KN, QN, WN, QN, KN, SK, QN, QN, QN, SK, QN, SK, QN, QN }, 	 //	 244	 1120
{ KN, KN, QN, QN, SK, KN, SK, QN, QN, QN, SK, QN, SK, QN, QN }, 	 //	 245	 1120
{ KN, KN, QN, QN, QN, KN, SK, QN, QN, QN, SK, QN, SK, QN, SH }, 	 //	 246	 1120
{ KN, KN, QN, QN, QN, KN, SK, SK, QN, QN, SK, QN, JA, QN, QN }, 	 //	 247	 1120
{ KN, KN, QN, QN, QN, KN, SK, SK, QN, QN, SK, QN, JA, SK, QN }, 	 //	 248	 1120
{ KN, KN, AC, KN, KN, KN, SK, WN, KN, KN, SK, QN, KN, SK, SK }, 	 //	 249	 1120
{ KN, KN, KN, QN, KN, KN, SK, KN, QN, KN, SK, QN, KN, SK, SK }, 	 //	 250	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, QN, AC, SK, QN, KN, SK, SK }, 	 //	 251	 1120
{ KN, KN, KN, QN, KN, KN, SK, KN, SK, KN, SK, QN, KN, JA, SK }, 	 //	 252	 1120
{ KN, KN, KN, QN, KN, KN, SK, KN, SK, SK, SK, QN, KN, JA, QN }, 	 //	 253	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, QN, SK, QN, KN, JA, QN }, 	 //	 254	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, KN, SK, QN, KN, JA, KN }, 	 //	 255	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, JA, KN, SK, QN, KN, JA, KN }, 	 //	 256	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, QN, QN, SK, QN, KN, KN, QN }, 	 //	 257	 1120
{ KN, KN, KN, QN, AC, KN, SK, KN, QN, AC, SK, QN, PF, SK, SK }, 	 //	 258	 1120
{ KN, KN, KN, QN, KN, KN, SK, KN, SK, KN, SK, QN, PF, JA, SK }, 	 //	 259	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, QN, SK, QN, PF, JA, QN }, 	 //	 260	 1120
{ KN, KN, KN, QN, SK, KN, SK, KN, SK, KN, SK, QN, PF, JA, KN }, 	 //	 261	 1120
{ KN, KN, KN, SK, SK, KN, SK, KN, QN, KN, SK, QN, PF, KN, KN }, 	 //	 262	 1120
{ KN, KN, KN, QN, KN, KN, SK, PF, QN, KN, SK, QN, QN, SK, SK }, 	 //	 263	 1120
{ KN, KN, KN, QN, KN, KN, SK, PF, SK, SK, SK, QN, QN, JA, QN }, 	 //	 264	 1120
{ KN, KN, KN, QN, SK, KN, SK, PF, SK, QN, SK, QN, QN, JA, QN }, 	 //	 265	 1120
{ KN, KN, KN, SK, SK, KN, SK, PF, QN, KN, SK, QN, QN, KN, KN }, 	 //	 266	 1120
{ KN, KN, QN, KN, KN, KN, SK, AC, KN, KN, SK, QN, KN, SK, SK }, 	 //	 267	 1120
{ KN, KN, QN, SK, SK, KN, SK, AC, QN, KN, SK, QN, KN, KN, KN }, 	 //	 268	 1120
{ KN, KN, AC, KN, KN, KN, SK, KN, KN, KN, SK, QN, WN, SK, SK }, 	 //	 269	 1120
{ KN, QN, QN, QN, AC, SK, QN, QN, SK, AC, QN, QN, SK, JA, SK }, 	 //	 270	 1120
{ KN, QN, QN, QN, KN, SK, QN, SK, SK, KN, QN, QN, JA, JA, SK }, 	 //	 271	 1120
{ KN, QN, QN, QN, AC, SK, QN, QN, SK, AC, QN, SK, SK, JA, AC }, 	 //	 272	 1120
{ KN, QN, QN, QN, AC, SK, QN, QN, SK, AC, QN, SK, SK, JA, CR }, 	 //	 273	 1120
{ KN, QN, QN, QN, CR, SK, QN, QN, SK, KN, QN, SK, SK, JA, KN }, 	 //	 274	 1120
{ KN, QN, QN, QN, SH, SK, QN, QN, SK, JA, QN, SK, SK, JA, JA }, 	 //	 275	 1120
{ KN, QN, QN, QN, JA, SK, QN, QN, SK, JA, QN, SK, SK, JA, JA }, 	 //	 276	 1120
{ KN, QN, QN, QN, JA, SK, QN, QN, SK, WN, QN, SK, SK, JA, TN }, 	 //	 277	 1120
{ KN, QN, QN, QN, WN, SK, QN, QN, SK, TN, QN, SK, SK, JA, TN }, 	 //	 278	 1120
{ KN, QN, QN, QN, TN, SK, QN, QN, SK, ST, QN, SK, SK, JA, AC }, 	 //	 279	 1120
{ KN, QN, QN, QN, AC, SK, QN, QN, SK, KN, QN, SK, SK, JA, QN }, 	 //	 280	 1120
{ KN, QN, QN, QN, KN, SK, QN, QN, SK, QN, QN, SK, SK, JA, PF }, 	 //	 281	 1120
{ KN, QN, QN, QN, JA, SK, QN, QN, SK, TN, QN, SK, SK, JA, AC }, 	 //	 282	 1120
{ KN, QN, QN, QN, AC, SK, QN, QN, SK, AC, QN, SK, SK, JA, AC }, 	 //	 283	 1120
{ KN, QN, QN, QN, KN, SK, QN, QN, SK, KN, QN, SK, SK, JA, KN }, 	 //	 284	 1120
{ KN, QN, QN, QN, KN, SK, QN, QN, SK, KN, QN, SK, SK, JA, CR }, 	 //	 285	 1120
{ KN, QN, QN, QN, CR, SK, QN, QN, SK, QN, QN, SK, SK, JA, KN }, 	 //	 286	 1120
{ KN, QN, QN, QN, KN, SK, QN, SK, SK, KN, QN, SK, JA, JA, SK }, 	 //	 287	 1120
{ KN, QN, QN, QN, SK, SK, QN, SK, SK, QN, QN, SK, JA, JA, QN }, 	 //	 288	 1120
{ KN, QN, QN, QN, SK, SK, QN, SK, SK, KN, QN, SK, JA, JA, KN }, 	 //	 289	 1120
{ KN, QN, KN, KN, KN, SK, SK, WN, SK, KN, QN, JA, TN, QN, SK }, 	 //	 290	 1120
{ KN, QN, ST, KN, KN, SK, SK, AC, KN, KN, QN, JA, KN, SK, SK }, 	 //	 291	 1120
{ KN, QN, AC, KN, KN, SK, SK, KN, KN, KN, QN, JA, QN, SK, SK }, 	 //	 292	 1120
{ KN, QN, KN, KN, KN, SK, SK, QN, SK, KN, QN, JA, PF, QN, SK }, 	 //	 293	 1120
{ KN, QN, QN, KN, KN, SK, SK, PF, KN, KN, QN, JA, KN, SK, SK }, 	 //	 294	 1120
{ KN, QN, PF, SK, SK, SK, SK, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 295	 1120
{ KN, QN, KN, KN, KN, SK, SK, KN, SK, KN, QN, JA, KN, QN, SK }, 	 //	 296	 1120
{ KN, QN, KN, KN, KN, SK, SK, KN, SK, SK, QN, JA, KN, QN, QN }, 	 //	 297	 1120
{ KN, QN, KN, SK, SK, SK, SK, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 298	 1120
{ KN, QN, QN, SK, SK, SK, SK, QN, QN, QN, QN, JA, QN, KN, QN }, 	 //	 299	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, QN, SH, QN, JA, SK, QN, JA }, 	 //	 300	 1120
{ KN, QN, QN, QN, KN, SK, SK, QN, QN, QN, QN, JA, SK, QN, PF }, 	 //	 301	 1120
{ KN, QN, QN, QN, CR, SK, SK, QN, QN, QN, QN, JA, SK, QN, KN }, 	 //	 302	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, QN, KN, QN, JA, SK, QN, AC }, 	 //	 303	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, ST, QN, QN, JA, SK, JA, SH }, 	 //	 304	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, ST, KN, QN, JA, SK, JA, AC }, 	 //	 305	 1120
{ KN, QN, QN, SK, QN, SK, SK, QN, QN, QN, QN, JA, SK, KN, QN }, 	 //	 306	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, KN, QN, QN, JA, SK, AC, SH }, 	 //	 307	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, KN, SH, QN, JA, SK, AC, JA }, 	 //	 308	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, KN, PF, QN, JA, SK, AC, JA }, 	 //	 309	 1120
{ KN, QN, QN, QN, QN, SK, SK, QN, KN, KN, QN, JA, SK, AC, AC }, 	 //	 310	 1120
{ KN, QN, AC, KN, KN, SK, SK, WN, KN, KN, QN, JA, KN, SK, SK }, 	 //	 311	 1120
{ KN, QN, AC, SK, SK, SK, SK, WN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 312	 1120
{ KN, QN, KN, SK, SK, SK, SK, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 313	 1120
{ KN, QN, KN, KN, KN, SK, SK, KN, SK, SK, QN, JA, PF, QN, QN }, 	 //	 314	 1120
{ KN, QN, KN, KN, KN, SK, SK, PF, KN, KN, QN, JA, QN, SK, SK }, 	 //	 315	 1120
{ KN, QN, KN, KN, KN, SK, SK, PF, SK, KN, QN, JA, QN, QN, SK }, 	 //	 316	 1120
{ KN, QN, QN, SK, SK, SK, SK, AC, QN, KN, QN, JA, KN, KN, KN }, 	 //	 317	 1120
{ KN, KN, KN, QN, KN, SK, SK, WN, SK, KN, QN, QN, TN, JA, SK }, 	 //	 318	 1120
{ KN, KN, KN, QN, KN, SK, SK, WN, SK, SK, QN, QN, TN, JA, QN }, 	 //	 319	 1120
{ KN, KN, KN, QN, SK, SK, SK, WN, SK, QN, QN, QN, TN, JA, QN }, 	 //	 320	 1120
{ KN, KN, KN, QN, AC, SK, SK, WN, SK, SK, QN, QN, TN, JA, KN }, 	 //	 321	 1120
{ KN, KN, KN, QN, SK, SK, SK, WN, SK, KN, QN, QN, TN, JA, KN }, 	 //	 322	 1120
{ KN, KN, KN, SK, SK, SK, SK, WN, QN, KN, QN, QN, TN, KN, KN }, 	 //	 323	 1120
{ KN, KN, AC, KN, KN, SK, SK, KN, SK, KN, QN, QN, QN, QN, SK }, 	 //	 324	 1120
{ KN, KN, KN, QN, AC, SK, SK, QN, QN, AC, QN, QN, PF, SK, SK }, 	 //	 325	 1120
{ KN, KN, KN, QN, KN, SK, SK, QN, SK, KN, QN, QN, PF, JA, SK }, 	 //	 326	 1120
{ KN, KN, KN, QN, KN, SK, SK, QN, SK, SK, QN, QN, PF, JA, QN }, 	 //	 327	 1120
{ KN, KN, KN, QN, SK, SK, SK, QN, SK, KN, QN, QN, PF, JA, KN }, 	 //	 328	 1120
{ KN, KN, KN, SK, SK, SK, SK, QN, JA, QN, QN, QN, PF, JA, QN }, 	 //	 329	 1120
{ KN, KN, KN, SK, SK, SK, SK, QN, QN, KN, QN, QN, PF, KN, KN }, 	 //	 330	 1120
{ KN, KN, KN, QN, KN, SK, SK, KN, SK, SK, QN, QN, KN, JA, QN }, 	 //	 331	 1120
{ KN, KN, KN, QN, SK, SK, SK, KN, SK, QN, QN, QN, KN, JA, QN }, 	 //	 332	 1120
{ KN, KN, KN, QN, AC, SK, SK, KN, SK, SK, QN, QN, KN, JA, KN }, 	 //	 333	 1120
{ KN, KN, KN, SK, SK, SK, SK, KN, JA, QN, QN, QN, KN, JA, QN }, 	 //	 334	 1120
{ KN, KN, KN, SK, SK, SK, SK, KN, JA, KN, QN, QN, KN, JA, KN }, 	 //	 335	 1120
{ KN, KN, KN, SK, SK, SK, SK, KN, QN, QN, QN, QN, KN, KN, QN }, 	 //	 336	 1120
{ KN, KN, KN, QN, KN, SK, SK, KN, SK, SK, QN, QN, SH, JA, QN }, 	 //	 337	 1120
{ KN, KN, KN, QN, AC, SK, SK, KN, SK, SK, QN, QN, SH, JA, KN }, 	 //	 338	 1120
{ KN, KN, KN, QN, KN, SK, SK, SH, QN, KN, QN, QN, AC, SK, SK }, 	 //	 339	 1120
{ KN, KN, KN, QN, KN, SK, SK, SH, SK, KN, QN, QN, AC, JA, SK }, 	 //	 340	 1120
{ KN, KN, KN, QN, KN, SK, SK, SH, SK, SK, QN, QN, AC, JA, QN }, 	 //	 341	 1120
{ KN, KN, KN, QN, SK, SK, SK, SH, SK, QN, QN, QN, AC, JA, QN }, 	 //	 342	 1120
{ KN, KN, KN, QN, SK, SK, SK, SH, SK, KN, QN, QN, AC, JA, KN }, 	 //	 343	 1120
{ KN, KN, KN, SK, SK, SK, SK, SH, JA, QN, QN, QN, AC, JA, QN }, 	 //	 344	 1120
{ KN, KN, KN, SK, SK, SK, SK, SH, QN, KN, QN, QN, AC, KN, KN }, 	 //	 345	 1120
{ KN, KN, AC, KN, KN, SK, SK, PF, SK, KN, QN, QN, QN, QN, SK }, 	 //	 346	 1120
{ KN, KN, PF, KN, KN, SK, SK, QN, SK, KN, QN, QN, QN, QN, SK }, 	 //	 347	 1120
{ KN, KN, PF, KN, AC, SK, SK, QN, SK, AC, QN, QN, QN, QN, SK }, 	 //	 348	 1120
{ KN, KN, PF, SK, SK, SK, SK, QN, QN, QN, QN, QN, QN, KN, QN }, 	 //	 349	 1120
{ KN, KN, QN, KN, AC, SK, SK, QN, SK, AC, QN, QN, QN, QN, SK }, 	 //	 350	 1120
{ KN, KN, QN, KN, AC, SK, SK, QN, SK, SK, QN, QN, QN, QN, KN }, 	 //	 351	 1120
{ KN, KN, QN, KN, SK, SK, SK, QN, SK, KN, QN, QN, QN, QN, KN }, 	 //	 352	 1120
{ KN, KN, QN, WN, QN, SK, SK, QN, QN, QN, QN, QN, SK, QN, QN }, 	 //	 353	 1120
{ KN, KN, QN, QN, SK, SK, SK, QN, QN, QN, QN, QN, SK, QN, QN }, 	 //	 354	 1120
{ KN, KN, QN, KN, SK, SK, SK, QN, QN, QN, QN, QN, SK, ST, QN }, 	 //	 355	 1120
{ KN, KN, AC, SK, SK, SK, SK, WN, QN, KN, QN, QN, KN, KN, KN }, 	 //	 356	 1120
{ KN, KN, WN, SK, SK, SK, SK, KN, QN, KN, QN, QN, KN, KN, KN }, 	 //	 357	 1120
{ KN, KN, KN, QN, KN, SK, SK, KN, SK, SK, QN, QN, KN, JA, QN }, 	 //	 358	 1120
{ KN, KN, KN, QN, SK, SK, SK, KN, SK, QN, QN, QN, KN, JA, QN }, 	 //	 359	 1120
{ KN, KN, KN, SK, SK, SK, SK, KN, JA, QN, QN, QN, KN, JA, QN }, 	 //	 360	 1120
{ KN, KN, KN, QN, KN, SK, SK, KN, QN, KN, QN, QN, PF, SK, SK }, 	 //	 361	 1120
{ KN, KN, KN, QN, AC, SK, SK, KN, QN, AC, QN, QN, PF, SK, SK }, 	 //	 362	 1120
{ KN, KN, KN, QN, SK, SK, SK, KN, SK, QN, QN, QN, PF, JA, QN }, 	 //	 363	 1120
{ KN, KN, KN, QN, AC, SK, SK, KN, SK, AC, QN, QN, PF, JA, SK }, 	 //	 364	 1120
{ KN, KN, KN, QN, SK, SK, SK, KN, SK, KN, QN, QN, PF, JA, KN }, 	 //	 365	 1120
{ KN, KN, QN, SK, SK, SK, SK, AC, QN, KN, QN, QN, KN, KN, KN }, 	 //	 366	 1120
{ SK, ST, QN, QN, KN, QN, QN, QN, SK, KN, QN, QN, SK, JA, SK }, 	 //	 367	 1120
{ SK, ST, QN, QN, KN, QN, QN, QN, SK, SK, QN, QN, SK, JA, QN }, 	 //	 368	 1120
{ SK, ST, QN, QN, AC, QN, QN, QN, SK, AC, QN, QN, SK, JA, SK }, 	 //	 369	 1120
{ SK, ST, QN, KN, AC, QN, QN, QN, SK, AC, QN, QN, SK, QN, SK }, 	 //	 370	 1120
{ SK, ST, QN, KN, AC, QN, QN, QN, SK, SK, QN, QN, SK, QN, KN }, 	 //	 371	 1120
{ SK, QN, QN, KN, KN, QN, QN, QN, SK, KN, QN, QN, SK, QN, SK }, 	 //	 372	 1120
{ SK, QN, QN, KN, AC, QN, QN, QN, SK, SK, QN, QN, SK, QN, KN }, 	 //	 373	 1120
{ SK, QN, QN, QN, KN, QN, QN, SK, SK, KN, QN, QN, JA, JA, SK }, 	 //	 374	 1120
{ SK, QN, QN, QN, AC, QN, QN, SK, SK, AC, QN, QN, JA, JA, SK }, 	 //	 375	 1120
{ SK, QN, QN, QN, SK, QN, QN, SK, SK, KN, QN, QN, JA, JA, KN }, 	 //	 376	 1120
{ SK, QN, QN, SK, SK, QN, QN, QN, JA, QN, QN, SK, SK, JA, QN }, 	 //	 377	 1120
{ SK, QN, QN, KN, AC, QN, QN, QN, SK, LO, QN, SK, SK, QN, AC }, 	 //	 378	 1120
{ SK, QN, QN, KN, AC, QN, QN, QN, SK, AC, QN, SK, SK, QN, AC }, 	 //	 379	 1120
{ SK, QN, QN, KN, CR, QN, QN, QN, SK, KN, QN, SK, SK, QN, KN }, 	 //	 380	 1120
{ SK, QN, QN, KN, KN, QN, QN, QN, SK, KN, QN, SK, SK, QN, KN }, 	 //	 381	 1120
{ SK, QN, QN, KN, QN, QN, QN, QN, SK, QN, QN, SK, SK, QN, QN }, 	 //	 382	 1120
{ SK, QN, QN, KN, SH, QN, QN, QN, SK, JA, QN, SK, SK, QN, JA }, 	 //	 383	 1120
{ SK, QN, QN, KN, JA, QN, QN, QN, SK, WN, QN, SK, SK, QN, TN }, 	 //	 384	 1120
{ SK, QN, QN, KN, QN, QN, QN, QN, SK, PF, QN, SK, SK, QN, JA }, 	 //	 385	 1120
{ SK, QN, QN, KN, JA, QN, QN, QN, SK, TN, QN, SK, SK, QN, AC }, 	 //	 386	 1120
{ SK, QN, QN, KN, KN, QN, QN, QN, SK, KN, QN, SK, SK, QN, CR }, 	 //	 387	 1120
{ SK, QN, QN, KN, CR, QN, QN, QN, SK, QN, QN, SK, SK, QN, KN }, 	 //	 388	 1120
{ SK, QN, QN, QN, KN, QN, QN, SK, SK, KN, QN, SK, JA, JA, SK }, 	 //	 389	 1120
{ SK, QN, QN, QN, AC, QN, QN, SK, SK, AC, QN, SK, JA, JA, SK }, 	 //	 390	 1120
{ SK, QN, KN, KN, KN, QN, SK, WN, KN, KN, QN, JA, TN, SK, SK }, 	 //	 391	 1120
{ SK, QN, KN, KN, KN, QN, SK, WN, SK, KN, QN, JA, TN, QN, SK }, 	 //	 392	 1120
{ SK, QN, KN, KN, KN, QN, SK, WN, SK, SK, QN, JA, TN, QN, QN }, 	 //	 393	 1120
{ SK, QN, KN, KN, KN, QN, SK, QN, SK, SK, QN, JA, PF, QN, QN }, 	 //	 394	 1120
{ SK, QN, QN, KN, KN, QN, SK, PF, KN, KN, QN, JA, KN, SK, SK }, 	 //	 395	 1120
{ SK, QN, QN, SK, SK, QN, SK, PF, QN, KN, QN, JA, KN, KN, KN }, 	 //	 396	 1120
{ SK, QN, PF, SK, SK, QN, SK, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 397	 1120
{ SK, QN, KN, KN, KN, QN, SK, KN, SK, KN, QN, JA, KN, QN, SK }, 	 //	 398	 1120
{ SK, QN, KN, KN, KN, QN, SK, KN, SK, SK, QN, JA, SH, QN, QN }, 	 //	 399	 1120
{ SK, QN, QN, QN, KN, QN, SK, SK, QN, SK, QN, JA, JA, QN, QN }, 	 //	 400	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, QN, SH, QN, JA, JA, QN, JA }, 	 //	 401	 1120
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, KN, QN, JA, JA, QN, QN }, 	 //	 402	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, QN, PF, QN, JA, JA, QN, JA }, 	 //	 403	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, QN, KN, QN, JA, JA, QN, AC }, 	 //	 404	 1120
{ SK, QN, QN, QN, KN, QN, SK, SK, QN, SK, QN, JA, JA, SK, QN }, 	 //	 405	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, QN, PF, QN, JA, JA, SK, JA }, 	 //	 406	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, QN, KN, QN, JA, JA, SK, AC }, 	 //	 407	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, KN, QN, QN, JA, JA, AC, QN }, 	 //	 408	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, KN, SH, QN, JA, JA, AC, JA }, 	 //	 409	 1120
{ SK, QN, QN, QN, QN, QN, SK, SK, KN, KN, QN, JA, JA, AC, AC }, 	 //	 410	 1120
{ SK, QN, AC, KN, KN, QN, SK, WN, KN, KN, QN, JA, KN, SK, SK }, 	 //	 411	 1120
{ SK, QN, KN, KN, KN, QN, SK, KN, SK, KN, QN, JA, KN, QN, SK }, 	 //	 412	 1120
{ SK, QN, KN, SK, SK, QN, SK, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 413	 1120
{ SK, QN, KN, KN, KN, QN, SK, PF, SK, KN, QN, JA, QN, QN, SK }, 	 //	 414	 1120
{ SK, SK, KN, KN, KN, QN, JA, WN, KN, KN, QN, JA, TN, SK, SK }, 	 //	 415	 1120
{ SK, SK, KN, KN, KN, QN, JA, WN, SK, KN, QN, JA, TN, QN, SK }, 	 //	 416	 1120
{ SK, SK, KN, KN, KN, QN, JA, WN, SK, SK, QN, JA, TN, QN, QN }, 	 //	 417	 1120
{ SK, SK, ST, SK, SK, QN, JA, AC, QN, KN, QN, JA, KN, KN, KN }, 	 //	 418	 1120
{ SK, SK, KN, KN, KN, QN, JA, QN, SK, SK, QN, JA, PF, QN, QN }, 	 //	 419	 1120
{ SK, SK, QN, KN, KN, QN, JA, PF, KN, KN, QN, JA, KN, SK, SK }, 	 //	 420	 1120
{ SK, SK, QN, SK, SK, QN, JA, PF, QN, KN, QN, JA, KN, KN, KN }, 	 //	 421	 1120
{ SK, SK, PF, SK, SK, QN, JA, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 422	 1120
{ SK, SK, KN, SK, SK, QN, JA, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 423	 1120
{ SK, SK, KN, KN, KN, QN, JA, KN, SK, SK, QN, JA, SH, QN, QN }, 	 //	 424	 1120
{ SK, SK, KN, KN, KN, QN, JA, SH, KN, KN, QN, JA, AC, SK, SK }, 	 //	 425	 1120
{ SK, SK, KN, KN, KN, QN, JA, SH, SK, KN, QN, JA, AC, QN, SK }, 	 //	 426	 1120
{ SK, SK, QN, SK, SK, QN, JA, QN, QN, QN, QN, JA, QN, KN, QN }, 	 //	 427	 1120
{ SK, SK, QN, QN, SK, QN, JA, QN, QN, QN, QN, JA, SK, SK, QN }, 	 //	 428	 1120
{ SK, SK, QN, SK, SK, QN, JA, QN, QN, QN, QN, JA, SK, KN, QN }, 	 //	 429	 1120
{ SK, SK, AC, SK, SK, QN, JA, WN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 430	 1120
{ SK, SK, WN, SK, SK, QN, JA, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 431	 1120
{ SK, SK, KN, KN, KN, QN, JA, KN, SK, SK, QN, JA, KN, QN, QN }, 	 //	 432	 1120
{ SK, SK, KN, SK, SK, QN, JA, KN, QN, KN, QN, JA, KN, KN, KN }, 	 //	 433	 1120
{ SK, SK, KN, KN, KN, QN, JA, KN, SK, KN, QN, JA, PF, QN, SK }, 	 //	 434	 1120
{ SK, SK, QN, KN, KN, QN, JA, AC, KN, KN, QN, JA, KN, SK, SK }, 	 //	 435	 1120
{ SK, KN, QN, QN, KN, QN, QN, QN, SK, SK, QN, ST, SK, JA, QN }, 	 //	 436	 1120
{ SK, KN, QN, QN, AC, QN, QN, QN, SK, AC, QN, ST, SK, JA, SK }, 	 //	 437	 1120
{ SK, KN, QN, QN, AC, QN, QN, QN, SK, SK, QN, ST, SK, JA, KN }, 	 //	 438	 1120
{ SK, KN, QN, KN, KN, QN, QN, QN, SK, SK, QN, ST, SK, QN, QN }, 	 //	 439	 1120
{ SK, KN, QN, KN, AC, QN, QN, QN, SK, AC, QN, ST, SK, QN, SK }, 	 //	 440	 1120
{ SK, KN, QN, KN, AC, QN, QN, QN, SK, SK, QN, ST, SK, QN, KN }, 	 //	 441	 1120
{ SK, KN, KN, KN, AC, QN, SK, WN, KN, AC, QN, QN, TN, SK, SK }, 	 //	 442	 1120
{ SK, KN, KN, KN, SK, QN, SK, WN, SK, QN, QN, QN, TN, QN, QN }, 	 //	 443	 1120
{ SK, KN, KN, KN, AC, QN, SK, WN, SK, AC, QN, QN, TN, QN, SK }, 	 //	 444	 1120
{ SK, KN, ST, SK, SK, QN, SK, AC, QN, KN, QN, QN, KN, KN, KN }, 	 //	 445	 1120
{ SK, KN, AC, KN, SK, QN, SK, KN, SK, KN, QN, QN, QN, QN, KN }, 	 //	 446	 1120
{ SK, KN, KN, KN, AC, QN, SK, QN, KN, AC, QN, QN, PF, SK, SK }, 	 //	 447	 1120
{ SK, KN, KN, KN, SK, QN, SK, QN, SK, QN, QN, QN, PF, QN, QN }, 	 //	 448	 1120
{ SK, KN, KN, KN, AC, QN, SK, QN, SK, AC, QN, QN, PF, QN, SK }, 	 //	 449	 1120
{ SK, KN, KN, KN, SK, QN, SK, KN, SK, QN, QN, QN, KN, QN, QN }, 	 //	 450	 1120
{ SK, KN, KN, KN, AC, QN, SK, KN, SK, SK, QN, QN, KN, QN, KN }, 	 //	 451	 1120
{ SK, KN, KN, SK, SK, QN, SK, KN, QN, KN, QN, QN, KN, KN, KN }, 	 //	 452	 1120
{ SK, KN, KN, KN, AC, QN, SK, KN, KN, AC, QN, QN, SH, SK, SK }, 	 //	 453	 1120
{ SK, KN, KN, KN, AC, QN, SK, SH, KN, AC, QN, QN, AC, SK, SK }, 	 //	 454	 1120
{ SK, KN, KN, KN, SK, QN, SK, SH, SK, QN, QN, QN, AC, QN, QN }, 	 //	 455	 1120
{ SK, KN, KN, KN, AC, QN, SK, SH, SK, AC, QN, QN, AC, QN, SK }, 	 //	 456	 1120
{ SK, KN, KN, KN, AC, QN, SK, SH, SK, SK, QN, QN, AC, QN, KN }, 	 //	 457	 1120
{ SK, KN, AC, KN, KN, QN, SK, PF, SK, KN, QN, QN, QN, QN, SK }, 	 //	 458	 1120
{ SK, KN, AC, KN, AC, QN, SK, PF, SK, AC, QN, QN, QN, QN, SK }, 	 //	 459	 1120
{ SK, KN, AC, KN, AC, QN, SK, PF, SK, SK, QN, QN, QN, QN, KN }, 	 //	 460	 1120
{ SK, KN, PF, KN, AC, QN, SK, QN, SK, SK, QN, QN, QN, QN, KN }, 	 //	 461	 1120
{ SK, KN, PF, KN, SK, QN, SK, QN, SK, KN, QN, QN, QN, QN, KN }, 	 //	 462	 1120
{ SK, KN, QN, KN, AC, QN, SK, QN, SK, AC, QN, QN, QN, QN, SK }, 	 //	 463	 1120
{ SK, KN, QN, KN, AC, QN, SK, QN, SK, SK, QN, QN, QN, QN, KN }, 	 //	 464	 1120
{ SK, KN, QN, QN, QN, QN, SK, SK, QN, QN, QN, QN, JA, SK, QN }, 	 //	 465	 1120
{ SK, KN, AC, KN, KN, QN, SK, WN, KN, KN, QN, QN, KN, SK, SK }, 	 //	 466	 1120
{ SK, KN, KN, KN, SK, QN, SK, KN, SK, QN, QN, QN, KN, QN, QN }, 	 //	 467	 1120
{ SK, KN, KN, KN, SK, QN, SK, KN, SK, KN, QN, QN, KN, QN, KN }, 	 //	 468	 1120
{ SK, KN, KN, KN, AC, QN, SK, KN, KN, AC, QN, QN, PF, SK, SK }, 	 //	 469	 1120
{ SK, KN, KN, KN, AC, QN, SK, KN, SK, AC, QN, QN, PF, QN, SK }, 	 //	 470	 1120
{ SK, KN, KN, KN, AC, QN, SK, KN, SK, SK, QN, QN, PF, QN, KN }, 	 //	 471	 1120
{ SK, KN, KN, KN, SK, QN, SK, KN, SK, KN, QN, QN, PF, QN, KN }, 	 //	 472	 1120
{ SK, KN, QN, SK, SK, QN, SK, AC, QN, KN, QN, QN, KN, KN, KN }, 	 //	 473	 1120
{ SK, KN, AC, KN, KN, QN, SK, KN, KN, KN, QN, QN, WN, SK, SK }, 	 //	 474	 1120
{ SK, SK, KN, KN, KN, QN, QN, WN, KN, KN, QN, KN, TN, SK, SK }, 	 //	 475	 1120
{ SK, SK, ST, KN, KN, QN, QN, AC, KN, KN, QN, KN, KN, SK, SK }, 	 //	 476	 1120
{ SK, SK, ST, SK, SK, QN, QN, AC, QN, QN, QN, KN, KN, KN, QN }, 	 //	 477	 1120
{ SK, SK, KN, QN, KN, QN, QN, QN, QN, KN, QN, KN, PF, SK, SK }, 	 //	 478	 1120
{ SK, SK, QN, QN, AC, QN, QN, PF, QN, AC, QN, KN, KN, SK, SK }, 	 //	 479	 1120
{ SK, SK, KN, KN, KN, QN, QN, KN, SK, KN, QN, KN, KN, QN, SK }, 	 //	 480	 1120
{ SK, SK, KN, KN, KN, QN, QN, KN, SK, SK, QN, KN, KN, QN, QN }, 	 //	 481	 1120
{ SK, SK, KN, KN, KN, QN, QN, KN, SK, SK, QN, KN, SH, QN, QN }, 	 //	 482	 1120
{ SK, SK, QN, QN, KN, QN, QN, QN, SK, KN, QN, KN, QN, JA, SK }, 	 //	 483	 1120
{ SK, SK, QN, QN, SK, QN, QN, QN, SK, QN, QN, KN, QN, JA, QN }, 	 //	 484	 1120
{ SK, SK, QN, QN, AC, QN, QN, QN, SK, AC, QN, KN, QN, JA, SK }, 	 //	 485	 1120
{ SK, SK, QN, QN, AC, QN, QN, QN, SK, SK, QN, KN, QN, JA, KN }, 	 //	 486	 1120
{ SK, SK, QN, QN, SK, QN, QN, QN, SK, KN, QN, KN, QN, JA, KN }, 	 //	 487	 1120
{ SK, SK, QN, SK, SK, QN, QN, QN, JA, QN, QN, KN, QN, JA, QN }, 	 //	 488	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, SK, AC, QN, KN, QN, QN, SK }, 	 //	 489	 1120
{ SK, SK, QN, KN, SK, QN, QN, QN, SK, KN, QN, KN, QN, QN, KN }, 	 //	 490	 1120
{ SK, SK, QN, QN, JA, QN, QN, QN, SK, JA, QN, KN, SK, JA, JA }, 	 //	 491	 1120
{ SK, SK, QN, QN, JA, QN, QN, QN, SK, JA, QN, KN, SK, JA, WN }, 	 //	 492	 1120
{ SK, SK, QN, QN, ST, QN, QN, QN, SK, AC, QN, KN, SK, JA, KN }, 	 //	 493	 1120
{ SK, SK, QN, QN, KN, QN, QN, QN, SK, QN, QN, KN, SK, JA, PF }, 	 //	 494	 1120
{ SK, SK, QN, QN, PF, QN, QN, QN, SK, JA, QN, KN, SK, JA, TN }, 	 //	 495	 1120
{ SK, SK, QN, QN, JA, QN, QN, QN, SK, TN, QN, KN, SK, JA, AC }, 	 //	 496	 1120
{ SK, SK, QN, QN, TN, QN, QN, QN, SK, AC, QN, KN, SK, JA, AC }, 	 //	 497	 1120
{ SK, SK, QN, QN, AC, QN, QN, QN, SK, AC, QN, KN, SK, JA, AC }, 	 //	 498	 1120
{ SK, SK, QN, QN, KN, QN, QN, QN, SK, KN, QN, KN, SK, JA, KN }, 	 //	 499	 1120
{ SK, SK, QN, QN, KN, QN, QN, QN, SK, KN, QN, KN, SK, JA, CR }, 	 //	 500	 1120
{ SK, SK, QN, SK, SK, QN, QN, QN, JA, QN, QN, KN, SK, JA, QN }, 	 //	 501	 1120
{ SK, SK, QN, KN, LO, QN, QN, QN, KN, AC, QN, KN, SK, SK, AC }, 	 //	 502	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, KN, AC, QN, KN, SK, SK, CR }, 	 //	 503	 1120
{ SK, SK, QN, KN, CR, QN, QN, QN, KN, KN, QN, KN, SK, SK, KN }, 	 //	 504	 1120
{ SK, SK, QN, KN, KN, QN, QN, QN, KN, KN, QN, KN, SK, SK, KN }, 	 //	 505	 1120
{ SK, SK, QN, KN, KN, QN, QN, QN, KN, SK, QN, KN, SK, SK, QN }, 	 //	 506	 1120
{ SK, SK, QN, KN, SK, QN, QN, QN, KN, QN, QN, KN, SK, SK, QN }, 	 //	 507	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, KN, QN, QN, KN, SK, SK, SH }, 	 //	 508	 1120
{ SK, SK, QN, KN, SH, QN, QN, QN, KN, JA, QN, KN, SK, SK, JA }, 	 //	 509	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, KN, JA, QN, KN, SK, SK, JA }, 	 //	 510	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, KN, JA, QN, KN, SK, SK, WN }, 	 //	 511	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, KN, WN, QN, KN, SK, SK, TN }, 	 //	 512	 1120
{ SK, SK, QN, KN, TN, QN, QN, QN, KN, TN, QN, KN, SK, SK, TN }, 	 //	 513	 1120
{ SK, SK, QN, KN, TN, QN, QN, QN, KN, ST, QN, KN, SK, SK, AC }, 	 //	 514	 1120
{ SK, SK, QN, KN, ST, QN, QN, QN, KN, AC, QN, KN, SK, SK, KN }, 	 //	 515	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, KN, TN, QN, KN, SK, SK, AC }, 	 //	 516	 1120
{ SK, SK, QN, KN, TN, QN, QN, QN, KN, AC, QN, KN, SK, SK, AC }, 	 //	 517	 1120
{ SK, SK, QN, KN, SK, QN, QN, QN, KN, KN, QN, KN, SK, SK, KN }, 	 //	 518	 1120
{ SK, SK, QN, KN, KN, QN, QN, QN, KN, KN, QN, KN, SK, SK, KN }, 	 //	 519	 1120
{ SK, SK, QN, KN, CR, QN, QN, QN, KN, QN, QN, KN, SK, SK, KN }, 	 //	 520	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, KN, KN, QN, KN, SK, SK, AC }, 	 //	 521	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, SK, LO, QN, KN, SK, QN, AC }, 	 //	 522	 1120
{ SK, SK, QN, KN, LO, QN, QN, QN, SK, AC, QN, KN, SK, QN, AC }, 	 //	 523	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, SK, AC, QN, KN, SK, QN, AC }, 	 //	 524	 1120
{ SK, SK, QN, KN, KN, QN, QN, QN, SK, KN, QN, KN, SK, QN, KN }, 	 //	 525	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, SK, QN, QN, KN, SK, QN, QN }, 	 //	 526	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, SK, QN, QN, KN, SK, QN, SH }, 	 //	 527	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, SK, SH, QN, KN, SK, QN, JA }, 	 //	 528	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, SK, JA, QN, KN, SK, QN, JA }, 	 //	 529	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, SK, JA, QN, KN, SK, QN, WN }, 	 //	 530	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, SK, WN, QN, KN, SK, QN, TN }, 	 //	 531	 1120
{ SK, SK, QN, KN, WN, QN, QN, QN, SK, TN, QN, KN, SK, QN, TN }, 	 //	 532	 1120
{ SK, SK, QN, KN, TN, QN, QN, QN, SK, TN, QN, KN, SK, QN, ST }, 	 //	 533	 1120
{ SK, SK, QN, KN, TN, QN, QN, QN, SK, ST, QN, KN, SK, QN, AC }, 	 //	 534	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, SK, KN, QN, KN, SK, QN, QN }, 	 //	 535	 1120
{ SK, SK, QN, KN, QN, QN, QN, QN, SK, PF, QN, KN, SK, QN, JA }, 	 //	 536	 1120
{ SK, SK, QN, KN, PF, QN, QN, QN, SK, JA, QN, KN, SK, QN, TN }, 	 //	 537	 1120
{ SK, SK, QN, KN, JA, QN, QN, QN, SK, TN, QN, KN, SK, QN, AC }, 	 //	 538	 1120
{ SK, SK, QN, KN, AC, QN, QN, QN, SK, AC, QN, KN, SK, QN, AC }, 	 //	 539	 1120
{ SK, SK, QN, KN, KN, QN, QN, QN, SK, KN, QN, KN, SK, QN, KN }, 	 //	 540	 1120
{ SK, SK, QN, QN, AC, QN, QN, SK, QN, AC, QN, KN, JA, SK, SK }, 	 //	 541	 1120
{ SK, SK, QN, QN, QN, QN, QN, SK, SK, QN, QN, KN, JA, JA, QN }, 	 //	 542	 1120
{ SK, SK, QN, QN, QN, QN, QN, SK, SK, KN, QN, KN, JA, JA, AC }, 	 //	 543	 1120
{ SK, SK, QN, SK, SK, QN, QN, SK, QN, KN, QN, KN, JA, KN, KN }, 	 //	 544	 1120
{ SK, SK, AC, KN, KN, QN, QN, WN, KN, KN, QN, KN, KN, SK, SK }, 	 //	 545	 1120
{ SK, SK, WN, SK, SK, QN, QN, KN, QN, QN, QN, KN, KN, KN, QN }, 	 //	 546	 1120
{ SK, SK, KN, KN, KN, QN, QN, KN, SK, KN, QN, KN, KN, QN, SK }, 	 //	 547	 1120
{ SK, SK, KN, KN, KN, QN, QN, KN, SK, SK, QN, KN, KN, QN, QN }, 	 //	 548	 1120
{ SK, SK, KN, SK, SK, QN, QN, KN, QN, QN, QN, KN, KN, KN, QN }, 	 //	 549	 1120
{ SK, SK, KN, KN, KN, QN, QN, PF, SK, KN, QN, KN, QN, QN, SK }, 	 //	 550	 1120
{ SK, SK, PF, QN, KN, QN, QN, QN, QN, KN, QN, KN, AC, SK, SK }, 	 //	 551	 1120
{ SK, SK, PF, QN, AC, QN, QN, QN, QN, AC, QN, KN, AC, SK, SK }, 	 //	 552	 1120
{ SK, SK, QN, QN, KN, QN, QN, AC, QN, KN, QN, KN, KN, SK, SK }, 	 //	 553	 1120
{ QN, ST, QN, QN, KN, QN, QN, QN, SK, KN, QN, QN, SK, JA, SK }, 	 //	 554	 1120
{ QN, ST, QN, KN, KN, QN, QN, QN, SK, KN, QN, QN, SK, QN, SK }, 	 //	 555	 1120
{ QN, ST, QN, KN, KN, QN, QN, QN, SK, SK, QN, QN, SK, QN, QN }, 	 //	 556	 1120
{ QN, ST, QN, KN, AC, QN, QN, QN, SK, AC, QN, QN, SK, QN, SK }, 	 //	 557	 1120
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 558	 1120
{ QN, QN, QN, KN, AC, QN, QN, SK, SK, AC, QN, QN, JA, QN, SK }, 	 //	 559	 1120
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, KN, QN, QN, JA, QN, KN }, 	 //	 560	 1120
{ QN, QN, QN, KN, KN, QN, QN, SK, SK, KN, QN, SK, JA, QN, SK }, 	 //	 561	 1120
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, QN, QN, SK, JA, QN, QN }, 	 //	 562	 1120
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, KN, QN, SK, JA, QN, KN }, 	 //	 563	 1120
{ QN, QN, QN, QN, LO, QN, SK, QN, QN, AC, QN, JA, SK, SK, AC }, 	 //	 564	 1120
{ QN, QN, QN, QN, AC, QN, SK, QN, QN, AC, QN, JA, SK, SK, CR }, 	 //	 565	 1120
{ QN, QN, QN, QN, CR, QN, SK, QN, QN, KN, QN, JA, SK, SK, KN }, 	 //	 566	 1120
{ QN, QN, QN, QN, KN, QN, SK, QN, QN, KN, QN, JA, SK, SK, KN }, 	 //	 567	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, JA, QN, JA, SK, SK, JA }, 	 //	 568	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, JA, QN, JA, SK, SK, WN }, 	 //	 569	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, WN, QN, JA, SK, SK, TN }, 	 //	 570	 1120
{ QN, QN, QN, QN, TN, QN, SK, QN, QN, ST, QN, JA, SK, SK, AC }, 	 //	 571	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, TN, QN, JA, SK, SK, AC }, 	 //	 572	 1120
{ QN, QN, QN, QN, KN, QN, SK, QN, QN, AC, QN, JA, SK, SK, LO }, 	 //	 573	 1120
{ QN, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, SK, SK }, 	 //	 574	 1120
{ QN, KN, QN, QN, KN, QN, QN, QN, SK, SK, QN, ST, SK, JA, QN }, 	 //	 575	 1120
{ QN, KN, QN, QN, AC, QN, QN, QN, SK, SK, QN, ST, SK, JA, KN }, 	 //	 576	 1120
{ QN, KN, QN, KN, KN, QN, QN, QN, SK, KN, QN, ST, SK, QN, SK }, 	 //	 577	 1120
{ QN, QN, QN, QN, KN, QN, ST, QN, SK, KN, QN, JA, SK, JA, SK }, 	 //	 578	 1120
{ QN, QN, QN, QN, KN, QN, ST, QN, SK, SK, QN, JA, SK, JA, QN }, 	 //	 579	 1120
{ QN, QN, QN, QN, AC, QN, ST, QN, SK, AC, QN, JA, SK, JA, SK }, 	 //	 580	 1120
{ QN, SK, QN, QN, KN, QN, QN, QN, SK, KN, QN, KN, SK, JA, SK }, 	 //	 581	 1120
{ QN, SK, QN, QN, AC, QN, QN, QN, SK, AC, QN, KN, SK, JA, SK }, 	 //	 582	 1120
{ QN, SK, QN, QN, AC, QN, QN, QN, SK, SK, QN, KN, SK, JA, KN }, 	 //	 583	 1120
{ QN, SK, QN, KN, KN, QN, QN, QN, SK, KN, QN, KN, SK, QN, SK }, 	 //	 584	 1120
{ QN, SK, QN, KN, AC, QN, QN, QN, SK, SK, QN, KN, SK, QN, KN }, 	 //	 585	 1120
{ QN, QN, QN, QN, KN, QN, KN, QN, SK, SK, QN, AC, SK, JA, QN }, 	 //	 586	 1120
{ QN, QN, QN, QN, AC, QN, KN, QN, SK, SK, QN, AC, SK, JA, KN }, 	 //	 587	 1120
{ QN, QN, QN, QN, KN, QN, KN, SK, SK, KN, QN, AC, JA, JA, SK }, 	 //	 588	 1120
{ QN, QN, QN, QN, SK, QN, KN, SK, SK, QN, QN, AC, JA, JA, QN }, 	 //	 589	 1120
{ QN, QN, QN, QN, AC, QN, KN, SK, SK, AC, QN, AC, JA, JA, SK }, 	 //	 590	 1120
{ QN, QN, QN, KN, KN, QN, QN, QN, SK, KN, SH, QN, SK, QN, SK }, 	 //	 591	 1120
{ QN, QN, QN, KN, KN, QN, QN, QN, SK, SK, SH, QN, SK, QN, QN }, 	 //	 592	 1120
{ QN, QN, QN, KN, AC, QN, QN, QN, SK, SK, SH, QN, SK, QN, KN }, 	 //	 593	 1120
{ QN, QN, QN, QN, SK, QN, QN, SK, SK, KN, SH, QN, JA, JA, KN }, 	 //	 594	 1120
{ QN, QN, QN, SK, SK, QN, QN, QN, JA, KN, SH, SK, SK, JA, KN }, 	 //	 595	 1120
{ QN, QN, QN, KN, AC, QN, QN, QN, SK, LO, SH, SK, SK, QN, AC }, 	 //	 596	 1120
{ QN, QN, QN, KN, AC, QN, QN, QN, SK, AC, SH, SK, SK, QN, AC }, 	 //	 597	 1120
{ QN, QN, QN, KN, KN, QN, QN, QN, SK, KN, SH, SK, SK, QN, KN }, 	 //	 598	 1120
{ QN, QN, QN, KN, QN, QN, QN, QN, SK, QN, SH, SK, SK, QN, QN }, 	 //	 599	 1120
{ QN, QN, QN, KN, QN, QN, QN, QN, SK, QN, SH, SK, SK, QN, SH }, 	 //	 600	 1120
{ QN, QN, QN, KN, QN, QN, QN, QN, SK, SH, SH, SK, SK, QN, JA }, 	 //	 601	 1120
{ QN, QN, QN, KN, JA, QN, QN, QN, SK, JA, SH, SK, SK, QN, JA }, 	 //	 602	 1120
{ QN, QN, QN, KN, JA, QN, QN, QN, SK, JA, SH, SK, SK, QN, WN }, 	 //	 603	 1120
{ QN, QN, QN, KN, JA, QN, QN, QN, SK, WN, SH, SK, SK, QN, TN }, 	 //	 604	 1120
{ QN, QN, QN, KN, WN, QN, QN, QN, SK, TN, SH, SK, SK, QN, TN }, 	 //	 605	 1120
{ QN, QN, QN, KN, TN, QN, QN, QN, SK, TN, SH, SK, SK, QN, ST }, 	 //	 606	 1120
{ QN, QN, QN, KN, TN, QN, QN, QN, SK, ST, SH, SK, SK, QN, AC }, 	 //	 607	 1120
{ QN, QN, QN, KN, AC, QN, QN, QN, SK, KN, SH, SK, SK, QN, QN }, 	 //	 608	 1120
{ QN, QN, QN, KN, PF, QN, QN, QN, SK, JA, SH, SK, SK, QN, TN }, 	 //	 609	 1120
{ QN, QN, QN, KN, JA, QN, QN, QN, SK, TN, SH, SK, SK, QN, AC }, 	 //	 610	 1120
{ QN, QN, QN, KN, AC, QN, QN, QN, SK, AC, SH, SK, SK, QN, AC }, 	 //	 611	 1120
{ QN, QN, QN, KN, KN, QN, QN, QN, SK, AC, SH, SK, SK, QN, LO }, 	 //	 612	 1120
{ QN, QN, QN, QN, SK, QN, QN, SK, SK, QN, SH, SK, JA, JA, QN }, 	 //	 613	 1120
{ QN, QN, QN, QN, SK, QN, QN, SK, SK, KN, SH, SK, JA, JA, KN }, 	 //	 614	 1120
{ QN, QN, QN, QN, LO, QN, SK, QN, QN, AC, SH, JA, SK, SK, AC }, 	 //	 615	 1120
{ QN, QN, QN, QN, AC, QN, SK, QN, QN, AC, SH, JA, SK, SK, AC }, 	 //	 616	 1120
{ QN, QN, QN, QN, KN, QN, SK, QN, QN, KN, SH, JA, SK, SK, KN }, 	 //	 617	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, JA, SH, JA, SK, SK, WN }, 	 //	 618	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, WN, SH, JA, SK, SK, TN }, 	 //	 619	 1120
{ QN, QN, QN, QN, WN, QN, SK, QN, QN, TN, SH, JA, SK, SK, TN }, 	 //	 620	 1120
{ QN, QN, QN, QN, TN, QN, SK, QN, QN, TN, SH, JA, SK, SK, TN }, 	 //	 621	 1120
{ QN, QN, QN, QN, TN, QN, SK, QN, QN, ST, SH, JA, SK, SK, AC }, 	 //	 622	 1120
{ QN, QN, QN, QN, ST, QN, SK, QN, QN, AC, SH, JA, SK, SK, KN }, 	 //	 623	 1120
{ QN, QN, QN, QN, PF, QN, SK, QN, QN, JA, SH, JA, SK, SK, TN }, 	 //	 624	 1120
{ QN, QN, QN, QN, JA, QN, SK, QN, QN, TN, SH, JA, SK, SK, AC }, 	 //	 625	 1120
{ QN, QN, QN, QN, TN, QN, SK, QN, QN, AC, SH, JA, SK, SK, AC }, 	 //	 626	 1120
{ QN, QN, QN, QN, AC, QN, SK, QN, QN, SK, SH, JA, SK, SK, KN }, 	 //	 627	 1120
{ QN, QN, QN, QN, SK, QN, SK, QN, QN, KN, SH, JA, SK, SK, KN }, 	 //	 628	 1120
{ QN, QN, QN, QN, KN, QN, SK, QN, QN, KN, SH, JA, SK, SK, KN }, 	 //	 629	 1120
{ QN, QN, QN, QN, KN, QN, SK, QN, QN, KN, SH, JA, SK, SK, CR }, 	 //	 630	 1120
{ QN, QN, QN, QN, KN, QN, SK, SK, QN, KN, SH, JA, JA, SK, SK }, 	 //	 631	 1120
{ QN, QN, QN, SK, SK, QN, SK, SK, QN, QN, SH, JA, JA, KN, QN }, 	 //	 632	 1120
{ QN, QN, QN, QN, KN, QN, ST, QN, SK, KN, SH, JA, SK, JA, SK }, 	 //	 633	 1120
{ QN, QN, QN, QN, AC, QN, ST, QN, SK, AC, SH, JA, SK, JA, SK }, 	 //	 634	 1120
{ QN, KN, QN, QN, SK, QN, SK, QN, QN, QN, SH, QN, SK, SK, QN }, 	 //	 635	 1120
{ QN, KN, QN, QN, QN, QN, SK, QN, QN, QN, SH, QN, SK, SK, SH }, 	 //	 636	 1120
{ QN, QN, QN, QN, KN, QN, KN, QN, SK, SK, SH, AC, SK, JA, QN }, 	 //	 637	 1120
{ QN, QN, QN, QN, AC, QN, KN, QN, SK, SK, SH, AC, SK, JA, KN }, 	 //	 638	 1120
{ QN, QN, QN, QN, KN, QN, KN, SK, SK, KN, SH, AC, JA, JA, SK }, 	 //	 639	 1120
{ QN, QN, QN, QN, AC, QN, KN, SK, SK, AC, SH, AC, JA, JA, SK }, 	 //	 640	 1120
{ QN, QN, QN, QN, SK, QN, KN, SK, SK, KN, SH, AC, JA, JA, KN }, 	 //	 641	 1120
{ QN, QN, QN, QN, KN, SH, QN, QN, SK, KN, JA, QN, SK, JA, SK }, 	 //	 642	 1120
{ QN, QN, QN, QN, KN, SH, QN, QN, SK, SK, JA, QN, SK, JA, QN }, 	 //	 643	 1120
{ QN, QN, QN, QN, AC, SH, QN, QN, SK, AC, JA, QN, SK, JA, SK }, 	 //	 644	 1120
{ QN, QN, QN, QN, AC, SH, QN, QN, SK, SK, JA, QN, SK, JA, KN }, 	 //	 645	 1120
{ QN, QN, QN, QN, SK, SH, QN, SK, SK, QN, JA, QN, JA, JA, QN }, 	 //	 646	 1120
{ QN, QN, QN, QN, AC, SH, QN, SK, SK, AC, JA, QN, JA, JA, SK }, 	 //	 647	 1120
{ QN, QN, QN, QN, SK, SH, QN, SK, SK, KN, JA, QN, JA, JA, KN }, 	 //	 648	 1120
{ QN, QN, QN, QN, AC, SH, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 649	 1120
{ QN, QN, QN, QN, CR, SH, QN, QN, SK, KN, JA, SK, SK, JA, KN }, 	 //	 650	 1120
{ QN, QN, QN, QN, KN, SH, QN, QN, SK, KN, JA, SK, SK, JA, KN }, 	 //	 651	 1120
{ QN, QN, QN, QN, JA, SH, QN, QN, SK, JA, JA, SK, SK, JA, JA }, 	 //	 652	 1120
{ QN, QN, QN, QN, JA, SH, QN, QN, SK, JA, JA, SK, SK, JA, WN }, 	 //	 653	 1120
{ QN, QN, QN, QN, JA, SH, QN, QN, SK, WN, JA, SK, SK, JA, TN }, 	 //	 654	 1120
{ QN, QN, QN, QN, TN, SH, QN, QN, SK, TN, JA, SK, SK, JA, TN }, 	 //	 655	 1120
{ QN, QN, QN, QN, TN, SH, QN, QN, SK, TN, JA, SK, SK, JA, ST }, 	 //	 656	 1120
{ QN, QN, QN, QN, AC, SH, QN, QN, SK, KN, JA, SK, SK, JA, QN }, 	 //	 657	 1120
{ QN, QN, QN, QN, PF, SH, QN, QN, SK, JA, JA, SK, SK, JA, TN }, 	 //	 658	 1120
{ QN, QN, QN, QN, JA, SH, QN, QN, SK, TN, JA, SK, SK, JA, AC }, 	 //	 659	 1120
{ QN, QN, QN, QN, AC, SH, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 660	 1120
{ QN, QN, QN, QN, KN, SH, QN, QN, SK, KN, JA, SK, SK, JA, KN }, 	 //	 661	 1120
{ QN, QN, QN, QN, KN, SH, QN, QN, SK, KN, JA, SK, SK, JA, CR }, 	 //	 662	 1120
{ QN, QN, QN, QN, KN, SH, QN, SK, SK, KN, JA, SK, JA, JA, SK }, 	 //	 663	 1120
{ QN, QN, QN, QN, SK, SH, QN, SK, SK, KN, JA, SK, JA, JA, KN }, 	 //	 664	 1120
{ QN, QN, QN, QN, AC, SH, SK, QN, QN, LO, JA, JA, SK, SK, AC }, 	 //	 665	 1120
{ QN, QN, QN, QN, LO, SH, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 666	 1120
{ QN, QN, QN, QN, AC, SH, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 667	 1120
{ QN, QN, QN, QN, AC, SH, SK, QN, QN, AC, JA, JA, SK, SK, CR }, 	 //	 668	 1120
{ QN, QN, QN, QN, CR, SH, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 669	 1120
{ QN, QN, QN, QN, KN, SH, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 670	 1120
{ QN, QN, QN, QN, SH, SH, SK, QN, QN, JA, JA, JA, SK, SK, JA }, 	 //	 671	 1120
{ QN, QN, QN, QN, JA, SH, SK, QN, QN, JA, JA, JA, SK, SK, WN }, 	 //	 672	 1120
{ QN, QN, QN, QN, JA, SH, SK, QN, QN, WN, JA, JA, SK, SK, TN }, 	 //	 673	 1120
{ QN, QN, QN, QN, TN, SH, SK, QN, QN, TN, JA, JA, SK, SK, ST }, 	 //	 674	 1120
{ QN, QN, QN, QN, TN, SH, SK, QN, QN, ST, JA, JA, SK, SK, AC }, 	 //	 675	 1120
{ QN, QN, QN, QN, ST, SH, SK, QN, QN, AC, JA, JA, SK, SK, KN }, 	 //	 676	 1120
{ QN, QN, QN, QN, PF, SH, SK, QN, QN, JA, JA, JA, SK, SK, TN }, 	 //	 677	 1120
{ QN, QN, QN, QN, JA, SH, SK, QN, QN, TN, JA, JA, SK, SK, AC }, 	 //	 678	 1120
{ QN, QN, QN, QN, TN, SH, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 679	 1120
{ QN, QN, QN, QN, AC, SH, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 680	 1120
{ QN, QN, QN, QN, AC, SH, SK, QN, QN, SK, JA, JA, SK, SK, KN }, 	 //	 681	 1120
{ QN, QN, QN, QN, SK, SH, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 682	 1120
{ QN, QN, QN, QN, KN, SH, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 683	 1120
{ QN, QN, QN, QN, KN, SH, SK, QN, QN, KN, JA, JA, SK, SK, CR }, 	 //	 684	 1120
{ QN, QN, QN, QN, KN, SH, SK, QN, QN, AC, JA, JA, SK, SK, LO }, 	 //	 685	 1120
{ QN, QN, QN, QN, KN, SH, ST, QN, SK, KN, JA, JA, SK, JA, SK }, 	 //	 686	 1120
{ QN, KN, QN, QN, QN, SH, SK, QN, QN, QN, JA, QN, SK, SK, SH }, 	 //	 687	 1120
{ QN, QN, QN, QN, AC, SH, KN, QN, SK, SK, JA, AC, SK, JA, KN }, 	 //	 688	 1120
{ QN, QN, QN, QN, KN, SH, KN, SK, SK, KN, JA, AC, JA, JA, SK }, 	 //	 689	 1120
{ SH, QN, QN, QN, QN, JA, QN, QN, SK, QN, JA, SK, SK, JA, QN }, 	 //	 690	 1120
{ SH, QN, QN, QN, QN, JA, QN, QN, SK, QN, JA, SK, SK, JA, SH }, 	 //	 691	 1120
{ SH, QN, QN, QN, QN, JA, QN, QN, SK, PF, JA, SK, SK, JA, JA }, 	 //	 692	 1120
{ SH, QN, QN, QN, QN, JA, QN, QN, SK, KN, JA, SK, SK, JA, AC }, 	 //	 693	 1120
{ SH, QN, QN, SK, SK, JA, QN, QN, QN, KN, JA, SK, SK, KN, KN }, 	 //	 694	 1120
{ SH, QN, QN, QN, QN, JA, SK, QN, QN, SH, JA, JA, SK, SK, JA }, 	 //	 695	 1120
{ SH, QN, QN, QN, AC, JA, SK, QN, QN, KN, JA, JA, SK, SK, QN }, 	 //	 696	 1120
{ SH, QN, QN, QN, KN, JA, SK, QN, QN, QN, JA, JA, SK, SK, PF }, 	 //	 697	 1120
{ SH, QN, QN, QN, QN, JA, SK, QN, QN, KN, JA, JA, SK, SK, AC }, 	 //	 698	 1120
{ SH, QN, QN, SK, SK, JA, SK, QN, QN, QN, JA, JA, SK, KN, QN }, 	 //	 699	 1120
{ SH, KN, QN, QN, SK, JA, SK, QN, QN, QN, JA, QN, SK, SK, QN }, 	 //	 700	 1120
{ JA, QN, QN, QN, QN, JA, QN, QN, SK, QN, JA, SK, SK, JA, QN }, 	 //	 701	 1120
{ JA, QN, QN, QN, QN, JA, QN, QN, SK, QN, JA, SK, SK, JA, SH }, 	 //	 702	 1120
{ JA, QN, QN, QN, AC, JA, SK, QN, QN, KN, JA, JA, SK, SK, QN }, 	 //	 703	 1120
{ JA, QN, QN, QN, KN, JA, SK, QN, QN, QN, JA, JA, SK, SK, PF }, 	 //	 704	 1120
{ JA, QN, QN, QN, QN, JA, SK, QN, QN, KN, JA, JA, SK, SK, AC }, 	 //	 705	 1120
{ JA, QN, QN, SK, SK, JA, SK, QN, QN, QN, JA, JA, SK, KN, QN }, 	 //	 706	 1120
{ JA, KN, QN, QN, QN, JA, SK, QN, QN, QN, JA, QN, SK, SK, SH }, 	 //	 707	 1120
{ JA, KN, QN, SK, SK, JA, SK, QN, QN, QN, JA, QN, SK, KN, QN }, 	 //	 708	 1120
{ JA, QN, QN, QN, QN, JA, QN, QN, SK, QN, WN, SK, SK, JA, QN }, 	 //	 709	 1120
{ JA, QN, QN, QN, QN, JA, QN, QN, SK, QN, WN, SK, SK, JA, SH }, 	 //	 710	 1120
{ JA, QN, QN, QN, QN, JA, QN, QN, SK, PF, WN, SK, SK, JA, JA }, 	 //	 711	 1120
{ JA, QN, QN, QN, KN, JA, SK, QN, QN, QN, WN, JA, SK, SK, PF }, 	 //	 712	 1120
{ JA, QN, QN, QN, QN, JA, SK, QN, QN, PF, WN, JA, SK, SK, JA }, 	 //	 713	 1120
{ JA, QN, QN, SK, SK, JA, SK, QN, QN, QN, WN, JA, SK, KN, QN }, 	 //	 714	 1120
{ JA, KN, QN, QN, SK, JA, SK, QN, QN, QN, WN, QN, SK, SK, QN }, 	 //	 715	 1120
{ JA, KN, QN, QN, QN, JA, SK, QN, QN, QN, WN, QN, SK, SK, SH }, 	 //	 716	 1120
{ JA, QN, QN, QN, QN, WN, QN, QN, SK, QN, TN, SK, SK, JA, QN }, 	 //	 717	 1120
{ JA, QN, QN, QN, QN, WN, QN, QN, SK, SH, TN, SK, SK, JA, JA }, 	 //	 718	 1120
{ JA, QN, QN, QN, QN, WN, QN, QN, SK, PF, TN, SK, SK, JA, JA }, 	 //	 719	 1120
{ JA, QN, QN, QN, QN, WN, QN, QN, SK, KN, TN, SK, SK, JA, AC }, 	 //	 720	 1120
{ JA, QN, QN, QN, KN, WN, SK, QN, QN, QN, TN, JA, SK, SK, PF }, 	 //	 721	 1120
{ JA, QN, QN, SK, SK, WN, SK, QN, QN, QN, TN, JA, SK, KN, QN }, 	 //	 722	 1120
{ JA, KN, QN, QN, SK, WN, SK, QN, QN, QN, TN, QN, SK, SK, QN }, 	 //	 723	 1120
{ JA, KN, QN, QN, QN, WN, SK, QN, QN, QN, TN, QN, SK, SK, SH }, 	 //	 724	 1120
{ WN, QN, QN, QN, QN, TN, QN, QN, SK, QN, TN, SK, SK, JA, QN }, 	 //	 725	 1120
{ WN, QN, QN, QN, KN, TN, SK, QN, QN, SK, TN, JA, SK, SK, QN }, 	 //	 726	 1120
{ WN, QN, QN, QN, QN, TN, SK, QN, QN, PF, TN, JA, SK, SK, JA }, 	 //	 727	 1120
{ WN, QN, QN, QN, QN, TN, SK, QN, QN, KN, TN, JA, SK, SK, AC }, 	 //	 728	 1120
{ WN, QN, QN, SK, SK, TN, SK, QN, QN, QN, TN, JA, SK, KN, QN }, 	 //	 729	 1120
{ WN, KN, QN, SK, SK, TN, KN, QN, QN, QN, TN, SK, SK, KN, QN }, 	 //	 730	 1120
{ WN, KN, QN, QN, QN, TN, SK, QN, QN, QN, TN, QN, SK, SK, SH }, 	 //	 731	 1120
{ WN, KN, QN, SK, SK, TN, SK, QN, QN, QN, TN, QN, SK, KN, QN }, 	 //	 732	 1120
{ TN, QN, QN, QN, QN, TN, QN, QN, SK, SH, TN, SK, SK, JA, JA }, 	 //	 733	 1120
{ TN, QN, QN, QN, QN, TN, QN, QN, SK, PF, TN, SK, SK, JA, JA }, 	 //	 734	 1120
{ TN, QN, QN, QN, QN, TN, SK, QN, QN, SH, TN, JA, SK, SK, JA }, 	 //	 735	 1120
{ TN, QN, QN, QN, KN, TN, SK, QN, QN, QN, TN, JA, SK, SK, PF }, 	 //	 736	 1120
{ TN, QN, QN, QN, QN, TN, SK, QN, QN, KN, TN, JA, SK, SK, AC }, 	 //	 737	 1120
{ TN, KN, QN, SK, SK, TN, SK, QN, QN, QN, TN, QN, SK, KN, QN }, 	 //	 738	 1120
{ TN, QN, QN, QN, QN, TN, QN, QN, SK, QN, ST, SK, SK, JA, QN }, 	 //	 739	 1120
{ TN, QN, QN, QN, QN, TN, QN, QN, SK, SH, ST, SK, SK, JA, JA }, 	 //	 740	 1120
{ TN, QN, QN, SK, SK, TN, QN, QN, QN, KN, ST, SK, SK, KN, KN }, 	 //	 741	 1120
{ TN, QN, QN, QN, KN, TN, SK, QN, QN, QN, ST, JA, SK, SK, PF }, 	 //	 742	 1120
{ TN, QN, QN, QN, CR, TN, SK, QN, QN, QN, ST, JA, SK, SK, KN }, 	 //	 743	 1120
{ TN, QN, QN, QN, QN, TN, SK, QN, QN, KN, ST, JA, SK, SK, AC }, 	 //	 744	 1120
{ TN, KN, QN, QN, QN, TN, SK, QN, QN, QN, ST, QN, SK, SK, SH }, 	 //	 745	 1120
{ TN, KN, QN, SK, SK, TN, SK, QN, QN, QN, ST, QN, SK, KN, QN }, 	 //	 746	 1120
{ TN, QN, QN, QN, QN, ST, QN, QN, SK, QN, AC, SK, SK, JA, QN }, 	 //	 747	 1120
{ TN, QN, QN, QN, QN, ST, QN, QN, SK, QN, AC, SK, SK, JA, SH }, 	 //	 748	 1120
{ TN, QN, QN, QN, QN, ST, QN, QN, SK, PF, AC, SK, SK, JA, JA }, 	 //	 749	 1120
{ TN, QN, QN, QN, QN, ST, QN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 750	 1120
{ TN, QN, QN, QN, KN, ST, SK, QN, QN, SK, AC, JA, SK, SK, QN }, 	 //	 751	 1120
{ TN, QN, QN, QN, QN, ST, SK, QN, QN, SH, AC, JA, SK, SK, JA }, 	 //	 752	 1120
{ TN, QN, QN, QN, CR, ST, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 753	 1120
{ TN, QN, QN, SK, SK, ST, SK, QN, QN, QN, AC, JA, SK, KN, QN }, 	 //	 754	 1120
{ TN, KN, QN, SK, SK, ST, KN, QN, QN, QN, AC, SK, SK, KN, QN }, 	 //	 755	 1120
{ TN, KN, QN, QN, QN, ST, SK, QN, QN, QN, AC, QN, SK, SK, SH }, 	 //	 756	 1120
{ TN, KN, QN, SK, SK, ST, SK, QN, QN, QN, AC, QN, SK, KN, QN }, 	 //	 757	 1120
{ ST, QN, QN, QN, QN, AC, QN, QN, SK, SH, KN, SK, SK, JA, JA }, 	 //	 758	 1120
{ ST, QN, QN, QN, AC, AC, SK, QN, QN, KN, KN, JA, SK, SK, QN }, 	 //	 759	 1120
{ ST, QN, QN, QN, KN, AC, SK, QN, QN, QN, KN, JA, SK, SK, PF }, 	 //	 760	 1120
{ ST, QN, QN, QN, QN, AC, SK, QN, QN, PF, KN, JA, SK, SK, JA }, 	 //	 761	 1120
{ ST, QN, QN, QN, QN, AC, SK, QN, QN, KN, KN, JA, SK, SK, AC }, 	 //	 762	 1120
{ ST, KN, QN, QN, SK, AC, SK, QN, QN, QN, KN, QN, SK, SK, QN }, 	 //	 763	 1120
{ ST, KN, QN, QN, QN, AC, SK, QN, QN, QN, KN, QN, SK, SK, SH }, 	 //	 764	 1120
{ AC, QN, QN, QN, KN, KN, QN, QN, SK, SK, QN, QN, SK, JA, QN }, 	 //	 765	 1120
{ AC, QN, QN, QN, AC, KN, QN, QN, SK, SK, QN, QN, SK, JA, KN }, 	 //	 766	 1120
{ AC, QN, QN, QN, AC, KN, QN, QN, SK, LO, QN, SK, SK, JA, AC }, 	 //	 767	 1120
{ AC, QN, QN, QN, KN, KN, QN, QN, SK, KN, QN, SK, SK, JA, KN }, 	 //	 768	 1120
{ AC, QN, QN, QN, SH, KN, QN, QN, SK, JA, QN, SK, SK, JA, JA }, 	 //	 769	 1120
{ AC, QN, QN, QN, JA, KN, QN, QN, SK, JA, QN, SK, SK, JA, WN }, 	 //	 770	 1120
{ AC, QN, QN, QN, JA, KN, QN, QN, SK, WN, QN, SK, SK, JA, TN }, 	 //	 771	 1120
{ AC, QN, QN, QN, WN, KN, QN, QN, SK, TN, QN, SK, SK, JA, TN }, 	 //	 772	 1120
{ AC, QN, QN, QN, TN, KN, QN, QN, SK, TN, QN, SK, SK, JA, TN }, 	 //	 773	 1120
{ AC, QN, QN, QN, TN, KN, QN, QN, SK, TN, QN, SK, SK, JA, ST }, 	 //	 774	 1120
{ AC, QN, QN, QN, ST, KN, QN, QN, SK, AC, QN, SK, SK, JA, KN }, 	 //	 775	 1120
{ AC, QN, QN, QN, TN, KN, QN, QN, SK, AC, QN, SK, SK, JA, AC }, 	 //	 776	 1120
{ AC, QN, QN, QN, KN, KN, QN, QN, SK, KN, QN, SK, SK, JA, KN }, 	 //	 777	 1120
{ AC, QN, QN, QN, CR, KN, QN, QN, SK, QN, QN, SK, SK, JA, KN }, 	 //	 778	 1120
{ AC, QN, QN, QN, KN, KN, QN, SK, SK, KN, QN, SK, JA, JA, SK }, 	 //	 779	 1120
{ AC, QN, QN, QN, AC, KN, QN, SK, SK, AC, QN, SK, JA, JA, SK }, 	 //	 780	 1120
{ AC, QN, QN, QN, QN, KN, SK, QN, QN, SH, QN, JA, SK, SK, JA }, 	 //	 781	 1120
{ AC, QN, QN, QN, AC, KN, SK, QN, QN, KN, QN, JA, SK, SK, QN }, 	 //	 782	 1120
{ AC, QN, QN, QN, QN, KN, SK, QN, QN, PF, QN, JA, SK, SK, JA }, 	 //	 783	 1120
{ AC, QN, QN, QN, CR, KN, SK, QN, QN, QN, QN, JA, SK, SK, KN }, 	 //	 784	 1120
{ AC, QN, QN, QN, QN, KN, SK, QN, QN, KN, QN, JA, SK, SK, AC }, 	 //	 785	 1120
{ AC, KN, QN, QN, SK, KN, SK, QN, QN, QN, QN, QN, SK, SK, QN }, 	 //	 786	 1120
{ AC, KN, QN, SK, SK, KN, SK, QN, QN, QN, QN, QN, SK, KN, QN }, 	 //	 787	 1120
{ KN, QN, QN, QN, AC, QN, QN, QN, SK, LO, PF, SK, SK, JA, AC }, 	 //	 788	 1120
{ KN, QN, QN, QN, LO, QN, QN, QN, SK, AC, PF, SK, SK, JA, AC }, 	 //	 789	 1120
{ KN, QN, QN, QN, AC, QN, QN, QN, SK, AC, PF, SK, SK, JA, AC }, 	 //	 790	 1120
{ KN, QN, QN, QN, AC, QN, QN, QN, SK, AC, PF, SK, SK, JA, CR }, 	 //	 791	 1120
{ KN, QN, QN, QN, KN, QN, QN, QN, SK, KN, PF, SK, SK, JA, KN }, 	 //	 792	 1120
{ KN, QN, QN, QN, SH, QN, QN, QN, SK, JA, PF, SK, SK, JA, JA }, 	 //	 793	 1120
{ KN, QN, QN, QN, JA, QN, QN, QN, SK, WN, PF, SK, SK, JA, TN }, 	 //	 794	 1120
{ KN, QN, QN, QN, TN, QN, QN, QN, SK, TN, PF, SK, SK, JA, TN }, 	 //	 795	 1120
{ KN, QN, QN, QN, TN, QN, QN, QN, SK, ST, PF, SK, SK, JA, AC }, 	 //	 796	 1120
{ KN, QN, QN, QN, AC, QN, QN, QN, SK, KN, PF, SK, SK, JA, QN }, 	 //	 797	 1120
{ KN, QN, QN, QN, PF, QN, QN, QN, SK, JA, PF, SK, SK, JA, TN }, 	 //	 798	 1120
{ KN, QN, QN, QN, JA, QN, QN, QN, SK, TN, PF, SK, SK, JA, AC }, 	 //	 799	 1120
{ KN, QN, QN, QN, TN, QN, QN, QN, SK, AC, PF, SK, SK, JA, AC }, 	 //	 800	 1120
{ KN, QN, QN, QN, KN, QN, QN, QN, SK, KN, PF, SK, SK, JA, CR }, 	 //	 801	 1120
{ KN, QN, QN, QN, CR, QN, QN, QN, SK, QN, PF, SK, SK, JA, KN }, 	 //	 802	 1120
{ KN, QN, QN, QN, QN, QN, SK, QN, QN, SH, PF, JA, SK, SK, JA }, 	 //	 803	 1120
{ KN, QN, QN, QN, AC, QN, SK, QN, QN, KN, PF, JA, SK, SK, QN }, 	 //	 804	 1120
{ KN, QN, QN, QN, CR, QN, SK, QN, QN, QN, PF, JA, SK, SK, KN }, 	 //	 805	 1120
{ KN, QN, QN, SK, SK, QN, SK, QN, QN, QN, PF, JA, SK, KN, QN }, 	 //	 806	 1120
{ QN, QN, QN, QN, KN, PF, QN, QN, SK, KN, JA, QN, SK, JA, SK }, 	 //	 807	 1120
{ QN, QN, QN, QN, AC, PF, QN, QN, SK, AC, JA, QN, SK, JA, SK }, 	 //	 808	 1120
{ QN, QN, QN, QN, AC, PF, QN, QN, SK, SK, JA, QN, SK, JA, KN }, 	 //	 809	 1120
{ QN, QN, QN, QN, KN, PF, QN, SK, SK, KN, JA, QN, JA, JA, SK }, 	 //	 810	 1120
{ QN, QN, QN, QN, LO, PF, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 811	 1120
{ QN, QN, QN, QN, AC, PF, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 812	 1120
{ QN, QN, QN, QN, JA, PF, QN, QN, SK, JA, JA, SK, SK, JA, JA }, 	 //	 813	 1120
{ QN, QN, QN, QN, WN, PF, QN, QN, SK, TN, JA, SK, SK, JA, TN }, 	 //	 814	 1120
{ QN, QN, QN, QN, TN, PF, QN, QN, SK, TN, JA, SK, SK, JA, TN }, 	 //	 815	 1120
{ QN, QN, QN, QN, TN, PF, QN, QN, SK, TN, JA, SK, SK, JA, ST }, 	 //	 816	 1120
{ QN, QN, QN, QN, PF, PF, QN, QN, SK, JA, JA, SK, SK, JA, TN }, 	 //	 817	 1120
{ QN, QN, QN, QN, JA, PF, QN, QN, SK, TN, JA, SK, SK, JA, AC }, 	 //	 818	 1120
{ QN, QN, QN, QN, AC, PF, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 819	 1120
{ QN, QN, QN, QN, KN, PF, QN, QN, SK, KN, JA, SK, SK, JA, KN }, 	 //	 820	 1120
{ QN, QN, QN, QN, KN, PF, QN, QN, SK, KN, JA, SK, SK, JA, CR }, 	 //	 821	 1120
{ QN, QN, QN, QN, CR, PF, QN, QN, SK, QN, JA, SK, SK, JA, KN }, 	 //	 822	 1120
{ QN, QN, QN, QN, KN, PF, QN, QN, SK, AC, JA, SK, SK, JA, LO }, 	 //	 823	 1120
{ QN, QN, QN, QN, AC, PF, QN, SK, SK, AC, JA, SK, JA, JA, SK }, 	 //	 824	 1120
{ QN, QN, QN, QN, SK, PF, QN, SK, SK, KN, JA, SK, JA, JA, KN }, 	 //	 825	 1120
{ QN, QN, QN, QN, AC, PF, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 826	 1120
{ QN, QN, QN, QN, CR, PF, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 827	 1120
{ QN, QN, QN, QN, KN, PF, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 828	 1120
{ QN, QN, QN, QN, SH, PF, SK, QN, QN, JA, JA, JA, SK, SK, JA }, 	 //	 829	 1120
{ QN, QN, QN, QN, JA, PF, SK, QN, QN, JA, JA, JA, SK, SK, JA }, 	 //	 830	 1120
{ QN, QN, QN, QN, JA, PF, SK, QN, QN, JA, JA, JA, SK, SK, WN }, 	 //	 831	 1120
{ QN, QN, QN, QN, JA, PF, SK, QN, QN, WN, JA, JA, SK, SK, TN }, 	 //	 832	 1120
{ QN, QN, QN, QN, TN, PF, SK, QN, QN, TN, JA, JA, SK, SK, TN }, 	 //	 833	 1120
{ QN, QN, QN, QN, TN, PF, SK, QN, QN, ST, JA, JA, SK, SK, AC }, 	 //	 834	 1120
{ QN, QN, QN, QN, JA, PF, SK, QN, QN, TN, JA, JA, SK, SK, AC }, 	 //	 835	 1120
{ QN, QN, QN, QN, AC, PF, SK, QN, QN, SK, JA, JA, SK, SK, KN }, 	 //	 836	 1120
{ QN, QN, QN, QN, KN, PF, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 837	 1120
{ QN, QN, QN, QN, KN, PF, SK, QN, QN, KN, JA, JA, SK, SK, CR }, 	 //	 838	 1120
{ QN, QN, QN, QN, KN, PF, SK, QN, QN, AC, JA, JA, SK, SK, LO }, 	 //	 839	 1120
{ QN, QN, QN, QN, KN, PF, ST, QN, SK, KN, JA, JA, SK, JA, SK }, 	 //	 840	 1120
{ QN, QN, QN, QN, KN, PF, ST, QN, SK, SK, JA, JA, SK, JA, QN }, 	 //	 841	 1120
{ QN, QN, QN, QN, AC, PF, ST, QN, SK, SK, JA, JA, SK, JA, KN }, 	 //	 842	 1120
{ QN, KN, QN, SK, SK, PF, SK, QN, QN, QN, JA, QN, SK, KN, QN }, 	 //	 843	 1120
{ QN, QN, QN, QN, KN, PF, KN, QN, SK, SK, JA, AC, SK, JA, QN }, 	 //	 844	 1120
{ QN, QN, QN, QN, AC, PF, KN, QN, SK, SK, JA, AC, SK, JA, KN }, 	 //	 845	 1120
{ QN, QN, QN, QN, SK, PF, KN, SK, SK, KN, JA, AC, JA, JA, KN }, 	 //	 846	 1120
{ PF, QN, QN, QN, QN, JA, QN, QN, SK, QN, TN, SK, SK, JA, QN }, 	 //	 847	 1120
{ PF, QN, QN, QN, QN, JA, QN, QN, SK, QN, TN, SK, SK, JA, SH }, 	 //	 848	 1120
{ PF, QN, QN, QN, QN, JA, QN, QN, SK, PF, TN, SK, SK, JA, JA }, 	 //	 849	 1120
{ PF, QN, QN, QN, KN, JA, SK, QN, QN, SK, TN, JA, SK, SK, QN }, 	 //	 850	 1120
{ PF, QN, QN, QN, KN, JA, SK, QN, QN, QN, TN, JA, SK, SK, PF }, 	 //	 851	 1120
{ PF, QN, QN, QN, CR, JA, SK, QN, QN, QN, TN, JA, SK, SK, KN }, 	 //	 852	 1120
{ PF, KN, QN, QN, QN, JA, SK, QN, QN, QN, TN, QN, SK, SK, SH }, 	 //	 853	 1120
{ JA, QN, QN, QN, QN, TN, QN, QN, SK, PF, AC, SK, SK, JA, JA }, 	 //	 854	 1120
{ JA, QN, QN, QN, QN, TN, QN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 855	 1120
{ JA, QN, QN, QN, QN, TN, SK, QN, QN, SH, AC, JA, SK, SK, JA }, 	 //	 856	 1120
{ JA, QN, QN, QN, CR, TN, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 857	 1120
{ JA, QN, QN, QN, QN, TN, SK, QN, QN, KN, AC, JA, SK, SK, AC }, 	 //	 858	 1120
{ JA, KN, QN, SK, SK, TN, SK, QN, QN, QN, AC, QN, SK, KN, QN }, 	 //	 859	 1120
{ TN, QN, QN, QN, QN, AC, QN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 860	 1120
{ TN, QN, QN, SK, SK, AC, QN, QN, QN, KN, AC, SK, SK, KN, KN }, 	 //	 861	 1120
{ TN, QN, QN, QN, QN, AC, SK, QN, QN, PF, AC, JA, SK, SK, JA }, 	 //	 862	 1120
{ TN, QN, QN, QN, CR, AC, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 863	 1120
{ TN, QN, QN, QN, QN, AC, SK, QN, QN, KN, AC, JA, SK, SK, AC }, 	 //	 864	 1120
{ TN, KN, QN, SK, SK, AC, KN, QN, QN, QN, AC, SK, SK, KN, QN }, 	 //	 865	 1120
{ TN, KN, QN, SK, SK, AC, SK, QN, QN, QN, AC, QN, SK, KN, QN }, 	 //	 866	 1120
{ AC, QN, QN, QN, QN, AC, QN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 867	 1120
{ AC, QN, QN, SK, SK, AC, QN, QN, QN, KN, AC, SK, SK, KN, KN }, 	 //	 868	 1120
{ AC, QN, QN, QN, CR, AC, SK, QN, QN, QN, AC, JA, SK, SK, KN }, 	 //	 869	 1120
{ AC, KN, QN, QN, SK, AC, SK, QN, QN, QN, AC, QN, SK, SK, QN }, 	 //	 870	 1120
{ AC, KN, QN, QN, QN, AC, SK, QN, QN, QN, AC, QN, SK, SK, SH }, 	 //	 871	 1120
{ AC, KN, QN, SK, SK, AC, SK, QN, QN, QN, AC, QN, SK, KN, QN }, 	 //	 872	 1120
{ AC, QN, ST, KN, KN, AC, QN, AC, KN, KN, SK, SK, KN, SK, SK }, 	 //	 873	 1120
{ AC, QN, KN, KN, KN, AC, QN, QN, KN, KN, SK, SK, PF, SK, SK }, 	 //	 874	 1120
{ AC, QN, KN, KN, KN, AC, QN, QN, SK, KN, SK, SK, PF, QN, SK }, 	 //	 875	 1120
{ AC, QN, QN, QN, KN, AC, QN, PF, QN, KN, SK, SK, KN, SK, SK }, 	 //	 876	 1120
{ AC, QN, QN, KN, KN, AC, QN, PF, KN, KN, SK, SK, KN, SK, SK }, 	 //	 877	 1120
{ AC, QN, PF, SK, SK, AC, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 878	 1120
{ AC, QN, KN, KN, KN, AC, QN, KN, SK, KN, SK, SK, KN, QN, SK }, 	 //	 879	 1120
{ AC, QN, KN, KN, KN, AC, QN, KN, SK, SK, SK, SK, KN, QN, QN }, 	 //	 880	 1120
{ AC, QN, KN, SK, SK, AC, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 881	 1120
{ AC, QN, KN, KN, KN, AC, QN, KN, SK, SK, SK, SK, SH, QN, QN }, 	 //	 882	 1120
{ AC, QN, KN, KN, KN, AC, QN, SH, KN, KN, SK, SK, AC, SK, SK }, 	 //	 883	 1120
{ AC, QN, KN, KN, KN, AC, QN, SH, SK, KN, SK, SK, AC, QN, SK }, 	 //	 884	 1120
{ AC, QN, KN, KN, KN, AC, QN, SH, SK, SK, SK, SK, AC, QN, QN }, 	 //	 885	 1120
{ AC, QN, PF, SK, SK, AC, QN, QN, QN, KN, SK, SK, QN, KN, KN }, 	 //	 886	 1120
{ AC, QN, QN, QN, KN, AC, QN, SK, QN, KN, SK, SK, JA, SK, SK }, 	 //	 887	 1120
{ AC, QN, QN, QN, AC, AC, QN, SK, QN, AC, SK, SK, JA, SK, SK }, 	 //	 888	 1120
{ AC, QN, QN, QN, QN, AC, QN, SK, SK, QN, SK, SK, JA, JA, SH }, 	 //	 889	 1120
{ AC, QN, QN, QN, QN, AC, QN, SK, SK, KN, SK, SK, JA, JA, AC }, 	 //	 890	 1120
{ AC, QN, QN, SK, SK, AC, QN, SK, QN, QN, SK, SK, JA, KN, QN }, 	 //	 891	 1120
{ AC, QN, AC, KN, KN, AC, QN, WN, KN, KN, SK, SK, KN, SK, SK }, 	 //	 892	 1120
{ AC, QN, WN, SK, SK, AC, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 893	 1120
{ AC, QN, KN, KN, KN, AC, QN, KN, SK, KN, SK, SK, KN, QN, SK }, 	 //	 894	 1120
{ AC, QN, KN, SK, SK, AC, QN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 895	 1120
{ AC, QN, KN, KN, KN, AC, QN, KN, SK, SK, SK, SK, PF, QN, QN }, 	 //	 896	 1120
{ AC, QN, QN, KN, KN, AC, QN, AC, KN, KN, SK, SK, KN, SK, SK }, 	 //	 897	 1120
{ AC, QN, QN, SK, SK, AC, QN, AC, QN, QN, SK, SK, KN, KN, QN }, 	 //	 898	 1120
{ AC, QN, KN, KN, KN, AC, SK, WN, SK, KN, SK, JA, TN, QN, SK }, 	 //	 899	 1120
{ AC, QN, KN, KN, KN, AC, SK, QN, SK, SK, SK, JA, PF, QN, QN }, 	 //	 900	 1120
{ AC, QN, QN, SK, SK, AC, SK, PF, QN, KN, SK, JA, KN, KN, KN }, 	 //	 901	 1120
{ AC, QN, KN, KN, KN, AC, SK, KN, SK, KN, SK, JA, KN, QN, SK }, 	 //	 902	 1120
{ AC, QN, KN, SK, SK, AC, SK, KN, QN, KN, SK, JA, KN, KN, KN }, 	 //	 903	 1120
{ AC, QN, KN, KN, KN, AC, SK, SH, KN, KN, SK, JA, AC, SK, SK }, 	 //	 904	 1120
{ AC, QN, KN, KN, KN, AC, SK, SH, SK, KN, SK, JA, AC, QN, SK }, 	 //	 905	 1120
{ AC, QN, KN, KN, KN, AC, SK, SH, SK, SK, SK, JA, AC, QN, QN }, 	 //	 906	 1120
{ AC, QN, QN, WN, SK, AC, SK, QN, QN, QN, SK, JA, SK, QN, QN }, 	 //	 907	 1120
{ AC, QN, QN, WN, QN, AC, SK, QN, QN, QN, SK, JA, SK, QN, QN }, 	 //	 908	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, SH, SK, JA, SK, QN, JA }, 	 //	 909	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, PF, SK, JA, SK, QN, JA }, 	 //	 910	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, QN, KN, SK, JA, SK, QN, AC }, 	 //	 911	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, ST, SH, SK, JA, SK, JA, JA }, 	 //	 912	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, ST, KN, SK, JA, SK, JA, AC }, 	 //	 913	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, KN, QN, SK, JA, SK, AC, QN }, 	 //	 914	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, KN, QN, SK, JA, SK, AC, SH }, 	 //	 915	 1120
{ AC, QN, QN, QN, QN, AC, SK, QN, KN, KN, SK, JA, SK, AC, AC }, 	 //	 916	 1120
{ AC, QN, QN, QN, SK, AC, SK, SK, QN, QN, SK, JA, JA, QN, QN }, 	 //	 917	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, QN, QN, SK, JA, JA, QN, SH }, 	 //	 918	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, QN, SH, SK, JA, JA, QN, JA }, 	 //	 919	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, QN, PF, SK, JA, JA, QN, JA }, 	 //	 920	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, QN, KN, SK, JA, JA, QN, AC }, 	 //	 921	 1120
{ AC, QN, QN, QN, SK, AC, SK, SK, QN, QN, SK, JA, JA, SK, QN }, 	 //	 922	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, QN, QN, SK, JA, JA, SK, SH }, 	 //	 923	 1120
{ AC, QN, QN, QN, QN, AC, SK, SK, KN, QN, SK, JA, JA, AC, QN }, 	 //	 924	 1120
{ AC, QN, AC, SK, SK, AC, SK, WN, QN, KN, SK, JA, KN, KN, KN }, 	 //	 925	 1120
{ AC, QN, KN, KN, KN, AC, SK, KN, SK, KN, SK, JA, KN, QN, SK }, 	 //	 926	 1120
{ AC, QN, KN, KN, KN, AC, SK, KN, SK, SK, SK, JA, KN, QN, QN }, 	 //	 927	 1120
{ AC, QN, KN, KN, KN, AC, SK, KN, SK, SK, SK, JA, PF, QN, QN }, 	 //	 928	 1120
{ AC, QN, KN, KN, KN, AC, SK, PF, SK, KN, SK, JA, QN, QN, SK }, 	 //	 929	 1120
{ AC, QN, QN, KN, KN, AC, SK, AC, KN, KN, SK, JA, KN, SK, SK }, 	 //	 930	 1120
{ AC, QN, QN, SK, SK, AC, SK, AC, QN, KN, SK, JA, KN, KN, KN }, 	 //	 931	 1120
{ AC, KN, KN, KN, AC, AC, KN, WN, SK, SK, SK, SK, TN, QN, KN }, 	 //	 932	 1120
{ AC, KN, KN, KN, AC, AC, KN, QN, SK, AC, SK, SK, PF, QN, SK }, 	 //	 933	 1120
{ AC, KN, KN, KN, AC, AC, KN, QN, SK, SK, SK, SK, PF, QN, KN }, 	 //	 934	 1120
{ AC, KN, QN, KN, AC, AC, KN, PF, KN, AC, SK, SK, KN, SK, SK }, 	 //	 935	 1120
{ AC, KN, PF, SK, SK, AC, KN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 936	 1120
{ AC, KN, KN, KN, SK, AC, KN, KN, SK, QN, SK, SK, KN, QN, QN }, 	 //	 937	 1120
{ AC, KN, KN, KN, AC, AC, KN, KN, SK, AC, SK, SK, KN, QN, SK }, 	 //	 938	 1120
{ AC, KN, KN, KN, AC, AC, KN, KN, SK, SK, SK, SK, KN, QN, KN }, 	 //	 939	 1120
{ AC, KN, KN, SK, SK, AC, KN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 940	 1120
{ AC, KN, KN, KN, SK, AC, KN, KN, SK, QN, SK, SK, SH, QN, QN }, 	 //	 941	 1120
{ AC, KN, KN, KN, AC, AC, KN, KN, SK, SK, SK, SK, SH, QN, KN }, 	 //	 942	 1120
{ AC, KN, KN, KN, SK, AC, KN, SH, SK, QN, SK, SK, AC, QN, QN }, 	 //	 943	 1120
{ AC, KN, KN, KN, SK, AC, KN, SH, SK, KN, SK, SK, AC, QN, KN }, 	 //	 944	 1120
{ AC, KN, AC, KN, AC, AC, KN, WN, KN, AC, SK, SK, KN, SK, SK }, 	 //	 945	 1120
{ AC, KN, AC, SK, SK, AC, KN, WN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 946	 1120
{ AC, KN, WN, SK, SK, AC, KN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 947	 1120
{ AC, KN, KN, KN, SK, AC, KN, KN, SK, QN, SK, SK, KN, QN, QN }, 	 //	 948	 1120
{ AC, KN, KN, KN, AC, AC, KN, KN, SK, SK, SK, SK, KN, QN, KN }, 	 //	 949	 1120
{ AC, KN, KN, SK, SK, AC, KN, KN, QN, KN, SK, SK, KN, KN, KN }, 	 //	 950	 1120
{ AC, KN, KN, KN, SK, AC, KN, KN, SK, QN, SK, SK, PF, QN, QN }, 	 //	 951	 1120
{ AC, KN, KN, KN, AC, AC, KN, KN, SK, SK, SK, SK, PF, QN, KN }, 	 //	 952	 1120
{ AC, KN, KN, KN, SK, AC, KN, KN, SK, KN, SK, SK, PF, QN, KN }, 	 //	 953	 1120
{ AC, KN, KN, KN, AC, AC, KN, PF, SK, AC, SK, SK, QN, QN, SK }, 	 //	 954	 1120
{ AC, KN, KN, KN, SK, AC, KN, PF, SK, KN, SK, SK, QN, QN, KN }, 	 //	 955	 1120
{ AC, KN, KN, KN, AC, AC, SK, WN, KN, AC, SK, QN, TN, SK, SK }, 	 //	 956	 1120
{ AC, KN, KN, KN, AC, AC, SK, WN, SK, AC, SK, QN, TN, QN, SK }, 	 //	 957	 1120
{ AC, KN, AC, KN, KN, AC, SK, KN, KN, KN, SK, QN, QN, SK, SK }, 	 //	 958	 1120
{ AC, KN, AC, KN, KN, AC, SK, KN, SK, SK, SK, QN, QN, QN, QN }, 	 //	 959	 1120
{ AC, KN, KN, KN, AC, AC, SK, QN, KN, AC, SK, QN, PF, SK, SK }, 	 //	 960	 1120
{ AC, KN, KN, KN, SK, AC, SK, QN, SK, QN, SK, QN, PF, QN, QN }, 	 //	 961	 1120
{ AC, KN, KN, KN, SK, AC, SK, QN, SK, KN, SK, QN, PF, QN, KN }, 	 //	 962	 1120
{ AC, KN, QN, KN, KN, AC, SK, PF, KN, KN, SK, QN, KN, SK, SK }, 	 //	 963	 1120
{ AC, KN, QN, SK, SK, AC, SK, PF, QN, KN, SK, QN, KN, KN, KN }, 	 //	 964	 1120
{ AC, KN, PF, SK, SK, AC, SK, KN, QN, KN, SK, QN, KN, KN, KN }, 	 //	 965	 1120
{ AC, KN, KN, KN, AC, AC, SK, KN, KN, AC, SK, QN, KN, SK, SK }, 	 //	 966	 1120
{ AC, KN, KN, KN, AC, AC, SK, KN, KN, AC, SK, QN, SH, SK, SK }, 	 //	 967	 1120
{ AC, KN, KN, KN, AC, AC, SK, KN, SK, SK, SK, QN, SH, QN, KN }, 	 //	 968	 1120
{ AC, KN, KN, KN, SK, AC, SK, KN, SK, KN, SK, QN, SH, QN, KN }, 	 //	 969	 1120
{ AC, KN, KN, KN, AC, AC, SK, SH, KN, AC, SK, QN, AC, SK, SK }, 	 //	 970	 1120
{ AC, KN, KN, KN, AC, AC, SK, SH, SK, AC, SK, QN, AC, QN, SK }, 	 //	 971	 1120
{ AC, KN, KN, KN, AC, AC, SK, SH, SK, SK, SK, QN, AC, QN, KN }, 	 //	 972	 1120
{ AC, KN, AC, KN, SK, AC, SK, PF, SK, QN, SK, QN, QN, QN, QN }, 	 //	 973	 1120
{ AC, KN, PF, KN, SK, AC, SK, QN, SK, QN, SK, QN, QN, QN, QN }, 	 //	 974	 1120
{ AC, KN, QN, KN, SK, AC, SK, QN, SK, QN, SK, QN, QN, QN, QN }, 	 //	 975	 1120
{ AC, KN, QN, SK, SK, AC, SK, QN, QN, QN, SK, QN, QN, KN, QN }, 	 //	 976	 1120
{ AC, KN, QN, WN, SK, AC, SK, QN, QN, QN, SK, QN, SK, QN, QN }, 	 //	 977	 1120
{ AC, KN, QN, KN, QN, AC, SK, QN, QN, QN, SK, QN, SK, ST, QN }, 	 //	 978	 1120
{ AC, KN, QN, QN, QN, AC, SK, SK, QN, QN, SK, QN, JA, QN, QN }, 	 //	 979	 1120
{ AC, KN, AC, KN, KN, AC, SK, WN, KN, KN, SK, QN, KN, SK, SK }, 	 //	 980	 1120
{ AC, KN, KN, KN, AC, AC, SK, KN, SK, AC, SK, QN, KN, QN, SK }, 	 //	 981	 1120
{ AC, KN, KN, KN, SK, AC, SK, KN, SK, KN, SK, QN, KN, QN, KN }, 	 //	 982	 1120
{ AC, KN, KN, KN, AC, AC, SK, KN, SK, SK, SK, QN, PF, QN, KN }, 	 //	 983	 1120
{ AC, KN, KN, KN, SK, AC, SK, KN, SK, KN, SK, QN, PF, QN, KN }, 	 //	 984	 1120
{ AC, KN, QN, SK, SK, AC, SK, AC, QN, KN, SK, QN, KN, KN, KN }, 	 //	 985	 1120
{ AC, QN, QN, QN, QN, SK, QN, QN, SK, SH, KN, SK, SK, JA, JA }, 	 //	 986	 1120
{ AC, QN, QN, SK, SK, SK, QN, QN, QN, KN, KN, SK, SK, KN, KN }, 	 //	 987	 1120
{ AC, QN, ST, KN, KN, SK, SK, AC, KN, KN, KN, JA, KN, SK, SK }, 	 //	 988	 1120
{ AC, QN, AC, KN, KN, SK, SK, KN, KN, KN, KN, JA, QN, SK, SK }, 	 //	 989	 1120
{ AC, QN, KN, KN, KN, SK, SK, QN, KN, KN, KN, JA, PF, SK, SK }, 	 //	 990	 1120
{ AC, QN, QN, SK, SK, SK, SK, PF, QN, KN, KN, JA, KN, KN, KN }, 	 //	 991	 1120
{ AC, QN, PF, SK, SK, SK, SK, KN, QN, KN, KN, JA, KN, KN, KN }, 	 //	 992	 1120
{ AC, QN, KN, KN, KN, SK, SK, KN, SK, KN, KN, JA, KN, QN, SK }, 	 //	 993	 1120
{ AC, QN, KN, KN, KN, SK, SK, KN, SK, SK, KN, JA, KN, QN, QN }, 	 //	 994	 1120
{ AC, QN, KN, SK, SK, SK, SK, KN, QN, KN, KN, JA, KN, KN, KN }, 	 //	 995	 1120
{ AC, QN, KN, KN, KN, SK, SK, KN, SK, KN, KN, JA, SH, QN, SK }, 	 //	 996	 1120
{ AC, QN, KN, KN, KN, SK, SK, KN, SK, SK, KN, JA, SH, QN, QN }, 	 //	 997	 1120
{ AC, QN, KN, KN, KN, SK, SK, SH, KN, KN, KN, JA, AC, SK, SK }, 	 //	 998	 1120
{ AC, QN, KN, KN, KN, SK, SK, SH, SK, SK, KN, JA, AC, QN, QN }, 	 //	 999	 1120
{ AC, QN, QN, WN, SK, SK, SK, QN, QN, QN, KN, JA, SK, QN, QN }};	 //	 1000	 1120
