unsigned char L5_Outcome_5000[1000][15]={	 //	 0	 5000
{ AC, AC, AC, AC, AC, LO, SH, KN, AC, KN, AC, AC, QN, PF, QN }, 	 //	 1	 5000
{ AC, AC, AC, AC, AC, LO, SH, AC, PF, SK, AC, AC, WN, AC, KN }, 	 //	 2	 5000
{ AC, AC, AC, AC, AC, LO, SH, WN, LO, AC, AC, AC, KN, KN, AC }, 	 //	 3	 5000
{ AC, AC, PF, AC, JA, LO, SH, QN, PF, TN, AC, AC, AC, AC, AC }, 	 //	 4	 5000
{ AC, SH, AC, QN, QN, LO, AC, AC, KN, SH, AC, AC, AC, AC, JA }, 	 //	 5	 5000
{ AC, SH, AC, QN, QN, LO, AC, AC, KN, QN, AC, AC, AC, AC, SH }, 	 //	 6	 5000
{ AC, SH, AC, AC, LO, LO, AC, WN, AC, AC, AC, AC, KN, PF, AC }, 	 //	 7	 5000
{ AC, SH, AC, AC, QN, LO, AC, WN, AC, KN, AC, AC, KN, PF, AC }, 	 //	 8	 5000
{ AC, AC, SH, KN, SK, LO, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 9	 5000
{ AC, AC, AC, WN, KN, LO, AC, AC, AC, KN, AC, AC, WN, KN, CR }, 	 //	 10	 5000
{ AC, AC, AC, AC, TN, LO, AC, AC, LO, TN, AC, LO, AC, KN, TN }, 	 //	 11	 5000
{ AC, AC, AC, AC, AC, LO, LO, KN, PF, AC, AC, KN, QN, AC, AC }, 	 //	 12	 5000
{ AC, AC, AC, AC, AC, LO, LO, KN, LO, AC, AC, KN, QN, KN, AC }, 	 //	 13	 5000
{ AC, AC, AC, AC, AC, LO, LO, KN, AC, AC, AC, KN, WN, AC, SK }, 	 //	 14	 5000
{ AC, LO, KN, KN, KN, LO, KN, KN, KN, SK, AC, KN, KN, SK, QN }, 	 //	 15	 5000
{ AC, LO, KN, LO, QN, LO, KN, KN, KN, KN, AC, KN, KN, KN, AC }, 	 //	 16	 5000
{ AC, KN, KN, KN, AC, LO, KN, KN, KN, AC, AC, KN, KN, KN, CR }, 	 //	 17	 5000
{ AC, TN, SH, PF, AC, LO, WN, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 18	 5000
{ AC, TN, AC, TN, AC, LO, WN, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 19	 5000
{ AC, TN, JA, TN, LO, LO, WN, TN, WN, AC, AC, AC, AC, AC, AC }, 	 //	 20	 5000
{ AC, WN, AC, TN, AC, LO, AC, PF, AC, LO, AC, KN, QN, AC, AC }, 	 //	 21	 5000
{ AC, WN, AC, AC, AC, LO, AC, AC, AC, KN, AC, KN, WN, PF, QN }, 	 //	 22	 5000
{ AC, AC, KN, KN, KN, LO, KN, KN, KN, QN, AC, QN, KN, SK, PF }, 	 //	 23	 5000
{ AC, AC, AC, AC, AC, LO, KN, AC, AC, KN, AC, QN, WN, AC, QN }, 	 //	 24	 5000
{ AC, AC, AC, AC, AC, LO, KN, WN, AC, KN, AC, QN, KN, PF, QN }, 	 //	 25	 5000
{ AC, JA, TN, PF, TN, LO, TN, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 26	 5000
{ AC, JA, PF, AC, JA, LO, TN, QN, PF, TN, AC, AC, AC, AC, AC }, 	 //	 27	 5000
{ AC, JA, PF, PF, TN, LO, TN, QN, AC, AC, AC, AC, AC, AC, AC }, 	 //	 28	 5000
{ AC, TN, AC, TN, JA, LO, AC, AC, WN, JA, AC, AC, AC, AC, WN }, 	 //	 29	 5000
{ AC, TN, TN, AC, SK, LO, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 30	 5000
{ AC, TN, AC, JA, SK, LO, AC, AC, TN, QN, AC, AC, AC, AC, QN }, 	 //	 31	 5000
{ AC, TN, AC, QN, KN, LO, AC, AC, KN, KN, AC, AC, AC, AC, CR }, 	 //	 32	 5000
{ AC, AC, AC, TN, JA, LO, AC, AC, AC, WN, AC, AC, PF, AC, TN }, 	 //	 33	 5000
{ AC, AC, AC, WN, QN, LO, AC, AC, AC, QN, AC, PF, WN, KN, SH }, 	 //	 34	 5000
{ AC, AC, AC, TN, TN, LO, AC, AC, AC, TN, AC, PF, WN, AC, TN }, 	 //	 35	 5000
{ AC, AC, AC, AC, AC, LO, PF, WN, KN, SK, AC, KN, KN, QN, KN }, 	 //	 36	 5000
{ AC, PF, WN, LO, CR, LO, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 37	 5000
{ AC, KN, KN, KN, QN, LO, KN, KN, KN, PF, AC, KN, KN, KN, JA }, 	 //	 38	 5000
{ AC, QN, SH, AC, TN, LO, KN, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 39	 5000
{ AC, KN, AC, AC, QN, LO, AC, PF, AC, KN, AC, SH, QN, AC, AC }, 	 //	 40	 5000
{ LO, AC, JA, AC, TN, AC, SH, ST, PF, ST, AC, AC, AC, AC, AC }, 	 //	 41	 5000
{ LO, AC, TN, TN, JA, AC, SH, AC, WN, TN, AC, AC, AC, AC, AC }, 	 //	 42	 5000
{ LO, AC, TN, AC, TN, AC, SH, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 43	 5000
{ LO, SH, JA, QN, AC, AC, AC, ST, KN, LO, AC, AC, AC, AC, AC }, 	 //	 44	 5000
{ LO, SH, KN, TN, AC, AC, AC, SH, WN, AC, AC, AC, AC, AC, AC }, 	 //	 45	 5000
{ LO, SH, JA, JA, LO, AC, AC, TN, TN, AC, AC, AC, AC, AC, AC }, 	 //	 46	 5000
{ LO, AC, ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC }, 	 //	 47	 5000
{ LO, AC, AC, JA, TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST }, 	 //	 48	 5000
{ LO, AC, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, PF, AC, AC }, 	 //	 49	 5000
{ LO, AC, AC, PF, AC, AC, AC, PF, AC, LO, AC, AC, QN, AC, AC }, 	 //	 50	 5000
{ LO, AC, PF, AC, AC, AC, AC, QN, PF, AC, AC, AC, AC, AC, AC }, 	 //	 51	 5000
{ LO, AC, PF, QN, JA, AC, AC, QN, KN, TN, AC, AC, AC, AC, AC }, 	 //	 52	 5000
{ LO, AC, AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, WN, PF, AC }, 	 //	 53	 5000
{ LO, AC, ST, AC, TN, AC, AC, AC, AC, AC, AC, LO, KN, AC, AC }, 	 //	 54	 5000
{ LO, AC, AC, PF, JA, AC, AC, KN, AC, TN, AC, LO, WN, AC, AC }, 	 //	 55	 5000
{ LO, KN, PF, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, CR }, 	 //	 56	 5000
{ LO, KN, KN, KN, AC, AC, KN, KN, KN, KN, AC, ST, KN, KN, QN }, 	 //	 57	 5000
{ LO, TN, KN, TN, JA, AC, WN, SH, AC, TN, AC, AC, AC, AC, AC }, 	 //	 58	 5000
{ LO, TN, AC, QN, AC, AC, WN, AC, KN, AC, AC, AC, AC, AC, AC }, 	 //	 59	 5000
{ LO, AC, KN, KN, KN, AC, KN, KN, KN, KN, AC, QN, SH, SK, KN }, 	 //	 60	 5000
{ LO, JA, JA, QN, TN, AC, TN, ST, KN, ST, AC, AC, AC, AC, AC }, 	 //	 61	 5000
{ LO, JA, SH, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 62	 5000
{ LO, TN, JA, AC, TN, AC, AC, ST, PF, ST, AC, AC, AC, AC, AC }, 	 //	 63	 5000
{ LO, TN, SH, KN, QN, AC, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 64	 5000
{ LO, TN, TN, WN, SH, AC, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 65	 5000
{ LO, TN, AC, AC, JA, AC, AC, AC, PF, WN, AC, AC, AC, AC, TN }, 	 //	 66	 5000
{ LO, TN, AC, KN, AC, AC, AC, KN, AC, AC, AC, AC, WN, PF, AC }, 	 //	 67	 5000
{ LO, AC, ST, PF, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, CR }, 	 //	 68	 5000
{ LO, AC, ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC }, 	 //	 69	 5000
{ LO, AC, PF, AC, AC, AC, AC, QN, PF, AC, AC, AC, AC, AC, AC }, 	 //	 70	 5000
{ LO, AC, PF, TN, AC, AC, AC, QN, WN, AC, AC, AC, AC, AC, AC }, 	 //	 71	 5000
{ LO, AC, AC, KN, AC, AC, AC, KN, AC, AC, AC, PF, WN, PF, AC }, 	 //	 72	 5000
{ LO, AC, AC, AC, AC, AC, PF, AC, AC, LO, AC, KN, AC, PF, AC }, 	 //	 73	 5000
{ LO, KN, PF, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, CR }, 	 //	 74	 5000
{ LO, KN, KN, KN, SH, AC, KN, KN, KN, JA, AC, KN, KN, KN, JA }, 	 //	 75	 5000
{ LO, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, PF, KN, CR }, 	 //	 76	 5000
{ LO, QN, SH, TN, AC, AC, KN, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 77	 5000
{ LO, KN, ST, TN, AC, AC, AC, AC, AC, AC, AC, SH, KN, AC, AC }, 	 //	 78	 5000
{ LO, KN, ST, TN, ST, AC, AC, AC, AC, AC, AC, SH, KN, AC, KN }, 	 //	 79	 5000
{ LO, KN, SH, AC, TN, AC, AC, AC, AC, ST, AC, SH, AC, AC, AC }, 	 //	 80	 5000
{ LO, KN, AC, WN, QN, AC, AC, PF, AC, KN, AC, SH, QN, KN, AC }, 	 //	 81	 5000
{ AC, AC, AC, AC, AC, AC, SH, PF, KN, AC, AC, AC, QN, QN, SK }, 	 //	 82	 5000
{ AC, SH, AC, PF, LO, AC, AC, WN, AC, AC, AC, AC, KN, AC, AC }, 	 //	 83	 5000
{ AC, SH, QN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC }, 	 //	 84	 5000
{ AC, SH, AC, AC, QN, AC, AC, KN, AC, KN, AC, AC, WN, AC, AC }, 	 //	 85	 5000
{ AC, AC, TN, TN, SH, AC, AC, AC, WN, JA, AC, AC, AC, AC, JA }, 	 //	 86	 5000
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, KN, AC, AC, WN, AC, AC }, 	 //	 87	 5000
{ AC, AC, AC, AC, TN, AC, AC, AC, PF, TN, AC, AC, WN, KN, ST }, 	 //	 88	 5000
{ AC, AC, ST, TN, ST, AC, AC, AC, AC, AC, AC, LO, KN, AC, KN }, 	 //	 89	 5000
{ AC, AC, AC, AC, AC, AC, LO, AC, LO, SK, AC, KN, AC, KN, KN }, 	 //	 90	 5000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, ST, SH, KN, CR }, 	 //	 91	 5000
{ AC, TN, JA, JA, TN, AC, WN, ST, TN, AC, AC, AC, AC, AC, AC }, 	 //	 92	 5000
{ AC, TN, KN, TN, TN, AC, WN, SH, AC, ST, AC, AC, AC, AC, AC }, 	 //	 93	 5000
{ AC, TN, AC, TN, LO, AC, WN, AC, WN, AC, AC, AC, AC, AC, AC }, 	 //	 94	 5000
{ AC, TN, TN, AC, QN, AC, WN, AC, PF, KN, AC, AC, AC, AC, AC }, 	 //	 95	 5000
{ AC, WN, AC, AC, TN, AC, AC, KN, AC, ST, AC, KN, QN, LO, AC }, 	 //	 96	 5000
{ AC, WN, JA, AC, AC, AC, AC, TN, AC, SK, AC, KN, AC, PF, KN }, 	 //	 97	 5000
{ AC, AC, KN, KN, KN, AC, KN, KN, KN, KN, AC, QN, PF, KN, KN }, 	 //	 98	 5000
{ AC, JA, JA, AC, TN, AC, TN, ST, AC, ST, AC, AC, AC, AC, AC }, 	 //	 99	 5000
{ AC, TN, TN, AC, QN, AC, AC, AC, PF, QN, AC, AC, AC, AC, QN }, 	 //	 100	 5000
{ AC, AC, ST, AC, LO, AC, AC, AC, AC, AC, AC, AC, KN, LO, AC }, 	 //	 101	 5000
{ AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, SK }, 	 //	 102	 5000
{ AC, AC, AC, AC, QN, AC, AC, AC, LO, QN, AC, AC, PF, KN, QN }, 	 //	 103	 5000
{ AC, AC, JA, AC, AC, AC, AC, TN, AC, SK, AC, PF, AC, PF, KN }, 	 //	 104	 5000
{ AC, AC, QN, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, AC, AC }, 	 //	 105	 5000
{ AC, PF, KN, LO, KN, AC, KN, KN, KN, SK, AC, KN, KN, KN, QN }, 	 //	 106	 5000
{ AC, PF, KN, QN, SK, AC, KN, KN, KN, KN, AC, KN, KN, AC, KN }, 	 //	 107	 5000
{ AC, PF, KN, KN, KN, AC, KN, KN, KN, SK, AC, KN, KN, WN, QN }, 	 //	 108	 5000
{ AC, KN, PF, KN, KN, AC, KN, KN, KN, KN, AC, SK, KN, KN, KN }, 	 //	 109	 5000
{ AC, QN, AC, QN, AC, AC, KN, AC, KN, AC, AC, AC, AC, AC, AC }, 	 //	 110	 5000
{ AC, QN, KN, PF, CR, AC, KN, KN, KN, QN, AC, AC, KN, KN, KN }, 	 //	 111	 5000
{ AC, KN, JA, WN, AC, AC, AC, ST, AC, SK, AC, SH, AC, KN, KN }, 	 //	 112	 5000
{ AC, KN, ST, PF, ST, AC, AC, AC, AC, AC, AC, SH, KN, AC, KN }, 	 //	 113	 5000
{ AC, SH, SH, TN, LO, AC, AC, AC, WN, AC, ST, AC, AC, AC, AC }, 	 //	 114	 5000
{ AC, AC, AC, AC, JA, AC, AC, AC, KN, JA, ST, AC, AC, QN, JA }, 	 //	 115	 5000
{ AC, AC, ST, KN, AC, AC, AC, AC, AC, AC, ST, LO, KN, PF, SK }, 	 //	 116	 5000
{ AC, AC, KN, AC, AC, AC, AC, SH, AC, AC, ST, LO, AC, PF, AC }, 	 //	 117	 5000
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, JA, ST, LO, PF, AC, JA }, 	 //	 118	 5000
{ AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, ST, LO, AC, LO, AC }, 	 //	 119	 5000
{ AC, AC, AC, AC, AC, AC, AC, KN, PF, LO, ST, LO, WN, AC, AC }, 	 //	 120	 5000
{ AC, AC, AC, AC, AC, AC, LO, KN, KN, SK, ST, KN, QN, QN, KN }, 	 //	 121	 5000
{ AC, AC, AC, AC, AC, AC, LO, AC, AC, SK, ST, KN, WN, LO, KN }, 	 //	 122	 5000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, ST, KN, PF, WN, SK }, 	 //	 123	 5000
{ AC, ST, KN, KN, KN, AC, QN, KN, KN, KN, ST, QN, KN, KN, KN }, 	 //	 124	 5000
{ AC, WN, ST, KN, AC, AC, AC, AC, AC, AC, ST, KN, KN, PF, AC }, 	 //	 125	 5000
{ AC, WN, PF, AC, AC, AC, AC, QN, AC, AC, ST, KN, AC, LO, AC }, 	 //	 126	 5000
{ AC, AC, AC, AC, TN, AC, KN, AC, AC, AC, ST, QN, AC, PF, AC }, 	 //	 127	 5000
{ AC, AC, ST, AC, TN, AC, AC, AC, AC, AC, ST, AC, KN, AC, AC }, 	 //	 128	 5000
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, TN, ST, AC, WN, KN, TN }, 	 //	 129	 5000
{ AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, ST, PF, KN, LO, AC }, 	 //	 130	 5000
{ AC, AC, KN, KN, AC, AC, AC, SH, AC, LO, ST, PF, AC, PF, AC }, 	 //	 131	 5000
{ AC, AC, AC, AC, SK, AC, AC, AC, PF, KN, ST, PF, AC, AC, KN }, 	 //	 132	 5000
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, KN, ST, PF, AC, KN, SK }, 	 //	 133	 5000
{ AC, AC, KN, KN, KN, AC, AC, KN, KN, KN, ST, PF, KN, KN, KN }, 	 //	 134	 5000
{ AC, AC, AC, AC, TN, AC, PF, AC, AC, AC, ST, KN, PF, LO, AC }, 	 //	 135	 5000
{ AC, KN, KN, KN, AC, AC, KN, KN, KN, KN, ST, KN, KN, WN, QN }, 	 //	 136	 5000
{ AC, KN, WN, KN, KN, AC, KN, KN, KN, KN, ST, SK, KN, KN, KN }, 	 //	 137	 5000
{ AC, QN, KN, PF, KN, AC, KN, KN, KN, KN, ST, AC, KN, KN, CR }, 	 //	 138	 5000
{ AC, KN, KN, AC, AC, AC, AC, SH, AC, AC, ST, SH, AC, AC, SK }, 	 //	 139	 5000
{ AC, SH, KN, KN, AC, ST, AC, SH, AC, AC, KN, AC, AC, PF, SK }, 	 //	 140	 5000
{ AC, SH, SH, TN, KN, ST, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 141	 5000
{ AC, SH, AC, KN, JA, ST, AC, AC, AC, WN, KN, AC, AC, PF, TN }, 	 //	 142	 5000
{ AC, SH, AC, WN, SH, ST, AC, AC, AC, JA, KN, AC, AC, KN, JA }, 	 //	 143	 5000
{ AC, SH, PF, KN, AC, ST, AC, QN, AC, SK, KN, AC, AC, PF, KN }, 	 //	 144	 5000
{ AC, AC, AC, AC, AC, ST, AC, KN, KN, SK, KN, AC, QN, QN, KN }, 	 //	 145	 5000
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, QN, KN, AC, WN, PF, PF }, 	 //	 146	 5000
{ AC, AC, AC, TN, AC, ST, AC, AC, AC, LO, KN, LO, PF, AC, AC }, 	 //	 147	 5000
{ AC, AC, AC, AC, AC, ST, AC, PF, LO, AC, KN, LO, QN, KN, SK }, 	 //	 148	 5000
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, SH, KN, LO, WN, PF, JA }, 	 //	 149	 5000
{ AC, AC, PF, WN, AC, ST, AC, QN, AC, AC, KN, LO, AC, KN, AC }, 	 //	 150	 5000
{ AC, AC, AC, AC, AC, ST, LO, KN, KN, AC, KN, KN, WN, QN, SK }, 	 //	 151	 5000
{ AC, KN, KN, KN, KN, ST, KN, WN, KN, KN, KN, KN, TN, KN, KN }, 	 //	 152	 5000
{ AC, KN, WN, KN, AC, ST, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 153	 5000
{ AC, KN, KN, KN, KN, ST, KN, QN, KN, KN, KN, ST, PF, KN, KN }, 	 //	 154	 5000
{ AC, KN, KN, AC, KN, ST, KN, KN, KN, AC, KN, ST, KN, QN, LO }, 	 //	 155	 5000
{ AC, KN, KN, LO, QN, ST, KN, KN, KN, KN, KN, ST, KN, KN, AC }, 	 //	 156	 5000
{ AC, KN, KN, KN, SK, ST, KN, KN, KN, QN, KN, ST, KN, WN, QN }, 	 //	 157	 5000
{ AC, KN, KN, KN, KN, ST, KN, KN, KN, QN, KN, ST, PF, KN, PF }, 	 //	 158	 5000
{ AC, QN, KN, KN, KN, ST, QN, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 159	 5000
{ AC, WN, AC, AC, JA, ST, AC, AC, AC, JA, KN, KN, AC, AC, WN }, 	 //	 160	 5000
{ AC, WN, KN, KN, KN, ST, AC, KN, KN, KN, KN, KN, KN, KN, SK }, 	 //	 161	 5000
{ AC, AC, KN, QN, KN, ST, KN, KN, KN, AC, KN, QN, KN, AC, LO }, 	 //	 162	 5000
{ AC, AC, AC, AC, AC, ST, KN, PF, AC, AC, KN, QN, QN, LO, CR }, 	 //	 163	 5000
{ AC, AC, KN, AC, KN, ST, KN, KN, KN, KN, KN, QN, PF, QN, KN }, 	 //	 164	 5000
{ AC, TN, AC, WN, KN, ST, AC, AC, AC, KN, KN, AC, AC, KN, KN }, 	 //	 165	 5000
{ AC, TN, PF, WN, AC, ST, AC, QN, AC, AC, KN, AC, AC, KN, CR }, 	 //	 166	 5000
{ AC, AC, KN, WN, AC, ST, AC, SH, AC, AC, KN, AC, AC, KN, CR }, 	 //	 167	 5000
{ AC, AC, AC, AC, KN, ST, AC, AC, AC, SK, KN, AC, WN, LO, QN }, 	 //	 168	 5000
{ AC, AC, AC, WN, JA, ST, AC, AC, AC, TN, KN, AC, WN, KN, AC }, 	 //	 169	 5000
{ AC, AC, AC, AC, SK, ST, AC, AC, AC, QN, KN, AC, WN, AC, QN }, 	 //	 170	 5000
{ AC, AC, PF, AC, AC, ST, AC, QN, AC, KN, KN, AC, AC, LO, QN }, 	 //	 171	 5000
{ AC, AC, AC, AC, AC, ST, PF, PF, AC, KN, KN, KN, QN, AC, QN }, 	 //	 172	 5000
{ AC, AC, AC, AC, AC, ST, PF, AC, PF, KN, KN, KN, AC, AC, QN }, 	 //	 173	 5000
{ AC, PF, ST, PF, KN, ST, KN, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 174	 5000
{ AC, PF, KN, KN, AC, ST, KN, KN, KN, AC, KN, KN, KN, SK, AC }, 	 //	 175	 5000
{ AC, KN, PF, KN, QN, ST, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 176	 5000
{ AC, KN, KN, QN, TN, ST, KN, KN, KN, TN, KN, KN, KN, AC, TN }, 	 //	 177	 5000
{ AC, SK, KN, KN, KN, ST, QN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 178	 5000
{ AC, QN, KN, LO, QN, ST, KN, KN, KN, KN, KN, AC, KN, KN, AC }, 	 //	 179	 5000
{ ST, AC, AC, TN, AC, KN, SH, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 180	 5000
{ ST, SH, AC, AC, JA, KN, AC, AC, AC, TN, KN, AC, AC, LO, AC }, 	 //	 181	 5000
{ ST, AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, KN, AC, AC, SK }, 	 //	 182	 5000
{ ST, LO, PF, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN }, 	 //	 183	 5000
{ ST, LO, WN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, ST }, 	 //	 184	 5000
{ ST, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, SH, KN, TN }, 	 //	 185	 5000
{ ST, KN, PF, LO, CR, KN, KN, KN, KN, KN, KN, ST, KN, KN, KN }, 	 //	 186	 5000
{ ST, KN, PF, KN, CR, KN, KN, KN, KN, KN, KN, ST, KN, KN, KN }, 	 //	 187	 5000
{ ST, WN, PF, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 188	 5000
{ ST, WN, SH, TN, TN, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 189	 5000
{ ST, AC, KN, LO, KN, KN, KN, KN, KN, KN, KN, QN, SH, KN, CR }, 	 //	 190	 5000
{ ST, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN, AC, AC, SK }, 	 //	 191	 5000
{ ST, AC, KN, LO, AC, KN, KN, KN, KN, AC, KN, QN, KN, KN, CR }, 	 //	 192	 5000
{ ST, TN, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, PF, AC, AC }, 	 //	 193	 5000
{ ST, AC, SH, TN, ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 194	 5000
{ ST, AC, AC, AC, AC, KN, PF, WN, PF, SK, KN, KN, KN, KN, KN }, 	 //	 195	 5000
{ ST, PF, PF, KN, LO, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 196	 5000
{ ST, KN, PF, PF, TN, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 197	 5000
{ ST, KN, KN, KN, KN, KN, KN, KN, SK, QN, KN, KN, KN, QN, PF }, 	 //	 198	 5000
{ ST, QN, KN, KN, PF, KN, KN, KN, KN, JA, KN, AC, KN, KN, TN }, 	 //	 199	 5000
{ ST, QN, KN, KN, TN, KN, KN, KN, KN, AC, KN, AC, KN, SK, AC }, 	 //	 200	 5000
{ KN, AC, TN, TN, AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 201	 5000
{ KN, AC, AC, WN, ST, KN, AC, AC, AC, AC, KN, LO, AC, KN, KN }, 	 //	 202	 5000
{ KN, LO, PF, AC, ST, KN, KN, KN, PF, AC, KN, KN, KN, KN, KN }, 	 //	 203	 5000
{ KN, LO, KN, SK, AC, KN, KN, KN, QN, AC, KN, KN, KN, KN, SK }, 	 //	 204	 5000
{ KN, LO, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, SH, SK, AC }, 	 //	 205	 5000
{ KN, KN, KN, TN, QN, KN, KN, KN, TN, PF, KN, KN, KN, TN, JA }, 	 //	 206	 5000
{ KN, KN, KN, AC, QN, KN, KN, KN, PF, PF, KN, KN, KN, AC, JA }, 	 //	 207	 5000
{ KN, KN, KN, QN, KN, KN, KN, KN, QN, QN, KN, KN, KN, QN, PF }, 	 //	 208	 5000
{ KN, KN, KN, JA, JA, KN, KN, KN, JA, JA, KN, KN, KN, JA, WN }, 	 //	 209	 5000
{ KN, KN, KN, JA, QN, KN, KN, KN, TN, PF, KN, KN, KN, AC, JA }, 	 //	 210	 5000
{ KN, KN, KN, TN, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN }, 	 //	 211	 5000
{ KN, KN, KN, AC, QN, KN, KN, KN, KN, QN, KN, KN, PF, QN, SH }, 	 //	 212	 5000
{ KN, KN, QN, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, SK }, 	 //	 213	 5000
{ KN, KN, QN, KN, KN, KN, KN, AC, KN, AC, KN, KN, KN, KN, LO }, 	 //	 214	 5000
{ KN, KN, KN, KN, SH, KN, KN, KN, AC, JA, KN, ST, KN, PF, JA }, 	 //	 215	 5000
{ KN, KN, KN, PF, AC, KN, KN, KN, KN, LO, KN, ST, PF, KN, AC }, 	 //	 216	 5000
{ KN, KN, KN, QN, SK, KN, KN, KN, KN, QN, KN, ST, PF, AC, QN }, 	 //	 217	 5000
{ KN, KN, KN, KN, KN, KN, KN, PF, KN, KN, KN, ST, QN, WN, SK }, 	 //	 218	 5000
{ KN, AC, PF, AC, SK, KN, KN, KN, KN, KN, KN, QN, KN, QN, KN }, 	 //	 219	 5000
{ KN, AC, PF, KN, KN, KN, KN, KN, KN, AC, KN, QN, KN, KN, LO }, 	 //	 220	 5000
{ KN, JA, KN, KN, KN, KN, TN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 221	 5000
{ KN, AC, AC, AC, AC, KN, PF, AC, AC, LO, KN, KN, AC, LO, AC }, 	 //	 222	 5000
{ KN, PF, KN, KN, KN, KN, KN, KN, SK, QN, KN, KN, KN, QN, PF }, 	 //	 223	 5000
{ KN, PF, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, PF, KN, KN }, 	 //	 224	 5000
{ KN, PF, QN, PF, KN, KN, KN, AC, KN, AC, KN, KN, KN, KN, LO }, 	 //	 225	 5000
{ KN, KN, KN, WN, AC, KN, KN, KN, QN, LO, KN, KN, KN, QN, AC }, 	 //	 226	 5000
{ KN, KN, KN, JA, TN, KN, KN, KN, JA, AC, KN, KN, KN, SH, AC }, 	 //	 227	 5000
{ KN, KN, KN, ST, TN, KN, KN, KN, JA, TN, KN, KN, KN, TN, ST }, 	 //	 228	 5000
{ KN, KN, KN, ST, TN, KN, KN, KN, JA, AC, KN, KN, KN, TN, AC }, 	 //	 229	 5000
{ KN, KN, KN, JA, WN, KN, KN, KN, TN, TN, KN, KN, KN, AC, TN }, 	 //	 230	 5000
{ KN, KN, KN, QN, JA, KN, KN, KN, SK, JA, KN, KN, KN, JA, JA }, 	 //	 231	 5000
{ KN, KN, KN, QN, QN, KN, KN, KN, ST, QN, KN, KN, KN, JA, SH }, 	 //	 232	 5000
{ KN, KN, KN, AC, ST, KN, KN, KN, LO, AC, KN, SK, KN, KN, KN }, 	 //	 233	 5000
{ KN, KN, KN, AC, SK, KN, KN, KN, LO, KN, KN, SK, KN, KN, KN }, 	 //	 234	 5000
{ KN, KN, KN, PF, AC, KN, KN, SH, AC, LO, KN, SK, AC, AC, AC }, 	 //	 235	 5000
{ KN, KN, WN, KN, AC, KN, KN, KN, KN, KN, KN, SK, KN, KN, QN }, 	 //	 236	 5000
{ KN, KN, WN, QN, KN, KN, KN, KN, KN, AC, KN, SK, KN, AC, LO }, 	 //	 237	 5000
{ KN, KN, KN, LO, JA, KN, KN, KN, KN, WN, KN, SK, PF, KN, TN }, 	 //	 238	 5000
{ KN, QN, KN, KN, KN, KN, KN, KN, KN, QN, KN, AC, SH, KN, PF }, 	 //	 239	 5000
{ KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, SH, KN, WN, SK }, 	 //	 240	 5000
{ KN, SH, AC, AC, TN, KN, AC, AC, AC, ST, SK, AC, AC, PF, AC }, 	 //	 241	 5000
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, SK, AC, PF, AC, QN }, 	 //	 242	 5000
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, AC, SK, AC, PF, LO, LO }, 	 //	 243	 5000
{ KN, AC, TN, AC, ST, KN, AC, AC, AC, AC, SK, AC, AC, AC, KN }, 	 //	 244	 5000
{ KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, SK, AC, KN, KN, KN }, 	 //	 245	 5000
{ KN, AC, SH, TN, AC, KN, AC, AC, AC, LO, SK, LO, AC, AC, AC }, 	 //	 246	 5000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, SK, KN, PF, SK, CR }, 	 //	 247	 5000
{ KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, SK, KN, KN, KN, KN }, 	 //	 248	 5000
{ KN, KN, PF, KN, JA, KN, KN, KN, KN, JA, SK, KN, KN, KN, WN }, 	 //	 249	 5000
{ KN, KN, KN, QN, AC, KN, KN, KN, KN, KN, SK, KN, SH, AC, QN }, 	 //	 250	 5000
{ KN, KN, KN, AC, KN, KN, KN, KN, LO, KN, SK, KN, KN, KN, KN }, 	 //	 251	 5000
{ KN, SH, KN, KN, KN, KN, TN, KN, KN, KN, SK, TN, KN, KN, KN }, 	 //	 252	 5000
{ KN, TN, AC, AC, TN, KN, WN, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 253	 5000
{ KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, SK, QN, WN, PF, AC }, 	 //	 254	 5000
{ KN, AC, KN, KN, QN, KN, KN, KN, KN, QN, SK, QN, KN, WN, QN }, 	 //	 255	 5000
{ KN, PF, KN, QN, LO, KN, KN, KN, KN, AC, SK, KN, KN, AC, AC }, 	 //	 256	 5000
{ KN, PF, QN, PF, KN, KN, KN, AC, KN, KN, SK, KN, KN, KN, KN }, 	 //	 257	 5000
{ KN, KN, KN, KN, SH, KN, KN, KN, KN, JA, SK, KN, PF, WN, JA }, 	 //	 258	 5000
{ KN, QN, PF, KN, QN, KN, KN, KN, KN, KN, SK, AC, KN, KN, AC }, 	 //	 259	 5000
{ KN, QN, KN, KN, QN, KN, KN, KN, KN, QN, SK, AC, KN, KN, SH }, 	 //	 260	 5000
{ KN, QN, KN, KN, SK, KN, KN, KN, KN, KN, SK, AC, PF, KN, KN }, 	 //	 261	 5000
{ KN, KN, AC, AC, QN, KN, AC, AC, AC, KN, SK, SH, AC, PF, AC }, 	 //	 262	 5000
{ KN, AC, AC, WN, JA, SK, AC, AC, AC, TN, QN, AC, AC, KN, AC }, 	 //	 263	 5000
{ KN, AC, AC, AC, QN, SK, AC, AC, AC, KN, QN, LO, PF, AC, AC }, 	 //	 264	 5000
{ KN, LO, KN, LO, JA, SK, KN, KN, KN, JA, QN, KN, KN, KN, JA }, 	 //	 265	 5000
{ KN, LO, WN, PF, AC, SK, KN, KN, KN, KN, QN, KN, KN, KN, QN }, 	 //	 266	 5000
{ KN, KN, KN, AC, WN, SK, KN, KN, KN, TN, QN, KN, KN, QN, TN }, 	 //	 267	 5000
{ KN, KN, WN, LO, KN, SK, KN, KN, KN, AC, QN, KN, KN, KN, LO }, 	 //	 268	 5000
{ KN, KN, KN, KN, KN, SK, KN, QN, KN, KN, QN, ST, PF, WN, KN }, 	 //	 269	 5000
{ KN, KN, KN, QN, JA, SK, KN, KN, KN, TN, QN, ST, KN, AC, AC }, 	 //	 270	 5000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, QN, QN, ST, SH, KN, PF }, 	 //	 271	 5000
{ KN, KN, KN, AC, AC, SK, KN, KN, KN, LO, QN, ST, KN, QN, AC }, 	 //	 272	 5000
{ KN, WN, AC, AC, KN, SK, AC, AC, AC, AC, QN, KN, AC, LO, LO }, 	 //	 273	 5000
{ KN, WN, AC, AC, AC, SK, AC, AC, AC, AC, QN, KN, WN, PF, CR }, 	 //	 274	 5000
{ KN, AC, KN, KN, KN, SK, KN, KN, KN, KN, QN, QN, SH, SK, KN }, 	 //	 275	 5000
{ KN, AC, AC, AC, AC, SK, KN, AC, AC, AC, QN, QN, AC, AC, SK }, 	 //	 276	 5000
{ KN, ST, KN, KN, KN, SK, JA, KN, KN, KN, QN, TN, KN, KN, KN }, 	 //	 277	 5000
{ KN, JA, AC, TN, AC, SK, TN, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 278	 5000
{ KN, AC, AC, WN, TN, SK, AC, AC, AC, ST, QN, PF, AC, KN, AC }, 	 //	 279	 5000
{ KN, PF, KN, KN, TN, SK, KN, KN, KN, TN, QN, KN, KN, KN, ST }, 	 //	 280	 5000
{ KN, KN, QN, PF, KN, SK, KN, PF, KN, KN, QN, KN, KN, KN, KN }, 	 //	 281	 5000
{ KN, KN, KN, AC, TN, SK, KN, KN, KN, ST, QN, KN, KN, QN, AC }, 	 //	 282	 5000
{ KN, KN, KN, KN, KN, SK, KN, KN, KN, AC, QN, KN, PF, KN, LO }, 	 //	 283	 5000
{ KN, KN, WN, AC, KN, SK, KN, KN, KN, KN, QN, SK, KN, QN, KN }, 	 //	 284	 5000
{ KN, KN, KN, AC, TN, SK, KN, KN, KN, ST, QN, SK, KN, QN, AC }, 	 //	 285	 5000
{ KN, KN, KN, PF, JA, SK, KN, KN, KN, JA, QN, SK, KN, KN, JA }, 	 //	 286	 5000
{ KN, KN, AC, AC, AC, SK, AC, AC, AC, LO, QN, SH, PF, AC, AC }, 	 //	 287	 5000
{ KN, KN, AC, AC, JA, SK, AC, AC, AC, TN, QN, SH, AC, LO, AC }, 	 //	 288	 5000
{ SK, SH, TN, PF, ST, QN, AC, AC, AC, AC, QN, AC, AC, AC, KN }, 	 //	 289	 5000
{ SK, SH, AC, WN, AC, QN, AC, AC, AC, KN, QN, AC, AC, KN, QN }, 	 //	 290	 5000
{ SK, AC, SH, PF, TN, QN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 291	 5000
{ SK, AC, AC, WN, QN, QN, AC, AC, AC, KN, QN, LO, AC, KN, AC }, 	 //	 292	 5000
{ SK, AC, AC, AC, ST, QN, AC, AC, AC, AC, QN, LO, PF, AC, KN }, 	 //	 293	 5000
{ SK, KN, KN, KN, JA, QN, KN, KN, KN, JA, QN, KN, KN, KN, WN }, 	 //	 294	 5000
{ SK, KN, KN, KN, QN, QN, KN, KN, KN, PF, QN, KN, KN, KN, JA }, 	 //	 295	 5000
{ SK, AC, KN, KN, AC, QN, KN, KN, KN, SK, QN, QN, KN, KN, KN }, 	 //	 296	 5000
{ SK, KN, KN, KN, KN, QN, QN, KN, KN, KN, QN, ST, KN, SK, KN }, 	 //	 297	 5000
{ SK, TN, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, PF, LO }, 	 //	 298	 5000
{ SK, AC, SH, AC, AC, QN, AC, AC, AC, LO, QN, PF, AC, AC, AC }, 	 //	 299	 5000
{ SK, AC, AC, AC, AC, QN, PF, AC, AC, AC, QN, KN, AC, AC, SK }, 	 //	 300	 5000
{ SK, KN, KN, KN, AC, QN, KN, KN, KN, LO, QN, KN, KN, KN, AC }, 	 //	 301	 5000
{ SK, KN, KN, KN, CR, QN, KN, KN, KN, KN, QN, SK, PF, KN, KN }, 	 //	 302	 5000
{ SK, QN, TN, AC, AC, QN, KN, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 303	 5000
{ SK, QN, KN, KN, KN, QN, KN, KN, KN, AC, QN, AC, KN, WN, LO }, 	 //	 304	 5000
{ QN, AC, SH, AC, JA, QN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 305	 5000
{ QN, LO, WN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, SK }, 	 //	 306	 5000
{ QN, KN, KN, KN, JA, QN, KN, KN, KN, TN, QN, KN, KN, KN, AC }, 	 //	 307	 5000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, KN, QN, KN, KN, WN, QN }, 	 //	 308	 5000
{ QN, KN, KN, AC, KN, QN, KN, KN, KN, KN, QN, ST, KN, QN, CR }, 	 //	 309	 5000
{ QN, TN, TN, AC, AC, QN, WN, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 310	 5000
{ QN, WN, SH, AC, TN, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 311	 5000
{ QN, AC, SH, AC, ST, QN, AC, AC, AC, AC, QN, AC, AC, AC, KN }, 	 //	 312	 5000
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN, AC, WN, LO, QN }, 	 //	 313	 5000
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, ST, QN, AC, WN, PF, AC }, 	 //	 314	 5000
{ QN, PF, WN, KN, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, CR }, 	 //	 315	 5000
{ QN, KN, KN, KN, SK, QN, KN, KN, KN, KN, QN, SK, PF, KN, KN }, 	 //	 316	 5000
{ QN, QN, KN, KN, KN, QN, KN, KN, KN, QN, QN, AC, KN, KN, PF }, 	 //	 317	 5000
{ QN, QN, KN, KN, SK, QN, KN, KN, KN, KN, QN, AC, KN, WN, KN }, 	 //	 318	 5000
{ QN, SH, SH, AC, TN, QN, AC, AC, AC, ST, SH, AC, AC, AC, AC }, 	 //	 319	 5000
{ QN, AC, AC, KN, TN, QN, AC, AC, AC, ST, SH, AC, AC, PF, AC }, 	 //	 320	 5000
{ QN, AC, AC, AC, QN, QN, AC, AC, AC, KN, SH, LO, WN, AC, AC }, 	 //	 321	 5000
{ QN, LO, KN, PF, QN, QN, KN, KN, KN, KN, SH, KN, KN, KN, AC }, 	 //	 322	 5000
{ QN, KN, KN, KN, TN, QN, KN, KN, KN, TN, SH, KN, KN, KN, TN }, 	 //	 323	 5000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, AC, SH, KN, KN, KN, CR }, 	 //	 324	 5000
{ QN, KN, KN, KN, QN, QN, KN, KN, KN, QN, SH, KN, KN, KN, SH }, 	 //	 325	 5000
{ QN, TN, TN, AC, AC, QN, WN, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 326	 5000
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, AC, SH, KN, PF, LO, CR }, 	 //	 327	 5000
{ QN, AC, SH, AC, TN, QN, AC, AC, AC, ST, SH, AC, AC, AC, AC }, 	 //	 328	 5000
{ QN, AC, AC, KN, JA, QN, AC, AC, AC, TN, SH, AC, AC, PF, AC }, 	 //	 329	 5000
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SH, PF, WN, LO, KN }, 	 //	 330	 5000
{ QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, SH, KN, PF, KN, CR }, 	 //	 331	 5000
{ QN, KN, AC, PF, AC, QN, AC, AC, AC, KN, SH, SH, AC, AC, QN }, 	 //	 332	 5000
{ QN, SH, SH, TN, JA, SH, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 333	 5000
{ QN, SH, KN, KN, KN, SH, AC, KN, KN, KN, JA, AC, KN, KN, KN }, 	 //	 334	 5000
{ QN, KN, KN, KN, QN, SH, KN, KN, KN, KN, JA, KN, KN, WN, AC }, 	 //	 335	 5000
{ QN, KN, KN, KN, CR, SH, KN, KN, KN, KN, JA, KN, PF, KN, KN }, 	 //	 336	 5000
{ QN, KN, KN, QN, CR, SH, KN, KN, KN, KN, JA, ST, KN, AC, KN }, 	 //	 337	 5000
{ QN, AC, KN, KN, KN, SH, KN, KN, KN, KN, JA, QN, PF, WN, KN }, 	 //	 338	 5000
{ QN, JA, AC, AC, TN, SH, TN, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 339	 5000
{ QN, JA, TN, TN, AC, SH, TN, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 340	 5000
{ QN, TN, TN, AC, JA, SH, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 341	 5000
{ QN, AC, SH, TN, JA, SH, AC, AC, AC, TN, JA, AC, AC, AC, AC }, 	 //	 342	 5000
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, KN, JA, PF, WN, AC, QN }, 	 //	 343	 5000
{ QN, KN, SH, TN, LO, SH, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 344	 5000
{ QN, KN, AC, AC, AC, SH, AC, AC, AC, LO, JA, SH, PF, AC, AC }, 	 //	 345	 5000
{ SH, AC, AC, TN, AC, JA, SH, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 346	 5000
{ SH, AC, TN, AC, KN, JA, AC, AC, AC, AC, JA, AC, AC, AC, LO }, 	 //	 347	 5000
{ SH, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA, LO, PF, AC, AC }, 	 //	 348	 5000
{ SH, LO, WN, PF, CR, JA, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 349	 5000
{ SH, KN, KN, AC, CR, JA, KN, KN, KN, KN, JA, ST, KN, QN, KN }, 	 //	 350	 5000
{ SH, KN, KN, KN, CR, JA, KN, KN, KN, KN, JA, ST, PF, KN, KN }, 	 //	 351	 5000
{ SH, WN, AC, AC, ST, JA, AC, AC, AC, AC, JA, KN, AC, AC, KN }, 	 //	 352	 5000
{ SH, AC, AC, AC, ST, JA, AC, AC, AC, AC, JA, PF, WN, AC, KN }, 	 //	 353	 5000
{ SH, PF, KN, LO, KN, JA, KN, KN, KN, SK, JA, KN, KN, KN, QN }, 	 //	 354	 5000
{ SH, KN, KN, KN, ST, JA, KN, KN, KN, AC, JA, SK, KN, WN, KN }, 	 //	 355	 5000
{ SH, KN, WN, KN, KN, JA, KN, KN, KN, KN, JA, SK, KN, KN, KN }, 	 //	 356	 5000
{ JA, AC, AC, AC, AC, JA, SH, AC, AC, KN, JA, AC, AC, AC, QN }, 	 //	 357	 5000
{ JA, SH, SH, TN, TN, JA, AC, AC, AC, ST, JA, AC, AC, AC, AC }, 	 //	 358	 5000
{ JA, AC, AC, WN, AC, JA, AC, AC, AC, SK, JA, AC, AC, KN, KN }, 	 //	 359	 5000
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, ST, JA, AC, PF, LO, AC }, 	 //	 360	 5000
{ JA, LO, KN, LO, AC, JA, KN, KN, KN, KN, JA, KN, KN, KN, QN }, 	 //	 361	 5000
{ JA, KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, SH, KN, CR }, 	 //	 362	 5000
{ JA, KN, KN, KN, KN, JA, ST, KN, KN, KN, JA, QN, KN, SK, KN }, 	 //	 363	 5000
{ JA, AC, SH, PF, KN, JA, AC, AC, AC, AC, JA, AC, AC, AC, LO }, 	 //	 364	 5000
{ JA, AC, TN, AC, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC, AC }, 	 //	 365	 5000
{ JA, AC, SH, TN, TN, JA, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 366	 5000
{ JA, SK, KN, PF, KN, JA, QN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 367	 5000
{ JA, SK, KN, LO, KN, JA, QN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 368	 5000
{ JA, QN, KN, LO, KN, JA, KN, KN, KN, KN, JA, AC, KN, KN, SK }, 	 //	 369	 5000
{ JA, AC, SH, AC, JA, JA, AC, AC, AC, TN, WN, AC, AC, AC, AC }, 	 //	 370	 5000
{ JA, LO, KN, KN, SK, JA, KN, KN, KN, KN, WN, KN, KN, WN, KN }, 	 //	 371	 5000
{ JA, KN, KN, KN, SK, JA, KN, KN, KN, QN, WN, KN, KN, KN, QN }, 	 //	 372	 5000
{ JA, AC, KN, PF, ST, JA, KN, KN, KN, AC, WN, QN, KN, KN, KN }, 	 //	 373	 5000
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, ST, WN, AC, WN, PF, AC }, 	 //	 374	 5000
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, SK, WN, PF, WN, AC, KN }, 	 //	 375	 5000
{ JA, PF, WN, KN, CR, JA, KN, KN, KN, KN, WN, KN, KN, KN, KN }, 	 //	 376	 5000
{ JA, QN, KN, KN, AC, JA, KN, KN, KN, SK, WN, AC, KN, KN, KN }, 	 //	 377	 5000
{ JA, AC, KN, PF, KN, WN, LO, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 378	 5000
{ JA, LO, PF, KN, CR, WN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 379	 5000
{ JA, TN, KN, KN, KN, WN, TN, KN, KN, KN, TN, TN, KN, KN, KN }, 	 //	 380	 5000
{ JA, TN, AC, WN, TN, WN, AC, AC, AC, ST, TN, AC, AC, KN, AC }, 	 //	 381	 5000
{ JA, AC, KN, KN, KN, WN, AC, KN, KN, KN, TN, AC, KN, KN, KN }, 	 //	 382	 5000
{ JA, AC, AC, AC, AC, WN, AC, AC, AC, SK, TN, PF, PF, AC, KN }, 	 //	 383	 5000
{ JA, PF, KN, KN, KN, WN, KN, KN, KN, QN, TN, KN, KN, WN, PF }, 	 //	 384	 5000
{ JA, KN, KN, KN, CR, WN, KN, KN, KN, QN, TN, KN, KN, SK, KN }, 	 //	 385	 5000
{ JA, KN, KN, KN, JA, WN, KN, KN, KN, WN, TN, KN, KN, KN, TN }, 	 //	 386	 5000
{ JA, KN, KN, QN, KN, WN, KN, KN, KN, KN, TN, SK, KN, AC, SK }, 	 //	 387	 5000
{ JA, QN, SH, AC, AC, WN, KN, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 388	 5000
{ JA, KN, AC, AC, KN, WN, AC, AC, AC, AC, TN, SH, AC, AC, LO }, 	 //	 389	 5000
{ WN, AC, AC, AC, AC, TN, SH, AC, AC, AC, TN, AC, PF, PF, AC }, 	 //	 390	 5000
{ WN, AC, AC, AC, ST, TN, AC, AC, AC, AC, TN, AC, WN, PF, KN }, 	 //	 391	 5000
{ WN, LO, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, PF, KN, KN }, 	 //	 392	 5000
{ WN, KN, KN, KN, JA, TN, KN, KN, KN, TN, TN, KN, KN, KN, AC }, 	 //	 393	 5000
{ WN, KN, KN, KN, KN, TN, QN, KN, KN, KN, TN, ST, KN, WN, KN }, 	 //	 394	 5000
{ WN, AC, SH, PF, TN, TN, AC, AC, AC, ST, TN, AC, AC, AC, AC }, 	 //	 395	 5000
{ WN, AC, KN, KN, KN, TN, AC, KN, KN, KN, TN, AC, KN, KN, KN }, 	 //	 396	 5000
{ WN, AC, SH, TN, TN, TN, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 397	 5000
{ WN, PF, KN, QN, CR, TN, KN, KN, KN, KN, TN, KN, KN, AC, KN }, 	 //	 398	 5000
{ WN, PF, WN, LO, CR, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 399	 5000
{ WN, QN, KN, KN, KN, TN, KN, KN, KN, KN, TN, AC, PF, KN, KN }, 	 //	 400	 5000
{ TN, SH, AC, WN, TN, TN, AC, AC, AC, ST, TN, AC, AC, KN, AC }, 	 //	 401	 5000
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN, AC, PF, AC, QN }, 	 //	 402	 5000
{ TN, KN, KN, KN, QN, TN, KN, KN, KN, KN, TN, KN, KN, WN, AC }, 	 //	 403	 5000
{ TN, AC, KN, KN, KN, TN, KN, KN, KN, AC, TN, QN, KN, WN, LO }, 	 //	 404	 5000
{ TN, AC, KN, KN, SK, TN, KN, KN, KN, KN, TN, QN, KN, SK, KN }, 	 //	 405	 5000
{ TN, AC, KN, LO, AC, TN, KN, KN, KN, SK, TN, QN, KN, KN, KN }, 	 //	 406	 5000
{ TN, PF, WN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, CR }, 	 //	 407	 5000
{ TN, KN, WN, KN, SK, TN, KN, KN, KN, KN, TN, KN, KN, KN, KN }, 	 //	 408	 5000
{ TN, KN, KN, KN, PF, TN, KN, KN, KN, JA, TN, KN, KN, KN, TN }, 	 //	 409	 5000
{ TN, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, SK, PF, WN, CR }, 	 //	 410	 5000
{ TN, QN, KN, LO, AC, TN, KN, KN, KN, SK, TN, AC, KN, KN, KN }, 	 //	 411	 5000
{ TN, QN, KN, PF, KN, TN, KN, KN, KN, KN, TN, AC, KN, KN, SK }, 	 //	 412	 5000
{ TN, KN, SH, PF, AC, TN, AC, AC, AC, LO, TN, SH, AC, AC, AC }, 	 //	 413	 5000
{ TN, AC, AC, AC, AC, TN, SH, AC, AC, AC, ST, AC, AC, LO, CR }, 	 //	 414	 5000
{ TN, SH, AC, WN, ST, TN, AC, AC, AC, AC, ST, AC, AC, KN, KN }, 	 //	 415	 5000
{ TN, SH, AC, KN, QN, TN, AC, AC, AC, KN, ST, AC, AC, PF, AC }, 	 //	 416	 5000
{ TN, AC, AC, AC, ST, TN, AC, AC, AC, AC, ST, LO, PF, PF, KN }, 	 //	 417	 5000
{ TN, LO, KN, KN, AC, TN, KN, KN, KN, KN, ST, KN, KN, KN, QN }, 	 //	 418	 5000
{ TN, TN, KN, KN, KN, TN, WN, KN, KN, KN, ST, AC, KN, KN, KN }, 	 //	 419	 5000
{ TN, AC, KN, PF, CR, TN, KN, KN, KN, QN, ST, QN, KN, KN, KN }, 	 //	 420	 5000
{ TN, AC, AC, AC, AC, TN, KN, AC, AC, AC, ST, QN, AC, AC, SK }, 	 //	 421	 5000
{ TN, AC, KN, LO, KN, TN, KN, KN, KN, KN, ST, QN, KN, KN, SK }, 	 //	 422	 5000
{ TN, TN, AC, WN, AC, TN, AC, AC, AC, SK, ST, AC, AC, KN, KN }, 	 //	 423	 5000
{ TN, AC, SH, AC, TN, TN, AC, AC, AC, ST, ST, AC, AC, AC, AC }, 	 //	 424	 5000
{ TN, AC, AC, AC, AC, TN, PF, AC, AC, AC, ST, KN, AC, AC, CR }, 	 //	 425	 5000
{ TN, KN, KN, KN, CR, TN, KN, KN, KN, QN, ST, SK, KN, WN, KN }, 	 //	 426	 5000
{ TN, QN, KN, KN, KN, TN, KN, KN, KN, KN, ST, AC, PF, KN, KN }, 	 //	 427	 5000
{ TN, AC, JA, JA, TN, ST, SH, ST, TN, AC, AC, AC, AC, AC, AC }, 	 //	 428	 5000
{ TN, SH, JA, JA, LO, ST, AC, ST, TN, AC, AC, AC, AC, AC, AC }, 	 //	 429	 5000
{ TN, SH, TN, WN, AC, ST, AC, AC, AC, KN, AC, AC, AC, KN, QN }, 	 //	 430	 5000
{ TN, SH, AC, KN, LO, ST, AC, WN, AC, AC, AC, AC, KN, PF, AC }, 	 //	 431	 5000
{ TN, AC, SH, AC, PF, ST, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 432	 5000
{ TN, AC, AC, TN, JA, ST, AC, KN, AC, TN, AC, AC, WN, AC, AC }, 	 //	 433	 5000
{ TN, AC, AC, KN, LO, ST, AC, PF, AC, AC, AC, LO, QN, PF, AC }, 	 //	 434	 5000
{ TN, AC, AC, PF, TN, ST, AC, AC, AC, TN, AC, LO, AC, AC, ST }, 	 //	 435	 5000
{ TN, AC, AC, TN, TN, ST, AC, AC, AC, TN, AC, LO, AC, AC, ST }, 	 //	 436	 5000
{ TN, AC, AC, AC, KN, ST, AC, AC, AC, QN, AC, LO, WN, PF, PF }, 	 //	 437	 5000
{ TN, KN, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, PF, WN, CR }, 	 //	 438	 5000
{ TN, TN, JA, AC, TN, ST, WN, ST, AC, AC, AC, AC, AC, AC, AC }, 	 //	 439	 5000
{ TN, TN, JA, TN, TN, ST, WN, ST, WN, AC, AC, AC, AC, AC, AC }, 	 //	 440	 5000
{ TN, TN, JA, TN, TN, ST, WN, ST, AC, AC, AC, AC, AC, AC, AC }, 	 //	 441	 5000
{ TN, WN, AC, PF, KN, ST, AC, AC, AC, KN, AC, KN, AC, AC, KN }, 	 //	 442	 5000
{ TN, WN, AC, AC, KN, ST, AC, AC, AC, KN, AC, KN, AC, PF, CR }, 	 //	 443	 5000
{ TN, WN, KN, LO, KN, ST, AC, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 444	 5000
{ TN, AC, KN, QN, KN, ST, KN, KN, KN, KN, AC, QN, KN, AC, SK }, 	 //	 445	 5000
{ TN, AC, AC, AC, AC, ST, KN, AC, AC, AC, AC, QN, AC, LO, CR }, 	 //	 446	 5000
{ TN, JA, SH, AC, LO, ST, TN, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 447	 5000
{ TN, TN, SH, PF, JA, ST, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 448	 5000
{ TN, TN, SH, TN, KN, ST, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 449	 5000
{ TN, TN, AC, KN, LO, ST, AC, PF, AC, AC, AC, AC, QN, PF, AC }, 	 //	 450	 5000
{ TN, TN, AC, AC, TN, ST, AC, KN, AC, ST, AC, AC, WN, AC, AC }, 	 //	 451	 5000
{ TN, AC, SH, JA, AC, ST, AC, AC, TN, AC, AC, AC, AC, AC, AC }, 	 //	 452	 5000
{ TN, AC, SH, AC, JA, ST, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 453	 5000
{ TN, AC, AC, AC, QN, ST, AC, AC, AC, PF, AC, AC, PF, LO, JA }, 	 //	 454	 5000
{ TN, AC, AC, PF, TN, ST, AC, PF, AC, ST, AC, AC, QN, AC, AC }, 	 //	 455	 5000
{ TN, AC, AC, WN, AC, ST, AC, PF, AC, AC, AC, AC, QN, KN, AC }, 	 //	 456	 5000
{ TN, AC, AC, TN, AC, ST, AC, PF, AC, AC, AC, AC, QN, AC, AC }, 	 //	 457	 5000
{ TN, AC, AC, KN, LO, ST, AC, PF, AC, AC, AC, AC, QN, PF, AC }, 	 //	 458	 5000
{ TN, AC, AC, AC, SK, ST, AC, AC, PF, KN, AC, AC, AC, AC, KN }, 	 //	 459	 5000
{ TN, AC, AC, AC, KN, ST, AC, AC, AC, QN, AC, AC, WN, AC, PF }, 	 //	 460	 5000
{ TN, AC, AC, PF, SH, ST, AC, AC, AC, JA, AC, PF, AC, AC, JA }, 	 //	 461	 5000
{ TN, AC, AC, AC, AC, ST, PF, AC, AC, AC, AC, KN, AC, AC, SK }, 	 //	 462	 5000
{ TN, KN, KN, KN, QN, ST, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 463	 5000
{ TN, QN, KN, AC, QN, ST, KN, SH, PF, KN, AC, AC, AC, AC, AC }, 	 //	 464	 5000
{ TN, KN, AC, AC, CR, ST, AC, AC, AC, QN, AC, SH, AC, AC, KN }, 	 //	 465	 5000
{ ST, SH, SH, TN, JA, AC, AC, AC, AC, JA, KN, AC, AC, AC, JA }, 	 //	 466	 5000
{ ST, SH, AC, KN, QN, AC, AC, AC, AC, PF, KN, AC, AC, PF, JA }, 	 //	 467	 5000
{ ST, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, PF, AC, SH }, 	 //	 468	 5000
{ ST, AC, AC, WN, JA, AC, AC, AC, AC, WN, KN, AC, AC, KN, TN }, 	 //	 469	 5000
{ ST, AC, AC, AC, JA, AC, AC, AC, AC, WN, KN, AC, WN, AC, TN }, 	 //	 470	 5000
{ ST, AC, QN, AC, LO, AC, AC, AC, AC, AC, KN, AC, KN, LO, AC }, 	 //	 471	 5000
{ ST, AC, SH, TN, JA, AC, AC, AC, AC, TN, KN, LO, AC, AC, AC }, 	 //	 472	 5000
{ ST, LO, PF, LO, KN, AC, KN, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 473	 5000
{ ST, LO, KN, QN, QN, AC, KN, KN, KN, QN, KN, KN, KN, AC, QN }, 	 //	 474	 5000
{ ST, LO, WN, PF, KN, AC, KN, KN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 475	 5000
{ ST, LO, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN, PF, WN, CR }, 	 //	 476	 5000
{ ST, KN, ST, KN, KN, AC, KN, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 477	 5000
{ ST, KN, KN, QN, TN, AC, KN, KN, KN, TN, KN, KN, KN, AC, ST }, 	 //	 478	 5000
{ ST, KN, KN, AC, TN, AC, KN, KN, KN, TN, KN, KN, KN, QN, ST }, 	 //	 479	 5000
{ ST, KN, KN, KN, AC, AC, KN, KN, KN, SK, KN, KN, PF, KN, KN }, 	 //	 480	 5000
{ ST, KN, KN, KN, QN, AC, KN, KN, KN, KN, KN, KN, PF, SK, AC }, 	 //	 481	 5000
{ ST, KN, KN, KN, KN, AC, KN, SH, KN, KN, KN, ST, AC, KN, KN }, 	 //	 482	 5000
{ ST, WN, AC, PF, KN, AC, AC, AC, AC, SK, KN, KN, AC, AC, QN }, 	 //	 483	 5000
{ ST, WN, AC, WN, TN, AC, AC, AC, AC, TN, KN, KN, AC, KN, TN }, 	 //	 484	 5000
{ ST, WN, AC, TN, PF, AC, AC, AC, AC, JA, KN, KN, AC, AC, TN }, 	 //	 485	 5000
{ ST, WN, AC, AC, KN, AC, AC, AC, AC, KN, KN, KN, AC, AC, KN }, 	 //	 486	 5000
{ ST, WN, AC, AC, TN, AC, AC, AC, AC, TN, KN, KN, AC, AC, ST }, 	 //	 487	 5000
{ ST, AC, KN, LO, KN, AC, KN, KN, KN, KN, KN, QN, SH, KN, KN }, 	 //	 488	 5000
{ ST, AC, AC, AC, AC, AC, KN, AC, AC, AC, KN, QN, PF, LO, AC }, 	 //	 489	 5000
{ ST, AC, KN, LO, KN, AC, KN, KN, KN, QN, KN, QN, KN, KN, PF }, 	 //	 490	 5000
{ ST, TN, AC, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, LO, TN }, 	 //	 491	 5000
{ ST, TN, AC, WN, SK, AC, AC, AC, AC, KN, KN, AC, AC, KN, KN }, 	 //	 492	 5000
{ ST, AC, ST, AC, ST, AC, AC, AC, AC, AC, KN, AC, KN, AC, KN }, 	 //	 493	 5000
{ ST, AC, SH, PF, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 494	 5000
{ ST, AC, SH, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 495	 5000
{ ST, AC, AC, KN, JA, AC, AC, AC, AC, JA, KN, AC, AC, PF, WN }, 	 //	 496	 5000
{ ST, AC, QN, AC, ST, AC, AC, AC, AC, AC, KN, PF, KN, LO, KN }, 	 //	 497	 5000
{ ST, PF, KN, QN, QN, AC, KN, KN, KN, QN, KN, KN, KN, AC, SH }, 	 //	 498	 5000
{ ST, KN, PF, QN, KN, AC, KN, KN, KN, KN, KN, KN, KN, AC, SK }, 	 //	 499	 5000
{ ST, KN, KN, QN, JA, AC, KN, KN, KN, JA, KN, KN, KN, AC, JA }, 	 //	 500	 5000
{ ST, KN, KN, QN, AC, AC, KN, KN, KN, AC, KN, KN, KN, AC, SK }, 	 //	 501	 5000
{ ST, KN, WN, PF, AC, AC, KN, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 502	 5000
{ ST, KN, KN, AC, QN, AC, KN, KN, KN, QN, KN, KN, KN, QN, SH }, 	 //	 503	 5000
{ ST, KN, KN, QN, QN, AC, KN, KN, KN, QN, KN, KN, KN, AC, SH }, 	 //	 504	 5000
{ ST, KN, KN, KN, KN, AC, KN, KN, KN, SK, KN, SK, SH, KN, QN }, 	 //	 505	 5000
{ ST, KN, KN, KN, PF, AC, KN, KN, KN, JA, KN, SK, KN, KN, TN }, 	 //	 506	 5000
{ ST, KN, KN, AC, KN, AC, KN, KN, KN, QN, KN, SK, KN, QN, PF }, 	 //	 507	 5000
{ ST, KN, AC, AC, JA, AC, AC, AC, AC, JA, KN, SH, AC, AC, WN }, 	 //	 508	 5000
{ AC, SH, AC, KN, KN, KN, AC, AC, AC, KN, QN, AC, AC, PF, KN }, 	 //	 509	 5000
{ AC, SH, TN, AC, PF, KN, AC, AC, AC, JA, QN, AC, AC, AC, TN }, 	 //	 510	 5000
{ AC, SH, AC, WN, KN, KN, AC, AC, AC, QN, QN, AC, AC, KN, PF }, 	 //	 511	 5000
{ AC, AC, AC, PF, QN, KN, AC, AC, AC, KN, QN, AC, PF, AC, AC }, 	 //	 512	 5000
{ AC, AC, JA, WN, AC, KN, AC, TN, AC, AC, QN, LO, AC, KN, AC }, 	 //	 513	 5000
{ AC, AC, AC, AC, AC, KN, AC, KN, LO, SK, QN, LO, WN, KN, KN }, 	 //	 514	 5000
{ AC, AC, AC, AC, AC, KN, LO, AC, LO, LO, QN, KN, AC, KN, AC }, 	 //	 515	 5000
{ AC, AC, AC, AC, AC, KN, LO, AC, AC, KN, QN, KN, WN, AC, QN }, 	 //	 516	 5000
{ AC, LO, WN, KN, QN, KN, KN, KN, KN, KN, QN, KN, KN, KN, AC }, 	 //	 517	 5000
{ AC, LO, KN, KN, AC, KN, KN, KN, KN, LO, QN, KN, KN, KN, AC }, 	 //	 518	 5000
{ AC, KN, KN, KN, KN, KN, KN, KN, KN, AC, QN, ST, PF, KN, LO }, 	 //	 519	 5000
{ AC, KN, KN, KN, CR, KN, KN, KN, KN, QN, QN, ST, PF, WN, KN }, 	 //	 520	 5000
{ AC, WN, JA, AC, AC, KN, AC, ST, AC, KN, QN, KN, AC, LO, QN }, 	 //	 521	 5000
{ AC, WN, TN, AC, TN, KN, AC, AC, AC, ST, QN, KN, AC, AC, AC }, 	 //	 522	 5000
{ AC, WN, PF, AC, AC, KN, AC, QN, AC, AC, QN, KN, AC, LO, AC }, 	 //	 523	 5000
{ AC, AC, AC, AC, AC, KN, KN, AC, PF, LO, QN, QN, AC, KN, AC }, 	 //	 524	 5000
{ AC, AC, AC, AC, AC, KN, KN, AC, KN, SK, QN, QN, AC, QN, KN }, 	 //	 525	 5000
{ AC, TN, SH, TN, TN, KN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 526	 5000
{ AC, TN, SH, AC, TN, KN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 527	 5000
{ AC, TN, PF, AC, AC, KN, AC, QN, AC, AC, QN, AC, AC, PF, SK }, 	 //	 528	 5000
{ AC, AC, JA, WN, AC, KN, AC, ST, AC, KN, QN, AC, AC, KN, QN }, 	 //	 529	 5000
{ AC, AC, TN, AC, QN, KN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 530	 5000
{ AC, AC, AC, AC, CR, KN, AC, AC, PF, KN, QN, AC, AC, AC, KN }, 	 //	 531	 5000
{ AC, AC, AC, AC, SK, KN, AC, AC, AC, KN, QN, AC, WN, PF, KN }, 	 //	 532	 5000
{ AC, AC, JA, PF, AC, KN, AC, ST, AC, KN, QN, PF, AC, AC, QN }, 	 //	 533	 5000
{ AC, AC, SH, TN, JA, KN, AC, AC, AC, TN, QN, PF, AC, AC, AC }, 	 //	 534	 5000
{ AC, AC, AC, AC, AC, KN, AC, AC, LO, AC, QN, PF, PF, KN, AC }, 	 //	 535	 5000
{ AC, AC, AC, AC, AC, KN, AC, AC, KN, AC, QN, PF, PF, QN, AC }, 	 //	 536	 5000
{ AC, AC, PF, TN, AC, KN, AC, QN, AC, KN, QN, PF, AC, AC, QN }, 	 //	 537	 5000
{ AC, AC, AC, AC, AC, KN, PF, KN, AC, AC, QN, KN, QN, AC, CR }, 	 //	 538	 5000
{ AC, AC, AC, AC, AC, KN, PF, AC, PF, AC, QN, KN, AC, AC, SK }, 	 //	 539	 5000
{ AC, KN, KN, KN, QN, KN, KN, KN, KN, QN, QN, KN, KN, WN, SH }, 	 //	 540	 5000
{ AC, KN, KN, KN, AC, KN, KN, KN, KN, AC, QN, SK, KN, KN, AC }, 	 //	 541	 5000
{ AC, KN, KN, KN, JA, KN, KN, KN, KN, WN, QN, SK, KN, KN, TN }, 	 //	 542	 5000
{ AC, KN, KN, LO, CR, KN, KN, KN, KN, KN, QN, SK, PF, KN, KN }, 	 //	 543	 5000
{ AC, KN, KN, KN, AC, KN, KN, KN, KN, SK, QN, SK, PF, SK, KN }, 	 //	 544	 5000
{ AC, KN, AC, AC, SK, KN, AC, AC, AC, QN, QN, SH, AC, LO, QN }, 	 //	 545	 5000
{ AC, KN, AC, AC, KN, KN, AC, AC, AC, KN, QN, SH, AC, PF, KN }, 	 //	 546	 5000
{ KN, SH, SH, AC, KN, QN, AC, AC, AC, AC, PF, AC, AC, AC, LO }, 	 //	 547	 5000
{ KN, LO, WN, PF, KN, QN, KN, KN, KN, SK, PF, KN, KN, KN, QN }, 	 //	 548	 5000
{ KN, KN, KN, QN, QN, QN, KN, KN, KN, SH, PF, KN, KN, AC, JA }, 	 //	 549	 5000
{ KN, KN, KN, KN, KN, QN, KN, PF, KN, KN, PF, KN, QN, KN, KN }, 	 //	 550	 5000
{ KN, KN, KN, LO, TN, QN, KN, KN, KN, TN, PF, ST, KN, KN, TN }, 	 //	 551	 5000
{ KN, KN, KN, PF, AC, QN, KN, KN, KN, AC, PF, ST, KN, KN, AC }, 	 //	 552	 5000
{ KN, KN, KN, PF, AC, QN, KN, KN, KN, AC, PF, ST, KN, KN, AC }, 	 //	 553	 5000
{ KN, KN, KN, KN, KN, QN, KN, KN, KN, AC, PF, ST, SH, WN, LO }, 	 //	 554	 5000
{ KN, KN, KN, LO, AC, QN, KN, KN, KN, LO, PF, ST, KN, KN, AC }, 	 //	 555	 5000
{ KN, QN, KN, KN, KN, QN, SK, KN, KN, KN, PF, JA, KN, KN, KN }, 	 //	 556	 5000
{ KN, AC, AC, AC, AC, QN, KN, KN, KN, KN, PF, QN, QN, QN, QN }, 	 //	 557	 5000
{ KN, KN, KN, KN, KN, QN, QN, KN, KN, KN, PF, ST, KN, KN, CR }, 	 //	 558	 5000
{ KN, QN, KN, KN, KN, QN, ST, KN, KN, KN, PF, JA, KN, KN, KN }, 	 //	 559	 5000
{ KN, AC, AC, AC, AC, QN, PF, AC, AC, AC, PF, KN, AC, AC, SK }, 	 //	 560	 5000
{ KN, PF, KN, KN, QN, QN, KN, KN, KN, SH, PF, KN, KN, KN, JA }, 	 //	 561	 5000
{ KN, KN, KN, QN, QN, QN, KN, KN, KN, SH, PF, KN, KN, AC, JA }, 	 //	 562	 5000
{ KN, KN, KN, KN, ST, QN, KN, KN, KN, AC, PF, KN, SH, WN, KN }, 	 //	 563	 5000
{ KN, KN, KN, PF, WN, QN, KN, KN, KN, TN, PF, SK, KN, KN, TN }, 	 //	 564	 5000
{ KN, KN, KN, AC, AC, QN, KN, KN, KN, LO, PF, SK, KN, QN, AC }, 	 //	 565	 5000
{ KN, KN, KN, KN, CR, QN, SK, KN, KN, KN, PF, QN, KN, KN, KN }, 	 //	 566	 5000
{ KN, KN, AC, AC, JA, QN, AC, AC, AC, TN, PF, SH, AC, LO, AC }, 	 //	 567	 5000
{ KN, KN, AC, KN, KN, QN, AC, AC, AC, AC, PF, SH, AC, PF, LO }, 	 //	 568	 5000
{ QN, SH, TN, AC, AC, PF, AC, AC, AC, SK, JA, AC, AC, AC, KN }, 	 //	 569	 5000
{ QN, SH, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, WN, LO, CR }, 	 //	 570	 5000
{ QN, AC, AC, AC, QN, PF, AC, AC, AC, KN, JA, AC, PF, LO, AC }, 	 //	 571	 5000
{ QN, AC, AC, WN, ST, PF, AC, AC, AC, AC, JA, LO, AC, KN, KN }, 	 //	 572	 5000
{ QN, AC, AC, AC, AC, PF, LO, AC, AC, LO, JA, KN, AC, PF, AC }, 	 //	 573	 5000
{ QN, KN, PF, KN, CR, PF, KN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 574	 5000
{ QN, KN, KN, KN, WN, PF, KN, KN, KN, TN, JA, KN, KN, KN, TN }, 	 //	 575	 5000
{ QN, KN, KN, KN, QN, PF, KN, KN, KN, QN, JA, KN, KN, KN, QN }, 	 //	 576	 5000
{ QN, QN, KN, KN, KN, PF, QN, KN, KN, KN, JA, QN, KN, KN, KN }, 	 //	 577	 5000
{ QN, AC, KN, KN, KN, PF, KN, KN, KN, SK, JA, QN, KN, WN, QN }, 	 //	 578	 5000
{ QN, QN, KN, KN, KN, PF, KN, KN, KN, AC, JA, AC, KN, WN, LO }, 	 //	 579	 5000
{ PF, AC, SH, TN, AC, JA, AC, AC, AC, SK, TN, AC, AC, AC, KN }, 	 //	 580	 5000
{ PF, AC, SH, AC, TN, JA, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 581	 5000
{ PF, AC, AC, TN, AC, JA, AC, AC, AC, KN, TN, LO, AC, AC, QN }, 	 //	 582	 5000
{ PF, KN, KN, KN, ST, JA, KN, KN, KN, AC, TN, ST, KN, SK, KN }, 	 //	 583	 5000
{ PF, TN, TN, AC, AC, JA, WN, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 584	 5000
{ PF, AC, KN, KN, KN, JA, KN, KN, KN, KN, TN, QN, PF, KN, KN }, 	 //	 585	 5000
{ PF, KN, KN, KN, KN, JA, SK, KN, KN, KN, TN, QN, KN, WN, KN }, 	 //	 586	 5000
{ PF, KN, KN, KN, KN, JA, SK, KN, KN, KN, TN, QN, KN, SK, KN }, 	 //	 587	 5000
{ PF, QN, KN, KN, KN, JA, KN, KN, KN, SK, TN, AC, KN, WN, QN }, 	 //	 588	 5000
{ JA, AC, JA, AC, TN, TN, SH, ST, PF, ST, AC, AC, AC, AC, AC }, 	 //	 589	 5000
{ JA, AC, JA, PF, TN, TN, SH, ST, AC, ST, AC, AC, AC, AC, AC }, 	 //	 590	 5000
{ JA, AC, KN, TN, LO, TN, SH, SH, AC, AC, AC, AC, AC, AC, AC }, 	 //	 591	 5000
{ JA, AC, AC, TN, AC, TN, SH, AC, WN, LO, AC, AC, AC, AC, AC }, 	 //	 592	 5000
{ JA, SH, SH, PF, JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 593	 5000
{ JA, SH, SH, AC, LO, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 594	 5000
{ JA, SH, JA, TN, AC, TN, AC, TN, WN, AC, AC, AC, AC, AC, AC }, 	 //	 595	 5000
{ JA, SH, TN, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 596	 5000
{ JA, AC, KN, QN, AC, TN, AC, SH, KN, AC, AC, AC, AC, AC, AC }, 	 //	 597	 5000
{ JA, AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, PF, AC, KN }, 	 //	 598	 5000
{ JA, AC, AC, AC, KN, TN, AC, AC, AC, SK, AC, AC, PF, AC, QN }, 	 //	 599	 5000
{ JA, AC, AC, KN, AC, TN, AC, PF, AC, AC, AC, LO, QN, PF, AC }, 	 //	 600	 5000
{ JA, AC, AC, TN, KN, TN, AC, AC, AC, KN, AC, LO, AC, AC, CR }, 	 //	 601	 5000
{ JA, KN, PF, PF, KN, TN, KN, KN, KN, KN, AC, KN, KN, KN, CR }, 	 //	 602	 5000
{ JA, KN, KN, KN, AC, TN, KN, KN, KN, KN, AC, KN, KN, SK, QN }, 	 //	 603	 5000
{ JA, KN, KN, KN, QN, TN, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 604	 5000
{ JA, ST, KN, KN, KN, TN, QN, KN, KN, KN, AC, QN, KN, KN, KN }, 	 //	 605	 5000
{ JA, TN, PF, AC, AC, TN, WN, QN, PF, AC, AC, AC, AC, AC, AC }, 	 //	 606	 5000
{ JA, WN, SH, AC, TN, TN, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 607	 5000
{ JA, WN, AC, AC, KN, TN, AC, AC, AC, KN, AC, KN, AC, AC, CR }, 	 //	 608	 5000
{ JA, WN, AC, AC, LO, TN, AC, PF, AC, AC, AC, KN, QN, PF, AC }, 	 //	 609	 5000
{ JA, WN, AC, AC, QN, TN, AC, AC, AC, QN, AC, KN, AC, AC, QN }, 	 //	 610	 5000
{ JA, WN, AC, AC, CR, TN, AC, AC, AC, QN, AC, KN, AC, AC, KN }, 	 //	 611	 5000
{ JA, WN, AC, TN, TN, TN, AC, KN, AC, AC, AC, KN, WN, AC, AC }, 	 //	 612	 5000
{ JA, WN, AC, AC, QN, TN, AC, KN, AC, KN, AC, KN, WN, PF, AC }, 	 //	 613	 5000
{ JA, AC, KN, KN, KN, TN, KN, KN, KN, KN, AC, QN, SH, SK, KN }, 	 //	 614	 5000
{ JA, AC, AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, AC, CR }, 	 //	 615	 5000
{ JA, TN, SH, KN, AC, TN, AC, AC, AC, KN, AC, AC, AC, PF, QN }, 	 //	 616	 5000
{ JA, TN, TN, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 617	 5000
{ JA, TN, AC, AC, QN, TN, AC, WN, AC, KN, AC, AC, KN, AC, AC }, 	 //	 618	 5000
{ JA, AC, SH, AC, JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 619	 5000
{ JA, AC, SH, KN, AC, TN, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 620	 5000
{ JA, AC, AC, AC, SH, TN, AC, AC, AC, JA, AC, AC, WN, PF, JA }, 	 //	 621	 5000
{ JA, AC, SH, AC, TN, TN, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 622	 5000
{ JA, AC, AC, PF, CR, TN, AC, AC, AC, QN, AC, PF, AC, AC, KN }, 	 //	 623	 5000
{ JA, AC, AC, KN, TN, TN, AC, AC, AC, TN, AC, PF, AC, PF, TN }, 	 //	 624	 5000
{ JA, KN, KN, QN, CR, TN, KN, KN, KN, KN, AC, KN, KN, AC, KN }, 	 //	 625	 5000
{ JA, QN, JA, PF, QN, TN, KN, ST, AC, KN, AC, AC, AC, AC, AC }, 	 //	 626	 5000
{ JA, QN, KN, KN, KN, TN, KN, KN, KN, QN, AC, AC, KN, SK, PF }, 	 //	 627	 5000
{ JA, QN, PF, AC, QN, TN, KN, QN, PF, KN, AC, AC, AC, AC, AC }, 	 //	 628	 5000
{ JA, KN, AC, AC, KN, TN, AC, AC, AC, KN, AC, SH, AC, AC, KN }, 	 //	 629	 5000
{ JA, KN, AC, PF, CR, TN, AC, AC, AC, QN, AC, SH, AC, AC, KN }, 	 //	 630	 5000
{ JA, KN, AC, AC, KN, TN, AC, AC, AC, QN, AC, SH, AC, AC, PF }, 	 //	 631	 5000
{ JA, KN, AC, AC, TN, TN, AC, AC, AC, TN, AC, SH, AC, PF, ST }, 	 //	 632	 5000
{ JA, KN, AC, KN, PF, TN, AC, AC, AC, JA, AC, SH, AC, PF, TN }, 	 //	 633	 5000
{ TN, AC, KN, TN, JA, AC, SH, SH, AC, TN, AC, AC, AC, AC, AC }, 	 //	 634	 5000
{ TN, AC, SH, AC, TN, AC, SH, AC, AC, ST, AC, AC, AC, AC, AC }, 	 //	 635	 5000
{ TN, AC, AC, TN, AC, AC, SH, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 636	 5000
{ TN, SH, AC, QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC, SK }, 	 //	 637	 5000
{ TN, SH, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, PF, ST }, 	 //	 638	 5000
{ TN, SH, AC, TN, SH, AC, AC, AC, WN, JA, AC, AC, AC, AC, JA }, 	 //	 639	 5000
{ TN, SH, AC, AC, LO, AC, AC, WN, AC, AC, AC, AC, KN, AC, AC }, 	 //	 640	 5000
{ TN, SH, AC, KN, LO, AC, AC, KN, AC, AC, AC, AC, WN, PF, AC }, 	 //	 641	 5000
{ TN, AC, AC, KN, QN, AC, AC, KN, AC, KN, AC, AC, QN, PF, AC }, 	 //	 642	 5000
{ TN, AC, AC, JA, TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST }, 	 //	 643	 5000
{ TN, AC, AC, WN, AC, AC, AC, KN, AC, LO, AC, AC, WN, KN, AC }, 	 //	 644	 5000
{ TN, AC, AC, TN, JA, AC, AC, PF, AC, TN, AC, LO, QN, AC, AC }, 	 //	 645	 5000
{ TN, AC, AC, WN, AC, AC, AC, KN, AC, AC, AC, LO, WN, KN, AC }, 	 //	 646	 5000
{ TN, KN, KN, KN, SH, AC, KN, KN, KN, JA, AC, KN, KN, KN, JA }, 	 //	 647	 5000
{ TN, KN, KN, KN, SK, AC, KN, KN, KN, KN, AC, KN, SH, SK, KN }, 	 //	 648	 5000
{ TN, KN, KN, KN, CR, AC, KN, KN, KN, KN, AC, ST, SH, KN, KN }, 	 //	 649	 5000
{ TN, TN, KN, KN, KN, AC, WN, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 650	 5000
{ TN, TN, SH, AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, AC, SK }, 	 //	 651	 5000
{ TN, AC, AC, AC, AC, AC, KN, AC, AC, LO, AC, QN, AC, LO, AC }, 	 //	 652	 5000
{ TN, JA, AC, TN, AC, AC, TN, AC, WN, AC, AC, AC, AC, AC, AC }, 	 //	 653	 5000
{ TN, JA, TN, TN, AC, AC, TN, AC, WN, AC, AC, AC, AC, AC, AC }, 	 //	 654	 5000
{ TN, TN, AC, PF, AC, AC, AC, PF, AC, LO, AC, AC, QN, AC, AC }, 	 //	 655	 5000
{ TN, TN, AC, AC, TN, AC, AC, PF, AC, AC, AC, AC, QN, LO, AC }, 	 //	 656	 5000
{ TN, TN, PF, AC, TN, AC, AC, QN, PF, AC, AC, AC, AC, AC, AC }, 	 //	 657	 5000
{ TN, TN, PF, JA, LO, AC, AC, QN, TN, AC, AC, AC, AC, AC, AC }, 	 //	 658	 5000
{ TN, TN, QN, TN, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC }, 	 //	 659	 5000
{ TN, TN, QN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC }, 	 //	 660	 5000
{ TN, AC, ST, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC }, 	 //	 661	 5000
{ TN, AC, AC, TN, SK, AC, AC, AC, WN, KN, AC, AC, AC, AC, KN }, 	 //	 662	 5000
{ TN, AC, ST, AC, AC, AC, AC, AC, AC, AC, AC, PF, KN, LO, SK }, 	 //	 663	 5000
{ TN, AC, AC, AC, AC, AC, AC, AC, LO, KN, AC, PF, AC, KN, QN }, 	 //	 664	 5000
{ TN, PF, PF, KN, CR, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 665	 5000
{ TN, KN, PF, LO, CR, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 666	 5000
{ TN, KN, PF, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, CR }, 	 //	 667	 5000
{ TN, KN, KN, KN, QN, AC, KN, KN, KN, KN, AC, KN, KN, WN, AC }, 	 //	 668	 5000
{ TN, KN, WN, KN, SK, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 669	 5000
{ TN, QN, JA, QN, AC, AC, KN, TN, KN, AC, AC, AC, AC, AC, AC }, 	 //	 670	 5000
{ TN, QN, PF, AC, LO, AC, KN, QN, AC, AC, AC, AC, AC, AC, AC }, 	 //	 671	 5000
{ TN, KN, AC, KN, AC, AC, AC, WN, AC, AC, AC, SH, KN, PF, AC }, 	 //	 672	 5000
{ TN, KN, AC, TN, QN, AC, AC, KN, AC, KN, AC, SH, WN, AC, AC }, 	 //	 673	 5000
{ AC, AC, AC, AC, AC, AC, SH, WN, AC, AC, AC, AC, KN, AC, SK }, 	 //	 674	 5000
{ AC, SH, ST, PF, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC }, 	 //	 675	 5000
{ AC, SH, AC, AC, QN, AC, AC, PF, AC, KN, AC, AC, QN, LO, AC }, 	 //	 676	 5000
{ AC, SH, QN, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, LO, AC }, 	 //	 677	 5000
{ AC, AC, TN, TN, QN, AC, AC, AC, WN, SH, AC, AC, AC, AC, JA }, 	 //	 678	 5000
{ AC, AC, TN, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC, PF }, 	 //	 679	 5000
{ AC, AC, TN, QN, QN, AC, AC, AC, KN, QN, AC, AC, AC, AC, QN }, 	 //	 680	 5000
{ AC, AC, ST, AC, KN, AC, AC, AC, AC, AC, AC, LO, KN, LO, LO }, 	 //	 681	 5000
{ AC, AC, KN, KN, AC, AC, AC, SH, AC, AC, AC, LO, AC, PF, AC }, 	 //	 682	 5000
{ AC, AC, AC, AC, AC, AC, LO, AC, AC, KN, AC, KN, WN, PF, QN }, 	 //	 683	 5000
{ AC, LO, KN, KN, KN, AC, KN, KN, KN, SK, AC, KN, KN, WN, QN }, 	 //	 684	 5000
{ AC, LO, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, SH, SK, KN }, 	 //	 685	 5000
{ AC, KN, KN, KN, TN, AC, KN, KN, KN, ST, AC, KN, KN, KN, AC }, 	 //	 686	 5000
{ AC, KN, KN, PF, AC, AC, KN, KN, KN, SK, AC, ST, KN, KN, KN }, 	 //	 687	 5000
{ AC, TN, KN, KN, KN, AC, WN, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 688	 5000
{ AC, WN, AC, WN, TN, AC, AC, KN, AC, AC, AC, KN, QN, KN, AC }, 	 //	 689	 5000
{ AC, AC, KN, QN, SK, AC, KN, KN, KN, KN, AC, QN, KN, AC, KN }, 	 //	 690	 5000
{ AC, AC, AC, AC, QN, AC, KN, AC, AC, KN, AC, QN, AC, AC, AC }, 	 //	 691	 5000
{ AC, AC, AC, AC, AC, AC, KN, AC, KN, AC, AC, QN, WN, QN, CR }, 	 //	 692	 5000
{ AC, JA, PF, QN, TN, AC, TN, QN, KN, AC, AC, AC, AC, AC, AC }, 	 //	 693	 5000
{ AC, TN, ST, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, LO }, 	 //	 694	 5000
{ AC, TN, ST, AC, AC, AC, AC, AC, AC, AC, AC, AC, KN, PF, AC }, 	 //	 695	 5000
{ AC, TN, AC, TN, QN, AC, AC, WN, AC, KN, AC, AC, KN, AC, AC }, 	 //	 696	 5000
{ AC, AC, ST, PF, AC, AC, AC, AC, AC, AC, AC, AC, KN, AC, CR }, 	 //	 697	 5000
{ AC, AC, TN, QN, JA, AC, AC, AC, KN, JA, AC, AC, AC, AC, JA }, 	 //	 698	 5000
{ AC, AC, KN, WN, AC, AC, AC, SH, AC, AC, AC, PF, AC, KN, CR }, 	 //	 699	 5000
{ AC, AC, AC, AC, SH, AC, AC, AC, KN, JA, AC, PF, PF, QN, JA }, 	 //	 700	 5000
{ AC, AC, QN, WN, AC, AC, AC, AC, AC, AC, AC, PF, KN, KN, SK }, 	 //	 701	 5000
{ AC, AC, AC, AC, TN, AC, PF, AC, AC, AC, AC, KN, WN, AC, AC }, 	 //	 702	 5000
{ AC, KN, KN, AC, KN, AC, KN, KN, KN, KN, AC, SK, KN, QN, SK }, 	 //	 703	 5000
{ AC, KN, AC, AC, QN, AC, AC, WN, AC, KN, AC, SH, KN, PF, AC }, 	 //	 704	 5000
{ AC, AC, AC, AC, AC, AC, SH, KN, PF, AC, SK, AC, QN, KN, CR }, 	 //	 705	 5000
{ AC, AC, AC, AC, AC, AC, SH, AC, AC, SK, SK, AC, PF, AC, KN }, 	 //	 706	 5000
{ AC, AC, JA, KN, AC, AC, AC, ST, AC, AC, SK, AC, AC, PF, AC }, 	 //	 707	 5000
{ AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, SK, AC, KN, KN, AC }, 	 //	 708	 5000
{ AC, AC, SH, QN, TN, AC, AC, AC, KN, ST, SK, AC, AC, AC, AC }, 	 //	 709	 5000
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, SK, AC, PF, AC, KN }, 	 //	 710	 5000
{ AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, SK, AC, AC, PF, SK }, 	 //	 711	 5000
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, PF, SK, AC, WN, KN, JA }, 	 //	 712	 5000
{ AC, AC, PF, AC, AC, AC, AC, QN, AC, AC, SK, AC, AC, LO, AC }, 	 //	 713	 5000
{ AC, AC, AC, AC, QN, AC, AC, AC, PF, SH, SK, LO, AC, KN, JA }, 	 //	 714	 5000
{ AC, AC, QN, WN, AC, AC, AC, AC, AC, AC, SK, LO, KN, KN, SK }, 	 //	 715	 5000
{ AC, AC, QN, AC, AC, AC, AC, AC, AC, AC, SK, LO, KN, PF, AC }, 	 //	 716	 5000
{ AC, AC, AC, AC, AC, AC, LO, KN, PF, AC, SK, KN, QN, AC, AC }, 	 //	 717	 5000
{ AC, AC, AC, AC, AC, AC, LO, KN, PF, SK, SK, KN, QN, KN, KN }, 	 //	 718	 5000
{ AC, AC, AC, AC, AC, AC, LO, KN, PF, LO, SK, KN, WN, AC, AC }, 	 //	 719	 5000
{ AC, LO, KN, QN, CR, AC, KN, KN, KN, KN, SK, KN, KN, AC, KN }, 	 //	 720	 5000
{ AC, LO, KN, PF, KN, AC, KN, KN, KN, AC, SK, KN, KN, KN, LO }, 	 //	 721	 5000
{ AC, QN, KN, KN, KN, AC, QN, KN, KN, KN, SK, QN, KN, KN, KN }, 	 //	 722	 5000
{ AC, WN, JA, PF, AC, AC, AC, TN, AC, AC, SK, KN, AC, AC, CR }, 	 //	 723	 5000
{ AC, WN, JA, AC, AC, AC, AC, TN, AC, AC, SK, KN, AC, AC, SK }, 	 //	 724	 5000
{ AC, WN, PF, AC, AC, AC, AC, QN, AC, KN, SK, KN, AC, PF, QN }, 	 //	 725	 5000
{ AC, AC, AC, AC, AC, AC, KN, AC, PF, SK, SK, QN, AC, AC, KN }, 	 //	 726	 5000
{ AC, AC, KN, PF, KN, AC, KN, KN, KN, KN, SK, QN, KN, KN, CR }, 	 //	 727	 5000
{ AC, TN, AC, TN, AC, AC, AC, AC, WN, AC, SK, AC, AC, AC, AC }, 	 //	 728	 5000
{ AC, AC, KN, AC, AC, AC, AC, SH, AC, KN, SK, AC, AC, PF, QN }, 	 //	 729	 5000
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, SK, SK, AC, PF, AC, QN }, 	 //	 730	 5000
{ AC, AC, JA, WN, AC, AC, AC, TN, AC, SK, SK, AC, AC, KN, KN }, 	 //	 731	 5000
{ AC, AC, TN, JA, JA, AC, AC, AC, TN, TN, SK, AC, AC, AC, AC }, 	 //	 732	 5000
{ AC, AC, AC, AC, KN, AC, AC, AC, PF, AC, SK, AC, AC, KN, LO }, 	 //	 733	 5000
{ AC, AC, KN, WN, AC, AC, AC, SH, AC, LO, SK, PF, AC, KN, AC }, 	 //	 734	 5000
{ AC, AC, AC, AC, JA, AC, AC, AC, LO, WN, SK, PF, AC, KN, TN }, 	 //	 735	 5000
{ AC, AC, AC, AC, AC, AC, PF, PF, KN, AC, SK, KN, QN, QN, AC }, 	 //	 736	 5000
{ AC, AC, AC, AC, AC, AC, PF, AC, PF, KN, SK, KN, AC, KN, QN }, 	 //	 737	 5000
{ AC, AC, AC, AC, AC, AC, PF, WN, AC, SK, SK, KN, KN, LO, KN }, 	 //	 738	 5000
{ AC, QN, PF, LO, KN, AC, KN, KN, KN, KN, SK, AC, KN, KN, KN }, 	 //	 739	 5000
{ AC, QN, KN, LO, AC, AC, KN, KN, KN, SK, SK, AC, KN, KN, KN }, 	 //	 740	 5000
{ AC, QN, SH, TN, AC, AC, KN, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 741	 5000
{ AC, KN, QN, AC, AC, AC, AC, AC, AC, AC, SK, SH, KN, AC, SK }, 	 //	 742	 5000
{ AC, AC, AC, AC, AC, SK, SH, WN, AC, KN, KN, AC, KN, AC, QN }, 	 //	 743	 5000
{ AC, SH, AC, AC, TN, SK, AC, AC, AC, TN, KN, AC, AC, LO, TN }, 	 //	 744	 5000
{ AC, AC, AC, AC, AC, SK, AC, KN, LO, KN, KN, AC, QN, KN, QN }, 	 //	 745	 5000
{ AC, AC, AC, AC, AC, SK, AC, AC, PF, AC, KN, AC, PF, AC, SK }, 	 //	 746	 5000
{ AC, AC, JA, AC, AC, SK, AC, TN, AC, AC, KN, AC, AC, LO, AC }, 	 //	 747	 5000
{ AC, AC, AC, JA, QN, SK, AC, AC, TN, KN, KN, AC, AC, AC, AC }, 	 //	 748	 5000
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN, AC, WN, PF, KN }, 	 //	 749	 5000
{ AC, AC, AC, AC, AC, SK, AC, AC, PF, AC, KN, AC, WN, KN, SK }, 	 //	 750	 5000
{ AC, AC, PF, AC, AC, SK, AC, QN, AC, AC, KN, AC, AC, LO, CR }, 	 //	 751	 5000
{ AC, AC, AC, AC, AC, SK, AC, KN, KN, LO, KN, AC, WN, QN, AC }, 	 //	 752	 5000
{ AC, AC, AC, AC, AC, SK, AC, KN, PF, AC, KN, LO, QN, KN, AC }, 	 //	 753	 5000
{ AC, AC, AC, AC, AC, SK, AC, AC, PF, SK, KN, LO, PF, KN, KN }, 	 //	 754	 5000
{ AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, LO, WN, AC, QN }, 	 //	 755	 5000
{ AC, AC, AC, AC, AC, SK, AC, WN, PF, SK, KN, LO, KN, AC, KN }, 	 //	 756	 5000
{ AC, AC, PF, AC, AC, SK, AC, QN, AC, SK, KN, LO, AC, LO, KN }, 	 //	 757	 5000
{ AC, AC, AC, AC, AC, SK, LO, AC, PF, AC, KN, KN, AC, KN, AC }, 	 //	 758	 5000
{ AC, LO, KN, QN, LO, SK, KN, KN, KN, AC, KN, KN, KN, AC, AC }, 	 //	 759	 5000
{ AC, LO, AC, PF, KN, SK, KN, WN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 760	 5000
{ AC, LO, KN, QN, LO, SK, KN, KN, KN, AC, KN, KN, KN, AC, AC }, 	 //	 761	 5000
{ AC, KN, PF, KN, KN, SK, KN, KN, KN, KN, KN, ST, KN, KN, KN }, 	 //	 762	 5000
{ AC, KN, KN, PF, KN, SK, KN, KN, KN, KN, KN, ST, SH, KN, KN }, 	 //	 763	 5000
{ AC, JA, KN, KN, KN, SK, SH, KN, KN, KN, KN, TN, KN, KN, KN }, 	 //	 764	 5000
{ AC, WN, JA, KN, AC, SK, AC, ST, AC, KN, KN, KN, AC, PF, QN }, 	 //	 765	 5000
{ AC, AC, AC, AC, AC, SK, KN, WN, PF, KN, KN, QN, KN, AC, QN }, 	 //	 766	 5000
{ AC, TN, SH, AC, KN, SK, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 767	 5000
{ AC, TN, TN, AC, TN, SK, AC, AC, AC, TN, KN, AC, AC, AC, ST }, 	 //	 768	 5000
{ AC, AC, JA, AC, AC, SK, AC, TN, AC, LO, KN, AC, AC, LO, AC }, 	 //	 769	 5000
{ AC, AC, TN, TN, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN }, 	 //	 770	 5000
{ AC, AC, AC, AC, SK, SK, AC, AC, PF, QN, KN, AC, AC, AC, QN }, 	 //	 771	 5000
{ AC, AC, AC, AC, AC, SK, AC, KN, PF, AC, KN, PF, QN, AC, CR }, 	 //	 772	 5000
{ AC, AC, AC, AC, AC, SK, AC, WN, LO, LO, KN, PF, KN, KN, AC }, 	 //	 773	 5000
{ AC, PF, PF, LO, AC, SK, KN, KN, KN, KN, KN, KN, KN, KN, QN }, 	 //	 774	 5000
{ AC, KN, KN, KN, KN, SK, KN, WN, KN, KN, KN, SK, TN, KN, KN }, 	 //	 775	 5000
{ AC, KN, KN, KN, TN, SK, KN, KN, KN, TN, KN, SK, KN, KN, TN }, 	 //	 776	 5000
{ AC, KN, KN, PF, KN, SK, KN, KN, KN, AC, KN, SK, KN, KN, LO }, 	 //	 777	 5000
{ AC, KN, KN, KN, QN, SK, KN, KN, KN, QN, KN, SK, KN, KN, QN }, 	 //	 778	 5000
{ AC, QN, KN, QN, KN, SK, KN, KN, KN, KN, KN, AC, SH, AC, KN }, 	 //	 779	 5000
{ AC, QN, KN, AC, CR, SK, KN, KN, KN, KN, KN, AC, PF, QN, KN }, 	 //	 780	 5000
{ AC, KN, JA, AC, AC, SK, AC, ST, AC, SK, KN, SH, AC, AC, KN }, 	 //	 781	 5000
{ AC, KN, KN, AC, AC, SK, AC, SH, AC, LO, KN, SH, AC, LO, AC }, 	 //	 782	 5000
{ AC, KN, AC, TN, KN, SK, AC, AC, AC, QN, KN, SH, AC, AC, PF }, 	 //	 783	 5000
{ AC, KN, JA, AC, AC, SK, AC, TN, AC, AC, KN, SH, AC, AC, SK }, 	 //	 784	 5000
{ AC, KN, AC, WN, KN, SK, AC, AC, AC, SK, KN, SH, AC, KN, QN }, 	 //	 785	 5000
{ AC, KN, AC, TN, KN, SK, AC, AC, AC, QN, KN, SH, AC, AC, PF }, 	 //	 786	 5000
{ AC, KN, AC, KN, KN, SK, AC, AC, AC, SK, KN, SH, AC, PF, QN }, 	 //	 787	 5000
{ SK, SH, AC, KN, AC, KN, AC, AC, AC, SK, KN, AC, AC, PF, KN }, 	 //	 788	 5000
{ SK, SH, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, PF, AC, AC }, 	 //	 789	 5000
{ SK, AC, SH, TN, ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 790	 5000
{ SK, AC, AC, WN, QN, KN, AC, AC, AC, KN, KN, AC, AC, KN, AC }, 	 //	 791	 5000
{ SK, LO, PF, LO, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, JA }, 	 //	 792	 5000
{ SK, LO, KN, KN, KN, KN, KN, KN, KN, AC, KN, KN, SH, SK, LO }, 	 //	 793	 5000
{ SK, LO, KN, AC, QN, KN, KN, KN, KN, KN, KN, KN, PF, QN, AC }, 	 //	 794	 5000
{ SK, KN, KN, KN, KN, KN, KN, KN, QN, SK, KN, KN, KN, ST, QN }, 	 //	 795	 5000
{ SK, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, SH, KN, AC }, 	 //	 796	 5000
{ SK, KN, KN, PF, QN, KN, KN, KN, KN, QN, KN, ST, KN, KN, SH }, 	 //	 797	 5000
{ SK, KN, KN, KN, TN, KN, KN, KN, KN, AC, KN, ST, PF, KN, AC }, 	 //	 798	 5000
{ SK, TN, KN, KN, KN, KN, WN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 799	 5000
{ SK, AC, KN, PF, JA, KN, KN, KN, KN, TN, KN, QN, KN, KN, AC }, 	 //	 800	 5000
{ SK, AC, AC, WN, ST, KN, AC, AC, AC, AC, KN, AC, AC, KN, KN }, 	 //	 801	 5000
{ SK, AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, PF, PF, LO }, 	 //	 802	 5000
{ SK, AC, AC, AC, AC, KN, PF, AC, AC, AC, KN, KN, PF, LO, AC }, 	 //	 803	 5000
{ SK, KN, PF, KN, KN, KN, KN, KN, KN, AC, KN, KN, KN, WN, LO }, 	 //	 804	 5000
{ SK, KN, KN, KN, KN, KN, KN, KN, AC, AC, KN, KN, KN, PF, LO }, 	 //	 805	 5000
{ SK, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN, SK, SH, QN, SK }, 	 //	 806	 5000
{ SK, QN, KN, KN, AC, KN, KN, KN, KN, LO, KN, AC, KN, WN, AC }, 	 //	 807	 5000
{ SK, QN, KN, KN, AC, KN, KN, KN, KN, LO, KN, AC, KN, SK, AC }, 	 //	 808	 5000
{ SK, QN, KN, KN, JA, KN, KN, KN, KN, TN, KN, AC, KN, SK, AC }, 	 //	 809	 5000
{ SK, KN, AC, AC, TN, KN, AC, AC, AC, ST, KN, SH, AC, LO, AC }, 	 //	 810	 5000
{ SK, KN, AC, AC, QN, KN, AC, AC, AC, KN, KN, SH, AC, LO, AC }, 	 //	 811	 5000
{ SK, KN, AC, WN, AC, KN, AC, AC, AC, KN, KN, SH, AC, KN, QN }, 	 //	 812	 5000
{ KN, AC, KN, KN, KN, KN, SH, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 813	 5000
{ KN, SH, TN, AC, AC, KN, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 814	 5000
{ KN, LO, QN, LO, KN, KN, KN, PF, KN, SK, KN, KN, KN, KN, QN }, 	 //	 815	 5000
{ KN, LO, QN, PF, CR, KN, KN, PF, KN, KN, KN, KN, KN, KN, KN }, 	 //	 816	 5000
{ KN, LO, KN, WN, TN, KN, KN, KN, AC, TN, KN, KN, KN, KN, TN }, 	 //	 817	 5000
{ KN, LO, KN, PF, QN, KN, KN, KN, KN, KN, KN, KN, SH, KN, AC }, 	 //	 818	 5000
{ KN, LO, WN, KN, AC, KN, KN, KN, KN, LO, KN, KN, KN, WN, AC }, 	 //	 819	 5000
{ KN, LO, KN, AC, TN, KN, KN, KN, LO, TN, KN, KN, KN, KN, ST }, 	 //	 820	 5000
{ KN, KN, KN, WN, AC, KN, KN, KN, QN, SK, KN, KN, KN, QN, KN }, 	 //	 821	 5000
{ KN, KN, KN, QN, JA, KN, KN, KN, SK, JA, KN, KN, KN, JA, JA }, 	 //	 822	 5000
{ KN, KN, KN, QN, TN, KN, KN, KN, SK, TN, KN, KN, KN, JA, ST }, 	 //	 823	 5000
{ KN, KN, KN, AC, QN, KN, KN, KN, PF, SH, KN, KN, KN, AC, JA }, 	 //	 824	 5000
{ KN, KN, KN, AC, QN, KN, KN, KN, AC, QN, KN, KN, KN, AC, QN }, 	 //	 825	 5000
{ KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, KN, LO, CR }, 	 //	 826	 5000
{ KN, KN, KN, JA, CR, KN, KN, KN, SH, QN, KN, KN, KN, TN, KN }, 	 //	 827	 5000
{ KN, KN, KN, TN, QN, KN, KN, KN, WN, SH, KN, KN, KN, AC, JA }, 	 //	 828	 5000
{ KN, KN, KN, AC, TN, KN, KN, KN, KN, ST, KN, KN, PF, QN, AC }, 	 //	 829	 5000
{ KN, KN, KN, KN, CR, KN, KN, QN, KN, QN, KN, ST, PF, WN, KN }, 	 //	 830	 5000
{ KN, KN, PF, LO, ST, KN, KN, KN, KN, AC, KN, ST, KN, KN, KN }, 	 //	 831	 5000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, TN, KN, ST, SH, KN, TN }, 	 //	 832	 5000
{ KN, KN, KN, LO, TN, KN, KN, KN, KN, AC, KN, ST, SH, KN, AC }, 	 //	 833	 5000
{ KN, KN, KN, KN, TN, KN, KN, KN, SK, ST, KN, ST, KN, QN, AC }, 	 //	 834	 5000
{ KN, WN, AC, TN, ST, KN, AC, AC, AC, AC, KN, KN, AC, AC, KN }, 	 //	 835	 5000
{ KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN, WN, LO, AC }, 	 //	 836	 5000
{ KN, JA, AC, AC, TN, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 837	 5000
{ KN, TN, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, PF, LO }, 	 //	 838	 5000
{ KN, AC, AC, AC, AC, KN, PF, AC, AC, AC, KN, KN, PF, AC, AC }, 	 //	 839	 5000
{ KN, AC, AC, AC, AC, KN, PF, AC, AC, AC, KN, KN, AC, AC, SK }, 	 //	 840	 5000
{ KN, PF, PF, KN, JA, KN, KN, KN, KN, TN, KN, KN, KN, WN, AC }, 	 //	 841	 5000
{ KN, PF, KN, SK, KN, KN, KN, KN, QN, AC, KN, KN, KN, KN, LO }, 	 //	 842	 5000
{ KN, PF, WN, KN, JA, KN, KN, KN, KN, WN, KN, KN, KN, WN, TN }, 	 //	 843	 5000
{ KN, PF, WN, KN, SH, KN, KN, KN, KN, JA, KN, KN, KN, SK, JA }, 	 //	 844	 5000
{ KN, PF, KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, PF, KN, KN }, 	 //	 845	 5000
{ KN, PF, QN, KN, KN, KN, KN, AC, KN, QN, KN, KN, KN, KN, PF }, 	 //	 846	 5000
{ KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, KN, KN, KN, KN, CR }, 	 //	 847	 5000
{ KN, KN, KN, PF, KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, KN }, 	 //	 848	 5000
{ KN, KN, WN, KN, TN, KN, KN, KN, KN, TN, KN, KN, KN, SK, ST }, 	 //	 849	 5000
{ KN, KN, KN, ST, AC, KN, KN, KN, JA, AC, KN, KN, KN, TN, CR }, 	 //	 850	 5000
{ KN, KN, KN, LO, WN, KN, KN, KN, KN, TN, KN, KN, PF, KN, TN }, 	 //	 851	 5000
{ KN, KN, KN, KN, AC, KN, KN, WN, KN, SK, KN, SK, TN, WN, KN }, 	 //	 852	 5000
{ KN, KN, PF, KN, KN, KN, KN, KN, KN, QN, KN, SK, KN, SK, PF }, 	 //	 853	 5000
{ KN, KN, KN, AC, TN, KN, KN, KN, KN, ST, KN, SK, SH, QN, AC }, 	 //	 854	 5000
{ KN, KN, KN, QN, TN, KN, KN, KN, KN, TN, KN, SK, SH, AC, TN }, 	 //	 855	 5000
{ KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 856	 5000
{ KN, QN, KN, KN, AC, KN, KN, KN, KN, KN, KN, AC, SH, KN, QN }, 	 //	 857	 5000
{ KN, AC, TN, TN, JA, KN, AC, AC, AC, TN, WN, AC, AC, AC, AC }, 	 //	 858	 5000
{ KN, AC, TN, TN, LO, KN, AC, AC, AC, AC, WN, LO, AC, AC, AC }, 	 //	 859	 5000
{ KN, LO, KN, KN, KN, KN, KN, KN, KN, KN, WN, KN, SH, SK, CR }, 	 //	 860	 5000
{ KN, LO, KN, AC, KN, KN, KN, KN, KN, KN, WN, KN, PF, QN, KN }, 	 //	 861	 5000
{ KN, KN, PF, KN, AC, KN, KN, KN, KN, AC, WN, KN, KN, KN, AC }, 	 //	 862	 5000
{ KN, KN, KN, KN, KN, KN, KN, KN, SK, QN, WN, KN, KN, QN, PF }, 	 //	 863	 5000
{ KN, KN, AC, KN, KN, KN, KN, WN, KN, KN, WN, KN, KN, KN, KN }, 	 //	 864	 5000
{ KN, KN, WN, KN, PF, KN, KN, KN, KN, JA, WN, KN, KN, KN, TN }, 	 //	 865	 5000
{ KN, KN, KN, KN, SK, KN, KN, KN, KN, QN, WN, KN, PF, KN, QN }, 	 //	 866	 5000
{ KN, KN, PF, QN, AC, KN, KN, KN, KN, KN, WN, ST, KN, AC, QN }, 	 //	 867	 5000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, WN, ST, SH, KN, WN }, 	 //	 868	 5000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, WN, ST, SH, SK, CR }, 	 //	 869	 5000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, WN, WN, ST, PF, KN, TN }, 	 //	 870	 5000
{ KN, AC, WN, KN, AC, KN, KN, KN, KN, KN, WN, QN, KN, KN, QN }, 	 //	 871	 5000
{ KN, AC, KN, KN, SK, KN, KN, KN, KN, QN, WN, QN, KN, KN, QN }, 	 //	 872	 5000
{ KN, AC, KN, PF, TN, KN, KN, KN, KN, AC, WN, QN, KN, KN, AC }, 	 //	 873	 5000
{ KN, AC, KN, QN, PF, KN, KN, KN, KN, JA, WN, QN, KN, AC, TN }, 	 //	 874	 5000
{ KN, QN, KN, KN, KN, KN, ST, KN, KN, KN, WN, JA, KN, KN, KN }, 	 //	 875	 5000
{ KN, TN, AC, AC, ST, KN, AC, AC, AC, AC, WN, AC, AC, PF, KN }, 	 //	 876	 5000
{ KN, AC, SH, AC, JA, KN, AC, AC, AC, TN, WN, AC, AC, AC, AC }, 	 //	 877	 5000
{ KN, AC, AC, AC, JA, KN, AC, AC, AC, TN, WN, AC, PF, LO, AC }, 	 //	 878	 5000
{ KN, AC, AC, AC, AC, KN, PF, AC, AC, AC, WN, KN, AC, AC, SK }, 	 //	 879	 5000
{ KN, PF, WN, LO, JA, KN, KN, KN, KN, TN, WN, KN, KN, KN, AC }, 	 //	 880	 5000
{ KN, PF, WN, QN, SK, KN, KN, KN, KN, KN, WN, KN, KN, AC, KN }, 	 //	 881	 5000
{ KN, KN, PF, KN, JA, KN, KN, KN, KN, WN, WN, KN, KN, KN, TN }, 	 //	 882	 5000
{ KN, KN, KN, KN, JA, KN, KN, KN, KN, JA, WN, KN, PF, KN, WN }, 	 //	 883	 5000
{ KN, KN, PF, AC, KN, KN, KN, KN, KN, AC, WN, SK, KN, QN, LO }, 	 //	 884	 5000
{ KN, KN, KN, KN, AC, KN, KN, KN, KN, AC, WN, SK, PF, SK, AC }, 	 //	 885	 5000
{ KN, KN, KN, LO, KN, KN, AC, KN, KN, KN, WN, SH, KN, KN, KN }, 	 //	 886	 5000
{ KN, SH, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC, WN, AC, CR }, 	 //	 887	 5000
{ KN, AC, SH, TN, AC, WN, AC, AC, AC, SK, QN, AC, AC, AC, KN }, 	 //	 888	 5000
{ KN, AC, AC, AC, AC, WN, LO, AC, AC, LO, QN, KN, AC, PF, AC }, 	 //	 889	 5000
{ KN, KN, WN, PF, AC, WN, KN, KN, KN, SK, QN, KN, KN, KN, KN }, 	 //	 890	 5000
{ KN, KN, KN, AC, JA, WN, KN, KN, KN, JA, QN, ST, KN, QN, JA }, 	 //	 891	 5000
{ KN, QN, KN, KN, KN, WN, ST, KN, KN, KN, QN, JA, KN, KN, KN }, 	 //	 892	 5000
{ KN, AC, KN, KN, KN, WN, AC, KN, KN, KN, QN, AC, KN, KN, KN }, 	 //	 893	 5000
{ KN, AC, SH, AC, JA, WN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 894	 5000
{ KN, KN, PF, KN, KN, WN, KN, KN, KN, KN, QN, KN, KN, WN, KN }, 	 //	 895	 5000
{ KN, KN, KN, KN, ST, WN, KN, KN, KN, AC, QN, KN, SH, WN, KN }, 	 //	 896	 5000
{ KN, KN, AC, KN, KN, WN, KN, WN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 897	 5000
{ KN, KN, KN, LO, KN, WN, KN, KN, KN, KN, QN, KN, PF, KN, KN }, 	 //	 898	 5000
{ KN, KN, KN, KN, KN, WN, KN, PF, KN, KN, QN, KN, QN, WN, KN }, 	 //	 899	 5000
{ KN, KN, KN, PF, JA, WN, KN, KN, KN, JA, QN, SK, KN, KN, JA }, 	 //	 900	 5000
{ KN, KN, KN, QN, JA, WN, KN, KN, KN, JA, QN, SK, KN, AC, WN }, 	 //	 901	 5000
{ KN, KN, KN, KN, CR, WN, KN, KN, KN, QN, QN, SK, SH, KN, KN }, 	 //	 902	 5000
{ KN, QN, KN, PF, KN, WN, KN, KN, KN, QN, QN, AC, KN, KN, PF }, 	 //	 903	 5000
{ KN, QN, KN, PF, KN, WN, KN, KN, KN, QN, QN, AC, KN, KN, PF }, 	 //	 904	 5000
{ WN, AC, AC, AC, AC, QN, SH, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 905	 5000
{ WN, AC, AC, AC, KN, QN, AC, AC, AC, AC, KN, LO, PF, AC, LO }, 	 //	 906	 5000
{ WN, LO, KN, KN, PF, QN, KN, KN, KN, JA, KN, KN, KN, SK, TN }, 	 //	 907	 5000
{ WN, KN, KN, KN, WN, QN, KN, KN, KN, TN, KN, ST, KN, KN, TN }, 	 //	 908	 5000
{ WN, KN, KN, KN, WN, QN, KN, KN, KN, TN, KN, ST, KN, WN, TN }, 	 //	 909	 5000
{ WN, JA, KN, KN, KN, QN, JA, KN, KN, KN, KN, SH, KN, KN, KN }, 	 //	 910	 5000
{ WN, TN, KN, KN, KN, QN, TN, KN, KN, KN, KN, WN, KN, KN, KN }, 	 //	 911	 5000
{ WN, TN, AC, AC, QN, QN, AC, AC, AC, KN, KN, AC, AC, PF, AC }, 	 //	 912	 5000
{ WN, AC, KN, PF, SK, QN, PF, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 913	 5000
{ WN, PF, ST, KN, KN, QN, KN, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 914	 5000
{ WN, PF, KN, AC, TN, QN, KN, KN, KN, TN, KN, KN, KN, QN, TN }, 	 //	 915	 5000
{ WN, PF, KN, KN, QN, QN, KN, KN, KN, PF, KN, KN, KN, WN, JA }, 	 //	 916	 5000
{ WN, KN, PF, PF, QN, QN, KN, KN, KN, KN, KN, KN, KN, KN, AC }, 	 //	 917	 5000
{ WN, KN, KN, QN, SK, QN, KN, KN, KN, KN, KN, KN, PF, AC, KN }, 	 //	 918	 5000
{ WN, KN, KN, KN, TN, QN, KN, KN, KN, ST, KN, SK, KN, WN, AC }, 	 //	 919	 5000
{ WN, KN, AC, PF, AC, QN, AC, AC, AC, KN, KN, SH, AC, AC, QN }, 	 //	 920	 5000
{ QN, AC, KN, JA, QN, KN, SH, SH, TN, KN, AC, AC, AC, AC, AC }, 	 //	 921	 5000
{ QN, AC, JA, TN, AC, KN, SH, TN, WN, AC, AC, AC, AC, AC, AC }, 	 //	 922	 5000
{ QN, AC, TN, TN, AC, KN, SH, AC, AC, AC, AC, AC, AC, AC, CR }, 	 //	 923	 5000
{ QN, SH, KN, JA, TN, KN, AC, SH, TN, ST, AC, AC, AC, AC, AC }, 	 //	 924	 5000
{ QN, SH, SH, JA, QN, KN, AC, AC, TN, KN, AC, AC, AC, AC, AC }, 	 //	 925	 5000
{ QN, SH, TN, TN, LO, KN, AC, AC, WN, AC, AC, AC, AC, AC, AC }, 	 //	 926	 5000
{ QN, SH, AC, AC, QN, KN, AC, KN, AC, KN, AC, AC, WN, AC, AC }, 	 //	 927	 5000
{ QN, AC, JA, JA, TN, KN, AC, ST, TN, AC, AC, AC, AC, AC, AC }, 	 //	 928	 5000
{ QN, AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, AC, WN, AC, QN }, 	 //	 929	 5000
{ QN, AC, AC, AC, JA, KN, AC, AC, AC, JA, AC, AC, WN, AC, WN }, 	 //	 930	 5000
{ QN, AC, AC, PF, QN, KN, AC, AC, AC, PF, AC, LO, AC, AC, JA }, 	 //	 931	 5000
{ QN, AC, AC, AC, KN, KN, AC, AC, AC, KN, AC, LO, WN, LO, KN }, 	 //	 932	 5000
{ QN, AC, AC, AC, TN, KN, AC, AC, AC, TN, AC, LO, WN, AC, ST }, 	 //	 933	 5000
{ QN, LO, PF, PF, KN, KN, KN, KN, KN, AC, AC, KN, KN, KN, LO }, 	 //	 934	 5000
{ QN, KN, PF, PF, AC, KN, KN, KN, KN, KN, AC, KN, KN, KN, QN }, 	 //	 935	 5000
{ QN, KN, KN, LO, TN, KN, KN, KN, KN, AC, AC, KN, KN, KN, AC }, 	 //	 936	 5000
{ QN, KN, KN, KN, QN, KN, KN, KN, KN, PF, AC, ST, KN, SK, JA }, 	 //	 937	 5000
{ QN, KN, KN, KN, CR, KN, KN, KN, KN, QN, AC, ST, PF, WN, KN }, 	 //	 938	 5000
{ QN, TN, KN, TN, JA, KN, WN, SH, WN, TN, AC, AC, AC, AC, AC }, 	 //	 939	 5000
{ QN, TN, TN, AC, JA, KN, WN, AC, AC, TN, AC, AC, AC, AC, AC }, 	 //	 940	 5000
{ QN, WN, AC, AC, JA, KN, AC, KN, AC, TN, AC, KN, QN, AC, AC }, 	 //	 941	 5000
{ QN, WN, AC, WN, QN, KN, AC, PF, AC, KN, AC, KN, QN, KN, AC }, 	 //	 942	 5000
{ QN, WN, AC, AC, KN, KN, AC, AC, AC, KN, AC, KN, AC, AC, CR }, 	 //	 943	 5000
{ QN, AC, PF, PF, CR, KN, KN, KN, KN, KN, AC, QN, KN, KN, KN }, 	 //	 944	 5000
{ QN, AC, KN, KN, SK, KN, KN, KN, KN, KN, AC, QN, SH, SK, KN }, 	 //	 945	 5000
{ QN, JA, AC, AC, LO, KN, TN, AC, PF, AC, AC, AC, AC, AC, AC }, 	 //	 946	 5000
{ QN, TN, SH, PF, KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 947	 5000
{ QN, TN, SH, TN, AC, KN, AC, AC, WN, AC, AC, AC, AC, AC, AC }, 	 //	 948	 5000
{ QN, TN, TN, AC, JA, KN, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 949	 5000
{ QN, AC, JA, TN, QN, KN, AC, ST, WN, KN, AC, AC, AC, AC, AC }, 	 //	 950	 5000
{ QN, AC, TN, AC, JA, KN, AC, AC, PF, TN, AC, AC, AC, AC, AC }, 	 //	 951	 5000
{ QN, AC, AC, TN, LO, KN, AC, KN, AC, AC, AC, PF, QN, AC, AC }, 	 //	 952	 5000
{ QN, AC, AC, WN, AC, KN, AC, WN, AC, AC, AC, PF, KN, KN, AC }, 	 //	 953	 5000
{ QN, AC, AC, WN, TN, KN, AC, KN, AC, AC, AC, PF, WN, KN, AC }, 	 //	 954	 5000
{ QN, PF, WN, QN, KN, KN, KN, KN, KN, KN, AC, KN, KN, AC, SK }, 	 //	 955	 5000
{ QN, KN, KN, LO, AC, KN, KN, KN, KN, AC, AC, KN, KN, KN, AC }, 	 //	 956	 5000
{ QN, KN, KN, KN, AC, KN, KN, KN, KN, AC, AC, KN, KN, SK, AC }, 	 //	 957	 5000
{ QN, QN, JA, PF, JA, KN, KN, ST, AC, TN, AC, AC, AC, AC, AC }, 	 //	 958	 5000
{ QN, QN, PF, QN, KN, KN, KN, KN, KN, KN, AC, AC, KN, AC, KN }, 	 //	 959	 5000
{ QN, QN, JA, PF, LO, KN, KN, TN, AC, AC, AC, AC, AC, AC, AC }, 	 //	 960	 5000
{ QN, QN, WN, LO, KN, KN, KN, KN, KN, KN, AC, AC, KN, KN, CR }, 	 //	 961	 5000
{ QN, QN, PF, AC, AC, KN, KN, QN, PF, AC, AC, AC, AC, AC, AC }, 	 //	 962	 5000
{ QN, KN, AC, PF, QN, KN, AC, AC, AC, PF, AC, SH, AC, AC, JA }, 	 //	 963	 5000
{ QN, KN, AC, AC, WN, KN, AC, AC, AC, TN, AC, SH, AC, AC, TN }, 	 //	 964	 5000
{ QN, KN, AC, AC, TN, KN, AC, AC, AC, TN, AC, SH, AC, PF, ST }, 	 //	 965	 5000
{ KN, SH, AC, WN, TN, AC, AC, AC, AC, TN, LO, AC, AC, KN, ST }, 	 //	 966	 5000
{ KN, AC, SH, PF, PF, AC, AC, AC, AC, JA, LO, AC, AC, AC, TN }, 	 //	 967	 5000
{ KN, AC, SH, AC, SH, AC, AC, AC, AC, JA, LO, AC, AC, AC, JA }, 	 //	 968	 5000
{ KN, AC, AC, AC, QN, AC, AC, AC, AC, PF, LO, AC, PF, AC, JA }, 	 //	 969	 5000
{ KN, AC, KN, KN, KN, AC, AC, KN, KN, KN, LO, LO, KN, KN, KN }, 	 //	 970	 5000
{ KN, AC, AC, WN, QN, AC, AC, AC, AC, SH, LO, LO, AC, KN, JA }, 	 //	 971	 5000
{ KN, AC, AC, WN, TN, AC, AC, AC, AC, TN, LO, LO, AC, KN, TN }, 	 //	 972	 5000
{ KN, LO, PF, KN, AC, AC, KN, KN, KN, SK, LO, KN, KN, KN, KN }, 	 //	 973	 5000
{ KN, LO, KN, PF, QN, AC, KN, KN, KN, PF, LO, KN, KN, KN, JA }, 	 //	 974	 5000
{ KN, KN, KN, AC, QN, AC, KN, KN, KN, SH, LO, KN, KN, QN, JA }, 	 //	 975	 5000
{ KN, KN, KN, AC, KN, AC, KN, KN, KN, KN, LO, ST, SH, QN, KN }, 	 //	 976	 5000
{ KN, KN, KN, PF, AC, AC, KN, KN, KN, AC, LO, ST, KN, KN, SK }, 	 //	 977	 5000
{ KN, WN, AC, PF, KN, AC, AC, AC, AC, KN, LO, KN, AC, AC, KN }, 	 //	 978	 5000
{ KN, WN, AC, KN, QN, AC, AC, AC, AC, QN, LO, KN, AC, PF, SH }, 	 //	 979	 5000
{ KN, AC, WN, LO, CR, AC, KN, KN, KN, KN, LO, QN, KN, KN, KN }, 	 //	 980	 5000
{ KN, TN, SH, TN, KN, AC, AC, AC, AC, SK, LO, AC, AC, AC, QN }, 	 //	 981	 5000
{ KN, TN, SH, TN, JA, AC, AC, AC, AC, JA, LO, AC, AC, AC, WN }, 	 //	 982	 5000
{ KN, AC, TN, PF, JA, AC, AC, AC, AC, WN, LO, AC, AC, AC, TN }, 	 //	 983	 5000
{ KN, AC, TN, TN, CR, AC, AC, AC, AC, QN, LO, AC, AC, AC, KN }, 	 //	 984	 5000
{ KN, AC, AC, AC, TN, AC, AC, AC, PF, AC, LO, AC, AC, AC, AC }, 	 //	 985	 5000
{ KN, AC, AC, AC, QN, AC, AC, AC, AC, SH, LO, AC, WN, AC, JA }, 	 //	 986	 5000
{ KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, PF, PF, AC, KN }, 	 //	 987	 5000
{ KN, AC, TN, AC, TN, AC, AC, AC, AC, ST, LO, PF, AC, AC, AC }, 	 //	 988	 5000
{ KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, PF, WN, PF, KN }, 	 //	 989	 5000
{ KN, PF, KN, KN, AC, AC, KN, KN, KN, AC, LO, KN, KN, KN, SK }, 	 //	 990	 5000
{ KN, KN, KN, KN, KN, AC, KN, WN, KN, KN, LO, KN, TN, SK, KN }, 	 //	 991	 5000
{ KN, KN, KN, QN, SK, AC, KN, KN, KN, KN, LO, SK, SH, AC, KN }, 	 //	 992	 5000
{ KN, KN, KN, PF, QN, AC, KN, KN, KN, QN, LO, SK, KN, KN, QN }, 	 //	 993	 5000
{ KN, KN, AC, AC, SK, AC, AC, AC, AC, QN, LO, SH, AC, PF, QN }, 	 //	 994	 5000
{ KN, KN, AC, AC, AC, AC, AC, AC, AC, KN, LO, SH, PF, AC, QN }, 	 //	 995	 5000
{ KN, KN, AC, KN, KN, AC, AC, AC, AC, KN, LO, SH, AC, PF, CR }, 	 //	 996	 5000
