#include "ReelDefine.h"

unsigned char L5_Outcome_4000[1000][15]={	 //	 0	 4000
{ AC, SH, JA, AC, KN, LO, AC, ST, AC, KN, AC, AC, AC, AC, CR }, 	 //	 1	 4000
{ AC, SH, KN, KN, CR, LO, AC, SH, KN, QN, AC, AC, AC, KN, KN }, 	 //	 2	 4000
{ AC, SH, JA, AC, KN, LO, AC, TN, AC, KN, AC, AC, AC, AC, CR }, 	 //	 3	 4000
{ AC, AC, JA, AC, PF, LO, AC, TN, AC, JA, AC, AC, AC, AC, TN }, 	 //	 4	 4000
{ AC, AC, AC, AC, JA, LO, AC, WN, AC, JA, AC, AC, KN, PF, JA }, 	 //	 5	 4000
{ AC, AC, AC, LO, KN, LO, AC, KN, KN, KN, AC, AC, WN, KN, SK }, 	 //	 6	 4000
{ AC, AC, AC, AC, PF, LO, AC, KN, AC, JA, AC, AC, WN, PF, TN }, 	 //	 7	 4000
{ AC, AC, AC, AC, JA, LO, AC, KN, AC, WN, AC, LO, QN, AC, TN }, 	 //	 8	 4000
{ AC, AC, AC, KN, KN, LO, AC, KN, KN, KN, AC, LO, WN, SK, KN }, 	 //	 9	 4000
{ AC, AC, AC, AC, CR, LO, LO, WN, LO, QN, AC, KN, KN, KN, KN }, 	 //	 10	 4000
{ AC, LO, KN, KN, QN, LO, KN, KN, KN, SH, AC, KN, KN, KN, JA }, 	 //	 11	 4000
{ AC, KN, KN, KN, KN, LO, QN, KN, KN, KN, AC, ST, PF, KN, KN }, 	 //	 12	 4000
{ AC, TN, KN, LO, KN, LO, AC, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 13	 4000
{ AC, AC, JA, PF, JA, LO, AC, ST, AC, JA, AC, AC, AC, AC, WN }, 	 //	 14	 4000
{ AC, AC, AC, AC, CR, LO, AC, KN, AC, KN, AC, AC, QN, PF, KN }, 	 //	 15	 4000
{ AC, AC, AC, AC, QN, LO, AC, PF, KN, QN, AC, AC, QN, QN, QN }, 	 //	 16	 4000
{ AC, AC, AC, AC, KN, LO, AC, KN, AC, SK, AC, PF, QN, PF, QN }, 	 //	 17	 4000
{ AC, AC, AC, AC, TN, LO, AC, KN, AC, TN, AC, PF, WN, PF, TN }, 	 //	 18	 4000
{ AC, PF, PF, KN, KN, LO, KN, KN, KN, QN, AC, KN, KN, KN, PF }, 	 //	 19	 4000
{ AC, PF, WN, KN, KN, LO, KN, KN, KN, AC, AC, KN, KN, KN, LO }, 	 //	 20	 4000
{ AC, PF, KN, KN, PF, LO, KN, KN, KN, JA, AC, KN, KN, KN, TN }, 	 //	 21	 4000
{ AC, KN, PF, QN, KN, LO, KN, KN, KN, KN, AC, KN, KN, AC, SK }, 	 //	 22	 4000
{ AC, KN, KN, KN, SH, LO, KN, KN, KN, JA, AC, SK, KN, SK, JA }, 	 //	 23	 4000
{ AC, KN, AC, AC, AC, LO, AC, KN, KN, KN, AC, SH, WN, QN, QN }, 	 //	 24	 4000
{ LO, SH, KN, AC, AC, AC, AC, SH, AC, KN, AC, AC, AC, AC, QN }, 	 //	 25	 4000
{ LO, SH, AC, KN, JA, AC, AC, AC, AC, JA, AC, AC, WN, PF, JA }, 	 //	 26	 4000
{ LO, AC, AC, WN, JA, AC, AC, AC, AC, JA, AC, AC, PF, KN, JA }, 	 //	 27	 4000
{ LO, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, LO, PF, AC, PF }, 	 //	 28	 4000
{ LO, AC, AC, KN, QN, AC, AC, AC, AC, PF, AC, LO, PF, PF, JA }, 	 //	 29	 4000
{ LO, LO, PF, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, SK, KN }, 	 //	 30	 4000
{ LO, LO, KN, KN, QN, AC, KN, KN, KN, PF, AC, KN, KN, KN, JA }, 	 //	 31	 4000
{ LO, LO, QN, LO, KN, AC, KN, AC, KN, KN, AC, KN, KN, KN, KN }, 	 //	 32	 4000
{ LO, KN, WN, KN, KN, AC, KN, KN, KN, QN, AC, KN, KN, KN, PF }, 	 //	 33	 4000
{ LO, AC, WN, KN, CR, AC, KN, KN, KN, KN, AC, QN, KN, KN, KN }, 	 //	 34	 4000
{ LO, AC, KN, AC, ST, AC, KN, KN, KN, AC, AC, QN, KN, QN, KN }, 	 //	 35	 4000
{ LO, JA, KN, KN, KN, AC, TN, KN, KN, KN, AC, AC, KN, WN, KN }, 	 //	 36	 4000
{ LO, TN, KN, PF, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 37	 4000
{ LO, AC, AC, WN, QN, AC, AC, AC, AC, SH, AC, AC, PF, KN, JA }, 	 //	 38	 4000
{ LO, AC, AC, PF, SH, AC, AC, AC, AC, JA, AC, AC, WN, AC, JA }, 	 //	 39	 4000
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, PF, WN, AC, KN }, 	 //	 40	 4000
{ LO, AC, AC, WN, JA, AC, AC, AC, AC, JA, AC, PF, WN, KN, JA }, 	 //	 41	 4000
{ LO, AC, KN, PF, CR, AC, PF, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 42	 4000
{ LO, PF, WN, QN, KN, AC, KN, KN, KN, KN, AC, KN, KN, AC, SK }, 	 //	 43	 4000
{ LO, PF, KN, QN, KN, AC, KN, KN, KN, AC, AC, KN, KN, AC, LO }, 	 //	 44	 4000
{ LO, PF, QN, PF, KN, AC, KN, AC, KN, KN, AC, KN, KN, KN, KN }, 	 //	 45	 4000
{ LO, KN, KN, LO, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN, AC }, 	 //	 46	 4000
{ LO, KN, WN, KN, KN, AC, KN, KN, KN, KN, AC, SK, KN, SK, KN }, 	 //	 47	 4000
{ LO, KN, KN, KN, QN, AC, KN, KN, KN, QN, AC, SK, KN, KN, SH }, 	 //	 48	 4000
{ LO, KN, KN, KN, JA, AC, KN, KN, KN, TN, AC, SK, KN, KN, AC }, 	 //	 49	 4000
{ LO, SK, KN, PF, SK, AC, QN, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 50	 4000
{ LO, SK, KN, KN, KN, AC, QN, KN, KN, KN, AC, KN, KN, KN, CR }, 	 //	 51	 4000
{ LO, KN, KN, KN, KN, AC, AC, KN, KN, KN, AC, SH, SH, KN, KN }, 	 //	 52	 4000
{ LO, KN, AC, WN, KN, AC, AC, AC, AC, KN, AC, SH, WN, KN, KN }, 	 //	 53	 4000
{ AC, SH, KN, PF, JA, AC, AC, SH, AC, JA, AC, AC, AC, AC, JA }, 	 //	 54	 4000
{ AC, AC, KN, KN, SK, AC, AC, SH, KN, KN, AC, AC, AC, KN, KN }, 	 //	 55	 4000
{ AC, AC, JA, AC, JA, AC, AC, TN, AC, JA, AC, AC, AC, AC, WN }, 	 //	 56	 4000
{ AC, AC, AC, KN, SK, AC, AC, KN, KN, KN, AC, AC, WN, SK, KN }, 	 //	 57	 4000
{ AC, LO, KN, LO, TN, AC, KN, KN, KN, ST, AC, KN, KN, KN, AC }, 	 //	 58	 4000
{ AC, LO, KN, KN, QN, AC, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 59	 4000
{ AC, KN, KN, KN, KN, AC, KN, WN, KN, KN, AC, KN, TN, KN, KN }, 	 //	 60	 4000
{ AC, KN, KN, AC, SK, AC, KN, KN, KN, KN, AC, ST, PF, QN, KN }, 	 //	 61	 4000
{ AC, TN, KN, KN, KN, AC, TN, KN, KN, KN, AC, WN, KN, SK, KN }, 	 //	 62	 4000
{ AC, WN, SH, AC, QN, AC, AC, AC, AC, PF, AC, KN, AC, LO, JA }, 	 //	 63	 4000
{ AC, WN, SH, KN, JA, AC, AC, AC, AC, JA, AC, KN, AC, PF, WN }, 	 //	 64	 4000
{ AC, WN, TN, AC, JA, AC, AC, AC, AC, WN, AC, KN, AC, PF, TN }, 	 //	 65	 4000
{ AC, TN, JA, PF, KN, AC, AC, TN, AC, SK, AC, AC, AC, AC, QN }, 	 //	 66	 4000
{ AC, AC, AC, AC, SK, AC, AC, KN, AC, QN, AC, AC, QN, LO, QN }, 	 //	 67	 4000
{ AC, AC, AC, LO, CR, AC, AC, KN, KN, KN, AC, AC, QN, KN, KN }, 	 //	 68	 4000
{ AC, AC, KN, AC, KN, AC, AC, SH, AC, KN, AC, AC, AC, AC, KN }, 	 //	 69	 4000
{ AC, AC, JA, AC, QN, AC, AC, TN, AC, QN, AC, AC, AC, AC, SH }, 	 //	 70	 4000
{ AC, AC, KN, LO, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 71	 4000
{ AC, AC, AC, AC, KN, AC, AC, KN, AC, KN, AC, PF, QN, AC, KN }, 	 //	 72	 4000
{ AC, AC, AC, AC, QN, AC, AC, KN, AC, QN, AC, PF, QN, AC, QN }, 	 //	 73	 4000
{ AC, AC, AC, AC, JA, AC, AC, PF, AC, JA, AC, PF, QN, AC, JA }, 	 //	 74	 4000
{ AC, AC, AC, AC, SK, AC, AC, PF, AC, QN, AC, PF, QN, PF, QN }, 	 //	 75	 4000
{ AC, AC, TN, AC, QN, AC, AC, AC, AC, KN, AC, PF, AC, PF, AC }, 	 //	 76	 4000
{ AC, AC, AC, AC, KN, AC, AC, WN, AC, QN, AC, PF, KN, AC, PF }, 	 //	 77	 4000
{ AC, AC, AC, AC, CR, AC, PF, WN, PF, KN, AC, KN, KN, KN, KN }, 	 //	 78	 4000
{ AC, KN, PF, LO, AC, AC, KN, KN, KN, SK, AC, KN, KN, KN, KN }, 	 //	 79	 4000
{ AC, KN, KN, LO, CR, AC, KN, KN, KN, KN, AC, KN, SH, KN, KN }, 	 //	 80	 4000
{ AC, KN, KN, LO, QN, AC, KN, KN, KN, KN, AC, SK, KN, KN, AC }, 	 //	 81	 4000
{ AC, KN, KN, KN, AC, AC, KN, KN, KN, AC, AC, SK, KN, KN, AC }, 	 //	 82	 4000
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, TN, AC, SH, PF, PF, TN }, 	 //	 83	 4000
{ AC, KN, TN, AC, KN, AC, AC, AC, AC, QN, AC, SH, AC, PF, PF }, 	 //	 84	 4000
{ AC, SH, SH, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, PF, SK }, 	 //	 85	 4000
{ AC, AC, JA, TN, TN, AC, AC, ST, AC, AC, ST, AC, AC, AC, AC }, 	 //	 86	 4000
{ AC, AC, KN, TN, LO, AC, AC, SH, AC, AC, ST, AC, AC, AC, AC }, 	 //	 87	 4000
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, PF, KN }, 	 //	 88	 4000
{ AC, AC, SH, AC, SK, AC, AC, AC, AC, KN, ST, AC, AC, PF, KN }, 	 //	 89	 4000
{ AC, AC, SH, TN, CR, AC, AC, AC, AC, KN, ST, LO, AC, AC, KN }, 	 //	 90	 4000
{ AC, LO, KN, QN, AC, AC, KN, KN, KN, SK, ST, KN, KN, AC, KN }, 	 //	 91	 4000
{ AC, KN, KN, PF, TN, AC, KN, KN, KN, AC, ST, KN, KN, KN, AC }, 	 //	 92	 4000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, QN, ST, KN, SH, KN, PF }, 	 //	 93	 4000
{ AC, KN, PF, KN, KN, AC, KN, KN, KN, KN, ST, ST, KN, WN, SK }, 	 //	 94	 4000
{ AC, AC, PF, KN, KN, AC, KN, KN, KN, KN, ST, QN, KN, KN, CR }, 	 //	 95	 4000
{ AC, AC, KN, KN, QN, AC, KN, KN, KN, KN, ST, QN, KN, KN, AC }, 	 //	 96	 4000
{ AC, AC, KN, AC, CR, AC, KN, KN, KN, QN, ST, QN, KN, QN, KN }, 	 //	 97	 4000
{ AC, KN, KN, LO, KN, AC, QN, KN, KN, KN, ST, ST, KN, KN, KN }, 	 //	 98	 4000
{ AC, AC, SH, WN, SH, AC, AC, AC, AC, JA, ST, AC, AC, KN, JA }, 	 //	 99	 4000
{ AC, AC, JA, AC, TN, AC, AC, TN, AC, ST, ST, AC, AC, AC, AC }, 	 //	 100	 4000
{ AC, AC, TN, AC, SH, AC, AC, AC, AC, JA, ST, AC, AC, LO, JA }, 	 //	 101	 4000
{ AC, AC, TN, WN, SH, AC, AC, AC, AC, JA, ST, AC, AC, KN, JA }, 	 //	 102	 4000
{ AC, AC, SH, PF, KN, AC, AC, AC, AC, KN, ST, PF, AC, AC, CR }, 	 //	 103	 4000
{ AC, AC, TN, TN, QN, AC, AC, AC, AC, QN, ST, PF, AC, AC, SH }, 	 //	 104	 4000
{ AC, AC, AC, AC, TN, AC, AC, WN, AC, ST, ST, PF, KN, AC, AC }, 	 //	 105	 4000
{ AC, PF, ST, KN, KN, AC, KN, AC, KN, KN, ST, KN, KN, KN, KN }, 	 //	 106	 4000
{ AC, PF, QN, KN, KN, AC, KN, AC, KN, KN, ST, KN, KN, KN, KN }, 	 //	 107	 4000
{ AC, KN, KN, QN, CR, AC, KN, KN, KN, QN, ST, SK, KN, AC, KN }, 	 //	 108	 4000
{ AC, KN, SH, TN, JA, AC, AC, AC, AC, JA, ST, SH, AC, AC, WN }, 	 //	 109	 4000
{ AC, SH, JA, TN, TN, ST, AC, TN, AC, ST, KN, AC, AC, AC, AC }, 	 //	 110	 4000
{ AC, SH, AC, KN, AC, ST, AC, AC, AC, AC, KN, AC, WN, PF, AC }, 	 //	 111	 4000
{ AC, AC, KN, PF, AC, ST, LO, KN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 112	 4000
{ AC, LO, AC, KN, AC, ST, KN, WN, KN, SK, KN, KN, KN, KN, KN }, 	 //	 113	 4000
{ AC, LO, WN, PF, SK, ST, KN, KN, KN, QN, KN, KN, KN, KN, QN }, 	 //	 114	 4000
{ AC, KN, QN, PF, KN, ST, KN, PF, KN, KN, KN, KN, KN, KN, CR }, 	 //	 115	 4000
{ AC, KN, KN, QN, AC, ST, KN, KN, KN, SK, KN, KN, SH, AC, KN }, 	 //	 116	 4000
{ AC, KN, AC, LO, KN, ST, KN, WN, KN, SK, KN, KN, KN, KN, QN }, 	 //	 117	 4000
{ AC, KN, AC, LO, SK, ST, KN, WN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 118	 4000
{ AC, KN, KN, KN, CR, ST, KN, PF, KN, QN, KN, KN, QN, SK, KN }, 	 //	 119	 4000
{ AC, KN, KN, AC, JA, ST, KN, KN, KN, TN, KN, ST, KN, QN, AC }, 	 //	 120	 4000
{ AC, KN, KN, PF, AC, ST, KN, KN, KN, SK, KN, ST, PF, KN, KN }, 	 //	 121	 4000
{ AC, WN, ST, WN, KN, ST, AC, AC, AC, AC, KN, KN, KN, KN, LO }, 	 //	 122	 4000
{ AC, AC, KN, PF, CR, ST, KN, KN, KN, QN, KN, QN, SH, KN, KN }, 	 //	 123	 4000
{ AC, AC, KN, AC, AC, ST, KN, KN, KN, SK, KN, QN, PF, QN, KN }, 	 //	 124	 4000
{ AC, AC, KN, KN, CR, ST, KN, KN, KN, QN, KN, QN, PF, SK, KN }, 	 //	 125	 4000
{ AC, AC, JA, TN, LO, ST, AC, ST, AC, AC, KN, AC, AC, AC, AC }, 	 //	 126	 4000
{ AC, PF, KN, PF, AC, ST, KN, KN, KN, SK, KN, KN, SH, KN, KN }, 	 //	 127	 4000
{ AC, PF, AC, AC, AC, ST, KN, WN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 128	 4000
{ AC, KN, PF, LO, JA, ST, KN, KN, KN, TN, KN, KN, KN, KN, AC }, 	 //	 129	 4000
{ AC, KN, PF, KN, TN, ST, KN, KN, KN, TN, KN, KN, KN, KN, TN }, 	 //	 130	 4000
{ AC, KN, WN, KN, AC, ST, KN, KN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 131	 4000
{ AC, KN, KN, WN, SK, ST, KN, KN, AC, KN, KN, KN, KN, KN, KN }, 	 //	 132	 4000
{ AC, KN, KN, KN, AC, ST, KN, QN, KN, SK, KN, SK, PF, KN, KN }, 	 //	 133	 4000
{ AC, KN, PF, LO, KN, ST, KN, KN, KN, KN, KN, SK, KN, KN, CR }, 	 //	 134	 4000
{ AC, KN, KN, KN, SK, ST, KN, KN, KN, QN, KN, SK, SH, KN, QN }, 	 //	 135	 4000
{ AC, KN, KN, KN, JA, ST, KN, KN, KN, JA, KN, SK, PF, KN, WN }, 	 //	 136	 4000
{ AC, SK, AC, AC, AC, ST, QN, WN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 137	 4000
{ AC, QN, KN, AC, AC, ST, KN, KN, KN, AC, KN, AC, KN, QN, SK }, 	 //	 138	 4000
{ AC, QN, KN, QN, SH, ST, KN, KN, KN, JA, KN, AC, KN, AC, JA }, 	 //	 139	 4000
{ AC, QN, KN, QN, AC, ST, KN, KN, KN, AC, KN, AC, KN, AC, CR }, 	 //	 140	 4000
{ AC, QN, KN, KN, KN, ST, KN, KN, KN, QN, KN, AC, PF, KN, PF }, 	 //	 141	 4000
{ AC, KN, KN, KN, KN, ST, AC, KN, KN, KN, KN, SH, SH, WN, KN }, 	 //	 142	 4000
{ ST, SH, AC, TN, AC, KN, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 143	 4000
{ ST, AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, CR }, 	 //	 144	 4000
{ ST, LO, WN, AC, AC, KN, KN, KN, KN, SK, KN, KN, KN, QN, KN }, 	 //	 145	 4000
{ ST, KN, KN, SK, TN, KN, KN, KN, QN, AC, KN, KN, KN, KN, AC }, 	 //	 146	 4000
{ ST, KN, AC, AC, AC, KN, KN, WN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 147	 4000
{ ST, KN, WN, WN, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, KN }, 	 //	 148	 4000
{ ST, KN, KN, SK, KN, KN, KN, KN, QN, QN, KN, KN, KN, KN, PF }, 	 //	 149	 4000
{ ST, KN, KN, PF, AC, KN, KN, KN, KN, AC, KN, KN, PF, KN, AC }, 	 //	 150	 4000
{ ST, KN, AC, AC, AC, KN, KN, KN, AC, AC, KN, ST, WN, AC, AC }, 	 //	 151	 4000
{ ST, QN, KN, KN, KN, KN, SK, KN, KN, KN, KN, JA, KN, WN, KN }, 	 //	 152	 4000
{ ST, AC, KN, KN, JA, KN, KN, KN, KN, WN, KN, QN, SH, KN, TN }, 	 //	 153	 4000
{ ST, PF, PF, QN, AC, KN, KN, KN, KN, AC, KN, KN, KN, AC, SK }, 	 //	 154	 4000
{ ST, PF, KN, KN, QN, KN, KN, KN, KN, PF, KN, KN, SH, KN, JA }, 	 //	 155	 4000
{ ST, PF, KN, AC, AC, KN, KN, KN, KN, AC, KN, KN, PF, QN, SK }, 	 //	 156	 4000
{ ST, KN, KN, KN, KN, KN, KN, KN, SK, QN, KN, KN, SH, QN, PF }, 	 //	 157	 4000
{ ST, KN, WN, AC, TN, KN, KN, KN, KN, AC, KN, KN, KN, QN, AC }, 	 //	 158	 4000
{ ST, KN, KN, KN, JA, KN, KN, KN, WN, JA, KN, KN, KN, QN, WN }, 	 //	 159	 4000
{ ST, KN, KN, AC, AC, KN, KN, KN, PF, AC, KN, KN, KN, KN, SK }, 	 //	 160	 4000
{ ST, KN, KN, KN, KN, KN, KN, KN, QN, KN, KN, SK, KN, ST, CR }, 	 //	 161	 4000
{ ST, KN, KN, KN, KN, KN, KN, KN, SK, KN, KN, SK, KN, QN, CR }, 	 //	 162	 4000
{ ST, KN, KN, KN, AC, KN, KN, PF, KN, SK, KN, SK, QN, KN, KN }, 	 //	 163	 4000
{ ST, SK, KN, QN, KN, KN, QN, KN, KN, KN, KN, KN, KN, AC, KN }, 	 //	 164	 4000
{ ST, QN, KN, PF, JA, KN, KN, KN, KN, JA, KN, AC, PF, KN, WN }, 	 //	 165	 4000
{ KN, AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, SK }, 	 //	 166	 4000
{ KN, LO, ST, AC, SK, KN, KN, AC, PF, KN, KN, KN, KN, KN, KN }, 	 //	 167	 4000
{ KN, LO, ST, PF, TN, KN, KN, AC, KN, TN, KN, KN, KN, KN, ST }, 	 //	 168	 4000
{ KN, LO, ST, KN, JA, KN, KN, AC, KN, TN, KN, KN, KN, KN, AC }, 	 //	 169	 4000
{ KN, LO, PF, AC, PF, KN, KN, KN, LO, JA, KN, KN, KN, KN, TN }, 	 //	 170	 4000
{ KN, LO, KN, QN, TN, KN, KN, KN, QN, TN, KN, KN, KN, SK, ST }, 	 //	 171	 4000
{ KN, LO, KN, TN, AC, KN, KN, KN, TN, SK, KN, KN, KN, TN, KN }, 	 //	 172	 4000
{ KN, LO, KN, JA, KN, KN, KN, KN, TN, KN, KN, KN, KN, AC, KN }, 	 //	 173	 4000
{ KN, LO, KN, AC, QN, KN, KN, KN, KN, QN, KN, KN, SH, QN, SH }, 	 //	 174	 4000
{ KN, LO, KN, AC, AC, KN, KN, KN, KN, AC, KN, KN, SH, QN, AC }, 	 //	 175	 4000
{ KN, LO, AC, KN, AC, KN, KN, WN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 176	 4000
{ KN, LO, KN, JA, JA, KN, KN, KN, JA, WN, KN, KN, KN, JA, TN }, 	 //	 177	 4000
{ KN, LO, KN, JA, AC, KN, KN, KN, JA, LO, KN, KN, KN, SH, AC }, 	 //	 178	 4000
{ KN, LO, QN, KN, TN, KN, KN, AC, KN, AC, KN, KN, KN, KN, AC }, 	 //	 179	 4000
{ KN, KN, ST, SK, CR, KN, KN, AC, QN, KN, KN, KN, KN, KN, KN }, 	 //	 180	 4000
{ KN, KN, KN, KN, AC, KN, KN, QN, KN, AC, KN, KN, PF, KN, AC }, 	 //	 181	 4000
{ KN, KN, KN, KN, CR, KN, KN, KN, WN, KN, KN, KN, PF, QN, KN }, 	 //	 182	 4000
{ KN, KN, KN, KN, QN, KN, KN, KN, WN, PF, KN, KN, PF, QN, JA }, 	 //	 183	 4000
{ KN, KN, PF, KN, AC, KN, KN, KN, KN, AC, KN, ST, KN, WN, SK }, 	 //	 184	 4000
{ KN, KN, KN, JA, TN, KN, KN, KN, JA, ST, KN, ST, KN, SH, AC }, 	 //	 185	 4000
{ KN, KN, KN, KN, ST, KN, KN, KN, AC, AC, KN, ST, SH, PF, KN }, 	 //	 186	 4000
{ KN, KN, KN, KN, JA, KN, KN, SH, KN, JA, KN, ST, AC, WN, JA }, 	 //	 187	 4000
{ KN, KN, WN, LO, TN, KN, KN, KN, KN, TN, KN, ST, KN, KN, TN }, 	 //	 188	 4000
{ KN, KN, KN, PF, JA, KN, KN, KN, AC, TN, KN, ST, KN, AC, AC }, 	 //	 189	 4000
{ KN, KN, KN, QN, KN, KN, KN, KN, SK, QN, KN, ST, KN, JA, PF }, 	 //	 190	 4000
{ KN, KN, KN, SH, AC, KN, KN, KN, TN, SK, KN, ST, KN, TN, KN }, 	 //	 191	 4000
{ KN, KN, KN, SH, KN, KN, KN, KN, TN, AC, KN, ST, KN, TN, LO }, 	 //	 192	 4000
{ KN, KN, KN, TN, AC, KN, KN, KN, AC, AC, KN, ST, KN, AC, AC }, 	 //	 193	 4000
{ KN, KN, KN, AC, ST, KN, KN, KN, AC, AC, KN, ST, KN, AC, KN }, 	 //	 194	 4000
{ KN, KN, KN, KN, KN, KN, ST, KN, KN, AC, KN, QN, KN, KN, LO }, 	 //	 195	 4000
{ KN, WN, SH, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, LO, SK }, 	 //	 196	 4000
{ KN, AC, PF, KN, CR, KN, KN, KN, KN, QN, KN, QN, KN, SK, KN }, 	 //	 197	 4000
{ KN, AC, KN, AC, KN, KN, KN, KN, PF, KN, KN, QN, KN, KN, KN }, 	 //	 198	 4000
{ KN, AC, WN, AC, SK, KN, KN, KN, KN, QN, KN, QN, KN, QN, QN }, 	 //	 199	 4000
{ KN, AC, KN, KN, QN, KN, KN, KN, KN, PF, KN, QN, PF, WN, JA }, 	 //	 200	 4000
{ KN, AC, KN, AC, QN, KN, KN, KN, KN, SH, KN, QN, PF, QN, JA }, 	 //	 201	 4000
{ KN, KN, KN, KN, KN, KN, QN, PF, KN, KN, KN, ST, QN, WN, KN }, 	 //	 202	 4000
{ KN, AC, AC, PF, TN, KN, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 203	 4000
{ KN, AC, PF, KN, KN, KN, PF, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 204	 4000
{ KN, PF, KN, AC, KN, KN, KN, KN, AC, QN, KN, KN, KN, LO, PF }, 	 //	 205	 4000
{ KN, PF, KN, QN, KN, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN }, 	 //	 206	 4000
{ KN, PF, KN, SK, QN, KN, KN, KN, JA, KN, KN, KN, KN, JA, AC }, 	 //	 207	 4000
{ KN, PF, KN, TN, CR, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN }, 	 //	 208	 4000
{ KN, PF, KN, AC, QN, KN, KN, KN, KN, PF, KN, KN, SH, QN, JA }, 	 //	 209	 4000
{ KN, PF, KN, PF, AC, KN, KN, SH, AC, AC, KN, KN, AC, AC, AC }, 	 //	 210	 4000
{ KN, PF, AC, KN, TN, KN, KN, WN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 211	 4000
{ KN, PF, KN, WN, QN, KN, KN, KN, QN, QN, KN, KN, KN, QN, QN }, 	 //	 212	 4000
{ KN, PF, KN, QN, AC, KN, KN, KN, QN, LO, KN, KN, KN, SK, AC }, 	 //	 213	 4000
{ KN, PF, KN, SK, AC, KN, KN, KN, JA, AC, KN, KN, KN, JA, AC }, 	 //	 214	 4000
{ KN, PF, KN, TN, AC, KN, KN, KN, TN, AC, KN, KN, KN, TN, AC }, 	 //	 215	 4000
{ KN, PF, KN, AC, CR, KN, KN, KN, AC, QN, KN, KN, KN, AC, KN }, 	 //	 216	 4000
{ KN, PF, KN, KN, SH, KN, KN, KN, KN, JA, KN, KN, PF, KN, JA }, 	 //	 217	 4000
{ KN, PF, KN, KN, JA, KN, KN, KN, KN, WN, KN, KN, PF, KN, TN }, 	 //	 218	 4000
{ KN, KN, KN, KN, TN, KN, KN, WN, KN, TN, KN, KN, TN, KN, TN }, 	 //	 219	 4000
{ KN, KN, KN, KN, TN, KN, KN, QN, KN, TN, KN, KN, PF, SK, TN }, 	 //	 220	 4000
{ KN, KN, PF, WN, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, CR }, 	 //	 221	 4000
{ KN, KN, KN, KN, TN, KN, KN, KN, QN, TN, KN, KN, PF, ST, ST }, 	 //	 222	 4000
{ KN, KN, KN, KN, AC, KN, KN, KN, AC, LO, KN, KN, PF, PF, AC }, 	 //	 223	 4000
{ KN, KN, KN, KN, AC, KN, KN, PF, KN, AC, KN, KN, QN, SK, AC }, 	 //	 224	 4000
{ KN, KN, AC, AC, AC, KN, KN, KN, AC, LO, KN, KN, WN, AC, AC }, 	 //	 225	 4000
{ KN, KN, KN, KN, KN, KN, KN, WN, AC, AC, KN, SK, TN, PF, LO }, 	 //	 226	 4000
{ KN, KN, KN, KN, TN, KN, KN, QN, KN, ST, KN, SK, PF, SK, AC }, 	 //	 227	 4000
{ KN, KN, KN, AC, QN, KN, KN, KN, AC, QN, KN, SK, KN, LO, QN }, 	 //	 228	 4000
{ KN, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, SK, KN, LO, CR }, 	 //	 229	 4000
{ KN, KN, KN, PF, SK, KN, KN, SH, KN, KN, KN, SK, AC, KN, KN }, 	 //	 230	 4000
{ KN, KN, WN, KN, TN, KN, KN, KN, KN, ST, KN, SK, KN, KN, AC }, 	 //	 231	 4000
{ KN, KN, WN, KN, QN, KN, KN, KN, KN, SH, KN, SK, KN, SK, JA }, 	 //	 232	 4000
{ KN, KN, KN, AC, KN, KN, KN, KN, PF, KN, KN, SK, KN, AC, CR }, 	 //	 233	 4000
{ KN, KN, KN, PF, AC, KN, KN, KN, AC, KN, KN, SK, KN, AC, QN }, 	 //	 234	 4000
{ KN, KN, KN, JA, LO, KN, KN, KN, JA, AC, KN, SK, KN, JA, AC }, 	 //	 235	 4000
{ KN, KN, KN, SH, KN, KN, KN, KN, TN, QN, KN, SK, KN, TN, PF }, 	 //	 236	 4000
{ KN, KN, KN, TN, TN, KN, KN, KN, TN, TN, KN, SK, KN, TN, TN }, 	 //	 237	 4000
{ KN, KN, KN, TN, AC, KN, KN, KN, WN, LO, KN, SK, KN, AC, AC }, 	 //	 238	 4000
{ KN, KN, KN, ST, SH, KN, KN, KN, JA, JA, KN, SK, KN, TN, JA }, 	 //	 239	 4000
{ KN, KN, KN, TN, AC, KN, KN, KN, AC, AC, KN, SK, KN, AC, AC }, 	 //	 240	 4000
{ KN, KN, KN, KN, KN, KN, KN, PF, AC, QN, KN, SK, QN, PF, PF }, 	 //	 241	 4000
{ KN, KN, KN, KN, KN, KN, SK, SH, KN, KN, KN, QN, AC, SK, KN }, 	 //	 242	 4000
{ KN, QN, PF, KN, SH, KN, KN, KN, KN, JA, KN, AC, KN, KN, JA }, 	 //	 243	 4000
{ KN, QN, PF, KN, AC, KN, KN, KN, KN, SK, KN, AC, KN, SK, KN }, 	 //	 244	 4000
{ KN, QN, KN, KN, TN, KN, KN, KN, KN, ST, KN, AC, SH, WN, AC }, 	 //	 245	 4000
{ KN, QN, KN, KN, JA, KN, KN, KN, KN, TN, KN, AC, SH, SK, AC }, 	 //	 246	 4000
{ KN, QN, WN, KN, PF, KN, KN, KN, KN, JA, KN, AC, KN, KN, TN }, 	 //	 247	 4000
{ KN, KN, KN, PF, TN, KN, AC, SH, AC, AC, KN, SH, AC, AC, AC }, 	 //	 248	 4000
{ KN, AC, SH, WN, AC, KN, AC, AC, AC, AC, SK, AC, AC, KN, SK }, 	 //	 249	 4000
{ KN, AC, AC, AC, AC, KN, AC, PF, AC, AC, SK, AC, QN, AC, AC }, 	 //	 250	 4000
{ KN, LO, QN, LO, KN, KN, KN, PF, KN, SK, SK, KN, KN, KN, QN }, 	 //	 251	 4000
{ KN, KN, KN, SK, KN, KN, KN, KN, QN, AC, SK, KN, KN, KN, LO }, 	 //	 252	 4000
{ KN, KN, PF, LO, TN, KN, KN, KN, KN, AC, SK, ST, KN, KN, AC }, 	 //	 253	 4000
{ KN, KN, KN, QN, JA, KN, KN, KN, KN, TN, SK, ST, SH, AC, AC }, 	 //	 254	 4000
{ KN, KN, KN, AC, AC, KN, KN, SH, AC, AC, SK, ST, AC, AC, AC }, 	 //	 255	 4000
{ KN, KN, AC, KN, KN, KN, KN, WN, KN, KN, SK, ST, KN, KN, KN }, 	 //	 256	 4000
{ KN, KN, KN, AC, KN, KN, KN, KN, LO, KN, SK, ST, KN, KN, KN }, 	 //	 257	 4000
{ KN, KN, KN, KN, KN, KN, KN, PF, KN, QN, SK, ST, QN, SK, PF }, 	 //	 258	 4000
{ KN, TN, KN, PF, KN, KN, TN, KN, KN, KN, SK, WN, KN, KN, KN }, 	 //	 259	 4000
{ KN, WN, KN, KN, SK, KN, AC, KN, KN, KN, SK, KN, KN, KN, KN }, 	 //	 260	 4000
{ KN, WN, KN, KN, KN, KN, AC, KN, KN, KN, SK, KN, KN, WN, KN }, 	 //	 261	 4000
{ KN, AC, KN, KN, QN, KN, KN, KN, KN, KN, SK, QN, PF, WN, AC }, 	 //	 262	 4000
{ KN, AC, KN, PF, AC, KN, KN, KN, KN, SK, SK, QN, PF, KN, KN }, 	 //	 263	 4000
{ KN, QN, KN, PF, KN, KN, ST, KN, KN, KN, SK, JA, KN, KN, KN }, 	 //	 264	 4000
{ KN, TN, AC, WN, TN, KN, AC, AC, AC, AC, SK, AC, PF, KN, AC }, 	 //	 265	 4000
{ KN, PF, WN, QN, JA, KN, KN, KN, KN, WN, SK, KN, KN, AC, TN }, 	 //	 266	 4000
{ KN, PF, QN, LO, KN, KN, KN, AC, KN, KN, SK, KN, KN, KN, SK }, 	 //	 267	 4000
{ KN, KN, KN, KN, KN, KN, KN, WN, KN, KN, SK, KN, TN, KN, SK }, 	 //	 268	 4000
{ KN, KN, KN, AC, AC, KN, KN, SH, AC, AC, SK, KN, AC, AC, AC }, 	 //	 269	 4000
{ KN, KN, WN, AC, ST, KN, KN, KN, PF, AC, SK, KN, KN, KN, KN }, 	 //	 270	 4000
{ KN, KN, WN, KN, ST, KN, KN, KN, KN, AC, SK, KN, KN, SK, KN }, 	 //	 271	 4000
{ KN, QN, WN, AC, SK, KN, KN, KN, KN, QN, SK, AC, KN, QN, QN }, 	 //	 272	 4000
{ KN, KN, KN, KN, KN, KN, AC, KN, KN, SK, SK, SH, KN, SK, QN }, 	 //	 273	 4000
{ KN, AC, JA, PF, AC, SK, AC, TN, AC, AC, QN, AC, AC, AC, AC }, 	 //	 274	 4000
{ KN, AC, KN, KN, KN, SK, AC, KN, KN, KN, QN, AC, KN, SK, KN }, 	 //	 275	 4000
{ KN, AC, TN, AC, AC, SK, AC, AC, AC, AC, QN, LO, AC, LO, CR }, 	 //	 276	 4000
{ KN, KN, PF, PF, KN, SK, KN, KN, KN, SK, QN, ST, KN, KN, QN }, 	 //	 277	 4000
{ KN, KN, KN, KN, KN, SK, KN, KN, SK, AC, QN, ST, KN, QN, LO }, 	 //	 278	 4000
{ KN, KN, KN, LO, QN, SK, KN, KN, KN, KN, QN, ST, SH, KN, AC }, 	 //	 279	 4000
{ KN, TN, KN, KN, KN, SK, WN, KN, KN, KN, QN, AC, KN, WN, KN }, 	 //	 280	 4000
{ KN, WN, AC, AC, LO, SK, AC, AC, AC, AC, QN, KN, PF, AC, AC }, 	 //	 281	 4000
{ KN, WN, AC, AC, LO, SK, AC, AC, AC, AC, QN, KN, WN, LO, AC }, 	 //	 282	 4000
{ KN, AC, KN, KN, PF, SK, KN, KN, KN, JA, QN, QN, KN, WN, TN }, 	 //	 283	 4000
{ KN, TN, AC, KN, AC, SK, AC, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 284	 4000
{ KN, AC, AC, AC, AC, SK, AC, KN, AC, AC, QN, AC, QN, AC, AC }, 	 //	 285	 4000
{ KN, PF, PF, KN, QN, SK, KN, KN, KN, QN, QN, KN, KN, KN, SH }, 	 //	 286	 4000
{ KN, PF, WN, KN, TN, SK, KN, KN, KN, TN, QN, KN, KN, KN, TN }, 	 //	 287	 4000
{ KN, PF, WN, QN, AC, SK, KN, KN, KN, KN, QN, KN, KN, AC, QN }, 	 //	 288	 4000
{ KN, KN, AC, LO, KN, SK, KN, WN, KN, SK, QN, KN, KN, KN, QN }, 	 //	 289	 4000
{ KN, KN, WN, KN, TN, SK, KN, KN, KN, ST, QN, KN, KN, KN, AC }, 	 //	 290	 4000
{ KN, KN, WN, AC, QN, SK, KN, KN, KN, KN, QN, KN, KN, QN, AC }, 	 //	 291	 4000
{ KN, KN, KN, KN, AC, SK, KN, KN, KN, AC, QN, KN, PF, KN, SK }, 	 //	 292	 4000
{ KN, KN, PF, KN, QN, SK, KN, KN, KN, KN, QN, SK, KN, WN, AC }, 	 //	 293	 4000
{ KN, QN, KN, AC, AC, SK, KN, KN, KN, AC, QN, AC, KN, QN, AC }, 	 //	 294	 4000
{ KN, QN, WN, KN, CR, SK, KN, KN, KN, KN, QN, AC, KN, WN, KN }, 	 //	 295	 4000
{ KN, QN, KN, PF, JA, SK, KN, KN, KN, WN, QN, AC, KN, KN, TN }, 	 //	 296	 4000
{ SK, SH, AC, TN, LO, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC }, 	 //	 297	 4000
{ SK, AC, WN, PF, KN, QN, LO, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 298	 4000
{ SK, LO, KN, PF, TN, QN, KN, KN, KN, TN, QN, KN, KN, KN, TN }, 	 //	 299	 4000
{ SK, LO, KN, PF, KN, QN, KN, KN, KN, KN, QN, KN, SH, KN, KN }, 	 //	 300	 4000
{ SK, LO, WN, PF, KN, QN, KN, KN, KN, QN, QN, KN, KN, KN, PF }, 	 //	 301	 4000
{ SK, LO, KN, KN, CR, QN, KN, KN, KN, KN, QN, KN, PF, KN, KN }, 	 //	 302	 4000
{ SK, KN, KN, KN, QN, QN, KN, KN, KN, QN, QN, KN, KN, WN, QN }, 	 //	 303	 4000
{ SK, KN, KN, AC, KN, QN, KN, KN, KN, KN, QN, ST, SH, QN, KN }, 	 //	 304	 4000
{ SK, JA, KN, LO, KN, QN, TN, KN, KN, KN, QN, AC, KN, KN, KN }, 	 //	 305	 4000
{ SK, TN, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, WN, AC, AC }, 	 //	 306	 4000
{ SK, PF, KN, LO, AC, QN, KN, KN, KN, AC, QN, KN, KN, KN, CR }, 	 //	 307	 4000
{ SK, PF, KN, LO, QN, QN, KN, KN, KN, QN, QN, KN, KN, KN, SH }, 	 //	 308	 4000
{ SK, KN, KN, AC, QN, QN, KN, KN, KN, KN, QN, SK, KN, QN, AC }, 	 //	 309	 4000
{ SK, KN, TN, AC, AC, QN, AC, AC, AC, AC, QN, SH, AC, PF, SK }, 	 //	 310	 4000
{ QN, SH, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 311	 4000
{ QN, SH, PF, PF, AC, QN, AC, QN, AC, AC, QN, AC, AC, AC, AC }, 	 //	 312	 4000
{ QN, AC, AC, AC, AC, QN, AC, KN, AC, AC, QN, LO, WN, AC, AC }, 	 //	 313	 4000
{ QN, LO, KN, KN, LO, QN, KN, KN, KN, AC, QN, KN, KN, KN, AC }, 	 //	 314	 4000
{ QN, LO, KN, KN, AC, QN, KN, KN, KN, AC, QN, KN, KN, KN, AC }, 	 //	 315	 4000
{ QN, KN, KN, PF, QN, QN, KN, KN, KN, PF, QN, KN, KN, KN, JA }, 	 //	 316	 4000
{ QN, KN, WN, KN, KN, QN, KN, KN, KN, SK, QN, KN, KN, KN, QN }, 	 //	 317	 4000
{ QN, KN, KN, LO, KN, QN, KN, KN, KN, KN, QN, KN, PF, KN, KN }, 	 //	 318	 4000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, AC, QN, ST, KN, WN, AC }, 	 //	 319	 4000
{ QN, KN, KN, KN, JA, QN, KN, KN, KN, JA, QN, ST, KN, WN, JA }, 	 //	 320	 4000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, SK, QN, ST, PF, WN, KN }, 	 //	 321	 4000
{ QN, QN, QN, QN, PF, QN, QN, QN, QN, JA, QN, SK, QN, SK, TN }, 	 //	 322	 4000
{ QN, TN, KN, KN, KN, QN, WN, KN, KN, KN, QN, AC, KN, SK, KN }, 	 //	 323	 4000
{ QN, AC, KN, KN, ST, QN, KN, KN, KN, AC, QN, QN, KN, SK, KN }, 	 //	 324	 4000
{ QN, AC, AC, AC, AC, QN, AC, KN, AC, AC, QN, AC, QN, AC, AC }, 	 //	 325	 4000
{ QN, AC, KN, KN, KN, QN, AC, KN, KN, KN, QN, AC, KN, SK, KN }, 	 //	 326	 4000
{ QN, AC, AC, AC, AC, QN, AC, WN, AC, AC, QN, AC, KN, AC, AC }, 	 //	 327	 4000
{ QN, AC, AC, WN, AC, QN, AC, AC, AC, AC, QN, PF, WN, KN, AC }, 	 //	 328	 4000
{ QN, PF, KN, KN, KN, QN, KN, KN, KN, KN, QN, KN, PF, SK, CR }, 	 //	 329	 4000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, LO, QN, KN, KN, SK, AC }, 	 //	 330	 4000
{ QN, KN, KN, QN, KN, QN, KN, KN, KN, QN, QN, KN, KN, AC, PF }, 	 //	 331	 4000
{ QN, KN, KN, LO, SH, QN, KN, KN, KN, JA, QN, KN, KN, KN, JA }, 	 //	 332	 4000
{ QN, KN, KN, LO, SK, QN, KN, KN, KN, KN, QN, KN, PF, KN, KN }, 	 //	 333	 4000
{ QN, KN, KN, KN, PF, QN, KN, KN, KN, JA, QN, SK, KN, SK, TN }, 	 //	 334	 4000
{ QN, KN, KN, KN, QN, QN, KN, KN, KN, KN, QN, SK, SH, SK, AC }, 	 //	 335	 4000
{ QN, KN, KN, KN, KN, QN, KN, PF, KN, KN, QN, SK, QN, KN, KN }, 	 //	 336	 4000
{ QN, AC, AC, AC, AC, QN, AC, PF, AC, AC, SH, AC, QN, PF, AC }, 	 //	 337	 4000
{ QN, LO, KN, KN, WN, QN, KN, KN, KN, TN, SH, KN, KN, KN, TN }, 	 //	 338	 4000
{ QN, KN, KN, QN, SK, QN, KN, KN, KN, KN, SH, KN, PF, AC, KN }, 	 //	 339	 4000
{ QN, TN, KN, KN, KN, QN, TN, KN, KN, KN, SH, WN, KN, WN, KN }, 	 //	 340	 4000
{ QN, AC, WN, QN, KN, QN, KN, KN, KN, KN, SH, QN, KN, AC, SK }, 	 //	 341	 4000
{ QN, AC, KN, AC, KN, QN, KN, KN, KN, AC, SH, QN, KN, QN, LO }, 	 //	 342	 4000
{ QN, AC, KN, PF, KN, QN, KN, KN, KN, SK, SH, QN, KN, KN, QN }, 	 //	 343	 4000
{ QN, AC, KN, LO, CR, QN, PF, KN, KN, KN, SH, KN, KN, KN, KN }, 	 //	 344	 4000
{ QN, KN, PF, PF, KN, QN, KN, KN, KN, AC, SH, KN, KN, KN, LO }, 	 //	 345	 4000
{ QN, KN, KN, KN, KN, QN, KN, SH, KN, KN, SH, KN, AC, WN, KN }, 	 //	 346	 4000
{ QN, KN, WN, AC, KN, QN, KN, KN, KN, KN, SH, KN, KN, QN, CR }, 	 //	 347	 4000
{ QN, KN, KN, KN, AC, QN, KN, KN, KN, AC, SH, KN, KN, SK, AC }, 	 //	 348	 4000
{ QN, KN, KN, KN, TN, QN, KN, KN, KN, TN, SH, SK, KN, KN, ST }, 	 //	 349	 4000
{ QN, KN, KN, AC, QN, QN, KN, KN, KN, KN, SH, SK, KN, QN, AC }, 	 //	 350	 4000
{ QN, KN, SH, PF, AC, QN, AC, AC, AC, AC, SH, SH, AC, AC, SK }, 	 //	 351	 4000
{ QN, SH, PF, AC, AC, SH, AC, QN, AC, LO, JA, AC, AC, AC, AC }, 	 //	 352	 4000
{ QN, AC, AC, AC, AC, SH, AC, PF, AC, LO, JA, LO, QN, AC, AC }, 	 //	 353	 4000
{ QN, AC, AC, AC, AC, SH, AC, PF, AC, AC, JA, LO, QN, LO, AC }, 	 //	 354	 4000
{ QN, AC, PF, PF, KN, SH, LO, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 355	 4000
{ QN, LO, KN, QN, CR, SH, KN, KN, KN, KN, JA, KN, SH, AC, KN }, 	 //	 356	 4000
{ QN, LO, KN, PF, QN, SH, KN, KN, KN, QN, JA, KN, KN, KN, SH }, 	 //	 357	 4000
{ QN, KN, KN, KN, KN, SH, KN, QN, KN, KN, JA, KN, PF, KN, KN }, 	 //	 358	 4000
{ QN, KN, KN, KN, PF, SH, KN, KN, KN, JA, JA, KN, KN, WN, TN }, 	 //	 359	 4000
{ QN, KN, KN, KN, JA, SH, KN, KN, KN, JA, JA, ST, KN, KN, JA }, 	 //	 360	 4000
{ QN, AC, WN, KN, KN, SH, KN, KN, KN, KN, JA, QN, KN, WN, KN }, 	 //	 361	 4000
{ QN, ST, KN, KN, KN, SH, JA, KN, KN, KN, JA, TN, KN, WN, KN }, 	 //	 362	 4000
{ QN, TN, SH, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, PF, CR }, 	 //	 363	 4000
{ QN, PF, WN, QN, KN, SH, KN, KN, KN, KN, JA, KN, KN, AC, KN }, 	 //	 364	 4000
{ QN, PF, WN, QN, KN, SH, KN, KN, KN, KN, JA, KN, KN, AC, CR }, 	 //	 365	 4000
{ QN, PF, KN, LO, CR, SH, KN, KN, KN, KN, JA, KN, PF, KN, KN }, 	 //	 366	 4000
{ QN, PF, QN, LO, KN, SH, KN, AC, KN, KN, JA, KN, KN, KN, KN }, 	 //	 367	 4000
{ QN, KN, KN, KN, WN, SH, KN, KN, KN, TN, JA, KN, KN, WN, TN }, 	 //	 368	 4000
{ QN, KN, WN, KN, ST, SH, KN, KN, KN, AC, JA, KN, KN, KN, KN }, 	 //	 369	 4000
{ QN, KN, KN, LO, AC, SH, KN, KN, KN, AC, JA, KN, KN, KN, AC }, 	 //	 370	 4000
{ QN, KN, KN, KN, KN, SH, KN, QN, KN, KN, JA, SK, PF, WN, KN }, 	 //	 371	 4000
{ QN, KN, PF, QN, KN, SH, KN, KN, KN, KN, JA, SK, KN, AC, KN }, 	 //	 372	 4000
{ QN, KN, AC, TN, TN, SH, AC, AC, AC, AC, JA, SH, WN, AC, AC }, 	 //	 373	 4000
{ SH, AC, SH, TN, AC, JA, AC, AC, AC, AC, JA, LO, AC, AC, SK }, 	 //	 374	 4000
{ SH, AC, PF, LO, KN, JA, LO, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 375	 4000
{ SH, LO, PF, KN, KN, JA, KN, KN, KN, KN, JA, KN, KN, WN, SK }, 	 //	 376	 4000
{ SH, KN, WN, AC, KN, JA, KN, KN, KN, KN, JA, KN, KN, QN, SK }, 	 //	 377	 4000
{ SH, KN, KN, KN, JA, JA, KN, KN, KN, TN, JA, KN, KN, WN, AC }, 	 //	 378	 4000
{ SH, KN, KN, KN, KN, JA, KN, KN, KN, QN, JA, ST, SH, WN, PF }, 	 //	 379	 4000
{ SH, KN, KN, KN, KN, JA, ST, KN, KN, KN, JA, QN, KN, KN, SK }, 	 //	 380	 4000
{ SH, ST, KN, KN, KN, JA, QN, KN, KN, KN, JA, QN, KN, WN, KN }, 	 //	 381	 4000
{ SH, QN, KN, KN, KN, JA, QN, KN, KN, KN, JA, QN, KN, WN, KN }, 	 //	 382	 4000
{ SH, WN, KN, LO, SK, JA, AC, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 383	 4000
{ SH, AC, TN, AC, AC, JA, AC, AC, AC, AC, JA, PF, AC, LO, CR }, 	 //	 384	 4000
{ SH, AC, PF, PF, KN, JA, PF, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 385	 4000
{ SH, AC, KN, KN, KN, JA, PF, KN, KN, KN, JA, KN, KN, KN, SK }, 	 //	 386	 4000
{ SH, PF, KN, KN, TN, JA, KN, KN, KN, AC, JA, KN, KN, KN, AC }, 	 //	 387	 4000
{ SH, PF, KN, KN, QN, JA, KN, KN, KN, PF, JA, KN, KN, KN, JA }, 	 //	 388	 4000
{ JA, SH, AC, WN, LO, JA, AC, AC, AC, AC, JA, AC, PF, KN, AC }, 	 //	 389	 4000
{ JA, AC, AC, AC, AC, JA, AC, PF, AC, LO, JA, LO, QN, AC, AC }, 	 //	 390	 4000
{ JA, AC, AC, AC, AC, JA, AC, WN, AC, LO, JA, LO, KN, LO, AC }, 	 //	 391	 4000
{ JA, LO, PF, KN, KN, JA, KN, KN, KN, AC, JA, KN, KN, KN, LO }, 	 //	 392	 4000
{ JA, LO, KN, KN, KN, JA, KN, KN, KN, KN, JA, KN, PF, KN, SK }, 	 //	 393	 4000
{ JA, KN, WN, LO, KN, JA, KN, KN, KN, QN, JA, KN, KN, KN, PF }, 	 //	 394	 4000
{ JA, KN, KN, LO, LO, JA, KN, KN, KN, AC, JA, KN, KN, KN, AC }, 	 //	 395	 4000
{ JA, KN, KN, QN, QN, JA, KN, KN, KN, KN, JA, ST, KN, AC, AC }, 	 //	 396	 4000
{ JA, TN, KN, LO, KN, JA, WN, KN, KN, KN, JA, AC, KN, KN, KN }, 	 //	 397	 4000
{ JA, AC, AC, AC, AC, JA, AC, AC, PF, AC, JA, AC, AC, AC, AC }, 	 //	 398	 4000
{ JA, AC, AC, PF, TN, JA, AC, AC, AC, AC, JA, PF, PF, AC, AC }, 	 //	 399	 4000
{ JA, PF, KN, LO, LO, JA, KN, KN, KN, AC, JA, KN, KN, KN, AC }, 	 //	 400	 4000
{ JA, PF, KN, LO, JA, JA, KN, KN, KN, JA, JA, KN, KN, KN, WN }, 	 //	 401	 4000
{ JA, PF, KN, LO, KN, JA, KN, KN, KN, KN, JA, KN, SH, KN, KN }, 	 //	 402	 4000
{ JA, KN, KN, KN, SK, JA, KN, KN, KN, QN, JA, KN, KN, WN, QN }, 	 //	 403	 4000
{ JA, KN, KN, KN, JA, JA, KN, KN, KN, WN, JA, KN, KN, WN, TN }, 	 //	 404	 4000
{ JA, KN, WN, PF, KN, JA, KN, KN, KN, SK, JA, KN, KN, KN, QN }, 	 //	 405	 4000
{ JA, KN, KN, PF, KN, JA, KN, KN, KN, KN, JA, SK, SH, KN, KN }, 	 //	 406	 4000
{ JA, KN, KN, PF, AC, JA, KN, KN, KN, KN, JA, SK, KN, KN, QN }, 	 //	 407	 4000
{ JA, KN, KN, KN, QN, JA, KN, KN, KN, QN, JA, SK, KN, KN, QN }, 	 //	 408	 4000
{ JA, QN, KN, KN, AC, JA, KN, KN, KN, KN, JA, AC, KN, KN, QN }, 	 //	 409	 4000
{ JA, KN, KN, KN, JA, JA, KN, KN, KN, JA, WN, ST, KN, KN, WN }, 	 //	 410	 4000
{ JA, AC, WN, PF, SK, JA, KN, KN, KN, KN, WN, QN, KN, KN, KN }, 	 //	 411	 4000
{ JA, AC, SH, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, PF, CR }, 	 //	 412	 4000
{ JA, AC, SH, AC, AC, JA, AC, AC, AC, AC, WN, PF, AC, PF, SK }, 	 //	 413	 4000
{ JA, KN, KN, KN, TN, JA, KN, KN, KN, TN, WN, KN, KN, WN, TN }, 	 //	 414	 4000
{ JA, SK, KN, KN, KN, JA, QN, KN, KN, KN, WN, KN, KN, SK, KN }, 	 //	 415	 4000
{ JA, SH, AC, PF, AC, WN, AC, AC, AC, AC, TN, AC, WN, AC, AC }, 	 //	 416	 4000
{ JA, LO, ST, KN, KN, WN, KN, AC, KN, KN, TN, KN, KN, KN, KN }, 	 //	 417	 4000
{ JA, LO, KN, AC, QN, WN, KN, KN, KN, KN, TN, KN, KN, QN, AC }, 	 //	 418	 4000
{ JA, KN, KN, KN, KN, WN, KN, WN, KN, KN, TN, KN, TN, KN, KN }, 	 //	 419	 4000
{ JA, KN, KN, AC, KN, WN, KN, KN, KN, KN, TN, KN, PF, QN, KN }, 	 //	 420	 4000
{ JA, KN, KN, KN, KN, WN, KN, QN, KN, KN, TN, ST, PF, KN, KN }, 	 //	 421	 4000
{ JA, KN, KN, KN, QN, WN, KN, KN, KN, KN, TN, ST, SH, SK, AC }, 	 //	 422	 4000
{ JA, KN, KN, KN, KN, WN, KN, SH, KN, KN, TN, ST, AC, KN, KN }, 	 //	 423	 4000
{ JA, KN, KN, KN, QN, WN, KN, KN, KN, PF, TN, ST, KN, WN, JA }, 	 //	 424	 4000
{ JA, KN, KN, KN, JA, WN, KN, KN, KN, JA, TN, ST, KN, KN, WN }, 	 //	 425	 4000
{ JA, JA, KN, PF, KN, WN, JA, KN, KN, KN, TN, SH, KN, KN, KN }, 	 //	 426	 4000
{ JA, TN, AC, AC, LO, WN, AC, AC, AC, AC, TN, AC, PF, AC, AC }, 	 //	 427	 4000
{ JA, AC, SH, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, LO, AC }, 	 //	 428	 4000
{ JA, PF, PF, KN, KN, WN, KN, KN, KN, KN, TN, KN, KN, WN, KN }, 	 //	 429	 4000
{ JA, PF, WN, PF, KN, WN, KN, KN, KN, SK, TN, KN, KN, KN, QN }, 	 //	 430	 4000
{ JA, KN, KN, QN, KN, WN, KN, KN, KN, SK, TN, KN, KN, AC, QN }, 	 //	 431	 4000
{ JA, KN, KN, KN, KN, WN, KN, KN, KN, SK, TN, KN, SH, KN, QN }, 	 //	 432	 4000
{ JA, KN, KN, KN, AC, WN, KN, KN, KN, AC, TN, KN, KN, WN, SK }, 	 //	 433	 4000
{ JA, KN, KN, PF, SH, WN, KN, KN, KN, JA, TN, KN, KN, KN, JA }, 	 //	 434	 4000
{ JA, KN, KN, KN, TN, WN, KN, KN, KN, ST, TN, KN, KN, SK, AC }, 	 //	 435	 4000
{ JA, KN, KN, KN, KN, WN, AC, KN, KN, KN, TN, SH, SH, KN, KN }, 	 //	 436	 4000
{ JA, KN, TN, KN, AC, WN, AC, AC, AC, AC, TN, SH, AC, PF, SK }, 	 //	 437	 4000
{ WN, SH, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, WN, LO, AC }, 	 //	 438	 4000
{ WN, AC, JA, AC, AC, TN, AC, ST, AC, LO, TN, AC, AC, AC, AC }, 	 //	 439	 4000
{ WN, AC, PF, PF, AC, TN, AC, QN, AC, AC, TN, AC, AC, AC, AC }, 	 //	 440	 4000
{ WN, AC, KN, KN, KN, TN, LO, KN, KN, KN, TN, KN, KN, WN, KN }, 	 //	 441	 4000
{ WN, AC, KN, KN, KN, TN, LO, KN, KN, KN, TN, KN, KN, SK, KN }, 	 //	 442	 4000
{ WN, LO, ST, KN, KN, TN, KN, AC, KN, KN, TN, KN, KN, KN, KN }, 	 //	 443	 4000
{ WN, LO, KN, KN, SK, TN, KN, KN, KN, QN, TN, KN, KN, KN, QN }, 	 //	 444	 4000
{ WN, LO, KN, KN, AC, TN, KN, KN, KN, AC, TN, KN, KN, KN, SK }, 	 //	 445	 4000
{ WN, LO, KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, PF, SK, CR }, 	 //	 446	 4000
{ WN, KN, PF, KN, ST, TN, KN, KN, KN, AC, TN, KN, KN, KN, KN }, 	 //	 447	 4000
{ WN, KN, KN, AC, QN, TN, KN, KN, KN, KN, TN, KN, KN, QN, AC }, 	 //	 448	 4000
{ WN, KN, KN, QN, KN, TN, KN, KN, KN, QN, TN, KN, KN, AC, PF }, 	 //	 449	 4000
{ WN, KN, KN, KN, TN, TN, KN, KN, KN, TN, TN, ST, KN, KN, TN }, 	 //	 450	 4000
{ WN, JA, KN, KN, KN, TN, JA, KN, KN, KN, TN, SH, KN, SK, KN }, 	 //	 451	 4000
{ WN, TN, KN, PF, KN, TN, TN, KN, KN, KN, TN, WN, KN, KN, KN }, 	 //	 452	 4000
{ WN, TN, KN, KN, KN, TN, TN, KN, KN, KN, TN, WN, KN, SK, KN }, 	 //	 453	 4000
{ WN, AC, KN, KN, KN, TN, KN, KN, KN, KN, TN, QN, PF, KN, SK }, 	 //	 454	 4000
{ WN, TN, AC, KN, AC, TN, AC, AC, AC, AC, TN, AC, WN, PF, AC }, 	 //	 455	 4000
{ WN, AC, AC, PF, AC, TN, AC, AC, AC, AC, TN, AC, PF, AC, AC }, 	 //	 456	 4000
{ WN, AC, JA, TN, AC, TN, AC, TN, AC, AC, TN, AC, AC, AC, AC }, 	 //	 457	 4000
{ WN, AC, TN, AC, AC, TN, AC, AC, AC, AC, TN, PF, AC, PF, AC }, 	 //	 458	 4000
{ WN, PF, KN, KN, QN, TN, KN, KN, KN, QN, TN, KN, KN, KN, SH }, 	 //	 459	 4000
{ WN, PF, KN, QN, KN, TN, KN, KN, KN, QN, TN, KN, KN, AC, PF }, 	 //	 460	 4000
{ WN, PF, KN, AC, CR, TN, KN, KN, KN, KN, TN, KN, SH, QN, KN }, 	 //	 461	 4000
{ WN, KN, KN, LO, KN, TN, KN, KN, KN, KN, TN, KN, SH, KN, KN }, 	 //	 462	 4000
{ WN, KN, KN, KN, KN, TN, KN, WN, KN, KN, TN, SK, TN, SK, KN }, 	 //	 463	 4000
{ WN, SK, KN, KN, KN, TN, QN, KN, KN, KN, TN, KN, KN, SK, KN }, 	 //	 464	 4000
{ WN, QN, KN, PF, KN, TN, KN, KN, KN, KN, TN, AC, SH, KN, KN }, 	 //	 465	 4000
{ WN, QN, KN, QN, KN, TN, KN, KN, KN, KN, TN, AC, SH, AC, KN }, 	 //	 466	 4000
{ TN, AC, KN, TN, AC, TN, AC, SH, AC, AC, TN, AC, AC, AC, AC }, 	 //	 467	 4000
{ TN, LO, KN, LO, AC, TN, KN, KN, KN, AC, TN, KN, KN, KN, AC }, 	 //	 468	 4000
{ TN, KN, KN, KN, QN, TN, KN, KN, KN, KN, TN, ST, PF, WN, AC }, 	 //	 469	 4000
{ TN, TN, KN, PF, KN, TN, WN, KN, KN, KN, TN, AC, KN, KN, KN }, 	 //	 470	 4000
{ TN, AC, KN, PF, KN, TN, KN, KN, KN, SK, TN, QN, KN, KN, QN }, 	 //	 471	 4000
{ TN, AC, KN, KN, SK, TN, KN, KN, KN, KN, TN, QN, PF, KN, KN }, 	 //	 472	 4000
{ TN, AC, SH, AC, AC, TN, AC, AC, AC, AC, TN, PF, AC, PF, AC }, 	 //	 473	 4000
{ TN, KN, QN, KN, KN, TN, KN, PF, KN, KN, TN, KN, KN, KN, KN }, 	 //	 474	 4000
{ TN, KN, KN, PF, KN, TN, KN, KN, KN, KN, TN, KN, PF, KN, KN }, 	 //	 475	 4000
{ TN, KN, KN, QN, QN, TN, KN, KN, KN, KN, TN, SK, KN, AC, AC }, 	 //	 476	 4000
{ TN, SK, KN, KN, KN, TN, QN, KN, KN, KN, TN, KN, KN, SK, KN }, 	 //	 477	 4000
{ TN, QN, KN, AC, SK, TN, KN, KN, KN, KN, TN, AC, SH, QN, KN }, 	 //	 478	 4000
{ TN, KN, SH, KN, AC, TN, AC, AC, AC, AC, TN, SH, AC, PF, CR }, 	 //	 479	 4000
{ TN, KN, TN, AC, AC, TN, AC, AC, AC, AC, TN, SH, AC, PF, AC }, 	 //	 480	 4000
{ TN, AC, AC, WN, LO, TN, AC, AC, AC, AC, ST, AC, WN, KN, AC }, 	 //	 481	 4000
{ TN, LO, KN, KN, CR, TN, KN, KN, KN, KN, ST, KN, PF, SK, KN }, 	 //	 482	 4000
{ TN, KN, AC, AC, AC, TN, KN, KN, KN, KN, ST, KN, QN, QN, QN }, 	 //	 483	 4000
{ TN, KN, QN, LO, KN, TN, KN, PF, KN, KN, ST, KN, KN, KN, KN }, 	 //	 484	 4000
{ TN, KN, KN, PF, QN, TN, KN, KN, KN, SH, ST, KN, KN, KN, JA }, 	 //	 485	 4000
{ TN, KN, KN, AC, KN, TN, KN, KN, KN, SK, ST, KN, KN, QN, QN }, 	 //	 486	 4000
{ TN, KN, KN, KN, QN, TN, KN, KN, KN, QN, ST, KN, KN, SK, QN }, 	 //	 487	 4000
{ TN, KN, QN, PF, KN, TN, KN, AC, KN, KN, ST, KN, KN, KN, KN }, 	 //	 488	 4000
{ TN, KN, KN, KN, WN, TN, KN, KN, KN, TN, ST, ST, KN, WN, TN }, 	 //	 489	 4000
{ TN, KN, KN, KN, PF, TN, KN, KN, KN, JA, ST, ST, KN, KN, TN }, 	 //	 490	 4000
{ TN, KN, KN, KN, JA, TN, KN, KN, KN, JA, ST, ST, KN, SK, WN }, 	 //	 491	 4000
{ TN, WN, PF, LO, KN, TN, AC, KN, KN, KN, ST, KN, KN, KN, KN }, 	 //	 492	 4000
{ TN, WN, WN, PF, KN, TN, AC, KN, KN, KN, ST, KN, KN, KN, KN }, 	 //	 493	 4000
{ TN, PF, PF, LO, KN, TN, KN, KN, KN, QN, ST, KN, KN, KN, PF }, 	 //	 494	 4000
{ TN, PF, KN, LO, AC, TN, KN, KN, KN, AC, ST, KN, KN, KN, AC }, 	 //	 495	 4000
{ TN, PF, KN, AC, KN, TN, KN, KN, KN, KN, ST, KN, SH, QN, KN }, 	 //	 496	 4000
{ TN, PF, WN, KN, KN, TN, KN, KN, KN, KN, ST, KN, KN, WN, KN }, 	 //	 497	 4000
{ TN, KN, KN, KN, AC, TN, KN, KN, KN, AC, ST, KN, KN, WN, SK }, 	 //	 498	 4000
{ TN, KN, KN, KN, TN, TN, KN, KN, KN, AC, ST, SK, KN, WN, AC }, 	 //	 499	 4000
{ TN, KN, KN, KN, AC, TN, KN, KN, KN, AC, ST, SK, KN, KN, AC }, 	 //	 500	 4000
{ TN, QN, PF, KN, KN, TN, KN, KN, KN, KN, ST, AC, KN, WN, KN }, 	 //	 501	 4000
{ TN, QN, WN, KN, CR, TN, KN, KN, KN, KN, ST, AC, KN, KN, KN }, 	 //	 502	 4000
{ TN, AC, AC, WN, AC, ST, AC, AC, AC, AC, AC, AC, WN, KN, SK }, 	 //	 503	 4000
{ TN, AC, TN, KN, AC, ST, AC, AC, AC, AC, AC, LO, AC, PF, AC }, 	 //	 504	 4000
{ TN, LO, QN, KN, KN, ST, KN, PF, KN, KN, AC, KN, KN, KN, KN }, 	 //	 505	 4000
{ TN, LO, KN, KN, KN, ST, KN, KN, KN, KN, AC, KN, SH, KN, CR }, 	 //	 506	 4000
{ TN, KN, KN, KN, AC, ST, KN, KN, KN, AC, AC, KN, KN, SK, AC }, 	 //	 507	 4000
{ TN, KN, KN, KN, LO, ST, KN, KN, KN, AC, AC, KN, KN, WN, AC }, 	 //	 508	 4000
{ TN, KN, KN, QN, KN, ST, KN, KN, KN, QN, AC, ST, KN, AC, PF }, 	 //	 509	 4000
{ TN, AC, KN, KN, KN, ST, KN, KN, KN, KN, AC, QN, PF, KN, CR }, 	 //	 510	 4000
{ TN, AC, SH, AC, AC, ST, AC, AC, AC, AC, AC, PF, AC, LO, SK }, 	 //	 511	 4000
{ TN, PF, ST, PF, KN, ST, KN, AC, KN, KN, AC, KN, KN, KN, KN }, 	 //	 512	 4000
{ TN, PF, KN, LO, AC, ST, KN, KN, KN, AC, AC, KN, KN, KN, AC }, 	 //	 513	 4000
{ TN, KN, ST, LO, KN, ST, KN, AC, KN, KN, AC, KN, KN, KN, KN }, 	 //	 514	 4000
{ TN, KN, KN, QN, KN, ST, KN, KN, KN, AC, AC, KN, KN, AC, LO }, 	 //	 515	 4000
{ TN, KN, KN, KN, SK, ST, KN, KN, KN, QN, AC, SK, KN, KN, QN }, 	 //	 516	 4000
{ TN, KN, KN, KN, AC, ST, KN, KN, KN, AC, AC, SK, KN, KN, AC }, 	 //	 517	 4000
{ TN, KN, KN, KN, KN, ST, KN, KN, KN, SK, AC, SK, PF, WN, QN }, 	 //	 518	 4000
{ TN, QN, KN, QN, CR, ST, KN, SH, KN, QN, AC, AC, AC, AC, KN }, 	 //	 519	 4000
{ TN, KN, AC, AC, AC, ST, AC, WN, LO, SK, AC, SH, KN, KN, KN }, 	 //	 520	 4000
{ ST, SH, AC, AC, JA, AC, AC, AC, AC, TN, KN, AC, PF, LO, AC }, 	 //	 521	 4000
{ ST, AC, KN, KN, KN, AC, LO, KN, KN, QN, KN, KN, KN, KN, PF }, 	 //	 522	 4000
{ ST, AC, KN, KN, CR, AC, LO, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 523	 4000
{ ST, LO, PF, AC, KN, AC, KN, KN, KN, SK, KN, KN, KN, QN, QN }, 	 //	 524	 4000
{ ST, LO, WN, LO, AC, AC, KN, KN, KN, AC, KN, KN, KN, KN, CR }, 	 //	 525	 4000
{ ST, LO, QN, LO, KN, AC, KN, AC, KN, KN, KN, KN, KN, KN, CR }, 	 //	 526	 4000
{ ST, KN, KN, KN, JA, AC, KN, KN, KN, JA, KN, KN, PF, KN, JA }, 	 //	 527	 4000
{ ST, KN, KN, KN, JA, AC, KN, KN, KN, JA, KN, KN, PF, KN, WN }, 	 //	 528	 4000
{ ST, KN, KN, KN, SK, AC, KN, KN, KN, QN, KN, KN, PF, WN, QN }, 	 //	 529	 4000
{ ST, KN, KN, KN, KN, AC, KN, SH, KN, SK, KN, ST, AC, WN, QN }, 	 //	 530	 4000
{ ST, WN, KN, LO, ST, AC, AC, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 531	 4000
{ ST, TN, AC, AC, JA, AC, AC, AC, AC, TN, KN, AC, PF, PF, AC }, 	 //	 532	 4000
{ ST, AC, AC, TN, TN, AC, AC, AC, AC, ST, KN, AC, WN, AC, AC }, 	 //	 533	 4000
{ ST, KN, KN, AC, CR, AC, KN, KN, LO, KN, KN, KN, KN, KN, KN }, 	 //	 534	 4000
{ ST, KN, KN, AC, CR, AC, KN, KN, PF, KN, KN, KN, KN, KN, KN }, 	 //	 535	 4000
{ ST, KN, WN, KN, TN, AC, KN, KN, KN, TN, KN, KN, KN, KN, ST }, 	 //	 536	 4000
{ ST, KN, QN, KN, CR, AC, KN, AC, KN, QN, KN, KN, KN, KN, KN }, 	 //	 537	 4000
{ ST, KN, KN, KN, AC, AC, KN, SH, KN, SK, KN, SK, AC, KN, KN }, 	 //	 538	 4000
{ ST, SK, WN, LO, KN, AC, QN, KN, KN, KN, KN, KN, KN, KN, CR }, 	 //	 539	 4000
{ ST, QN, KN, KN, TN, AC, KN, KN, KN, TN, KN, AC, KN, KN, TN }, 	 //	 540	 4000
{ AC, SH, KN, KN, KN, KN, AC, KN, KN, KN, QN, AC, KN, WN, KN }, 	 //	 541	 4000
{ AC, AC, JA, PF, TN, KN, AC, ST, AC, ST, QN, AC, AC, AC, AC }, 	 //	 542	 4000
{ AC, AC, JA, TN, TN, KN, AC, TN, AC, AC, QN, AC, AC, AC, AC }, 	 //	 543	 4000
{ AC, LO, PF, QN, KN, KN, KN, KN, KN, AC, QN, KN, KN, AC, LO }, 	 //	 544	 4000
{ AC, LO, KN, QN, AC, KN, KN, KN, KN, AC, QN, KN, KN, AC, CR }, 	 //	 545	 4000
{ AC, KN, KN, KN, AC, KN, KN, KN, KN, AC, QN, KN, SH, WN, AC }, 	 //	 546	 4000
{ AC, KN, KN, QN, LO, KN, KN, KN, KN, AC, QN, ST, KN, AC, AC }, 	 //	 547	 4000
{ AC, ST, KN, KN, KN, KN, QN, KN, KN, KN, QN, QN, KN, WN, KN }, 	 //	 548	 4000
{ AC, QN, QN, WN, QN, KN, QN, QN, QN, QN, QN, SK, QN, QN, QN }, 	 //	 549	 4000
{ AC, TN, KN, KN, KN, KN, TN, KN, KN, KN, QN, WN, KN, SK, KN }, 	 //	 550	 4000
{ AC, WN, PF, PF, KN, KN, AC, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 551	 4000
{ AC, AC, KN, KN, AC, KN, KN, KN, KN, AC, QN, QN, KN, KN, AC }, 	 //	 552	 4000
{ AC, AC, KN, KN, LO, KN, KN, KN, KN, AC, QN, QN, KN, KN, AC }, 	 //	 553	 4000
{ AC, AC, KN, KN, QN, KN, KN, KN, KN, QN, QN, QN, KN, KN, SH }, 	 //	 554	 4000
{ AC, AC, KN, PF, CR, KN, PF, KN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 555	 4000
{ AC, PF, KN, KN, KN, KN, KN, KN, KN, QN, QN, KN, SH, KN, PF }, 	 //	 556	 4000
{ AC, PF, KN, AC, KN, KN, KN, KN, KN, KN, QN, KN, SH, QN, SK }, 	 //	 557	 4000
{ AC, KN, WN, PF, TN, KN, KN, KN, KN, AC, QN, KN, KN, KN, AC }, 	 //	 558	 4000
{ AC, KN, AC, AC, AC, KN, KN, KN, AC, AC, QN, SK, QN, AC, AC }, 	 //	 559	 4000
{ AC, KN, SH, AC, LO, KN, AC, AC, AC, AC, QN, SH, AC, PF, AC }, 	 //	 560	 4000
{ AC, KN, KN, KN, CR, KN, AC, KN, KN, KN, QN, SH, KN, KN, KN }, 	 //	 561	 4000
{ KN, AC, AC, KN, LO, QN, AC, AC, AC, AC, PF, AC, PF, PF, AC }, 	 //	 562	 4000
{ KN, AC, PF, AC, AC, QN, AC, QN, AC, AC, PF, AC, AC, AC, AC }, 	 //	 563	 4000
{ KN, LO, PF, LO, QN, QN, KN, KN, KN, QN, PF, KN, KN, KN, QN }, 	 //	 564	 4000
{ KN, LO, PF, LO, JA, QN, KN, KN, KN, TN, PF, KN, KN, KN, AC }, 	 //	 565	 4000
{ KN, LO, KN, QN, JA, QN, KN, KN, KN, TN, PF, KN, KN, AC, AC }, 	 //	 566	 4000
{ KN, KN, KN, KN, AC, QN, KN, KN, KN, AC, PF, KN, PF, KN, AC }, 	 //	 567	 4000
{ KN, KN, KN, KN, CR, QN, KN, QN, KN, KN, PF, ST, PF, SK, KN }, 	 //	 568	 4000
{ KN, KN, PF, AC, KN, QN, KN, KN, KN, QN, PF, ST, KN, QN, PF }, 	 //	 569	 4000
{ KN, KN, PF, AC, KN, QN, KN, KN, KN, AC, PF, ST, KN, QN, LO }, 	 //	 570	 4000
{ KN, KN, KN, LO, QN, QN, KN, KN, KN, KN, PF, ST, SH, KN, AC }, 	 //	 571	 4000
{ KN, KN, QN, PF, KN, QN, KN, AC, KN, KN, PF, ST, KN, KN, KN }, 	 //	 572	 4000
{ KN, KN, KN, KN, KN, QN, ST, PF, KN, KN, PF, QN, QN, KN, KN }, 	 //	 573	 4000
{ KN, AC, KN, KN, QN, QN, KN, KN, KN, QN, PF, QN, KN, KN, SH }, 	 //	 574	 4000
{ KN, KN, KN, KN, KN, QN, QN, KN, KN, SK, PF, ST, KN, WN, QN }, 	 //	 575	 4000
{ KN, PF, KN, KN, SK, QN, KN, KN, KN, KN, PF, KN, SH, WN, KN }, 	 //	 576	 4000
{ KN, PF, QN, PF, KN, QN, KN, AC, KN, KN, PF, KN, KN, KN, SK }, 	 //	 577	 4000
{ KN, KN, PF, PF, QN, QN, KN, KN, KN, SH, PF, KN, KN, KN, JA }, 	 //	 578	 4000
{ KN, KN, KN, AC, KN, QN, KN, KN, LO, KN, PF, KN, KN, KN, KN }, 	 //	 579	 4000
{ KN, KN, KN, WN, CR, QN, KN, KN, AC, QN, PF, KN, KN, KN, KN }, 	 //	 580	 4000
{ KN, KN, WN, PF, SK, QN, KN, KN, KN, QN, PF, KN, KN, KN, QN }, 	 //	 581	 4000
{ KN, KN, WN, PF, QN, QN, KN, KN, KN, SH, PF, KN, KN, KN, JA }, 	 //	 582	 4000
{ KN, KN, WN, PF, AC, QN, KN, KN, KN, KN, PF, SK, KN, KN, QN }, 	 //	 583	 4000
{ KN, QN, PF, AC, KN, QN, KN, KN, KN, SK, PF, AC, KN, QN, QN }, 	 //	 584	 4000
{ KN, QN, KN, QN, AC, QN, KN, KN, KN, AC, PF, AC, KN, AC, SK }, 	 //	 585	 4000
{ KN, QN, KN, KN, TN, QN, KN, KN, KN, ST, PF, AC, KN, KN, AC }, 	 //	 586	 4000
{ KN, QN, KN, KN, AC, QN, KN, KN, KN, LO, PF, AC, KN, WN, AC }, 	 //	 587	 4000
{ KN, QN, QN, KN, KN, QN, KN, AC, KN, KN, PF, AC, KN, KN, KN }, 	 //	 588	 4000
{ QN, SH, KN, KN, KN, PF, AC, KN, KN, KN, JA, AC, KN, WN, KN }, 	 //	 589	 4000
{ QN, AC, AC, PF, AC, PF, AC, AC, AC, AC, JA, LO, PF, AC, AC }, 	 //	 590	 4000
{ QN, LO, KN, QN, CR, PF, KN, KN, KN, QN, JA, KN, KN, AC, KN }, 	 //	 591	 4000
{ QN, LO, KN, KN, CR, PF, KN, KN, KN, KN, JA, KN, SH, WN, KN }, 	 //	 592	 4000
{ QN, KN, QN, KN, KN, PF, KN, PF, KN, KN, JA, KN, KN, KN, KN }, 	 //	 593	 4000
{ QN, KN, KN, PF, WN, PF, KN, KN, KN, TN, JA, KN, KN, KN, TN }, 	 //	 594	 4000
{ QN, KN, KN, LO, KN, PF, ST, KN, KN, KN, JA, QN, KN, KN, KN }, 	 //	 595	 4000
{ QN, AC, KN, AC, KN, PF, KN, KN, KN, SK, JA, QN, KN, QN, QN }, 	 //	 596	 4000
{ QN, AC, KN, AC, KN, PF, KN, KN, KN, KN, JA, QN, PF, QN, KN }, 	 //	 597	 4000
{ QN, KN, KN, PF, KN, PF, QN, KN, KN, KN, JA, ST, KN, KN, KN }, 	 //	 598	 4000
{ QN, AC, SH, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, LO, SK }, 	 //	 599	 4000
{ QN, AC, JA, TN, AC, PF, AC, TN, AC, LO, JA, AC, AC, AC, AC }, 	 //	 600	 4000
{ QN, PF, KN, LO, AC, PF, KN, KN, KN, AC, JA, KN, KN, KN, AC }, 	 //	 601	 4000
{ QN, PF, KN, LO, KN, PF, KN, KN, KN, KN, JA, KN, PF, KN, KN }, 	 //	 602	 4000
{ QN, KN, KN, AC, KN, PF, KN, KN, KN, QN, JA, KN, KN, QN, PF }, 	 //	 603	 4000
{ QN, KN, KN, PF, QN, PF, KN, KN, KN, SH, JA, KN, KN, KN, JA }, 	 //	 604	 4000
{ QN, SK, PF, KN, KN, PF, QN, KN, KN, KN, JA, KN, KN, KN, KN }, 	 //	 605	 4000
{ QN, QN, KN, KN, CR, PF, KN, KN, KN, KN, JA, AC, SH, WN, KN }, 	 //	 606	 4000
{ PF, AC, TN, WN, AC, JA, AC, AC, AC, AC, TN, AC, AC, KN, CR }, 	 //	 607	 4000
{ PF, AC, TN, WN, AC, JA, AC, AC, AC, AC, TN, LO, AC, KN, AC }, 	 //	 608	 4000
{ PF, LO, PF, AC, KN, JA, KN, KN, KN, KN, TN, KN, KN, QN, SK }, 	 //	 609	 4000
{ PF, KN, KN, LO, TN, JA, KN, KN, KN, AC, TN, KN, KN, KN, AC }, 	 //	 610	 4000
{ PF, KN, KN, KN, TN, JA, KN, KN, KN, TN, TN, KN, KN, WN, TN }, 	 //	 611	 4000
{ PF, KN, KN, KN, SH, JA, KN, KN, KN, JA, TN, KN, KN, SK, JA }, 	 //	 612	 4000
{ PF, KN, KN, KN, KN, JA, ST, KN, KN, KN, TN, QN, SH, KN, KN }, 	 //	 613	 4000
{ PF, AC, WN, QN, KN, JA, KN, KN, KN, KN, TN, QN, KN, AC, KN }, 	 //	 614	 4000
{ PF, KN, KN, KN, KN, JA, QN, KN, KN, KN, TN, ST, PF, KN, KN }, 	 //	 615	 4000
{ PF, AC, JA, AC, AC, JA, AC, TN, AC, LO, TN, AC, AC, AC, AC }, 	 //	 616	 4000
{ PF, KN, KN, KN, AC, JA, KN, KN, KN, SK, TN, SK, SH, KN, KN }, 	 //	 617	 4000
{ PF, KN, KN, KN, KN, JA, SK, KN, KN, KN, TN, QN, SH, WN, KN }, 	 //	 618	 4000
{ PF, QN, KN, KN, CR, JA, KN, KN, KN, KN, TN, AC, SH, WN, KN }, 	 //	 619	 4000
{ JA, AC, JA, PF, AC, TN, AC, TN, AC, AC, AC, AC, AC, AC, SK }, 	 //	 620	 4000
{ JA, AC, AC, AC, CR, TN, AC, WN, LO, KN, AC, AC, KN, KN, KN }, 	 //	 621	 4000
{ JA, AC, AC, AC, AC, TN, AC, WN, AC, SK, AC, AC, KN, AC, KN }, 	 //	 622	 4000
{ JA, LO, PF, KN, KN, TN, KN, KN, KN, QN, AC, KN, KN, KN, PF }, 	 //	 623	 4000
{ JA, KN, KN, KN, KN, TN, KN, KN, KN, SK, AC, KN, PF, WN, QN }, 	 //	 624	 4000
{ JA, KN, PF, AC, KN, TN, KN, KN, KN, KN, AC, ST, KN, QN, SK }, 	 //	 625	 4000
{ JA, KN, KN, KN, TN, TN, KN, KN, KN, ST, AC, ST, KN, SK, AC }, 	 //	 626	 4000
{ JA, KN, KN, KN, KN, TN, ST, KN, KN, KN, AC, QN, KN, KN, CR }, 	 //	 627	 4000
{ JA, QN, KN, KN, KN, TN, SK, KN, KN, KN, AC, JA, KN, WN, KN }, 	 //	 628	 4000
{ JA, QN, KN, LO, KN, TN, ST, KN, KN, KN, AC, JA, KN, KN, KN }, 	 //	 629	 4000
{ JA, AC, AC, AC, AC, TN, AC, WN, AC, SK, AC, AC, KN, PF, KN }, 	 //	 630	 4000
{ JA, PF, KN, KN, SK, TN, KN, KN, KN, KN, AC, KN, PF, KN, KN }, 	 //	 631	 4000
{ JA, KN, WN, PF, SK, TN, KN, KN, KN, KN, AC, SK, KN, KN, KN }, 	 //	 632	 4000
{ JA, KN, KN, KN, KN, TN, SK, KN, KN, KN, AC, QN, KN, WN, CR }, 	 //	 633	 4000
{ JA, SK, KN, KN, KN, TN, QN, KN, KN, KN, AC, KN, KN, SK, KN }, 	 //	 634	 4000
{ JA, QN, PF, PF, KN, TN, KN, KN, KN, KN, AC, AC, KN, KN, SK }, 	 //	 635	 4000
{ JA, QN, KN, PF, QN, TN, KN, KN, KN, KN, AC, AC, KN, KN, AC }, 	 //	 636	 4000
{ JA, KN, TN, AC, AC, TN, AC, AC, AC, AC, AC, SH, AC, LO, SK }, 	 //	 637	 4000
{ TN, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, LO, KN }, 	 //	 638	 4000
{ TN, SH, AC, KN, SH, AC, AC, AC, AC, JA, AC, AC, WN, PF, JA }, 	 //	 639	 4000
{ TN, AC, KN, PF, AC, AC, AC, SH, AC, SK, AC, AC, AC, AC, KN }, 	 //	 640	 4000
{ TN, AC, AC, WN, CR, AC, AC, AC, AC, QN, AC, AC, WN, KN, KN }, 	 //	 641	 4000
{ TN, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, LO, PF, AC, KN }, 	 //	 642	 4000
{ TN, AC, AC, AC, KN, AC, AC, KN, KN, KN, AC, LO, WN, QN, CR }, 	 //	 643	 4000
{ TN, LO, KN, KN, SK, AC, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 644	 4000
{ TN, LO, KN, PF, JA, AC, KN, KN, KN, JA, AC, KN, KN, KN, JA }, 	 //	 645	 4000
{ TN, KN, KN, KN, KN, AC, KN, KN, KN, QN, AC, KN, SH, WN, PF }, 	 //	 646	 4000
{ TN, KN, KN, PF, TN, AC, KN, KN, KN, TN, AC, KN, KN, KN, ST }, 	 //	 647	 4000
{ TN, KN, KN, KN, JA, AC, KN, KN, KN, JA, AC, ST, KN, KN, JA }, 	 //	 648	 4000
{ TN, QN, KN, PF, KN, AC, QN, KN, KN, KN, AC, SK, KN, KN, KN }, 	 //	 649	 4000
{ TN, TN, KN, LO, KN, AC, TN, KN, KN, KN, AC, WN, KN, KN, KN }, 	 //	 650	 4000
{ TN, WN, AC, AC, SK, AC, AC, AC, AC, QN, AC, KN, WN, LO, QN }, 	 //	 651	 4000
{ TN, WN, AC, AC, WN, AC, AC, AC, AC, TN, AC, KN, WN, PF, TN }, 	 //	 652	 4000
{ TN, TN, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, PF, LO, QN }, 	 //	 653	 4000
{ TN, TN, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, PF, AC, KN }, 	 //	 654	 4000
{ TN, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, LO, CR }, 	 //	 655	 4000
{ TN, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, WN, PF, SK }, 	 //	 656	 4000
{ TN, PF, PF, AC, KN, AC, KN, KN, KN, KN, AC, KN, KN, QN, KN }, 	 //	 657	 4000
{ TN, KN, AC, AC, AC, AC, KN, KN, KN, KN, AC, KN, QN, QN, QN }, 	 //	 658	 4000
{ TN, KN, KN, LO, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN, SK }, 	 //	 659	 4000
{ TN, KN, PF, PF, KN, AC, KN, KN, KN, KN, AC, SK, KN, KN, CR }, 	 //	 660	 4000
{ TN, KN, KN, KN, QN, AC, KN, KN, KN, SH, AC, SK, KN, KN, JA }, 	 //	 661	 4000
{ TN, KN, KN, KN, AC, AC, KN, KN, KN, AC, AC, SK, KN, KN, AC }, 	 //	 662	 4000
{ TN, KN, KN, KN, KN, AC, KN, KN, KN, AC, AC, SK, PF, SK, LO }, 	 //	 663	 4000
{ TN, QN, KN, KN, SK, AC, KN, KN, KN, KN, AC, AC, SH, SK, KN }, 	 //	 664	 4000
{ TN, QN, WN, AC, KN, AC, KN, KN, KN, KN, AC, AC, KN, QN, SK }, 	 //	 665	 4000
{ TN, KN, AC, PF, KN, AC, AC, AC, AC, QN, AC, SH, PF, AC, PF }, 	 //	 666	 4000
{ TN, KN, AC, AC, SK, AC, AC, AC, AC, KN, AC, SH, PF, AC, KN }, 	 //	 667	 4000
{ TN, KN, AC, AC, JA, AC, AC, AC, AC, JA, AC, SH, PF, LO, WN }, 	 //	 668	 4000
{ AC, SH, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, WN, AC, QN }, 	 //	 669	 4000
{ AC, SH, KN, PF, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN }, 	 //	 670	 4000
{ AC, AC, JA, AC, CR, AC, AC, ST, AC, KN, AC, AC, AC, AC, KN }, 	 //	 671	 4000
{ AC, AC, AC, AC, KN, AC, AC, PF, AC, SK, AC, AC, QN, AC, QN }, 	 //	 672	 4000
{ AC, AC, AC, AC, CR, AC, AC, KN, AC, QN, AC, LO, QN, PF, KN }, 	 //	 673	 4000
{ AC, AC, TN, AC, SK, AC, AC, AC, AC, QN, AC, LO, AC, AC, QN }, 	 //	 674	 4000
{ AC, AC, AC, AC, QN, AC, AC, KN, AC, SH, AC, LO, WN, AC, JA }, 	 //	 675	 4000
{ AC, AC, AC, KN, KN, AC, AC, KN, KN, KN, AC, LO, WN, SK, CR }, 	 //	 676	 4000
{ AC, LO, KN, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, KN, AC }, 	 //	 677	 4000
{ AC, LO, KN, KN, AC, AC, KN, KN, KN, KN, AC, KN, KN, WN, QN }, 	 //	 678	 4000
{ AC, KN, WN, KN, KN, AC, KN, KN, KN, AC, AC, KN, KN, KN, LO }, 	 //	 679	 4000
{ AC, KN, KN, KN, LO, AC, KN, KN, KN, AC, AC, KN, KN, WN, AC }, 	 //	 680	 4000
{ AC, KN, KN, KN, AC, AC, KN, KN, KN, AC, AC, KN, KN, WN, AC }, 	 //	 681	 4000
{ AC, KN, KN, AC, KN, AC, KN, KN, KN, AC, AC, KN, KN, QN, LO }, 	 //	 682	 4000
{ AC, KN, KN, KN, QN, AC, KN, KN, KN, QN, AC, KN, KN, SK, QN }, 	 //	 683	 4000
{ AC, KN, PF, LO, SK, AC, KN, KN, KN, KN, AC, ST, KN, KN, KN }, 	 //	 684	 4000
{ AC, KN, KN, LO, KN, AC, KN, KN, KN, AC, AC, ST, KN, KN, LO }, 	 //	 685	 4000
{ AC, KN, KN, KN, KN, AC, KN, KN, KN, AC, AC, ST, PF, SK, LO }, 	 //	 686	 4000
{ AC, KN, KN, QN, KN, AC, KN, KN, KN, KN, AC, ST, PF, AC, KN }, 	 //	 687	 4000
{ AC, QN, KN, KN, KN, AC, QN, KN, KN, KN, AC, QN, KN, SK, KN }, 	 //	 688	 4000
{ AC, WN, SH, WN, KN, AC, AC, AC, AC, QN, AC, KN, AC, KN, PF }, 	 //	 689	 4000
{ AC, WN, AC, AC, TN, AC, AC, AC, AC, TN, AC, KN, PF, PF, ST }, 	 //	 690	 4000
{ AC, WN, TN, WN, WN, AC, AC, AC, AC, TN, AC, KN, AC, KN, TN }, 	 //	 691	 4000
{ AC, AC, KN, KN, AC, AC, KN, KN, KN, KN, AC, QN, KN, KN, QN }, 	 //	 692	 4000
{ AC, ST, KN, KN, KN, AC, JA, KN, KN, KN, AC, TN, KN, SK, KN }, 	 //	 693	 4000
{ AC, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC, TN }, 	 //	 694	 4000
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, PF, PF, QN }, 	 //	 695	 4000
{ AC, TN, JA, AC, SH, AC, AC, TN, AC, JA, AC, AC, AC, AC, JA }, 	 //	 696	 4000
{ AC, TN, PF, PF, KN, AC, AC, QN, AC, KN, AC, AC, AC, AC, CR }, 	 //	 697	 4000
{ AC, AC, JA, TN, SK, AC, AC, TN, AC, QN, AC, AC, AC, AC, QN }, 	 //	 698	 4000
{ AC, AC, AC, AC, JA, AC, AC, WN, AC, JA, AC, AC, KN, LO, JA }, 	 //	 699	 4000
{ AC, AC, AC, SK, KN, AC, AC, WN, QN, KN, AC, AC, KN, KN, KN }, 	 //	 700	 4000
{ AC, AC, AC, KN, QN, AC, AC, KN, KN, KN, AC, AC, WN, KN, AC }, 	 //	 701	 4000
{ AC, AC, SH, AC, CR, AC, AC, AC, AC, KN, AC, PF, AC, PF, KN }, 	 //	 702	 4000
{ AC, PF, PF, KN, KN, AC, KN, KN, KN, AC, AC, KN, KN, KN, LO }, 	 //	 703	 4000
{ AC, PF, KN, PF, JA, AC, KN, KN, KN, TN, AC, KN, KN, KN, AC }, 	 //	 704	 4000
{ AC, PF, KN, AC, KN, AC, KN, KN, KN, SK, AC, KN, KN, QN, QN }, 	 //	 705	 4000
{ AC, PF, KN, KN, SK, AC, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 706	 4000
{ AC, KN, ST, LO, KN, AC, KN, AC, KN, KN, AC, KN, KN, KN, KN }, 	 //	 707	 4000
{ AC, KN, KN, KN, WN, AC, KN, KN, KN, TN, AC, KN, KN, SK, TN }, 	 //	 708	 4000
{ AC, QN, KN, AC, AC, AC, KN, KN, KN, KN, AC, AC, KN, QN, QN }, 	 //	 709	 4000
{ AC, QN, KN, KN, ST, AC, KN, KN, KN, AC, AC, AC, KN, SK, KN }, 	 //	 710	 4000
{ AC, KN, SH, WN, SK, AC, AC, AC, AC, QN, AC, SH, AC, KN, QN }, 	 //	 711	 4000
{ AC, KN, SH, KN, CR, AC, AC, AC, AC, QN, AC, SH, AC, PF, KN }, 	 //	 712	 4000
{ AC, KN, TN, AC, QN, AC, AC, AC, AC, QN, AC, SH, AC, PF, SH }, 	 //	 713	 4000
{ AC, SH, TN, WN, SK, AC, AC, AC, AC, KN, SK, AC, AC, KN, KN }, 	 //	 714	 4000
{ AC, SH, TN, AC, CR, AC, AC, AC, AC, KN, SK, AC, AC, PF, KN }, 	 //	 715	 4000
{ AC, AC, AC, AC, TN, AC, AC, KN, AC, ST, SK, AC, WN, AC, AC }, 	 //	 716	 4000
{ AC, AC, SH, AC, WN, AC, AC, AC, AC, TN, SK, LO, AC, LO, TN }, 	 //	 717	 4000
{ AC, AC, SH, AC, CR, AC, AC, AC, AC, KN, SK, LO, AC, PF, KN }, 	 //	 718	 4000
{ AC, AC, TN, AC, JA, AC, AC, AC, AC, JA, SK, LO, AC, LO, WN }, 	 //	 719	 4000
{ AC, AC, TN, TN, CR, AC, AC, AC, AC, KN, SK, LO, AC, AC, KN }, 	 //	 720	 4000
{ AC, LO, KN, KN, QN, AC, KN, KN, KN, QN, SK, KN, KN, KN, SH }, 	 //	 721	 4000
{ AC, LO, WN, PF, KN, AC, KN, KN, KN, SK, SK, KN, KN, KN, QN }, 	 //	 722	 4000
{ AC, KN, WN, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, SK, KN }, 	 //	 723	 4000
{ AC, KN, PF, KN, KN, AC, KN, KN, KN, KN, SK, ST, KN, SK, KN }, 	 //	 724	 4000
{ AC, KN, KN, KN, JA, AC, KN, KN, KN, JA, SK, ST, KN, SK, JA }, 	 //	 725	 4000
{ AC, SK, KN, KN, KN, AC, JA, KN, KN, KN, SK, JA, KN, SK, KN }, 	 //	 726	 4000
{ AC, WN, TN, KN, KN, AC, AC, AC, AC, KN, SK, KN, AC, PF, KN }, 	 //	 727	 4000
{ AC, AC, KN, KN, SK, AC, KN, KN, KN, KN, SK, QN, PF, SK, KN }, 	 //	 728	 4000
{ AC, TN, TN, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, LO, QN }, 	 //	 729	 4000
{ AC, PF, KN, AC, KN, AC, KN, KN, KN, AC, SK, KN, KN, QN, LO }, 	 //	 730	 4000
{ AC, KN, PF, KN, KN, AC, KN, KN, KN, KN, SK, KN, KN, SK, KN }, 	 //	 731	 4000
{ AC, KN, TN, WN, CR, AC, AC, AC, AC, QN, SK, SH, AC, KN, KN }, 	 //	 732	 4000
{ AC, KN, TN, AC, KN, AC, AC, AC, AC, KN, SK, SH, AC, PF, CR }, 	 //	 733	 4000
{ AC, SH, SH, WN, KN, SK, AC, AC, AC, AC, KN, AC, AC, KN, LO }, 	 //	 734	 4000
{ AC, AC, PF, PF, QN, SK, AC, QN, AC, KN, KN, AC, AC, AC, AC }, 	 //	 735	 4000
{ AC, LO, QN, KN, CR, SK, KN, PF, KN, KN, KN, KN, KN, KN, KN }, 	 //	 736	 4000
{ AC, LO, KN, AC, QN, SK, KN, KN, KN, KN, KN, KN, PF, QN, AC }, 	 //	 737	 4000
{ AC, LO, KN, KN, AC, SK, KN, KN, KN, SK, KN, KN, PF, SK, KN }, 	 //	 738	 4000
{ AC, KN, KN, AC, SK, SK, KN, KN, PF, KN, KN, KN, KN, KN, KN }, 	 //	 739	 4000
{ AC, KN, KN, KN, QN, SK, KN, KN, KN, QN, KN, ST, PF, KN, QN }, 	 //	 740	 4000
{ AC, KN, KN, KN, JA, SK, KN, KN, KN, WN, KN, ST, PF, KN, TN }, 	 //	 741	 4000
{ AC, KN, KN, KN, KN, SK, ST, KN, KN, KN, KN, QN, PF, KN, KN }, 	 //	 742	 4000
{ AC, WN, ST, LO, KN, SK, AC, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 743	 4000
{ AC, AC, PF, AC, KN, SK, KN, KN, KN, KN, KN, QN, KN, QN, KN }, 	 //	 744	 4000
{ AC, AC, KN, AC, PF, SK, KN, KN, KN, JA, KN, QN, KN, QN, TN }, 	 //	 745	 4000
{ AC, AC, KN, KN, AC, SK, KN, KN, KN, KN, KN, QN, SH, KN, QN }, 	 //	 746	 4000
{ AC, AC, SH, WN, LO, SK, AC, AC, AC, AC, KN, PF, AC, KN, AC }, 	 //	 747	 4000
{ AC, AC, PF, KN, CR, SK, PF, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 748	 4000
{ AC, AC, AC, AC, KN, SK, PF, WN, KN, AC, KN, KN, KN, QN, LO }, 	 //	 749	 4000
{ AC, AC, WN, KN, KN, SK, PF, KN, KN, KN, KN, KN, KN, KN, SK }, 	 //	 750	 4000
{ AC, PF, KN, AC, AC, SK, KN, SH, AC, AC, KN, KN, AC, AC, AC }, 	 //	 751	 4000
{ AC, PF, AC, LO, SK, SK, KN, WN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 752	 4000
{ AC, PF, QN, KN, KN, SK, KN, AC, KN, AC, KN, KN, KN, KN, LO }, 	 //	 753	 4000
{ AC, KN, QN, KN, KN, SK, KN, PF, KN, AC, KN, KN, KN, KN, LO }, 	 //	 754	 4000
{ AC, KN, AC, KN, CR, SK, KN, WN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 755	 4000
{ AC, KN, WN, KN, TN, SK, KN, KN, KN, ST, KN, KN, KN, KN, AC }, 	 //	 756	 4000
{ AC, KN, KN, KN, KN, SK, KN, QN, KN, KN, KN, SK, PF, WN, CR }, 	 //	 757	 4000
{ AC, KN, PF, KN, KN, SK, KN, KN, KN, KN, KN, SK, KN, KN, SK }, 	 //	 758	 4000
{ AC, KN, KN, QN, ST, SK, KN, KN, KN, AC, KN, SK, PF, AC, KN }, 	 //	 759	 4000
{ SK, SH, TN, WN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, CR }, 	 //	 760	 4000
{ SK, AC, TN, WN, AC, KN, AC, AC, AC, AC, KN, LO, AC, KN, SK }, 	 //	 761	 4000
{ SK, LO, QN, KN, KN, KN, KN, PF, KN, AC, KN, KN, KN, KN, LO }, 	 //	 762	 4000
{ SK, LO, KN, AC, TN, KN, KN, KN, PF, TN, KN, KN, KN, KN, ST }, 	 //	 763	 4000
{ SK, LO, KN, SK, AC, KN, KN, KN, QN, KN, KN, KN, KN, KN, QN }, 	 //	 764	 4000
{ SK, LO, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, PF, WN, ST }, 	 //	 765	 4000
{ SK, LO, KN, KN, JA, KN, KN, KN, KN, TN, KN, KN, PF, KN, AC }, 	 //	 766	 4000
{ SK, KN, KN, AC, SH, KN, KN, KN, LO, JA, KN, KN, KN, KN, JA }, 	 //	 767	 4000
{ SK, KN, KN, KN, CR, KN, KN, KN, AC, QN, KN, KN, KN, PF, KN }, 	 //	 768	 4000
{ SK, KN, AC, AC, AC, KN, KN, WN, AC, AC, KN, KN, KN, AC, AC }, 	 //	 769	 4000
{ SK, KN, KN, AC, AC, KN, KN, KN, PF, LO, KN, KN, KN, KN, AC }, 	 //	 770	 4000
{ SK, KN, KN, QN, JA, KN, KN, KN, KN, JA, KN, KN, PF, AC, WN }, 	 //	 771	 4000
{ SK, KN, QN, KN, AC, KN, KN, AC, KN, SK, KN, KN, KN, KN, KN }, 	 //	 772	 4000
{ SK, KN, KN, KN, KN, KN, KN, KN, SK, AC, KN, ST, KN, QN, LO }, 	 //	 773	 4000
{ SK, KN, KN, QN, SH, KN, KN, KN, KN, JA, KN, ST, SH, AC, JA }, 	 //	 774	 4000
{ SK, KN, KN, KN, KN, KN, KN, SH, KN, KN, KN, ST, AC, SK, CR }, 	 //	 775	 4000
{ SK, KN, KN, AC, JA, KN, KN, KN, KN, JA, KN, ST, PF, QN, WN }, 	 //	 776	 4000
{ SK, KN, KN, QN, WN, KN, KN, KN, KN, TN, KN, ST, PF, AC, TN }, 	 //	 777	 4000
{ SK, KN, KN, KN, KN, KN, KN, PF, KN, KN, KN, ST, QN, SK, CR }, 	 //	 778	 4000
{ SK, KN, KN, KN, KN, KN, ST, KN, KN, KN, KN, QN, KN, WN, CR }, 	 //	 779	 4000
{ SK, KN, KN, KN, CR, KN, ST, KN, KN, KN, KN, QN, KN, KN, KN }, 	 //	 780	 4000
{ SK, WN, TN, KN, AC, KN, AC, AC, AC, AC, KN, KN, AC, PF, AC }, 	 //	 781	 4000
{ SK, WN, WN, LO, SK, KN, AC, KN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 782	 4000
{ SK, AC, PF, PF, KN, KN, KN, KN, KN, QN, KN, QN, KN, KN, PF }, 	 //	 783	 4000
{ SK, AC, PF, KN, AC, KN, KN, KN, KN, KN, KN, QN, KN, KN, QN }, 	 //	 784	 4000
{ SK, AC, KN, LO, SH, KN, KN, KN, KN, JA, KN, QN, SH, KN, JA }, 	 //	 785	 4000
{ SK, AC, KN, AC, JA, KN, KN, KN, KN, TN, KN, QN, PF, QN, AC }, 	 //	 786	 4000
{ SK, AC, KN, QN, JA, KN, KN, KN, KN, TN, KN, QN, PF, AC, AC }, 	 //	 787	 4000
{ SK, TN, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, PF, PF, AC }, 	 //	 788	 4000
{ SK, AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, AC }, 	 //	 789	 4000
{ SK, PF, PF, AC, SK, KN, KN, KN, LO, KN, KN, KN, KN, KN, KN }, 	 //	 790	 4000
{ SK, PF, PF, AC, JA, KN, KN, KN, KN, JA, KN, KN, KN, QN, JA }, 	 //	 791	 4000
{ SK, PF, QN, PF, SK, KN, KN, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 792	 4000
{ SK, KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, KN, PF, WN, CR }, 	 //	 793	 4000
{ SK, KN, KN, AC, AC, KN, KN, SH, AC, AC, KN, KN, AC, AC, AC }, 	 //	 794	 4000
{ SK, KN, WN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN, SK, AC }, 	 //	 795	 4000
{ SK, KN, KN, AC, TN, KN, KN, KN, LO, TN, KN, KN, KN, KN, ST }, 	 //	 796	 4000
{ SK, KN, KN, KN, AC, KN, KN, SH, KN, SK, KN, SK, AC, KN, KN }, 	 //	 797	 4000
{ SK, KN, KN, QN, QN, KN, KN, KN, KN, QN, KN, SK, PF, AC, SH }, 	 //	 798	 4000
{ SK, QN, KN, KN, JA, KN, KN, KN, KN, JA, KN, AC, SH, SK, JA }, 	 //	 799	 4000
{ SK, QN, KN, PF, WN, KN, KN, KN, KN, TN, KN, AC, PF, KN, TN }, 	 //	 800	 4000
{ SK, KN, KN, KN, KN, KN, AC, KN, KN, KN, KN, SH, PF, SK, KN }, 	 //	 801	 4000
{ KN, LO, KN, AC, TN, KN, KN, KN, PF, AC, KN, KN, KN, AC, AC }, 	 //	 802	 4000
{ KN, LO, KN, JA, PF, KN, KN, KN, TN, JA, KN, KN, KN, AC, TN }, 	 //	 803	 4000
{ KN, LO, KN, KN, WN, KN, KN, KN, AC, TN, KN, KN, KN, PF, TN }, 	 //	 804	 4000
{ KN, LO, KN, AC, AC, KN, KN, KN, KN, AC, KN, KN, SH, QN, AC }, 	 //	 805	 4000
{ KN, LO, AC, KN, TN, KN, KN, WN, KN, ST, KN, KN, KN, KN, AC }, 	 //	 806	 4000
{ KN, LO, WN, SK, KN, KN, KN, KN, QN, SK, KN, KN, KN, KN, QN }, 	 //	 807	 4000
{ KN, LO, KN, WN, KN, KN, KN, KN, QN, SK, KN, KN, KN, QN, QN }, 	 //	 808	 4000
{ KN, LO, KN, QN, JA, KN, KN, KN, QN, TN, KN, KN, KN, SK, AC }, 	 //	 809	 4000
{ KN, LO, KN, AC, KN, KN, KN, KN, AC, AC, KN, KN, KN, PF, LO }, 	 //	 810	 4000
{ KN, LO, KN, KN, ST, KN, KN, KN, SK, AC, KN, KN, KN, QN, KN }, 	 //	 811	 4000
{ KN, LO, KN, PF, TN, KN, KN, KN, KN, TN, KN, KN, PF, KN, TN }, 	 //	 812	 4000
{ KN, LO, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, PF, KN, CR }, 	 //	 813	 4000
{ KN, LO, QN, KN, JA, KN, KN, AC, KN, JA, KN, KN, KN, KN, JA }, 	 //	 814	 4000
{ KN, KN, KN, KN, JA, KN, KN, WN, KN, WN, KN, KN, TN, KN, TN }, 	 //	 815	 4000
{ KN, KN, KN, KN, QN, KN, KN, QN, KN, SH, KN, KN, PF, KN, JA }, 	 //	 816	 4000
{ KN, KN, PF, AC, WN, KN, KN, KN, LO, TN, KN, KN, KN, KN, TN }, 	 //	 817	 4000
{ KN, KN, KN, KN, AC, KN, KN, KN, QN, AC, KN, KN, SH, ST, AC }, 	 //	 818	 4000
{ KN, KN, KN, KN, AC, KN, KN, SH, KN, KN, KN, KN, AC, SK, QN }, 	 //	 819	 4000
{ KN, KN, AC, LO, AC, KN, KN, WN, KN, AC, KN, KN, KN, KN, AC }, 	 //	 820	 4000
{ KN, KN, AC, KN, JA, KN, KN, WN, KN, TN, KN, KN, KN, KN, AC }, 	 //	 821	 4000
{ KN, KN, KN, KN, AC, KN, KN, QN, KN, AC, KN, ST, PF, WN, AC }, 	 //	 822	 4000
{ KN, KN, PF, LO, TN, KN, KN, KN, KN, TN, KN, ST, KN, KN, ST }, 	 //	 823	 4000
{ KN, KN, KN, SK, KN, KN, KN, KN, JA, KN, KN, ST, KN, JA, KN }, 	 //	 824	 4000
{ KN, KN, KN, JA, QN, KN, KN, KN, SH, PF, KN, ST, KN, TN, JA }, 	 //	 825	 4000
{ KN, KN, KN, TN, KN, KN, KN, KN, TN, KN, KN, ST, KN, WN, CR }, 	 //	 826	 4000
{ KN, KN, KN, AC, KN, KN, KN, KN, PF, AC, KN, ST, KN, KN, LO }, 	 //	 827	 4000
{ KN, KN, WN, KN, TN, KN, KN, KN, KN, TN, KN, ST, KN, SK, TN }, 	 //	 828	 4000
{ KN, KN, KN, AC, SK, KN, KN, KN, AC, QN, KN, ST, KN, LO, QN }, 	 //	 829	 4000
{ KN, KN, KN, QN, KN, KN, KN, KN, QN, SK, KN, ST, KN, QN, QN }, 	 //	 830	 4000
{ KN, KN, KN, KN, JA, KN, KN, KN, WN, TN, KN, ST, PF, QN, AC }, 	 //	 831	 4000
{ KN, KN, KN, KN, SH, KN, KN, KN, QN, JA, KN, ST, PF, ST, JA }, 	 //	 832	 4000
{ KN, KN, KN, KN, TN, KN, KN, KN, AC, TN, KN, ST, PF, PF, ST }, 	 //	 833	 4000
{ KN, KN, KN, QN, KN, KN, ST, KN, KN, KN, KN, QN, KN, AC, KN }, 	 //	 834	 4000
{ KN, KN, KN, KN, KN, KN, ST, PF, KN, KN, KN, QN, QN, WN, KN }, 	 //	 835	 4000
{ KN, TN, KN, PF, KN, KN, TN, KN, KN, KN, KN, WN, KN, KN, KN }, 	 //	 836	 4000
{ KN, WN, KN, KN, ST, KN, AC, KN, KN, AC, KN, KN, KN, KN, KN }, 	 //	 837	 4000
{ KN, AC, PF, QN, QN, KN, KN, KN, KN, QN, KN, QN, KN, AC, QN }, 	 //	 838	 4000
{ KN, AC, KN, PF, AC, KN, KN, KN, KN, AC, KN, QN, SH, KN, AC }, 	 //	 839	 4000
{ KN, AC, TN, KN, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 840	 4000
{ KN, AC, KN, LO, KN, KN, AC, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 841	 4000
{ KN, AC, QN, KN, KN, KN, PF, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 842	 4000
{ KN, PF, ST, KN, AC, KN, KN, AC, KN, KN, KN, KN, KN, KN, QN }, 	 //	 843	 4000
{ KN, PF, QN, KN, AC, KN, KN, PF, KN, KN, KN, KN, KN, KN, QN }, 	 //	 844	 4000
{ KN, PF, KN, JA, JA, KN, KN, KN, SH, TN, KN, KN, KN, TN, AC }, 	 //	 845	 4000
{ KN, PF, KN, TN, KN, KN, KN, KN, WN, KN, KN, KN, KN, AC, KN }, 	 //	 846	 4000
{ KN, PF, KN, QN, TN, KN, KN, KN, QN, ST, KN, KN, KN, SK, AC }, 	 //	 847	 4000
{ KN, PF, KN, SH, KN, KN, KN, KN, TN, KN, KN, KN, KN, TN, CR }, 	 //	 848	 4000
{ KN, KN, ST, KN, TN, KN, KN, AC, KN, TN, KN, KN, KN, KN, TN }, 	 //	 849	 4000
{ KN, KN, PF, WN, KN, KN, KN, KN, AC, KN, KN, KN, KN, KN, CR }, 	 //	 850	 4000
{ KN, KN, KN, KN, TN, KN, KN, KN, AC, AC, KN, KN, PF, PF, AC }, 	 //	 851	 4000
{ KN, KN, KN, KN, SH, KN, KN, QN, KN, JA, KN, SK, PF, KN, JA }, 	 //	 852	 4000
{ KN, KN, KN, KN, AC, KN, KN, QN, KN, AC, KN, SK, PF, WN, SK }, 	 //	 853	 4000
{ KN, KN, KN, KN, KN, KN, KN, QN, WN, QN, KN, SK, PF, QN, PF }, 	 //	 854	 4000
{ KN, KN, PF, LO, AC, KN, KN, KN, KN, AC, KN, SK, KN, KN, AC }, 	 //	 855	 4000
{ KN, KN, KN, PF, LO, KN, KN, KN, AC, AC, KN, SK, KN, AC, AC }, 	 //	 856	 4000
{ KN, KN, KN, WN, AC, KN, KN, KN, QN, AC, KN, SK, KN, QN, AC }, 	 //	 857	 4000
{ KN, KN, KN, QN, AC, KN, KN, KN, QN, LO, KN, SK, KN, SK, AC }, 	 //	 858	 4000
{ KN, KN, KN, JA, JA, KN, KN, KN, JA, WN, KN, SK, KN, SH, TN }, 	 //	 859	 4000
{ KN, KN, KN, TN, SK, KN, KN, KN, TN, KN, KN, SK, KN, WN, KN }, 	 //	 860	 4000
{ KN, KN, KN, AC, AC, KN, KN, KN, PF, LO, KN, SK, KN, KN, AC }, 	 //	 861	 4000
{ KN, KN, KN, AC, AC, KN, KN, KN, PF, AC, KN, SK, KN, KN, AC }, 	 //	 862	 4000
{ KN, KN, KN, KN, AC, KN, KN, KN, QN, AC, KN, SK, SH, ST, SK }, 	 //	 863	 4000
{ KN, KN, KN, LO, KN, KN, KN, SH, KN, KN, KN, SK, AC, KN, KN }, 	 //	 864	 4000
{ KN, KN, KN, QN, SH, KN, KN, KN, QN, JA, KN, SK, KN, QN, JA }, 	 //	 865	 4000
{ KN, QN, KN, AC, KN, KN, KN, KN, LO, KN, KN, AC, KN, KN, KN }, 	 //	 866	 4000
{ KN, QN, WN, KN, AC, KN, KN, KN, KN, LO, KN, AC, KN, WN, AC }, 	 //	 867	 4000
{ KN, QN, KN, KN, JA, KN, KN, KN, KN, TN, KN, AC, PF, KN, AC }, 	 //	 868	 4000
{ KN, LO, KN, QN, CR, KN, KN, KN, KN, QN, WN, KN, SH, AC, KN }, 	 //	 869	 4000
{ KN, LO, WN, KN, WN, KN, KN, KN, KN, TN, WN, KN, KN, WN, TN }, 	 //	 870	 4000
{ KN, LO, WN, AC, SK, KN, KN, KN, KN, QN, WN, KN, KN, QN, QN }, 	 //	 871	 4000
{ KN, LO, QN, KN, KN, KN, KN, AC, KN, KN, WN, KN, KN, KN, SK }, 	 //	 872	 4000
{ KN, KN, KN, SK, PF, KN, KN, KN, QN, JA, WN, KN, KN, KN, TN }, 	 //	 873	 4000
{ KN, KN, KN, AC, JA, KN, KN, KN, KN, WN, WN, KN, SH, QN, TN }, 	 //	 874	 4000
{ KN, KN, KN, KN, CR, KN, KN, SH, KN, KN, WN, KN, AC, SK, KN }, 	 //	 875	 4000
{ KN, KN, KN, KN, ST, KN, KN, KN, SK, AC, WN, KN, KN, QN, KN }, 	 //	 876	 4000
{ KN, KN, KN, KN, AC, KN, KN, KN, SK, KN, WN, KN, KN, QN, QN }, 	 //	 877	 4000
{ KN, KN, KN, KN, KN, KN, KN, PF, KN, KN, WN, KN, QN, SK, CR }, 	 //	 878	 4000
{ KN, KN, KN, KN, KN, KN, KN, WN, KN, SK, WN, ST, TN, SK, QN }, 	 //	 879	 4000
{ KN, KN, KN, KN, TN, KN, KN, KN, WN, TN, WN, ST, KN, QN, ST }, 	 //	 880	 4000
{ KN, KN, KN, KN, AC, KN, KN, KN, SK, AC, WN, ST, KN, QN, CR }, 	 //	 881	 4000
{ KN, AC, AC, AC, JA, KN, KN, KN, AC, TN, WN, QN, QN, AC, AC }, 	 //	 882	 4000
{ KN, AC, AC, AC, QN, KN, KN, KN, KN, PF, WN, QN, QN, QN, JA }, 	 //	 883	 4000
{ KN, AC, KN, KN, QN, KN, KN, KN, KN, KN, WN, QN, PF, KN, AC }, 	 //	 884	 4000
{ KN, KN, KN, KN, KN, KN, QN, KN, KN, KN, WN, ST, PF, KN, SK }, 	 //	 885	 4000
{ KN, TN, JA, PF, AC, KN, AC, TN, AC, AC, WN, AC, AC, AC, AC }, 	 //	 886	 4000
{ KN, PF, QN, KN, ST, KN, KN, PF, KN, AC, WN, KN, KN, KN, KN }, 	 //	 887	 4000
{ KN, PF, PF, KN, AC, KN, KN, KN, KN, AC, WN, KN, KN, WN, CR }, 	 //	 888	 4000
{ KN, KN, ST, KN, KN, KN, KN, AC, KN, KN, WN, KN, KN, KN, CR }, 	 //	 889	 4000
{ KN, KN, KN, KN, QN, KN, KN, KN, SK, QN, WN, KN, KN, QN, QN }, 	 //	 890	 4000
{ KN, KN, AC, KN, KN, KN, KN, WN, KN, KN, WN, KN, KN, KN, CR }, 	 //	 891	 4000
{ KN, KN, WN, AC, QN, KN, KN, KN, KN, QN, WN, KN, KN, QN, QN }, 	 //	 892	 4000
{ KN, KN, WN, AC, TN, KN, KN, KN, KN, AC, WN, KN, KN, QN, AC }, 	 //	 893	 4000
{ KN, KN, WN, AC, SK, KN, KN, KN, PF, KN, WN, KN, KN, KN, KN }, 	 //	 894	 4000
{ KN, KN, QN, LO, KN, KN, KN, AC, KN, KN, WN, KN, KN, KN, SK }, 	 //	 895	 4000
{ KN, KN, KN, AC, AC, KN, KN, KN, KN, AC, WN, SK, SH, QN, AC }, 	 //	 896	 4000
{ KN, SK, KN, KN, KN, KN, QN, KN, KN, KN, WN, KN, KN, KN, CR }, 	 //	 897	 4000
{ KN, QN, KN, LO, KN, KN, KN, KN, KN, KN, WN, AC, SH, KN, CR }, 	 //	 898	 4000
{ KN, KN, KN, AC, QN, KN, AC, SH, AC, KN, WN, SH, AC, AC, AC }, 	 //	 899	 4000
{ KN, KN, KN, KN, AC, KN, AC, SH, AC, AC, WN, SH, AC, PF, AC }, 	 //	 900	 4000
{ KN, AC, SH, AC, AC, WN, AC, AC, AC, AC, QN, AC, AC, PF, AC }, 	 //	 901	 4000
{ KN, AC, AC, KN, LO, WN, AC, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 902	 4000
{ KN, AC, AC, PF, TN, WN, AC, AC, AC, AC, QN, LO, WN, AC, AC }, 	 //	 903	 4000
{ KN, LO, ST, KN, KN, WN, KN, AC, KN, KN, QN, KN, KN, KN, SK }, 	 //	 904	 4000
{ KN, LO, PF, KN, TN, WN, KN, KN, KN, TN, QN, KN, KN, KN, TN }, 	 //	 905	 4000
{ KN, LO, AC, PF, SK, WN, KN, WN, KN, KN, QN, KN, KN, KN, KN }, 	 //	 906	 4000
{ KN, KN, KN, KN, AC, WN, KN, KN, KN, AC, QN, KN, PF, SK, AC }, 	 //	 907	 4000
{ KN, KN, KN, KN, SH, WN, KN, KN, KN, JA, QN, ST, SH, SK, JA }, 	 //	 908	 4000
{ KN, KN, KN, LO, SK, WN, ST, KN, KN, KN, QN, QN, KN, KN, KN }, 	 //	 909	 4000
{ KN, TN, KN, KN, KN, WN, TN, KN, KN, KN, QN, WN, KN, SK, KN }, 	 //	 910	 4000
{ KN, AC, PF, LO, AC, WN, KN, KN, KN, SK, QN, QN, KN, KN, KN }, 	 //	 911	 4000
{ KN, AC, AC, AC, AC, WN, KN, PF, AC, AC, QN, QN, QN, LO, AC }, 	 //	 912	 4000
{ KN, JA, KN, PF, KN, WN, TN, KN, KN, KN, QN, AC, KN, KN, KN }, 	 //	 913	 4000
{ KN, AC, AC, PF, AC, WN, AC, AC, AC, AC, QN, AC, WN, AC, AC }, 	 //	 914	 4000
{ KN, PF, PF, KN, TN, WN, KN, KN, KN, TN, QN, KN, KN, KN, TN }, 	 //	 915	 4000
{ KN, PF, KN, KN, JA, WN, KN, KN, KN, JA, QN, KN, KN, SK, JA }, 	 //	 916	 4000
{ KN, KN, KN, KN, KN, WN, KN, QN, KN, KN, QN, KN, PF, KN, CR }, 	 //	 917	 4000
{ KN, KN, KN, KN, SK, WN, KN, QN, KN, KN, QN, KN, PF, SK, KN }, 	 //	 918	 4000
{ KN, KN, QN, KN, CR, WN, KN, PF, KN, KN, QN, KN, KN, KN, KN }, 	 //	 919	 4000
{ KN, KN, KN, WN, AC, WN, KN, KN, AC, SK, QN, KN, KN, KN, KN }, 	 //	 920	 4000
{ KN, KN, AC, KN, KN, WN, KN, WN, KN, KN, QN, KN, KN, KN, SK }, 	 //	 921	 4000
{ KN, KN, WN, LO, QN, WN, KN, KN, KN, QN, QN, KN, KN, KN, QN }, 	 //	 922	 4000
{ KN, KN, KN, KN, JA, WN, KN, KN, KN, JA, QN, SK, SH, KN, JA }, 	 //	 923	 4000
{ KN, KN, KN, KN, JA, WN, KN, KN, KN, JA, QN, SK, PF, KN, JA }, 	 //	 924	 4000
{ KN, KN, KN, KN, LO, WN, KN, KN, KN, AC, QN, SK, PF, KN, AC }, 	 //	 925	 4000
{ KN, KN, KN, QN, AC, WN, KN, KN, KN, SK, QN, SK, PF, AC, KN }, 	 //	 926	 4000
{ KN, KN, KN, PF, CR, WN, SK, KN, KN, KN, QN, QN, KN, KN, KN }, 	 //	 927	 4000
{ KN, QN, KN, AC, LO, WN, KN, KN, KN, AC, QN, AC, KN, QN, AC }, 	 //	 928	 4000
{ KN, QN, WN, LO, AC, WN, KN, KN, KN, KN, QN, AC, KN, KN, QN }, 	 //	 929	 4000
{ KN, KN, KN, KN, KN, WN, AC, KN, KN, AC, QN, SH, KN, SK, LO }, 	 //	 930	 4000
{ KN, KN, KN, KN, KN, WN, AC, SH, KN, KN, QN, SH, AC, KN, KN }, 	 //	 931	 4000
{ KN, KN, KN, KN, KN, WN, AC, KN, KN, QN, QN, SH, KN, KN, PF }, 	 //	 932	 4000
{ WN, SH, KN, KN, KN, QN, AC, KN, KN, KN, KN, AC, KN, WN, KN }, 	 //	 933	 4000
{ WN, AC, AC, AC, AC, QN, AC, AC, PF, AC, KN, AC, AC, AC, AC }, 	 //	 934	 4000
{ WN, LO, KN, AC, KN, QN, KN, KN, LO, KN, KN, KN, KN, KN, KN }, 	 //	 935	 4000
{ WN, LO, AC, KN, SK, QN, KN, WN, KN, KN, KN, KN, KN, KN, KN }, 	 //	 936	 4000
{ WN, LO, KN, KN, CR, QN, KN, KN, KN, QN, KN, KN, PF, SK, KN }, 	 //	 937	 4000
{ WN, KN, KN, KN, KN, QN, KN, WN, KN, KN, KN, KN, TN, WN, CR }, 	 //	 938	 4000
{ WN, KN, KN, KN, CR, QN, KN, WN, KN, QN, KN, KN, TN, WN, KN }, 	 //	 939	 4000
{ WN, KN, QN, KN, KN, QN, KN, PF, KN, AC, KN, KN, KN, KN, LO }, 	 //	 940	 4000
{ WN, KN, WN, KN, JA, QN, KN, KN, KN, TN, KN, KN, KN, KN, AC }, 	 //	 941	 4000
{ WN, KN, KN, KN, KN, QN, KN, QN, KN, KN, KN, ST, PF, WN, CR }, 	 //	 942	 4000
{ WN, KN, KN, KN, JA, QN, KN, KN, KN, JA, KN, ST, PF, SK, JA }, 	 //	 943	 4000
{ WN, ST, KN, KN, KN, QN, QN, KN, KN, KN, KN, QN, KN, SK, KN }, 	 //	 944	 4000
{ WN, WN, KN, PF, CR, QN, AC, KN, KN, QN, KN, KN, KN, KN, KN }, 	 //	 945	 4000
{ WN, AC, KN, KN, QN, QN, KN, KN, KN, QN, KN, QN, KN, KN, QN }, 	 //	 946	 4000
{ WN, AC, KN, QN, AC, QN, KN, KN, KN, AC, KN, QN, KN, AC, CR }, 	 //	 947	 4000
{ WN, TN, TN, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, PF, CR }, 	 //	 948	 4000
{ WN, AC, AC, AC, AC, QN, AC, KN, AC, AC, KN, AC, QN, LO, AC }, 	 //	 949	 4000
{ WN, AC, TN, AC, AC, QN, AC, AC, AC, AC, KN, PF, AC, AC, CR }, 	 //	 950	 4000
{ WN, KN, WN, KN, KN, QN, KN, KN, KN, QN, KN, KN, KN, SK, PF }, 	 //	 951	 4000
{ WN, KN, KN, KN, CR, QN, KN, PF, KN, QN, KN, KN, QN, KN, KN }, 	 //	 952	 4000
{ WN, KN, QN, KN, SK, QN, KN, AC, KN, KN, KN, KN, KN, KN, KN }, 	 //	 953	 4000
{ WN, KN, KN, LO, LO, QN, KN, KN, KN, AC, KN, SK, KN, KN, AC }, 	 //	 954	 4000
{ WN, QN, PF, KN, SK, QN, KN, KN, KN, KN, KN, AC, KN, KN, KN }, 	 //	 955	 4000
{ WN, QN, WN, KN, KN, QN, KN, KN, KN, KN, KN, AC, KN, WN, CR }, 	 //	 956	 4000
{ WN, QN, KN, KN, QN, QN, KN, KN, KN, QN, KN, AC, KN, KN, QN }, 	 //	 957	 4000
{ WN, QN, KN, KN, AC, QN, KN, KN, KN, AC, KN, AC, KN, WN, CR }, 	 //	 958	 4000
{ QN, AC, JA, AC, AC, KN, AC, TN, AC, KN, AC, AC, AC, AC, QN }, 	 //	 959	 4000
{ QN, LO, KN, KN, JA, KN, KN, KN, KN, JA, AC, KN, KN, SK, JA }, 	 //	 960	 4000
{ QN, LO, WN, KN, KN, KN, KN, KN, KN, SK, AC, KN, KN, WN, QN }, 	 //	 961	 4000
{ QN, KN, KN, PF, AC, KN, KN, KN, KN, AC, AC, ST, KN, KN, AC }, 	 //	 962	 4000
{ QN, KN, KN, QN, AC, KN, KN, KN, KN, AC, AC, ST, KN, AC, CR }, 	 //	 963	 4000
{ QN, KN, KN, AC, AC, KN, KN, KN, KN, SK, AC, ST, PF, QN, KN }, 	 //	 964	 4000
{ QN, JA, KN, KN, KN, KN, JA, KN, KN, KN, AC, SH, KN, WN, KN }, 	 //	 965	 4000
{ QN, AC, KN, KN, JA, KN, KN, KN, KN, TN, AC, QN, KN, SK, AC }, 	 //	 966	 4000
{ QN, AC, KN, QN, AC, KN, KN, KN, KN, KN, AC, QN, PF, AC, QN }, 	 //	 967	 4000
{ QN, QN, KN, LO, KN, KN, ST, KN, KN, KN, AC, JA, KN, KN, KN }, 	 //	 968	 4000
{ QN, TN, JA, AC, AC, KN, AC, TN, AC, AC, AC, AC, AC, AC, SK }, 	 //	 969	 4000
{ QN, AC, KN, KN, SK, KN, PF, KN, KN, KN, AC, KN, KN, KN, KN }, 	 //	 970	 4000
{ QN, PF, WN, PF, SK, KN, KN, KN, KN, QN, AC, KN, KN, KN, QN }, 	 //	 971	 4000
{ QN, KN, WN, KN, TN, KN, KN, KN, KN, ST, AC, KN, KN, KN, AC }, 	 //	 972	 4000
{ QN, KN, KN, QN, ST, KN, KN, KN, KN, AC, AC, SK, SH, AC, KN }, 	 //	 973	 4000
{ QN, KN, KN, QN, JA, KN, KN, KN, KN, JA, AC, SK, KN, AC, JA }, 	 //	 974	 4000
{ QN, KN, KN, KN, TN, KN, KN, KN, KN, AC, AC, SK, PF, WN, AC }, 	 //	 975	 4000
{ QN, QN, AC, AC, AC, KN, KN, KN, AC, AC, AC, AC, WN, PF, AC }, 	 //	 976	 4000
{ QN, KN, KN, KN, KN, KN, AC, KN, KN, KN, AC, SH, KN, KN, CR }, 	 //	 977	 4000
{ KN, AC, WN, KN, KN, AC, LO, KN, KN, KN, LO, KN, KN, KN, KN }, 	 //	 978	 4000
{ KN, LO, QN, LO, KN, AC, KN, PF, KN, SK, LO, KN, KN, KN, QN }, 	 //	 979	 4000
{ KN, LO, QN, KN, AC, AC, KN, PF, KN, SK, LO, KN, KN, KN, KN }, 	 //	 980	 4000
{ KN, LO, QN, KN, CR, AC, KN, PF, KN, QN, LO, KN, KN, KN, KN }, 	 //	 981	 4000
{ KN, LO, KN, AC, AC, AC, KN, KN, KN, AC, LO, KN, KN, QN, SK }, 	 //	 982	 4000
{ KN, LO, KN, KN, SK, AC, KN, KN, KN, KN, LO, KN, SH, WN, KN }, 	 //	 983	 4000
{ KN, LO, WN, KN, AC, AC, KN, KN, KN, AC, LO, KN, KN, KN, AC }, 	 //	 984	 4000
{ KN, KN, ST, PF, AC, AC, KN, AC, KN, SK, LO, KN, KN, KN, KN }, 	 //	 985	 4000
{ KN, KN, KN, KN, AC, AC, KN, QN, KN, SK, LO, KN, PF, KN, KN }, 	 //	 986	 4000
{ KN, KN, PF, LO, JA, AC, KN, KN, KN, JA, LO, KN, KN, KN, WN }, 	 //	 987	 4000
{ KN, KN, KN, KN, SK, AC, KN, WN, KN, KN, LO, ST, TN, SK, KN }, 	 //	 988	 4000
{ KN, KN, KN, KN, AC, AC, KN, KN, KN, LO, LO, ST, SH, WN, AC }, 	 //	 989	 4000
{ KN, KN, KN, KN, TN, AC, KN, KN, KN, AC, LO, ST, PF, KN, AC }, 	 //	 990	 4000
{ KN, KN, KN, QN, KN, AC, ST, KN, KN, KN, LO, QN, KN, AC, KN }, 	 //	 991	 4000
{ KN, JA, KN, KN, KN, AC, SH, KN, KN, KN, LO, TN, KN, WN, KN }, 	 //	 992	 4000
{ KN, AC, KN, LO, KN, AC, KN, KN, KN, KN, LO, QN, PF, KN, KN }, 	 //	 993	 4000
{ KN, TN, AC, TN, TN, AC, AC, AC, AC, ST, LO, AC, PF, AC, AC }, 	 //	 994	 4000
{ KN, TN, TN, AC, AC, AC, AC, AC, AC, KN, LO, AC, AC, PF, QN }, 	 //	 995	 4000
{ KN, KN, KN, KN, SK, AC, KN, WN, KN, KN, LO, KN, TN, WN, KN }, 	 //	 996	 4000
{ KN, KN, QN, KN, KN, AC, KN, PF, KN, KN, LO, KN, KN, KN, CR }, 	 //	 997	 4000
{ KN, KN, PF, KN, AC, AC, KN, KN, KN, KN, LO, KN, KN, SK, QN }, 	 //	 998	 4000
{ KN, KN, KN, KN, CR, AC, KN, SH, KN, QN, LO, KN, AC, SK, KN }, 	 //	 999	 4000
{ KN, KN, AC, AC, AC, AC, KN, WN, AC, AC, LO, KN, KN, AC, AC }};	 //	 1000	 4000
