unsigned char L5_Outcome_0620[1000][15]={	 //	 0	 620
{ AC, QN, QN, QN, KN, LO, QN, QN, SK, SK, AC, QN, SK, JA, QN }, 	 //	 1	 620
{ AC, QN, QN, QN, KN, LO, QN, SK, SK, KN, AC, QN, JA, JA, SK }, 	 //	 2	 620
{ AC, QN, QN, QN, AC, LO, QN, SK, SK, AC, AC, QN, JA, JA, SK }, 	 //	 3	 620
{ AC, QN, QN, QN, AC, LO, QN, QN, SK, AC, AC, SK, SK, JA, CR }, 	 //	 4	 620
{ AC, QN, QN, QN, JA, LO, QN, QN, SK, JA, AC, SK, SK, JA, JA }, 	 //	 5	 620
{ AC, QN, QN, QN, JA, LO, QN, QN, SK, WN, AC, SK, SK, JA, TN }, 	 //	 6	 620
{ AC, QN, QN, QN, TN, LO, QN, QN, SK, TN, AC, SK, SK, JA, TN }, 	 //	 7	 620
{ AC, QN, QN, QN, TN, LO, QN, QN, SK, ST, AC, SK, SK, JA, AC }, 	 //	 8	 620
{ AC, QN, QN, QN, KN, LO, QN, QN, SK, QN, AC, SK, SK, JA, PF }, 	 //	 9	 620
{ AC, QN, QN, QN, TN, LO, QN, QN, SK, AC, AC, SK, SK, JA, AC }, 	 //	 10	 620
{ AC, QN, QN, QN, KN, LO, QN, QN, SK, KN, AC, SK, SK, JA, KN }, 	 //	 11	 620
{ AC, QN, QN, QN, KN, LO, QN, QN, SK, KN, AC, SK, SK, JA, CR }, 	 //	 12	 620
{ AC, QN, QN, QN, SK, LO, QN, SK, SK, QN, AC, SK, JA, JA, QN }, 	 //	 13	 620
{ AC, QN, QN, QN, AC, LO, QN, SK, SK, AC, AC, SK, JA, JA, SK }, 	 //	 14	 620
{ AC, QN, QN, QN, AC, LO, SK, QN, QN, AC, AC, JA, SK, SK, CR }, 	 //	 15	 620
{ AC, QN, QN, QN, TN, LO, SK, QN, QN, TN, AC, JA, SK, SK, ST }, 	 //	 16	 620
{ AC, QN, QN, QN, TN, LO, SK, QN, QN, ST, AC, JA, SK, SK, AC }, 	 //	 17	 620
{ AC, KN, QN, QN, QN, LO, SK, QN, QN, PF, AC, QN, SK, SK, JA }, 	 //	 18	 620
{ AC, QN, QN, QN, KN, LO, KN, QN, SK, KN, AC, AC, SK, JA, SK }, 	 //	 19	 620
{ AC, QN, QN, QN, AC, LO, KN, QN, SK, SK, AC, AC, SK, JA, KN }, 	 //	 20	 620
{ LO, QN, QN, QN, KN, AC, QN, QN, SK, KN, AC, QN, SK, JA, SK }, 	 //	 21	 620
{ LO, QN, QN, QN, KN, AC, QN, QN, SK, SK, AC, QN, SK, JA, QN }, 	 //	 22	 620
{ LO, QN, QN, QN, AC, AC, QN, QN, SK, LO, AC, SK, SK, JA, AC }, 	 //	 23	 620
{ LO, QN, QN, QN, AC, AC, QN, QN, SK, AC, AC, SK, SK, JA, CR }, 	 //	 24	 620
{ LO, QN, QN, QN, TN, AC, QN, QN, SK, TN, AC, SK, SK, JA, ST }, 	 //	 25	 620
{ LO, QN, QN, QN, ST, AC, QN, QN, SK, AC, AC, SK, SK, JA, KN }, 	 //	 26	 620
{ LO, QN, QN, QN, KN, AC, QN, QN, SK, KN, AC, SK, SK, JA, KN }, 	 //	 27	 620
{ LO, QN, QN, QN, KN, AC, QN, SK, SK, KN, AC, SK, JA, JA, SK }, 	 //	 28	 620
{ LO, QN, QN, QN, KN, AC, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 29	 620
{ LO, QN, QN, QN, SH, AC, SK, QN, QN, JA, AC, JA, SK, SK, JA }, 	 //	 30	 620
{ LO, QN, QN, QN, KN, AC, ST, QN, SK, KN, AC, JA, SK, JA, SK }, 	 //	 31	 620
{ LO, KN, QN, QN, QN, AC, KN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 32	 620
{ LO, KN, QN, QN, QN, AC, SK, QN, QN, KN, AC, QN, SK, SK, AC }, 	 //	 33	 620
{ LO, QN, QN, QN, SK, AC, KN, SK, SK, QN, AC, AC, JA, JA, QN }, 	 //	 34	 620
{ LO, QN, QN, QN, AC, AC, KN, SK, SK, AC, AC, AC, JA, JA, SK }, 	 //	 35	 620
{ LO, QN, QN, QN, SK, AC, KN, SK, SK, KN, AC, AC, JA, JA, KN }, 	 //	 36	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, KN, AC, QN, SK, JA, SK }, 	 //	 37	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, SK, AC, QN, SK, JA, QN }, 	 //	 38	 620
{ AC, QN, QN, QN, AC, AC, QN, SK, SK, AC, AC, QN, JA, JA, SK }, 	 //	 39	 620
{ AC, QN, QN, QN, AC, AC, QN, QN, SK, AC, AC, SK, SK, JA, CR }, 	 //	 40	 620
{ AC, QN, QN, QN, AC, AC, QN, QN, SK, KN, AC, SK, SK, JA, QN }, 	 //	 41	 620
{ AC, QN, QN, QN, TN, AC, QN, QN, SK, AC, AC, SK, SK, JA, AC }, 	 //	 42	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, AC, AC, SK, SK, JA, LO }, 	 //	 43	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, QN, LO, AC, JA, SK, SK, AC }, 	 //	 44	 620
{ AC, QN, QN, QN, TN, AC, SK, QN, QN, ST, AC, JA, SK, SK, AC }, 	 //	 45	 620
{ AC, QN, QN, QN, ST, AC, SK, QN, QN, AC, AC, JA, SK, SK, KN }, 	 //	 46	 620
{ AC, QN, QN, QN, KN, AC, SK, QN, QN, AC, AC, JA, SK, SK, LO }, 	 //	 47	 620
{ AC, KN, QN, QN, QN, AC, KN, QN, SK, QN, AC, SK, SK, JA, QN }, 	 //	 48	 620
{ AC, KN, QN, QN, KN, AC, SK, QN, QN, SK, AC, QN, SK, SK, QN }, 	 //	 49	 620
{ AC, KN, QN, QN, KN, AC, SK, QN, QN, QN, AC, QN, SK, SK, PF }, 	 //	 50	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, SK, ST, QN, SK, JA, QN }, 	 //	 51	 620
{ AC, QN, QN, QN, KN, AC, QN, SK, SK, KN, ST, QN, JA, JA, SK }, 	 //	 52	 620
{ AC, QN, QN, QN, AC, AC, QN, SK, SK, AC, ST, QN, JA, JA, SK }, 	 //	 53	 620
{ AC, QN, QN, QN, SK, AC, QN, SK, SK, KN, ST, QN, JA, JA, KN }, 	 //	 54	 620
{ AC, QN, QN, QN, LO, AC, QN, QN, SK, AC, ST, SK, SK, JA, AC }, 	 //	 55	 620
{ AC, QN, QN, QN, WN, AC, QN, QN, SK, TN, ST, SK, SK, JA, TN }, 	 //	 56	 620
{ AC, QN, QN, QN, PF, AC, QN, QN, SK, JA, ST, SK, SK, JA, TN }, 	 //	 57	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, AC, ST, SK, SK, JA, LO }, 	 //	 58	 620
{ AC, QN, QN, QN, KN, AC, QN, SK, SK, KN, ST, SK, JA, JA, SK }, 	 //	 59	 620
{ AC, QN, QN, QN, AC, AC, QN, SK, SK, AC, ST, SK, JA, JA, SK }, 	 //	 60	 620
{ AC, QN, QN, QN, SK, AC, QN, SK, SK, KN, ST, SK, JA, JA, KN }, 	 //	 61	 620
{ AC, QN, QN, QN, JA, AC, SK, QN, QN, JA, ST, JA, SK, SK, JA }, 	 //	 62	 620
{ AC, QN, QN, QN, WN, AC, SK, QN, QN, TN, ST, JA, SK, SK, TN }, 	 //	 63	 620
{ AC, QN, QN, QN, ST, AC, SK, QN, QN, AC, ST, JA, SK, SK, KN }, 	 //	 64	 620
{ AC, QN, QN, QN, TN, AC, SK, QN, QN, AC, ST, JA, SK, SK, AC }, 	 //	 65	 620
{ AC, KN, QN, QN, QN, AC, KN, QN, SK, QN, ST, SK, SK, JA, QN }, 	 //	 66	 620
{ AC, KN, QN, QN, QN, AC, KN, QN, SK, KN, ST, SK, SK, JA, AC }, 	 //	 67	 620
{ AC, KN, QN, QN, QN, AC, SK, QN, QN, PF, ST, QN, SK, SK, JA }, 	 //	 68	 620
{ AC, QN, QN, QN, SK, AC, KN, SK, SK, QN, ST, AC, JA, JA, QN }, 	 //	 69	 620
{ AC, QN, QN, QN, KN, ST, QN, SK, SK, KN, KN, QN, JA, JA, SK }, 	 //	 70	 620
{ AC, QN, QN, QN, AC, ST, QN, SK, SK, AC, KN, QN, JA, JA, SK }, 	 //	 71	 620
{ AC, QN, QN, QN, SH, ST, QN, QN, SK, JA, KN, SK, SK, JA, JA }, 	 //	 72	 620
{ AC, QN, QN, QN, JA, ST, QN, QN, SK, JA, KN, SK, SK, JA, WN }, 	 //	 73	 620
{ AC, QN, QN, QN, TN, ST, QN, QN, SK, TN, KN, SK, SK, JA, ST }, 	 //	 74	 620
{ AC, QN, QN, QN, TN, ST, QN, QN, SK, AC, KN, SK, SK, JA, AC }, 	 //	 75	 620
{ AC, QN, QN, QN, KN, ST, QN, QN, SK, KN, KN, SK, SK, JA, KN }, 	 //	 76	 620
{ AC, QN, QN, QN, AC, ST, SK, QN, QN, LO, KN, JA, SK, SK, AC }, 	 //	 77	 620
{ AC, QN, QN, QN, KN, ST, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 78	 620
{ AC, QN, QN, QN, JA, ST, SK, QN, QN, JA, KN, JA, SK, SK, JA }, 	 //	 79	 620
{ AC, QN, QN, QN, TN, ST, SK, QN, QN, TN, KN, JA, SK, SK, TN }, 	 //	 80	 620
{ AC, QN, QN, QN, PF, ST, SK, QN, QN, JA, KN, JA, SK, SK, TN }, 	 //	 81	 620
{ AC, QN, QN, QN, KN, ST, SK, QN, QN, AC, KN, JA, SK, SK, LO }, 	 //	 82	 620
{ AC, QN, QN, QN, AC, ST, SK, SK, QN, AC, KN, JA, JA, SK, SK }, 	 //	 83	 620
{ AC, QN, QN, QN, AC, ST, ST, QN, SK, AC, KN, JA, SK, JA, SK }, 	 //	 84	 620
{ AC, KN, QN, QN, QN, ST, KN, QN, SK, KN, KN, SK, SK, JA, AC }, 	 //	 85	 620
{ AC, KN, QN, QN, QN, ST, SK, QN, QN, PF, KN, QN, SK, SK, JA }, 	 //	 86	 620
{ AC, QN, QN, QN, SK, ST, KN, SK, SK, KN, KN, AC, JA, JA, KN }, 	 //	 87	 620
{ ST, QN, QN, QN, AC, KN, QN, QN, SK, SK, KN, QN, SK, JA, KN }, 	 //	 88	 620
{ ST, QN, QN, QN, KN, KN, QN, SK, SK, KN, KN, QN, JA, JA, SK }, 	 //	 89	 620
{ ST, QN, QN, QN, AC, KN, QN, SK, SK, AC, KN, QN, JA, JA, SK }, 	 //	 90	 620
{ ST, QN, QN, QN, TN, KN, QN, QN, SK, TN, KN, SK, SK, JA, ST }, 	 //	 91	 620
{ ST, QN, QN, QN, ST, KN, QN, QN, SK, AC, KN, SK, SK, JA, KN }, 	 //	 92	 620
{ ST, QN, QN, QN, KN, KN, QN, QN, SK, QN, KN, SK, SK, JA, PF }, 	 //	 93	 620
{ ST, QN, QN, QN, KN, KN, QN, QN, SK, KN, KN, SK, SK, JA, KN }, 	 //	 94	 620
{ ST, QN, QN, QN, KN, KN, QN, SK, SK, KN, KN, SK, JA, JA, SK }, 	 //	 95	 620
{ ST, QN, QN, QN, AC, KN, SK, QN, QN, LO, KN, JA, SK, SK, AC }, 	 //	 96	 620
{ ST, QN, QN, QN, JA, KN, SK, QN, QN, JA, KN, JA, SK, SK, JA }, 	 //	 97	 620
{ ST, QN, QN, QN, TN, KN, SK, QN, QN, ST, KN, JA, SK, SK, AC }, 	 //	 98	 620
{ ST, QN, QN, QN, AC, KN, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 99	 620
{ ST, QN, QN, QN, KN, KN, ST, QN, SK, SK, KN, JA, SK, JA, QN }, 	 //	 100	 620
{ ST, KN, QN, QN, KN, KN, SK, QN, QN, QN, KN, QN, SK, SK, PF }, 	 //	 101	 620
{ ST, QN, QN, QN, AC, KN, KN, QN, SK, SK, KN, AC, SK, JA, KN }, 	 //	 102	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, SK, KN, QN, SK, JA, QN }, 	 //	 103	 620
{ KN, QN, QN, QN, AC, KN, QN, QN, SK, AC, KN, SK, SK, JA, CR }, 	 //	 104	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, KN, KN, SK, SK, JA, CR }, 	 //	 105	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, AC, KN, SK, SK, JA, LO }, 	 //	 106	 620
{ KN, QN, QN, QN, SK, KN, QN, SK, SK, QN, KN, SK, JA, JA, QN }, 	 //	 107	 620
{ KN, QN, QN, QN, LO, KN, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 108	 620
{ KN, QN, QN, QN, KN, KN, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 109	 620
{ KN, QN, QN, QN, SH, KN, SK, QN, QN, JA, KN, JA, SK, SK, JA }, 	 //	 110	 620
{ KN, QN, QN, QN, WN, KN, SK, QN, QN, TN, KN, JA, SK, SK, TN }, 	 //	 111	 620
{ KN, QN, QN, QN, AC, KN, ST, QN, SK, AC, KN, JA, SK, JA, SK }, 	 //	 112	 620
{ KN, KN, QN, QN, AC, KN, SK, QN, QN, KN, KN, QN, SK, SK, QN }, 	 //	 113	 620
{ KN, KN, QN, SK, SK, KN, SK, SK, QN, QN, KN, QN, JA, KN, QN }, 	 //	 114	 620
{ KN, QN, QN, QN, AC, KN, KN, QN, SK, SK, KN, AC, SK, JA, KN }, 	 //	 115	 620
{ KN, QN, QN, QN, AC, KN, QN, QN, SK, AC, SK, QN, SK, JA, SK }, 	 //	 116	 620
{ KN, QN, QN, QN, SK, KN, QN, SK, SK, QN, SK, QN, JA, JA, QN }, 	 //	 117	 620
{ KN, QN, QN, QN, SK, KN, QN, SK, SK, KN, SK, QN, JA, JA, KN }, 	 //	 118	 620
{ KN, QN, AC, QN, KN, KN, QN, KN, QN, KN, SK, SK, QN, SK, SK }, 	 //	 119	 620
{ KN, QN, KN, QN, AC, KN, QN, QN, QN, AC, SK, SK, PF, SK, SK }, 	 //	 120	 620
{ KN, QN, AC, KN, SK, KN, QN, PF, SK, QN, SK, SK, QN, QN, QN }, 	 //	 121	 620
{ KN, QN, AC, SK, SK, KN, QN, PF, QN, QN, SK, SK, QN, KN, QN }, 	 //	 122	 620
{ KN, QN, PF, KN, KN, KN, QN, QN, SK, SK, SK, SK, QN, QN, QN }, 	 //	 123	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, KN, SK, SK, QN, JA, SK }, 	 //	 124	 620
{ KN, QN, QN, QN, AC, KN, QN, QN, SK, SK, SK, SK, QN, JA, KN }, 	 //	 125	 620
{ KN, QN, QN, QN, SK, KN, QN, QN, SK, KN, SK, SK, QN, JA, KN }, 	 //	 126	 620
{ KN, QN, QN, QN, AC, KN, QN, SK, SK, LO, SK, SK, JA, JA, AC }, 	 //	 127	 620
{ KN, QN, QN, QN, LO, KN, QN, SK, SK, AC, SK, SK, JA, JA, AC }, 	 //	 128	 620
{ KN, QN, QN, QN, TN, KN, QN, SK, SK, ST, SK, SK, JA, JA, AC }, 	 //	 129	 620
{ KN, QN, QN, QN, JA, KN, QN, SK, SK, TN, SK, SK, JA, JA, AC }, 	 //	 130	 620
{ KN, QN, KN, QN, KN, KN, QN, PF, QN, KN, SK, SK, QN, SK, SK }, 	 //	 131	 620
{ KN, QN, KN, QN, AC, KN, QN, PF, QN, AC, SK, SK, QN, SK, SK }, 	 //	 132	 620
{ KN, QN, QN, QN, AC, KN, QN, AC, SK, SK, SK, SK, KN, JA, KN }, 	 //	 133	 620
{ KN, QN, AC, KN, KN, KN, SK, KN, SK, SK, SK, JA, QN, QN, QN }, 	 //	 134	 620
{ KN, QN, AC, KN, SK, KN, SK, KN, SK, QN, SK, JA, QN, QN, QN }, 	 //	 135	 620
{ KN, QN, KN, SK, SK, KN, SK, QN, QN, QN, SK, JA, PF, KN, QN }, 	 //	 136	 620
{ KN, QN, QN, QN, AC, KN, SK, PF, QN, AC, SK, JA, KN, SK, SK }, 	 //	 137	 620
{ KN, QN, QN, QN, SK, KN, SK, PF, SK, QN, SK, JA, KN, JA, QN }, 	 //	 138	 620
{ KN, QN, QN, QN, AC, KN, SK, PF, SK, SK, SK, JA, KN, JA, KN }, 	 //	 139	 620
{ KN, QN, QN, SK, SK, KN, SK, PF, QN, QN, SK, JA, KN, KN, QN }, 	 //	 140	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, SK, QN, SK, JA, QN, JA, QN }, 	 //	 141	 620
{ KN, QN, QN, QN, AC, KN, SK, QN, SK, AC, SK, JA, QN, JA, SK }, 	 //	 142	 620
{ KN, QN, QN, WN, KN, KN, SK, QN, QN, SK, SK, JA, SK, QN, QN }, 	 //	 143	 620
{ KN, QN, QN, WN, QN, KN, SK, QN, QN, QN, SK, JA, SK, QN, SH }, 	 //	 144	 620
{ KN, QN, QN, QN, JA, KN, SK, QN, QN, JA, SK, JA, SK, QN, JA }, 	 //	 145	 620
{ KN, QN, QN, QN, JA, KN, SK, QN, QN, WN, SK, JA, SK, QN, TN }, 	 //	 146	 620
{ KN, QN, QN, QN, TN, KN, SK, QN, QN, TN, SK, JA, SK, QN, ST }, 	 //	 147	 620
{ KN, QN, QN, KN, KN, KN, SK, QN, QN, SK, SK, JA, SK, ST, QN }, 	 //	 148	 620
{ KN, QN, QN, KN, AC, KN, SK, QN, QN, KN, SK, JA, SK, ST, QN }, 	 //	 149	 620
{ KN, QN, QN, KN, CR, KN, SK, QN, QN, QN, SK, JA, SK, ST, KN }, 	 //	 150	 620
{ KN, QN, QN, QN, KN, KN, SK, QN, ST, KN, SK, JA, SK, JA, KN }, 	 //	 151	 620
{ KN, QN, QN, QN, KN, KN, SK, QN, ST, SK, SK, JA, SK, JA, QN }, 	 //	 152	 620
{ KN, QN, QN, QN, JA, KN, SK, QN, ST, JA, SK, JA, SK, JA, WN }, 	 //	 153	 620
{ KN, QN, QN, QN, PF, KN, SK, QN, ST, JA, SK, JA, SK, JA, TN }, 	 //	 154	 620
{ KN, QN, QN, QN, TN, KN, SK, QN, ST, AC, SK, JA, SK, JA, AC }, 	 //	 155	 620
{ KN, QN, QN, QN, AC, KN, SK, QN, ST, AC, SK, JA, SK, JA, SK }, 	 //	 156	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, ST, KN, SK, JA, SK, JA, KN }, 	 //	 157	 620
{ KN, QN, QN, QN, LO, KN, SK, QN, KN, AC, SK, JA, SK, AC, AC }, 	 //	 158	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, KN, QN, SK, JA, SK, AC, QN }, 	 //	 159	 620
{ KN, QN, QN, QN, PF, KN, SK, QN, KN, JA, SK, JA, SK, AC, TN }, 	 //	 160	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, KN, KN, SK, JA, SK, AC, KN }, 	 //	 161	 620
{ KN, QN, QN, QN, LO, KN, SK, SK, QN, AC, SK, JA, JA, QN, AC }, 	 //	 162	 620
{ KN, QN, QN, QN, CR, KN, SK, SK, QN, QN, SK, JA, JA, QN, KN }, 	 //	 163	 620
{ KN, QN, QN, QN, SH, KN, SK, SK, QN, JA, SK, JA, JA, SK, JA }, 	 //	 164	 620
{ KN, QN, QN, QN, JA, KN, SK, SK, QN, WN, SK, JA, JA, SK, TN }, 	 //	 165	 620
{ KN, QN, QN, QN, TN, KN, SK, SK, QN, ST, SK, JA, JA, SK, AC }, 	 //	 166	 620
{ KN, QN, QN, QN, JA, KN, SK, SK, QN, TN, SK, JA, JA, SK, AC }, 	 //	 167	 620
{ KN, QN, QN, QN, TN, KN, SK, SK, QN, AC, SK, JA, JA, SK, AC }, 	 //	 168	 620
{ KN, QN, QN, QN, SK, KN, SK, SK, QN, KN, SK, JA, JA, SK, KN }, 	 //	 169	 620
{ KN, QN, QN, QN, CR, KN, SK, SK, QN, QN, SK, JA, JA, SK, KN }, 	 //	 170	 620
{ KN, QN, QN, QN, KN, KN, SK, SK, QN, AC, SK, JA, JA, SK, LO }, 	 //	 171	 620
{ KN, QN, QN, KN, SK, KN, SK, SK, QN, QN, SK, JA, JA, ST, QN }, 	 //	 172	 620
{ KN, QN, QN, QN, JA, KN, SK, SK, KN, WN, SK, JA, JA, AC, TN }, 	 //	 173	 620
{ KN, QN, QN, QN, TN, KN, SK, SK, KN, TN, SK, JA, JA, AC, ST }, 	 //	 174	 620
{ KN, QN, QN, QN, AC, KN, SK, SK, KN, SK, SK, JA, JA, AC, KN }, 	 //	 175	 620
{ KN, QN, QN, QN, KN, KN, SK, SK, KN, KN, SK, JA, JA, AC, KN }, 	 //	 176	 620
{ KN, QN, QN, QN, AC, KN, SK, AC, QN, AC, SK, JA, KN, SK, SK }, 	 //	 177	 620
{ KN, QN, QN, SK, SK, KN, SK, AC, QN, QN, SK, JA, KN, KN, QN }, 	 //	 178	 620
{ KN, QN, QN, QN, KN, KN, ST, QN, SK, KN, SK, JA, SK, JA, SK }, 	 //	 179	 620
{ KN, QN, QN, QN, AC, KN, ST, QN, SK, AC, SK, JA, SK, JA, SK }, 	 //	 180	 620
{ KN, KN, PF, KN, SK, KN, KN, QN, SK, QN, SK, SK, QN, QN, QN }, 	 //	 181	 620
{ KN, KN, AC, KN, AC, KN, SK, KN, SK, AC, SK, QN, QN, QN, SK }, 	 //	 182	 620
{ KN, KN, AC, KN, AC, KN, SK, PF, SK, SK, SK, QN, QN, QN, KN }, 	 //	 183	 620
{ KN, KN, AC, KN, SK, KN, SK, PF, SK, KN, SK, QN, QN, QN, KN }, 	 //	 184	 620
{ KN, KN, QN, WN, KN, KN, SK, QN, QN, QN, SK, QN, SK, QN, PF }, 	 //	 185	 620
{ KN, KN, QN, QN, KN, KN, SK, QN, QN, SK, SK, QN, SK, QN, QN }, 	 //	 186	 620
{ KN, KN, QN, KN, KN, KN, SK, QN, QN, QN, SK, QN, SK, ST, PF }, 	 //	 187	 620
{ KN, KN, QN, QN, QN, KN, SK, QN, ST, SH, SK, QN, SK, JA, JA }, 	 //	 188	 620
{ KN, KN, QN, QN, QN, KN, SK, QN, ST, KN, SK, QN, SK, JA, AC }, 	 //	 189	 620
{ KN, KN, QN, QN, QN, KN, SK, QN, KN, QN, SK, QN, SK, AC, SH }, 	 //	 190	 620
{ KN, KN, QN, QN, QN, KN, SK, QN, KN, SH, SK, QN, SK, AC, JA }, 	 //	 191	 620
{ KN, KN, QN, WN, KN, KN, SK, SK, QN, SK, SK, QN, JA, QN, QN }, 	 //	 192	 620
{ KN, KN, QN, QN, KN, KN, SK, SK, QN, SK, SK, QN, JA, QN, QN }, 	 //	 193	 620
{ KN, KN, QN, QN, QN, KN, SK, SK, QN, SH, SK, QN, JA, SK, JA }, 	 //	 194	 620
{ KN, KN, QN, KN, SK, KN, SK, SK, QN, QN, SK, QN, JA, ST, QN }, 	 //	 195	 620
{ KN, KN, QN, SK, QN, KN, SK, SK, QN, QN, SK, QN, JA, KN, QN }, 	 //	 196	 620
{ KN, QN, QN, QN, KN, KN, KN, QN, SK, SK, SK, AC, SK, JA, QN }, 	 //	 197	 620
{ KN, QN, QN, QN, AC, KN, KN, QN, SK, AC, SK, AC, SK, JA, SK }, 	 //	 198	 620
{ KN, QN, QN, QN, KN, KN, KN, SK, SK, KN, SK, AC, JA, JA, SK }, 	 //	 199	 620
{ KN, QN, QN, QN, SK, KN, KN, SK, SK, KN, SK, AC, JA, JA, KN }, 	 //	 200	 620
{ KN, ST, QN, QN, KN, SK, QN, QN, SK, SK, QN, QN, SK, JA, QN }, 	 //	 201	 620
{ KN, ST, QN, QN, KN, SK, QN, SK, SK, KN, QN, QN, JA, JA, SK }, 	 //	 202	 620
{ KN, ST, QN, QN, SK, SK, QN, SK, SK, QN, QN, QN, JA, JA, QN }, 	 //	 203	 620
{ KN, ST, QN, QN, AC, SK, QN, SK, SK, AC, QN, QN, JA, JA, SK }, 	 //	 204	 620
{ KN, QN, QN, KN, KN, SK, QN, SK, SK, KN, QN, QN, JA, QN, SK }, 	 //	 205	 620
{ KN, QN, QN, KN, SK, SK, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 206	 620
{ KN, QN, QN, KN, SK, SK, QN, SK, SK, KN, QN, QN, JA, QN, KN }, 	 //	 207	 620
{ KN, QN, QN, KN, LO, SK, QN, QN, SK, AC, QN, SK, SK, QN, AC }, 	 //	 208	 620
{ KN, QN, QN, KN, QN, SK, QN, QN, SK, KN, QN, SK, SK, QN, AC }, 	 //	 209	 620
{ KN, QN, QN, KN, KN, SK, QN, QN, SK, AC, QN, SK, SK, QN, LO }, 	 //	 210	 620
{ KN, QN, AC, KN, KN, SK, SK, KN, SK, SK, QN, JA, QN, QN, QN }, 	 //	 211	 620
{ KN, QN, QN, QN, AC, SK, SK, PF, QN, AC, QN, JA, KN, SK, SK }, 	 //	 212	 620
{ KN, QN, QN, QN, SK, SK, SK, PF, SK, KN, QN, JA, KN, JA, KN }, 	 //	 213	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, QN, KN, QN, JA, QN, SK, SK }, 	 //	 214	 620
{ KN, QN, QN, QN, AC, SK, SK, QN, SK, SK, QN, JA, QN, JA, KN }, 	 //	 215	 620
{ KN, QN, QN, WN, CR, SK, SK, QN, QN, QN, QN, JA, SK, QN, KN }, 	 //	 216	 620
{ KN, QN, QN, QN, AC, SK, SK, QN, QN, LO, QN, JA, SK, QN, AC }, 	 //	 217	 620
{ KN, QN, QN, QN, JA, SK, SK, QN, QN, JA, QN, JA, SK, QN, JA }, 	 //	 218	 620
{ KN, QN, QN, QN, TN, SK, SK, QN, QN, AC, QN, JA, SK, QN, AC }, 	 //	 219	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, QN, KN, QN, JA, SK, QN, CR }, 	 //	 220	 620
{ KN, QN, QN, QN, AC, SK, SK, QN, ST, AC, QN, JA, SK, JA, AC }, 	 //	 221	 620
{ KN, QN, QN, QN, JA, SK, SK, QN, ST, JA, QN, JA, SK, JA, JA }, 	 //	 222	 620
{ KN, QN, QN, QN, JA, SK, SK, QN, ST, WN, QN, JA, SK, JA, TN }, 	 //	 223	 620
{ KN, QN, QN, QN, AC, SK, SK, QN, ST, KN, QN, JA, SK, JA, QN }, 	 //	 224	 620
{ KN, QN, QN, QN, JA, SK, SK, QN, ST, TN, QN, JA, SK, JA, AC }, 	 //	 225	 620
{ KN, QN, QN, QN, AC, SK, SK, QN, ST, SK, QN, JA, SK, JA, KN }, 	 //	 226	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, ST, KN, QN, JA, SK, JA, CR }, 	 //	 227	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, ST, AC, QN, JA, SK, JA, LO }, 	 //	 228	 620
{ KN, QN, QN, SK, QN, SK, SK, QN, QN, QN, QN, JA, SK, KN, SH }, 	 //	 229	 620
{ KN, QN, QN, SK, CR, SK, SK, QN, QN, QN, QN, JA, SK, KN, KN }, 	 //	 230	 620
{ KN, QN, QN, QN, LO, SK, SK, QN, KN, AC, QN, JA, SK, AC, AC }, 	 //	 231	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, KN, KN, QN, JA, SK, AC, KN }, 	 //	 232	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, KN, KN, QN, JA, SK, AC, SK }, 	 //	 233	 620
{ KN, QN, QN, QN, SH, SK, SK, QN, KN, JA, QN, JA, SK, AC, JA }, 	 //	 234	 620
{ KN, QN, QN, QN, JA, SK, SK, QN, KN, JA, QN, JA, SK, AC, WN }, 	 //	 235	 620
{ KN, QN, QN, QN, SK, SK, SK, QN, KN, KN, QN, JA, SK, AC, KN }, 	 //	 236	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, KN, KN, QN, JA, SK, AC, CR }, 	 //	 237	 620
{ KN, QN, QN, QN, CR, SK, SK, QN, KN, QN, QN, JA, SK, AC, KN }, 	 //	 238	 620
{ KN, QN, QN, QN, KN, SK, SK, QN, KN, AC, QN, JA, SK, AC, LO }, 	 //	 239	 620
{ KN, QN, QN, QN, AC, SK, SK, AC, SK, AC, QN, JA, KN, JA, SK }, 	 //	 240	 620
{ KN, KN, QN, QN, KN, SK, QN, QN, SK, KN, QN, ST, SK, JA, SK }, 	 //	 241	 620
{ KN, KN, QN, QN, KN, SK, QN, QN, SK, SK, QN, ST, SK, JA, QN }, 	 //	 242	 620
{ KN, KN, QN, QN, SK, SK, QN, SK, SK, KN, QN, ST, JA, JA, KN }, 	 //	 243	 620
{ KN, QN, QN, QN, KN, SK, ST, QN, SK, KN, QN, JA, SK, JA, SK }, 	 //	 244	 620
{ KN, KN, QN, QN, QN, SK, KN, QN, SK, QN, QN, SK, SK, JA, QN }, 	 //	 245	 620
{ KN, KN, QN, QN, QN, SK, KN, QN, SK, SH, QN, SK, SK, JA, JA }, 	 //	 246	 620
{ KN, KN, AC, QN, KN, SK, SK, KN, SK, KN, QN, QN, QN, JA, SK }, 	 //	 247	 620
{ KN, KN, AC, QN, KN, SK, SK, PF, QN, KN, QN, QN, QN, SK, SK }, 	 //	 248	 620
{ KN, KN, PF, QN, SK, SK, SK, QN, SK, QN, QN, QN, QN, JA, QN }, 	 //	 249	 620
{ KN, KN, PF, QN, AC, SK, SK, QN, SK, SK, QN, QN, QN, JA, KN }, 	 //	 250	 620
{ KN, KN, PF, SK, SK, SK, SK, QN, QN, KN, QN, QN, QN, KN, KN }, 	 //	 251	 620
{ KN, KN, QN, QN, KN, SK, SK, QN, QN, KN, QN, QN, QN, SK, SK }, 	 //	 252	 620
{ KN, KN, QN, QN, KN, SK, SK, QN, SK, KN, QN, QN, QN, JA, SK }, 	 //	 253	 620
{ KN, KN, QN, KN, KN, SK, SK, QN, KN, KN, QN, QN, QN, SK, SK }, 	 //	 254	 620
{ KN, KN, QN, KN, AC, SK, SK, QN, KN, AC, QN, QN, QN, SK, SK }, 	 //	 255	 620
{ KN, KN, QN, SK, SK, SK, SK, QN, QN, KN, QN, QN, QN, KN, KN }, 	 //	 256	 620
{ KN, KN, QN, WN, KN, SK, SK, QN, QN, QN, QN, QN, SK, QN, PF }, 	 //	 257	 620
{ KN, KN, QN, QN, QN, SK, SK, QN, QN, PF, QN, QN, SK, QN, JA }, 	 //	 258	 620
{ KN, KN, QN, QN, QN, SK, SK, QN, ST, KN, QN, QN, SK, JA, AC }, 	 //	 259	 620
{ KN, KN, QN, QN, QN, SK, SK, QN, KN, SH, QN, QN, SK, AC, JA }, 	 //	 260	 620
{ KN, KN, PF, SK, SK, SK, SK, QN, QN, QN, QN, QN, AC, KN, QN }, 	 //	 261	 620
{ KN, KN, QN, SK, SK, SK, SK, AC, QN, QN, QN, QN, KN, KN, QN }, 	 //	 262	 620
{ KN, SK, QN, QN, KN, SK, QN, QN, SK, KN, QN, KN, SK, JA, SK }, 	 //	 263	 620
{ KN, SK, QN, KN, KN, SK, QN, QN, SK, SK, QN, KN, SK, QN, QN }, 	 //	 264	 620
{ KN, SK, QN, KN, AC, SK, QN, QN, SK, SK, QN, KN, SK, QN, KN }, 	 //	 265	 620
{ KN, SK, QN, QN, SK, SK, QN, SK, SK, QN, QN, KN, JA, JA, QN }, 	 //	 266	 620
{ KN, SK, QN, KN, SK, SK, QN, SK, SK, KN, QN, KN, JA, QN, KN }, 	 //	 267	 620
{ KN, QN, QN, QN, KN, SK, KN, QN, SK, KN, QN, AC, SK, JA, SK }, 	 //	 268	 620
{ KN, QN, QN, QN, KN, SK, KN, QN, SK, SK, QN, AC, SK, JA, QN }, 	 //	 269	 620
{ KN, QN, QN, QN, SK, SK, KN, SK, SK, QN, QN, AC, JA, JA, QN }, 	 //	 270	 620
{ KN, QN, QN, QN, SK, SK, KN, SK, SK, KN, QN, AC, JA, JA, KN }, 	 //	 271	 620
{ SK, ST, QN, QN, SK, QN, QN, SK, SK, KN, QN, QN, JA, JA, KN }, 	 //	 272	 620
{ SK, ST, QN, KN, SK, QN, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 273	 620
{ SK, QN, QN, KN, KN, QN, QN, SK, SK, KN, QN, QN, JA, QN, SK }, 	 //	 274	 620
{ SK, QN, QN, KN, SK, QN, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 275	 620
{ SK, QN, QN, KN, AC, QN, QN, SK, SK, AC, QN, SK, JA, QN, SK }, 	 //	 276	 620
{ SK, QN, AC, KN, KN, QN, SK, KN, SK, SK, QN, JA, QN, QN, QN }, 	 //	 277	 620
{ SK, QN, QN, QN, KN, QN, SK, PF, QN, KN, QN, JA, KN, SK, SK }, 	 //	 278	 620
{ SK, QN, QN, QN, SK, QN, SK, PF, SK, QN, QN, JA, KN, JA, QN }, 	 //	 279	 620
{ SK, QN, QN, QN, AC, QN, SK, PF, SK, AC, QN, JA, KN, JA, SK }, 	 //	 280	 620
{ SK, QN, AC, KN, KN, QN, SK, PF, SK, SK, QN, JA, QN, QN, QN }, 	 //	 281	 620
{ SK, QN, AC, KN, SK, QN, SK, PF, SK, QN, QN, JA, QN, QN, QN }, 	 //	 282	 620
{ SK, QN, QN, QN, AC, QN, SK, QN, QN, AC, QN, JA, QN, SK, SK }, 	 //	 283	 620
{ SK, QN, QN, QN, SK, QN, SK, QN, SK, QN, QN, JA, QN, JA, QN }, 	 //	 284	 620
{ SK, QN, QN, QN, SK, QN, SK, QN, SK, KN, QN, JA, QN, JA, KN }, 	 //	 285	 620
{ SK, QN, QN, KN, SK, QN, SK, QN, SK, QN, QN, JA, QN, QN, QN }, 	 //	 286	 620
{ SK, QN, QN, WN, KN, QN, SK, SK, QN, SK, QN, JA, JA, QN, QN }, 	 //	 287	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, LO, QN, JA, JA, QN, AC }, 	 //	 288	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, QN, CR }, 	 //	 289	 620
{ SK, QN, QN, QN, KN, QN, SK, SK, QN, QN, QN, JA, JA, QN, PF }, 	 //	 290	 620
{ SK, QN, QN, QN, TN, QN, SK, SK, QN, AC, QN, JA, JA, QN, AC }, 	 //	 291	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, QN, AC }, 	 //	 292	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, QN, SK }, 	 //	 293	 620
{ SK, QN, QN, QN, SK, QN, SK, SK, QN, KN, QN, JA, JA, QN, KN }, 	 //	 294	 620
{ SK, QN, QN, QN, CR, QN, SK, SK, QN, QN, QN, JA, JA, QN, KN }, 	 //	 295	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, SK, AC }, 	 //	 296	 620
{ SK, QN, QN, QN, JA, QN, SK, SK, QN, JA, QN, JA, JA, SK, JA }, 	 //	 297	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, QN, AC, QN, JA, JA, SK, AC }, 	 //	 298	 620
{ SK, QN, QN, QN, KN, QN, SK, SK, QN, KN, QN, JA, JA, SK, KN }, 	 //	 299	 620
{ SK, QN, QN, KN, SK, QN, SK, SK, QN, QN, QN, JA, JA, ST, QN }, 	 //	 300	 620
{ SK, QN, QN, KN, QN, QN, SK, SK, QN, QN, QN, JA, JA, ST, QN }, 	 //	 301	 620
{ SK, QN, QN, SK, QN, QN, SK, SK, QN, QN, QN, JA, JA, KN, QN }, 	 //	 302	 620
{ SK, QN, QN, SK, AC, QN, SK, SK, QN, KN, QN, JA, JA, KN, QN }, 	 //	 303	 620
{ SK, QN, QN, QN, SH, QN, SK, SK, KN, JA, QN, JA, JA, AC, JA }, 	 //	 304	 620
{ SK, QN, QN, QN, JA, QN, SK, SK, KN, JA, QN, JA, JA, AC, WN }, 	 //	 305	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, KN, AC, QN, JA, JA, AC, AC }, 	 //	 306	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, KN, AC, QN, JA, JA, AC, SK }, 	 //	 307	 620
{ SK, QN, QN, QN, AC, QN, SK, SK, KN, SK, QN, JA, JA, AC, KN }, 	 //	 308	 620
{ SK, QN, QN, QN, SK, QN, SK, SK, KN, KN, QN, JA, JA, AC, KN }, 	 //	 309	 620
{ SK, QN, QN, QN, KN, QN, SK, AC, QN, KN, QN, JA, KN, SK, SK }, 	 //	 310	 620
{ SK, QN, QN, QN, KN, QN, SK, AC, SK, KN, QN, JA, KN, JA, SK }, 	 //	 311	 620
{ SK, QN, QN, QN, SK, QN, SK, AC, SK, QN, QN, JA, KN, JA, QN }, 	 //	 312	 620
{ SK, QN, QN, QN, SK, QN, SK, AC, SK, KN, QN, JA, KN, JA, KN }, 	 //	 313	 620
{ SK, SK, PF, SK, SK, QN, JA, QN, QN, QN, QN, JA, QN, KN, QN }, 	 //	 314	 620
{ SK, SK, QN, QN, AC, QN, JA, QN, QN, KN, QN, JA, SK, SK, QN }, 	 //	 315	 620
{ SK, SK, QN, QN, QN, QN, JA, QN, QN, PF, QN, JA, SK, SK, JA }, 	 //	 316	 620
{ SK, SK, QN, QN, CR, QN, JA, QN, QN, QN, QN, JA, SK, SK, KN }, 	 //	 317	 620
{ SK, SK, QN, QN, QN, QN, JA, QN, SK, PF, QN, JA, SK, JA, JA }, 	 //	 318	 620
{ SK, SK, QN, QN, QN, QN, JA, QN, SK, KN, QN, JA, SK, JA, AC }, 	 //	 319	 620
{ SK, SK, KN, KN, SK, QN, JA, PF, SK, QN, QN, JA, QN, QN, QN }, 	 //	 320	 620
{ SK, KN, QN, QN, SK, QN, QN, SK, SK, QN, QN, ST, JA, JA, QN }, 	 //	 321	 620
{ SK, KN, QN, KN, SK, QN, QN, SK, SK, QN, QN, ST, JA, QN, QN }, 	 //	 322	 620
{ SK, KN, QN, KN, SK, QN, QN, SK, SK, KN, QN, ST, JA, QN, KN }, 	 //	 323	 620
{ SK, KN, AC, QN, KN, QN, SK, KN, SK, SK, QN, QN, QN, JA, QN }, 	 //	 324	 620
{ SK, KN, AC, KN, AC, QN, SK, KN, KN, AC, QN, QN, QN, SK, SK }, 	 //	 325	 620
{ SK, KN, AC, SK, SK, QN, SK, KN, QN, KN, QN, QN, QN, KN, KN }, 	 //	 326	 620
{ SK, KN, AC, QN, AC, QN, SK, PF, SK, SK, QN, QN, QN, JA, KN }, 	 //	 327	 620
{ SK, KN, PF, QN, AC, QN, SK, QN, QN, AC, QN, QN, QN, SK, SK }, 	 //	 328	 620
{ SK, KN, PF, QN, SK, QN, SK, QN, SK, QN, QN, QN, QN, JA, QN }, 	 //	 329	 620
{ SK, KN, PF, QN, SK, QN, SK, QN, SK, KN, QN, QN, QN, JA, KN }, 	 //	 330	 620
{ SK, KN, PF, SK, SK, QN, SK, QN, JA, KN, QN, QN, QN, JA, KN }, 	 //	 331	 620
{ SK, KN, QN, QN, SK, QN, SK, QN, SK, QN, QN, QN, QN, JA, QN }, 	 //	 332	 620
{ SK, KN, QN, QN, SK, QN, SK, QN, SK, KN, QN, QN, QN, JA, KN }, 	 //	 333	 620
{ SK, KN, QN, SK, SK, QN, SK, QN, JA, KN, QN, QN, QN, JA, KN }, 	 //	 334	 620
{ SK, KN, QN, KN, KN, QN, SK, QN, KN, KN, QN, QN, QN, SK, SK }, 	 //	 335	 620
{ SK, KN, QN, WN, KN, QN, SK, SK, QN, SK, QN, QN, JA, QN, QN }, 	 //	 336	 620
{ SK, KN, QN, WN, QN, QN, SK, SK, QN, QN, QN, QN, JA, QN, QN }, 	 //	 337	 620
{ SK, KN, QN, QN, SK, QN, SK, SK, QN, QN, QN, QN, JA, QN, QN }, 	 //	 338	 620
{ SK, KN, QN, QN, QN, QN, SK, SK, QN, KN, QN, QN, JA, QN, AC }, 	 //	 339	 620
{ SK, KN, QN, QN, KN, QN, SK, SK, QN, SK, QN, QN, JA, SK, QN }, 	 //	 340	 620
{ SK, KN, QN, SK, AC, QN, SK, SK, QN, KN, QN, QN, JA, KN, QN }, 	 //	 341	 620
{ SK, KN, QN, QN, QN, QN, SK, SK, KN, QN, QN, QN, JA, AC, SH }, 	 //	 342	 620
{ SK, KN, KN, QN, AC, QN, SK, PF, SK, SK, QN, QN, QN, JA, KN }, 	 //	 343	 620
{ SK, SK, AC, QN, KN, QN, QN, KN, QN, KN, QN, KN, QN, SK, SK }, 	 //	 344	 620
{ SK, SK, AC, KN, SK, QN, QN, KN, SK, QN, QN, KN, QN, QN, QN }, 	 //	 345	 620
{ SK, SK, KN, QN, AC, QN, QN, QN, SK, AC, QN, KN, PF, JA, SK }, 	 //	 346	 620
{ SK, SK, QN, QN, AC, QN, QN, PF, SK, AC, QN, KN, KN, JA, SK }, 	 //	 347	 620
{ SK, SK, QN, KN, SK, QN, QN, PF, SK, KN, QN, KN, KN, QN, KN }, 	 //	 348	 620
{ SK, SK, PF, QN, AC, QN, QN, QN, SK, SK, QN, KN, QN, JA, KN }, 	 //	 349	 620
{ SK, SK, PF, SK, SK, QN, QN, QN, JA, QN, QN, KN, QN, JA, QN }, 	 //	 350	 620
{ SK, SK, PF, KN, KN, QN, QN, QN, KN, KN, QN, KN, QN, SK, SK }, 	 //	 351	 620
{ SK, SK, PF, KN, AC, QN, QN, QN, SK, SK, QN, KN, QN, QN, KN }, 	 //	 352	 620
{ SK, SK, QN, QN, AC, QN, QN, SK, SK, LO, QN, KN, JA, JA, AC }, 	 //	 353	 620
{ SK, SK, QN, QN, CR, QN, QN, SK, SK, KN, QN, KN, JA, JA, KN }, 	 //	 354	 620
{ SK, SK, QN, QN, KN, QN, QN, SK, SK, KN, QN, KN, JA, JA, KN }, 	 //	 355	 620
{ SK, SK, QN, QN, TN, QN, QN, SK, SK, TN, QN, KN, JA, JA, TN }, 	 //	 356	 620
{ SK, SK, QN, QN, TN, QN, QN, SK, SK, ST, QN, KN, JA, JA, AC }, 	 //	 357	 620
{ SK, SK, QN, QN, AC, QN, QN, SK, SK, KN, QN, KN, JA, JA, QN }, 	 //	 358	 620
{ SK, SK, QN, KN, AC, QN, QN, SK, SK, AC, QN, KN, JA, QN, AC }, 	 //	 359	 620
{ SK, SK, QN, KN, CR, QN, QN, SK, SK, KN, QN, KN, JA, QN, KN }, 	 //	 360	 620
{ SK, SK, QN, KN, QN, QN, QN, SK, SK, QN, QN, KN, JA, QN, QN }, 	 //	 361	 620
{ SK, SK, QN, KN, TN, QN, QN, SK, SK, ST, QN, KN, JA, QN, AC }, 	 //	 362	 620
{ SK, SK, QN, KN, KN, QN, QN, SK, SK, QN, QN, KN, JA, QN, PF }, 	 //	 363	 620
{ SK, SK, QN, KN, KN, QN, QN, SK, SK, AC, QN, KN, JA, QN, LO }, 	 //	 364	 620
{ SK, SK, PF, QN, AC, QN, QN, QN, SK, SK, QN, KN, AC, JA, KN }, 	 //	 365	 620
{ SK, SK, PF, QN, SK, QN, QN, QN, SK, KN, QN, KN, AC, JA, KN }, 	 //	 366	 620
{ SK, SK, QN, QN, AC, QN, QN, AC, SK, SK, QN, KN, KN, JA, KN }, 	 //	 367	 620
{ SK, SK, QN, QN, SK, QN, QN, AC, SK, KN, QN, KN, KN, JA, KN }, 	 //	 368	 620
{ SK, QN, QN, QN, KN, QN, KN, SK, SK, KN, QN, AC, JA, JA, SK }, 	 //	 369	 620
{ SK, QN, QN, QN, AC, QN, KN, SK, SK, AC, QN, AC, JA, JA, SK }, 	 //	 370	 620
{ QN, ST, QN, KN, SK, QN, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 371	 620
{ QN, ST, QN, KN, AC, QN, QN, SK, SK, AC, QN, QN, JA, QN, SK }, 	 //	 372	 620
{ QN, QN, QN, KN, QN, QN, SK, QN, KN, QN, QN, JA, SK, SK, QN }, 	 //	 373	 620
{ QN, QN, QN, KN, SH, QN, SK, QN, KN, JA, QN, JA, SK, SK, JA }, 	 //	 374	 620
{ QN, QN, QN, KN, ST, QN, SK, QN, KN, AC, QN, JA, SK, SK, KN }, 	 //	 375	 620
{ QN, QN, QN, KN, TN, QN, SK, QN, KN, AC, QN, JA, SK, SK, AC }, 	 //	 376	 620
{ QN, KN, QN, QN, QN, QN, KN, QN, SK, SH, QN, SK, SK, JA, JA }, 	 //	 377	 620
{ QN, KN, QN, QN, QN, QN, KN, QN, SK, PF, QN, SK, SK, JA, JA }, 	 //	 378	 620
{ QN, KN, QN, QN, QN, QN, KN, QN, SK, KN, QN, SK, SK, JA, AC }, 	 //	 379	 620
{ QN, KN, QN, QN, KN, QN, SK, QN, QN, SK, QN, QN, SK, SK, QN }, 	 //	 380	 620
{ QN, SK, QN, QN, SK, QN, QN, SK, SK, QN, QN, KN, JA, JA, QN }, 	 //	 381	 620
{ QN, SK, QN, KN, SK, QN, QN, SK, SK, QN, QN, KN, JA, QN, QN }, 	 //	 382	 620
{ QN, QN, QN, KN, SK, QN, KN, SK, SK, QN, QN, AC, JA, QN, QN }, 	 //	 383	 620
{ QN, ST, QN, KN, AC, QN, QN, QN, SK, SK, SH, QN, SK, QN, KN }, 	 //	 384	 620
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, QN, SH, QN, JA, QN, QN }, 	 //	 385	 620
{ QN, QN, QN, KN, SK, QN, QN, SK, SK, KN, SH, QN, JA, QN, KN }, 	 //	 386	 620
{ QN, QN, QN, KN, KN, QN, QN, SK, SK, KN, SH, SK, JA, QN, SK }, 	 //	 387	 620
{ QN, QN, QN, KN, LO, QN, SK, QN, KN, AC, SH, JA, SK, SK, AC }, 	 //	 388	 620
{ QN, QN, QN, KN, QN, QN, SK, QN, KN, QN, SH, JA, SK, SK, QN }, 	 //	 389	 620
{ QN, QN, QN, KN, JA, QN, SK, QN, KN, JA, SH, JA, SK, SK, JA }, 	 //	 390	 620
{ QN, QN, QN, KN, TN, QN, SK, QN, KN, TN, SH, JA, SK, SK, TN }, 	 //	 391	 620
{ QN, QN, QN, KN, TN, QN, SK, QN, KN, ST, SH, JA, SK, SK, AC }, 	 //	 392	 620
{ QN, QN, QN, KN, AC, QN, SK, QN, KN, KN, SH, JA, SK, SK, QN }, 	 //	 393	 620
{ QN, QN, QN, KN, CR, QN, SK, QN, KN, QN, SH, JA, SK, SK, KN }, 	 //	 394	 620
{ QN, KN, QN, QN, KN, QN, QN, QN, SK, KN, SH, ST, SK, JA, SK }, 	 //	 395	 620
{ QN, KN, QN, QN, AC, QN, QN, QN, SK, SK, SH, ST, SK, JA, KN }, 	 //	 396	 620
{ QN, KN, QN, KN, AC, QN, QN, QN, SK, AC, SH, ST, SK, QN, SK }, 	 //	 397	 620
{ QN, QN, QN, KN, AC, QN, ST, QN, SK, AC, SH, JA, SK, QN, SK }, 	 //	 398	 620
{ QN, QN, QN, KN, SK, QN, ST, SK, SK, QN, SH, JA, JA, QN, QN }, 	 //	 399	 620
{ QN, KN, QN, QN, QN, QN, KN, QN, SK, QN, SH, SK, SK, JA, QN }, 	 //	 400	 620
{ QN, SK, QN, KN, AC, QN, QN, QN, SK, SK, SH, KN, SK, QN, KN }, 	 //	 401	 620
{ QN, QN, QN, KN, KN, QN, KN, QN, SK, KN, SH, AC, SK, QN, SK }, 	 //	 402	 620
{ QN, QN, QN, KN, KN, QN, KN, SK, SK, KN, SH, AC, JA, QN, SK }, 	 //	 403	 620
{ QN, QN, QN, KN, KN, SH, QN, SK, SK, KN, JA, QN, JA, QN, SK }, 	 //	 404	 620
{ QN, QN, QN, KN, AC, SH, QN, QN, SK, AC, JA, SK, SK, QN, AC }, 	 //	 405	 620
{ QN, QN, QN, KN, ST, SH, QN, QN, SK, AC, JA, SK, SK, QN, KN }, 	 //	 406	 620
{ QN, QN, QN, KN, AC, SH, QN, SK, SK, AC, JA, SK, JA, QN, SK }, 	 //	 407	 620
{ QN, QN, QN, KN, SK, SH, QN, SK, SK, KN, JA, SK, JA, QN, KN }, 	 //	 408	 620
{ QN, QN, QN, SK, SK, SH, SK, QN, JA, QN, JA, JA, SK, JA, QN }, 	 //	 409	 620
{ QN, QN, QN, KN, QN, SH, SK, QN, KN, QN, JA, JA, SK, SK, QN }, 	 //	 410	 620
{ QN, QN, QN, KN, QN, SH, SK, QN, KN, SH, JA, JA, SK, SK, JA }, 	 //	 411	 620
{ QN, QN, QN, KN, JA, SH, SK, QN, KN, JA, JA, JA, SK, SK, JA }, 	 //	 412	 620
{ QN, QN, QN, KN, JA, SH, SK, QN, KN, WN, JA, JA, SK, SK, TN }, 	 //	 413	 620
{ QN, QN, QN, KN, TN, SH, SK, QN, KN, TN, JA, JA, SK, SK, ST }, 	 //	 414	 620
{ QN, QN, QN, KN, QN, SH, SK, QN, KN, PF, JA, JA, SK, SK, JA }, 	 //	 415	 620
{ QN, QN, QN, KN, PF, SH, SK, QN, KN, JA, JA, JA, SK, SK, TN }, 	 //	 416	 620
{ QN, QN, QN, KN, SK, SH, SK, QN, KN, KN, JA, JA, SK, SK, KN }, 	 //	 417	 620
{ QN, QN, QN, KN, AC, SH, ST, QN, SK, AC, JA, JA, SK, QN, SK }, 	 //	 418	 620
{ QN, KN, QN, QN, QN, SH, SK, QN, QN, PF, JA, QN, SK, SK, JA }, 	 //	 419	 620
{ QN, KN, QN, QN, CR, SH, SK, QN, QN, QN, JA, QN, SK, SK, KN }, 	 //	 420	 620
{ QN, QN, QN, KN, KN, SH, KN, QN, SK, SK, JA, AC, SK, QN, QN }, 	 //	 421	 620
{ QN, QN, QN, KN, AC, SH, KN, QN, SK, AC, JA, AC, SK, QN, SK }, 	 //	 422	 620
{ QN, QN, QN, KN, AC, SH, KN, QN, SK, SK, JA, AC, SK, QN, KN }, 	 //	 423	 620
{ QN, QN, QN, KN, SK, SH, KN, SK, SK, QN, JA, AC, JA, QN, QN }, 	 //	 424	 620
{ SH, QN, QN, QN, AC, JA, QN, QN, SK, SK, JA, QN, SK, JA, KN }, 	 //	 425	 620
{ SH, QN, QN, QN, TN, JA, QN, QN, SK, TN, JA, SK, SK, JA, ST }, 	 //	 426	 620
{ SH, QN, QN, QN, JA, JA, QN, QN, SK, TN, JA, SK, SK, JA, AC }, 	 //	 427	 620
{ SH, QN, QN, QN, TN, JA, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 428	 620
{ SH, QN, QN, QN, KN, JA, QN, QN, SK, KN, JA, SK, SK, JA, CR }, 	 //	 429	 620
{ SH, QN, QN, QN, LO, JA, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 430	 620
{ SH, QN, QN, QN, SH, JA, SK, QN, QN, JA, JA, JA, SK, SK, JA }, 	 //	 431	 620
{ SH, QN, QN, QN, TN, JA, SK, QN, QN, TN, JA, JA, SK, SK, TN }, 	 //	 432	 620
{ SH, QN, QN, QN, ST, JA, SK, QN, QN, AC, JA, JA, SK, SK, KN }, 	 //	 433	 620
{ SH, QN, QN, QN, KN, JA, ST, QN, SK, KN, JA, JA, SK, JA, SK }, 	 //	 434	 620
{ SH, KN, QN, QN, QN, JA, KN, QN, SK, SH, JA, SK, SK, JA, JA }, 	 //	 435	 620
{ SH, KN, QN, QN, KN, JA, SK, QN, QN, SK, JA, QN, SK, SK, QN }, 	 //	 436	 620
{ SH, QN, QN, QN, SK, JA, KN, SK, SK, QN, JA, AC, JA, JA, QN }, 	 //	 437	 620
{ JA, QN, QN, QN, AC, JA, QN, QN, SK, SK, JA, QN, SK, JA, KN }, 	 //	 438	 620
{ JA, QN, QN, QN, LO, JA, QN, QN, SK, AC, JA, SK, SK, JA, AC }, 	 //	 439	 620
{ JA, QN, QN, QN, TN, JA, QN, QN, SK, TN, JA, SK, SK, JA, TN }, 	 //	 440	 620
{ JA, QN, QN, QN, SK, JA, QN, SK, SK, KN, JA, SK, JA, JA, KN }, 	 //	 441	 620
{ JA, QN, QN, QN, AC, JA, SK, QN, QN, AC, JA, JA, SK, SK, AC }, 	 //	 442	 620
{ JA, QN, QN, QN, AC, JA, SK, QN, QN, AC, JA, JA, SK, SK, CR }, 	 //	 443	 620
{ JA, QN, QN, QN, TN, JA, SK, QN, QN, TN, JA, JA, SK, SK, ST }, 	 //	 444	 620
{ JA, QN, QN, QN, PF, JA, SK, QN, QN, JA, JA, JA, SK, SK, TN }, 	 //	 445	 620
{ JA, QN, QN, QN, AC, JA, SK, QN, QN, SK, JA, JA, SK, SK, KN }, 	 //	 446	 620
{ JA, QN, QN, QN, SK, JA, SK, QN, QN, KN, JA, JA, SK, SK, KN }, 	 //	 447	 620
{ JA, QN, QN, QN, AC, JA, KN, QN, SK, AC, JA, AC, SK, JA, SK }, 	 //	 448	 620
{ JA, QN, QN, QN, AC, JA, KN, QN, SK, SK, JA, AC, SK, JA, KN }, 	 //	 449	 620
{ JA, QN, QN, QN, KN, JA, KN, SK, SK, KN, JA, AC, JA, JA, SK }, 	 //	 450	 620
{ JA, QN, QN, QN, SK, JA, KN, SK, SK, KN, JA, AC, JA, JA, KN }, 	 //	 451	 620
{ JA, QN, QN, QN, KN, JA, QN, QN, SK, SK, WN, QN, SK, JA, QN }, 	 //	 452	 620
{ JA, QN, QN, QN, AC, JA, QN, QN, SK, AC, WN, QN, SK, JA, SK }, 	 //	 453	 620
{ JA, QN, QN, QN, AC, JA, QN, QN, SK, SK, WN, QN, SK, JA, KN }, 	 //	 454	 620
{ JA, QN, QN, QN, SK, JA, QN, SK, SK, QN, WN, QN, JA, JA, QN }, 	 //	 455	 620
{ JA, QN, QN, QN, LO, JA, QN, QN, SK, AC, WN, SK, SK, JA, AC }, 	 //	 456	 620
{ JA, QN, QN, QN, AC, JA, QN, QN, SK, AC, WN, SK, SK, JA, CR }, 	 //	 457	 620
{ JA, QN, QN, QN, TN, JA, QN, QN, SK, TN, WN, SK, SK, JA, TN }, 	 //	 458	 620
{ JA, QN, QN, QN, KN, JA, QN, SK, SK, KN, WN, SK, JA, JA, SK }, 	 //	 459	 620
{ JA, QN, QN, QN, SK, JA, QN, SK, SK, QN, WN, SK, JA, JA, QN }, 	 //	 460	 620
{ JA, QN, QN, QN, AC, JA, SK, QN, QN, LO, WN, JA, SK, SK, AC }, 	 //	 461	 620
{ JA, QN, QN, QN, CR, JA, SK, QN, QN, KN, WN, JA, SK, SK, KN }, 	 //	 462	 620
{ JA, QN, QN, QN, JA, JA, SK, QN, QN, TN, WN, JA, SK, SK, AC }, 	 //	 463	 620
{ JA, QN, QN, QN, SK, JA, SK, QN, QN, KN, WN, JA, SK, SK, KN }, 	 //	 464	 620
{ JA, QN, QN, QN, KN, JA, SK, QN, QN, AC, WN, JA, SK, SK, LO }, 	 //	 465	 620
{ JA, KN, QN, QN, QN, JA, KN, QN, SK, SH, WN, SK, SK, JA, JA }, 	 //	 466	 620
{ JA, KN, QN, QN, QN, JA, KN, QN, SK, PF, WN, SK, SK, JA, JA }, 	 //	 467	 620
{ JA, KN, QN, QN, KN, JA, SK, QN, QN, QN, WN, QN, SK, SK, PF }, 	 //	 468	 620
{ JA, KN, QN, QN, QN, JA, SK, QN, QN, PF, WN, QN, SK, SK, JA }, 	 //	 469	 620
{ JA, KN, QN, QN, CR, JA, SK, QN, QN, QN, WN, QN, SK, SK, KN }, 	 //	 470	 620
{ JA, QN, QN, QN, KN, JA, KN, QN, SK, SK, WN, AC, SK, JA, QN }, 	 //	 471	 620
{ JA, QN, QN, QN, AC, JA, KN, QN, SK, SK, WN, AC, SK, JA, KN }, 	 //	 472	 620
{ JA, QN, QN, QN, AC, WN, QN, QN, SK, LO, TN, SK, SK, JA, AC }, 	 //	 473	 620
{ JA, QN, QN, QN, TN, WN, QN, QN, SK, ST, TN, SK, SK, JA, AC }, 	 //	 474	 620
{ JA, QN, QN, QN, KN, WN, QN, QN, SK, QN, TN, SK, SK, JA, PF }, 	 //	 475	 620
{ JA, QN, QN, QN, TN, WN, QN, QN, SK, AC, TN, SK, SK, JA, AC }, 	 //	 476	 620
{ JA, QN, QN, QN, AC, WN, QN, SK, SK, AC, TN, SK, JA, JA, SK }, 	 //	 477	 620
{ JA, QN, QN, QN, SH, WN, SK, QN, QN, JA, TN, JA, SK, SK, JA }, 	 //	 478	 620
{ JA, QN, QN, QN, JA, WN, SK, QN, QN, WN, TN, JA, SK, SK, TN }, 	 //	 479	 620
{ JA, QN, QN, QN, TN, WN, SK, QN, QN, TN, TN, JA, SK, SK, ST }, 	 //	 480	 620
{ JA, QN, QN, QN, PF, WN, SK, QN, QN, JA, TN, JA, SK, SK, TN }, 	 //	 481	 620
{ JA, QN, QN, QN, SK, WN, SK, QN, QN, KN, TN, JA, SK, SK, KN }, 	 //	 482	 620
{ JA, QN, QN, QN, AC, WN, KN, QN, SK, SK, TN, AC, SK, JA, KN }, 	 //	 483	 620
{ JA, QN, QN, QN, KN, WN, KN, SK, SK, KN, TN, AC, JA, JA, SK }, 	 //	 484	 620
{ WN, QN, QN, QN, AC, TN, QN, QN, SK, AC, TN, QN, SK, JA, SK }, 	 //	 485	 620
{ WN, QN, QN, QN, AC, TN, QN, QN, SK, SK, TN, QN, SK, JA, KN }, 	 //	 486	 620
{ WN, QN, QN, QN, AC, TN, QN, SK, SK, AC, TN, QN, JA, JA, SK }, 	 //	 487	 620
{ WN, QN, QN, QN, CR, TN, QN, QN, SK, KN, TN, SK, SK, JA, KN }, 	 //	 488	 620
{ WN, QN, QN, QN, JA, TN, QN, QN, SK, WN, TN, SK, SK, JA, TN }, 	 //	 489	 620
{ WN, QN, QN, QN, WN, TN, QN, QN, SK, TN, TN, SK, SK, JA, TN }, 	 //	 490	 620
{ WN, QN, QN, QN, TN, TN, QN, QN, SK, TN, TN, SK, SK, JA, ST }, 	 //	 491	 620
{ WN, QN, QN, QN, KN, TN, QN, QN, SK, QN, TN, SK, SK, JA, PF }, 	 //	 492	 620
{ WN, QN, QN, QN, PF, TN, QN, QN, SK, JA, TN, SK, SK, JA, TN }, 	 //	 493	 620
{ WN, QN, QN, QN, KN, TN, QN, QN, SK, KN, TN, SK, SK, JA, CR }, 	 //	 494	 620
{ WN, QN, QN, QN, LO, TN, SK, QN, QN, AC, TN, JA, SK, SK, AC }, 	 //	 495	 620
{ WN, QN, QN, QN, TN, TN, SK, QN, QN, ST, TN, JA, SK, SK, AC }, 	 //	 496	 620
{ WN, QN, QN, QN, PF, TN, SK, QN, QN, JA, TN, JA, SK, SK, TN }, 	 //	 497	 620
{ WN, QN, QN, QN, AC, TN, SK, QN, QN, SK, TN, JA, SK, SK, KN }, 	 //	 498	 620
{ WN, QN, QN, QN, KN, TN, SK, SK, QN, KN, TN, JA, JA, SK, SK }, 	 //	 499	 620
{ WN, QN, QN, QN, AC, TN, SK, SK, QN, AC, TN, JA, JA, SK, SK }, 	 //	 500	 620
{ WN, KN, QN, QN, QN, TN, KN, QN, SK, SH, TN, SK, SK, JA, JA }, 	 //	 501	 620
{ WN, KN, QN, QN, KN, TN, SK, QN, QN, SK, TN, QN, SK, SK, QN }, 	 //	 502	 620
{ WN, KN, QN, QN, AC, TN, SK, QN, QN, KN, TN, QN, SK, SK, QN }, 	 //	 503	 620
{ WN, KN, QN, QN, QN, TN, SK, QN, QN, KN, TN, QN, SK, SK, AC }, 	 //	 504	 620
{ WN, QN, QN, QN, AC, TN, KN, QN, SK, AC, TN, AC, SK, JA, SK }, 	 //	 505	 620
{ WN, QN, QN, QN, AC, TN, KN, SK, SK, AC, TN, AC, JA, JA, SK }, 	 //	 506	 620
{ WN, QN, QN, QN, SK, TN, KN, SK, SK, KN, TN, AC, JA, JA, KN }, 	 //	 507	 620
{ TN, QN, QN, QN, SK, TN, QN, SK, SK, KN, TN, QN, JA, JA, KN }, 	 //	 508	 620
{ TN, QN, QN, QN, JA, TN, QN, QN, SK, JA, TN, SK, SK, JA, WN }, 	 //	 509	 620
{ TN, QN, QN, QN, TN, TN, QN, QN, SK, TN, TN, SK, SK, JA, TN }, 	 //	 510	 620
{ TN, QN, QN, QN, PF, TN, QN, QN, SK, JA, TN, SK, SK, JA, TN }, 	 //	 511	 620
{ TN, QN, QN, QN, SH, TN, SK, QN, QN, JA, TN, JA, SK, SK, JA }, 	 //	 512	 620
{ TN, KN, QN, QN, QN, TN, SK, QN, QN, PF, TN, QN, SK, SK, JA }, 	 //	 513	 620
{ TN, KN, QN, QN, CR, TN, SK, QN, QN, QN, TN, QN, SK, SK, KN }, 	 //	 514	 620
{ TN, QN, QN, QN, KN, TN, KN, QN, SK, SK, TN, AC, SK, JA, QN }, 	 //	 515	 620
{ TN, QN, QN, QN, KN, TN, KN, SK, SK, KN, TN, AC, JA, JA, SK }, 	 //	 516	 620
{ TN, QN, QN, QN, KN, TN, QN, QN, SK, KN, ST, QN, SK, JA, SK }, 	 //	 517	 620
{ TN, QN, QN, QN, SK, TN, QN, SK, SK, KN, ST, QN, JA, JA, KN }, 	 //	 518	 620
{ TN, QN, QN, QN, JA, TN, QN, QN, SK, JA, ST, SK, SK, JA, JA }, 	 //	 519	 620
{ TN, QN, QN, QN, TN, TN, QN, QN, SK, ST, ST, SK, SK, JA, AC }, 	 //	 520	 620
{ TN, QN, QN, QN, KN, TN, QN, QN, SK, KN, ST, SK, SK, JA, KN }, 	 //	 521	 620
{ TN, QN, QN, QN, JA, TN, SK, QN, QN, JA, ST, JA, SK, SK, WN }, 	 //	 522	 620
{ TN, QN, QN, QN, JA, TN, SK, QN, QN, WN, ST, JA, SK, SK, TN }, 	 //	 523	 620
{ TN, QN, QN, QN, WN, TN, SK, QN, QN, TN, ST, JA, SK, SK, TN }, 	 //	 524	 620
{ TN, QN, QN, QN, AC, TN, SK, SK, QN, AC, ST, JA, JA, SK, SK }, 	 //	 525	 620
{ TN, QN, QN, QN, KN, TN, ST, QN, SK, KN, ST, JA, SK, JA, SK }, 	 //	 526	 620
{ TN, QN, QN, QN, KN, TN, ST, QN, SK, SK, ST, JA, SK, JA, QN }, 	 //	 527	 620
{ TN, KN, QN, QN, QN, TN, KN, QN, SK, PF, ST, SK, SK, JA, JA }, 	 //	 528	 620
{ TN, KN, QN, QN, KN, TN, SK, QN, QN, QN, ST, QN, SK, SK, PF }, 	 //	 529	 620
{ TN, QN, QN, QN, AC, TN, KN, QN, SK, AC, ST, AC, SK, JA, SK }, 	 //	 530	 620
{ TN, QN, QN, QN, SK, TN, KN, SK, SK, QN, ST, AC, JA, JA, QN }, 	 //	 531	 620
{ TN, QN, QN, QN, LO, ST, QN, QN, SK, AC, AC, SK, SK, JA, AC }, 	 //	 532	 620
{ TN, QN, QN, QN, CR, ST, QN, QN, SK, KN, AC, SK, SK, JA, KN }, 	 //	 533	 620
{ TN, QN, QN, QN, KN, ST, QN, QN, SK, KN, AC, SK, SK, JA, KN }, 	 //	 534	 620
{ TN, QN, QN, QN, TN, ST, QN, QN, SK, TN, AC, SK, SK, JA, ST }, 	 //	 535	 620
{ TN, QN, QN, QN, ST, ST, QN, QN, SK, AC, AC, SK, SK, JA, KN }, 	 //	 536	 620
{ TN, QN, QN, QN, JA, ST, QN, QN, SK, TN, AC, SK, SK, JA, AC }, 	 //	 537	 620
{ TN, QN, QN, QN, SH, ST, SK, QN, QN, JA, AC, JA, SK, SK, JA }, 	 //	 538	 620
{ TN, QN, QN, QN, TN, ST, SK, QN, QN, TN, AC, JA, SK, SK, TN }, 	 //	 539	 620
{ TN, QN, QN, QN, TN, ST, SK, QN, QN, ST, AC, JA, SK, SK, AC }, 	 //	 540	 620
{ TN, QN, QN, QN, JA, ST, SK, QN, QN, TN, AC, JA, SK, SK, AC }, 	 //	 541	 620
{ TN, QN, QN, QN, SK, ST, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 542	 620
{ TN, QN, QN, QN, KN, ST, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 543	 620
{ TN, QN, QN, QN, AC, ST, SK, SK, QN, AC, AC, JA, JA, SK, SK }, 	 //	 544	 620
{ TN, KN, QN, QN, QN, ST, KN, QN, SK, SH, AC, SK, SK, JA, JA }, 	 //	 545	 620
{ TN, KN, QN, QN, QN, ST, KN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 546	 620
{ TN, KN, QN, QN, KN, ST, SK, QN, QN, SK, AC, QN, SK, SK, QN }, 	 //	 547	 620
{ TN, KN, QN, QN, AC, ST, SK, QN, QN, KN, AC, QN, SK, SK, QN }, 	 //	 548	 620
{ TN, KN, QN, QN, CR, ST, SK, QN, QN, QN, AC, QN, SK, SK, KN }, 	 //	 549	 620
{ TN, KN, QN, SK, SK, ST, SK, SK, QN, QN, AC, QN, JA, KN, QN }, 	 //	 550	 620
{ ST, QN, QN, QN, KN, AC, QN, QN, SK, SK, KN, QN, SK, JA, QN }, 	 //	 551	 620
{ ST, QN, QN, QN, SK, AC, QN, SK, SK, KN, KN, QN, JA, JA, KN }, 	 //	 552	 620
{ ST, QN, QN, QN, SH, AC, QN, QN, SK, JA, KN, SK, SK, JA, JA }, 	 //	 553	 620
{ ST, QN, QN, QN, JA, AC, QN, QN, SK, WN, KN, SK, SK, JA, TN }, 	 //	 554	 620
{ ST, QN, QN, QN, TN, AC, QN, QN, SK, ST, KN, SK, SK, JA, AC }, 	 //	 555	 620
{ ST, QN, QN, QN, SK, AC, QN, SK, SK, QN, KN, SK, JA, JA, QN }, 	 //	 556	 620
{ ST, QN, QN, QN, AC, AC, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 557	 620
{ ST, QN, QN, QN, TN, AC, SK, QN, QN, TN, KN, JA, SK, SK, TN }, 	 //	 558	 620
{ ST, QN, QN, QN, TN, AC, SK, QN, QN, ST, KN, JA, SK, SK, AC }, 	 //	 559	 620
{ ST, QN, QN, QN, AC, AC, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 560	 620
{ ST, QN, QN, QN, AC, AC, SK, QN, QN, SK, KN, JA, SK, SK, KN }, 	 //	 561	 620
{ ST, QN, QN, QN, AC, AC, ST, QN, SK, AC, KN, JA, SK, JA, SK }, 	 //	 562	 620
{ ST, KN, QN, QN, QN, AC, KN, QN, SK, KN, KN, SK, SK, JA, AC }, 	 //	 563	 620
{ ST, KN, QN, QN, QN, AC, SK, QN, QN, PF, KN, QN, SK, SK, JA }, 	 //	 564	 620
{ ST, QN, QN, QN, KN, AC, KN, QN, SK, SK, KN, AC, SK, JA, QN }, 	 //	 565	 620
{ ST, QN, QN, QN, SK, AC, KN, SK, SK, KN, KN, AC, JA, JA, KN }, 	 //	 566	 620
{ AC, ST, QN, QN, KN, KN, QN, QN, SK, KN, QN, QN, SK, JA, SK }, 	 //	 567	 620
{ AC, ST, QN, QN, KN, KN, QN, QN, SK, SK, QN, QN, SK, JA, QN }, 	 //	 568	 620
{ AC, ST, QN, QN, SK, KN, QN, SK, SK, KN, QN, QN, JA, JA, KN }, 	 //	 569	 620
{ AC, QN, QN, KN, AC, KN, QN, QN, SK, SK, QN, QN, SK, QN, KN }, 	 //	 570	 620
{ AC, QN, QN, KN, SK, KN, QN, SK, SK, KN, QN, QN, JA, QN, KN }, 	 //	 571	 620
{ AC, QN, QN, SK, SK, KN, QN, QN, JA, QN, QN, SK, SK, JA, QN }, 	 //	 572	 620
{ AC, QN, QN, KN, AC, KN, QN, QN, SK, LO, QN, SK, SK, QN, AC }, 	 //	 573	 620
{ AC, QN, QN, KN, LO, KN, QN, QN, SK, AC, QN, SK, SK, QN, AC }, 	 //	 574	 620
{ AC, QN, QN, KN, CR, KN, QN, QN, SK, KN, QN, SK, SK, QN, KN }, 	 //	 575	 620
{ AC, QN, QN, KN, SH, KN, QN, QN, SK, JA, QN, SK, SK, QN, JA }, 	 //	 576	 620
{ AC, QN, QN, KN, JA, KN, QN, QN, SK, JA, QN, SK, SK, QN, WN }, 	 //	 577	 620
{ AC, QN, QN, KN, WN, KN, QN, QN, SK, TN, QN, SK, SK, QN, TN }, 	 //	 578	 620
{ AC, QN, QN, KN, KN, KN, QN, QN, SK, QN, QN, SK, SK, QN, PF }, 	 //	 579	 620
{ AC, QN, QN, QN, AC, KN, SK, QN, QN, AC, QN, JA, SK, SK, AC }, 	 //	 580	 620
{ AC, QN, QN, QN, KN, KN, SK, QN, QN, KN, QN, JA, SK, SK, KN }, 	 //	 581	 620
{ AC, QN, QN, QN, WN, KN, SK, QN, QN, TN, QN, JA, SK, SK, TN }, 	 //	 582	 620
{ AC, QN, QN, QN, TN, KN, SK, QN, QN, TN, QN, JA, SK, SK, TN }, 	 //	 583	 620
{ AC, KN, QN, QN, KN, KN, QN, QN, SK, KN, QN, ST, SK, JA, SK }, 	 //	 584	 620
{ AC, KN, QN, KN, KN, KN, QN, QN, SK, KN, QN, ST, SK, QN, SK }, 	 //	 585	 620
{ AC, KN, QN, KN, SK, KN, QN, SK, SK, KN, QN, ST, JA, QN, KN }, 	 //	 586	 620
{ AC, KN, QN, QN, QN, KN, KN, QN, SK, QN, QN, SK, SK, JA, QN }, 	 //	 587	 620
{ AC, KN, QN, QN, QN, KN, KN, QN, SK, PF, QN, SK, SK, JA, JA }, 	 //	 588	 620
{ AC, KN, QN, QN, CR, KN, SK, QN, QN, QN, QN, QN, SK, SK, KN }, 	 //	 589	 620
{ KN, QN, QN, KN, KN, QN, QN, QN, SK, KN, PF, QN, SK, QN, SK }, 	 //	 590	 620
{ KN, QN, QN, KN, KN, QN, QN, QN, SK, SK, PF, QN, SK, QN, QN }, 	 //	 591	 620
{ KN, QN, QN, KN, AC, QN, QN, QN, SK, AC, PF, QN, SK, QN, SK }, 	 //	 592	 620
{ KN, QN, QN, QN, AC, QN, QN, SK, SK, AC, PF, QN, JA, JA, SK }, 	 //	 593	 620
{ KN, QN, QN, QN, SK, QN, QN, SK, SK, KN, PF, QN, JA, JA, KN }, 	 //	 594	 620
{ KN, QN, QN, SK, SK, QN, QN, QN, JA, QN, PF, SK, SK, JA, QN }, 	 //	 595	 620
{ KN, QN, QN, KN, AC, QN, QN, QN, SK, AC, PF, SK, SK, QN, CR }, 	 //	 596	 620
{ KN, QN, QN, KN, QN, QN, QN, QN, SK, QN, PF, SK, SK, QN, SH }, 	 //	 597	 620
{ KN, QN, QN, KN, SH, QN, QN, QN, SK, JA, PF, SK, SK, QN, JA }, 	 //	 598	 620
{ KN, QN, QN, KN, WN, QN, QN, QN, SK, TN, PF, SK, SK, QN, TN }, 	 //	 599	 620
{ KN, QN, QN, KN, ST, QN, QN, QN, SK, AC, PF, SK, SK, QN, KN }, 	 //	 600	 620
{ KN, QN, QN, KN, TN, QN, QN, QN, SK, AC, PF, SK, SK, QN, AC }, 	 //	 601	 620
{ KN, QN, QN, KN, KN, QN, QN, QN, SK, KN, PF, SK, SK, QN, CR }, 	 //	 602	 620
{ KN, QN, QN, KN, CR, QN, QN, QN, SK, QN, PF, SK, SK, QN, KN }, 	 //	 603	 620
{ KN, QN, QN, KN, QN, QN, QN, QN, SK, KN, PF, SK, SK, QN, AC }, 	 //	 604	 620
{ KN, QN, QN, QN, SK, QN, QN, SK, SK, KN, PF, SK, JA, JA, KN }, 	 //	 605	 620
{ KN, QN, QN, QN, AC, QN, SK, QN, QN, AC, PF, JA, SK, SK, CR }, 	 //	 606	 620
{ KN, QN, QN, QN, CR, QN, SK, QN, QN, KN, PF, JA, SK, SK, KN }, 	 //	 607	 620
{ KN, QN, QN, QN, JA, QN, SK, QN, QN, WN, PF, JA, SK, SK, TN }, 	 //	 608	 620
{ KN, QN, QN, QN, JA, QN, SK, QN, QN, TN, PF, JA, SK, SK, AC }, 	 //	 609	 620
{ KN, QN, QN, QN, SK, QN, SK, QN, QN, KN, PF, JA, SK, SK, KN }, 	 //	 610	 620
{ KN, QN, QN, QN, KN, QN, SK, SK, QN, KN, PF, JA, JA, SK, SK }, 	 //	 611	 620
{ KN, KN, QN, QN, AC, QN, QN, QN, SK, AC, PF, ST, SK, JA, SK }, 	 //	 612	 620
{ KN, KN, QN, QN, AC, QN, QN, QN, SK, SK, PF, ST, SK, JA, KN }, 	 //	 613	 620
{ KN, KN, QN, KN, KN, QN, QN, QN, SK, KN, PF, ST, SK, QN, SK }, 	 //	 614	 620
{ KN, QN, QN, QN, KN, QN, ST, QN, SK, KN, PF, JA, SK, JA, SK }, 	 //	 615	 620
{ KN, KN, QN, QN, QN, QN, KN, QN, SK, QN, PF, SK, SK, JA, QN }, 	 //	 616	 620
{ KN, KN, QN, QN, QN, QN, KN, QN, SK, QN, PF, SK, SK, JA, SH }, 	 //	 617	 620
{ KN, KN, QN, QN, QN, QN, KN, QN, SK, KN, PF, SK, SK, JA, AC }, 	 //	 618	 620
{ KN, KN, QN, QN, KN, QN, SK, QN, QN, SK, PF, QN, SK, SK, QN }, 	 //	 619	 620
{ KN, KN, QN, QN, QN, QN, SK, QN, QN, KN, PF, QN, SK, SK, AC }, 	 //	 620	 620
{ KN, SK, QN, KN, KN, QN, QN, QN, SK, SK, PF, KN, SK, QN, QN }, 	 //	 621	 620
{ KN, QN, QN, QN, AC, QN, KN, QN, SK, SK, PF, AC, SK, JA, KN }, 	 //	 622	 620
{ QN, QN, QN, KN, AC, PF, QN, QN, SK, AC, JA, QN, SK, QN, SK }, 	 //	 623	 620
{ QN, QN, QN, KN, KN, PF, QN, QN, SK, KN, JA, SK, SK, QN, KN }, 	 //	 624	 620
{ QN, QN, QN, KN, TN, PF, QN, QN, SK, ST, JA, SK, SK, QN, AC }, 	 //	 625	 620
{ QN, QN, QN, KN, PF, PF, QN, QN, SK, JA, JA, SK, SK, QN, TN }, 	 //	 626	 620
{ QN, QN, QN, KN, KN, PF, QN, SK, SK, KN, JA, SK, JA, QN, SK }, 	 //	 627	 620
{ QN, QN, QN, KN, AC, PF, SK, QN, KN, LO, JA, JA, SK, SK, AC }, 	 //	 628	 620
{ QN, QN, QN, KN, KN, PF, SK, QN, KN, SK, JA, JA, SK, SK, QN }, 	 //	 629	 620
{ QN, QN, QN, KN, QN, PF, SK, QN, KN, QN, JA, JA, SK, SK, QN }, 	 //	 630	 620
{ QN, QN, QN, KN, QN, PF, SK, QN, KN, SH, JA, JA, SK, SK, JA }, 	 //	 631	 620
{ QN, QN, QN, KN, JA, PF, SK, QN, KN, JA, JA, JA, SK, SK, WN }, 	 //	 632	 620
{ QN, QN, QN, KN, TN, PF, SK, QN, KN, TN, JA, JA, SK, SK, TN }, 	 //	 633	 620
{ QN, QN, QN, KN, JA, PF, SK, QN, KN, TN, JA, JA, SK, SK, AC }, 	 //	 634	 620
{ QN, QN, QN, KN, AC, PF, SK, QN, KN, AC, JA, JA, SK, SK, AC }, 	 //	 635	 620
{ QN, QN, QN, KN, KN, PF, ST, QN, SK, SK, JA, JA, SK, QN, QN }, 	 //	 636	 620
{ QN, KN, QN, SK, SK, PF, SK, SK, QN, QN, JA, QN, JA, KN, QN }, 	 //	 637	 620
{ PF, QN, QN, QN, AC, JA, QN, SK, SK, AC, TN, QN, JA, JA, SK }, 	 //	 638	 620
{ PF, QN, QN, QN, AC, JA, QN, QN, SK, LO, TN, SK, SK, JA, AC }, 	 //	 639	 620
{ PF, QN, QN, QN, AC, JA, QN, QN, SK, AC, TN, SK, SK, JA, AC }, 	 //	 640	 620
{ PF, QN, QN, QN, TN, JA, QN, QN, SK, ST, TN, SK, SK, JA, AC }, 	 //	 641	 620
{ PF, QN, QN, QN, KN, JA, QN, QN, SK, KN, TN, SK, SK, JA, KN }, 	 //	 642	 620
{ PF, QN, QN, QN, AC, JA, SK, QN, QN, AC, TN, JA, SK, SK, CR }, 	 //	 643	 620
{ PF, QN, QN, QN, KN, JA, SK, QN, QN, KN, TN, JA, SK, SK, KN }, 	 //	 644	 620
{ PF, QN, QN, QN, KN, JA, SK, QN, QN, KN, TN, JA, SK, SK, CR }, 	 //	 645	 620
{ PF, QN, QN, SK, SK, JA, SK, SK, QN, QN, TN, JA, JA, KN, QN }, 	 //	 646	 620
{ PF, KN, QN, QN, QN, JA, KN, QN, SK, PF, TN, SK, SK, JA, JA }, 	 //	 647	 620
{ PF, KN, QN, QN, QN, JA, SK, QN, QN, PF, TN, QN, SK, SK, JA }, 	 //	 648	 620
{ PF, KN, QN, QN, QN, JA, SK, QN, QN, KN, TN, QN, SK, SK, AC }, 	 //	 649	 620
{ PF, QN, QN, QN, AC, JA, KN, QN, SK, AC, TN, AC, SK, JA, SK }, 	 //	 650	 620
{ PF, QN, QN, QN, AC, JA, KN, QN, SK, SK, TN, AC, SK, JA, KN }, 	 //	 651	 620
{ JA, QN, QN, QN, KN, TN, QN, SK, SK, KN, AC, QN, JA, JA, SK }, 	 //	 652	 620
{ JA, QN, QN, QN, SK, TN, QN, SK, SK, KN, AC, QN, JA, JA, KN }, 	 //	 653	 620
{ JA, QN, QN, QN, LO, TN, QN, QN, SK, AC, AC, SK, SK, JA, AC }, 	 //	 654	 620
{ JA, QN, QN, QN, TN, TN, QN, QN, SK, TN, AC, SK, SK, JA, ST }, 	 //	 655	 620
{ JA, QN, QN, QN, JA, TN, QN, QN, SK, TN, AC, SK, SK, JA, AC }, 	 //	 656	 620
{ JA, QN, QN, QN, KN, TN, QN, QN, SK, AC, AC, SK, SK, JA, LO }, 	 //	 657	 620
{ JA, QN, QN, QN, SK, TN, QN, SK, SK, QN, AC, SK, JA, JA, QN }, 	 //	 658	 620
{ JA, QN, QN, QN, AC, TN, QN, SK, SK, AC, AC, SK, JA, JA, SK }, 	 //	 659	 620
{ JA, QN, QN, QN, AC, TN, SK, QN, QN, LO, AC, JA, SK, SK, AC }, 	 //	 660	 620
{ JA, QN, QN, QN, LO, TN, SK, QN, QN, AC, AC, JA, SK, SK, AC }, 	 //	 661	 620
{ JA, QN, QN, QN, CR, TN, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 662	 620
{ JA, QN, QN, QN, KN, TN, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 663	 620
{ JA, QN, QN, QN, TN, TN, SK, QN, QN, TN, AC, JA, SK, SK, TN }, 	 //	 664	 620
{ JA, QN, QN, QN, KN, TN, SK, QN, QN, KN, AC, JA, SK, SK, CR }, 	 //	 665	 620
{ JA, QN, QN, SK, SK, TN, SK, SK, QN, QN, AC, JA, JA, KN, QN }, 	 //	 666	 620
{ JA, KN, QN, QN, QN, TN, KN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 667	 620
{ JA, KN, QN, QN, KN, TN, SK, QN, QN, QN, AC, QN, SK, SK, PF }, 	 //	 668	 620
{ JA, KN, QN, QN, CR, TN, SK, QN, QN, QN, AC, QN, SK, SK, KN }, 	 //	 669	 620
{ TN, QN, QN, QN, SH, AC, QN, QN, SK, JA, AC, SK, SK, JA, JA }, 	 //	 670	 620
{ TN, QN, QN, QN, KN, AC, QN, QN, SK, QN, AC, SK, SK, JA, PF }, 	 //	 671	 620
{ TN, QN, QN, QN, JA, AC, QN, QN, SK, TN, AC, SK, SK, JA, AC }, 	 //	 672	 620
{ TN, QN, QN, QN, KN, AC, QN, QN, SK, AC, AC, SK, SK, JA, LO }, 	 //	 673	 620
{ TN, QN, QN, QN, KN, AC, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 674	 620
{ TN, QN, QN, QN, AC, AC, SK, QN, QN, SK, AC, JA, SK, SK, KN }, 	 //	 675	 620
{ TN, KN, QN, QN, QN, AC, KN, QN, SK, QN, AC, SK, SK, JA, QN }, 	 //	 676	 620
{ TN, KN, QN, QN, QN, AC, KN, QN, SK, QN, AC, SK, SK, JA, SH }, 	 //	 677	 620
{ TN, KN, QN, QN, QN, AC, KN, QN, SK, KN, AC, SK, SK, JA, AC }, 	 //	 678	 620
{ TN, KN, QN, QN, QN, AC, SK, QN, QN, SH, AC, QN, SK, SK, JA }, 	 //	 679	 620
{ TN, KN, QN, QN, CR, AC, SK, QN, QN, QN, AC, QN, SK, SK, KN }, 	 //	 680	 620
{ TN, KN, QN, QN, QN, AC, SK, QN, QN, KN, AC, QN, SK, SK, AC }, 	 //	 681	 620
{ TN, QN, QN, QN, AC, AC, KN, QN, SK, AC, AC, AC, SK, JA, SK }, 	 //	 682	 620
{ TN, QN, QN, QN, KN, AC, KN, SK, SK, KN, AC, AC, JA, JA, SK }, 	 //	 683	 620
{ AC, QN, QN, QN, AC, AC, QN, QN, SK, AC, AC, QN, SK, JA, SK }, 	 //	 684	 620
{ AC, QN, QN, QN, TN, AC, QN, QN, SK, ST, AC, SK, SK, JA, AC }, 	 //	 685	 620
{ AC, QN, QN, QN, AC, AC, QN, QN, SK, KN, AC, SK, SK, JA, QN }, 	 //	 686	 620
{ AC, QN, QN, QN, SK, AC, QN, SK, SK, QN, AC, SK, JA, JA, QN }, 	 //	 687	 620
{ AC, QN, QN, QN, CR, AC, SK, QN, QN, KN, AC, JA, SK, SK, KN }, 	 //	 688	 620
{ AC, QN, QN, QN, JA, AC, SK, QN, QN, WN, AC, JA, SK, SK, TN }, 	 //	 689	 620
{ AC, QN, QN, QN, TN, AC, SK, QN, QN, TN, AC, JA, SK, SK, ST }, 	 //	 690	 620
{ AC, QN, QN, QN, AC, AC, SK, SK, QN, AC, AC, JA, JA, SK, SK }, 	 //	 691	 620
{ AC, KN, QN, QN, KN, AC, SK, QN, QN, QN, AC, QN, SK, SK, PF }, 	 //	 692	 620
{ AC, KN, QN, QN, CR, AC, SK, QN, QN, QN, AC, QN, SK, SK, KN }, 	 //	 693	 620
{ AC, KN, QN, QN, QN, AC, SK, QN, QN, KN, AC, QN, SK, SK, AC }, 	 //	 694	 620
{ AC, KN, QN, SK, SK, AC, SK, SK, QN, QN, AC, QN, JA, KN, QN }, 	 //	 695	 620
{ AC, QN, QN, QN, KN, AC, QN, QN, SK, SK, SK, QN, SK, JA, QN }, 	 //	 696	 620
{ AC, QN, QN, QN, SK, AC, QN, SK, SK, KN, SK, QN, JA, JA, KN }, 	 //	 697	 620
{ AC, QN, QN, QN, SK, AC, QN, PF, SK, QN, SK, SK, KN, JA, QN }, 	 //	 698	 620
{ AC, QN, QN, QN, AC, AC, QN, PF, SK, SK, SK, SK, KN, JA, KN }, 	 //	 699	 620
{ AC, QN, QN, QN, SK, AC, QN, QN, SK, QN, SK, SK, QN, JA, QN }, 	 //	 700	 620
{ AC, QN, QN, QN, AC, AC, QN, SK, SK, LO, SK, SK, JA, JA, AC }, 	 //	 701	 620
{ AC, QN, QN, QN, AC, AC, QN, SK, SK, AC, SK, SK, JA, JA, AC }, 	 //	 702	 620
{ AC, QN, QN, QN, TN, AC, QN, SK, SK, TN, SK, SK, JA, JA, TN }, 	 //	 703	 620
{ AC, QN, QN, QN, KN, AC, QN, SK, SK, KN, SK, SK, JA, JA, KN }, 	 //	 704	 620
{ AC, QN, QN, QN, CR, AC, QN, SK, SK, QN, SK, SK, JA, JA, KN }, 	 //	 705	 620
{ AC, QN, PF, SK, SK, AC, QN, QN, QN, KN, SK, SK, AC, KN, KN }, 	 //	 706	 620
{ AC, QN, AC, KN, KN, AC, SK, KN, SK, SK, SK, JA, QN, QN, QN }, 	 //	 707	 620
{ AC, QN, AC, KN, SK, AC, SK, KN, SK, QN, SK, JA, QN, QN, QN }, 	 //	 708	 620
{ AC, QN, QN, QN, AC, AC, SK, PF, QN, AC, SK, JA, KN, SK, SK }, 	 //	 709	 620
{ AC, QN, QN, QN, KN, AC, SK, PF, SK, SK, SK, JA, KN, JA, QN }, 	 //	 710	 620
{ AC, QN, QN, QN, SK, AC, SK, PF, SK, QN, SK, JA, KN, JA, QN }, 	 //	 711	 620
{ AC, QN, PF, KN, SK, AC, SK, QN, SK, QN, SK, JA, QN, QN, QN }, 	 //	 712	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, QN, AC, SK, JA, QN, SK, SK }, 	 //	 713	 620
{ AC, QN, QN, QN, KN, AC, SK, QN, SK, KN, SK, JA, QN, JA, SK }, 	 //	 714	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, SK, SK, SK, JA, QN, JA, KN }, 	 //	 715	 620
{ AC, QN, QN, WN, CR, AC, SK, QN, QN, QN, SK, JA, SK, QN, KN }, 	 //	 716	 620
{ AC, QN, QN, QN, TN, AC, SK, QN, QN, TN, SK, JA, SK, QN, TN }, 	 //	 717	 620
{ AC, QN, QN, QN, JA, AC, SK, QN, QN, TN, SK, JA, SK, QN, AC }, 	 //	 718	 620
{ AC, QN, QN, QN, KN, AC, SK, QN, QN, KN, SK, JA, SK, QN, KN }, 	 //	 719	 620
{ AC, QN, QN, KN, CR, AC, SK, QN, QN, QN, SK, JA, SK, ST, KN }, 	 //	 720	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, ST, AC, SK, JA, SK, JA, CR }, 	 //	 721	 620
{ AC, QN, QN, QN, CR, AC, SK, QN, ST, KN, SK, JA, SK, JA, KN }, 	 //	 722	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, ST, KN, SK, JA, SK, JA, QN }, 	 //	 723	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, KN, AC, SK, JA, SK, AC, CR }, 	 //	 724	 620
{ AC, QN, QN, QN, KN, AC, SK, QN, KN, KN, SK, JA, SK, AC, SK }, 	 //	 725	 620
{ AC, QN, QN, QN, KN, AC, SK, QN, KN, SK, SK, JA, SK, AC, QN }, 	 //	 726	 620
{ AC, QN, QN, QN, SK, AC, SK, QN, KN, QN, SK, JA, SK, AC, QN }, 	 //	 727	 620
{ AC, QN, QN, QN, JA, AC, SK, QN, KN, WN, SK, JA, SK, AC, TN }, 	 //	 728	 620
{ AC, QN, QN, QN, AC, AC, SK, QN, KN, KN, SK, JA, SK, AC, QN }, 	 //	 729	 620
{ AC, QN, QN, QN, PF, AC, SK, QN, KN, JA, SK, JA, SK, AC, TN }, 	 //	 730	 620
{ AC, QN, QN, WN, SK, AC, SK, SK, QN, QN, SK, JA, JA, QN, QN }, 	 //	 731	 620
{ AC, QN, QN, QN, AC, AC, SK, SK, QN, AC, SK, JA, JA, QN, CR }, 	 //	 732	 620
{ AC, QN, QN, QN, SH, AC, SK, SK, QN, JA, SK, JA, JA, QN, JA }, 	 //	 733	 620
{ AC, QN, QN, QN, JA, AC, SK, SK, QN, JA, SK, JA, JA, QN, WN }, 	 //	 734	 620
{ AC, QN, QN, QN, TN, AC, SK, SK, QN, TN, SK, JA, JA, QN, ST }, 	 //	 735	 620
{ AC, QN, QN, QN, TN, AC, SK, SK, QN, AC, SK, JA, JA, QN, AC }, 	 //	 736	 620
{ AC, QN, QN, QN, AC, AC, SK, SK, QN, AC, SK, JA, JA, SK, AC }, 	 //	 737	 620
{ AC, QN, QN, QN, JA, AC, SK, SK, QN, WN, SK, JA, JA, SK, TN }, 	 //	 738	 620
{ AC, QN, QN, KN, SK, AC, SK, SK, QN, QN, SK, JA, JA, ST, QN }, 	 //	 739	 620
{ AC, QN, QN, KN, AC, AC, SK, SK, QN, KN, SK, JA, JA, ST, QN }, 	 //	 740	 620
{ AC, QN, QN, QN, LO, AC, SK, SK, KN, AC, SK, JA, JA, AC, AC }, 	 //	 741	 620
{ AC, QN, QN, QN, AC, AC, SK, SK, KN, AC, SK, JA, JA, AC, AC }, 	 //	 742	 620
{ AC, QN, QN, QN, KN, AC, SK, SK, KN, KN, SK, JA, JA, AC, KN }, 	 //	 743	 620
{ AC, QN, QN, QN, WN, AC, SK, SK, KN, TN, SK, JA, JA, AC, TN }, 	 //	 744	 620
{ AC, QN, QN, QN, AC, AC, SK, SK, KN, AC, SK, JA, JA, AC, SK }, 	 //	 745	 620
{ AC, QN, QN, QN, KN, AC, SK, SK, KN, AC, SK, JA, JA, AC, LO }, 	 //	 746	 620
{ AC, QN, QN, QN, KN, AC, SK, AC, SK, SK, SK, JA, KN, JA, QN }, 	 //	 747	 620
{ AC, QN, QN, QN, SK, AC, SK, AC, SK, QN, SK, JA, KN, JA, QN }, 	 //	 748	 620
{ AC, KN, AC, KN, SK, AC, KN, KN, SK, QN, SK, SK, QN, QN, QN }, 	 //	 749	 620
{ AC, KN, KN, SK, SK, AC, KN, QN, QN, QN, SK, SK, PF, KN, QN }, 	 //	 750	 620
{ AC, KN, QN, QN, QN, AC, KN, SK, SK, QN, SK, SK, JA, JA, QN }, 	 //	 751	 620
{ AC, KN, QN, QN, QN, AC, KN, SK, SK, KN, SK, SK, JA, JA, AC }, 	 //	 752	 620
{ AC, KN, AC, KN, AC, AC, SK, KN, SK, SK, SK, QN, QN, QN, KN }, 	 //	 753	 620
{ AC, KN, PF, KN, KN, AC, SK, QN, SK, KN, SK, QN, QN, QN, SK }, 	 //	 754	 620
{ AC, KN, QN, WN, AC, AC, SK, QN, QN, KN, SK, QN, SK, QN, QN }, 	 //	 755	 620
{ AC, KN, QN, QN, KN, AC, SK, QN, QN, SK, SK, QN, SK, QN, QN }, 	 //	 756	 620
{ AC, KN, QN, KN, QN, AC, SK, QN, QN, QN, SK, QN, SK, ST, SH }, 	 //	 757	 620
{ AC, KN, QN, SK, KN, AC, SK, QN, QN, QN, SK, QN, SK, KN, PF }, 	 //	 758	 620
{ AC, KN, QN, QN, QN, AC, SK, QN, KN, PF, SK, QN, SK, AC, JA }, 	 //	 759	 620
{ AC, KN, QN, QN, QN, AC, SK, SK, QN, PF, SK, QN, JA, QN, JA }, 	 //	 760	 620
{ AC, KN, QN, KN, AC, AC, SK, SK, QN, KN, SK, QN, JA, ST, QN }, 	 //	 761	 620
{ AC, KN, QN, SK, KN, AC, SK, SK, QN, SK, SK, QN, JA, KN, QN }, 	 //	 762	 620
{ AC, KN, QN, SK, AC, AC, SK, SK, QN, KN, SK, QN, JA, KN, QN }, 	 //	 763	 620
{ AC, KN, QN, QN, QN, AC, SK, SK, KN, QN, SK, QN, JA, AC, SH }, 	 //	 764	 620
{ AC, KN, QN, QN, QN, AC, SK, SK, KN, KN, SK, QN, JA, AC, AC }, 	 //	 765	 620
{ AC, QN, QN, QN, SK, AC, KN, SK, SK, KN, SK, AC, JA, JA, KN }, 	 //	 766	 620
{ AC, QN, QN, QN, AC, SK, QN, QN, SK, AC, KN, QN, SK, JA, SK }, 	 //	 767	 620
{ AC, QN, QN, QN, AC, SK, QN, QN, SK, AC, KN, SK, SK, JA, AC }, 	 //	 768	 620
{ AC, QN, QN, QN, AC, SK, QN, QN, SK, AC, KN, SK, SK, JA, CR }, 	 //	 769	 620
{ AC, QN, QN, QN, CR, SK, QN, QN, SK, KN, KN, SK, SK, JA, KN }, 	 //	 770	 620
{ AC, QN, QN, QN, JA, SK, QN, QN, SK, JA, KN, SK, SK, JA, WN }, 	 //	 771	 620
{ AC, QN, QN, QN, SK, SK, QN, SK, SK, KN, KN, SK, JA, JA, KN }, 	 //	 772	 620
{ AC, QN, AC, KN, KN, SK, SK, KN, SK, SK, KN, JA, QN, QN, QN }, 	 //	 773	 620
{ AC, QN, AC, KN, SK, SK, SK, KN, SK, QN, KN, JA, QN, QN, QN }, 	 //	 774	 620
{ AC, QN, QN, QN, KN, SK, SK, PF, QN, KN, KN, JA, KN, SK, SK }, 	 //	 775	 620
{ AC, QN, QN, QN, KN, SK, SK, QN, SK, SK, KN, JA, QN, JA, QN }, 	 //	 776	 620
{ AC, QN, QN, QN, SK, SK, SK, QN, SK, QN, KN, JA, QN, JA, QN }, 	 //	 777	 620
{ AC, QN, QN, KN, KN, SK, SK, QN, SK, SK, KN, JA, QN, QN, QN }, 	 //	 778	 620
{ AC, QN, QN, WN, QN, SK, SK, QN, QN, QN, KN, JA, SK, QN, SH }, 	 //	 779	 620
{ AC, QN, QN, QN, JA, SK, SK, QN, QN, WN, KN, JA, SK, QN, TN }, 	 //	 780	 620
{ AC, QN, QN, QN, ST, SK, SK, QN, QN, AC, KN, JA, SK, QN, KN }, 	 //	 781	 620
{ AC, QN, QN, QN, PF, SK, SK, QN, QN, JA, KN, JA, SK, QN, TN }, 	 //	 782	 620
{ AC, QN, QN, QN, TN, SK, SK, QN, QN, AC, KN, JA, SK, QN, AC }, 	 //	 783	 620
{ AC, QN, QN, QN, AC, SK, SK, QN, QN, AC, KN, JA, SK, QN, AC }, 	 //	 784	 620
{ AC, QN, QN, QN, SK, SK, SK, QN, QN, KN, KN, JA, SK, QN, KN }, 	 //	 785	 620
{ AC, QN, QN, KN, CR, SK, SK, QN, QN, QN, KN, JA, SK, ST, KN }, 	 //	 786	 620
{ AC, QN, QN, QN, AC, SK, SK, QN, ST, LO, KN, JA, SK, JA, AC }, 	 //	 787	 620
{ AC, QN, QN, QN, KN, SK, SK, QN, ST, KN, KN, JA, SK, JA, SK }, 	 //	 788	 620
{ AC, QN, QN, QN, KN, SK, SK, QN, ST, SK, KN, JA, SK, JA, QN }, 	 //	 789	 620
{ AC, QN, QN, QN, SK, SK, SK, QN, ST, QN, KN, JA, SK, JA, QN }, 	 //	 790	 620
{ AC, QN, QN, QN, JA, SK, SK, QN, ST, JA, KN, JA, SK, JA, JA }, 	 //	 791	 620
{ AC, QN, QN, QN, WN, SK, SK, QN, ST, TN, KN, JA, SK, JA, TN }, 	 //	 792	 620
{ AC, QN, QN, QN, TN, SK, SK, QN, ST, TN, KN, JA, SK, JA, ST }, 	 //	 793	 620
{ AC, QN, QN, QN, TN, SK, SK, QN, ST, ST, KN, JA, SK, JA, AC }, 	 //	 794	 620
{ AC, QN, QN, QN, KN, SK, SK, QN, ST, QN, KN, JA, SK, JA, PF }, 	 //	 795	 620
{ AC, QN, QN, SK, KN, SK, SK, QN, QN, QN, KN, JA, SK, KN, PF }, 	 //	 796	 620
{ AC, QN, QN, QN, AC, SK, SK, QN, KN, AC, KN, JA, SK, AC, AC }, 	 //	 797	 620
{ AC, QN, QN, QN, AC, SK, SK, QN, KN, AC, KN, JA, SK, AC, CR }, 	 //	 798	 620
{ AC, QN, QN, QN, JA, SK, SK, QN, KN, JA, KN, JA, SK, AC, WN }, 	 //	 799	 620
{ AC, QN, QN, QN, TN, SK, SK, QN, KN, ST, KN, JA, SK, AC, AC }, 	 //	 800	 620
{ AC, QN, QN, QN, AC, SK, SK, QN, KN, KN, KN, JA, SK, AC, QN }, 	 //	 801	 620
{ AC, QN, QN, QN, JA, SK, SK, QN, KN, TN, KN, JA, SK, AC, AC }, 	 //	 802	 620
{ AC, QN, QN, QN, TN, SK, SK, QN, KN, AC, KN, JA, SK, AC, AC }, 	 //	 803	 620
{ AC, QN, QN, QN, KN, SK, SK, QN, KN, KN, KN, JA, SK, AC, KN }, 	 //	 804	 620
{ AC, QN, PF, SK, SK, SK, SK, QN, QN, QN, KN, JA, AC, KN, QN }, 	 //	 805	 620
{ AC, QN, QN, QN, AC, SK, ST, QN, SK, AC, KN, JA, SK, JA, SK }, 	 //	 806	 620
{ AC, QN, QN, QN, AC, SK, ST, QN, SK, SK, KN, JA, SK, JA, KN }, 	 //	 807	 620
{ AC, KN, QN, QN, QN, SK, KN, QN, SK, KN, KN, SK, SK, JA, AC }, 	 //	 808	 620
{ AC, KN, AC, KN, KN, SK, SK, KN, SK, KN, KN, QN, QN, QN, SK }, 	 //	 809	 620
{ AC, KN, QN, SK, SK, SK, SK, PF, QN, QN, KN, QN, KN, KN, QN }, 	 //	 810	 620
{ AC, KN, AC, KN, AC, SK, SK, PF, SK, SK, KN, QN, QN, QN, KN }, 	 //	 811	 620
{ AC, KN, PF, KN, SK, SK, SK, QN, SK, KN, KN, QN, QN, QN, KN }, 	 //	 812	 620
{ AC, KN, QN, KN, AC, SK, SK, QN, SK, SK, KN, QN, QN, QN, KN }, 	 //	 813	 620
{ AC, KN, QN, WN, AC, SK, SK, QN, QN, KN, KN, QN, SK, QN, QN }, 	 //	 814	 620
{ AC, KN, QN, QN, QN, SK, SK, QN, QN, SH, KN, QN, SK, QN, JA }, 	 //	 815	 620
{ AC, KN, QN, KN, QN, SK, SK, QN, QN, QN, KN, QN, SK, ST, SH }, 	 //	 816	 620
{ AC, KN, QN, QN, QN, SK, SK, QN, ST, PF, KN, QN, SK, JA, JA }, 	 //	 817	 620
{ AC, KN, QN, QN, QN, SK, SK, QN, ST, KN, KN, QN, SK, JA, AC }, 	 //	 818	 620
{ AC, KN, QN, QN, QN, SK, SK, QN, KN, SH, KN, QN, SK, AC, JA }, 	 //	 819	 620
{ AC, QN, QN, QN, KN, SK, KN, QN, SK, KN, KN, AC, SK, JA, SK }, 	 //	 820	 620
{ AC, QN, QN, QN, KN, SK, KN, SK, SK, KN, KN, AC, JA, JA, SK }, 	 //	 821	 620
{ SK, QN, QN, QN, AC, KN, QN, SK, SK, AC, KN, QN, JA, JA, SK }, 	 //	 822	 620
{ SK, QN, QN, QN, SH, KN, QN, QN, SK, JA, KN, SK, SK, JA, JA }, 	 //	 823	 620
{ SK, QN, QN, QN, TN, KN, QN, QN, SK, TN, KN, SK, SK, JA, TN }, 	 //	 824	 620
{ SK, QN, QN, QN, KN, KN, QN, SK, SK, KN, KN, SK, JA, JA, SK }, 	 //	 825	 620
{ SK, QN, AC, KN, SK, KN, SK, KN, SK, QN, KN, JA, QN, QN, QN }, 	 //	 826	 620
{ SK, QN, QN, QN, SK, KN, SK, PF, SK, KN, KN, JA, KN, JA, KN }, 	 //	 827	 620
{ SK, QN, QN, QN, AC, KN, SK, QN, QN, AC, KN, JA, QN, SK, SK }, 	 //	 828	 620
{ SK, QN, QN, QN, JA, KN, SK, SK, QN, WN, KN, JA, JA, QN, TN }, 	 //	 829	 620
{ SK, QN, QN, QN, KN, KN, SK, SK, QN, QN, KN, JA, JA, QN, PF }, 	 //	 830	 620
{ SK, QN, QN, QN, AC, KN, SK, SK, QN, SK, KN, JA, JA, QN, KN }, 	 //	 831	 620
{ SK, QN, QN, QN, CR, KN, SK, SK, QN, QN, KN, JA, JA, QN, KN }, 	 //	 832	 620
{ SK, QN, QN, QN, AC, KN, SK, SK, QN, LO, KN, JA, JA, SK, AC }, 	 //	 833	 620
{ SK, QN, QN, QN, CR, KN, SK, SK, QN, KN, KN, JA, JA, SK, KN }, 	 //	 834	 620
{ SK, QN, QN, QN, JA, KN, SK, SK, QN, WN, KN, JA, JA, SK, TN }, 	 //	 835	 620
{ SK, QN, QN, QN, TN, KN, SK, SK, QN, TN, KN, JA, JA, SK, TN }, 	 //	 836	 620
{ SK, QN, QN, QN, KN, KN, SK, SK, QN, AC, KN, JA, JA, SK, LO }, 	 //	 837	 620
{ SK, QN, QN, KN, SK, KN, SK, SK, QN, QN, KN, JA, JA, ST, QN }, 	 //	 838	 620
{ SK, QN, QN, KN, QN, KN, SK, SK, QN, QN, KN, JA, JA, ST, QN }, 	 //	 839	 620
{ SK, QN, QN, QN, AC, KN, SK, SK, KN, LO, KN, JA, JA, AC, AC }, 	 //	 840	 620
{ SK, QN, QN, QN, SK, KN, SK, SK, KN, QN, KN, JA, JA, AC, QN }, 	 //	 841	 620
{ SK, QN, QN, QN, SH, KN, SK, SK, KN, JA, KN, JA, JA, AC, JA }, 	 //	 842	 620
{ SK, QN, QN, QN, JA, KN, SK, SK, KN, TN, KN, JA, JA, AC, AC }, 	 //	 843	 620
{ SK, QN, QN, QN, KN, KN, SK, SK, KN, KN, KN, JA, JA, AC, CR }, 	 //	 844	 620
{ SK, QN, QN, QN, KN, KN, SK, AC, SK, KN, KN, JA, KN, JA, SK }, 	 //	 845	 620
{ SK, QN, QN, QN, KN, KN, SK, AC, SK, SK, KN, JA, KN, JA, QN }, 	 //	 846	 620
{ SK, QN, QN, QN, SK, KN, SK, AC, SK, KN, KN, JA, KN, JA, KN }, 	 //	 847	 620
{ SK, SK, AC, KN, KN, KN, JA, KN, SK, SK, KN, JA, QN, QN, QN }, 	 //	 848	 620
{ SK, SK, QN, SK, SK, KN, JA, PF, QN, QN, KN, JA, KN, KN, QN }, 	 //	 849	 620
{ SK, SK, QN, KN, SK, KN, JA, QN, SK, QN, KN, JA, QN, QN, QN }, 	 //	 850	 620
{ SK, SK, QN, QN, QN, KN, JA, QN, QN, PF, KN, JA, SK, SK, JA }, 	 //	 851	 620
{ SK, SK, QN, QN, QN, KN, JA, QN, QN, KN, KN, JA, SK, SK, AC }, 	 //	 852	 620
{ SK, QN, QN, QN, KN, KN, ST, QN, SK, SK, KN, JA, SK, JA, QN }, 	 //	 853	 620
{ SK, KN, AC, KN, AC, KN, SK, KN, SK, AC, KN, QN, QN, QN, SK }, 	 //	 854	 620
{ SK, KN, QN, SK, SK, KN, SK, PF, QN, QN, KN, QN, KN, KN, QN }, 	 //	 855	 620
{ SK, KN, AC, KN, AC, KN, SK, PF, SK, AC, KN, QN, QN, QN, SK }, 	 //	 856	 620
{ SK, KN, AC, KN, AC, KN, SK, PF, SK, SK, KN, QN, QN, QN, KN }, 	 //	 857	 620
{ SK, KN, QN, KN, AC, KN, SK, QN, SK, SK, KN, QN, QN, QN, KN }, 	 //	 858	 620
{ SK, KN, QN, QN, KN, KN, SK, SK, QN, SK, KN, QN, JA, SK, QN }, 	 //	 859	 620
{ SK, KN, QN, KN, SK, KN, SK, SK, QN, QN, KN, QN, JA, ST, QN }, 	 //	 860	 620
{ SK, KN, QN, SK, KN, KN, SK, SK, QN, SK, KN, QN, JA, KN, QN }, 	 //	 861	 620
{ SK, KN, QN, QN, QN, KN, SK, SK, KN, QN, KN, QN, JA, AC, SH }, 	 //	 862	 620
{ SK, SK, AC, QN, KN, KN, QN, KN, QN, KN, KN, KN, QN, SK, SK }, 	 //	 863	 620
{ SK, SK, AC, SK, SK, KN, QN, KN, QN, QN, KN, KN, QN, KN, QN }, 	 //	 864	 620
{ SK, SK, AC, SK, SK, KN, QN, KN, QN, KN, KN, KN, QN, KN, KN }, 	 //	 865	 620
{ SK, SK, AC, SK, SK, KN, QN, PF, QN, KN, KN, KN, QN, KN, KN }, 	 //	 866	 620
{ SK, SK, QN, QN, QN, KN, QN, QN, SK, QN, KN, KN, SK, JA, QN }, 	 //	 867	 620
{ SK, SK, QN, QN, QN, KN, QN, QN, SK, SH, KN, KN, SK, JA, JA }, 	 //	 868	 620
{ SK, SK, QN, QN, QN, KN, QN, QN, SK, PF, KN, KN, SK, JA, JA }, 	 //	 869	 620
{ SK, SK, QN, QN, QN, KN, QN, SK, SK, QN, KN, KN, JA, JA, QN }, 	 //	 870	 620
{ SK, SK, PF, QN, KN, KN, QN, QN, QN, KN, KN, KN, AC, SK, SK }, 	 //	 871	 620
{ SK, SK, PF, QN, AC, KN, QN, QN, QN, AC, KN, KN, AC, SK, SK }, 	 //	 872	 620
{ SK, SK, PF, SK, SK, KN, QN, QN, QN, KN, KN, KN, AC, KN, KN }, 	 //	 873	 620
{ SK, QN, QN, QN, AC, KN, KN, QN, SK, SK, KN, AC, SK, JA, KN }, 	 //	 874	 620
{ KN, QN, QN, QN, AC, KN, QN, QN, SK, AC, KN, SK, SK, JA, AC }, 	 //	 875	 620
{ KN, QN, QN, QN, JA, KN, QN, QN, SK, JA, KN, SK, SK, JA, JA }, 	 //	 876	 620
{ KN, QN, QN, QN, AC, KN, QN, QN, SK, AC, KN, SK, SK, JA, AC }, 	 //	 877	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, KN, KN, SK, SK, JA, CR }, 	 //	 878	 620
{ KN, QN, QN, QN, CR, KN, QN, QN, SK, QN, KN, SK, SK, JA, KN }, 	 //	 879	 620
{ KN, QN, QN, QN, KN, KN, QN, SK, SK, KN, KN, SK, JA, JA, SK }, 	 //	 880	 620
{ KN, QN, QN, QN, AC, KN, SK, QN, QN, LO, KN, JA, SK, SK, AC }, 	 //	 881	 620
{ KN, QN, QN, QN, LO, KN, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 882	 620
{ KN, QN, QN, QN, AC, KN, SK, QN, QN, AC, KN, JA, SK, SK, AC }, 	 //	 883	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 884	 620
{ KN, KN, QN, QN, QN, KN, KN, QN, SK, PF, KN, SK, SK, JA, JA }, 	 //	 885	 620
{ KN, KN, QN, QN, QN, KN, SK, QN, QN, KN, KN, QN, SK, SK, AC }, 	 //	 886	 620
{ KN, QN, QN, QN, AC, KN, KN, QN, SK, SK, KN, AC, SK, JA, KN }, 	 //	 887	 620
{ KN, QN, QN, QN, AC, KN, QN, SK, SK, AC, WN, QN, JA, JA, SK }, 	 //	 888	 620
{ KN, QN, QN, QN, SH, KN, QN, QN, SK, JA, WN, SK, SK, JA, JA }, 	 //	 889	 620
{ KN, QN, QN, QN, WN, KN, QN, QN, SK, TN, WN, SK, SK, JA, TN }, 	 //	 890	 620
{ KN, QN, QN, QN, TN, KN, QN, QN, SK, TN, WN, SK, SK, JA, ST }, 	 //	 891	 620
{ KN, QN, QN, QN, ST, KN, QN, QN, SK, AC, WN, SK, SK, JA, KN }, 	 //	 892	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, KN, WN, SK, SK, JA, KN }, 	 //	 893	 620
{ KN, QN, QN, QN, KN, KN, QN, QN, SK, AC, WN, SK, SK, JA, LO }, 	 //	 894	 620
{ KN, QN, QN, QN, LO, KN, SK, QN, QN, AC, WN, JA, SK, SK, AC }, 	 //	 895	 620
{ KN, QN, QN, QN, CR, KN, SK, QN, QN, KN, WN, JA, SK, SK, KN }, 	 //	 896	 620
{ KN, QN, QN, QN, TN, KN, SK, QN, QN, TN, WN, JA, SK, SK, TN }, 	 //	 897	 620
{ KN, QN, QN, QN, TN, KN, SK, QN, QN, TN, WN, JA, SK, SK, ST }, 	 //	 898	 620
{ KN, QN, QN, QN, SK, KN, SK, QN, QN, KN, WN, JA, SK, SK, KN }, 	 //	 899	 620
{ KN, QN, QN, QN, AC, KN, ST, QN, SK, SK, WN, JA, SK, JA, KN }, 	 //	 900	 620
{ KN, KN, QN, QN, AC, KN, SK, QN, QN, KN, WN, QN, SK, SK, QN }, 	 //	 901	 620
{ KN, QN, QN, QN, KN, KN, KN, QN, SK, KN, WN, AC, SK, JA, SK }, 	 //	 902	 620
{ KN, ST, QN, QN, AC, WN, QN, QN, SK, SK, QN, QN, SK, JA, KN }, 	 //	 903	 620
{ KN, ST, QN, KN, KN, WN, QN, QN, SK, SK, QN, QN, SK, QN, QN }, 	 //	 904	 620
{ KN, ST, QN, QN, KN, WN, QN, SK, SK, KN, QN, QN, JA, JA, SK }, 	 //	 905	 620
{ KN, ST, QN, KN, KN, WN, QN, SK, SK, KN, QN, QN, JA, QN, SK }, 	 //	 906	 620
{ KN, QN, QN, KN, KN, WN, QN, QN, SK, KN, QN, QN, SK, QN, SK }, 	 //	 907	 620
{ KN, QN, QN, KN, KN, WN, QN, QN, SK, SK, QN, QN, SK, QN, QN }, 	 //	 908	 620
{ KN, QN, QN, KN, AC, WN, QN, QN, SK, AC, QN, QN, SK, QN, SK }, 	 //	 909	 620
{ KN, QN, QN, KN, SK, WN, QN, SK, SK, QN, QN, QN, JA, QN, QN }, 	 //	 910	 620
{ KN, QN, QN, KN, AC, WN, QN, QN, SK, LO, QN, SK, SK, QN, AC }, 	 //	 911	 620
{ KN, QN, QN, KN, JA, WN, QN, QN, SK, JA, QN, SK, SK, QN, WN }, 	 //	 912	 620
{ KN, QN, QN, KN, WN, WN, QN, QN, SK, TN, QN, SK, SK, QN, TN }, 	 //	 913	 620
{ KN, QN, QN, KN, TN, WN, QN, QN, SK, TN, QN, SK, SK, QN, ST }, 	 //	 914	 620
{ KN, QN, QN, KN, QN, WN, QN, QN, SK, PF, QN, SK, SK, QN, JA }, 	 //	 915	 620
{ KN, QN, QN, KN, KN, WN, QN, QN, SK, KN, QN, SK, SK, QN, KN }, 	 //	 916	 620
{ KN, QN, QN, KN, SK, WN, QN, SK, SK, QN, QN, SK, JA, QN, QN }, 	 //	 917	 620
{ KN, QN, QN, QN, AC, WN, SK, QN, QN, LO, QN, JA, SK, SK, AC }, 	 //	 918	 620
{ KN, QN, QN, QN, AC, WN, SK, QN, QN, AC, QN, JA, SK, SK, AC }, 	 //	 919	 620
{ KN, QN, QN, QN, AC, WN, SK, QN, QN, AC, QN, JA, SK, SK, AC }, 	 //	 920	 620
{ KN, KN, QN, QN, AC, WN, QN, QN, SK, AC, QN, ST, SK, JA, SK }, 	 //	 921	 620
{ KN, KN, QN, KN, KN, WN, QN, QN, SK, KN, QN, ST, SK, QN, SK }, 	 //	 922	 620
{ KN, KN, QN, KN, AC, WN, QN, QN, SK, AC, QN, ST, SK, QN, SK }, 	 //	 923	 620
{ KN, KN, QN, KN, AC, WN, QN, QN, SK, SK, QN, ST, SK, QN, KN }, 	 //	 924	 620
{ KN, KN, QN, QN, SK, WN, QN, SK, SK, QN, QN, ST, JA, JA, QN }, 	 //	 925	 620
{ KN, KN, QN, QN, AC, WN, QN, SK, SK, AC, QN, ST, JA, JA, SK }, 	 //	 926	 620
{ KN, KN, QN, KN, SK, WN, QN, SK, SK, QN, QN, ST, JA, QN, QN }, 	 //	 927	 620
{ KN, QN, QN, QN, AC, WN, ST, QN, SK, AC, QN, JA, SK, JA, SK }, 	 //	 928	 620
{ KN, QN, QN, QN, AC, WN, ST, QN, SK, SK, QN, JA, SK, JA, KN }, 	 //	 929	 620
{ KN, KN, QN, QN, QN, WN, KN, QN, SK, QN, QN, SK, SK, JA, QN }, 	 //	 930	 620
{ KN, KN, QN, QN, QN, WN, KN, QN, SK, QN, QN, SK, SK, JA, SH }, 	 //	 931	 620
{ KN, KN, QN, QN, KN, WN, SK, QN, QN, SK, QN, QN, SK, SK, QN }, 	 //	 932	 620
{ KN, SK, QN, QN, KN, WN, QN, QN, SK, KN, QN, KN, SK, JA, SK }, 	 //	 933	 620
{ KN, SK, QN, QN, KN, WN, QN, QN, SK, SK, QN, KN, SK, JA, QN }, 	 //	 934	 620
{ KN, SK, QN, QN, AC, WN, QN, QN, SK, AC, QN, KN, SK, JA, SK }, 	 //	 935	 620
{ KN, SK, QN, KN, KN, WN, QN, QN, SK, SK, QN, KN, SK, QN, QN }, 	 //	 936	 620
{ KN, SK, QN, KN, AC, WN, QN, QN, SK, AC, QN, KN, SK, QN, SK }, 	 //	 937	 620
{ KN, SK, QN, KN, SK, WN, QN, SK, SK, QN, QN, KN, JA, QN, QN }, 	 //	 938	 620
{ KN, SK, QN, KN, SK, WN, QN, SK, SK, KN, QN, KN, JA, QN, KN }, 	 //	 939	 620
{ WN, QN, QN, SK, SK, QN, QN, QN, JA, QN, KN, SK, SK, JA, QN }, 	 //	 940	 620
{ WN, QN, QN, KN, QN, QN, QN, QN, SK, SH, KN, SK, SK, QN, JA }, 	 //	 941	 620
{ WN, QN, QN, KN, WN, QN, QN, QN, SK, TN, KN, SK, SK, QN, TN }, 	 //	 942	 620
{ WN, QN, QN, KN, TN, QN, QN, QN, SK, TN, KN, SK, SK, QN, ST }, 	 //	 943	 620
{ WN, QN, QN, KN, TN, QN, QN, QN, SK, ST, KN, SK, SK, QN, AC }, 	 //	 944	 620
{ WN, QN, QN, KN, QN, QN, QN, QN, SK, KN, KN, SK, SK, QN, AC }, 	 //	 945	 620
{ WN, QN, QN, QN, CR, QN, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 946	 620
{ WN, QN, QN, QN, TN, QN, SK, QN, QN, ST, KN, JA, SK, SK, AC }, 	 //	 947	 620
{ WN, QN, QN, QN, JA, QN, SK, QN, QN, TN, KN, JA, SK, SK, AC }, 	 //	 948	 620
{ WN, QN, QN, QN, SK, QN, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 949	 620
{ WN, QN, QN, QN, KN, QN, SK, QN, QN, KN, KN, JA, SK, SK, KN }, 	 //	 950	 620
{ WN, KN, QN, QN, KN, QN, QN, QN, SK, KN, KN, ST, SK, JA, SK }, 	 //	 951	 620
{ WN, KN, QN, QN, KN, QN, QN, QN, SK, SK, KN, ST, SK, JA, QN }, 	 //	 952	 620
{ WN, KN, QN, KN, KN, QN, QN, QN, SK, SK, KN, ST, SK, QN, QN }, 	 //	 953	 620
{ WN, KN, QN, KN, AC, QN, QN, QN, SK, SK, KN, ST, SK, QN, KN }, 	 //	 954	 620
{ WN, SK, QN, KN, AC, QN, QN, QN, SK, AC, KN, KN, SK, QN, SK }, 	 //	 955	 620
{ WN, SK, QN, KN, AC, QN, QN, QN, SK, SK, KN, KN, SK, QN, KN }, 	 //	 956	 620
{ WN, QN, QN, QN, KN, QN, KN, QN, SK, SK, KN, AC, SK, JA, QN }, 	 //	 957	 620
{ WN, QN, QN, QN, AC, QN, KN, QN, SK, AC, KN, AC, SK, JA, SK }, 	 //	 958	 620
{ WN, QN, QN, QN, AC, QN, KN, SK, SK, AC, KN, AC, JA, JA, SK }, 	 //	 959	 620
{ QN, QN, QN, KN, KN, KN, QN, QN, SK, SK, AC, QN, SK, QN, QN }, 	 //	 960	 620
{ QN, QN, QN, KN, AC, KN, QN, QN, SK, SK, AC, QN, SK, QN, KN }, 	 //	 961	 620
{ QN, QN, QN, KN, SK, KN, QN, SK, SK, QN, AC, QN, JA, QN, QN }, 	 //	 962	 620
{ QN, QN, QN, KN, AC, KN, QN, QN, SK, LO, AC, SK, SK, QN, AC }, 	 //	 963	 620
{ QN, QN, QN, KN, QN, KN, QN, QN, SK, SH, AC, SK, SK, QN, JA }, 	 //	 964	 620
{ QN, QN, QN, KN, JA, KN, QN, QN, SK, JA, AC, SK, SK, QN, WN }, 	 //	 965	 620
{ QN, QN, QN, KN, TN, KN, QN, QN, SK, TN, AC, SK, SK, QN, TN }, 	 //	 966	 620
{ QN, QN, QN, KN, TN, KN, QN, QN, SK, ST, AC, SK, SK, QN, AC }, 	 //	 967	 620
{ QN, QN, QN, KN, ST, KN, QN, QN, SK, AC, AC, SK, SK, QN, KN }, 	 //	 968	 620
{ QN, QN, QN, KN, AC, KN, QN, QN, SK, AC, AC, SK, SK, QN, AC }, 	 //	 969	 620
{ QN, QN, QN, KN, KN, KN, QN, QN, SK, KN, AC, SK, SK, QN, CR }, 	 //	 970	 620
{ QN, QN, QN, KN, SK, KN, QN, SK, SK, QN, AC, SK, JA, QN, QN }, 	 //	 971	 620
{ QN, QN, QN, KN, AC, KN, QN, SK, SK, AC, AC, SK, JA, QN, SK }, 	 //	 972	 620
{ QN, QN, QN, KN, AC, KN, SK, QN, KN, AC, AC, JA, SK, SK, CR }, 	 //	 973	 620
{ QN, QN, QN, KN, SK, KN, SK, QN, KN, QN, AC, JA, SK, SK, QN }, 	 //	 974	 620
{ QN, QN, QN, KN, QN, KN, SK, QN, KN, QN, AC, JA, SK, SK, SH }, 	 //	 975	 620
{ QN, QN, QN, KN, SH, KN, SK, QN, KN, JA, AC, JA, SK, SK, JA }, 	 //	 976	 620
{ QN, QN, QN, KN, TN, KN, SK, QN, KN, TN, AC, JA, SK, SK, TN }, 	 //	 977	 620
{ QN, QN, QN, KN, TN, KN, SK, QN, KN, AC, AC, JA, SK, SK, AC }, 	 //	 978	 620
{ QN, QN, QN, KN, KN, KN, SK, QN, KN, KN, AC, JA, SK, SK, CR }, 	 //	 979	 620
{ QN, QN, QN, KN, AC, KN, SK, SK, KN, AC, AC, JA, JA, SK, SK }, 	 //	 980	 620
{ QN, QN, QN, KN, AC, KN, ST, QN, SK, SK, AC, JA, SK, QN, KN }, 	 //	 981	 620
{ QN, QN, QN, KN, AC, KN, ST, SK, SK, AC, AC, JA, JA, QN, SK }, 	 //	 982	 620
{ QN, KN, QN, QN, QN, KN, KN, QN, SK, QN, AC, SK, SK, JA, QN }, 	 //	 983	 620
{ KN, QN, QN, QN, KN, AC, QN, QN, SK, SK, LO, QN, SK, JA, QN }, 	 //	 984	 620
{ KN, QN, QN, QN, AC, AC, QN, QN, SK, AC, LO, SK, SK, JA, AC }, 	 //	 985	 620
{ KN, QN, QN, QN, AC, AC, QN, QN, SK, AC, LO, SK, SK, JA, CR }, 	 //	 986	 620
{ KN, QN, QN, QN, CR, AC, QN, QN, SK, QN, LO, SK, SK, JA, KN }, 	 //	 987	 620
{ KN, QN, QN, QN, LO, AC, SK, QN, QN, AC, LO, JA, SK, SK, AC }, 	 //	 988	 620
{ KN, QN, QN, QN, KN, AC, SK, QN, QN, KN, LO, JA, SK, SK, KN }, 	 //	 989	 620
{ KN, QN, QN, QN, TN, AC, SK, QN, QN, AC, LO, JA, SK, SK, AC }, 	 //	 990	 620
{ KN, QN, QN, QN, SK, AC, SK, QN, QN, KN, LO, JA, SK, SK, KN }, 	 //	 991	 620
{ KN, QN, QN, QN, KN, AC, SK, QN, QN, KN, LO, JA, SK, SK, KN }, 	 //	 992	 620
{ KN, QN, QN, QN, KN, AC, SK, QN, QN, AC, LO, JA, SK, SK, LO }, 	 //	 993	 620
{ KN, QN, QN, SK, SK, AC, SK, SK, QN, QN, LO, JA, JA, KN, QN }, 	 //	 994	 620
{ KN, QN, QN, QN, KN, AC, ST, QN, SK, KN, LO, JA, SK, JA, SK }, 	 //	 995	 620
{ KN, QN, QN, QN, KN, AC, ST, QN, SK, SK, LO, JA, SK, JA, QN }, 	 //	 996	 620
{ KN, KN, QN, QN, QN, AC, KN, QN, SK, QN, LO, SK, SK, JA, SH }, 	 //	 997	 620
{ KN, KN, QN, QN, QN, AC, KN, QN, SK, SH, LO, SK, SK, JA, JA }, 	 //	 998	 620
{ KN, KN, QN, QN, QN, AC, KN, QN, SK, KN, LO, SK, SK, JA, AC }, 	 //	 999	 620
{ KN, KN, QN, QN, QN, AC, SK, QN, QN, SH, LO, QN, SK, SK, JA }};	 //	 1000	 620
