unsigned char L5_Outcome_7500[1000][15]={	 //	 0	 7500
{ AC, SH, AC, TN, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 1	 7500
{ AC, SH, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 2	 7500
{ AC, SH, AC, PF, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 3	 7500
{ AC, SH, AC, PF, WN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 4	 7500
{ AC, SH, AC, PF, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 5	 7500
{ AC, SH, AC, TN, SK, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 6	 7500
{ AC, SH, AC, TN, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 7	 7500
{ AC, SH, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 8	 7500
{ AC, SH, AC, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 9	 7500
{ AC, SH, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 10	 7500
{ AC, AC, AC, AC, CR, LO, AC, AC, AC, QN, AC, LO, AC, LO, KN }, 	 //	 11	 7500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, LO, AC, AC, CR }, 	 //	 12	 7500
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, QN, AC, LO, AC, PF, SH }, 	 //	 13	 7500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, LO, AC, AC, SK }, 	 //	 14	 7500
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, SH, AC, LO, AC, LO, JA }, 	 //	 15	 7500
{ AC, AC, AC, AC, WN, LO, AC, AC, AC, TN, AC, LO, AC, LO, TN }, 	 //	 16	 7500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, LO, AC, LO, CR }, 	 //	 17	 7500
{ AC, AC, AC, TN, AC, LO, LO, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 18	 7500
{ AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 19	 7500
{ AC, SK, AC, AC, AC, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 20	 7500
{ AC, SH, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 21	 7500
{ AC, TN, AC, PF, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 22	 7500
{ AC, TN, AC, PF, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 23	 7500
{ AC, TN, AC, PF, KN, LO, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 24	 7500
{ AC, TN, AC, PF, KN, LO, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 25	 7500
{ AC, TN, AC, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 26	 7500
{ AC, TN, AC, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 27	 7500
{ AC, TN, AC, TN, QN, LO, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 28	 7500
{ AC, AC, AC, AC, SK, LO, AC, AC, AC, QN, AC, PF, AC, LO, QN }, 	 //	 29	 7500
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, PF, AC, PF, ST }, 	 //	 30	 7500
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, PF, AC, PF, AC, AC, JA }, 	 //	 31	 7500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, PF, AC, PF, JA }, 	 //	 32	 7500
{ AC, AC, AC, PF, AC, LO, PF, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 33	 7500
{ AC, PF, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 34	 7500
{ AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 35	 7500
{ LO, SH, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 36	 7500
{ LO, SH, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 37	 7500
{ LO, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 38	 7500
{ LO, SH, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 39	 7500
{ LO, SH, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 40	 7500
{ LO, SH, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 41	 7500
{ LO, SH, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 42	 7500
{ LO, AC, AC, PF, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 43	 7500
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 44	 7500
{ LO, AC, AC, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 45	 7500
{ LO, AC, AC, TN, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 46	 7500
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 47	 7500
{ LO, LO, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 48	 7500
{ LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 49	 7500
{ LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 50	 7500
{ LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 51	 7500
{ LO, TN, AC, PF, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 52	 7500
{ LO, TN, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 53	 7500
{ LO, TN, AC, TN, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 54	 7500
{ LO, TN, AC, TN, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 55	 7500
{ LO, TN, AC, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 56	 7500
{ LO, TN, AC, PF, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 57	 7500
{ LO, TN, AC, TN, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 58	 7500
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 59	 7500
{ LO, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 60	 7500
{ LO, AC, AC, TN, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 61	 7500
{ AC, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 62	 7500
{ AC, SH, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 63	 7500
{ AC, SH, AC, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 64	 7500
{ AC, SH, AC, WN, QN, AC, AC, AC, AC, QN, AC, AC, AC, KN, SH }, 	 //	 65	 7500
{ AC, SH, AC, AC, AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, SK }, 	 //	 66	 7500
{ AC, SH, AC, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, PF, KN }, 	 //	 67	 7500
{ AC, SH, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, KN, SK }, 	 //	 68	 7500
{ AC, SH, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 69	 7500
{ AC, SH, AC, KN, WN, AC, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 70	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN }, 	 //	 71	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, JA, AC, AC, AC, QN, JA }, 	 //	 72	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, JA, AC, AC, AC, QN, WN }, 	 //	 73	 7500
{ AC, AC, AC, WN, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, QN }, 	 //	 74	 7500
{ AC, AC, AC, WN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN, SH }, 	 //	 75	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, QN, PF, AC, AC, AC, SK, JA }, 	 //	 76	 7500
{ AC, AC, AC, QN, ST, AC, AC, AC, SK, AC, AC, AC, AC, JA, KN }, 	 //	 77	 7500
{ AC, AC, AC, SK, QN, AC, AC, AC, JA, SH, AC, AC, AC, JA, JA }, 	 //	 78	 7500
{ AC, AC, AC, JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, SH, QN }, 	 //	 79	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, SK }, 	 //	 80	 7500
{ AC, AC, AC, SH, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, WN }, 	 //	 81	 7500
{ AC, AC, AC, SH, ST, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN }, 	 //	 82	 7500
{ AC, AC, AC, TN, CR, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 83	 7500
{ AC, AC, AC, TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 84	 7500
{ AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, WN, ST }, 	 //	 85	 7500
{ AC, AC, AC, KN, PF, AC, AC, AC, QN, JA, AC, AC, AC, ST, TN }, 	 //	 86	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, ST, KN, AC, AC, AC, JA, KN }, 	 //	 87	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, ST, KN, AC, AC, AC, JA, SK }, 	 //	 88	 7500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC }, 	 //	 89	 7500
{ AC, AC, AC, PF, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 90	 7500
{ AC, AC, AC, PF, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA }, 	 //	 91	 7500
{ AC, AC, AC, PF, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN }, 	 //	 92	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC }, 	 //	 93	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, AC, AC, AC, AC, QN, LO }, 	 //	 94	 7500
{ AC, AC, AC, SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, WN }, 	 //	 95	 7500
{ AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 96	 7500
{ AC, AC, AC, SK, KN, AC, AC, AC, QN, AC, AC, AC, AC, KN, LO }, 	 //	 97	 7500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC }, 	 //	 98	 7500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN }, 	 //	 99	 7500
{ AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC, WN, QN }, 	 //	 100	 7500
{ AC, AC, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, AC, WN, KN }, 	 //	 101	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, JA, AC, AC, AC, QN, JA }, 	 //	 102	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, WN, TN, AC, AC, AC, QN, ST }, 	 //	 103	 7500
{ AC, AC, AC, KN, ST, AC, AC, AC, WN, AC, AC, AC, AC, QN, KN }, 	 //	 104	 7500
{ AC, AC, AC, WN, AC, AC, AC, AC, QN, KN, AC, AC, AC, QN, QN }, 	 //	 105	 7500
{ AC, AC, AC, WN, TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC }, 	 //	 106	 7500
{ AC, AC, AC, QN, JA, AC, AC, AC, QN, WN, AC, AC, AC, QN, TN }, 	 //	 107	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, QN, AC }, 	 //	 108	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, QN, AC, AC, AC, SK, PF }, 	 //	 109	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, QN, AC, AC, AC, SK, KN }, 	 //	 110	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, SK, QN, AC, AC, AC, JA, KN }, 	 //	 111	 7500
{ AC, AC, AC, SK, CR, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 112	 7500
{ AC, AC, AC, SK, KN, AC, AC, AC, JA, SK, AC, AC, AC, JA, QN }, 	 //	 113	 7500
{ AC, AC, AC, JA, CR, AC, AC, AC, JA, KN, AC, AC, AC, SH, KN }, 	 //	 114	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, SK }, 	 //	 115	 7500
{ AC, AC, AC, SH, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN, JA }, 	 //	 116	 7500
{ AC, AC, AC, TN, JA, AC, AC, AC, TN, TN, AC, AC, AC, TN, AC }, 	 //	 117	 7500
{ AC, AC, AC, TN, CR, AC, AC, AC, TN, QN, AC, AC, AC, WN, KN }, 	 //	 118	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC, ST, AC }, 	 //	 119	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, ST, AC, AC, AC, AC, JA, AC }, 	 //	 120	 7500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, SK, AC, AC, AC, TN, KN }, 	 //	 121	 7500
{ AC, AC, AC, ST, KN, AC, AC, AC, JA, KN, AC, AC, AC, TN, KN }, 	 //	 122	 7500
{ AC, AC, AC, PF, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN }, 	 //	 123	 7500
{ AC, AC, AC, PF, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN }, 	 //	 124	 7500
{ AC, AC, AC, PF, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN, KN }, 	 //	 125	 7500
{ AC, AC, AC, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN }, 	 //	 126	 7500
{ AC, AC, AC, KN, ST, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN }, 	 //	 127	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, SK, SH, AC, AC, AC, QN, JA }, 	 //	 128	 7500
{ AC, AC, AC, KN, WN, AC, AC, AC, SK, TN, AC, AC, AC, QN, TN }, 	 //	 129	 7500
{ AC, AC, AC, SK, CR, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 130	 7500
{ AC, AC, AC, SK, SH, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA }, 	 //	 131	 7500
{ AC, AC, AC, PF, CR, AC, AC, AC, AC, KN, AC, LO, AC, AC, KN }, 	 //	 132	 7500
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, PF, AC, LO, AC, AC, JA }, 	 //	 133	 7500
{ AC, AC, AC, WN, TN, AC, AC, AC, AC, TN, AC, LO, AC, KN, TN }, 	 //	 134	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, TN, KN, AC, LO, AC, AC, AC }, 	 //	 135	 7500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, LO, AC, AC, QN }, 	 //	 136	 7500
{ AC, AC, AC, KN, SK, AC, AC, AC, AC, QN, AC, LO, AC, PF, QN }, 	 //	 137	 7500
{ AC, AC, AC, PF, CR, AC, AC, AC, AC, QN, AC, LO, AC, AC, KN }, 	 //	 138	 7500
{ AC, AC, AC, WN, CR, AC, AC, AC, AC, QN, AC, LO, AC, KN, KN }, 	 //	 139	 7500
{ AC, AC, AC, TN, AC, AC, LO, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 140	 7500
{ AC, LO, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 141	 7500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 142	 7500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 143	 7500
{ AC, KN, AC, AC, AC, AC, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 144	 7500
{ AC, ST, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 145	 7500
{ AC, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 146	 7500
{ AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 147	 7500
{ AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC }, 	 //	 148	 7500
{ AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 149	 7500
{ AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 150	 7500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 151	 7500
{ AC, TN, AC, AC, AC, AC, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 152	 7500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN }, 	 //	 153	 7500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, SK }, 	 //	 154	 7500
{ AC, TN, AC, AC, AC, AC, AC, AC, LO, AC, AC, AC, AC, KN, AC }, 	 //	 155	 7500
{ AC, TN, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, KN, AC }, 	 //	 156	 7500
{ AC, TN, AC, KN, SH, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 157	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN }, 	 //	 158	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, JA, AC, AC, AC, QN, WN }, 	 //	 159	 7500
{ AC, AC, AC, KN, ST, AC, AC, AC, WN, AC, AC, AC, AC, QN, KN }, 	 //	 160	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, TN, AC, AC, AC, QN, AC }, 	 //	 161	 7500
{ AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA }, 	 //	 162	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN }, 	 //	 163	 7500
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, AC }, 	 //	 164	 7500
{ AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 165	 7500
{ AC, AC, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, SH, AC }, 	 //	 166	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, CR }, 	 //	 167	 7500
{ AC, AC, AC, JA, SK, AC, AC, AC, SH, QN, AC, AC, AC, TN, QN }, 	 //	 168	 7500
{ AC, AC, AC, JA, ST, AC, AC, AC, SH, AC, AC, AC, AC, TN, KN }, 	 //	 169	 7500
{ AC, AC, AC, SH, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 170	 7500
{ AC, AC, AC, SH, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN, QN }, 	 //	 171	 7500
{ AC, AC, AC, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, WN, QN }, 	 //	 172	 7500
{ AC, AC, AC, TN, ST, AC, AC, AC, TN, AC, AC, AC, AC, WN, KN }, 	 //	 173	 7500
{ AC, AC, AC, TN, SK, AC, AC, AC, TN, KN, AC, AC, AC, WN, KN }, 	 //	 174	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, QN, WN, AC, AC, AC, ST, TN }, 	 //	 175	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, ST, QN, AC, AC, AC, JA, SH }, 	 //	 176	 7500
{ AC, AC, AC, ST, JA, AC, AC, AC, JA, TN, AC, AC, AC, TN, AC }, 	 //	 177	 7500
{ AC, AC, AC, ST, TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC }, 	 //	 178	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 179	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN }, 	 //	 180	 7500
{ AC, AC, AC, KN, CR, AC, AC, AC, KN, KN, AC, AC, AC, SK, KN }, 	 //	 181	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SH }, 	 //	 182	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, SK, JA }, 	 //	 183	 7500
{ AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, SK, JA }, 	 //	 184	 7500
{ AC, AC, AC, KN, SH, AC, AC, AC, SK, JA, AC, AC, AC, QN, JA }, 	 //	 185	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN, TN }, 	 //	 186	 7500
{ AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 187	 7500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC }, 	 //	 188	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN }, 	 //	 189	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, WN, SK, AC, AC, AC, QN, KN }, 	 //	 190	 7500
{ AC, AC, AC, QN, ST, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN }, 	 //	 191	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, KN, AC, AC, AC, SK, KN }, 	 //	 192	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, SK, SH }, 	 //	 193	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 194	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, AC, AC, AC, AC, JA, LO }, 	 //	 195	 7500
{ AC, AC, AC, SK, ST, AC, AC, AC, JA, AC, AC, AC, AC, JA, KN }, 	 //	 196	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, JA, KN, AC, AC, AC, JA, QN }, 	 //	 197	 7500
{ AC, AC, AC, JA, SK, AC, AC, AC, JA, KN, AC, AC, AC, SH, KN }, 	 //	 198	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, JA, KN, AC, AC, AC, SH, AC }, 	 //	 199	 7500
{ AC, AC, AC, SH, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 200	 7500
{ AC, AC, AC, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 201	 7500
{ AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, WN, WN }, 	 //	 202	 7500
{ AC, AC, AC, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, WN, KN }, 	 //	 203	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, ST, AC }, 	 //	 204	 7500
{ AC, AC, AC, QN, JA, AC, AC, AC, ST, JA, AC, AC, AC, JA, WN }, 	 //	 205	 7500
{ AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA }, 	 //	 206	 7500
{ AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN, SK }, 	 //	 207	 7500
{ AC, AC, AC, SK, SH, AC, AC, AC, QN, JA, AC, AC, AC, KN, JA }, 	 //	 208	 7500
{ AC, AC, AC, SK, AC, AC, AC, AC, QN, SK, AC, AC, AC, KN, KN }, 	 //	 209	 7500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, WN, AC, PF, AC, AC, TN }, 	 //	 210	 7500
{ AC, AC, AC, PF, SK, AC, AC, AC, AC, KN, AC, PF, AC, AC, KN }, 	 //	 211	 7500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, SK, AC, PF, AC, KN, QN }, 	 //	 212	 7500
{ AC, AC, AC, JA, TN, AC, AC, AC, TN, AC, AC, PF, AC, AC, AC }, 	 //	 213	 7500
{ AC, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, PF, AC, AC, ST }, 	 //	 214	 7500
{ AC, AC, AC, TN, CR, AC, AC, AC, AC, QN, AC, PF, AC, AC, KN }, 	 //	 215	 7500
{ AC, AC, AC, KN, SK, AC, AC, AC, AC, QN, AC, PF, AC, PF, QN }, 	 //	 216	 7500
{ AC, AC, AC, KN, WN, AC, AC, AC, AC, TN, AC, PF, AC, PF, TN }, 	 //	 217	 7500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, PF, AC, AC, KN }, 	 //	 218	 7500
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC, QN }, 	 //	 219	 7500
{ AC, AC, AC, PF, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC, SH }, 	 //	 220	 7500
{ AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 221	 7500
{ AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 222	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, ST, AC, AC, PF, QN }, 	 //	 223	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, ST, ST, AC, AC, PF, AC }, 	 //	 224	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, ST, LO, AC, LO, PF }, 	 //	 225	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, LO, AC, LO, CR }, 	 //	 226	 7500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, ST, LO, AC, AC, KN }, 	 //	 227	 7500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, LO, AC, LO, KN }, 	 //	 228	 7500
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, ST, LO, AC, AC, TN }, 	 //	 229	 7500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, ST, LO, AC, PF, JA }, 	 //	 230	 7500
{ AC, KN, AC, AC, AC, AC, ST, AC, AC, AC, ST, QN, AC, AC, AC }, 	 //	 231	 7500
{ AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, ST, JA, AC, AC, AC }, 	 //	 232	 7500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, ST, WN, AC, AC, AC }, 	 //	 233	 7500
{ AC, AC, AC, TN, AC, AC, KN, AC, AC, AC, ST, QN, AC, AC, AC }, 	 //	 234	 7500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, ST, AC, AC, PF, JA }, 	 //	 235	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, KN, ST, AC, AC, PF, AC }, 	 //	 236	 7500
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, ST, PF, AC, AC, TN }, 	 //	 237	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, PF, AC, LO, KN }, 	 //	 238	 7500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, ST, PF, AC, PF, JA }, 	 //	 239	 7500
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, ST, PF, AC, PF, TN }, 	 //	 240	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, PF, AC, PF, CR }, 	 //	 241	 7500
{ AC, PF, AC, AC, AC, AC, KN, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 242	 7500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 243	 7500
{ AC, SH, AC, PF, QN, ST, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 244	 7500
{ AC, AC, AC, KN, TN, ST, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 245	 7500
{ AC, KN, AC, AC, AC, ST, ST, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 246	 7500
{ AC, JA, AC, AC, AC, ST, SH, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 247	 7500
{ AC, TN, AC, PF, QN, ST, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 248	 7500
{ AC, AC, AC, AC, ST, ST, AC, AC, AC, AC, KN, AC, AC, PF, KN }, 	 //	 249	 7500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, KN, KN, PF, AC, PF, AC }, 	 //	 250	 7500
{ AC, AC, AC, AC, ST, ST, AC, AC, AC, AC, KN, PF, AC, AC, KN }, 	 //	 251	 7500
{ AC, AC, AC, PF, AC, ST, PF, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 252	 7500
{ AC, KN, AC, AC, AC, ST, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 253	 7500
{ AC, SK, AC, AC, AC, ST, QN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 254	 7500
{ ST, AC, AC, AC, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 255	 7500
{ ST, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 256	 7500
{ ST, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 257	 7500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, AC, LO, CR }, 	 //	 258	 7500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, AC, LO, SK }, 	 //	 259	 7500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, LO, AC, PF, AC }, 	 //	 260	 7500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, AC, PF, CR }, 	 //	 261	 7500
{ ST, LO, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 262	 7500
{ ST, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 263	 7500
{ ST, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 264	 7500
{ ST, JA, AC, AC, AC, KN, SH, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 265	 7500
{ ST, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 266	 7500
{ ST, WN, AC, PF, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 267	 7500
{ ST, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, PF, AC }, 	 //	 268	 7500
{ ST, WN, AC, TN, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 269	 7500
{ ST, KN, AC, AC, AC, KN, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 270	 7500
{ ST, AC, AC, PF, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 271	 7500
{ ST, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 272	 7500
{ ST, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN }, 	 //	 273	 7500
{ ST, AC, AC, TN, AC, KN, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 274	 7500
{ ST, PF, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 275	 7500
{ KN, SH, AC, TN, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 276	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 277	 7500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC, JA }, 	 //	 278	 7500
{ KN, AC, AC, AC, PF, KN, AC, AC, AC, JA, KN, AC, AC, AC, TN }, 	 //	 279	 7500
{ KN, AC, AC, TN, AC, KN, AC, AC, AC, AC, KN, LO, AC, AC, AC }, 	 //	 280	 7500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, AC, PF, CR }, 	 //	 281	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 282	 7500
{ KN, ST, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 283	 7500
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 284	 7500
{ KN, JA, AC, AC, AC, KN, SH, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 285	 7500
{ KN, KN, AC, AC, AC, KN, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 286	 7500
{ KN, QN, AC, AC, AC, KN, ST, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 287	 7500
{ KN, ST, AC, AC, AC, KN, JA, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 288	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF }, 	 //	 289	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 290	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 291	 7500
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 292	 7500
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 293	 7500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN }, 	 //	 294	 7500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 295	 7500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, SK, AC, AC, PF, AC }, 	 //	 296	 7500
{ KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 297	 7500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, ST }, 	 //	 298	 7500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 299	 7500
{ KN, AC, AC, TN, AC, KN, AC, AC, AC, AC, SK, LO, AC, AC, AC }, 	 //	 300	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 301	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, ST, AC, AC, AC }, 	 //	 302	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, ST, AC, AC, AC }, 	 //	 303	 7500
{ KN, KN, AC, AC, AC, KN, ST, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 304	 7500
{ KN, KN, AC, AC, AC, KN, QN, AC, AC, AC, SK, ST, AC, AC, AC }, 	 //	 305	 7500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, PF, AC }, 	 //	 306	 7500
{ KN, TN, AC, PF, LO, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 307	 7500
{ KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN }, 	 //	 308	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN }, 	 //	 309	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK }, 	 //	 310	 7500
{ KN, AC, AC, PF, AC, KN, AC, AC, AC, AC, SK, PF, AC, AC, AC }, 	 //	 311	 7500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, SK, PF, AC, LO, AC }, 	 //	 312	 7500
{ KN, PF, AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 313	 7500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, SK, SH, AC, PF, AC }, 	 //	 314	 7500
{ KN, SH, AC, PF, TN, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 315	 7500
{ KN, AC, AC, AC, CR, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN }, 	 //	 316	 7500
{ KN, AC, AC, AC, JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 317	 7500
{ KN, AC, AC, AC, JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 318	 7500
{ KN, AC, AC, PF, AC, SK, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 319	 7500
{ KN, LO, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 320	 7500
{ KN, KN, AC, AC, AC, SK, ST, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 321	 7500
{ KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 322	 7500
{ KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 323	 7500
{ KN, TN, AC, TN, AC, SK, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 324	 7500
{ KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 325	 7500
{ KN, AC, AC, AC, TN, SK, AC, AC, AC, TN, QN, AC, AC, AC, ST }, 	 //	 326	 7500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, PF, SK }, 	 //	 327	 7500
{ KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 328	 7500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, LO, SK }, 	 //	 329	 7500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, PF, AC, LO, CR }, 	 //	 330	 7500
{ KN, PF, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 331	 7500
{ KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 332	 7500
{ KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK, AC, AC, AC }, 	 //	 333	 7500
{ KN, KN, AC, AC, AC, SK, AC, AC, AC, AC, QN, SH, AC, LO, AC }, 	 //	 334	 7500
{ SK, SH, AC, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 335	 7500
{ SK, SH, AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 336	 7500
{ SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 337	 7500
{ SK, AC, AC, AC, QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA }, 	 //	 338	 7500
{ SK, AC, AC, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 339	 7500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, CR }, 	 //	 340	 7500
{ SK, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 341	 7500
{ SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 342	 7500
{ SK, SH, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 343	 7500
{ SK, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 344	 7500
{ SK, WN, AC, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, LO, AC }, 	 //	 345	 7500
{ SK, TN, AC, TN, AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 346	 7500
{ SK, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 347	 7500
{ SK, AC, AC, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 348	 7500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, PF, AC, PF, CR }, 	 //	 349	 7500
{ SK, KN, AC, PF, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 350	 7500
{ SK, KN, AC, TN, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 351	 7500
{ QN, SH, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, PF, AC }, 	 //	 352	 7500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 353	 7500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, WN }, 	 //	 354	 7500
{ QN, AC, AC, TN, AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 355	 7500
{ QN, AC, AC, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC, JA }, 	 //	 356	 7500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 357	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 358	 7500
{ QN, AC, AC, PF, AC, QN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 359	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, LO, AC, AC, CR }, 	 //	 360	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, LO, AC, AC, SK }, 	 //	 361	 7500
{ QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, ST, AC, AC, AC }, 	 //	 362	 7500
{ QN, KN, AC, AC, AC, QN, ST, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 363	 7500
{ QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN, SK, AC, AC, AC }, 	 //	 364	 7500
{ QN, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 365	 7500
{ QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 366	 7500
{ QN, SH, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 367	 7500
{ QN, WN, AC, PF, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 368	 7500
{ QN, QN, AC, AC, AC, QN, ST, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 369	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN }, 	 //	 370	 7500
{ QN, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN, AC, AC, AC, QN }, 	 //	 371	 7500
{ QN, AC, AC, AC, SH, QN, AC, AC, AC, JA, QN, AC, AC, AC, JA }, 	 //	 372	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, CR }, 	 //	 373	 7500
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN }, 	 //	 374	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, PF, AC, PF, CR }, 	 //	 375	 7500
{ QN, PF, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 376	 7500
{ QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 377	 7500
{ QN, SH, AC, PF, LO, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 378	 7500
{ QN, AC, AC, AC, CR, QN, AC, AC, AC, QN, SH, AC, AC, AC, KN }, 	 //	 379	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, SK }, 	 //	 380	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SH, AC, AC, AC, QN }, 	 //	 381	 7500
{ QN, AC, AC, AC, JA, QN, AC, AC, AC, WN, SH, AC, AC, AC, TN }, 	 //	 382	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, QN, SH, AC, AC, AC, PF }, 	 //	 383	 7500
{ QN, AC, AC, AC, WN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 384	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, LO, AC, AC, SK }, 	 //	 385	 7500
{ QN, LO, AC, AC, AC, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC }, 	 //	 386	 7500
{ QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC }, 	 //	 387	 7500
{ QN, ST, AC, AC, AC, QN, QN, AC, AC, AC, SH, QN, AC, AC, AC }, 	 //	 388	 7500
{ QN, QN, AC, AC, AC, QN, QN, AC, AC, AC, SH, SK, AC, AC, AC }, 	 //	 389	 7500
{ QN, KN, AC, AC, AC, QN, QN, AC, AC, AC, SH, ST, AC, AC, AC }, 	 //	 390	 7500
{ QN, TN, AC, TN, LO, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 391	 7500
{ QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, SK }, 	 //	 392	 7500
{ QN, AC, AC, AC, QN, QN, AC, AC, AC, QN, SH, AC, AC, AC, SH }, 	 //	 393	 7500
{ QN, AC, AC, AC, SH, QN, AC, AC, AC, JA, SH, AC, AC, AC, JA }, 	 //	 394	 7500
{ QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, SH, AC, AC, AC, TN }, 	 //	 395	 7500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, LO, SH, PF, AC, PF, AC }, 	 //	 396	 7500
{ QN, SK, AC, AC, AC, QN, QN, AC, AC, AC, SH, KN, AC, AC, AC }, 	 //	 397	 7500
{ QN, KN, AC, PF, AC, QN, AC, AC, AC, AC, SH, SH, AC, AC, AC }, 	 //	 398	 7500
{ QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 399	 7500
{ QN, AC, AC, AC, JA, SH, AC, AC, AC, WN, JA, AC, AC, AC, TN }, 	 //	 400	 7500
{ QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 401	 7500
{ QN, AC, AC, AC, CR, SH, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 402	 7500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, AC, LO, CR }, 	 //	 403	 7500
{ QN, AC, AC, PF, AC, SH, AC, AC, AC, AC, JA, LO, AC, AC, AC }, 	 //	 404	 7500
{ QN, LO, AC, AC, AC, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 405	 7500
{ QN, LO, AC, AC, AC, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 406	 7500
{ QN, QN, AC, AC, AC, SH, SK, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 407	 7500
{ QN, SH, AC, AC, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 408	 7500
{ QN, WN, AC, AC, AC, SH, AC, AC, AC, AC, JA, KN, AC, LO, AC }, 	 //	 409	 7500
{ QN, AC, AC, AC, KN, SH, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 410	 7500
{ QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 411	 7500
{ QN, AC, AC, AC, TN, SH, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 412	 7500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, PF, AC, LO, CR }, 	 //	 413	 7500
{ QN, PF, AC, AC, AC, SH, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 414	 7500
{ QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA, SK, AC, AC, AC }, 	 //	 415	 7500
{ QN, KN, AC, AC, AC, SH, AC, AC, AC, AC, JA, SH, AC, LO, AC }, 	 //	 416	 7500
{ SH, SH, AC, TN, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 417	 7500
{ SH, AC, AC, AC, SH, JA, AC, AC, AC, JA, JA, AC, AC, AC, JA }, 	 //	 418	 7500
{ SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, PF, AC }, 	 //	 419	 7500
{ SH, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, CR }, 	 //	 420	 7500
{ SH, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 421	 7500
{ SH, AC, AC, AC, QN, JA, AC, AC, AC, PF, JA, AC, AC, AC, JA }, 	 //	 422	 7500
{ SH, LO, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 423	 7500
{ SH, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 424	 7500
{ SH, QN, AC, AC, AC, JA, SK, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 425	 7500
{ SH, SK, AC, AC, AC, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 426	 7500
{ SH, SH, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 427	 7500
{ SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 428	 7500
{ SH, WN, AC, AC, AC, JA, AC, AC, AC, AC, JA, KN, AC, LO, AC }, 	 //	 429	 7500
{ SH, TN, AC, PF, AC, JA, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 430	 7500
{ SH, AC, AC, PF, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 431	 7500
{ SH, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, SK }, 	 //	 432	 7500
{ SH, AC, AC, AC, KN, JA, AC, AC, AC, QN, JA, AC, AC, AC, PF }, 	 //	 433	 7500
{ SH, AC, AC, TN, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 434	 7500
{ SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, LO, AC }, 	 //	 435	 7500
{ SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, LO, SK }, 	 //	 436	 7500
{ SH, AC, AC, PF, AC, JA, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 437	 7500
{ SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, PF, AC, AC, CR }, 	 //	 438	 7500
{ SH, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 439	 7500
{ SH, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 440	 7500
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, LO, AC }, 	 //	 441	 7500
{ JA, AC, AC, PF, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 442	 7500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 443	 7500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 444	 7500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, SH }, 	 //	 445	 7500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, SK, JA, AC, AC, AC, QN }, 	 //	 446	 7500
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, LO, AC, AC, CR }, 	 //	 447	 7500
{ JA, ST, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC }, 	 //	 448	 7500
{ JA, SK, AC, AC, AC, JA, JA, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 449	 7500
{ JA, SH, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 450	 7500
{ JA, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN, AC, AC, AC }, 	 //	 451	 7500
{ JA, WN, AC, AC, AC, JA, AC, AC, AC, AC, JA, KN, AC, PF, AC }, 	 //	 452	 7500
{ JA, KN, AC, AC, AC, JA, QN, AC, AC, AC, JA, ST, AC, AC, AC }, 	 //	 453	 7500
{ JA, QN, AC, AC, AC, JA, ST, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 454	 7500
{ JA, QN, AC, AC, AC, JA, ST, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 455	 7500
{ JA, TN, AC, TN, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 456	 7500
{ JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, PF, AC }, 	 //	 457	 7500
{ JA, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, LO, AC }, 	 //	 458	 7500
{ JA, TN, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 459	 7500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC, QN }, 	 //	 460	 7500
{ JA, AC, AC, AC, CR, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 461	 7500
{ JA, AC, AC, AC, JA, JA, AC, AC, AC, WN, JA, AC, AC, AC, TN }, 	 //	 462	 7500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, ST }, 	 //	 463	 7500
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, PF, AC, AC, SK }, 	 //	 464	 7500
{ JA, PF, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 465	 7500
{ JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, JA, SK, AC, AC, AC }, 	 //	 466	 7500
{ JA, SH, AC, AC, TN, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 467	 7500
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, PF, AC }, 	 //	 468	 7500
{ JA, SH, AC, PF, LO, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 469	 7500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, SK, WN, AC, AC, AC, QN }, 	 //	 470	 7500
{ JA, AC, AC, AC, SK, JA, AC, AC, AC, QN, WN, AC, AC, AC, QN }, 	 //	 471	 7500
{ JA, AC, AC, AC, JA, JA, AC, AC, AC, JA, WN, AC, AC, AC, WN }, 	 //	 472	 7500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, SK, WN, AC, AC, AC, QN }, 	 //	 473	 7500
{ JA, AC, AC, AC, WN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 474	 7500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, WN, AC, AC, AC, TN }, 	 //	 475	 7500
{ JA, AC, AC, AC, JA, JA, AC, AC, AC, JA, WN, AC, AC, AC, JA }, 	 //	 476	 7500
{ JA, AC, AC, AC, QN, JA, AC, AC, AC, QN, WN, AC, AC, AC, SH }, 	 //	 477	 7500
{ JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 478	 7500
{ JA, KN, AC, AC, AC, JA, ST, AC, AC, AC, WN, QN, AC, AC, AC }, 	 //	 479	 7500
{ JA, ST, AC, AC, AC, JA, QN, AC, AC, AC, WN, QN, AC, AC, AC }, 	 //	 480	 7500
{ JA, QN, AC, AC, AC, JA, SK, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 481	 7500
{ JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 482	 7500
{ JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 483	 7500
{ JA, JA, AC, AC, AC, JA, JA, AC, AC, AC, WN, SH, AC, AC, AC }, 	 //	 484	 7500
{ JA, WN, AC, AC, AC, JA, AC, AC, AC, AC, WN, KN, AC, PF, AC }, 	 //	 485	 7500
{ JA, KN, AC, AC, AC, JA, QN, AC, AC, AC, WN, ST, AC, AC, AC }, 	 //	 486	 7500
{ JA, AC, AC, AC, KN, JA, AC, AC, AC, SK, WN, AC, AC, AC, QN }, 	 //	 487	 7500
{ JA, KN, AC, AC, AC, JA, KN, AC, AC, AC, WN, SK, AC, AC, AC }, 	 //	 488	 7500
{ JA, SK, AC, AC, AC, JA, QN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 489	 7500
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 490	 7500
{ JA, AC, AC, TN, AC, WN, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 491	 7500
{ JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 492	 7500
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 493	 7500
{ JA, AC, AC, PF, AC, WN, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 494	 7500
{ JA, AC, AC, PF, AC, WN, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 495	 7500
{ JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 496	 7500
{ JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 497	 7500
{ JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 498	 7500
{ JA, JA, AC, AC, AC, WN, SH, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 499	 7500
{ JA, SH, AC, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 500	 7500
{ JA, WN, AC, TN, AC, WN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 501	 7500
{ JA, WN, AC, PF, AC, WN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 502	 7500
{ JA, ST, AC, AC, AC, WN, JA, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 503	 7500
{ JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 504	 7500
{ JA, AC, AC, AC, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 505	 7500
{ JA, AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, PF, AC, AC, SK }, 	 //	 506	 7500
{ JA, KN, AC, AC, AC, WN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 507	 7500
{ JA, SK, AC, AC, AC, WN, QN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 508	 7500
{ WN, SH, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 509	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 510	 7500
{ WN, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 511	 7500
{ WN, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, QN }, 	 //	 512	 7500
{ WN, AC, AC, AC, JA, TN, AC, AC, AC, WN, TN, AC, AC, AC, TN }, 	 //	 513	 7500
{ WN, AC, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 514	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 515	 7500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, LO, AC, LO, AC }, 	 //	 516	 7500
{ WN, AC, AC, TN, AC, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 517	 7500
{ WN, LO, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 518	 7500
{ WN, KN, AC, AC, AC, TN, ST, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 519	 7500
{ WN, QN, AC, AC, AC, TN, SK, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 520	 7500
{ WN, JA, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 521	 7500
{ WN, JA, AC, AC, AC, TN, SH, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 522	 7500
{ WN, JA, AC, AC, AC, TN, SH, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 523	 7500
{ WN, SH, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC }, 	 //	 524	 7500
{ WN, WN, AC, TN, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 525	 7500
{ WN, WN, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN, AC, PF, AC }, 	 //	 526	 7500
{ WN, WN, AC, PF, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 527	 7500
{ WN, TN, AC, PF, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 528	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 529	 7500
{ WN, AC, AC, AC, WN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 530	 7500
{ WN, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 531	 7500
{ WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN }, 	 //	 532	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF }, 	 //	 533	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN }, 	 //	 534	 7500
{ WN, AC, AC, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN }, 	 //	 535	 7500
{ WN, PF, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 536	 7500
{ WN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 537	 7500
{ WN, KN, AC, TN, AC, TN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 538	 7500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, SK }, 	 //	 539	 7500
{ TN, AC, AC, AC, QN, TN, AC, AC, AC, QN, TN, AC, AC, AC, SH }, 	 //	 540	 7500
{ TN, AC, AC, AC, SH, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 541	 7500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, LO, AC, LO, SK }, 	 //	 542	 7500
{ TN, LO, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 543	 7500
{ TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 544	 7500
{ TN, SK, AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 545	 7500
{ TN, WN, AC, TN, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 546	 7500
{ TN, WN, AC, AC, AC, TN, AC, AC, AC, AC, TN, KN, AC, LO, AC }, 	 //	 547	 7500
{ TN, AC, AC, AC, PF, TN, AC, AC, AC, JA, TN, AC, AC, AC, TN }, 	 //	 548	 7500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, CR }, 	 //	 549	 7500
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 550	 7500
{ TN, KN, AC, TN, AC, TN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 551	 7500
{ TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, TN, SH, AC, PF, AC }, 	 //	 552	 7500
{ TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, TN, SH, AC, LO, AC }, 	 //	 553	 7500
{ TN, SH, AC, PF, LO, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 554	 7500
{ TN, SH, AC, TN, AC, TN, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 555	 7500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, QN, ST, AC, AC, AC, PF }, 	 //	 556	 7500
{ TN, AC, AC, AC, CR, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 557	 7500
{ TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, ST, ST, AC, AC, AC }, 	 //	 558	 7500
{ TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, ST, QN, AC, AC, AC }, 	 //	 559	 7500
{ TN, SK, AC, AC, AC, TN, JA, AC, AC, AC, ST, JA, AC, AC, AC }, 	 //	 560	 7500
{ TN, JA, AC, AC, AC, TN, SH, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 561	 7500
{ TN, ST, AC, AC, AC, TN, JA, AC, AC, AC, ST, TN, AC, AC, AC }, 	 //	 562	 7500
{ TN, TN, AC, TN, TN, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 563	 7500
{ TN, AC, AC, TN, LO, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 564	 7500
{ TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 565	 7500
{ TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 566	 7500
{ TN, AC, AC, TN, TN, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 567	 7500
{ TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 568	 7500
{ TN, AC, AC, AC, WN, TN, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 569	 7500
{ TN, PF, AC, AC, AC, TN, KN, AC, AC, AC, ST, KN, AC, AC, AC }, 	 //	 570	 7500
{ TN, KN, AC, PF, AC, TN, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 571	 7500
{ TN, KN, AC, TN, AC, TN, AC, AC, AC, AC, ST, SH, AC, AC, AC }, 	 //	 572	 7500
{ TN, SH, AC, PF, KN, ST, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 573	 7500
{ TN, AC, AC, WN, AC, ST, AC, AC, AC, AC, AC, AC, AC, KN, CR }, 	 //	 574	 7500
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, SK, AC, LO, AC, LO, KN }, 	 //	 575	 7500
{ TN, QN, AC, AC, AC, ST, QN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 576	 7500
{ TN, QN, AC, AC, AC, ST, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 577	 7500
{ TN, QN, AC, AC, AC, ST, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 578	 7500
{ TN, SK, AC, AC, AC, ST, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 579	 7500
{ TN, TN, AC, AC, AC, ST, WN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 580	 7500
{ TN, AC, AC, TN, ST, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 581	 7500
{ TN, KN, AC, AC, AC, ST, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 582	 7500
{ TN, KN, AC, AC, AC, ST, SK, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 583	 7500
{ TN, QN, AC, AC, AC, ST, KN, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 584	 7500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, SK, KN, AC, AC, LO, KN }, 	 //	 585	 7500
{ ST, ST, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 586	 7500
{ ST, JA, AC, AC, AC, AC, SH, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 587	 7500
{ ST, TN, AC, AC, AC, AC, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 588	 7500
{ ST, WN, AC, TN, AC, AC, AC, AC, AC, LO, KN, KN, AC, AC, AC }, 	 //	 589	 7500
{ ST, KN, AC, AC, AC, AC, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 590	 7500
{ ST, KN, AC, AC, AC, AC, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 591	 7500
{ ST, TN, AC, PF, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 592	 7500
{ ST, TN, AC, AC, AC, AC, AC, AC, AC, LO, KN, AC, AC, LO, AC }, 	 //	 593	 7500
{ ST, AC, AC, TN, JA, AC, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 594	 7500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, SK, KN, PF, AC, AC, KN }, 	 //	 595	 7500
{ ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 596	 7500
{ ST, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 597	 7500
{ ST, KN, AC, AC, AC, AC, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 598	 7500
{ ST, SK, AC, AC, AC, AC, QN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 599	 7500
{ ST, KN, AC, TN, AC, AC, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 600	 7500
{ AC, SH, AC, TN, QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 601	 7500
{ AC, SH, AC, AC, QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 602	 7500
{ AC, SH, AC, PF, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 603	 7500
{ AC, SH, AC, AC, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 604	 7500
{ AC, AC, AC, AC, KN, KN, AC, AC, AC, AC, QN, LO, AC, AC, LO }, 	 //	 605	 7500
{ AC, AC, AC, AC, KN, KN, AC, AC, AC, AC, QN, LO, AC, AC, LO }, 	 //	 606	 7500
{ AC, KN, AC, AC, AC, KN, KN, AC, AC, AC, QN, ST, AC, AC, AC }, 	 //	 607	 7500
{ AC, TN, AC, AC, AC, KN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 608	 7500
{ AC, TN, AC, AC, AC, KN, TN, AC, AC, AC, QN, WN, AC, AC, AC }, 	 //	 609	 7500
{ AC, WN, AC, AC, TN, KN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 610	 7500
{ AC, QN, AC, AC, AC, KN, ST, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 611	 7500
{ AC, ST, AC, AC, AC, KN, JA, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 612	 7500
{ AC, TN, AC, PF, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 613	 7500
{ AC, AC, AC, AC, ST, KN, AC, AC, AC, AC, QN, PF, AC, AC, KN }, 	 //	 614	 7500
{ AC, AC, AC, AC, JA, KN, AC, AC, AC, TN, QN, PF, AC, PF, AC }, 	 //	 615	 7500
{ AC, AC, AC, PF, AC, KN, PF, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 616	 7500
{ AC, AC, AC, PF, AC, KN, PF, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 617	 7500
{ AC, SK, AC, AC, AC, KN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 618	 7500
{ KN, AC, AC, AC, CR, QN, AC, AC, AC, QN, PF, AC, AC, AC, KN }, 	 //	 619	 7500
{ KN, AC, AC, AC, KN, QN, AC, AC, AC, KN, PF, AC, AC, AC, CR }, 	 //	 620	 7500
{ KN, AC, AC, AC, KN, QN, AC, AC, AC, SK, PF, AC, AC, AC, QN }, 	 //	 621	 7500
{ KN, AC, AC, AC, SK, QN, AC, AC, AC, KN, PF, AC, AC, AC, KN }, 	 //	 622	 7500
{ KN, AC, AC, TN, AC, QN, AC, AC, AC, AC, PF, LO, AC, AC, AC }, 	 //	 623	 7500
{ KN, AC, AC, PF, AC, QN, AC, AC, AC, AC, PF, LO, AC, AC, AC }, 	 //	 624	 7500
{ KN, ST, AC, AC, AC, QN, QN, AC, AC, AC, PF, QN, AC, AC, AC }, 	 //	 625	 7500
{ KN, JA, AC, AC, AC, QN, JA, AC, AC, AC, PF, JA, AC, AC, AC }, 	 //	 626	 7500
{ KN, SH, AC, AC, AC, QN, TN, AC, AC, AC, PF, TN, AC, AC, AC }, 	 //	 627	 7500
{ KN, TN, AC, AC, AC, QN, TN, AC, AC, AC, PF, WN, AC, AC, AC }, 	 //	 628	 7500
{ KN, TN, AC, PF, LO, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 629	 7500
{ KN, TN, AC, PF, TN, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 630	 7500
{ KN, TN, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, LO, AC }, 	 //	 631	 7500
{ KN, AC, AC, AC, KN, QN, AC, AC, AC, KN, PF, AC, AC, AC, KN }, 	 //	 632	 7500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF, AC, AC, LO, AC }, 	 //	 633	 7500
{ KN, AC, AC, AC, QN, QN, AC, AC, AC, QN, PF, AC, AC, AC, SH }, 	 //	 634	 7500
{ KN, AC, AC, AC, PF, QN, AC, AC, AC, JA, PF, AC, AC, AC, TN }, 	 //	 635	 7500
{ KN, AC, AC, PF, LO, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 636	 7500
{ KN, AC, AC, AC, WN, QN, AC, AC, AC, TN, PF, AC, AC, AC, TN }, 	 //	 637	 7500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF, AC, AC, PF, AC }, 	 //	 638	 7500
{ KN, PF, AC, AC, AC, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 639	 7500
{ KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 640	 7500
{ KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF, SK, AC, AC, AC }, 	 //	 641	 7500
{ KN, KN, AC, AC, AC, QN, SK, AC, AC, AC, PF, QN, AC, AC, AC }, 	 //	 642	 7500
{ KN, KN, AC, AC, AC, QN, AC, AC, AC, AC, PF, SH, AC, LO, AC }, 	 //	 643	 7500
{ QN, AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 644	 7500
{ QN, AC, AC, AC, QN, PF, AC, AC, AC, SH, JA, AC, AC, AC, JA }, 	 //	 645	 7500
{ QN, AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 646	 7500
{ QN, AC, AC, AC, WN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 647	 7500
{ QN, AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, KN }, 	 //	 648	 7500
{ QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA, LO, AC, LO, SK }, 	 //	 649	 7500
{ QN, KN, AC, AC, AC, PF, KN, AC, AC, AC, JA, ST, AC, AC, AC }, 	 //	 650	 7500
{ QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA, SK, AC, AC, AC }, 	 //	 651	 7500
{ QN, QN, AC, AC, AC, PF, QN, AC, AC, AC, JA, SK, AC, AC, AC }, 	 //	 652	 7500
{ QN, JA, AC, AC, AC, PF, JA, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 653	 7500
{ QN, QN, AC, AC, AC, PF, ST, AC, AC, AC, JA, JA, AC, AC, AC }, 	 //	 654	 7500
{ QN, AC, AC, AC, WN, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN }, 	 //	 655	 7500
{ QN, AC, AC, AC, KN, PF, AC, AC, AC, QN, JA, AC, AC, AC, PF }, 	 //	 656	 7500
{ QN, AC, AC, AC, CR, PF, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 657	 7500
{ QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, LO, CR }, 	 //	 658	 7500
{ QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, LO, SK }, 	 //	 659	 7500
{ QN, AC, AC, AC, CR, PF, AC, AC, AC, QN, JA, AC, AC, AC, KN }, 	 //	 660	 7500
{ QN, KN, AC, PF, AC, PF, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 661	 7500
{ PF, SH, AC, TN, AC, JA, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 662	 7500
{ PF, SH, AC, PF, LO, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 663	 7500
{ PF, SH, AC, TN, TN, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 664	 7500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, LO, AC, AC, SK }, 	 //	 665	 7500
{ PF, AC, AC, TN, AC, JA, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 666	 7500
{ PF, LO, AC, AC, AC, JA, KN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 667	 7500
{ PF, ST, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN, AC, AC, AC }, 	 //	 668	 7500
{ PF, QN, AC, AC, AC, JA, SK, AC, AC, AC, TN, JA, AC, AC, AC }, 	 //	 669	 7500
{ PF, JA, AC, AC, AC, JA, JA, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 670	 7500
{ PF, KN, AC, AC, AC, JA, QN, AC, AC, AC, TN, ST, AC, AC, AC }, 	 //	 671	 7500
{ PF, TN, AC, AC, LO, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 672	 7500
{ PF, TN, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, LO, AC }, 	 //	 673	 7500
{ PF, TN, AC, PF, TN, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 674	 7500
{ PF, AC, AC, AC, JA, JA, AC, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 675	 7500
{ PF, AC, AC, AC, JA, JA, AC, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 676	 7500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, PF, AC, AC, SK }, 	 //	 677	 7500
{ PF, SK, AC, AC, AC, JA, QN, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 678	 7500
{ PF, KN, AC, PF, AC, JA, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 679	 7500
{ JA, SH, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 680	 7500
{ JA, SH, AC, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 681	 7500
{ JA, SH, AC, AC, KN, TN, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 682	 7500
{ JA, KN, AC, AC, AC, TN, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 683	 7500
{ JA, TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 684	 7500
{ JA, TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 685	 7500
{ JA, ST, AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 686	 7500
{ JA, KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 687	 7500
{ JA, KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 688	 7500
{ JA, KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 689	 7500
{ JA, QN, AC, AC, AC, TN, KN, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 690	 7500
{ TN, SH, AC, PF, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 691	 7500
{ TN, SH, AC, PF, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 692	 7500
{ TN, SH, AC, PF, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 693	 7500
{ TN, SH, AC, PF, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 694	 7500
{ TN, SH, AC, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 695	 7500
{ TN, SH, AC, PF, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 696	 7500
{ TN, SH, AC, TN, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 697	 7500
{ TN, AC, AC, PF, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 698	 7500
{ TN, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 699	 7500
{ TN, AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 700	 7500
{ TN, ST, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 701	 7500
{ TN, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 702	 7500
{ TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 703	 7500
{ TN, ST, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 704	 7500
{ TN, TN, AC, PF, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 705	 7500
{ TN, TN, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 706	 7500
{ TN, TN, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 707	 7500
{ TN, TN, AC, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 708	 7500
{ TN, TN, AC, PF, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 709	 7500
{ TN, TN, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 710	 7500
{ TN, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 711	 7500
{ TN, AC, AC, PF, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 712	 7500
{ TN, AC, AC, TN, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 713	 7500
{ TN, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 714	 7500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, SH, AC, AC, QN }, 	 //	 715	 7500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, SH, AC, PF, QN }, 	 //	 716	 7500
{ AC, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, CR }, 	 //	 717	 7500
{ AC, SH, AC, AC, AC, AC, AC, AC, PF, AC, AC, AC, AC, KN, AC }, 	 //	 718	 7500
{ AC, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, SK }, 	 //	 719	 7500
{ AC, SH, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, ST }, 	 //	 720	 7500
{ AC, SH, AC, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 721	 7500
{ AC, SH, AC, WN, QN, AC, AC, AC, AC, PF, AC, AC, AC, KN, JA }, 	 //	 722	 7500
{ AC, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 723	 7500
{ AC, SH, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 724	 7500
{ AC, AC, AC, LO, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA }, 	 //	 725	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 726	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, CR }, 	 //	 727	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, PF, AC, AC, AC, WN, JA }, 	 //	 728	 7500
{ AC, AC, AC, KN, ST, AC, AC, AC, WN, AC, AC, AC, AC, QN, KN }, 	 //	 729	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, WN, TN, AC, AC, AC, QN, AC }, 	 //	 730	 7500
{ AC, AC, AC, WN, JA, AC, AC, AC, QN, WN, AC, AC, AC, QN, TN }, 	 //	 731	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, ST, AC, AC, AC, SK, AC }, 	 //	 732	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, SK, ST, AC, AC, AC, JA, AC }, 	 //	 733	 7500
{ AC, AC, AC, SK, AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC }, 	 //	 734	 7500
{ AC, AC, AC, SK, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN }, 	 //	 735	 7500
{ AC, AC, AC, SK, TN, AC, AC, AC, JA, TN, AC, AC, AC, JA, ST }, 	 //	 736	 7500
{ AC, AC, AC, SK, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC }, 	 //	 737	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, CR }, 	 //	 738	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, SH, QN, AC, AC, AC, TN, SH }, 	 //	 739	 7500
{ AC, AC, AC, JA, CR, AC, AC, AC, SH, QN, AC, AC, AC, TN, KN }, 	 //	 740	 7500
{ AC, AC, AC, SH, AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC }, 	 //	 741	 7500
{ AC, AC, AC, TN, KN, AC, AC, AC, TN, AC, AC, AC, AC, TN, LO }, 	 //	 742	 7500
{ AC, AC, AC, TN, JA, AC, AC, AC, TN, JA, AC, AC, AC, WN, WN }, 	 //	 743	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, ST, TN, AC, AC, AC, JA, ST }, 	 //	 744	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, ST, AC, AC, AC, AC, JA, AC }, 	 //	 745	 7500
{ AC, AC, AC, ST, JA, AC, AC, AC, JA, TN, AC, AC, AC, TN, AC }, 	 //	 746	 7500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC }, 	 //	 747	 7500
{ AC, AC, AC, PF, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SH }, 	 //	 748	 7500
{ AC, AC, AC, SK, CR, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 749	 7500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC }, 	 //	 750	 7500
{ AC, AC, AC, KN, CR, AC, AC, AC, KN, QN, AC, AC, AC, KN, KN }, 	 //	 751	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN }, 	 //	 752	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC }, 	 //	 753	 7500
{ AC, AC, AC, KN, LO, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC }, 	 //	 754	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, WN, SH, AC, AC, AC, QN, JA }, 	 //	 755	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN }, 	 //	 756	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, SK, AC, AC, AC, SK, QN }, 	 //	 757	 7500
{ AC, AC, AC, QN, SK, AC, AC, AC, QN, KN, AC, AC, AC, SK, KN }, 	 //	 758	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, JA, QN, AC, AC, AC, SH, SH }, 	 //	 759	 7500
{ AC, AC, AC, JA, CR, AC, AC, AC, JA, QN, AC, AC, AC, SH, KN }, 	 //	 760	 7500
{ AC, AC, AC, SH, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 761	 7500
{ AC, AC, AC, TN, WN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 762	 7500
{ AC, AC, AC, TN, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 763	 7500
{ AC, AC, AC, TN, KN, AC, AC, AC, TN, SK, AC, AC, AC, WN, QN }, 	 //	 764	 7500
{ AC, AC, AC, KN, SK, AC, AC, AC, QN, KN, AC, AC, AC, ST, KN }, 	 //	 765	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, QN, AC, AC, AC, AC, ST, LO }, 	 //	 766	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, ST, KN, AC, AC, AC, JA, KN }, 	 //	 767	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, ST, QN, AC, AC, AC, JA, QN }, 	 //	 768	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, ST, KN, AC, AC, AC, JA, AC }, 	 //	 769	 7500
{ AC, AC, AC, KN, SH, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA }, 	 //	 770	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, ST }, 	 //	 771	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, AC, KN, QN }, 	 //	 772	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC }, 	 //	 773	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, CR }, 	 //	 774	 7500
{ AC, AC, AC, TN, AC, AC, AC, AC, WN, LO, AC, LO, AC, AC, AC }, 	 //	 775	 7500
{ AC, AC, AC, TN, JA, AC, AC, AC, WN, TN, AC, LO, AC, AC, AC }, 	 //	 776	 7500
{ AC, AC, AC, WN, CR, AC, AC, AC, AC, KN, AC, LO, AC, KN, KN }, 	 //	 777	 7500
{ AC, AC, AC, WN, PF, AC, AC, AC, AC, JA, AC, LO, AC, KN, TN }, 	 //	 778	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, TN, KN, AC, LO, AC, AC, AC }, 	 //	 779	 7500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, KN, AC, LO, AC, AC, KN }, 	 //	 780	 7500
{ AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, LO, AC, PF, KN }, 	 //	 781	 7500
{ AC, AC, AC, KN, CR, AC, AC, AC, AC, QN, AC, LO, AC, PF, KN }, 	 //	 782	 7500
{ AC, KN, AC, AC, AC, AC, ST, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 783	 7500
{ AC, SH, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 784	 7500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 785	 7500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 786	 7500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, CR }, 	 //	 787	 7500
{ AC, TN, AC, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 788	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK }, 	 //	 789	 7500
{ AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC }, 	 //	 790	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, KN, TN, AC, AC, AC, WN, AC }, 	 //	 791	 7500
{ AC, AC, AC, KN, CR, AC, AC, AC, WN, QN, AC, AC, AC, QN, KN }, 	 //	 792	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN }, 	 //	 793	 7500
{ AC, AC, AC, QN, JA, AC, AC, AC, QN, TN, AC, AC, AC, SK, AC }, 	 //	 794	 7500
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, AC }, 	 //	 795	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 796	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, AC, AC, AC, AC, JA, LO }, 	 //	 797	 7500
{ AC, AC, AC, SK, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, CR }, 	 //	 798	 7500
{ AC, AC, AC, SK, WN, AC, AC, AC, JA, TN, AC, AC, AC, JA, TN }, 	 //	 799	 7500
{ AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC }, 	 //	 800	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, JA, KN, AC, AC, AC, SH, QN }, 	 //	 801	 7500
{ AC, AC, AC, JA, TN, AC, AC, AC, SH, TN, AC, AC, AC, TN, TN }, 	 //	 802	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, SH, PF, AC, AC, AC, TN, JA }, 	 //	 803	 7500
{ AC, AC, AC, SH, TN, AC, AC, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 804	 7500
{ AC, AC, AC, TN, SK, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN }, 	 //	 805	 7500
{ AC, AC, AC, KN, SH, AC, AC, AC, QN, JA, AC, AC, AC, ST, JA }, 	 //	 806	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, QN, AC, AC, AC, AC, ST, AC }, 	 //	 807	 7500
{ AC, AC, AC, QN, KN, AC, AC, AC, ST, KN, AC, AC, AC, JA, KN }, 	 //	 808	 7500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC }, 	 //	 809	 7500
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC }, 	 //	 810	 7500
{ AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, SK, TN }, 	 //	 811	 7500
{ AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC }, 	 //	 812	 7500
{ AC, AC, AC, SK, PF, AC, AC, AC, QN, JA, AC, AC, AC, KN, TN }, 	 //	 813	 7500
{ AC, AC, AC, LO, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC }, 	 //	 814	 7500
{ AC, AC, AC, LO, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN }, 	 //	 815	 7500
{ AC, AC, AC, LO, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK }, 	 //	 816	 7500
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, SK }, 	 //	 817	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, KN, WN, AC, AC, AC, KN, TN }, 	 //	 818	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, WN, SH }, 	 //	 819	 7500
{ AC, AC, AC, WN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, KN }, 	 //	 820	 7500
{ AC, AC, AC, WN, KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, CR }, 	 //	 821	 7500
{ AC, AC, AC, QN, QN, AC, AC, AC, QN, PF, AC, AC, AC, QN, JA }, 	 //	 822	 7500
{ AC, AC, AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, SK, AC }, 	 //	 823	 7500
{ AC, AC, AC, QN, CR, AC, AC, AC, QN, QN, AC, AC, AC, SK, KN }, 	 //	 824	 7500
{ AC, AC, AC, SK, TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC }, 	 //	 825	 7500
{ AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, SH, AC }, 	 //	 826	 7500
{ AC, AC, AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, AC, TN, AC }, 	 //	 827	 7500
{ AC, AC, AC, JA, QN, AC, AC, AC, SH, KN, AC, AC, AC, TN, AC }, 	 //	 828	 7500
{ AC, AC, AC, SH, KN, AC, AC, AC, TN, SK, AC, AC, AC, TN, QN }, 	 //	 829	 7500
{ AC, AC, AC, SH, PF, AC, AC, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 830	 7500
{ AC, AC, AC, SH, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, CR }, 	 //	 831	 7500
{ AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, SK }, 	 //	 832	 7500
{ AC, AC, AC, TN, QN, AC, AC, AC, TN, QN, AC, AC, AC, TN, QN }, 	 //	 833	 7500
{ AC, AC, AC, ST, AC, AC, AC, AC, JA, LO, AC, AC, AC, TN, AC }, 	 //	 834	 7500
{ AC, AC, AC, ST, QN, AC, AC, AC, JA, QN, AC, AC, AC, TN, QN }, 	 //	 835	 7500
{ AC, AC, AC, PF, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, CR }, 	 //	 836	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, KN, SH, AC, AC, AC, KN, JA }, 	 //	 837	 7500
{ AC, AC, AC, KN, PF, AC, AC, AC, KN, JA, AC, AC, AC, SK, TN }, 	 //	 838	 7500
{ AC, AC, AC, KN, JA, AC, AC, AC, SK, WN, AC, AC, AC, QN, TN }, 	 //	 839	 7500
{ AC, AC, AC, KN, TN, AC, AC, AC, SK, TN, AC, AC, AC, QN, ST }, 	 //	 840	 7500
{ AC, AC, AC, SK, JA, AC, AC, AC, QN, JA, AC, AC, AC, KN, WN }, 	 //	 841	 7500
{ AC, AC, AC, AC, AC, AC, AC, WN, PF, SK, AC, AC, KN, KN, KN }, 	 //	 842	 7500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, JA, AC, PF, AC, AC, JA }, 	 //	 843	 7500
{ AC, AC, AC, TN, CR, AC, AC, AC, AC, KN, AC, PF, AC, AC, KN }, 	 //	 844	 7500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, QN, AC, PF, AC, AC, QN }, 	 //	 845	 7500
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, PF, AC, PF, SH }, 	 //	 846	 7500
{ AC, AC, AC, TN, PF, AC, AC, AC, AC, JA, AC, PF, AC, AC, TN }, 	 //	 847	 7500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 848	 7500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, SK, AC, AC, LO, KN }, 	 //	 849	 7500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, SK, AC, AC, LO, JA }, 	 //	 850	 7500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, PF, WN }, 	 //	 851	 7500
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, KN, SK, AC, AC, KN, AC }, 	 //	 852	 7500
{ AC, AC, AC, WN, QN, AC, AC, AC, AC, KN, SK, LO, AC, KN, AC }, 	 //	 853	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, LO, AC, AC, KN }, 	 //	 854	 7500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, SK, LO, AC, AC, KN }, 	 //	 855	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, LO, AC, LO, QN }, 	 //	 856	 7500
{ AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK, LO, AC, LO, QN }, 	 //	 857	 7500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, LO, AC, PF, WN }, 	 //	 858	 7500
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 859	 7500
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 860	 7500
{ AC, SK, AC, AC, AC, AC, JA, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 861	 7500
{ AC, SK, AC, AC, AC, AC, JA, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 862	 7500
{ AC, JA, AC, AC, AC, AC, SH, AC, AC, AC, SK, TN, AC, AC, AC }, 	 //	 863	 7500
{ AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, SK, WN, AC, AC, AC }, 	 //	 864	 7500
{ AC, WN, AC, PF, JA, AC, AC, AC, AC, TN, SK, KN, AC, AC, AC }, 	 //	 865	 7500
{ AC, AC, AC, TN, AC, AC, KN, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 866	 7500
{ AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, SK, ST, AC, AC, AC }, 	 //	 867	 7500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, SK, AC, AC, PF, JA }, 	 //	 868	 7500
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, SK, AC, AC, PF, TN }, 	 //	 869	 7500
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, SK, AC, AC, PF, ST }, 	 //	 870	 7500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, SK, AC, AC, PF, KN }, 	 //	 871	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, PF, AC, LO, CR }, 	 //	 872	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, PF, AC, AC, QN }, 	 //	 873	 7500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, PF, AC, AC, WN }, 	 //	 874	 7500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, SK, PF, AC, PF, QN }, 	 //	 875	 7500
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, SK, PF, AC, PF, ST }, 	 //	 876	 7500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, PF, AC, LO, WN }, 	 //	 877	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, QN, SK, PF, AC, AC, PF }, 	 //	 878	 7500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, PF, AC, AC, KN }, 	 //	 879	 7500
{ AC, AC, AC, TN, AC, AC, PF, AC, AC, AC, SK, KN, AC, AC, AC }, 	 //	 880	 7500
{ AC, KN, AC, PF, QN, AC, AC, AC, AC, KN, SK, SH, AC, AC, AC }, 	 //	 881	 7500
{ AC, SH, AC, PF, TN, SK, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 882	 7500
{ AC, AC, AC, WN, LO, SK, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 883	 7500
{ AC, AC, AC, AC, ST, SK, AC, AC, AC, AC, KN, LO, AC, AC, KN }, 	 //	 884	 7500
{ AC, AC, AC, AC, TN, SK, AC, AC, AC, ST, KN, LO, AC, LO, AC }, 	 //	 885	 7500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, LO, AC, PF, LO }, 	 //	 886	 7500
{ AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 887	 7500
{ AC, AC, AC, PF, AC, SK, KN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 888	 7500
{ AC, AC, AC, PF, AC, SK, KN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 889	 7500
{ AC, KN, AC, AC, AC, SK, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 890	 7500
{ AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 891	 7500
{ AC, KN, AC, AC, AC, SK, KN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 892	 7500
{ AC, SK, AC, AC, AC, SK, QN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 893	 7500
{ AC, KN, AC, TN, LO, SK, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 894	 7500
{ SK, AC, AC, AC, CR, KN, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 895	 7500
{ SK, AC, AC, TN, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 896	 7500
{ SK, AC, AC, AC, QN, KN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 897	 7500
{ SK, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, PF, AC }, 	 //	 898	 7500
{ SK, QN, AC, AC, AC, KN, QN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 899	 7500
{ SK, TN, AC, AC, AC, KN, TN, AC, AC, AC, KN, WN, AC, AC, AC }, 	 //	 900	 7500
{ SK, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, AC }, 	 //	 901	 7500
{ SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, CR }, 	 //	 902	 7500
{ SK, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, SK, AC, AC, AC }, 	 //	 903	 7500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, AC }, 	 //	 904	 7500
{ KN, SH, AC, TN, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 905	 7500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 906	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 907	 7500
{ KN, AC, AC, AC, CR, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 908	 7500
{ KN, AC, AC, AC, KN, KN, AC, AC, AC, QN, KN, AC, AC, AC, PF }, 	 //	 909	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 910	 7500
{ KN, ST, AC, AC, AC, KN, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 911	 7500
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 912	 7500
{ KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 913	 7500
{ KN, JA, AC, AC, AC, KN, JA, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 914	 7500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, AC, LO, AC }, 	 //	 915	 7500
{ KN, TN, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 916	 7500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, PF, AC, LO, AC }, 	 //	 917	 7500
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 918	 7500
{ KN, SH, AC, TN, AC, KN, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 919	 7500
{ KN, SH, AC, PF, AC, KN, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 920	 7500
{ KN, AC, AC, AC, SH, KN, AC, AC, AC, JA, WN, AC, AC, AC, JA }, 	 //	 921	 7500
{ KN, AC, AC, TN, TN, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 922	 7500
{ KN, AC, AC, AC, JA, KN, AC, AC, AC, WN, WN, AC, AC, AC, TN }, 	 //	 923	 7500
{ KN, AC, AC, AC, CR, KN, AC, AC, AC, QN, WN, AC, AC, AC, KN }, 	 //	 924	 7500
{ KN, AC, AC, TN, TN, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 925	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 926	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 927	 7500
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, WN, ST, AC, AC, AC }, 	 //	 928	 7500
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 929	 7500
{ KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, WN, TN, AC, AC, AC }, 	 //	 930	 7500
{ KN, TN, AC, AC, AC, KN, TN, AC, AC, AC, WN, WN, AC, AC, AC }, 	 //	 931	 7500
{ KN, QN, AC, AC, AC, KN, ST, AC, AC, AC, WN, JA, AC, AC, AC }, 	 //	 932	 7500
{ KN, TN, AC, PF, LO, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 933	 7500
{ KN, TN, AC, TN, AC, KN, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 934	 7500
{ KN, AC, AC, AC, QN, KN, AC, AC, AC, QN, WN, AC, AC, AC, QN }, 	 //	 935	 7500
{ KN, AC, AC, TN, AC, KN, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 936	 7500
{ KN, AC, AC, TN, LO, KN, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 937	 7500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, WN, PF, AC, AC, SK }, 	 //	 938	 7500
{ KN, PF, AC, AC, AC, KN, KN, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 939	 7500
{ KN, KN, AC, PF, AC, KN, AC, AC, AC, AC, WN, SH, AC, AC, AC }, 	 //	 940	 7500
{ KN, SH, AC, TN, AC, WN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 941	 7500
{ KN, SH, AC, AC, AC, WN, AC, AC, AC, AC, QN, AC, AC, LO, AC }, 	 //	 942	 7500
{ KN, AC, AC, PF, TN, WN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 943	 7500
{ KN, AC, AC, AC, QN, WN, AC, AC, AC, PF, QN, AC, AC, AC, JA }, 	 //	 944	 7500
{ KN, AC, AC, AC, KN, WN, AC, AC, AC, SK, QN, AC, AC, AC, QN }, 	 //	 945	 7500
{ KN, AC, AC, AC, KN, WN, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 946	 7500
{ KN, KN, AC, AC, AC, WN, KN, AC, AC, AC, QN, ST, AC, AC, AC }, 	 //	 947	 7500
{ KN, ST, AC, AC, AC, WN, QN, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 948	 7500
{ KN, QN, AC, AC, AC, WN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 949	 7500
{ KN, SH, AC, AC, AC, WN, TN, AC, AC, AC, QN, TN, AC, AC, AC }, 	 //	 950	 7500
{ KN, KN, AC, AC, AC, WN, QN, AC, AC, AC, QN, ST, AC, AC, AC }, 	 //	 951	 7500
{ KN, AC, AC, AC, QN, WN, AC, AC, AC, QN, QN, AC, AC, AC, SH }, 	 //	 952	 7500
{ KN, AC, AC, AC, KN, WN, AC, AC, AC, QN, QN, AC, AC, AC, PF }, 	 //	 953	 7500
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, LO, QN, PF, AC, PF, AC }, 	 //	 954	 7500
{ KN, PF, AC, AC, AC, WN, KN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 955	 7500
{ KN, KN, AC, AC, AC, WN, KN, AC, AC, AC, QN, SK, AC, AC, AC }, 	 //	 956	 7500
{ KN, KN, AC, AC, AC, WN, AC, AC, AC, AC, QN, SH, AC, LO, AC }, 	 //	 957	 7500
{ WN, SH, AC, AC, LO, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 958	 7500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, LO, SK }, 	 //	 959	 7500
{ WN, AC, AC, AC, KN, QN, AC, AC, AC, KN, KN, AC, AC, AC, SK }, 	 //	 960	 7500
{ WN, AC, AC, AC, QN, QN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 961	 7500
{ WN, AC, AC, AC, QN, QN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 962	 7500
{ WN, AC, AC, AC, SK, QN, AC, AC, AC, KN, KN, AC, AC, AC, KN }, 	 //	 963	 7500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, LO, AC, LO, CR }, 	 //	 964	 7500
{ WN, QN, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 965	 7500
{ WN, SH, AC, AC, AC, QN, TN, AC, AC, AC, KN, TN, AC, AC, AC }, 	 //	 966	 7500
{ WN, WN, AC, AC, AC, QN, AC, AC, AC, AC, KN, KN, AC, PF, AC }, 	 //	 967	 7500
{ WN, KN, AC, AC, AC, QN, QN, AC, AC, AC, KN, ST, AC, AC, AC }, 	 //	 968	 7500
{ WN, AC, AC, PF, TN, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 969	 7500
{ WN, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC, QN }, 	 //	 970	 7500
{ WN, AC, AC, AC, QN, QN, AC, AC, AC, SH, KN, AC, AC, AC, JA }, 	 //	 971	 7500
{ WN, AC, AC, AC, TN, QN, AC, AC, AC, TN, KN, AC, AC, AC, TN }, 	 //	 972	 7500
{ WN, AC, AC, PF, TN, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 973	 7500
{ WN, AC, AC, AC, KN, QN, AC, AC, AC, KN, KN, AC, AC, AC, CR }, 	 //	 974	 7500
{ WN, AC, AC, AC, CR, QN, AC, AC, AC, QN, KN, AC, AC, AC, KN }, 	 //	 975	 7500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, LO, KN, PF, AC, PF, AC }, 	 //	 976	 7500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN, PF, AC, PF, CR }, 	 //	 977	 7500
{ WN, KN, AC, AC, AC, QN, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 978	 7500
{ QN, SH, AC, TN, AC, KN, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 979	 7500
{ QN, SH, AC, TN, AC, KN, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 980	 7500
{ QN, AC, AC, PF, KN, KN, AC, AC, AC, AC, AC, AC, AC, AC, LO }, 	 //	 981	 7500
{ QN, AC, AC, WN, AC, KN, AC, AC, AC, AC, AC, AC, AC, KN, SK }, 	 //	 982	 7500
{ QN, LO, AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 983	 7500
{ QN, LO, AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 984	 7500
{ QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC, ST, AC, AC, AC }, 	 //	 985	 7500
{ QN, KN, AC, AC, AC, KN, KN, AC, AC, AC, AC, ST, AC, AC, AC }, 	 //	 986	 7500
{ QN, QN, AC, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, AC }, 	 //	 987	 7500
{ QN, QN, AC, AC, AC, KN, QN, AC, AC, AC, AC, SK, AC, AC, AC }, 	 //	 988	 7500
{ QN, QN, AC, AC, AC, KN, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 989	 7500
{ QN, QN, AC, AC, AC, KN, SK, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 990	 7500
{ QN, JA, AC, AC, AC, KN, SH, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 991	 7500
{ QN, TN, AC, AC, AC, KN, TN, AC, AC, AC, AC, WN, AC, AC, AC }, 	 //	 992	 7500
{ QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC, ST, AC, AC, AC }, 	 //	 993	 7500
{ QN, QN, AC, AC, AC, KN, ST, AC, AC, AC, AC, JA, AC, AC, AC }, 	 //	 994	 7500
{ QN, ST, AC, AC, AC, KN, JA, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 995	 7500
{ QN, ST, AC, AC, AC, KN, JA, AC, AC, AC, AC, TN, AC, AC, AC }, 	 //	 996	 7500
{ QN, TN, AC, TN, ST, KN, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 997	 7500
{ QN, TN, AC, KN, AC, KN, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 998	 7500
{ QN, SK, AC, AC, AC, KN, QN, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 999	 7500
{ QN, QN, AC, AC, AC, KN, KN, AC, AC, AC, AC, AC, AC, LO, AC }};	 //	 1000	 7500
