unsigned char L5_Outcome_0320[1000][15]={	 //	 0	 320
{ AC, QN, QN, SK, SK, LO, SK, SK, JA, QN, AC, JA, JA, JA, QN }, 	 //	 1	 320
{ AC, QN, QN, SK, SK, LO, SK, SK, JA, KN, AC, JA, JA, JA, KN }, 	 //	 2	 320
{ AC, QN, SK, SK, SH, LO, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 3	 320
{ AC, QN, SK, SK, JA, LO, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 4	 320
{ AC, QN, SK, SK, JA, LO, SK, JA, JA, JA, AC, JA, TN, JA, WN }, 	 //	 5	 320
{ AC, QN, SK, SK, PF, LO, SK, JA, JA, JA, AC, JA, TN, JA, TN }, 	 //	 6	 320
{ AC, SK, QN, QN, KN, LO, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 7	 320
{ AC, SK, QN, QN, SK, LO, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 8	 320
{ AC, SK, QN, QN, AC, LO, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 9	 320
{ AC, SK, QN, QN, SK, LO, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 10	 320
{ AC, JA, QN, QN, KN, LO, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 11	 320
{ AC, JA, QN, QN, SK, LO, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 12	 320
{ AC, JA, QN, QN, AC, LO, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 13	 320
{ AC, JA, QN, QN, SK, LO, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 14	 320
{ AC, KN, SK, SK, SH, LO, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 15	 320
{ AC, KN, SK, SK, JA, LO, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 16	 320
{ AC, KN, SK, SK, JA, LO, SK, JA, JA, JA, AC, QN, TN, JA, WN }, 	 //	 17	 320
{ AC, KN, SK, SK, PF, LO, SK, JA, JA, JA, AC, QN, TN, JA, TN }, 	 //	 18	 320
{ LO, QN, QN, SK, SK, AC, SK, SK, JA, QN, AC, JA, JA, JA, QN }, 	 //	 19	 320
{ LO, QN, QN, SK, SK, AC, SK, SK, JA, KN, AC, JA, JA, JA, KN }, 	 //	 20	 320
{ LO, QN, SK, SK, SH, AC, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 21	 320
{ LO, QN, SK, SK, JA, AC, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 22	 320
{ LO, QN, SK, SK, JA, AC, SK, JA, JA, JA, AC, JA, TN, JA, WN }, 	 //	 23	 320
{ LO, QN, SK, SK, PF, AC, SK, JA, JA, JA, AC, JA, TN, JA, TN }, 	 //	 24	 320
{ LO, SK, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 25	 320
{ LO, SK, QN, QN, SK, AC, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 26	 320
{ LO, SK, QN, QN, AC, AC, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 27	 320
{ LO, SK, QN, QN, SK, AC, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 28	 320
{ LO, JA, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 29	 320
{ LO, JA, QN, QN, SK, AC, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 30	 320
{ LO, JA, QN, QN, AC, AC, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 31	 320
{ LO, JA, QN, QN, SK, AC, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 32	 320
{ LO, KN, SK, SK, SH, AC, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 33	 320
{ LO, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 34	 320
{ LO, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC, QN, TN, JA, WN }, 	 //	 35	 320
{ LO, KN, SK, SK, PF, AC, SK, JA, JA, JA, AC, QN, TN, JA, TN }, 	 //	 36	 320
{ AC, QN, QN, SK, SK, AC, SK, SK, JA, QN, AC, JA, JA, JA, QN }, 	 //	 37	 320
{ AC, QN, QN, SK, SK, AC, SK, SK, JA, KN, AC, JA, JA, JA, KN }, 	 //	 38	 320
{ AC, QN, SK, SK, SH, AC, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 39	 320
{ AC, QN, SK, SK, JA, AC, SK, JA, JA, JA, AC, JA, TN, JA, JA }, 	 //	 40	 320
{ AC, QN, SK, SK, JA, AC, SK, JA, JA, JA, AC, JA, TN, JA, WN }, 	 //	 41	 320
{ AC, QN, SK, SK, PF, AC, SK, JA, JA, JA, AC, JA, TN, JA, TN }, 	 //	 42	 320
{ AC, SK, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 43	 320
{ AC, SK, QN, QN, SK, AC, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 44	 320
{ AC, SK, QN, QN, AC, AC, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 45	 320
{ AC, SK, QN, QN, SK, AC, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 46	 320
{ AC, JA, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK }, 	 //	 47	 320
{ AC, JA, QN, QN, SK, AC, JA, SK, SK, QN, AC, JA, JA, JA, QN }, 	 //	 48	 320
{ AC, JA, QN, QN, AC, AC, JA, SK, SK, AC, AC, JA, JA, JA, SK }, 	 //	 49	 320
{ AC, JA, QN, QN, SK, AC, JA, SK, SK, KN, AC, JA, JA, JA, KN }, 	 //	 50	 320
{ AC, KN, SK, SK, SH, AC, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 51	 320
{ AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC, QN, TN, JA, JA }, 	 //	 52	 320
{ AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC, QN, TN, JA, WN }, 	 //	 53	 320
{ AC, KN, SK, SK, PF, AC, SK, JA, JA, JA, AC, QN, TN, JA, TN }, 	 //	 54	 320
{ AC, QN, QN, SK, SK, AC, SK, SK, JA, QN, ST, JA, JA, JA, QN }, 	 //	 55	 320
{ AC, QN, QN, SK, SK, AC, SK, SK, JA, KN, ST, JA, JA, JA, KN }, 	 //	 56	 320
{ AC, QN, SK, SK, SH, AC, SK, JA, JA, JA, ST, JA, TN, JA, JA }, 	 //	 57	 320
{ AC, QN, SK, SK, JA, AC, SK, JA, JA, JA, ST, JA, TN, JA, JA }, 	 //	 58	 320
{ AC, QN, SK, SK, JA, AC, SK, JA, JA, JA, ST, JA, TN, JA, WN }, 	 //	 59	 320
{ AC, QN, SK, SK, PF, AC, SK, JA, JA, JA, ST, JA, TN, JA, TN }, 	 //	 60	 320
{ AC, SK, QN, QN, KN, AC, JA, SK, SK, KN, ST, JA, JA, JA, SK }, 	 //	 61	 320
{ AC, SK, QN, QN, SK, AC, JA, SK, SK, QN, ST, JA, JA, JA, QN }, 	 //	 62	 320
{ AC, SK, QN, QN, AC, AC, JA, SK, SK, AC, ST, JA, JA, JA, SK }, 	 //	 63	 320
{ AC, SK, QN, QN, SK, AC, JA, SK, SK, KN, ST, JA, JA, JA, KN }, 	 //	 64	 320
{ AC, JA, QN, QN, KN, AC, JA, SK, SK, KN, ST, JA, JA, JA, SK }, 	 //	 65	 320
{ AC, JA, QN, QN, SK, AC, JA, SK, SK, QN, ST, JA, JA, JA, QN }, 	 //	 66	 320
{ AC, JA, QN, QN, AC, AC, JA, SK, SK, AC, ST, JA, JA, JA, SK }, 	 //	 67	 320
{ AC, JA, QN, QN, SK, AC, JA, SK, SK, KN, ST, JA, JA, JA, KN }, 	 //	 68	 320
{ AC, KN, SK, SK, SH, AC, SK, JA, JA, JA, ST, QN, TN, JA, JA }, 	 //	 69	 320
{ AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, ST, QN, TN, JA, JA }, 	 //	 70	 320
{ AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, ST, QN, TN, JA, WN }, 	 //	 71	 320
{ AC, KN, SK, SK, PF, AC, SK, JA, JA, JA, ST, QN, TN, JA, TN }, 	 //	 72	 320
{ AC, QN, QN, SK, SK, ST, SK, SK, JA, QN, KN, JA, JA, JA, QN }, 	 //	 73	 320
{ AC, QN, QN, SK, SK, ST, SK, SK, JA, KN, KN, JA, JA, JA, KN }, 	 //	 74	 320
{ AC, QN, SK, SK, SH, ST, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 75	 320
{ AC, QN, SK, SK, JA, ST, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 76	 320
{ AC, QN, SK, SK, JA, ST, SK, JA, JA, JA, KN, JA, TN, JA, WN }, 	 //	 77	 320
{ AC, QN, SK, SK, PF, ST, SK, JA, JA, JA, KN, JA, TN, JA, TN }, 	 //	 78	 320
{ AC, SK, QN, QN, KN, ST, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 79	 320
{ AC, SK, QN, QN, SK, ST, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 80	 320
{ AC, SK, QN, QN, AC, ST, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 81	 320
{ AC, SK, QN, QN, SK, ST, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 82	 320
{ AC, JA, QN, QN, KN, ST, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 83	 320
{ AC, JA, QN, QN, SK, ST, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 84	 320
{ AC, JA, QN, QN, AC, ST, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 85	 320
{ AC, JA, QN, QN, SK, ST, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 86	 320
{ AC, KN, SK, SK, SH, ST, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 87	 320
{ AC, KN, SK, SK, JA, ST, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 88	 320
{ AC, KN, SK, SK, JA, ST, SK, JA, JA, JA, KN, QN, TN, JA, WN }, 	 //	 89	 320
{ AC, KN, SK, SK, PF, ST, SK, JA, JA, JA, KN, QN, TN, JA, TN }, 	 //	 90	 320
{ ST, QN, QN, SK, SK, KN, SK, SK, JA, QN, KN, JA, JA, JA, QN }, 	 //	 91	 320
{ ST, QN, QN, SK, SK, KN, SK, SK, JA, KN, KN, JA, JA, JA, KN }, 	 //	 92	 320
{ ST, QN, SK, SK, SH, KN, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 93	 320
{ ST, QN, SK, SK, JA, KN, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 94	 320
{ ST, QN, SK, SK, JA, KN, SK, JA, JA, JA, KN, JA, TN, JA, WN }, 	 //	 95	 320
{ ST, QN, SK, SK, PF, KN, SK, JA, JA, JA, KN, JA, TN, JA, TN }, 	 //	 96	 320
{ ST, SK, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 97	 320
{ ST, SK, QN, QN, SK, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 98	 320
{ ST, SK, QN, QN, AC, KN, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 99	 320
{ ST, SK, QN, QN, SK, KN, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 100	 320
{ ST, JA, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 101	 320
{ ST, JA, QN, QN, SK, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 102	 320
{ ST, JA, QN, QN, AC, KN, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 103	 320
{ ST, JA, QN, QN, SK, KN, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 104	 320
{ ST, KN, SK, SK, SH, KN, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 105	 320
{ ST, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 106	 320
{ ST, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN, QN, TN, JA, WN }, 	 //	 107	 320
{ ST, KN, SK, SK, PF, KN, SK, JA, JA, JA, KN, QN, TN, JA, TN }, 	 //	 108	 320
{ KN, QN, QN, SK, SK, KN, SK, SK, JA, QN, KN, JA, JA, JA, QN }, 	 //	 109	 320
{ KN, QN, QN, SK, SK, KN, SK, SK, JA, KN, KN, JA, JA, JA, KN }, 	 //	 110	 320
{ KN, QN, SK, SK, SH, KN, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 111	 320
{ KN, QN, SK, SK, JA, KN, SK, JA, JA, JA, KN, JA, TN, JA, JA }, 	 //	 112	 320
{ KN, QN, SK, SK, JA, KN, SK, JA, JA, JA, KN, JA, TN, JA, WN }, 	 //	 113	 320
{ KN, QN, SK, SK, PF, KN, SK, JA, JA, JA, KN, JA, TN, JA, TN }, 	 //	 114	 320
{ KN, SK, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 115	 320
{ KN, SK, QN, QN, SK, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 116	 320
{ KN, SK, QN, QN, AC, KN, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 117	 320
{ KN, SK, QN, QN, SK, KN, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 118	 320
{ KN, JA, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK }, 	 //	 119	 320
{ KN, JA, QN, QN, SK, KN, JA, SK, SK, QN, KN, JA, JA, JA, QN }, 	 //	 120	 320
{ KN, JA, QN, QN, AC, KN, JA, SK, SK, AC, KN, JA, JA, JA, SK }, 	 //	 121	 320
{ KN, JA, QN, QN, SK, KN, JA, SK, SK, KN, KN, JA, JA, JA, KN }, 	 //	 122	 320
{ KN, KN, SK, SK, SH, KN, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 123	 320
{ KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN, QN, TN, JA, JA }, 	 //	 124	 320
{ KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN, QN, TN, JA, WN }, 	 //	 125	 320
{ KN, KN, SK, SK, PF, KN, SK, JA, JA, JA, KN, QN, TN, JA, TN }, 	 //	 126	 320
{ KN, QN, SK, SK, SH, KN, QN, JA, JA, JA, SK, SK, TN, JA, JA }, 	 //	 127	 320
{ KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, SK, SK, TN, JA, JA }, 	 //	 128	 320
{ KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, SK, SK, TN, JA, WN }, 	 //	 129	 320
{ KN, QN, SK, SK, PF, KN, QN, JA, JA, JA, SK, SK, TN, JA, TN }, 	 //	 130	 320
{ KN, QN, TN, QN, KN, KN, SK, LO, SK, KN, SK, JA, JA, JA, SK }, 	 //	 131	 320
{ KN, QN, TN, QN, KN, KN, SK, LO, SK, SK, SK, JA, JA, JA, QN }, 	 //	 132	 320
{ KN, QN, TN, QN, SK, KN, SK, LO, SK, QN, SK, JA, JA, JA, QN }, 	 //	 133	 320
{ KN, QN, TN, QN, AC, KN, SK, LO, SK, AC, SK, JA, JA, JA, SK }, 	 //	 134	 320
{ KN, QN, TN, QN, AC, KN, SK, LO, SK, SK, SK, JA, JA, JA, KN }, 	 //	 135	 320
{ KN, QN, TN, QN, SK, KN, SK, LO, SK, KN, SK, JA, JA, JA, KN }, 	 //	 136	 320
{ KN, QN, TN, SK, SK, KN, SK, LO, JA, QN, SK, JA, JA, JA, QN }, 	 //	 137	 320
{ KN, QN, TN, SK, SK, KN, SK, LO, JA, KN, SK, JA, JA, JA, KN }, 	 //	 138	 320
{ KN, QN, LO, QN, KN, KN, SK, JA, SK, KN, SK, JA, JA, JA, SK }, 	 //	 139	 320
{ KN, QN, LO, QN, KN, KN, SK, JA, SK, SK, SK, JA, JA, JA, QN }, 	 //	 140	 320
{ KN, QN, LO, QN, SK, KN, SK, JA, SK, QN, SK, JA, JA, JA, QN }, 	 //	 141	 320
{ KN, QN, LO, QN, AC, KN, SK, JA, SK, AC, SK, JA, JA, JA, SK }, 	 //	 142	 320
{ KN, QN, LO, QN, AC, KN, SK, JA, SK, SK, SK, JA, JA, JA, KN }, 	 //	 143	 320
{ KN, QN, LO, QN, SK, KN, SK, JA, SK, KN, SK, JA, JA, JA, KN }, 	 //	 144	 320
{ KN, QN, LO, SK, SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN }, 	 //	 145	 320
{ KN, QN, LO, SK, SK, KN, SK, JA, JA, KN, SK, JA, JA, JA, KN }, 	 //	 146	 320
{ KN, QN, JA, QN, KN, KN, SK, JA, SK, KN, SK, JA, JA, JA, SK }, 	 //	 147	 320
{ KN, QN, JA, QN, KN, KN, SK, JA, SK, SK, SK, JA, JA, JA, QN }, 	 //	 148	 320
{ KN, QN, JA, QN, SK, KN, SK, JA, SK, QN, SK, JA, JA, JA, QN }, 	 //	 149	 320
{ KN, QN, JA, QN, AC, KN, SK, JA, SK, AC, SK, JA, JA, JA, SK }, 	 //	 150	 320
{ KN, QN, JA, QN, AC, KN, SK, JA, SK, SK, SK, JA, JA, JA, KN }, 	 //	 151	 320
{ KN, QN, JA, QN, SK, KN, SK, JA, SK, KN, SK, JA, JA, JA, KN }, 	 //	 152	 320
{ KN, QN, JA, SK, SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN }, 	 //	 153	 320
{ KN, QN, JA, SK, SK, KN, SK, JA, JA, KN, SK, JA, JA, JA, KN }, 	 //	 154	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, LO, SK, JA, JA, JA, AC }, 	 //	 155	 320
{ KN, QN, QN, SK, LO, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 156	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 157	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, CR }, 	 //	 158	 320
{ KN, QN, QN, SK, CR, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 159	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 160	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, SK }, 	 //	 161	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, SK, SK, JA, JA, JA, QN }, 	 //	 162	 320
{ KN, QN, QN, SK, QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, QN }, 	 //	 163	 320
{ KN, QN, QN, SK, QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, SH }, 	 //	 164	 320
{ KN, QN, QN, SK, WN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN }, 	 //	 165	 320
{ KN, QN, QN, SK, TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN }, 	 //	 166	 320
{ KN, QN, QN, SK, TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, ST }, 	 //	 167	 320
{ KN, QN, QN, SK, TN, KN, SK, SK, JA, ST, SK, JA, JA, JA, AC }, 	 //	 168	 320
{ KN, QN, QN, SK, ST, KN, SK, SK, JA, AC, SK, JA, JA, JA, KN }, 	 //	 169	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, KN, SK, JA, JA, JA, QN }, 	 //	 170	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, QN, SK, JA, JA, JA, PF }, 	 //	 171	 320
{ KN, QN, QN, SK, PF, KN, SK, SK, JA, JA, SK, JA, JA, JA, TN }, 	 //	 172	 320
{ KN, QN, QN, SK, TN, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 173	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 174	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, SK }, 	 //	 175	 320
{ KN, QN, QN, SK, AC, KN, SK, SK, JA, SK, SK, JA, JA, JA, KN }, 	 //	 176	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 177	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, CR }, 	 //	 178	 320
{ KN, QN, QN, SK, CR, KN, SK, SK, JA, QN, SK, JA, JA, JA, KN }, 	 //	 179	 320
{ KN, QN, QN, SK, QN, KN, SK, SK, JA, KN, SK, JA, JA, JA, AC }, 	 //	 180	 320
{ KN, QN, QN, SK, KN, KN, SK, SK, JA, AC, SK, JA, JA, JA, LO }, 	 //	 181	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, LO, SK, JA, JA, JA, AC }, 	 //	 182	 320
{ KN, QN, QN, JA, LO, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 183	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 184	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, CR }, 	 //	 185	 320
{ KN, QN, QN, JA, CR, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 186	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 187	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, SK }, 	 //	 188	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, SK, SK, JA, JA, JA, QN }, 	 //	 189	 320
{ KN, QN, QN, JA, SK, KN, SK, SK, JA, QN, SK, JA, JA, JA, QN }, 	 //	 190	 320
{ KN, QN, QN, JA, QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, QN }, 	 //	 191	 320
{ KN, QN, QN, JA, QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, SH }, 	 //	 192	 320
{ KN, QN, QN, JA, WN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN }, 	 //	 193	 320
{ KN, QN, QN, JA, TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN }, 	 //	 194	 320
{ KN, QN, QN, JA, TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, ST }, 	 //	 195	 320
{ KN, QN, QN, JA, TN, KN, SK, SK, JA, ST, SK, JA, JA, JA, AC }, 	 //	 196	 320
{ KN, QN, QN, JA, ST, KN, SK, SK, JA, AC, SK, JA, JA, JA, KN }, 	 //	 197	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, KN, SK, JA, JA, JA, QN }, 	 //	 198	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, QN, SK, JA, JA, JA, PF }, 	 //	 199	 320
{ KN, QN, QN, JA, PF, KN, SK, SK, JA, JA, SK, JA, JA, JA, TN }, 	 //	 200	 320
{ KN, QN, QN, JA, TN, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 201	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, AC }, 	 //	 202	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, AC, SK, JA, JA, JA, SK }, 	 //	 203	 320
{ KN, QN, QN, JA, AC, KN, SK, SK, JA, SK, SK, JA, JA, JA, KN }, 	 //	 204	 320
{ KN, QN, QN, JA, SK, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 205	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, KN }, 	 //	 206	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, KN, SK, JA, JA, JA, CR }, 	 //	 207	 320
{ KN, QN, QN, JA, CR, KN, SK, SK, JA, QN, SK, JA, JA, JA, KN }, 	 //	 208	 320
{ KN, QN, QN, JA, QN, KN, SK, SK, JA, KN, SK, JA, JA, JA, AC }, 	 //	 209	 320
{ KN, QN, QN, JA, KN, KN, SK, SK, JA, AC, SK, JA, JA, JA, LO }, 	 //	 210	 320
{ KN, QN, QN, JA, JA, KN, SK, SK, JA, JA, SK, JA, JA, SH, JA }, 	 //	 211	 320
{ KN, QN, QN, JA, JA, KN, SK, SK, JA, JA, SK, JA, JA, SH, WN }, 	 //	 212	 320
{ KN, QN, QN, JA, JA, KN, SK, SK, JA, WN, SK, JA, JA, SH, TN }, 	 //	 213	 320
{ KN, QN, QN, JA, JA, KN, SK, SK, JA, TN, SK, JA, JA, SH, AC }, 	 //	 214	 320
{ KN, QN, QN, ST, JA, KN, SK, SK, JA, JA, SK, JA, JA, TN, JA }, 	 //	 215	 320
{ KN, QN, QN, ST, JA, KN, SK, SK, JA, JA, SK, JA, JA, TN, WN }, 	 //	 216	 320
{ KN, QN, QN, ST, JA, KN, SK, SK, JA, WN, SK, JA, JA, TN, TN }, 	 //	 217	 320
{ KN, QN, QN, ST, JA, KN, SK, SK, JA, TN, SK, JA, JA, TN, AC }, 	 //	 218	 320
{ KN, SK, QN, QN, KN, KN, JA, SK, SK, KN, SK, JA, JA, JA, SK }, 	 //	 219	 320
{ KN, SK, QN, QN, SK, KN, JA, SK, SK, QN, SK, JA, JA, JA, QN }, 	 //	 220	 320
{ KN, SK, QN, QN, AC, KN, JA, SK, SK, AC, SK, JA, JA, JA, SK }, 	 //	 221	 320
{ KN, SK, QN, QN, SK, KN, JA, SK, SK, KN, SK, JA, JA, JA, KN }, 	 //	 222	 320
{ KN, JA, QN, QN, KN, KN, JA, SK, SK, KN, SK, JA, JA, JA, SK }, 	 //	 223	 320
{ KN, JA, QN, QN, SK, KN, JA, SK, SK, QN, SK, JA, JA, JA, QN }, 	 //	 224	 320
{ KN, JA, QN, QN, AC, KN, JA, SK, SK, AC, SK, JA, JA, JA, SK }, 	 //	 225	 320
{ KN, JA, QN, QN, SK, KN, JA, SK, SK, KN, SK, JA, JA, JA, KN }, 	 //	 226	 320
{ KN, KN, QN, QN, SH, KN, KN, SK, SK, JA, SK, SK, JA, JA, JA }, 	 //	 227	 320
{ KN, KN, QN, QN, JA, KN, KN, SK, SK, JA, SK, SK, JA, JA, JA }, 	 //	 228	 320
{ KN, KN, SK, SK, SH, KN, KN, JA, JA, JA, SK, SK, TN, JA, JA }, 	 //	 229	 320
{ KN, KN, SK, SK, JA, KN, KN, JA, JA, JA, SK, SK, TN, JA, JA }, 	 //	 230	 320
{ KN, KN, SK, SK, JA, KN, KN, JA, JA, JA, SK, SK, TN, JA, WN }, 	 //	 231	 320
{ KN, KN, SK, SK, PF, KN, KN, JA, JA, JA, SK, SK, TN, JA, TN }, 	 //	 232	 320
{ KN, KN, QN, SK, QN, KN, SK, SK, JA, SH, SK, QN, JA, JA, JA }, 	 //	 233	 320
{ KN, KN, QN, SK, SH, KN, SK, SK, JA, JA, SK, QN, JA, JA, JA }, 	 //	 234	 320
{ KN, KN, QN, SK, JA, KN, SK, SK, JA, JA, SK, QN, JA, JA, WN }, 	 //	 235	 320
{ KN, KN, QN, SK, JA, KN, SK, SK, JA, WN, SK, QN, JA, JA, TN }, 	 //	 236	 320
{ KN, KN, QN, SK, QN, KN, SK, SK, JA, PF, SK, QN, JA, JA, JA }, 	 //	 237	 320
{ KN, KN, QN, SK, JA, KN, SK, SK, JA, TN, SK, QN, JA, JA, AC }, 	 //	 238	 320
{ KN, KN, QN, JA, QN, KN, SK, SK, JA, SH, SK, QN, JA, JA, JA }, 	 //	 239	 320
{ KN, KN, QN, JA, SH, KN, SK, SK, JA, JA, SK, QN, JA, JA, JA }, 	 //	 240	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, JA, SK, QN, JA, JA, WN }, 	 //	 241	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, WN, SK, QN, JA, JA, TN }, 	 //	 242	 320
{ KN, KN, QN, JA, QN, KN, SK, SK, JA, PF, SK, QN, JA, JA, JA }, 	 //	 243	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, TN, SK, QN, JA, JA, AC }, 	 //	 244	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, JA, SK, QN, JA, SH, JA }, 	 //	 245	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, JA, SK, QN, JA, SH, WN }, 	 //	 246	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, WN, SK, QN, JA, SH, TN }, 	 //	 247	 320
{ KN, KN, QN, JA, JA, KN, SK, SK, JA, TN, SK, QN, JA, SH, AC }, 	 //	 248	 320
{ KN, KN, QN, QN, SH, KN, SK, SK, ST, JA, SK, QN, JA, JA, JA }, 	 //	 249	 320
{ KN, KN, QN, QN, JA, KN, SK, SK, ST, JA, SK, QN, JA, JA, JA }, 	 //	 250	 320
{ KN, KN, QN, ST, JA, KN, SK, SK, JA, JA, SK, QN, JA, TN, JA }, 	 //	 251	 320
{ KN, KN, QN, ST, JA, KN, SK, SK, JA, JA, SK, QN, JA, TN, WN }, 	 //	 252	 320
{ KN, KN, QN, ST, JA, KN, SK, SK, JA, WN, SK, QN, JA, TN, TN }, 	 //	 253	 320
{ KN, KN, QN, ST, JA, KN, SK, SK, JA, TN, SK, QN, JA, TN, AC }, 	 //	 254	 320
{ KN, QN, TN, QN, KN, SK, SK, LO, SK, KN, QN, JA, JA, JA, SK }, 	 //	 255	 320
{ KN, QN, TN, QN, KN, SK, SK, LO, SK, SK, QN, JA, JA, JA, QN }, 	 //	 256	 320
{ KN, QN, TN, QN, SK, SK, SK, LO, SK, QN, QN, JA, JA, JA, QN }, 	 //	 257	 320
{ KN, QN, TN, QN, AC, SK, SK, LO, SK, AC, QN, JA, JA, JA, SK }, 	 //	 258	 320
{ KN, QN, TN, QN, AC, SK, SK, LO, SK, SK, QN, JA, JA, JA, KN }, 	 //	 259	 320
{ KN, QN, TN, QN, SK, SK, SK, LO, SK, KN, QN, JA, JA, JA, KN }, 	 //	 260	 320
{ KN, QN, TN, SK, SK, SK, SK, LO, JA, QN, QN, JA, JA, JA, QN }, 	 //	 261	 320
{ KN, QN, TN, SK, SK, SK, SK, LO, JA, KN, QN, JA, JA, JA, KN }, 	 //	 262	 320
{ KN, QN, LO, QN, KN, SK, SK, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 263	 320
{ KN, QN, LO, QN, KN, SK, SK, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 264	 320
{ KN, QN, LO, QN, SK, SK, SK, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 265	 320
{ KN, QN, LO, QN, AC, SK, SK, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 266	 320
{ KN, QN, LO, QN, AC, SK, SK, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 267	 320
{ KN, QN, LO, QN, SK, SK, SK, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 268	 320
{ KN, QN, LO, SK, SK, SK, SK, JA, JA, QN, QN, JA, JA, JA, QN }, 	 //	 269	 320
{ KN, QN, LO, SK, SK, SK, SK, JA, JA, KN, QN, JA, JA, JA, KN }, 	 //	 270	 320
{ KN, QN, JA, QN, KN, SK, SK, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 271	 320
{ KN, QN, JA, QN, KN, SK, SK, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 272	 320
{ KN, QN, JA, QN, SK, SK, SK, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 273	 320
{ KN, QN, JA, QN, AC, SK, SK, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 274	 320
{ KN, QN, JA, QN, AC, SK, SK, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 275	 320
{ KN, QN, JA, QN, SK, SK, SK, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 276	 320
{ KN, QN, JA, SK, SK, SK, SK, JA, JA, QN, QN, JA, JA, JA, QN }, 	 //	 277	 320
{ KN, QN, JA, SK, SK, SK, SK, JA, JA, KN, QN, JA, JA, JA, KN }, 	 //	 278	 320
{ KN, QN, SK, JA, SH, SK, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 279	 320
{ KN, QN, SK, JA, JA, SK, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 280	 320
{ KN, QN, SK, JA, JA, SK, SK, JA, JA, JA, QN, JA, TN, JA, WN }, 	 //	 281	 320
{ KN, QN, SK, JA, PF, SK, SK, JA, JA, JA, QN, JA, TN, JA, TN }, 	 //	 282	 320
{ KN, QN, SK, JA, SH, SK, SK, JA, JA, JA, QN, JA, TN, SH, JA }, 	 //	 283	 320
{ KN, QN, SK, JA, JA, SK, SK, JA, JA, JA, QN, JA, TN, SH, JA }, 	 //	 284	 320
{ KN, QN, SK, JA, JA, SK, SK, JA, JA, JA, QN, JA, TN, SH, WN }, 	 //	 285	 320
{ KN, QN, SK, JA, PF, SK, SK, JA, JA, JA, QN, JA, TN, SH, TN }, 	 //	 286	 320
{ KN, QN, SK, SH, TN, SK, SK, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 287	 320
{ KN, QN, SK, TN, TN, SK, SK, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 288	 320
{ KN, QN, SK, ST, SH, SK, SK, JA, JA, JA, QN, JA, TN, TN, JA }, 	 //	 289	 320
{ KN, QN, SK, ST, JA, SK, SK, JA, JA, JA, QN, JA, TN, TN, JA }, 	 //	 290	 320
{ KN, QN, SK, ST, JA, SK, SK, JA, JA, JA, QN, JA, TN, TN, WN }, 	 //	 291	 320
{ KN, SK, QN, QN, KN, SK, JA, SK, SK, KN, QN, JA, JA, JA, SK }, 	 //	 292	 320
{ KN, SK, QN, QN, SK, SK, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 293	 320
{ KN, SK, QN, QN, AC, SK, JA, SK, SK, AC, QN, JA, JA, JA, SK }, 	 //	 294	 320
{ KN, SK, QN, QN, SK, SK, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 295	 320
{ KN, JA, QN, QN, KN, SK, JA, SK, SK, KN, QN, JA, JA, JA, SK }, 	 //	 296	 320
{ KN, JA, QN, QN, SK, SK, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 297	 320
{ KN, JA, QN, QN, AC, SK, JA, SK, SK, AC, QN, JA, JA, JA, SK }, 	 //	 298	 320
{ KN, JA, QN, QN, SK, SK, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 299	 320
{ KN, KN, SK, JA, SH, SK, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 300	 320
{ KN, KN, SK, JA, JA, SK, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 301	 320
{ KN, KN, SK, JA, JA, SK, SK, JA, JA, JA, QN, QN, TN, JA, WN }, 	 //	 302	 320
{ KN, KN, SK, JA, PF, SK, SK, JA, JA, JA, QN, QN, TN, JA, TN }, 	 //	 303	 320
{ KN, KN, SK, JA, SH, SK, SK, JA, JA, JA, QN, QN, TN, SH, JA }, 	 //	 304	 320
{ KN, KN, SK, JA, JA, SK, SK, JA, JA, JA, QN, QN, TN, SH, JA }, 	 //	 305	 320
{ KN, KN, SK, JA, JA, SK, SK, JA, JA, JA, QN, QN, TN, SH, WN }, 	 //	 306	 320
{ KN, KN, SK, JA, PF, SK, SK, JA, JA, JA, QN, QN, TN, SH, TN }, 	 //	 307	 320
{ KN, KN, SK, SH, TN, SK, SK, JA, TN, TN, QN, QN, TN, TN, TN }, 	 //	 308	 320
{ KN, KN, SK, TN, TN, SK, SK, JA, TN, TN, QN, QN, TN, TN, TN }, 	 //	 309	 320
{ KN, KN, SK, ST, SH, SK, SK, JA, JA, JA, QN, QN, TN, TN, JA }, 	 //	 310	 320
{ KN, KN, SK, ST, JA, SK, SK, JA, JA, JA, QN, QN, TN, TN, JA }, 	 //	 311	 320
{ KN, KN, SK, ST, JA, SK, SK, JA, JA, JA, QN, QN, TN, TN, WN }, 	 //	 312	 320
{ SK, QN, TN, QN, KN, QN, SK, LO, SK, KN, QN, JA, JA, JA, SK }, 	 //	 313	 320
{ SK, QN, TN, QN, KN, QN, SK, LO, SK, SK, QN, JA, JA, JA, QN }, 	 //	 314	 320
{ SK, QN, TN, QN, SK, QN, SK, LO, SK, QN, QN, JA, JA, JA, QN }, 	 //	 315	 320
{ SK, QN, TN, QN, AC, QN, SK, LO, SK, AC, QN, JA, JA, JA, SK }, 	 //	 316	 320
{ SK, QN, TN, QN, AC, QN, SK, LO, SK, SK, QN, JA, JA, JA, KN }, 	 //	 317	 320
{ SK, QN, TN, QN, SK, QN, SK, LO, SK, KN, QN, JA, JA, JA, KN }, 	 //	 318	 320
{ SK, QN, TN, SK, SK, QN, SK, LO, JA, QN, QN, JA, JA, JA, QN }, 	 //	 319	 320
{ SK, QN, TN, SK, SK, QN, SK, LO, JA, KN, QN, JA, JA, JA, KN }, 	 //	 320	 320
{ SK, QN, LO, QN, KN, QN, SK, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 321	 320
{ SK, QN, LO, QN, KN, QN, SK, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 322	 320
{ SK, QN, LO, QN, SK, QN, SK, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 323	 320
{ SK, QN, LO, QN, AC, QN, SK, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 324	 320
{ SK, QN, LO, QN, AC, QN, SK, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 325	 320
{ SK, QN, LO, QN, SK, QN, SK, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 326	 320
{ SK, QN, LO, SK, SK, QN, SK, JA, JA, QN, QN, JA, JA, JA, QN }, 	 //	 327	 320
{ SK, QN, LO, SK, SK, QN, SK, JA, JA, KN, QN, JA, JA, JA, KN }, 	 //	 328	 320
{ SK, QN, JA, QN, KN, QN, SK, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 329	 320
{ SK, QN, JA, QN, KN, QN, SK, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 330	 320
{ SK, QN, JA, QN, SK, QN, SK, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 331	 320
{ SK, QN, JA, QN, AC, QN, SK, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 332	 320
{ SK, QN, JA, QN, AC, QN, SK, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 333	 320
{ SK, QN, JA, QN, SK, QN, SK, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 334	 320
{ SK, QN, JA, SK, SK, QN, SK, JA, JA, QN, QN, JA, JA, JA, QN }, 	 //	 335	 320
{ SK, QN, JA, SK, SK, QN, SK, JA, JA, KN, QN, JA, JA, JA, KN }, 	 //	 336	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, LO, QN, JA, JA, JA, AC }, 	 //	 337	 320
{ SK, QN, QN, SK, LO, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 338	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 339	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, CR }, 	 //	 340	 320
{ SK, QN, QN, SK, CR, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 341	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 342	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, SK }, 	 //	 343	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, SK, QN, JA, JA, JA, QN }, 	 //	 344	 320
{ SK, QN, QN, SK, QN, QN, SK, SK, JA, QN, QN, JA, JA, JA, QN }, 	 //	 345	 320
{ SK, QN, QN, SK, QN, QN, SK, SK, JA, QN, QN, JA, JA, JA, SH }, 	 //	 346	 320
{ SK, QN, QN, SK, WN, QN, SK, SK, JA, TN, QN, JA, JA, JA, TN }, 	 //	 347	 320
{ SK, QN, QN, SK, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA, TN }, 	 //	 348	 320
{ SK, QN, QN, SK, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA, ST }, 	 //	 349	 320
{ SK, QN, QN, SK, TN, QN, SK, SK, JA, ST, QN, JA, JA, JA, AC }, 	 //	 350	 320
{ SK, QN, QN, SK, ST, QN, SK, SK, JA, AC, QN, JA, JA, JA, KN }, 	 //	 351	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, KN, QN, JA, JA, JA, QN }, 	 //	 352	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, QN, QN, JA, JA, JA, PF }, 	 //	 353	 320
{ SK, QN, QN, SK, PF, QN, SK, SK, JA, JA, QN, JA, JA, JA, TN }, 	 //	 354	 320
{ SK, QN, QN, SK, TN, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 355	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 356	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, SK }, 	 //	 357	 320
{ SK, QN, QN, SK, AC, QN, SK, SK, JA, SK, QN, JA, JA, JA, KN }, 	 //	 358	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 359	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, CR }, 	 //	 360	 320
{ SK, QN, QN, SK, CR, QN, SK, SK, JA, QN, QN, JA, JA, JA, KN }, 	 //	 361	 320
{ SK, QN, QN, SK, QN, QN, SK, SK, JA, KN, QN, JA, JA, JA, AC }, 	 //	 362	 320
{ SK, QN, QN, SK, KN, QN, SK, SK, JA, AC, QN, JA, JA, JA, LO }, 	 //	 363	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, LO, QN, JA, JA, JA, AC }, 	 //	 364	 320
{ SK, QN, QN, JA, LO, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 365	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 366	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, CR }, 	 //	 367	 320
{ SK, QN, QN, JA, CR, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 368	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 369	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, SK }, 	 //	 370	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, SK, QN, JA, JA, JA, QN }, 	 //	 371	 320
{ SK, QN, QN, JA, SK, QN, SK, SK, JA, QN, QN, JA, JA, JA, QN }, 	 //	 372	 320
{ SK, QN, QN, JA, QN, QN, SK, SK, JA, QN, QN, JA, JA, JA, QN }, 	 //	 373	 320
{ SK, QN, QN, JA, QN, QN, SK, SK, JA, QN, QN, JA, JA, JA, SH }, 	 //	 374	 320
{ SK, QN, QN, JA, WN, QN, SK, SK, JA, TN, QN, JA, JA, JA, TN }, 	 //	 375	 320
{ SK, QN, QN, JA, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA, TN }, 	 //	 376	 320
{ SK, QN, QN, JA, TN, QN, SK, SK, JA, TN, QN, JA, JA, JA, ST }, 	 //	 377	 320
{ SK, QN, QN, JA, TN, QN, SK, SK, JA, ST, QN, JA, JA, JA, AC }, 	 //	 378	 320
{ SK, QN, QN, JA, ST, QN, SK, SK, JA, AC, QN, JA, JA, JA, KN }, 	 //	 379	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, KN, QN, JA, JA, JA, QN }, 	 //	 380	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, QN, QN, JA, JA, JA, PF }, 	 //	 381	 320
{ SK, QN, QN, JA, PF, QN, SK, SK, JA, JA, QN, JA, JA, JA, TN }, 	 //	 382	 320
{ SK, QN, QN, JA, TN, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 383	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, AC }, 	 //	 384	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, AC, QN, JA, JA, JA, SK }, 	 //	 385	 320
{ SK, QN, QN, JA, AC, QN, SK, SK, JA, SK, QN, JA, JA, JA, KN }, 	 //	 386	 320
{ SK, QN, QN, JA, SK, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 387	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, KN }, 	 //	 388	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, KN, QN, JA, JA, JA, CR }, 	 //	 389	 320
{ SK, QN, QN, JA, CR, QN, SK, SK, JA, QN, QN, JA, JA, JA, KN }, 	 //	 390	 320
{ SK, QN, QN, JA, QN, QN, SK, SK, JA, KN, QN, JA, JA, JA, AC }, 	 //	 391	 320
{ SK, QN, QN, JA, KN, QN, SK, SK, JA, AC, QN, JA, JA, JA, LO }, 	 //	 392	 320
{ SK, QN, QN, JA, JA, QN, SK, SK, JA, JA, QN, JA, JA, SH, JA }, 	 //	 393	 320
{ SK, QN, QN, JA, JA, QN, SK, SK, JA, JA, QN, JA, JA, SH, WN }, 	 //	 394	 320
{ SK, QN, QN, JA, JA, QN, SK, SK, JA, WN, QN, JA, JA, SH, TN }, 	 //	 395	 320
{ SK, QN, QN, JA, JA, QN, SK, SK, JA, TN, QN, JA, JA, SH, AC }, 	 //	 396	 320
{ SK, QN, QN, ST, JA, QN, SK, SK, JA, JA, QN, JA, JA, TN, JA }, 	 //	 397	 320
{ SK, QN, QN, ST, JA, QN, SK, SK, JA, JA, QN, JA, JA, TN, WN }, 	 //	 398	 320
{ SK, QN, QN, ST, JA, QN, SK, SK, JA, WN, QN, JA, JA, TN, TN }, 	 //	 399	 320
{ SK, QN, QN, ST, JA, QN, SK, SK, JA, TN, QN, JA, JA, TN, AC }, 	 //	 400	 320
{ SK, QN, SK, JA, SH, QN, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 401	 320
{ SK, QN, SK, JA, JA, QN, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 402	 320
{ SK, QN, SK, JA, JA, QN, SK, JA, JA, JA, QN, JA, TN, JA, WN }, 	 //	 403	 320
{ SK, QN, SK, JA, PF, QN, SK, JA, JA, JA, QN, JA, TN, JA, TN }, 	 //	 404	 320
{ SK, QN, SK, JA, SH, QN, SK, JA, JA, JA, QN, JA, TN, SH, JA }, 	 //	 405	 320
{ SK, QN, SK, JA, JA, QN, SK, JA, JA, JA, QN, JA, TN, SH, JA }, 	 //	 406	 320
{ SK, QN, SK, JA, JA, QN, SK, JA, JA, JA, QN, JA, TN, SH, WN }, 	 //	 407	 320
{ SK, QN, SK, JA, PF, QN, SK, JA, JA, JA, QN, JA, TN, SH, TN }, 	 //	 408	 320
{ SK, QN, SK, SH, TN, QN, SK, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 409	 320
{ SK, QN, SK, TN, TN, QN, SK, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 410	 320
{ SK, QN, SK, ST, SH, QN, SK, JA, JA, JA, QN, JA, TN, TN, JA }, 	 //	 411	 320
{ SK, QN, SK, ST, JA, QN, SK, JA, JA, JA, QN, JA, TN, TN, JA }, 	 //	 412	 320
{ SK, QN, SK, ST, JA, QN, SK, JA, JA, JA, QN, JA, TN, TN, WN }, 	 //	 413	 320
{ SK, SK, TN, QN, KN, QN, JA, LO, SK, KN, QN, JA, JA, JA, SK }, 	 //	 414	 320
{ SK, SK, TN, QN, KN, QN, JA, LO, SK, SK, QN, JA, JA, JA, QN }, 	 //	 415	 320
{ SK, SK, TN, QN, SK, QN, JA, LO, SK, QN, QN, JA, JA, JA, QN }, 	 //	 416	 320
{ SK, SK, TN, QN, AC, QN, JA, LO, SK, AC, QN, JA, JA, JA, SK }, 	 //	 417	 320
{ SK, SK, TN, QN, AC, QN, JA, LO, SK, SK, QN, JA, JA, JA, KN }, 	 //	 418	 320
{ SK, SK, TN, QN, SK, QN, JA, LO, SK, KN, QN, JA, JA, JA, KN }, 	 //	 419	 320
{ SK, SK, LO, QN, KN, QN, JA, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 420	 320
{ SK, SK, LO, QN, KN, QN, JA, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 421	 320
{ SK, SK, LO, QN, SK, QN, JA, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 422	 320
{ SK, SK, LO, QN, AC, QN, JA, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 423	 320
{ SK, SK, LO, QN, AC, QN, JA, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 424	 320
{ SK, SK, LO, QN, SK, QN, JA, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 425	 320
{ SK, SK, JA, QN, KN, QN, JA, JA, SK, KN, QN, JA, JA, JA, SK }, 	 //	 426	 320
{ SK, SK, JA, QN, KN, QN, JA, JA, SK, SK, QN, JA, JA, JA, QN }, 	 //	 427	 320
{ SK, SK, JA, QN, SK, QN, JA, JA, SK, QN, QN, JA, JA, JA, QN }, 	 //	 428	 320
{ SK, SK, JA, QN, AC, QN, JA, JA, SK, AC, QN, JA, JA, JA, SK }, 	 //	 429	 320
{ SK, SK, JA, QN, AC, QN, JA, JA, SK, SK, QN, JA, JA, JA, KN }, 	 //	 430	 320
{ SK, SK, JA, QN, SK, QN, JA, JA, SK, KN, QN, JA, JA, JA, KN }, 	 //	 431	 320
{ SK, SK, JA, SK, SK, QN, JA, ST, JA, QN, QN, JA, AC, JA, QN }, 	 //	 432	 320
{ SK, SK, JA, SK, SK, QN, JA, ST, JA, KN, QN, JA, AC, JA, KN }, 	 //	 433	 320
{ SK, SK, QN, QN, AC, QN, JA, SK, SK, LO, QN, JA, JA, JA, AC }, 	 //	 434	 320
{ SK, SK, QN, QN, LO, QN, JA, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 435	 320
{ SK, SK, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 436	 320
{ SK, SK, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, CR }, 	 //	 437	 320
{ SK, SK, QN, QN, CR, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 438	 320
{ SK, SK, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 439	 320
{ SK, SK, QN, QN, JA, QN, JA, SK, SK, JA, QN, JA, JA, JA, WN }, 	 //	 440	 320
{ SK, SK, QN, QN, JA, QN, JA, SK, SK, WN, QN, JA, JA, JA, TN }, 	 //	 441	 320
{ SK, SK, QN, QN, WN, QN, JA, SK, SK, TN, QN, JA, JA, JA, TN }, 	 //	 442	 320
{ SK, SK, QN, QN, TN, QN, JA, SK, SK, TN, QN, JA, JA, JA, TN }, 	 //	 443	 320
{ SK, SK, QN, QN, TN, QN, JA, SK, SK, TN, QN, JA, JA, JA, ST }, 	 //	 444	 320
{ SK, SK, QN, QN, TN, QN, JA, SK, SK, ST, QN, JA, JA, JA, AC }, 	 //	 445	 320
{ SK, SK, QN, QN, ST, QN, JA, SK, SK, AC, QN, JA, JA, JA, KN }, 	 //	 446	 320
{ SK, SK, QN, QN, AC, QN, JA, SK, SK, KN, QN, JA, JA, JA, QN }, 	 //	 447	 320
{ SK, SK, QN, QN, KN, QN, JA, SK, SK, QN, QN, JA, JA, JA, PF }, 	 //	 448	 320
{ SK, SK, QN, QN, PF, QN, JA, SK, SK, JA, QN, JA, JA, JA, TN }, 	 //	 449	 320
{ SK, SK, QN, QN, JA, QN, JA, SK, SK, TN, QN, JA, JA, JA, AC }, 	 //	 450	 320
{ SK, SK, QN, QN, TN, QN, JA, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 451	 320
{ SK, SK, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, AC }, 	 //	 452	 320
{ SK, SK, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 453	 320
{ SK, SK, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, CR }, 	 //	 454	 320
{ SK, SK, QN, QN, CR, QN, JA, SK, SK, QN, QN, JA, JA, JA, KN }, 	 //	 455	 320
{ SK, SK, QN, QN, KN, QN, JA, SK, SK, AC, QN, JA, JA, JA, LO }, 	 //	 456	 320
{ SK, SK, JA, SK, SK, QN, JA, TN, JA, QN, QN, JA, AC, JA, QN }, 	 //	 457	 320
{ SK, SK, JA, SK, SK, QN, JA, TN, JA, KN, QN, JA, AC, JA, KN }, 	 //	 458	 320
{ SK, JA, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, SK }, 	 //	 459	 320
{ SK, JA, QN, QN, SK, QN, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 460	 320
{ SK, JA, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, SK }, 	 //	 461	 320
{ SK, JA, QN, QN, SK, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 462	 320
{ SK, KN, QN, SK, QN, QN, SK, SK, JA, SH, QN, QN, JA, JA, JA }, 	 //	 463	 320
{ SK, KN, QN, SK, SH, QN, SK, SK, JA, JA, QN, QN, JA, JA, JA }, 	 //	 464	 320
{ SK, KN, QN, SK, JA, QN, SK, SK, JA, JA, QN, QN, JA, JA, WN }, 	 //	 465	 320
{ SK, KN, QN, SK, JA, QN, SK, SK, JA, WN, QN, QN, JA, JA, TN }, 	 //	 466	 320
{ SK, KN, QN, SK, QN, QN, SK, SK, JA, PF, QN, QN, JA, JA, JA }, 	 //	 467	 320
{ SK, KN, QN, SK, JA, QN, SK, SK, JA, TN, QN, QN, JA, JA, AC }, 	 //	 468	 320
{ SK, KN, QN, JA, QN, QN, SK, SK, JA, SH, QN, QN, JA, JA, JA }, 	 //	 469	 320
{ SK, KN, QN, JA, SH, QN, SK, SK, JA, JA, QN, QN, JA, JA, JA }, 	 //	 470	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, JA, QN, QN, JA, JA, WN }, 	 //	 471	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, WN, QN, QN, JA, JA, TN }, 	 //	 472	 320
{ SK, KN, QN, JA, QN, QN, SK, SK, JA, PF, QN, QN, JA, JA, JA }, 	 //	 473	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, TN, QN, QN, JA, JA, AC }, 	 //	 474	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, JA, QN, QN, JA, SH, JA }, 	 //	 475	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, JA, QN, QN, JA, SH, WN }, 	 //	 476	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, WN, QN, QN, JA, SH, TN }, 	 //	 477	 320
{ SK, KN, QN, JA, JA, QN, SK, SK, JA, TN, QN, QN, JA, SH, AC }, 	 //	 478	 320
{ SK, KN, QN, QN, SH, QN, SK, SK, ST, JA, QN, QN, JA, JA, JA }, 	 //	 479	 320
{ SK, KN, QN, QN, JA, QN, SK, SK, ST, JA, QN, QN, JA, JA, JA }, 	 //	 480	 320
{ SK, KN, QN, ST, JA, QN, SK, SK, JA, JA, QN, QN, JA, TN, JA }, 	 //	 481	 320
{ SK, KN, QN, ST, JA, QN, SK, SK, JA, JA, QN, QN, JA, TN, WN }, 	 //	 482	 320
{ SK, KN, QN, ST, JA, QN, SK, SK, JA, WN, QN, QN, JA, TN, TN }, 	 //	 483	 320
{ SK, KN, QN, ST, JA, QN, SK, SK, JA, TN, QN, QN, JA, TN, AC }, 	 //	 484	 320
{ SK, KN, SK, JA, SH, QN, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 485	 320
{ SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 486	 320
{ SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN, QN, TN, JA, WN }, 	 //	 487	 320
{ SK, KN, SK, JA, PF, QN, SK, JA, JA, JA, QN, QN, TN, JA, TN }, 	 //	 488	 320
{ SK, KN, SK, JA, SH, QN, SK, JA, JA, JA, QN, QN, TN, SH, JA }, 	 //	 489	 320
{ SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN, QN, TN, SH, JA }, 	 //	 490	 320
{ SK, KN, SK, JA, JA, QN, SK, JA, JA, JA, QN, QN, TN, SH, WN }, 	 //	 491	 320
{ SK, KN, SK, JA, PF, QN, SK, JA, JA, JA, QN, QN, TN, SH, TN }, 	 //	 492	 320
{ SK, KN, SK, SH, TN, QN, SK, JA, TN, TN, QN, QN, TN, TN, TN }, 	 //	 493	 320
{ SK, KN, SK, TN, TN, QN, SK, JA, TN, TN, QN, QN, TN, TN, TN }, 	 //	 494	 320
{ SK, KN, SK, ST, SH, QN, SK, JA, JA, JA, QN, QN, TN, TN, JA }, 	 //	 495	 320
{ SK, KN, SK, ST, JA, QN, SK, JA, JA, JA, QN, QN, TN, TN, JA }, 	 //	 496	 320
{ SK, KN, SK, ST, JA, QN, SK, JA, JA, JA, QN, QN, TN, TN, WN }, 	 //	 497	 320
{ QN, QN, SK, SK, SH, QN, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 498	 320
{ QN, QN, SK, SK, JA, QN, SK, JA, JA, JA, QN, JA, TN, JA, JA }, 	 //	 499	 320
{ QN, QN, SK, SK, JA, QN, SK, JA, JA, JA, QN, JA, TN, JA, WN }, 	 //	 500	 320
{ QN, QN, SK, SK, PF, QN, SK, JA, JA, JA, QN, JA, TN, JA, TN }, 	 //	 501	 320
{ QN, SK, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, SK }, 	 //	 502	 320
{ QN, SK, QN, QN, SK, QN, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 503	 320
{ QN, SK, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, SK }, 	 //	 504	 320
{ QN, SK, QN, QN, SK, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 505	 320
{ QN, JA, QN, QN, KN, QN, JA, SK, SK, KN, QN, JA, JA, JA, SK }, 	 //	 506	 320
{ QN, JA, QN, QN, SK, QN, JA, SK, SK, QN, QN, JA, JA, JA, QN }, 	 //	 507	 320
{ QN, JA, QN, QN, AC, QN, JA, SK, SK, AC, QN, JA, JA, JA, SK }, 	 //	 508	 320
{ QN, JA, QN, QN, SK, QN, JA, SK, SK, KN, QN, JA, JA, JA, KN }, 	 //	 509	 320
{ QN, KN, SK, SK, SH, QN, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 510	 320
{ QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, QN, QN, TN, JA, JA }, 	 //	 511	 320
{ QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, QN, QN, TN, JA, WN }, 	 //	 512	 320
{ QN, KN, SK, SK, PF, QN, SK, JA, JA, JA, QN, QN, TN, JA, TN }, 	 //	 513	 320
{ QN, QN, SK, SK, SH, QN, SK, JA, JA, JA, SH, JA, TN, JA, JA }, 	 //	 514	 320
{ QN, QN, SK, SK, JA, QN, SK, JA, JA, JA, SH, JA, TN, JA, JA }, 	 //	 515	 320
{ QN, QN, SK, SK, JA, QN, SK, JA, JA, JA, SH, JA, TN, JA, WN }, 	 //	 516	 320
{ QN, QN, SK, SK, PF, QN, SK, JA, JA, JA, SH, JA, TN, JA, TN }, 	 //	 517	 320
{ QN, SK, QN, QN, KN, QN, JA, SK, SK, KN, SH, JA, JA, JA, SK }, 	 //	 518	 320
{ QN, SK, QN, QN, SK, QN, JA, SK, SK, QN, SH, JA, JA, JA, QN }, 	 //	 519	 320
{ QN, SK, QN, QN, AC, QN, JA, SK, SK, AC, SH, JA, JA, JA, SK }, 	 //	 520	 320
{ QN, SK, QN, QN, SK, QN, JA, SK, SK, KN, SH, JA, JA, JA, KN }, 	 //	 521	 320
{ QN, JA, QN, QN, KN, QN, JA, SK, SK, KN, SH, JA, JA, JA, SK }, 	 //	 522	 320
{ QN, JA, QN, QN, SK, QN, JA, SK, SK, QN, SH, JA, JA, JA, QN }, 	 //	 523	 320
{ QN, JA, QN, QN, AC, QN, JA, SK, SK, AC, SH, JA, JA, JA, SK }, 	 //	 524	 320
{ QN, JA, QN, QN, SK, QN, JA, SK, SK, KN, SH, JA, JA, JA, KN }, 	 //	 525	 320
{ QN, KN, SK, SK, SH, QN, SK, JA, JA, JA, SH, QN, TN, JA, JA }, 	 //	 526	 320
{ QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, SH, QN, TN, JA, JA }, 	 //	 527	 320
{ QN, KN, SK, SK, JA, QN, SK, JA, JA, JA, SH, QN, TN, JA, WN }, 	 //	 528	 320
{ QN, KN, SK, SK, PF, QN, SK, JA, JA, JA, SH, QN, TN, JA, TN }, 	 //	 529	 320
{ QN, QN, SK, SK, SH, SH, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 530	 320
{ QN, QN, SK, SK, JA, SH, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 531	 320
{ QN, QN, SK, SK, JA, SH, SK, JA, JA, JA, JA, JA, TN, JA, WN }, 	 //	 532	 320
{ QN, QN, SK, SK, PF, SH, SK, JA, JA, JA, JA, JA, TN, JA, TN }, 	 //	 533	 320
{ QN, SK, QN, KN, KN, SH, JA, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 534	 320
{ QN, SK, QN, KN, SK, SH, JA, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 535	 320
{ QN, SK, QN, KN, AC, SH, JA, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 536	 320
{ QN, SK, QN, KN, SK, SH, JA, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 537	 320
{ QN, JA, QN, KN, KN, SH, JA, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 538	 320
{ QN, JA, QN, KN, SK, SH, JA, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 539	 320
{ QN, JA, QN, KN, AC, SH, JA, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 540	 320
{ QN, JA, QN, KN, SK, SH, JA, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 541	 320
{ QN, KN, SK, SK, SH, SH, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 542	 320
{ QN, KN, SK, SK, JA, SH, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 543	 320
{ QN, KN, SK, SK, JA, SH, SK, JA, JA, JA, JA, QN, TN, JA, WN }, 	 //	 544	 320
{ QN, KN, SK, SK, PF, SH, SK, JA, JA, JA, JA, QN, TN, JA, TN }, 	 //	 545	 320
{ SH, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK, SK }, 	 //	 546	 320
{ SH, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK, SK }, 	 //	 547	 320
{ SH, QN, QN, SK, SK, JA, SK, SK, QN, KN, JA, JA, JA, KN, KN }, 	 //	 548	 320
{ SH, QN, SK, SK, SH, JA, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 549	 320
{ SH, QN, SK, SK, JA, JA, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 550	 320
{ SH, QN, SK, SK, JA, JA, SK, JA, JA, JA, JA, JA, TN, JA, WN }, 	 //	 551	 320
{ SH, QN, SK, SK, PF, JA, SK, JA, JA, JA, JA, JA, TN, JA, TN }, 	 //	 552	 320
{ SH, SK, QN, KN, KN, JA, JA, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 553	 320
{ SH, SK, QN, KN, SK, JA, JA, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 554	 320
{ SH, SK, QN, KN, AC, JA, JA, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 555	 320
{ SH, SK, QN, KN, SK, JA, JA, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 556	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, QN, KN, JA, JA, TN, SK, SK }, 	 //	 557	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, QN, AC, JA, JA, TN, SK, SK }, 	 //	 558	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, SK, LO, JA, JA, TN, JA, AC }, 	 //	 559	 320
{ SH, SK, SK, QN, LO, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 560	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 561	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, CR }, 	 //	 562	 320
{ SH, SK, SK, QN, CR, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 563	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 564	 320
{ SH, SK, SK, QN, QN, JA, JA, JA, SK, QN, JA, JA, TN, JA, QN }, 	 //	 565	 320
{ SH, SK, SK, QN, QN, JA, JA, JA, SK, QN, JA, JA, TN, JA, SH }, 	 //	 566	 320
{ SH, SK, SK, QN, QN, JA, JA, JA, SK, SH, JA, JA, TN, JA, JA }, 	 //	 567	 320
{ SH, SK, SK, QN, SH, JA, JA, JA, SK, JA, JA, JA, TN, JA, JA }, 	 //	 568	 320
{ SH, SK, SK, QN, JA, JA, JA, JA, SK, JA, JA, JA, TN, JA, JA }, 	 //	 569	 320
{ SH, SK, SK, QN, JA, JA, JA, JA, SK, JA, JA, JA, TN, JA, WN }, 	 //	 570	 320
{ SH, SK, SK, QN, JA, JA, JA, JA, SK, WN, JA, JA, TN, JA, TN }, 	 //	 571	 320
{ SH, SK, SK, QN, WN, JA, JA, JA, SK, TN, JA, JA, TN, JA, TN }, 	 //	 572	 320
{ SH, SK, SK, QN, TN, JA, JA, JA, SK, TN, JA, JA, TN, JA, TN }, 	 //	 573	 320
{ SH, SK, SK, QN, TN, JA, JA, JA, SK, TN, JA, JA, TN, JA, ST }, 	 //	 574	 320
{ SH, SK, SK, QN, TN, JA, JA, JA, SK, ST, JA, JA, TN, JA, AC }, 	 //	 575	 320
{ SH, SK, SK, QN, ST, JA, JA, JA, SK, AC, JA, JA, TN, JA, KN }, 	 //	 576	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, SK, KN, JA, JA, TN, JA, QN }, 	 //	 577	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, SK, QN, JA, JA, TN, JA, PF }, 	 //	 578	 320
{ SH, SK, SK, QN, QN, JA, JA, JA, SK, PF, JA, JA, TN, JA, JA }, 	 //	 579	 320
{ SH, SK, SK, QN, PF, JA, JA, JA, SK, JA, JA, JA, TN, JA, TN }, 	 //	 580	 320
{ SH, SK, SK, QN, JA, JA, JA, JA, SK, TN, JA, JA, TN, JA, AC }, 	 //	 581	 320
{ SH, SK, SK, QN, TN, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 582	 320
{ SH, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 583	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 584	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, CR }, 	 //	 585	 320
{ SH, SK, SK, QN, CR, JA, JA, JA, SK, QN, JA, JA, TN, JA, KN }, 	 //	 586	 320
{ SH, SK, SK, QN, QN, JA, JA, JA, SK, KN, JA, JA, TN, JA, AC }, 	 //	 587	 320
{ SH, SK, SK, QN, KN, JA, JA, JA, SK, AC, JA, JA, TN, JA, LO }, 	 //	 588	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, KN, KN, JA, JA, TN, SK, SK }, 	 //	 589	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, KN, AC, JA, JA, TN, SK, SK }, 	 //	 590	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, SK, LO, JA, JA, TN, QN, AC }, 	 //	 591	 320
{ SH, SK, SK, KN, LO, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 592	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 593	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, CR }, 	 //	 594	 320
{ SH, SK, SK, KN, CR, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 595	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 596	 320
{ SH, SK, SK, KN, QN, JA, JA, JA, SK, QN, JA, JA, TN, QN, QN }, 	 //	 597	 320
{ SH, SK, SK, KN, QN, JA, JA, JA, SK, QN, JA, JA, TN, QN, SH }, 	 //	 598	 320
{ SH, SK, SK, KN, QN, JA, JA, JA, SK, SH, JA, JA, TN, QN, JA }, 	 //	 599	 320
{ SH, SK, SK, KN, SH, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA }, 	 //	 600	 320
{ SH, SK, SK, KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA }, 	 //	 601	 320
{ SH, SK, SK, KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, WN }, 	 //	 602	 320
{ SH, SK, SK, KN, JA, JA, JA, JA, SK, WN, JA, JA, TN, QN, TN }, 	 //	 603	 320
{ SH, SK, SK, KN, WN, JA, JA, JA, SK, TN, JA, JA, TN, QN, TN }, 	 //	 604	 320
{ SH, SK, SK, KN, TN, JA, JA, JA, SK, TN, JA, JA, TN, QN, TN }, 	 //	 605	 320
{ SH, SK, SK, KN, TN, JA, JA, JA, SK, TN, JA, JA, TN, QN, ST }, 	 //	 606	 320
{ SH, SK, SK, KN, TN, JA, JA, JA, SK, ST, JA, JA, TN, QN, AC }, 	 //	 607	 320
{ SH, SK, SK, KN, ST, JA, JA, JA, SK, AC, JA, JA, TN, QN, KN }, 	 //	 608	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, SK, KN, JA, JA, TN, QN, QN }, 	 //	 609	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, SK, QN, JA, JA, TN, QN, PF }, 	 //	 610	 320
{ SH, SK, SK, KN, QN, JA, JA, JA, SK, PF, JA, JA, TN, QN, JA }, 	 //	 611	 320
{ SH, SK, SK, KN, PF, JA, JA, JA, SK, JA, JA, JA, TN, QN, TN }, 	 //	 612	 320
{ SH, SK, SK, KN, JA, JA, JA, JA, SK, TN, JA, JA, TN, QN, AC }, 	 //	 613	 320
{ SH, SK, SK, KN, TN, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 614	 320
{ SH, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 615	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 616	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, CR }, 	 //	 617	 320
{ SH, SK, SK, KN, CR, JA, JA, JA, SK, QN, JA, JA, TN, QN, KN }, 	 //	 618	 320
{ SH, SK, SK, KN, QN, JA, JA, JA, SK, KN, JA, JA, TN, QN, AC }, 	 //	 619	 320
{ SH, SK, SK, KN, KN, JA, JA, JA, SK, AC, JA, JA, TN, QN, LO }, 	 //	 620	 320
{ SH, JA, QN, KN, KN, JA, JA, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 621	 320
{ SH, JA, QN, KN, SK, JA, JA, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 622	 320
{ SH, JA, QN, KN, AC, JA, JA, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 623	 320
{ SH, JA, QN, KN, SK, JA, JA, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 624	 320
{ SH, JA, SK, QN, KN, JA, JA, JA, SK, SK, JA, JA, TN, JA, QN }, 	 //	 625	 320
{ SH, JA, SK, QN, SK, JA, JA, JA, SK, QN, JA, JA, TN, JA, QN }, 	 //	 626	 320
{ SH, JA, SK, QN, AC, JA, JA, JA, SK, SK, JA, JA, TN, JA, KN }, 	 //	 627	 320
{ SH, JA, SK, QN, SK, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 628	 320
{ SH, JA, SK, KN, KN, JA, JA, JA, SK, SK, JA, JA, TN, QN, QN }, 	 //	 629	 320
{ SH, JA, SK, KN, SK, JA, JA, JA, SK, QN, JA, JA, TN, QN, QN }, 	 //	 630	 320
{ SH, JA, SK, KN, AC, JA, JA, JA, SK, SK, JA, JA, TN, QN, KN }, 	 //	 631	 320
{ SH, JA, SK, KN, SK, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 632	 320
{ SH, JA, SK, QN, KN, JA, JA, JA, SK, SK, JA, SH, TN, JA, QN }, 	 //	 633	 320
{ SH, JA, SK, QN, SK, JA, JA, JA, SK, QN, JA, SH, TN, JA, QN }, 	 //	 634	 320
{ SH, JA, SK, QN, AC, JA, JA, JA, SK, SK, JA, SH, TN, JA, KN }, 	 //	 635	 320
{ SH, JA, SK, QN, SK, JA, JA, JA, SK, KN, JA, SH, TN, JA, KN }, 	 //	 636	 320
{ SH, JA, SK, KN, KN, JA, JA, JA, SK, SK, JA, SH, TN, QN, QN }, 	 //	 637	 320
{ SH, JA, SK, KN, SK, JA, JA, JA, SK, QN, JA, SH, TN, QN, QN }, 	 //	 638	 320
{ SH, JA, SK, KN, AC, JA, JA, JA, SK, SK, JA, SH, TN, QN, KN }, 	 //	 639	 320
{ SH, JA, SK, KN, SK, JA, JA, JA, SK, KN, JA, SH, TN, QN, KN }, 	 //	 640	 320
{ SH, QN, QN, KN, KN, JA, ST, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 641	 320
{ SH, QN, QN, KN, SK, JA, ST, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 642	 320
{ SH, QN, QN, KN, AC, JA, ST, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 643	 320
{ SH, QN, QN, KN, SK, JA, ST, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 644	 320
{ SH, ST, SK, QN, KN, JA, JA, JA, SK, SK, JA, TN, TN, JA, QN }, 	 //	 645	 320
{ SH, ST, SK, QN, SK, JA, JA, JA, SK, QN, JA, TN, TN, JA, QN }, 	 //	 646	 320
{ SH, ST, SK, QN, AC, JA, JA, JA, SK, SK, JA, TN, TN, JA, KN }, 	 //	 647	 320
{ SH, ST, SK, QN, SK, JA, JA, JA, SK, KN, JA, TN, TN, JA, KN }, 	 //	 648	 320
{ SH, ST, SK, KN, KN, JA, JA, JA, SK, SK, JA, TN, TN, QN, QN }, 	 //	 649	 320
{ SH, ST, SK, KN, SK, JA, JA, JA, SK, QN, JA, TN, TN, QN, QN }, 	 //	 650	 320
{ SH, ST, SK, KN, AC, JA, JA, JA, SK, SK, JA, TN, TN, QN, KN }, 	 //	 651	 320
{ SH, ST, SK, KN, SK, JA, JA, JA, SK, KN, JA, TN, TN, QN, KN }, 	 //	 652	 320
{ SH, KN, SK, SK, SH, JA, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 653	 320
{ SH, KN, SK, SK, JA, JA, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 654	 320
{ SH, KN, SK, SK, JA, JA, SK, JA, JA, JA, JA, QN, TN, JA, WN }, 	 //	 655	 320
{ SH, KN, SK, SK, PF, JA, SK, JA, JA, JA, JA, QN, TN, JA, TN }, 	 //	 656	 320
{ JA, QN, QN, KN, KN, JA, SK, SK, KN, KN, JA, JA, JA, SK, SK }, 	 //	 657	 320
{ JA, QN, QN, KN, AC, JA, SK, SK, KN, AC, JA, JA, JA, SK, SK }, 	 //	 658	 320
{ JA, QN, QN, SK, SK, JA, SK, SK, QN, KN, JA, JA, JA, KN, KN }, 	 //	 659	 320
{ JA, QN, SK, SK, SH, JA, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 660	 320
{ JA, QN, SK, SK, JA, JA, SK, JA, JA, JA, JA, JA, TN, JA, JA }, 	 //	 661	 320
{ JA, QN, SK, SK, JA, JA, SK, JA, JA, JA, JA, JA, TN, JA, WN }, 	 //	 662	 320
{ JA, QN, SK, SK, PF, JA, SK, JA, JA, JA, JA, JA, TN, JA, TN }, 	 //	 663	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, QN, KN, JA, JA, TN, SK, SK }, 	 //	 664	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, QN, AC, JA, JA, TN, SK, SK }, 	 //	 665	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, LO, JA, JA, TN, JA, AC }, 	 //	 666	 320
{ JA, SK, SK, QN, LO, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 667	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 668	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, CR }, 	 //	 669	 320
{ JA, SK, SK, QN, CR, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 670	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 671	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, QN, JA, JA, TN, JA, QN }, 	 //	 672	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, QN, JA, JA, TN, JA, SH }, 	 //	 673	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, SH, JA, JA, TN, JA, JA }, 	 //	 674	 320
{ JA, SK, SK, QN, SH, JA, JA, JA, SK, JA, JA, JA, TN, JA, JA }, 	 //	 675	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, JA, JA, JA, TN, JA, JA }, 	 //	 676	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, JA, JA, JA, TN, JA, WN }, 	 //	 677	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, WN, JA, JA, TN, JA, TN }, 	 //	 678	 320
{ JA, SK, SK, QN, WN, JA, JA, JA, SK, TN, JA, JA, TN, JA, TN }, 	 //	 679	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, TN, JA, JA, TN, JA, TN }, 	 //	 680	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, TN, JA, JA, TN, JA, ST }, 	 //	 681	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, ST, JA, JA, TN, JA, AC }, 	 //	 682	 320
{ JA, SK, SK, QN, ST, JA, JA, JA, SK, AC, JA, JA, TN, JA, KN }, 	 //	 683	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, KN, JA, JA, TN, JA, QN }, 	 //	 684	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, QN, JA, JA, TN, JA, PF }, 	 //	 685	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, PF, JA, JA, TN, JA, JA }, 	 //	 686	 320
{ JA, SK, SK, QN, PF, JA, JA, JA, SK, JA, JA, JA, TN, JA, TN }, 	 //	 687	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, TN, JA, JA, TN, JA, AC }, 	 //	 688	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 689	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, JA, JA, TN, JA, AC }, 	 //	 690	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 691	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, JA, JA, TN, JA, CR }, 	 //	 692	 320
{ JA, SK, SK, QN, CR, JA, JA, JA, SK, QN, JA, JA, TN, JA, KN }, 	 //	 693	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, KN, JA, JA, TN, JA, AC }, 	 //	 694	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, AC, JA, JA, TN, JA, LO }, 	 //	 695	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, KN, KN, JA, JA, TN, SK, SK }, 	 //	 696	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, KN, AC, JA, JA, TN, SK, SK }, 	 //	 697	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, LO, JA, JA, TN, QN, AC }, 	 //	 698	 320
{ JA, SK, SK, KN, LO, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 699	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 700	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, CR }, 	 //	 701	 320
{ JA, SK, SK, KN, CR, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 702	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 703	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, QN, JA, JA, TN, QN, QN }, 	 //	 704	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, QN, JA, JA, TN, QN, SH }, 	 //	 705	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, SH, JA, JA, TN, QN, JA }, 	 //	 706	 320
{ JA, SK, SK, KN, SH, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA }, 	 //	 707	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, JA }, 	 //	 708	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, JA, JA, JA, TN, QN, WN }, 	 //	 709	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, WN, JA, JA, TN, QN, TN }, 	 //	 710	 320
{ JA, SK, SK, KN, WN, JA, JA, JA, SK, TN, JA, JA, TN, QN, TN }, 	 //	 711	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, TN, JA, JA, TN, QN, TN }, 	 //	 712	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, TN, JA, JA, TN, QN, ST }, 	 //	 713	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, ST, JA, JA, TN, QN, AC }, 	 //	 714	 320
{ JA, SK, SK, KN, ST, JA, JA, JA, SK, AC, JA, JA, TN, QN, KN }, 	 //	 715	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, KN, JA, JA, TN, QN, QN }, 	 //	 716	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, QN, JA, JA, TN, QN, PF }, 	 //	 717	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, PF, JA, JA, TN, QN, JA }, 	 //	 718	 320
{ JA, SK, SK, KN, PF, JA, JA, JA, SK, JA, JA, JA, TN, QN, TN }, 	 //	 719	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, TN, JA, JA, TN, QN, AC }, 	 //	 720	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 721	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, JA, JA, TN, QN, AC }, 	 //	 722	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 723	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, JA, JA, TN, QN, CR }, 	 //	 724	 320
{ JA, SK, SK, KN, CR, JA, JA, JA, SK, QN, JA, JA, TN, QN, KN }, 	 //	 725	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, KN, JA, JA, TN, QN, AC }, 	 //	 726	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, AC, JA, JA, TN, QN, LO }, 	 //	 727	 320
{ JA, JA, SK, QN, KN, JA, JA, JA, SK, SK, JA, JA, TN, JA, QN }, 	 //	 728	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, QN, JA, JA, TN, JA, QN }, 	 //	 729	 320
{ JA, JA, SK, QN, AC, JA, JA, JA, SK, SK, JA, JA, TN, JA, KN }, 	 //	 730	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, KN, JA, JA, TN, JA, KN }, 	 //	 731	 320
{ JA, JA, SK, KN, KN, JA, JA, JA, SK, SK, JA, JA, TN, QN, QN }, 	 //	 732	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, QN, JA, JA, TN, QN, QN }, 	 //	 733	 320
{ JA, JA, SK, KN, AC, JA, JA, JA, SK, SK, JA, JA, TN, QN, KN }, 	 //	 734	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, KN, JA, JA, TN, QN, KN }, 	 //	 735	 320
{ JA, JA, QN, QN, KN, JA, JA, SK, SK, KN, JA, SH, JA, JA, SK }, 	 //	 736	 320
{ JA, JA, QN, QN, SK, JA, JA, SK, SK, QN, JA, SH, JA, JA, QN }, 	 //	 737	 320
{ JA, JA, QN, QN, AC, JA, JA, SK, SK, AC, JA, SH, JA, JA, SK }, 	 //	 738	 320
{ JA, JA, QN, QN, SK, JA, JA, SK, SK, KN, JA, SH, JA, JA, KN }, 	 //	 739	 320
{ JA, JA, QN, KN, KN, JA, JA, SK, SK, KN, JA, SH, JA, QN, SK }, 	 //	 740	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, QN, JA, SH, JA, QN, QN }, 	 //	 741	 320
{ JA, JA, QN, KN, AC, JA, JA, SK, SK, AC, JA, SH, JA, QN, SK }, 	 //	 742	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, KN, JA, SH, JA, QN, KN }, 	 //	 743	 320
{ JA, JA, SK, QN, KN, JA, JA, JA, SK, SK, JA, SH, TN, JA, QN }, 	 //	 744	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, QN, JA, SH, TN, JA, QN }, 	 //	 745	 320
{ JA, JA, SK, QN, AC, JA, JA, JA, SK, SK, JA, SH, TN, JA, KN }, 	 //	 746	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, KN, JA, SH, TN, JA, KN }, 	 //	 747	 320
{ JA, JA, SK, KN, KN, JA, JA, JA, SK, SK, JA, SH, TN, QN, QN }, 	 //	 748	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, QN, JA, SH, TN, QN, QN }, 	 //	 749	 320
{ JA, JA, SK, KN, AC, JA, JA, JA, SK, SK, JA, SH, TN, QN, KN }, 	 //	 750	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, KN, JA, SH, TN, QN, KN }, 	 //	 751	 320
{ JA, QN, QN, KN, KN, JA, ST, SK, SK, KN, JA, JA, JA, QN, SK }, 	 //	 752	 320
{ JA, QN, QN, KN, SK, JA, ST, SK, SK, QN, JA, JA, JA, QN, QN }, 	 //	 753	 320
{ JA, QN, QN, KN, AC, JA, ST, SK, SK, AC, JA, JA, JA, QN, SK }, 	 //	 754	 320
{ JA, QN, QN, KN, SK, JA, ST, SK, SK, KN, JA, JA, JA, QN, KN }, 	 //	 755	 320
{ JA, ST, QN, QN, KN, JA, JA, SK, SK, KN, JA, TN, JA, JA, SK }, 	 //	 756	 320
{ JA, ST, QN, QN, SK, JA, JA, SK, SK, QN, JA, TN, JA, JA, QN }, 	 //	 757	 320
{ JA, ST, QN, QN, AC, JA, JA, SK, SK, AC, JA, TN, JA, JA, SK }, 	 //	 758	 320
{ JA, ST, QN, QN, SK, JA, JA, SK, SK, KN, JA, TN, JA, JA, KN }, 	 //	 759	 320
{ JA, ST, QN, KN, KN, JA, JA, SK, SK, KN, JA, TN, JA, QN, SK }, 	 //	 760	 320
{ JA, ST, QN, KN, SK, JA, JA, SK, SK, QN, JA, TN, JA, QN, QN }, 	 //	 761	 320
{ JA, ST, QN, KN, AC, JA, JA, SK, SK, AC, JA, TN, JA, QN, SK }, 	 //	 762	 320
{ JA, ST, QN, KN, SK, JA, JA, SK, SK, KN, JA, TN, JA, QN, KN }, 	 //	 763	 320
{ JA, ST, SK, QN, KN, JA, JA, JA, SK, SK, JA, TN, TN, JA, QN }, 	 //	 764	 320
{ JA, ST, SK, QN, SK, JA, JA, JA, SK, QN, JA, TN, TN, JA, QN }, 	 //	 765	 320
{ JA, ST, SK, QN, AC, JA, JA, JA, SK, SK, JA, TN, TN, JA, KN }, 	 //	 766	 320
{ JA, ST, SK, QN, SK, JA, JA, JA, SK, KN, JA, TN, TN, JA, KN }, 	 //	 767	 320
{ JA, ST, SK, KN, KN, JA, JA, JA, SK, SK, JA, TN, TN, QN, QN }, 	 //	 768	 320
{ JA, ST, SK, KN, SK, JA, JA, JA, SK, QN, JA, TN, TN, QN, QN }, 	 //	 769	 320
{ JA, ST, SK, KN, AC, JA, JA, JA, SK, SK, JA, TN, TN, QN, KN }, 	 //	 770	 320
{ JA, ST, SK, KN, SK, JA, JA, JA, SK, KN, JA, TN, TN, QN, KN }, 	 //	 771	 320
{ JA, KN, SK, SK, SH, JA, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 772	 320
{ JA, KN, SK, SK, JA, JA, SK, JA, JA, JA, JA, QN, TN, JA, JA }, 	 //	 773	 320
{ JA, KN, SK, SK, JA, JA, SK, JA, JA, JA, JA, QN, TN, JA, WN }, 	 //	 774	 320
{ JA, KN, SK, SK, PF, JA, SK, JA, JA, JA, JA, QN, TN, JA, TN }, 	 //	 775	 320
{ JA, QN, QN, SK, SK, JA, SK, SK, JA, QN, WN, JA, JA, JA, QN }, 	 //	 776	 320
{ JA, QN, QN, SK, SK, JA, SK, SK, JA, KN, WN, JA, JA, JA, KN }, 	 //	 777	 320
{ JA, QN, SK, SK, SH, JA, SK, JA, JA, JA, WN, JA, TN, JA, JA }, 	 //	 778	 320
{ JA, QN, SK, SK, JA, JA, SK, JA, JA, JA, WN, JA, TN, JA, JA }, 	 //	 779	 320
{ JA, QN, SK, SK, JA, JA, SK, JA, JA, JA, WN, JA, TN, JA, WN }, 	 //	 780	 320
{ JA, QN, SK, SK, PF, JA, SK, JA, JA, JA, WN, JA, TN, JA, TN }, 	 //	 781	 320
{ JA, SK, QN, KN, KN, JA, JA, SK, SK, KN, WN, JA, JA, QN, SK }, 	 //	 782	 320
{ JA, SK, QN, KN, SK, JA, JA, SK, SK, QN, WN, JA, JA, QN, QN }, 	 //	 783	 320
{ JA, SK, QN, KN, AC, JA, JA, SK, SK, AC, WN, JA, JA, QN, SK }, 	 //	 784	 320
{ JA, SK, QN, KN, SK, JA, JA, SK, SK, KN, WN, JA, JA, QN, KN }, 	 //	 785	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, QN, KN, WN, JA, TN, SK, SK }, 	 //	 786	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, QN, AC, WN, JA, TN, SK, SK }, 	 //	 787	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, LO, WN, JA, TN, JA, AC }, 	 //	 788	 320
{ JA, SK, SK, QN, LO, JA, JA, JA, SK, AC, WN, JA, TN, JA, AC }, 	 //	 789	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, WN, JA, TN, JA, AC }, 	 //	 790	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, WN, JA, TN, JA, CR }, 	 //	 791	 320
{ JA, SK, SK, QN, CR, JA, JA, JA, SK, KN, WN, JA, TN, JA, KN }, 	 //	 792	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, WN, JA, TN, JA, KN }, 	 //	 793	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, QN, WN, JA, TN, JA, QN }, 	 //	 794	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, QN, WN, JA, TN, JA, SH }, 	 //	 795	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, SH, WN, JA, TN, JA, JA }, 	 //	 796	 320
{ JA, SK, SK, QN, SH, JA, JA, JA, SK, JA, WN, JA, TN, JA, JA }, 	 //	 797	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, JA, WN, JA, TN, JA, JA }, 	 //	 798	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, JA, WN, JA, TN, JA, WN }, 	 //	 799	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, WN, WN, JA, TN, JA, TN }, 	 //	 800	 320
{ JA, SK, SK, QN, WN, JA, JA, JA, SK, TN, WN, JA, TN, JA, TN }, 	 //	 801	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, TN, WN, JA, TN, JA, TN }, 	 //	 802	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, TN, WN, JA, TN, JA, ST }, 	 //	 803	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, ST, WN, JA, TN, JA, AC }, 	 //	 804	 320
{ JA, SK, SK, QN, ST, JA, JA, JA, SK, AC, WN, JA, TN, JA, KN }, 	 //	 805	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, KN, WN, JA, TN, JA, QN }, 	 //	 806	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, QN, WN, JA, TN, JA, PF }, 	 //	 807	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, PF, WN, JA, TN, JA, JA }, 	 //	 808	 320
{ JA, SK, SK, QN, PF, JA, JA, JA, SK, JA, WN, JA, TN, JA, TN }, 	 //	 809	 320
{ JA, SK, SK, QN, JA, JA, JA, JA, SK, TN, WN, JA, TN, JA, AC }, 	 //	 810	 320
{ JA, SK, SK, QN, TN, JA, JA, JA, SK, AC, WN, JA, TN, JA, AC }, 	 //	 811	 320
{ JA, SK, SK, QN, AC, JA, JA, JA, SK, AC, WN, JA, TN, JA, AC }, 	 //	 812	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, WN, JA, TN, JA, KN }, 	 //	 813	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, KN, WN, JA, TN, JA, CR }, 	 //	 814	 320
{ JA, SK, SK, QN, CR, JA, JA, JA, SK, QN, WN, JA, TN, JA, KN }, 	 //	 815	 320
{ JA, SK, SK, QN, QN, JA, JA, JA, SK, KN, WN, JA, TN, JA, AC }, 	 //	 816	 320
{ JA, SK, SK, QN, KN, JA, JA, JA, SK, AC, WN, JA, TN, JA, LO }, 	 //	 817	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, KN, KN, WN, JA, TN, SK, SK }, 	 //	 818	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, KN, AC, WN, JA, TN, SK, SK }, 	 //	 819	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, LO, WN, JA, TN, QN, AC }, 	 //	 820	 320
{ JA, SK, SK, KN, LO, JA, JA, JA, SK, AC, WN, JA, TN, QN, AC }, 	 //	 821	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, WN, JA, TN, QN, AC }, 	 //	 822	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, WN, JA, TN, QN, CR }, 	 //	 823	 320
{ JA, SK, SK, KN, CR, JA, JA, JA, SK, KN, WN, JA, TN, QN, KN }, 	 //	 824	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, WN, JA, TN, QN, KN }, 	 //	 825	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, QN, WN, JA, TN, QN, QN }, 	 //	 826	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, QN, WN, JA, TN, QN, SH }, 	 //	 827	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, SH, WN, JA, TN, QN, JA }, 	 //	 828	 320
{ JA, SK, SK, KN, SH, JA, JA, JA, SK, JA, WN, JA, TN, QN, JA }, 	 //	 829	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, JA, WN, JA, TN, QN, JA }, 	 //	 830	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, JA, WN, JA, TN, QN, WN }, 	 //	 831	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, WN, WN, JA, TN, QN, TN }, 	 //	 832	 320
{ JA, SK, SK, KN, WN, JA, JA, JA, SK, TN, WN, JA, TN, QN, TN }, 	 //	 833	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, TN, WN, JA, TN, QN, TN }, 	 //	 834	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, TN, WN, JA, TN, QN, ST }, 	 //	 835	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, ST, WN, JA, TN, QN, AC }, 	 //	 836	 320
{ JA, SK, SK, KN, ST, JA, JA, JA, SK, AC, WN, JA, TN, QN, KN }, 	 //	 837	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, KN, WN, JA, TN, QN, QN }, 	 //	 838	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, QN, WN, JA, TN, QN, PF }, 	 //	 839	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, PF, WN, JA, TN, QN, JA }, 	 //	 840	 320
{ JA, SK, SK, KN, PF, JA, JA, JA, SK, JA, WN, JA, TN, QN, TN }, 	 //	 841	 320
{ JA, SK, SK, KN, JA, JA, JA, JA, SK, TN, WN, JA, TN, QN, AC }, 	 //	 842	 320
{ JA, SK, SK, KN, TN, JA, JA, JA, SK, AC, WN, JA, TN, QN, AC }, 	 //	 843	 320
{ JA, SK, SK, KN, AC, JA, JA, JA, SK, AC, WN, JA, TN, QN, AC }, 	 //	 844	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, WN, JA, TN, QN, KN }, 	 //	 845	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, KN, WN, JA, TN, QN, CR }, 	 //	 846	 320
{ JA, SK, SK, KN, CR, JA, JA, JA, SK, QN, WN, JA, TN, QN, KN }, 	 //	 847	 320
{ JA, SK, SK, KN, QN, JA, JA, JA, SK, KN, WN, JA, TN, QN, AC }, 	 //	 848	 320
{ JA, SK, SK, KN, KN, JA, JA, JA, SK, AC, WN, JA, TN, QN, LO }, 	 //	 849	 320
{ JA, JA, QN, KN, KN, JA, JA, SK, SK, KN, WN, JA, JA, QN, SK }, 	 //	 850	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, QN, WN, JA, JA, QN, QN }, 	 //	 851	 320
{ JA, JA, QN, KN, AC, JA, JA, SK, SK, AC, WN, JA, JA, QN, SK }, 	 //	 852	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, KN, WN, JA, JA, QN, KN }, 	 //	 853	 320
{ JA, JA, SK, QN, KN, JA, JA, JA, SK, SK, WN, JA, TN, JA, QN }, 	 //	 854	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, QN, WN, JA, TN, JA, QN }, 	 //	 855	 320
{ JA, JA, SK, QN, AC, JA, JA, JA, SK, SK, WN, JA, TN, JA, KN }, 	 //	 856	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, KN, WN, JA, TN, JA, KN }, 	 //	 857	 320
{ JA, JA, SK, KN, KN, JA, JA, JA, SK, SK, WN, JA, TN, QN, QN }, 	 //	 858	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, QN, WN, JA, TN, QN, QN }, 	 //	 859	 320
{ JA, JA, SK, KN, AC, JA, JA, JA, SK, SK, WN, JA, TN, QN, KN }, 	 //	 860	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, KN, WN, JA, TN, QN, KN }, 	 //	 861	 320
{ JA, JA, QN, QN, KN, JA, JA, SK, SK, KN, WN, SH, JA, JA, SK }, 	 //	 862	 320
{ JA, JA, QN, QN, SK, JA, JA, SK, SK, QN, WN, SH, JA, JA, QN }, 	 //	 863	 320
{ JA, JA, QN, QN, AC, JA, JA, SK, SK, AC, WN, SH, JA, JA, SK }, 	 //	 864	 320
{ JA, JA, QN, QN, SK, JA, JA, SK, SK, KN, WN, SH, JA, JA, KN }, 	 //	 865	 320
{ JA, JA, QN, KN, KN, JA, JA, SK, SK, KN, WN, SH, JA, QN, SK }, 	 //	 866	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, QN, WN, SH, JA, QN, QN }, 	 //	 867	 320
{ JA, JA, QN, KN, AC, JA, JA, SK, SK, AC, WN, SH, JA, QN, SK }, 	 //	 868	 320
{ JA, JA, QN, KN, SK, JA, JA, SK, SK, KN, WN, SH, JA, QN, KN }, 	 //	 869	 320
{ JA, JA, SK, QN, KN, JA, JA, JA, SK, SK, WN, SH, TN, JA, QN }, 	 //	 870	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, QN, WN, SH, TN, JA, QN }, 	 //	 871	 320
{ JA, JA, SK, QN, AC, JA, JA, JA, SK, SK, WN, SH, TN, JA, KN }, 	 //	 872	 320
{ JA, JA, SK, QN, SK, JA, JA, JA, SK, KN, WN, SH, TN, JA, KN }, 	 //	 873	 320
{ JA, JA, SK, KN, KN, JA, JA, JA, SK, SK, WN, SH, TN, QN, QN }, 	 //	 874	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, QN, WN, SH, TN, QN, QN }, 	 //	 875	 320
{ JA, JA, SK, KN, AC, JA, JA, JA, SK, SK, WN, SH, TN, QN, KN }, 	 //	 876	 320
{ JA, JA, SK, KN, SK, JA, JA, JA, SK, KN, WN, SH, TN, QN, KN }, 	 //	 877	 320
{ JA, ST, QN, QN, KN, JA, JA, SK, SK, KN, WN, TN, JA, JA, SK }, 	 //	 878	 320
{ JA, ST, QN, QN, SK, JA, JA, SK, SK, QN, WN, TN, JA, JA, QN }, 	 //	 879	 320
{ JA, ST, QN, QN, AC, JA, JA, SK, SK, AC, WN, TN, JA, JA, SK }, 	 //	 880	 320
{ JA, ST, QN, QN, SK, JA, JA, SK, SK, KN, WN, TN, JA, JA, KN }, 	 //	 881	 320
{ JA, ST, QN, KN, KN, JA, JA, SK, SK, KN, WN, TN, JA, QN, SK }, 	 //	 882	 320
{ JA, ST, QN, KN, SK, JA, JA, SK, SK, QN, WN, TN, JA, QN, QN }, 	 //	 883	 320
{ JA, ST, QN, KN, AC, JA, JA, SK, SK, AC, WN, TN, JA, QN, SK }, 	 //	 884	 320
{ JA, ST, QN, KN, SK, JA, JA, SK, SK, KN, WN, TN, JA, QN, KN }, 	 //	 885	 320
{ JA, ST, SK, QN, KN, JA, JA, JA, SK, SK, WN, TN, TN, JA, QN }, 	 //	 886	 320
{ JA, ST, SK, QN, SK, JA, JA, JA, SK, QN, WN, TN, TN, JA, QN }, 	 //	 887	 320
{ JA, ST, SK, QN, AC, JA, JA, JA, SK, SK, WN, TN, TN, JA, KN }, 	 //	 888	 320
{ JA, ST, SK, QN, SK, JA, JA, JA, SK, KN, WN, TN, TN, JA, KN }, 	 //	 889	 320
{ JA, ST, SK, KN, KN, JA, JA, JA, SK, SK, WN, TN, TN, QN, QN }, 	 //	 890	 320
{ JA, ST, SK, KN, SK, JA, JA, JA, SK, QN, WN, TN, TN, QN, QN }, 	 //	 891	 320
{ JA, ST, SK, KN, AC, JA, JA, JA, SK, SK, WN, TN, TN, QN, KN }, 	 //	 892	 320
{ JA, ST, SK, KN, SK, JA, JA, JA, SK, KN, WN, TN, TN, QN, KN }, 	 //	 893	 320
{ JA, KN, SK, SK, SH, JA, SK, JA, JA, JA, WN, QN, TN, JA, JA }, 	 //	 894	 320
{ JA, KN, SK, SK, JA, JA, SK, JA, JA, JA, WN, QN, TN, JA, JA }, 	 //	 895	 320
{ JA, KN, SK, SK, JA, JA, SK, JA, JA, JA, WN, QN, TN, JA, WN }, 	 //	 896	 320
{ JA, KN, SK, SK, PF, JA, SK, JA, JA, JA, WN, QN, TN, JA, TN }, 	 //	 897	 320
{ JA, QN, QN, SK, SK, WN, SK, SK, JA, QN, TN, JA, JA, JA, QN }, 	 //	 898	 320
{ JA, QN, QN, SK, SK, WN, SK, SK, JA, KN, TN, JA, JA, JA, KN }, 	 //	 899	 320
{ JA, QN, SK, SK, SH, WN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 900	 320
{ JA, QN, SK, SK, JA, WN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 901	 320
{ JA, QN, SK, SK, JA, WN, SK, JA, JA, JA, TN, JA, TN, JA, WN }, 	 //	 902	 320
{ JA, QN, SK, SK, PF, WN, SK, JA, JA, JA, TN, JA, TN, JA, TN }, 	 //	 903	 320
{ JA, SK, QN, KN, KN, WN, JA, SK, SK, KN, TN, JA, JA, QN, SK }, 	 //	 904	 320
{ JA, SK, QN, KN, SK, WN, JA, SK, SK, QN, TN, JA, JA, QN, QN }, 	 //	 905	 320
{ JA, SK, QN, KN, AC, WN, JA, SK, SK, AC, TN, JA, JA, QN, SK }, 	 //	 906	 320
{ JA, SK, QN, KN, SK, WN, JA, SK, SK, KN, TN, JA, JA, QN, KN }, 	 //	 907	 320
{ JA, JA, QN, KN, KN, WN, JA, SK, SK, KN, TN, JA, JA, QN, SK }, 	 //	 908	 320
{ JA, JA, QN, KN, SK, WN, JA, SK, SK, QN, TN, JA, JA, QN, QN }, 	 //	 909	 320
{ JA, JA, QN, KN, AC, WN, JA, SK, SK, AC, TN, JA, JA, QN, SK }, 	 //	 910	 320
{ JA, JA, QN, KN, SK, WN, JA, SK, SK, KN, TN, JA, JA, QN, KN }, 	 //	 911	 320
{ JA, JA, QN, QN, KN, WN, JA, SK, SK, KN, TN, SH, JA, JA, SK }, 	 //	 912	 320
{ JA, JA, QN, QN, SK, WN, JA, SK, SK, QN, TN, SH, JA, JA, QN }, 	 //	 913	 320
{ JA, JA, QN, QN, AC, WN, JA, SK, SK, AC, TN, SH, JA, JA, SK }, 	 //	 914	 320
{ JA, JA, QN, QN, SK, WN, JA, SK, SK, KN, TN, SH, JA, JA, KN }, 	 //	 915	 320
{ JA, JA, QN, KN, KN, WN, JA, SK, SK, KN, TN, SH, JA, QN, SK }, 	 //	 916	 320
{ JA, JA, QN, KN, SK, WN, JA, SK, SK, QN, TN, SH, JA, QN, QN }, 	 //	 917	 320
{ JA, JA, QN, KN, AC, WN, JA, SK, SK, AC, TN, SH, JA, QN, SK }, 	 //	 918	 320
{ JA, JA, QN, KN, SK, WN, JA, SK, SK, KN, TN, SH, JA, QN, KN }, 	 //	 919	 320
{ JA, ST, QN, QN, KN, WN, JA, SK, SK, KN, TN, TN, JA, JA, SK }, 	 //	 920	 320
{ JA, ST, QN, QN, SK, WN, JA, SK, SK, QN, TN, TN, JA, JA, QN }, 	 //	 921	 320
{ JA, ST, QN, QN, AC, WN, JA, SK, SK, AC, TN, TN, JA, JA, SK }, 	 //	 922	 320
{ JA, ST, QN, QN, SK, WN, JA, SK, SK, KN, TN, TN, JA, JA, KN }, 	 //	 923	 320
{ JA, ST, QN, KN, KN, WN, JA, SK, SK, KN, TN, TN, JA, QN, SK }, 	 //	 924	 320
{ JA, ST, QN, KN, SK, WN, JA, SK, SK, QN, TN, TN, JA, QN, QN }, 	 //	 925	 320
{ JA, ST, QN, KN, AC, WN, JA, SK, SK, AC, TN, TN, JA, QN, SK }, 	 //	 926	 320
{ JA, ST, QN, KN, SK, WN, JA, SK, SK, KN, TN, TN, JA, QN, KN }, 	 //	 927	 320
{ JA, KN, SK, SK, SH, WN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 928	 320
{ JA, KN, SK, SK, JA, WN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 929	 320
{ JA, KN, SK, SK, JA, WN, SK, JA, JA, JA, TN, QN, TN, JA, WN }, 	 //	 930	 320
{ JA, KN, SK, SK, PF, WN, SK, JA, JA, JA, TN, QN, TN, JA, TN }, 	 //	 931	 320
{ WN, QN, QN, SK, SK, TN, SK, SK, JA, QN, TN, JA, JA, JA, QN }, 	 //	 932	 320
{ WN, QN, QN, SK, SK, TN, SK, SK, JA, KN, TN, JA, JA, JA, KN }, 	 //	 933	 320
{ WN, QN, SK, SK, SH, TN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 934	 320
{ WN, QN, SK, SK, JA, TN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 935	 320
{ WN, QN, SK, SK, JA, TN, SK, JA, JA, JA, TN, JA, TN, JA, WN }, 	 //	 936	 320
{ WN, QN, SK, SK, PF, TN, SK, JA, JA, JA, TN, JA, TN, JA, TN }, 	 //	 937	 320
{ WN, SK, QN, QN, KN, TN, JA, SK, SK, KN, TN, JA, JA, JA, SK }, 	 //	 938	 320
{ WN, SK, QN, QN, SK, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 939	 320
{ WN, SK, QN, QN, AC, TN, JA, SK, SK, AC, TN, JA, JA, JA, SK }, 	 //	 940	 320
{ WN, SK, QN, QN, SK, TN, JA, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 941	 320
{ WN, JA, QN, QN, KN, TN, JA, SK, SK, KN, TN, JA, JA, JA, SK }, 	 //	 942	 320
{ WN, JA, QN, QN, SK, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 943	 320
{ WN, JA, QN, QN, AC, TN, JA, SK, SK, AC, TN, JA, JA, JA, SK }, 	 //	 944	 320
{ WN, JA, QN, QN, SK, TN, JA, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 945	 320
{ WN, KN, SK, SK, SH, TN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 946	 320
{ WN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 947	 320
{ WN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN, QN, TN, JA, WN }, 	 //	 948	 320
{ WN, KN, SK, SK, PF, TN, SK, JA, JA, JA, TN, QN, TN, JA, TN }, 	 //	 949	 320
{ TN, QN, QN, SK, SK, TN, SK, SK, JA, QN, TN, JA, JA, JA, QN }, 	 //	 950	 320
{ TN, QN, QN, SK, SK, TN, SK, SK, JA, KN, TN, JA, JA, JA, KN }, 	 //	 951	 320
{ TN, QN, SK, SK, SH, TN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 952	 320
{ TN, QN, SK, SK, JA, TN, SK, JA, JA, JA, TN, JA, TN, JA, JA }, 	 //	 953	 320
{ TN, QN, SK, SK, JA, TN, SK, JA, JA, JA, TN, JA, TN, JA, WN }, 	 //	 954	 320
{ TN, QN, SK, SK, PF, TN, SK, JA, JA, JA, TN, JA, TN, JA, TN }, 	 //	 955	 320
{ TN, SK, QN, QN, KN, TN, JA, SK, SK, KN, TN, JA, JA, JA, SK }, 	 //	 956	 320
{ TN, SK, QN, QN, SK, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 957	 320
{ TN, SK, QN, QN, AC, TN, JA, SK, SK, AC, TN, JA, JA, JA, SK }, 	 //	 958	 320
{ TN, SK, QN, QN, SK, TN, JA, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 959	 320
{ TN, JA, QN, QN, KN, TN, JA, SK, SK, KN, TN, JA, JA, JA, SK }, 	 //	 960	 320
{ TN, JA, QN, QN, SK, TN, JA, SK, SK, QN, TN, JA, JA, JA, QN }, 	 //	 961	 320
{ TN, JA, QN, QN, AC, TN, JA, SK, SK, AC, TN, JA, JA, JA, SK }, 	 //	 962	 320
{ TN, JA, QN, QN, SK, TN, JA, SK, SK, KN, TN, JA, JA, JA, KN }, 	 //	 963	 320
{ TN, SH, SK, QN, KN, TN, TN, JA, SK, SK, TN, TN, TN, JA, QN }, 	 //	 964	 320
{ TN, SH, SK, QN, SK, TN, TN, JA, SK, QN, TN, TN, TN, JA, QN }, 	 //	 965	 320
{ TN, SH, SK, QN, AC, TN, TN, JA, SK, SK, TN, TN, TN, JA, KN }, 	 //	 966	 320
{ TN, SH, SK, QN, SK, TN, TN, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 967	 320
{ TN, SH, SK, KN, KN, TN, TN, JA, SK, SK, TN, TN, TN, QN, QN }, 	 //	 968	 320
{ TN, SH, SK, KN, SK, TN, TN, JA, SK, QN, TN, TN, TN, QN, QN }, 	 //	 969	 320
{ TN, SH, SK, KN, AC, TN, TN, JA, SK, SK, TN, TN, TN, QN, KN }, 	 //	 970	 320
{ TN, SH, SK, KN, SK, TN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 971	 320
{ TN, TN, SK, QN, KN, TN, TN, JA, SK, SK, TN, TN, TN, JA, QN }, 	 //	 972	 320
{ TN, TN, SK, QN, SK, TN, TN, JA, SK, QN, TN, TN, TN, JA, QN }, 	 //	 973	 320
{ TN, TN, SK, QN, AC, TN, TN, JA, SK, SK, TN, TN, TN, JA, KN }, 	 //	 974	 320
{ TN, TN, SK, QN, SK, TN, TN, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 975	 320
{ TN, TN, SK, KN, KN, TN, TN, JA, SK, SK, TN, TN, TN, QN, QN }, 	 //	 976	 320
{ TN, TN, SK, KN, SK, TN, TN, JA, SK, QN, TN, TN, TN, QN, QN }, 	 //	 977	 320
{ TN, TN, SK, KN, AC, TN, TN, JA, SK, SK, TN, TN, TN, QN, KN }, 	 //	 978	 320
{ TN, TN, SK, KN, SK, TN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 979	 320
{ TN, KN, SK, SK, SH, TN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 980	 320
{ TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN, QN, TN, JA, JA }, 	 //	 981	 320
{ TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, TN, QN, TN, JA, WN }, 	 //	 982	 320
{ TN, KN, SK, SK, PF, TN, SK, JA, JA, JA, TN, QN, TN, JA, TN }, 	 //	 983	 320
{ TN, QN, QN, SK, SK, TN, SK, SK, JA, QN, ST, JA, JA, JA, QN }, 	 //	 984	 320
{ TN, QN, QN, SK, SK, TN, SK, SK, JA, KN, ST, JA, JA, JA, KN }, 	 //	 985	 320
{ TN, QN, SK, SK, SH, TN, SK, JA, JA, JA, ST, JA, TN, JA, JA }, 	 //	 986	 320
{ TN, QN, SK, SK, JA, TN, SK, JA, JA, JA, ST, JA, TN, JA, JA }, 	 //	 987	 320
{ TN, QN, SK, SK, JA, TN, SK, JA, JA, JA, ST, JA, TN, JA, WN }, 	 //	 988	 320
{ TN, QN, SK, SK, PF, TN, SK, JA, JA, JA, ST, JA, TN, JA, TN }, 	 //	 989	 320
{ TN, SK, QN, QN, KN, TN, JA, SK, SK, KN, ST, JA, JA, JA, SK }, 	 //	 990	 320
{ TN, SK, QN, QN, SK, TN, JA, SK, SK, QN, ST, JA, JA, JA, QN }, 	 //	 991	 320
{ TN, SK, QN, QN, AC, TN, JA, SK, SK, AC, ST, JA, JA, JA, SK }, 	 //	 992	 320
{ TN, SK, QN, QN, SK, TN, JA, SK, SK, KN, ST, JA, JA, JA, KN }, 	 //	 993	 320
{ TN, JA, QN, QN, KN, TN, JA, SK, SK, KN, ST, JA, JA, JA, SK }, 	 //	 994	 320
{ TN, JA, QN, QN, SK, TN, JA, SK, SK, QN, ST, JA, JA, JA, QN }, 	 //	 995	 320
{ TN, JA, QN, QN, AC, TN, JA, SK, SK, AC, ST, JA, JA, JA, SK }, 	 //	 996	 320
{ TN, JA, QN, QN, SK, TN, JA, SK, SK, KN, ST, JA, JA, JA, KN }, 	 //	 997	 320
{ TN, KN, SK, SK, SH, TN, SK, JA, JA, JA, ST, QN, TN, JA, JA }, 	 //	 998	 320
{ TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, ST, QN, TN, JA, JA }, 	 //	 999	 320
{ TN, KN, SK, SK, JA, TN, SK, JA, JA, JA, ST, QN, TN, JA, WN }};	 //	 1000	 320
