#include "ReelDefine.h"

unsigned char L5_Outcome_1700[1000][15]={	 //	 0	 1700
{ AC, AC, JA, ST, JA, LO, SH, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 1	 1700
{ AC, AC, JA, JA, JA, LO, AC, ST, SH, TN, AC, LO, AC, TN, AC }, 	 //	 2	 1700
{ AC, AC, JA, JA, JA, LO, AC, TN, SH, TN, AC, LO, AC, TN, AC }, 	 //	 3	 1700
{ AC, AC, JA, JA, JA, LO, AC, TN, TN, JA, AC, LO, AC, AC, JA }, 	 //	 4	 1700
{ AC, JA, JA, JA, AC, LO, JA, ST, TN, LO, AC, SH, AC, AC, AC }, 	 //	 5	 1700
{ AC, TN, TN, TN, TN, LO, TN, AC, WN, AC, AC, TN, AC, AC, AC }, 	 //	 6	 1700
{ AC, TN, JA, JA, JA, LO, TN, ST, TN, TN, AC, WN, AC, AC, AC }, 	 //	 7	 1700
{ AC, TN, JA, ST, QN, LO, WN, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 8	 1700
{ AC, TN, JA, JA, SH, LO, WN, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 9	 1700
{ AC, WN, JA, JA, QN, LO, AC, ST, JA, SH, AC, KN, AC, SH, JA }, 	 //	 10	 1700
{ AC, WN, JA, SK, QN, LO, AC, TN, JA, SH, AC, KN, AC, JA, JA }, 	 //	 11	 1700
{ AC, WN, JA, ST, SH, LO, AC, TN, JA, JA, AC, KN, AC, TN, JA }, 	 //	 12	 1700
{ AC, JA, JA, SK, QN, LO, TN, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 13	 1700
{ AC, JA, JA, JA, KN, LO, TN, ST, JA, QN, AC, AC, AC, JA, PF }, 	 //	 14	 1700
{ AC, JA, JA, JA, PF, LO, TN, ST, JA, JA, AC, AC, AC, SH, TN }, 	 //	 15	 1700
{ AC, JA, JA, JA, SK, LO, TN, ST, JA, KN, AC, AC, AC, SH, KN }, 	 //	 16	 1700
{ AC, JA, JA, JA, TN, LO, TN, ST, SH, ST, AC, AC, AC, TN, AC }, 	 //	 17	 1700
{ AC, JA, JA, JA, LO, LO, TN, TN, JA, AC, AC, AC, AC, JA, AC }, 	 //	 18	 1700
{ AC, JA, JA, JA, TN, LO, TN, TN, JA, ST, AC, AC, AC, JA, AC }, 	 //	 19	 1700
{ AC, JA, JA, JA, KN, LO, TN, TN, JA, KN, AC, AC, AC, JA, KN }, 	 //	 20	 1700
{ AC, JA, JA, JA, AC, LO, TN, TN, SH, LO, AC, AC, AC, TN, AC }, 	 //	 21	 1700
{ AC, JA, JA, JA, QN, LO, TN, TN, SH, SH, AC, AC, AC, TN, JA }, 	 //	 22	 1700
{ AC, JA, JA, JA, QN, LO, TN, TN, SH, PF, AC, AC, AC, TN, JA }, 	 //	 23	 1700
{ AC, JA, JA, JA, KN, LO, TN, TN, SH, KN, AC, AC, AC, TN, KN }, 	 //	 24	 1700
{ AC, AC, JA, JA, JA, LO, AC, ST, SH, JA, AC, PF, AC, TN, WN }, 	 //	 25	 1700
{ AC, AC, JA, JA, QN, LO, AC, TN, JA, SH, AC, PF, AC, JA, JA }, 	 //	 26	 1700
{ AC, AC, JA, JA, JA, LO, AC, TN, JA, WN, AC, PF, AC, JA, TN }, 	 //	 27	 1700
{ AC, QN, JA, JA, JA, LO, KN, ST, SH, JA, AC, AC, AC, TN, JA }, 	 //	 28	 1700
{ AC, QN, JA, JA, JA, LO, KN, ST, SH, WN, AC, AC, AC, TN, TN }, 	 //	 29	 1700
{ AC, QN, JA, ST, QN, LO, KN, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 30	 1700
{ AC, KN, JA, JA, JA, LO, AC, ST, JA, WN, AC, SH, AC, SH, TN }, 	 //	 31	 1700
{ AC, KN, JA, JA, JA, LO, AC, ST, SH, JA, AC, SH, AC, TN, WN }, 	 //	 32	 1700
{ AC, KN, JA, ST, JA, LO, AC, ST, JA, JA, AC, SH, AC, TN, JA }, 	 //	 33	 1700
{ LO, AC, JA, SK, SH, AC, SH, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 34	 1700
{ LO, AC, JA, ST, QN, AC, SH, TN, JA, SH, AC, AC, AC, TN, JA }, 	 //	 35	 1700
{ LO, SH, JA, ST, QN, AC, AC, ST, JA, SH, AC, AC, AC, TN, JA }, 	 //	 36	 1700
{ LO, AC, JA, JA, JA, AC, AC, TN, SH, WN, AC, AC, AC, TN, TN }, 	 //	 37	 1700
{ LO, JA, JA, JA, TN, AC, SH, ST, TN, ST, AC, TN, AC, AC, AC }, 	 //	 38	 1700
{ LO, TN, JA, ST, JA, AC, WN, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 39	 1700
{ LO, AC, JA, JA, JA, AC, KN, ST, TN, TN, AC, QN, AC, AC, AC }, 	 //	 40	 1700
{ LO, JA, JA, SK, SH, AC, TN, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 41	 1700
{ LO, JA, JA, JA, LO, AC, TN, ST, JA, AC, AC, AC, AC, JA, AC }, 	 //	 42	 1700
{ LO, JA, JA, JA, KN, AC, TN, ST, JA, KN, AC, AC, AC, JA, SK }, 	 //	 43	 1700
{ LO, JA, JA, JA, LO, AC, TN, ST, JA, AC, AC, AC, AC, SH, AC }, 	 //	 44	 1700
{ LO, JA, JA, JA, PF, AC, TN, ST, JA, JA, AC, AC, AC, SH, TN }, 	 //	 45	 1700
{ LO, JA, JA, JA, KN, AC, TN, ST, SH, KN, AC, AC, AC, TN, KN }, 	 //	 46	 1700
{ LO, JA, JA, JA, AC, AC, TN, ST, SH, SK, AC, AC, AC, TN, KN }, 	 //	 47	 1700
{ LO, JA, JA, JA, AC, AC, TN, TN, JA, SK, AC, AC, AC, SH, KN }, 	 //	 48	 1700
{ LO, JA, JA, JA, KN, AC, TN, TN, JA, AC, AC, AC, AC, SH, LO }, 	 //	 49	 1700
{ LO, JA, JA, JA, WN, AC, TN, TN, SH, TN, AC, AC, AC, TN, TN }, 	 //	 50	 1700
{ LO, JA, JA, JA, KN, AC, TN, TN, SH, KN, AC, AC, AC, TN, CR }, 	 //	 51	 1700
{ LO, JA, TN, TN, JA, AC, TN, AC, TN, WN, AC, AC, AC, WN, TN }, 	 //	 52	 1700
{ LO, TN, JA, SK, SH, AC, AC, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 53	 1700
{ LO, TN, JA, JA, QN, AC, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 54	 1700
{ LO, TN, JA, JA, QN, AC, AC, ST, JA, PF, AC, AC, AC, SH, JA }, 	 //	 55	 1700
{ LO, AC, JA, SK, QN, AC, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 56	 1700
{ LO, AC, JA, JA, JA, AC, AC, ST, SH, JA, AC, AC, AC, TN, WN }, 	 //	 57	 1700
{ LO, AC, JA, JA, SH, AC, AC, TN, JA, JA, AC, AC, AC, SH, JA }, 	 //	 58	 1700
{ LO, AC, JA, JA, JA, AC, AC, TN, JA, JA, AC, AC, AC, SH, WN }, 	 //	 59	 1700
{ LO, AC, JA, JA, JA, AC, AC, TN, JA, WN, AC, AC, AC, SH, TN }, 	 //	 60	 1700
{ LO, PF, JA, JA, JA, AC, KN, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 61	 1700
{ LO, SK, JA, JA, JA, AC, QN, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 62	 1700
{ LO, QN, JA, JA, JA, AC, KN, ST, JA, JA, AC, AC, AC, SH, WN }, 	 //	 63	 1700
{ LO, QN, JA, JA, JA, AC, KN, ST, JA, TN, AC, AC, AC, SH, AC }, 	 //	 64	 1700
{ LO, QN, JA, SK, QN, AC, KN, TN, JA, PF, AC, AC, AC, JA, JA }, 	 //	 65	 1700
{ LO, QN, JA, JA, JA, AC, KN, TN, JA, WN, AC, AC, AC, SH, TN }, 	 //	 66	 1700
{ AC, AC, JA, JA, JA, AC, SH, ST, SH, TN, AC, AC, AC, TN, AC }, 	 //	 67	 1700
{ AC, AC, JA, JA, JA, AC, SH, TN, SH, WN, AC, AC, AC, TN, TN }, 	 //	 68	 1700
{ AC, AC, JA, JA, JA, AC, AC, ST, JA, JA, AC, LO, AC, SH, WN }, 	 //	 69	 1700
{ AC, AC, JA, ST, SH, AC, AC, ST, JA, JA, AC, LO, AC, TN, JA }, 	 //	 70	 1700
{ AC, AC, JA, ST, SH, AC, AC, TN, JA, JA, AC, LO, AC, TN, JA }, 	 //	 71	 1700
{ AC, LO, JA, JA, JA, AC, KN, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 72	 1700
{ AC, KN, JA, JA, JA, AC, KN, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 73	 1700
{ AC, JA, JA, JA, QN, AC, JA, TN, TN, KN, AC, JA, AC, AC, AC }, 	 //	 74	 1700
{ AC, JA, JA, JA, LO, AC, JA, ST, TN, AC, AC, SH, AC, AC, AC }, 	 //	 75	 1700
{ AC, JA, JA, JA, TN, AC, JA, ST, TN, ST, AC, SH, AC, AC, AC }, 	 //	 76	 1700
{ AC, JA, JA, JA, AC, AC, JA, TN, TN, LO, AC, SH, AC, AC, AC }, 	 //	 77	 1700
{ AC, TN, JA, JA, JA, AC, TN, ST, TN, TN, AC, WN, AC, AC, AC }, 	 //	 78	 1700
{ AC, TN, JA, JA, QN, AC, WN, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 79	 1700
{ AC, TN, JA, SK, JA, AC, WN, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 80	 1700
{ AC, TN, JA, JA, QN, AC, WN, TN, JA, SH, AC, AC, AC, JA, JA }, 	 //	 81	 1700
{ AC, TN, TN, TN, PF, AC, WN, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 82	 1700
{ AC, TN, TN, TN, TN, AC, WN, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 83	 1700
{ AC, WN, JA, JA, JA, AC, AC, ST, JA, WN, AC, KN, AC, SH, TN }, 	 //	 84	 1700
{ AC, WN, JA, SK, JA, AC, AC, TN, JA, JA, AC, KN, AC, JA, JA }, 	 //	 85	 1700
{ AC, WN, JA, SK, QN, AC, AC, TN, JA, PF, AC, KN, AC, JA, JA }, 	 //	 86	 1700
{ AC, WN, JA, JA, JA, AC, AC, TN, SH, TN, AC, KN, AC, TN, AC }, 	 //	 87	 1700
{ AC, JA, JA, JA, PF, AC, TN, ST, JA, JA, AC, AC, AC, JA, TN }, 	 //	 88	 1700
{ AC, JA, JA, JA, SK, AC, TN, ST, JA, KN, AC, AC, AC, JA, KN }, 	 //	 89	 1700
{ AC, JA, JA, JA, LO, AC, TN, ST, SH, AC, AC, AC, AC, TN, AC }, 	 //	 90	 1700
{ AC, JA, JA, JA, CR, AC, TN, ST, SH, QN, AC, AC, AC, TN, KN }, 	 //	 91	 1700
{ AC, JA, JA, JA, QN, AC, TN, TN, JA, QN, AC, AC, AC, JA, SH }, 	 //	 92	 1700
{ AC, JA, JA, JA, WN, AC, TN, TN, JA, TN, AC, AC, AC, JA, TN }, 	 //	 93	 1700
{ AC, JA, JA, JA, KN, AC, TN, TN, JA, AC, AC, AC, AC, JA, LO }, 	 //	 94	 1700
{ AC, JA, JA, JA, KN, AC, TN, TN, JA, KN, AC, AC, AC, SH, SK }, 	 //	 95	 1700
{ AC, JA, JA, JA, QN, AC, TN, TN, JA, QN, AC, AC, AC, SH, QN }, 	 //	 96	 1700
{ AC, JA, JA, JA, CR, AC, TN, TN, JA, QN, AC, AC, AC, SH, KN }, 	 //	 97	 1700
{ AC, JA, JA, JA, QN, AC, TN, TN, SH, SH, AC, AC, AC, TN, JA }, 	 //	 98	 1700
{ AC, AC, JA, JA, SH, AC, AC, ST, JA, JA, AC, PF, AC, JA, JA }, 	 //	 99	 1700
{ AC, AC, JA, ST, QN, AC, AC, TN, JA, SH, AC, PF, AC, TN, JA }, 	 //	 100	 1700
{ AC, QN, JA, JA, JA, AC, KN, ST, JA, TN, AC, AC, AC, SH, AC }, 	 //	 101	 1700
{ AC, QN, JA, JA, JA, AC, KN, TN, JA, JA, AC, AC, AC, SH, WN }, 	 //	 102	 1700
{ AC, QN, JA, ST, QN, AC, KN, TN, JA, PF, AC, AC, AC, TN, JA }, 	 //	 103	 1700
{ AC, KN, JA, JA, JA, AC, AC, ST, TN, WN, AC, SH, AC, AC, TN }, 	 //	 104	 1700
{ AC, KN, JA, JA, JA, AC, AC, TN, JA, WN, AC, SH, AC, SH, TN }, 	 //	 105	 1700
{ AC, AC, JA, JA, JA, AC, SH, ST, TN, WN, ST, AC, AC, AC, TN }, 	 //	 106	 1700
{ AC, SH, JA, ST, QN, AC, AC, ST, JA, SH, ST, AC, AC, TN, JA }, 	 //	 107	 1700
{ AC, SH, JA, ST, QN, AC, AC, TN, JA, SH, ST, AC, AC, TN, JA }, 	 //	 108	 1700
{ AC, AC, JA, JA, QN, AC, AC, TN, JA, SH, ST, AC, AC, JA, JA }, 	 //	 109	 1700
{ AC, AC, JA, JA, QN, AC, AC, TN, JA, PF, ST, AC, AC, SH, JA }, 	 //	 110	 1700
{ AC, LO, JA, JA, JA, AC, KN, ST, TN, TN, ST, KN, AC, AC, AC }, 	 //	 111	 1700
{ AC, ST, JA, JA, JA, AC, QN, ST, TN, TN, ST, QN, AC, AC, AC }, 	 //	 112	 1700
{ AC, JA, JA, JA, TN, AC, JA, ST, TN, ST, ST, JA, AC, AC, AC }, 	 //	 113	 1700
{ AC, JA, JA, JA, AC, AC, SH, ST, TN, AC, ST, TN, AC, AC, AC }, 	 //	 114	 1700
{ AC, WN, JA, SK, SH, AC, AC, ST, JA, JA, ST, KN, AC, JA, JA }, 	 //	 115	 1700
{ AC, WN, JA, JA, JA, AC, AC, ST, JA, JA, ST, KN, AC, SH, WN }, 	 //	 116	 1700
{ AC, WN, JA, JA, QN, AC, AC, TN, JA, PF, ST, KN, AC, JA, JA }, 	 //	 117	 1700
{ AC, WN, JA, JA, JA, AC, AC, TN, JA, WN, ST, KN, AC, SH, TN }, 	 //	 118	 1700
{ AC, JA, JA, JA, QN, AC, TN, ST, TN, PF, ST, AC, AC, AC, JA }, 	 //	 119	 1700
{ AC, JA, JA, JA, CR, AC, TN, ST, TN, QN, ST, AC, AC, AC, KN }, 	 //	 120	 1700
{ AC, TN, JA, JA, QN, AC, AC, ST, JA, PF, ST, AC, AC, JA, JA }, 	 //	 121	 1700
{ AC, TN, JA, JA, SH, AC, AC, TN, JA, JA, ST, AC, AC, JA, JA }, 	 //	 122	 1700
{ AC, AC, JA, JA, JA, AC, AC, ST, JA, TN, ST, AC, AC, JA, AC }, 	 //	 123	 1700
{ AC, AC, JA, SK, QN, AC, AC, TN, JA, SH, ST, PF, AC, JA, JA }, 	 //	 124	 1700
{ AC, AC, JA, SK, JA, AC, AC, TN, JA, JA, ST, PF, AC, JA, JA }, 	 //	 125	 1700
{ AC, AC, JA, JA, SH, AC, AC, TN, JA, JA, ST, PF, AC, SH, JA }, 	 //	 126	 1700
{ AC, AC, JA, JA, JA, AC, AC, TN, TN, WN, ST, PF, AC, AC, TN }, 	 //	 127	 1700
{ AC, KN, JA, JA, JA, AC, AC, ST, SH, JA, ST, SH, AC, TN, JA }, 	 //	 128	 1700
{ AC, KN, JA, JA, JA, AC, AC, ST, SH, WN, ST, SH, AC, TN, TN }, 	 //	 129	 1700
{ AC, KN, JA, JA, JA, AC, AC, TN, SH, TN, ST, SH, AC, TN, AC }, 	 //	 130	 1700
{ AC, SH, JA, JA, JA, ST, AC, ST, SH, JA, KN, AC, AC, TN, JA }, 	 //	 131	 1700
{ AC, SH, JA, JA, JA, ST, AC, ST, SH, WN, KN, AC, AC, TN, TN }, 	 //	 132	 1700
{ AC, AC, JA, JA, JA, ST, AC, ST, JA, WN, KN, AC, AC, SH, TN }, 	 //	 133	 1700
{ AC, AC, JA, SK, SH, ST, AC, TN, JA, JA, KN, AC, AC, JA, JA }, 	 //	 134	 1700
{ AC, AC, JA, JA, JA, ST, AC, TN, JA, WN, KN, AC, AC, JA, TN }, 	 //	 135	 1700
{ AC, AC, JA, JA, JA, ST, AC, TN, SH, JA, KN, AC, AC, TN, WN }, 	 //	 136	 1700
{ AC, AC, JA, ST, QN, ST, AC, TN, JA, SH, KN, LO, AC, TN, JA }, 	 //	 137	 1700
{ AC, JA, JA, JA, AC, ST, JA, TN, TN, LO, KN, JA, AC, AC, AC }, 	 //	 138	 1700
{ AC, JA, JA, JA, TN, ST, JA, TN, TN, ST, KN, JA, AC, AC, AC }, 	 //	 139	 1700
{ AC, JA, JA, JA, QN, ST, JA, TN, TN, KN, KN, SH, AC, AC, AC }, 	 //	 140	 1700
{ AC, SH, JA, JA, JA, ST, TN, ST, TN, TN, KN, TN, AC, AC, AC }, 	 //	 141	 1700
{ AC, WN, JA, JA, JA, ST, AC, ST, SH, TN, KN, KN, AC, TN, AC }, 	 //	 142	 1700
{ AC, WN, JA, JA, JA, ST, AC, TN, SH, WN, KN, KN, AC, TN, TN }, 	 //	 143	 1700
{ AC, WN, JA, JA, JA, ST, AC, TN, TN, JA, KN, KN, AC, AC, JA }, 	 //	 144	 1700
{ AC, JA, JA, JA, SK, ST, TN, ST, TN, KN, KN, AC, AC, AC, KN }, 	 //	 145	 1700
{ AC, JA, JA, JA, KN, ST, TN, ST, TN, KN, KN, AC, AC, AC, KN }, 	 //	 146	 1700
{ AC, JA, JA, JA, KN, ST, TN, ST, TN, KN, KN, AC, AC, AC, CR }, 	 //	 147	 1700
{ AC, JA, JA, JA, CR, ST, TN, ST, TN, QN, KN, AC, AC, AC, KN }, 	 //	 148	 1700
{ AC, TN, JA, SK, QN, ST, AC, ST, JA, SH, KN, AC, AC, JA, JA }, 	 //	 149	 1700
{ AC, TN, JA, SK, SH, ST, AC, ST, JA, JA, KN, AC, AC, JA, JA }, 	 //	 150	 1700
{ AC, TN, JA, SK, QN, ST, AC, ST, JA, PF, KN, AC, AC, JA, JA }, 	 //	 151	 1700
{ AC, TN, JA, JA, QN, ST, AC, TN, JA, PF, KN, AC, AC, SH, JA }, 	 //	 152	 1700
{ AC, TN, JA, ST, QN, ST, AC, TN, JA, PF, KN, AC, AC, TN, JA }, 	 //	 153	 1700
{ AC, AC, JA, JA, QN, ST, AC, ST, JA, PF, KN, PF, AC, JA, JA }, 	 //	 154	 1700
{ AC, AC, JA, JA, QN, ST, AC, ST, JA, PF, KN, PF, AC, SH, JA }, 	 //	 155	 1700
{ AC, AC, JA, SK, SH, ST, AC, TN, JA, JA, KN, PF, AC, JA, JA }, 	 //	 156	 1700
{ AC, AC, JA, JA, QN, ST, AC, TN, JA, SH, KN, PF, AC, JA, JA }, 	 //	 157	 1700
{ AC, KN, JA, JA, JA, ST, KN, ST, TN, TN, KN, SK, AC, AC, AC }, 	 //	 158	 1700
{ AC, KN, JA, JA, QN, ST, AC, TN, JA, SH, KN, SH, AC, SH, JA }, 	 //	 159	 1700
{ AC, KN, JA, JA, SH, ST, AC, TN, JA, JA, KN, SH, AC, SH, JA }, 	 //	 160	 1700
{ ST, JA, JA, JA, TN, KN, JA, ST, TN, ST, KN, SH, AC, AC, AC }, 	 //	 161	 1700
{ ST, JA, JA, JA, TN, KN, JA, TN, TN, ST, KN, SH, AC, AC, AC }, 	 //	 162	 1700
{ ST, JA, JA, JA, AC, KN, SH, TN, TN, LO, KN, TN, AC, AC, AC }, 	 //	 163	 1700
{ ST, TN, JA, JA, JA, KN, WN, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 164	 1700
{ ST, JA, JA, JA, KN, KN, TN, ST, TN, KN, KN, AC, AC, AC, CR }, 	 //	 165	 1700
{ KN, SH, JA, JA, JA, KN, AC, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 166	 1700
{ KN, AC, JA, JA, JA, KN, AC, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 167	 1700
{ KN, AC, JA, JA, JA, KN, AC, TN, TN, WN, KN, AC, AC, AC, TN }, 	 //	 168	 1700
{ KN, JA, JA, JA, LO, KN, JA, TN, TN, AC, KN, SH, AC, AC, AC }, 	 //	 169	 1700
{ KN, JA, JA, JA, QN, KN, JA, TN, TN, KN, KN, SH, AC, AC, AC }, 	 //	 170	 1700
{ KN, JA, JA, JA, AC, KN, SH, ST, TN, AC, KN, TN, AC, AC, AC }, 	 //	 171	 1700
{ KN, JA, JA, JA, QN, KN, SH, TN, TN, KN, KN, TN, AC, AC, AC }, 	 //	 172	 1700
{ KN, TN, JA, JA, JA, KN, WN, ST, TN, JA, KN, AC, AC, AC, JA }, 	 //	 173	 1700
{ KN, ST, JA, JA, JA, KN, JA, ST, TN, TN, KN, TN, AC, AC, AC }, 	 //	 174	 1700
{ KN, JA, JA, JA, TN, KN, TN, ST, TN, TN, KN, AC, AC, AC, TN }, 	 //	 175	 1700
{ KN, KN, JA, JA, JA, KN, AC, ST, TN, TN, KN, SH, AC, AC, AC }, 	 //	 176	 1700
{ KN, KN, JA, JA, JA, KN, KN, ST, TN, TN, SK, ST, AC, AC, AC }, 	 //	 177	 1700
{ KN, QN, JA, JA, JA, KN, QN, ST, TN, TN, SK, QN, AC, AC, AC }, 	 //	 178	 1700
{ KN, SK, JA, JA, JA, KN, JA, ST, TN, TN, SK, JA, AC, AC, AC }, 	 //	 179	 1700
{ KN, JA, JA, JA, LO, KN, JA, ST, TN, AC, SK, JA, AC, AC, AC }, 	 //	 180	 1700
{ KN, JA, JA, JA, QN, KN, SH, TN, TN, KN, SK, TN, AC, AC, AC }, 	 //	 181	 1700
{ KN, KN, JA, JA, JA, KN, QN, ST, TN, TN, SK, ST, AC, AC, AC }, 	 //	 182	 1700
{ KN, JA, JA, JA, SH, KN, TN, ST, TN, JA, SK, AC, AC, AC, JA }, 	 //	 183	 1700
{ KN, TN, JA, JA, JA, KN, AC, TN, TN, WN, SK, AC, AC, AC, TN }, 	 //	 184	 1700
{ KN, LO, JA, JA, JA, SK, KN, ST, TN, TN, QN, KN, AC, AC, AC }, 	 //	 185	 1700
{ KN, JA, JA, JA, AC, SK, JA, ST, TN, LO, QN, JA, AC, AC, AC }, 	 //	 186	 1700
{ KN, JA, JA, JA, QN, SK, JA, ST, TN, KN, QN, JA, AC, AC, AC }, 	 //	 187	 1700
{ KN, JA, JA, JA, TN, SK, SH, TN, TN, AC, QN, TN, AC, AC, AC }, 	 //	 188	 1700
{ KN, TN, JA, JA, JA, SK, TN, ST, TN, TN, QN, TN, AC, AC, AC }, 	 //	 189	 1700
{ KN, TN, TN, TN, TN, SK, TN, AC, WN, AC, QN, TN, AC, AC, AC }, 	 //	 190	 1700
{ KN, TN, JA, JA, JA, SK, WN, TN, TN, JA, QN, AC, AC, AC, WN }, 	 //	 191	 1700
{ KN, JA, JA, JA, KN, SK, TN, ST, TN, KN, QN, AC, AC, AC, KN }, 	 //	 192	 1700
{ KN, JA, JA, JA, KN, SK, TN, ST, TN, AC, QN, AC, AC, AC, LO }, 	 //	 193	 1700
{ KN, AC, JA, JA, JA, SK, AC, TN, TN, JA, QN, AC, AC, AC, JA }, 	 //	 194	 1700
{ KN, KN, JA, JA, JA, SK, AC, ST, TN, TN, QN, SH, AC, AC, AC }, 	 //	 195	 1700
{ SK, AC, JA, JA, JA, QN, SH, ST, TN, JA, QN, AC, AC, AC, WN }, 	 //	 196	 1700
{ SK, AC, JA, JA, JA, QN, SH, TN, TN, WN, QN, AC, AC, AC, TN }, 	 //	 197	 1700
{ SK, SH, JA, JA, JA, QN, AC, TN, TN, JA, QN, AC, AC, AC, WN }, 	 //	 198	 1700
{ SK, QN, QN, QN, QN, QN, SK, SK, SK, PF, QN, JA, JA, JA, JA }, 	 //	 199	 1700
{ SK, JA, JA, JA, QN, QN, JA, TN, TN, KN, QN, JA, AC, AC, AC }, 	 //	 200	 1700
{ SK, JA, JA, JA, QN, QN, JA, TN, TN, KN, QN, SH, AC, AC, AC }, 	 //	 201	 1700
{ SK, JA, JA, JA, AC, QN, SH, ST, TN, LO, QN, TN, AC, AC, AC }, 	 //	 202	 1700
{ SK, JA, JA, JA, AC, QN, SH, ST, TN, AC, QN, TN, AC, AC, AC }, 	 //	 203	 1700
{ SK, JA, JA, JA, PF, QN, TN, ST, TN, JA, QN, AC, AC, AC, TN }, 	 //	 204	 1700
{ SK, TN, JA, JA, JA, QN, AC, ST, TN, JA, QN, AC, AC, AC, WN }, 	 //	 205	 1700
{ SK, TN, JA, JA, JA, QN, AC, TN, TN, JA, QN, AC, AC, AC, JA }, 	 //	 206	 1700
{ SK, TN, JA, JA, JA, QN, AC, TN, TN, WN, QN, AC, AC, AC, TN }, 	 //	 207	 1700
{ SK, KN, JA, JA, JA, QN, KN, ST, TN, TN, QN, SK, AC, AC, AC }, 	 //	 208	 1700
{ SK, QN, JA, JA, JA, QN, KN, TN, TN, JA, QN, AC, AC, AC, WN }, 	 //	 209	 1700
{ QN, AC, JA, JA, JA, QN, SH, ST, TN, JA, QN, AC, AC, AC, JA }, 	 //	 210	 1700
{ QN, QN, JA, JA, JA, QN, QN, ST, TN, TN, QN, QN, AC, AC, AC }, 	 //	 211	 1700
{ QN, QN, QN, QN, JA, QN, QN, SK, ST, JA, QN, QN, JA, JA, JA }, 	 //	 212	 1700
{ QN, TN, TN, TN, TN, QN, TN, AC, WN, ST, QN, TN, AC, AC, AC }, 	 //	 213	 1700
{ QN, QN, JA, JA, JA, QN, ST, ST, TN, TN, QN, JA, AC, AC, AC }, 	 //	 214	 1700
{ QN, JA, JA, JA, PF, QN, TN, ST, TN, JA, QN, AC, AC, AC, TN }, 	 //	 215	 1700
{ QN, JA, JA, JA, AC, QN, TN, ST, TN, AC, QN, AC, AC, AC, SK }, 	 //	 216	 1700
{ QN, JA, JA, JA, KN, QN, TN, ST, TN, KN, QN, AC, AC, AC, KN }, 	 //	 217	 1700
{ QN, JA, TN, JA, PF, QN, TN, AC, TN, JA, QN, AC, AC, AC, TN }, 	 //	 218	 1700
{ QN, QN, QN, QN, QN, QN, QN, SK, ST, PF, SH, SK, JA, JA, JA }, 	 //	 219	 1700
{ QN, JA, JA, JA, AC, QN, SH, ST, TN, LO, SH, TN, AC, AC, AC }, 	 //	 220	 1700
{ QN, TN, JA, JA, JA, QN, TN, ST, TN, TN, SH, TN, AC, AC, AC }, 	 //	 221	 1700
{ QN, TN, TN, TN, TN, QN, TN, AC, WN, ST, SH, WN, AC, AC, AC }, 	 //	 222	 1700
{ QN, JA, JA, JA, KN, QN, TN, ST, TN, KN, SH, AC, AC, AC, SK }, 	 //	 223	 1700
{ QN, JA, JA, JA, TN, QN, TN, ST, TN, TN, SH, AC, AC, AC, TN }, 	 //	 224	 1700
{ QN, JA, TN, JA, TN, QN, TN, AC, TN, TN, SH, AC, AC, AC, TN }, 	 //	 225	 1700
{ QN, TN, TN, TN, TN, QN, AC, AC, WN, TN, SH, AC, AC, AC, TN }, 	 //	 226	 1700
{ QN, QN, QN, QN, QN, SH, QN, SK, ST, PF, JA, SK, JA, JA, JA }, 	 //	 227	 1700
{ QN, SK, JA, AC, LO, SH, JA, ST, PF, AC, JA, JA, AC, AC, AC }, 	 //	 228	 1700
{ QN, SK, JA, PF, TN, SH, JA, ST, AC, ST, JA, JA, AC, AC, AC }, 	 //	 229	 1700
{ QN, SK, JA, WN, AC, SH, JA, ST, AC, LO, JA, JA, AC, KN, AC }, 	 //	 230	 1700
{ QN, SK, JA, JA, AC, SH, JA, ST, TN, AC, JA, JA, AC, AC, AC }, 	 //	 231	 1700
{ QN, SK, JA, TN, AC, SH, JA, ST, AC, SK, JA, JA, AC, AC, KN }, 	 //	 232	 1700
{ QN, SK, JA, AC, TN, SH, JA, ST, AC, AC, JA, JA, AC, AC, AC }, 	 //	 233	 1700
{ QN, SK, JA, AC, AC, SH, JA, TN, AC, KN, JA, JA, AC, AC, QN }, 	 //	 234	 1700
{ QN, SK, JA, AC, AC, SH, JA, TN, AC, LO, JA, JA, AC, LO, AC }, 	 //	 235	 1700
{ QN, SK, JA, TN, TN, SH, JA, TN, WN, AC, JA, JA, AC, AC, AC }, 	 //	 236	 1700
{ QN, SK, JA, AC, AC, SH, JA, TN, AC, LO, JA, JA, AC, PF, AC }, 	 //	 237	 1700
{ QN, JA, JA, PF, AC, SH, JA, ST, AC, AC, JA, JA, AC, AC, SK }, 	 //	 238	 1700
{ QN, JA, JA, AC, AC, SH, JA, ST, AC, AC, JA, JA, AC, AC, CR }, 	 //	 239	 1700
{ QN, JA, JA, WN, AC, SH, JA, ST, AC, SK, JA, JA, AC, KN, KN }, 	 //	 240	 1700
{ QN, JA, JA, AC, AC, SH, JA, ST, AC, KN, JA, JA, AC, AC, QN }, 	 //	 241	 1700
{ QN, JA, JA, AC, QN, SH, JA, ST, AC, KN, JA, JA, AC, AC, AC }, 	 //	 242	 1700
{ QN, JA, JA, AC, AC, SH, JA, ST, AC, SK, JA, JA, AC, PF, KN }, 	 //	 243	 1700
{ QN, JA, JA, PF, AC, SH, JA, TN, AC, AC, JA, JA, AC, AC, SK }, 	 //	 244	 1700
{ QN, JA, JA, AC, TN, SH, JA, TN, AC, AC, JA, JA, AC, AC, AC }, 	 //	 245	 1700
{ QN, JA, JA, AC, QN, SH, JA, TN, AC, KN, JA, JA, AC, AC, AC }, 	 //	 246	 1700
{ QN, JA, JA, QN, TN, SH, JA, TN, KN, AC, JA, JA, AC, AC, AC }, 	 //	 247	 1700
{ QN, JA, JA, QN, QN, SH, JA, TN, KN, KN, JA, JA, AC, AC, AC }, 	 //	 248	 1700
{ QN, JA, JA, TN, JA, SH, JA, ST, AC, TN, JA, SH, AC, AC, AC }, 	 //	 249	 1700
{ QN, JA, JA, AC, AC, SH, JA, ST, AC, SK, JA, SH, AC, AC, KN }, 	 //	 250	 1700
{ QN, JA, JA, QN, AC, SH, JA, ST, KN, AC, JA, SH, AC, AC, AC }, 	 //	 251	 1700
{ QN, JA, JA, KN, AC, SH, JA, ST, AC, LO, JA, SH, AC, PF, AC }, 	 //	 252	 1700
{ QN, JA, JA, PF, LO, SH, JA, TN, AC, AC, JA, SH, AC, AC, AC }, 	 //	 253	 1700
{ QN, JA, JA, AC, AC, SH, JA, TN, AC, AC, JA, SH, AC, LO, CR }, 	 //	 254	 1700
{ QN, JA, JA, AC, AC, SH, JA, TN, AC, AC, JA, SH, AC, LO, SK }, 	 //	 255	 1700
{ QN, JA, JA, WN, AC, SH, JA, TN, AC, AC, JA, SH, AC, KN, CR }, 	 //	 256	 1700
{ QN, JA, JA, AC, AC, SH, JA, TN, AC, SK, JA, SH, AC, PF, KN }, 	 //	 257	 1700
{ QN, JA, JA, KN, AC, SH, JA, TN, AC, SK, JA, SH, AC, PF, KN }, 	 //	 258	 1700
{ QN, JA, JA, JA, AC, SH, SH, ST, TN, AC, JA, TN, AC, AC, AC }, 	 //	 259	 1700
{ QN, QN, QN, QN, AC, SH, ST, SK, QN, KN, JA, JA, JA, QN, QN }, 	 //	 260	 1700
{ QN, QN, QN, QN, QN, SH, ST, SK, QN, QN, JA, JA, JA, SK, SH }, 	 //	 261	 1700
{ QN, ST, JA, AC, LO, SH, JA, ST, PF, AC, JA, TN, AC, AC, AC }, 	 //	 262	 1700
{ QN, ST, JA, AC, JA, SH, JA, ST, PF, TN, JA, TN, AC, AC, AC }, 	 //	 263	 1700
{ QN, ST, JA, PF, JA, SH, JA, ST, AC, TN, JA, TN, AC, AC, AC }, 	 //	 264	 1700
{ QN, ST, JA, AC, LO, SH, JA, ST, AC, AC, JA, TN, AC, AC, AC }, 	 //	 265	 1700
{ QN, ST, JA, AC, AC, SH, JA, ST, AC, KN, JA, TN, AC, PF, QN }, 	 //	 266	 1700
{ QN, ST, JA, AC, AC, SH, JA, TN, PF, AC, JA, TN, AC, AC, AC }, 	 //	 267	 1700
{ QN, ST, JA, PF, AC, SH, JA, TN, AC, SK, JA, TN, AC, AC, KN }, 	 //	 268	 1700
{ QN, ST, JA, AC, JA, SH, JA, TN, AC, TN, JA, TN, AC, AC, AC }, 	 //	 269	 1700
{ QN, ST, JA, TN, TN, SH, JA, TN, AC, AC, JA, TN, AC, AC, AC }, 	 //	 270	 1700
{ QN, JA, JA, JA, SH, SH, TN, ST, TN, JA, JA, AC, AC, AC, JA }, 	 //	 271	 1700
{ SH, AC, JA, JA, JA, JA, LO, ST, TN, TN, JA, KN, AC, AC, AC }, 	 //	 272	 1700
{ SH, SK, JA, AC, TN, JA, JA, ST, PF, AC, JA, JA, AC, AC, AC }, 	 //	 273	 1700
{ SH, SK, JA, WN, AC, JA, JA, ST, AC, AC, JA, JA, AC, KN, CR }, 	 //	 274	 1700
{ SH, SK, JA, JA, AC, JA, JA, ST, TN, LO, JA, JA, AC, AC, AC }, 	 //	 275	 1700
{ SH, SK, JA, AC, TN, JA, JA, ST, AC, AC, JA, JA, AC, AC, AC }, 	 //	 276	 1700
{ SH, SK, JA, AC, AC, JA, JA, ST, AC, AC, JA, JA, AC, AC, SK }, 	 //	 277	 1700
{ SH, SK, JA, AC, AC, JA, JA, ST, AC, KN, JA, JA, AC, PF, QN }, 	 //	 278	 1700
{ SH, SK, JA, KN, AC, JA, JA, ST, AC, KN, JA, JA, AC, PF, QN }, 	 //	 279	 1700
{ SH, SK, JA, AC, JA, JA, JA, TN, PF, TN, JA, JA, AC, AC, AC }, 	 //	 280	 1700
{ SH, SK, JA, PF, AC, JA, JA, TN, AC, AC, JA, JA, AC, AC, SK }, 	 //	 281	 1700
{ SH, SK, JA, AC, TN, JA, JA, TN, AC, ST, JA, JA, AC, AC, AC }, 	 //	 282	 1700
{ SH, SK, JA, JA, LO, JA, JA, TN, TN, AC, JA, JA, AC, AC, AC }, 	 //	 283	 1700
{ SH, SK, JA, JA, AC, JA, JA, TN, TN, AC, JA, JA, AC, AC, AC }, 	 //	 284	 1700
{ SH, SK, JA, AC, LO, JA, JA, TN, AC, AC, JA, JA, AC, AC, AC }, 	 //	 285	 1700
{ SH, SK, JA, AC, TN, JA, JA, TN, AC, ST, JA, JA, AC, AC, AC }, 	 //	 286	 1700
{ SH, SK, JA, AC, AC, JA, JA, TN, AC, AC, JA, JA, AC, AC, SK }, 	 //	 287	 1700
{ SH, SK, JA, KN, AC, JA, JA, TN, AC, LO, JA, JA, AC, PF, AC }, 	 //	 288	 1700
{ SH, JA, JA, WN, AC, JA, JA, ST, AC, KN, JA, JA, AC, KN, QN }, 	 //	 289	 1700
{ SH, JA, JA, AC, TN, JA, JA, ST, AC, AC, JA, JA, AC, AC, AC }, 	 //	 290	 1700
{ SH, JA, JA, PF, QN, JA, JA, TN, AC, KN, JA, JA, AC, AC, AC }, 	 //	 291	 1700
{ SH, JA, JA, WN, AC, JA, JA, TN, AC, AC, JA, JA, AC, KN, AC }, 	 //	 292	 1700
{ SH, JA, JA, AC, AC, JA, JA, TN, AC, AC, JA, JA, AC, PF, AC }, 	 //	 293	 1700
{ SH, JA, JA, AC, AC, JA, JA, ST, PF, AC, JA, SH, AC, AC, AC }, 	 //	 294	 1700
{ SH, JA, JA, PF, LO, JA, JA, ST, AC, AC, JA, SH, AC, AC, AC }, 	 //	 295	 1700
{ SH, JA, JA, AC, AC, JA, JA, ST, AC, KN, JA, SH, AC, LO, QN }, 	 //	 296	 1700
{ SH, JA, JA, TN, TN, JA, JA, ST, AC, AC, JA, SH, AC, AC, AC }, 	 //	 297	 1700
{ SH, JA, JA, AC, JA, JA, JA, TN, AC, TN, JA, SH, AC, AC, AC }, 	 //	 298	 1700
{ SH, JA, JA, TN, TN, JA, JA, TN, AC, ST, JA, SH, AC, AC, AC }, 	 //	 299	 1700
{ SH, JA, JA, TN, AC, JA, JA, TN, AC, SK, JA, SH, AC, AC, KN }, 	 //	 300	 1700
{ SH, JA, JA, AC, TN, JA, JA, TN, AC, ST, JA, SH, AC, AC, AC }, 	 //	 301	 1700
{ SH, JA, JA, AC, AC, JA, JA, TN, AC, AC, JA, SH, AC, AC, SK }, 	 //	 302	 1700
{ SH, JA, JA, AC, AC, JA, JA, TN, AC, AC, JA, SH, AC, PF, SK }, 	 //	 303	 1700
{ SH, JA, JA, KN, AC, JA, JA, TN, AC, AC, JA, SH, AC, PF, CR }, 	 //	 304	 1700
{ SH, TN, JA, JA, JA, JA, WN, ST, TN, JA, JA, AC, AC, AC, JA }, 	 //	 305	 1700
{ SH, QN, QN, QN, QN, JA, ST, SK, QN, QN, JA, JA, JA, SK, QN }, 	 //	 306	 1700
{ SH, ST, JA, AC, AC, JA, JA, ST, AC, AC, JA, TN, AC, AC, CR }, 	 //	 307	 1700
{ SH, ST, JA, AC, AC, JA, JA, ST, AC, LO, JA, TN, AC, LO, AC }, 	 //	 308	 1700
{ SH, ST, JA, AC, AC, JA, JA, ST, AC, AC, JA, TN, AC, LO, CR }, 	 //	 309	 1700
{ SH, ST, JA, AC, AC, JA, JA, ST, AC, AC, JA, TN, AC, LO, AC }, 	 //	 310	 1700
{ SH, ST, JA, WN, AC, JA, JA, ST, AC, AC, JA, TN, AC, KN, CR }, 	 //	 311	 1700
{ SH, ST, JA, TN, LO, JA, JA, ST, AC, AC, JA, TN, AC, AC, AC }, 	 //	 312	 1700
{ SH, ST, JA, PF, TN, JA, JA, TN, AC, AC, JA, TN, AC, AC, AC }, 	 //	 313	 1700
{ SH, ST, JA, TN, AC, JA, JA, TN, WN, AC, JA, TN, AC, AC, AC }, 	 //	 314	 1700
{ SH, ST, JA, TN, TN, JA, JA, TN, WN, AC, JA, TN, AC, AC, AC }, 	 //	 315	 1700
{ SH, ST, JA, WN, AC, JA, JA, TN, AC, AC, JA, TN, AC, KN, AC }, 	 //	 316	 1700
{ SH, ST, JA, AC, TN, JA, JA, TN, AC, ST, JA, TN, AC, AC, AC }, 	 //	 317	 1700
{ SH, ST, JA, AC, AC, JA, JA, TN, AC, SK, JA, TN, AC, AC, KN }, 	 //	 318	 1700
{ SH, ST, JA, AC, AC, JA, JA, TN, AC, AC, JA, TN, AC, PF, SK }, 	 //	 319	 1700
{ SH, ST, JA, KN, AC, JA, JA, TN, AC, AC, JA, TN, AC, PF, AC }, 	 //	 320	 1700
{ SH, JA, JA, JA, AC, JA, TN, ST, TN, AC, JA, AC, AC, AC, SK }, 	 //	 321	 1700
{ SH, AC, JA, JA, JA, JA, AC, TN, TN, WN, JA, AC, AC, AC, TN }, 	 //	 322	 1700
{ SH, AC, JA, JA, JA, JA, PF, ST, TN, TN, JA, KN, AC, AC, AC }, 	 //	 323	 1700
{ SH, QN, JA, JA, JA, JA, KN, ST, TN, WN, JA, AC, AC, AC, TN }, 	 //	 324	 1700
{ JA, SH, JA, JA, JA, JA, AC, TN, TN, JA, JA, AC, AC, AC, WN }, 	 //	 325	 1700
{ JA, AC, JA, JA, JA, JA, AC, ST, TN, WN, JA, AC, AC, AC, TN }, 	 //	 326	 1700
{ JA, SK, JA, AC, AC, JA, JA, ST, PF, AC, JA, JA, AC, AC, AC }, 	 //	 327	 1700
{ JA, SK, JA, AC, AC, JA, JA, ST, AC, AC, JA, JA, AC, LO, SK }, 	 //	 328	 1700
{ JA, SK, JA, WN, AC, JA, JA, ST, AC, LO, JA, JA, AC, KN, AC }, 	 //	 329	 1700
{ JA, SK, JA, AC, TN, JA, JA, ST, AC, AC, JA, JA, AC, AC, AC }, 	 //	 330	 1700
{ JA, SK, JA, PF, JA, JA, JA, TN, AC, TN, JA, JA, AC, AC, AC }, 	 //	 331	 1700
{ JA, SK, JA, PF, TN, JA, JA, TN, AC, AC, JA, JA, AC, AC, AC }, 	 //	 332	 1700
{ JA, SK, JA, AC, TN, JA, JA, TN, AC, ST, JA, JA, AC, AC, AC }, 	 //	 333	 1700
{ JA, SK, JA, TN, TN, JA, JA, TN, WN, AC, JA, JA, AC, AC, AC }, 	 //	 334	 1700
{ JA, SK, JA, WN, AC, JA, JA, TN, AC, AC, JA, JA, AC, KN, SK }, 	 //	 335	 1700
{ JA, SK, JA, WN, AC, JA, JA, TN, AC, SK, JA, JA, AC, KN, KN }, 	 //	 336	 1700
{ JA, SK, JA, TN, LO, JA, JA, TN, AC, AC, JA, JA, AC, AC, AC }, 	 //	 337	 1700
{ JA, SK, JA, AC, AC, JA, JA, TN, AC, AC, JA, JA, AC, PF, AC }, 	 //	 338	 1700
{ JA, JA, JA, AC, QN, JA, SH, ST, PF, KN, JA, TN, AC, AC, AC }, 	 //	 339	 1700
{ JA, JA, JA, AC, AC, JA, SH, ST, AC, AC, JA, TN, AC, LO, AC }, 	 //	 340	 1700
{ JA, JA, JA, TN, TN, JA, SH, ST, WN, ST, JA, TN, AC, AC, AC }, 	 //	 341	 1700
{ JA, JA, JA, AC, AC, JA, SH, ST, AC, AC, JA, TN, AC, AC, SK }, 	 //	 342	 1700
{ JA, JA, JA, AC, AC, JA, SH, ST, AC, LO, JA, TN, AC, PF, AC }, 	 //	 343	 1700
{ JA, JA, JA, KN, AC, JA, SH, ST, AC, LO, JA, TN, AC, PF, AC }, 	 //	 344	 1700
{ JA, JA, JA, KN, AC, JA, SH, ST, AC, AC, JA, TN, AC, PF, SK }, 	 //	 345	 1700
{ JA, JA, JA, PF, TN, JA, SH, TN, AC, AC, JA, TN, AC, AC, AC }, 	 //	 346	 1700
{ JA, JA, JA, AC, LO, JA, SH, TN, AC, AC, JA, TN, AC, AC, AC }, 	 //	 347	 1700
{ JA, JA, JA, AC, TN, JA, SH, TN, AC, AC, JA, TN, AC, AC, AC }, 	 //	 348	 1700
{ JA, JA, JA, QN, TN, JA, SH, TN, KN, ST, JA, TN, AC, AC, AC }, 	 //	 349	 1700
{ JA, JA, JA, QN, AC, JA, SH, TN, KN, AC, JA, TN, AC, AC, AC }, 	 //	 350	 1700
{ JA, TN, JA, JA, JA, JA, WN, TN, TN, JA, JA, AC, AC, AC, WN }, 	 //	 351	 1700
{ JA, ST, JA, AC, AC, JA, JA, ST, AC, KN, JA, TN, AC, AC, QN }, 	 //	 352	 1700
{ JA, ST, JA, AC, AC, JA, JA, ST, AC, AC, JA, TN, AC, LO, AC }, 	 //	 353	 1700
{ JA, ST, JA, TN, JA, JA, JA, ST, AC, TN, JA, TN, AC, AC, AC }, 	 //	 354	 1700
{ JA, ST, JA, PF, AC, JA, JA, TN, AC, SK, JA, TN, AC, AC, KN }, 	 //	 355	 1700
{ JA, ST, JA, AC, AC, JA, JA, TN, AC, SK, JA, TN, AC, AC, KN }, 	 //	 356	 1700
{ JA, ST, JA, TN, QN, JA, JA, TN, WN, KN, JA, TN, AC, AC, AC }, 	 //	 357	 1700
{ JA, ST, JA, JA, QN, JA, JA, TN, TN, KN, JA, TN, AC, AC, AC }, 	 //	 358	 1700
{ JA, ST, JA, TN, QN, JA, JA, TN, AC, KN, JA, TN, AC, AC, AC }, 	 //	 359	 1700
{ JA, ST, JA, AC, AC, JA, JA, TN, AC, KN, JA, TN, AC, AC, QN }, 	 //	 360	 1700
{ JA, ST, JA, QN, AC, JA, JA, TN, KN, AC, JA, TN, AC, AC, AC }, 	 //	 361	 1700
{ JA, JA, JA, PF, KN, JA, TN, ST, AC, SK, JA, AC, AC, AC, QN }, 	 //	 362	 1700
{ JA, JA, JA, PF, JA, JA, TN, ST, AC, JA, JA, AC, AC, AC, WN }, 	 //	 363	 1700
{ JA, JA, JA, PF, TN, JA, TN, ST, AC, TN, JA, AC, AC, AC, TN }, 	 //	 364	 1700
{ JA, JA, JA, AC, CR, JA, TN, ST, AC, KN, JA, AC, AC, AC, KN }, 	 //	 365	 1700
{ JA, JA, JA, AC, TN, JA, TN, ST, AC, TN, JA, AC, AC, AC, TN }, 	 //	 366	 1700
{ JA, JA, JA, TN, QN, JA, TN, ST, AC, SH, JA, AC, AC, AC, JA }, 	 //	 367	 1700
{ JA, JA, JA, TN, PF, JA, TN, ST, AC, JA, JA, AC, AC, AC, TN }, 	 //	 368	 1700
{ JA, JA, JA, AC, KN, JA, TN, ST, AC, KN, JA, AC, AC, AC, SK }, 	 //	 369	 1700
{ JA, JA, JA, AC, AC, JA, TN, ST, AC, LO, JA, AC, AC, PF, AC }, 	 //	 370	 1700
{ JA, JA, JA, QN, AC, JA, TN, ST, KN, KN, JA, AC, AC, AC, QN }, 	 //	 371	 1700
{ JA, JA, JA, QN, KN, JA, TN, ST, KN, KN, JA, AC, AC, AC, CR }, 	 //	 372	 1700
{ JA, JA, JA, KN, AC, JA, TN, ST, AC, AC, JA, AC, AC, PF, AC }, 	 //	 373	 1700
{ JA, JA, JA, AC, TN, JA, TN, TN, PF, TN, JA, AC, AC, AC, TN }, 	 //	 374	 1700
{ JA, JA, JA, PF, QN, JA, TN, TN, AC, QN, JA, AC, AC, AC, SH }, 	 //	 375	 1700
{ JA, JA, JA, PF, JA, JA, TN, TN, AC, JA, JA, AC, AC, AC, WN }, 	 //	 376	 1700
{ JA, JA, JA, TN, QN, JA, TN, TN, WN, PF, JA, AC, AC, AC, JA }, 	 //	 377	 1700
{ JA, JA, JA, TN, KN, JA, TN, TN, WN, KN, JA, AC, AC, AC, KN }, 	 //	 378	 1700
{ JA, JA, JA, TN, KN, JA, TN, TN, WN, AC, JA, AC, AC, AC, LO }, 	 //	 379	 1700
{ JA, JA, JA, TN, ST, JA, TN, TN, AC, AC, JA, AC, AC, AC, KN }, 	 //	 380	 1700
{ JA, JA, JA, TN, PF, JA, TN, TN, AC, JA, JA, AC, AC, AC, TN }, 	 //	 381	 1700
{ JA, JA, JA, AC, ST, JA, TN, TN, AC, AC, JA, AC, AC, AC, KN }, 	 //	 382	 1700
{ JA, JA, JA, AC, PF, JA, TN, TN, AC, JA, JA, AC, AC, AC, TN }, 	 //	 383	 1700
{ JA, JA, JA, AC, KN, JA, TN, TN, AC, KN, JA, AC, AC, AC, KN }, 	 //	 384	 1700
{ JA, JA, JA, AC, AC, JA, TN, TN, AC, AC, JA, AC, AC, PF, AC }, 	 //	 385	 1700
{ JA, JA, JA, AC, AC, JA, TN, TN, AC, AC, JA, AC, AC, PF, SK }, 	 //	 386	 1700
{ JA, JA, JA, QN, AC, JA, TN, TN, KN, KN, JA, AC, AC, AC, QN }, 	 //	 387	 1700
{ JA, JA, JA, KN, AC, JA, TN, TN, AC, AC, JA, AC, AC, PF, AC }, 	 //	 388	 1700
{ JA, JA, JA, KN, AC, JA, TN, TN, AC, SK, JA, AC, AC, PF, KN }, 	 //	 389	 1700
{ JA, AC, JA, JA, JA, JA, PF, ST, TN, TN, JA, KN, AC, AC, AC }, 	 //	 390	 1700
{ JA, AC, JA, JA, JA, JA, SH, ST, TN, WN, WN, AC, AC, AC, TN }, 	 //	 391	 1700
{ JA, SH, JA, JA, JA, JA, AC, ST, TN, WN, WN, AC, AC, AC, TN }, 	 //	 392	 1700
{ JA, JA, JA, AC, JA, JA, JA, ST, PF, TN, WN, JA, AC, AC, AC }, 	 //	 393	 1700
{ JA, JA, JA, PF, TN, JA, JA, ST, AC, ST, WN, JA, AC, AC, AC }, 	 //	 394	 1700
{ JA, JA, JA, AC, TN, JA, JA, ST, AC, ST, WN, JA, AC, AC, AC }, 	 //	 395	 1700
{ JA, JA, JA, AC, TN, JA, JA, ST, AC, AC, WN, JA, AC, AC, AC }, 	 //	 396	 1700
{ JA, JA, JA, TN, LO, JA, JA, ST, WN, AC, WN, JA, AC, AC, AC }, 	 //	 397	 1700
{ JA, JA, JA, WN, AC, JA, JA, ST, AC, AC, WN, JA, AC, KN, CR }, 	 //	 398	 1700
{ JA, JA, JA, WN, AC, JA, JA, ST, AC, KN, WN, JA, AC, KN, QN }, 	 //	 399	 1700
{ JA, JA, JA, AC, AC, JA, JA, ST, AC, KN, WN, JA, AC, AC, QN }, 	 //	 400	 1700
{ JA, JA, JA, AC, AC, JA, JA, TN, PF, LO, WN, JA, AC, AC, AC }, 	 //	 401	 1700
{ JA, JA, JA, AC, TN, JA, JA, TN, AC, AC, WN, JA, AC, AC, AC }, 	 //	 402	 1700
{ JA, JA, JA, WN, AC, JA, JA, TN, AC, AC, WN, JA, AC, KN, AC }, 	 //	 403	 1700
{ JA, JA, JA, TN, TN, JA, JA, TN, AC, ST, WN, JA, AC, AC, AC }, 	 //	 404	 1700
{ JA, JA, JA, AC, JA, JA, JA, ST, AC, TN, WN, SH, AC, AC, AC }, 	 //	 405	 1700
{ JA, JA, JA, TN, AC, JA, JA, ST, AC, AC, WN, SH, AC, AC, SK }, 	 //	 406	 1700
{ JA, JA, JA, AC, TN, JA, JA, ST, AC, AC, WN, SH, AC, AC, AC }, 	 //	 407	 1700
{ JA, JA, JA, QN, JA, JA, JA, ST, KN, TN, WN, SH, AC, AC, AC }, 	 //	 408	 1700
{ JA, JA, JA, AC, LO, JA, JA, TN, AC, AC, WN, SH, AC, AC, AC }, 	 //	 409	 1700
{ JA, JA, JA, AC, TN, JA, JA, TN, AC, ST, WN, SH, AC, AC, AC }, 	 //	 410	 1700
{ JA, JA, JA, AC, JA, JA, JA, TN, AC, TN, WN, SH, AC, AC, AC }, 	 //	 411	 1700
{ JA, JA, JA, AC, JA, JA, JA, TN, AC, TN, WN, SH, AC, AC, AC }, 	 //	 412	 1700
{ JA, JA, JA, AC, AC, JA, JA, TN, AC, AC, WN, SH, AC, PF, AC }, 	 //	 413	 1700
{ JA, JA, JA, QN, JA, JA, JA, TN, KN, TN, WN, SH, AC, AC, AC }, 	 //	 414	 1700
{ JA, JA, JA, KN, AC, JA, JA, TN, AC, AC, WN, SH, AC, PF, AC }, 	 //	 415	 1700
{ JA, JA, JA, KN, AC, JA, JA, TN, AC, SK, WN, SH, AC, PF, KN }, 	 //	 416	 1700
{ JA, JA, JA, TN, LO, JA, SH, ST, WN, AC, WN, TN, AC, AC, AC }, 	 //	 417	 1700
{ JA, JA, JA, TN, AC, JA, SH, ST, WN, AC, WN, TN, AC, AC, AC }, 	 //	 418	 1700
{ JA, JA, JA, AC, AC, JA, SH, ST, AC, AC, WN, TN, AC, AC, CR }, 	 //	 419	 1700
{ JA, JA, JA, KN, AC, JA, SH, ST, AC, AC, WN, TN, AC, PF, CR }, 	 //	 420	 1700
{ JA, JA, JA, TN, AC, JA, SH, TN, WN, AC, WN, TN, AC, AC, AC }, 	 //	 421	 1700
{ JA, JA, JA, TN, JA, JA, SH, TN, AC, TN, WN, TN, AC, AC, AC }, 	 //	 422	 1700
{ JA, JA, JA, AC, LO, JA, SH, TN, AC, AC, WN, TN, AC, AC, AC }, 	 //	 423	 1700
{ JA, JA, JA, AC, AC, JA, SH, TN, AC, AC, WN, TN, AC, PF, AC }, 	 //	 424	 1700
{ JA, JA, JA, QN, TN, JA, SH, TN, KN, ST, WN, TN, AC, AC, AC }, 	 //	 425	 1700
{ JA, TN, TN, TN, TN, JA, WN, AC, WN, TN, WN, AC, AC, AC, ST }, 	 //	 426	 1700
{ JA, JA, JA, AC, QN, JA, TN, ST, PF, QN, WN, AC, AC, AC, QN }, 	 //	 427	 1700
{ JA, JA, JA, AC, TN, JA, TN, ST, PF, TN, WN, AC, AC, AC, ST }, 	 //	 428	 1700
{ JA, JA, JA, AC, KN, JA, TN, ST, PF, QN, WN, AC, AC, AC, PF }, 	 //	 429	 1700
{ JA, JA, JA, PF, KN, JA, TN, ST, AC, KN, WN, AC, AC, AC, KN }, 	 //	 430	 1700
{ JA, JA, JA, AC, ST, JA, TN, ST, AC, AC, WN, AC, AC, AC, KN }, 	 //	 431	 1700
{ JA, JA, JA, AC, KN, JA, TN, ST, AC, KN, WN, AC, AC, AC, CR }, 	 //	 432	 1700
{ JA, JA, JA, TN, KN, JA, TN, ST, WN, KN, WN, AC, AC, AC, SK }, 	 //	 433	 1700
{ JA, JA, JA, TN, JA, JA, TN, ST, WN, JA, WN, AC, AC, AC, WN }, 	 //	 434	 1700
{ JA, JA, JA, TN, KN, JA, TN, ST, WN, QN, WN, AC, AC, AC, PF }, 	 //	 435	 1700
{ JA, JA, JA, TN, KN, JA, TN, ST, WN, KN, WN, AC, AC, AC, KN }, 	 //	 436	 1700
{ JA, JA, JA, WN, AC, JA, TN, ST, AC, AC, WN, AC, AC, KN, AC }, 	 //	 437	 1700
{ JA, JA, JA, TN, KN, JA, TN, ST, AC, KN, WN, AC, AC, AC, KN }, 	 //	 438	 1700
{ JA, JA, JA, AC, QN, JA, TN, ST, AC, QN, WN, AC, AC, AC, SH }, 	 //	 439	 1700
{ JA, JA, JA, AC, AC, JA, TN, ST, AC, KN, WN, AC, AC, PF, QN }, 	 //	 440	 1700
{ JA, JA, JA, QN, SK, JA, TN, ST, KN, KN, WN, AC, AC, AC, KN }, 	 //	 441	 1700
{ JA, JA, JA, AC, QN, JA, TN, TN, PF, SH, WN, AC, AC, AC, JA }, 	 //	 442	 1700
{ JA, JA, JA, AC, AC, JA, TN, TN, PF, SK, WN, AC, AC, AC, KN }, 	 //	 443	 1700
{ JA, JA, JA, AC, AC, JA, TN, TN, AC, KN, WN, AC, AC, LO, QN }, 	 //	 444	 1700
{ JA, JA, JA, TN, TN, JA, TN, TN, WN, TN, WN, AC, AC, AC, ST }, 	 //	 445	 1700
{ JA, JA, JA, TN, ST, JA, TN, TN, WN, AC, WN, AC, AC, AC, KN }, 	 //	 446	 1700
{ JA, JA, JA, TN, KN, JA, TN, TN, AC, SK, WN, AC, AC, AC, QN }, 	 //	 447	 1700
{ JA, JA, JA, KN, AC, JA, TN, TN, AC, AC, WN, AC, AC, PF, AC }, 	 //	 448	 1700
{ JA, JA, TN, JA, TN, JA, TN, AC, TN, TN, WN, AC, AC, AC, TN }, 	 //	 449	 1700
{ JA, AC, JA, JA, JA, JA, AC, TN, TN, WN, WN, AC, AC, AC, TN }, 	 //	 450	 1700
{ JA, QN, JA, JA, JA, WN, QN, ST, TN, TN, TN, SK, AC, AC, AC }, 	 //	 451	 1700
{ JA, JA, JA, AC, AC, WN, JA, ST, PF, LO, TN, JA, AC, AC, AC }, 	 //	 452	 1700
{ JA, JA, JA, PF, AC, WN, JA, ST, AC, AC, TN, JA, AC, AC, CR }, 	 //	 453	 1700
{ JA, JA, JA, PF, QN, WN, JA, ST, AC, KN, TN, JA, AC, AC, AC }, 	 //	 454	 1700
{ JA, JA, JA, AC, AC, WN, JA, ST, AC, AC, TN, JA, AC, PF, AC }, 	 //	 455	 1700
{ JA, JA, JA, KN, AC, WN, JA, ST, AC, KN, TN, JA, AC, PF, QN }, 	 //	 456	 1700
{ JA, JA, JA, KN, AC, WN, JA, ST, AC, SK, TN, JA, AC, PF, KN }, 	 //	 457	 1700
{ JA, JA, JA, AC, TN, WN, JA, TN, AC, AC, TN, JA, AC, AC, AC }, 	 //	 458	 1700
{ JA, JA, JA, TN, AC, WN, JA, TN, WN, LO, TN, JA, AC, AC, AC }, 	 //	 459	 1700
{ JA, JA, JA, AC, JA, WN, JA, TN, AC, TN, TN, JA, AC, AC, AC }, 	 //	 460	 1700
{ JA, JA, JA, QN, AC, WN, JA, TN, KN, LO, TN, JA, AC, AC, AC }, 	 //	 461	 1700
{ JA, JA, JA, AC, AC, WN, JA, ST, AC, AC, TN, SH, AC, LO, AC }, 	 //	 462	 1700
{ JA, JA, JA, TN, AC, WN, JA, ST, WN, AC, TN, SH, AC, AC, AC }, 	 //	 463	 1700
{ JA, JA, JA, KN, AC, WN, JA, ST, AC, KN, TN, SH, AC, PF, QN }, 	 //	 464	 1700
{ JA, JA, JA, AC, JA, WN, JA, TN, PF, TN, TN, SH, AC, AC, AC }, 	 //	 465	 1700
{ JA, JA, JA, AC, QN, WN, JA, TN, AC, KN, TN, SH, AC, AC, AC }, 	 //	 466	 1700
{ JA, JA, JA, WN, AC, WN, JA, TN, AC, AC, TN, SH, AC, KN, SK }, 	 //	 467	 1700
{ JA, JA, JA, AC, TN, WN, JA, TN, AC, AC, TN, SH, AC, AC, AC }, 	 //	 468	 1700
{ JA, JA, JA, AC, AC, WN, JA, TN, AC, AC, TN, SH, AC, PF, AC }, 	 //	 469	 1700
{ JA, JA, JA, QN, TN, WN, JA, TN, KN, ST, TN, SH, AC, AC, AC }, 	 //	 470	 1700
{ JA, JA, JA, KN, AC, WN, JA, TN, AC, AC, TN, SH, AC, PF, AC }, 	 //	 471	 1700
{ JA, JA, JA, KN, AC, WN, JA, TN, AC, AC, TN, SH, AC, PF, SK }, 	 //	 472	 1700
{ JA, JA, JA, AC, AC, WN, SH, ST, PF, LO, TN, TN, AC, AC, AC }, 	 //	 473	 1700
{ JA, JA, JA, AC, JA, WN, SH, ST, PF, TN, TN, TN, AC, AC, AC }, 	 //	 474	 1700
{ JA, JA, JA, AC, AC, WN, SH, ST, AC, LO, TN, TN, AC, LO, AC }, 	 //	 475	 1700
{ JA, JA, JA, AC, AC, WN, SH, ST, AC, KN, TN, TN, AC, LO, QN }, 	 //	 476	 1700
{ JA, JA, JA, WN, AC, WN, SH, ST, AC, AC, TN, TN, AC, KN, AC }, 	 //	 477	 1700
{ JA, JA, JA, TN, TN, WN, SH, ST, AC, ST, TN, TN, AC, AC, AC }, 	 //	 478	 1700
{ JA, JA, JA, TN, JA, WN, SH, ST, AC, TN, TN, TN, AC, AC, AC }, 	 //	 479	 1700
{ JA, JA, JA, TN, AC, WN, SH, ST, AC, SK, TN, TN, AC, AC, KN }, 	 //	 480	 1700
{ JA, JA, JA, AC, AC, WN, SH, ST, AC, SK, TN, TN, AC, AC, KN }, 	 //	 481	 1700
{ JA, JA, JA, AC, AC, WN, SH, ST, AC, KN, TN, TN, AC, PF, QN }, 	 //	 482	 1700
{ JA, JA, JA, KN, AC, WN, SH, ST, AC, SK, TN, TN, AC, PF, KN }, 	 //	 483	 1700
{ JA, JA, JA, PF, TN, WN, SH, TN, AC, ST, TN, TN, AC, AC, AC }, 	 //	 484	 1700
{ JA, JA, JA, WN, AC, WN, SH, TN, AC, LO, TN, TN, AC, KN, AC }, 	 //	 485	 1700
{ JA, JA, JA, WN, AC, WN, SH, TN, AC, KN, TN, TN, AC, KN, QN }, 	 //	 486	 1700
{ JA, JA, JA, QN, TN, WN, SH, TN, KN, ST, TN, TN, AC, AC, AC }, 	 //	 487	 1700
{ JA, JA, JA, QN, AC, WN, SH, TN, KN, AC, TN, TN, AC, AC, AC }, 	 //	 488	 1700
{ JA, TN, TN, TN, ST, WN, TN, AC, AC, AC, TN, TN, AC, AC, KN }, 	 //	 489	 1700
{ JA, TN, TN, TN, AC, WN, TN, AC, AC, SK, TN, WN, AC, AC, KN }, 	 //	 490	 1700
{ JA, TN, JA, JA, JA, WN, WN, TN, TN, WN, TN, AC, AC, AC, TN }, 	 //	 491	 1700
{ JA, TN, TN, TN, TN, WN, WN, AC, AC, TN, TN, AC, AC, AC, ST }, 	 //	 492	 1700
{ JA, QN, JA, JA, JA, WN, ST, ST, TN, TN, TN, JA, AC, AC, AC }, 	 //	 493	 1700
{ JA, JA, JA, AC, CR, WN, TN, ST, PF, KN, TN, AC, AC, AC, KN }, 	 //	 494	 1700
{ JA, JA, JA, AC, KN, WN, TN, ST, PF, QN, TN, AC, AC, AC, PF }, 	 //	 495	 1700
{ JA, JA, JA, PF, CR, WN, TN, ST, AC, QN, TN, AC, AC, AC, KN }, 	 //	 496	 1700
{ JA, JA, JA, AC, WN, WN, TN, ST, AC, TN, TN, AC, AC, AC, TN }, 	 //	 497	 1700
{ JA, JA, JA, AC, TN, WN, TN, ST, AC, TN, TN, AC, AC, AC, TN }, 	 //	 498	 1700
{ JA, JA, JA, AC, ST, WN, TN, ST, AC, AC, TN, AC, AC, AC, KN }, 	 //	 499	 1700
{ JA, JA, JA, AC, AC, WN, TN, ST, AC, AC, TN, AC, AC, LO, AC }, 	 //	 500	 1700
{ JA, JA, JA, TN, SH, WN, TN, ST, WN, JA, TN, AC, AC, AC, JA }, 	 //	 501	 1700
{ JA, JA, JA, TN, SK, WN, TN, ST, AC, KN, TN, AC, AC, AC, KN }, 	 //	 502	 1700
{ JA, JA, JA, AC, WN, WN, TN, ST, AC, TN, TN, AC, AC, AC, TN }, 	 //	 503	 1700
{ JA, JA, JA, AC, AC, WN, TN, ST, AC, AC, TN, AC, AC, PF, AC }, 	 //	 504	 1700
{ JA, JA, JA, QN, QN, WN, TN, ST, KN, QN, TN, AC, AC, AC, SH }, 	 //	 505	 1700
{ JA, JA, JA, KN, AC, WN, TN, ST, AC, KN, TN, AC, AC, PF, QN }, 	 //	 506	 1700
{ JA, JA, JA, AC, JA, WN, TN, TN, PF, JA, TN, AC, AC, AC, JA }, 	 //	 507	 1700
{ JA, JA, JA, AC, KN, WN, TN, TN, PF, QN, TN, AC, AC, AC, PF }, 	 //	 508	 1700
{ JA, JA, JA, AC, KN, WN, TN, TN, PF, KN, TN, AC, AC, AC, KN }, 	 //	 509	 1700
{ JA, JA, JA, PF, SH, WN, TN, TN, AC, JA, TN, AC, AC, AC, JA }, 	 //	 510	 1700
{ JA, JA, JA, PF, KN, WN, TN, TN, AC, QN, TN, AC, AC, AC, PF }, 	 //	 511	 1700
{ JA, JA, JA, AC, SK, WN, TN, TN, AC, QN, TN, AC, AC, AC, QN }, 	 //	 512	 1700
{ JA, JA, JA, AC, PF, WN, TN, TN, AC, JA, TN, AC, AC, AC, TN }, 	 //	 513	 1700
{ JA, JA, JA, TN, KN, WN, TN, TN, WN, KN, TN, AC, AC, AC, KN }, 	 //	 514	 1700
{ JA, JA, JA, TN, KN, WN, TN, TN, WN, KN, TN, AC, AC, AC, KN }, 	 //	 515	 1700
{ JA, JA, JA, TN, CR, WN, TN, TN, WN, QN, TN, AC, AC, AC, KN }, 	 //	 516	 1700
{ JA, JA, JA, WN, AC, WN, TN, TN, AC, AC, TN, AC, AC, KN, SK }, 	 //	 517	 1700
{ JA, JA, JA, TN, TN, WN, TN, TN, AC, TN, TN, AC, AC, AC, TN }, 	 //	 518	 1700
{ JA, JA, JA, TN, PF, WN, TN, TN, AC, JA, TN, AC, AC, AC, TN }, 	 //	 519	 1700
{ JA, JA, TN, JA, AC, WN, TN, AC, TN, AC, TN, AC, AC, AC, CR }, 	 //	 520	 1700
{ JA, JA, TN, JA, AC, WN, TN, AC, TN, AC, TN, AC, AC, AC, SK }, 	 //	 521	 1700
{ WN, AC, JA, JA, JA, TN, AC, ST, TN, WN, TN, AC, AC, AC, TN }, 	 //	 522	 1700
{ WN, JA, JA, JA, TN, TN, JA, ST, TN, ST, TN, JA, AC, AC, AC }, 	 //	 523	 1700
{ WN, JA, JA, JA, AC, TN, JA, ST, TN, LO, TN, SH, AC, AC, AC }, 	 //	 524	 1700
{ WN, JA, JA, JA, TN, TN, JA, ST, TN, ST, TN, SH, AC, AC, AC }, 	 //	 525	 1700
{ WN, TN, TN, JA, TN, TN, TN, AC, TN, AC, TN, TN, AC, AC, AC }, 	 //	 526	 1700
{ WN, TN, TN, JA, AC, TN, TN, AC, TN, AC, TN, WN, AC, AC, AC }, 	 //	 527	 1700
{ WN, TN, TN, TN, JA, TN, TN, AC, AC, TN, TN, WN, AC, AC, AC }, 	 //	 528	 1700
{ WN, TN, TN, TN, KN, TN, TN, AC, AC, AC, TN, WN, AC, AC, LO }, 	 //	 529	 1700
{ WN, JA, JA, JA, KN, TN, TN, ST, TN, KN, TN, AC, AC, AC, KN }, 	 //	 530	 1700
{ WN, JA, TN, JA, AC, TN, TN, AC, TN, SK, TN, AC, AC, AC, KN }, 	 //	 531	 1700
{ WN, AC, JA, JA, JA, TN, AC, TN, TN, WN, TN, AC, AC, AC, TN }, 	 //	 532	 1700
{ TN, JA, JA, JA, AC, TN, JA, ST, TN, AC, TN, JA, AC, AC, AC }, 	 //	 533	 1700
{ TN, SH, JA, JA, TN, TN, TN, TN, TN, AC, TN, TN, AC, AC, AC }, 	 //	 534	 1700
{ TN, TN, TN, AC, JA, TN, TN, AC, AC, TN, TN, TN, AC, AC, AC }, 	 //	 535	 1700
{ TN, TN, TN, AC, TN, TN, TN, AC, AC, ST, TN, TN, AC, AC, AC }, 	 //	 536	 1700
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, KN, TN, TN, AC, AC, QN }, 	 //	 537	 1700
{ TN, TN, TN, AC, LO, TN, TN, AC, AC, AC, TN, TN, AC, PF, AC }, 	 //	 538	 1700
{ TN, TN, TN, AC, ST, TN, TN, AC, AC, AC, TN, TN, AC, PF, KN }, 	 //	 539	 1700
{ TN, TN, TN, KN, LO, TN, TN, AC, AC, AC, TN, TN, AC, PF, AC }, 	 //	 540	 1700
{ TN, TN, JA, JA, AC, TN, TN, TN, TN, AC, TN, WN, AC, AC, AC }, 	 //	 541	 1700
{ TN, TN, TN, PF, QN, TN, TN, AC, AC, KN, TN, WN, AC, AC, AC }, 	 //	 542	 1700
{ TN, TN, TN, AC, AC, TN, TN, AC, AC, KN, TN, WN, AC, LO, QN }, 	 //	 543	 1700
{ TN, TN, TN, KN, AC, TN, TN, AC, AC, LO, TN, WN, AC, PF, AC }, 	 //	 544	 1700
{ TN, TN, JA, JA, JA, TN, WN, TN, TN, JA, TN, AC, AC, AC, WN }, 	 //	 545	 1700
{ TN, TN, TN, TN, CR, TN, WN, AC, WN, KN, TN, AC, AC, AC, KN }, 	 //	 546	 1700
{ TN, TN, TN, TN, KN, TN, WN, AC, WN, SK, TN, AC, AC, AC, QN }, 	 //	 547	 1700
{ TN, TN, TN, TN, JA, TN, WN, AC, WN, JA, TN, AC, AC, AC, JA }, 	 //	 548	 1700
{ TN, TN, TN, TN, AC, TN, WN, AC, WN, AC, TN, AC, AC, AC, SK }, 	 //	 549	 1700
{ TN, TN, TN, JA, TN, TN, WN, AC, TN, TN, TN, AC, AC, AC, TN }, 	 //	 550	 1700
{ TN, TN, TN, TN, SH, TN, WN, AC, AC, JA, TN, AC, AC, AC, JA }, 	 //	 551	 1700
{ TN, TN, TN, TN, JA, TN, WN, AC, AC, JA, TN, AC, AC, AC, WN }, 	 //	 552	 1700
{ TN, JA, JA, JA, KN, TN, TN, ST, TN, QN, TN, AC, AC, AC, PF }, 	 //	 553	 1700
{ TN, JA, TN, JA, AC, TN, TN, AC, TN, SK, TN, AC, AC, AC, KN }, 	 //	 554	 1700
{ TN, TN, TN, TN, KN, TN, AC, AC, WN, QN, TN, AC, AC, AC, PF }, 	 //	 555	 1700
{ TN, AC, JA, JA, JA, TN, PF, ST, TN, TN, TN, KN, AC, AC, AC }, 	 //	 556	 1700
{ TN, PF, JA, JA, JA, TN, KN, ST, TN, TN, TN, KN, AC, AC, AC }, 	 //	 557	 1700
{ TN, JA, JA, JA, AC, TN, JA, TN, TN, AC, ST, SH, AC, AC, AC }, 	 //	 558	 1700
{ TN, JA, JA, JA, LO, TN, SH, ST, TN, AC, ST, TN, AC, AC, AC }, 	 //	 559	 1700
{ TN, JA, JA, JA, QN, TN, SH, ST, TN, KN, ST, TN, AC, AC, AC }, 	 //	 560	 1700
{ TN, TN, JA, JA, QN, TN, TN, TN, TN, KN, ST, TN, AC, AC, AC }, 	 //	 561	 1700
{ TN, TN, TN, JA, TN, TN, TN, AC, TN, AC, ST, TN, AC, AC, AC }, 	 //	 562	 1700
{ TN, TN, JA, JA, QN, TN, TN, TN, TN, KN, ST, WN, AC, AC, AC }, 	 //	 563	 1700
{ TN, TN, TN, TN, QN, TN, TN, AC, WN, KN, ST, WN, AC, AC, AC }, 	 //	 564	 1700
{ TN, TN, TN, TN, JA, TN, TN, AC, AC, TN, ST, WN, AC, AC, AC }, 	 //	 565	 1700
{ TN, TN, TN, TN, KN, TN, TN, AC, AC, AC, ST, WN, AC, AC, LO }, 	 //	 566	 1700
{ TN, TN, TN, TN, AC, TN, WN, AC, WN, AC, ST, AC, AC, AC, CR }, 	 //	 567	 1700
{ TN, TN, TN, TN, QN, TN, WN, AC, WN, SH, ST, AC, AC, AC, JA }, 	 //	 568	 1700
{ TN, TN, TN, JA, JA, TN, WN, AC, TN, WN, ST, AC, AC, AC, TN }, 	 //	 569	 1700
{ TN, TN, TN, TN, QN, TN, WN, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 570	 1700
{ TN, JA, JA, JA, KN, TN, TN, ST, TN, SK, ST, AC, AC, AC, QN }, 	 //	 571	 1700
{ TN, JA, JA, JA, ST, TN, TN, ST, TN, AC, ST, AC, AC, AC, KN }, 	 //	 572	 1700
{ TN, JA, JA, JA, AC, TN, TN, ST, TN, SK, ST, AC, AC, AC, KN }, 	 //	 573	 1700
{ TN, TN, JA, JA, JA, TN, AC, TN, TN, WN, ST, AC, AC, AC, TN }, 	 //	 574	 1700
{ TN, TN, TN, TN, AC, TN, AC, AC, WN, AC, ST, AC, AC, AC, CR }, 	 //	 575	 1700
{ TN, TN, TN, TN, KN, TN, AC, AC, WN, SK, ST, AC, AC, AC, QN }, 	 //	 576	 1700
{ TN, AC, JA, JA, JA, ST, SH, ST, JA, JA, AC, AC, AC, JA, WN }, 	 //	 577	 1700
{ TN, AC, JA, SK, JA, ST, SH, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 578	 1700
{ TN, AC, JA, JA, QN, ST, SH, TN, JA, PF, AC, AC, AC, SH, JA }, 	 //	 579	 1700
{ TN, SH, JA, SK, QN, ST, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 580	 1700
{ TN, SH, JA, JA, JA, ST, AC, ST, JA, JA, AC, AC, AC, SH, WN }, 	 //	 581	 1700
{ TN, SH, JA, JA, JA, ST, AC, ST, JA, WN, AC, AC, AC, SH, TN }, 	 //	 582	 1700
{ TN, SH, JA, JA, JA, ST, AC, ST, JA, TN, AC, AC, AC, SH, AC }, 	 //	 583	 1700
{ TN, AC, JA, JA, QN, ST, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 584	 1700
{ TN, AC, JA, SK, SH, ST, AC, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 585	 1700
{ TN, AC, JA, JA, QN, ST, AC, TN, JA, SH, AC, AC, AC, SH, JA }, 	 //	 586	 1700
{ TN, JA, JA, JA, AC, ST, JA, ST, TN, AC, AC, SH, AC, AC, AC }, 	 //	 587	 1700
{ TN, JA, JA, JA, AC, ST, SH, ST, TN, LO, AC, TN, AC, AC, AC }, 	 //	 588	 1700
{ TN, TN, TN, JA, AC, ST, TN, AC, TN, LO, AC, TN, AC, AC, AC }, 	 //	 589	 1700
{ TN, TN, JA, JA, JA, ST, WN, ST, JA, WN, AC, AC, AC, SH, TN }, 	 //	 590	 1700
{ TN, TN, JA, JA, JA, ST, WN, ST, SH, JA, AC, AC, AC, TN, JA }, 	 //	 591	 1700
{ TN, TN, JA, ST, JA, ST, WN, ST, JA, JA, AC, AC, AC, TN, JA }, 	 //	 592	 1700
{ TN, TN, JA, SK, QN, ST, WN, TN, JA, PF, AC, AC, AC, JA, JA }, 	 //	 593	 1700
{ TN, TN, TN, SH, PF, ST, WN, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 594	 1700
{ TN, TN, TN, TN, KN, ST, WN, AC, TN, KN, AC, AC, AC, TN, CR }, 	 //	 595	 1700
{ TN, TN, TN, TN, AC, ST, WN, AC, TN, AC, AC, AC, AC, WN, AC }, 	 //	 596	 1700
{ TN, KN, JA, JA, JA, ST, QN, ST, TN, TN, AC, ST, AC, AC, AC }, 	 //	 597	 1700
{ TN, JA, JA, JA, KN, ST, TN, ST, JA, SK, AC, AC, AC, JA, QN }, 	 //	 598	 1700
{ TN, JA, JA, JA, ST, ST, TN, ST, JA, AC, AC, AC, AC, JA, KN }, 	 //	 599	 1700
{ TN, JA, JA, JA, KN, ST, TN, ST, JA, KN, AC, AC, AC, SH, CR }, 	 //	 600	 1700
{ TN, JA, JA, JA, AC, ST, TN, ST, SH, AC, AC, AC, AC, TN, AC }, 	 //	 601	 1700
{ TN, JA, JA, JA, AC, ST, TN, ST, SH, AC, AC, AC, AC, TN, AC }, 	 //	 602	 1700
{ TN, JA, JA, SK, QN, ST, TN, TN, JA, PF, AC, AC, AC, JA, JA }, 	 //	 603	 1700
{ TN, JA, JA, JA, AC, ST, TN, TN, JA, AC, AC, AC, AC, JA, CR }, 	 //	 604	 1700
{ TN, JA, JA, JA, SK, ST, TN, TN, JA, KN, AC, AC, AC, JA, KN }, 	 //	 605	 1700
{ TN, JA, JA, JA, AC, ST, TN, TN, JA, LO, AC, AC, AC, SH, AC }, 	 //	 606	 1700
{ TN, JA, JA, JA, WN, ST, TN, TN, JA, TN, AC, AC, AC, SH, TN }, 	 //	 607	 1700
{ TN, JA, JA, SH, WN, ST, TN, TN, TN, TN, AC, AC, AC, TN, TN }, 	 //	 608	 1700
{ TN, JA, JA, SH, TN, ST, TN, TN, TN, TN, AC, AC, AC, TN, ST }, 	 //	 609	 1700
{ TN, JA, TN, SH, PF, ST, TN, AC, TN, JA, AC, AC, AC, TN, TN }, 	 //	 610	 1700
{ TN, TN, JA, JA, SH, ST, AC, ST, JA, JA, AC, AC, AC, SH, JA }, 	 //	 611	 1700
{ TN, TN, JA, JA, JA, ST, AC, ST, SH, WN, AC, AC, AC, TN, TN }, 	 //	 612	 1700
{ TN, TN, JA, SK, SH, ST, AC, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 613	 1700
{ TN, TN, JA, JA, QN, ST, AC, TN, JA, SH, AC, AC, AC, JA, JA }, 	 //	 614	 1700
{ TN, TN, JA, JA, JA, ST, AC, TN, SH, JA, AC, AC, AC, TN, JA }, 	 //	 615	 1700
{ TN, TN, JA, JA, JA, ST, AC, TN, SH, WN, AC, AC, AC, TN, TN }, 	 //	 616	 1700
{ TN, AC, JA, JA, QN, ST, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 617	 1700
{ TN, AC, JA, JA, JA, ST, AC, ST, JA, TN, AC, AC, AC, SH, AC }, 	 //	 618	 1700
{ TN, AC, JA, ST, QN, ST, AC, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 619	 1700
{ TN, AC, JA, SK, JA, ST, AC, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 620	 1700
{ TN, AC, JA, JA, SH, ST, AC, TN, JA, JA, AC, AC, AC, SH, JA }, 	 //	 621	 1700
{ TN, QN, JA, JA, JA, ST, KN, TN, SH, JA, AC, AC, AC, TN, JA }, 	 //	 622	 1700
{ TN, QN, TN, TN, TN, ST, KN, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 623	 1700
{ ST, SH, JA, JA, JA, AC, AC, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 624	 1700
{ ST, JA, JA, JA, AC, AC, JA, ST, TN, AC, KN, JA, AC, AC, AC }, 	 //	 625	 1700
{ ST, JA, JA, JA, TN, AC, JA, ST, TN, AC, KN, JA, AC, AC, AC }, 	 //	 626	 1700
{ ST, JA, JA, JA, TN, AC, JA, ST, TN, ST, KN, SH, AC, AC, AC }, 	 //	 627	 1700
{ AC, SH, JA, SK, SH, KN, AC, ST, JA, JA, QN, AC, AC, JA, JA }, 	 //	 628	 1700
{ AC, SH, JA, JA, JA, KN, AC, ST, JA, TN, QN, AC, AC, JA, AC }, 	 //	 629	 1700
{ AC, AC, JA, JA, JA, KN, AC, ST, JA, JA, QN, AC, AC, JA, WN }, 	 //	 630	 1700
{ AC, AC, JA, JA, JA, KN, AC, TN, JA, JA, QN, AC, AC, SH, WN }, 	 //	 631	 1700
{ AC, AC, JA, ST, QN, KN, AC, TN, JA, SH, QN, AC, AC, TN, JA }, 	 //	 632	 1700
{ AC, AC, TN, TN, TN, KN, AC, AC, TN, TN, QN, AC, AC, WN, TN }, 	 //	 633	 1700
{ AC, AC, JA, JA, JA, KN, AC, ST, TN, JA, QN, LO, AC, AC, WN }, 	 //	 634	 1700
{ AC, AC, JA, SK, QN, KN, AC, TN, JA, SH, QN, LO, AC, JA, JA }, 	 //	 635	 1700
{ AC, AC, JA, SK, SH, KN, AC, TN, JA, JA, QN, LO, AC, JA, JA }, 	 //	 636	 1700
{ AC, JA, JA, JA, AC, KN, JA, TN, TN, AC, QN, JA, AC, AC, AC }, 	 //	 637	 1700
{ AC, WN, JA, JA, QN, KN, AC, ST, JA, SH, QN, KN, AC, SH, JA }, 	 //	 638	 1700
{ AC, WN, JA, JA, SH, KN, AC, TN, JA, JA, QN, KN, AC, JA, JA }, 	 //	 639	 1700
{ AC, TN, JA, JA, JA, KN, AC, ST, SH, JA, QN, AC, AC, TN, WN }, 	 //	 640	 1700
{ AC, TN, JA, JA, SH, KN, AC, TN, JA, JA, QN, AC, AC, SH, JA }, 	 //	 641	 1700
{ AC, TN, TN, TN, TN, KN, AC, AC, TN, ST, QN, AC, AC, TN, AC }, 	 //	 642	 1700
{ AC, AC, JA, SK, QN, KN, AC, ST, JA, SH, QN, AC, AC, JA, JA }, 	 //	 643	 1700
{ AC, AC, JA, ST, QN, KN, AC, TN, JA, SH, QN, AC, AC, TN, JA }, 	 //	 644	 1700
{ AC, AC, JA, JA, JA, KN, AC, TN, JA, WN, QN, PF, AC, JA, TN }, 	 //	 645	 1700
{ AC, AC, JA, JA, JA, KN, AC, TN, SH, JA, QN, PF, AC, TN, JA }, 	 //	 646	 1700
{ AC, AC, JA, JA, JA, KN, AC, TN, SH, WN, QN, PF, AC, TN, TN }, 	 //	 647	 1700
{ AC, AC, JA, ST, SH, KN, AC, TN, JA, JA, QN, PF, AC, TN, JA }, 	 //	 648	 1700
{ AC, KN, JA, JA, QN, KN, AC, ST, JA, PF, QN, SH, AC, JA, JA }, 	 //	 649	 1700
{ AC, KN, JA, JA, JA, KN, AC, TN, JA, TN, QN, SH, AC, JA, AC }, 	 //	 650	 1700
{ AC, KN, JA, JA, JA, KN, AC, TN, JA, WN, QN, SH, AC, SH, TN }, 	 //	 651	 1700
{ KN, AC, JA, JA, JA, QN, SH, ST, TN, JA, PF, AC, AC, AC, WN }, 	 //	 652	 1700
{ KN, AC, JA, JA, JA, QN, SH, ST, TN, WN, PF, AC, AC, AC, TN }, 	 //	 653	 1700
{ KN, SH, JA, JA, JA, QN, AC, ST, TN, JA, PF, AC, AC, AC, WN }, 	 //	 654	 1700
{ KN, SH, JA, JA, JA, QN, AC, TN, TN, WN, PF, AC, AC, AC, TN }, 	 //	 655	 1700
{ KN, KN, JA, JA, JA, QN, KN, ST, TN, TN, PF, ST, AC, AC, AC }, 	 //	 656	 1700
{ KN, QN, JA, JA, JA, QN, QN, ST, TN, TN, PF, QN, AC, AC, AC }, 	 //	 657	 1700
{ KN, JA, JA, JA, TN, QN, JA, TN, TN, AC, PF, JA, AC, AC, AC }, 	 //	 658	 1700
{ KN, JA, JA, JA, AC, QN, JA, ST, TN, AC, PF, SH, AC, AC, AC }, 	 //	 659	 1700
{ KN, JA, JA, JA, TN, QN, JA, ST, TN, ST, PF, SH, AC, AC, AC }, 	 //	 660	 1700
{ KN, JA, JA, JA, TN, QN, JA, ST, TN, AC, PF, SH, AC, AC, AC }, 	 //	 661	 1700
{ KN, JA, JA, JA, LO, QN, SH, TN, TN, AC, PF, TN, AC, AC, AC }, 	 //	 662	 1700
{ KN, JA, JA, JA, QN, QN, SH, TN, TN, KN, PF, TN, AC, AC, AC }, 	 //	 663	 1700
{ KN, TN, JA, JA, JA, QN, TN, ST, TN, TN, PF, TN, AC, AC, AC }, 	 //	 664	 1700
{ KN, JA, JA, JA, AC, QN, TN, ST, TN, AC, PF, AC, AC, AC, SK }, 	 //	 665	 1700
{ KN, PF, JA, JA, JA, QN, KN, ST, TN, TN, PF, KN, AC, AC, AC }, 	 //	 666	 1700
{ QN, SH, JA, JA, JA, PF, AC, TN, TN, WN, JA, AC, AC, AC, TN }, 	 //	 667	 1700
{ QN, AC, JA, JA, JA, PF, AC, TN, TN, JA, JA, AC, AC, AC, JA }, 	 //	 668	 1700
{ QN, SK, JA, AC, AC, PF, JA, ST, PF, AC, JA, JA, AC, AC, AC }, 	 //	 669	 1700
{ QN, SK, JA, JA, AC, PF, JA, ST, TN, AC, JA, JA, AC, AC, AC }, 	 //	 670	 1700
{ QN, SK, JA, AC, AC, PF, JA, ST, AC, SK, JA, JA, AC, PF, KN }, 	 //	 671	 1700
{ QN, SK, JA, QN, QN, PF, JA, ST, KN, KN, JA, JA, AC, AC, AC }, 	 //	 672	 1700
{ QN, SK, JA, KN, AC, PF, JA, ST, AC, KN, JA, JA, AC, PF, QN }, 	 //	 673	 1700
{ QN, SK, JA, PF, JA, PF, JA, TN, AC, TN, JA, JA, AC, AC, AC }, 	 //	 674	 1700
{ QN, SK, JA, AC, TN, PF, JA, TN, AC, ST, JA, JA, AC, AC, AC }, 	 //	 675	 1700
{ QN, SK, JA, TN, JA, PF, JA, TN, AC, TN, JA, JA, AC, AC, AC }, 	 //	 676	 1700
{ QN, SK, JA, QN, AC, PF, JA, TN, KN, AC, JA, JA, AC, AC, AC }, 	 //	 677	 1700
{ QN, JA, JA, PF, AC, PF, JA, ST, AC, AC, JA, JA, AC, AC, SK }, 	 //	 678	 1700
{ QN, JA, JA, TN, LO, PF, JA, ST, WN, AC, JA, JA, AC, AC, AC }, 	 //	 679	 1700
{ QN, JA, JA, WN, AC, PF, JA, ST, AC, KN, JA, JA, AC, KN, QN }, 	 //	 680	 1700
{ QN, JA, JA, TN, AC, PF, JA, ST, AC, AC, JA, JA, AC, AC, CR }, 	 //	 681	 1700
{ QN, JA, JA, AC, AC, PF, JA, ST, AC, KN, JA, JA, AC, AC, QN }, 	 //	 682	 1700
{ QN, JA, JA, PF, AC, PF, JA, TN, AC, AC, JA, JA, AC, AC, SK }, 	 //	 683	 1700
{ QN, JA, JA, AC, TN, PF, JA, TN, AC, AC, JA, JA, AC, AC, AC }, 	 //	 684	 1700
{ QN, JA, JA, AC, AC, PF, JA, TN, AC, AC, JA, JA, AC, LO, AC }, 	 //	 685	 1700
{ QN, JA, JA, TN, AC, PF, JA, TN, AC, SK, JA, JA, AC, AC, KN }, 	 //	 686	 1700
{ QN, JA, JA, TN, QN, PF, JA, TN, AC, KN, JA, JA, AC, AC, AC }, 	 //	 687	 1700
{ QN, JA, JA, KN, AC, PF, JA, TN, AC, AC, JA, JA, AC, PF, CR }, 	 //	 688	 1700
{ QN, JA, JA, KN, AC, PF, JA, TN, AC, AC, JA, JA, AC, PF, SK }, 	 //	 689	 1700
{ QN, JA, JA, PF, TN, PF, JA, ST, AC, ST, JA, SH, AC, AC, AC }, 	 //	 690	 1700
{ QN, JA, JA, TN, JA, PF, JA, ST, WN, TN, JA, SH, AC, AC, AC }, 	 //	 691	 1700
{ QN, JA, JA, TN, TN, PF, JA, ST, WN, AC, JA, SH, AC, AC, AC }, 	 //	 692	 1700
{ QN, JA, JA, AC, AC, PF, JA, ST, AC, AC, JA, SH, AC, AC, CR }, 	 //	 693	 1700
{ QN, JA, JA, AC, TN, PF, JA, ST, AC, ST, JA, SH, AC, AC, AC }, 	 //	 694	 1700
{ QN, JA, JA, AC, TN, PF, JA, ST, AC, AC, JA, SH, AC, AC, AC }, 	 //	 695	 1700
{ QN, JA, JA, AC, AC, PF, JA, ST, AC, AC, JA, SH, AC, PF, AC }, 	 //	 696	 1700
{ QN, JA, JA, QN, JA, PF, JA, TN, KN, TN, JA, SH, AC, AC, AC }, 	 //	 697	 1700
{ QN, QN, QN, QN, AC, PF, ST, SK, QN, KN, JA, JA, JA, SK, QN }, 	 //	 698	 1700
{ QN, ST, JA, AC, TN, PF, JA, ST, AC, AC, JA, TN, AC, AC, AC }, 	 //	 699	 1700
{ QN, ST, JA, TN, LO, PF, JA, ST, AC, AC, JA, TN, AC, AC, AC }, 	 //	 700	 1700
{ QN, ST, JA, AC, AC, PF, JA, ST, AC, AC, JA, TN, AC, PF, AC }, 	 //	 701	 1700
{ QN, ST, JA, QN, LO, PF, JA, ST, KN, AC, JA, TN, AC, AC, AC }, 	 //	 702	 1700
{ QN, ST, JA, AC, AC, PF, JA, TN, PF, AC, JA, TN, AC, AC, AC }, 	 //	 703	 1700
{ QN, ST, JA, AC, JA, PF, JA, TN, PF, TN, JA, TN, AC, AC, AC }, 	 //	 704	 1700
{ QN, ST, JA, PF, TN, PF, JA, TN, AC, ST, JA, TN, AC, AC, AC }, 	 //	 705	 1700
{ QN, ST, JA, PF, AC, PF, JA, TN, AC, KN, JA, TN, AC, AC, QN }, 	 //	 706	 1700
{ QN, ST, JA, KN, AC, PF, JA, TN, AC, SK, JA, TN, AC, PF, KN }, 	 //	 707	 1700
{ QN, JA, JA, JA, QN, PF, TN, ST, TN, SH, JA, AC, AC, AC, JA }, 	 //	 708	 1700
{ QN, JA, JA, JA, AC, PF, TN, ST, TN, KN, JA, AC, AC, AC, QN }, 	 //	 709	 1700
{ QN, JA, TN, JA, WN, PF, TN, AC, TN, TN, JA, AC, AC, AC, TN }, 	 //	 710	 1700
{ QN, AC, JA, JA, JA, PF, AC, ST, TN, JA, JA, AC, AC, AC, JA }, 	 //	 711	 1700
{ QN, AC, JA, JA, JA, PF, AC, TN, TN, WN, JA, AC, AC, AC, TN }, 	 //	 712	 1700
{ PF, AC, JA, JA, JA, JA, SH, TN, TN, JA, TN, AC, AC, AC, WN }, 	 //	 713	 1700
{ PF, SK, JA, JA, JA, JA, JA, ST, TN, TN, TN, JA, AC, AC, AC }, 	 //	 714	 1700
{ PF, JA, JA, JA, TN, JA, SH, TN, TN, ST, TN, TN, AC, AC, AC }, 	 //	 715	 1700
{ PF, SH, TN, TN, TN, JA, TN, AC, WN, ST, TN, TN, AC, AC, AC }, 	 //	 716	 1700
{ PF, SH, TN, JA, TN, JA, TN, AC, TN, ST, TN, TN, AC, AC, AC }, 	 //	 717	 1700
{ PF, TN, JA, JA, JA, JA, TN, ST, TN, TN, TN, TN, AC, AC, AC }, 	 //	 718	 1700
{ PF, TN, TN, JA, TN, JA, TN, AC, TN, ST, TN, TN, AC, AC, AC }, 	 //	 719	 1700
{ PF, TN, TN, TN, AC, JA, TN, AC, WN, AC, TN, WN, AC, AC, AC }, 	 //	 720	 1700
{ PF, TN, TN, JA, JA, JA, TN, AC, TN, TN, TN, WN, AC, AC, AC }, 	 //	 721	 1700
{ PF, TN, JA, JA, JA, JA, WN, TN, TN, WN, TN, AC, AC, AC, TN }, 	 //	 722	 1700
{ PF, AC, JA, JA, JA, JA, KN, ST, TN, TN, TN, QN, AC, AC, AC }, 	 //	 723	 1700
{ PF, AC, JA, JA, JA, JA, AC, ST, TN, TN, TN, PF, AC, AC, AC }, 	 //	 724	 1700
{ PF, QN, JA, JA, JA, JA, KN, TN, TN, WN, TN, AC, AC, AC, TN }, 	 //	 725	 1700
{ JA, AC, JA, ST, JA, TN, SH, ST, JA, JA, AC, AC, AC, TN, JA }, 	 //	 726	 1700
{ JA, SH, JA, SK, QN, TN, AC, ST, JA, SH, AC, AC, AC, JA, JA }, 	 //	 727	 1700
{ JA, SH, JA, JA, JA, TN, AC, TN, JA, WN, AC, AC, AC, JA, TN }, 	 //	 728	 1700
{ JA, SH, JA, ST, JA, TN, AC, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 729	 1700
{ JA, AC, JA, SK, JA, TN, AC, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 730	 1700
{ JA, AC, JA, JA, JA, TN, AC, ST, JA, TN, AC, AC, AC, SH, AC }, 	 //	 731	 1700
{ JA, AC, JA, ST, QN, TN, AC, TN, JA, PF, AC, AC, AC, TN, JA }, 	 //	 732	 1700
{ JA, JA, JA, AC, AC, TN, JA, ST, PF, AC, AC, JA, AC, AC, AC }, 	 //	 733	 1700
{ JA, JA, JA, PF, TN, TN, JA, ST, AC, ST, AC, JA, AC, AC, AC }, 	 //	 734	 1700
{ JA, JA, JA, PF, AC, TN, JA, ST, AC, AC, AC, JA, AC, AC, SK }, 	 //	 735	 1700
{ JA, JA, JA, TN, LO, TN, JA, ST, WN, AC, AC, JA, AC, AC, AC }, 	 //	 736	 1700
{ JA, JA, JA, WN, AC, TN, JA, ST, AC, AC, AC, JA, AC, KN, AC }, 	 //	 737	 1700
{ JA, JA, JA, WN, AC, TN, JA, ST, AC, SK, AC, JA, AC, KN, KN }, 	 //	 738	 1700
{ JA, JA, JA, TN, JA, TN, JA, ST, AC, TN, AC, JA, AC, AC, AC }, 	 //	 739	 1700
{ JA, JA, JA, AC, AC, TN, JA, ST, AC, AC, AC, JA, AC, AC, SK }, 	 //	 740	 1700
{ JA, JA, JA, PF, AC, TN, JA, TN, AC, SK, AC, JA, AC, AC, KN }, 	 //	 741	 1700
{ JA, JA, JA, WN, AC, TN, JA, TN, AC, LO, AC, JA, AC, KN, AC }, 	 //	 742	 1700
{ JA, JA, JA, WN, AC, TN, JA, TN, AC, AC, AC, JA, AC, KN, CR }, 	 //	 743	 1700
{ JA, JA, JA, WN, AC, TN, JA, TN, AC, AC, AC, JA, AC, KN, AC }, 	 //	 744	 1700
{ JA, JA, JA, TN, TN, TN, JA, TN, AC, AC, AC, JA, AC, AC, AC }, 	 //	 745	 1700
{ JA, JA, JA, QN, LO, TN, JA, TN, KN, AC, AC, JA, AC, AC, AC }, 	 //	 746	 1700
{ JA, JA, JA, PF, AC, TN, JA, ST, AC, AC, AC, SH, AC, AC, CR }, 	 //	 747	 1700
{ JA, JA, JA, WN, AC, TN, JA, ST, AC, AC, AC, SH, AC, KN, SK }, 	 //	 748	 1700
{ JA, JA, JA, AC, AC, TN, JA, ST, AC, AC, AC, SH, AC, AC, CR }, 	 //	 749	 1700
{ JA, JA, JA, AC, QN, TN, JA, ST, AC, KN, AC, SH, AC, AC, AC }, 	 //	 750	 1700
{ JA, JA, JA, QN, AC, TN, JA, ST, KN, AC, AC, SH, AC, AC, AC }, 	 //	 751	 1700
{ JA, JA, JA, TN, AC, TN, JA, TN, WN, AC, AC, SH, AC, AC, AC }, 	 //	 752	 1700
{ JA, JA, JA, AC, AC, TN, JA, TN, AC, SK, AC, SH, AC, AC, KN }, 	 //	 753	 1700
{ JA, JA, JA, KN, AC, TN, JA, TN, AC, AC, AC, SH, AC, PF, AC }, 	 //	 754	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, KN, AC, TN, AC, AC, QN }, 	 //	 755	 1700
{ JA, JA, JA, AC, QN, TN, SH, ST, AC, KN, AC, TN, AC, AC, AC }, 	 //	 756	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, KN, AC, TN, AC, LO, QN }, 	 //	 757	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, SK, AC, TN, AC, AC, KN }, 	 //	 758	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, AC, AC, TN, AC, PF, AC }, 	 //	 759	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, AC, AC, TN, AC, PF, CR }, 	 //	 760	 1700
{ JA, JA, JA, AC, AC, TN, SH, ST, AC, AC, AC, TN, AC, PF, SK }, 	 //	 761	 1700
{ JA, JA, JA, QN, TN, TN, SH, ST, KN, ST, AC, TN, AC, AC, AC }, 	 //	 762	 1700
{ JA, JA, JA, QN, JA, TN, SH, ST, KN, TN, AC, TN, AC, AC, AC }, 	 //	 763	 1700
{ JA, JA, JA, KN, AC, TN, SH, ST, AC, SK, AC, TN, AC, PF, KN }, 	 //	 764	 1700
{ JA, JA, JA, AC, LO, TN, SH, TN, PF, AC, AC, TN, AC, AC, AC }, 	 //	 765	 1700
{ JA, JA, JA, PF, TN, TN, SH, TN, AC, AC, AC, TN, AC, AC, AC }, 	 //	 766	 1700
{ JA, JA, JA, TN, QN, TN, SH, TN, WN, KN, AC, TN, AC, AC, AC }, 	 //	 767	 1700
{ JA, JA, JA, WN, AC, TN, SH, TN, AC, SK, AC, TN, AC, KN, KN }, 	 //	 768	 1700
{ JA, TN, JA, JA, TN, TN, TN, TN, TN, AC, AC, WN, AC, AC, AC }, 	 //	 769	 1700
{ JA, TN, JA, ST, JA, TN, WN, ST, JA, JA, AC, AC, AC, TN, JA }, 	 //	 770	 1700
{ JA, TN, JA, JA, QN, TN, WN, TN, JA, PF, AC, AC, AC, JA, JA }, 	 //	 771	 1700
{ JA, TN, JA, JA, QN, TN, WN, TN, JA, PF, AC, AC, AC, SH, JA }, 	 //	 772	 1700
{ JA, TN, TN, TN, JA, TN, WN, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 773	 1700
{ JA, TN, TN, TN, WN, TN, WN, AC, TN, TN, AC, AC, AC, WN, TN }, 	 //	 774	 1700
{ JA, QN, JA, JA, JA, TN, ST, ST, TN, TN, AC, JA, AC, AC, AC }, 	 //	 775	 1700
{ JA, JA, JA, AC, CR, TN, TN, ST, AC, QN, AC, AC, AC, LO, KN }, 	 //	 776	 1700
{ JA, JA, JA, AC, SK, TN, TN, ST, LO, QN, AC, AC, AC, KN, QN }, 	 //	 777	 1700
{ JA, JA, JA, AC, JA, TN, TN, ST, LO, JA, AC, AC, AC, KN, JA }, 	 //	 778	 1700
{ JA, JA, JA, AC, QN, TN, TN, ST, LO, PF, AC, AC, AC, KN, JA }, 	 //	 779	 1700
{ JA, JA, JA, LO, TN, TN, TN, ST, KN, ST, AC, AC, AC, KN, AC }, 	 //	 780	 1700
{ JA, JA, JA, LO, SK, TN, TN, ST, KN, KN, AC, AC, AC, KN, KN }, 	 //	 781	 1700
{ JA, JA, JA, KN, TN, TN, TN, ST, KN, TN, AC, AC, AC, KN, ST }, 	 //	 782	 1700
{ JA, JA, JA, KN, KN, TN, TN, ST, KN, KN, AC, AC, AC, WN, KN }, 	 //	 783	 1700
{ JA, JA, JA, KN, SH, TN, TN, ST, KN, JA, AC, AC, AC, WN, JA }, 	 //	 784	 1700
{ JA, JA, JA, KN, TN, TN, TN, ST, KN, TN, AC, AC, AC, WN, TN }, 	 //	 785	 1700
{ JA, JA, JA, KN, SK, TN, TN, ST, WN, QN, AC, AC, AC, QN, QN }, 	 //	 786	 1700
{ JA, JA, JA, KN, QN, TN, TN, ST, WN, QN, AC, AC, AC, QN, SH }, 	 //	 787	 1700
{ JA, JA, JA, KN, AC, TN, TN, ST, WN, KN, AC, AC, AC, QN, QN }, 	 //	 788	 1700
{ JA, JA, JA, KN, KN, TN, TN, ST, WN, QN, AC, AC, AC, QN, PF }, 	 //	 789	 1700
{ JA, JA, JA, KN, KN, TN, TN, ST, WN, KN, AC, AC, AC, QN, CR }, 	 //	 790	 1700
{ JA, JA, JA, QN, TN, TN, TN, ST, QN, ST, AC, AC, AC, QN, AC }, 	 //	 791	 1700
{ JA, JA, JA, QN, JA, TN, TN, ST, QN, JA, AC, AC, AC, SK, JA }, 	 //	 792	 1700
{ JA, JA, JA, QN, JA, TN, TN, ST, QN, JA, AC, AC, AC, SK, WN }, 	 //	 793	 1700
{ JA, JA, JA, QN, JA, TN, TN, ST, SK, JA, AC, AC, AC, JA, WN }, 	 //	 794	 1700
{ JA, JA, JA, SK, QN, TN, TN, ST, JA, QN, AC, AC, AC, JA, QN }, 	 //	 795	 1700
{ JA, JA, JA, SK, QN, TN, TN, ST, JA, KN, AC, AC, AC, JA, AC }, 	 //	 796	 1700
{ JA, JA, JA, SK, KN, TN, TN, ST, JA, AC, AC, AC, AC, JA, LO }, 	 //	 797	 1700
{ JA, JA, JA, SH, AC, TN, TN, ST, TN, LO, AC, AC, AC, TN, AC }, 	 //	 798	 1700
{ JA, JA, JA, SH, AC, TN, TN, ST, TN, AC, AC, AC, AC, TN, CR }, 	 //	 799	 1700
{ JA, JA, JA, TN, LO, TN, TN, ST, TN, AC, AC, AC, AC, TN, AC }, 	 //	 800	 1700
{ JA, JA, JA, TN, WN, TN, TN, ST, TN, TN, AC, AC, AC, WN, TN }, 	 //	 801	 1700
{ JA, JA, JA, WN, LO, TN, TN, ST, AC, AC, AC, AC, AC, KN, AC }, 	 //	 802	 1700
{ JA, JA, JA, AC, AC, TN, TN, ST, KN, AC, AC, AC, AC, QN, AC }, 	 //	 803	 1700
{ JA, JA, JA, KN, LO, TN, TN, ST, QN, AC, AC, AC, AC, ST, AC }, 	 //	 804	 1700
{ JA, JA, JA, KN, WN, TN, TN, ST, QN, TN, AC, AC, AC, ST, TN }, 	 //	 805	 1700
{ JA, JA, JA, KN, CR, TN, TN, ST, QN, QN, AC, AC, AC, ST, KN }, 	 //	 806	 1700
{ JA, JA, JA, ST, AC, TN, TN, ST, JA, AC, AC, AC, AC, TN, CR }, 	 //	 807	 1700
{ JA, JA, JA, ST, SK, TN, TN, ST, JA, QN, AC, AC, AC, TN, QN }, 	 //	 808	 1700
{ JA, JA, JA, PF, JA, TN, TN, ST, KN, WN, AC, AC, AC, KN, TN }, 	 //	 809	 1700
{ JA, JA, JA, PF, WN, TN, TN, ST, KN, TN, AC, AC, AC, KN, TN }, 	 //	 810	 1700
{ JA, JA, JA, PF, KN, TN, TN, ST, KN, AC, AC, AC, AC, KN, LO }, 	 //	 811	 1700
{ JA, JA, JA, KN, TN, TN, TN, ST, KN, TN, AC, AC, AC, KN, TN }, 	 //	 812	 1700
{ JA, JA, JA, KN, TN, TN, TN, ST, KN, ST, AC, AC, AC, KN, AC }, 	 //	 813	 1700
{ JA, JA, JA, KN, PF, TN, TN, ST, KN, JA, AC, AC, AC, KN, TN }, 	 //	 814	 1700
{ JA, JA, JA, KN, TN, TN, TN, ST, KN, ST, AC, AC, AC, SK, AC }, 	 //	 815	 1700
{ JA, JA, JA, KN, KN, TN, TN, ST, KN, KN, AC, AC, AC, SK, KN }, 	 //	 816	 1700
{ JA, JA, JA, KN, QN, TN, TN, ST, KN, KN, AC, AC, AC, SK, AC }, 	 //	 817	 1700
{ JA, JA, JA, KN, AC, TN, TN, ST, SK, KN, AC, AC, AC, QN, QN }, 	 //	 818	 1700
{ JA, JA, JA, KN, CR, TN, TN, ST, SK, QN, AC, AC, AC, QN, KN }, 	 //	 819	 1700
{ JA, JA, JA, SK, AC, TN, TN, ST, QN, AC, AC, AC, AC, KN, CR }, 	 //	 820	 1700
{ JA, JA, JA, SK, TN, TN, TN, ST, QN, AC, AC, AC, AC, KN, AC }, 	 //	 821	 1700
{ JA, AC, JA, JA, SH, TN, AC, ST, JA, JA, AC, AC, AC, SH, JA }, 	 //	 822	 1700
{ JA, AC, JA, SK, JA, TN, AC, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 823	 1700
{ JA, AC, JA, JA, JA, TN, AC, TN, SH, JA, AC, AC, AC, TN, JA }, 	 //	 824	 1700
{ JA, PF, JA, JA, JA, TN, KN, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 825	 1700
{ JA, QN, JA, JA, JA, TN, KN, ST, SH, WN, AC, AC, AC, TN, TN }, 	 //	 826	 1700
{ JA, QN, JA, ST, QN, TN, KN, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 827	 1700
{ TN, AC, JA, SK, SH, AC, SH, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 828	 1700
{ TN, AC, JA, JA, JA, AC, SH, ST, JA, TN, AC, AC, AC, JA, AC }, 	 //	 829	 1700
{ TN, AC, JA, ST, QN, AC, SH, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 830	 1700
{ TN, AC, JA, JA, JA, AC, SH, TN, JA, WN, AC, AC, AC, JA, TN }, 	 //	 831	 1700
{ TN, SH, JA, JA, SH, AC, AC, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 832	 1700
{ TN, SH, JA, JA, QN, AC, AC, ST, JA, SH, AC, AC, AC, SH, JA }, 	 //	 833	 1700
{ TN, AC, JA, JA, QN, AC, AC, ST, JA, SH, AC, AC, AC, SH, JA }, 	 //	 834	 1700
{ TN, AC, JA, ST, QN, AC, AC, ST, JA, PF, AC, AC, AC, TN, JA }, 	 //	 835	 1700
{ TN, AC, JA, JA, QN, AC, AC, TN, JA, SH, AC, AC, AC, JA, JA }, 	 //	 836	 1700
{ TN, AC, JA, JA, QN, AC, AC, TN, JA, PF, AC, AC, AC, JA, JA }, 	 //	 837	 1700
{ TN, AC, JA, JA, JA, AC, AC, TN, JA, TN, AC, AC, AC, JA, AC }, 	 //	 838	 1700
{ TN, AC, TN, TN, TN, AC, AC, AC, TN, TN, AC, LO, AC, WN, TN }, 	 //	 839	 1700
{ TN, JA, JA, JA, QN, AC, JA, ST, TN, KN, AC, SH, AC, AC, AC }, 	 //	 840	 1700
{ TN, JA, JA, JA, AC, AC, SH, ST, TN, LO, AC, TN, AC, AC, AC }, 	 //	 841	 1700
{ TN, JA, JA, JA, AC, AC, SH, TN, TN, AC, AC, TN, AC, AC, AC }, 	 //	 842	 1700
{ TN, TN, TN, JA, QN, AC, TN, AC, TN, KN, AC, TN, AC, AC, AC }, 	 //	 843	 1700
{ TN, TN, JA, ST, SH, AC, WN, ST, JA, JA, AC, AC, AC, TN, JA }, 	 //	 844	 1700
{ TN, TN, JA, JA, JA, AC, WN, TN, SH, JA, AC, AC, AC, TN, WN }, 	 //	 845	 1700
{ TN, TN, TN, SH, WN, AC, WN, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 846	 1700
{ TN, TN, TN, TN, AC, AC, WN, AC, TN, AC, AC, AC, AC, TN, AC }, 	 //	 847	 1700
{ TN, TN, TN, TN, AC, AC, WN, AC, TN, AC, AC, AC, AC, WN, CR }, 	 //	 848	 1700
{ TN, TN, TN, TN, KN, AC, WN, AC, TN, AC, AC, AC, AC, WN, LO }, 	 //	 849	 1700
{ TN, JA, JA, JA, QN, AC, TN, ST, JA, QN, AC, AC, AC, JA, SH }, 	 //	 850	 1700
{ TN, JA, JA, JA, CR, AC, TN, ST, JA, QN, AC, AC, AC, JA, KN }, 	 //	 851	 1700
{ TN, JA, JA, JA, QN, AC, TN, ST, SH, QN, AC, AC, AC, TN, SH }, 	 //	 852	 1700
{ TN, JA, JA, JA, TN, AC, TN, ST, SH, TN, AC, AC, AC, TN, ST }, 	 //	 853	 1700
{ TN, JA, JA, JA, ST, AC, TN, ST, SH, AC, AC, AC, AC, TN, KN }, 	 //	 854	 1700
{ TN, JA, JA, JA, CR, AC, TN, TN, JA, KN, AC, AC, AC, SH, KN }, 	 //	 855	 1700
{ TN, JA, JA, JA, AC, AC, TN, TN, JA, KN, AC, AC, AC, SH, QN }, 	 //	 856	 1700
{ TN, JA, JA, JA, SK, AC, TN, TN, JA, KN, AC, AC, AC, SH, KN }, 	 //	 857	 1700
{ TN, JA, JA, JA, CR, AC, TN, TN, JA, QN, AC, AC, AC, SH, KN }, 	 //	 858	 1700
{ TN, JA, JA, JA, KN, AC, TN, TN, SH, KN, AC, AC, AC, TN, KN }, 	 //	 859	 1700
{ TN, JA, JA, JA, KN, AC, TN, TN, SH, KN, AC, AC, AC, TN, SK }, 	 //	 860	 1700
{ TN, JA, JA, JA, TN, AC, TN, TN, SH, TN, AC, AC, AC, TN, TN }, 	 //	 861	 1700
{ TN, JA, JA, JA, KN, AC, TN, TN, SH, QN, AC, AC, AC, TN, PF }, 	 //	 862	 1700
{ TN, JA, TN, TN, JA, AC, TN, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 863	 1700
{ TN, JA, TN, TN, WN, AC, TN, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 864	 1700
{ TN, JA, TN, TN, TN, AC, TN, AC, TN, ST, AC, AC, AC, TN, AC }, 	 //	 865	 1700
{ TN, TN, JA, SK, QN, AC, AC, TN, JA, SH, AC, AC, AC, JA, JA }, 	 //	 866	 1700
{ TN, TN, JA, ST, SH, AC, AC, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 867	 1700
{ TN, TN, JA, ST, JA, AC, AC, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 868	 1700
{ TN, AC, JA, JA, JA, AC, AC, TN, SH, TN, AC, AC, AC, TN, AC }, 	 //	 869	 1700
{ TN, AC, JA, JA, JA, AC, PF, ST, TN, TN, AC, KN, AC, AC, AC }, 	 //	 870	 1700
{ TN, KN, JA, JA, JA, AC, SK, ST, TN, TN, AC, QN, AC, AC, AC }, 	 //	 871	 1700
{ AC, AC, JA, SK, QN, AC, SH, ST, JA, PF, AC, AC, AC, JA, JA }, 	 //	 872	 1700
{ AC, AC, JA, JA, QN, AC, SH, ST, JA, SH, AC, AC, AC, SH, JA }, 	 //	 873	 1700
{ AC, AC, JA, JA, QN, AC, AC, TN, JA, PF, AC, LO, AC, SH, JA }, 	 //	 874	 1700
{ AC, JA, JA, JA, AC, AC, JA, TN, TN, LO, AC, SH, AC, AC, AC }, 	 //	 875	 1700
{ AC, JA, JA, JA, AC, AC, SH, ST, TN, AC, AC, TN, AC, AC, AC }, 	 //	 876	 1700
{ AC, TN, JA, JA, JA, AC, WN, ST, SH, JA, AC, AC, AC, TN, JA }, 	 //	 877	 1700
{ AC, TN, TN, TN, JA, AC, WN, AC, TN, WN, AC, AC, AC, TN, TN }, 	 //	 878	 1700
{ AC, TN, TN, TN, TN, AC, WN, AC, TN, TN, AC, AC, AC, TN, ST }, 	 //	 879	 1700
{ AC, TN, TN, TN, TN, AC, WN, AC, TN, ST, AC, AC, AC, WN, AC }, 	 //	 880	 1700
{ AC, WN, JA, SK, SH, AC, AC, ST, JA, JA, AC, KN, AC, JA, JA }, 	 //	 881	 1700
{ AC, WN, JA, JA, JA, AC, AC, ST, JA, TN, AC, KN, AC, SH, AC }, 	 //	 882	 1700
{ AC, KN, JA, JA, JA, AC, QN, ST, TN, TN, AC, ST, AC, AC, AC }, 	 //	 883	 1700
{ AC, JA, JA, JA, SK, AC, TN, ST, JA, QN, AC, AC, AC, JA, QN }, 	 //	 884	 1700
{ AC, JA, JA, JA, QN, AC, TN, ST, JA, QN, AC, AC, AC, JA, SH }, 	 //	 885	 1700
{ AC, JA, JA, JA, KN, AC, TN, ST, JA, AC, AC, AC, AC, JA, LO }, 	 //	 886	 1700
{ AC, JA, JA, JA, AC, AC, TN, ST, SH, AC, AC, AC, AC, TN, AC }, 	 //	 887	 1700
{ AC, JA, JA, SK, JA, AC, TN, TN, JA, JA, AC, AC, AC, JA, JA }, 	 //	 888	 1700
{ AC, JA, JA, JA, AC, AC, TN, TN, JA, AC, AC, AC, AC, JA, CR }, 	 //	 889	 1700
{ AC, JA, JA, JA, KN, AC, TN, TN, JA, SK, AC, AC, AC, SH, QN }, 	 //	 890	 1700
{ AC, JA, JA, JA, SK, AC, TN, TN, JA, QN, AC, AC, AC, SH, QN }, 	 //	 891	 1700
{ AC, JA, JA, JA, SK, AC, TN, TN, SH, QN, AC, AC, AC, TN, QN }, 	 //	 892	 1700
{ AC, JA, JA, ST, JA, AC, TN, TN, JA, JA, AC, AC, AC, TN, JA }, 	 //	 893	 1700
{ AC, JA, TN, TN, WN, AC, TN, AC, TN, TN, AC, AC, AC, TN, TN }, 	 //	 894	 1700
{ AC, AC, JA, SK, SH, AC, AC, ST, JA, JA, AC, PF, AC, JA, JA }, 	 //	 895	 1700
{ AC, AC, JA, JA, JA, AC, AC, ST, SH, JA, AC, PF, AC, TN, WN }, 	 //	 896	 1700
{ AC, AC, JA, JA, JA, AC, AC, TN, JA, JA, AC, PF, AC, SH, WN }, 	 //	 897	 1700
{ AC, AC, JA, JA, JA, AC, AC, TN, SH, WN, AC, PF, AC, TN, TN }, 	 //	 898	 1700
{ AC, QN, JA, SK, JA, AC, KN, ST, JA, JA, AC, AC, AC, JA, JA }, 	 //	 899	 1700
{ AC, QN, JA, JA, QN, AC, KN, ST, JA, SH, AC, AC, AC, SH, JA }, 	 //	 900	 1700
{ AC, QN, JA, JA, JA, AC, KN, TN, JA, TN, AC, AC, AC, SH, AC }, 	 //	 901	 1700
{ AC, KN, JA, ST, SH, AC, AC, ST, JA, JA, AC, SH, AC, TN, JA }, 	 //	 902	 1700
{ AC, KN, JA, SK, JA, AC, AC, TN, JA, JA, AC, SH, AC, JA, JA }, 	 //	 903	 1700
{ AC, KN, JA, ST, QN, AC, AC, TN, JA, SH, AC, SH, AC, TN, JA }, 	 //	 904	 1700
{ AC, SH, JA, JA, JA, AC, AC, ST, JA, WN, SK, AC, AC, SH, TN }, 	 //	 905	 1700
{ AC, SH, JA, JA, JA, AC, AC, TN, JA, JA, SK, AC, AC, SH, WN }, 	 //	 906	 1700
{ AC, SH, JA, JA, JA, AC, AC, TN, JA, TN, SK, AC, AC, SH, AC }, 	 //	 907	 1700
{ AC, SH, JA, JA, JA, AC, AC, TN, SH, WN, SK, AC, AC, TN, TN }, 	 //	 908	 1700
{ AC, SH, JA, ST, QN, AC, AC, TN, JA, SH, SK, AC, AC, TN, JA }, 	 //	 909	 1700
{ AC, AC, JA, JA, JA, AC, AC, TN, JA, WN, SK, AC, AC, SH, TN }, 	 //	 910	 1700
{ AC, AC, JA, JA, JA, AC, AC, ST, TN, JA, SK, LO, AC, AC, JA }, 	 //	 911	 1700
{ AC, AC, JA, SK, QN, AC, AC, TN, JA, PF, SK, LO, AC, JA, JA }, 	 //	 912	 1700
{ AC, TN, TN, TN, TN, AC, WN, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 913	 1700
{ AC, WN, JA, ST, QN, AC, AC, TN, JA, SH, SK, KN, AC, TN, JA }, 	 //	 914	 1700
{ AC, AC, JA, JA, JA, AC, KN, ST, TN, TN, SK, QN, AC, AC, AC }, 	 //	 915	 1700
{ AC, QN, JA, JA, JA, AC, ST, ST, TN, TN, SK, JA, AC, AC, AC }, 	 //	 916	 1700
{ AC, JA, JA, JA, KN, AC, TN, ST, TN, KN, SK, AC, AC, AC, KN }, 	 //	 917	 1700
{ AC, TN, JA, JA, QN, AC, AC, ST, JA, PF, SK, AC, AC, JA, JA }, 	 //	 918	 1700
{ AC, AC, JA, SK, QN, AC, AC, ST, JA, SH, SK, AC, AC, JA, JA }, 	 //	 919	 1700
{ AC, AC, JA, JA, QN, AC, AC, ST, JA, PF, SK, AC, AC, SH, JA }, 	 //	 920	 1700
{ AC, AC, JA, JA, JA, AC, AC, ST, SH, WN, SK, AC, AC, TN, TN }, 	 //	 921	 1700
{ AC, AC, JA, JA, JA, AC, AC, TN, JA, JA, SK, AC, AC, SH, WN }, 	 //	 922	 1700
{ AC, AC, JA, SK, QN, AC, AC, ST, JA, PF, SK, PF, AC, JA, JA }, 	 //	 923	 1700
{ AC, AC, JA, SK, JA, AC, AC, TN, JA, JA, SK, PF, AC, JA, JA }, 	 //	 924	 1700
{ AC, SK, JA, JA, JA, AC, QN, ST, TN, TN, SK, KN, AC, AC, AC }, 	 //	 925	 1700
{ AC, KN, JA, JA, SH, AC, AC, ST, JA, JA, SK, SH, AC, SH, JA }, 	 //	 926	 1700
{ AC, KN, JA, JA, JA, AC, AC, ST, SH, JA, SK, SH, AC, TN, WN }, 	 //	 927	 1700
{ AC, KN, JA, ST, SH, AC, AC, TN, JA, JA, SK, SH, AC, TN, JA }, 	 //	 928	 1700
{ AC, SH, JA, JA, SH, SK, AC, ST, JA, JA, KN, AC, AC, SH, JA }, 	 //	 929	 1700
{ AC, SH, JA, JA, JA, SK, AC, TN, SH, TN, KN, AC, AC, TN, AC }, 	 //	 930	 1700
{ AC, AC, JA, JA, JA, SK, AC, ST, JA, WN, KN, AC, AC, SH, TN }, 	 //	 931	 1700
{ AC, AC, JA, SK, QN, SK, AC, ST, JA, PF, KN, LO, AC, JA, JA }, 	 //	 932	 1700
{ AC, AC, JA, JA, QN, SK, AC, ST, JA, SH, KN, LO, AC, JA, JA }, 	 //	 933	 1700
{ AC, AC, JA, JA, QN, SK, AC, ST, JA, PF, KN, LO, AC, JA, JA }, 	 //	 934	 1700
{ AC, AC, JA, SK, JA, SK, AC, TN, JA, JA, KN, LO, AC, JA, JA }, 	 //	 935	 1700
{ AC, AC, JA, JA, JA, SK, AC, TN, TN, WN, KN, LO, AC, AC, TN }, 	 //	 936	 1700
{ AC, AC, TN, TN, TN, SK, AC, AC, TN, TN, KN, LO, AC, WN, TN }, 	 //	 937	 1700
{ AC, JA, JA, JA, AC, SK, JA, TN, TN, AC, KN, SH, AC, AC, AC }, 	 //	 938	 1700
{ AC, TN, TN, TN, TN, SK, TN, AC, WN, AC, KN, TN, AC, AC, AC }, 	 //	 939	 1700
{ AC, TN, TN, TN, TN, SK, TN, AC, WN, AC, KN, WN, AC, AC, AC }, 	 //	 940	 1700
{ AC, TN, JA, JA, JA, SK, WN, TN, TN, JA, KN, AC, AC, AC, WN }, 	 //	 941	 1700
{ AC, WN, JA, JA, JA, SK, AC, ST, JA, TN, KN, KN, AC, SH, AC }, 	 //	 942	 1700
{ AC, WN, JA, JA, QN, SK, AC, TN, JA, SH, KN, KN, AC, JA, JA }, 	 //	 943	 1700
{ AC, WN, JA, JA, JA, SK, AC, TN, JA, TN, KN, KN, AC, JA, AC }, 	 //	 944	 1700
{ AC, TN, JA, JA, JA, SK, AC, ST, SH, JA, KN, AC, AC, TN, WN }, 	 //	 945	 1700
{ AC, TN, JA, JA, SH, SK, AC, TN, JA, JA, KN, AC, AC, JA, JA }, 	 //	 946	 1700
{ AC, TN, JA, JA, JA, SK, AC, TN, SH, JA, KN, AC, AC, TN, JA }, 	 //	 947	 1700
{ AC, AC, JA, JA, JA, SK, AC, TN, JA, WN, KN, AC, AC, SH, TN }, 	 //	 948	 1700
{ AC, AC, JA, ST, QN, SK, AC, TN, JA, SH, KN, AC, AC, TN, JA }, 	 //	 949	 1700
{ AC, AC, JA, ST, SH, SK, AC, TN, JA, JA, KN, AC, AC, TN, JA }, 	 //	 950	 1700
{ AC, AC, JA, JA, JA, SK, AC, ST, JA, TN, KN, PF, AC, SH, AC }, 	 //	 951	 1700
{ AC, AC, JA, JA, JA, SK, AC, TN, JA, WN, KN, PF, AC, SH, TN }, 	 //	 952	 1700
{ AC, AC, JA, JA, QN, SK, AC, TN, JA, PF, KN, PF, AC, SH, JA }, 	 //	 953	 1700
{ AC, KN, JA, JA, JA, SK, KN, ST, TN, TN, KN, KN, AC, AC, AC }, 	 //	 954	 1700
{ AC, KN, JA, JA, JA, SK, AC, ST, SH, WN, KN, SH, AC, TN, TN }, 	 //	 955	 1700
{ AC, KN, JA, SK, QN, SK, AC, TN, JA, PF, KN, SH, AC, JA, JA }, 	 //	 956	 1700
{ AC, KN, TN, TN, TN, SK, AC, AC, TN, TN, KN, SH, AC, TN, TN }, 	 //	 957	 1700
{ SK, SH, JA, JA, JA, KN, AC, ST, TN, WN, KN, AC, AC, AC, TN }, 	 //	 958	 1700
{ SK, AC, JA, JA, JA, KN, AC, ST, TN, JA, KN, AC, AC, AC, WN }, 	 //	 959	 1700
{ SK, JA, JA, JA, SK, KN, TN, ST, TN, QN, KN, AC, AC, AC, QN }, 	 //	 960	 1700
{ SK, JA, JA, JA, QN, KN, TN, ST, TN, PF, KN, AC, AC, AC, JA }, 	 //	 961	 1700
{ SK, JA, JA, JA, PF, KN, TN, ST, TN, JA, KN, AC, AC, AC, TN }, 	 //	 962	 1700
{ SK, JA, TN, JA, PF, KN, TN, AC, TN, JA, KN, AC, AC, AC, TN }, 	 //	 963	 1700
{ SK, TN, JA, JA, JA, KN, AC, ST, TN, JA, KN, AC, AC, AC, WN }, 	 //	 964	 1700
{ SK, AC, JA, JA, JA, KN, AC, ST, TN, TN, KN, PF, AC, AC, AC }, 	 //	 965	 1700
{ SK, PF, JA, JA, JA, KN, KN, ST, TN, TN, KN, KN, AC, AC, AC }, 	 //	 966	 1700
{ SK, QN, JA, JA, JA, KN, KN, ST, TN, JA, KN, AC, AC, AC, JA }, 	 //	 967	 1700
{ KN, SH, JA, JA, JA, KN, AC, ST, TN, WN, KN, AC, AC, AC, TN }, 	 //	 968	 1700
{ KN, SH, JA, JA, JA, KN, AC, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 969	 1700
{ KN, AC, JA, JA, JA, KN, AC, ST, TN, JA, KN, AC, AC, AC, WN }, 	 //	 970	 1700
{ KN, QN, JA, JA, JA, KN, QN, ST, TN, TN, KN, SK, AC, AC, AC }, 	 //	 971	 1700
{ KN, JA, JA, JA, TN, KN, JA, TN, TN, AC, KN, JA, AC, AC, AC }, 	 //	 972	 1700
{ KN, JA, JA, JA, QN, KN, JA, TN, TN, KN, KN, JA, AC, AC, AC }, 	 //	 973	 1700
{ KN, JA, JA, JA, AC, KN, SH, ST, TN, AC, KN, TN, AC, AC, AC }, 	 //	 974	 1700
{ KN, JA, JA, JA, AC, KN, SH, TN, TN, LO, KN, TN, AC, AC, AC }, 	 //	 975	 1700
{ KN, JA, JA, JA, TN, KN, SH, TN, TN, AC, KN, TN, AC, AC, AC }, 	 //	 976	 1700
{ KN, WN, JA, JA, JA, KN, AC, ST, TN, TN, KN, KN, AC, AC, AC }, 	 //	 977	 1700
{ KN, JA, TN, JA, JA, KN, TN, AC, TN, WN, KN, AC, AC, AC, TN }, 	 //	 978	 1700
{ KN, JA, TN, JA, TN, KN, TN, AC, TN, TN, KN, AC, AC, AC, TN }, 	 //	 979	 1700
{ KN, SH, JA, JA, JA, KN, AC, ST, TN, JA, WN, AC, AC, AC, JA }, 	 //	 980	 1700
{ KN, JA, JA, JA, AC, KN, JA, TN, TN, AC, WN, JA, AC, AC, AC }, 	 //	 981	 1700
{ KN, SH, JA, JA, JA, KN, TN, ST, TN, TN, WN, TN, AC, AC, AC }, 	 //	 982	 1700
{ KN, TN, JA, JA, JA, KN, WN, ST, TN, JA, WN, AC, AC, AC, JA }, 	 //	 983	 1700
{ KN, QN, JA, JA, JA, KN, ST, ST, TN, TN, WN, JA, AC, AC, AC }, 	 //	 984	 1700
{ KN, JA, JA, JA, KN, KN, TN, ST, TN, KN, WN, AC, AC, AC, KN }, 	 //	 985	 1700
{ KN, JA, JA, JA, QN, KN, TN, ST, TN, QN, WN, AC, AC, AC, QN }, 	 //	 986	 1700
{ KN, PF, JA, JA, JA, KN, KN, ST, TN, TN, WN, KN, AC, AC, AC }, 	 //	 987	 1700
{ KN, QN, JA, JA, JA, KN, KN, ST, TN, JA, WN, AC, AC, AC, JA }, 	 //	 988	 1700
{ KN, AC, JA, JA, JA, WN, AC, ST, TN, WN, QN, AC, AC, AC, TN }, 	 //	 989	 1700
{ KN, JA, JA, JA, TN, WN, JA, TN, TN, AC, QN, JA, AC, AC, AC }, 	 //	 990	 1700
{ KN, JA, JA, JA, AC, WN, JA, TN, TN, AC, QN, JA, AC, AC, AC }, 	 //	 991	 1700
{ KN, JA, JA, JA, AC, WN, SH, ST, TN, AC, QN, TN, AC, AC, AC }, 	 //	 992	 1700
{ KN, SH, JA, JA, JA, WN, TN, ST, TN, TN, QN, TN, AC, AC, AC }, 	 //	 993	 1700
{ KN, TN, JA, JA, JA, WN, TN, ST, TN, TN, QN, WN, AC, AC, AC }, 	 //	 994	 1700
{ KN, TN, JA, JA, JA, WN, WN, ST, TN, JA, QN, AC, AC, AC, WN }, 	 //	 995	 1700
{ KN, ST, JA, JA, JA, WN, JA, ST, TN, TN, QN, TN, AC, AC, AC }, 	 //	 996	 1700
{ WN, AC, JA, JA, JA, QN, SH, TN, TN, JA, KN, AC, AC, AC, JA }, 	 //	 997	 1700
{ WN, AC, JA, JA, JA, QN, SH, TN, TN, JA, KN, AC, AC, AC, WN }, 	 //	 998	 1700
{ WN, AC, JA, JA, JA, QN, AC, ST, TN, JA, KN, AC, AC, AC, WN }, 	 //	 999	 1700
{ WN, JA, JA, JA, AC, QN, JA, TN, TN, AC, KN, JA, AC, AC, AC }};	 //	 1000	 1700
