unsigned char L5_Outcome_5500[1000][15]={	 //	 0	 5500
{ AC, AC, AC, AC, AC, LO, SH, PF, KN, KN, AC, AC, QN, QN, QN }, 	 //	 1	 5500
{ AC, SH, SH, PF, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 2	 5500
{ AC, SH, SH, TN, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 3	 5500
{ AC, SH, SH, TN, JA, LO, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 4	 5500
{ AC, SH, SH, TN, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 5	 5500
{ AC, SH, SH, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 6	 5500
{ AC, SH, TN, PF, CR, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 7	 5500
{ AC, SH, TN, PF, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 8	 5500
{ AC, SH, TN, AC, KN, LO, AC, AC, AC, AC, AC, AC, AC, LO, LO }, 	 //	 9	 5500
{ AC, SH, TN, WN, ST, LO, AC, AC, AC, AC, AC, AC, AC, KN, KN }, 	 //	 10	 5500
{ AC, SH, TN, TN, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 11	 5500
{ AC, SH, TN, TN, WN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 12	 5500
{ AC, AC, SH, PF, SK, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 13	 5500
{ AC, AC, SH, TN, JA, LO, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 14	 5500
{ AC, AC, SH, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 15	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, PF, AC, SK }, 	 //	 16	 5500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, PF, PF, JA }, 	 //	 17	 5500
{ AC, AC, TN, PF, CR, LO, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 18	 5500
{ AC, AC, TN, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 19	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, QN, AC, AC, WN, PF, PF }, 	 //	 20	 5500
{ AC, AC, AC, AC, QN, LO, AC, AC, AC, QN, AC, LO, PF, LO, QN }, 	 //	 21	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, LO, WN, AC, SK }, 	 //	 22	 5500
{ AC, AC, AC, AC, SK, LO, AC, AC, AC, QN, AC, LO, WN, AC, QN }, 	 //	 23	 5500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, WN, AC, LO, WN, LO, TN }, 	 //	 24	 5500
{ AC, AC, AC, AC, PF, LO, AC, AC, AC, JA, AC, LO, WN, LO, TN }, 	 //	 25	 5500
{ AC, AC, AC, AC, SK, LO, AC, AC, AC, KN, AC, LO, WN, LO, KN }, 	 //	 26	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, LO, WN, PF, KN }, 	 //	 27	 5500
{ AC, AC, AC, AC, SK, LO, AC, AC, AC, KN, AC, LO, WN, PF, KN }, 	 //	 28	 5500
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, AC, AC, LO, WN, PF, CR }, 	 //	 29	 5500
{ AC, WN, AC, PF, KN, LO, AC, AC, AC, KN, AC, KN, AC, AC, KN }, 	 //	 30	 5500
{ AC, WN, AC, AC, KN, LO, AC, AC, AC, SK, AC, KN, AC, AC, QN }, 	 //	 31	 5500
{ AC, WN, AC, AC, JA, LO, AC, AC, AC, JA, AC, KN, AC, AC, JA }, 	 //	 32	 5500
{ AC, WN, AC, AC, QN, LO, AC, AC, AC, QN, AC, KN, AC, LO, QN }, 	 //	 33	 5500
{ AC, WN, AC, AC, QN, LO, AC, AC, AC, SH, AC, KN, AC, LO, JA }, 	 //	 34	 5500
{ AC, WN, AC, AC, TN, LO, AC, AC, AC, TN, AC, KN, AC, LO, TN }, 	 //	 35	 5500
{ AC, WN, AC, TN, QN, LO, AC, AC, AC, QN, AC, KN, AC, AC, QN }, 	 //	 36	 5500
{ AC, WN, AC, AC, SK, LO, AC, AC, AC, KN, AC, KN, AC, AC, KN }, 	 //	 37	 5500
{ AC, WN, AC, KN, QN, LO, AC, AC, AC, SH, AC, KN, AC, PF, JA }, 	 //	 38	 5500
{ AC, WN, AC, KN, JA, LO, AC, AC, AC, JA, AC, KN, AC, PF, WN }, 	 //	 39	 5500
{ AC, WN, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, PF, AC, CR }, 	 //	 40	 5500
{ AC, WN, AC, AC, AC, LO, AC, AC, AC, AC, AC, KN, PF, PF, SK }, 	 //	 41	 5500
{ AC, WN, TN, AC, TN, LO, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 42	 5500
{ AC, WN, AC, AC, QN, LO, AC, AC, AC, SH, AC, KN, AC, AC, JA }, 	 //	 43	 5500
{ AC, WN, AC, AC, TN, LO, AC, AC, AC, TN, AC, KN, AC, LO, TN }, 	 //	 44	 5500
{ AC, WN, AC, WN, CR, LO, AC, AC, AC, QN, AC, KN, AC, KN, KN }, 	 //	 45	 5500
{ AC, WN, AC, AC, SH, LO, AC, AC, AC, JA, AC, KN, AC, AC, JA }, 	 //	 46	 5500
{ AC, WN, AC, AC, SK, LO, AC, AC, AC, KN, AC, KN, AC, PF, KN }, 	 //	 47	 5500
{ AC, TN, SH, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 48	 5500
{ AC, TN, AC, AC, AC, LO, AC, AC, AC, AC, AC, AC, PF, AC, CR }, 	 //	 49	 5500
{ AC, TN, TN, PF, CR, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 50	 5500
{ AC, TN, TN, PF, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 51	 5500
{ AC, TN, TN, AC, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 52	 5500
{ AC, TN, TN, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, SH }, 	 //	 53	 5500
{ AC, AC, SH, AC, JA, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 54	 5500
{ AC, AC, SH, WN, TN, LO, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 55	 5500
{ AC, AC, SH, TN, KN, LO, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 56	 5500
{ AC, AC, SH, AC, SK, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 57	 5500
{ AC, AC, SH, AC, KN, LO, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 58	 5500
{ AC, AC, SH, KN, LO, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 59	 5500
{ AC, AC, SH, KN, TN, LO, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 60	 5500
{ AC, AC, AC, AC, TN, LO, AC, AC, AC, TN, AC, AC, PF, LO, ST }, 	 //	 61	 5500
{ AC, AC, AC, TN, ST, LO, AC, AC, AC, AC, AC, AC, PF, AC, KN }, 	 //	 62	 5500
{ AC, AC, AC, AC, JA, LO, AC, AC, AC, JA, AC, AC, PF, PF, WN }, 	 //	 63	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, AC, PF, PF, CR }, 	 //	 64	 5500
{ AC, AC, TN, PF, SH, LO, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 65	 5500
{ AC, AC, TN, PF, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 66	 5500
{ AC, AC, TN, PF, SK, LO, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 67	 5500
{ AC, AC, TN, AC, QN, LO, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 68	 5500
{ AC, AC, TN, AC, TN, LO, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 69	 5500
{ AC, AC, AC, PF, ST, LO, AC, AC, AC, AC, AC, AC, WN, AC, KN }, 	 //	 70	 5500
{ AC, AC, AC, AC, WN, LO, AC, AC, AC, TN, AC, AC, WN, LO, TN }, 	 //	 71	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, SK, AC, AC, WN, PF, QN }, 	 //	 72	 5500
{ AC, AC, AC, WN, AC, LO, AC, AC, AC, AC, AC, PF, PF, KN, CR }, 	 //	 73	 5500
{ AC, AC, AC, AC, KN, LO, AC, AC, AC, KN, AC, PF, PF, AC, SK }, 	 //	 74	 5500
{ AC, AC, AC, WN, ST, LO, AC, AC, AC, AC, AC, PF, WN, KN, KN }, 	 //	 75	 5500
{ AC, AC, AC, KN, AC, LO, AC, AC, AC, AC, AC, PF, WN, PF, SK }, 	 //	 76	 5500
{ AC, KN, AC, AC, KN, LO, AC, AC, AC, QN, AC, SH, AC, LO, PF }, 	 //	 77	 5500
{ AC, KN, AC, WN, KN, LO, AC, AC, AC, QN, AC, SH, AC, KN, PF }, 	 //	 78	 5500
{ AC, KN, AC, TN, KN, LO, AC, AC, AC, SK, AC, SH, AC, AC, QN }, 	 //	 79	 5500
{ AC, KN, AC, TN, JA, LO, AC, AC, AC, JA, AC, SH, AC, AC, WN }, 	 //	 80	 5500
{ AC, KN, AC, AC, KN, LO, AC, AC, AC, KN, AC, SH, AC, PF, KN }, 	 //	 81	 5500
{ AC, KN, AC, KN, QN, LO, AC, AC, AC, QN, AC, SH, AC, PF, QN }, 	 //	 82	 5500
{ AC, KN, AC, AC, KN, LO, AC, AC, AC, KN, AC, SH, AC, AC, KN }, 	 //	 83	 5500
{ AC, KN, AC, AC, KN, LO, AC, AC, AC, SK, AC, SH, AC, AC, QN }, 	 //	 84	 5500
{ AC, KN, AC, AC, SK, LO, AC, AC, AC, KN, AC, SH, AC, LO, KN }, 	 //	 85	 5500
{ AC, KN, AC, WN, KN, LO, AC, AC, AC, KN, AC, SH, AC, KN, KN }, 	 //	 86	 5500
{ AC, KN, AC, AC, JA, LO, AC, AC, AC, WN, AC, SH, AC, AC, TN }, 	 //	 87	 5500
{ AC, KN, AC, AC, QN, LO, AC, AC, AC, SH, AC, SH, AC, PF, JA }, 	 //	 88	 5500
{ AC, KN, AC, AC, KN, LO, AC, AC, AC, KN, AC, SH, AC, PF, KN }, 	 //	 89	 5500
{ AC, KN, AC, KN, KN, LO, AC, AC, AC, KN, AC, SH, AC, PF, KN }, 	 //	 90	 5500
{ AC, KN, AC, KN, PF, LO, AC, AC, AC, JA, AC, SH, AC, PF, TN }, 	 //	 91	 5500
{ LO, AC, AC, AC, AC, AC, SH, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 92	 5500
{ LO, SH, SH, WN, AC, AC, AC, AC, AC, SK, AC, AC, AC, KN, KN }, 	 //	 93	 5500
{ LO, SH, SH, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 94	 5500
{ LO, SH, TN, PF, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 95	 5500
{ LO, SH, TN, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 96	 5500
{ LO, SH, TN, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 97	 5500
{ LO, SH, TN, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 98	 5500
{ LO, AC, SH, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 99	 5500
{ LO, AC, SH, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 100	 5500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, LO, KN }, 	 //	 101	 5500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, PF, LO, QN }, 	 //	 102	 5500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, AC, PF, LO, QN }, 	 //	 103	 5500
{ LO, AC, TN, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 104	 5500
{ LO, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, WN, LO, ST }, 	 //	 105	 5500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, KN, AC, AC, WN, LO, KN }, 	 //	 106	 5500
{ LO, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, LO, AC, PF, SH }, 	 //	 107	 5500
{ LO, AC, AC, KN, KN, AC, AC, AC, AC, QN, AC, LO, AC, PF, PF }, 	 //	 108	 5500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, LO, PF, PF, JA }, 	 //	 109	 5500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, LO, PF, PF, TN }, 	 //	 110	 5500
{ LO, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, LO, AC, KN, KN }, 	 //	 111	 5500
{ LO, AC, AC, TN, SK, AC, AC, AC, AC, QN, AC, LO, AC, AC, QN }, 	 //	 112	 5500
{ LO, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, LO, AC, AC, ST }, 	 //	 113	 5500
{ LO, AC, AC, AC, SK, AC, AC, AC, AC, QN, AC, LO, WN, LO, QN }, 	 //	 114	 5500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, LO, WN, LO, WN }, 	 //	 115	 5500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, LO, WN, AC, JA }, 	 //	 116	 5500
{ LO, WN, AC, AC, KN, AC, AC, AC, AC, KN, AC, KN, AC, PF, SK }, 	 //	 117	 5500
{ LO, WN, AC, KN, SH, AC, AC, AC, AC, JA, AC, KN, AC, PF, JA }, 	 //	 118	 5500
{ LO, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, PF, AC, QN }, 	 //	 119	 5500
{ LO, WN, TN, TN, AC, AC, AC, AC, AC, LO, AC, KN, AC, AC, AC }, 	 //	 120	 5500
{ LO, WN, AC, AC, JA, AC, AC, AC, AC, JA, AC, KN, AC, LO, JA }, 	 //	 121	 5500
{ LO, WN, AC, WN, QN, AC, AC, AC, AC, QN, AC, KN, AC, KN, QN }, 	 //	 122	 5500
{ LO, WN, AC, TN, TN, AC, AC, AC, AC, TN, AC, KN, AC, AC, TN }, 	 //	 123	 5500
{ LO, WN, AC, AC, JA, AC, AC, AC, AC, WN, AC, KN, AC, AC, TN }, 	 //	 124	 5500
{ LO, TN, SH, PF, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 125	 5500
{ LO, TN, SH, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 126	 5500
{ LO, TN, SH, AC, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA }, 	 //	 127	 5500
{ LO, TN, SH, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 128	 5500
{ LO, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, PF, PF, KN }, 	 //	 129	 5500
{ LO, TN, TN, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN }, 	 //	 130	 5500
{ LO, AC, SH, PF, SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 131	 5500
{ LO, AC, SH, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 132	 5500
{ LO, AC, SH, WN, AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC }, 	 //	 133	 5500
{ LO, AC, SH, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 134	 5500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, LO, KN }, 	 //	 135	 5500
{ LO, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, PF, AC, QN }, 	 //	 136	 5500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, AC, CR }, 	 //	 137	 5500
{ LO, AC, TN, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 138	 5500
{ LO, AC, TN, WN, AC, AC, AC, AC, AC, LO, AC, AC, AC, KN, AC }, 	 //	 139	 5500
{ LO, AC, TN, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 140	 5500
{ LO, AC, TN, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 141	 5500
{ LO, AC, TN, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA }, 	 //	 142	 5500
{ LO, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, WN, LO, WN }, 	 //	 143	 5500
{ LO, AC, AC, PF, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC, SH }, 	 //	 144	 5500
{ LO, AC, AC, PF, JA, AC, AC, AC, AC, JA, AC, PF, AC, AC, WN }, 	 //	 145	 5500
{ LO, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, PF, AC, AC, CR }, 	 //	 146	 5500
{ LO, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, PF, AC, KN, KN }, 	 //	 147	 5500
{ LO, AC, AC, AC, CR, AC, AC, AC, AC, QN, AC, PF, PF, AC, KN }, 	 //	 148	 5500
{ LO, AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, PF, AC, AC, QN }, 	 //	 149	 5500
{ LO, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, PF, WN, LO, KN }, 	 //	 150	 5500
{ LO, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, PF, WN, AC, KN }, 	 //	 151	 5500
{ LO, KN, SH, AC, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 152	 5500
{ LO, KN, AC, PF, KN, AC, AC, AC, AC, SK, AC, SH, AC, AC, QN }, 	 //	 153	 5500
{ LO, KN, AC, TN, QN, AC, AC, AC, AC, SH, AC, SH, AC, AC, JA }, 	 //	 154	 5500
{ LO, KN, AC, KN, CR, AC, AC, AC, AC, QN, AC, SH, AC, PF, KN }, 	 //	 155	 5500
{ LO, KN, TN, TN, AC, AC, AC, AC, AC, LO, AC, SH, AC, AC, AC }, 	 //	 156	 5500
{ LO, KN, AC, PF, QN, AC, AC, AC, AC, QN, AC, SH, AC, AC, SH }, 	 //	 157	 5500
{ LO, KN, AC, TN, CR, AC, AC, AC, AC, QN, AC, SH, AC, AC, KN }, 	 //	 158	 5500
{ LO, KN, AC, AC, JA, AC, AC, AC, AC, JA, AC, SH, AC, PF, JA }, 	 //	 159	 5500
{ LO, KN, AC, KN, SH, AC, AC, AC, AC, JA, AC, SH, AC, PF, JA }, 	 //	 160	 5500
{ LO, KN, AC, KN, JA, AC, AC, AC, AC, JA, AC, SH, AC, PF, WN }, 	 //	 161	 5500
{ AC, SH, SH, WN, SH, AC, AC, AC, AC, JA, AC, AC, AC, KN, JA }, 	 //	 162	 5500
{ AC, SH, SH, WN, TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC }, 	 //	 163	 5500
{ AC, SH, TN, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, LO, QN }, 	 //	 164	 5500
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 165	 5500
{ AC, AC, SH, WN, QN, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN }, 	 //	 166	 5500
{ AC, AC, SH, KN, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 167	 5500
{ AC, AC, SH, KN, SH, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 168	 5500
{ AC, AC, AC, WN, AC, AC, AC, AC, AC, KN, AC, AC, PF, KN, QN }, 	 //	 169	 5500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, PF, AC, QN }, 	 //	 170	 5500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, AC, PF, AC, PF }, 	 //	 171	 5500
{ AC, AC, AC, TN, QN, AC, AC, AC, AC, PF, AC, AC, PF, AC, JA }, 	 //	 172	 5500
{ AC, AC, AC, KN, CR, AC, AC, AC, AC, KN, AC, AC, PF, PF, KN }, 	 //	 173	 5500
{ AC, AC, TN, WN, JA, AC, AC, AC, AC, JA, AC, AC, AC, KN, WN }, 	 //	 174	 5500
{ AC, AC, TN, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, PF, TN }, 	 //	 175	 5500
{ AC, AC, TN, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, PF, KN }, 	 //	 176	 5500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, WN, AC, AC, WN, KN, TN }, 	 //	 177	 5500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, AC, WN, KN, KN }, 	 //	 178	 5500
{ AC, AC, AC, WN, CR, AC, AC, AC, AC, QN, AC, AC, WN, KN, KN }, 	 //	 179	 5500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, KN, AC, AC, WN, AC, KN }, 	 //	 180	 5500
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, QN, AC, AC, WN, PF, QN }, 	 //	 181	 5500
{ AC, AC, AC, PF, WN, AC, AC, AC, AC, TN, AC, LO, PF, AC, TN }, 	 //	 182	 5500
{ AC, AC, AC, KN, SH, AC, AC, AC, AC, JA, AC, LO, PF, PF, JA }, 	 //	 183	 5500
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, LO, WN, PF, KN }, 	 //	 184	 5500
{ AC, AC, AC, KN, SH, AC, AC, AC, AC, JA, AC, LO, WN, PF, JA }, 	 //	 185	 5500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, PF, LO, QN }, 	 //	 186	 5500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, KN, AC, KN, PF, PF, QN }, 	 //	 187	 5500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, SK, AC, KN, WN, AC, KN }, 	 //	 188	 5500
{ AC, AC, AC, AC, AC, AC, KN, PF, KN, AC, AC, QN, QN, QN, AC }, 	 //	 189	 5500
{ AC, TN, SH, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN }, 	 //	 190	 5500
{ AC, TN, SH, KN, SH, AC, AC, AC, AC, JA, AC, AC, AC, PF, JA }, 	 //	 191	 5500
{ AC, TN, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 192	 5500
{ AC, TN, TN, KN, WN, AC, AC, AC, AC, TN, AC, AC, AC, PF, TN }, 	 //	 193	 5500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, WN, AC, KN }, 	 //	 194	 5500
{ AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC, AC, WN, PF, QN }, 	 //	 195	 5500
{ AC, AC, SH, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 196	 5500
{ AC, AC, SH, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN }, 	 //	 197	 5500
{ AC, AC, SH, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 198	 5500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC, ST }, 	 //	 199	 5500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, AC, PF, KN, KN }, 	 //	 200	 5500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, AC, PF, AC, PF }, 	 //	 201	 5500
{ AC, AC, TN, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, LO, AC }, 	 //	 202	 5500
{ AC, AC, TN, WN, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 203	 5500
{ AC, AC, TN, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, PF, AC }, 	 //	 204	 5500
{ AC, AC, TN, KN, TN, AC, AC, AC, AC, ST, AC, AC, AC, PF, AC }, 	 //	 205	 5500
{ AC, AC, TN, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 206	 5500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, PF, PF, KN, SK }, 	 //	 207	 5500
{ AC, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, PF, WN, AC, PF }, 	 //	 208	 5500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, KN, AC, PF, WN, AC, KN }, 	 //	 209	 5500
{ AC, KN, SH, AC, TN, AC, AC, AC, AC, ST, AC, SH, AC, AC, AC }, 	 //	 210	 5500
{ AC, KN, TN, AC, TN, AC, AC, AC, AC, ST, AC, SH, AC, AC, AC }, 	 //	 211	 5500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, SK, AC, SH, WN, AC, KN }, 	 //	 212	 5500
{ AC, AC, AC, AC, JA, AC, SH, AC, AC, TN, ST, AC, AC, AC, AC }, 	 //	 213	 5500
{ AC, SH, SH, TN, JA, AC, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 214	 5500
{ AC, SH, SH, TN, QN, AC, AC, AC, AC, PF, ST, AC, AC, AC, JA }, 	 //	 215	 5500
{ AC, SH, SH, AC, JA, AC, AC, AC, AC, JA, ST, AC, AC, AC, WN }, 	 //	 216	 5500
{ AC, SH, SH, AC, TN, AC, AC, AC, AC, TN, ST, AC, AC, AC, TN }, 	 //	 217	 5500
{ AC, SH, AC, WN, JA, AC, AC, AC, AC, JA, ST, AC, AC, KN, WN }, 	 //	 218	 5500
{ AC, SH, TN, AC, SK, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 219	 5500
{ AC, SH, TN, TN, QN, AC, AC, AC, AC, SH, ST, AC, AC, AC, JA }, 	 //	 220	 5500
{ AC, SH, AC, AC, JA, AC, AC, AC, AC, JA, ST, AC, AC, LO, JA }, 	 //	 221	 5500
{ AC, AC, AC, PF, JA, AC, AC, AC, AC, TN, ST, AC, PF, AC, AC }, 	 //	 222	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, AC, PF, AC, KN }, 	 //	 223	 5500
{ AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, ST, AC, PF, AC, KN }, 	 //	 224	 5500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, TN, ST, AC, PF, KN, AC }, 	 //	 225	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, ST, AC, PF, AC, SH }, 	 //	 226	 5500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, LO, ST, AC, PF, PF, AC }, 	 //	 227	 5500
{ AC, AC, TN, TN, SH, AC, AC, AC, AC, JA, ST, AC, AC, AC, JA }, 	 //	 228	 5500
{ AC, AC, TN, AC, CR, AC, AC, AC, AC, QN, ST, AC, AC, AC, KN }, 	 //	 229	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, AC, WN, AC, KN }, 	 //	 230	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, ST, LO, PF, AC, JA }, 	 //	 231	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, LO, PF, LO, SK }, 	 //	 232	 5500
{ AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, ST, LO, PF, LO, QN }, 	 //	 233	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, QN, ST, LO, PF, PF, KN }, 	 //	 234	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, ST, LO, WN, AC, TN }, 	 //	 235	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, ST, LO, WN, LO, TN }, 	 //	 236	 5500
{ AC, AC, AC, AC, SK, AC, AC, AC, AC, KN, ST, LO, WN, LO, KN }, 	 //	 237	 5500
{ AC, WN, AC, PF, CR, AC, AC, AC, AC, KN, ST, KN, AC, AC, KN }, 	 //	 238	 5500
{ AC, WN, AC, AC, SH, AC, AC, AC, AC, JA, ST, KN, AC, LO, JA }, 	 //	 239	 5500
{ AC, WN, AC, TN, PF, AC, AC, AC, AC, JA, ST, KN, AC, AC, TN }, 	 //	 240	 5500
{ AC, WN, AC, AC, KN, AC, AC, AC, AC, KN, ST, KN, AC, AC, CR }, 	 //	 241	 5500
{ AC, WN, AC, AC, JA, AC, AC, AC, AC, JA, ST, KN, AC, LO, WN }, 	 //	 242	 5500
{ AC, WN, AC, AC, KN, AC, AC, AC, AC, KN, ST, KN, AC, LO, CR }, 	 //	 243	 5500
{ AC, WN, AC, TN, SK, AC, AC, AC, AC, QN, ST, KN, AC, AC, QN }, 	 //	 244	 5500
{ AC, WN, AC, AC, CR, AC, AC, AC, AC, QN, ST, KN, AC, AC, KN }, 	 //	 245	 5500
{ AC, WN, AC, KN, CR, AC, AC, AC, AC, QN, ST, KN, AC, PF, KN }, 	 //	 246	 5500
{ AC, WN, AC, AC, AC, AC, AC, AC, AC, LO, ST, KN, WN, LO, AC }, 	 //	 247	 5500
{ AC, TN, SH, PF, SK, AC, AC, AC, AC, QN, ST, AC, AC, AC, QN }, 	 //	 248	 5500
{ AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, LO, KN }, 	 //	 249	 5500
{ AC, TN, AC, WN, JA, AC, AC, AC, AC, JA, ST, AC, AC, KN, WN }, 	 //	 250	 5500
{ AC, TN, AC, WN, QN, AC, AC, AC, AC, QN, ST, AC, AC, KN, QN }, 	 //	 251	 5500
{ AC, TN, AC, WN, SH, AC, AC, AC, AC, JA, ST, AC, AC, KN, JA }, 	 //	 252	 5500
{ AC, AC, SH, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 253	 5500
{ AC, AC, SH, AC, CR, AC, AC, AC, AC, KN, ST, AC, AC, AC, KN }, 	 //	 254	 5500
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 255	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, AC, PF, AC, SK }, 	 //	 256	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, AC, PF, AC, KN }, 	 //	 257	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, ST, AC, PF, AC, SH }, 	 //	 258	 5500
{ AC, AC, TN, PF, KN, AC, AC, AC, AC, KN, ST, AC, AC, AC, CR }, 	 //	 259	 5500
{ AC, AC, SH, PF, QN, AC, AC, AC, AC, KN, ST, PF, AC, AC, AC }, 	 //	 260	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, ST, PF, PF, AC, KN }, 	 //	 261	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, PF, PF, AC, KN }, 	 //	 262	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, ST, PF, PF, AC, JA }, 	 //	 263	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, ST, PF, WN, AC, KN }, 	 //	 264	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, ST, PF, WN, AC, JA }, 	 //	 265	 5500
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, ST, PF, WN, LO, TN }, 	 //	 266	 5500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, LO, ST, PF, WN, AC, AC }, 	 //	 267	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, ST, PF, WN, AC, JA }, 	 //	 268	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, ST, PF, WN, PF, WN }, 	 //	 269	 5500
{ AC, KN, AC, PF, KN, AC, AC, AC, AC, KN, ST, SH, AC, AC, KN }, 	 //	 270	 5500
{ AC, KN, AC, PF, KN, AC, AC, AC, AC, KN, ST, SH, AC, AC, SK }, 	 //	 271	 5500
{ AC, KN, AC, AC, WN, AC, AC, AC, AC, TN, ST, SH, AC, LO, TN }, 	 //	 272	 5500
{ AC, KN, AC, WN, TN, AC, AC, AC, AC, TN, ST, SH, AC, KN, ST }, 	 //	 273	 5500
{ AC, KN, AC, TN, CR, AC, AC, AC, AC, KN, ST, SH, AC, AC, KN }, 	 //	 274	 5500
{ AC, KN, AC, TN, JA, AC, AC, AC, AC, WN, ST, SH, AC, AC, TN }, 	 //	 275	 5500
{ AC, KN, AC, AC, QN, AC, AC, AC, AC, QN, ST, SH, AC, PF, QN }, 	 //	 276	 5500
{ AC, KN, AC, AC, JA, AC, AC, AC, AC, JA, ST, SH, AC, PF, JA }, 	 //	 277	 5500
{ AC, KN, AC, AC, KN, AC, AC, AC, AC, KN, ST, SH, AC, PF, CR }, 	 //	 278	 5500
{ AC, KN, AC, KN, KN, AC, AC, AC, AC, KN, ST, SH, AC, PF, KN }, 	 //	 279	 5500
{ AC, KN, TN, TN, QN, AC, AC, AC, AC, KN, ST, SH, AC, AC, AC }, 	 //	 280	 5500
{ AC, KN, AC, PF, QN, AC, AC, AC, AC, SH, ST, SH, AC, AC, JA }, 	 //	 281	 5500
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, TN, ST, SH, AC, LO, ST }, 	 //	 282	 5500
{ AC, KN, AC, AC, TN, AC, AC, AC, AC, TN, ST, SH, AC, AC, ST }, 	 //	 283	 5500
{ AC, AC, AC, AC, JA, ST, SH, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 284	 5500
{ AC, SH, SH, AC, ST, ST, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 285	 5500
{ AC, SH, AC, AC, TN, ST, AC, AC, AC, ST, KN, AC, AC, LO, AC }, 	 //	 286	 5500
{ AC, SH, AC, KN, KN, ST, AC, AC, AC, AC, KN, AC, AC, PF, LO }, 	 //	 287	 5500
{ AC, SH, TN, TN, ST, ST, AC, AC, AC, AC, KN, AC, AC, AC, KN }, 	 //	 288	 5500
{ AC, SH, TN, TN, KN, ST, AC, AC, AC, AC, KN, AC, AC, AC, LO }, 	 //	 289	 5500
{ AC, AC, SH, TN, TN, ST, AC, AC, AC, ST, KN, AC, AC, AC, AC }, 	 //	 290	 5500
{ AC, AC, AC, AC, TN, ST, AC, AC, AC, ST, KN, AC, PF, LO, AC }, 	 //	 291	 5500
{ AC, AC, AC, AC, JA, ST, AC, AC, AC, TN, KN, LO, PF, AC, AC }, 	 //	 292	 5500
{ AC, AC, AC, AC, ST, ST, AC, AC, AC, AC, KN, LO, PF, LO, KN }, 	 //	 293	 5500
{ AC, AC, AC, WN, AC, ST, AC, AC, AC, AC, KN, LO, PF, KN, AC }, 	 //	 294	 5500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, KN, KN, LO, WN, PF, AC }, 	 //	 295	 5500
{ AC, WN, AC, KN, JA, ST, AC, AC, AC, TN, KN, KN, AC, PF, AC }, 	 //	 296	 5500
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, PF, LO, AC }, 	 //	 297	 5500
{ AC, WN, AC, AC, KN, ST, AC, AC, AC, AC, KN, KN, AC, AC, LO }, 	 //	 298	 5500
{ AC, WN, AC, WN, TN, ST, AC, AC, AC, ST, KN, KN, AC, KN, AC }, 	 //	 299	 5500
{ AC, WN, AC, AC, AC, ST, AC, AC, AC, AC, KN, KN, WN, AC, AC }, 	 //	 300	 5500
{ AC, TN, AC, AC, QN, ST, AC, AC, AC, KN, KN, AC, AC, PF, AC }, 	 //	 301	 5500
{ AC, AC, AC, KN, TN, ST, AC, AC, AC, AC, KN, AC, PF, PF, AC }, 	 //	 302	 5500
{ AC, AC, TN, PF, JA, ST, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 303	 5500
{ AC, AC, TN, TN, JA, ST, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 304	 5500
{ AC, AC, AC, TN, TN, ST, AC, AC, AC, AC, KN, AC, WN, AC, AC }, 	 //	 305	 5500
{ AC, AC, AC, AC, JA, ST, AC, AC, AC, TN, KN, PF, PF, AC, AC }, 	 //	 306	 5500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, KN, KN, PF, WN, LO, AC }, 	 //	 307	 5500
{ AC, AC, AC, AC, QN, ST, AC, AC, AC, KN, KN, PF, WN, AC, AC }, 	 //	 308	 5500
{ AC, KN, AC, WN, KN, ST, AC, AC, AC, AC, KN, SH, AC, KN, LO }, 	 //	 309	 5500
{ AC, KN, AC, KN, TN, ST, AC, AC, AC, ST, KN, SH, AC, PF, AC }, 	 //	 310	 5500
{ ST, SH, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, LO, AC }, 	 //	 311	 5500
{ ST, AC, SH, PF, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 312	 5500
{ ST, AC, SH, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 313	 5500
{ ST, AC, TN, PF, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 314	 5500
{ ST, WN, AC, AC, TN, KN, AC, AC, AC, AC, KN, KN, AC, LO, AC }, 	 //	 315	 5500
{ ST, TN, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 316	 5500
{ ST, TN, SH, AC, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 317	 5500
{ ST, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, WN, AC, AC }, 	 //	 318	 5500
{ ST, AC, TN, TN, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 319	 5500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, PF, PF, AC, SK }, 	 //	 320	 5500
{ ST, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, PF, PF, AC, AC }, 	 //	 321	 5500
{ ST, AC, AC, WN, AC, KN, AC, AC, AC, LO, KN, PF, AC, KN, AC }, 	 //	 322	 5500
{ ST, AC, AC, WN, AC, KN, AC, AC, AC, AC, KN, PF, AC, KN, SK }, 	 //	 323	 5500
{ ST, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, PF, WN, AC, AC }, 	 //	 324	 5500
{ ST, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, PF, WN, LO, SK }, 	 //	 325	 5500
{ KN, SH, SH, PF, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 326	 5500
{ KN, SH, SH, PF, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 327	 5500
{ KN, SH, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 328	 5500
{ KN, SH, SH, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 329	 5500
{ KN, SH, AC, KN, AC, KN, AC, AC, AC, LO, KN, AC, AC, PF, AC }, 	 //	 330	 5500
{ KN, AC, AC, WN, TN, KN, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 331	 5500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, AC, PF, LO, AC }, 	 //	 332	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, PF, PF, SK }, 	 //	 333	 5500
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, WN, PF, AC }, 	 //	 334	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, PF, AC, CR }, 	 //	 335	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, LO, WN, LO, CR }, 	 //	 336	 5500
{ KN, WN, AC, AC, TN, KN, AC, AC, AC, AC, KN, KN, AC, LO, AC }, 	 //	 337	 5500
{ KN, WN, AC, TN, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, CR }, 	 //	 338	 5500
{ KN, TN, AC, KN, LO, KN, AC, AC, AC, AC, KN, AC, AC, PF, AC }, 	 //	 339	 5500
{ KN, TN, TN, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 340	 5500
{ KN, AC, AC, KN, AC, KN, AC, AC, AC, LO, KN, AC, AC, PF, AC }, 	 //	 341	 5500
{ KN, AC, AC, WN, AC, KN, AC, AC, AC, AC, KN, PF, AC, KN, CR }, 	 //	 342	 5500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, PF, WN, AC, AC }, 	 //	 343	 5500
{ KN, PF, QN, WN, ST, KN, KN, AC, AC, AC, KN, KN, KN, KN, KN }, 	 //	 344	 5500
{ KN, KN, ST, WN, ST, KN, KN, AC, AC, AC, KN, KN, KN, KN, KN }, 	 //	 345	 5500
{ KN, KN, SH, TN, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 346	 5500
{ KN, KN, SH, AC, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 347	 5500
{ KN, SH, SH, TN, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC }, 	 //	 348	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, PF, PF, CR }, 	 //	 349	 5500
{ KN, AC, TN, TN, AC, KN, AC, AC, AC, LO, SK, AC, AC, AC, AC }, 	 //	 350	 5500
{ KN, AC, AC, WN, AC, KN, AC, AC, AC, AC, SK, AC, AC, KN, SK }, 	 //	 351	 5500
{ KN, AC, AC, WN, TN, KN, AC, AC, AC, AC, SK, LO, AC, KN, AC }, 	 //	 352	 5500
{ KN, AC, AC, KN, LO, KN, AC, AC, AC, AC, SK, LO, AC, PF, AC }, 	 //	 353	 5500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, SK, KN, PF, AC, AC }, 	 //	 354	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, PF, LO, SK }, 	 //	 355	 5500
{ KN, AC, AC, WN, TN, KN, AC, AC, AC, AC, SK, AC, AC, KN, AC }, 	 //	 356	 5500
{ KN, AC, SH, AC, AC, KN, AC, AC, AC, AC, SK, PF, AC, AC, AC }, 	 //	 357	 5500
{ KN, AC, AC, WN, TN, KN, AC, AC, AC, AC, SK, PF, AC, KN, AC }, 	 //	 358	 5500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, SK, PF, WN, AC, AC }, 	 //	 359	 5500
{ KN, KN, SH, PF, AC, KN, AC, AC, AC, AC, SK, SH, AC, AC, AC }, 	 //	 360	 5500
{ KN, KN, TN, AC, AC, KN, AC, AC, AC, AC, SK, SH, AC, AC, AC }, 	 //	 361	 5500
{ KN, KN, AC, TN, AC, KN, AC, AC, AC, AC, SK, SH, AC, AC, SK }, 	 //	 362	 5500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, SK, SH, WN, AC, AC }, 	 //	 363	 5500
{ KN, SH, TN, TN, AC, SK, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 364	 5500
{ KN, SH, TN, AC, AC, SK, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 365	 5500
{ KN, AC, AC, WN, AC, SK, AC, AC, AC, AC, QN, AC, AC, KN, SK }, 	 //	 366	 5500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN, AC, PF, AC, AC }, 	 //	 367	 5500
{ KN, AC, SH, TN, AC, SK, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 368	 5500
{ KN, WN, AC, AC, AC, SK, AC, AC, AC, AC, QN, KN, PF, LO, AC }, 	 //	 369	 5500
{ KN, TN, SH, AC, TN, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 370	 5500
{ KN, TN, AC, KN, AC, SK, AC, AC, AC, AC, QN, AC, AC, PF, SK }, 	 //	 371	 5500
{ KN, TN, TN, PF, AC, SK, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 372	 5500
{ KN, AC, AC, WN, AC, SK, AC, AC, AC, LO, QN, AC, AC, KN, AC }, 	 //	 373	 5500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN, AC, WN, PF, AC }, 	 //	 374	 5500
{ KN, AC, AC, TN, AC, SK, AC, AC, AC, AC, QN, PF, AC, AC, CR }, 	 //	 375	 5500
{ KN, AC, AC, AC, AC, SK, AC, AC, AC, LO, QN, PF, PF, AC, AC }, 	 //	 376	 5500
{ KN, AC, AC, AC, TN, SK, AC, AC, AC, AC, QN, PF, PF, AC, AC }, 	 //	 377	 5500
{ KN, KN, AC, KN, AC, SK, AC, AC, AC, LO, QN, SH, AC, PF, AC }, 	 //	 378	 5500
{ SK, SH, TN, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 379	 5500
{ SK, SH, TN, TN, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 380	 5500
{ SK, SH, TN, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 381	 5500
{ SK, SH, TN, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 382	 5500
{ SK, AC, AC, KN, AC, QN, AC, AC, AC, LO, QN, AC, AC, PF, AC }, 	 //	 383	 5500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, AC, CR }, 	 //	 384	 5500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, AC, SK }, 	 //	 385	 5500
{ SK, AC, TN, PF, AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 386	 5500
{ SK, AC, TN, TN, AC, QN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 387	 5500
{ SK, AC, AC, WN, AC, QN, AC, AC, AC, LO, QN, LO, AC, KN, AC }, 	 //	 388	 5500
{ SK, WN, AC, WN, AC, QN, AC, AC, AC, AC, QN, KN, AC, KN, SK }, 	 //	 389	 5500
{ SK, WN, AC, KN, AC, QN, AC, AC, AC, LO, QN, KN, AC, PF, AC }, 	 //	 390	 5500
{ SK, AC, AC, WN, AC, QN, AC, AC, AC, LO, QN, AC, AC, KN, AC }, 	 //	 391	 5500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, AC, CR }, 	 //	 392	 5500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, PF, CR }, 	 //	 393	 5500
{ SK, AC, TN, PF, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 394	 5500
{ SK, AC, TN, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 395	 5500
{ SK, AC, AC, WN, AC, QN, AC, AC, AC, AC, QN, AC, AC, KN, SK }, 	 //	 396	 5500
{ SK, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, PF, WN, AC, AC }, 	 //	 397	 5500
{ SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, PF, WN, LO, SK }, 	 //	 398	 5500
{ SK, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, PF, WN, AC, AC }, 	 //	 399	 5500
{ SK, KN, AC, AC, TN, QN, AC, AC, AC, AC, QN, SH, AC, PF, AC }, 	 //	 400	 5500
{ SK, KN, AC, KN, TN, QN, AC, AC, AC, AC, QN, SH, AC, PF, AC }, 	 //	 401	 5500
{ QN, SH, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC }, 	 //	 402	 5500
{ QN, AC, SH, AC, AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 403	 5500
{ QN, AC, SH, AC, LO, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 404	 5500
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, LO, WN, LO, AC }, 	 //	 405	 5500
{ QN, WN, AC, WN, AC, QN, AC, AC, AC, AC, QN, KN, AC, KN, CR }, 	 //	 406	 5500
{ QN, WN, TN, PF, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 407	 5500
{ QN, WN, TN, AC, AC, QN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 408	 5500
{ QN, WN, AC, AC, LO, QN, AC, AC, AC, AC, QN, KN, AC, LO, AC }, 	 //	 409	 5500
{ QN, TN, SH, PF, AC, QN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 410	 5500
{ QN, TN, SH, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK }, 	 //	 411	 5500
{ QN, TN, TN, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 412	 5500
{ QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, WN, AC, AC }, 	 //	 413	 5500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, PF, PF, AC, CR }, 	 //	 414	 5500
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, QN, PF, WN, PF, AC }, 	 //	 415	 5500
{ QN, KN, AC, PF, AC, QN, AC, AC, AC, AC, QN, SH, AC, AC, SK }, 	 //	 416	 5500
{ QN, KN, AC, WN, AC, QN, AC, AC, AC, AC, QN, SH, AC, KN, SK }, 	 //	 417	 5500
{ QN, SH, SH, AC, AC, QN, AC, AC, AC, LO, SH, AC, AC, AC, AC }, 	 //	 418	 5500
{ QN, SH, AC, WN, AC, QN, AC, AC, AC, LO, SH, AC, AC, KN, AC }, 	 //	 419	 5500
{ QN, SH, AC, KN, AC, QN, AC, AC, AC, AC, SH, AC, AC, PF, SK }, 	 //	 420	 5500
{ QN, SH, TN, AC, AC, QN, AC, AC, AC, LO, SH, AC, AC, AC, AC }, 	 //	 421	 5500
{ QN, SH, AC, AC, TN, QN, AC, AC, AC, AC, SH, AC, AC, PF, AC }, 	 //	 422	 5500
{ QN, AC, SH, TN, LO, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 423	 5500
{ QN, AC, AC, AC, LO, QN, AC, AC, AC, AC, SH, AC, PF, LO, AC }, 	 //	 424	 5500
{ QN, AC, AC, TN, AC, QN, AC, AC, AC, AC, SH, LO, AC, AC, CR }, 	 //	 425	 5500
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, AC, SH, KN, PF, AC, AC }, 	 //	 426	 5500
{ QN, WN, AC, AC, AC, QN, AC, AC, AC, AC, SH, KN, PF, PF, AC }, 	 //	 427	 5500
{ QN, TN, SH, AC, AC, QN, AC, AC, AC, LO, SH, AC, AC, AC, AC }, 	 //	 428	 5500
{ QN, TN, SH, AC, TN, QN, AC, AC, AC, AC, SH, AC, AC, AC, AC }, 	 //	 429	 5500
{ QN, TN, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, WN, AC, AC }, 	 //	 430	 5500
{ QN, AC, AC, WN, LO, QN, AC, AC, AC, AC, SH, AC, AC, KN, AC }, 	 //	 431	 5500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, WN, PF, SK }, 	 //	 432	 5500
{ QN, AC, AC, TN, AC, QN, AC, AC, AC, AC, SH, PF, AC, AC, SK }, 	 //	 433	 5500
{ QN, AC, AC, KN, LO, QN, AC, AC, AC, AC, SH, PF, AC, PF, AC }, 	 //	 434	 5500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, PF, PF, AC, CR }, 	 //	 435	 5500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, PF, PF, AC, SK }, 	 //	 436	 5500
{ QN, AC, AC, TN, AC, QN, AC, AC, AC, AC, SH, PF, AC, AC, CR }, 	 //	 437	 5500
{ QN, AC, AC, KN, TN, QN, AC, AC, AC, AC, SH, PF, AC, PF, AC }, 	 //	 438	 5500
{ QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, PF, WN, AC, CR }, 	 //	 439	 5500
{ QN, KN, AC, WN, AC, QN, AC, AC, AC, LO, SH, SH, AC, KN, AC }, 	 //	 440	 5500
{ QN, KN, TN, TN, AC, QN, AC, AC, AC, AC, SH, SH, AC, AC, AC }, 	 //	 441	 5500
{ QN, SH, SH, PF, AC, SH, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 442	 5500
{ QN, SH, AC, WN, AC, SH, AC, AC, AC, AC, JA, AC, AC, KN, SK }, 	 //	 443	 5500
{ QN, AC, AC, WN, AC, SH, AC, AC, AC, AC, JA, AC, AC, KN, CR }, 	 //	 444	 5500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, WN, PF, SK }, 	 //	 445	 5500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, LO, PF, LO, CR }, 	 //	 446	 5500
{ QN, WN, AC, AC, AC, SH, AC, AC, AC, AC, JA, KN, PF, PF, AC }, 	 //	 447	 5500
{ QN, WN, TN, AC, AC, SH, AC, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 448	 5500
{ QN, WN, AC, AC, AC, SH, AC, AC, AC, AC, JA, KN, WN, AC, AC }, 	 //	 449	 5500
{ QN, WN, AC, AC, AC, SH, AC, AC, AC, AC, JA, KN, WN, LO, AC }, 	 //	 450	 5500
{ QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, PF, AC, AC }, 	 //	 451	 5500
{ QN, TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, WN, PF, AC }, 	 //	 452	 5500
{ QN, AC, SH, AC, TN, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 453	 5500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, PF, AC, SK }, 	 //	 454	 5500
{ QN, AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, WN, AC, CR }, 	 //	 455	 5500
{ QN, KN, SH, AC, AC, SH, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 456	 5500
{ QN, KN, SH, AC, AC, SH, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 457	 5500
{ QN, KN, TN, AC, AC, SH, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 458	 5500
{ SH, SH, TN, PF, AC, JA, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 459	 5500
{ SH, AC, TN, AC, LO, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 460	 5500
{ SH, AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, WN, LO, AC }, 	 //	 461	 5500
{ SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA, AC, WN, AC, AC }, 	 //	 462	 5500
{ SH, WN, AC, KN, LO, JA, AC, AC, AC, AC, JA, KN, AC, PF, AC }, 	 //	 463	 5500
{ SH, WN, AC, KN, AC, JA, AC, AC, AC, AC, JA, KN, AC, PF, CR }, 	 //	 464	 5500
{ SH, TN, TN, AC, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 465	 5500
{ SH, AC, AC, AC, LO, JA, AC, AC, AC, AC, JA, AC, PF, AC, AC }, 	 //	 466	 5500
{ SH, AC, AC, AC, TN, JA, AC, AC, AC, AC, JA, AC, PF, PF, AC }, 	 //	 467	 5500
{ JA, SH, AC, KN, AC, JA, AC, AC, AC, AC, JA, AC, AC, PF, SK }, 	 //	 468	 5500
{ JA, SH, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, PF, PF, AC }, 	 //	 469	 5500
{ JA, SH, AC, WN, LO, JA, AC, AC, AC, AC, JA, AC, AC, KN, AC }, 	 //	 470	 5500
{ JA, AC, AC, AC, LO, JA, AC, AC, AC, AC, JA, AC, WN, AC, AC }, 	 //	 471	 5500
{ JA, AC, AC, TN, AC, JA, AC, AC, AC, AC, JA, LO, AC, AC, CR }, 	 //	 472	 5500
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, LO, PF, AC, CR }, 	 //	 473	 5500
{ JA, TN, SH, PF, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 474	 5500
{ JA, TN, AC, KN, TN, JA, AC, AC, AC, AC, JA, AC, AC, PF, AC }, 	 //	 475	 5500
{ JA, AC, SH, AC, AC, JA, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 476	 5500
{ JA, AC, AC, KN, AC, JA, AC, AC, AC, LO, JA, AC, AC, PF, AC }, 	 //	 477	 5500
{ JA, AC, TN, PF, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 478	 5500
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, WN, PF, CR }, 	 //	 479	 5500
{ JA, KN, SH, PF, AC, JA, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 480	 5500
{ JA, KN, AC, KN, AC, JA, AC, AC, AC, AC, JA, SH, AC, PF, SK }, 	 //	 481	 5500
{ JA, KN, TN, TN, AC, JA, AC, AC, AC, AC, JA, SH, AC, AC, AC }, 	 //	 482	 5500
{ JA, KN, AC, AC, LO, JA, AC, AC, AC, AC, JA, SH, AC, PF, AC }, 	 //	 483	 5500
{ JA, AC, SH, AC, AC, JA, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 484	 5500
{ JA, AC, TN, AC, AC, JA, AC, AC, AC, LO, WN, AC, AC, AC, AC }, 	 //	 485	 5500
{ JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, WN, AC, CR }, 	 //	 486	 5500
{ JA, AC, TN, AC, AC, JA, AC, AC, AC, AC, WN, LO, AC, AC, AC }, 	 //	 487	 5500
{ JA, TN, SH, AC, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 488	 5500
{ JA, TN, TN, AC, LO, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 489	 5500
{ JA, TN, AC, WN, AC, JA, AC, AC, AC, AC, WN, AC, AC, KN, CR }, 	 //	 490	 5500
{ JA, TN, AC, KN, AC, JA, AC, AC, AC, AC, WN, AC, AC, PF, CR }, 	 //	 491	 5500
{ JA, AC, SH, AC, LO, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC }, 	 //	 492	 5500
{ JA, AC, SH, AC, AC, JA, AC, AC, AC, AC, WN, PF, AC, AC, AC }, 	 //	 493	 5500
{ JA, AC, AC, KN, AC, JA, AC, AC, AC, AC, WN, PF, AC, PF, CR }, 	 //	 494	 5500
{ JA, AC, AC, KN, AC, JA, AC, AC, AC, AC, WN, PF, AC, PF, CR }, 	 //	 495	 5500
{ JA, AC, AC, AC, TN, JA, AC, AC, AC, AC, WN, PF, WN, PF, AC }, 	 //	 496	 5500
{ JA, KN, SH, PF, AC, JA, AC, AC, AC, AC, WN, SH, AC, AC, AC }, 	 //	 497	 5500
{ JA, SH, SH, AC, AC, WN, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 498	 5500
{ JA, AC, AC, WN, AC, WN, AC, AC, AC, LO, TN, AC, AC, KN, AC }, 	 //	 499	 5500
{ JA, AC, AC, WN, AC, WN, AC, AC, AC, AC, TN, AC, AC, KN, SK }, 	 //	 500	 5500
{ JA, AC, AC, KN, AC, WN, AC, AC, AC, AC, TN, AC, AC, PF, CR }, 	 //	 501	 5500
{ JA, AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, LO, PF, AC, SK }, 	 //	 502	 5500
{ JA, WN, TN, PF, AC, WN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 503	 5500
{ JA, WN, TN, AC, AC, WN, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 504	 5500
{ JA, WN, AC, WN, AC, WN, AC, AC, AC, AC, TN, KN, AC, KN, SK }, 	 //	 505	 5500
{ JA, WN, AC, AC, TN, WN, AC, AC, AC, AC, TN, KN, AC, PF, AC }, 	 //	 506	 5500
{ JA, WN, AC, KN, AC, WN, AC, AC, AC, AC, TN, KN, AC, PF, SK }, 	 //	 507	 5500
{ JA, WN, AC, AC, AC, WN, AC, AC, AC, AC, TN, KN, WN, PF, AC }, 	 //	 508	 5500
{ JA, TN, AC, AC, TN, WN, AC, AC, AC, AC, TN, AC, AC, LO, AC }, 	 //	 509	 5500
{ JA, TN, TN, AC, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 510	 5500
{ JA, TN, AC, AC, AC, WN, AC, AC, AC, AC, TN, AC, WN, AC, AC }, 	 //	 511	 5500
{ JA, AC, SH, PF, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 512	 5500
{ JA, AC, SH, TN, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 513	 5500
{ JA, AC, AC, KN, AC, WN, AC, AC, AC, LO, TN, AC, AC, PF, AC }, 	 //	 514	 5500
{ JA, AC, TN, PF, TN, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 515	 5500
{ JA, AC, AC, WN, AC, WN, AC, AC, AC, AC, TN, PF, AC, KN, SK }, 	 //	 516	 5500
{ JA, AC, AC, KN, LO, WN, AC, AC, AC, AC, TN, PF, AC, PF, AC }, 	 //	 517	 5500
{ JA, KN, SH, PF, AC, WN, AC, AC, AC, AC, TN, SH, AC, AC, AC }, 	 //	 518	 5500
{ JA, KN, AC, WN, TN, WN, AC, AC, AC, AC, TN, SH, AC, KN, AC }, 	 //	 519	 5500
{ JA, KN, AC, KN, AC, WN, AC, AC, AC, AC, TN, SH, AC, PF, SK }, 	 //	 520	 5500
{ WN, SH, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, LO, AC }, 	 //	 521	 5500
{ WN, SH, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, PF, AC, AC }, 	 //	 522	 5500
{ WN, SH, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, PF, AC, AC }, 	 //	 523	 5500
{ WN, SH, AC, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 524	 5500
{ WN, SH, AC, KN, TN, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 525	 5500
{ WN, SH, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, WN, LO, AC }, 	 //	 526	 5500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, WN, PF, SK }, 	 //	 527	 5500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, LO, PF, LO, AC }, 	 //	 528	 5500
{ WN, AC, AC, PF, AC, TN, AC, AC, AC, AC, TN, LO, AC, AC, SK }, 	 //	 529	 5500
{ WN, AC, AC, WN, AC, TN, AC, AC, AC, AC, TN, LO, AC, KN, CR }, 	 //	 530	 5500
{ WN, AC, AC, KN, AC, TN, AC, AC, AC, AC, TN, LO, AC, PF, CR }, 	 //	 531	 5500
{ WN, WN, AC, PF, AC, TN, AC, AC, AC, AC, TN, KN, AC, AC, CR }, 	 //	 532	 5500
{ WN, WN, AC, KN, AC, TN, AC, AC, AC, AC, TN, KN, AC, PF, CR }, 	 //	 533	 5500
{ WN, TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, PF, PF, AC }, 	 //	 534	 5500
{ WN, AC, AC, KN, TN, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 535	 5500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, WN, LO, SK }, 	 //	 536	 5500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, WN, AC, SK }, 	 //	 537	 5500
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, PF, PF, LO, AC }, 	 //	 538	 5500
{ WN, AC, AC, AC, LO, TN, AC, AC, AC, AC, TN, PF, WN, AC, AC }, 	 //	 539	 5500
{ WN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, PF, WN, LO, AC }, 	 //	 540	 5500
{ WN, KN, AC, TN, AC, TN, AC, AC, AC, AC, TN, SH, AC, AC, SK }, 	 //	 541	 5500
{ WN, KN, AC, KN, LO, TN, AC, AC, AC, AC, TN, SH, AC, PF, AC }, 	 //	 542	 5500
{ WN, KN, AC, WN, AC, TN, AC, AC, AC, AC, TN, SH, AC, KN, CR }, 	 //	 543	 5500
{ TN, SH, SH, AC, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 544	 5500
{ TN, SH, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, PF, AC, AC }, 	 //	 545	 5500
{ TN, SH, TN, AC, LO, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 546	 5500
{ TN, AC, AC, KN, AC, TN, AC, AC, AC, AC, TN, LO, AC, PF, CR }, 	 //	 547	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, LO, PF, AC, CR }, 	 //	 548	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, LO, PF, LO, AC }, 	 //	 549	 5500
{ TN, AC, TN, AC, AC, TN, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 550	 5500
{ TN, AC, AC, PF, AC, TN, AC, AC, AC, AC, TN, LO, AC, AC, SK }, 	 //	 551	 5500
{ TN, AC, AC, KN, LO, TN, AC, AC, AC, AC, TN, LO, AC, PF, AC }, 	 //	 552	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, TN, LO, WN, AC, AC }, 	 //	 553	 5500
{ TN, WN, AC, AC, LO, TN, AC, AC, AC, AC, TN, KN, AC, LO, AC }, 	 //	 554	 5500
{ TN, TN, AC, WN, AC, TN, AC, AC, AC, AC, TN, AC, AC, KN, CR }, 	 //	 555	 5500
{ TN, TN, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 556	 5500
{ TN, AC, SH, PF, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 557	 5500
{ TN, AC, SH, TN, TN, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 558	 5500
{ TN, AC, TN, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 559	 5500
{ TN, AC, AC, KN, LO, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 560	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, WN, AC, SK }, 	 //	 561	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, PF, PF, AC, CR }, 	 //	 562	 5500
{ TN, AC, AC, WN, TN, TN, AC, AC, AC, AC, TN, PF, AC, KN, AC }, 	 //	 563	 5500
{ TN, AC, AC, KN, AC, TN, AC, AC, AC, AC, TN, PF, AC, PF, CR }, 	 //	 564	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, PF, WN, AC, SK }, 	 //	 565	 5500
{ TN, SH, SH, PF, AC, TN, AC, AC, AC, LO, ST, AC, AC, AC, AC }, 	 //	 566	 5500
{ TN, SH, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 567	 5500
{ TN, SH, TN, PF, AC, TN, AC, AC, AC, AC, ST, AC, AC, AC, CR }, 	 //	 568	 5500
{ TN, AC, SH, TN, TN, TN, AC, AC, AC, AC, ST, AC, AC, AC, AC }, 	 //	 569	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, PF, CR }, 	 //	 570	 5500
{ TN, AC, AC, AC, TN, TN, AC, AC, AC, AC, ST, AC, WN, LO, AC }, 	 //	 571	 5500
{ TN, AC, AC, KN, TN, TN, AC, AC, AC, AC, ST, LO, AC, PF, AC }, 	 //	 572	 5500
{ TN, AC, AC, AC, AC, TN, AC, AC, AC, LO, ST, LO, WN, LO, AC }, 	 //	 573	 5500
{ TN, WN, AC, KN, LO, TN, AC, AC, AC, AC, ST, KN, AC, PF, AC }, 	 //	 574	 5500
{ TN, TN, AC, AC, AC, TN, AC, AC, AC, AC, ST, AC, PF, AC, AC }, 	 //	 575	 5500
{ TN, AC, AC, AC, LO, TN, AC, AC, AC, AC, ST, AC, PF, PF, AC }, 	 //	 576	 5500
{ TN, AC, AC, WN, TN, TN, AC, AC, AC, AC, ST, PF, AC, KN, AC }, 	 //	 577	 5500
{ TN, AC, AC, AC, AC, ST, SH, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 578	 5500
{ TN, SH, SH, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 579	 5500
{ TN, SH, SH, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 580	 5500
{ TN, SH, TN, KN, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 581	 5500
{ TN, AC, TN, AC, AC, ST, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 582	 5500
{ TN, AC, TN, KN, AC, ST, AC, AC, AC, AC, AC, AC, AC, PF, CR }, 	 //	 583	 5500
{ TN, AC, AC, AC, AC, ST, AC, AC, AC, KN, AC, LO, PF, AC, QN }, 	 //	 584	 5500
{ TN, AC, AC, PF, AC, ST, AC, AC, AC, SK, AC, LO, AC, AC, KN }, 	 //	 585	 5500
{ TN, AC, AC, TN, AC, ST, AC, AC, AC, KN, AC, LO, AC, AC, QN }, 	 //	 586	 5500
{ TN, WN, SH, TN, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 587	 5500
{ TN, WN, AC, AC, KN, ST, AC, AC, AC, AC, AC, KN, AC, AC, LO }, 	 //	 588	 5500
{ TN, WN, AC, AC, ST, ST, AC, AC, AC, AC, AC, KN, AC, LO, KN }, 	 //	 589	 5500
{ TN, WN, AC, KN, AC, ST, AC, AC, AC, KN, AC, KN, AC, PF, QN }, 	 //	 590	 5500
{ TN, WN, TN, AC, AC, ST, AC, AC, AC, AC, AC, KN, AC, AC, AC }, 	 //	 591	 5500
{ TN, WN, AC, AC, ST, ST, AC, AC, AC, AC, AC, KN, AC, AC, KN }, 	 //	 592	 5500
{ TN, WN, AC, AC, AC, ST, AC, AC, AC, AC, AC, KN, WN, AC, CR }, 	 //	 593	 5500
{ TN, TN, SH, AC, ST, ST, AC, AC, AC, AC, AC, AC, AC, AC, KN }, 	 //	 594	 5500
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, PF, LO, CR }, 	 //	 595	 5500
{ TN, TN, AC, AC, AC, ST, AC, AC, AC, AC, AC, AC, WN, PF, CR }, 	 //	 596	 5500
{ TN, AC, AC, AC, ST, ST, AC, AC, AC, AC, AC, AC, WN, PF, KN }, 	 //	 597	 5500
{ TN, AC, AC, AC, KN, ST, AC, AC, AC, AC, AC, PF, WN, PF, LO }, 	 //	 598	 5500
{ TN, KN, AC, WN, AC, ST, AC, AC, AC, KN, AC, SH, AC, KN, QN }, 	 //	 599	 5500
{ TN, KN, AC, KN, AC, ST, AC, AC, AC, KN, AC, SH, AC, PF, QN }, 	 //	 600	 5500
{ TN, KN, AC, TN, AC, ST, AC, AC, AC, SK, AC, SH, AC, AC, KN }, 	 //	 601	 5500
{ TN, KN, AC, AC, ST, ST, AC, AC, AC, AC, AC, SH, AC, PF, KN }, 	 //	 602	 5500
{ ST, SH, SH, TN, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 603	 5500
{ ST, SH, AC, AC, AC, AC, AC, AC, AC, LO, KN, AC, PF, LO, AC }, 	 //	 604	 5500
{ ST, AC, AC, AC, AC, AC, AC, AC, PF, LO, KN, AC, AC, AC, AC }, 	 //	 605	 5500
{ ST, AC, TN, PF, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 606	 5500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, KN, KN, LO, WN, AC, QN }, 	 //	 607	 5500
{ ST, WN, SH, TN, AC, AC, AC, AC, AC, LO, KN, KN, AC, AC, AC }, 	 //	 608	 5500
{ ST, WN, TN, AC, AC, AC, AC, AC, AC, LO, KN, KN, AC, AC, AC }, 	 //	 609	 5500
{ ST, TN, TN, PF, AC, AC, AC, AC, AC, KN, KN, AC, AC, AC, QN }, 	 //	 610	 5500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, SK, KN, AC, PF, LO, KN }, 	 //	 611	 5500
{ ST, AC, TN, TN, AC, AC, AC, AC, AC, SK, KN, AC, AC, AC, KN }, 	 //	 612	 5500
{ ST, AC, AC, AC, JA, AC, AC, AC, AC, TN, KN, AC, WN, LO, AC }, 	 //	 613	 5500
{ ST, AC, AC, TN, AC, AC, AC, AC, AC, KN, KN, PF, AC, AC, QN }, 	 //	 614	 5500
{ ST, AC, AC, AC, AC, AC, AC, AC, AC, SK, KN, PF, WN, PF, KN }, 	 //	 615	 5500
{ ST, KN, AC, AC, TN, AC, AC, AC, AC, ST, KN, SH, AC, LO, AC }, 	 //	 616	 5500
{ ST, KN, TN, AC, AC, AC, AC, AC, AC, LO, KN, SH, AC, AC, AC }, 	 //	 617	 5500
{ AC, AC, AC, WN, LO, KN, AC, AC, AC, AC, QN, AC, PF, KN, AC }, 	 //	 618	 5500
{ AC, AC, AC, WN, TN, KN, AC, AC, AC, AC, QN, AC, PF, KN, AC }, 	 //	 619	 5500
{ AC, AC, AC, WN, AC, KN, AC, AC, AC, AC, QN, AC, PF, KN, AC }, 	 //	 620	 5500
{ AC, AC, AC, AC, KN, KN, AC, AC, AC, AC, QN, AC, PF, AC, LO }, 	 //	 621	 5500
{ AC, AC, TN, AC, QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 622	 5500
{ AC, AC, AC, AC, JA, KN, AC, AC, AC, TN, QN, AC, WN, AC, AC }, 	 //	 623	 5500
{ AC, AC, SH, PF, LO, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 624	 5500
{ AC, AC, TN, PF, TN, KN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 625	 5500
{ AC, AC, AC, WN, LO, KN, AC, AC, AC, AC, QN, LO, WN, KN, AC }, 	 //	 626	 5500
{ AC, AC, AC, AC, ST, KN, AC, AC, AC, AC, QN, LO, WN, AC, KN }, 	 //	 627	 5500
{ AC, WN, AC, AC, KN, KN, AC, AC, AC, AC, QN, KN, AC, AC, LO }, 	 //	 628	 5500
{ AC, WN, AC, WN, TN, KN, AC, AC, AC, ST, QN, KN, AC, KN, AC }, 	 //	 629	 5500
{ AC, WN, AC, PF, KN, KN, AC, AC, AC, AC, QN, KN, AC, AC, LO }, 	 //	 630	 5500
{ AC, AC, AC, AC, AC, KN, KN, PF, PF, KN, QN, QN, QN, KN, QN }, 	 //	 631	 5500
{ AC, TN, SH, TN, TN, KN, AC, AC, AC, ST, QN, AC, AC, AC, AC }, 	 //	 632	 5500
{ AC, TN, SH, TN, QN, KN, AC, AC, AC, KN, QN, AC, AC, AC, AC }, 	 //	 633	 5500
{ AC, TN, SH, AC, JA, KN, AC, AC, AC, TN, QN, AC, AC, AC, AC }, 	 //	 634	 5500
{ AC, TN, AC, KN, TN, KN, AC, AC, AC, ST, QN, AC, AC, PF, AC }, 	 //	 635	 5500
{ AC, AC, AC, AC, QN, KN, AC, AC, AC, KN, QN, AC, PF, AC, AC }, 	 //	 636	 5500
{ AC, AC, AC, AC, TN, KN, AC, AC, AC, ST, QN, AC, PF, AC, AC }, 	 //	 637	 5500
{ AC, AC, AC, KN, AC, KN, AC, AC, AC, AC, QN, AC, PF, PF, AC }, 	 //	 638	 5500
{ AC, AC, AC, KN, AC, KN, AC, AC, AC, AC, QN, AC, WN, PF, AC }, 	 //	 639	 5500
{ AC, AC, AC, TN, LO, KN, AC, AC, AC, AC, QN, PF, PF, AC, AC }, 	 //	 640	 5500
{ AC, KN, SH, AC, LO, KN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 641	 5500
{ AC, KN, AC, AC, ST, KN, AC, AC, AC, AC, QN, SH, AC, PF, KN }, 	 //	 642	 5500
{ AC, KN, AC, AC, JA, KN, AC, AC, AC, TN, QN, SH, AC, PF, AC }, 	 //	 643	 5500
{ AC, KN, AC, AC, ST, KN, AC, AC, AC, AC, QN, SH, AC, LO, KN }, 	 //	 644	 5500
{ KN, SH, SH, PF, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, CR }, 	 //	 645	 5500
{ KN, AC, SH, PF, TN, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 646	 5500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, AC, WN, AC, SK }, 	 //	 647	 5500
{ KN, AC, AC, TN, AC, QN, AC, AC, AC, AC, PF, LO, AC, AC, CR }, 	 //	 648	 5500
{ KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF, LO, PF, AC, AC }, 	 //	 649	 5500
{ KN, WN, SH, TN, AC, QN, AC, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 650	 5500
{ KN, WN, TN, PF, AC, QN, AC, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 651	 5500
{ KN, WN, TN, AC, AC, QN, AC, AC, AC, AC, PF, KN, AC, AC, AC }, 	 //	 652	 5500
{ KN, TN, SH, PF, AC, QN, AC, AC, AC, LO, PF, AC, AC, AC, AC }, 	 //	 653	 5500
{ KN, TN, TN, PF, LO, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 654	 5500
{ KN, AC, TN, AC, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, SK }, 	 //	 655	 5500
{ KN, AC, TN, AC, TN, QN, AC, AC, AC, AC, PF, AC, AC, AC, AC }, 	 //	 656	 5500
{ KN, AC, SH, AC, AC, QN, AC, AC, AC, AC, PF, PF, AC, AC, AC }, 	 //	 657	 5500
{ KN, AC, TN, AC, AC, QN, AC, AC, AC, AC, PF, PF, AC, AC, AC }, 	 //	 658	 5500
{ KN, AC, TN, AC, AC, QN, AC, AC, AC, AC, PF, PF, AC, AC, AC }, 	 //	 659	 5500
{ KN, AC, AC, AC, LO, QN, AC, AC, AC, AC, PF, PF, WN, AC, AC }, 	 //	 660	 5500
{ KN, KN, AC, WN, AC, QN, AC, AC, AC, LO, PF, SH, AC, KN, AC }, 	 //	 661	 5500
{ QN, SH, TN, AC, LO, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 662	 5500
{ QN, SH, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, WN, AC, AC }, 	 //	 663	 5500
{ QN, AC, SH, PF, LO, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 664	 5500
{ QN, AC, TN, PF, LO, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 665	 5500
{ QN, AC, TN, PF, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 666	 5500
{ QN, AC, TN, PF, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, SK }, 	 //	 667	 5500
{ QN, AC, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, WN, AC, SK }, 	 //	 668	 5500
{ QN, WN, SH, AC, AC, PF, AC, AC, AC, AC, JA, KN, AC, AC, AC }, 	 //	 669	 5500
{ QN, TN, SH, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 670	 5500
{ QN, TN, TN, AC, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 671	 5500
{ QN, TN, AC, KN, LO, PF, AC, AC, AC, AC, JA, AC, AC, PF, AC }, 	 //	 672	 5500
{ QN, AC, SH, AC, AC, PF, AC, AC, AC, LO, JA, AC, AC, AC, AC }, 	 //	 673	 5500
{ QN, AC, TN, PF, LO, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC }, 	 //	 674	 5500
{ QN, AC, TN, PF, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, CR }, 	 //	 675	 5500
{ QN, AC, TN, AC, AC, PF, AC, AC, AC, AC, JA, PF, AC, AC, AC }, 	 //	 676	 5500
{ QN, AC, AC, TN, AC, PF, AC, AC, AC, AC, JA, PF, AC, AC, CR }, 	 //	 677	 5500
{ QN, AC, AC, AC, LO, PF, AC, AC, AC, AC, JA, PF, WN, LO, AC }, 	 //	 678	 5500
{ QN, KN, AC, AC, AC, PF, AC, AC, AC, AC, JA, SH, PF, AC, AC }, 	 //	 679	 5500
{ QN, KN, AC, KN, AC, PF, AC, AC, AC, LO, JA, SH, AC, PF, AC }, 	 //	 680	 5500
{ QN, KN, AC, AC, AC, PF, AC, AC, AC, AC, JA, SH, WN, LO, AC }, 	 //	 681	 5500
{ PF, AC, SH, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 682	 5500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN, AC, PF, LO, CR }, 	 //	 683	 5500
{ PF, AC, TN, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, CR }, 	 //	 684	 5500
{ PF, AC, TN, AC, LO, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 685	 5500
{ PF, AC, SH, AC, AC, JA, AC, AC, AC, AC, TN, LO, AC, AC, AC }, 	 //	 686	 5500
{ PF, AC, AC, AC, LO, JA, AC, AC, AC, AC, TN, LO, PF, AC, AC }, 	 //	 687	 5500
{ PF, AC, AC, AC, TN, JA, AC, AC, AC, AC, TN, LO, PF, LO, AC }, 	 //	 688	 5500
{ PF, AC, AC, AC, AC, JA, AC, AC, AC, LO, TN, LO, PF, AC, AC }, 	 //	 689	 5500
{ PF, WN, SH, PF, AC, JA, AC, AC, AC, AC, TN, KN, AC, AC, AC }, 	 //	 690	 5500
{ PF, WN, AC, WN, TN, JA, AC, AC, AC, AC, TN, KN, AC, KN, AC }, 	 //	 691	 5500
{ PF, TN, TN, AC, LO, JA, AC, AC, AC, AC, TN, AC, AC, AC, AC }, 	 //	 692	 5500
{ PF, TN, TN, AC, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, SK }, 	 //	 693	 5500
{ PF, TN, AC, KN, LO, JA, AC, AC, AC, AC, TN, AC, AC, PF, AC }, 	 //	 694	 5500
{ PF, AC, SH, PF, AC, JA, AC, AC, AC, LO, TN, AC, AC, AC, AC }, 	 //	 695	 5500
{ PF, AC, SH, AC, AC, JA, AC, AC, AC, AC, TN, PF, AC, AC, AC }, 	 //	 696	 5500
{ PF, AC, AC, WN, AC, JA, AC, AC, AC, AC, TN, PF, AC, KN, CR }, 	 //	 697	 5500
{ PF, KN, AC, TN, AC, JA, AC, AC, AC, AC, TN, SH, AC, AC, SK }, 	 //	 698	 5500
{ JA, SH, TN, PF, AC, TN, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 699	 5500
{ JA, SH, TN, WN, AC, TN, AC, AC, AC, AC, AC, AC, AC, KN, AC }, 	 //	 700	 5500
{ JA, AC, AC, TN, AC, TN, AC, AC, AC, SK, AC, LO, AC, AC, KN }, 	 //	 701	 5500
{ JA, AC, TN, AC, AC, TN, AC, AC, AC, AC, AC, LO, AC, AC, AC }, 	 //	 702	 5500
{ JA, AC, AC, AC, ST, TN, AC, AC, AC, AC, AC, LO, WN, AC, KN }, 	 //	 703	 5500
{ JA, TN, SH, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, PF, AC }, 	 //	 704	 5500
{ JA, TN, TN, AC, AC, TN, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 705	 5500
{ JA, TN, TN, AC, AC, TN, AC, AC, AC, AC, AC, AC, AC, LO, AC }, 	 //	 706	 5500
{ JA, TN, AC, AC, AC, TN, AC, AC, AC, AC, AC, AC, WN, LO, CR }, 	 //	 707	 5500
{ JA, AC, SH, TN, AC, TN, AC, AC, AC, KN, AC, AC, AC, AC, QN }, 	 //	 708	 5500
{ JA, AC, SH, TN, AC, TN, AC, AC, AC, SK, AC, AC, AC, AC, KN }, 	 //	 709	 5500
{ JA, AC, TN, TN, AC, TN, AC, AC, AC, AC, AC, PF, AC, AC, AC }, 	 //	 710	 5500
{ TN, SH, SH, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 711	 5500
{ TN, SH, SH, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 712	 5500
{ TN, SH, SH, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 713	 5500
{ TN, SH, TN, PF, CR, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 714	 5500
{ TN, SH, TN, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK }, 	 //	 715	 5500
{ TN, SH, TN, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 716	 5500
{ TN, SH, TN, KN, AC, AC, AC, AC, AC, LO, AC, AC, AC, PF, AC }, 	 //	 717	 5500
{ TN, SH, TN, KN, AC, AC, AC, AC, AC, SK, AC, AC, AC, PF, KN }, 	 //	 718	 5500
{ TN, SH, AC, AC, AC, AC, AC, AC, AC, SK, AC, AC, WN, AC, KN }, 	 //	 719	 5500
{ TN, AC, SH, PF, SH, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 720	 5500
{ TN, AC, SH, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 721	 5500
{ TN, AC, SH, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 722	 5500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, PF, AC, QN }, 	 //	 723	 5500
{ TN, AC, TN, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 724	 5500
{ TN, AC, TN, AC, TN, AC, AC, AC, AC, TN, AC, AC, AC, AC, ST }, 	 //	 725	 5500
{ TN, AC, TN, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, CR }, 	 //	 726	 5500
{ TN, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, AC, WN, AC, KN }, 	 //	 727	 5500
{ TN, AC, AC, TN, TN, AC, AC, AC, AC, TN, AC, LO, AC, AC, ST }, 	 //	 728	 5500
{ TN, AC, AC, KN, PF, AC, AC, AC, AC, JA, AC, LO, AC, PF, TN }, 	 //	 729	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, LO, PF, AC, CR }, 	 //	 730	 5500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, LO, PF, PF, QN }, 	 //	 731	 5500
{ TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, LO, WN, LO, JA }, 	 //	 732	 5500
{ TN, AC, AC, AC, PF, AC, AC, AC, AC, JA, AC, LO, WN, LO, TN }, 	 //	 733	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, QN, AC, LO, WN, AC, PF }, 	 //	 734	 5500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, LO, WN, PF, TN }, 	 //	 735	 5500
{ TN, WN, AC, AC, KN, AC, AC, AC, AC, KN, AC, KN, AC, AC, KN }, 	 //	 736	 5500
{ TN, WN, AC, AC, KN, AC, AC, AC, AC, QN, AC, KN, AC, AC, PF }, 	 //	 737	 5500
{ TN, WN, AC, AC, QN, AC, AC, AC, AC, PF, AC, KN, AC, LO, JA }, 	 //	 738	 5500
{ TN, WN, AC, AC, PF, AC, AC, AC, AC, JA, AC, KN, AC, LO, TN }, 	 //	 739	 5500
{ TN, WN, AC, AC, KN, AC, AC, AC, AC, KN, AC, KN, AC, PF, KN }, 	 //	 740	 5500
{ TN, WN, AC, AC, KN, AC, AC, AC, AC, KN, AC, KN, AC, PF, KN }, 	 //	 741	 5500
{ TN, WN, AC, AC, AC, AC, AC, AC, AC, SK, AC, KN, PF, AC, KN }, 	 //	 742	 5500
{ TN, WN, AC, PF, QN, AC, AC, AC, AC, QN, AC, KN, AC, AC, QN }, 	 //	 743	 5500
{ TN, WN, AC, PF, TN, AC, AC, AC, AC, TN, AC, KN, AC, AC, ST }, 	 //	 744	 5500
{ TN, WN, AC, AC, QN, AC, AC, AC, AC, QN, AC, KN, AC, LO, QN }, 	 //	 745	 5500
{ TN, WN, AC, KN, QN, AC, AC, AC, AC, QN, AC, KN, AC, PF, QN }, 	 //	 746	 5500
{ TN, TN, SH, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 747	 5500
{ TN, TN, SH, TN, JA, AC, AC, AC, AC, JA, AC, AC, AC, AC, JA }, 	 //	 748	 5500
{ TN, TN, SH, AC, WN, AC, AC, AC, AC, TN, AC, AC, AC, AC, TN }, 	 //	 749	 5500
{ TN, TN, SH, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, AC, PF }, 	 //	 750	 5500
{ TN, AC, SH, PF, CR, AC, AC, AC, AC, QN, AC, AC, AC, AC, KN }, 	 //	 751	 5500
{ TN, AC, SH, AC, JA, AC, AC, AC, AC, WN, AC, AC, AC, AC, TN }, 	 //	 752	 5500
{ TN, AC, SH, TN, CR, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN }, 	 //	 753	 5500
{ TN, AC, SH, TN, SK, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 754	 5500
{ TN, AC, SH, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, QN }, 	 //	 755	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, AC, KN }, 	 //	 756	 5500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, AC, PF, AC, ST }, 	 //	 757	 5500
{ TN, AC, TN, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN }, 	 //	 758	 5500
{ TN, AC, TN, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 759	 5500
{ TN, AC, TN, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, AC, TN }, 	 //	 760	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, WN, AC, KN }, 	 //	 761	 5500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, WN, PF, QN }, 	 //	 762	 5500
{ TN, AC, SH, PF, AC, AC, AC, AC, AC, LO, AC, PF, AC, AC, AC }, 	 //	 763	 5500
{ TN, AC, AC, WN, KN, AC, AC, AC, AC, SK, AC, PF, AC, KN, QN }, 	 //	 764	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, PF, PF, AC, KN }, 	 //	 765	 5500
{ TN, AC, AC, AC, CR, AC, AC, AC, AC, KN, AC, PF, PF, LO, KN }, 	 //	 766	 5500
{ TN, AC, AC, AC, SH, AC, AC, AC, AC, JA, AC, PF, PF, AC, JA }, 	 //	 767	 5500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, JA, AC, PF, PF, AC, JA }, 	 //	 768	 5500
{ TN, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, PF, AC, KN, SK }, 	 //	 769	 5500
{ TN, AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, PF, AC, AC, QN }, 	 //	 770	 5500
{ TN, AC, AC, TN, KN, AC, AC, AC, AC, QN, AC, PF, AC, AC, PF }, 	 //	 771	 5500
{ TN, AC, AC, TN, QN, AC, AC, AC, AC, PF, AC, PF, AC, AC, JA }, 	 //	 772	 5500
{ TN, AC, AC, KN, SK, AC, AC, AC, AC, QN, AC, PF, AC, PF, QN }, 	 //	 773	 5500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, PF, WN, AC, SH }, 	 //	 774	 5500
{ TN, AC, AC, AC, JA, AC, AC, AC, AC, WN, AC, PF, WN, LO, TN }, 	 //	 775	 5500
{ TN, AC, AC, AC, QN, AC, AC, AC, AC, SH, AC, PF, WN, AC, JA }, 	 //	 776	 5500
{ TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, PF, WN, AC, KN }, 	 //	 777	 5500
{ TN, AC, AC, AC, TN, AC, AC, AC, AC, TN, AC, PF, WN, PF, TN }, 	 //	 778	 5500
{ TN, KN, AC, AC, QN, AC, AC, AC, AC, PF, AC, SH, AC, AC, JA }, 	 //	 779	 5500
{ TN, KN, AC, WN, CR, AC, AC, AC, AC, KN, AC, SH, AC, KN, KN }, 	 //	 780	 5500
{ TN, KN, AC, WN, KN, AC, AC, AC, AC, KN, AC, SH, AC, KN, SK }, 	 //	 781	 5500
{ TN, KN, AC, WN, KN, AC, AC, AC, AC, SK, AC, SH, AC, KN, QN }, 	 //	 782	 5500
{ TN, KN, AC, WN, KN, AC, AC, AC, AC, KN, AC, SH, AC, KN, CR }, 	 //	 783	 5500
{ TN, KN, AC, AC, KN, AC, AC, AC, AC, QN, AC, SH, AC, AC, PF }, 	 //	 784	 5500
{ TN, KN, AC, AC, KN, AC, AC, AC, AC, KN, AC, SH, AC, AC, SK }, 	 //	 785	 5500
{ TN, KN, AC, AC, QN, AC, AC, AC, AC, QN, AC, SH, AC, AC, SH }, 	 //	 786	 5500
{ TN, KN, AC, AC, TN, AC, AC, AC, AC, TN, AC, SH, AC, AC, TN }, 	 //	 787	 5500
{ TN, KN, AC, AC, CR, AC, AC, AC, AC, QN, AC, SH, AC, AC, KN }, 	 //	 788	 5500
{ TN, KN, AC, AC, JA, AC, AC, AC, AC, JA, AC, SH, AC, LO, JA }, 	 //	 789	 5500
{ TN, KN, AC, WN, KN, AC, AC, AC, AC, KN, AC, SH, AC, KN, SK }, 	 //	 790	 5500
{ TN, KN, AC, TN, TN, AC, AC, AC, AC, TN, AC, SH, AC, AC, TN }, 	 //	 791	 5500
{ TN, KN, AC, AC, QN, AC, AC, AC, AC, PF, AC, SH, AC, AC, JA }, 	 //	 792	 5500
{ TN, KN, AC, AC, SK, AC, AC, AC, AC, QN, AC, SH, AC, PF, QN }, 	 //	 793	 5500
{ TN, KN, AC, KN, CR, AC, AC, AC, AC, KN, AC, SH, AC, PF, KN }, 	 //	 794	 5500
{ TN, KN, AC, KN, JA, AC, AC, AC, AC, JA, AC, SH, AC, PF, JA }, 	 //	 795	 5500
{ TN, KN, AC, KN, JA, AC, AC, AC, AC, JA, AC, SH, AC, PF, WN }, 	 //	 796	 5500
{ TN, KN, AC, AC, AC, AC, AC, AC, AC, KN, AC, SH, WN, LO, QN }, 	 //	 797	 5500
{ AC, SH, SH, AC, CR, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 798	 5500
{ AC, SH, SH, WN, QN, AC, AC, AC, AC, QN, AC, AC, AC, KN, QN }, 	 //	 799	 5500
{ AC, SH, TN, AC, SH, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 800	 5500
{ AC, SH, TN, AC, JA, AC, AC, AC, AC, TN, AC, AC, AC, LO, AC }, 	 //	 801	 5500
{ AC, SH, TN, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 802	 5500
{ AC, SH, TN, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, PF, WN }, 	 //	 803	 5500
{ AC, AC, SH, AC, JA, AC, AC, AC, AC, JA, AC, AC, AC, LO, JA }, 	 //	 804	 5500
{ AC, AC, SH, AC, CR, AC, AC, AC, AC, QN, AC, AC, AC, LO, KN }, 	 //	 805	 5500
{ AC, AC, SH, WN, QN, AC, AC, AC, AC, SH, AC, AC, AC, KN, JA }, 	 //	 806	 5500
{ AC, AC, SH, WN, WN, AC, AC, AC, AC, TN, AC, AC, AC, KN, TN }, 	 //	 807	 5500
{ AC, AC, SH, AC, QN, AC, AC, AC, AC, PF, AC, AC, AC, PF, JA }, 	 //	 808	 5500
{ AC, AC, SH, KN, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, SK }, 	 //	 809	 5500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, SK, AC, AC, PF, AC, QN }, 	 //	 810	 5500
{ AC, AC, AC, KN, TN, AC, AC, AC, AC, TN, AC, AC, PF, PF, ST }, 	 //	 811	 5500
{ AC, AC, TN, WN, KN, AC, AC, AC, AC, SK, AC, AC, AC, KN, QN }, 	 //	 812	 5500
{ AC, AC, TN, KN, SK, AC, AC, AC, AC, QN, AC, AC, AC, PF, QN }, 	 //	 813	 5500
{ AC, AC, AC, PF, KN, AC, AC, AC, AC, KN, AC, AC, WN, AC, KN }, 	 //	 814	 5500
{ AC, AC, AC, WN, JA, AC, AC, AC, AC, JA, AC, AC, WN, KN, WN }, 	 //	 815	 5500
{ AC, AC, AC, KN, WN, AC, AC, AC, AC, TN, AC, AC, WN, PF, TN }, 	 //	 816	 5500
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, AC, WN, PF, KN }, 	 //	 817	 5500
{ AC, AC, SH, AC, JA, AC, AC, AC, AC, TN, AC, LO, AC, AC, AC }, 	 //	 818	 5500
{ AC, AC, AC, WN, KN, AC, AC, AC, AC, KN, AC, LO, PF, KN, SK }, 	 //	 819	 5500
{ AC, AC, AC, WN, SH, AC, AC, AC, AC, JA, AC, LO, PF, KN, JA }, 	 //	 820	 5500
{ AC, AC, AC, KN, JA, AC, AC, AC, AC, JA, AC, LO, WN, PF, WN }, 	 //	 821	 5500
{ AC, TN, SH, AC, KN, AC, AC, AC, AC, QN, AC, AC, AC, LO, PF }, 	 //	 822	 5500
{ AC, TN, SH, AC, SK, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN }, 	 //	 823	 5500
{ AC, TN, SH, WN, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 824	 5500
{ AC, TN, SH, WN, KN, AC, AC, AC, AC, KN, AC, AC, AC, KN, CR }, 	 //	 825	 5500
{ AC, TN, TN, AC, PF, AC, AC, AC, AC, JA, AC, AC, AC, PF, TN }, 	 //	 826	 5500
{ AC, TN, TN, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 827	 5500
{ AC, AC, SH, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, LO, SH }, 	 //	 828	 5500
{ AC, AC, SH, WN, CR, AC, AC, AC, AC, KN, AC, AC, AC, KN, KN }, 	 //	 829	 5500
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, PF, KN }, 	 //	 830	 5500
{ AC, AC, AC, TN, SK, AC, AC, AC, AC, KN, AC, AC, PF, AC, KN }, 	 //	 831	 5500
{ AC, AC, TN, KN, QN, AC, AC, AC, AC, KN, AC, AC, AC, PF, AC }, 	 //	 832	 5500
{ AC, AC, AC, TN, AC, AC, AC, AC, AC, KN, AC, AC, WN, AC, QN }, 	 //	 833	 5500
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, SK, AC, AC, WN, PF, QN }, 	 //	 834	 5500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, SK, AC, AC, WN, PF, KN }, 	 //	 835	 5500
{ AC, AC, SH, AC, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 836	 5500
{ AC, AC, SH, TN, JA, AC, AC, AC, AC, TN, AC, PF, AC, AC, AC }, 	 //	 837	 5500
{ AC, AC, AC, TN, SH, AC, AC, AC, AC, JA, AC, PF, PF, AC, JA }, 	 //	 838	 5500
{ AC, AC, TN, PF, QN, AC, AC, AC, AC, KN, AC, PF, AC, AC, AC }, 	 //	 839	 5500
{ AC, AC, AC, KN, QN, AC, AC, AC, AC, SH, AC, PF, WN, PF, JA }, 	 //	 840	 5500
{ AC, AC, AC, KN, KN, AC, AC, AC, AC, KN, AC, PF, WN, PF, CR }, 	 //	 841	 5500
{ AC, AC, AC, AC, AC, AC, SH, PF, KN, KN, SK, AC, QN, QN, QN }, 	 //	 842	 5500
{ AC, AC, AC, AC, QN, AC, SH, AC, AC, KN, SK, AC, AC, AC, AC }, 	 //	 843	 5500
{ AC, SH, SH, PF, QN, AC, AC, AC, AC, PF, SK, AC, AC, AC, JA }, 	 //	 844	 5500
{ AC, SH, SH, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 845	 5500
{ AC, SH, SH, TN, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 846	 5500
{ AC, SH, SH, TN, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 847	 5500
{ AC, SH, SH, TN, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 848	 5500
{ AC, SH, AC, WN, SK, AC, AC, AC, AC, KN, SK, AC, AC, KN, KN }, 	 //	 849	 5500
{ AC, SH, AC, KN, QN, AC, AC, AC, AC, QN, SK, AC, AC, PF, SH }, 	 //	 850	 5500
{ AC, SH, AC, WN, JA, AC, AC, AC, AC, JA, SK, AC, AC, KN, WN }, 	 //	 851	 5500
{ AC, AC, SH, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, JA }, 	 //	 852	 5500
{ AC, AC, SH, AC, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, CR }, 	 //	 853	 5500
{ AC, AC, SH, TN, SK, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 854	 5500
{ AC, AC, SH, AC, JA, AC, AC, AC, AC, JA, SK, AC, AC, AC, WN }, 	 //	 855	 5500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, SK, AC, PF, AC, JA }, 	 //	 856	 5500
{ AC, AC, AC, AC, SH, AC, AC, AC, AC, JA, SK, AC, PF, LO, JA }, 	 //	 857	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, PF, PF, KN }, 	 //	 858	 5500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, LO, SK, AC, PF, PF, AC }, 	 //	 859	 5500
{ AC, AC, AC, AC, CR, AC, AC, AC, AC, KN, SK, AC, WN, AC, KN }, 	 //	 860	 5500
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, SK, AC, WN, AC, TN }, 	 //	 861	 5500
{ AC, AC, SH, PF, TN, AC, AC, AC, AC, ST, SK, LO, AC, AC, AC }, 	 //	 862	 5500
{ AC, AC, AC, PF, TN, AC, AC, AC, AC, ST, SK, LO, PF, AC, AC }, 	 //	 863	 5500
{ AC, AC, AC, AC, PF, AC, AC, AC, AC, JA, SK, LO, PF, LO, TN }, 	 //	 864	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, SH, SK, LO, PF, AC, JA }, 	 //	 865	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, LO, PF, PF, KN }, 	 //	 866	 5500
{ AC, AC, AC, AC, JA, AC, AC, AC, AC, JA, SK, LO, WN, AC, WN }, 	 //	 867	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, QN, SK, LO, WN, LO, QN }, 	 //	 868	 5500
{ AC, AC, AC, AC, QN, AC, AC, AC, AC, PF, SK, LO, WN, LO, JA }, 	 //	 869	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, LO, WN, AC, SK }, 	 //	 870	 5500
{ AC, WN, SH, AC, JA, AC, AC, AC, AC, TN, SK, KN, AC, AC, AC }, 	 //	 871	 5500
{ AC, WN, AC, AC, KN, AC, AC, AC, AC, KN, SK, KN, AC, AC, KN }, 	 //	 872	 5500
{ AC, WN, AC, AC, TN, AC, AC, AC, AC, TN, SK, KN, AC, LO, TN }, 	 //	 873	 5500
{ AC, WN, AC, TN, QN, AC, AC, AC, AC, PF, SK, KN, AC, AC, JA }, 	 //	 874	 5500
{ AC, WN, AC, AC, SK, AC, AC, AC, AC, QN, SK, KN, AC, PF, QN }, 	 //	 875	 5500
{ AC, WN, AC, AC, JA, AC, AC, AC, AC, WN, SK, KN, AC, AC, TN }, 	 //	 876	 5500
{ AC, WN, AC, AC, KN, AC, AC, AC, AC, KN, SK, KN, AC, LO, KN }, 	 //	 877	 5500
{ AC, WN, AC, AC, TN, AC, AC, AC, AC, TN, SK, KN, AC, LO, ST }, 	 //	 878	 5500
{ AC, WN, AC, AC, SK, AC, AC, AC, AC, KN, SK, KN, AC, LO, KN }, 	 //	 879	 5500
{ AC, WN, AC, WN, JA, AC, AC, AC, AC, JA, SK, KN, AC, KN, WN }, 	 //	 880	 5500
{ AC, WN, AC, AC, QN, AC, AC, AC, AC, PF, SK, KN, AC, PF, JA }, 	 //	 881	 5500
{ AC, TN, SH, PF, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN }, 	 //	 882	 5500
{ AC, TN, SH, PF, QN, AC, AC, AC, AC, QN, SK, AC, AC, AC, SH }, 	 //	 883	 5500
{ AC, TN, SH, TN, KN, AC, AC, AC, AC, KN, SK, AC, AC, AC, SK }, 	 //	 884	 5500
{ AC, TN, SH, TN, TN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 885	 5500
{ AC, TN, TN, AC, PF, AC, AC, AC, AC, JA, SK, AC, AC, AC, TN }, 	 //	 886	 5500
{ AC, TN, AC, WN, KN, AC, AC, AC, AC, KN, SK, AC, AC, KN, KN }, 	 //	 887	 5500
{ AC, TN, AC, KN, JA, AC, AC, AC, AC, JA, SK, AC, AC, PF, WN }, 	 //	 888	 5500
{ AC, AC, SH, TN, QN, AC, AC, AC, AC, PF, SK, AC, AC, AC, JA }, 	 //	 889	 5500
{ AC, AC, SH, AC, WN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 890	 5500
{ AC, AC, AC, AC, TN, AC, AC, AC, AC, TN, SK, AC, PF, AC, TN }, 	 //	 891	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, PF, AC, CR }, 	 //	 892	 5500
{ AC, AC, AC, KN, AC, AC, AC, AC, AC, LO, SK, AC, PF, PF, AC }, 	 //	 893	 5500
{ AC, AC, TN, AC, CR, AC, AC, AC, AC, KN, SK, AC, AC, AC, KN }, 	 //	 894	 5500
{ AC, AC, TN, AC, SK, AC, AC, AC, AC, QN, SK, AC, AC, AC, QN }, 	 //	 895	 5500
{ AC, AC, TN, AC, WN, AC, AC, AC, AC, TN, SK, AC, AC, AC, TN }, 	 //	 896	 5500
{ AC, AC, TN, AC, CR, AC, AC, AC, AC, QN, SK, AC, AC, AC, KN }, 	 //	 897	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, AC, WN, AC, CR }, 	 //	 898	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, SK, PF, PF, AC, CR }, 	 //	 899	 5500
{ AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, PF, WN, PF, QN }, 	 //	 900	 5500
{ AC, AC, AC, AC, WN, AC, AC, AC, AC, TN, SK, PF, WN, PF, TN }, 	 //	 901	 5500
{ AC, KN, SH, AC, QN, AC, AC, AC, AC, KN, SK, SH, AC, AC, AC }, 	 //	 902	 5500
{ AC, KN, AC, WN, KN, AC, AC, AC, AC, KN, SK, SH, AC, KN, KN }, 	 //	 903	 5500
{ AC, KN, AC, WN, JA, AC, AC, AC, AC, WN, SK, SH, AC, KN, TN }, 	 //	 904	 5500
{ AC, KN, AC, KN, KN, AC, AC, AC, AC, QN, SK, SH, AC, PF, PF }, 	 //	 905	 5500
{ AC, KN, AC, AC, AC, AC, AC, AC, AC, LO, SK, SH, PF, LO, AC }, 	 //	 906	 5500
{ AC, KN, AC, TN, CR, AC, AC, AC, AC, KN, SK, SH, AC, AC, KN }, 	 //	 907	 5500
{ AC, KN, AC, KN, QN, AC, AC, AC, AC, SH, SK, SH, AC, PF, JA }, 	 //	 908	 5500
{ AC, AC, AC, AC, QN, SK, SH, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 909	 5500
{ AC, AC, AC, AC, QN, SK, SH, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 910	 5500
{ AC, SH, AC, WN, TN, SK, AC, AC, AC, ST, KN, AC, AC, KN, AC }, 	 //	 911	 5500
{ AC, AC, AC, AC, QN, SK, AC, AC, AC, KN, KN, AC, PF, LO, AC }, 	 //	 912	 5500
{ AC, AC, TN, TN, JA, SK, AC, AC, AC, TN, KN, AC, AC, AC, AC }, 	 //	 913	 5500
{ AC, AC, AC, AC, TN, SK, AC, AC, AC, ST, KN, LO, WN, AC, AC }, 	 //	 914	 5500
{ AC, TN, AC, WN, JA, SK, AC, AC, AC, TN, KN, AC, AC, KN, AC }, 	 //	 915	 5500
{ AC, TN, AC, AC, KN, SK, AC, AC, AC, AC, KN, AC, AC, PF, LO }, 	 //	 916	 5500
{ AC, TN, AC, AC, QN, SK, AC, AC, AC, KN, KN, AC, AC, LO, AC }, 	 //	 917	 5500
{ AC, TN, AC, WN, JA, SK, AC, AC, AC, TN, KN, AC, AC, KN, AC }, 	 //	 918	 5500
{ AC, TN, AC, WN, QN, SK, AC, AC, AC, KN, KN, AC, AC, KN, AC }, 	 //	 919	 5500
{ AC, AC, AC, AC, JA, SK, AC, AC, AC, TN, KN, AC, PF, AC, AC }, 	 //	 920	 5500
{ AC, AC, TN, AC, QN, SK, AC, AC, AC, KN, KN, AC, AC, AC, AC }, 	 //	 921	 5500
{ AC, AC, AC, AC, JA, SK, AC, AC, AC, TN, KN, PF, PF, LO, AC }, 	 //	 922	 5500
{ AC, AC, AC, AC, KN, SK, AC, AC, AC, AC, KN, PF, PF, LO, LO }, 	 //	 923	 5500
{ AC, AC, AC, WN, AC, SK, AC, AC, AC, AC, KN, PF, PF, KN, AC }, 	 //	 924	 5500
{ AC, AC, AC, TN, AC, SK, AC, AC, AC, AC, KN, PF, PF, AC, AC }, 	 //	 925	 5500
{ AC, AC, AC, PF, LO, SK, AC, AC, AC, AC, KN, PF, WN, AC, AC }, 	 //	 926	 5500
{ AC, AC, AC, KN, AC, SK, AC, AC, AC, AC, KN, PF, WN, PF, AC }, 	 //	 927	 5500
{ AC, KN, TN, TN, LO, SK, AC, AC, AC, AC, KN, SH, AC, AC, AC }, 	 //	 928	 5500
{ AC, KN, AC, AC, JA, SK, AC, AC, AC, TN, KN, SH, AC, PF, AC }, 	 //	 929	 5500
{ AC, KN, AC, AC, AC, SK, AC, AC, AC, AC, KN, SH, WN, AC, AC }, 	 //	 930	 5500
{ SK, SH, TN, PF, AC, KN, AC, AC, AC, LO, KN, AC, AC, AC, AC }, 	 //	 931	 5500
{ SK, AC, SH, TN, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 932	 5500
{ SK, AC, TN, PF, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 933	 5500
{ SK, AC, TN, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 934	 5500
{ SK, AC, AC, WN, AC, KN, AC, AC, AC, AC, KN, LO, AC, KN, CR }, 	 //	 935	 5500
{ SK, AC, AC, KN, AC, KN, AC, AC, AC, LO, KN, LO, AC, PF, AC }, 	 //	 936	 5500
{ SK, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, WN, AC, AC }, 	 //	 937	 5500
{ SK, TN, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, PF, AC, AC }, 	 //	 938	 5500
{ SK, TN, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 939	 5500
{ SK, AC, AC, WN, LO, KN, AC, AC, AC, AC, KN, AC, AC, KN, AC }, 	 //	 940	 5500
{ SK, AC, TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, CR }, 	 //	 941	 5500
{ SK, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, WN, PF, CR }, 	 //	 942	 5500
{ SK, AC, AC, PF, AC, KN, AC, AC, AC, AC, KN, PF, AC, AC, SK }, 	 //	 943	 5500
{ SK, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, PF, WN, LO, AC }, 	 //	 944	 5500
{ SK, AC, AC, AC, TN, KN, AC, AC, AC, AC, KN, PF, WN, PF, AC }, 	 //	 945	 5500
{ SK, KN, AC, PF, AC, KN, AC, AC, AC, AC, KN, SH, AC, AC, SK }, 	 //	 946	 5500
{ KN, SH, TN, AC, TN, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 947	 5500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, WN, LO, AC }, 	 //	 948	 5500
{ KN, SH, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, WN, PF, AC }, 	 //	 949	 5500
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, AC, PF, LO, AC }, 	 //	 950	 5500
{ KN, AC, TN, AC, LO, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 951	 5500
{ KN, AC, AC, WN, AC, KN, AC, AC, AC, LO, KN, AC, AC, KN, AC }, 	 //	 952	 5500
{ KN, AC, AC, KN, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, SK }, 	 //	 953	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, WN, PF, CR }, 	 //	 954	 5500
{ KN, AC, AC, AC, LO, KN, AC, AC, AC, AC, KN, LO, PF, PF, AC }, 	 //	 955	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, LO, KN, LO, WN, LO, AC }, 	 //	 956	 5500
{ KN, WN, AC, PF, AC, KN, AC, AC, AC, AC, KN, KN, AC, AC, SK }, 	 //	 957	 5500
{ KN, WN, AC, WN, TN, KN, AC, AC, AC, AC, KN, KN, AC, KN, AC }, 	 //	 958	 5500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, KN, KN, WN, AC, AC }, 	 //	 959	 5500
{ KN, TN, SH, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK }, 	 //	 960	 5500
{ KN, TN, AC, KN, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, SK }, 	 //	 961	 5500
{ KN, AC, AC, WN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, SK }, 	 //	 962	 5500
{ KN, AC, AC, WN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, SK }, 	 //	 963	 5500
{ KN, AC, SH, TN, AC, KN, AC, AC, AC, AC, KN, PF, AC, AC, AC }, 	 //	 964	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, KN, PF, WN, AC, SK }, 	 //	 965	 5500
{ KN, PF, ST, WN, ST, KN, KN, AC, AC, AC, KN, KN, KN, KN, KN }, 	 //	 966	 5500
{ KN, KN, AC, WN, AC, KN, AC, AC, AC, AC, KN, SH, AC, KN, SK }, 	 //	 967	 5500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, KN, SH, WN, AC, AC }, 	 //	 968	 5500
{ KN, AC, AC, KN, AC, KN, AC, AC, AC, AC, WN, AC, AC, PF, CR }, 	 //	 969	 5500
{ KN, AC, AC, AC, TN, KN, AC, AC, AC, AC, WN, AC, WN, PF, AC }, 	 //	 970	 5500
{ KN, AC, TN, PF, AC, KN, AC, AC, AC, AC, WN, LO, AC, AC, AC }, 	 //	 971	 5500
{ KN, WN, SH, AC, AC, KN, AC, AC, AC, AC, WN, KN, AC, AC, AC }, 	 //	 972	 5500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, WN, KN, PF, AC, AC }, 	 //	 973	 5500
{ KN, WN, AC, AC, AC, KN, AC, AC, AC, AC, WN, KN, WN, AC, AC }, 	 //	 974	 5500
{ KN, TN, AC, KN, AC, KN, AC, AC, AC, AC, WN, AC, AC, PF, CR }, 	 //	 975	 5500
{ KN, TN, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, WN, LO, AC }, 	 //	 976	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, PF, PF, SK }, 	 //	 977	 5500
{ KN, AC, TN, AC, AC, KN, AC, AC, AC, AC, WN, AC, AC, AC, SK }, 	 //	 978	 5500
{ KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, WN, AC, WN, PF, CR }, 	 //	 979	 5500
{ KN, AC, AC, KN, AC, KN, AC, AC, AC, AC, WN, PF, AC, PF, SK }, 	 //	 980	 5500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, WN, SH, PF, PF, AC }, 	 //	 981	 5500
{ KN, KN, AC, WN, AC, KN, AC, AC, AC, LO, WN, SH, AC, KN, AC }, 	 //	 982	 5500
{ KN, KN, AC, AC, AC, KN, AC, AC, AC, AC, WN, SH, WN, LO, AC }, 	 //	 983	 5500
{ KN, AC, AC, WN, AC, WN, AC, AC, AC, AC, QN, LO, AC, KN, SK }, 	 //	 984	 5500
{ KN, AC, TN, AC, AC, WN, AC, AC, AC, AC, QN, LO, AC, AC, AC }, 	 //	 985	 5500
{ KN, WN, TN, AC, AC, WN, AC, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 986	 5500
{ KN, WN, AC, AC, AC, WN, AC, AC, AC, AC, QN, KN, WN, AC, AC }, 	 //	 987	 5500
{ KN, AC, SH, PF, TN, WN, AC, AC, AC, AC, QN, AC, AC, AC, AC }, 	 //	 988	 5500
{ KN, AC, TN, AC, AC, WN, AC, AC, AC, LO, QN, AC, AC, AC, AC }, 	 //	 989	 5500
{ KN, AC, TN, AC, AC, WN, AC, AC, AC, AC, QN, AC, AC, AC, CR }, 	 //	 990	 5500
{ KN, AC, AC, AC, AC, WN, AC, AC, AC, AC, QN, PF, PF, AC, SK }, 	 //	 991	 5500
{ KN, AC, AC, WN, AC, WN, AC, AC, AC, AC, QN, PF, AC, KN, SK }, 	 //	 992	 5500
{ KN, AC, AC, AC, TN, WN, AC, AC, AC, AC, QN, PF, WN, AC, AC }, 	 //	 993	 5500
{ KN, KN, SH, PF, AC, WN, AC, AC, AC, AC, QN, SH, AC, AC, AC }, 	 //	 994	 5500
{ WN, SH, AC, WN, AC, QN, AC, AC, AC, LO, KN, AC, AC, KN, AC }, 	 //	 995	 5500
{ WN, AC, AC, KN, AC, QN, AC, AC, AC, LO, KN, AC, AC, PF, AC }, 	 //	 996	 5500
{ WN, AC, AC, AC, AC, QN, AC, AC, AC, LO, KN, LO, PF, AC, AC }, 	 //	 997	 5500
{ WN, WN, TN, AC, AC, QN, AC, AC, AC, AC, KN, KN, AC, AC, AC }, 	 //	 998	 5500
{ WN, TN, SH, PF, TN, QN, AC, AC, AC, AC, KN, AC, AC, AC, AC }, 	 //	 999	 5500
{ WN, TN, SH, AC, AC, QN, AC, AC, AC, AC, KN, AC, AC, AC, CR }};	 //	 1000	 5500
