unsigned char L5_Outcome_4560[1000][15]={	 //	 0	 4560
{ AC, SH, AC, QN, KN, LO, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 1	 4560
{ AC, SH, AC, QN, KN, LO, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 2	 4560
{ AC, SH, AC, SK, SK, LO, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 3	 4560
{ AC, SH, AC, KN, AC, LO, AC, AC, KN, AC, AC, AC, AC, SK, SK }, 	 //	 4	 4560
{ AC, SH, AC, KN, KN, LO, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 5	 4560
{ AC, SH, AC, KN, SK, LO, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 6	 4560
{ AC, SH, AC, SK, SK, LO, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 7	 4560
{ AC, SH, AC, QN, KN, LO, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 8	 4560
{ AC, SH, AC, QN, AC, LO, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 9	 4560
{ AC, SH, AC, QN, SK, LO, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 10	 4560
{ AC, SH, AC, KN, SK, LO, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 11	 4560
{ AC, AC, AC, QN, KN, LO, AC, AC, QN, KN, AC, LO, AC, SK, SK }, 	 //	 12	 4560
{ AC, AC, AC, QN, KN, LO, AC, AC, SK, SK, AC, LO, AC, JA, QN }, 	 //	 13	 4560
{ AC, AC, AC, QN, SK, LO, AC, AC, SK, KN, AC, LO, AC, JA, KN }, 	 //	 14	 4560
{ AC, AC, AC, KN, KN, LO, AC, AC, KN, KN, AC, LO, AC, SK, SK }, 	 //	 15	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, KN, AC, AC, LO, AC, SK, SK }, 	 //	 16	 4560
{ AC, AC, AC, KN, KN, LO, AC, AC, SK, SK, AC, LO, AC, QN, QN }, 	 //	 17	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, SK, AC, AC, LO, AC, QN, SK }, 	 //	 18	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, SK, SK, AC, LO, AC, QN, KN }, 	 //	 19	 4560
{ AC, AC, AC, QN, KN, LO, AC, AC, SK, KN, AC, LO, AC, JA, SK }, 	 //	 20	 4560
{ AC, AC, AC, QN, KN, LO, AC, AC, SK, SK, AC, LO, AC, JA, QN }, 	 //	 21	 4560
{ AC, AC, AC, QN, SK, LO, AC, AC, SK, KN, AC, LO, AC, JA, KN }, 	 //	 22	 4560
{ AC, AC, AC, KN, KN, LO, AC, AC, KN, KN, AC, LO, AC, SK, SK }, 	 //	 23	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, KN, AC, AC, LO, AC, SK, SK }, 	 //	 24	 4560
{ AC, TN, AC, QN, KN, LO, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 25	 4560
{ AC, TN, AC, QN, SK, LO, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 26	 4560
{ AC, TN, AC, SK, SK, LO, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 27	 4560
{ AC, TN, AC, KN, KN, LO, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 28	 4560
{ AC, TN, AC, KN, SK, LO, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 29	 4560
{ AC, TN, AC, KN, AC, LO, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 30	 4560
{ AC, TN, AC, KN, AC, LO, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 31	 4560
{ AC, TN, AC, SK, SK, LO, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 32	 4560
{ AC, TN, AC, QN, AC, LO, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 33	 4560
{ AC, TN, AC, QN, SK, LO, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 34	 4560
{ AC, TN, AC, KN, KN, LO, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 35	 4560
{ AC, TN, AC, KN, AC, LO, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 36	 4560
{ AC, TN, AC, SK, SK, LO, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 37	 4560
{ AC, AC, AC, QN, AC, LO, AC, AC, QN, AC, AC, PF, AC, SK, SK }, 	 //	 38	 4560
{ AC, AC, AC, QN, KN, LO, AC, AC, SK, KN, AC, PF, AC, JA, SK }, 	 //	 39	 4560
{ AC, AC, AC, QN, AC, LO, AC, AC, SK, AC, AC, PF, AC, JA, SK }, 	 //	 40	 4560
{ AC, AC, AC, SK, SK, LO, AC, AC, JA, KN, AC, PF, AC, JA, KN }, 	 //	 41	 4560
{ AC, AC, AC, KN, KN, LO, AC, AC, SK, KN, AC, PF, AC, QN, SK }, 	 //	 42	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, SK, SK, AC, PF, AC, QN, KN }, 	 //	 43	 4560
{ AC, AC, AC, KN, SK, LO, AC, AC, SK, KN, AC, PF, AC, QN, KN }, 	 //	 44	 4560
{ AC, AC, AC, SK, SK, LO, AC, AC, QN, QN, AC, PF, AC, KN, QN }, 	 //	 45	 4560
{ AC, AC, AC, SK, SK, LO, AC, AC, QN, KN, AC, PF, AC, KN, KN }, 	 //	 46	 4560
{ AC, AC, AC, QN, AC, LO, AC, AC, SK, SK, AC, PF, AC, JA, KN }, 	 //	 47	 4560
{ AC, AC, AC, KN, AC, LO, AC, AC, KN, AC, AC, PF, AC, SK, SK }, 	 //	 48	 4560
{ AC, AC, AC, KN, KN, LO, AC, AC, SK, KN, AC, PF, AC, QN, SK }, 	 //	 49	 4560
{ AC, AC, AC, SK, SK, LO, AC, AC, QN, KN, AC, PF, AC, KN, KN }, 	 //	 50	 4560
{ LO, SH, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 51	 4560
{ LO, SH, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 52	 4560
{ LO, SH, AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 53	 4560
{ LO, SH, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 54	 4560
{ LO, SH, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 55	 4560
{ LO, SH, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 56	 4560
{ LO, SH, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 57	 4560
{ LO, SH, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 58	 4560
{ LO, SH, AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 59	 4560
{ LO, SH, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 60	 4560
{ LO, SH, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 61	 4560
{ LO, SH, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 62	 4560
{ LO, SH, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 63	 4560
{ LO, SH, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 64	 4560
{ LO, SH, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 65	 4560
{ LO, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 66	 4560
{ LO, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 67	 4560
{ LO, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 68	 4560
{ LO, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 69	 4560
{ LO, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 70	 4560
{ LO, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 71	 4560
{ LO, AC, AC, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 72	 4560
{ LO, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 73	 4560
{ LO, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 74	 4560
{ LO, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 75	 4560
{ LO, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 76	 4560
{ LO, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 77	 4560
{ LO, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK }, 	 //	 78	 4560
{ LO, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 79	 4560
{ LO, TN, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 80	 4560
{ LO, TN, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 81	 4560
{ LO, TN, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 82	 4560
{ LO, TN, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 83	 4560
{ LO, TN, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 84	 4560
{ LO, TN, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 85	 4560
{ LO, TN, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 86	 4560
{ LO, TN, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 87	 4560
{ LO, TN, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK }, 	 //	 88	 4560
{ LO, TN, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 89	 4560
{ LO, TN, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 90	 4560
{ LO, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 91	 4560
{ LO, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 92	 4560
{ LO, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 93	 4560
{ LO, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 94	 4560
{ LO, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 95	 4560
{ LO, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 96	 4560
{ LO, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 97	 4560
{ LO, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 98	 4560
{ AC, SH, SH, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 99	 4560
{ AC, SH, SH, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 100	 4560
{ AC, SH, SH, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 101	 4560
{ AC, SH, SH, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 102	 4560
{ AC, SH, SH, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 103	 4560
{ AC, SH, SH, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 104	 4560
{ AC, SH, SH, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 105	 4560
{ AC, SH, SH, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 106	 4560
{ AC, SH, TN, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 107	 4560
{ AC, SH, TN, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 108	 4560
{ AC, SH, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 109	 4560
{ AC, SH, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 110	 4560
{ AC, AC, SH, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 111	 4560
{ AC, AC, SH, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 112	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 113	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 114	 4560
{ AC, AC, SH, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 115	 4560
{ AC, AC, SH, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 116	 4560
{ AC, AC, SH, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 117	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 118	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, PF, SK, SK }, 	 //	 119	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, PF, JA, KN }, 	 //	 120	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, PF, QN, QN }, 	 //	 121	 4560
{ AC, AC, TN, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 122	 4560
{ AC, AC, TN, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 123	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 124	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, WN, SK, SK }, 	 //	 125	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, WN, JA, SK }, 	 //	 126	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, WN, JA, KN }, 	 //	 127	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, WN, JA, QN }, 	 //	 128	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, WN, JA, KN }, 	 //	 129	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, WN, SK, SK }, 	 //	 130	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, WN, QN, KN }, 	 //	 131	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, WN, KN, QN }, 	 //	 132	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, WN, KN, KN }, 	 //	 133	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, LO, PF, SK, SK }, 	 //	 134	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, PF, SK, SK }, 	 //	 135	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, LO, PF, JA, SK }, 	 //	 136	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, LO, PF, JA, KN }, 	 //	 137	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, LO, PF, SK, SK }, 	 //	 138	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, PF, SK, SK }, 	 //	 139	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, LO, PF, QN, SK }, 	 //	 140	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, LO, PF, KN, KN }, 	 //	 141	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, LO, WN, JA, QN }, 	 //	 142	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, LO, WN, SK, SK }, 	 //	 143	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, LO, WN, SK, SK }, 	 //	 144	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, LO, WN, QN, QN }, 	 //	 145	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, LO, WN, QN, KN }, 	 //	 146	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, AC, LO, WN, QN, KN }, 	 //	 147	 4560
{ AC, WN, AC, QN, KN, AC, AC, AC, SK, KN, AC, KN, AC, JA, SK }, 	 //	 148	 4560
{ AC, WN, AC, QN, SK, AC, AC, AC, SK, QN, AC, KN, AC, JA, QN }, 	 //	 149	 4560
{ AC, WN, AC, QN, AC, AC, AC, AC, SK, AC, AC, KN, AC, JA, SK }, 	 //	 150	 4560
{ AC, WN, AC, SK, SK, AC, AC, AC, JA, QN, AC, KN, AC, JA, QN }, 	 //	 151	 4560
{ AC, WN, AC, KN, KN, AC, AC, AC, SK, KN, AC, KN, AC, QN, SK }, 	 //	 152	 4560
{ AC, WN, AC, KN, KN, AC, AC, AC, SK, SK, AC, KN, AC, QN, QN }, 	 //	 153	 4560
{ AC, WN, AC, KN, AC, AC, AC, AC, SK, AC, AC, KN, AC, QN, SK }, 	 //	 154	 4560
{ AC, WN, AC, KN, SK, AC, AC, AC, SK, KN, AC, KN, AC, QN, KN }, 	 //	 155	 4560
{ AC, WN, AC, QN, KN, AC, AC, AC, QN, KN, AC, KN, AC, SK, SK }, 	 //	 156	 4560
{ AC, WN, AC, QN, AC, AC, AC, AC, QN, AC, AC, KN, AC, SK, SK }, 	 //	 157	 4560
{ AC, WN, AC, QN, SK, AC, AC, AC, SK, KN, AC, KN, AC, JA, KN }, 	 //	 158	 4560
{ AC, WN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, AC, SK, SK }, 	 //	 159	 4560
{ AC, WN, AC, KN, AC, AC, AC, AC, SK, AC, AC, KN, AC, QN, SK }, 	 //	 160	 4560
{ AC, WN, AC, SK, SK, AC, AC, AC, QN, QN, AC, KN, AC, KN, QN }, 	 //	 161	 4560
{ AC, TN, SH, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 162	 4560
{ AC, TN, SH, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 163	 4560
{ AC, TN, SH, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 164	 4560
{ AC, TN, SH, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 165	 4560
{ AC, TN, SH, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 166	 4560
{ AC, TN, SH, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 167	 4560
{ AC, TN, SH, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 168	 4560
{ AC, TN, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 169	 4560
{ AC, TN, TN, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 170	 4560
{ AC, TN, TN, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 171	 4560
{ AC, TN, TN, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 172	 4560
{ AC, TN, TN, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 173	 4560
{ AC, TN, TN, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 174	 4560
{ AC, TN, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 175	 4560
{ AC, TN, TN, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 176	 4560
{ AC, AC, SH, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 177	 4560
{ AC, AC, SH, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 178	 4560
{ AC, AC, SH, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 179	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 180	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 181	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 182	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, PF, SK, SK }, 	 //	 183	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, PF, JA, SK }, 	 //	 184	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, PF, JA, KN }, 	 //	 185	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, PF, JA, QN }, 	 //	 186	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, PF, QN, QN }, 	 //	 187	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, PF, KN, KN }, 	 //	 188	 4560
{ AC, AC, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 189	 4560
{ AC, AC, TN, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 190	 4560
{ AC, AC, TN, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 191	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 192	 4560
{ AC, AC, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 193	 4560
{ AC, AC, TN, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 194	 4560
{ AC, AC, TN, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 195	 4560
{ AC, AC, TN, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 196	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 197	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, WN, SK, SK }, 	 //	 198	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, WN, JA, KN }, 	 //	 199	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, WN, JA, KN }, 	 //	 200	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, WN, QN, QN }, 	 //	 201	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, WN, QN, SK }, 	 //	 202	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, WN, QN, KN }, 	 //	 203	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, PF, PF, SK, SK }, 	 //	 204	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, PF, PF, JA, QN }, 	 //	 205	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, AC, PF, PF, JA, SK }, 	 //	 206	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, PF, PF, JA, KN }, 	 //	 207	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, PF, PF, JA, QN }, 	 //	 208	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, PF, PF, JA, KN }, 	 //	 209	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, PF, PF, QN, QN }, 	 //	 210	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, PF, PF, QN, SK }, 	 //	 211	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, AC, PF, WN, JA, SK }, 	 //	 212	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, PF, WN, SK, SK }, 	 //	 213	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, WN, KN, QN }, 	 //	 214	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, PF, WN, KN, KN }, 	 //	 215	 4560
{ AC, KN, AC, QN, KN, AC, AC, AC, QN, KN, AC, SH, AC, SK, SK }, 	 //	 216	 4560
{ AC, KN, AC, QN, KN, AC, AC, AC, SK, SK, AC, SH, AC, JA, QN }, 	 //	 217	 4560
{ AC, KN, AC, QN, SK, AC, AC, AC, SK, KN, AC, SH, AC, JA, KN }, 	 //	 218	 4560
{ AC, KN, AC, KN, KN, AC, AC, AC, SK, KN, AC, SH, AC, QN, SK }, 	 //	 219	 4560
{ AC, KN, AC, SK, SK, AC, AC, AC, QN, KN, AC, SH, AC, KN, KN }, 	 //	 220	 4560
{ AC, KN, AC, QN, SK, AC, AC, AC, SK, QN, AC, SH, AC, JA, QN }, 	 //	 221	 4560
{ AC, KN, AC, QN, SK, AC, AC, AC, SK, KN, AC, SH, AC, JA, KN }, 	 //	 222	 4560
{ AC, KN, AC, KN, AC, AC, AC, AC, KN, AC, AC, SH, AC, SK, SK }, 	 //	 223	 4560
{ AC, KN, AC, SK, SK, AC, AC, AC, QN, KN, AC, SH, AC, KN, KN }, 	 //	 224	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, ST, AC, AC, JA, SK }, 	 //	 225	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, ST, AC, AC, JA, QN }, 	 //	 226	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, ST, AC, AC, JA, QN }, 	 //	 227	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, ST, AC, AC, QN, KN }, 	 //	 228	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, ST, AC, AC, KN, QN }, 	 //	 229	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, ST, AC, AC, SK, SK }, 	 //	 230	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, ST, AC, AC, JA, QN }, 	 //	 231	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, ST, AC, AC, JA, QN }, 	 //	 232	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, ST, AC, AC, JA, QN }, 	 //	 233	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, ST, AC, AC, JA, KN }, 	 //	 234	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, ST, AC, AC, SK, SK }, 	 //	 235	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, ST, AC, AC, QN, SK }, 	 //	 236	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, ST, AC, AC, QN, KN }, 	 //	 237	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, ST, LO, AC, SK, SK }, 	 //	 238	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, ST, LO, AC, JA, QN }, 	 //	 239	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, ST, LO, AC, JA, QN }, 	 //	 240	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, ST, LO, AC, SK, SK }, 	 //	 241	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, ST, LO, AC, KN, QN }, 	 //	 242	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, ST, LO, AC, JA, QN }, 	 //	 243	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, ST, LO, AC, JA, KN }, 	 //	 244	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, ST, LO, AC, SK, SK }, 	 //	 245	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, ST, LO, AC, QN, QN }, 	 //	 246	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, ST, LO, AC, QN, KN }, 	 //	 247	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, ST, AC, AC, JA, SK }, 	 //	 248	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, ST, AC, AC, JA, QN }, 	 //	 249	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, ST, AC, AC, JA, SK }, 	 //	 250	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, ST, AC, AC, JA, QN }, 	 //	 251	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, ST, AC, AC, JA, KN }, 	 //	 252	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, ST, AC, AC, SK, SK }, 	 //	 253	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, ST, AC, AC, QN, SK }, 	 //	 254	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, ST, AC, AC, KN, KN }, 	 //	 255	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, ST, AC, AC, JA, SK }, 	 //	 256	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, ST, AC, AC, QN, QN }, 	 //	 257	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, ST, AC, AC, QN, SK }, 	 //	 258	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, ST, PF, AC, JA, QN }, 	 //	 259	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, ST, PF, AC, JA, QN }, 	 //	 260	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, ST, PF, AC, JA, KN }, 	 //	 261	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, ST, PF, AC, SK, SK }, 	 //	 262	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, ST, PF, AC, SK, SK }, 	 //	 263	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, ST, PF, AC, QN, SK }, 	 //	 264	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, ST, PF, AC, QN, QN }, 	 //	 265	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, ST, PF, AC, QN, KN }, 	 //	 266	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, ST, PF, AC, JA, SK }, 	 //	 267	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, ST, PF, AC, JA, SK }, 	 //	 268	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, ST, PF, AC, JA, QN }, 	 //	 269	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, ST, PF, AC, QN, SK }, 	 //	 270	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, ST, PF, AC, QN, QN }, 	 //	 271	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, ST, PF, AC, KN, QN }, 	 //	 272	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, ST, PF, AC, KN, KN }, 	 //	 273	 4560
{ KN, KN, KN, KN, KN, KN, KN, PF, SK, SK, KN, SK, QN, QN, QN }, 	 //	 274	 4560
{ KN, QN, SH, PF, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 275	 4560
{ KN, QN, SH, TN, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 276	 4560
{ KN, QN, SH, TN, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 277	 4560
{ KN, QN, SH, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 278	 4560
{ KN, QN, AC, PF, TN, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 279	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, LO, SK }, 	 //	 280	 4560
{ KN, QN, AC, WN, AC, KN, QN, AC, AC, AC, SK, SK, AC, KN, AC }, 	 //	 281	 4560
{ KN, QN, AC, TN, AC, KN, QN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 282	 4560
{ KN, QN, AC, TN, TN, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 283	 4560
{ KN, QN, AC, AC, TN, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 284	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, PF, CR }, 	 //	 285	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, PF, AC, AC }, 	 //	 286	 4560
{ KN, QN, TN, PF, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 287	 4560
{ KN, QN, TN, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 288	 4560
{ KN, QN, TN, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 289	 4560
{ KN, QN, AC, PF, AC, KN, QN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 290	 4560
{ KN, QN, AC, PF, LO, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 291	 4560
{ KN, QN, AC, AC, LO, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 292	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, AC, SK }, 	 //	 293	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, LO, SK, SK, AC, LO, AC }, 	 //	 294	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, LO, CR }, 	 //	 295	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, LO, SK }, 	 //	 296	 4560
{ KN, QN, AC, TN, AC, KN, QN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 297	 4560
{ KN, QN, AC, AC, TN, KN, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 298	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, LO, SK, SK, AC, PF, AC }, 	 //	 299	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, AC, PF, CR }, 	 //	 300	 4560
{ KN, QN, AC, KN, AC, KN, QN, AC, AC, AC, SK, SK, AC, PF, AC }, 	 //	 301	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, WN, LO, AC }, 	 //	 302	 4560
{ KN, QN, AC, AC, AC, KN, QN, AC, AC, AC, SK, SK, WN, PF, AC }, 	 //	 303	 4560
{ KN, QN, SH, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 304	 4560
{ KN, QN, SH, TN, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 305	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, LO, SK, JA, AC, LO, AC }, 	 //	 306	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, LO, SK }, 	 //	 307	 4560
{ KN, QN, AC, TN, LO, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 308	 4560
{ KN, QN, AC, TN, TN, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 309	 4560
{ KN, QN, AC, AC, LO, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 310	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, CR }, 	 //	 311	 4560
{ KN, QN, AC, AC, TN, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 312	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, SK }, 	 //	 313	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, PF, CR }, 	 //	 314	 4560
{ KN, QN, AC, KN, AC, KN, SK, AC, AC, AC, SK, JA, AC, PF, AC }, 	 //	 315	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, PF, AC, AC }, 	 //	 316	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, PF, LO, AC }, 	 //	 317	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, PF, PF, AC }, 	 //	 318	 4560
{ KN, QN, TN, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 319	 4560
{ KN, QN, TN, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 320	 4560
{ KN, QN, TN, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 321	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, CR }, 	 //	 322	 4560
{ KN, QN, AC, AC, TN, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 323	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, LO, CR }, 	 //	 324	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, LO, SK }, 	 //	 325	 4560
{ KN, QN, AC, TN, AC, KN, SK, AC, AC, LO, SK, JA, AC, AC, AC }, 	 //	 326	 4560
{ KN, QN, AC, AC, LO, KN, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 327	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, AC, SK }, 	 //	 328	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, PF, CR }, 	 //	 329	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, AC, PF, SK }, 	 //	 330	 4560
{ KN, QN, AC, AC, AC, KN, SK, AC, AC, AC, SK, JA, WN, PF, AC }, 	 //	 331	 4560
{ KN, KN, SH, PF, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 332	 4560
{ KN, KN, SH, PF, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 333	 4560
{ KN, KN, SH, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 334	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, CR }, 	 //	 335	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, SK }, 	 //	 336	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, LO, SK }, 	 //	 337	 4560
{ KN, KN, AC, TN, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 338	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, SK }, 	 //	 339	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, LO, SK, SK, AC, PF, AC }, 	 //	 340	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, PF, CR }, 	 //	 341	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, PF, AC, AC }, 	 //	 342	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, PF, PF, AC }, 	 //	 343	 4560
{ KN, KN, TN, TN, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 344	 4560
{ KN, KN, TN, TN, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 345	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, LO, CR }, 	 //	 346	 4560
{ KN, KN, AC, WN, AC, KN, KN, AC, AC, AC, SK, SK, AC, KN, AC }, 	 //	 347	 4560
{ KN, KN, AC, TN, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 348	 4560
{ KN, KN, AC, AC, LO, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 349	 4560
{ KN, KN, AC, AC, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 350	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, PF, CR }, 	 //	 351	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, WN, AC, AC }, 	 //	 352	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, WN, LO, AC }, 	 //	 353	 4560
{ KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, WN, AC, AC }, 	 //	 354	 4560
{ KN, KN, AC, AC, AC, KN, KN, KN, KN, KN, SK, SK, WN, QN, QN }, 	 //	 355	 4560
{ KN, KN, SH, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 356	 4560
{ KN, KN, SH, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 357	 4560
{ KN, KN, SH, TN, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 358	 4560
{ KN, KN, AC, PF, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 359	 4560
{ KN, KN, AC, AC, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 360	 4560
{ KN, KN, AC, WN, AC, KN, SK, AC, AC, AC, SK, QN, AC, KN, AC }, 	 //	 361	 4560
{ KN, KN, AC, TN, AC, KN, SK, AC, AC, LO, SK, QN, AC, AC, AC }, 	 //	 362	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, SK }, 	 //	 363	 4560
{ KN, KN, AC, KN, AC, KN, SK, AC, AC, AC, SK, QN, AC, PF, AC }, 	 //	 364	 4560
{ KN, KN, AC, KN, AC, KN, SK, AC, AC, AC, SK, QN, AC, PF, AC }, 	 //	 365	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, AC, AC }, 	 //	 366	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, AC, AC }, 	 //	 367	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, LO, AC }, 	 //	 368	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, LO, AC }, 	 //	 369	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, AC, AC }, 	 //	 370	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, PF, PF, AC }, 	 //	 371	 4560
{ KN, KN, TN, TN, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 372	 4560
{ KN, KN, TN, TN, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 373	 4560
{ KN, KN, TN, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 374	 4560
{ KN, KN, TN, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 375	 4560
{ KN, KN, AC, PF, AC, KN, SK, AC, AC, LO, SK, QN, AC, AC, AC }, 	 //	 376	 4560
{ KN, KN, AC, PF, LO, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 377	 4560
{ KN, KN, AC, AC, LO, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 378	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, SK }, 	 //	 379	 4560
{ KN, KN, AC, WN, AC, KN, SK, AC, AC, AC, SK, QN, AC, KN, AC }, 	 //	 380	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, SK }, 	 //	 381	 4560
{ KN, KN, AC, KN, AC, KN, SK, AC, AC, AC, SK, QN, AC, PF, AC }, 	 //	 382	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, WN, AC, AC }, 	 //	 383	 4560
{ KN, KN, AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, WN, AC, AC }, 	 //	 384	 4560
{ KN, KN, KN, KN, KN, SK, ST, PF, SK, SK, QN, QN, QN, QN, QN }, 	 //	 385	 4560
{ KN, QN, SH, TN, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 386	 4560
{ KN, QN, SH, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 387	 4560
{ KN, QN, AC, PF, LO, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 388	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, LO, QN, JA, AC, LO, AC }, 	 //	 389	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, LO, SK }, 	 //	 390	 4560
{ KN, QN, AC, WN, AC, SK, SK, AC, AC, AC, QN, JA, AC, KN, AC }, 	 //	 391	 4560
{ KN, QN, AC, TN, TN, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 392	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, SK }, 	 //	 393	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, PF, CR }, 	 //	 394	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, PF, SK }, 	 //	 395	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, PF, AC, AC }, 	 //	 396	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, PF, AC, AC }, 	 //	 397	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, PF, AC, AC }, 	 //	 398	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, PF, PF, AC }, 	 //	 399	 4560
{ KN, QN, TN, PF, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 400	 4560
{ KN, QN, TN, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 401	 4560
{ KN, QN, TN, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 402	 4560
{ KN, QN, TN, TN, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 403	 4560
{ KN, QN, TN, TN, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 404	 4560
{ KN, QN, TN, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 405	 4560
{ KN, QN, AC, PF, AC, SK, SK, AC, AC, LO, QN, JA, AC, AC, AC }, 	 //	 406	 4560
{ KN, QN, AC, AC, LO, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 407	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, LO, SK }, 	 //	 408	 4560
{ KN, QN, AC, AC, LO, SK, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 409	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, AC, SK }, 	 //	 410	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, AC, PF, CR }, 	 //	 411	 4560
{ KN, QN, AC, KN, AC, SK, SK, AC, AC, AC, QN, JA, AC, PF, AC }, 	 //	 412	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, WN, AC, AC }, 	 //	 413	 4560
{ KN, QN, AC, AC, AC, SK, SK, AC, AC, AC, QN, JA, WN, LO, AC }, 	 //	 414	 4560
{ KN, KN, SH, PF, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 415	 4560
{ KN, KN, SH, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 416	 4560
{ KN, KN, AC, PF, LO, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 417	 4560
{ KN, KN, AC, PF, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 418	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, CR }, 	 //	 419	 4560
{ KN, KN, AC, AC, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 420	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, LO, QN, QN, AC, LO, AC }, 	 //	 421	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, LO, SK }, 	 //	 422	 4560
{ KN, KN, AC, WN, AC, SK, SK, AC, AC, AC, QN, QN, AC, KN, AC }, 	 //	 423	 4560
{ KN, KN, AC, TN, AC, SK, SK, AC, AC, LO, QN, QN, AC, AC, AC }, 	 //	 424	 4560
{ KN, KN, AC, TN, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 425	 4560
{ KN, KN, AC, AC, LO, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 426	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, SK }, 	 //	 427	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, CR }, 	 //	 428	 4560
{ KN, KN, AC, KN, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, AC }, 	 //	 429	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, PF, AC, AC }, 	 //	 430	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, PF, AC, AC }, 	 //	 431	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, PF, PF, AC }, 	 //	 432	 4560
{ KN, KN, TN, PF, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 433	 4560
{ KN, KN, TN, TN, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 434	 4560
{ KN, KN, TN, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 435	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, CR }, 	 //	 436	 4560
{ KN, KN, AC, AC, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 437	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, LO, QN, QN, AC, LO, AC }, 	 //	 438	 4560
{ KN, KN, AC, TN, AC, SK, SK, AC, AC, LO, QN, QN, AC, AC, AC }, 	 //	 439	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, SK }, 	 //	 440	 4560
{ KN, KN, AC, KN, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, AC }, 	 //	 441	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, WN, AC, AC }, 	 //	 442	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, WN, AC, AC }, 	 //	 443	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, WN, AC, AC }, 	 //	 444	 4560
{ KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, WN, PF, AC }, 	 //	 445	 4560
{ KN, KN, KN, KN, KN, SK, SK, PF, KN, KN, QN, QN, QN, KN, KN }, 	 //	 446	 4560
{ KN, KN, KN, KN, KN, SK, SK, PF, KN, KN, QN, QN, QN, WN, KN }, 	 //	 447	 4560
{ KN, KN, KN, KN, KN, SK, SK, PF, WN, SK, QN, QN, QN, QN, QN }, 	 //	 448	 4560
{ KN, KN, KN, KN, KN, SK, SK, PF, KN, KN, QN, QN, QN, KN, KN }, 	 //	 449	 4560
{ KN, KN, KN, KN, KN, SK, SK, PF, KN, KN, QN, QN, QN, KN, KN }, 	 //	 450	 4560
{ SK, QN, SH, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 451	 4560
{ SK, QN, SH, TN, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 452	 4560
{ SK, QN, SH, TN, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 453	 4560
{ SK, QN, SH, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 454	 4560
{ SK, QN, AC, PF, TN, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 455	 4560
{ SK, QN, AC, AC, LO, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 456	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, LO, CR }, 	 //	 457	 4560
{ SK, QN, AC, TN, AC, QN, SK, AC, AC, LO, QN, JA, AC, AC, AC }, 	 //	 458	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, PF, CR }, 	 //	 459	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, PF, LO, AC }, 	 //	 460	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, PF, LO, AC }, 	 //	 461	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, PF, PF, AC }, 	 //	 462	 4560
{ SK, QN, TN, PF, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 463	 4560
{ SK, QN, TN, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 464	 4560
{ SK, QN, AC, AC, TN, QN, SK, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 465	 4560
{ SK, QN, AC, WN, AC, QN, SK, AC, AC, AC, QN, JA, AC, KN, AC }, 	 //	 466	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, AC, SK }, 	 //	 467	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, AC, PF, SK }, 	 //	 468	 4560
{ SK, QN, AC, KN, AC, QN, SK, AC, AC, AC, QN, JA, AC, PF, AC }, 	 //	 469	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, WN, LO, AC }, 	 //	 470	 4560
{ SK, QN, AC, AC, AC, QN, SK, AC, AC, AC, QN, JA, WN, AC, AC }, 	 //	 471	 4560
{ SK, SK, SH, PF, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 472	 4560
{ SK, SK, SH, PF, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 473	 4560
{ SK, SK, SH, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 474	 4560
{ SK, SK, AC, PF, LO, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 475	 4560
{ SK, SK, AC, PF, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 476	 4560
{ SK, SK, AC, AC, TN, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 477	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, LO, QN, JA, AC, LO, AC }, 	 //	 478	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, LO, CR }, 	 //	 479	 4560
{ SK, SK, AC, WN, AC, QN, JA, AC, AC, AC, QN, JA, AC, KN, AC }, 	 //	 480	 4560
{ SK, SK, AC, AC, LO, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 481	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, CR }, 	 //	 482	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, PF, SK }, 	 //	 483	 4560
{ SK, SK, AC, KN, AC, QN, JA, AC, AC, AC, QN, JA, AC, PF, AC }, 	 //	 484	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, PF, AC, AC }, 	 //	 485	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, PF, AC, AC }, 	 //	 486	 4560
{ SK, SK, TN, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 487	 4560
{ SK, SK, TN, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 488	 4560
{ SK, SK, TN, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 489	 4560
{ SK, SK, TN, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 490	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, AC, CR }, 	 //	 491	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, AC, LO, CR }, 	 //	 492	 4560
{ SK, SK, AC, AC, LO, QN, JA, AC, AC, AC, QN, JA, AC, AC, AC }, 	 //	 493	 4560
{ SK, SK, AC, KN, AC, QN, JA, AC, AC, AC, QN, JA, AC, PF, AC }, 	 //	 494	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, WN, AC, AC }, 	 //	 495	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, WN, AC, AC }, 	 //	 496	 4560
{ SK, SK, AC, AC, AC, QN, JA, AC, AC, AC, QN, JA, WN, PF, AC }, 	 //	 497	 4560
{ SK, KN, SH, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 498	 4560
{ SK, KN, SH, TN, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 499	 4560
{ SK, KN, SH, TN, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 500	 4560
{ SK, KN, SH, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 501	 4560
{ SK, KN, SH, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 502	 4560
{ SK, KN, AC, AC, LO, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 503	 4560
{ SK, KN, AC, AC, TN, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 504	 4560
{ SK, KN, AC, TN, AC, QN, SK, AC, AC, LO, QN, QN, AC, AC, AC }, 	 //	 505	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, CR }, 	 //	 506	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, SK }, 	 //	 507	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, PF, SK }, 	 //	 508	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, PF, LO, AC }, 	 //	 509	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, PF, AC, AC }, 	 //	 510	 4560
{ SK, KN, TN, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 511	 4560
{ SK, KN, TN, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 512	 4560
{ SK, KN, TN, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 513	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, AC, AC, CR }, 	 //	 514	 4560
{ SK, KN, AC, TN, TN, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 515	 4560
{ SK, KN, AC, AC, LO, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 516	 4560
{ SK, KN, AC, AC, TN, QN, SK, AC, AC, AC, QN, QN, AC, AC, AC }, 	 //	 517	 4560
{ SK, KN, AC, KN, AC, QN, SK, AC, AC, AC, QN, QN, AC, PF, AC }, 	 //	 518	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, WN, AC, AC }, 	 //	 519	 4560
{ SK, KN, AC, AC, AC, QN, SK, AC, AC, AC, QN, QN, WN, AC, AC }, 	 //	 520	 4560
{ SK, SK, SH, PF, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 521	 4560
{ SK, SK, SH, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 522	 4560
{ SK, SK, SH, TN, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 523	 4560
{ SK, SK, SH, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 524	 4560
{ SK, SK, AC, PF, LO, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 525	 4560
{ SK, SK, AC, AC, LO, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 526	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, SK }, 	 //	 527	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, LO, QN, KN, AC, LO, AC }, 	 //	 528	 4560
{ SK, SK, AC, TN, AC, QN, QN, AC, AC, LO, QN, KN, AC, AC, AC }, 	 //	 529	 4560
{ SK, SK, AC, AC, LO, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 530	 4560
{ SK, SK, AC, AC, TN, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 531	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, SK }, 	 //	 532	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, LO, QN, KN, AC, PF, AC }, 	 //	 533	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, PF, LO, AC }, 	 //	 534	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, PF, PF, AC }, 	 //	 535	 4560
{ SK, SK, TN, TN, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 536	 4560
{ SK, SK, TN, AC, AC, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 537	 4560
{ SK, SK, AC, PF, LO, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 538	 4560
{ SK, SK, AC, TN, TN, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 539	 4560
{ SK, SK, AC, AC, TN, QN, QN, AC, AC, AC, QN, KN, AC, AC, AC }, 	 //	 540	 4560
{ SK, SK, AC, KN, AC, QN, QN, AC, AC, AC, QN, KN, AC, PF, AC }, 	 //	 541	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, WN, AC, AC }, 	 //	 542	 4560
{ SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, QN, KN, WN, PF, AC }, 	 //	 543	 4560
{ QN, ST, QN, SK, SK, QN, QN, QN, QN, QN, QN, QN, QN, KN, QN }, 	 //	 544	 4560
{ QN, QN, QN, QN, QN, QN, QN, QN, QN, QN, QN, QN, SK, SK, QN }, 	 //	 545	 4560
{ ST, WN, QN, SK, SK, AC, AC, AC, QN, KN, KN, KN, KN, KN, KN }, 	 //	 546	 4560
{ TN, SH, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 547	 4560
{ TN, SH, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 548	 4560
{ TN, SH, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 549	 4560
{ TN, SH, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK }, 	 //	 550	 4560
{ TN, SH, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 551	 4560
{ TN, SH, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 552	 4560
{ TN, SH, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 553	 4560
{ TN, SH, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 554	 4560
{ TN, SH, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 555	 4560
{ TN, SH, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 556	 4560
{ TN, SH, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 557	 4560
{ TN, SH, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 558	 4560
{ TN, SH, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 559	 4560
{ TN, SH, AC, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 560	 4560
{ TN, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 561	 4560
{ TN, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 562	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 563	 4560
{ TN, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 564	 4560
{ TN, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 565	 4560
{ TN, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 566	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 567	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 568	 4560
{ TN, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 569	 4560
{ TN, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 570	 4560
{ TN, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 571	 4560
{ TN, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 572	 4560
{ TN, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 573	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 574	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 575	 4560
{ TN, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, AC, SK, SK }, 	 //	 576	 4560
{ TN, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 577	 4560
{ TN, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 578	 4560
{ TN, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 579	 4560
{ TN, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 580	 4560
{ TN, TN, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 581	 4560
{ TN, TN, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 582	 4560
{ TN, TN, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 583	 4560
{ TN, TN, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 584	 4560
{ TN, TN, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 585	 4560
{ TN, TN, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 586	 4560
{ TN, TN, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 587	 4560
{ TN, TN, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 588	 4560
{ TN, TN, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 589	 4560
{ TN, TN, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 590	 4560
{ TN, TN, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 591	 4560
{ TN, TN, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 592	 4560
{ TN, TN, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 593	 4560
{ TN, TN, AC, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 594	 4560
{ TN, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 595	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 596	 4560
{ TN, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 597	 4560
{ TN, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 598	 4560
{ TN, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 599	 4560
{ TN, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 600	 4560
{ AC, SH, SH, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 601	 4560
{ AC, SH, SH, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 602	 4560
{ AC, SH, SH, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 603	 4560
{ AC, SH, SH, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 604	 4560
{ AC, SH, SH, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 605	 4560
{ AC, SH, SH, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 606	 4560
{ AC, SH, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 607	 4560
{ AC, SH, TN, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 608	 4560
{ AC, SH, TN, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 609	 4560
{ AC, SH, TN, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 610	 4560
{ AC, SH, TN, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 611	 4560
{ AC, AC, SH, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 612	 4560
{ AC, AC, SH, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 613	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 614	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 615	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, SK, KN, AC, AC, AC, QN, SK }, 	 //	 616	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 617	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, QN, KN, AC, AC, AC, KN, KN }, 	 //	 618	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, PF, JA, QN }, 	 //	 619	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, AC, PF, JA, KN }, 	 //	 620	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, PF, JA, KN }, 	 //	 621	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, PF, QN, SK }, 	 //	 622	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, AC, PF, QN, QN }, 	 //	 623	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, AC, PF, QN, KN }, 	 //	 624	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, AC, PF, KN, QN }, 	 //	 625	 4560
{ AC, AC, TN, QN, KN, AC, AC, AC, QN, KN, AC, AC, AC, SK, SK }, 	 //	 626	 4560
{ AC, AC, TN, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 627	 4560
{ AC, AC, TN, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 628	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 629	 4560
{ AC, AC, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 630	 4560
{ AC, AC, TN, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 631	 4560
{ AC, AC, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 632	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 633	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, WN, JA, QN }, 	 //	 634	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, AC, WN, JA, KN }, 	 //	 635	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, WN, JA, QN }, 	 //	 636	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, LO, PF, SK, SK }, 	 //	 637	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, PF, SK, SK }, 	 //	 638	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, LO, PF, JA, SK }, 	 //	 639	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, LO, PF, JA, QN }, 	 //	 640	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, LO, PF, JA, QN }, 	 //	 641	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, LO, PF, JA, QN }, 	 //	 642	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, LO, PF, JA, KN }, 	 //	 643	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, LO, PF, SK, SK }, 	 //	 644	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, LO, PF, QN, SK }, 	 //	 645	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, LO, PF, QN, QN }, 	 //	 646	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, LO, PF, KN, KN }, 	 //	 647	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, WN, SK, SK }, 	 //	 648	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, AC, LO, WN, JA, SK }, 	 //	 649	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, LO, WN, JA, QN }, 	 //	 650	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, LO, WN, QN, QN }, 	 //	 651	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, LO, WN, QN, SK }, 	 //	 652	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, AC, LO, WN, QN, KN }, 	 //	 653	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, LO, WN, KN, QN }, 	 //	 654	 4560
{ AC, WN, AC, QN, AC, AC, AC, AC, QN, AC, AC, KN, AC, SK, SK }, 	 //	 655	 4560
{ AC, WN, AC, QN, KN, AC, AC, AC, SK, KN, AC, KN, AC, JA, SK }, 	 //	 656	 4560
{ AC, WN, AC, QN, AC, AC, AC, AC, SK, SK, AC, KN, AC, JA, KN }, 	 //	 657	 4560
{ AC, WN, AC, SK, SK, AC, AC, AC, JA, KN, AC, KN, AC, JA, KN }, 	 //	 658	 4560
{ AC, WN, AC, KN, KN, AC, AC, AC, KN, KN, AC, KN, AC, SK, SK }, 	 //	 659	 4560
{ AC, WN, AC, KN, AC, AC, AC, AC, KN, AC, AC, KN, AC, SK, SK }, 	 //	 660	 4560
{ AC, WN, AC, KN, KN, AC, AC, AC, SK, SK, AC, KN, AC, QN, QN }, 	 //	 661	 4560
{ AC, WN, AC, SK, SK, AC, AC, AC, QN, KN, AC, KN, AC, KN, KN }, 	 //	 662	 4560
{ AC, WN, AC, QN, KN, AC, AC, AC, SK, KN, AC, KN, AC, JA, SK }, 	 //	 663	 4560
{ AC, WN, AC, KN, SK, AC, AC, AC, SK, QN, AC, KN, AC, QN, QN }, 	 //	 664	 4560
{ AC, WN, AC, KN, AC, AC, AC, AC, SK, SK, AC, KN, AC, QN, KN }, 	 //	 665	 4560
{ AC, TN, SH, QN, AC, AC, AC, AC, QN, AC, AC, AC, AC, SK, SK }, 	 //	 666	 4560
{ AC, TN, SH, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 667	 4560
{ AC, TN, SH, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 668	 4560
{ AC, TN, SH, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 669	 4560
{ AC, TN, SH, KN, AC, AC, AC, AC, SK, AC, AC, AC, AC, QN, SK }, 	 //	 670	 4560
{ AC, TN, SH, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 671	 4560
{ AC, TN, SH, SK, SK, AC, AC, AC, QN, QN, AC, AC, AC, KN, QN }, 	 //	 672	 4560
{ AC, TN, TN, QN, AC, AC, AC, AC, SK, AC, AC, AC, AC, JA, SK }, 	 //	 673	 4560
{ AC, TN, TN, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 674	 4560
{ AC, TN, TN, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 675	 4560
{ AC, TN, TN, KN, KN, AC, AC, AC, KN, KN, AC, AC, AC, SK, SK }, 	 //	 676	 4560
{ AC, TN, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 677	 4560
{ AC, TN, TN, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 678	 4560
{ AC, TN, TN, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 679	 4560
{ AC, AC, SH, QN, KN, AC, AC, AC, SK, SK, AC, AC, AC, JA, QN }, 	 //	 680	 4560
{ AC, AC, SH, QN, SK, AC, AC, AC, SK, QN, AC, AC, AC, JA, QN }, 	 //	 681	 4560
{ AC, AC, SH, QN, AC, AC, AC, AC, SK, SK, AC, AC, AC, JA, KN }, 	 //	 682	 4560
{ AC, AC, SH, QN, SK, AC, AC, AC, SK, KN, AC, AC, AC, JA, KN }, 	 //	 683	 4560
{ AC, AC, SH, SK, SK, AC, AC, AC, JA, QN, AC, AC, AC, JA, QN }, 	 //	 684	 4560
{ AC, AC, SH, KN, KN, AC, AC, AC, SK, SK, AC, AC, AC, QN, QN }, 	 //	 685	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, AC, PF, SK, SK }, 	 //	 686	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, PF, SK, SK }, 	 //	 687	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, PF, JA, QN }, 	 //	 688	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, AC, PF, JA, QN }, 	 //	 689	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, AC, PF, SK, SK }, 	 //	 690	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, AC, PF, QN, SK }, 	 //	 691	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, AC, AC, PF, QN, QN }, 	 //	 692	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, PF, QN, SK }, 	 //	 693	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, AC, AC, PF, KN, KN }, 	 //	 694	 4560
{ AC, AC, TN, QN, KN, AC, AC, AC, SK, KN, AC, AC, AC, JA, SK }, 	 //	 695	 4560
{ AC, AC, TN, SK, SK, AC, AC, AC, JA, KN, AC, AC, AC, JA, KN }, 	 //	 696	 4560
{ AC, AC, TN, KN, SK, AC, AC, AC, SK, QN, AC, AC, AC, QN, QN }, 	 //	 697	 4560
{ AC, AC, TN, KN, AC, AC, AC, AC, SK, SK, AC, AC, AC, QN, KN }, 	 //	 698	 4560
{ AC, AC, TN, KN, SK, AC, AC, AC, SK, KN, AC, AC, AC, QN, KN }, 	 //	 699	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, WN, SK, SK }, 	 //	 700	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, AC, AC, WN, JA, QN }, 	 //	 701	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, AC, WN, JA, QN }, 	 //	 702	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, AC, AC, WN, JA, KN }, 	 //	 703	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, WN, QN, SK }, 	 //	 704	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, PF, PF, SK, SK }, 	 //	 705	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, PF, PF, JA, QN }, 	 //	 706	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, AC, PF, PF, JA, KN }, 	 //	 707	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, AC, PF, PF, JA, KN }, 	 //	 708	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, AC, PF, PF, JA, QN }, 	 //	 709	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, PF, PF, SK, SK }, 	 //	 710	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, PF, SK, SK }, 	 //	 711	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, AC, PF, PF, QN, QN }, 	 //	 712	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, AC, PF, PF, QN, KN }, 	 //	 713	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, AC, PF, WN, SK, SK }, 	 //	 714	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, AC, PF, WN, SK, SK }, 	 //	 715	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, AC, PF, WN, JA, SK }, 	 //	 716	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, AC, PF, WN, JA, QN }, 	 //	 717	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, AC, PF, WN, SK, SK }, 	 //	 718	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, AC, PF, WN, SK, SK }, 	 //	 719	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, AC, PF, WN, QN, SK }, 	 //	 720	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, AC, PF, WN, QN, SK }, 	 //	 721	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, AC, PF, WN, QN, KN }, 	 //	 722	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, AC, PF, WN, KN, QN }, 	 //	 723	 4560
{ AC, KN, AC, QN, KN, AC, AC, AC, SK, KN, AC, SH, AC, JA, SK }, 	 //	 724	 4560
{ AC, KN, AC, SK, SK, AC, AC, AC, JA, KN, AC, SH, AC, JA, KN }, 	 //	 725	 4560
{ AC, KN, AC, KN, KN, AC, AC, AC, KN, KN, AC, SH, AC, SK, SK }, 	 //	 726	 4560
{ AC, KN, AC, KN, AC, AC, AC, AC, KN, AC, AC, SH, AC, SK, SK }, 	 //	 727	 4560
{ AC, KN, AC, KN, KN, AC, AC, AC, SK, KN, AC, SH, AC, QN, SK }, 	 //	 728	 4560
{ AC, KN, AC, KN, KN, AC, AC, AC, SK, SK, AC, SH, AC, QN, QN }, 	 //	 729	 4560
{ AC, KN, AC, KN, SK, AC, AC, AC, SK, QN, AC, SH, AC, QN, QN }, 	 //	 730	 4560
{ AC, KN, AC, KN, SK, AC, AC, AC, SK, KN, AC, SH, AC, QN, KN }, 	 //	 731	 4560
{ AC, KN, AC, QN, KN, AC, AC, AC, SK, KN, AC, SH, AC, JA, SK }, 	 //	 732	 4560
{ AC, KN, AC, QN, KN, AC, AC, AC, SK, SK, AC, SH, AC, JA, QN }, 	 //	 733	 4560
{ AC, KN, AC, QN, AC, AC, AC, AC, SK, AC, AC, SH, AC, JA, SK }, 	 //	 734	 4560
{ AC, KN, AC, QN, AC, AC, AC, AC, SK, SK, AC, SH, AC, JA, KN }, 	 //	 735	 4560
{ AC, KN, AC, KN, AC, AC, AC, AC, SK, AC, AC, SH, AC, QN, SK }, 	 //	 736	 4560
{ AC, KN, AC, KN, SK, AC, AC, AC, SK, KN, AC, SH, AC, QN, KN }, 	 //	 737	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, SK, AC, AC, JA, QN }, 	 //	 738	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, SK, AC, AC, JA, KN }, 	 //	 739	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, SK, AC, AC, JA, KN }, 	 //	 740	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, SK, AC, AC, QN, SK }, 	 //	 741	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, SK, AC, AC, QN, QN }, 	 //	 742	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, SK, AC, AC, KN, KN }, 	 //	 743	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, AC, AC, SK, SK }, 	 //	 744	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, SK, AC, AC, JA, SK }, 	 //	 745	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, SK, AC, AC, JA, KN }, 	 //	 746	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, SK, AC, AC, JA, KN }, 	 //	 747	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, SK, AC, AC, SK, SK }, 	 //	 748	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, SK, AC, AC, QN, QN }, 	 //	 749	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, SK, AC, AC, QN, SK }, 	 //	 750	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, SK, LO, AC, JA, QN }, 	 //	 751	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, SK, LO, AC, JA, KN }, 	 //	 752	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, KN, KN, SK, LO, AC, SK, SK }, 	 //	 753	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, SK, SK, LO, AC, QN, QN }, 	 //	 754	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, SK, LO, AC, QN, KN }, 	 //	 755	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, SK, LO, AC, KN, KN }, 	 //	 756	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, LO, AC, SK, SK }, 	 //	 757	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, SK, LO, AC, JA, SK }, 	 //	 758	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, QN, SK, LO, AC, JA, QN }, 	 //	 759	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, SK, LO, AC, JA, SK }, 	 //	 760	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, SK, LO, AC, JA, KN }, 	 //	 761	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, SK, LO, AC, SK, SK }, 	 //	 762	 4560
{ AC, QN, SH, PF, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 763	 4560
{ AC, QN, SH, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 764	 4560
{ AC, QN, SH, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 765	 4560
{ AC, QN, AC, PF, LO, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 766	 4560
{ AC, QN, AC, AC, LO, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 767	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, LO, SK }, 	 //	 768	 4560
{ AC, QN, AC, TN, AC, AC, QN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 769	 4560
{ AC, QN, AC, AC, LO, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 770	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, SK }, 	 //	 771	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, PF, CR }, 	 //	 772	 4560
{ AC, QN, AC, KN, AC, AC, QN, AC, AC, AC, SK, SK, AC, PF, AC }, 	 //	 773	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, PF, AC, AC }, 	 //	 774	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, PF, LO, AC }, 	 //	 775	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, PF, PF, AC }, 	 //	 776	 4560
{ AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 777	 4560
{ AC, QN, TN, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 778	 4560
{ AC, QN, AC, PF, AC, AC, QN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 779	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, AC, AC, CR }, 	 //	 780	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, SK, SK, AC, LO, AC }, 	 //	 781	 4560
{ AC, QN, AC, TN, LO, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 782	 4560
{ AC, QN, AC, AC, LO, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 783	 4560
{ AC, QN, AC, AC, TN, AC, QN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 784	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, LO, SK, SK, AC, PF, AC }, 	 //	 785	 4560
{ AC, QN, AC, KN, AC, AC, QN, AC, AC, AC, SK, SK, AC, PF, AC }, 	 //	 786	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, WN, AC, AC }, 	 //	 787	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, WN, AC, AC }, 	 //	 788	 4560
{ AC, QN, AC, AC, AC, AC, QN, AC, AC, AC, SK, SK, WN, PF, AC }, 	 //	 789	 4560
{ AC, QN, SH, PF, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 790	 4560
{ AC, QN, SH, TN, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 791	 4560
{ AC, QN, SH, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 792	 4560
{ AC, QN, AC, PF, TN, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 793	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, CR }, 	 //	 794	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, LO, SK, JA, AC, LO, AC }, 	 //	 795	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, LO, CR }, 	 //	 796	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, CR }, 	 //	 797	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, LO, SK, JA, AC, PF, AC }, 	 //	 798	 4560
{ AC, QN, AC, KN, AC, AC, SK, AC, AC, AC, SK, JA, AC, PF, AC }, 	 //	 799	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, PF, AC, AC }, 	 //	 800	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, PF, LO, AC }, 	 //	 801	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, PF, AC, AC }, 	 //	 802	 4560
{ AC, QN, TN, PF, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 803	 4560
{ AC, QN, TN, PF, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 804	 4560
{ AC, QN, TN, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 805	 4560
{ AC, QN, TN, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 806	 4560
{ AC, QN, AC, PF, AC, AC, SK, AC, AC, LO, SK, JA, AC, AC, AC }, 	 //	 807	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, AC, CR }, 	 //	 808	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, LO, SK, JA, AC, LO, AC }, 	 //	 809	 4560
{ AC, QN, AC, TN, LO, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 810	 4560
{ AC, QN, AC, TN, TN, AC, SK, AC, AC, AC, SK, JA, AC, AC, AC }, 	 //	 811	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, AC, PF, CR }, 	 //	 812	 4560
{ AC, QN, AC, KN, AC, AC, SK, AC, AC, AC, SK, JA, AC, PF, AC }, 	 //	 813	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, WN, AC, AC }, 	 //	 814	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, WN, LO, AC }, 	 //	 815	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, WN, AC, AC }, 	 //	 816	 4560
{ AC, QN, AC, AC, AC, AC, SK, AC, AC, AC, SK, JA, WN, PF, AC }, 	 //	 817	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, AC, AC, SK, SK }, 	 //	 818	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, SK, AC, AC, JA, SK }, 	 //	 819	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, SK, SK, AC, AC, JA, QN }, 	 //	 820	 4560
{ AC, AC, AC, QN, SK, AC, AC, AC, SK, KN, SK, AC, AC, JA, KN }, 	 //	 821	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, QN, SK, AC, AC, JA, QN }, 	 //	 822	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, JA, KN, SK, AC, AC, JA, KN }, 	 //	 823	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, AC, AC, SK, SK }, 	 //	 824	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, SK, AC, AC, JA, SK }, 	 //	 825	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, KN, SK, AC, AC, QN, KN }, 	 //	 826	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, PF, AC, SK, SK }, 	 //	 827	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, QN, AC, SK, PF, AC, SK, SK }, 	 //	 828	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, SK, KN, SK, PF, AC, JA, SK }, 	 //	 829	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, SK, PF, AC, JA, SK }, 	 //	 830	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, KN, AC, SK, PF, AC, SK, SK }, 	 //	 831	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, SK, PF, AC, QN, SK }, 	 //	 832	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, SK, PF, AC, QN, KN }, 	 //	 833	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, SK, PF, AC, KN, QN }, 	 //	 834	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, SK, PF, AC, KN, KN }, 	 //	 835	 4560
{ AC, AC, AC, QN, KN, AC, AC, AC, QN, KN, SK, PF, AC, SK, SK }, 	 //	 836	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, AC, SK, PF, AC, JA, SK }, 	 //	 837	 4560
{ AC, AC, AC, QN, AC, AC, AC, AC, SK, SK, SK, PF, AC, JA, KN }, 	 //	 838	 4560
{ AC, AC, AC, KN, KN, AC, AC, AC, SK, KN, SK, PF, AC, QN, SK }, 	 //	 839	 4560
{ AC, AC, AC, KN, SK, AC, AC, AC, SK, QN, SK, PF, AC, QN, QN }, 	 //	 840	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, AC, SK, PF, AC, QN, SK }, 	 //	 841	 4560
{ AC, AC, AC, KN, AC, AC, AC, AC, SK, SK, SK, PF, AC, QN, KN }, 	 //	 842	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, QN, SK, PF, AC, KN, QN }, 	 //	 843	 4560
{ AC, AC, AC, SK, SK, AC, AC, AC, QN, KN, SK, PF, AC, KN, KN }, 	 //	 844	 4560
{ AC, KN, SH, PF, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 845	 4560
{ AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 846	 4560
{ AC, KN, SH, TN, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 847	 4560
{ AC, KN, SH, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 848	 4560
{ AC, KN, AC, PF, AC, AC, KN, AC, AC, LO, SK, SK, AC, AC, AC }, 	 //	 849	 4560
{ AC, KN, AC, PF, LO, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 850	 4560
{ AC, KN, AC, PF, TN, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 851	 4560
{ AC, KN, AC, AC, LO, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 852	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, CR }, 	 //	 853	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, LO, CR }, 	 //	 854	 4560
{ AC, KN, AC, TN, TN, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 855	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, PF, SK }, 	 //	 856	 4560
{ AC, KN, AC, KN, AC, AC, KN, AC, AC, AC, SK, SK, AC, PF, AC }, 	 //	 857	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, PF, AC, AC }, 	 //	 858	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, PF, LO, AC }, 	 //	 859	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, PF, AC, AC }, 	 //	 860	 4560
{ AC, KN, TN, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 861	 4560
{ AC, KN, TN, TN, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 862	 4560
{ AC, KN, AC, PF, TN, AC, KN, AC, AC, AC, SK, SK, AC, AC, AC }, 	 //	 863	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, CR }, 	 //	 864	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, AC, AC, SK }, 	 //	 865	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, WN, AC, AC }, 	 //	 866	 4560
{ AC, KN, AC, AC, AC, AC, KN, AC, AC, AC, SK, SK, WN, PF, AC }, 	 //	 867	 4560
{ AC, KN, SH, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 868	 4560
{ AC, KN, AC, PF, LO, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 869	 4560
{ AC, KN, AC, PF, TN, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 870	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, SK }, 	 //	 871	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, LO, CR }, 	 //	 872	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, LO, SK }, 	 //	 873	 4560
{ AC, KN, AC, WN, AC, AC, SK, AC, AC, AC, SK, QN, AC, KN, AC }, 	 //	 874	 4560
{ AC, KN, AC, TN, AC, AC, SK, AC, AC, LO, SK, QN, AC, AC, AC }, 	 //	 875	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, CR }, 	 //	 876	 4560
{ AC, KN, AC, AC, TN, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 877	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, LO, SK, QN, AC, PF, AC }, 	 //	 878	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, PF, CR }, 	 //	 879	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, PF, LO, AC }, 	 //	 880	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, PF, AC, AC }, 	 //	 881	 4560
{ AC, KN, TN, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 882	 4560
{ AC, KN, TN, TN, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 883	 4560
{ AC, KN, TN, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 884	 4560
{ AC, KN, AC, PF, LO, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 885	 4560
{ AC, KN, AC, PF, TN, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 886	 4560
{ AC, KN, AC, AC, LO, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 887	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, SK }, 	 //	 888	 4560
{ AC, KN, AC, WN, AC, AC, SK, AC, AC, AC, SK, QN, AC, KN, AC }, 	 //	 889	 4560
{ AC, KN, AC, TN, AC, AC, SK, AC, AC, LO, SK, QN, AC, AC, AC }, 	 //	 890	 4560
{ AC, KN, AC, TN, TN, AC, SK, AC, AC, AC, SK, QN, AC, AC, AC }, 	 //	 891	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, AC, CR }, 	 //	 892	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, LO, SK, QN, AC, PF, AC }, 	 //	 893	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, AC, PF, SK }, 	 //	 894	 4560
{ AC, KN, AC, KN, AC, AC, SK, AC, AC, AC, SK, QN, AC, PF, AC }, 	 //	 895	 4560
{ AC, KN, AC, AC, AC, AC, SK, AC, AC, AC, SK, QN, WN, AC, AC }, 	 //	 896	 4560
{ AC, AC, AC, SK, SK, SK, LO, WN, QN, KN, KN, KN, KN, KN, KN }, 	 //	 897	 4560
{ AC, QN, SH, PF, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 898	 4560
{ AC, QN, SH, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 899	 4560
{ AC, QN, SH, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 900	 4560
{ AC, QN, AC, PF, AC, SK, SK, AC, AC, LO, KN, JA, AC, AC, AC }, 	 //	 901	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 902	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, LO, CR }, 	 //	 903	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, LO, SK }, 	 //	 904	 4560
{ AC, QN, AC, WN, AC, SK, SK, AC, AC, AC, KN, JA, AC, KN, AC }, 	 //	 905	 4560
{ AC, QN, AC, TN, TN, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 906	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, CR }, 	 //	 907	 4560
{ AC, QN, AC, AC, TN, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 908	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 909	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, PF, SK }, 	 //	 910	 4560
{ AC, QN, AC, KN, AC, SK, SK, AC, AC, AC, KN, JA, AC, PF, AC }, 	 //	 911	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, PF, LO, AC }, 	 //	 912	 4560
{ AC, QN, TN, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 913	 4560
{ AC, QN, TN, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 914	 4560
{ AC, QN, AC, PF, TN, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 915	 4560
{ AC, QN, AC, AC, TN, SK, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 916	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 917	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, LO, KN, JA, AC, LO, AC }, 	 //	 918	 4560
{ AC, QN, AC, TN, AC, SK, SK, AC, AC, LO, KN, JA, AC, AC, AC }, 	 //	 919	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, AC, AC, CR }, 	 //	 920	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, LO, KN, JA, AC, PF, AC }, 	 //	 921	 4560
{ AC, QN, AC, KN, AC, SK, SK, AC, AC, AC, KN, JA, AC, PF, AC }, 	 //	 922	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, WN, AC, AC }, 	 //	 923	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, WN, LO, AC }, 	 //	 924	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, WN, AC, AC }, 	 //	 925	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, WN, PF, AC }, 	 //	 926	 4560
{ AC, QN, AC, AC, AC, SK, SK, AC, AC, AC, KN, JA, WN, PF, AC }, 	 //	 927	 4560
{ AC, AC, AC, SK, SK, SK, PF, WN, QN, KN, KN, KN, KN, KN, KN }, 	 //	 928	 4560
{ AC, KN, SH, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 929	 4560
{ AC, KN, SH, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 930	 4560
{ AC, KN, SH, TN, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 931	 4560
{ AC, KN, SH, TN, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 932	 4560
{ AC, KN, AC, PF, TN, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 933	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, SK }, 	 //	 934	 4560
{ AC, KN, AC, AC, LO, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 935	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, CR }, 	 //	 936	 4560
{ AC, KN, AC, AC, TN, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 937	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, PF, CR }, 	 //	 938	 4560
{ AC, KN, AC, KN, AC, SK, SK, AC, AC, AC, KN, QN, AC, PF, AC }, 	 //	 939	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, PF, LO, AC }, 	 //	 940	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, PF, AC, AC }, 	 //	 941	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, PF, PF, AC }, 	 //	 942	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, PF, PF, AC }, 	 //	 943	 4560
{ AC, KN, TN, PF, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 944	 4560
{ AC, KN, TN, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 945	 4560
{ AC, KN, TN, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 946	 4560
{ AC, KN, TN, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 947	 4560
{ AC, KN, AC, PF, AC, SK, SK, AC, AC, LO, KN, QN, AC, AC, AC }, 	 //	 948	 4560
{ AC, KN, AC, AC, LO, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 949	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, CR }, 	 //	 950	 4560
{ AC, KN, AC, AC, TN, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 951	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, LO, KN, QN, AC, LO, AC }, 	 //	 952	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, LO, CR }, 	 //	 953	 4560
{ AC, KN, AC, WN, AC, SK, SK, AC, AC, AC, KN, QN, AC, KN, AC }, 	 //	 954	 4560
{ AC, KN, AC, TN, LO, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 955	 4560
{ AC, KN, AC, AC, LO, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 956	 4560
{ AC, KN, AC, AC, TN, SK, SK, AC, AC, AC, KN, QN, AC, AC, AC }, 	 //	 957	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, AC, SK }, 	 //	 958	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, AC, PF, SK }, 	 //	 959	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, WN, AC, AC }, 	 //	 960	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, WN, AC, AC }, 	 //	 961	 4560
{ AC, KN, AC, AC, AC, SK, SK, AC, AC, AC, KN, QN, WN, PF, AC }, 	 //	 962	 4560
{ SK, QN, SH, PF, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 963	 4560
{ SK, QN, SH, PF, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 964	 4560
{ SK, QN, SH, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 965	 4560
{ SK, QN, SH, TN, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 966	 4560
{ SK, QN, SH, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 967	 4560
{ SK, QN, AC, AC, LO, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 968	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 969	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, LO, KN, JA, AC, LO, AC }, 	 //	 970	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, LO, CR }, 	 //	 971	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, LO, SK }, 	 //	 972	 4560
{ SK, QN, AC, TN, LO, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 973	 4560
{ SK, QN, AC, AC, TN, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 974	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, CR }, 	 //	 975	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, SK }, 	 //	 976	 4560
{ SK, QN, AC, KN, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, AC }, 	 //	 977	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, PF, AC, AC }, 	 //	 978	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, PF, AC, AC }, 	 //	 979	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, PF, LO, AC }, 	 //	 980	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, PF, PF, AC }, 	 //	 981	 4560
{ SK, QN, TN, PF, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 982	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, CR }, 	 //	 983	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, LO, KN, JA, AC, LO, AC }, 	 //	 984	 4560
{ SK, QN, AC, TN, AC, KN, SK, AC, AC, LO, KN, JA, AC, AC, AC }, 	 //	 985	 4560
{ SK, QN, AC, TN, TN, KN, SK, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 986	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, AC, CR }, 	 //	 987	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, CR }, 	 //	 988	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, SK }, 	 //	 989	 4560
{ SK, QN, AC, KN, AC, KN, SK, AC, AC, AC, KN, JA, AC, PF, AC }, 	 //	 990	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, WN, LO, AC }, 	 //	 991	 4560
{ SK, QN, AC, AC, AC, KN, SK, AC, AC, AC, KN, JA, WN, PF, AC }, 	 //	 992	 4560
{ SK, SK, SH, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 993	 4560
{ SK, SK, AC, AC, LO, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 994	 4560
{ SK, SK, AC, AC, AC, KN, JA, AC, AC, LO, KN, JA, AC, LO, AC }, 	 //	 995	 4560
{ SK, SK, AC, AC, LO, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 996	 4560
{ SK, SK, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, CR }, 	 //	 997	 4560
{ SK, SK, AC, AC, TN, KN, JA, AC, AC, AC, KN, JA, AC, AC, AC }, 	 //	 998	 4560
{ SK, SK, AC, AC, AC, KN, JA, AC, AC, AC, KN, JA, AC, AC, SK }, 	 //	 999	 4560
{ SK, SK, AC, AC, AC, KN, JA, AC, AC, LO, KN, JA, AC, PF, AC }};	 //	 1000	 4560
