unsigned char L5_Outcome_0500[1000][15]={	 //	 0	 500
{ AC, AC, QN, QN, QN, LO, AC, QN, QN, KN, AC, AC, SK, QN, AC }, 	 //	 1	 500
{ AC, AC, QN, QN, QN, LO, AC, AC, KN, QN, AC, LO, KN, AC, QN }, 	 //	 2	 500
{ AC, KN, QN, QN, QN, LO, KN, QN, KN, SH, AC, KN, SK, AC, JA }, 	 //	 3	 500
{ AC, KN, KN, QN, KN, LO, KN, PF, QN, SK, AC, KN, QN, QN, QN }, 	 //	 4	 500
{ AC, ST, AC, QN, ST, LO, QN, PF, QN, AC, AC, QN, QN, SK, KN }, 	 //	 5	 500
{ AC, QN, AC, QN, TN, LO, QN, KN, QN, TN, AC, QN, QN, SK, TN }, 	 //	 6	 500
{ AC, QN, AC, SK, KN, LO, QN, PF, QN, KN, AC, QN, QN, KN, SK }, 	 //	 7	 500
{ AC, SK, KN, QN, SK, LO, JA, PF, QN, QN, AC, JA, QN, QN, QN }, 	 //	 8	 500
{ AC, WN, QN, QN, QN, LO, AC, SK, QN, QN, AC, KN, JA, SK, SH }, 	 //	 9	 500
{ AC, AC, PF, KN, AC, LO, KN, QN, WN, AC, AC, QN, QN, QN, AC }, 	 //	 10	 500
{ AC, AC, PF, QN, QN, LO, KN, QN, QN, QN, AC, QN, AC, QN, QN }, 	 //	 11	 500
{ AC, KN, KN, QN, JA, LO, QN, PF, QN, JA, AC, ST, QN, SK, JA }, 	 //	 12	 500
{ AC, KN, AC, QN, QN, LO, SK, KN, QN, PF, AC, QN, QN, SK, JA }, 	 //	 13	 500
{ AC, SK, KN, QN, WN, LO, QN, QN, QN, TN, AC, KN, PF, QN, TN }, 	 //	 14	 500
{ AC, SK, KN, SK, AC, LO, QN, PF, QN, AC, AC, KN, QN, KN, AC }, 	 //	 15	 500
{ AC, SK, PF, KN, KN, LO, QN, QN, QN, SK, AC, KN, AC, ST, QN }, 	 //	 16	 500
{ AC, QN, AC, AC, QN, LO, KN, PF, KN, QN, AC, AC, QN, QN, QN }, 	 //	 17	 500
{ AC, QN, QN, QN, KN, LO, KN, QN, KN, KN, AC, AC, SK, AC, KN }, 	 //	 18	 500
{ LO, AC, PF, QN, QN, AC, SH, QN, QN, SH, AC, AC, QN, SK, JA }, 	 //	 19	 500
{ LO, SH, QN, KN, QN, AC, AC, PF, QN, QN, AC, AC, KN, ST, QN }, 	 //	 20	 500
{ LO, AC, QN, QN, QN, AC, AC, QN, SK, PF, AC, AC, QN, JA, JA }, 	 //	 21	 500
{ LO, LO, QN, KN, AC, AC, KN, QN, WN, KN, AC, KN, QN, QN, QN }, 	 //	 22	 500
{ LO, QN, QN, KN, TN, AC, QN, PF, QN, ST, AC, SK, KN, ST, AC }, 	 //	 23	 500
{ LO, QN, QN, QN, AC, AC, QN, PF, KN, AC, AC, SK, KN, AC, SK }, 	 //	 24	 500
{ LO, QN, QN, QN, TN, AC, QN, AC, SK, AC, AC, SK, KN, JA, AC }, 	 //	 25	 500
{ LO, JA, KN, SK, QN, AC, SH, QN, QN, QN, AC, TN, PF, KN, SH }, 	 //	 26	 500
{ LO, JA, QN, QN, QN, AC, SH, QN, KN, KN, AC, TN, QN, AC, AC }, 	 //	 27	 500
{ LO, SH, QN, QN, AC, AC, TN, PF, QN, KN, AC, TN, KN, SK, QN }, 	 //	 28	 500
{ LO, TN, QN, QN, QN, AC, WN, PF, KN, KN, AC, AC, KN, AC, AC }, 	 //	 29	 500
{ LO, TN, QN, QN, SK, AC, WN, SK, QN, QN, AC, AC, JA, QN, QN }, 	 //	 30	 500
{ LO, KN, QN, SK, KN, AC, QN, SK, QN, KN, AC, ST, JA, KN, SK }, 	 //	 31	 500
{ LO, KN, QN, SK, QN, AC, QN, AC, QN, PF, AC, ST, KN, KN, JA }, 	 //	 32	 500
{ LO, QN, PF, AC, SK, AC, ST, QN, KN, QN, AC, JA, QN, QN, QN }, 	 //	 33	 500
{ LO, QN, QN, QN, AC, AC, ST, SK, QN, AC, AC, JA, JA, SK, AC }, 	 //	 34	 500
{ LO, AC, QN, QN, AC, AC, AC, PF, QN, KN, AC, PF, KN, SK, QN }, 	 //	 35	 500
{ LO, AC, PF, QN, QN, AC, PF, QN, QN, KN, AC, KN, QN, SK, AC }, 	 //	 36	 500
{ LO, AC, KN, KN, QN, AC, PF, PF, WN, QN, AC, KN, QN, QN, QN }, 	 //	 37	 500
{ LO, PF, PF, AC, SK, AC, KN, QN, KN, QN, AC, KN, QN, QN, QN }, 	 //	 38	 500
{ LO, KN, QN, QN, AC, AC, KN, AC, QN, KN, AC, SK, KN, QN, QN }, 	 //	 39	 500
{ LO, SK, AC, WN, TN, AC, QN, KN, QN, TN, AC, KN, QN, QN, ST }, 	 //	 40	 500
{ LO, SK, QN, KN, AC, AC, QN, PF, QN, AC, AC, KN, KN, ST, AC }, 	 //	 41	 500
{ LO, QN, QN, QN, TN, AC, KN, SK, QN, TN, AC, AC, JA, SK, TN }, 	 //	 42	 500
{ AC, AC, KN, QN, QN, AC, AC, PF, QN, KN, AC, LO, QN, QN, AC }, 	 //	 43	 500
{ AC, KN, PF, KN, QN, AC, ST, QN, QN, SH, AC, QN, QN, ST, JA }, 	 //	 44	 500
{ AC, KN, QN, QN, QN, AC, ST, QN, ST, KN, AC, QN, QN, JA, AC }, 	 //	 45	 500
{ AC, KN, QN, KN, AC, AC, ST, QN, QN, KN, AC, QN, SK, ST, QN }, 	 //	 46	 500
{ AC, ST, QN, SK, SH, AC, QN, AC, QN, JA, AC, QN, KN, KN, JA }, 	 //	 47	 500
{ AC, QN, AC, KN, QN, AC, QN, KN, WN, KN, AC, QN, QN, QN, AC }, 	 //	 48	 500
{ AC, QN, KN, QN, TN, AC, QN, QN, QN, TN, AC, QN, PF, SK, TN }, 	 //	 49	 500
{ AC, QN, QN, QN, JA, AC, QN, PF, KN, WN, AC, QN, KN, AC, TN }, 	 //	 50	 500
{ AC, QN, KN, SK, QN, AC, SK, QN, QN, QN, AC, JA, PF, KN, QN }, 	 //	 51	 500
{ AC, JA, QN, QN, QN, AC, JA, PF, ST, KN, AC, SH, KN, JA, AC }, 	 //	 52	 500
{ AC, JA, QN, SK, QN, AC, JA, PF, QN, QN, AC, SH, KN, KN, QN }, 	 //	 53	 500
{ AC, TN, KN, AC, KN, AC, TN, PF, KN, SK, AC, WN, QN, QN, QN }, 	 //	 54	 500
{ AC, TN, QN, QN, QN, AC, TN, AC, QN, PF, AC, WN, KN, QN, JA }, 	 //	 55	 500
{ AC, KN, KN, WN, WN, AC, QN, QN, QN, TN, AC, ST, PF, QN, TN }, 	 //	 56	 500
{ AC, KN, PF, WN, AC, AC, QN, QN, QN, AC, AC, ST, AC, QN, SK }, 	 //	 57	 500
{ AC, QN, AC, WN, QN, AC, ST, PF, QN, KN, AC, JA, QN, QN, AC }, 	 //	 58	 500
{ AC, QN, PF, KN, QN, AC, ST, QN, QN, KN, AC, JA, QN, ST, AC }, 	 //	 59	 500
{ AC, TN, KN, QN, QN, AC, AC, QN, QN, QN, AC, AC, PF, QN, QN }, 	 //	 60	 500
{ AC, KN, AC, SK, QN, AC, KN, PF, QN, PF, AC, SK, QN, KN, JA }, 	 //	 61	 500
{ AC, KN, AC, WN, KN, AC, SK, PF, QN, KN, AC, QN, QN, QN, KN }, 	 //	 62	 500
{ AC, KN, KN, QN, TN, AC, SK, PF, QN, ST, AC, QN, QN, QN, AC }, 	 //	 63	 500
{ AC, KN, QN, KN, AC, AC, SK, AC, QN, KN, AC, QN, KN, ST, QN }, 	 //	 64	 500
{ AC, SK, KN, KN, QN, AC, QN, QN, QN, SH, AC, KN, PF, ST, JA }, 	 //	 65	 500
{ AC, ST, QN, WN, SH, AC, QN, SK, QN, JA, ST, QN, JA, QN, JA }, 	 //	 66	 500
{ AC, QN, QN, QN, SK, AC, QN, PF, ST, QN, ST, QN, KN, JA, QN }, 	 //	 67	 500
{ AC, QN, AC, QN, AC, AC, QN, KN, QN, AC, ST, SK, QN, QN, SK }, 	 //	 68	 500
{ AC, QN, PF, KN, WN, AC, QN, QN, QN, TN, ST, SK, AC, ST, TN }, 	 //	 69	 500
{ AC, JA, AC, WN, KN, AC, JA, KN, QN, SK, ST, JA, QN, QN, QN }, 	 //	 70	 500
{ AC, TN, WN, SH, TN, AC, TN, TN, TN, TN, ST, WN, TN, TN, TN }, 	 //	 71	 500
{ AC, TN, KN, KN, QN, AC, WN, PF, QN, KN, ST, AC, QN, ST, AC }, 	 //	 72	 500
{ AC, WN, QN, QN, QN, AC, AC, QN, QN, SH, ST, KN, SK, QN, JA }, 	 //	 73	 500
{ AC, AC, QN, WN, JA, AC, KN, QN, QN, WN, ST, QN, QN, QN, TN }, 	 //	 74	 500
{ AC, KN, QN, QN, TN, AC, QN, SK, QN, TN, ST, ST, JA, QN, TN }, 	 //	 75	 500
{ AC, ST, QN, SK, QN, AC, JA, QN, QN, SH, ST, TN, QN, KN, JA }, 	 //	 76	 500
{ AC, AC, QN, QN, QN, AC, AC, PF, QN, QN, ST, AC, KN, QN, SH }, 	 //	 77	 500
{ AC, KN, QN, QN, QN, AC, KN, AC, SK, PF, ST, SK, KN, JA, JA }, 	 //	 78	 500
{ AC, SK, AC, AC, SK, AC, QN, PF, KN, QN, ST, KN, QN, QN, QN }, 	 //	 79	 500
{ AC, KN, QN, SK, KN, ST, ST, QN, QN, SK, KN, QN, SK, KN, QN }, 	 //	 80	 500
{ AC, QN, KN, WN, TN, ST, QN, QN, QN, ST, KN, QN, PF, QN, AC }, 	 //	 81	 500
{ AC, QN, AC, KN, LO, ST, QN, PF, QN, AC, KN, SK, QN, ST, AC }, 	 //	 82	 500
{ AC, QN, QN, KN, KN, ST, QN, SK, QN, KN, KN, SK, JA, ST, KN }, 	 //	 83	 500
{ AC, JA, KN, AC, SK, ST, JA, PF, KN, QN, KN, SH, QN, QN, QN }, 	 //	 84	 500
{ AC, TN, QN, QN, QN, ST, TN, PF, ST, QN, KN, WN, KN, JA, SH }, 	 //	 85	 500
{ AC, WN, KN, WN, KN, ST, AC, QN, QN, QN, KN, KN, PF, QN, PF }, 	 //	 86	 500
{ AC, WN, QN, KN, SK, ST, AC, QN, WN, QN, KN, KN, QN, QN, QN }, 	 //	 87	 500
{ AC, KN, AC, KN, AC, ST, QN, KN, QN, AC, KN, ST, QN, ST, CR }, 	 //	 88	 500
{ AC, QN, QN, QN, KN, ST, ST, AC, SK, KN, KN, JA, KN, JA, KN }, 	 //	 89	 500
{ AC, TN, PF, QN, QN, ST, AC, QN, QN, KN, KN, AC, QN, QN, AC }, 	 //	 90	 500
{ AC, AC, QN, WN, QN, ST, PF, QN, QN, QN, KN, KN, SK, QN, SH }, 	 //	 91	 500
{ AC, PF, PF, KN, SK, ST, KN, QN, QN, QN, KN, KN, QN, ST, QN }, 	 //	 92	 500
{ AC, KN, PF, SK, KN, ST, KN, QN, QN, QN, KN, SK, QN, KN, PF }, 	 //	 93	 500
{ AC, KN, PF, KN, KN, ST, SK, QN, WN, KN, KN, QN, QN, QN, KN }, 	 //	 94	 500
{ ST, AC, QN, AC, SK, KN, SH, QN, KN, QN, KN, AC, QN, QN, QN }, 	 //	 95	 500
{ ST, AC, QN, QN, QN, KN, AC, QN, KN, KN, KN, AC, SK, AC, AC }, 	 //	 96	 500
{ ST, AC, QN, KN, AC, KN, AC, PF, QN, KN, KN, LO, KN, ST, QN }, 	 //	 97	 500
{ ST, AC, AC, KN, SK, KN, LO, PF, WN, QN, KN, KN, QN, QN, QN }, 	 //	 98	 500
{ ST, KN, KN, WN, QN, KN, ST, QN, QN, QN, KN, QN, PF, QN, SH }, 	 //	 99	 500
{ ST, ST, AC, KN, LO, KN, QN, PF, QN, AC, KN, QN, QN, ST, AC }, 	 //	 100	 500
{ ST, QN, QN, KN, TN, KN, QN, PF, QN, TN, KN, QN, KN, ST, ST }, 	 //	 101	 500
{ ST, QN, QN, AC, AC, KN, QN, QN, KN, SK, KN, QN, QN, QN, KN }, 	 //	 102	 500
{ ST, QN, QN, WN, JA, KN, QN, PF, QN, WN, KN, SK, KN, QN, TN }, 	 //	 103	 500
{ ST, QN, AC, QN, KN, KN, QN, PF, QN, KN, KN, SK, QN, QN, CR }, 	 //	 104	 500
{ ST, QN, QN, WN, JA, KN, QN, AC, QN, JA, KN, SK, KN, QN, WN }, 	 //	 105	 500
{ ST, JA, KN, WN, KN, KN, JA, QN, QN, QN, KN, JA, PF, QN, PF }, 	 //	 106	 500
{ ST, JA, PF, QN, QN, KN, JA, QN, QN, SH, KN, SH, QN, QN, JA }, 	 //	 107	 500
{ ST, SH, KN, SK, QN, KN, TN, PF, QN, SH, KN, TN, QN, KN, JA }, 	 //	 108	 500
{ ST, TN, QN, QN, QN, KN, TN, QN, ST, QN, KN, WN, SK, JA, QN }, 	 //	 109	 500
{ ST, TN, QN, QN, QN, KN, TN, AC, KN, SH, KN, WN, KN, AC, JA }, 	 //	 110	 500
{ ST, KN, QN, QN, PF, KN, QN, AC, QN, JA, KN, ST, KN, QN, TN }, 	 //	 111	 500
{ ST, ST, AC, KN, AC, KN, JA, PF, WN, KN, KN, TN, QN, QN, QN }, 	 //	 112	 500
{ ST, JA, TN, TN, TN, KN, TN, TN, TN, TN, KN, AC, LO, WN, TN }, 	 //	 113	 500
{ ST, JA, PF, QN, QN, KN, TN, QN, QN, PF, KN, AC, QN, SK, JA }, 	 //	 114	 500
{ ST, PF, QN, KN, KN, KN, KN, QN, QN, QN, KN, KN, QN, ST, PF }, 	 //	 115	 500
{ ST, KN, QN, QN, QN, KN, KN, AC, ST, PF, KN, SK, KN, JA, JA }, 	 //	 116	 500
{ ST, KN, AC, WN, KN, KN, SK, PF, QN, KN, KN, QN, QN, QN, KN }, 	 //	 117	 500
{ ST, SK, PF, SK, KN, KN, QN, QN, QN, KN, KN, KN, AC, KN, KN }, 	 //	 118	 500
{ ST, QN, QN, QN, AC, KN, KN, QN, QN, AC, KN, AC, QN, SK, CR }, 	 //	 119	 500
{ KN, KN, AC, AC, QN, KN, ST, KN, KN, PF, KN, QN, QN, QN, JA }, 	 //	 120	 500
{ KN, QN, AC, KN, LO, KN, QN, PF, WN, AC, KN, QN, QN, QN, AC }, 	 //	 121	 500
{ KN, QN, QN, KN, KN, KN, QN, SK, QN, KN, KN, QN, JA, ST, KN }, 	 //	 122	 500
{ KN, QN, QN, QN, KN, KN, QN, SK, KN, KN, KN, QN, JA, AC, KN }, 	 //	 123	 500
{ KN, JA, QN, KN, CR, KN, JA, QN, QN, QN, KN, SH, SK, ST, KN }, 	 //	 124	 500
{ KN, WN, QN, SK, AC, KN, AC, QN, QN, KN, KN, KN, SK, KN, QN }, 	 //	 125	 500
{ KN, QN, QN, QN, KN, KN, ST, QN, QN, AC, KN, JA, SK, QN, LO }, 	 //	 126	 500
{ KN, AC, PF, QN, QN, KN, AC, QN, QN, SH, KN, PF, QN, QN, JA }, 	 //	 127	 500
{ KN, KN, PF, SK, QN, KN, KN, QN, QN, QN, KN, KN, AC, KN, SH }, 	 //	 128	 500
{ KN, SH, KN, QN, QN, KN, AC, PF, QN, KN, SK, AC, QN, SK, AC }, 	 //	 129	 500
{ KN, SH, QN, QN, KN, KN, AC, AC, QN, SK, SK, AC, KN, QN, QN }, 	 //	 130	 500
{ KN, AC, AC, QN, QN, KN, AC, PF, QN, PF, SK, AC, QN, SK, JA }, 	 //	 131	 500
{ KN, KN, QN, QN, QN, KN, ST, QN, SK, KN, SK, QN, QN, JA, AC }, 	 //	 132	 500
{ KN, SK, QN, KN, QN, KN, JA, AC, QN, QN, SK, JA, KN, ST, QN }, 	 //	 133	 500
{ KN, SH, QN, SK, KN, KN, TN, AC, QN, SK, SK, TN, KN, KN, QN }, 	 //	 134	 500
{ KN, TN, PF, QN, CR, KN, TN, QN, QN, QN, SK, TN, AC, SK, KN }, 	 //	 135	 500
{ KN, WN, QN, WN, QN, KN, AC, QN, QN, SH, SK, KN, QN, QN, JA }, 	 //	 136	 500
{ KN, ST, KN, QN, QN, KN, JA, PF, QN, KN, SK, TN, QN, SK, AC }, 	 //	 137	 500
{ KN, PF, QN, QN, QN, KN, KN, QN, QN, PF, SK, KN, SK, QN, JA }, 	 //	 138	 500
{ KN, QN, QN, QN, KN, KN, KN, SK, QN, AC, SK, AC, JA, SK, LO }, 	 //	 139	 500
{ KN, AC, AC, SK, QN, SK, SH, PF, QN, SH, QN, AC, QN, KN, JA }, 	 //	 140	 500
{ KN, SH, PF, WN, QN, SK, AC, QN, QN, SH, QN, AC, QN, QN, JA }, 	 //	 141	 500
{ KN, SH, PF, KN, AC, SK, AC, QN, SK, KN, QN, AC, QN, QN, QN }, 	 //	 142	 500
{ KN, KN, PF, AC, CR, SK, ST, QN, AC, QN, QN, QN, QN, LO, KN }, 	 //	 143	 500
{ KN, KN, QN, LO, QN, SK, ST, QN, KN, QN, QN, QN, QN, KN, QN }, 	 //	 144	 500
{ KN, KN, QN, TN, QN, SK, ST, QN, TN, KN, QN, QN, QN, WN, AC }, 	 //	 145	 500
{ KN, KN, QN, TN, WN, SK, ST, QN, AC, TN, QN, QN, QN, AC, TN }, 	 //	 146	 500
{ KN, ST, QN, PF, QN, SK, QN, PF, AC, KN, QN, QN, KN, AC, AC }, 	 //	 147	 500
{ KN, ST, AC, PF, TN, SK, QN, PF, AC, TN, QN, QN, QN, AC, TN }, 	 //	 148	 500
{ KN, ST, AC, KN, AC, SK, QN, PF, KN, SK, QN, QN, QN, KN, KN }, 	 //	 149	 500
{ KN, ST, AC, AC, KN, SK, QN, PF, AC, QN, QN, QN, QN, AC, PF }, 	 //	 150	 500
{ KN, ST, PF, SH, CR, SK, QN, QN, TN, KN, QN, QN, QN, TN, KN }, 	 //	 151	 500
{ KN, ST, QN, AC, QN, SK, QN, SK, PF, QN, QN, QN, JA, AC, QN }, 	 //	 152	 500
{ KN, ST, QN, TN, SH, SK, QN, SK, TN, JA, QN, QN, JA, TN, JA }, 	 //	 153	 500
{ KN, ST, QN, KN, JA, SK, QN, SK, AC, JA, QN, QN, JA, PF, WN }, 	 //	 154	 500
{ KN, ST, KN, WN, KN, SK, QN, PF, AC, SK, QN, QN, QN, KN, QN }, 	 //	 155	 500
{ KN, ST, KN, AC, SK, SK, QN, PF, AC, QN, QN, QN, QN, PF, QN }, 	 //	 156	 500
{ KN, ST, PF, QN, QN, SK, QN, QN, QN, SH, QN, QN, AC, QN, JA }, 	 //	 157	 500
{ KN, ST, QN, JA, JA, SK, QN, AC, SH, TN, QN, QN, KN, TN, AC }, 	 //	 158	 500
{ KN, ST, QN, KN, CR, SK, QN, AC, AC, QN, QN, QN, KN, PF, KN }, 	 //	 159	 500
{ KN, QN, QN, TN, JA, SK, QN, PF, AC, JA, QN, QN, KN, AC, JA }, 	 //	 160	 500
{ KN, QN, AC, JA, JA, SK, QN, PF, JA, TN, QN, QN, QN, SH, AC }, 	 //	 161	 500
{ KN, QN, PF, PF, SK, SK, QN, QN, AC, KN, QN, QN, QN, AC, KN }, 	 //	 162	 500
{ KN, QN, QN, JA, KN, SK, QN, QN, SH, KN, QN, QN, SK, TN, KN }, 	 //	 163	 500
{ KN, QN, QN, JA, WN, SK, QN, QN, TN, TN, QN, QN, SK, AC, TN }, 	 //	 164	 500
{ KN, QN, KN, SK, QN, SK, QN, PF, JA, QN, QN, QN, QN, JA, QN }, 	 //	 165	 500
{ KN, QN, PF, QN, KN, SK, QN, QN, QN, AC, QN, QN, AC, QN, LO }, 	 //	 166	 500
{ KN, QN, QN, SK, AC, SK, QN, AC, JA, AC, QN, QN, KN, JA, CR }, 	 //	 167	 500
{ KN, QN, QN, AC, TN, SK, QN, AC, PF, TN, QN, QN, KN, KN, ST }, 	 //	 168	 500
{ KN, QN, QN, AC, TN, SK, QN, PF, PF, AC, QN, SK, KN, AC, AC }, 	 //	 169	 500
{ KN, QN, QN, AC, QN, SK, QN, PF, AC, QN, QN, SK, KN, PF, QN }, 	 //	 170	 500
{ KN, QN, QN, KN, CR, SK, QN, QN, KN, KN, QN, SK, QN, KN, KN }, 	 //	 171	 500
{ KN, QN, QN, JA, TN, SK, QN, AC, TN, AC, QN, SK, KN, AC, AC }, 	 //	 172	 500
{ KN, TN, TN, TN, JA, SK, TN, TN, TN, JA, QN, TN, TN, TN, WN }, 	 //	 173	 500
{ KN, AC, AC, SK, PF, SK, KN, KN, JA, JA, QN, QN, QN, JA, TN }, 	 //	 174	 500
{ KN, AC, KN, KN, QN, SK, KN, QN, QN, QN, QN, QN, PF, ST, QN }, 	 //	 175	 500
{ KN, AC, AC, JA, AC, SK, KN, PF, SH, KN, QN, QN, QN, TN, QN }, 	 //	 176	 500
{ KN, AC, AC, JA, SK, SK, KN, PF, SH, KN, QN, QN, QN, TN, KN }, 	 //	 177	 500
{ KN, AC, AC, TN, AC, SK, KN, PF, WN, SK, QN, QN, QN, AC, KN }, 	 //	 178	 500
{ KN, AC, AC, QN, TN, SK, KN, PF, ST, ST, QN, QN, QN, JA, AC }, 	 //	 179	 500
{ KN, AC, QN, AC, KN, SK, KN, QN, PF, SK, QN, QN, QN, KN, QN }, 	 //	 180	 500
{ KN, KN, QN, AC, QN, SK, QN, QN, AC, QN, QN, ST, QN, AC, QN }, 	 //	 181	 500
{ KN, PF, KN, QN, QN, SK, KN, PF, QN, QN, QN, KN, QN, SK, QN }, 	 //	 182	 500
{ KN, SK, QN, TN, JA, SK, QN, PF, AC, JA, QN, KN, KN, AC, WN }, 	 //	 183	 500
{ KN, SK, QN, JA, AC, SK, QN, QN, SH, AC, QN, KN, SK, TN, CR }, 	 //	 184	 500
{ KN, SK, QN, QN, LO, SK, QN, AC, KN, AC, QN, KN, KN, AC, AC }, 	 //	 185	 500
{ KN, KN, AC, WN, QN, SK, AC, KN, QN, QN, QN, SH, QN, QN, SH }, 	 //	 186	 500
{ SK, SH, QN, QN, AC, QN, AC, AC, QN, KN, QN, AC, KN, QN, QN }, 	 //	 187	 500
{ SK, KN, QN, JA, AC, QN, ST, QN, JA, AC, QN, QN, QN, SH, SK }, 	 //	 188	 500
{ SK, KN, KN, AC, WN, QN, ST, PF, AC, TN, QN, QN, QN, LO, TN }, 	 //	 189	 500
{ SK, KN, KN, LO, SK, QN, ST, PF, KN, QN, QN, QN, QN, KN, QN }, 	 //	 190	 500
{ SK, KN, KN, TN, QN, QN, ST, PF, TN, KN, QN, QN, QN, WN, AC }, 	 //	 191	 500
{ SK, ST, AC, PF, TN, QN, QN, KN, AC, TN, QN, QN, QN, AC, TN }, 	 //	 192	 500
{ SK, ST, KN, AC, QN, QN, QN, QN, LO, QN, QN, QN, PF, KN, QN }, 	 //	 193	 500
{ SK, ST, KN, AC, QN, QN, QN, QN, KN, KN, QN, QN, PF, QN, AC }, 	 //	 194	 500
{ SK, ST, AC, KN, TN, QN, QN, PF, KN, ST, QN, QN, QN, WN, AC }, 	 //	 195	 500
{ SK, ST, AC, JA, KN, QN, QN, PF, JA, QN, QN, QN, QN, JA, PF }, 	 //	 196	 500
{ SK, ST, AC, KN, JA, QN, QN, PF, KN, JA, QN, QN, QN, SK, WN }, 	 //	 197	 500
{ SK, ST, QN, KN, QN, QN, QN, SK, AC, SH, QN, QN, JA, PF, JA }, 	 //	 198	 500
{ SK, ST, KN, PF, QN, QN, QN, PF, AC, QN, QN, QN, QN, AC, QN }, 	 //	 199	 500
{ SK, ST, KN, TN, CR, QN, QN, PF, WN, KN, QN, QN, QN, AC, KN }, 	 //	 200	 500
{ SK, ST, QN, KN, QN, QN, QN, AC, KN, QN, QN, QN, KN, KN, QN }, 	 //	 201	 500
{ SK, QN, AC, TN, JA, QN, QN, KN, WN, JA, QN, QN, QN, AC, WN }, 	 //	 202	 500
{ SK, QN, AC, TN, JA, QN, QN, KN, WN, TN, QN, QN, QN, AC, AC }, 	 //	 203	 500
{ SK, QN, AC, AC, CR, QN, QN, KN, AC, QN, QN, QN, QN, AC, KN }, 	 //	 204	 500
{ SK, QN, QN, JA, JA, QN, QN, PF, JA, WN, QN, QN, KN, SH, TN }, 	 //	 205	 500
{ SK, QN, AC, QN, QN, QN, QN, PF, ST, QN, QN, QN, QN, JA, SH }, 	 //	 206	 500
{ SK, QN, AC, KN, JA, QN, QN, PF, KN, JA, QN, QN, QN, KN, JA }, 	 //	 207	 500
{ SK, QN, KN, QN, SH, QN, QN, PF, SK, JA, QN, QN, QN, JA, JA }, 	 //	 208	 500
{ SK, QN, PF, AC, JA, QN, QN, QN, AC, WN, QN, QN, AC, AC, TN }, 	 //	 209	 500
{ SK, QN, KN, AC, TN, QN, QN, QN, LO, AC, QN, SK, PF, KN, AC }, 	 //	 210	 500
{ SK, QN, KN, JA, QN, QN, QN, QN, TN, SH, QN, SK, PF, AC, JA }, 	 //	 211	 500
{ SK, QN, AC, QN, AC, QN, QN, PF, QN, SK, QN, SK, QN, SK, KN }, 	 //	 212	 500
{ SK, QN, PF, JA, JA, QN, QN, QN, JA, JA, QN, SK, QN, SH, WN }, 	 //	 213	 500
{ SK, QN, PF, QN, QN, QN, QN, QN, KN, QN, QN, SK, QN, AC, SH }, 	 //	 214	 500
{ SK, QN, QN, AC, AC, QN, QN, SK, AC, AC, QN, SK, JA, LO, SK }, 	 //	 215	 500
{ SK, QN, PF, ST, QN, QN, QN, QN, JA, QN, QN, SK, AC, TN, QN }, 	 //	 216	 500
{ SK, QN, QN, AC, AC, QN, QN, AC, AC, KN, QN, SK, KN, LO, QN }, 	 //	 217	 500
{ SK, JA, KN, QN, KN, QN, JA, QN, QN, QN, QN, SH, PF, SK, PF }, 	 //	 218	 500
{ SK, JA, QN, QN, QN, QN, JA, PF, QN, SH, QN, SH, KN, QN, JA }, 	 //	 219	 500
{ SK, JA, QN, WN, KN, QN, SH, QN, QN, QN, QN, TN, QN, QN, PF }, 	 //	 220	 500
{ SK, TN, QN, QN, QN, QN, TN, PF, QN, QN, QN, WN, KN, QN, SH }, 	 //	 221	 500
{ SK, TN, QN, QN, QN, QN, WN, PF, KN, QN, QN, AC, KN, AC, SH }, 	 //	 222	 500
{ SK, WN, QN, QN, QN, QN, AC, AC, QN, SH, QN, KN, KN, SK, JA }, 	 //	 223	 500
{ SK, AC, AC, KN, SH, QN, KN, PF, QN, JA, QN, QN, QN, ST, JA }, 	 //	 224	 500
{ SK, AC, KN, KN, PF, QN, KN, PF, QN, JA, QN, QN, QN, ST, TN }, 	 //	 225	 500
{ SK, KN, QN, KN, JA, QN, QN, PF, KN, JA, QN, ST, KN, KN, WN }, 	 //	 226	 500
{ SK, KN, AC, KN, JA, QN, QN, PF, QN, WN, QN, ST, QN, ST, TN }, 	 //	 227	 500
{ SK, KN, PF, KN, KN, QN, QN, QN, KN, KN, QN, ST, QN, KN, KN }, 	 //	 228	 500
{ SK, KN, QN, AC, AC, QN, QN, SK, PF, KN, QN, ST, JA, AC, QN }, 	 //	 229	 500
{ SK, KN, PF, SK, AC, QN, QN, QN, JA, AC, QN, ST, AC, JA, AC }, 	 //	 230	 500
{ SK, AC, QN, QN, QN, QN, AC, PF, ST, QN, QN, PF, KN, JA, SH }, 	 //	 231	 500
{ SK, AC, PF, QN, AC, QN, PF, QN, QN, KN, QN, KN, QN, QN, QN }, 	 //	 232	 500
{ SK, KN, QN, KN, SK, QN, KN, SK, QN, QN, QN, SK, JA, ST, QN }, 	 //	 233	 500
{ SK, KN, AC, SK, QN, QN, AC, PF, QN, PF, QN, SH, QN, KN, JA }, 	 //	 234	 500
{ SK, KN, QN, QN, QN, QN, AC, AC, KN, SH, QN, SH, KN, AC, JA }, 	 //	 235	 500
{ QN, AC, AC, KN, QN, QN, AC, KN, QN, QN, QN, LO, QN, ST, SH }, 	 //	 236	 500
{ QN, AC, QN, WN, QN, QN, LO, QN, QN, PF, QN, KN, QN, QN, JA }, 	 //	 237	 500
{ QN, LO, QN, WN, AC, QN, KN, AC, QN, KN, QN, KN, KN, QN, QN }, 	 //	 238	 500
{ QN, KN, QN, SH, TN, QN, ST, QN, TN, TN, QN, QN, QN, TN, TN }, 	 //	 239	 500
{ QN, KN, KN, QN, AC, QN, ST, PF, SK, AC, QN, QN, QN, JA, AC }, 	 //	 240	 500
{ QN, ST, KN, KN, JA, QN, QN, QN, KN, WN, QN, QN, PF, KN, TN }, 	 //	 241	 500
{ QN, ST, QN, KN, JA, QN, QN, AC, WN, WN, QN, QN, KN, QN, TN }, 	 //	 242	 500
{ QN, ST, QN, JA, SK, QN, QN, AC, JA, KN, QN, QN, KN, SH, KN }, 	 //	 243	 500
{ QN, ST, QN, TN, KN, QN, QN, AC, TN, AC, QN, QN, KN, WN, LO }, 	 //	 244	 500
{ QN, ST, QN, JA, QN, QN, QN, AC, TN, SH, QN, QN, KN, AC, JA }, 	 //	 245	 500
{ QN, QN, AC, AC, PF, QN, QN, KN, KN, JA, QN, SK, QN, QN, TN }, 	 //	 246	 500
{ QN, QN, AC, AC, TN, QN, QN, KN, AC, TN, QN, SK, QN, AC, TN }, 	 //	 247	 500
{ QN, QN, AC, KN, LO, QN, QN, KN, SK, AC, QN, SK, QN, QN, AC }, 	 //	 248	 500
{ QN, QN, KN, AC, JA, QN, QN, QN, AC, WN, QN, SK, PF, AC, TN }, 	 //	 249	 500
{ QN, QN, AC, KN, KN, QN, QN, PF, KN, KN, QN, SK, QN, KN, KN }, 	 //	 250	 500
{ QN, QN, KN, AC, AC, QN, QN, PF, PF, AC, QN, SK, QN, KN, CR }, 	 //	 251	 500
{ QN, QN, QN, JA, KN, QN, SK, QN, SH, KN, QN, JA, QN, TN, KN }, 	 //	 252	 500
{ QN, QN, QN, TN, AC, QN, SK, QN, TN, AC, QN, JA, QN, WN, SK }, 	 //	 253	 500
{ QN, QN, QN, KN, JA, QN, SK, AC, WN, TN, QN, JA, KN, QN, AC }, 	 //	 254	 500
{ QN, QN, QN, TN, JA, QN, SK, AC, AC, JA, QN, JA, KN, AC, WN }, 	 //	 255	 500
{ QN, SK, KN, QN, QN, QN, JA, PF, QN, SH, QN, JA, QN, QN, JA }, 	 //	 256	 500
{ QN, JA, KN, QN, KN, QN, JA, QN, QN, QN, QN, JA, PF, SK, PF }, 	 //	 257	 500
{ QN, WN, KN, SK, CR, QN, AC, QN, QN, QN, QN, KN, PF, KN, KN }, 	 //	 258	 500
{ QN, WN, PF, KN, QN, QN, AC, QN, WN, QN, QN, KN, QN, QN, QN }, 	 //	 259	 500
{ QN, AC, AC, SK, CR, QN, KN, KN, QN, QN, QN, QN, QN, KN, KN }, 	 //	 260	 500
{ QN, AC, PF, TN, KN, QN, KN, QN, TN, AC, QN, QN, QN, WN, LO }, 	 //	 261	 500
{ QN, AC, KN, AC, TN, QN, KN, PF, AC, AC, QN, QN, QN, AC, AC }, 	 //	 262	 500
{ QN, KN, KN, JA, PF, QN, QN, QN, JA, JA, QN, ST, PF, SH, TN }, 	 //	 263	 500
{ QN, KN, AC, PF, CR, QN, QN, PF, AC, KN, QN, ST, QN, AC, KN }, 	 //	 264	 500
{ QN, KN, AC, ST, QN, QN, QN, PF, JA, KN, QN, ST, QN, TN, AC }, 	 //	 265	 500
{ QN, KN, QN, JA, WN, QN, QN, SK, SH, TN, QN, ST, JA, TN, TN }, 	 //	 266	 500
{ QN, QN, QN, TN, KN, QN, ST, PF, TN, QN, QN, JA, KN, WN, PF }, 	 //	 267	 500
{ QN, QN, QN, TN, JA, QN, ST, QN, TN, TN, QN, JA, SK, WN, AC }, 	 //	 268	 500
{ QN, QN, QN, TN, TN, QN, ST, QN, WN, ST, QN, JA, SK, AC, AC }, 	 //	 269	 500
{ QN, QN, QN, ST, AC, QN, ST, SK, JA, SK, QN, JA, JA, TN, KN }, 	 //	 270	 500
{ QN, QN, QN, TN, QN, QN, ST, SK, AC, PF, QN, JA, JA, AC, JA }, 	 //	 271	 500
{ QN, QN, QN, TN, SH, QN, ST, AC, TN, JA, QN, JA, KN, TN, JA }, 	 //	 272	 500
{ QN, TN, QN, QN, QN, QN, AC, AC, KN, QN, QN, AC, KN, AC, QN }, 	 //	 273	 500
{ QN, AC, PF, QN, QN, QN, AC, QN, QN, QN, QN, AC, AC, QN, SH }, 	 //	 274	 500
{ QN, KN, AC, QN, AC, QN, SK, KN, ST, KN, QN, QN, QN, JA, QN }, 	 //	 275	 500
{ QN, KN, AC, AC, TN, QN, SK, PF, LO, TN, QN, QN, QN, KN, TN }, 	 //	 276	 500
{ QN, KN, QN, LO, KN, QN, SK, QN, KN, KN, QN, QN, QN, KN, KN }, 	 //	 277	 500
{ QN, KN, QN, JA, JA, QN, SK, QN, SH, JA, QN, QN, QN, TN, WN }, 	 //	 278	 500
{ QN, SK, AC, KN, TN, QN, QN, KN, KN, ST, QN, KN, QN, KN, AC }, 	 //	 279	 500
{ QN, SK, KN, AC, AC, QN, QN, QN, PF, LO, QN, KN, PF, KN, AC }, 	 //	 280	 500
{ QN, SK, QN, PF, JA, QN, QN, SK, AC, TN, QN, KN, JA, AC, AC }, 	 //	 281	 500
{ QN, SK, QN, AC, TN, QN, QN, SK, AC, TN, QN, KN, JA, LO, TN }, 	 //	 282	 500
{ QN, SK, KN, AC, TN, QN, QN, PF, AC, TN, QN, KN, QN, LO, ST }, 	 //	 283	 500
{ QN, SK, KN, PF, QN, QN, QN, PF, KN, QN, QN, KN, QN, KN, SH }, 	 //	 284	 500
{ QN, SK, QN, PF, JA, QN, QN, AC, AC, JA, QN, KN, KN, AC, JA }, 	 //	 285	 500
{ QN, QN, QN, KN, QN, QN, KN, QN, SK, SH, QN, AC, QN, QN, JA }, 	 //	 286	 500
{ QN, AC, QN, QN, QN, QN, AC, PF, KN, QN, SH, AC, KN, AC, QN }, 	 //	 287	 500
{ QN, AC, QN, SK, KN, QN, AC, SK, QN, SK, SH, LO, JA, KN, QN }, 	 //	 288	 500
{ QN, LO, QN, QN, QN, QN, KN, QN, QN, SH, SH, KN, SK, QN, JA }, 	 //	 289	 500
{ QN, KN, QN, KN, KN, QN, KN, QN, QN, SK, SH, KN, SK, ST, QN }, 	 //	 290	 500
{ QN, ST, QN, KN, KN, QN, QN, PF, QN, KN, SH, QN, KN, ST, CR }, 	 //	 291	 500
{ QN, ST, QN, QN, KN, QN, QN, SK, QN, KN, SH, QN, JA, SK, KN }, 	 //	 292	 500
{ QN, ST, QN, QN, KN, QN, QN, AC, QN, KN, SH, QN, KN, SK, KN }, 	 //	 293	 500
{ QN, QN, QN, LO, WN, QN, QN, PF, KN, TN, SH, QN, KN, KN, TN }, 	 //	 294	 500
{ QN, QN, AC, TN, LO, QN, QN, PF, TN, AC, SH, QN, QN, TN, AC }, 	 //	 295	 500
{ QN, QN, PF, LO, TN, QN, QN, QN, KN, AC, SH, QN, AC, KN, AC }, 	 //	 296	 500
{ QN, QN, QN, ST, QN, QN, QN, AC, JA, SH, SH, QN, KN, TN, JA }, 	 //	 297	 500
{ QN, QN, AC, JA, TN, QN, QN, KN, SH, TN, SH, SK, QN, TN, ST }, 	 //	 298	 500
{ QN, QN, AC, SH, TN, QN, QN, KN, TN, ST, SH, SK, QN, TN, AC }, 	 //	 299	 500
{ QN, QN, KN, SK, JA, QN, QN, QN, JA, JA, SH, SK, PF, JA, JA }, 	 //	 300	 500
{ QN, QN, KN, AC, TN, QN, QN, QN, AC, TN, SH, SK, PF, PF, ST }, 	 //	 301	 500
{ QN, QN, AC, AC, QN, QN, QN, PF, KN, QN, SH, SK, QN, QN, SH }, 	 //	 302	 500
{ QN, QN, QN, AC, AC, QN, QN, SK, AC, KN, SH, SK, JA, LO, QN }, 	 //	 303	 500
{ QN, QN, KN, PF, TN, QN, QN, PF, KN, TN, SH, SK, QN, KN, TN }, 	 //	 304	 500
{ QN, QN, PF, AC, JA, QN, QN, QN, AC, WN, SH, SK, AC, AC, TN }, 	 //	 305	 500
{ QN, QN, PF, AC, SK, QN, QN, QN, LO, QN, SH, SK, AC, KN, QN }, 	 //	 306	 500
{ QN, QN, PF, KN, JA, QN, QN, QN, WN, TN, SH, SK, AC, QN, AC }, 	 //	 307	 500
{ QN, QN, QN, KN, QN, QN, QN, AC, KN, QN, SH, SK, KN, WN, QN }, 	 //	 308	 500
{ QN, QN, QN, TN, QN, QN, SK, PF, TN, PF, SH, JA, KN, TN, JA }, 	 //	 309	 500
{ QN, QN, QN, WN, TN, QN, SK, AC, AC, TN, SH, JA, KN, KN, ST }, 	 //	 310	 500
{ QN, QN, QN, ST, SH, QN, SK, AC, JA, JA, SH, JA, KN, TN, JA }, 	 //	 311	 500
{ QN, TN, QN, QN, KN, QN, TN, PF, QN, SK, SH, WN, KN, QN, QN }, 	 //	 312	 500
{ QN, TN, KN, KN, QN, QN, TN, PF, QN, PF, SH, WN, QN, ST, JA }, 	 //	 313	 500
{ QN, KN, AC, AC, CR, QN, QN, PF, LO, KN, SH, ST, QN, KN, KN }, 	 //	 314	 500
{ QN, KN, KN, SH, QN, QN, QN, PF, TN, QN, SH, ST, QN, TN, SH }, 	 //	 315	 500
{ QN, KN, PF, TN, AC, QN, QN, QN, TN, AC, SH, ST, AC, WN, AC }, 	 //	 316	 500
{ QN, KN, PF, PF, KN, QN, QN, QN, KN, KN, SH, ST, AC, KN, CR }, 	 //	 317	 500
{ QN, QN, QN, AC, KN, QN, ST, PF, AC, SK, SH, JA, KN, AC, QN }, 	 //	 318	 500
{ QN, QN, QN, TN, KN, QN, ST, QN, WN, QN, SH, JA, QN, AC, PF }, 	 //	 319	 500
{ QN, QN, QN, TN, ST, QN, ST, QN, AC, AC, SH, JA, SK, AC, KN }, 	 //	 320	 500
{ QN, QN, QN, AC, JA, QN, ST, QN, AC, TN, SH, JA, SK, AC, AC }, 	 //	 321	 500
{ QN, QN, QN, AC, AC, QN, ST, QN, PF, KN, SH, JA, SK, KN, QN }, 	 //	 322	 500
{ QN, QN, QN, LO, AC, QN, ST, AC, KN, AC, SH, JA, KN, KN, AC }, 	 //	 323	 500
{ QN, QN, QN, SH, KN, QN, ST, AC, TN, KN, SH, JA, KN, TN, SK }, 	 //	 324	 500
{ QN, QN, QN, SH, SH, QN, ST, AC, TN, JA, SH, JA, KN, TN, JA }, 	 //	 325	 500
{ QN, QN, QN, KN, TN, QN, ST, AC, AC, ST, SH, JA, KN, PF, AC }, 	 //	 326	 500
{ QN, AC, PF, SK, CR, QN, AC, QN, QN, QN, SH, AC, AC, KN, KN }, 	 //	 327	 500
{ QN, AC, QN, QN, QN, QN, AC, PF, QN, KN, SH, PF, KN, SK, AC }, 	 //	 328	 500
{ QN, AC, QN, QN, CR, QN, PF, QN, QN, QN, SH, KN, SK, QN, KN }, 	 //	 329	 500
{ QN, PF, QN, QN, AC, QN, KN, SK, QN, KN, SH, KN, JA, QN, QN }, 	 //	 330	 500
{ QN, KN, QN, QN, QN, QN, KN, QN, QN, KN, SH, KN, SK, QN, AC }, 	 //	 331	 500
{ QN, SK, AC, JA, AC, QN, QN, KN, SH, AC, SH, KN, QN, TN, SK }, 	 //	 332	 500
{ QN, SK, AC, SH, PF, QN, QN, KN, TN, JA, SH, KN, QN, TN, TN }, 	 //	 333	 500
{ QN, SK, AC, TN, KN, QN, QN, KN, TN, KN, SH, KN, QN, WN, CR }, 	 //	 334	 500
{ QN, SK, AC, WN, WN, QN, QN, KN, AC, TN, SH, KN, QN, KN, TN }, 	 //	 335	 500
{ QN, SK, QN, QN, AC, QN, QN, QN, ST, KN, SH, KN, SK, JA, QN }, 	 //	 336	 500
{ QN, SK, QN, KN, QN, QN, QN, QN, AC, QN, SH, KN, SK, PF, QN }, 	 //	 337	 500
{ QN, SK, QN, KN, ST, QN, QN, AC, QN, AC, SH, KN, KN, ST, KN }, 	 //	 338	 500
{ QN, QN, QN, AC, TN, QN, KN, QN, AC, TN, SH, AC, QN, AC, TN }, 	 //	 339	 500
{ QN, QN, QN, ST, JA, QN, KN, QN, JA, JA, SH, AC, QN, TN, WN }, 	 //	 340	 500
{ QN, QN, QN, WN, KN, QN, KN, QN, AC, QN, SH, AC, SK, KN, PF }, 	 //	 341	 500
{ QN, QN, QN, KN, KN, QN, KN, QN, AC, KN, SH, AC, SK, PF, SK }, 	 //	 342	 500
{ QN, QN, QN, WN, KN, QN, KN, AC, QN, KN, SH, AC, KN, QN, CR }, 	 //	 343	 500
{ QN, KN, QN, QN, SK, QN, AC, PF, QN, QN, SH, SH, KN, QN, QN }, 	 //	 344	 500
{ QN, AC, QN, SK, CR, SH, AC, QN, QN, QN, JA, LO, SK, KN, KN }, 	 //	 345	 500
{ QN, AC, KN, KN, QN, SH, AC, PF, QN, KN, JA, LO, QN, ST, AC }, 	 //	 346	 500
{ QN, AC, QN, QN, QN, SH, LO, SK, QN, QN, JA, KN, JA, QN, SH }, 	 //	 347	 500
{ QN, KN, KN, QN, SK, SH, KN, QN, QN, QN, JA, ST, PF, QN, QN }, 	 //	 348	 500
{ QN, KN, QN, KN, SH, SH, ST, QN, WN, JA, JA, QN, QN, QN, JA }, 	 //	 349	 500
{ QN, KN, QN, QN, QN, SH, ST, SK, QN, KN, JA, QN, JA, QN, AC }, 	 //	 350	 500
{ QN, ST, AC, KN, CR, SH, QN, PF, KN, KN, JA, QN, QN, KN, KN }, 	 //	 351	 500
{ QN, ST, PF, AC, WN, SH, QN, QN, PF, TN, JA, QN, QN, AC, TN }, 	 //	 352	 500
{ QN, ST, QN, AC, KN, SH, QN, QN, AC, KN, JA, QN, QN, AC, SK }, 	 //	 353	 500
{ QN, ST, QN, TN, AC, SH, QN, QN, WN, AC, JA, QN, QN, AC, CR }, 	 //	 354	 500
{ QN, QN, AC, KN, KN, SH, QN, KN, KN, AC, JA, QN, QN, WN, LO }, 	 //	 355	 500
{ QN, QN, AC, JA, PF, SH, QN, PF, TN, JA, JA, QN, QN, AC, TN }, 	 //	 356	 500
{ QN, QN, QN, AC, QN, SH, QN, QN, AC, PF, JA, QN, SK, PF, JA }, 	 //	 357	 500
{ QN, QN, QN, KN, AC, SH, QN, SK, KN, AC, JA, QN, JA, KN, AC }, 	 //	 358	 500
{ QN, QN, KN, AC, QN, SH, QN, PF, PF, SH, JA, QN, QN, AC, JA }, 	 //	 359	 500
{ QN, QN, KN, LO, AC, SH, QN, PF, KN, AC, JA, QN, QN, KN, AC }, 	 //	 360	 500
{ QN, QN, QN, AC, JA, SH, QN, AC, AC, WN, JA, QN, KN, AC, TN }, 	 //	 361	 500
{ QN, QN, AC, TN, TN, SH, QN, KN, WN, ST, JA, SK, QN, AC, AC }, 	 //	 362	 500
{ QN, QN, AC, AC, TN, SH, QN, PF, KN, ST, JA, SK, QN, QN, AC }, 	 //	 363	 500
{ QN, QN, AC, KN, KN, SH, QN, PF, KN, KN, JA, SK, QN, KN, KN }, 	 //	 364	 500
{ QN, QN, QN, WN, JA, SH, QN, SK, AC, JA, JA, SK, JA, KN, WN }, 	 //	 365	 500
{ QN, QN, QN, JA, QN, SH, QN, AC, JA, SH, JA, SK, KN, JA, JA }, 	 //	 366	 500
{ QN, QN, QN, AC, JA, SH, QN, AC, PF, JA, JA, SK, KN, KN, JA }, 	 //	 367	 500
{ QN, QN, QN, KN, QN, SH, SK, PF, KN, SH, JA, JA, KN, KN, JA }, 	 //	 368	 500
{ QN, QN, QN, SH, JA, SH, SK, PF, TN, TN, JA, JA, KN, TN, AC }, 	 //	 369	 500
{ QN, QN, QN, TN, TN, SH, SK, PF, AC, ST, JA, JA, KN, AC, AC }, 	 //	 370	 500
{ QN, QN, QN, AC, AC, SH, SK, QN, AC, AC, JA, JA, QN, AC, SK }, 	 //	 371	 500
{ QN, QN, QN, KN, CR, SH, SK, QN, SK, QN, JA, JA, QN, QN, KN }, 	 //	 372	 500
{ QN, SK, KN, QN, QN, SH, JA, PF, QN, QN, JA, JA, QN, QN, SH }, 	 //	 373	 500
{ QN, JA, AC, SK, QN, SH, JA, PF, QN, PF, JA, JA, QN, KN, JA }, 	 //	 374	 500
{ QN, TN, QN, WN, KN, SH, TN, AC, QN, SK, JA, WN, KN, QN, QN }, 	 //	 375	 500
{ QN, TN, QN, QN, KN, SH, WN, QN, QN, SK, JA, AC, QN, SK, QN }, 	 //	 376	 500
{ QN, WN, PF, WN, QN, SH, AC, QN, QN, QN, JA, KN, AC, QN, QN }, 	 //	 377	 500
{ QN, AC, QN, QN, TN, SH, KN, QN, QN, AC, JA, QN, QN, QN, AC }, 	 //	 378	 500
{ QN, KN, AC, AC, KN, SH, QN, KN, AC, KN, JA, ST, QN, AC, SK }, 	 //	 379	 500
{ QN, KN, AC, QN, AC, SH, QN, PF, ST, AC, JA, ST, QN, JA, CR }, 	 //	 380	 500
{ QN, KN, PF, AC, KN, SH, QN, QN, AC, AC, JA, ST, QN, LO, LO }, 	 //	 381	 500
{ QN, KN, QN, PF, LO, SH, QN, QN, KN, AC, JA, ST, QN, KN, AC }, 	 //	 382	 500
{ QN, KN, KN, QN, QN, SH, QN, PF, KN, SH, JA, ST, QN, AC, JA }, 	 //	 383	 500
{ QN, KN, QN, QN, KN, SH, QN, AC, QN, AC, JA, ST, KN, SK, LO }, 	 //	 384	 500
{ QN, KN, QN, KN, KN, SH, QN, AC, QN, KN, JA, ST, KN, ST, CR }, 	 //	 385	 500
{ QN, QN, QN, AC, KN, SH, ST, QN, LO, AC, JA, JA, QN, KN, LO }, 	 //	 386	 500
{ QN, QN, QN, JA, QN, SH, ST, QN, JA, PF, JA, JA, QN, JA, JA }, 	 //	 387	 500
{ QN, QN, QN, AC, SK, SH, ST, QN, PF, QN, JA, JA, SK, KN, QN }, 	 //	 388	 500
{ QN, PF, QN, QN, QN, SH, KN, SK, ST, KN, JA, KN, JA, JA, AC }, 	 //	 389	 500
{ QN, KN, AC, SK, QN, SH, KN, KN, QN, KN, JA, SK, QN, KN, AC }, 	 //	 390	 500
{ QN, KN, AC, QN, QN, SH, KN, PF, QN, KN, JA, SK, QN, QN, AC }, 	 //	 391	 500
{ QN, KN, AC, QN, JA, SH, SK, KN, QN, JA, JA, QN, QN, QN, JA }, 	 //	 392	 500
{ QN, KN, QN, SK, QN, SH, SK, QN, QN, KN, JA, QN, QN, KN, AC }, 	 //	 393	 500
{ QN, SK, AC, TN, AC, SH, QN, PF, TN, LO, JA, KN, QN, TN, AC }, 	 //	 394	 500
{ QN, SK, QN, SK, QN, SH, QN, SK, QN, SH, JA, KN, JA, KN, JA }, 	 //	 395	 500
{ QN, SK, KN, TN, PF, SH, QN, PF, AC, JA, JA, KN, QN, AC, TN }, 	 //	 396	 500
{ QN, SK, KN, KN, WN, SH, QN, PF, KN, TN, JA, KN, QN, KN, TN }, 	 //	 397	 500
{ QN, SK, PF, KN, JA, SH, QN, QN, QN, JA, JA, KN, AC, ST, WN }, 	 //	 398	 500
{ QN, QN, QN, PF, QN, SH, KN, PF, AC, QN, JA, AC, KN, AC, QN }, 	 //	 399	 500
{ QN, QN, QN, JA, AC, SH, KN, QN, JA, AC, JA, AC, QN, SH, AC }, 	 //	 400	 500
{ QN, QN, QN, JA, CR, SH, KN, QN, JA, KN, JA, AC, SK, JA, KN }, 	 //	 401	 500
{ QN, QN, QN, KN, TN, SH, KN, QN, QN, TN, JA, AC, SK, ST, ST }, 	 //	 402	 500
{ SH, KN, AC, KN, QN, JA, ST, KN, WN, PF, JA, QN, QN, QN, JA }, 	 //	 403	 500
{ SH, KN, AC, WN, SK, JA, ST, KN, QN, KN, JA, QN, QN, QN, KN }, 	 //	 404	 500
{ SH, QN, QN, QN, JA, JA, QN, QN, ST, JA, JA, QN, SK, JA, JA }, 	 //	 405	 500
{ SH, QN, QN, KN, KN, JA, QN, SK, QN, KN, JA, SK, JA, ST, CR }, 	 //	 406	 500
{ SH, QN, QN, QN, SK, JA, QN, AC, ST, KN, JA, SK, KN, JA, KN }, 	 //	 407	 500
{ SH, QN, QN, QN, AC, JA, SK, AC, QN, AC, JA, JA, KN, SK, AC }, 	 //	 408	 500
{ SH, QN, QN, QN, AC, JA, ST, PF, SK, AC, JA, JA, KN, JA, AC }, 	 //	 409	 500
{ SH, KN, PF, AC, KN, JA, KN, QN, KN, SK, JA, KN, QN, QN, QN }, 	 //	 410	 500
{ SH, SK, KN, SK, KN, JA, QN, QN, QN, SK, JA, KN, PF, KN, QN }, 	 //	 411	 500
{ SH, SK, AC, WN, KN, JA, QN, PF, QN, KN, JA, KN, QN, QN, CR }, 	 //	 412	 500
{ JA, AC, PF, QN, QN, JA, AC, QN, QN, QN, JA, AC, AC, SK, SH }, 	 //	 413	 500
{ JA, AC, KN, QN, QN, JA, LO, PF, QN, PF, JA, KN, QN, QN, JA }, 	 //	 414	 500
{ JA, ST, AC, KN, TN, JA, QN, PF, QN, TN, JA, QN, QN, ST, TN }, 	 //	 415	 500
{ JA, ST, QN, QN, QN, JA, QN, SK, KN, SH, JA, QN, JA, AC, JA }, 	 //	 416	 500
{ JA, QN, QN, SK, KN, JA, QN, PF, QN, KN, JA, QN, KN, KN, SK }, 	 //	 417	 500
{ JA, QN, QN, QN, TN, JA, QN, PF, ST, ST, JA, SK, KN, JA, AC }, 	 //	 418	 500
{ JA, QN, QN, KN, CR, JA, QN, SK, QN, QN, JA, SK, JA, ST, KN }, 	 //	 419	 500
{ JA, TN, KN, WN, AC, JA, WN, PF, QN, KN, JA, AC, QN, QN, QN }, 	 //	 420	 500
{ JA, KN, KN, SK, AC, JA, QN, QN, QN, LO, JA, ST, PF, KN, AC }, 	 //	 421	 500
{ JA, SK, PF, WN, ST, JA, QN, QN, QN, AC, JA, KN, AC, QN, KN }, 	 //	 422	 500
{ JA, QN, QN, QN, ST, JA, KN, AC, ST, AC, JA, AC, KN, JA, KN }, 	 //	 423	 500
{ JA, KN, QN, WN, KN, JA, AC, QN, QN, QN, JA, SH, QN, QN, PF }, 	 //	 424	 500
{ JA, SH, QN, WN, SK, JA, AC, AC, QN, QN, WN, AC, KN, QN, QN }, 	 //	 425	 500
{ JA, AC, KN, WN, AC, JA, LO, PF, QN, KN, WN, KN, QN, QN, QN }, 	 //	 426	 500
{ JA, LO, PF, KN, QN, JA, KN, QN, QN, KN, WN, KN, QN, ST, AC }, 	 //	 427	 500
{ JA, ST, AC, KN, AC, JA, QN, KN, QN, SK, WN, QN, QN, ST, KN }, 	 //	 428	 500
{ JA, QN, KN, SK, TN, JA, QN, QN, QN, AC, WN, QN, PF, KN, AC }, 	 //	 429	 500
{ JA, QN, QN, WN, QN, JA, QN, SK, QN, SH, WN, QN, JA, QN, JA }, 	 //	 430	 500
{ JA, QN, KN, KN, TN, JA, QN, PF, QN, TN, WN, QN, QN, ST, ST }, 	 //	 431	 500
{ JA, QN, AC, SK, CR, JA, QN, KN, QN, KN, WN, SK, QN, KN, KN }, 	 //	 432	 500
{ JA, QN, QN, QN, ST, JA, QN, SK, KN, AC, WN, SK, JA, AC, KN }, 	 //	 433	 500
{ JA, JA, QN, QN, QN, JA, JA, QN, SK, KN, WN, JA, QN, JA, AC }, 	 //	 434	 500
{ JA, JA, AC, WN, QN, JA, JA, KN, QN, QN, WN, SH, QN, QN, SH }, 	 //	 435	 500
{ JA, AC, PF, KN, KN, JA, KN, QN, WN, KN, WN, QN, QN, QN, KN }, 	 //	 436	 500
{ JA, AC, QN, WN, AC, JA, KN, SK, QN, KN, WN, QN, JA, QN, QN }, 	 //	 437	 500
{ JA, AC, KN, KN, AC, JA, KN, PF, SK, AC, WN, QN, QN, QN, AC }, 	 //	 438	 500
{ JA, QN, QN, QN, SH, JA, ST, PF, KN, JA, WN, JA, KN, AC, JA }, 	 //	 439	 500
{ JA, QN, QN, QN, CR, JA, ST, QN, ST, QN, WN, JA, SK, JA, KN }, 	 //	 440	 500
{ JA, QN, QN, QN, AC, JA, ST, QN, KN, LO, WN, JA, SK, AC, AC }, 	 //	 441	 500
{ JA, PF, PF, WN, QN, JA, KN, QN, QN, QN, WN, KN, AC, QN, SH }, 	 //	 442	 500
{ JA, KN, AC, KN, JA, JA, SK, PF, SK, WN, WN, QN, QN, QN, TN }, 	 //	 443	 500
{ JA, KN, PF, KN, AC, JA, SK, QN, WN, AC, WN, QN, QN, QN, AC }, 	 //	 444	 500
{ JA, QN, QN, QN, KN, JA, KN, QN, ST, KN, WN, AC, SK, JA, CR }, 	 //	 445	 500
{ JA, SH, QN, QN, QN, WN, AC, PF, QN, KN, TN, AC, KN, QN, AC }, 	 //	 446	 500
{ JA, SH, QN, QN, QN, WN, AC, AC, QN, PF, TN, AC, KN, QN, JA }, 	 //	 447	 500
{ JA, AC, QN, WN, KN, WN, AC, QN, QN, QN, TN, AC, SK, QN, PF }, 	 //	 448	 500
{ JA, KN, AC, AC, TN, WN, ST, KN, KN, ST, TN, QN, QN, QN, AC }, 	 //	 449	 500
{ JA, ST, QN, QN, QN, WN, QN, PF, SK, SH, TN, QN, KN, JA, JA }, 	 //	 450	 500
{ JA, ST, QN, KN, QN, WN, QN, QN, WN, KN, TN, QN, QN, QN, AC }, 	 //	 451	 500
{ JA, QN, AC, KN, TN, WN, QN, PF, QN, ST, TN, QN, QN, ST, AC }, 	 //	 452	 500
{ JA, QN, PF, SK, JA, WN, QN, QN, QN, JA, TN, QN, AC, KN, JA }, 	 //	 453	 500
{ JA, JA, PF, KN, KN, WN, JA, QN, WN, SK, TN, JA, QN, QN, QN }, 	 //	 454	 500
{ JA, JA, QN, QN, KN, WN, JA, QN, QN, SK, TN, SH, QN, SK, QN }, 	 //	 455	 500
{ JA, JA, QN, WN, SK, WN, SH, PF, QN, QN, TN, TN, KN, QN, QN }, 	 //	 456	 500
{ JA, SH, TN, JA, AC, WN, TN, TN, TN, AC, TN, TN, TN, AC, SK }, 	 //	 457	 500
{ JA, SH, QN, KN, KN, WN, TN, QN, WN, SK, TN, TN, QN, QN, QN }, 	 //	 458	 500
{ JA, TN, PF, QN, CR, WN, TN, QN, QN, QN, TN, TN, AC, SK, KN }, 	 //	 459	 500
{ JA, WN, AC, KN, QN, WN, AC, PF, SK, QN, TN, KN, QN, QN, QN }, 	 //	 460	 500
{ JA, KN, QN, KN, SK, WN, QN, QN, WN, QN, TN, ST, QN, QN, QN }, 	 //	 461	 500
{ JA, KN, PF, QN, KN, WN, QN, QN, QN, KN, TN, ST, AC, QN, KN }, 	 //	 462	 500
{ JA, KN, PF, QN, AC, WN, QN, QN, QN, KN, TN, ST, AC, QN, QN }, 	 //	 463	 500
{ JA, AC, PF, WN, QN, WN, PF, QN, QN, SH, TN, KN, QN, QN, JA }, 	 //	 464	 500
{ JA, AC, QN, QN, SK, WN, PF, AC, QN, QN, TN, KN, KN, QN, QN }, 	 //	 465	 500
{ JA, KN, AC, KN, QN, WN, SK, KN, WN, PF, TN, QN, QN, QN, JA }, 	 //	 466	 500
{ JA, QN, QN, QN, TN, WN, KN, PF, QN, TN, TN, AC, KN, QN, ST }, 	 //	 467	 500
{ WN, SH, QN, KN, SK, TN, AC, SK, QN, QN, TN, AC, JA, ST, QN }, 	 //	 468	 500
{ WN, AC, AC, SK, QN, TN, AC, PF, QN, PF, TN, AC, QN, KN, JA }, 	 //	 469	 500
{ WN, AC, QN, QN, QN, TN, AC, SK, ST, QN, TN, AC, JA, JA, QN }, 	 //	 470	 500
{ WN, KN, QN, SK, KN, TN, KN, QN, QN, SK, TN, KN, SK, KN, QN }, 	 //	 471	 500
{ WN, KN, KN, SK, QN, TN, KN, PF, QN, QN, TN, ST, QN, KN, QN }, 	 //	 472	 500
{ WN, KN, QN, QN, QN, TN, ST, QN, KN, PF, TN, QN, SK, AC, JA }, 	 //	 473	 500
{ WN, ST, AC, QN, TN, TN, QN, PF, QN, ST, TN, QN, QN, SK, AC }, 	 //	 474	 500
{ WN, ST, QN, QN, AC, TN, QN, SK, QN, SK, TN, QN, JA, SK, KN }, 	 //	 475	 500
{ WN, ST, PF, WN, ST, TN, QN, QN, QN, AC, TN, QN, AC, QN, KN }, 	 //	 476	 500
{ WN, QN, QN, QN, TN, TN, QN, AC, ST, AC, TN, SK, KN, JA, AC }, 	 //	 477	 500
{ WN, JA, AC, QN, AC, TN, SH, KN, QN, KN, TN, TN, QN, QN, QN }, 	 //	 478	 500
{ WN, JA, QN, WN, QN, TN, SH, SK, QN, QN, TN, TN, JA, QN, QN }, 	 //	 479	 500
{ WN, TN, AC, KN, QN, TN, TN, KN, SK, QN, TN, TN, QN, QN, QN }, 	 //	 480	 500
{ WN, AC, PF, QN, CR, TN, AC, QN, QN, QN, TN, PF, QN, SK, KN }, 	 //	 481	 500
{ WN, KN, KN, QN, QN, TN, KN, QN, QN, QN, TN, KN, PF, SK, SH }, 	 //	 482	 500
{ WN, KN, QN, WN, QN, TN, KN, QN, QN, PF, TN, KN, QN, QN, JA }, 	 //	 483	 500
{ WN, KN, QN, QN, AC, TN, SK, QN, QN, SK, TN, QN, QN, QN, KN }, 	 //	 484	 500
{ WN, SK, AC, KN, CR, TN, QN, KN, QN, QN, TN, KN, QN, ST, KN }, 	 //	 485	 500
{ WN, SK, QN, KN, JA, TN, QN, SK, QN, JA, TN, KN, JA, ST, WN }, 	 //	 486	 500
{ WN, QN, KN, QN, AC, TN, KN, PF, QN, KN, TN, AC, QN, QN, QN }, 	 //	 487	 500
{ WN, KN, KN, QN, QN, TN, AC, PF, QN, SH, TN, SH, QN, QN, JA }, 	 //	 488	 500
{ TN, LO, QN, QN, QN, TN, KN, AC, SK, QN, TN, KN, KN, JA, QN }, 	 //	 489	 500
{ TN, KN, KN, WN, SK, TN, KN, QN, QN, QN, TN, ST, PF, QN, QN }, 	 //	 490	 500
{ TN, KN, AC, WN, JA, TN, ST, KN, QN, JA, TN, QN, QN, QN, JA }, 	 //	 491	 500
{ TN, ST, AC, KN, JA, TN, QN, KN, SK, WN, TN, QN, QN, QN, TN }, 	 //	 492	 500
{ TN, ST, PF, KN, KN, TN, QN, QN, WN, KN, TN, QN, QN, QN, KN }, 	 //	 493	 500
{ TN, QN, QN, WN, JA, TN, QN, PF, QN, JA, TN, SK, KN, QN, WN }, 	 //	 494	 500
{ TN, QN, QN, QN, ST, TN, QN, SK, KN, AC, TN, SK, JA, AC, KN }, 	 //	 495	 500
{ TN, JA, AC, WN, QN, TN, JA, PF, QN, QN, TN, SH, QN, QN, SH }, 	 //	 496	 500
{ TN, SH, QN, SK, AC, TN, TN, QN, QN, KN, TN, TN, SK, KN, QN }, 	 //	 497	 500
{ TN, WN, QN, SK, KN, TN, AC, QN, QN, SK, TN, KN, QN, KN, QN }, 	 //	 498	 500
{ TN, AC, AC, QN, QN, TN, KN, KN, QN, KN, TN, QN, QN, SK, AC }, 	 //	 499	 500
{ TN, KN, AC, WN, PF, TN, SK, PF, QN, JA, TN, QN, QN, QN, TN }, 	 //	 500	 500
{ TN, SK, KN, QN, JA, TN, QN, QN, QN, TN, TN, KN, PF, QN, AC }, 	 //	 501	 500
{ TN, SK, KN, KN, JA, TN, QN, QN, QN, TN, TN, KN, PF, ST, AC }, 	 //	 502	 500
{ TN, SK, AC, WN, KN, TN, QN, PF, QN, KN, TN, KN, QN, QN, KN }, 	 //	 503	 500
{ TN, AC, QN, QN, QN, TN, SH, AC, ST, QN, ST, AC, KN, JA, SH }, 	 //	 504	 500
{ TN, AC, KN, AC, AC, TN, LO, PF, KN, KN, ST, KN, QN, QN, QN }, 	 //	 505	 500
{ TN, KN, KN, AC, KN, TN, ST, PF, KN, KN, ST, QN, QN, QN, CR }, 	 //	 506	 500
{ TN, QN, AC, KN, JA, TN, QN, KN, SK, JA, ST, QN, QN, QN, WN }, 	 //	 507	 500
{ TN, QN, QN, QN, AC, TN, QN, AC, ST, KN, ST, SK, KN, JA, QN }, 	 //	 508	 500
{ TN, JA, QN, QN, QN, TN, JA, PF, QN, QN, ST, SH, KN, QN, SH }, 	 //	 509	 500
{ TN, TN, PF, QN, AC, TN, TN, QN, QN, KN, ST, WN, QN, QN, QN }, 	 //	 510	 500
{ TN, KN, QN, QN, JA, TN, QN, AC, QN, TN, ST, ST, KN, QN, AC }, 	 //	 511	 500
{ TN, ST, PF, KN, QN, TN, JA, QN, SK, QN, ST, TN, QN, QN, QN }, 	 //	 512	 500
{ TN, KN, PF, SK, KN, TN, KN, QN, QN, QN, ST, SK, QN, KN, PF }, 	 //	 513	 500
{ TN, SK, AC, QN, KN, TN, QN, PF, QN, KN, ST, KN, QN, SK, KN }, 	 //	 514	 500
{ TN, KN, KN, WN, QN, TN, AC, QN, QN, QN, ST, SH, PF, QN, SH }, 	 //	 515	 500
{ TN, AC, PF, QN, QN, ST, AC, QN, QN, SH, AC, AC, QN, SK, JA }, 	 //	 516	 500
{ TN, KN, KN, QN, QN, ST, KN, PF, QN, KN, AC, ST, QN, QN, AC }, 	 //	 517	 500
{ TN, ST, AC, QN, TN, ST, QN, KN, QN, ST, AC, QN, QN, SK, AC }, 	 //	 518	 500
{ TN, ST, AC, SK, CR, ST, QN, PF, QN, QN, AC, QN, QN, KN, KN }, 	 //	 519	 500
{ TN, QN, QN, KN, AC, ST, QN, PF, QN, LO, AC, QN, KN, ST, AC }, 	 //	 520	 500
{ TN, QN, AC, KN, KN, ST, QN, PF, QN, QN, AC, QN, QN, ST, PF }, 	 //	 521	 500
{ TN, QN, QN, QN, JA, ST, QN, QN, KN, JA, AC, QN, SK, AC, WN }, 	 //	 522	 500
{ TN, QN, KN, WN, ST, ST, QN, QN, QN, AC, AC, SK, PF, QN, KN }, 	 //	 523	 500
{ TN, QN, PF, QN, AC, ST, QN, QN, QN, AC, AC, SK, AC, SK, AC }, 	 //	 524	 500
{ TN, QN, QN, WN, QN, ST, QN, AC, QN, QN, AC, SK, KN, QN, SH }, 	 //	 525	 500
{ TN, QN, QN, QN, AC, ST, QN, AC, ST, AC, AC, SK, KN, JA, AC }, 	 //	 526	 500
{ TN, SK, PF, SK, QN, ST, JA, QN, QN, QN, AC, JA, AC, KN, QN }, 	 //	 527	 500
{ TN, SH, QN, QN, AC, ST, TN, QN, QN, KN, AC, TN, SK, QN, QN }, 	 //	 528	 500
{ TN, TN, AC, QN, QN, ST, TN, PF, QN, PF, AC, WN, QN, QN, JA }, 	 //	 529	 500
{ TN, KN, QN, QN, QN, ST, QN, QN, ST, QN, AC, ST, SK, JA, QN }, 	 //	 530	 500
{ TN, JA, AC, KN, QN, ST, TN, KN, WN, QN, AC, AC, QN, QN, QN }, 	 //	 531	 500
{ TN, AC, KN, QN, QN, ST, AC, QN, QN, QN, AC, PF, PF, SK, QN }, 	 //	 532	 500
{ ST, LO, PF, KN, CR, AC, KN, QN, QN, QN, KN, KN, QN, ST, KN }, 	 //	 533	 500
{ ST, KN, AC, KN, AC, AC, ST, PF, WN, AC, KN, QN, QN, QN, AC }, 	 //	 534	 500
{ ST, ST, QN, KN, QN, AC, QN, SK, QN, QN, KN, QN, JA, ST, SH }, 	 //	 535	 500
{ ST, QN, AC, AC, TN, AC, QN, PF, KN, TN, KN, QN, QN, QN, ST }, 	 //	 536	 500
{ ST, QN, AC, KN, AC, AC, QN, PF, SK, AC, KN, QN, QN, QN, CR }, 	 //	 537	 500
{ ST, QN, PF, WN, KN, AC, QN, QN, QN, KN, KN, QN, AC, QN, SK }, 	 //	 538	 500
{ ST, QN, AC, WN, KN, AC, QN, KN, QN, KN, KN, SK, QN, QN, SK }, 	 //	 539	 500
{ ST, QN, QN, KN, WN, AC, QN, PF, QN, TN, KN, SK, KN, ST, TN }, 	 //	 540	 500
{ ST, QN, KN, QN, KN, AC, QN, PF, QN, SK, KN, SK, QN, SK, QN }, 	 //	 541	 500
{ ST, JA, KN, KN, QN, AC, SH, PF, QN, SH, KN, TN, QN, ST, JA }, 	 //	 542	 500
{ ST, KN, KN, QN, LO, AC, QN, QN, QN, AC, KN, ST, PF, SK, AC }, 	 //	 543	 500
{ ST, KN, AC, SK, TN, AC, QN, PF, QN, TN, KN, ST, QN, KN, ST }, 	 //	 544	 500
{ ST, KN, QN, WN, PF, AC, QN, AC, QN, JA, KN, ST, KN, QN, TN }, 	 //	 545	 500
{ ST, AC, QN, SK, AC, AC, AC, QN, QN, KN, KN, AC, SK, KN, QN }, 	 //	 546	 500
{ ST, AC, QN, KN, KN, AC, PF, QN, QN, SK, KN, KN, QN, ST, QN }, 	 //	 547	 500
{ ST, PF, QN, WN, KN, AC, KN, QN, QN, QN, KN, KN, SK, QN, PF }, 	 //	 548	 500
{ ST, KN, KN, WN, AC, AC, SK, PF, QN, AC, KN, QN, QN, QN, AC }, 	 //	 549	 500
{ ST, KN, QN, QN, QN, AC, SK, AC, KN, SH, KN, QN, KN, AC, JA }, 	 //	 550	 500
{ AC, SH, AC, KN, QN, KN, AC, KN, QN, QN, QN, AC, QN, ST, QN }, 	 //	 551	 500
{ AC, KN, AC, KN, TN, KN, ST, KN, AC, TN, QN, QN, QN, PF, ST }, 	 //	 552	 500
{ AC, KN, QN, KN, KN, KN, ST, PF, QN, SK, QN, QN, KN, ST, QN }, 	 //	 553	 500
{ AC, KN, AC, AC, KN, KN, ST, PF, LO, KN, QN, QN, QN, KN, KN }, 	 //	 554	 500
{ AC, KN, AC, JA, SK, KN, ST, PF, JA, KN, QN, QN, QN, SH, KN }, 	 //	 555	 500
{ AC, KN, PF, SK, JA, KN, ST, QN, JA, WN, QN, QN, QN, JA, TN }, 	 //	 556	 500
{ AC, KN, QN, JA, QN, KN, ST, QN, SH, KN, QN, QN, QN, TN, AC }, 	 //	 557	 500
{ AC, ST, AC, PF, WN, KN, QN, KN, KN, TN, QN, QN, QN, KN, TN }, 	 //	 558	 500
{ AC, ST, KN, QN, JA, KN, QN, QN, QN, TN, QN, QN, PF, QN, AC }, 	 //	 559	 500
{ AC, ST, KN, KN, SH, KN, QN, QN, QN, JA, QN, QN, PF, ST, JA }, 	 //	 560	 500
{ AC, ST, QN, AC, JA, KN, QN, PF, LO, TN, QN, QN, KN, KN, AC }, 	 //	 561	 500
{ AC, ST, QN, AC, AC, KN, QN, PF, KN, SK, QN, QN, KN, QN, KN }, 	 //	 562	 500
{ AC, ST, AC, JA, AC, KN, QN, PF, TN, SK, QN, QN, QN, AC, KN }, 	 //	 563	 500
{ AC, ST, QN, JA, KN, KN, QN, QN, JA, QN, QN, QN, SK, JA, PF }, 	 //	 564	 500
{ AC, ST, QN, TN, WN, KN, QN, SK, WN, TN, QN, QN, JA, AC, TN }, 	 //	 565	 500
{ AC, ST, KN, TN, KN, KN, QN, PF, TN, KN, QN, QN, QN, WN, CR }, 	 //	 566	 500
{ AC, QN, QN, SK, QN, KN, QN, PF, JA, KN, QN, QN, KN, JA, AC }, 	 //	 567	 500
{ AC, QN, QN, ST, ST, KN, QN, PF, JA, AC, QN, QN, KN, TN, KN }, 	 //	 568	 500
{ AC, QN, PF, JA, KN, KN, QN, QN, JA, KN, QN, QN, QN, SH, SK }, 	 //	 569	 500
{ AC, QN, QN, PF, TN, KN, QN, QN, AC, AC, QN, QN, SK, AC, AC }, 	 //	 570	 500
{ AC, QN, QN, KN, AC, KN, QN, QN, KN, AC, QN, QN, SK, WN, CR }, 	 //	 571	 500
{ AC, QN, KN, KN, ST, KN, QN, PF, AC, AC, QN, QN, QN, PF, KN }, 	 //	 572	 500
{ AC, QN, AC, KN, SK, KN, QN, KN, QN, QN, QN, SK, QN, ST, QN }, 	 //	 573	 500
{ AC, QN, AC, QN, SH, KN, QN, PF, QN, JA, QN, SK, QN, QN, JA }, 	 //	 574	 500
{ AC, QN, QN, TN, TN, KN, QN, QN, AC, ST, QN, SK, QN, AC, AC }, 	 //	 575	 500
{ AC, QN, QN, PF, TN, KN, QN, SK, KN, TN, QN, SK, JA, KN, TN }, 	 //	 576	 500
{ AC, QN, KN, QN, TN, KN, QN, PF, QN, AC, QN, SK, QN, SK, AC }, 	 //	 577	 500
{ AC, QN, QN, PF, SK, KN, QN, AC, KN, QN, QN, SK, KN, KN, QN }, 	 //	 578	 500
{ AC, SH, KN, QN, QN, KN, TN, PF, QN, PF, QN, TN, QN, SK, JA }, 	 //	 579	 500
{ AC, AC, QN, KN, AC, KN, KN, PF, QN, KN, QN, QN, KN, ST, QN }, 	 //	 580	 500
{ AC, AC, PF, QN, JA, KN, KN, QN, ST, JA, QN, QN, QN, JA, WN }, 	 //	 581	 500
{ AC, AC, QN, TN, AC, KN, KN, QN, WN, AC, QN, QN, QN, AC, SK }, 	 //	 582	 500
{ AC, AC, QN, KN, WN, KN, KN, QN, AC, TN, QN, QN, QN, PF, TN }, 	 //	 583	 500
{ AC, KN, AC, SK, AC, KN, QN, KN, QN, SK, QN, ST, QN, KN, KN }, 	 //	 584	 500
{ AC, KN, QN, KN, LO, KN, QN, QN, WN, AC, QN, ST, QN, QN, AC }, 	 //	 585	 500
{ AC, KN, QN, JA, KN, KN, QN, QN, SH, KN, QN, ST, SK, TN, KN }, 	 //	 586	 500
{ AC, KN, QN, QN, TN, KN, QN, AC, SK, ST, QN, ST, KN, JA, AC }, 	 //	 587	 500
{ AC, QN, PF, QN, QN, KN, ST, QN, QN, PF, QN, JA, QN, QN, JA }, 	 //	 588	 500
{ AC, QN, KN, KN, QN, KN, ST, PF, WN, QN, QN, JA, QN, QN, QN }, 	 //	 589	 500
{ AC, QN, QN, QN, LO, KN, ST, AC, KN, AC, QN, JA, KN, AC, AC }, 	 //	 590	 500
{ AC, AC, QN, WN, AC, KN, PF, AC, QN, KN, QN, KN, KN, QN, QN }, 	 //	 591	 500
{ AC, KN, AC, SK, TN, KN, SK, KN, JA, ST, QN, QN, QN, JA, AC }, 	 //	 592	 500
{ AC, KN, AC, AC, KN, KN, SK, PF, LO, KN, QN, QN, QN, KN, KN }, 	 //	 593	 500
{ AC, KN, AC, AC, KN, KN, SK, PF, AC, AC, QN, QN, QN, AC, LO }, 	 //	 594	 500
{ AC, KN, QN, KN, JA, KN, SK, QN, KN, TN, QN, QN, QN, SK, AC }, 	 //	 595	 500
{ AC, SK, QN, TN, AC, KN, QN, PF, TN, AC, QN, KN, KN, WN, AC }, 	 //	 596	 500
{ AC, SK, AC, SK, JA, KN, QN, PF, QN, WN, QN, KN, QN, KN, TN }, 	 //	 597	 500
{ AC, SK, QN, QN, KN, KN, QN, QN, ST, QN, QN, KN, QN, JA, PF }, 	 //	 598	 500
{ AC, SK, QN, JA, KN, KN, QN, QN, JA, QN, QN, KN, SK, SH, PF }, 	 //	 599	 500
{ AC, SK, QN, TN, JA, KN, QN, QN, TN, JA, QN, KN, SK, WN, WN }, 	 //	 600	 500
{ AC, QN, QN, QN, JA, KN, KN, PF, QN, JA, QN, AC, KN, SK, JA }, 	 //	 601	 500
{ AC, QN, PF, AC, AC, KN, KN, QN, KN, KN, QN, AC, QN, QN, QN }, 	 //	 602	 500
{ AC, QN, QN, QN, KN, KN, KN, SK, QN, QN, QN, AC, JA, SK, PF }, 	 //	 603	 500
{ KN, SH, PF, WN, QN, QN, AC, QN, QN, KN, PF, AC, QN, QN, AC }, 	 //	 604	 500
{ KN, SH, PF, SK, CR, QN, AC, QN, QN, QN, PF, AC, AC, KN, KN }, 	 //	 605	 500
{ KN, AC, AC, SK, QN, QN, AC, PF, QN, QN, PF, AC, QN, KN, QN }, 	 //	 606	 500
{ KN, AC, KN, KN, QN, QN, AC, PF, QN, QN, PF, AC, QN, ST, QN }, 	 //	 607	 500
{ KN, AC, QN, QN, QN, QN, AC, AC, ST, QN, PF, AC, KN, JA, QN }, 	 //	 608	 500
{ KN, ST, QN, AC, TN, QN, QN, QN, LO, TN, PF, QN, QN, KN, TN }, 	 //	 609	 500
{ KN, ST, QN, AC, AC, QN, QN, QN, AC, AC, PF, QN, SK, LO, AC }, 	 //	 610	 500
{ KN, ST, PF, TN, JA, QN, QN, QN, AC, JA, PF, QN, AC, AC, WN }, 	 //	 611	 500
{ KN, QN, AC, QN, SH, QN, QN, PF, QN, JA, PF, QN, QN, SK, JA }, 	 //	 612	 500
{ KN, QN, QN, TN, KN, QN, QN, QN, AC, KN, PF, QN, SK, AC, KN }, 	 //	 613	 500
{ KN, QN, QN, QN, WN, QN, QN, SK, ST, TN, PF, QN, JA, JA, TN }, 	 //	 614	 500
{ KN, QN, KN, AC, JA, QN, QN, PF, KN, JA, PF, QN, QN, QN, JA }, 	 //	 615	 500
{ KN, QN, PF, KN, AC, QN, QN, QN, KN, AC, PF, QN, AC, WN, AC }, 	 //	 616	 500
{ KN, QN, PF, KN, TN, QN, QN, QN, WN, ST, PF, QN, AC, QN, AC }, 	 //	 617	 500
{ KN, QN, PF, JA, JA, QN, QN, QN, TN, WN, PF, SK, QN, AC, TN }, 	 //	 618	 500
{ KN, QN, QN, QN, KN, QN, SK, AC, QN, QN, PF, JA, KN, QN, PF }, 	 //	 619	 500
{ KN, QN, QN, QN, KN, QN, SK, AC, QN, KN, PF, JA, KN, SK, CR }, 	 //	 620	 500
{ KN, TN, AC, AC, KN, QN, TN, PF, KN, SK, PF, WN, QN, QN, QN }, 	 //	 621	 500
{ KN, TN, QN, WN, SK, QN, WN, PF, QN, QN, PF, AC, KN, QN, QN }, 	 //	 622	 500
{ KN, KN, PF, AC, QN, QN, QN, QN, KN, SH, PF, ST, QN, QN, JA }, 	 //	 623	 500
{ KN, KN, QN, KN, TN, QN, QN, QN, KN, TN, PF, ST, QN, KN, ST }, 	 //	 624	 500
{ KN, KN, PF, JA, WN, QN, QN, QN, JA, TN, PF, ST, AC, SH, TN }, 	 //	 625	 500
{ KN, QN, QN, QN, JA, QN, ST, SK, QN, JA, PF, JA, JA, SK, WN }, 	 //	 626	 500
{ KN, ST, QN, QN, QN, QN, JA, PF, KN, SH, PF, TN, KN, AC, JA }, 	 //	 627	 500
{ KN, ST, QN, QN, CR, QN, JA, QN, QN, QN, PF, TN, SK, QN, KN }, 	 //	 628	 500
{ KN, AC, QN, WN, KN, QN, PF, QN, QN, SK, PF, KN, SK, QN, QN }, 	 //	 629	 500
{ KN, PF, QN, QN, QN, QN, KN, QN, SK, KN, PF, KN, QN, JA, AC }, 	 //	 630	 500
{ KN, KN, PF, AC, AC, QN, SK, QN, KN, AC, PF, QN, QN, QN, SK }, 	 //	 631	 500
{ KN, SK, AC, AC, SK, QN, QN, KN, KN, QN, PF, KN, QN, QN, QN }, 	 //	 632	 500
{ KN, SK, AC, SK, AC, QN, QN, KN, QN, AC, PF, KN, QN, KN, SK }, 	 //	 633	 500
{ KN, SK, KN, TN, QN, QN, QN, QN, TN, SH, PF, KN, PF, WN, JA }, 	 //	 634	 500
{ KN, SK, KN, TN, SH, QN, QN, QN, AC, JA, PF, KN, PF, AC, JA }, 	 //	 635	 500
{ KN, SK, AC, SK, AC, QN, QN, PF, QN, AC, PF, KN, QN, KN, AC }, 	 //	 636	 500
{ KN, SK, PF, SK, JA, QN, QN, QN, JA, TN, PF, KN, QN, JA, AC }, 	 //	 637	 500
{ KN, SK, QN, AC, KN, QN, QN, QN, PF, KN, PF, KN, QN, AC, SK }, 	 //	 638	 500
{ KN, SK, KN, KN, AC, QN, QN, PF, QN, LO, PF, KN, QN, ST, AC }, 	 //	 639	 500
{ KN, SK, PF, AC, QN, QN, QN, QN, LO, SH, PF, KN, AC, KN, JA }, 	 //	 640	 500
{ KN, SK, PF, AC, QN, QN, QN, QN, LO, KN, PF, KN, AC, KN, AC }, 	 //	 641	 500
{ KN, SK, PF, QN, TN, QN, QN, QN, KN, TN, PF, KN, AC, AC, ST }, 	 //	 642	 500
{ QN, AC, QN, QN, QN, PF, SH, AC, QN, QN, JA, AC, KN, SK, SH }, 	 //	 643	 500
{ QN, AC, QN, WN, CR, PF, AC, QN, QN, QN, JA, AC, QN, QN, KN }, 	 //	 644	 500
{ QN, AC, KN, WN, QN, PF, LO, QN, QN, QN, JA, KN, PF, QN, SH }, 	 //	 645	 500
{ QN, AC, QN, QN, QN, PF, LO, SK, QN, QN, JA, KN, JA, QN, SH }, 	 //	 646	 500
{ QN, ST, AC, QN, QN, PF, QN, KN, ST, QN, JA, QN, QN, JA, SH }, 	 //	 647	 500
{ QN, ST, KN, TN, JA, PF, QN, PF, AC, TN, JA, QN, QN, AC, AC }, 	 //	 648	 500
{ QN, QN, QN, KN, CR, PF, QN, PF, SK, QN, JA, QN, KN, QN, KN }, 	 //	 649	 500
{ QN, QN, PF, WN, ST, PF, QN, QN, AC, AC, JA, QN, QN, KN, KN }, 	 //	 650	 500
{ QN, QN, QN, AC, PF, PF, QN, QN, AC, JA, JA, QN, SK, AC, TN }, 	 //	 651	 500
{ QN, QN, KN, KN, LO, PF, QN, PF, KN, AC, JA, QN, QN, KN, AC }, 	 //	 652	 500
{ QN, QN, QN, SK, AC, PF, QN, AC, JA, AC, JA, QN, KN, JA, CR }, 	 //	 653	 500
{ QN, QN, QN, JA, AC, PF, QN, AC, JA, AC, JA, QN, KN, SH, AC }, 	 //	 654	 500
{ QN, QN, AC, SH, KN, PF, QN, KN, TN, KN, JA, SK, QN, TN, KN }, 	 //	 655	 500
{ QN, QN, AC, JA, KN, PF, QN, KN, TN, AC, JA, SK, QN, AC, LO }, 	 //	 656	 500
{ QN, QN, AC, AC, QN, PF, QN, KN, PF, SH, JA, SK, QN, KN, JA }, 	 //	 657	 500
{ QN, QN, QN, TN, KN, PF, QN, PF, TN, KN, JA, SK, KN, WN, SK }, 	 //	 658	 500
{ QN, QN, PF, JA, KN, PF, QN, QN, JA, AC, JA, SK, QN, SH, LO }, 	 //	 659	 500
{ QN, QN, KN, WN, TN, PF, QN, PF, AC, TN, JA, SK, QN, KN, ST }, 	 //	 660	 500
{ QN, QN, KN, KN, TN, PF, QN, PF, KN, TN, JA, SK, QN, SK, ST }, 	 //	 661	 500
{ QN, QN, KN, QN, AC, PF, QN, PF, KN, KN, JA, SK, QN, AC, QN }, 	 //	 662	 500
{ QN, QN, QN, AC, QN, PF, QN, AC, PF, KN, JA, SK, KN, AC, AC }, 	 //	 663	 500
{ QN, QN, QN, AC, QN, PF, SK, PF, KN, QN, JA, JA, KN, QN, SH }, 	 //	 664	 500
{ QN, QN, QN, PF, AC, PF, SK, QN, KN, LO, JA, JA, QN, KN, AC }, 	 //	 665	 500
{ QN, KN, PF, AC, KN, PF, QN, QN, AC, AC, JA, ST, QN, LO, LO }, 	 //	 666	 500
{ QN, KN, QN, LO, KN, PF, QN, QN, KN, SK, JA, ST, QN, KN, QN }, 	 //	 667	 500
{ QN, KN, PF, KN, SH, PF, QN, QN, QN, JA, JA, ST, AC, ST, JA }, 	 //	 668	 500
{ QN, KN, QN, WN, QN, PF, QN, AC, QN, PF, JA, ST, KN, QN, JA }, 	 //	 669	 500
{ QN, QN, QN, JA, TN, PF, ST, QN, TN, TN, JA, JA, QN, AC, TN }, 	 //	 670	 500
{ QN, QN, QN, JA, AC, PF, ST, QN, JA, AC, JA, JA, SK, SH, AC }, 	 //	 671	 500
{ QN, QN, QN, JA, QN, PF, ST, AC, SH, QN, JA, JA, KN, TN, QN }, 	 //	 672	 500
{ QN, QN, QN, AC, TN, PF, ST, AC, AC, TN, JA, JA, KN, AC, TN }, 	 //	 673	 500
{ QN, QN, QN, KN, QN, PF, ST, AC, KN, KN, JA, JA, KN, SK, AC }, 	 //	 674	 500
{ QN, ST, QN, QN, QN, PF, JA, PF, QN, QN, JA, TN, KN, QN, SH }, 	 //	 675	 500
{ QN, AC, AC, WN, QN, PF, AC, PF, QN, SH, JA, AC, QN, QN, JA }, 	 //	 676	 500
{ QN, KN, QN, QN, SK, PF, KN, PF, QN, QN, JA, SK, KN, SK, QN }, 	 //	 677	 500
{ QN, KN, AC, KN, AC, PF, SK, PF, WN, AC, JA, QN, QN, QN, AC }, 	 //	 678	 500
{ QN, SK, AC, AC, QN, PF, QN, KN, AC, QN, JA, KN, QN, LO, SH }, 	 //	 679	 500
{ QN, SK, AC, TN, JA, PF, QN, KN, TN, TN, JA, KN, QN, TN, AC }, 	 //	 680	 500
{ QN, SK, PF, SH, JA, PF, QN, QN, TN, TN, JA, KN, QN, TN, AC }, 	 //	 681	 500
{ QN, SK, PF, TN, KN, PF, QN, QN, TN, SK, JA, KN, QN, WN, QN }, 	 //	 682	 500
{ QN, SK, KN, LO, JA, PF, QN, PF, KN, TN, JA, KN, QN, KN, AC }, 	 //	 683	 500
{ QN, QN, QN, KN, AC, PF, KN, QN, WN, AC, JA, AC, QN, QN, CR }, 	 //	 684	 500
{ QN, QN, QN, SH, AC, PF, KN, SK, TN, AC, JA, AC, JA, TN, AC }, 	 //	 685	 500
{ QN, KN, QN, AC, KN, PF, AC, QN, KN, SK, JA, SH, QN, QN, QN }, 	 //	 686	 500
{ QN, KN, QN, SK, KN, PF, AC, QN, QN, SK, JA, SH, QN, KN, QN }, 	 //	 687	 500
{ PF, AC, AC, SK, QN, JA, LO, PF, QN, QN, TN, KN, QN, KN, QN }, 	 //	 688	 500
{ PF, AC, QN, QN, QN, JA, LO, AC, KN, QN, TN, KN, KN, AC, QN }, 	 //	 689	 500
{ PF, KN, QN, WN, AC, JA, KN, AC, QN, KN, TN, KN, KN, QN, QN }, 	 //	 690	 500
{ PF, KN, AC, WN, JA, JA, ST, KN, QN, WN, TN, QN, QN, QN, TN }, 	 //	 691	 500
{ PF, ST, AC, AC, JA, JA, QN, KN, KN, JA, TN, QN, QN, QN, JA }, 	 //	 692	 500
{ PF, ST, PF, KN, TN, JA, QN, QN, SK, AC, TN, QN, QN, QN, AC }, 	 //	 693	 500
{ PF, QN, QN, KN, LO, JA, QN, PF, QN, AC, TN, QN, KN, ST, AC }, 	 //	 694	 500
{ PF, QN, QN, WN, QN, JA, QN, AC, QN, PF, TN, SK, KN, QN, JA }, 	 //	 695	 500
{ PF, JA, PF, KN, QN, JA, SH, QN, QN, QN, TN, TN, AC, ST, SH }, 	 //	 696	 500
{ PF, AC, KN, KN, TN, JA, KN, PF, WN, TN, TN, QN, QN, QN, ST }, 	 //	 697	 500
{ PF, AC, KN, QN, KN, JA, KN, PF, QN, KN, TN, QN, QN, QN, CR }, 	 //	 698	 500
{ PF, JA, QN, QN, QN, JA, TN, QN, QN, SH, TN, AC, SK, QN, JA }, 	 //	 699	 500
{ PF, JA, QN, QN, QN, JA, TN, QN, KN, QN, TN, AC, SK, AC, SH }, 	 //	 700	 500
{ PF, TN, QN, SK, CR, JA, AC, QN, QN, QN, TN, AC, SK, KN, KN }, 	 //	 701	 500
{ PF, KN, AC, KN, QN, JA, KN, KN, SK, QN, TN, KN, QN, QN, QN }, 	 //	 702	 500
{ PF, KN, QN, QN, QN, JA, KN, QN, SK, KN, TN, SK, QN, JA, AC }, 	 //	 703	 500
{ PF, KN, QN, KN, QN, JA, SK, PF, QN, QN, TN, QN, KN, ST, QN }, 	 //	 704	 500
{ JA, AC, PF, QN, KN, TN, SH, QN, QN, SK, AC, AC, QN, QN, QN }, 	 //	 705	 500
{ JA, SH, QN, QN, KN, TN, AC, QN, QN, QN, AC, AC, QN, SK, PF }, 	 //	 706	 500
{ JA, AC, QN, WN, CR, TN, AC, QN, QN, QN, AC, AC, SK, QN, KN }, 	 //	 707	 500
{ JA, AC, PF, QN, QN, TN, AC, QN, QN, QN, AC, LO, AC, SK, SH }, 	 //	 708	 500
{ JA, KN, QN, QN, QN, TN, KN, QN, KN, QN, AC, ST, QN, AC, SH }, 	 //	 709	 500
{ JA, KN, PF, KN, CR, TN, ST, QN, WN, QN, AC, QN, QN, QN, KN }, 	 //	 710	 500
{ JA, ST, QN, SK, AC, TN, QN, AC, QN, AC, AC, QN, KN, KN, AC }, 	 //	 711	 500
{ JA, QN, AC, SK, KN, TN, QN, KN, QN, QN, AC, QN, QN, KN, PF }, 	 //	 712	 500
{ JA, QN, PF, AC, QN, TN, QN, QN, KN, PF, AC, QN, QN, QN, JA }, 	 //	 713	 500
{ JA, QN, QN, WN, TN, TN, QN, SK, QN, TN, AC, QN, JA, QN, ST }, 	 //	 714	 500
{ JA, QN, QN, QN, AC, TN, QN, SK, KN, AC, AC, QN, JA, AC, AC }, 	 //	 715	 500
{ JA, QN, KN, SK, AC, TN, QN, PF, QN, KN, AC, QN, QN, KN, QN }, 	 //	 716	 500
{ JA, QN, KN, WN, KN, TN, QN, QN, QN, KN, AC, SK, PF, QN, CR }, 	 //	 717	 500
{ JA, QN, PF, QN, QN, TN, QN, QN, QN, SH, AC, SK, AC, QN, JA }, 	 //	 718	 500
{ JA, QN, QN, SK, KN, TN, SK, QN, QN, SK, AC, JA, QN, KN, QN }, 	 //	 719	 500
{ JA, SK, AC, QN, AC, TN, JA, PF, QN, KN, AC, JA, QN, QN, QN }, 	 //	 720	 500
{ JA, SH, QN, AC, AC, TN, TN, QN, KN, KN, AC, TN, QN, QN, QN }, 	 //	 721	 500
{ JA, AC, QN, WN, AC, TN, KN, PF, QN, KN, AC, QN, KN, QN, QN }, 	 //	 722	 500
{ JA, ST, KN, QN, QN, TN, JA, PF, QN, PF, AC, TN, QN, QN, JA }, 	 //	 723	 500
{ JA, ST, KN, QN, QN, TN, JA, PF, QN, KN, AC, TN, QN, SK, AC }, 	 //	 724	 500
{ JA, ST, QN, QN, QN, TN, JA, AC, KN, QN, AC, TN, KN, AC, SH }, 	 //	 725	 500
{ JA, JA, KN, WN, QN, TN, TN, QN, QN, QN, AC, AC, PF, QN, QN }, 	 //	 726	 500
{ JA, TN, QN, QN, QN, TN, AC, PF, SK, PF, AC, AC, KN, JA, JA }, 	 //	 727	 500
{ JA, KN, PF, AC, AC, TN, SK, QN, KN, AC, AC, QN, QN, QN, AC }, 	 //	 728	 500
{ JA, KN, KN, WN, AC, TN, SK, PF, QN, AC, AC, QN, QN, QN, AC }, 	 //	 729	 500
{ JA, QN, QN, QN, CR, TN, KN, QN, KN, KN, AC, AC, QN, AC, KN }, 	 //	 730	 500
{ TN, AC, PF, QN, KN, AC, AC, QN, QN, QN, AC, AC, QN, SK, PF }, 	 //	 731	 500
{ TN, LO, KN, WN, QN, AC, KN, QN, QN, QN, AC, KN, PF, QN, SH }, 	 //	 732	 500
{ TN, KN, QN, KN, AC, AC, KN, QN, WN, KN, AC, KN, QN, QN, QN }, 	 //	 733	 500
{ TN, KN, KN, WN, CR, AC, ST, QN, QN, QN, AC, QN, PF, QN, KN }, 	 //	 734	 500
{ TN, ST, QN, QN, JA, AC, QN, AC, QN, JA, AC, QN, KN, SK, WN }, 	 //	 735	 500
{ TN, ST, QN, SK, TN, AC, QN, AC, QN, AC, AC, QN, KN, KN, AC }, 	 //	 736	 500
{ TN, QN, PF, QN, KN, AC, QN, QN, QN, AC, AC, QN, AC, SK, LO }, 	 //	 737	 500
{ TN, QN, KN, QN, AC, AC, QN, PF, QN, AC, AC, SK, QN, QN, AC }, 	 //	 738	 500
{ TN, QN, QN, QN, CR, AC, SK, PF, QN, QN, AC, JA, KN, SK, KN }, 	 //	 739	 500
{ TN, JA, AC, QN, QN, AC, JA, PF, QN, QN, AC, SH, QN, SK, QN }, 	 //	 740	 500
{ TN, JA, QN, QN, QN, AC, JA, SK, KN, PF, AC, SH, JA, AC, JA }, 	 //	 741	 500
{ TN, JA, PF, KN, KN, AC, SH, QN, QN, QN, AC, TN, QN, ST, PF }, 	 //	 742	 500
{ TN, TN, AC, AC, KN, AC, TN, KN, KN, SK, AC, WN, QN, QN, QN }, 	 //	 743	 500
{ TN, AC, PF, AC, KN, AC, KN, QN, KN, QN, AC, QN, QN, QN, PF }, 	 //	 744	 500
{ TN, QN, QN, QN, TN, AC, ST, SK, QN, AC, AC, JA, JA, SK, AC }, 	 //	 745	 500
{ TN, JA, QN, QN, KN, AC, TN, QN, QN, QN, AC, AC, QN, QN, PF }, 	 //	 746	 500
{ TN, AC, QN, KN, SK, AC, PF, SK, QN, QN, AC, KN, JA, ST, QN }, 	 //	 747	 500
{ TN, KN, AC, KN, TN, AC, SK, KN, SK, TN, AC, QN, QN, QN, ST }, 	 //	 748	 500
{ TN, SK, AC, WN, CR, AC, QN, PF, QN, QN, AC, KN, QN, QN, KN }, 	 //	 749	 500
{ TN, SK, KN, KN, CR, AC, QN, PF, QN, QN, AC, KN, QN, ST, KN }, 	 //	 750	 500
{ TN, QN, PF, KN, SK, AC, KN, QN, WN, QN, AC, AC, QN, QN, QN }, 	 //	 751	 500
{ AC, AC, KN, QN, QN, AC, SH, PF, QN, PF, AC, AC, QN, QN, JA }, 	 //	 752	 500
{ AC, LO, PF, QN, KN, AC, KN, QN, QN, QN, AC, KN, QN, SK, PF }, 	 //	 753	 500
{ AC, KN, QN, QN, QN, AC, KN, SK, ST, QN, AC, KN, JA, JA, QN }, 	 //	 754	 500
{ AC, KN, AC, KN, KN, AC, ST, KN, WN, AC, AC, QN, QN, QN, LO }, 	 //	 755	 500
{ AC, KN, AC, KN, QN, AC, ST, PF, SK, KN, AC, QN, QN, QN, AC }, 	 //	 756	 500
{ AC, ST, PF, KN, TN, AC, QN, QN, WN, AC, AC, QN, QN, QN, AC }, 	 //	 757	 500
{ AC, ST, QN, QN, TN, AC, QN, AC, QN, TN, AC, QN, KN, QN, ST }, 	 //	 758	 500
{ AC, QN, QN, QN, ST, AC, SK, QN, ST, AC, AC, JA, QN, JA, KN }, 	 //	 759	 500
{ AC, TN, QN, WN, AC, AC, TN, QN, QN, KN, AC, WN, SK, QN, QN }, 	 //	 760	 500
{ AC, AC, PF, AC, AC, AC, KN, QN, KN, AC, AC, QN, QN, QN, AC }, 	 //	 761	 500
{ AC, KN, QN, WN, LO, AC, QN, PF, QN, AC, AC, ST, KN, QN, AC }, 	 //	 762	 500
{ AC, KN, QN, SK, LO, AC, QN, SK, QN, AC, AC, ST, JA, KN, AC }, 	 //	 763	 500
{ AC, KN, PF, WN, PF, AC, QN, QN, QN, JA, AC, ST, AC, QN, TN }, 	 //	 764	 500
{ AC, KN, PF, WN, QN, AC, KN, QN, QN, PF, AC, KN, QN, QN, JA }, 	 //	 765	 500
{ AC, KN, AC, AC, JA, AC, SK, KN, KN, TN, AC, QN, QN, QN, AC }, 	 //	 766	 500
{ AC, KN, QN, KN, QN, AC, SK, QN, QN, SH, AC, QN, QN, ST, JA }, 	 //	 767	 500
{ AC, SK, QN, KN, LO, AC, QN, PF, QN, AC, AC, KN, KN, ST, AC }, 	 //	 768	 500
{ AC, SK, QN, KN, AC, AC, QN, QN, WN, KN, AC, KN, QN, QN, QN }, 	 //	 769	 500
{ AC, SK, QN, QN, QN, AC, QN, QN, SK, QN, AC, KN, QN, JA, SH }, 	 //	 770	 500
{ AC, AC, QN, QN, QN, AC, SH, AC, QN, SH, SK, AC, KN, QN, JA }, 	 //	 771	 500
{ AC, AC, KN, KN, AC, AC, AC, PF, WN, KN, SK, AC, QN, QN, QN }, 	 //	 772	 500
{ AC, LO, QN, QN, QN, AC, KN, QN, SK, KN, SK, KN, QN, JA, AC }, 	 //	 773	 500
{ AC, LO, KN, KN, AC, AC, KN, PF, WN, KN, SK, KN, QN, QN, QN }, 	 //	 774	 500
{ AC, KN, QN, QN, QN, AC, KN, QN, KN, QN, SK, KN, SK, AC, SH }, 	 //	 775	 500
{ AC, KN, QN, QN, AC, AC, KN, AC, QN, KN, SK, ST, KN, SK, QN }, 	 //	 776	 500
{ AC, ST, KN, SK, LO, AC, QN, PF, QN, AC, SK, QN, QN, KN, AC }, 	 //	 777	 500
{ AC, QN, PF, AC, KN, AC, QN, QN, KN, KN, SK, QN, QN, QN, CR }, 	 //	 778	 500
{ AC, JA, QN, SK, AC, AC, SH, SK, QN, KN, SK, TN, JA, KN, QN }, 	 //	 779	 500
{ AC, KN, KN, SK, KN, AC, QN, PF, QN, AC, SK, ST, QN, KN, LO }, 	 //	 780	 500
{ AC, KN, QN, QN, QN, AC, QN, AC, SK, SH, SK, ST, KN, JA, JA }, 	 //	 781	 500
{ AC, QN, PF, AC, KN, AC, ST, QN, KN, SK, SK, JA, QN, QN, QN }, 	 //	 782	 500
{ AC, JA, QN, SK, AC, AC, TN, PF, QN, KN, SK, AC, KN, KN, QN }, 	 //	 783	 500
{ AC, AC, QN, SK, KN, AC, AC, PF, QN, SK, SK, AC, KN, KN, QN }, 	 //	 784	 500
{ AC, KN, QN, QN, QN, AC, AC, PF, ST, QN, SK, SH, KN, JA, SH }, 	 //	 785	 500
{ AC, AC, KN, QN, QN, SK, AC, QN, QN, QN, KN, AC, PF, SK, SH }, 	 //	 786	 500
{ AC, AC, QN, QN, QN, SK, AC, AC, QN, KN, KN, AC, KN, QN, AC }, 	 //	 787	 500
{ AC, AC, QN, SK, QN, SK, LO, QN, QN, PF, KN, KN, QN, KN, JA }, 	 //	 788	 500
{ AC, ST, AC, KN, TN, SK, QN, KN, QN, ST, KN, QN, QN, ST, AC }, 	 //	 789	 500
{ AC, QN, QN, WN, AC, SK, QN, SK, QN, AC, KN, QN, JA, QN, AC }, 	 //	 790	 500
{ AC, QN, QN, SK, JA, SK, QN, SK, QN, JA, KN, QN, JA, KN, WN }, 	 //	 791	 500
{ AC, QN, KN, KN, PF, SK, QN, PF, SK, JA, KN, QN, QN, QN, TN }, 	 //	 792	 500
{ AC, QN, KN, KN, JA, SK, QN, PF, SK, TN, KN, QN, QN, QN, AC }, 	 //	 793	 500
{ AC, QN, KN, KN, AC, SK, QN, PF, SK, AC, KN, QN, QN, QN, AC }, 	 //	 794	 500
{ AC, QN, PF, QN, QN, SK, QN, QN, QN, SH, KN, QN, AC, QN, JA }, 	 //	 795	 500
{ AC, QN, QN, WN, KN, SK, QN, PF, QN, KN, KN, SK, KN, QN, KN }, 	 //	 796	 500
{ AC, QN, AC, QN, CR, SK, QN, PF, QN, QN, KN, SK, QN, QN, KN }, 	 //	 797	 500
{ AC, QN, QN, SK, TN, SK, QN, AC, QN, AC, KN, SK, KN, KN, AC }, 	 //	 798	 500
{ AC, SK, QN, SK, KN, SK, JA, PF, QN, SK, KN, JA, KN, KN, QN }, 	 //	 799	 500
{ AC, TN, QN, SK, KN, SK, TN, SK, QN, SK, KN, TN, JA, KN, QN }, 	 //	 800	 500
{ AC, WN, AC, AC, QN, SK, AC, PF, KN, QN, KN, KN, QN, QN, QN }, 	 //	 801	 500
{ AC, QN, QN, QN, TN, SK, ST, PF, SK, ST, KN, JA, KN, JA, AC }, 	 //	 802	 500
{ AC, QN, KN, AC, AC, SK, ST, PF, KN, KN, KN, JA, QN, QN, QN }, 	 //	 803	 500
{ AC, ST, AC, SK, QN, SK, JA, PF, QN, QN, KN, TN, QN, KN, QN }, 	 //	 804	 500
{ AC, ST, PF, QN, QN, SK, JA, QN, QN, PF, KN, TN, QN, SK, JA }, 	 //	 805	 500
{ AC, AC, QN, QN, QN, SK, AC, QN, ST, QN, KN, AC, QN, JA, SH }, 	 //	 806	 500
{ SK, AC, PF, KN, KN, KN, AC, QN, QN, QN, KN, AC, QN, ST, PF }, 	 //	 807	 500
{ SK, AC, QN, WN, SK, KN, AC, AC, QN, QN, KN, AC, KN, QN, QN }, 	 //	 808	 500
{ SK, ST, PF, KN, AC, KN, QN, QN, QN, SK, KN, QN, AC, ST, KN }, 	 //	 809	 500
{ SK, QN, AC, KN, JA, KN, QN, KN, SK, JA, KN, QN, QN, QN, WN }, 	 //	 810	 500
{ SK, QN, PF, KN, AC, KN, QN, QN, WN, AC, KN, QN, QN, QN, CR }, 	 //	 811	 500
{ SK, QN, KN, QN, QN, KN, QN, QN, QN, PF, KN, SK, PF, SK, JA }, 	 //	 812	 500
{ SK, QN, QN, SK, AC, KN, QN, SK, QN, AC, KN, SK, JA, KN, AC }, 	 //	 813	 500
{ SK, QN, KN, KN, AC, KN, QN, PF, QN, AC, KN, SK, QN, ST, SK }, 	 //	 814	 500
{ SK, JA, QN, QN, QN, KN, JA, PF, KN, SH, KN, SH, KN, AC, JA }, 	 //	 815	 500
{ SK, TN, AC, WN, AC, KN, TN, PF, QN, KN, KN, WN, QN, QN, QN }, 	 //	 816	 500
{ SK, WN, QN, KN, QN, KN, AC, QN, SK, QN, KN, KN, QN, QN, QN }, 	 //	 817	 500
{ SK, KN, AC, QN, CR, KN, QN, PF, QN, QN, KN, ST, QN, SK, KN }, 	 //	 818	 500
{ SK, KN, AC, KN, KN, KN, QN, PF, QN, AC, KN, ST, QN, ST, LO }, 	 //	 819	 500
{ SK, QN, QN, QN, JA, KN, ST, QN, ST, TN, KN, JA, QN, JA, AC }, 	 //	 820	 500
{ SK, AC, AC, SK, QN, KN, AC, KN, QN, QN, KN, AC, QN, KN, SH }, 	 //	 821	 500
{ SK, AC, QN, QN, KN, KN, PF, QN, QN, SK, KN, KN, SK, QN, QN }, 	 //	 822	 500
{ SK, QN, QN, QN, KN, KN, KN, PF, SK, KN, KN, AC, KN, JA, KN }, 	 //	 823	 500
{ KN, KN, AC, KN, QN, KN, KN, PF, QN, KN, KN, KN, QN, ST, AC }, 	 //	 824	 500
{ KN, KN, AC, WN, CR, KN, ST, PF, QN, KN, KN, QN, QN, QN, KN }, 	 //	 825	 500
{ KN, ST, AC, KN, JA, KN, QN, PF, SK, WN, KN, QN, QN, QN, TN }, 	 //	 826	 500
{ KN, ST, KN, SK, KN, KN, QN, PF, QN, KN, KN, QN, QN, KN, KN }, 	 //	 827	 500
{ KN, QN, KN, WN, JA, KN, QN, QN, QN, JA, KN, QN, PF, QN, WN }, 	 //	 828	 500
{ KN, QN, PF, KN, CR, KN, SK, QN, QN, QN, KN, JA, QN, ST, KN }, 	 //	 829	 500
{ KN, QN, QN, QN, TN, KN, SK, QN, QN, TN, KN, JA, QN, QN, TN }, 	 //	 830	 500
{ KN, JA, QN, WN, SK, KN, JA, SK, QN, QN, KN, SH, JA, QN, QN }, 	 //	 831	 500
{ KN, JA, PF, SK, CR, KN, SH, QN, QN, QN, KN, TN, QN, KN, KN }, 	 //	 832	 500
{ KN, SH, TN, TN, WN, KN, TN, TN, TN, TN, KN, TN, TN, WN, TN }, 	 //	 833	 500
{ KN, SH, PF, SK, QN, KN, TN, QN, QN, QN, KN, TN, AC, KN, QN }, 	 //	 834	 500
{ KN, TN, QN, QN, AC, KN, TN, SK, QN, KN, KN, TN, JA, SK, QN }, 	 //	 835	 500
{ KN, TN, AC, WN, QN, KN, WN, KN, QN, KN, KN, AC, QN, QN, AC }, 	 //	 836	 500
{ KN, AC, QN, QN, QN, KN, KN, SK, KN, QN, KN, QN, JA, AC, SH }, 	 //	 837	 500
{ KN, KN, QN, WN, KN, KN, QN, PF, QN, KN, KN, ST, KN, QN, CR }, 	 //	 838	 500
{ KN, KN, QN, QN, AC, KN, QN, AC, QN, SK, KN, ST, KN, QN, KN }, 	 //	 839	 500
{ KN, QN, QN, QN, AC, KN, ST, AC, QN, AC, KN, JA, KN, QN, CR }, 	 //	 840	 500
{ KN, AC, QN, QN, QN, KN, AC, PF, KN, SH, KN, AC, KN, AC, JA }, 	 //	 841	 500
{ KN, KN, AC, WN, QN, KN, KN, PF, QN, QN, KN, SK, QN, QN, SH }, 	 //	 842	 500
{ KN, AC, QN, QN, QN, KN, AC, AC, ST, KN, WN, LO, KN, JA, AC }, 	 //	 843	 500
{ KN, AC, QN, QN, QN, KN, LO, QN, KN, KN, WN, KN, QN, AC, AC }, 	 //	 844	 500
{ KN, KN, PF, SK, KN, KN, KN, QN, QN, QN, WN, KN, QN, KN, PF }, 	 //	 845	 500
{ KN, ST, AC, SK, KN, KN, QN, KN, QN, SK, WN, QN, QN, KN, QN }, 	 //	 846	 500
{ KN, ST, QN, AC, TN, KN, QN, QN, KN, AC, WN, QN, QN, QN, AC }, 	 //	 847	 500
{ KN, QN, QN, SK, KN, KN, QN, SK, QN, AC, WN, QN, JA, KN, LO }, 	 //	 848	 500
{ KN, QN, QN, QN, TN, KN, QN, AC, SK, ST, WN, SK, KN, JA, AC }, 	 //	 849	 500
{ KN, TN, QN, QN, QN, KN, TN, QN, QN, KN, WN, TN, SK, QN, AC }, 	 //	 850	 500
{ KN, QN, QN, QN, LO, KN, ST, PF, QN, AC, WN, JA, KN, QN, AC }, 	 //	 851	 500
{ KN, QN, PF, QN, QN, KN, ST, QN, QN, QN, WN, JA, AC, SK, SH }, 	 //	 852	 500
{ KN, ST, QN, WN, QN, KN, JA, SK, QN, QN, WN, TN, JA, QN, QN }, 	 //	 853	 500
{ KN, AC, AC, KN, QN, KN, AC, PF, QN, PF, WN, AC, QN, ST, JA }, 	 //	 854	 500
{ KN, AC, QN, QN, QN, KN, AC, QN, ST, QN, WN, PF, SK, JA, SH }, 	 //	 855	 500
{ KN, KN, PF, QN, TN, KN, SK, QN, QN, AC, WN, QN, QN, QN, AC }, 	 //	 856	 500
{ KN, SK, PF, AC, KN, KN, QN, QN, KN, SK, WN, KN, QN, QN, QN }, 	 //	 857	 500
{ KN, QN, QN, QN, KN, KN, KN, QN, ST, KN, WN, AC, SK, JA, KN }, 	 //	 858	 500
{ KN, LO, AC, KN, QN, WN, KN, PF, QN, SH, QN, KN, QN, ST, JA }, 	 //	 859	 500
{ KN, LO, PF, WN, AC, WN, KN, QN, QN, KN, QN, KN, QN, QN, QN }, 	 //	 860	 500
{ KN, KN, AC, AC, PF, WN, ST, PF, LO, JA, QN, QN, QN, KN, TN }, 	 //	 861	 500
{ KN, KN, PF, AC, SK, WN, ST, QN, AC, QN, QN, QN, QN, AC, QN }, 	 //	 862	 500
{ KN, KN, QN, LO, QN, WN, ST, QN, KN, KN, QN, QN, QN, KN, AC }, 	 //	 863	 500
{ KN, KN, QN, QN, SK, WN, ST, QN, ST, KN, QN, QN, QN, JA, KN }, 	 //	 864	 500
{ KN, ST, AC, SH, ST, WN, QN, KN, TN, AC, QN, QN, QN, TN, KN }, 	 //	 865	 500
{ KN, ST, AC, QN, TN, WN, QN, PF, SK, AC, QN, QN, QN, JA, AC }, 	 //	 866	 500
{ KN, ST, PF, JA, CR, WN, QN, QN, TN, QN, QN, QN, QN, AC, KN }, 	 //	 867	 500
{ KN, ST, QN, AC, JA, WN, QN, QN, AC, JA, QN, QN, SK, AC, WN }, 	 //	 868	 500
{ KN, ST, KN, QN, KN, WN, QN, PF, SK, KN, QN, QN, QN, JA, CR }, 	 //	 869	 500
{ KN, ST, QN, TN, KN, WN, QN, AC, TN, KN, QN, QN, KN, WN, KN }, 	 //	 870	 500
{ KN, QN, AC, KN, QN, WN, QN, KN, KN, QN, QN, QN, QN, KN, SH }, 	 //	 871	 500
{ KN, QN, QN, AC, ST, WN, QN, PF, PF, AC, QN, QN, KN, AC, KN }, 	 //	 872	 500
{ KN, QN, PF, KN, AC, WN, QN, QN, KN, AC, QN, QN, QN, WN, AC }, 	 //	 873	 500
{ KN, QN, PF, JA, KN, WN, QN, QN, JA, KN, QN, QN, QN, SH, CR }, 	 //	 874	 500
{ KN, QN, QN, KN, KN, WN, QN, QN, KN, KN, QN, QN, SK, KN, CR }, 	 //	 875	 500
{ KN, QN, QN, JA, KN, WN, QN, QN, SH, QN, QN, QN, SK, TN, PF }, 	 //	 876	 500
{ KN, QN, QN, PF, TN, WN, QN, QN, KN, TN, QN, QN, SK, KN, TN }, 	 //	 877	 500
{ KN, QN, QN, JA, AC, WN, QN, SK, JA, SK, QN, QN, JA, SH, KN }, 	 //	 878	 500
{ KN, QN, KN, AC, KN, WN, QN, PF, LO, KN, QN, QN, QN, KN, KN }, 	 //	 879	 500
{ KN, QN, KN, QN, QN, WN, QN, PF, ST, QN, QN, QN, QN, JA, QN }, 	 //	 880	 500
{ KN, QN, QN, JA, KN, WN, QN, AC, JA, KN, QN, QN, KN, SH, SK }, 	 //	 881	 500
{ KN, QN, QN, TN, KN, WN, QN, AC, TN, QN, QN, QN, KN, TN, PF }, 	 //	 882	 500
{ KN, QN, QN, TN, QN, WN, QN, AC, TN, QN, QN, QN, KN, WN, SH }, 	 //	 883	 500
{ KN, QN, QN, JA, QN, WN, QN, PF, SH, KN, QN, SK, KN, TN, AC }, 	 //	 884	 500
{ KN, QN, QN, SH, QN, WN, QN, QN, TN, QN, QN, SK, QN, TN, QN }, 	 //	 885	 500
{ KN, JA, QN, QN, QN, WN, SH, AC, KN, QN, QN, TN, KN, AC, QN }, 	 //	 886	 500
{ KN, SH, QN, WN, QN, WN, TN, SK, QN, QN, QN, TN, JA, QN, QN }, 	 //	 887	 500
{ KN, TN, QN, QN, QN, WN, TN, PF, KN, SH, QN, TN, KN, AC, JA }, 	 //	 888	 500
{ KN, TN, QN, QN, AC, WN, TN, PF, QN, KN, QN, WN, KN, QN, QN }, 	 //	 889	 500
{ KN, WN, QN, QN, QN, WN, AC, PF, SK, PF, QN, KN, KN, JA, JA }, 	 //	 890	 500
{ KN, WN, PF, WN, QN, WN, AC, QN, QN, SH, QN, KN, QN, QN, JA }, 	 //	 891	 500
{ KN, WN, PF, WN, SK, WN, AC, QN, QN, QN, QN, KN, AC, QN, QN }, 	 //	 892	 500
{ KN, AC, AC, KN, AC, WN, KN, PF, AC, SK, QN, QN, QN, PF, KN }, 	 //	 893	 500
{ KN, AC, KN, KN, SH, WN, KN, PF, AC, JA, QN, QN, QN, PF, JA }, 	 //	 894	 500
{ KN, KN, QN, QN, JA, WN, QN, PF, SK, WN, QN, ST, KN, JA, TN }, 	 //	 895	 500
{ KN, KN, QN, QN, CR, WN, QN, PF, SK, QN, QN, ST, KN, JA, KN }, 	 //	 896	 500
{ KN, KN, QN, JA, AC, WN, QN, PF, SH, AC, QN, ST, KN, TN, AC }, 	 //	 897	 500
{ KN, KN, QN, JA, CR, WN, QN, PF, SH, QN, QN, ST, KN, TN, KN }, 	 //	 898	 500
{ KN, KN, QN, ST, KN, WN, QN, SK, JA, SK, QN, ST, JA, TN, QN }, 	 //	 899	 500
{ KN, KN, QN, ST, PF, WN, QN, AC, JA, JA, QN, ST, KN, TN, TN }, 	 //	 900	 500
{ KN, QN, QN, QN, AC, WN, ST, PF, KN, AC, QN, JA, KN, AC, AC }, 	 //	 901	 500
{ KN, QN, PF, WN, KN, WN, ST, QN, QN, QN, QN, JA, AC, QN, PF }, 	 //	 902	 500
{ KN, TN, PF, KN, KN, WN, AC, QN, QN, QN, QN, AC, QN, ST, PF }, 	 //	 903	 500
{ KN, KN, AC, TN, AC, WN, SK, KN, TN, SK, QN, QN, QN, WN, KN }, 	 //	 904	 500
{ KN, KN, AC, SK, TN, WN, SK, PF, JA, ST, QN, QN, QN, JA, AC }, 	 //	 905	 500
{ KN, KN, AC, TN, AC, WN, SK, PF, TN, KN, QN, QN, QN, TN, QN }, 	 //	 906	 500
{ KN, KN, QN, KN, AC, WN, SK, QN, QN, AC, QN, QN, QN, ST, AC }, 	 //	 907	 500
{ KN, SK, KN, SK, AC, WN, QN, QN, QN, KN, QN, KN, PF, KN, QN }, 	 //	 908	 500
{ KN, SK, QN, AC, KN, WN, QN, QN, PF, QN, QN, KN, SK, AC, PF }, 	 //	 909	 500
{ KN, SK, QN, SH, JA, WN, QN, SK, TN, TN, QN, KN, JA, TN, AC }, 	 //	 910	 500
{ KN, SK, QN, AC, CR, WN, QN, AC, AC, QN, QN, KN, KN, AC, KN }, 	 //	 911	 500
{ KN, KN, AC, QN, QN, WN, AC, KN, QN, PF, QN, SH, QN, QN, JA }, 	 //	 912	 500
{ WN, SH, AC, KN, QN, QN, AC, KN, QN, SH, KN, AC, QN, ST, JA }, 	 //	 913	 500
{ WN, ST, AC, KN, JA, QN, QN, PF, SK, JA, KN, QN, QN, QN, JA }, 	 //	 914	 500
{ WN, ST, AC, KN, JA, QN, QN, PF, SK, TN, KN, QN, QN, QN, AC }, 	 //	 915	 500
{ WN, ST, PF, PF, TN, QN, QN, QN, KN, AC, KN, QN, QN, KN, AC }, 	 //	 916	 500
{ WN, ST, QN, WN, AC, QN, QN, SK, QN, AC, KN, QN, JA, QN, SK }, 	 //	 917	 500
{ WN, ST, QN, SK, TN, QN, QN, SK, QN, ST, KN, QN, JA, KN, AC }, 	 //	 918	 500
{ WN, QN, KN, PF, QN, QN, QN, QN, AC, QN, KN, QN, PF, AC, QN }, 	 //	 919	 500
{ WN, QN, KN, QN, TN, QN, QN, QN, SK, TN, KN, QN, PF, JA, TN }, 	 //	 920	 500
{ WN, QN, QN, QN, AC, QN, QN, PF, KN, SK, KN, QN, KN, AC, KN }, 	 //	 921	 500
{ WN, QN, QN, KN, ST, QN, QN, QN, KN, AC, KN, QN, QN, KN, KN }, 	 //	 922	 500
{ WN, QN, QN, TN, CR, QN, QN, QN, WN, QN, KN, QN, QN, AC, KN }, 	 //	 923	 500
{ WN, QN, PF, JA, KN, QN, QN, QN, TN, QN, KN, QN, AC, AC, PF }, 	 //	 924	 500
{ WN, QN, QN, QN, KN, QN, QN, AC, ST, AC, KN, QN, KN, JA, LO }, 	 //	 925	 500
{ WN, QN, AC, QN, JA, QN, QN, KN, QN, JA, KN, SK, QN, QN, JA }, 	 //	 926	 500
{ WN, QN, PF, ST, KN, QN, QN, QN, JA, KN, KN, SK, QN, TN, KN }, 	 //	 927	 500
{ WN, QN, QN, JA, KN, QN, QN, QN, SH, KN, KN, SK, QN, TN, KN }, 	 //	 928	 500
{ WN, QN, QN, KN, AC, QN, QN, QN, KN, AC, KN, SK, QN, SK, AC }, 	 //	 929	 500
{ WN, QN, PF, SK, AC, QN, QN, QN, JA, AC, KN, SK, AC, JA, AC }, 	 //	 930	 500
{ WN, QN, PF, QN, CR, QN, QN, QN, KN, KN, KN, SK, AC, AC, KN }, 	 //	 931	 500
{ WN, QN, PF, KN, JA, QN, QN, QN, AC, JA, KN, SK, AC, PF, JA }, 	 //	 932	 500
{ WN, QN, QN, QN, CR, QN, SK, PF, ST, KN, KN, JA, KN, JA, KN }, 	 //	 933	 500
{ WN, JA, PF, WN, KN, QN, JA, QN, QN, QN, KN, SH, AC, QN, PF }, 	 //	 934	 500
{ WN, TN, QN, QN, KN, QN, TN, QN, QN, QN, KN, TN, QN, SK, PF }, 	 //	 935	 500
{ WN, TN, QN, QN, QN, QN, TN, SK, QN, QN, KN, WN, JA, QN, SH }, 	 //	 936	 500
{ WN, AC, QN, QN, QN, QN, KN, QN, KN, PF, KN, QN, QN, AC, JA }, 	 //	 937	 500
{ WN, KN, KN, AC, TN, QN, QN, QN, AC, AC, KN, ST, PF, LO, AC }, 	 //	 938	 500
{ WN, KN, KN, QN, AC, QN, QN, QN, KN, AC, KN, ST, PF, AC, AC }, 	 //	 939	 500
{ WN, KN, QN, AC, TN, QN, QN, QN, KN, TN, KN, ST, SK, QN, TN }, 	 //	 940	 500
{ WN, KN, PF, AC, KN, QN, QN, QN, AC, KN, KN, ST, AC, AC, SK }, 	 //	 941	 500
{ WN, KN, QN, QN, KN, QN, QN, AC, QN, KN, KN, ST, KN, SK, CR }, 	 //	 942	 500
{ WN, QN, AC, SK, QN, QN, ST, KN, QN, PF, KN, JA, QN, KN, JA }, 	 //	 943	 500
{ WN, QN, QN, QN, KN, QN, ST, SK, KN, KN, KN, JA, JA, AC, KN }, 	 //	 944	 500
{ WN, QN, QN, QN, TN, QN, ST, AC, QN, TN, KN, JA, KN, QN, ST }, 	 //	 945	 500
{ WN, ST, QN, SK, AC, QN, JA, AC, QN, KN, KN, TN, KN, KN, QN }, 	 //	 946	 500
{ WN, AC, PF, KN, SK, QN, AC, QN, QN, QN, KN, AC, QN, ST, QN }, 	 //	 947	 500
{ WN, AC, PF, KN, AC, QN, AC, QN, SK, KN, KN, PF, QN, QN, QN }, 	 //	 948	 500
{ WN, SK, PF, TN, QN, QN, QN, QN, WN, QN, KN, KN, QN, AC, QN }, 	 //	 949	 500
{ WN, SK, PF, AC, AC, QN, QN, QN, PF, AC, KN, KN, QN, KN, CR }, 	 //	 950	 500
{ WN, SK, QN, TN, JA, QN, QN, QN, TN, JA, KN, KN, QN, WN, WN }, 	 //	 951	 500
{ WN, QN, QN, QN, KN, QN, KN, QN, KN, AC, KN, AC, QN, AC, LO }, 	 //	 952	 500
{ QN, AC, QN, QN, QN, KN, SH, PF, QN, KN, AC, AC, KN, QN, AC }, 	 //	 953	 500
{ QN, SH, QN, QN, AC, KN, AC, SK, QN, KN, AC, AC, JA, QN, QN }, 	 //	 954	 500
{ QN, LO, QN, QN, CR, KN, KN, QN, QN, QN, AC, KN, SK, QN, KN }, 	 //	 955	 500
{ QN, KN, KN, AC, KN, KN, ST, PF, KN, AC, AC, QN, QN, QN, LO }, 	 //	 956	 500
{ QN, ST, AC, TN, CR, KN, QN, KN, WN, QN, AC, QN, QN, AC, KN }, 	 //	 957	 500
{ QN, ST, QN, QN, KN, KN, QN, PF, QN, KN, AC, QN, KN, SK, KN }, 	 //	 958	 500
{ QN, ST, AC, JA, AC, KN, QN, PF, TN, KN, AC, QN, QN, AC, QN }, 	 //	 959	 500
{ QN, ST, PF, KN, KN, KN, QN, QN, KN, KN, AC, QN, QN, KN, SK }, 	 //	 960	 500
{ QN, ST, PF, TN, AC, KN, QN, QN, TN, AC, AC, QN, QN, TN, AC }, 	 //	 961	 500
{ QN, ST, QN, JA, KN, KN, QN, QN, TN, KN, AC, QN, QN, AC, KN }, 	 //	 962	 500
{ QN, QN, QN, AC, KN, KN, QN, PF, LO, SK, AC, QN, KN, KN, QN }, 	 //	 963	 500
{ QN, QN, AC, PF, WN, KN, QN, PF, KN, TN, AC, QN, QN, KN, TN }, 	 //	 964	 500
{ QN, QN, PF, QN, PF, KN, QN, QN, SK, JA, AC, QN, QN, JA, TN }, 	 //	 965	 500
{ QN, QN, QN, PF, QN, KN, QN, QN, AC, SH, AC, QN, SK, AC, JA }, 	 //	 966	 500
{ QN, QN, KN, AC, CR, KN, QN, PF, AC, QN, AC, QN, QN, LO, KN }, 	 //	 967	 500
{ QN, QN, KN, SK, CR, KN, QN, PF, JA, KN, AC, QN, QN, JA, KN }, 	 //	 968	 500
{ QN, QN, QN, SH, QN, KN, QN, PF, TN, KN, AC, SK, KN, TN, AC }, 	 //	 969	 500
{ QN, QN, AC, LO, KN, KN, QN, PF, KN, KN, AC, SK, QN, KN, SK }, 	 //	 970	 500
{ QN, QN, PF, JA, QN, KN, QN, QN, JA, QN, AC, SK, QN, JA, SH }, 	 //	 971	 500
{ QN, QN, KN, TN, KN, KN, QN, PF, TN, KN, AC, SK, QN, WN, SK }, 	 //	 972	 500
{ QN, QN, KN, AC, KN, KN, QN, PF, PF, SK, AC, SK, QN, KN, QN }, 	 //	 973	 500
{ QN, QN, QN, ST, KN, KN, QN, AC, JA, KN, AC, SK, KN, TN, KN }, 	 //	 974	 500
{ QN, QN, QN, AC, KN, KN, SK, PF, PF, KN, AC, JA, KN, AC, SK }, 	 //	 975	 500
{ QN, QN, QN, SH, TN, KN, SK, PF, TN, AC, AC, JA, KN, TN, AC }, 	 //	 976	 500
{ QN, QN, QN, TN, JA, KN, SK, PF, TN, JA, AC, JA, KN, TN, WN }, 	 //	 977	 500
{ QN, QN, QN, TN, KN, KN, SK, AC, TN, KN, AC, JA, KN, WN, SK }, 	 //	 978	 500
{ QN, JA, QN, SK, CR, KN, JA, QN, QN, QN, AC, SH, SK, KN, KN }, 	 //	 979	 500
{ QN, TN, QN, KN, AC, KN, WN, QN, SK, KN, AC, AC, QN, QN, QN }, 	 //	 980	 500
{ QN, AC, QN, WN, SK, KN, KN, PF, QN, QN, AC, QN, KN, QN, QN }, 	 //	 981	 500
{ QN, KN, AC, TN, AC, KN, QN, KN, WN, AC, AC, ST, QN, AC, AC }, 	 //	 982	 500
{ QN, KN, QN, SK, LO, KN, QN, PF, QN, AC, AC, ST, KN, KN, AC }, 	 //	 983	 500
{ QN, KN, AC, JA, AC, KN, QN, PF, JA, AC, AC, ST, QN, SH, AC }, 	 //	 984	 500
{ QN, KN, PF, TN, QN, KN, QN, QN, WN, PF, AC, ST, QN, AC, JA }, 	 //	 985	 500
{ QN, QN, QN, TN, TN, KN, ST, QN, TN, TN, AC, JA, QN, TN, ST }, 	 //	 986	 500
{ QN, QN, QN, TN, QN, KN, ST, QN, WN, QN, AC, JA, SK, AC, SH }, 	 //	 987	 500
{ QN, QN, QN, JA, QN, KN, ST, SK, JA, QN, AC, JA, JA, SH, SH }, 	 //	 988	 500
{ QN, QN, QN, JA, KN, KN, ST, SK, TN, KN, AC, JA, JA, AC, CR }, 	 //	 989	 500
{ QN, QN, QN, ST, AC, KN, ST, AC, JA, KN, AC, JA, KN, TN, QN }, 	 //	 990	 500
{ QN, TN, KN, QN, CR, KN, AC, QN, QN, QN, AC, AC, PF, SK, KN }, 	 //	 991	 500
{ QN, AC, PF, WN, KN, KN, PF, QN, QN, SK, AC, KN, QN, QN, QN }, 	 //	 992	 500
{ QN, SK, AC, JA, AC, KN, QN, KN, SH, AC, AC, KN, QN, TN, CR }, 	 //	 993	 500
{ QN, SK, AC, PF, SH, KN, QN, PF, AC, JA, AC, KN, QN, AC, JA }, 	 //	 994	 500
{ QN, SK, AC, JA, LO, KN, QN, PF, JA, AC, AC, KN, QN, JA, AC }, 	 //	 995	 500
{ QN, SK, AC, PF, JA, KN, QN, PF, KN, JA, AC, KN, QN, KN, JA }, 	 //	 996	 500
{ QN, SK, PF, WN, AC, KN, QN, QN, AC, LO, AC, KN, QN, KN, AC }, 	 //	 997	 500
{ QN, SK, QN, SK, ST, KN, QN, QN, JA, AC, AC, KN, QN, JA, KN }, 	 //	 998	 500
{ QN, SK, KN, TN, AC, KN, QN, PF, AC, SK, AC, KN, QN, AC, KN }, 	 //	 999	 500
{ QN, SK, KN, AC, LO, KN, QN, PF, PF, AC, AC, KN, QN, KN, AC }};	 //	 1000	 500
