unsigned char L5_Outcome_0160[1000][15]={	 //	 0	 160
{ AC, QN, SK, SH, TN, LO, SK, JA, TN, AC, AC, JA, TN, TN, AC }, 	 //	 1	 160
{ AC, QN, SK, TN, TN, LO, SK, JA, TN, AC, AC, JA, TN, TN, AC }, 	 //	 2	 160
{ AC, SK, SK, SH, JA, LO, JA, JA, TN, WN, AC, JA, TN, TN, TN }, 	 //	 3	 160
{ AC, SK, SK, SH, TN, LO, JA, JA, TN, TN, AC, JA, TN, TN, ST }, 	 //	 4	 160
{ AC, SK, SK, SH, TN, LO, JA, JA, TN, AC, AC, JA, TN, TN, AC }, 	 //	 5	 160
{ AC, SK, SK, TN, TN, LO, JA, JA, TN, TN, AC, JA, TN, WN, ST }, 	 //	 6	 160
{ AC, SK, SK, JA, TN, LO, JA, JA, TN, TN, AC, JA, TN, AC, TN }, 	 //	 7	 160
{ AC, KN, SK, SH, JA, LO, SK, JA, TN, WN, AC, QN, TN, TN, TN }, 	 //	 8	 160
{ AC, KN, SK, TN, TN, LO, SK, JA, TN, TN, AC, QN, TN, TN, ST }, 	 //	 9	 160
{ AC, SK, SK, JA, JA, LO, QN, JA, SH, WN, AC, KN, TN, TN, TN }, 	 //	 10	 160
{ AC, SK, SK, SH, TN, LO, QN, JA, TN, TN, AC, KN, TN, TN, ST }, 	 //	 11	 160
{ AC, SK, SK, TN, JA, LO, QN, JA, TN, WN, AC, KN, TN, TN, TN }, 	 //	 12	 160
{ AC, SK, SK, TN, TN, LO, QN, JA, TN, AC, AC, KN, TN, WN, AC }, 	 //	 13	 160
{ AC, SK, SK, JA, TN, LO, QN, JA, TN, TN, AC, KN, TN, AC, ST }, 	 //	 14	 160
{ LO, QN, SK, SH, TN, AC, SK, JA, TN, TN, AC, JA, TN, TN, ST }, 	 //	 15	 160
{ LO, QN, SK, SH, TN, AC, SK, JA, TN, ST, AC, JA, TN, TN, AC }, 	 //	 16	 160
{ LO, SK, SK, SH, WN, AC, JA, JA, TN, TN, AC, JA, TN, TN, TN }, 	 //	 17	 160
{ LO, SK, SK, SH, TN, AC, JA, JA, TN, ST, AC, JA, TN, TN, AC }, 	 //	 18	 160
{ LO, SK, SK, TN, TN, AC, JA, JA, TN, TN, AC, JA, TN, WN, ST }, 	 //	 19	 160
{ LO, SK, SK, JA, TN, AC, JA, JA, TN, TN, AC, JA, TN, AC, ST }, 	 //	 20	 160
{ LO, KN, SK, SH, TN, AC, SK, JA, TN, TN, AC, QN, TN, TN, ST }, 	 //	 21	 160
{ LO, KN, SK, TN, JA, AC, SK, JA, TN, WN, AC, QN, TN, TN, TN }, 	 //	 22	 160
{ LO, KN, SK, TN, TN, AC, SK, JA, TN, ST, AC, QN, TN, WN, AC }, 	 //	 23	 160
{ LO, SK, SK, SH, WN, AC, QN, JA, TN, TN, AC, KN, TN, TN, TN }, 	 //	 24	 160
{ AC, QN, SK, JA, TN, AC, SK, JA, SH, TN, AC, JA, TN, TN, TN }, 	 //	 25	 160
{ AC, SK, SK, SH, TN, AC, JA, JA, TN, TN, AC, JA, TN, TN, ST }, 	 //	 26	 160
{ AC, SK, SK, SH, PF, AC, JA, JA, TN, JA, AC, JA, TN, TN, TN }, 	 //	 27	 160
{ AC, SK, SK, TN, WN, AC, JA, JA, TN, TN, AC, JA, TN, TN, TN }, 	 //	 28	 160
{ AC, KN, SK, JA, WN, AC, SK, JA, SH, TN, AC, QN, TN, TN, TN }, 	 //	 29	 160
{ AC, KN, SK, SH, JA, AC, SK, JA, TN, WN, AC, QN, TN, TN, TN }, 	 //	 30	 160
{ AC, SK, SK, JA, TN, AC, QN, JA, SH, TN, AC, KN, TN, TN, TN }, 	 //	 31	 160
{ AC, SK, SK, SH, PF, AC, QN, JA, TN, JA, AC, KN, TN, TN, TN }, 	 //	 32	 160
{ AC, QN, SK, TN, TN, AC, SK, JA, TN, ST, ST, JA, TN, WN, AC }, 	 //	 33	 160
{ AC, QN, SK, ST, WN, AC, SK, JA, JA, TN, ST, JA, TN, TN, TN }, 	 //	 34	 160
{ AC, SK, SK, JA, TN, AC, JA, JA, TN, TN, ST, JA, TN, AC, ST }, 	 //	 35	 160
{ AC, KN, SK, SH, WN, AC, SK, JA, TN, TN, ST, QN, TN, TN, TN }, 	 //	 36	 160
{ AC, SK, SK, JA, WN, AC, QN, JA, SH, TN, ST, KN, TN, TN, TN }, 	 //	 37	 160
{ AC, QN, SK, TN, JA, ST, SK, JA, TN, WN, KN, JA, TN, TN, TN }, 	 //	 38	 160
{ AC, QN, SK, JA, TN, ST, SK, JA, TN, ST, KN, JA, TN, AC, AC }, 	 //	 39	 160
{ AC, SK, SK, TN, TN, ST, JA, JA, TN, AC, KN, JA, TN, WN, AC }, 	 //	 40	 160
{ AC, SK, SK, TN, JA, ST, QN, JA, TN, WN, KN, KN, TN, TN, TN }, 	 //	 41	 160
{ AC, SK, SK, TN, TN, ST, QN, JA, TN, ST, KN, KN, TN, WN, AC }, 	 //	 42	 160
{ ST, QN, SK, SH, TN, KN, SK, JA, TN, AC, KN, JA, TN, TN, AC }, 	 //	 43	 160
{ ST, SK, SK, JA, PF, KN, JA, JA, SH, JA, KN, JA, TN, TN, TN }, 	 //	 44	 160
{ ST, KN, SK, SH, PF, KN, SK, JA, TN, JA, KN, QN, TN, TN, TN }, 	 //	 45	 160
{ ST, SK, SK, JA, PF, KN, QN, JA, SH, JA, KN, KN, TN, TN, TN }, 	 //	 46	 160
{ KN, QN, SK, TN, JA, KN, SK, JA, TN, WN, KN, JA, TN, TN, TN }, 	 //	 47	 160
{ KN, QN, SK, TN, TN, KN, SK, JA, TN, AC, KN, JA, TN, WN, AC }, 	 //	 48	 160
{ KN, QN, SK, ST, WN, KN, SK, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 49	 160
{ KN, KN, SK, SH, TN, KN, SK, JA, TN, TN, KN, QN, TN, TN, ST }, 	 //	 50	 160
{ KN, KN, SK, TN, WN, KN, SK, JA, TN, TN, KN, QN, TN, TN, TN }, 	 //	 51	 160
{ KN, SK, SK, TN, TN, KN, QN, JA, TN, TN, KN, KN, TN, TN, ST }, 	 //	 52	 160
{ KN, SK, SK, TN, TN, KN, QN, JA, TN, TN, KN, KN, TN, WN, ST }, 	 //	 53	 160
{ KN, QN, WN, JA, JA, KN, QN, TN, SH, WN, SK, SK, TN, TN, TN }, 	 //	 54	 160
{ KN, QN, WN, SH, PF, KN, QN, TN, TN, JA, SK, SK, TN, TN, TN }, 	 //	 55	 160
{ KN, QN, WN, TN, PF, KN, QN, TN, TN, JA, SK, SK, TN, TN, TN }, 	 //	 56	 160
{ KN, QN, WN, TN, TN, KN, QN, TN, TN, ST, SK, SK, TN, WN, AC }, 	 //	 57	 160
{ KN, QN, TN, SH, TN, KN, QN, TN, TN, ST, SK, SK, TN, TN, AC }, 	 //	 58	 160
{ KN, QN, TN, TN, JA, KN, QN, TN, TN, TN, SK, SK, TN, TN, AC }, 	 //	 59	 160
{ KN, QN, TN, ST, JA, KN, QN, TN, JA, WN, SK, SK, TN, TN, TN }, 	 //	 60	 160
{ KN, QN, TN, TN, JA, KN, QN, TN, TN, WN, SK, SK, LO, TN, TN }, 	 //	 61	 160
{ KN, QN, TN, TN, TN, KN, QN, TN, AC, ST, SK, SK, LO, AC, AC }, 	 //	 62	 160
{ KN, QN, TN, TN, TN, KN, QN, LO, TN, TN, SK, SK, JA, TN, ST }, 	 //	 63	 160
{ KN, QN, TN, TN, JA, KN, QN, LO, TN, WN, SK, SK, JA, WN, TN }, 	 //	 64	 160
{ KN, QN, TN, TN, TN, KN, QN, LO, TN, ST, SK, SK, JA, WN, AC }, 	 //	 65	 160
{ KN, QN, TN, TN, TN, KN, QN, LO, AC, ST, SK, SK, JA, AC, AC }, 	 //	 66	 160
{ KN, QN, SK, SH, TN, KN, QN, JA, TN, ST, SK, SK, TN, TN, AC }, 	 //	 67	 160
{ KN, QN, SK, TN, TN, KN, QN, JA, TN, TN, SK, SK, TN, WN, ST }, 	 //	 68	 160
{ KN, QN, SK, TN, TN, KN, QN, JA, TN, ST, SK, SK, TN, WN, AC }, 	 //	 69	 160
{ KN, QN, SK, ST, JA, KN, QN, JA, JA, WN, SK, SK, TN, TN, TN }, 	 //	 70	 160
{ KN, QN, SK, JA, TN, KN, QN, JA, TN, AC, SK, SK, TN, AC, AC }, 	 //	 71	 160
{ KN, QN, JA, TN, WN, KN, QN, TN, TN, TN, SK, SK, AC, TN, TN }, 	 //	 72	 160
{ KN, QN, JA, TN, TN, KN, QN, TN, TN, TN, SK, SK, AC, WN, ST }, 	 //	 73	 160
{ KN, QN, TN, TN, TN, KN, QN, AC, TN, AC, SK, SK, AC, WN, AC }, 	 //	 74	 160
{ KN, QN, KN, ST, JA, KN, SK, WN, JA, WN, SK, JA, TN, TN, TN }, 	 //	 75	 160
{ KN, QN, WN, TN, JA, KN, SK, TN, TN, TN, SK, JA, TN, TN, AC }, 	 //	 76	 160
{ KN, QN, WN, TN, WN, KN, SK, TN, TN, TN, SK, JA, TN, WN, TN }, 	 //	 77	 160
{ KN, QN, TN, TN, JA, KN, SK, TN, TN, TN, SK, JA, TN, WN, AC }, 	 //	 78	 160
{ KN, QN, TN, JA, TN, KN, SK, TN, TN, AC, SK, JA, TN, AC, AC }, 	 //	 79	 160
{ KN, QN, TN, TN, JA, KN, SK, TN, TN, TN, SK, JA, LO, TN, AC }, 	 //	 80	 160
{ KN, QN, TN, JA, TN, KN, SK, LO, TN, TN, SK, JA, JA, AC, TN }, 	 //	 81	 160
{ KN, QN, TN, TN, TN, KN, SK, LO, AC, TN, SK, JA, JA, AC, ST }, 	 //	 82	 160
{ KN, QN, TN, JA, TN, KN, SK, AC, TN, TN, SK, JA, AC, AC, TN }, 	 //	 83	 160
{ KN, QN, TN, JA, PF, KN, SK, AC, TN, JA, SK, JA, AC, AC, TN }, 	 //	 84	 160
{ KN, SK, SK, TN, TN, KN, JA, JA, TN, AC, SK, JA, TN, TN, AC }, 	 //	 85	 160
{ KN, SK, SK, TN, TN, KN, JA, JA, TN, AC, SK, JA, TN, WN, AC }, 	 //	 86	 160
{ KN, KN, WN, JA, PF, KN, KN, TN, SH, JA, SK, SK, TN, TN, TN }, 	 //	 87	 160
{ KN, KN, WN, ST, JA, KN, KN, TN, JA, WN, SK, SK, TN, TN, TN }, 	 //	 88	 160
{ KN, KN, TN, JA, WN, KN, KN, TN, SH, TN, SK, SK, TN, TN, TN }, 	 //	 89	 160
{ KN, KN, TN, SH, JA, KN, KN, TN, TN, TN, SK, SK, TN, TN, AC }, 	 //	 90	 160
{ KN, KN, TN, ST, WN, KN, KN, TN, JA, TN, SK, SK, TN, TN, TN }, 	 //	 91	 160
{ KN, KN, TN, JA, JA, KN, KN, TN, TN, WN, SK, SK, TN, AC, TN }, 	 //	 92	 160
{ KN, KN, TN, TN, TN, KN, KN, TN, TN, ST, SK, SK, LO, TN, AC }, 	 //	 93	 160
{ KN, KN, TN, TN, TN, KN, KN, LO, AC, ST, SK, SK, JA, AC, AC }, 	 //	 94	 160
{ KN, KN, SK, ST, TN, KN, KN, JA, JA, TN, SK, SK, TN, TN, TN }, 	 //	 95	 160
{ KN, KN, JA, TN, JA, KN, KN, TN, TN, TN, SK, SK, AC, TN, AC }, 	 //	 96	 160
{ KN, KN, TN, TN, TN, KN, KN, AC, AC, TN, SK, SK, AC, AC, TN }, 	 //	 97	 160
{ KN, KN, WN, TN, JA, KN, SK, TN, TN, TN, SK, QN, TN, TN, AC }, 	 //	 98	 160
{ KN, KN, TN, JA, JA, KN, SK, TN, TN, WN, SK, QN, TN, AC, TN }, 	 //	 99	 160
{ KN, KN, TN, TN, TN, KN, SK, TN, TN, AC, SK, QN, LO, TN, AC }, 	 //	 100	 160
{ KN, KN, TN, JA, PF, KN, SK, TN, TN, JA, SK, QN, LO, AC, TN }, 	 //	 101	 160
{ KN, KN, TN, SH, WN, KN, SK, LO, TN, TN, SK, QN, JA, TN, TN }, 	 //	 102	 160
{ KN, KN, TN, TN, TN, KN, SK, LO, TN, ST, SK, QN, JA, WN, AC }, 	 //	 103	 160
{ KN, KN, JA, TN, JA, KN, SK, TN, TN, TN, SK, QN, AC, TN, AC }, 	 //	 104	 160
{ KN, KN, TN, JA, PF, KN, SK, AC, TN, JA, SK, QN, AC, AC, TN }, 	 //	 105	 160
{ KN, SK, SK, JA, TN, KN, QN, JA, TN, TN, SK, KN, TN, AC, ST }, 	 //	 106	 160
{ KN, QN, KN, SH, TN, SK, SK, WN, TN, ST, QN, JA, TN, TN, AC }, 	 //	 107	 160
{ KN, QN, WN, JA, WN, SK, SK, TN, TN, TN, QN, JA, TN, AC, TN }, 	 //	 108	 160
{ KN, QN, TN, JA, TN, SK, SK, TN, SH, TN, QN, JA, TN, TN, TN }, 	 //	 109	 160
{ KN, QN, TN, TN, PF, SK, SK, TN, TN, JA, QN, JA, TN, WN, TN }, 	 //	 110	 160
{ KN, QN, TN, TN, TN, SK, SK, TN, WN, TN, QN, JA, TN, AC, TN }, 	 //	 111	 160
{ KN, QN, TN, TN, JA, SK, SK, TN, TN, WN, QN, JA, LO, TN, TN }, 	 //	 112	 160
{ KN, QN, TN, SH, WN, SK, SK, LO, TN, TN, QN, JA, JA, TN, TN }, 	 //	 113	 160
{ KN, QN, TN, TN, TN, SK, SK, LO, TN, TN, QN, JA, JA, WN, ST }, 	 //	 114	 160
{ KN, QN, JA, SH, JA, SK, SK, TN, TN, TN, QN, JA, AC, TN, AC }, 	 //	 115	 160
{ KN, QN, TN, TN, TN, SK, SK, AC, TN, AC, QN, JA, AC, WN, AC }, 	 //	 116	 160
{ KN, QN, TN, TN, TN, SK, SK, AC, WN, TN, QN, JA, AC, AC, ST }, 	 //	 117	 160
{ KN, KN, WN, TN, JA, SK, SK, TN, TN, WN, QN, QN, TN, TN, TN }, 	 //	 118	 160
{ KN, KN, WN, TN, JA, SK, SK, TN, TN, TN, QN, QN, TN, WN, AC }, 	 //	 119	 160
{ KN, KN, WN, JA, TN, SK, SK, TN, TN, AC, QN, QN, TN, AC, AC }, 	 //	 120	 160
{ KN, KN, TN, TN, TN, SK, SK, TN, WN, TN, QN, QN, TN, AC, TN }, 	 //	 121	 160
{ KN, KN, TN, SH, JA, SK, SK, TN, TN, WN, QN, QN, LO, TN, TN }, 	 //	 122	 160
{ KN, KN, TN, TN, JA, SK, SK, TN, TN, WN, QN, QN, LO, TN, TN }, 	 //	 123	 160
{ KN, KN, TN, TN, TN, SK, SK, TN, WN, ST, QN, QN, LO, AC, AC }, 	 //	 124	 160
{ KN, KN, TN, SH, TN, SK, SK, LO, TN, TN, QN, QN, JA, TN, TN }, 	 //	 125	 160
{ KN, KN, TN, JA, PF, SK, SK, LO, TN, JA, QN, QN, JA, AC, TN }, 	 //	 126	 160
{ KN, KN, TN, TN, TN, SK, SK, LO, AC, TN, QN, QN, JA, AC, ST }, 	 //	 127	 160
{ KN, KN, JA, TN, TN, SK, SK, TN, TN, TN, QN, QN, AC, TN, ST }, 	 //	 128	 160
{ KN, KN, JA, TN, JA, SK, SK, TN, TN, TN, QN, QN, AC, TN, AC }, 	 //	 129	 160
{ KN, KN, JA, TN, JA, SK, SK, TN, TN, TN, QN, QN, AC, WN, AC }, 	 //	 130	 160
{ KN, KN, TN, TN, JA, SK, SK, AC, TN, WN, QN, QN, AC, TN, TN }, 	 //	 131	 160
{ KN, KN, TN, TN, TN, SK, SK, AC, TN, ST, QN, QN, AC, WN, AC }, 	 //	 132	 160
{ KN, SK, SK, SH, TN, SK, QN, JA, TN, TN, QN, KN, TN, TN, ST }, 	 //	 133	 160
{ KN, SK, SK, SH, TN, SK, QN, JA, TN, ST, QN, KN, TN, TN, AC }, 	 //	 134	 160
{ KN, SK, SK, ST, JA, SK, QN, JA, JA, WN, QN, KN, TN, TN, TN }, 	 //	 135	 160
{ SK, QN, KN, ST, WN, QN, SK, WN, JA, TN, QN, JA, TN, TN, TN }, 	 //	 136	 160
{ SK, QN, KN, ST, TN, QN, SK, WN, JA, TN, QN, JA, TN, TN, TN }, 	 //	 137	 160
{ SK, QN, WN, ST, WN, QN, SK, TN, JA, TN, QN, JA, TN, TN, TN }, 	 //	 138	 160
{ SK, QN, TN, SH, TN, QN, SK, TN, TN, AC, QN, JA, TN, TN, AC }, 	 //	 139	 160
{ SK, QN, TN, TN, TN, QN, SK, TN, WN, AC, QN, JA, TN, AC, AC }, 	 //	 140	 160
{ SK, QN, TN, TN, TN, QN, SK, TN, TN, AC, QN, JA, LO, WN, AC }, 	 //	 141	 160
{ SK, QN, TN, TN, TN, QN, SK, LO, TN, AC, QN, JA, JA, TN, AC }, 	 //	 142	 160
{ SK, QN, TN, JA, PF, QN, SK, LO, TN, JA, QN, JA, JA, AC, TN }, 	 //	 143	 160
{ SK, QN, JA, JA, WN, QN, SK, TN, TN, TN, QN, JA, AC, AC, TN }, 	 //	 144	 160
{ SK, QN, TN, TN, WN, QN, SK, AC, TN, TN, QN, JA, AC, TN, TN }, 	 //	 145	 160
{ SK, QN, TN, TN, TN, QN, SK, AC, TN, AC, QN, JA, AC, TN, AC }, 	 //	 146	 160
{ SK, QN, TN, TN, WN, QN, SK, AC, TN, TN, QN, JA, AC, WN, TN }, 	 //	 147	 160
{ SK, SK, KN, ST, TN, QN, JA, WN, JA, TN, QN, JA, TN, TN, TN }, 	 //	 148	 160
{ SK, SK, WN, SH, JA, QN, JA, TN, TN, TN, QN, JA, TN, TN, AC }, 	 //	 149	 160
{ SK, SK, WN, TN, TN, QN, JA, TN, TN, ST, QN, JA, TN, TN, AC }, 	 //	 150	 160
{ SK, SK, WN, ST, WN, QN, JA, TN, JA, TN, QN, JA, TN, TN, TN }, 	 //	 151	 160
{ SK, SK, TN, JA, WN, QN, JA, TN, SH, TN, QN, JA, TN, TN, TN }, 	 //	 152	 160
{ SK, SK, TN, SH, JA, QN, JA, TN, TN, TN, QN, JA, TN, TN, AC }, 	 //	 153	 160
{ SK, SK, TN, TN, JA, QN, JA, TN, TN, TN, QN, JA, TN, WN, AC }, 	 //	 154	 160
{ SK, SK, TN, TN, TN, QN, JA, TN, AC, AC, QN, JA, TN, AC, AC }, 	 //	 155	 160
{ SK, SK, TN, TN, TN, QN, JA, TN, TN, AC, QN, JA, LO, TN, AC }, 	 //	 156	 160
{ SK, SK, JA, SH, TN, QN, JA, TN, TN, TN, QN, JA, AC, TN, TN }, 	 //	 157	 160
{ SK, SK, TN, TN, JA, QN, JA, AC, TN, WN, QN, JA, AC, TN, TN }, 	 //	 158	 160
{ SK, SK, TN, TN, TN, QN, JA, AC, TN, TN, QN, JA, AC, TN, ST }, 	 //	 159	 160
{ SK, SK, TN, TN, TN, QN, JA, AC, TN, AC, QN, JA, AC, WN, AC }, 	 //	 160	 160
{ SK, SK, TN, JA, JA, QN, JA, AC, TN, WN, QN, JA, AC, AC, TN }, 	 //	 161	 160
{ SK, SK, TN, JA, WN, QN, JA, AC, TN, TN, QN, JA, AC, AC, TN }, 	 //	 162	 160
{ SK, KN, KN, TN, TN, QN, SK, WN, TN, ST, QN, QN, TN, TN, AC }, 	 //	 163	 160
{ SK, KN, WN, TN, TN, QN, SK, TN, TN, ST, QN, QN, TN, TN, AC }, 	 //	 164	 160
{ SK, KN, WN, ST, TN, QN, SK, TN, JA, TN, QN, QN, TN, TN, TN }, 	 //	 165	 160
{ SK, KN, TN, SH, TN, QN, SK, TN, TN, AC, QN, QN, TN, TN, AC }, 	 //	 166	 160
{ SK, KN, TN, SH, JA, QN, SK, TN, TN, TN, QN, QN, LO, TN, AC }, 	 //	 167	 160
{ SK, KN, TN, SH, WN, QN, SK, LO, TN, TN, QN, QN, JA, TN, TN }, 	 //	 168	 160
{ SK, KN, TN, TN, TN, QN, SK, LO, TN, TN, QN, QN, JA, WN, ST }, 	 //	 169	 160
{ SK, KN, JA, TN, JA, QN, SK, TN, TN, TN, QN, QN, AC, TN, AC }, 	 //	 170	 160
{ SK, KN, JA, TN, WN, QN, SK, TN, TN, TN, QN, QN, AC, WN, TN }, 	 //	 171	 160
{ SK, KN, TN, TN, TN, QN, SK, AC, TN, TN, QN, QN, AC, TN, ST }, 	 //	 172	 160
{ SK, SK, KN, ST, TN, QN, QN, WN, JA, TN, QN, KN, TN, TN, TN }, 	 //	 173	 160
{ SK, SK, WN, JA, JA, QN, QN, TN, TN, TN, QN, KN, TN, AC, AC }, 	 //	 174	 160
{ SK, SK, TN, TN, TN, QN, QN, TN, WN, TN, QN, KN, TN, AC, ST }, 	 //	 175	 160
{ SK, SK, TN, SH, TN, QN, QN, TN, TN, TN, QN, KN, LO, TN, ST }, 	 //	 176	 160
{ SK, SK, TN, TN, TN, QN, QN, TN, AC, ST, QN, KN, LO, AC, AC }, 	 //	 177	 160
{ SK, SK, TN, TN, TN, QN, QN, LO, TN, TN, QN, KN, JA, TN, ST }, 	 //	 178	 160
{ SK, SK, JA, SH, TN, QN, QN, TN, TN, TN, QN, KN, AC, TN, TN }, 	 //	 179	 160
{ SK, SK, JA, TN, WN, QN, QN, TN, TN, TN, QN, KN, AC, TN, TN }, 	 //	 180	 160
{ SK, SK, JA, TN, WN, QN, QN, TN, TN, TN, QN, KN, AC, WN, TN }, 	 //	 181	 160
{ SK, SK, TN, SH, WN, QN, QN, AC, TN, TN, QN, KN, AC, TN, TN }, 	 //	 182	 160
{ QN, QN, SK, SH, TN, QN, SK, JA, TN, ST, QN, JA, TN, TN, AC }, 	 //	 183	 160
{ QN, SK, SK, TN, WN, QN, JA, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 184	 160
{ QN, SK, SK, JA, TN, QN, JA, JA, TN, ST, QN, JA, TN, AC, AC }, 	 //	 185	 160
{ QN, KN, SK, ST, JA, QN, SK, JA, JA, WN, QN, QN, TN, TN, TN }, 	 //	 186	 160
{ QN, SK, SK, TN, WN, QN, QN, JA, TN, TN, QN, KN, TN, TN, TN }, 	 //	 187	 160
{ QN, QN, SK, JA, PF, QN, SK, JA, SH, JA, SH, JA, TN, TN, TN }, 	 //	 188	 160
{ QN, QN, SK, TN, JA, QN, SK, JA, TN, WN, SH, JA, TN, TN, TN }, 	 //	 189	 160
{ QN, QN, SK, TN, TN, QN, SK, JA, TN, AC, SH, JA, TN, TN, AC }, 	 //	 190	 160
{ QN, SK, SK, JA, TN, QN, JA, JA, TN, ST, SH, JA, TN, AC, AC }, 	 //	 191	 160
{ QN, KN, SK, SH, TN, QN, SK, JA, TN, AC, SH, QN, TN, TN, AC }, 	 //	 192	 160
{ QN, SK, SK, JA, WN, QN, QN, JA, SH, TN, SH, KN, TN, TN, TN }, 	 //	 193	 160
{ QN, SK, SK, SH, JA, QN, QN, JA, TN, WN, SH, KN, TN, TN, TN }, 	 //	 194	 160
{ QN, SK, SK, TN, TN, QN, QN, JA, TN, ST, SH, KN, TN, WN, AC }, 	 //	 195	 160
{ QN, QN, SK, SH, JA, SH, SK, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 196	 160
{ QN, QN, SK, SH, TN, SH, SK, JA, TN, TN, JA, JA, TN, TN, ST }, 	 //	 197	 160
{ QN, QN, SK, SH, PF, SH, SK, JA, TN, JA, JA, JA, TN, TN, TN }, 	 //	 198	 160
{ QN, SK, SK, TN, TN, SH, JA, JA, TN, AC, JA, JA, TN, WN, AC }, 	 //	 199	 160
{ QN, SK, SK, JA, TN, SH, JA, JA, TN, TN, JA, JA, TN, AC, ST }, 	 //	 200	 160
{ QN, KN, SK, JA, JA, SH, SK, JA, SH, WN, JA, QN, TN, TN, TN }, 	 //	 201	 160
{ QN, KN, SK, SH, WN, SH, SK, JA, TN, TN, JA, QN, TN, TN, TN }, 	 //	 202	 160
{ QN, KN, SK, SH, PF, SH, SK, JA, TN, JA, JA, QN, TN, TN, TN }, 	 //	 203	 160
{ QN, KN, SK, TN, TN, SH, SK, JA, TN, TN, JA, QN, TN, WN, ST }, 	 //	 204	 160
{ QN, SK, SK, TN, TN, SH, QN, JA, TN, TN, JA, KN, TN, WN, TN }, 	 //	 205	 160
{ QN, SK, SK, ST, TN, SH, QN, JA, JA, TN, JA, KN, TN, TN, TN }, 	 //	 206	 160
{ SH, QN, SK, TN, WN, JA, SK, JA, TN, TN, JA, JA, TN, TN, TN }, 	 //	 207	 160
{ SH, QN, SK, JA, TN, JA, SK, JA, TN, TN, JA, JA, TN, AC, ST }, 	 //	 208	 160
{ SH, SK, SK, JA, PF, JA, QN, JA, SH, JA, JA, KN, TN, TN, TN }, 	 //	 209	 160
{ JA, QN, SK, JA, JA, JA, SK, JA, SH, WN, JA, JA, TN, TN, TN }, 	 //	 210	 160
{ JA, QN, SK, TN, TN, JA, SK, JA, TN, ST, JA, JA, TN, TN, AC }, 	 //	 211	 160
{ JA, QN, SK, TN, TN, JA, SK, JA, TN, TN, JA, JA, TN, WN, TN }, 	 //	 212	 160
{ JA, QN, SK, ST, JA, JA, SK, JA, JA, WN, JA, JA, TN, TN, TN }, 	 //	 213	 160
{ JA, KN, SK, JA, JA, JA, SK, JA, SH, WN, JA, QN, TN, TN, TN }, 	 //	 214	 160
{ JA, KN, SK, JA, PF, JA, SK, JA, SH, JA, JA, QN, TN, TN, TN }, 	 //	 215	 160
{ JA, SK, SK, JA, PF, JA, QN, JA, SH, JA, JA, KN, TN, TN, TN }, 	 //	 216	 160
{ JA, SK, SK, TN, TN, JA, QN, JA, TN, TN, JA, KN, TN, TN, ST }, 	 //	 217	 160
{ JA, QN, SK, JA, TN, JA, SK, JA, TN, TN, WN, JA, TN, AC, TN }, 	 //	 218	 160
{ JA, KN, SK, JA, TN, JA, SK, JA, SH, TN, WN, QN, TN, TN, TN }, 	 //	 219	 160
{ JA, KN, SK, TN, WN, JA, SK, JA, TN, TN, WN, QN, TN, TN, TN }, 	 //	 220	 160
{ JA, KN, SK, TN, TN, JA, SK, JA, TN, TN, WN, QN, TN, WN, TN }, 	 //	 221	 160
{ JA, SK, SK, JA, WN, JA, QN, JA, SH, TN, WN, KN, TN, TN, TN }, 	 //	 222	 160
{ JA, SK, SK, JA, TN, JA, QN, JA, TN, ST, WN, KN, TN, AC, AC }, 	 //	 223	 160
{ JA, QN, SK, ST, TN, WN, SK, JA, JA, TN, TN, JA, TN, TN, TN }, 	 //	 224	 160
{ JA, QN, SK, JA, TN, WN, SK, JA, TN, ST, TN, JA, TN, AC, AC }, 	 //	 225	 160
{ JA, QN, SK, JA, TN, WN, SK, JA, TN, AC, TN, JA, TN, AC, AC }, 	 //	 226	 160
{ JA, JA, KN, QN, KN, WN, SH, WN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 227	 160
{ JA, JA, WN, QN, KN, WN, SH, TN, QN, KN, TN, TN, TN, SK, SK }, 	 //	 228	 160
{ JA, JA, WN, QN, AC, WN, SH, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 229	 160
{ JA, JA, SK, QN, LO, WN, SH, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 230	 160
{ JA, JA, SK, QN, SH, WN, SH, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 231	 160
{ JA, JA, SK, QN, QN, WN, SH, JA, SK, KN, TN, TN, TN, JA, AC }, 	 //	 232	 160
{ JA, JA, SK, SK, QN, WN, SH, JA, QN, PF, TN, TN, TN, KN, JA }, 	 //	 233	 160
{ JA, JA, SK, SK, AC, WN, SH, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 234	 160
{ JA, SH, KN, QN, SK, WN, TN, WN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 235	 160
{ JA, SH, KN, KN, AC, WN, TN, WN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 236	 160
{ JA, SH, WN, QN, AC, WN, TN, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 237	 160
{ JA, SH, WN, SK, SK, WN, TN, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 238	 160
{ JA, SH, WN, KN, KN, WN, TN, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 239	 160
{ JA, SH, WN, KN, KN, WN, TN, TN, SK, KN, TN, TN, TN, QN, SK }, 	 //	 240	 160
{ JA, SH, TN, KN, AC, WN, TN, TN, SK, SK, TN, TN, LO, QN, KN }, 	 //	 241	 160
{ JA, SH, TN, QN, AC, WN, TN, LO, SK, AC, TN, TN, JA, JA, SK }, 	 //	 242	 160
{ JA, SH, TN, KN, AC, WN, TN, LO, SK, SK, TN, TN, JA, QN, KN }, 	 //	 243	 160
{ JA, SH, TN, SK, SK, WN, TN, LO, QN, KN, TN, TN, JA, KN, KN }, 	 //	 244	 160
{ JA, SH, SK, QN, PF, WN, TN, JA, SK, JA, TN, TN, TN, JA, TN }, 	 //	 245	 160
{ JA, SH, SK, QN, KN, WN, TN, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 246	 160
{ JA, SH, SK, SK, QN, WN, TN, JA, JA, SH, TN, TN, TN, JA, JA }, 	 //	 247	 160
{ JA, SH, SK, SK, TN, WN, TN, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 248	 160
{ JA, SH, SK, SK, QN, WN, TN, JA, JA, KN, TN, TN, TN, JA, AC }, 	 //	 249	 160
{ JA, SH, SK, KN, PF, WN, TN, JA, SK, JA, TN, TN, TN, QN, TN }, 	 //	 250	 160
{ JA, SH, SK, KN, KN, WN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 251	 160
{ JA, SH, TN, SK, SK, WN, TN, AC, JA, QN, TN, TN, AC, JA, QN }, 	 //	 252	 160
{ JA, TN, KN, KN, AC, WN, TN, WN, SK, AC, TN, TN, TN, QN, SK }, 	 //	 253	 160
{ JA, TN, WN, QN, AC, WN, TN, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 254	 160
{ JA, TN, TN, QN, KN, WN, TN, LO, SK, SK, TN, TN, JA, JA, QN }, 	 //	 255	 160
{ JA, TN, TN, SK, SK, WN, TN, LO, JA, QN, TN, TN, JA, JA, QN }, 	 //	 256	 160
{ JA, TN, TN, SK, SK, WN, TN, LO, QN, KN, TN, TN, JA, KN, KN }, 	 //	 257	 160
{ JA, TN, SK, QN, KN, WN, TN, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 258	 160
{ JA, TN, SK, QN, SH, WN, TN, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 259	 160
{ JA, TN, SK, QN, TN, WN, TN, JA, SK, ST, TN, TN, TN, JA, AC }, 	 //	 260	 160
{ JA, TN, SK, QN, PF, WN, TN, JA, SK, JA, TN, TN, TN, JA, TN }, 	 //	 261	 160
{ JA, TN, SK, SK, AC, WN, TN, JA, JA, AC, TN, TN, TN, JA, CR }, 	 //	 262	 160
{ JA, TN, SK, SK, CR, WN, TN, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 263	 160
{ JA, TN, SK, SK, KN, WN, TN, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 264	 160
{ JA, TN, SK, KN, CR, WN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 265	 160
{ JA, TN, SK, KN, KN, WN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 266	 160
{ JA, TN, SK, SK, JA, WN, TN, JA, QN, WN, TN, TN, TN, KN, TN }, 	 //	 267	 160
{ JA, TN, SK, SK, AC, WN, TN, JA, QN, KN, TN, TN, TN, KN, QN }, 	 //	 268	 160
{ JA, TN, SK, SK, TN, WN, TN, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 269	 160
{ JA, TN, SK, SK, AC, WN, TN, JA, QN, SK, TN, TN, TN, KN, KN }, 	 //	 270	 160
{ JA, TN, TN, QN, KN, WN, TN, AC, SK, SK, TN, TN, AC, JA, QN }, 	 //	 271	 160
{ JA, TN, TN, QN, AC, WN, TN, AC, SK, SK, TN, TN, AC, JA, KN }, 	 //	 272	 160
{ JA, TN, TN, SK, SK, WN, TN, TN, JA, KN, TN, WN, LO, JA, KN }, 	 //	 273	 160
{ JA, TN, TN, KN, AC, WN, TN, TN, SK, SK, TN, WN, LO, QN, KN }, 	 //	 274	 160
{ JA, TN, TN, QN, AC, WN, TN, LO, SK, AC, TN, WN, JA, JA, SK }, 	 //	 275	 160
{ JA, TN, TN, QN, AC, WN, TN, AC, SK, AC, TN, WN, AC, JA, SK }, 	 //	 276	 160
{ JA, TN, TN, KN, SK, WN, TN, AC, SK, QN, TN, WN, AC, QN, QN }, 	 //	 277	 160
{ JA, ST, KN, SK, SK, WN, JA, WN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 278	 160
{ JA, ST, WN, QN, SK, WN, JA, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 279	 160
{ JA, ST, WN, KN, KN, WN, JA, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 280	 160
{ JA, ST, TN, KN, AC, WN, JA, TN, SK, SK, TN, TN, TN, QN, KN }, 	 //	 281	 160
{ JA, ST, SK, KN, KN, WN, JA, JA, SK, AC, TN, TN, TN, QN, LO }, 	 //	 282	 160
{ JA, ST, SK, SK, ST, WN, JA, JA, QN, AC, TN, TN, TN, KN, KN }, 	 //	 283	 160
{ JA, ST, SK, SK, AC, WN, JA, JA, QN, AC, TN, TN, TN, KN, SK }, 	 //	 284	 160
{ JA, ST, SK, SK, KN, WN, JA, JA, QN, AC, TN, TN, TN, KN, LO }, 	 //	 285	 160
{ JA, JA, TN, KN, AC, WN, TN, TN, SK, SK, TN, AC, TN, QN, KN }, 	 //	 286	 160
{ JA, JA, TN, SK, SK, WN, TN, TN, QN, KN, TN, AC, TN, KN, KN }, 	 //	 287	 160
{ JA, JA, TN, QN, KN, WN, TN, TN, SK, SK, TN, AC, LO, JA, QN }, 	 //	 288	 160
{ JA, JA, TN, QN, KN, WN, TN, AC, QN, KN, TN, AC, AC, SK, SK }, 	 //	 289	 160
{ JA, JA, TN, QN, AC, WN, TN, AC, QN, AC, TN, AC, AC, SK, SK }, 	 //	 290	 160
{ JA, JA, TN, KN, AC, WN, TN, AC, SK, SK, TN, AC, AC, QN, KN }, 	 //	 291	 160
{ JA, KN, SK, JA, TN, WN, SK, JA, TN, ST, TN, QN, TN, AC, AC }, 	 //	 292	 160
{ JA, KN, SK, JA, TN, WN, SK, JA, TN, AC, TN, QN, TN, AC, AC }, 	 //	 293	 160
{ JA, SK, SK, TN, TN, WN, QN, JA, TN, AC, TN, KN, TN, TN, AC }, 	 //	 294	 160
{ JA, SK, SK, JA, TN, WN, QN, JA, TN, TN, TN, KN, TN, AC, ST }, 	 //	 295	 160
{ WN, QN, SK, SH, TN, TN, SK, JA, TN, TN, TN, JA, TN, TN, ST }, 	 //	 296	 160
{ WN, QN, SK, JA, TN, TN, SK, JA, TN, TN, TN, JA, TN, AC, TN }, 	 //	 297	 160
{ WN, SK, SK, JA, JA, TN, JA, JA, SH, WN, TN, JA, TN, TN, TN }, 	 //	 298	 160
{ WN, SK, SK, SH, TN, TN, JA, JA, TN, ST, TN, JA, TN, TN, AC }, 	 //	 299	 160
{ WN, SK, SK, TN, TN, TN, JA, JA, TN, TN, TN, JA, TN, TN, ST }, 	 //	 300	 160
{ WN, JA, KN, QN, SK, TN, SH, WN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 301	 160
{ WN, JA, KN, SK, SK, TN, SH, WN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 302	 160
{ WN, JA, SK, QN, SH, TN, SH, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 303	 160
{ WN, JA, SK, QN, ST, TN, SH, JA, SK, AC, TN, TN, TN, JA, KN }, 	 //	 304	 160
{ WN, JA, SK, SK, AC, TN, SH, JA, JA, AC, TN, TN, TN, JA, CR }, 	 //	 305	 160
{ WN, JA, SK, SK, AC, TN, SH, JA, QN, AC, TN, TN, TN, KN, CR }, 	 //	 306	 160
{ WN, JA, SK, SK, JA, TN, SH, JA, QN, WN, TN, TN, TN, KN, TN }, 	 //	 307	 160
{ WN, JA, SK, SK, TN, TN, SH, JA, QN, ST, TN, TN, TN, KN, AC }, 	 //	 308	 160
{ WN, JA, SK, SK, AC, TN, SH, JA, QN, KN, TN, TN, TN, KN, QN }, 	 //	 309	 160
{ WN, JA, SK, SK, PF, TN, SH, JA, QN, JA, TN, TN, TN, KN, TN }, 	 //	 310	 160
{ WN, JA, SK, SK, TN, TN, SH, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 311	 160
{ WN, SH, KN, QN, SK, TN, TN, WN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 312	 160
{ WN, SH, KN, SK, SK, TN, TN, WN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 313	 160
{ WN, SH, KN, KN, AC, TN, TN, WN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 314	 160
{ WN, SH, KN, KN, SK, TN, TN, WN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 315	 160
{ WN, SH, KN, KN, SK, TN, TN, WN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 316	 160
{ WN, SH, KN, SK, SK, TN, TN, WN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 317	 160
{ WN, SH, TN, KN, KN, TN, TN, LO, SK, SK, TN, TN, JA, QN, QN }, 	 //	 318	 160
{ WN, SH, TN, KN, AC, TN, TN, LO, SK, AC, TN, TN, JA, QN, SK }, 	 //	 319	 160
{ WN, SH, SK, QN, AC, TN, TN, JA, QN, AC, TN, TN, TN, SK, SK }, 	 //	 320	 160
{ WN, SH, SK, QN, JA, TN, TN, JA, SK, WN, TN, TN, TN, JA, TN }, 	 //	 321	 160
{ WN, SH, SK, QN, TN, TN, TN, JA, SK, TN, TN, TN, TN, JA, ST }, 	 //	 322	 160
{ WN, SH, SK, QN, CR, TN, TN, JA, SK, QN, TN, TN, TN, JA, KN }, 	 //	 323	 160
{ WN, SH, SK, QN, QN, TN, TN, JA, SK, KN, TN, TN, TN, JA, AC }, 	 //	 324	 160
{ WN, SH, SK, SK, TN, TN, TN, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 325	 160
{ WN, SH, SK, SK, AC, TN, TN, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 326	 160
{ WN, SH, SK, SK, KN, TN, TN, JA, JA, KN, TN, TN, TN, JA, CR }, 	 //	 327	 160
{ WN, SH, SK, KN, KN, TN, TN, JA, KN, KN, TN, TN, TN, SK, SK }, 	 //	 328	 160
{ WN, SH, SK, KN, AC, TN, TN, JA, SK, AC, TN, TN, TN, QN, CR }, 	 //	 329	 160
{ WN, SH, SK, KN, CR, TN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 330	 160
{ WN, SH, SK, KN, SH, TN, TN, JA, SK, JA, TN, TN, TN, QN, JA }, 	 //	 331	 160
{ WN, SH, SK, KN, JA, TN, TN, JA, SK, JA, TN, TN, TN, QN, WN }, 	 //	 332	 160
{ WN, SH, SK, KN, QN, TN, TN, JA, SK, PF, TN, TN, TN, QN, JA }, 	 //	 333	 160
{ WN, SH, SK, SK, AC, TN, TN, JA, QN, LO, TN, TN, TN, KN, AC }, 	 //	 334	 160
{ WN, SH, SK, SK, QN, TN, TN, JA, QN, SH, TN, TN, TN, KN, JA }, 	 //	 335	 160
{ WN, SH, SK, SK, KN, TN, TN, JA, QN, AC, TN, TN, TN, KN, LO }, 	 //	 336	 160
{ WN, SH, JA, QN, KN, TN, TN, TN, SK, KN, TN, TN, AC, JA, SK }, 	 //	 337	 160
{ WN, SH, JA, QN, KN, TN, TN, TN, SK, SK, TN, TN, AC, JA, QN }, 	 //	 338	 160
{ WN, SH, JA, SK, SK, TN, TN, TN, JA, QN, TN, TN, AC, JA, QN }, 	 //	 339	 160
{ WN, SH, TN, QN, AC, TN, TN, AC, SK, SK, TN, TN, AC, JA, KN }, 	 //	 340	 160
{ WN, TN, KN, SK, SK, TN, TN, WN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 341	 160
{ WN, TN, TN, QN, SK, TN, TN, LO, SK, KN, TN, TN, JA, JA, KN }, 	 //	 342	 160
{ WN, TN, TN, KN, KN, TN, TN, LO, KN, KN, TN, TN, JA, SK, SK }, 	 //	 343	 160
{ WN, TN, TN, KN, KN, TN, TN, LO, SK, KN, TN, TN, JA, QN, SK }, 	 //	 344	 160
{ WN, TN, SK, QN, KN, TN, TN, JA, QN, KN, TN, TN, TN, SK, SK }, 	 //	 345	 160
{ WN, TN, SK, QN, WN, TN, TN, JA, SK, TN, TN, TN, TN, JA, TN }, 	 //	 346	 160
{ WN, TN, SK, SK, TN, TN, TN, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 347	 160
{ WN, TN, SK, SK, AC, TN, TN, JA, JA, KN, TN, TN, TN, JA, QN }, 	 //	 348	 160
{ WN, TN, SK, KN, AC, TN, TN, JA, KN, AC, TN, TN, TN, SK, SK }, 	 //	 349	 160
{ WN, TN, SK, KN, CR, TN, TN, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 350	 160
{ WN, TN, SK, KN, JA, TN, TN, JA, SK, JA, TN, TN, TN, QN, WN }, 	 //	 351	 160
{ WN, TN, SK, KN, WN, TN, TN, JA, SK, TN, TN, TN, TN, QN, TN }, 	 //	 352	 160
{ WN, TN, SK, KN, TN, TN, TN, JA, SK, ST, TN, TN, TN, QN, AC }, 	 //	 353	 160
{ WN, TN, SK, KN, KN, TN, TN, JA, SK, KN, TN, TN, TN, QN, CR }, 	 //	 354	 160
{ WN, TN, SK, KN, CR, TN, TN, JA, SK, QN, TN, TN, TN, QN, KN }, 	 //	 355	 160
{ WN, TN, SK, KN, KN, TN, TN, JA, SK, AC, TN, TN, TN, QN, LO }, 	 //	 356	 160
{ WN, TN, JA, KN, KN, TN, TN, TN, KN, KN, TN, TN, AC, SK, SK }, 	 //	 357	 160
{ WN, TN, TN, QN, KN, TN, TN, AC, QN, KN, TN, TN, AC, SK, SK }, 	 //	 358	 160
{ WN, TN, TN, QN, KN, TN, TN, LO, QN, KN, TN, WN, JA, SK, SK }, 	 //	 359	 160
{ WN, TN, TN, QN, AC, TN, TN, LO, QN, AC, TN, WN, JA, SK, SK }, 	 //	 360	 160
{ WN, TN, TN, QN, KN, TN, TN, AC, QN, KN, TN, WN, AC, SK, SK }, 	 //	 361	 160
{ WN, ST, KN, QN, AC, TN, JA, WN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 362	 160
{ WN, ST, KN, SK, SK, TN, JA, WN, JA, QN, TN, TN, TN, JA, QN }, 	 //	 363	 160
{ WN, ST, WN, QN, AC, TN, JA, TN, SK, SK, TN, TN, TN, JA, KN }, 	 //	 364	 160
{ WN, ST, TN, QN, AC, TN, JA, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 365	 160
{ WN, ST, SK, QN, ST, TN, JA, JA, SK, AC, TN, TN, TN, JA, KN }, 	 //	 366	 160
{ WN, ST, SK, KN, KN, TN, JA, JA, SK, KN, TN, TN, TN, QN, KN }, 	 //	 367	 160
{ WN, ST, SK, KN, TN, TN, JA, JA, SK, TN, TN, TN, TN, QN, TN }, 	 //	 368	 160
{ WN, ST, SK, KN, KN, TN, JA, JA, SK, KN, TN, TN, TN, QN, CR }, 	 //	 369	 160
{ WN, ST, SK, SK, KN, TN, JA, JA, QN, KN, TN, TN, TN, KN, KN }, 	 //	 370	 160
{ WN, ST, SK, SK, JA, TN, JA, JA, QN, JA, TN, TN, TN, KN, WN }, 	 //	 371	 160
{ WN, JA, WN, QN, AC, TN, TN, TN, QN, AC, TN, AC, TN, SK, SK }, 	 //	 372	 160
{ WN, JA, WN, QN, AC, TN, TN, TN, SK, SK, TN, AC, TN, JA, KN }, 	 //	 373	 160
{ WN, JA, TN, QN, AC, TN, TN, AC, QN, AC, TN, AC, AC, SK, SK }, 	 //	 374	 160
{ WN, JA, TN, KN, KN, TN, TN, AC, SK, SK, TN, AC, AC, QN, QN }, 	 //	 375	 160
{ WN, JA, TN, KN, AC, TN, TN, AC, SK, AC, TN, AC, AC, QN, SK }, 	 //	 376	 160
{ WN, KN, SK, SH, TN, TN, SK, JA, TN, AC, TN, QN, TN, TN, AC }, 	 //	 377	 160
{ WN, SK, SK, SH, JA, TN, QN, JA, TN, WN, TN, KN, TN, TN, TN }, 	 //	 378	 160
{ WN, SK, SK, TN, PF, TN, QN, JA, TN, JA, TN, KN, TN, TN, TN }, 	 //	 379	 160
{ WN, SK, SK, TN, TN, TN, QN, JA, TN, AC, TN, KN, TN, TN, AC }, 	 //	 380	 160
{ WN, SK, SK, ST, TN, TN, QN, JA, JA, TN, TN, KN, TN, TN, TN }, 	 //	 381	 160
{ TN, QN, SK, JA, TN, TN, SK, JA, SH, TN, TN, JA, TN, TN, TN }, 	 //	 382	 160
{ TN, QN, SK, TN, PF, TN, SK, JA, TN, JA, TN, JA, TN, TN, TN }, 	 //	 383	 160
{ TN, JA, KN, KN, SK, TN, SH, WN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 384	 160
{ TN, JA, WN, QN, AC, TN, SH, TN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 385	 160
{ TN, JA, SK, QN, AC, TN, SH, JA, SK, AC, TN, TN, TN, JA, AC }, 	 //	 386	 160
{ TN, JA, SK, SK, QN, TN, SH, JA, JA, QN, TN, TN, TN, JA, SH }, 	 //	 387	 160
{ TN, JA, SK, SK, ST, TN, SH, JA, JA, AC, TN, TN, TN, JA, KN }, 	 //	 388	 160
{ TN, JA, SK, SK, TN, TN, SH, JA, JA, AC, TN, TN, TN, JA, AC }, 	 //	 389	 160
{ TN, JA, SK, KN, QN, TN, SH, JA, SK, QN, TN, TN, TN, QN, SH }, 	 //	 390	 160
{ TN, JA, SK, KN, QN, TN, SH, JA, SK, SH, TN, TN, TN, QN, JA }, 	 //	 391	 160
{ TN, JA, SK, KN, JA, TN, SH, JA, SK, JA, TN, TN, TN, QN, WN }, 	 //	 392	 160
{ TN, JA, SK, KN, TN, TN, SH, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 393	 160
{ TN, JA, SK, SK, AC, TN, SH, JA, QN, LO, TN, TN, TN, KN, AC }, 	 //	 394	 160
{ TN, JA, SK, SK, KN, TN, SH, JA, QN, KN, TN, TN, TN, KN, SK }, 	 //	 395	 160
{ TN, JA, SK, SK, JA, TN, SH, JA, QN, JA, TN, TN, TN, KN, WN }, 	 //	 396	 160
{ TN, JA, SK, SK, AC, TN, SH, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 397	 160
{ TN, SH, TN, QN, AC, TN, TN, LO, SK, SK, TN, TN, JA, JA, KN }, 	 //	 398	 160
{ TN, SH, TN, SK, SK, TN, TN, LO, JA, QN, TN, TN, JA, JA, QN }, 	 //	 399	 160
{ TN, SH, JA, QN, KN, TN, TN, TN, SK, SK, TN, TN, AC, JA, QN }, 	 //	 400	 160
{ TN, SH, TN, QN, AC, TN, TN, AC, SK, SK, TN, TN, AC, JA, KN }, 	 //	 401	 160
{ TN, SH, TN, QN, SK, TN, TN, AC, SK, KN, TN, TN, AC, JA, KN }, 	 //	 402	 160
{ TN, SH, TN, KN, KN, TN, TN, AC, SK, KN, TN, TN, AC, QN, SK }, 	 //	 403	 160
{ TN, TN, JA, QN, KN, TN, TN, TN, SK, SK, TN, TN, AC, JA, QN }, 	 //	 404	 160
{ TN, TN, JA, KN, AC, TN, TN, TN, SK, AC, TN, TN, AC, QN, SK }, 	 //	 405	 160
{ TN, TN, JA, KN, AC, TN, TN, TN, SK, SK, TN, TN, AC, QN, KN }, 	 //	 406	 160
{ TN, TN, SK, QN, AC, TN, TN, JA, SK, LO, TN, WN, TN, JA, AC }, 	 //	 407	 160
{ TN, TN, SK, QN, ST, TN, TN, JA, SK, AC, TN, WN, TN, JA, KN }, 	 //	 408	 160
{ TN, TN, SK, KN, TN, TN, TN, JA, SK, AC, TN, WN, TN, QN, AC }, 	 //	 409	 160
{ TN, TN, SK, KN, QN, TN, TN, JA, SK, KN, TN, WN, TN, QN, AC }, 	 //	 410	 160
{ TN, TN, SK, SK, SH, TN, TN, JA, QN, JA, TN, WN, TN, KN, JA }, 	 //	 411	 160
{ TN, TN, SK, SK, KN, TN, TN, JA, QN, KN, TN, WN, TN, KN, CR }, 	 //	 412	 160
{ TN, TN, JA, QN, SK, TN, TN, TN, SK, KN, TN, WN, AC, JA, KN }, 	 //	 413	 160
{ TN, TN, JA, KN, SK, TN, TN, TN, SK, QN, TN, WN, AC, QN, QN }, 	 //	 414	 160
{ TN, TN, TN, KN, SK, TN, WN, LO, SK, KN, TN, AC, JA, QN, KN }, 	 //	 415	 160
{ TN, TN, TN, QN, KN, TN, WN, AC, QN, KN, TN, AC, AC, SK, SK }, 	 //	 416	 160
{ TN, ST, KN, KN, AC, TN, JA, WN, KN, AC, TN, TN, TN, SK, SK }, 	 //	 417	 160
{ TN, ST, WN, KN, SK, TN, JA, TN, SK, KN, TN, TN, TN, QN, KN }, 	 //	 418	 160
{ TN, ST, TN, QN, AC, TN, JA, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 419	 160
{ TN, ST, SK, QN, JA, TN, JA, JA, SK, WN, TN, TN, TN, JA, TN }, 	 //	 420	 160
{ TN, ST, SK, QN, AC, TN, JA, JA, SK, KN, TN, TN, TN, JA, QN }, 	 //	 421	 160
{ TN, ST, SK, QN, QN, TN, JA, JA, SK, KN, TN, TN, TN, JA, AC }, 	 //	 422	 160
{ TN, ST, SK, KN, SH, TN, JA, JA, SK, JA, TN, TN, TN, QN, JA }, 	 //	 423	 160
{ TN, ST, SK, SK, KN, TN, JA, JA, QN, KN, TN, TN, TN, KN, KN }, 	 //	 424	 160
{ TN, ST, SK, SK, QN, TN, JA, JA, QN, KN, TN, TN, TN, KN, AC }, 	 //	 425	 160
{ TN, JA, KN, QN, KN, TN, TN, WN, SK, KN, TN, AC, TN, JA, SK }, 	 //	 426	 160
{ TN, JA, KN, SK, SK, TN, TN, WN, QN, KN, TN, AC, TN, KN, KN }, 	 //	 427	 160
{ TN, JA, TN, QN, AC, TN, TN, LO, SK, AC, TN, AC, JA, JA, SK }, 	 //	 428	 160
{ TN, JA, TN, KN, SK, TN, TN, LO, SK, QN, TN, AC, JA, QN, QN }, 	 //	 429	 160
{ TN, JA, SK, QN, AC, TN, TN, JA, SK, LO, TN, AC, TN, JA, AC }, 	 //	 430	 160
{ TN, JA, SK, QN, TN, TN, TN, JA, SK, TN, TN, AC, TN, JA, ST }, 	 //	 431	 160
{ TN, JA, SK, QN, AC, TN, TN, JA, SK, KN, TN, AC, TN, JA, QN }, 	 //	 432	 160
{ TN, JA, SK, SK, JA, TN, TN, JA, JA, TN, TN, AC, TN, JA, AC }, 	 //	 433	 160
{ TN, JA, SK, KN, AC, TN, TN, JA, SK, AC, TN, AC, TN, QN, AC }, 	 //	 434	 160
{ TN, JA, SK, KN, TN, TN, TN, JA, SK, TN, TN, AC, TN, QN, ST }, 	 //	 435	 160
{ TN, JA, SK, KN, AC, TN, TN, JA, SK, KN, TN, AC, TN, QN, QN }, 	 //	 436	 160
{ TN, JA, SK, KN, KN, TN, TN, JA, SK, QN, TN, AC, TN, QN, PF }, 	 //	 437	 160
{ TN, JA, SK, SK, KN, TN, TN, JA, QN, QN, TN, AC, TN, KN, PF }, 	 //	 438	 160
{ TN, JA, SK, SK, QN, TN, TN, JA, QN, KN, TN, AC, TN, KN, AC }, 	 //	 439	 160
{ TN, JA, JA, SK, SK, TN, TN, TN, JA, KN, TN, AC, AC, JA, KN }, 	 //	 440	 160
{ TN, JA, JA, SK, SK, TN, TN, TN, QN, KN, TN, AC, AC, KN, KN }, 	 //	 441	 160
{ TN, TN, TN, QN, KN, TN, AC, TN, QN, KN, TN, AC, LO, SK, SK }, 	 //	 442	 160
{ TN, TN, TN, KN, KN, TN, AC, LO, KN, KN, TN, AC, JA, SK, SK }, 	 //	 443	 160
{ TN, TN, TN, QN, KN, TN, AC, AC, SK, KN, TN, AC, AC, JA, SK }, 	 //	 444	 160
{ TN, TN, TN, KN, AC, TN, AC, AC, SK, AC, TN, AC, AC, QN, SK }, 	 //	 445	 160
{ TN, KN, SK, JA, PF, TN, SK, JA, SH, JA, TN, QN, TN, TN, TN }, 	 //	 446	 160
{ TN, KN, SK, SH, TN, TN, SK, JA, TN, AC, TN, QN, TN, TN, AC }, 	 //	 447	 160
{ TN, KN, SK, TN, WN, TN, SK, JA, TN, TN, TN, QN, TN, TN, TN }, 	 //	 448	 160
{ TN, KN, SK, TN, TN, TN, SK, JA, TN, TN, TN, QN, TN, WN, TN }, 	 //	 449	 160
{ TN, SK, SK, SH, TN, TN, QN, JA, TN, AC, TN, KN, TN, TN, AC }, 	 //	 450	 160
{ TN, QN, SK, TN, TN, TN, SK, JA, TN, TN, ST, JA, TN, WN, TN }, 	 //	 451	 160
{ TN, SK, SK, JA, JA, TN, JA, JA, SH, WN, ST, JA, TN, TN, TN }, 	 //	 452	 160
{ TN, SH, KN, SK, SK, TN, TN, WN, JA, KN, ST, TN, TN, JA, KN }, 	 //	 453	 160
{ TN, SH, KN, SK, SK, TN, TN, WN, QN, QN, ST, TN, TN, KN, QN }, 	 //	 454	 160
{ TN, SH, TN, QN, KN, TN, TN, TN, SK, SK, ST, TN, LO, JA, QN }, 	 //	 455	 160
{ TN, SH, TN, KN, KN, TN, TN, TN, KN, KN, ST, TN, LO, SK, SK }, 	 //	 456	 160
{ TN, SH, TN, KN, AC, TN, TN, TN, KN, AC, ST, TN, LO, SK, SK }, 	 //	 457	 160
{ TN, SH, SK, QN, QN, TN, TN, JA, SK, SH, ST, TN, TN, JA, JA }, 	 //	 458	 160
{ TN, SH, SK, QN, TN, TN, TN, JA, SK, ST, ST, TN, TN, JA, AC }, 	 //	 459	 160
{ TN, SH, SK, QN, KN, TN, TN, JA, SK, KN, ST, TN, TN, JA, CR }, 	 //	 460	 160
{ TN, SH, SK, QN, QN, TN, TN, JA, SK, KN, ST, TN, TN, JA, AC }, 	 //	 461	 160
{ TN, SH, SK, KN, KN, TN, TN, JA, SK, KN, ST, TN, TN, QN, KN }, 	 //	 462	 160
{ TN, SH, SK, SK, JA, TN, TN, JA, QN, JA, ST, TN, TN, KN, WN }, 	 //	 463	 160
{ TN, SH, SK, SK, KN, TN, TN, JA, QN, KN, ST, TN, TN, KN, CR }, 	 //	 464	 160
{ TN, SH, JA, QN, AC, TN, TN, TN, SK, SK, ST, TN, AC, JA, KN }, 	 //	 465	 160
{ TN, TN, KN, QN, SK, TN, TN, WN, SK, KN, ST, TN, TN, JA, KN }, 	 //	 466	 160
{ TN, TN, SK, QN, AC, TN, TN, JA, SK, AC, ST, TN, TN, JA, CR }, 	 //	 467	 160
{ TN, TN, SK, QN, QN, TN, TN, JA, SK, SH, ST, TN, TN, JA, JA }, 	 //	 468	 160
{ TN, TN, SK, QN, TN, TN, TN, JA, SK, AC, ST, TN, TN, JA, AC }, 	 //	 469	 160
{ TN, TN, SK, SK, AC, TN, TN, JA, JA, AC, ST, TN, TN, JA, CR }, 	 //	 470	 160
{ TN, TN, SK, SK, KN, TN, TN, JA, JA, KN, ST, TN, TN, JA, KN }, 	 //	 471	 160
{ TN, TN, SK, SK, AC, TN, TN, JA, JA, AC, ST, TN, TN, JA, SK }, 	 //	 472	 160
{ TN, TN, SK, SK, KN, TN, TN, JA, JA, AC, ST, TN, TN, JA, LO }, 	 //	 473	 160
{ TN, TN, SK, KN, ST, TN, TN, JA, SK, AC, ST, TN, TN, QN, KN }, 	 //	 474	 160
{ TN, TN, SK, KN, AC, TN, TN, JA, SK, KN, ST, TN, TN, QN, QN }, 	 //	 475	 160
{ TN, TN, SK, SK, LO, TN, TN, JA, QN, AC, ST, TN, TN, KN, AC }, 	 //	 476	 160
{ TN, TN, SK, SK, KN, TN, TN, JA, QN, KN, ST, TN, TN, KN, KN }, 	 //	 477	 160
{ TN, TN, SK, SK, TN, TN, TN, JA, QN, TN, ST, TN, TN, KN, ST }, 	 //	 478	 160
{ TN, TN, JA, QN, KN, TN, TN, TN, QN, KN, ST, TN, AC, SK, SK }, 	 //	 479	 160
{ TN, TN, JA, QN, AC, TN, TN, TN, QN, AC, ST, TN, AC, SK, SK }, 	 //	 480	 160
{ TN, TN, JA, KN, KN, TN, TN, TN, KN, KN, ST, TN, AC, SK, SK }, 	 //	 481	 160
{ TN, TN, JA, KN, AC, TN, TN, TN, KN, AC, ST, TN, AC, SK, SK }, 	 //	 482	 160
{ TN, TN, TN, SK, SK, TN, TN, AC, JA, QN, ST, TN, AC, JA, QN }, 	 //	 483	 160
{ TN, TN, TN, KN, AC, TN, TN, AC, KN, AC, ST, TN, AC, SK, SK }, 	 //	 484	 160
{ TN, TN, KN, KN, SK, TN, TN, WN, SK, KN, ST, WN, TN, QN, KN }, 	 //	 485	 160
{ TN, TN, TN, SK, SK, TN, TN, LO, QN, QN, ST, WN, JA, KN, QN }, 	 //	 486	 160
{ TN, TN, SK, QN, PF, TN, TN, JA, SK, JA, ST, WN, TN, JA, TN }, 	 //	 487	 160
{ TN, TN, SK, QN, TN, TN, TN, JA, SK, AC, ST, WN, TN, JA, AC }, 	 //	 488	 160
{ TN, TN, SK, SK, QN, TN, TN, JA, JA, QN, ST, WN, TN, JA, QN }, 	 //	 489	 160
{ TN, TN, SK, SK, TN, TN, TN, JA, JA, ST, ST, WN, TN, JA, AC }, 	 //	 490	 160
{ TN, TN, SK, SK, ST, TN, TN, JA, JA, AC, ST, WN, TN, JA, KN }, 	 //	 491	 160
{ TN, TN, SK, SK, KN, TN, TN, JA, JA, QN, ST, WN, TN, JA, PF }, 	 //	 492	 160
{ TN, TN, SK, SK, AC, TN, TN, JA, JA, AC, ST, WN, TN, JA, AC }, 	 //	 493	 160
{ TN, TN, SK, SK, CR, TN, TN, JA, JA, QN, ST, WN, TN, JA, KN }, 	 //	 494	 160
{ TN, TN, SK, SK, JA, TN, TN, JA, QN, WN, ST, WN, TN, KN, TN }, 	 //	 495	 160
{ TN, TN, SK, SK, ST, TN, TN, JA, QN, AC, ST, WN, TN, KN, KN }, 	 //	 496	 160
{ TN, TN, SK, SK, AC, TN, TN, JA, QN, KN, ST, WN, TN, KN, QN }, 	 //	 497	 160
{ TN, TN, JA, SK, SK, TN, TN, TN, JA, QN, ST, WN, AC, JA, QN }, 	 //	 498	 160
{ TN, TN, TN, QN, KN, TN, TN, AC, QN, KN, ST, WN, AC, SK, SK }, 	 //	 499	 160
{ TN, TN, TN, QN, AC, TN, TN, AC, SK, AC, ST, WN, AC, JA, SK }, 	 //	 500	 160
{ TN, TN, TN, KN, KN, TN, TN, AC, SK, KN, ST, WN, AC, QN, SK }, 	 //	 501	 160
{ TN, TN, TN, QN, AC, TN, WN, TN, SK, SK, ST, AC, TN, JA, KN }, 	 //	 502	 160
{ TN, TN, TN, SK, SK, TN, WN, TN, QN, QN, ST, AC, TN, KN, QN }, 	 //	 503	 160
{ TN, TN, TN, SK, SK, TN, WN, TN, QN, KN, ST, AC, TN, KN, KN }, 	 //	 504	 160
{ TN, TN, TN, QN, KN, TN, WN, TN, SK, SK, ST, AC, LO, JA, QN }, 	 //	 505	 160
{ TN, TN, TN, QN, KN, TN, WN, LO, QN, KN, ST, AC, JA, SK, SK }, 	 //	 506	 160
{ TN, TN, TN, KN, AC, TN, WN, LO, KN, AC, ST, AC, JA, SK, SK }, 	 //	 507	 160
{ TN, TN, TN, QN, KN, TN, WN, AC, SK, SK, ST, AC, AC, JA, QN }, 	 //	 508	 160
{ TN, JA, KN, SK, SK, TN, TN, WN, QN, QN, ST, AC, TN, KN, QN }, 	 //	 509	 160
{ TN, JA, TN, QN, KN, TN, TN, TN, QN, KN, ST, AC, LO, SK, SK }, 	 //	 510	 160
{ TN, JA, TN, QN, KN, TN, TN, TN, SK, KN, ST, AC, LO, JA, SK }, 	 //	 511	 160
{ TN, JA, SK, QN, CR, TN, TN, JA, SK, QN, ST, AC, TN, JA, KN }, 	 //	 512	 160
{ TN, JA, SK, KN, KN, TN, TN, JA, SK, KN, ST, AC, TN, QN, KN }, 	 //	 513	 160
{ TN, JA, SK, KN, KN, TN, TN, JA, SK, KN, ST, AC, TN, QN, CR }, 	 //	 514	 160
{ TN, JA, JA, QN, SK, TN, TN, TN, SK, KN, ST, AC, AC, JA, KN }, 	 //	 515	 160
{ TN, TN, TN, QN, KN, TN, AC, LO, SK, SK, ST, AC, JA, JA, QN }, 	 //	 516	 160
{ TN, TN, TN, SK, SK, TN, AC, LO, JA, QN, ST, AC, JA, JA, QN }, 	 //	 517	 160
{ TN, TN, TN, KN, AC, TN, AC, LO, SK, SK, ST, AC, JA, QN, KN }, 	 //	 518	 160
{ TN, SK, SK, JA, JA, TN, QN, JA, SH, WN, ST, KN, TN, TN, TN }, 	 //	 519	 160
{ TN, SK, SK, SH, WN, TN, QN, JA, TN, TN, ST, KN, TN, TN, TN }, 	 //	 520	 160
{ TN, SK, SK, TN, JA, TN, QN, JA, TN, WN, ST, KN, TN, TN, TN }, 	 //	 521	 160
{ TN, QN, SK, TN, WN, ST, SK, JA, TN, TN, AC, JA, TN, TN, TN }, 	 //	 522	 160
{ TN, SK, SK, TN, PF, ST, JA, JA, TN, JA, AC, JA, TN, TN, TN }, 	 //	 523	 160
{ TN, SK, SK, TN, TN, ST, JA, JA, TN, TN, AC, JA, TN, WN, ST }, 	 //	 524	 160
{ TN, SH, KN, QN, AC, ST, TN, WN, SK, SK, AC, TN, TN, JA, KN }, 	 //	 525	 160
{ TN, SH, KN, SK, SK, ST, TN, WN, QN, QN, AC, TN, TN, KN, QN }, 	 //	 526	 160
{ TN, SH, WN, QN, KN, ST, TN, TN, QN, KN, AC, TN, TN, SK, SK }, 	 //	 527	 160
{ TN, SH, WN, QN, KN, ST, TN, TN, SK, SK, AC, TN, TN, JA, QN }, 	 //	 528	 160
{ TN, SH, WN, QN, SK, ST, TN, TN, SK, QN, AC, TN, TN, JA, QN }, 	 //	 529	 160
{ TN, SH, WN, QN, AC, ST, TN, TN, SK, SK, AC, TN, TN, JA, KN }, 	 //	 530	 160
{ TN, SH, WN, SK, SK, ST, TN, TN, JA, QN, AC, TN, TN, JA, QN }, 	 //	 531	 160
{ TN, SH, WN, SK, SK, ST, TN, TN, JA, KN, AC, TN, TN, JA, KN }, 	 //	 532	 160
{ TN, SH, TN, QN, AC, ST, TN, TN, SK, AC, AC, TN, TN, JA, SK }, 	 //	 533	 160
{ TN, SH, TN, SK, SK, ST, TN, TN, QN, QN, AC, TN, TN, KN, QN }, 	 //	 534	 160
{ TN, SH, SK, QN, KN, ST, TN, JA, SK, KN, AC, TN, TN, JA, CR }, 	 //	 535	 160
{ TN, SH, SK, QN, QN, ST, TN, JA, SK, KN, AC, TN, TN, JA, AC }, 	 //	 536	 160
{ TN, SH, SK, SK, JA, ST, TN, JA, JA, WN, AC, TN, TN, JA, TN }, 	 //	 537	 160
{ TN, SH, SK, SK, QN, ST, TN, JA, JA, PF, AC, TN, TN, JA, JA }, 	 //	 538	 160
{ TN, SH, SK, KN, AC, ST, TN, JA, SK, AC, AC, TN, TN, QN, AC }, 	 //	 539	 160
{ TN, SH, SK, KN, KN, ST, TN, JA, SK, KN, AC, TN, TN, QN, KN }, 	 //	 540	 160
{ TN, SH, SK, SK, AC, ST, TN, JA, QN, AC, AC, TN, TN, KN, AC }, 	 //	 541	 160
{ TN, SH, SK, SK, KN, ST, TN, JA, QN, KN, AC, TN, TN, KN, KN }, 	 //	 542	 160
{ TN, SH, SK, SK, KN, ST, TN, JA, QN, AC, AC, TN, TN, KN, LO }, 	 //	 543	 160
{ TN, TN, WN, QN, SK, ST, TN, TN, SK, QN, AC, TN, TN, JA, QN }, 	 //	 544	 160
{ TN, TN, TN, KN, KN, ST, TN, TN, KN, KN, AC, TN, LO, SK, SK }, 	 //	 545	 160
{ TN, TN, TN, SK, SK, ST, TN, LO, JA, QN, AC, TN, JA, JA, QN }, 	 //	 546	 160
{ TN, TN, TN, KN, SK, ST, TN, LO, SK, QN, AC, TN, JA, QN, QN }, 	 //	 547	 160
{ TN, TN, SK, SK, AC, ST, TN, JA, JA, AC, AC, TN, TN, JA, AC }, 	 //	 548	 160
{ TN, TN, SK, SK, ST, ST, TN, JA, JA, AC, AC, TN, TN, JA, KN }, 	 //	 549	 160
{ TN, TN, SK, KN, AC, ST, TN, JA, SK, AC, AC, TN, TN, QN, CR }, 	 //	 550	 160
{ TN, TN, SK, SK, QN, ST, TN, JA, QN, QN, AC, TN, TN, KN, QN }, 	 //	 551	 160
{ TN, TN, SK, SK, QN, ST, TN, JA, QN, PF, AC, TN, TN, KN, JA }, 	 //	 552	 160
{ TN, TN, TN, SK, SK, ST, TN, AC, JA, KN, AC, TN, AC, JA, KN }, 	 //	 553	 160
{ TN, TN, KN, KN, AC, ST, TN, WN, SK, AC, AC, WN, TN, QN, SK }, 	 //	 554	 160
{ TN, TN, KN, SK, SK, ST, TN, WN, QN, KN, AC, WN, TN, KN, KN }, 	 //	 555	 160
{ TN, TN, WN, QN, SK, ST, TN, TN, SK, QN, AC, WN, TN, JA, QN }, 	 //	 556	 160
{ TN, TN, WN, KN, KN, ST, TN, TN, SK, SK, AC, WN, TN, QN, QN }, 	 //	 557	 160
{ TN, TN, WN, KN, SK, ST, TN, TN, SK, QN, AC, WN, TN, QN, QN }, 	 //	 558	 160
{ TN, TN, TN, QN, SK, ST, TN, TN, SK, QN, AC, WN, LO, JA, QN }, 	 //	 559	 160
{ TN, TN, TN, KN, SK, ST, TN, TN, SK, QN, AC, WN, LO, QN, QN }, 	 //	 560	 160
{ TN, TN, TN, QN, KN, ST, TN, LO, SK, SK, AC, WN, JA, JA, QN }, 	 //	 561	 160
{ TN, TN, SK, QN, LO, ST, TN, JA, SK, AC, AC, WN, TN, JA, AC }, 	 //	 562	 160
{ TN, TN, SK, QN, QN, ST, TN, JA, SK, SH, AC, WN, TN, JA, JA }, 	 //	 563	 160
{ TN, TN, SK, QN, TN, ST, TN, JA, SK, TN, AC, WN, TN, JA, TN }, 	 //	 564	 160
{ TN, TN, SK, QN, AC, ST, TN, JA, SK, KN, AC, WN, TN, JA, QN }, 	 //	 565	 160
{ TN, TN, SK, KN, TN, ST, TN, JA, SK, TN, AC, WN, TN, QN, TN }, 	 //	 566	 160
{ TN, TN, SK, KN, AC, ST, TN, JA, SK, AC, AC, WN, TN, QN, AC }, 	 //	 567	 160
{ TN, TN, SK, SK, AC, ST, TN, JA, QN, KN, AC, WN, TN, KN, QN }, 	 //	 568	 160
{ TN, TN, SK, SK, KN, ST, TN, JA, QN, AC, AC, WN, TN, KN, LO }, 	 //	 569	 160
{ TN, TN, TN, QN, KN, ST, TN, AC, SK, SK, AC, WN, AC, JA, QN }, 	 //	 570	 160
{ TN, TN, TN, QN, AC, ST, WN, TN, SK, SK, AC, AC, TN, JA, KN }, 	 //	 571	 160
{ TN, TN, TN, QN, SK, ST, WN, TN, SK, KN, AC, AC, TN, JA, KN }, 	 //	 572	 160
{ TN, TN, TN, KN, AC, ST, WN, TN, KN, AC, AC, AC, TN, SK, SK }, 	 //	 573	 160
{ TN, TN, TN, QN, SK, ST, WN, LO, SK, QN, AC, AC, JA, JA, QN }, 	 //	 574	 160
{ TN, TN, TN, SK, SK, ST, WN, LO, QN, QN, AC, AC, JA, KN, QN }, 	 //	 575	 160
{ TN, JA, KN, QN, SK, ST, TN, WN, SK, QN, AC, AC, TN, JA, QN }, 	 //	 576	 160
{ TN, JA, KN, KN, SK, ST, TN, WN, SK, QN, AC, AC, TN, QN, QN }, 	 //	 577	 160
{ TN, JA, TN, KN, KN, ST, TN, TN, KN, KN, AC, AC, TN, SK, SK }, 	 //	 578	 160
{ TN, JA, SK, QN, AC, ST, TN, JA, QN, AC, AC, AC, TN, SK, SK }, 	 //	 579	 160
{ TN, JA, SK, KN, AC, ST, TN, JA, KN, AC, AC, AC, TN, SK, SK }, 	 //	 580	 160
{ TN, JA, SK, KN, AC, ST, TN, JA, SK, AC, AC, AC, TN, QN, CR }, 	 //	 581	 160
{ TN, JA, SK, KN, SH, ST, TN, JA, SK, JA, AC, AC, TN, QN, JA }, 	 //	 582	 160
{ TN, JA, SK, SK, QN, ST, TN, JA, QN, QN, AC, AC, TN, KN, SH }, 	 //	 583	 160
{ TN, JA, SK, SK, JA, ST, TN, JA, QN, WN, AC, AC, TN, KN, TN }, 	 //	 584	 160
{ TN, TN, TN, KN, KN, ST, AC, TN, SK, SK, AC, AC, TN, QN, QN }, 	 //	 585	 160
{ TN, KN, SK, TN, PF, ST, SK, JA, TN, JA, AC, QN, TN, TN, TN }, 	 //	 586	 160
{ TN, KN, SK, TN, TN, ST, SK, JA, TN, TN, AC, QN, TN, WN, ST }, 	 //	 587	 160
{ TN, SK, SK, JA, PF, ST, QN, JA, SH, JA, AC, KN, TN, TN, TN }, 	 //	 588	 160
{ TN, SK, SK, SH, JA, ST, QN, JA, TN, WN, AC, KN, TN, TN, TN }, 	 //	 589	 160
{ TN, SK, SK, ST, TN, ST, QN, JA, JA, TN, AC, KN, TN, TN, TN }, 	 //	 590	 160
{ ST, QN, SK, JA, JA, AC, SK, JA, SH, WN, KN, JA, TN, TN, TN }, 	 //	 591	 160
{ ST, QN, SK, SH, JA, AC, SK, JA, TN, WN, KN, JA, TN, TN, TN }, 	 //	 592	 160
{ ST, QN, SK, SH, TN, AC, SK, JA, TN, ST, KN, JA, TN, TN, AC }, 	 //	 593	 160
{ ST, QN, SK, TN, JA, AC, SK, JA, TN, WN, KN, JA, TN, TN, TN }, 	 //	 594	 160
{ ST, QN, SK, TN, TN, AC, SK, JA, TN, AC, KN, JA, TN, TN, AC }, 	 //	 595	 160
{ ST, SK, SK, SH, TN, AC, JA, JA, TN, AC, KN, JA, TN, TN, AC }, 	 //	 596	 160
{ ST, SK, SK, TN, TN, AC, JA, JA, TN, ST, KN, JA, TN, WN, AC }, 	 //	 597	 160
{ ST, KN, SK, SH, TN, AC, SK, JA, TN, TN, KN, QN, TN, TN, ST }, 	 //	 598	 160
{ ST, KN, SK, TN, WN, AC, SK, JA, TN, TN, KN, QN, TN, TN, TN }, 	 //	 599	 160
{ ST, SK, SK, SH, TN, AC, QN, JA, TN, ST, KN, KN, TN, TN, AC }, 	 //	 600	 160
{ ST, SK, SK, TN, WN, AC, QN, JA, TN, TN, KN, KN, TN, TN, TN }, 	 //	 601	 160
{ ST, SK, SK, TN, TN, AC, QN, JA, TN, AC, KN, KN, TN, WN, AC }, 	 //	 602	 160
{ AC, QN, SK, TN, TN, KN, SK, JA, TN, ST, QN, JA, TN, TN, AC }, 	 //	 603	 160
{ AC, SK, SK, SH, PF, KN, JA, JA, TN, JA, QN, JA, TN, TN, TN }, 	 //	 604	 160
{ AC, KN, SK, JA, WN, KN, SK, JA, SH, TN, QN, QN, TN, TN, TN }, 	 //	 605	 160
{ KN, SK, SK, TN, WN, QN, JA, JA, TN, TN, PF, JA, TN, TN, TN }, 	 //	 606	 160
{ KN, SK, SK, TN, TN, QN, JA, JA, TN, ST, PF, JA, TN, TN, AC }, 	 //	 607	 160
{ KN, KN, SK, TN, TN, QN, SK, JA, TN, TN, PF, QN, TN, TN, ST }, 	 //	 608	 160
{ KN, KN, SK, JA, TN, QN, SK, JA, TN, ST, PF, QN, TN, AC, AC }, 	 //	 609	 160
{ KN, SK, SK, TN, WN, QN, QN, JA, TN, TN, PF, KN, TN, TN, TN }, 	 //	 610	 160
{ KN, SK, SK, ST, TN, QN, QN, JA, JA, TN, PF, KN, TN, TN, TN }, 	 //	 611	 160
{ QN, QN, SK, TN, JA, PF, SK, JA, TN, WN, JA, JA, TN, TN, TN }, 	 //	 612	 160
{ QN, QN, SK, TN, TN, PF, SK, JA, TN, AC, JA, JA, TN, TN, AC }, 	 //	 613	 160
{ QN, QN, SK, JA, TN, PF, SK, JA, TN, TN, JA, JA, TN, AC, ST }, 	 //	 614	 160
{ QN, SK, SK, JA, WN, PF, JA, JA, SH, TN, JA, JA, TN, TN, TN }, 	 //	 615	 160
{ QN, SK, SK, TN, TN, PF, JA, JA, TN, ST, JA, JA, TN, WN, AC }, 	 //	 616	 160
{ QN, SK, SK, JA, TN, PF, JA, JA, TN, ST, JA, JA, TN, AC, AC }, 	 //	 617	 160
{ QN, KN, SK, TN, TN, PF, SK, JA, TN, ST, JA, QN, TN, TN, AC }, 	 //	 618	 160
{ QN, SK, SK, SH, WN, PF, QN, JA, TN, TN, JA, KN, TN, TN, TN }, 	 //	 619	 160
{ QN, SK, SK, SH, PF, PF, QN, JA, TN, JA, JA, KN, TN, TN, TN }, 	 //	 620	 160
{ QN, SK, SK, TN, WN, PF, QN, JA, TN, TN, JA, KN, TN, TN, TN }, 	 //	 621	 160
{ QN, SK, SK, TN, TN, PF, QN, JA, TN, ST, JA, KN, TN, TN, AC }, 	 //	 622	 160
{ PF, JA, WN, QN, SK, JA, SH, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 623	 160
{ PF, JA, TN, QN, SK, JA, SH, TN, SK, QN, TN, TN, TN, JA, QN }, 	 //	 624	 160
{ PF, JA, TN, KN, KN, JA, SH, TN, SK, SK, TN, TN, TN, QN, QN }, 	 //	 625	 160
{ PF, JA, SK, QN, CR, JA, SH, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 626	 160
{ PF, JA, SK, QN, KN, JA, SH, JA, SK, KN, TN, TN, TN, JA, KN }, 	 //	 627	 160
{ PF, JA, SK, QN, JA, JA, SH, JA, SK, WN, TN, TN, TN, JA, TN }, 	 //	 628	 160
{ PF, JA, SK, QN, TN, JA, SH, JA, SK, TN, TN, TN, TN, JA, ST }, 	 //	 629	 160
{ PF, JA, SK, SK, AC, JA, SH, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 630	 160
{ PF, JA, SK, SK, TN, JA, SH, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 631	 160
{ PF, JA, SK, SK, CR, JA, SH, JA, JA, QN, TN, TN, TN, JA, KN }, 	 //	 632	 160
{ PF, JA, SK, KN, JA, JA, SH, JA, SK, WN, TN, TN, TN, QN, TN }, 	 //	 633	 160
{ PF, JA, SK, KN, QN, JA, SH, JA, SK, PF, TN, TN, TN, QN, JA }, 	 //	 634	 160
{ PF, JA, SK, KN, JA, JA, SH, JA, SK, TN, TN, TN, TN, QN, AC }, 	 //	 635	 160
{ PF, JA, SK, SK, JA, JA, SH, JA, QN, JA, TN, TN, TN, KN, WN }, 	 //	 636	 160
{ PF, SH, KN, QN, KN, JA, TN, WN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 637	 160
{ PF, SH, TN, QN, SK, JA, TN, TN, SK, KN, TN, TN, LO, JA, KN }, 	 //	 638	 160
{ PF, SH, TN, KN, KN, JA, TN, TN, KN, KN, TN, TN, LO, SK, SK }, 	 //	 639	 160
{ PF, SH, TN, KN, AC, JA, TN, TN, KN, AC, TN, TN, LO, SK, SK }, 	 //	 640	 160
{ PF, SH, SK, QN, JA, JA, TN, JA, SK, JA, TN, TN, TN, JA, JA }, 	 //	 641	 160
{ PF, SH, SK, QN, TN, JA, TN, JA, SK, TN, TN, TN, TN, JA, ST }, 	 //	 642	 160
{ PF, SH, SK, QN, AC, JA, TN, JA, SK, KN, TN, TN, TN, JA, QN }, 	 //	 643	 160
{ PF, SH, SK, SK, AC, JA, TN, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 644	 160
{ PF, SH, SK, SK, QN, JA, TN, JA, JA, QN, TN, TN, TN, JA, SH }, 	 //	 645	 160
{ PF, SH, SK, KN, AC, JA, TN, JA, SK, AC, TN, TN, TN, QN, CR }, 	 //	 646	 160
{ PF, SH, SK, KN, AC, JA, TN, JA, SK, AC, TN, TN, TN, QN, AC }, 	 //	 647	 160
{ PF, SH, SK, SK, TN, JA, TN, JA, QN, AC, TN, TN, TN, KN, AC }, 	 //	 648	 160
{ PF, SH, SK, SK, AC, JA, TN, JA, QN, AC, TN, TN, TN, KN, SK }, 	 //	 649	 160
{ PF, SH, SK, SK, QN, JA, TN, JA, QN, KN, TN, TN, TN, KN, AC }, 	 //	 650	 160
{ PF, SH, TN, SK, SK, JA, TN, AC, QN, QN, TN, TN, AC, KN, QN }, 	 //	 651	 160
{ PF, TN, KN, QN, SK, JA, TN, WN, SK, KN, TN, TN, TN, JA, KN }, 	 //	 652	 160
{ PF, TN, WN, KN, SK, JA, TN, TN, SK, QN, TN, TN, TN, QN, QN }, 	 //	 653	 160
{ PF, TN, TN, KN, SK, JA, TN, LO, SK, QN, TN, TN, JA, QN, QN }, 	 //	 654	 160
{ PF, TN, SK, QN, AC, JA, TN, JA, SK, AC, TN, TN, TN, JA, CR }, 	 //	 655	 160
{ PF, TN, SK, SK, AC, JA, TN, JA, JA, LO, TN, TN, TN, JA, AC }, 	 //	 656	 160
{ PF, TN, SK, SK, KN, JA, TN, JA, JA, SK, TN, TN, TN, JA, QN }, 	 //	 657	 160
{ PF, TN, SK, SK, TN, JA, TN, JA, JA, TN, TN, TN, TN, JA, ST }, 	 //	 658	 160
{ PF, TN, SK, SK, QN, JA, TN, JA, JA, PF, TN, TN, TN, JA, JA }, 	 //	 659	 160
{ PF, TN, SK, SK, KN, JA, TN, JA, JA, KN, TN, TN, TN, JA, KN }, 	 //	 660	 160
{ PF, TN, SK, SK, KN, JA, TN, JA, JA, AC, TN, TN, TN, JA, LO }, 	 //	 661	 160
{ PF, TN, TN, QN, KN, JA, TN, AC, SK, KN, TN, TN, AC, JA, SK }, 	 //	 662	 160
{ PF, TN, TN, QN, SK, JA, TN, AC, SK, KN, TN, TN, AC, JA, KN }, 	 //	 663	 160
{ PF, TN, TN, KN, KN, JA, TN, AC, SK, SK, TN, TN, AC, QN, QN }, 	 //	 664	 160
{ PF, TN, TN, KN, SK, JA, TN, AC, SK, QN, TN, TN, AC, QN, QN }, 	 //	 665	 160
{ PF, TN, TN, KN, AC, JA, TN, AC, SK, SK, TN, TN, AC, QN, KN }, 	 //	 666	 160
{ PF, TN, TN, KN, KN, JA, TN, TN, KN, KN, TN, WN, TN, SK, SK }, 	 //	 667	 160
{ PF, TN, TN, QN, SK, JA, TN, TN, SK, QN, TN, WN, LO, JA, QN }, 	 //	 668	 160
{ PF, TN, TN, KN, KN, JA, TN, TN, SK, SK, TN, WN, LO, QN, QN }, 	 //	 669	 160
{ PF, TN, TN, SK, SK, JA, TN, TN, QN, QN, TN, WN, LO, KN, QN }, 	 //	 670	 160
{ PF, TN, TN, KN, SK, JA, TN, LO, SK, QN, TN, WN, JA, QN, QN }, 	 //	 671	 160
{ PF, TN, TN, KN, AC, JA, TN, LO, SK, SK, TN, WN, JA, QN, KN }, 	 //	 672	 160
{ PF, TN, TN, QN, AC, JA, TN, AC, QN, AC, TN, WN, AC, SK, SK }, 	 //	 673	 160
{ PF, TN, TN, QN, AC, JA, TN, AC, SK, SK, TN, WN, AC, JA, KN }, 	 //	 674	 160
{ PF, ST, KN, QN, KN, JA, JA, WN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 675	 160
{ PF, ST, KN, QN, AC, JA, JA, WN, SK, AC, TN, TN, TN, JA, SK }, 	 //	 676	 160
{ PF, ST, WN, QN, AC, JA, JA, TN, QN, AC, TN, TN, TN, SK, SK }, 	 //	 677	 160
{ PF, ST, WN, SK, SK, JA, JA, TN, JA, KN, TN, TN, TN, JA, KN }, 	 //	 678	 160
{ PF, ST, WN, KN, KN, JA, JA, TN, KN, KN, TN, TN, TN, SK, SK }, 	 //	 679	 160
{ PF, ST, TN, QN, KN, JA, JA, TN, SK, KN, TN, TN, TN, JA, SK }, 	 //	 680	 160
{ PF, ST, TN, QN, KN, JA, JA, TN, SK, SK, TN, TN, TN, JA, QN }, 	 //	 681	 160
{ PF, ST, TN, SK, SK, JA, JA, TN, QN, QN, TN, TN, TN, KN, QN }, 	 //	 682	 160
{ PF, JA, TN, SK, SK, JA, TN, TN, JA, KN, TN, AC, LO, JA, KN }, 	 //	 683	 160
{ PF, JA, TN, KN, AC, JA, TN, LO, SK, AC, TN, AC, JA, QN, SK }, 	 //	 684	 160
{ PF, JA, TN, QN, AC, JA, TN, AC, SK, SK, TN, AC, AC, JA, KN }, 	 //	 685	 160
{ PF, JA, TN, KN, SK, JA, TN, AC, SK, KN, TN, AC, AC, QN, KN }, 	 //	 686	 160
{ PF, JA, TN, SK, SK, JA, TN, AC, QN, QN, TN, AC, AC, KN, QN }, 	 //	 687	 160
{ PF, KN, SK, SH, PF, JA, SK, JA, TN, JA, TN, QN, TN, TN, TN }, 	 //	 688	 160
{ PF, KN, SK, TN, JA, JA, SK, JA, TN, WN, TN, QN, TN, TN, TN }, 	 //	 689	 160
{ PF, SK, SK, JA, TN, JA, QN, JA, SH, TN, TN, KN, TN, TN, TN }, 	 //	 690	 160
{ PF, SK, SK, SH, TN, JA, QN, JA, TN, TN, TN, KN, TN, TN, ST }, 	 //	 691	 160
{ PF, SK, SK, ST, WN, JA, QN, JA, JA, TN, TN, KN, TN, TN, TN }, 	 //	 692	 160
{ JA, QN, SK, SH, TN, TN, SK, JA, TN, ST, AC, JA, TN, TN, AC }, 	 //	 693	 160
{ JA, QN, SK, TN, TN, TN, SK, JA, TN, AC, AC, JA, TN, WN, AC }, 	 //	 694	 160
{ JA, SK, SK, JA, JA, TN, JA, JA, SH, WN, AC, JA, TN, TN, TN }, 	 //	 695	 160
{ JA, SK, SK, SH, TN, TN, JA, JA, TN, TN, AC, JA, TN, TN, ST }, 	 //	 696	 160
{ JA, SK, SK, TN, WN, TN, JA, JA, TN, TN, AC, JA, TN, TN, TN }, 	 //	 697	 160
{ JA, SK, SK, JA, TN, TN, JA, JA, TN, TN, AC, JA, TN, AC, TN }, 	 //	 698	 160
{ JA, SH, WN, QN, AC, TN, TN, TN, SK, AC, AC, TN, TN, JA, SK }, 	 //	 699	 160
{ JA, SH, WN, SK, SK, TN, TN, TN, JA, KN, AC, TN, TN, JA, KN }, 	 //	 700	 160
{ JA, SH, WN, KN, KN, TN, TN, TN, SK, SK, AC, TN, TN, QN, QN }, 	 //	 701	 160
{ JA, SH, WN, KN, SK, TN, TN, TN, SK, KN, AC, TN, TN, QN, KN }, 	 //	 702	 160
{ JA, SH, TN, QN, AC, TN, TN, TN, SK, AC, AC, TN, TN, JA, SK }, 	 //	 703	 160
{ JA, SH, TN, SK, SK, TN, TN, TN, QN, QN, AC, TN, TN, KN, QN }, 	 //	 704	 160
{ JA, SH, TN, SK, SK, TN, TN, TN, QN, KN, AC, TN, TN, KN, KN }, 	 //	 705	 160
{ JA, SH, JA, SK, SK, TN, TN, TN, QN, KN, AC, TN, AC, KN, KN }, 	 //	 706	 160
{ JA, TN, WN, QN, KN, TN, TN, TN, SK, KN, AC, TN, TN, JA, SK }, 	 //	 707	 160
{ JA, TN, TN, QN, AC, TN, TN, TN, SK, SK, AC, TN, LO, JA, KN }, 	 //	 708	 160
{ JA, TN, TN, QN, SK, TN, TN, TN, SK, KN, AC, TN, LO, JA, KN }, 	 //	 709	 160
{ JA, TN, TN, KN, AC, TN, TN, TN, KN, AC, AC, TN, LO, SK, SK }, 	 //	 710	 160
{ JA, TN, TN, SK, SK, TN, TN, TN, QN, KN, AC, TN, LO, KN, KN }, 	 //	 711	 160
{ JA, TN, JA, SK, SK, TN, TN, TN, JA, KN, AC, TN, AC, JA, KN }, 	 //	 712	 160
{ JA, TN, WN, QN, KN, TN, TN, TN, QN, KN, AC, WN, TN, SK, SK }, 	 //	 713	 160
{ JA, TN, WN, QN, SK, TN, TN, TN, SK, QN, AC, WN, TN, JA, QN }, 	 //	 714	 160
{ JA, TN, WN, SK, SK, TN, TN, TN, JA, QN, AC, WN, TN, JA, QN }, 	 //	 715	 160
{ JA, TN, TN, KN, KN, TN, TN, TN, KN, KN, AC, WN, TN, SK, SK }, 	 //	 716	 160
{ JA, TN, TN, QN, SK, TN, TN, TN, SK, KN, AC, WN, LO, JA, KN }, 	 //	 717	 160
{ JA, TN, TN, KN, AC, TN, TN, TN, SK, AC, AC, WN, LO, QN, SK }, 	 //	 718	 160
{ JA, TN, JA, KN, SK, TN, TN, TN, SK, QN, AC, WN, AC, QN, QN }, 	 //	 719	 160
{ JA, JA, WN, KN, KN, TN, TN, TN, SK, SK, AC, AC, TN, QN, QN }, 	 //	 720	 160
{ JA, JA, TN, SK, SK, TN, TN, TN, JA, QN, AC, AC, LO, JA, QN }, 	 //	 721	 160
{ JA, KN, SK, JA, TN, TN, SK, JA, SH, TN, AC, QN, TN, TN, TN }, 	 //	 722	 160
{ JA, KN, SK, SH, TN, TN, SK, JA, TN, TN, AC, QN, TN, TN, ST }, 	 //	 723	 160
{ JA, KN, SK, TN, TN, TN, SK, JA, TN, TN, AC, QN, TN, WN, ST }, 	 //	 724	 160
{ JA, KN, SK, ST, WN, TN, SK, JA, JA, TN, AC, QN, TN, TN, TN }, 	 //	 725	 160
{ TN, QN, SK, SH, TN, AC, SK, JA, TN, ST, AC, JA, TN, TN, AC }, 	 //	 726	 160
{ TN, QN, SK, SH, PF, AC, SK, JA, TN, JA, AC, JA, TN, TN, TN }, 	 //	 727	 160
{ TN, QN, SK, ST, TN, AC, SK, JA, JA, TN, AC, JA, TN, TN, TN }, 	 //	 728	 160
{ TN, SK, SK, SH, PF, AC, JA, JA, TN, JA, AC, JA, TN, TN, TN }, 	 //	 729	 160
{ TN, SK, SK, TN, TN, AC, JA, JA, TN, ST, AC, JA, TN, TN, AC }, 	 //	 730	 160
{ TN, SH, WN, QN, KN, AC, TN, TN, SK, SK, AC, TN, TN, JA, QN }, 	 //	 731	 160
{ TN, SH, WN, QN, AC, AC, TN, TN, SK, SK, AC, TN, TN, JA, KN }, 	 //	 732	 160
{ TN, SH, TN, QN, KN, AC, TN, TN, QN, KN, AC, TN, TN, SK, SK }, 	 //	 733	 160
{ TN, SH, TN, KN, KN, AC, TN, TN, SK, SK, AC, TN, TN, QN, QN }, 	 //	 734	 160
{ TN, SH, SK, QN, KN, AC, TN, JA, SK, AC, AC, TN, TN, JA, LO }, 	 //	 735	 160
{ TN, SH, SK, SK, AC, AC, TN, JA, JA, AC, AC, TN, TN, JA, SK }, 	 //	 736	 160
{ TN, SH, SK, KN, KN, AC, TN, JA, KN, KN, AC, TN, TN, SK, SK }, 	 //	 737	 160
{ TN, SH, SK, KN, JA, AC, TN, JA, SK, JA, AC, TN, TN, QN, WN }, 	 //	 738	 160
{ TN, SH, SK, KN, WN, AC, TN, JA, SK, TN, AC, TN, TN, QN, TN }, 	 //	 739	 160
{ TN, SH, SK, KN, KN, AC, TN, JA, SK, KN, AC, TN, TN, QN, CR }, 	 //	 740	 160
{ TN, SH, SK, SK, AC, AC, TN, JA, QN, LO, AC, TN, TN, KN, AC }, 	 //	 741	 160
{ TN, SH, SK, SK, TN, AC, TN, JA, QN, TN, AC, TN, TN, KN, TN }, 	 //	 742	 160
{ TN, SH, SK, SK, TN, AC, TN, JA, QN, ST, AC, TN, TN, KN, AC }, 	 //	 743	 160
{ TN, SH, SK, SK, TN, AC, TN, JA, QN, AC, AC, TN, TN, KN, AC }, 	 //	 744	 160
{ TN, TN, WN, QN, KN, AC, TN, TN, QN, KN, AC, TN, TN, SK, SK }, 	 //	 745	 160
{ TN, TN, WN, KN, KN, AC, TN, TN, SK, SK, AC, TN, TN, QN, QN }, 	 //	 746	 160
{ TN, TN, TN, QN, SK, AC, TN, LO, SK, KN, AC, TN, JA, JA, KN }, 	 //	 747	 160
{ TN, TN, TN, SK, SK, AC, TN, LO, JA, QN, AC, TN, JA, JA, QN }, 	 //	 748	 160
{ TN, TN, SK, SK, QN, AC, TN, JA, JA, QN, AC, TN, TN, JA, SH }, 	 //	 749	 160
{ TN, TN, SK, SK, KN, AC, TN, JA, JA, QN, AC, TN, TN, JA, PF }, 	 //	 750	 160
{ TN, TN, SK, SK, CR, AC, TN, JA, JA, QN, AC, TN, TN, JA, KN }, 	 //	 751	 160
{ TN, TN, SK, KN, KN, AC, TN, JA, KN, KN, AC, TN, TN, SK, SK }, 	 //	 752	 160
{ TN, TN, SK, KN, PF, AC, TN, JA, SK, JA, AC, TN, TN, QN, TN }, 	 //	 753	 160
{ TN, TN, SK, KN, KN, AC, TN, JA, SK, KN, AC, TN, TN, QN, CR }, 	 //	 754	 160
{ TN, TN, SK, KN, QN, AC, TN, JA, SK, KN, AC, TN, TN, QN, AC }, 	 //	 755	 160
{ TN, TN, SK, KN, KN, AC, TN, JA, SK, AC, AC, TN, TN, QN, LO }, 	 //	 756	 160
{ TN, TN, SK, SK, SH, AC, TN, JA, QN, JA, AC, TN, TN, KN, JA }, 	 //	 757	 160
{ TN, TN, SK, SK, CR, AC, TN, JA, QN, QN, AC, TN, TN, KN, KN }, 	 //	 758	 160
{ TN, TN, SK, SK, KN, AC, TN, JA, QN, AC, AC, TN, TN, KN, LO }, 	 //	 759	 160
{ TN, TN, KN, QN, AC, AC, TN, WN, SK, AC, AC, WN, TN, JA, SK }, 	 //	 760	 160
{ TN, TN, KN, KN, AC, AC, TN, WN, KN, AC, AC, WN, TN, SK, SK }, 	 //	 761	 160
{ TN, TN, KN, KN, AC, AC, TN, WN, SK, SK, AC, WN, TN, QN, KN }, 	 //	 762	 160
{ TN, TN, WN, QN, AC, AC, TN, TN, SK, SK, AC, WN, TN, JA, KN }, 	 //	 763	 160
{ TN, TN, WN, SK, SK, AC, TN, TN, JA, KN, AC, WN, TN, JA, KN }, 	 //	 764	 160
{ TN, TN, TN, QN, SK, AC, TN, TN, SK, KN, AC, WN, LO, JA, KN }, 	 //	 765	 160
{ TN, TN, TN, KN, AC, AC, TN, TN, SK, AC, AC, WN, LO, QN, SK }, 	 //	 766	 160
{ TN, TN, TN, QN, KN, AC, TN, LO, SK, SK, AC, WN, JA, JA, QN }, 	 //	 767	 160
{ TN, TN, TN, QN, AC, AC, TN, LO, SK, SK, AC, WN, JA, JA, KN }, 	 //	 768	 160
{ TN, TN, TN, KN, KN, AC, TN, LO, SK, KN, AC, WN, JA, QN, SK }, 	 //	 769	 160
{ TN, TN, TN, SK, SK, AC, TN, LO, QN, KN, AC, WN, JA, KN, KN }, 	 //	 770	 160
{ TN, TN, SK, QN, AC, AC, TN, JA, SK, AC, AC, WN, TN, JA, AC }, 	 //	 771	 160
{ TN, TN, SK, QN, WN, AC, TN, JA, SK, TN, AC, WN, TN, JA, TN }, 	 //	 772	 160
{ TN, TN, SK, SK, AC, AC, TN, JA, JA, AC, AC, WN, TN, JA, CR }, 	 //	 773	 160
{ TN, TN, SK, KN, KN, AC, TN, JA, KN, KN, AC, WN, TN, SK, SK }, 	 //	 774	 160
{ TN, TN, SK, KN, AC, AC, TN, JA, SK, AC, AC, WN, TN, QN, CR }, 	 //	 775	 160
{ TN, TN, SK, KN, JA, AC, TN, JA, SK, JA, AC, WN, TN, QN, JA }, 	 //	 776	 160
{ TN, TN, SK, SK, JA, AC, TN, JA, QN, JA, AC, WN, TN, KN, JA }, 	 //	 777	 160
{ TN, TN, TN, QN, SK, AC, TN, AC, SK, KN, AC, WN, AC, JA, KN }, 	 //	 778	 160
{ TN, TN, TN, SK, SK, AC, WN, TN, QN, KN, AC, AC, TN, KN, KN }, 	 //	 779	 160
{ TN, TN, TN, KN, KN, AC, WN, TN, KN, KN, AC, AC, LO, SK, SK }, 	 //	 780	 160
{ TN, TN, TN, SK, SK, AC, WN, LO, QN, KN, AC, AC, JA, KN, KN }, 	 //	 781	 160
{ TN, JA, WN, SK, SK, AC, TN, TN, JA, QN, AC, AC, TN, JA, QN }, 	 //	 782	 160
{ TN, JA, WN, SK, SK, AC, TN, TN, JA, KN, AC, AC, TN, JA, KN }, 	 //	 783	 160
{ TN, JA, TN, KN, AC, AC, TN, TN, KN, AC, AC, AC, TN, SK, SK }, 	 //	 784	 160
{ TN, JA, TN, KN, KN, AC, TN, TN, SK, KN, AC, AC, TN, QN, SK }, 	 //	 785	 160
{ TN, JA, SK, QN, JA, AC, TN, JA, SK, JA, AC, AC, TN, JA, WN }, 	 //	 786	 160
{ TN, JA, SK, QN, AC, AC, TN, JA, SK, KN, AC, AC, TN, JA, QN }, 	 //	 787	 160
{ TN, JA, SK, QN, QN, AC, TN, JA, SK, KN, AC, AC, TN, JA, AC }, 	 //	 788	 160
{ TN, JA, SK, SK, JA, AC, TN, JA, JA, TN, AC, AC, TN, JA, AC }, 	 //	 789	 160
{ TN, JA, SK, SK, AC, AC, TN, JA, JA, AC, AC, AC, TN, JA, SK }, 	 //	 790	 160
{ TN, JA, SK, SK, QN, AC, TN, JA, QN, QN, AC, AC, TN, KN, SH }, 	 //	 791	 160
{ TN, JA, SK, SK, JA, AC, TN, JA, QN, JA, AC, AC, TN, KN, JA }, 	 //	 792	 160
{ TN, JA, SK, SK, WN, AC, TN, JA, QN, TN, AC, AC, TN, KN, TN }, 	 //	 793	 160
{ TN, JA, SK, SK, ST, AC, TN, JA, QN, AC, AC, AC, TN, KN, KN }, 	 //	 794	 160
{ TN, JA, SK, SK, KN, AC, TN, JA, QN, AC, AC, AC, TN, KN, LO }, 	 //	 795	 160
{ TN, TN, TN, QN, AC, AC, AC, TN, SK, AC, AC, AC, TN, JA, SK }, 	 //	 796	 160
{ TN, TN, TN, QN, AC, AC, AC, TN, SK, SK, AC, AC, TN, JA, KN }, 	 //	 797	 160
{ TN, TN, TN, SK, SK, AC, AC, TN, JA, KN, AC, AC, TN, JA, KN }, 	 //	 798	 160
{ TN, TN, TN, KN, KN, AC, AC, TN, KN, KN, AC, AC, TN, SK, SK }, 	 //	 799	 160
{ TN, TN, TN, KN, KN, AC, AC, TN, SK, SK, AC, AC, TN, QN, QN }, 	 //	 800	 160
{ TN, SK, SK, TN, JA, AC, QN, JA, TN, WN, AC, KN, TN, TN, TN }, 	 //	 801	 160
{ TN, SK, SK, TN, TN, AC, QN, JA, TN, ST, AC, KN, TN, TN, AC }, 	 //	 802	 160
{ AC, SK, SK, JA, TN, AC, JA, JA, TN, AC, AC, JA, TN, AC, AC }, 	 //	 803	 160
{ AC, KN, SK, JA, TN, AC, SK, JA, SH, TN, AC, QN, TN, TN, TN }, 	 //	 804	 160
{ AC, KN, SK, SH, JA, AC, SK, JA, TN, WN, AC, QN, TN, TN, TN }, 	 //	 805	 160
{ AC, KN, SK, TN, JA, AC, SK, JA, TN, WN, AC, QN, TN, TN, TN }, 	 //	 806	 160
{ AC, KN, SK, TN, TN, AC, SK, JA, TN, TN, AC, QN, TN, WN, TN }, 	 //	 807	 160
{ AC, SK, SK, JA, TN, AC, QN, JA, SH, TN, AC, KN, TN, TN, TN }, 	 //	 808	 160
{ AC, SK, SK, ST, TN, AC, QN, JA, JA, TN, AC, KN, TN, TN, TN }, 	 //	 809	 160
{ AC, SK, SK, JA, TN, AC, QN, JA, TN, ST, AC, KN, TN, AC, AC }, 	 //	 810	 160
{ AC, QN, KN, JA, TN, AC, QN, WN, SH, TN, SK, SK, TN, TN, TN }, 	 //	 811	 160
{ AC, QN, KN, TN, JA, AC, QN, WN, TN, WN, SK, SK, TN, TN, TN }, 	 //	 812	 160
{ AC, QN, WN, SH, TN, AC, QN, TN, TN, ST, SK, SK, TN, TN, AC }, 	 //	 813	 160
{ AC, QN, TN, JA, PF, AC, QN, TN, SH, JA, SK, SK, TN, TN, TN }, 	 //	 814	 160
{ AC, QN, TN, SH, JA, AC, QN, TN, TN, TN, SK, SK, LO, TN, AC }, 	 //	 815	 160
{ AC, QN, TN, TN, TN, AC, QN, TN, AC, TN, SK, SK, LO, AC, TN }, 	 //	 816	 160
{ AC, QN, TN, TN, TN, AC, QN, LO, TN, TN, SK, SK, JA, WN, ST }, 	 //	 817	 160
{ AC, QN, TN, JA, PF, AC, QN, LO, TN, JA, SK, SK, JA, AC, TN }, 	 //	 818	 160
{ AC, QN, SK, TN, WN, AC, QN, JA, TN, TN, SK, SK, TN, TN, TN }, 	 //	 819	 160
{ AC, QN, JA, TN, TN, AC, QN, TN, TN, TN, SK, SK, AC, TN, ST }, 	 //	 820	 160
{ AC, QN, TN, SH, JA, AC, QN, AC, TN, WN, SK, SK, AC, TN, TN }, 	 //	 821	 160
{ AC, QN, TN, SH, WN, AC, QN, AC, TN, TN, SK, SK, AC, TN, TN }, 	 //	 822	 160
{ AC, QN, KN, JA, TN, AC, SK, WN, TN, TN, SK, JA, TN, AC, ST }, 	 //	 823	 160
{ AC, QN, KN, JA, TN, AC, SK, WN, TN, AC, SK, JA, TN, AC, AC }, 	 //	 824	 160
{ AC, QN, WN, ST, PF, AC, SK, TN, JA, JA, SK, JA, TN, TN, TN }, 	 //	 825	 160
{ AC, QN, WN, JA, JA, AC, SK, TN, TN, TN, SK, JA, TN, AC, AC }, 	 //	 826	 160
{ AC, QN, TN, JA, TN, AC, SK, TN, SH, TN, SK, JA, TN, TN, TN }, 	 //	 827	 160
{ AC, QN, TN, TN, PF, AC, SK, TN, TN, JA, SK, JA, TN, WN, TN }, 	 //	 828	 160
{ AC, QN, TN, TN, JA, AC, SK, TN, TN, TN, SK, JA, TN, WN, AC }, 	 //	 829	 160
{ AC, QN, TN, TN, TN, AC, SK, TN, AC, TN, SK, JA, TN, AC, TN }, 	 //	 830	 160
{ AC, QN, TN, SH, TN, AC, SK, LO, TN, TN, SK, JA, JA, TN, TN }, 	 //	 831	 160
{ AC, QN, TN, SH, TN, AC, SK, AC, TN, TN, SK, JA, AC, TN, TN }, 	 //	 832	 160
{ AC, QN, TN, TN, TN, AC, SK, AC, TN, TN, SK, JA, AC, TN, ST }, 	 //	 833	 160
{ AC, QN, TN, TN, WN, AC, SK, AC, TN, TN, SK, JA, AC, WN, TN }, 	 //	 834	 160
{ AC, SK, SK, JA, TN, AC, JA, JA, TN, AC, SK, JA, TN, AC, AC }, 	 //	 835	 160
{ AC, KN, KN, JA, TN, AC, KN, WN, TN, AC, SK, SK, TN, AC, AC }, 	 //	 836	 160
{ AC, KN, TN, SH, TN, AC, KN, TN, TN, AC, SK, SK, TN, TN, AC }, 	 //	 837	 160
{ AC, KN, TN, TN, PF, AC, KN, TN, TN, JA, SK, SK, TN, WN, TN }, 	 //	 838	 160
{ AC, KN, TN, TN, TN, AC, KN, TN, WN, TN, SK, SK, TN, AC, TN }, 	 //	 839	 160
{ AC, KN, TN, TN, PF, AC, KN, TN, TN, JA, SK, SK, LO, WN, TN }, 	 //	 840	 160
{ AC, KN, TN, TN, TN, AC, KN, TN, AC, TN, SK, SK, LO, AC, ST }, 	 //	 841	 160
{ AC, KN, TN, TN, TN, AC, KN, LO, TN, AC, SK, SK, JA, TN, AC }, 	 //	 842	 160
{ AC, KN, TN, JA, JA, AC, KN, LO, TN, WN, SK, SK, JA, AC, TN }, 	 //	 843	 160
{ AC, KN, TN, JA, TN, AC, KN, LO, TN, TN, SK, SK, JA, AC, TN }, 	 //	 844	 160
{ AC, KN, TN, TN, TN, AC, KN, LO, AC, TN, SK, SK, JA, AC, ST }, 	 //	 845	 160
{ AC, KN, TN, SH, TN, AC, KN, AC, TN, TN, SK, SK, AC, TN, TN }, 	 //	 846	 160
{ AC, KN, TN, TN, PF, AC, KN, AC, TN, JA, SK, SK, AC, TN, TN }, 	 //	 847	 160
{ AC, KN, TN, TN, TN, AC, KN, AC, TN, AC, SK, SK, AC, WN, AC }, 	 //	 848	 160
{ AC, KN, KN, SH, WN, AC, SK, WN, TN, TN, SK, QN, TN, TN, TN }, 	 //	 849	 160
{ AC, KN, KN, TN, TN, AC, SK, WN, TN, AC, SK, QN, TN, TN, AC }, 	 //	 850	 160
{ AC, KN, WN, SH, TN, AC, SK, TN, TN, AC, SK, QN, TN, TN, AC }, 	 //	 851	 160
{ AC, KN, WN, TN, JA, AC, SK, TN, TN, TN, SK, QN, TN, TN, AC }, 	 //	 852	 160
{ AC, KN, WN, TN, WN, AC, SK, TN, TN, TN, SK, QN, TN, WN, TN }, 	 //	 853	 160
{ AC, KN, WN, ST, JA, AC, SK, TN, JA, WN, SK, QN, TN, TN, TN }, 	 //	 854	 160
{ AC, KN, TN, JA, JA, AC, SK, TN, TN, WN, SK, QN, LO, AC, TN }, 	 //	 855	 160
{ AC, KN, TN, JA, PF, AC, SK, TN, TN, JA, SK, QN, LO, AC, TN }, 	 //	 856	 160
{ AC, KN, TN, SH, PF, AC, SK, LO, TN, JA, SK, QN, JA, TN, TN }, 	 //	 857	 160
{ AC, KN, TN, TN, TN, AC, SK, LO, AC, TN, SK, QN, JA, AC, ST }, 	 //	 858	 160
{ AC, KN, JA, TN, WN, AC, SK, TN, TN, TN, SK, QN, AC, TN, TN }, 	 //	 859	 160
{ AC, KN, TN, SH, JA, AC, SK, AC, TN, WN, SK, QN, AC, TN, TN }, 	 //	 860	 160
{ AC, KN, TN, SH, TN, AC, SK, AC, TN, TN, SK, QN, AC, TN, TN }, 	 //	 861	 160
{ AC, KN, TN, TN, TN, AC, SK, AC, TN, ST, SK, QN, AC, WN, AC }, 	 //	 862	 160
{ AC, SK, SK, SH, PF, AC, QN, JA, TN, JA, SK, KN, TN, TN, TN }, 	 //	 863	 160
{ AC, SK, SK, JA, TN, AC, QN, JA, TN, ST, SK, KN, TN, AC, AC }, 	 //	 864	 160
{ AC, QN, WN, JA, PF, SK, SK, TN, SH, JA, KN, JA, TN, TN, TN }, 	 //	 865	 160
{ AC, QN, WN, ST, TN, SK, SK, TN, JA, TN, KN, JA, TN, TN, TN }, 	 //	 866	 160
{ AC, QN, WN, ST, PF, SK, SK, TN, JA, JA, KN, JA, TN, TN, TN }, 	 //	 867	 160
{ AC, QN, TN, ST, WN, SK, SK, TN, JA, TN, KN, JA, TN, TN, TN }, 	 //	 868	 160
{ AC, QN, TN, JA, JA, SK, SK, TN, TN, WN, KN, JA, TN, AC, TN }, 	 //	 869	 160
{ AC, QN, TN, TN, TN, SK, SK, TN, AC, TN, KN, JA, TN, AC, TN }, 	 //	 870	 160
{ AC, QN, TN, TN, TN, SK, SK, TN, TN, ST, KN, JA, LO, TN, AC }, 	 //	 871	 160
{ AC, QN, TN, TN, TN, SK, SK, TN, AC, AC, KN, JA, LO, AC, AC }, 	 //	 872	 160
{ AC, QN, TN, TN, TN, SK, SK, LO, TN, TN, KN, JA, JA, WN, ST }, 	 //	 873	 160
{ AC, QN, TN, SH, JA, SK, SK, AC, TN, WN, KN, JA, AC, TN, TN }, 	 //	 874	 160
{ AC, QN, TN, JA, PF, SK, SK, AC, TN, JA, KN, JA, AC, AC, TN }, 	 //	 875	 160
{ AC, SK, SK, JA, WN, SK, JA, JA, SH, TN, KN, JA, TN, TN, TN }, 	 //	 876	 160
{ AC, SK, SK, TN, TN, SK, JA, JA, TN, AC, KN, JA, TN, TN, AC }, 	 //	 877	 160
{ AC, KN, KN, JA, JA, SK, SK, WN, SH, WN, KN, QN, TN, TN, TN }, 	 //	 878	 160
{ AC, KN, KN, SH, TN, SK, SK, WN, TN, ST, KN, QN, TN, TN, AC }, 	 //	 879	 160
{ AC, KN, KN, ST, WN, SK, SK, WN, JA, TN, KN, QN, TN, TN, TN }, 	 //	 880	 160
{ AC, KN, WN, JA, TN, SK, SK, TN, SH, TN, KN, QN, TN, TN, TN }, 	 //	 881	 160
{ AC, KN, WN, SH, TN, SK, SK, TN, TN, ST, KN, QN, TN, TN, AC }, 	 //	 882	 160
{ AC, KN, WN, SH, TN, SK, SK, TN, TN, AC, KN, QN, TN, TN, AC }, 	 //	 883	 160
{ AC, KN, WN, JA, JA, SK, SK, TN, TN, TN, KN, QN, TN, AC, AC }, 	 //	 884	 160
{ AC, KN, TN, JA, WN, SK, SK, TN, SH, TN, KN, QN, TN, TN, TN }, 	 //	 885	 160
{ AC, KN, TN, TN, TN, SK, SK, TN, WN, TN, KN, QN, TN, AC, TN }, 	 //	 886	 160
{ AC, KN, TN, JA, TN, SK, SK, TN, TN, ST, KN, QN, TN, AC, AC }, 	 //	 887	 160
{ AC, KN, TN, SH, JA, SK, SK, TN, TN, WN, KN, QN, LO, TN, TN }, 	 //	 888	 160
{ AC, KN, TN, SH, PF, SK, SK, TN, TN, JA, KN, QN, LO, TN, TN }, 	 //	 889	 160
{ AC, KN, TN, TN, PF, SK, SK, TN, TN, JA, KN, QN, LO, WN, TN }, 	 //	 890	 160
{ AC, KN, TN, JA, JA, SK, SK, TN, TN, WN, KN, QN, LO, AC, TN }, 	 //	 891	 160
{ AC, KN, TN, SH, TN, SK, SK, LO, TN, TN, KN, QN, JA, TN, TN }, 	 //	 892	 160
{ AC, KN, TN, TN, PF, SK, SK, LO, TN, JA, KN, QN, JA, WN, TN }, 	 //	 893	 160
{ AC, KN, TN, TN, TN, SK, SK, LO, WN, TN, KN, QN, JA, AC, TN }, 	 //	 894	 160
{ AC, KN, JA, SH, JA, SK, SK, TN, TN, TN, KN, QN, AC, TN, AC }, 	 //	 895	 160
{ AC, KN, TN, TN, JA, SK, SK, AC, TN, WN, KN, QN, AC, TN, TN }, 	 //	 896	 160
{ AC, SK, SK, JA, JA, SK, QN, JA, SH, WN, KN, KN, TN, TN, TN }, 	 //	 897	 160
{ AC, SK, SK, TN, TN, SK, QN, JA, TN, TN, KN, KN, TN, TN, ST }, 	 //	 898	 160
{ SK, QN, KN, ST, WN, KN, SK, WN, JA, TN, KN, JA, TN, TN, TN }, 	 //	 899	 160
{ SK, QN, WN, TN, TN, KN, SK, TN, TN, ST, KN, JA, TN, TN, AC }, 	 //	 900	 160
{ SK, QN, WN, ST, WN, KN, SK, TN, JA, TN, KN, JA, TN, TN, TN }, 	 //	 901	 160
{ SK, QN, TN, ST, TN, KN, SK, TN, JA, TN, KN, JA, TN, TN, TN }, 	 //	 902	 160
{ SK, QN, TN, JA, JA, KN, SK, TN, TN, WN, KN, JA, TN, AC, TN }, 	 //	 903	 160
{ SK, QN, TN, SH, PF, KN, SK, TN, TN, JA, KN, JA, LO, TN, TN }, 	 //	 904	 160
{ SK, QN, TN, TN, JA, KN, SK, TN, TN, WN, KN, JA, LO, WN, TN }, 	 //	 905	 160
{ SK, QN, TN, TN, TN, KN, SK, TN, WN, TN, KN, JA, LO, AC, TN }, 	 //	 906	 160
{ SK, QN, TN, JA, PF, KN, SK, TN, TN, JA, KN, JA, LO, AC, TN }, 	 //	 907	 160
{ SK, QN, TN, TN, JA, KN, SK, LO, TN, WN, KN, JA, JA, WN, TN }, 	 //	 908	 160
{ SK, QN, TN, TN, TN, KN, SK, LO, WN, TN, KN, JA, JA, AC, ST }, 	 //	 909	 160
{ SK, QN, TN, JA, TN, KN, SK, LO, TN, TN, KN, JA, JA, AC, TN }, 	 //	 910	 160
{ SK, QN, TN, TN, TN, KN, SK, LO, AC, ST, KN, JA, JA, AC, AC }, 	 //	 911	 160
{ SK, QN, TN, TN, TN, KN, SK, AC, TN, ST, KN, JA, AC, WN, AC }, 	 //	 912	 160
{ SK, SK, TN, SH, JA, KN, JA, TN, TN, TN, KN, JA, LO, TN, AC }, 	 //	 913	 160
{ SK, SK, TN, TN, TN, KN, JA, TN, TN, AC, KN, JA, LO, TN, AC }, 	 //	 914	 160
{ SK, SK, TN, JA, JA, KN, JA, TN, TN, TN, KN, JA, LO, AC, AC }, 	 //	 915	 160
{ SK, SK, JA, SH, WN, KN, JA, TN, TN, TN, KN, JA, AC, TN, TN }, 	 //	 916	 160
{ SK, SK, JA, JA, TN, KN, JA, TN, TN, TN, KN, JA, AC, AC, ST }, 	 //	 917	 160
{ SK, SK, TN, TN, JA, KN, JA, AC, TN, WN, KN, JA, AC, TN, TN }, 	 //	 918	 160
{ SK, SK, TN, TN, WN, KN, JA, AC, TN, TN, KN, JA, AC, TN, TN }, 	 //	 919	 160
{ SK, SK, TN, TN, WN, KN, JA, AC, TN, TN, KN, JA, AC, WN, TN }, 	 //	 920	 160
{ SK, KN, KN, TN, TN, KN, SK, WN, TN, AC, KN, QN, TN, WN, AC }, 	 //	 921	 160
{ SK, KN, KN, ST, TN, KN, SK, WN, JA, TN, KN, QN, TN, TN, TN }, 	 //	 922	 160
{ SK, KN, TN, TN, JA, KN, SK, TN, TN, TN, KN, QN, TN, WN, AC }, 	 //	 923	 160
{ SK, KN, TN, TN, TN, KN, SK, TN, AC, AC, KN, QN, TN, AC, AC }, 	 //	 924	 160
{ SK, KN, TN, SH, PF, KN, SK, TN, TN, JA, KN, QN, LO, TN, TN }, 	 //	 925	 160
{ SK, KN, TN, TN, TN, KN, SK, TN, AC, TN, KN, QN, LO, AC, ST }, 	 //	 926	 160
{ SK, KN, TN, SH, WN, KN, SK, LO, TN, TN, KN, QN, JA, TN, TN }, 	 //	 927	 160
{ SK, KN, JA, TN, TN, KN, SK, TN, TN, TN, KN, QN, AC, WN, ST }, 	 //	 928	 160
{ SK, KN, JA, JA, WN, KN, SK, TN, TN, TN, KN, QN, AC, AC, TN }, 	 //	 929	 160
{ SK, KN, JA, JA, TN, KN, SK, TN, TN, TN, KN, QN, AC, AC, TN }, 	 //	 930	 160
{ SK, KN, TN, SH, PF, KN, SK, AC, TN, JA, KN, QN, AC, TN, TN }, 	 //	 931	 160
{ SK, KN, TN, TN, PF, KN, SK, AC, TN, JA, KN, QN, AC, WN, TN }, 	 //	 932	 160
{ SK, SK, KN, JA, JA, KN, QN, WN, SH, WN, KN, KN, TN, TN, TN }, 	 //	 933	 160
{ SK, SK, KN, SH, JA, KN, QN, WN, TN, WN, KN, KN, TN, TN, TN }, 	 //	 934	 160
{ SK, SK, KN, TN, TN, KN, QN, WN, TN, ST, KN, KN, TN, TN, AC }, 	 //	 935	 160
{ SK, SK, KN, TN, TN, KN, QN, WN, TN, AC, KN, KN, TN, WN, AC }, 	 //	 936	 160
{ SK, SK, WN, TN, TN, KN, QN, TN, TN, ST, KN, KN, TN, WN, AC }, 	 //	 937	 160
{ SK, SK, WN, ST, PF, KN, QN, TN, JA, JA, KN, KN, TN, TN, TN }, 	 //	 938	 160
{ SK, SK, TN, JA, PF, KN, QN, TN, SH, JA, KN, KN, TN, TN, TN }, 	 //	 939	 160
{ SK, SK, TN, TN, JA, KN, QN, TN, TN, TN, KN, KN, TN, TN, AC }, 	 //	 940	 160
{ SK, SK, TN, JA, TN, KN, QN, TN, TN, ST, KN, KN, TN, AC, AC }, 	 //	 941	 160
{ SK, SK, TN, TN, JA, KN, QN, TN, TN, TN, KN, KN, LO, TN, AC }, 	 //	 942	 160
{ SK, SK, TN, SH, TN, KN, QN, LO, TN, TN, KN, KN, JA, TN, TN }, 	 //	 943	 160
{ SK, SK, TN, TN, JA, KN, QN, LO, TN, WN, KN, KN, JA, WN, TN }, 	 //	 944	 160
{ SK, SK, TN, TN, TN, KN, QN, LO, TN, ST, KN, KN, JA, WN, AC }, 	 //	 945	 160
{ SK, SK, TN, TN, PF, KN, QN, LO, TN, JA, KN, KN, JA, WN, TN }, 	 //	 946	 160
{ SK, SK, TN, TN, TN, KN, QN, LO, TN, AC, KN, KN, JA, WN, AC }, 	 //	 947	 160
{ SK, SK, TN, JA, WN, KN, QN, LO, TN, TN, KN, KN, JA, AC, TN }, 	 //	 948	 160
{ SK, SK, TN, JA, TN, KN, QN, LO, TN, TN, KN, KN, JA, AC, TN }, 	 //	 949	 160
{ SK, SK, JA, SH, WN, KN, QN, TN, TN, TN, KN, KN, AC, TN, TN }, 	 //	 950	 160
{ SK, SK, JA, SH, JA, KN, QN, TN, TN, TN, KN, KN, AC, TN, AC }, 	 //	 951	 160
{ SK, SK, JA, TN, TN, KN, QN, TN, TN, TN, KN, KN, AC, WN, ST }, 	 //	 952	 160
{ KN, SK, SK, TN, WN, KN, JA, JA, TN, TN, KN, JA, TN, TN, TN }, 	 //	 953	 160
{ KN, SK, SK, TN, TN, KN, JA, JA, TN, ST, KN, JA, TN, WN, AC }, 	 //	 954	 160
{ KN, KN, SK, JA, JA, KN, SK, JA, SH, WN, KN, QN, TN, TN, TN }, 	 //	 955	 160
{ KN, KN, SK, SH, TN, KN, SK, JA, TN, ST, KN, QN, TN, TN, AC }, 	 //	 956	 160
{ KN, KN, SK, TN, PF, KN, SK, JA, TN, JA, KN, QN, TN, TN, TN }, 	 //	 957	 160
{ KN, KN, SK, TN, TN, KN, SK, JA, TN, TN, KN, QN, TN, WN, ST }, 	 //	 958	 160
{ KN, SK, SK, JA, TN, KN, QN, JA, TN, ST, KN, KN, TN, AC, AC }, 	 //	 959	 160
{ KN, QN, SK, TN, TN, KN, SK, JA, TN, TN, WN, JA, TN, WN, ST }, 	 //	 960	 160
{ KN, QN, SK, ST, TN, KN, SK, JA, JA, TN, WN, JA, TN, TN, TN }, 	 //	 961	 160
{ KN, QN, SK, JA, TN, KN, SK, JA, TN, TN, WN, JA, TN, AC, TN }, 	 //	 962	 160
{ KN, SK, SK, SH, JA, KN, JA, JA, TN, WN, WN, JA, TN, TN, TN }, 	 //	 963	 160
{ KN, SK, SK, SH, TN, KN, JA, JA, TN, ST, WN, JA, TN, TN, AC }, 	 //	 964	 160
{ KN, SK, SK, SH, PF, KN, JA, JA, TN, JA, WN, JA, TN, TN, TN }, 	 //	 965	 160
{ KN, SK, SK, JA, TN, KN, JA, JA, TN, TN, WN, JA, TN, AC, ST }, 	 //	 966	 160
{ KN, KN, SK, JA, WN, KN, SK, JA, SH, TN, WN, QN, TN, TN, TN }, 	 //	 967	 160
{ KN, KN, SK, SH, JA, KN, SK, JA, TN, WN, WN, QN, TN, TN, TN }, 	 //	 968	 160
{ KN, SK, SK, JA, TN, KN, QN, JA, SH, TN, WN, KN, TN, TN, TN }, 	 //	 969	 160
{ KN, SK, SK, TN, JA, KN, QN, JA, TN, WN, WN, KN, TN, TN, TN }, 	 //	 970	 160
{ KN, SK, SK, JA, JA, WN, JA, JA, SH, WN, QN, JA, TN, TN, TN }, 	 //	 971	 160
{ KN, SK, SK, TN, JA, WN, JA, JA, TN, WN, QN, JA, TN, TN, TN }, 	 //	 972	 160
{ KN, SK, SK, TN, WN, WN, JA, JA, TN, TN, QN, JA, TN, TN, TN }, 	 //	 973	 160
{ KN, KN, SK, JA, TN, WN, SK, JA, TN, AC, QN, QN, TN, AC, AC }, 	 //	 974	 160
{ KN, SK, SK, JA, TN, WN, QN, JA, SH, TN, QN, KN, TN, TN, TN }, 	 //	 975	 160
{ KN, SK, SK, SH, PF, WN, QN, JA, TN, JA, QN, KN, TN, TN, TN }, 	 //	 976	 160
{ KN, SK, SK, TN, TN, WN, QN, JA, TN, TN, QN, KN, TN, WN, TN }, 	 //	 977	 160
{ KN, SK, SK, JA, TN, WN, QN, JA, TN, TN, QN, KN, TN, AC, TN }, 	 //	 978	 160
{ WN, QN, SK, ST, WN, QN, SK, JA, JA, TN, KN, JA, TN, TN, TN }, 	 //	 979	 160
{ WN, KN, SK, JA, TN, QN, SK, JA, TN, ST, KN, QN, TN, AC, AC }, 	 //	 980	 160
{ WN, SK, SK, TN, PF, QN, QN, JA, TN, JA, KN, KN, TN, TN, TN }, 	 //	 981	 160
{ WN, SK, SK, TN, TN, QN, QN, JA, TN, TN, KN, KN, TN, WN, ST }, 	 //	 982	 160
{ QN, QN, SK, JA, TN, KN, SK, JA, TN, TN, AC, JA, TN, AC, ST }, 	 //	 983	 160
{ QN, KN, SK, TN, TN, KN, SK, JA, TN, TN, AC, QN, TN, WN, ST }, 	 //	 984	 160
{ KN, QN, SK, SH, WN, AC, SK, JA, TN, TN, LO, JA, TN, TN, TN }, 	 //	 985	 160
{ KN, SK, SK, SH, WN, AC, JA, JA, TN, TN, LO, JA, TN, TN, TN }, 	 //	 986	 160
{ KN, KN, SK, JA, WN, AC, SK, JA, SH, TN, LO, QN, TN, TN, TN }, 	 //	 987	 160
{ KN, KN, SK, JA, TN, AC, SK, JA, TN, TN, LO, QN, TN, AC, TN }, 	 //	 988	 160
{ KN, SK, SK, JA, TN, AC, QN, JA, SH, TN, LO, KN, TN, TN, TN }, 	 //	 989	 160
{ KN, SK, SK, TN, WN, AC, QN, JA, TN, TN, LO, KN, TN, TN, TN }, 	 //	 990	 160
{ KN, SK, SK, TN, TN, AC, QN, JA, TN, TN, LO, KN, TN, TN, ST }, 	 //	 991	 160
{ KN, SK, SK, TN, TN, AC, QN, JA, TN, TN, LO, KN, TN, WN, TN }, 	 //	 992	 160
